
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_DESIG_SUBST" AFTER
  DELETE OR
  INSERT OR
  UPDATE ON "ARTERH"."RHPLCS_DESVIO_FUNC" FOR EACH ROW 
   DECLARE 
  vID PLS_INTEGER; 
  v_DML SMARH_INT_DESIGNACAO.TIPO_DML%TYPE;
  v_CONT number;
  v_MOTIVO_DESVIO NUMBER;
  cont_1 NUMBER;
  cont_2 NUMBER;
  v_quantidade_movim NUMBER;

  BEGIN

  SELECT ID_SEQ_DESIG.NEXTVAL INTO vID FROM dual;
  v_MOTIVO_DESVIO := 0;

    --------------------------------------------------------------------------INSERT SMARH_INT_DESIGNACAO --------------------------------------------------------------
    IF INSERTING THEN
      v_DML := 'I';   
      BEGIN

      SELECT COD_MOT_SOLIC into v_MOTIVO_DESVIO FROM RHPLCS_SOL_DES_FUN WHERE CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND ID_SOL_DES_FUNC = :NEW.ID_SOL_DES_FUNC ;

      EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 1°S TRG' || :NEW.CODIGO_EMPRESA || '-' || :NEW.TIPO_CONTRATO|| '-' ||  :NEW.CODIGO_CONTRATO || '-' || :NEW.OCORRENCIA || '-' || :NEW.ID_SOL_DES_FUNC  || '-' || v_MOTIVO_DESVIO);

      END;


      INSERT
      INTO SMARH_INT_DESIGNACAO
        (
          TIPO_DML,
          CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO,
          OCORRENCIA,
          DT_PROCESSAMENTO,
          ID,
          MOTIVO_DESVIO,
          DATA_INICIO_DESVIO,
          TIPO_CONTRATO_RESP,
          CODIG_CONTR_RESP,
          COD_UNIDADE1,
          COD_UNIDADE2,
          COD_UNIDADE3,
          COD_UNIDADE4,
          COD_UNIDADE5,
          COD_UNIDADE6,
          COD_CARGO_COMIS,
          COD_CARGO_EFET,
          DATA_REGULARIZACAO,
          LOGIN_USUARIO,
          DT_ULT_ALTER_USUA,
          DATA_FIM_DESVIO,
          TIPO_AGRUP,
          NIVEL_CARGO_COMISS,
          NIVEL_CARGO_EFETIV,
          CODIGO_VERBA,
          CODIGO_FUNCAO,
          ID_LEI,
          OPCAO_SERVIDOR,
          COD_ESCALA,
          TIPO_CONTRATO_TITULAR,
          CONTRATO_TITULAR,
          E_GESTOR_TITULAR,
          COD_PESSOA,
          NOME_TABELA,
          DOCUMENTO_PUBLIC,
          VAGA_RESP,
          E_GESTOR,
          DT_PUBLIC_DOM

        )
        VALUES
        (
          v_DML,
          :NEW.CODIGO_EMPRESA,
          :NEW.TIPO_CONTRATO,
          :NEW.CODIGO_CONTRATO ,
          :NEW.OCORRENCIA ,
          sysdate,
          vID,
          lpad(v_MOTIVO_DESVIO,4,0),
          :NEW.DATA_INICIO_DESVIO ,
          :NEW.TIPO_CONTRATO_RESP ,
          :NEW.CODIG_CONTR_RESP,
          :NEW.COD_UNIDADE1 ,
          :NEW.COD_UNIDADE2 ,
          :NEW.COD_UNIDADE3 ,
          :NEW.COD_UNIDADE4 ,
          :NEW.COD_UNIDADE5 ,
          :NEW.COD_UNIDADE6,
          :NEW.COD_CARGO_COMIS ,
          :NEW.COD_CARGO_EFET ,
          :NEW.DATA_REGULARIZACAO,
          :NEW.LOGIN_USUARIO,
          :NEW.DT_ULT_ALTER_USUA ,
          :NEW.DATA_FIM_DESVIO ,
          :NEW.TIPO_AGRUP ,
          :NEW.NIVEL_CARGO_COMISS ,
          :NEW.NIVEL_CARGO_EFETIV,
          :NEW.CODIGO_VERBA,
          :NEW.CODIGO_FUNCAO,
          :NEW.ID_LEI,
          :NEW.C_LIVRE_SELEC1,
          :NEW.CODIGO_ESCALA,
          :NEW.tipo_contrato_resp,
          :NEW.codig_contr_resp,
          (select CASE WHEN COUNT(1) > 0 THEN 'S' ELSE 'N' END AS E_GESTOR from RHORGA_CUSTO_GEREN WHERE CONTRATO_RESP = :NEW.codig_contr_resp AND TIPO_CONT_RESP = :NEW.tipo_contrato_resp and CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA ) ,
          (SELECT B.CODIGO_PESSOA FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :NEW.TIPO_CONTRATO AND B.CODIGO = :NEW.CODIGO_CONTRATO AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          (SELECT case when :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when  :NEW.COD_CARGO_COMIS IS not null  and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null  and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO' END FROM DUAL),
          :NEW.DOCUMENTO_PUBLIC,
          (SELECT B.codigo_vaga FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :NEW.tipo_contrato_resp AND B.CODIGO = :NEW.codig_contr_resp AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          :new.c_livre_opcao01,
          :NEW.c_livre_data10
        );

    IF ( :NEW.DATA_INICIO_DESVIO <= trunc(SYSDATE) and :NEW.DATA_CANCELAMENTO IS NULL )THEN


    --INCLUIDA EM 10-03-2021 PARA EVITAR ERRO QUANDO A HISTÓRICA DE MOVIMENTAÇÃO POSSUI MAIS DE 1 REGISTRO NA MESMA DATA
    -- verifica  a quantidade de movimentações que a pessooa tem
    SELECT count(1)  as quantidade into v_quantidade_movim FROM RHPESS_CONTRATO CT
          LEFT JOIN (SELECT * FROM RHCGED_TRANSFERENC M
          WHERE M.DT_ALT_UNID_CUSTO =
            (SELECT MAX(AUX.DT_ALT_UNID_CUSTO)
            FROM RHCGED_TRANSFERENC AUX
            WHERE AUX.CODIGO_EMPRESA   = M.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO      = M.TIPO_CONTRATO
            AND AUX.CODIGO             = M.CODIGO
            AND AUX.DT_ALT_UNID_CUSTO <=  :NEW.DATA_INICIO_DESVIO
            )) M
          ON M.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND M.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND M.CODIGO        = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <=  :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO;



    IF ( v_quantidade_movim = 1 )then 
      INSERT
      INTO SMARH_INT_DESIGNACAO_HIST
        (        
        SELECT 
          v_DML,
          case       when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO'
          else ''
          end as nome_tabela,
            CT.CODIGO_EMPRESA,
            CT.TIPO_CONTRATO,
            CT.CODIGO,
            vID,
            sysdate DT_saiu_arte,
            CT.ANO_MES_REFERENCIA,
            F.DATA_INICIO_FUNCAO,
            F.CODIGO_FUNCAO ,
            F.DT_FIM_TEMP,
            F.CODIGO_HIST_FUNCAO ,
            F.DOCUMENTO_PUBLIC ,
            F.TEXTO_ASSOCIADO ,
            F.ID_LEI,
            F.COD_FUNCAO_AVALIACAO,
            F.ALTERA_SAL_PAGTO_CONTR ,
            C.DT_ALTER_CARGO,
            C.MOTIVO_ALTERACAO ,
            C.COD_CARGO_EFET_AT,
            C.NIV_CARGO_EFET_AT ,
            C.COD_CARGO_COMIS_AT ,
            C.NIV_CARGO_COMIS_AT ,
            C.COD_CARGO_AMPAR_AT ,
            C.NIV_CARGO_AMPAR_AT ,
            C.DT_FIM_TEMP ,
            C.DOCUMENTO_PUBLIC ,
            C.OCORRENCIA ,
            C.SALARIO_PAGTO ,
            C.ID_LEI ,
            C.COD_CARGO_AVALIACAO ,
            M.DT_ALT_UNID_CUSTO,
            M.COD_MOVIMENTACAO,
            M.COD_LOTACAO_ATUAL1,
            M.COD_LOTACAO_ATUAL2,
            M.COD_LOTACAO_ATUAL3,
            M.COD_LOTACAO_ATUAL4,
            M.COD_LOTACAO_ATUAL5,
            M.COD_LOTACAO_ATUAL6,
            M.COD_UNIDADE_ATUAL1,
            M.COD_UNIDADE_ATUAL2,
            M.COD_UNIDADE_ATUAL3,
            M.COD_UNIDADE_ATUAL4,
            M.COD_UNIDADE_ATUAL5,
            M.COD_UNIDADE_ATUAL6,
            M.COD_CCONTAB_ATUAL1,
            M.COD_CCONTAB_ATUAL2,
            M.COD_CCONTAB_ATUAL3,
            M.COD_CCONTAB_ATUAL4,
            M.COD_CCONTAB_ATUAL5,
            M.COD_CCONTAB_ATUAL6,
            M.COD_CGERENC_ATUAL1,
            M.COD_CGERENC_ATUAL2,
            M.COD_CGERENC_ATUAL3,
            M.COD_CGERENC_ATUAL4,
            M.COD_CGERENC_ATUAL5,
            M.COD_CGERENC_ATUAL6,
            M.TEXTO_ASSOCIADO,
            M.MOTIVO_ALTERACAO,
            M.DT_FIM_TEMP,
            M.DOCUMENTO_PUBLIC,
            E.DT_INICIO_TROCA ,
            E.DT_FIM_TROCA ,
            E.COD_ESCALA ,
            E.COD_HORARIO,
            E.COD_MOTIVO ,
            E.COD_SITUACAO ,
            E.ORIGEM_PROGRAMACAO ,
            E.ALTER_DEFINITIVA ,
            E.DOCUMENTO_PUBLIC,
            E.ANALISA_ALTERN,
            E.TEXTO_ASSOCIADO,
            E.COD_MOT_CANCEL_SOL ,
            E.TIPO_HORARIO,
            :NEW.OCORRENCIA,
            'S'
          FROM RHPESS_CONTRATO CT
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_FUNCAO F
            WHERE F.DATA_INICIO_FUNCAO =
              (SELECT MAX(AUX.DATA_INICIO_FUNCAO)
              FROM RHPLCS_ALT_FUNCAO AUX
              WHERE AUX.CODIGO_EMPRESA    = F.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO       = F.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO     = F.CODIGO_CONTRATO
              AND AUX.DATA_INICIO_FUNCAO <= :NEW.DATA_INICIO_DESVIO
              )
            )F
          ON F.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND F.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND F.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_CARGO C
            WHERE C.DT_ALTER_CARGO =
               (SELECT MAX(AUX.DT_ALTER_CARGO)
              FROM RHPLCS_ALT_CARGO AUX
              WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              AND AUX.DT_ALTER_CARGO  <= :NEW.DATA_INICIO_DESVIO
              )
            ) C
          ON C.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND C.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND C.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHCGED_TRANSFERENC M
          WHERE M.DT_ALT_UNID_CUSTO =
            (SELECT MAX(AUX.DT_ALT_UNID_CUSTO)
            FROM RHCGED_TRANSFERENC AUX
            WHERE AUX.CODIGO_EMPRESA   = M.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO      = M.TIPO_CONTRATO
            AND AUX.CODIGO             = M.CODIGO
            AND AUX.DT_ALT_UNID_CUSTO <= :NEW.DATA_INICIO_DESVIO
            )) M
          ON M.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND M.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND M.CODIGO        = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPONT_ALT_ESCALA E
          WHERE  E.DT_INICIO_TROCA =
            (SELECT MAX(AUX.DT_INICIO_TROCA)
            FROM RHPONT_ALT_ESCALA AUX
            WHERE AUX.CODIGO_EMPRESA    = E.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = E.TIPO_CONTRATO
            AND AUX.CODIGO_CONTRATO     = E.CODIGO_CONTRATO
            AND AUX.DT_INICIO_TROCA <= :NEW.DATA_INICIO_DESVIO
            )) E
          ON E.CODIGO_EMPRESA         = CT.CODIGO_EMPRESA
          AND E.TIPO_CONTRATO         = CT.TIPO_CONTRATO
          AND E.CODIGO_CONTRATO       = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
            AND ( C.OCORRENCIA = (SELECT MAX(AUX2.OCORRENCIA)
              FROM RHPLCS_ALT_CARGO AUX2
              WHERE AUX2.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX2.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX2.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              and aux2.DT_ALTER_CARGO = c.DT_ALTER_CARGO ) 
              or c.ocorrencia is null )
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO);


     ELSE 

     -- BUSCA A MOVIMENTAÇÃO DO CONTRATO

           INSERT
      INTO SMARH_INT_DESIGNACAO_HIST
        (        
        SELECT 
          v_DML,
          case       when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO'
          else ''
          end as nome_tabela,
            CT.CODIGO_EMPRESA,
            CT.TIPO_CONTRATO,
            CT.CODIGO,
            vID,
            sysdate DT_saiu_arte,
            CT.ANO_MES_REFERENCIA,
            F.DATA_INICIO_FUNCAO,
            F.CODIGO_FUNCAO ,
            F.DT_FIM_TEMP,
            F.CODIGO_HIST_FUNCAO ,
            F.DOCUMENTO_PUBLIC ,
            F.TEXTO_ASSOCIADO ,
            F.ID_LEI,
            F.COD_FUNCAO_AVALIACAO,
            F.ALTERA_SAL_PAGTO_CONTR ,
            C.DT_ALTER_CARGO,
            C.MOTIVO_ALTERACAO ,
            C.COD_CARGO_EFET_AT,
            C.NIV_CARGO_EFET_AT ,
            C.COD_CARGO_COMIS_AT ,
            C.NIV_CARGO_COMIS_AT ,
            C.COD_CARGO_AMPAR_AT ,
            C.NIV_CARGO_AMPAR_AT ,
            C.DT_FIM_TEMP ,
            C.DOCUMENTO_PUBLIC ,
            C.OCORRENCIA ,
            C.SALARIO_PAGTO ,
            C.ID_LEI ,
            C.COD_CARGO_AVALIACAO ,
            CT2.DT_ULT_ALT_UNID	, 
            NULL,            
            CT2.COD_LOCAL1,
            CT2.COD_LOCAL2,
            CT2.COD_LOCAL3,
            CT2.COD_LOCAL4,
            CT2.COD_LOCAL5,
            CT2.COD_LOCAL6,
            CT2.COD_UNIDADE1,
            CT2.COD_UNIDADE2,
            CT2.COD_UNIDADE3	,  
            CT2.COD_UNIDADE4	,  
            CT2.COD_UNIDADE5	,  
            CT2.COD_UNIDADE6	,  
            CT2.COD_CUSTO_CONTAB1	,  
            CT2.COD_CUSTO_CONTAB2	,  
            CT2.COD_CUSTO_CONTAB3	,  
            CT2.COD_CUSTO_CONTAB4	,  
            CT2.COD_CUSTO_CONTAB5	,  
            CT2.COD_CUSTO_CONTAB6	,
            CT2.COD_CUSTO_GERENC1	,  
            CT2.COD_CUSTO_GERENC2	,  
            CT2.COD_CUSTO_GERENC3	,  
            CT2.COD_CUSTO_GERENC4	,  
            CT2.COD_CUSTO_GERENC5	,  
            CT2.COD_CUSTO_GERENC6	,  
            NULL,
            NULL,
            NULL,
            NULL,
            E.DT_INICIO_TROCA ,
            E.DT_FIM_TROCA ,
            E.COD_ESCALA ,
            E.COD_HORARIO,
            E.COD_MOTIVO ,
            E.COD_SITUACAO ,
            E.ORIGEM_PROGRAMACAO ,
            E.ALTER_DEFINITIVA ,
            E.DOCUMENTO_PUBLIC,
            E.ANALISA_ALTERN,
            E.TEXTO_ASSOCIADO,
            E.COD_MOT_CANCEL_SOL ,
            E.TIPO_HORARIO,
            :NEW.OCORRENCIA,
            'S'
          FROM RHPESS_CONTRATO CT
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_FUNCAO F
            WHERE F.DATA_INICIO_FUNCAO =
              (SELECT MAX(AUX.DATA_INICIO_FUNCAO)
              FROM RHPLCS_ALT_FUNCAO AUX
              WHERE AUX.CODIGO_EMPRESA    = F.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO       = F.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO     = F.CODIGO_CONTRATO
              AND AUX.DATA_INICIO_FUNCAO <= :NEW.DATA_INICIO_DESVIO
              )
            )F
          ON F.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND F.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND F.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_CARGO C
            WHERE C.DT_ALTER_CARGO =
               (SELECT MAX(AUX.DT_ALTER_CARGO)
              FROM RHPLCS_ALT_CARGO AUX
              WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              AND AUX.DT_ALTER_CARGO  <= :NEW.DATA_INICIO_DESVIO
              )
            ) C
          ON C.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND C.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND C.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPESS_CONTRATO CT2
          WHERE  CT2.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT2.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT2.TIPO_CONTRATO
            AND AUX.CODIGO              = CT2.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) ) CT2
          ON CT2.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND CT2.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND CT2.CODIGO        = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPONT_ALT_ESCALA E
          WHERE  E.DT_INICIO_TROCA =
            (SELECT MAX(AUX.DT_INICIO_TROCA)
            FROM RHPONT_ALT_ESCALA AUX
            WHERE AUX.CODIGO_EMPRESA    = E.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = E.TIPO_CONTRATO
            AND AUX.CODIGO_CONTRATO     = E.CODIGO_CONTRATO
            AND AUX.DT_INICIO_TROCA <= :NEW.DATA_INICIO_DESVIO
            )) E
          ON E.CODIGO_EMPRESA         = CT.CODIGO_EMPRESA
          AND E.TIPO_CONTRATO         = CT.TIPO_CONTRATO
          AND E.CODIGO_CONTRATO       = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
            AND ( C.OCORRENCIA = (SELECT MAX(AUX2.OCORRENCIA)
              FROM RHPLCS_ALT_CARGO AUX2
              WHERE AUX2.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX2.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX2.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              and aux2.DT_ALTER_CARGO = c.DT_ALTER_CARGO ) 
              or c.ocorrencia is null )
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO);

     END IF;



      FOR C1 IN
      (select 
      ANO_MES_REFERENCIA , 	CODIGO_EMPRESA  , 	TIPO_CONTRATO  , 	CODIGO  ,   CODIGO_PESSOA	,  COD_LOCAL1	,  COD_LOCAL2	,  COD_LOCAL3	,  COD_LOCAL4	,  COD_LOCAL5	,  COD_LOCAL6	,  DT_ULT_ALT_LOC	,  COD_UNIDADE1	,
      COD_UNIDADE2	,  COD_UNIDADE3	,  COD_UNIDADE4	,  COD_UNIDADE5	,  COD_UNIDADE6	,  DT_ULT_ALT_UNID	,  COD_CUSTO_CONTAB1	,  COD_CUSTO_CONTAB2	,  COD_CUSTO_CONTAB3	,  COD_CUSTO_CONTAB4	,  COD_CUSTO_CONTAB5	,  COD_CUSTO_CONTAB6	,
      DT_ULT_ALT_CONT	,  COD_CUSTO_GERENC1	,  COD_CUSTO_GERENC2	,  COD_CUSTO_GERENC3	,  COD_CUSTO_GERENC4	,  COD_CUSTO_GERENC5	,  COD_CUSTO_GERENC6	,  DT_ULT_ALT_GER	,  SALARIO_PAGTO	,  COD_CARGO_PAGTO	,
      NIVEL_CARGO_PAGTO	,  COD_CARGO_EFETIVO	,  NIVEL_CARGO_EFETIV	,  DT_ULT_CARGO_EFET	,  COD_CARGO_COMISS	,  NIVEL_CARGO_COMISS	,  DT_ULT_CARGO_COM	,  COD_CARGO_AMPAR	,  NIVEL_CARGO_AMPAR	,  DT_ULT_CARGO_AMPAR	,  
      CODIGO_FUNCAO	,  DT_ULT_FUNCAO	,  CODIGO_ESCALA	,  DT_ULT_ESCALA	,  LOGIN_USUARIO	,  DT_ULT_ALTER_USUA	
      from rhpess_contrato CT WHERE 

            ( ( CT.ANO_MES_REFERENCIA BETWEEN   trunc(:NEW.DATA_INICIO_DESVIO,'MM')    AND  NVL(:NEW.DATA_FIM_DESVIO,SYSDATE) 
            AND CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO )

            ) or (CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <=  NVL(:NEW.DATA_FIM_DESVIO,SYSDATE)
            )
            ) 
            OR ( CT.ANO_MES_REFERENCIA >= trunc(:NEW.DATA_INICIO_DESVIO,'MM')AND  :NEW.DATA_FIM_DESVIO IS NULL)
            )        
              AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
              AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
              AND CT.CODIGO         = :NEW.CODIGO_CONTRATO

      )
      LOOP
      INSERT INTO SMARH_INT_DESIGNACAO_CONTR ( TIPO_DML, ID,DT_SAIU_ARTE, ANO_MES_REFERENCIA,CODIGO_EMPRESA,TIPO_CONTRATO,CODIGO,CODIGO_PESSOA,COD_LOCAL1,COD_LOCAL2,COD_LOCAL3,COD_LOCAL4,COD_LOCAL5,
      COD_LOCAL6,DT_ULT_ALT_LOC,COD_UNIDADE1,COD_UNIDADE2,COD_UNIDADE3,COD_UNIDADE4,COD_UNIDADE5,COD_UNIDADE6,DT_ULT_ALT_UNID,COD_CUSTO_CONTAB1,COD_CUSTO_CONTAB2,COD_CUSTO_CONTAB3,COD_CUSTO_CONTAB4,COD_CUSTO_CONTAB5,
      COD_CUSTO_CONTAB6,DT_ULT_ALT_CONT,COD_CUSTO_GERENC1,COD_CUSTO_GERENC2,COD_CUSTO_GERENC3,COD_CUSTO_GERENC4,COD_CUSTO_GERENC5,COD_CUSTO_GERENC6,DT_ULT_ALT_GER,SALARIO_PAGTO,COD_CARGO_PAGTO,NIVEL_CARGO_PAGTO,COD_CARGO_EFETIVO,
      NIVEL_CARGO_EFETIV,LT_ULT_CARGO_EFET,COD_CARGO_COMISS,NIVEL_CARGO_COMISS,DT_ULT_CARGO_COM,COD_CARGO_AMPAR,NIVEL_CARGO_AMPAR,DT_ULT_CARGO_AMPAR,CODIGO_FUNCAO,DT_ULT_FUNCAO,CODIGO_ESCALA,DT_ULT_ESCALA,LOGIN_USUARIO,DT_ULT_ALTER_USUA, OCORRENCIA, CONSIDERAR) 
      VALUES ( v_DML,          vID,          sysdate,          trunc(C1.ANO_MES_REFERENCIA) ,          C1.CODIGO_EMPRESA,          C1.TIPO_CONTRATO,          C1.CODIGO ,           C1.CODIGO_PESSOA	,  C1.COD_LOCAL1	,  C1.COD_LOCAL2	, 
      C1.COD_LOCAL3	,  C1.COD_LOCAL4	,  C1.COD_LOCAL5	,  C1.COD_LOCAL6	,  C1.DT_ULT_ALT_LOC	,  C1.COD_UNIDADE1	,  C1.COD_UNIDADE2	,  C1.COD_UNIDADE3	,  C1.COD_UNIDADE4	,  C1.COD_UNIDADE5	,  C1.COD_UNIDADE6	,  
      C1.DT_ULT_ALT_UNID	, C1.COD_CUSTO_CONTAB1	,  C1.COD_CUSTO_CONTAB2	,  C1.COD_CUSTO_CONTAB3	,  C1.COD_CUSTO_CONTAB4	,  C1.COD_CUSTO_CONTAB5	,  C1.COD_CUSTO_CONTAB6	,  C1.DT_ULT_ALT_CONT	,  C1.COD_CUSTO_GERENC1	, 
      C1.COD_CUSTO_GERENC2	,  C1.COD_CUSTO_GERENC3	,  C1.COD_CUSTO_GERENC4	,  C1.COD_CUSTO_GERENC5	,  C1.COD_CUSTO_GERENC6	,  C1.DT_ULT_ALT_GER	,  C1.SALARIO_PAGTO	,  C1.COD_CARGO_PAGTO	,  C1.NIVEL_CARGO_PAGTO	, 
      C1.COD_CARGO_EFETIVO	,  C1.NIVEL_CARGO_EFETIV	,  C1.DT_ULT_CARGO_EFET	,  C1.COD_CARGO_COMISS	,  C1.NIVEL_CARGO_COMISS	,  C1.DT_ULT_CARGO_COM	,  C1.COD_CARGO_AMPAR	,  C1.NIVEL_CARGO_AMPAR	,  C1.DT_ULT_CARGO_AMPAR	,
      C1.CODIGO_FUNCAO	,  C1.DT_ULT_FUNCAO	, C1.CODIGO_ESCALA	,  C1.DT_ULT_ESCALA	,  C1.LOGIN_USUARIO	,  C1.DT_ULT_ALTER_USUA,  :NEW.OCORRENCIA, 'S');
      END LOOP;

     PR_MIGRA_DADOS_DESIG(:NEW.CODIGO_EMPRESA,:NEW.TIPO_CONTRATO,:NEW.CODIGO_CONTRATO,:NEW.DATA_INICIO_DESVIO, :NEW.DATA_FIM_DESVIO, vID, 'INSERIR', :NEW.LOGIN_USUARIO);

     END IF;


      --------------------------------------------------------------------------UPDATE--------------------------------------------------------------
ELSIF UPDATING THEN
     v_DML := 'U';  


-- PARTE DO DELETE 

     BEGIN
      SELECT COD_MOT_SOLIC into v_MOTIVO_DESVIO FROM RHPLCS_SOL_DES_FUN WHERE CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND ID_SOL_DES_FUNC = :OLD.ID_SOL_DES_FUNC ;
            EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 2°S TRG');
      END;

      INSERT
      INTO SMARH_INT_DESIGNACAO
        (
          TIPO_DML,
          CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO,
          OCORRENCIA,
          DT_PROCESSAMENTO,
          ID,
          MOTIVO_DESVIO,
          DATA_INICIO_DESVIO,
          TIPO_CONTRATO_RESP,
          CODIG_CONTR_RESP,
          COD_UNIDADE1,
          COD_UNIDADE2,
          COD_UNIDADE3,
          COD_UNIDADE4,
          COD_UNIDADE5,
          COD_UNIDADE6,
          COD_CARGO_COMIS,
          COD_CARGO_EFET,
          DATA_REGULARIZACAO,
          LOGIN_USUARIO,
          DT_ULT_ALTER_USUA,
          DATA_FIM_DESVIO,
          TIPO_AGRUP,
          NIVEL_CARGO_COMISS,
          NIVEL_CARGO_EFETIV,
          CODIGO_VERBA,
          CODIGO_FUNCAO,
          ID_LEI,
          OPCAO_SERVIDOR,
          COD_ESCALA,
          TIPO_CONTRATO_TITULAR,
          CONTRATO_TITULAR,
          E_GESTOR_TITULAR,
          COD_PESSOA,
          NOME_TABELA,
          DOCUMENTO_PUBLIC,
          VAGA_RESP,
          E_GESTOR,
          DT_PUBLIC_DOM
        )
        VALUES
        (
          v_DML || '/D',
          :OLD.CODIGO_EMPRESA,
          :OLD.TIPO_CONTRATO,
          :OLD.CODIGO_CONTRATO ,
          :OLD.OCORRENCIA ,
          sysdate,
          vID,
          lpad(v_MOTIVO_DESVIO,4,0),
          :OLD.DATA_INICIO_DESVIO ,
          :OLD.TIPO_CONTRATO_RESP ,
          :OLD.CODIG_CONTR_RESP,
          :OLD.COD_UNIDADE1 ,
          :OLD.COD_UNIDADE2 ,
          :OLD.COD_UNIDADE3 ,
          :OLD.COD_UNIDADE4 ,
          :OLD.COD_UNIDADE5 ,
          :OLD.COD_UNIDADE6,
          :OLD.COD_CARGO_COMIS ,
          :OLD.COD_CARGO_EFET ,
          :OLD.DATA_REGULARIZACAO,
          :OLD.LOGIN_USUARIO,
          :OLD.DT_ULT_ALTER_USUA ,
          :OLD.DATA_FIM_DESVIO ,
          :OLD.TIPO_AGRUP ,
          :OLD.NIVEL_CARGO_COMISS ,
          :OLD.NIVEL_CARGO_EFETIV,
          :OLD.CODIGO_VERBA,
          :OLD.CODIGO_FUNCAO,
          :OLD.ID_LEI,
          :OLD.C_LIVRE_SELEC1,
          :OLD.CODIGO_ESCALA,
          :OLD.tipo_contrato_resp,
          :OLD.codig_contr_resp,
          (select CASE WHEN COUNT(1) > 0 THEN 'S' ELSE 'N' END AS E_GESTOR from RHORGA_CUSTO_GEREN WHERE CONTRATO_RESP = :OLD.codig_contr_resp AND TIPO_CONT_RESP = :OLD.tipo_contrato_resp ) ,
          (SELECT B.CODIGO_PESSOA FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :OLD.TIPO_CONTRATO AND B.CODIGO = :OLD.CODIGO_CONTRATO AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          (SELECT case when  :OLD.COD_CARGO_COMIS IS not null and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO' END FROM DUAL),
          :OLD.DOCUMENTO_PUBLIC,
          (SELECT B.codigo_vaga FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :OLD.tipo_contrato_resp AND B.CODIGO = :OLD.codig_contr_resp AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          :OLD.c_livre_opcao01,
          :OLD.c_livre_data10

        );

    BEGIN
      select CASE WHEN count(1) IS NULL THEN 0 ELSE count(1) END into cont_1 from SMARH_INT_DESIGNACAO_CONTR where CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO AND CODIGO  = :OLD.CODIGO_CONTRATO AND OCORRENCIA = :OLD.OCORRENCIA ;
       EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 3°SA TRG');
      END;
    BEGIN
      select CASE WHEN count(1) IS NULL THEN 0 ELSE count(1) END into cont_2 from SMARH_INT_DESIGNACAO_HIST where CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO AND CODIGO = :OLD.CODIGO_CONTRATO AND OCORRENCIA_DESIG = :OLD.OCORRENCIA ;
       EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 4°SB TRG');
      END;

      if( ( cont_1 >0 and cont_1 is not null) and ( cont_2 > 0 and cont_1 is not null) ) THEN

      IF( :OLD.DATA_INICIO_DESVIO <=  trunc(SYSDATE) ) THEN 
      PR_MIGRA_DADOS_DESIG(:OLD.CODIGO_EMPRESA,:OLD.TIPO_CONTRATO,:OLD.CODIGO_CONTRATO,:OLD.DATA_INICIO_DESVIO, :OLD.DATA_FIM_DESVIO, vID, 'U-EXCLUIR', :OLD.LOGIN_USUARIO);

      UPDATE SMARH_INT_DESIGNACAO_CONTR SET CONSIDERAR = 'N' where 
      CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA
      AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO
      AND CODIGO  = :OLD.CODIGO_CONTRATO AND OCORRENCIA = :OLD.OCORRENCIA ;

      UPDATE SMARH_INT_DESIGNACAO_HIST SET CONSIDERAR = 'N' where 
      CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA
      AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO
      AND CODIGO = :OLD.CODIGO_CONTRATO AND OCORRENCIA_DESIG = :OLD.OCORRENCIA ;

    END IF;
    END IF;

-- PARTE DO INSERT     

    BEGIN
      SELECT ID_SEQ_DESIG.NEXTVAL INTO vID FROM dual; 
      SELECT COD_MOT_SOLIC into v_MOTIVO_DESVIO FROM RHPLCS_SOL_DES_FUN WHERE CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND ID_SOL_DES_FUNC = :NEW.ID_SOL_DES_FUNC ;

      EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 5°S TRG' || :NEW.CODIGO_EMPRESA || '-' || :NEW.TIPO_CONTRATO|| '-' ||  :NEW.CODIGO_CONTRATO || '-' || :NEW.OCORRENCIA || '-' || :NEW.ID_SOL_DES_FUNC  || '-' || v_MOTIVO_DESVIO);

      END;


      INSERT
      INTO SMARH_INT_DESIGNACAO
        (
          TIPO_DML,
          CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO,
          OCORRENCIA,
          DT_PROCESSAMENTO,
          ID,
          MOTIVO_DESVIO,
          DATA_INICIO_DESVIO,
          TIPO_CONTRATO_RESP,
          CODIG_CONTR_RESP,
          COD_UNIDADE1,
          COD_UNIDADE2,
          COD_UNIDADE3,
          COD_UNIDADE4,
          COD_UNIDADE5,
          COD_UNIDADE6,
          COD_CARGO_COMIS,
          COD_CARGO_EFET,
          DATA_REGULARIZACAO,
          LOGIN_USUARIO,
          DT_ULT_ALTER_USUA,
          DATA_FIM_DESVIO,
          TIPO_AGRUP,
          NIVEL_CARGO_COMISS,
          NIVEL_CARGO_EFETIV,
          CODIGO_VERBA,
          CODIGO_FUNCAO,
          ID_LEI,
          OPCAO_SERVIDOR,
          COD_ESCALA,
          TIPO_CONTRATO_TITULAR,
          CONTRATO_TITULAR,
          E_GESTOR_TITULAR,
          COD_PESSOA,
          NOME_TABELA,
          DOCUMENTO_PUBLIC,
          VAGA_RESP,
          E_GESTOR,
          DT_PUBLIC_DOM

        )
        VALUES
        (
          v_DML || '/I',
          :NEW.CODIGO_EMPRESA,
          :NEW.TIPO_CONTRATO,
          :NEW.CODIGO_CONTRATO ,
          :NEW.OCORRENCIA ,
          sysdate,
          vID,
          lpad(v_MOTIVO_DESVIO,4,0),
          :NEW.DATA_INICIO_DESVIO ,
          :NEW.TIPO_CONTRATO_RESP ,
          :NEW.CODIG_CONTR_RESP,
          :NEW.COD_UNIDADE1 ,
          :NEW.COD_UNIDADE2 ,
          :NEW.COD_UNIDADE3 ,
          :NEW.COD_UNIDADE4 ,
          :NEW.COD_UNIDADE5 ,
          :NEW.COD_UNIDADE6,
          :NEW.COD_CARGO_COMIS ,
          :NEW.COD_CARGO_EFET ,
          :NEW.DATA_REGULARIZACAO,
          :NEW.LOGIN_USUARIO,
          :NEW.DT_ULT_ALTER_USUA ,
          :NEW.DATA_FIM_DESVIO ,
          :NEW.TIPO_AGRUP ,
          :NEW.NIVEL_CARGO_COMISS ,
          :NEW.NIVEL_CARGO_EFETIV,
          :NEW.CODIGO_VERBA,
          :NEW.CODIGO_FUNCAO,
          :NEW.ID_LEI,
          :NEW.C_LIVRE_SELEC1,
          :NEW.CODIGO_ESCALA,
          :NEW.tipo_contrato_resp,
          :NEW.codig_contr_resp,
          (select CASE WHEN COUNT(1) > 0 THEN 'S' ELSE 'N' END AS E_GESTOR from RHORGA_CUSTO_GEREN WHERE CONTRATO_RESP = :NEW.codig_contr_resp AND TIPO_CONT_RESP = :NEW.tipo_contrato_resp and CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA ) ,
          (SELECT B.CODIGO_PESSOA FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :NEW.TIPO_CONTRATO AND B.CODIGO = :NEW.CODIGO_CONTRATO AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          (SELECT case when :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when  :NEW.COD_CARGO_COMIS IS not null  and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null  and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is not null and :NEW.CODIGO_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when  :NEW.COD_CARGO_COMIS IS not null and :NEW.CODIGO_FUNCAO is null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when  :NEW.COD_CARGO_COMIS IS NULL and :NEW.CODIGO_FUNCAO is not null and :NEW.COD_UNIDADE1  is null and :NEW.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO' END FROM DUAL),
          :NEW.DOCUMENTO_PUBLIC,
          (SELECT B.codigo_vaga FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :NEW.tipo_contrato_resp AND B.CODIGO = :NEW.codig_contr_resp AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          :new.c_livre_opcao01,
          :new.c_livre_data10
        );

    IF ( :NEW.DATA_INICIO_DESVIO <= trunc(SYSDATE) and :NEW.DATA_CANCELAMENTO IS NULL )THEN


    --INCLUIDA EM 10-03-2021 PARA EVITAR ERRO QUANDO A HISTÓRICA DE MOVIMENTAÇÃO POSSUI MAIS DE 1 REGISTRO NA MESMA DATA
    -- verifica  a quantidade de movimentações que a pessooa tem
    SELECT count(1)  as quantidade into v_quantidade_movim FROM RHPESS_CONTRATO CT
          LEFT JOIN (SELECT * FROM RHCGED_TRANSFERENC M
          WHERE M.DT_ALT_UNID_CUSTO =
            (SELECT MAX(AUX.DT_ALT_UNID_CUSTO)
            FROM RHCGED_TRANSFERENC AUX
            WHERE AUX.CODIGO_EMPRESA   = M.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO      = M.TIPO_CONTRATO
            AND AUX.CODIGO             = M.CODIGO
            AND AUX.DT_ALT_UNID_CUSTO <=  :NEW.DATA_INICIO_DESVIO
            )) M
          ON M.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND M.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND M.CODIGO        = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <=  :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO;



    IF ( v_quantidade_movim = 1 )then 
      INSERT
      INTO SMARH_INT_DESIGNACAO_HIST
        (        
        SELECT 
          v_DML,
          case       when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is not null and e.COD_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is not null and m.COD_LOTACAO_ATUAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO'
          else ''
          end as nome_tabela,
            CT.CODIGO_EMPRESA,
            CT.TIPO_CONTRATO,
            CT.CODIGO,
            vID,
            sysdate DT_saiu_arte,
            CT.ANO_MES_REFERENCIA,
            F.DATA_INICIO_FUNCAO,
            F.CODIGO_FUNCAO ,
            F.DT_FIM_TEMP,
            F.CODIGO_HIST_FUNCAO ,
            F.DOCUMENTO_PUBLIC ,
            F.TEXTO_ASSOCIADO ,
            F.ID_LEI,
            F.COD_FUNCAO_AVALIACAO,
            F.ALTERA_SAL_PAGTO_CONTR ,
            C.DT_ALTER_CARGO,
            C.MOTIVO_ALTERACAO ,
            C.COD_CARGO_EFET_AT,
            C.NIV_CARGO_EFET_AT ,
            C.COD_CARGO_COMIS_AT ,
            C.NIV_CARGO_COMIS_AT ,
            C.COD_CARGO_AMPAR_AT ,
            C.NIV_CARGO_AMPAR_AT ,
            C.DT_FIM_TEMP ,
            C.DOCUMENTO_PUBLIC ,
            C.OCORRENCIA ,
            C.SALARIO_PAGTO ,
            C.ID_LEI ,
            C.COD_CARGO_AVALIACAO ,
            M.DT_ALT_UNID_CUSTO,
            M.COD_MOVIMENTACAO,
            M.COD_LOTACAO_ATUAL1,
            M.COD_LOTACAO_ATUAL2,
            M.COD_LOTACAO_ATUAL3,
            M.COD_LOTACAO_ATUAL4,
            M.COD_LOTACAO_ATUAL5,
            M.COD_LOTACAO_ATUAL6,
            M.COD_UNIDADE_ATUAL1,
            M.COD_UNIDADE_ATUAL2,
            M.COD_UNIDADE_ATUAL3,
            M.COD_UNIDADE_ATUAL4,
            M.COD_UNIDADE_ATUAL5,
            M.COD_UNIDADE_ATUAL6,
            M.COD_CCONTAB_ATUAL1,
            M.COD_CCONTAB_ATUAL2,
            M.COD_CCONTAB_ATUAL3,
            M.COD_CCONTAB_ATUAL4,
            M.COD_CCONTAB_ATUAL5,
            M.COD_CCONTAB_ATUAL6,
            M.COD_CGERENC_ATUAL1,
            M.COD_CGERENC_ATUAL2,
            M.COD_CGERENC_ATUAL3,
            M.COD_CGERENC_ATUAL4,
            M.COD_CGERENC_ATUAL5,
            M.COD_CGERENC_ATUAL6,
            M.TEXTO_ASSOCIADO,
            M.MOTIVO_ALTERACAO,
            M.DT_FIM_TEMP,
            M.DOCUMENTO_PUBLIC,
            E.DT_INICIO_TROCA ,
            E.DT_FIM_TROCA ,
            E.COD_ESCALA ,
            E.COD_HORARIO,
            E.COD_MOTIVO ,
            E.COD_SITUACAO ,
            E.ORIGEM_PROGRAMACAO ,
            E.ALTER_DEFINITIVA ,
            E.DOCUMENTO_PUBLIC,
            E.ANALISA_ALTERN,
            E.TEXTO_ASSOCIADO,
            E.COD_MOT_CANCEL_SOL ,
            E.TIPO_HORARIO,
            :NEW.OCORRENCIA,
            'S'
          FROM RHPESS_CONTRATO CT
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_FUNCAO F
            WHERE F.DATA_INICIO_FUNCAO =
              (SELECT MAX(AUX.DATA_INICIO_FUNCAO)
              FROM RHPLCS_ALT_FUNCAO AUX
              WHERE AUX.CODIGO_EMPRESA    = F.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO       = F.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO     = F.CODIGO_CONTRATO
              AND AUX.DATA_INICIO_FUNCAO <= :NEW.DATA_INICIO_DESVIO
              )
            )F
          ON F.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND F.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND F.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_CARGO C
            WHERE C.DT_ALTER_CARGO =
               (SELECT MAX(AUX.DT_ALTER_CARGO)
              FROM RHPLCS_ALT_CARGO AUX
              WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              AND AUX.DT_ALTER_CARGO  <= :NEW.DATA_INICIO_DESVIO
              )
            ) C
          ON C.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND C.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND C.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHCGED_TRANSFERENC M
          WHERE M.DT_ALT_UNID_CUSTO =
            (SELECT MAX(AUX.DT_ALT_UNID_CUSTO)
            FROM RHCGED_TRANSFERENC AUX
            WHERE AUX.CODIGO_EMPRESA   = M.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO      = M.TIPO_CONTRATO
            AND AUX.CODIGO             = M.CODIGO
            AND AUX.DT_ALT_UNID_CUSTO <= :NEW.DATA_INICIO_DESVIO
            )) M
          ON M.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND M.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND M.CODIGO        = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPONT_ALT_ESCALA E
          WHERE  E.DT_INICIO_TROCA =
            (SELECT MAX(AUX.DT_INICIO_TROCA)
            FROM RHPONT_ALT_ESCALA AUX
            WHERE AUX.CODIGO_EMPRESA    = E.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = E.TIPO_CONTRATO
            AND AUX.CODIGO_CONTRATO     = E.CODIGO_CONTRATO
            AND AUX.DT_INICIO_TROCA <= :NEW.DATA_INICIO_DESVIO
            )) E
          ON E.CODIGO_EMPRESA         = CT.CODIGO_EMPRESA
          AND E.TIPO_CONTRATO         = CT.TIPO_CONTRATO
          AND E.CODIGO_CONTRATO       = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
            AND ( C.OCORRENCIA = (SELECT MAX(AUX2.OCORRENCIA)
              FROM RHPLCS_ALT_CARGO AUX2
              WHERE AUX2.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX2.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX2.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              and aux2.DT_ALTER_CARGO = c.DT_ALTER_CARGO ) 
              or c.ocorrencia is null )
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO);


     ELSE 

     -- BUSCA A MOVIMENTAÇÃO DO CONTRATO

           INSERT
      INTO SMARH_INT_DESIGNACAO_HIST
        (        
        SELECT 
          v_DML,
          case       when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO is null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is not null and e.COD_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when C.DT_ALTER_CARGO IS not null and F.CODIGO_FUNCAO is null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when C.DT_ALTER_CARGO IS null and F.CODIGO_FUNCAO is not null and CT2.COD_LOCAL1 is null and e.COD_ESCALA is null then 'RHPLCS_ALT_FUNCAO'
          else ''
          end as nome_tabela,
            CT.CODIGO_EMPRESA,
            CT.TIPO_CONTRATO,
            CT.CODIGO,
            vID,
            sysdate DT_saiu_arte,
            CT.ANO_MES_REFERENCIA,
            F.DATA_INICIO_FUNCAO,
            F.CODIGO_FUNCAO ,
            F.DT_FIM_TEMP,
            F.CODIGO_HIST_FUNCAO ,
            F.DOCUMENTO_PUBLIC ,
            F.TEXTO_ASSOCIADO ,
            F.ID_LEI,
            F.COD_FUNCAO_AVALIACAO,
            F.ALTERA_SAL_PAGTO_CONTR ,
            C.DT_ALTER_CARGO,
            C.MOTIVO_ALTERACAO ,
            C.COD_CARGO_EFET_AT,
            C.NIV_CARGO_EFET_AT ,
            C.COD_CARGO_COMIS_AT ,
            C.NIV_CARGO_COMIS_AT ,
            C.COD_CARGO_AMPAR_AT ,
            C.NIV_CARGO_AMPAR_AT ,
            C.DT_FIM_TEMP ,
            C.DOCUMENTO_PUBLIC ,
            C.OCORRENCIA ,
            C.SALARIO_PAGTO ,
            C.ID_LEI ,
            C.COD_CARGO_AVALIACAO ,
            CT2.DT_ULT_ALT_UNID	, 
            NULL,            
            CT2.COD_LOCAL1,
            CT2.COD_LOCAL2,
            CT2.COD_LOCAL3,
            CT2.COD_LOCAL4,
            CT2.COD_LOCAL5,
            CT2.COD_LOCAL6,
            CT2.COD_UNIDADE1,
            CT2.COD_UNIDADE2,
            CT2.COD_UNIDADE3	,  
            CT2.COD_UNIDADE4	,  
            CT2.COD_UNIDADE5	,  
            CT2.COD_UNIDADE6	,  
            CT2.COD_CUSTO_CONTAB1	,  
            CT2.COD_CUSTO_CONTAB2	,  
            CT2.COD_CUSTO_CONTAB3	,  
            CT2.COD_CUSTO_CONTAB4	,  
            CT2.COD_CUSTO_CONTAB5	,  
            CT2.COD_CUSTO_CONTAB6	,
            CT2.COD_CUSTO_GERENC1	,  
            CT2.COD_CUSTO_GERENC2	,  
            CT2.COD_CUSTO_GERENC3	,  
            CT2.COD_CUSTO_GERENC4	,  
            CT2.COD_CUSTO_GERENC5	,  
            CT2.COD_CUSTO_GERENC6	,  
            NULL,
            NULL,
            NULL,
            NULL,
            E.DT_INICIO_TROCA ,
            E.DT_FIM_TROCA ,
            E.COD_ESCALA ,
            E.COD_HORARIO,
            E.COD_MOTIVO ,
            E.COD_SITUACAO ,
            E.ORIGEM_PROGRAMACAO ,
            E.ALTER_DEFINITIVA ,
            E.DOCUMENTO_PUBLIC,
            E.ANALISA_ALTERN,
            E.TEXTO_ASSOCIADO,
            E.COD_MOT_CANCEL_SOL ,
            E.TIPO_HORARIO,
            :NEW.OCORRENCIA,
            'S'
          FROM RHPESS_CONTRATO CT
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_FUNCAO F
            WHERE F.DATA_INICIO_FUNCAO =
              (SELECT MAX(AUX.DATA_INICIO_FUNCAO)
              FROM RHPLCS_ALT_FUNCAO AUX
              WHERE AUX.CODIGO_EMPRESA    = F.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO       = F.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO     = F.CODIGO_CONTRATO
              AND AUX.DATA_INICIO_FUNCAO <= :NEW.DATA_INICIO_DESVIO
              )
            )F
          ON F.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND F.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND F.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN
            (SELECT *
            FROM RHPLCS_ALT_CARGO C
            WHERE C.DT_ALTER_CARGO =
               (SELECT MAX(AUX.DT_ALTER_CARGO)
              FROM RHPLCS_ALT_CARGO AUX
              WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              AND AUX.DT_ALTER_CARGO  <= :NEW.DATA_INICIO_DESVIO
              )
            ) C
          ON C.CODIGO_EMPRESA   = CT.CODIGO_EMPRESA
          AND C.TIPO_CONTRATO   = CT.TIPO_CONTRATO
          AND C.CODIGO_CONTRATO = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPESS_CONTRATO CT2
          WHERE  CT2.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT2.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT2.TIPO_CONTRATO
            AND AUX.CODIGO              = CT2.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) ) CT2
          ON CT2.CODIGO_EMPRESA = CT.CODIGO_EMPRESA
          AND CT2.TIPO_CONTRATO = CT.TIPO_CONTRATO
          AND CT2.CODIGO        = CT.CODIGO
          LEFT JOIN (SELECT * FROM RHPONT_ALT_ESCALA E
          WHERE  E.DT_INICIO_TROCA =
            (SELECT MAX(AUX.DT_INICIO_TROCA)
            FROM RHPONT_ALT_ESCALA AUX
            WHERE AUX.CODIGO_EMPRESA    = E.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = E.TIPO_CONTRATO
            AND AUX.CODIGO_CONTRATO     = E.CODIGO_CONTRATO
            AND AUX.DT_INICIO_TROCA <= :NEW.DATA_INICIO_DESVIO
            )) E
          ON E.CODIGO_EMPRESA         = CT.CODIGO_EMPRESA
          AND E.TIPO_CONTRATO         = CT.TIPO_CONTRATO
          AND E.CODIGO_CONTRATO       = CT.CODIGO
          WHERE CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <= :NEW.DATA_INICIO_DESVIO
            ) 
            --incluido em 26-10-2020 para exibir apenas uma ocorrencia
            AND ( C.OCORRENCIA = (SELECT MAX(AUX2.OCORRENCIA)
              FROM RHPLCS_ALT_CARGO AUX2
              WHERE AUX2.CODIGO_EMPRESA = C.CODIGO_EMPRESA
              AND AUX2.TIPO_CONTRATO    = C.TIPO_CONTRATO
              AND AUX2.CODIGO_CONTRATO  = C.CODIGO_CONTRATO
              and aux2.DT_ALTER_CARGO = c.DT_ALTER_CARGO ) 
              or c.ocorrencia is null )
          AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
          AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
          AND CT.CODIGO         = :NEW.CODIGO_CONTRATO);

     END IF;

      FOR C1 IN
      (select 
      ANO_MES_REFERENCIA , 	CODIGO_EMPRESA  , 	TIPO_CONTRATO  , 	CODIGO  ,   CODIGO_PESSOA	,  COD_LOCAL1	,  COD_LOCAL2	,  COD_LOCAL3	,  COD_LOCAL4	,  COD_LOCAL5	,  COD_LOCAL6	,  DT_ULT_ALT_LOC	,  COD_UNIDADE1	,
      COD_UNIDADE2	,  COD_UNIDADE3	,  COD_UNIDADE4	,  COD_UNIDADE5	,  COD_UNIDADE6	,  DT_ULT_ALT_UNID	,  COD_CUSTO_CONTAB1	,  COD_CUSTO_CONTAB2	,  COD_CUSTO_CONTAB3	,  COD_CUSTO_CONTAB4	,  COD_CUSTO_CONTAB5	,  COD_CUSTO_CONTAB6	,
      DT_ULT_ALT_CONT	,  COD_CUSTO_GERENC1	,  COD_CUSTO_GERENC2	,  COD_CUSTO_GERENC3	,  COD_CUSTO_GERENC4	,  COD_CUSTO_GERENC5	,  COD_CUSTO_GERENC6	,  DT_ULT_ALT_GER	,  SALARIO_PAGTO	,  COD_CARGO_PAGTO	,
      NIVEL_CARGO_PAGTO	,  COD_CARGO_EFETIVO	,  NIVEL_CARGO_EFETIV	,  DT_ULT_CARGO_EFET	,  COD_CARGO_COMISS	,  NIVEL_CARGO_COMISS	,  DT_ULT_CARGO_COM	,  COD_CARGO_AMPAR	,  NIVEL_CARGO_AMPAR	,  DT_ULT_CARGO_AMPAR	,  
      CODIGO_FUNCAO	,  DT_ULT_FUNCAO	,  CODIGO_ESCALA	,  DT_ULT_ESCALA	,  LOGIN_USUARIO	,  DT_ULT_ALTER_USUA	
      from rhpess_contrato CT WHERE 

            ( ( CT.ANO_MES_REFERENCIA BETWEEN   trunc(:NEW.DATA_INICIO_DESVIO,'MM')    AND  NVL(:NEW.DATA_FIM_DESVIO,SYSDATE) 
            AND CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO )

            ) or (CT.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = CT.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = CT.TIPO_CONTRATO
            AND AUX.CODIGO              = CT.CODIGO
            AND AUX.ANO_MES_REFERENCIA <=  NVL(:NEW.DATA_FIM_DESVIO,SYSDATE)
            )
            ) 
            OR ( CT.ANO_MES_REFERENCIA >= trunc(:NEW.DATA_INICIO_DESVIO,'MM')AND  :NEW.DATA_FIM_DESVIO IS NULL)
            )        
              AND CT.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA
              AND CT.TIPO_CONTRATO  = :NEW.TIPO_CONTRATO
              AND CT.CODIGO         = :NEW.CODIGO_CONTRATO

      )
      LOOP
      INSERT INTO SMARH_INT_DESIGNACAO_CONTR ( TIPO_DML, ID,DT_SAIU_ARTE, ANO_MES_REFERENCIA,CODIGO_EMPRESA,TIPO_CONTRATO,CODIGO,CODIGO_PESSOA,COD_LOCAL1,COD_LOCAL2,COD_LOCAL3,COD_LOCAL4,COD_LOCAL5,
      COD_LOCAL6,DT_ULT_ALT_LOC,COD_UNIDADE1,COD_UNIDADE2,COD_UNIDADE3,COD_UNIDADE4,COD_UNIDADE5,COD_UNIDADE6,DT_ULT_ALT_UNID,COD_CUSTO_CONTAB1,COD_CUSTO_CONTAB2,COD_CUSTO_CONTAB3,COD_CUSTO_CONTAB4,COD_CUSTO_CONTAB5,
      COD_CUSTO_CONTAB6,DT_ULT_ALT_CONT,COD_CUSTO_GERENC1,COD_CUSTO_GERENC2,COD_CUSTO_GERENC3,COD_CUSTO_GERENC4,COD_CUSTO_GERENC5,COD_CUSTO_GERENC6,DT_ULT_ALT_GER,SALARIO_PAGTO,COD_CARGO_PAGTO,NIVEL_CARGO_PAGTO,COD_CARGO_EFETIVO,
      NIVEL_CARGO_EFETIV,LT_ULT_CARGO_EFET,COD_CARGO_COMISS,NIVEL_CARGO_COMISS,DT_ULT_CARGO_COM,COD_CARGO_AMPAR,NIVEL_CARGO_AMPAR,DT_ULT_CARGO_AMPAR,CODIGO_FUNCAO,DT_ULT_FUNCAO,CODIGO_ESCALA,DT_ULT_ESCALA,LOGIN_USUARIO,DT_ULT_ALTER_USUA, OCORRENCIA, CONSIDERAR) 
      VALUES ( v_DML,          vID,          sysdate,          trunc(C1.ANO_MES_REFERENCIA) ,          C1.CODIGO_EMPRESA,          C1.TIPO_CONTRATO,          C1.CODIGO ,           C1.CODIGO_PESSOA	,  C1.COD_LOCAL1	,  C1.COD_LOCAL2	, 
      C1.COD_LOCAL3	,  C1.COD_LOCAL4	,  C1.COD_LOCAL5	,  C1.COD_LOCAL6	,  C1.DT_ULT_ALT_LOC	,  C1.COD_UNIDADE1	,  C1.COD_UNIDADE2	,  C1.COD_UNIDADE3	,  C1.COD_UNIDADE4	,  C1.COD_UNIDADE5	,  C1.COD_UNIDADE6	,  
      C1.DT_ULT_ALT_UNID	, C1.COD_CUSTO_CONTAB1	,  C1.COD_CUSTO_CONTAB2	,  C1.COD_CUSTO_CONTAB3	,  C1.COD_CUSTO_CONTAB4	,  C1.COD_CUSTO_CONTAB5	,  C1.COD_CUSTO_CONTAB6	,  C1.DT_ULT_ALT_CONT	,  C1.COD_CUSTO_GERENC1	, 
      C1.COD_CUSTO_GERENC2	,  C1.COD_CUSTO_GERENC3	,  C1.COD_CUSTO_GERENC4	,  C1.COD_CUSTO_GERENC5	,  C1.COD_CUSTO_GERENC6	,  C1.DT_ULT_ALT_GER	,  C1.SALARIO_PAGTO	,  C1.COD_CARGO_PAGTO	,  C1.NIVEL_CARGO_PAGTO	, 
      C1.COD_CARGO_EFETIVO	,  C1.NIVEL_CARGO_EFETIV	,  C1.DT_ULT_CARGO_EFET	,  C1.COD_CARGO_COMISS	,  C1.NIVEL_CARGO_COMISS	,  C1.DT_ULT_CARGO_COM	,  C1.COD_CARGO_AMPAR	,  C1.NIVEL_CARGO_AMPAR	,  C1.DT_ULT_CARGO_AMPAR	,
      C1.CODIGO_FUNCAO	,  C1.DT_ULT_FUNCAO	, C1.CODIGO_ESCALA	,  C1.DT_ULT_ESCALA	,  C1.LOGIN_USUARIO	,  C1.DT_ULT_ALTER_USUA,  :NEW.OCORRENCIA, 'S');
      END LOOP;

     PR_MIGRA_DADOS_DESIG(:NEW.CODIGO_EMPRESA,:NEW.TIPO_CONTRATO,:NEW.CODIGO_CONTRATO,:NEW.DATA_INICIO_DESVIO, :NEW.DATA_FIM_DESVIO, vID, 'U-INSERIR', :NEW.LOGIN_USUARIO);

     END IF;


ELSIF DELETING THEN
      v_DML := 'D';
      BEGIN
      SELECT COD_MOT_SOLIC into v_MOTIVO_DESVIO FROM RHPLCS_SOL_DES_FUN WHERE CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND ID_SOL_DES_FUNC = :OLD.ID_SOL_DES_FUNC ;
            EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 6°S TRG');
      END;

      INSERT
      INTO SMARH_INT_DESIGNACAO
        (
          TIPO_DML,
          CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO,
          OCORRENCIA,
          DT_PROCESSAMENTO,
          ID,
          MOTIVO_DESVIO,
          DATA_INICIO_DESVIO,
          TIPO_CONTRATO_RESP,
          CODIG_CONTR_RESP,
          COD_UNIDADE1,
          COD_UNIDADE2,
          COD_UNIDADE3,
          COD_UNIDADE4,
          COD_UNIDADE5,
          COD_UNIDADE6,
          COD_CARGO_COMIS,
          COD_CARGO_EFET,
          DATA_REGULARIZACAO,
          LOGIN_USUARIO,
          DT_ULT_ALTER_USUA,
          DATA_FIM_DESVIO,
          TIPO_AGRUP,
          NIVEL_CARGO_COMISS,
          NIVEL_CARGO_EFETIV,
          CODIGO_VERBA,
          CODIGO_FUNCAO,
          ID_LEI,
          OPCAO_SERVIDOR,
          COD_ESCALA,
          TIPO_CONTRATO_TITULAR,
          CONTRATO_TITULAR,
          E_GESTOR_TITULAR,
          COD_PESSOA,
          NOME_TABELA,
          DOCUMENTO_PUBLIC,
          VAGA_RESP,
          E_GESTOR,
          DT_PUBLIC_DOM
        )
        VALUES
        (
          v_DML,
          :OLD.CODIGO_EMPRESA,
          :OLD.TIPO_CONTRATO,
          :OLD.CODIGO_CONTRATO ,
          :OLD.OCORRENCIA ,
          sysdate,
          vID,
          lpad(v_MOTIVO_DESVIO,4,0),
          :OLD.DATA_INICIO_DESVIO ,
          :OLD.TIPO_CONTRATO_RESP ,
          :OLD.CODIG_CONTR_RESP,
          :OLD.COD_UNIDADE1 ,
          :OLD.COD_UNIDADE2 ,
          :OLD.COD_UNIDADE3 ,
          :OLD.COD_UNIDADE4 ,
          :OLD.COD_UNIDADE5 ,
          :OLD.COD_UNIDADE6,
          :OLD.COD_CARGO_COMIS ,
          :OLD.COD_CARGO_EFET ,
          :OLD.DATA_REGULARIZACAO,
          :OLD.LOGIN_USUARIO,
          :OLD.DT_ULT_ALTER_USUA ,
          :OLD.DATA_FIM_DESVIO ,
          :OLD.TIPO_AGRUP ,
          :OLD.NIVEL_CARGO_COMISS ,
          :OLD.NIVEL_CARGO_EFETIV,
          :OLD.CODIGO_VERBA,
          :OLD.CODIGO_FUNCAO,
          :OLD.ID_LEI,
          :OLD.C_LIVRE_SELEC1,
          :OLD.CODIGO_ESCALA,
          :OLD.tipo_contrato_resp,
          :OLD.codig_contr_resp,
          (select CASE WHEN COUNT(1) > 0 THEN 'S' ELSE 'N' END AS E_GESTOR from RHORGA_CUSTO_GEREN WHERE CONTRATO_RESP = :OLD.codig_contr_resp AND TIPO_CONT_RESP = :OLD.tipo_contrato_resp ) ,
          (SELECT B.CODIGO_PESSOA FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :OLD.TIPO_CONTRATO AND B.CODIGO = :OLD.CODIGO_CONTRATO AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          (SELECT case when  :OLD.COD_CARGO_COMIS IS not null and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC' 
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is  null then 'RHPLCS_ALT_CARGO;RHPLCS_ALT_FUNCAO'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_FUNCAO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPLCS_ALT_CARGO;RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA;RHCGED_TRANSFERENC'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is not null and :OLD.CODIGO_ESCALA is null then 'RHCGED_TRANSFERENC' 
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is not null then 'RHPONT_ALT_ESCALA'
          when   :OLD.COD_CARGO_COMIS IS not null  and :OLD.CODIGO_FUNCAO is null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_CARGO'
          when   :OLD.COD_CARGO_COMIS IS NULL and :OLD.CODIGO_FUNCAO is not null and :OLD.COD_UNIDADE1  is null and :OLD.CODIGO_ESCALA is null then 'RHPLCS_ALT_FUNCAO' END FROM DUAL),
          :OLD.DOCUMENTO_PUBLIC,
          (SELECT B.codigo_vaga FROM RHPESS_CONTRATO B WHERE B.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND B.TIPO_CONTRATO = :OLD.tipo_contrato_resp AND B.CODIGO = :OLD.codig_contr_resp AND B.ANO_MES_REFERENCIA =  (SELECT MAX(ANO_MES_REFERENCIA)  FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO  AND AUX.CODIGO           = B.CODIGO  )),
          :old.c_livre_opcao01,
          :old.c_livre_data10

        );

    BEGIN
      select CASE WHEN count(1) IS NULL THEN 0 ELSE count(1) END into cont_1 from SMARH_INT_DESIGNACAO_CONTR where CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO AND CODIGO  = :OLD.CODIGO_CONTRATO AND OCORRENCIA = :OLD.OCORRENCIA ;
       EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 7°SA TRG');
      END;
    BEGIN
      select CASE WHEN count(1) IS NULL THEN 0 ELSE count(1) END into cont_2 from SMARH_INT_DESIGNACAO_HIST where CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO AND CODIGO = :OLD.CODIGO_CONTRATO AND OCORRENCIA_DESIG = :OLD.OCORRENCIA ;
       EXCEPTION
           WHEN OTHERS THEN
            raise_application_error (-20003,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DA DESIGNAÇÃO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM || ' 8°SB TRG');
      END;

      if( ( cont_1 >0 and cont_1 is not null) and ( cont_2 > 0 and cont_1 is not null) ) THEN

      IF( :OLD.DATA_INICIO_DESVIO <=  trunc(SYSDATE) ) THEN 
      PR_MIGRA_DADOS_DESIG(:OLD.CODIGO_EMPRESA,:OLD.TIPO_CONTRATO,:OLD.CODIGO_CONTRATO,:OLD.DATA_INICIO_DESVIO, :OLD.DATA_FIM_DESVIO, vID, 'EXCLUIR', :OLD.LOGIN_USUARIO);

      UPDATE SMARH_INT_DESIGNACAO_CONTR SET CONSIDERAR = 'N' where 
      CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA
      AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO
      AND CODIGO  = :OLD.CODIGO_CONTRATO AND OCORRENCIA = :OLD.OCORRENCIA ;

      UPDATE SMARH_INT_DESIGNACAO_HIST SET CONSIDERAR = 'N' where 
      CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA
      AND TIPO_CONTRATO    = :OLD.TIPO_CONTRATO
      AND CODIGO = :OLD.CODIGO_CONTRATO AND OCORRENCIA_DESIG = :OLD.OCORRENCIA ;

    END IF;
    END IF;


      END IF; --FIM IF PARA SABER SE E INSERT, UPDATE ou DELETE
  END;      --FIM TRIGGER
ALTER TRIGGER "ARTERH"."TR_DESIG_SUBST" ENABLE