
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RHTEMP_APOSENT_QUIN" FOR INSERT ON ARTERH.RHPESS_CONTRATO COMPOUND TRIGGER
 
 VCONT NUMBER;
TYPE REG_DADOS IS RECORD ( 
VCODIGO_EMPRESA ARTERH.RHPESS_CONTRATO.CODIGO_EMPRESA%TYPE,
VTIPO_CONTRATO ARTERH.RHPESS_CONTRATO.TIPO_CONTRATO%TYPE,
VCODIGO_CONTRATO ARTERH.RHPESS_CONTRATO.CODIGO%TYPE,
VDATA_EFETIVO_EXERC ARTERH.RHPESS_CONTRATO.DATA_EFETIVO_EXERC%TYPE,
VCOD_CARGO_EFETIVO ARTERH.RHPESS_CONTRATO.COD_CARGO_EFETIVO%TYPE,
VVINCULO ARTERH.RHPESS_CONTRATO.VINCULO%TYPE
);

TYPE LINHA
IS 
  TABLE OF REG_DADOS INDEX BY PLS_INTEGER;
  LINHA_INFO LINHA;

   AFTER EACH ROW
IS

BEGIN
  LINHA_INFO(LINHA_INFO.COUNT + 1).VCODIGO_EMPRESA     := :NEW.CODIGO_EMPRESA;
  LINHA_INFO(LINHA_INFO.COUNT ).VCODIGO_CONTRATO       := :NEW.CODIGO;
  LINHA_INFO(LINHA_INFO.COUNT ).VTIPO_CONTRATO         := :NEW.TIPO_CONTRATO;
  LINHA_INFO(LINHA_INFO.COUNT ).VDATA_EFETIVO_EXERC    := :NEW.DATA_EFETIVO_EXERC;
  LINHA_INFO(LINHA_INFO.COUNT ).VCOD_CARGO_EFETIVO     := :NEW.COD_CARGO_EFETIVO;
  LINHA_INFO(LINHA_INFO.COUNT ).VVINCULO               := :NEW.VINCULO;
END AFTER EACH ROW;

AFTER STATEMENT
IS

BEGIN

  FOR INDX IN 1 .. LINHA_INFO.COUNT
  LOOP

SELECT COUNT(1) INTO VCONT 
FROM RHPESS_CONTRATO WHERE CODIGO = LINHA_INFO(INDX).VCODIGO_CONTRATO  AND TIPO_CONTRATO = LINHA_INFO(INDX).VTIPO_CONTRATO AND CODIGO_EMPRESA = LINHA_INFO(INDX).VCODIGO_EMPRESA;

CASE WHEN INSERTING AND VCONT = 1 AND SUBSTR(LINHA_INFO(INDX).VCOD_CARGO_EFETIVO, 12, 4) IN ( '1402', '1403', '1410', '1413', '1414', '1415', '1417', '1418', '1419', '1420', '1421', '1422', '1423', '1425', 
'1433', '1434', '1435', '1436', '1439', '1763', '1765', '1766', '1767', '1768', '1901', '1924', '1925' ) AND  LINHA_INFO(INDX).VVINCULO IN ('0002','0000') 
AND LINHA_INFO(INDX).VDATA_EFETIVO_EXERC >= TO_DATE('30/09/2010','DD/MM/YYYY') AND LINHA_INFO(INDX).VCODIGO_EMPRESA = '0001' AND LINHA_INFO(INDX).VTIPO_CONTRATO = '0001' THEN

INSERT INTO ARTERH.RHTEMP_APOSENT (CODIGO_EMPRESA,TIPO_CONTRATO,CODIGO_CONTRATO,COD_TIPO_APOS,DT_APURACAO,C_LIVRE_OPCAO01,C_LIVRE_OPCAO02,LOGIN_USUARIO,DT_ULT_ALTER_USUA,IND_CALCULO,OCORRENCIA,DT_INI_AQUISICAO,CODIGO_MOTIVO_OCOR,SOMA_FERIAS_DOBRO,TEMPO_ATUAL,TEMPO_COMPUTO,TEMPO_ANTER,PERC_SALARIO,TEMPO_BENEF,TEMPO_TRANSICAO) 
VALUES (LINHA_INFO(INDX).VCODIGO_EMPRESA,LINHA_INFO(INDX).VTIPO_CONTRATO,LINHA_INFO(INDX).VCODIGO_CONTRATO,'008A',LINHA_INFO(INDX).VDATA_EFETIVO_EXERC,'N','N','TR_RHTEMP_APOSENT_QUIN',SYSDATE,'N','1',LINHA_INFO(INDX).VDATA_EFETIVO_EXERC,'0000','N','0','0','0','0','0','0' );


WHEN INSERTING AND VCONT = 1 AND SUBSTR(LINHA_INFO(INDX).VCOD_CARGO_EFETIVO, 12, 4) NOT IN ( '1402', '1403', '1410', '1413', '1414', '1415', '1417', '1418', '1419', '1420', '1421', '1422', '1423', '1425', 
'1433', '1434', '1435', '1436', '1439', '1763', '1765', '1766', '1767', '1768', '1901', '1924', '1925' ) AND LINHA_INFO(INDX).VVINCULO IN ('0002','0000') 
AND  LINHA_INFO(INDX).VDATA_EFETIVO_EXERC >= TO_DATE('30/09/2010','DD/MM/YYYY') AND LINHA_INFO(INDX).VCODIGO_EMPRESA = '0001' AND LINHA_INFO(INDX).VTIPO_CONTRATO = '0001' THEN

INSERT INTO ARTERH.RHTEMP_APOSENT (CODIGO_EMPRESA,TIPO_CONTRATO,CODIGO_CONTRATO,COD_TIPO_APOS,DT_APURACAO,C_LIVRE_OPCAO01,C_LIVRE_OPCAO02,LOGIN_USUARIO,DT_ULT_ALTER_USUA,IND_CALCULO,OCORRENCIA,DT_INI_AQUISICAO,CODIGO_MOTIVO_OCOR,SOMA_FERIAS_DOBRO,TEMPO_ATUAL,TEMPO_COMPUTO,TEMPO_ANTER,PERC_SALARIO,TEMPO_BENEF,TEMPO_TRANSICAO) 
VALUES (LINHA_INFO(INDX).VCODIGO_EMPRESA,LINHA_INFO(INDX).VTIPO_CONTRATO,LINHA_INFO(INDX).VCODIGO_CONTRATO,'0008',LINHA_INFO(INDX).VDATA_EFETIVO_EXERC,'N','N','TR_RHTEMP_APOSENT_QUIN',SYSDATE,'N','1',LINHA_INFO(INDX).VDATA_EFETIVO_EXERC,'0000','N','0','0','0','0','0','0' );

ELSE 
NULL;

END CASE;

  END LOOP;

END AFTER STATEMENT;
END;

ALTER TRIGGER "ARTERH"."TR_RHTEMP_APOSENT_QUIN" ENABLE