
  CREATE OR REPLACE EDITIONABLE TRIGGER "PONTO_ELETRONICO"."TR_RHPONT_APUR_AGRUP_LOG" 
BEFORE INSERT OR UPDATE OR DELETE ON ARTERH.RHPONT_APUR_AGRUP
FOR EACH ROW
 DECLARE
vULT_ID number;
v_DML PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG.TIPO_DML%TYPE;

    vLOGIN_USUARIO_NEW VARCHAR2(40);
    vLOGIN_USUARIO_OLD VARCHAR2(40);
    vLOGIN_OS_NEW VARCHAR2(40);
    vLOGIN_OS_OLD VARCHAR2(40);
    vLOGIN_NEW VARCHAR2(40);
    vLOGIN_OLD VARCHAR2(40);
--PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
--POPULA VARIAVEIS
vULT_ID := 0;
    vLOGIN_USUARIO_NEW := :NEW.LOGIN_USUARIO;
    vLOGIN_USUARIO_OLD := :OLD.LOGIN_USUARIO;
    vLOGIN_OS_NEW := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_OS_OLD := SYS_CONTEXT ('USERENV', 'OS_USER');
--definir login a usar NEW
    IF vLOGIN_USUARIO_NEW = 'ARTERH_UPBH' then
    vLOGIN_NEW := vLOGIN_OS_NEW;
    ELSE
    vLOGIN_NEW := vLOGIN_USUARIO_NEW;
    END IF;
--definir login a usar OLD
    IF vLOGIN_USUARIO_OLD = 'ARTERH_UPBH' then
    vLOGIN_NEW := vLOGIN_OS_OLD;
    ELSE
    vLOGIN_OLD := vLOGIN_USUARIO_OLD;
    END IF;
--------------------------------------------------------------------------INSERT-------------------------------------------------------------------------------------------------------------------------------------------
IF INSERTING THEN
v_DML := 'I';
INSERT INTO PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG
(
ID,
TIPO_DML,
NEW_CODIGO_EMPRESA,
NEW_TIPO_APUR,
NEW_OCORRENCIA,
NEW_DATA_INI_VIGENCIA,
NEW_DATA_FIM_VIGENCIA,
NEW_DATA_INI_FOLHA,
NEW_DATA_FIM_FOLHA,
NEW_ID_AGRUP,
NEW_STATUS_APUR,
NEW_TIPO_FECHAMENTO,
NEW_FECHAMENTO_LOCAL_UNICO,
NEW_DATA_CADASTRO,
NEW_DATA_PROCESSAMENTO,
NEW_DATA_ESTORNO,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
(SELECT MAX(ID)+1 FROM PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG),
v_DML,
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_APUR,
:NEW.OCORRENCIA,
:NEW.DATA_INI_VIGENCIA,
:NEW.DATA_FIM_VIGENCIA,
:NEW.DATA_INI_FOLHA,
:NEW.DATA_FIM_FOLHA,
:NEW.ID_AGRUP,
:NEW.STATUS_APUR,
:NEW.C_LIVRE_SELEC01,
:NEW.C_LIVRE_OPCAO01,
:NEW.C_LIVRE_DATA01,
:NEW.C_LIVRE_DATA02,
:NEW.C_LIVRE_DATA03,
:NEW.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
-------------------------------------------------------------------------UPDATE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF UPDATING THEN
v_DML := 'U';
INSERT INTO PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG
(
ID,
TIPO_DML,
NEW_CODIGO_EMPRESA,
OLD_CODIGO_EMPRESA,
NEW_TIPO_APUR,
OLD_TIPO_APUR,
NEW_OCORRENCIA,
OLD_OCORRENCIA,
NEW_DATA_INI_VIGENCIA,
OLD_DATA_INI_VIGENCIA,
NEW_DATA_FIM_VIGENCIA,
OLD_DATA_FIM_VIGENCIA,
NEW_DATA_INI_FOLHA,
OLD_DATA_INI_FOLHA,
NEW_DATA_FIM_FOLHA,
OLD_DATA_FIM_FOLHA,
NEW_ID_AGRUP,
OLD_ID_AGRUP,
NEW_STATUS_APUR,
OLD_STATUS_APUR,
NEW_TIPO_FECHAMENTO,
OLD_TIPO_FECHAMENTO,
NEW_FECHAMENTO_LOCAL_UNICO,
OLD_FECHAMENTO_LOCAL_UNICO,
NEW_DATA_CADASTRO,
OLD_DATA_CADASTRO,
NEW_DATA_PROCESSAMENTO,
OLD_DATA_PROCESSAMENTO,
NEW_DATA_ESTORNO,
OLD_DATA_ESTORNO,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
(SELECT MAX(ID)+1 FROM PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG),
v_DML,
:NEW.CODIGO_EMPRESA,
:OLD.CODIGO_EMPRESA,
:NEW.TIPO_APUR,
:OLD.TIPO_APUR,
:NEW.OCORRENCIA,
:OLD.OCORRENCIA,
:NEW.DATA_INI_VIGENCIA,
:OLD.DATA_INI_VIGENCIA,
:NEW.DATA_FIM_VIGENCIA,
:OLD.DATA_FIM_VIGENCIA,
:NEW.DATA_INI_FOLHA,
:OLD.DATA_INI_FOLHA,
:NEW.DATA_FIM_FOLHA,
:OLD.DATA_FIM_FOLHA,
:NEW.ID_AGRUP,
:OLD.ID_AGRUP,
:NEW.STATUS_APUR,
:OLD.STATUS_APUR,
:NEW.C_LIVRE_SELEC01,
:OLD.C_LIVRE_SELEC01,
:NEW.C_LIVRE_OPCAO01,
:OLD.C_LIVRE_OPCAO01,
:NEW.C_LIVRE_DATA01,
:OLD.C_LIVRE_DATA01,
:NEW.C_LIVRE_DATA02,
:OLD.C_LIVRE_DATA02,
:NEW.C_LIVRE_DATA03,
:OLD.C_LIVRE_DATA03,
:NEW.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
--------------------------------------------------------------------------DELETE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF DELETING THEN
v_DML := 'D';
INSERT INTO PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG
(
ID,
TIPO_DML,
OLD_CODIGO_EMPRESA,
OLD_TIPO_APUR,
OLD_OCORRENCIA,
OLD_DATA_INI_VIGENCIA,
OLD_DATA_FIM_VIGENCIA,
OLD_DATA_INI_FOLHA,
OLD_DATA_FIM_FOLHA,
OLD_ID_AGRUP,
OLD_STATUS_APUR,
OLD_TIPO_FECHAMENTO,
OLD_FECHAMENTO_LOCAL_UNICO,
OLD_DATA_CADASTRO,
OLD_DATA_PROCESSAMENTO,
OLD_DATA_ESTORNO,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
(SELECT MAX(ID)+1 FROM PONTO_ELETRONICO.IFPONTO_RHPONT_APUR_AGRUP_LOG),
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_APUR,
:OLD.OCORRENCIA,
:OLD.DATA_INI_VIGENCIA,
:OLD.DATA_FIM_VIGENCIA,
:OLD.DATA_INI_FOLHA,
:OLD.DATA_FIM_FOLHA,
:OLD.ID_AGRUP,
:OLD.STATUS_APUR,
:OLD.C_LIVRE_SELEC01,
:OLD.C_LIVRE_OPCAO01,
:OLD.C_LIVRE_DATA01,
:OLD.C_LIVRE_DATA02,
:OLD.C_LIVRE_DATA03,
:OLD.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
END IF; --FIM IF PARA SABER SE Ã‰ INSERT, UPDATE ou DELETE
END; --FIM TRIGGER




ALTER TRIGGER "PONTO_ELETRONICO"."TR_RHPONT_APUR_AGRUP_LOG" ENABLE