
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RHPBH_CESSAO_LOG" 
AFTER INSERT OR UPDATE  OR DELETE 
ON "ARTERH"."RHPESS_CESSAO_TRAB"
FOR EACH ROW
DECLARE
    v_acao CHAR(1);
    v_cessao RHPESS_CESSAO_TRAB%rowtype;
BEGIN
 IF INSERTING THEN
        v_acao := 'I'; -- Insert
        v_cessao.codigo_empresa:=:new.codigo_empresa;
        v_cessao.TIPO_CONTRATO:=:new.TIPO_CONTRATO;
        v_cessao.CODIGO_CONTRATO:=:new.CODIGO_CONTRATO;
        v_cessao.DATA_INICIO_CESSAO:=:new.DATA_INICIO_CESSAO;
    ELSIF UPDATING THEN
     v_cessao.codigo_empresa:=:new.codigo_empresa;
     v_cessao.TIPO_CONTRATO:=:new.TIPO_CONTRATO;
     v_cessao.CODIGO_CONTRATO:=:new.CODIGO_CONTRATO;
     v_cessao.DATA_INICIO_CESSAO:=:new.DATA_INICIO_CESSAO;
     v_acao := 'U'; -- Update
    ELSIF DELETING THEN
       v_cessao.codigo_empresa:=:old.codigo_empresa;
     v_cessao.TIPO_CONTRATO:=:old.TIPO_CONTRATO;
     v_cessao.CODIGO_CONTRATO:=:old.CODIGO_CONTRATO;
     v_cessao.DATA_INICIO_CESSAO:=:old.DATA_INICIO_CESSAO;
     v_acao := 'D'; -- Delete
    END IF;
    INSERT INTO RHPBH_CESSAO_LOG (
        ACAO,
        CODIGO_EMPRESA,
        TIPO_CONTRATO,
        CODIGO_CONTRATO,
        DATA_INICIO_CESSAO,
        DATA_TERMINO_CESSAO_ANTIGO,
        DATA_TERMINO_CESSAO_NOVO,
        TIPO_CESSAO_ANTIGO,
        TIPO_CESSAO_NOVO,
        TP_INSCRICAO_CEDENTE_ANTIGO,
        TP_INSCRICAO_CEDENTE_NOVO,
        NRO_INSCRICAO_CEDENTE_ANTIGO,
        NRO_INSCRICAO_CEDENTE_NOVO,
        MATRICULA_CEDENTE_ANTIGO,
        MATRICULA_CEDENTE_NOVO,
        DT_ADMISSAO_CEDENTE_NOVO,
        INFO_ONUS_ANTIGO,
        INFO_ONUS_NOVO,
        CODIGO_CARGO_ORIGEM_ANTIGO,
        CODIGO_CARGO_ORIGEM_NOVO,
        COD_CATEG_ORIGEM_ANTIGO,
        COD_CATEG_ORIGEM_NOVO,
        TP_REGIME_TRAB_CEDENTE_ANTIGO,
        TP_REGIME_TRAB_CEDENTE_NOVO,
        TP_REGIME_PREV_CEDENTE_ANTIGO,
        TP_REGIME_PREV_CEDENTE_NOVO,
        LOGIN_USUARIO_ANTIGO,
        LOGIN_USUARIO_NOVO,
        DT_ULT_ALTER_USUA
    )
    VALUES (
        v_acao,
         v_cessao.codigo_empresa,
        v_cessao.TIPO_CONTRATO,
        v_cessao.CODIGO_CONTRATO,
     v_cessao.DATA_INICIO_CESSAO,
        :OLD.DATA_TERMINO_CESSAO,
        :NEW.DATA_TERMINO_CESSAO,
        :OLD.TIPO_CESSAO,
        :NEW.TIPO_CESSAO,
        :OLD.TP_INSCRICAO_CEDENTE,
        :NEW.TP_INSCRICAO_CEDENTE,
        :OLD.NRO_INSCRICAO_CEDENTE,
        :NEW.NRO_INSCRICAO_CEDENTE,
        :OLD.MATRICULA_CEDENTE,
        :NEW.MATRICULA_CEDENTE,
        :NEW.DT_ADMISSAO_CEDENTE,
        :OLD.INFO_ONUS,
        :NEW.INFO_ONUS,
        :OLD.CODIGO_CARGO_ORIGEM,
        :NEW.CODIGO_CARGO_ORIGEM,
        :OLD.COD_CATEG_ORIGEM,
        :NEW.COD_CATEG_ORIGEM,
        :OLD.TP_REGIME_TRAB_CEDENTE,
        :NEW.TP_REGIME_TRAB_CEDENTE,
        :OLD.TP_REGIME_PREV_CEDENTE,
        :NEW.TP_REGIME_PREV_CEDENTE,
        :OLD.LOGIN_USUARIO,
        :NEW.LOGIN_USUARIO,
        SYSDATE
    );
END;
ALTER TRIGGER "ARTERH"."TR_RHPBH_CESSAO_LOG" ENABLE