
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RHUSER_P_SIST" FOR 
DELETE OR 
INSERT OR 
UPDATE ON "ARTERH"."RHUSER_P_SIST" 
COMPOUND TRIGGER 
TYPE ID_USUARIO IS RECORD (CODIGO_USUARIO RHUSER_P_SIST.CODIGO_USUARIO%TYPE, CODIGO_SGBD_PADRAO RHUSER_P_SIST.CODIGO_SGBD_PADRAO%TYPE, STATUS_USUARIO RHUSER_P_SIST.STATUS_USUARIO%TYPE, EMPRESA_SELEC RHUSER_P_SIST.EMPRESA_SELEC%TYPE,  TIPO_CONTR_SELEC RHUSER_P_SIST.TIPO_CONTR_SELEC%TYPE);
TYPE DEF_USUARIO IS TABLE OF ID_USUARIO INDEX BY PLS_INTEGER;
LINHA_INFO DEF_USUARIO;
vID NUMBER;
vTIPO_DML VARCHAR2(1);

AFTER EACH ROW IS
BEGIN
 LINHA_INFO(LINHA_INFO.COUNT + 1).CODIGO_USUARIO     := :NEW.CODIGO_USUARIO;
 LINHA_INFO(LINHA_INFO.COUNT ).CODIGO_SGBD_PADRAO   := :NEW.CODIGO_SGBD_PADRAO;
 LINHA_INFO(LINHA_INFO.COUNT ).STATUS_USUARIO   := :NEW.STATUS_USUARIO;
 LINHA_INFO(LINHA_INFO.COUNT ).EMPRESA_SELEC   := :NEW.EMPRESA_SELEC;
 LINHA_INFO(LINHA_INFO.COUNT ).TIPO_CONTR_SELEC   := :NEW.TIPO_CONTR_SELEC;

 SELECT ID_SEQ_AUDIT_USER.NEXTVAL INTO vID FROM dual;

/* ------------------------------------------------------------- INICIO SALVA LOG --------------------------------------------------------*/

   IF INSERTING THEN
      vTIPO_DML:= 'I';

      INSERT
      INTO RHPBH_RHUSER_P_SIST_AUDIT
      VALUES (:NEW.CODIGO_USUARIO,:NEW.GERA_LOG,:NEW.USA_JANELA_ACOMP,:NEW.DT_M_OPER_PROPRIO,:NEW.DATA_SISTEMA,:NEW.ANO_BASE,:NEW.USA_SAL_PRINCIPAL,:NEW.MODO_OPER_MOVI,:NEW.CTRL_OPER_AUXILIAR,:NEW.MODO_OPER_TSAL,:NEW.MODO_OPER_PONTO,:NEW.EMPR_TP_CONTR_PROP,:NEW.EMPRESA_SELEC,:NEW.TIPO_CONTR_SELEC,:NEW.LOGIN_USUARIO,SYSDATE,:NEW.ALT_MOV_LIQUIDO,:NEW.COD_PAD_CONTRATO,:NEW.MSG_PARA_ARQ_TEXTO,:NEW.EXIBE_IDENT_TABELA,:NEW.USA_DELIMIT_EXPORT,:NEW.DELIMITADOR_EXPORT,:NEW.EXPORT_NRO_REAL,:NEW.ALT_MV_PT_DT_RETRO,:NEW.USA_COD_ALTER_VERB,:NEW.CODIGO_GRUPO,:NEW.GRUPO_SEL_CONTRATO,:NEW.GRUPO_SEL_PESSOA,:NEW.COD_SEL_PESSOA,:NEW.GRUPO_SEL_CAND,:NEW.COD_SEL_CANDIDATO,:NEW.GRUPO_SEL_VERBA,:NEW.COD_SEL_VERBA,:NEW.ALT_PROPRIEDADES,:NEW.QTDE_MIN_ATIVO,:NEW.PERMITE_INCLUSAO,:NEW.PERMITE_EXCLUSAO,:NEW.PERMITE_ALTERACAO,:NEW.PERMITE_EXECUCAO,:NEW.GRUPO_SEL_UNID,:NEW.COD_SEL_UNID,:NEW.GRUPO_SEL_CCONT,:NEW.COD_SEL_CCONT,:NEW.GRUPO_SEL_CGER,:NEW.COD_SEL_CGER,:NEW.EMPRESA_USUARIO,:NEW.TP_CONTR_USUARIO,:NEW.CONTRATO_USUARIO,:NEW.PESSOA_USUARIO,:NEW.GRUPO_SEL_LOC,:NEW.COD_SEL_LOC,:NEW.USA_DT_MAQUINA,:NEW.CTRL_ATIVO,:NEW.NRO_MOD_SIMULT,:NEW.QTDE_REG_AUTO,:NEW.CONSISTE_LANC_VERB,:NEW.INSERE_LIQUIDO,:NEW.BLOQUEIA_CONTRATO,:NEW.BLOQUEIA_PESSOA,:NEW.EXIBE_DICA,:NEW.ALT_CONT_DT_RETRO,:NEW.ALT_PESS_DT_RETRO,:NEW.ALT_DATA_GERAL,:NEW.COD_PERIODO,:NEW.EDITA_SALARIO,:NEW.NATUR_PROC_SELEC,:NEW.GRUPO_SEGURANCA,:NEW.MENU_DEF_ENABLED,:NEW.MENU_DEF_VISIBLE,:NEW.SENHA_USUARIO,:NEW.STATUS_USUARIO,:NEW.DT_ULT_TROCA_SENHA,:NEW.CODIGO_SGBD_PADRAO,:NEW.DIAS_EXPIRA_SENHA,:NEW.PW_QTDE_POSIC,:NEW.PW_ALFANUM,:NEW.PW_SUBSET_USUA,:NEW.PW_QTDE_TENTA,:NEW.PW_COMECA_VOGAL,:NEW.APLIC_PROPRIEDADES,:NEW.NOME_USUARIO,:NEW.CODIGO_IDIOMA,:NEW.DIAS_EXP_SEM_ACESS,:NEW.DT_ULT_ACESSO,:NEW.CT_APLIC_PSEL_CONT,:NEW.CT_APLIC_PSEL_PESS,:NEW.C_LIVRE_SELEC01,:NEW.C_LIVRE_SELEC02,:NEW.C_LIVRE_SELEC03,:NEW.C_LIVRE_VALOR01,:NEW.C_LIVRE_VALOR02,:NEW.C_LIVRE_VALOR03,:NEW.C_LIVRE_DESCR01,:NEW.C_LIVRE_DESCR02,:NEW.C_LIVRE_DESCR03,:NEW.C_LIVRE_OPCAO01,:NEW.C_LIVRE_OPCAO02,:NEW.C_LIVRE_OPCAO03,:NEW.C_LIVRE_DATA01,:NEW.C_LIVRE_DATA02,:NEW.C_LIVRE_DATA03,:NEW.ALT_MOV_LIQ_AGRUP,:NEW.EXPAND_CAMINHO,:NEW.EDITA_GRUPO,:NEW.GRAVA_TEMPO_FORM,:NEW.MIN_TESTE_ESCALONA,:NEW.ACERTO_BASE_HIST,:NEW.MODULO_ACESSADO,:NEW.ALT_PONTO_DT_RETRO,:NEW.CTRL_ACESSO_IND,:NEW.APELIDO,:NEW.TIPO_AGRUP_USUARIO,:NEW.PERMITE_TPAGR_ESP,:NEW.DEPURA,:NEW.PW_SUBSET_NOME,:NEW.PW_DATAS_PESSOAIS,:NEW.PW_DOCS_PESSOAIS,:NEW.USUARIO_LDAP,:NEW.TIPO_LOGIN,:NEW.CODIGO_SERV_AUTENT,:NEW.INS_MOV_MEST_CONTR,:NEW.INS_MOV_MEST_AGRUP,:NEW.INS_MOV_MEST_VAGA,:NEW.ACESSA_OUTRO_USUA,:NEW.MODULO_ACES_WEB,:NEW.ESTACAO_REDE,:NEW.LOG_DETALHADO,:NEW.PERSISTE_ARG_SEL,:NEW.DATA_CRIACAO,:NEW.EXEC_INST_ESCALONA,:NEW.PERMITE_EFETIVAR_SQL,:NEW.CONTROLE_BPM,:NEW.ULTIMO_PERFIL_ACESSO_AZC,vTIPO_DML,vID,SYS_CONTEXT ('USERENV', 'OS_USER'));

  ELSIF UPDATING THEN
      vTIPO_DML:= 'U';

      INSERT
      INTO RHPBH_RHUSER_P_SIST_AUDIT
      VALUES (:NEW.CODIGO_USUARIO,:NEW.GERA_LOG,:NEW.USA_JANELA_ACOMP,:NEW.DT_M_OPER_PROPRIO,:NEW.DATA_SISTEMA,:NEW.ANO_BASE,:NEW.USA_SAL_PRINCIPAL,:NEW.MODO_OPER_MOVI,:NEW.CTRL_OPER_AUXILIAR,:NEW.MODO_OPER_TSAL,:NEW.MODO_OPER_PONTO,:NEW.EMPR_TP_CONTR_PROP,:NEW.EMPRESA_SELEC,:NEW.TIPO_CONTR_SELEC,:NEW.LOGIN_USUARIO,SYSDATE,:NEW.ALT_MOV_LIQUIDO,:NEW.COD_PAD_CONTRATO,:NEW.MSG_PARA_ARQ_TEXTO,:NEW.EXIBE_IDENT_TABELA,:NEW.USA_DELIMIT_EXPORT,:NEW.DELIMITADOR_EXPORT,:NEW.EXPORT_NRO_REAL,:NEW.ALT_MV_PT_DT_RETRO,:NEW.USA_COD_ALTER_VERB,:NEW.CODIGO_GRUPO,:NEW.GRUPO_SEL_CONTRATO,:NEW.GRUPO_SEL_PESSOA,:NEW.COD_SEL_PESSOA,:NEW.GRUPO_SEL_CAND,:NEW.COD_SEL_CANDIDATO,:NEW.GRUPO_SEL_VERBA,:NEW.COD_SEL_VERBA,:NEW.ALT_PROPRIEDADES,:NEW.QTDE_MIN_ATIVO,:NEW.PERMITE_INCLUSAO,:NEW.PERMITE_EXCLUSAO,:NEW.PERMITE_ALTERACAO,:NEW.PERMITE_EXECUCAO,:NEW.GRUPO_SEL_UNID,:NEW.COD_SEL_UNID,:NEW.GRUPO_SEL_CCONT,:NEW.COD_SEL_CCONT,:NEW.GRUPO_SEL_CGER,:NEW.COD_SEL_CGER,:NEW.EMPRESA_USUARIO,:NEW.TP_CONTR_USUARIO,:NEW.CONTRATO_USUARIO,:NEW.PESSOA_USUARIO,:NEW.GRUPO_SEL_LOC,:NEW.COD_SEL_LOC,:NEW.USA_DT_MAQUINA,:NEW.CTRL_ATIVO,:NEW.NRO_MOD_SIMULT,:NEW.QTDE_REG_AUTO,:NEW.CONSISTE_LANC_VERB,:NEW.INSERE_LIQUIDO,:NEW.BLOQUEIA_CONTRATO,:NEW.BLOQUEIA_PESSOA,:NEW.EXIBE_DICA,:NEW.ALT_CONT_DT_RETRO,:NEW.ALT_PESS_DT_RETRO,:NEW.ALT_DATA_GERAL,:NEW.COD_PERIODO,:NEW.EDITA_SALARIO,:NEW.NATUR_PROC_SELEC,:NEW.GRUPO_SEGURANCA,:NEW.MENU_DEF_ENABLED,:NEW.MENU_DEF_VISIBLE,:NEW.SENHA_USUARIO,:NEW.STATUS_USUARIO,:NEW.DT_ULT_TROCA_SENHA,:NEW.CODIGO_SGBD_PADRAO,:NEW.DIAS_EXPIRA_SENHA,:NEW.PW_QTDE_POSIC,:NEW.PW_ALFANUM,:NEW.PW_SUBSET_USUA,:NEW.PW_QTDE_TENTA,:NEW.PW_COMECA_VOGAL,:NEW.APLIC_PROPRIEDADES,:NEW.NOME_USUARIO,:NEW.CODIGO_IDIOMA,:NEW.DIAS_EXP_SEM_ACESS,:NEW.DT_ULT_ACESSO,:NEW.CT_APLIC_PSEL_CONT,:NEW.CT_APLIC_PSEL_PESS,:NEW.C_LIVRE_SELEC01,:NEW.C_LIVRE_SELEC02,:NEW.C_LIVRE_SELEC03,:NEW.C_LIVRE_VALOR01,:NEW.C_LIVRE_VALOR02,:NEW.C_LIVRE_VALOR03,:NEW.C_LIVRE_DESCR01,:NEW.C_LIVRE_DESCR02,:NEW.C_LIVRE_DESCR03,:NEW.C_LIVRE_OPCAO01,:NEW.C_LIVRE_OPCAO02,:NEW.C_LIVRE_OPCAO03,:NEW.C_LIVRE_DATA01,:NEW.C_LIVRE_DATA02,:NEW.C_LIVRE_DATA03,:NEW.ALT_MOV_LIQ_AGRUP,:NEW.EXPAND_CAMINHO,:NEW.EDITA_GRUPO,:NEW.GRAVA_TEMPO_FORM,:NEW.MIN_TESTE_ESCALONA,:NEW.ACERTO_BASE_HIST,:NEW.MODULO_ACESSADO,:NEW.ALT_PONTO_DT_RETRO,:NEW.CTRL_ACESSO_IND,:NEW.APELIDO,:NEW.TIPO_AGRUP_USUARIO,:NEW.PERMITE_TPAGR_ESP,:NEW.DEPURA,:NEW.PW_SUBSET_NOME,:NEW.PW_DATAS_PESSOAIS,:NEW.PW_DOCS_PESSOAIS,:NEW.USUARIO_LDAP,:NEW.TIPO_LOGIN,:NEW.CODIGO_SERV_AUTENT,:NEW.INS_MOV_MEST_CONTR,:NEW.INS_MOV_MEST_AGRUP,:NEW.INS_MOV_MEST_VAGA,:NEW.ACESSA_OUTRO_USUA,:NEW.MODULO_ACES_WEB,:NEW.ESTACAO_REDE,:NEW.LOG_DETALHADO,:NEW.PERSISTE_ARG_SEL,:NEW.DATA_CRIACAO,:NEW.EXEC_INST_ESCALONA,:NEW.PERMITE_EFETIVAR_SQL,:NEW.CONTROLE_BPM,:NEW.ULTIMO_PERFIL_ACESSO_AZC,vTIPO_DML,vID,SYS_CONTEXT ('USERENV', 'OS_USER'));

  ELSIF DELETING THEN
      vTIPO_DML:= 'D';

      INSERT
      INTO RHPBH_RHUSER_P_SIST_AUDIT
      VALUES (:OLD.CODIGO_USUARIO,:OLD.GERA_LOG,:OLD.USA_JANELA_ACOMP,:OLD.DT_M_OPER_PROPRIO,:OLD.DATA_SISTEMA,:OLD.ANO_BASE,:OLD.USA_SAL_PRINCIPAL,:OLD.MODO_OPER_MOVI,:OLD.CTRL_OPER_AUXILIAR,:OLD.MODO_OPER_TSAL,:OLD.MODO_OPER_PONTO,:OLD.EMPR_TP_CONTR_PROP,:OLD.EMPRESA_SELEC,:OLD.TIPO_CONTR_SELEC,:OLD.LOGIN_USUARIO,SYSDATE,:OLD.ALT_MOV_LIQUIDO,:OLD.COD_PAD_CONTRATO,:OLD.MSG_PARA_ARQ_TEXTO,:OLD.EXIBE_IDENT_TABELA,:OLD.USA_DELIMIT_EXPORT,:OLD.DELIMITADOR_EXPORT,:OLD.EXPORT_NRO_REAL,:OLD.ALT_MV_PT_DT_RETRO,:OLD.USA_COD_ALTER_VERB,:OLD.CODIGO_GRUPO,:OLD.GRUPO_SEL_CONTRATO,:OLD.GRUPO_SEL_PESSOA,:OLD.COD_SEL_PESSOA,:OLD.GRUPO_SEL_CAND,:OLD.COD_SEL_CANDIDATO,:OLD.GRUPO_SEL_VERBA,:OLD.COD_SEL_VERBA,:OLD.ALT_PROPRIEDADES,:OLD.QTDE_MIN_ATIVO,:OLD.PERMITE_INCLUSAO,:OLD.PERMITE_EXCLUSAO,:OLD.PERMITE_ALTERACAO,:OLD.PERMITE_EXECUCAO,:OLD.GRUPO_SEL_UNID,:OLD.COD_SEL_UNID,:OLD.GRUPO_SEL_CCONT,:OLD.COD_SEL_CCONT,:OLD.GRUPO_SEL_CGER,:OLD.COD_SEL_CGER,:OLD.EMPRESA_USUARIO,:OLD.TP_CONTR_USUARIO,:OLD.CONTRATO_USUARIO,:OLD.PESSOA_USUARIO,:OLD.GRUPO_SEL_LOC,:OLD.COD_SEL_LOC,:OLD.USA_DT_MAQUINA,:OLD.CTRL_ATIVO,:OLD.NRO_MOD_SIMULT,:OLD.QTDE_REG_AUTO,:OLD.CONSISTE_LANC_VERB,:OLD.INSERE_LIQUIDO,:OLD.BLOQUEIA_CONTRATO,:OLD.BLOQUEIA_PESSOA,:OLD.EXIBE_DICA,:OLD.ALT_CONT_DT_RETRO,:OLD.ALT_PESS_DT_RETRO,:OLD.ALT_DATA_GERAL,:OLD.COD_PERIODO,:OLD.EDITA_SALARIO,:OLD.NATUR_PROC_SELEC,:OLD.GRUPO_SEGURANCA,:OLD.MENU_DEF_ENABLED,:OLD.MENU_DEF_VISIBLE,:OLD.SENHA_USUARIO,:OLD.STATUS_USUARIO,:OLD.DT_ULT_TROCA_SENHA,:OLD.CODIGO_SGBD_PADRAO,:OLD.DIAS_EXPIRA_SENHA,:OLD.PW_QTDE_POSIC,:OLD.PW_ALFANUM,:OLD.PW_SUBSET_USUA,:OLD.PW_QTDE_TENTA,:OLD.PW_COMECA_VOGAL,:OLD.APLIC_PROPRIEDADES,:OLD.NOME_USUARIO,:OLD.CODIGO_IDIOMA,:OLD.DIAS_EXP_SEM_ACESS,:OLD.DT_ULT_ACESSO,:OLD.CT_APLIC_PSEL_CONT,:OLD.CT_APLIC_PSEL_PESS,:OLD.C_LIVRE_SELEC01,:OLD.C_LIVRE_SELEC02,:OLD.C_LIVRE_SELEC03,:OLD.C_LIVRE_VALOR01,:OLD.C_LIVRE_VALOR02,:OLD.C_LIVRE_VALOR03,:OLD.C_LIVRE_DESCR01,:OLD.C_LIVRE_DESCR02,:OLD.C_LIVRE_DESCR03,:OLD.C_LIVRE_OPCAO01,:OLD.C_LIVRE_OPCAO02,:OLD.C_LIVRE_OPCAO03,:OLD.C_LIVRE_DATA01,:OLD.C_LIVRE_DATA02,:OLD.C_LIVRE_DATA03,:OLD.ALT_MOV_LIQ_AGRUP,:OLD.EXPAND_CAMINHO,:OLD.EDITA_GRUPO,:OLD.GRAVA_TEMPO_FORM,:OLD.MIN_TESTE_ESCALONA,:OLD.ACERTO_BASE_HIST,:OLD.MODULO_ACESSADO,:OLD.ALT_PONTO_DT_RETRO,:OLD.CTRL_ACESSO_IND,:OLD.APELIDO,:OLD.TIPO_AGRUP_USUARIO,:OLD.PERMITE_TPAGR_ESP,:OLD.DEPURA,:OLD.PW_SUBSET_NOME,:OLD.PW_DATAS_PESSOAIS,:OLD.PW_DOCS_PESSOAIS,:OLD.USUARIO_LDAP,:OLD.TIPO_LOGIN,:OLD.CODIGO_SERV_AUTENT,:OLD.INS_MOV_MEST_CONTR,:OLD.INS_MOV_MEST_AGRUP,:OLD.INS_MOV_MEST_VAGA,:OLD.ACESSA_OUTRO_USUA,:OLD.MODULO_ACES_WEB,:OLD.ESTACAO_REDE,:OLD.LOG_DETALHADO,:OLD.PERSISTE_ARG_SEL,:OLD.DATA_CRIACAO,:OLD.EXEC_INST_ESCALONA,:OLD.PERMITE_EFETIVAR_SQL,:OLD.CONTROLE_BPM,:OLD.ULTIMO_PERFIL_ACESSO_AZC,vTIPO_DML,vID,SYS_CONTEXT ('USERENV', 'OS_USER'));        

  END IF;
/* ------------------------------------------------------------- FIM SALVA LOG --------------------------------------------------------*/



    IF INSERTING OR UPDATING THEN
     -- dbms_output.put_line('EXECUTANDO PROCEDURE 1'||TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS')||:NEW.EMPRESA_USUARIO||:NEW.CONTRATO_USUARIO|| :NEW.TP_CONTR_USUARIO||:NEW.CODIGO_USUARIO||:NEW.STATUS_USUARIO||:NEW.CODIGO_SGBD_PADRAO);
      SMARH_USER_P_SIST (:NEW.EMPRESA_USUARIO, :NEW.CONTRATO_USUARIO, :NEW.TP_CONTR_USUARIO,:NEW.CODIGO_USUARIO,:NEW.STATUS_USUARIO, :NEW.CODIGO_SGBD_PADRAO);
     ELSIF DELETING THEN    
    -- REALIZAR A EXCLUSAO DO LOGIN NAS LISTAS DE CONVERSÃO DE: LOGINS QUE NUNCA FECHAM(US20) E TROCA DE GRUPO DE USUARIO(US07)
      DELETE FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'US07' AND DADO_ORIGEM = :OLD.CODIGO_USUARIO ;
      DELETE FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'US20' AND DADO_ORIGEM = :OLD.CODIGO_USUARIO;
    END IF;

 /*   
    IF DELETING THEN    
    -- REALIZAR A EXCLUSAO DO LOGIN NAS LISTAS DE CONVERSÃO DE: LOGINS QUE NUNCA FECHAM(US20) E TROCA DE GRUPO DE USUARIO(US07)
      DELETE FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'US07' AND DADO_ORIGEM = :OLD.CODIGO_USUARIO ;
      DELETE FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'US20' AND DADO_ORIGEM = :OLD.CODIGO_USUARIO;
    END IF;
*/
END AFTER EACH ROW;



AFTER STATEMENT IS
 BEGIN

       IF INSERTING OR UPDATING THEN
         FOR indx IN 1 .. LINHA_info.COUNT
            LOOP
            SMARH_USER_P_SIST_A ( LINHA_info(indx).CODIGO_USUARIO, LINHA_info(indx).EMPRESA_SELEC ,LINHA_info(indx).TIPO_CONTR_SELEC,LINHA_info(indx).STATUS_USUARIO, LINHA_info(indx).CODIGO_SGBD_PADRAO);
             -- dbms_output.put_line(indx||TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'));
                 -- dbms_output.put_line('EXECUTANDO PROCEDURE 2'|| LINHA_info(indx).CODIGO_USUARIO||LINHA_info(indx).EMPRESA_SELEC||LINHA_info(indx).TIPO_CONTR_SELEC||LINHA_info(indx).STATUS_USUARIO||LINHA_info(indx).CODIGO_SGBD_PADRAO);

          END LOOP;
      END IF;
END AFTER STATEMENT;
END ;

ALTER TRIGGER "ARTERH"."TR_RHUSER_P_SIST" ENABLE