
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RESSITDIA_AUDITO" 
AFTER INSERT OR UPDATE OR DELETE ON "ARTERH"."RHPONT_RES_SIT_DIA"
FOR EACH ROW
 DECLARE
v_DML SMARH_INT_PE_RESSITDIA_AUDITO.TIPO_DML%TYPE;

vLOGIN_USUARIO_NEW VARCHAR2(40);
vLOGIN_USUARIO_OLD VARCHAR2(40);
vLOGIN_OS_NEW VARCHAR2(40);
vLOGIN_OS_OLD VARCHAR2(40);
vLOGIN_NEW VARCHAR2(40);
vLOGIN_OLD VARCHAR2(40);

BEGIN

vLOGIN_USUARIO_NEW := :NEW.LOGIN_USUARIO;
vLOGIN_USUARIO_OLD := :OLD.LOGIN_USUARIO;
vLOGIN_OS_NEW := SYS_CONTEXT ('USERENV', 'OS_USER');
vLOGIN_OS_OLD := SYS_CONTEXT ('USERENV', 'OS_USER');
vLOGIN_NEW := NULL;
vLOGIN_OLD := NULL;

--definir login a usar NEW
    IF vLOGIN_USUARIO_NEW = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_NEW;
    ELSE 
    vLOGIN_NEW := vLOGIN_USUARIO_NEW;
    END IF;

--definir login a usar OLD
    IF vLOGIN_USUARIO_OLD = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_OLD;
    ELSE 
    vLOGIN_OLD := vLOGIN_USUARIO_OLD;
    END IF;

-------------------------------inicio----------------------grava tabela de log
IF INSERTING THEN 
v_DML := 'I';
INSERT INTO SMARH_INT_PE_RESSITDIA_AUDITO
(
ID,
TIPO_DML,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
DATA,
CODIGO_SITUACAO,
NEW_REF_HORAS,
LOGIN_USUARIO,
--OLD_LOGIN_USUARIO,
--OLD_DT_ULT_ALTER_USUA,
--NEW_LOGIN_USUARIO,
--NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
TIPO_APURACAO,
COD_NOVA_SITUACAO,
FORCA_SITUACAO,
MOTIVO_HISTORICO,
REF_HORAS_ABONADAS,
REF_HORAS_NOVA_SIT,
TEXTO_ASSOCIADO
)
VALUES
(
ARTERH.SEQUENCE_SITPONTO.NEXTVAL,--ate 20/1/20(SELECT MAX(ID)+1 FROM SMARH_INT_PE_RESSITDIA_AUDITO),
v_DML,
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO,
:NEW.DATA,
:NEW.CODIGO_SITUACAO,
:NEW.REF_HORAS,
--:OLD.LOGIN_USUARIO,
--:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,--USER,
--:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
:NEW.TIPO_APURACAO,
:NEW.COD_NOVA_SITUACAO,
:NEW.FORCA_SITUACAO,
:NEW.MOTIVO_HISTORICO,
:NEW.REF_HORAS_ABONADAS,
:NEW.REF_HORAS_NOVA_SIT,
:NEW.TEXTO_ASSOCIADO
);

ELSIF UPDATING THEN
v_DML := 'U';
INSERT INTO SMARH_INT_PE_RESSITDIA_AUDITO
(
ID,
TIPO_DML,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
DATA,
CODIGO_SITUACAO,
NEW_REF_HORAS,
OLD_REF_HORAS,
LOGIN_USUARIO,
--OLD_LOGIN_USUARIO,
--OLD_DT_ULT_ALTER_USUA,
--NEW_LOGIN_USUARIO,
--NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
TIPO_APURACAO,
COD_NOVA_SITUACAO,
FORCA_SITUACAO,
MOTIVO_HISTORICO,
REF_HORAS_ABONADAS,
REF_HORAS_NOVA_SIT,
TEXTO_ASSOCIADO
)
VALUES
(
ARTERH.SEQUENCE_SITPONTO.NEXTVAL,--ate 20/1/20(SELECT MAX(ID)+1 FROM SMARH_INT_PE_RESSITDIA_AUDITO),
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO,
:OLD.DATA,
:OLD.CODIGO_SITUACAO,
:NEW.REF_HORAS,
:OLD.REF_HORAS,
--:OLD.LOGIN_USUARIO,
--:OLD.DT_ULT_ALTER_USUA,
--:NEW.LOGIN_USUARIO,--USER,
:NEW.LOGIN_USUARIO,--USER,
--:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
:NEW.TIPO_APURACAO,
:NEW.COD_NOVA_SITUACAO,
:NEW.FORCA_SITUACAO,
:NEW.MOTIVO_HISTORICO,
:NEW.REF_HORAS_ABONADAS,
:NEW.REF_HORAS_NOVA_SIT,
:NEW.TEXTO_ASSOCIADO
);

ELSIF DELETING THEN
v_DML := 'D';
INSERT INTO SMARH_INT_PE_RESSITDIA_AUDITO
(
ID,
TIPO_DML,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
DATA,
CODIGO_SITUACAO,
OLD_REF_HORAS,
LOGIN_USUARIO,
--OLD_LOGIN_USUARIO,
--OLD_DT_ULT_ALTER_USUA,
--NEW_LOGIN_USUARIO,
--NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
TIPO_APURACAO,
COD_NOVA_SITUACAO,
FORCA_SITUACAO,
MOTIVO_HISTORICO,
REF_HORAS_ABONADAS,
REF_HORAS_NOVA_SIT,
TEXTO_ASSOCIADO
)
VALUES
(
ARTERH.SEQUENCE_SITPONTO.NEXTVAL,--ate 20/1/20(SELECT MAX(ID)+1 FROM SMARH_INT_PE_RESSITDIA_AUDITO),
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO,
:OLD.DATA,
:OLD.CODIGO_SITUACAO,
:OLD.REF_HORAS,
--:OLD.LOGIN_USUARIO,
--:OLD.DT_ULT_ALTER_USUA,
vLOGIN_OLD,
--:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
:OLD.TIPO_APURACAO,
:OLD.COD_NOVA_SITUACAO,
:OLD.FORCA_SITUACAO,
:OLD.MOTIVO_HISTORICO,
:OLD.REF_HORAS_ABONADAS,
:OLD.REF_HORAS_NOVA_SIT,
:OLD.TEXTO_ASSOCIADO
);




END IF;
-------------------------------fim----------------------grava tabela de log


--CHAMAR PROCEDURE PARA TODA LOGICA NO NOVO CENARIO TABELA RHPONT_RES_SIT_DIA
--SUGESP_RES_SIT_DIA('ALT_SIT_FUNC', 398);


END;





ALTER TRIGGER "ARTERH"."TR_RESSITDIA_AUDITO" ENABLE