
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RHTEMP_DESAVERB_AUDIT" 
AFTER UPDATE OR DELETE OR INSERT ON "ARTERH"."RHTEMP_DESAVERB" 
FOR EACH ROW
 DECLARE
v_DML RHPBH_RHTEMP_DESAVERB_AUDIT.TIPO_DML%TYPE;
BEGIN
IF INSERTING THEN
v_DML := 'I';
INSERT INTO RHPBH_RHTEMP_DESAVERB_AUDIT
(
TIPO_DML,
CODIGO_EMPRESA,
CODIGO_PESSOA,
OCORRENCIA,
DATA_INI_DESAVERB,
DATA_FIM_DESAVERB,
MOTIV_DESAVERBACAO,
DIAS,
MESES,
ANOS,
DIAS_LIQUIDO,
DIAS_FALTA_ACUMUL,
PROCESSO,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR01,
C_LIVRE_VALOR02,
C_LIVRE_VALOR03,
C_LIVRE_DATA01,
C_LIVRE_DATA02,
C_LIVRE_DATA03,
C_LIVRE_DESCR01,
C_LIVRE_DESCR02,
C_LIVRE_DESCR03,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
DATA_EMISSAO,
TIPO_CONTRATO,
CODIGO_CONTRATO
)
VALUES
(
v_DML,
:NEW.CODIGO_EMPRESA,
:NEW.CODIGO_PESSOA,
:NEW.OCORRENCIA,
:NEW.DATA_INI_DESAVERB,
:NEW.DATA_FIM_DESAVERB,
:NEW.MOTIV_DESAVERBACAO,
:NEW.DIAS,
:NEW.MESES,
:NEW.ANOS,
:NEW.DIAS_LIQUIDO,
:NEW.DIAS_FALTA_ACUMUL,
:NEW.PROCESSO,
:NEW.C_LIVRE_SELEC01,
:NEW.C_LIVRE_SELEC02,
:NEW.C_LIVRE_SELEC03,
:NEW.C_LIVRE_VALOR01,
:NEW.C_LIVRE_VALOR02,
:NEW.C_LIVRE_VALOR03,
:NEW.C_LIVRE_DATA01,
:NEW.C_LIVRE_DATA02,
:NEW.C_LIVRE_DATA03,
:NEW.C_LIVRE_DESCR01,
:NEW.C_LIVRE_DESCR02,
:NEW.C_LIVRE_DESCR03,
USER,
SYSDATE,
:NEW.DATA_EMISSAO,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO
);
GRAVA_MODULO_APOSENT(:NEW.CODIGO_CONTRATO,'RHTEMP_DESAVERB',:NEW.TIPO_CONTRATO, :NEW.CODIGO_EMPRESA, NULL,NULL,NULL,NULL,NULL,NULL,NULL,:NEW.DATA_INI_DESAVERB,NULL,NULL,NULL,NULL);
END IF;

IF DELETING THEN
v_DML := 'D';
INSERT INTO RHPBH_RHTEMP_DESAVERB_AUDIT
(
TIPO_DML,
CODIGO_EMPRESA,
CODIGO_PESSOA,
OCORRENCIA,
DATA_INI_DESAVERB,
DATA_FIM_DESAVERB,
MOTIV_DESAVERBACAO,
DIAS,
MESES,
ANOS,
DIAS_LIQUIDO,
DIAS_FALTA_ACUMUL,
PROCESSO,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR01,
C_LIVRE_VALOR02,
C_LIVRE_VALOR03,
C_LIVRE_DATA01,
C_LIVRE_DATA02,
C_LIVRE_DATA03,
C_LIVRE_DESCR01,
C_LIVRE_DESCR02,
C_LIVRE_DESCR03,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
DATA_EMISSAO,
TIPO_CONTRATO,
CODIGO_CONTRATO
)
VALUES
(
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.CODIGO_PESSOA,
:OLD.OCORRENCIA,
:OLD.DATA_INI_DESAVERB,
:OLD.DATA_FIM_DESAVERB,
:OLD.MOTIV_DESAVERBACAO,
:OLD.DIAS,
:OLD.MESES,
:OLD.ANOS,
:OLD.DIAS_LIQUIDO,
:OLD.DIAS_FALTA_ACUMUL,
:OLD.PROCESSO,
:OLD.C_LIVRE_SELEC01,
:OLD.C_LIVRE_SELEC02,
:OLD.C_LIVRE_SELEC03,
:OLD.C_LIVRE_VALOR01,
:OLD.C_LIVRE_VALOR02,
:OLD.C_LIVRE_VALOR03,
:OLD.C_LIVRE_DATA01,
:OLD.C_LIVRE_DATA02,
:OLD.C_LIVRE_DATA03,
:OLD.C_LIVRE_DESCR01,
:OLD.C_LIVRE_DESCR02,
:OLD.C_LIVRE_DESCR03,
USER,
SYSDATE,
:OLD.DATA_EMISSAO,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO
);
GRAVA_MODULO_APOSENT(:OLD.CODIGO_CONTRATO,'RHTEMP_DESAVERB',:OLD.TIPO_CONTRATO, :OLD.CODIGO_EMPRESA, NULL,NULL,NULL,NULL,NULL,NULL,NULL,:OLD.DATA_INI_DESAVERB,NULL,NULL,NULL,NULL);

END IF;

IF UPDATING THEN
v_DML := 'U';
INSERT INTO RHPBH_RHTEMP_DESAVERB_AUDIT
(
TIPO_DML,
CODIGO_EMPRESA,
CODIGO_PESSOA,
OCORRENCIA,
DATA_INI_DESAVERB,
DATA_FIM_DESAVERB,
MOTIV_DESAVERBACAO,
DIAS,
MESES,
ANOS,
DIAS_LIQUIDO,
DIAS_FALTA_ACUMUL,
PROCESSO,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR01,
C_LIVRE_VALOR02,
C_LIVRE_VALOR03,
C_LIVRE_DATA01,
C_LIVRE_DATA02,
C_LIVRE_DATA03,
C_LIVRE_DESCR01,
C_LIVRE_DESCR02,
C_LIVRE_DESCR03,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
DATA_EMISSAO,
TIPO_CONTRATO,
CODIGO_CONTRATO
)
VALUES
(
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.CODIGO_PESSOA,
:OLD.OCORRENCIA,
:OLD.DATA_INI_DESAVERB,
:OLD.DATA_FIM_DESAVERB,
:OLD.MOTIV_DESAVERBACAO,
:OLD.DIAS,
:OLD.MESES,
:OLD.ANOS,
:OLD.DIAS_LIQUIDO,
:OLD.DIAS_FALTA_ACUMUL,
:OLD.PROCESSO,
:OLD.C_LIVRE_SELEC01,
:OLD.C_LIVRE_SELEC02,
:OLD.C_LIVRE_SELEC03,
:OLD.C_LIVRE_VALOR01,
:OLD.C_LIVRE_VALOR02,
:OLD.C_LIVRE_VALOR03,
:OLD.C_LIVRE_DATA01,
:OLD.C_LIVRE_DATA02,
:OLD.C_LIVRE_DATA03,
:OLD.C_LIVRE_DESCR01,
:OLD.C_LIVRE_DESCR02,
:OLD.C_LIVRE_DESCR03,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
:OLD.DATA_EMISSAO,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO
);
GRAVA_MODULO_APOSENT(:OLD.CODIGO_CONTRATO,'RHTEMP_DESAVERB',:OLD.TIPO_CONTRATO, :OLD.CODIGO_EMPRESA, NULL,NULL,NULL,NULL,NULL,NULL,NULL,:OLD.DATA_INI_DESAVERB,NULL,NULL,NULL,NULL);

END IF;

END;




ALTER TRIGGER "ARTERH"."TR_RHTEMP_DESAVERB_AUDIT" ENABLE