
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_RHTEMP_PARAMETRO_AUDIT" 
AFTER UPDATE OR DELETE OR INSERT ON "ARTERH"."RHTEMP_PARAMETRO" 
FOR EACH ROW
 DECLARE
v_DML RHPBH_RHTEMP_PARAMETRO_AUDIT.TIPO_DML%TYPE;
BEGIN
IF INSERTING THEN
v_DML := 'I';
INSERT INTO RHPBH_RHTEMP_PARAMETRO_AUDIT
(
TIPO_DML,
C_LIVRE_DATA07,
C_LIVRE_DATA08,
C_LIVRE_DATA09,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR04,
C_LIVRE_VALOR05,
C_LIVRE_VALOR06,
CODIGO_EMPRESA,
DATA_FIM_CONTAGEM,
DATA_INI_CONTAGEM,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
MODULO_DV_PROCESSO
)
VALUES
(
v_DML,
:NEW.C_LIVRE_DATA07,
:NEW.C_LIVRE_DATA08,
:NEW.C_LIVRE_DATA09,
:NEW.C_LIVRE_SELEC01,
:NEW.C_LIVRE_SELEC02,
:NEW.C_LIVRE_SELEC03,
:NEW.C_LIVRE_VALOR04,
:NEW.C_LIVRE_VALOR05,
:NEW.C_LIVRE_VALOR06,
:NEW.CODIGO_EMPRESA,
:NEW.DATA_FIM_CONTAGEM,
:NEW.DATA_INI_CONTAGEM,
SYSDATE,
USER,
:NEW.MODULO_DV_PROCESSO
);
END IF;

IF DELETING THEN
v_DML := 'D';
INSERT INTO RHPBH_RHTEMP_PARAMETRO_AUDIT
(
TIPO_DML,
C_LIVRE_DATA07,
C_LIVRE_DATA08,
C_LIVRE_DATA09,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR04,
C_LIVRE_VALOR05,
C_LIVRE_VALOR06,
CODIGO_EMPRESA,
DATA_FIM_CONTAGEM,
DATA_INI_CONTAGEM,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
MODULO_DV_PROCESSO
)
VALUES
(
v_DML,
:OLD.C_LIVRE_DATA07,
:OLD.C_LIVRE_DATA08,
:OLD.C_LIVRE_DATA09,
:OLD.C_LIVRE_SELEC01,
:OLD.C_LIVRE_SELEC02,
:OLD.C_LIVRE_SELEC03,
:OLD.C_LIVRE_VALOR04,
:OLD.C_LIVRE_VALOR05,
:OLD.C_LIVRE_VALOR06,
:OLD.CODIGO_EMPRESA,
:OLD.DATA_FIM_CONTAGEM,
:OLD.DATA_INI_CONTAGEM,
SYSDATE,
USER,
:OLD.MODULO_DV_PROCESSO
);
END IF;

IF UPDATING THEN
v_DML := 'U';
INSERT INTO RHPBH_RHTEMP_PARAMETRO_AUDIT
(
TIPO_DML,
C_LIVRE_DATA07,
C_LIVRE_DATA08,
C_LIVRE_DATA09,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_VALOR04,
C_LIVRE_VALOR05,
C_LIVRE_VALOR06,
CODIGO_EMPRESA,
DATA_FIM_CONTAGEM,
DATA_INI_CONTAGEM,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
MODULO_DV_PROCESSO
)
VALUES
(
v_DML,
:OLD.C_LIVRE_DATA07,
:OLD.C_LIVRE_DATA08,
:OLD.C_LIVRE_DATA09,
:OLD.C_LIVRE_SELEC01,
:OLD.C_LIVRE_SELEC02,
:OLD.C_LIVRE_SELEC03,
:OLD.C_LIVRE_VALOR04,
:OLD.C_LIVRE_VALOR05,
:OLD.C_LIVRE_VALOR06,
:OLD.CODIGO_EMPRESA,
:OLD.DATA_FIM_CONTAGEM,
:OLD.DATA_INI_CONTAGEM,
:NEW.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:OLD.MODULO_DV_PROCESSO
);

END IF;

END;




ALTER TRIGGER "ARTERH"."TR_RHTEMP_PARAMETRO_AUDIT" ENABLE