
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_STATUS_FERI_FERIAS" FOR UPDATE OR
  INSERT OF STATUS_CONFIRMACAO ON ARTERH.RHFERI_FERIAS  COMPOUND TRIGGER TYPE id_pessoa IS RECORD ( DT_INI_AQUISICAO RHFERI_FERIAS.DT_INI_AQUISICAO%TYPE, TIPO_FERIAS RHFERI_FERIAS.TIPO_FERIAS%TYPE, PERIODO RHFERI_FERIAS.PERIODO%TYPE ,CODIGO_EMPRESA RHFERI_FERIAS.CODIGO_EMPRESA%TYPE, CODIGO_CONTRATO RHFERI_FERIAS.CODIGO_CONTRATO%TYPE ,TIPO_CONTRATO RHFERI_FERIAS.TIPO_CONTRATO%TYPE, NEW_STATUS_CONFIRMACAO RHFERI_FERIAS.STATUS_CONFIRMACAO%TYPE,OLD_STATUS_CONFIRMACAO RHFERI_FERIAS.STATUS_CONFIRMACAO%TYPE );
TYPE LINHA
IS 
  TABLE OF id_pessoa INDEX BY PLS_INTEGER;
  LINHA_info LINHA;
  AFTER EACH ROW
IS
BEGIN
  LINHA_info(LINHA_info.COUNT + 1).CODIGO_EMPRESA     := :NEW.CODIGO_EMPRESA;
  LINHA_info(LINHA_info.COUNT ).DT_INI_AQUISICAO   := :NEW.DT_INI_AQUISICAO;
  LINHA_info(LINHA_info.COUNT ).TIPO_FERIAS            := :NEW.TIPO_FERIAS;
  LINHA_info(LINHA_info.COUNT ).PERIODO            := :NEW.PERIODO;
  LINHA_info(LINHA_info.COUNT ).CODIGO_CONTRATO        := :NEW.CODIGO_CONTRATO;
  LINHA_info(LINHA_info.COUNT ).TIPO_CONTRATO          := :NEW.TIPO_CONTRATO;
  LINHA_info(LINHA_info.COUNT ).NEW_STATUS_CONFIRMACAO := :NEW.STATUS_CONFIRMACAO;
  LINHA_info(LINHA_info.COUNT ).OLD_STATUS_CONFIRMACAO := :OLD.STATUS_CONFIRMACAO;
END AFTER EACH ROW;


AFTER STATEMENT
IS
BEGIN

  FOR indx IN 1 .. LINHA_info.COUNT
  LOOP
  IF ( LINHA_info(indx).NEW_STATUS_CONFIRMACAO IN ('L','M') and LINHA_info(indx).CODIGO_EMPRESA = '0001' )THEN 
    UPDATE ARTERH.RHFERI_FERIAS
    SET STATUS_CONFIRMACAO = '0' , PROCESSO = NULL
    WHERE TRUNC(DT_INI_AQUISICAO) = TRUNC(LINHA_info(indx).DT_INI_AQUISICAO)
    AND TIPO_FERIAS        = LINHA_info(indx).TIPO_FERIAS
    AND PERIODO            = LINHA_info(indx).PERIODO
    AND CODIGO_EMPRESA     = LINHA_info(indx).CODIGO_EMPRESA
    AND TIPO_CONTRATO      = LINHA_info(indx).TIPO_CONTRATO
    AND CODIGO_CONTRATO    = LINHA_info(indx).CODIGO_CONTRATO
    AND STATUS_CONFIRMACAO = LINHA_info(indx).NEW_STATUS_CONFIRMACAO ;
     END IF;
  END LOOP;

END AFTER STATEMENT;
END tr_STATUS_FERI_FERIAS;



ALTER TRIGGER "ARTERH"."TR_STATUS_FERI_FERIAS" ENABLE