
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_SUGESP_RHMEDI_RL_FICH_DOE" 
AFTER INSERT OR UPDATE OR DELETE ON "ARTERH"."RHMEDI_RL_FICH_DOE" 
FOR EACH ROW
 DECLARE
v_DML SUGESP_FICHAS_MEDICAS.TIPO_DML%TYPE;

vID NUMBER;
vTIPO_DML VARCHAR2(1);
vTABELA VARCHAR2(30);
    vLOGIN_USUARIO_NEW VARCHAR2(40);
    vLOGIN_USUARIO_OLD VARCHAR2(40);
    vLOGIN_OS_NEW VARCHAR2(40);
    vLOGIN_OS_OLD VARCHAR2(40);
    vLOGIN_NEW VARCHAR2(40);
    vLOGIN_OLD VARCHAR2(40);

vULT_ID NUMBER;

--vNEW_C_LIVRE_OPCAO01 VARCHAR2(40);
--vOLD_C_LIVRE_OPCAO01 VARCHAR2(40 BYTE);
--vNEW_C_LIVRE_DESCR02 VARCHAR2(1 BYTE);
--vOLD_C_LIVRE_DESCR02 VARCHAR2(1 BYTE);
--vNEW_QTD_DOENCA NUMBER;
--vOLD_QTD_DOENCA NUMBER;


BEGIN

vTABELA := 'RHMEDI_RL_FICH_DOE';

    vLOGIN_USUARIO_NEW := :NEW.LOGIN_USUARIO;
    vLOGIN_USUARIO_OLD := :OLD.LOGIN_USUARIO;
    vLOGIN_OS_NEW := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_OS_OLD := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_NEW := NULL;
    vLOGIN_OLD := NULL;

--vNEW_C_LIVRE_OPCAO01 := NULL;
--vOLD_C_LIVRE_OPCAO01 := NULL;
--vNEW_C_LIVRE_DESCR02 := NULL;
--vOLD_C_LIVRE_DESCR02 := NULL;
--vNEW_QTD_DOENCA := NULL;
--vOLD_QTD_DOENCA := NULL;


--definir login a usar NEW
    IF vLOGIN_USUARIO_NEW = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_NEW;
    ELSE 
    vLOGIN_NEW := vLOGIN_USUARIO_NEW;
    END IF;

--definir login a usar OLD
    IF vLOGIN_USUARIO_OLD = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_OLD;
    ELSE 
    vLOGIN_OLD := vLOGIN_USUARIO_OLD;
    END IF;

vULT_ID := 0;       
--------------------------------------------------------------------------INSERT-------------------------------------------------------------------------------------------------------------------------------------------
IF INSERTING THEN 
v_DML := 'I';

/*
--PEGA CAMPOS LIVRES DOENCA
SELECT DOE.C_LIVRE_OPCAO01, DOE.C_LIVRE_DESCR02
INTO vNEW_C_LIVRE_OPCAO01, vNEW_C_LIVRE_DESCR02
FROM 
RHMEDI_RL_FICH_DOE D 
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
WHERE D.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND D.CODIGO_PESSOA = :NEW.CODIGO_PESSOA  AND D.DT_REG_OCORRENCIA =:NEW.DT_REG_OCORRENCIA AND D.OCORRENCIA = :NEW.OCORRENCIA;

--CONTA DOENCAS NA FICHA
SELECT COUNT(1)QUANT 
INTO vNEW_QTD_DOENCA
FROM RHMEDI_RL_FICH_DOE D 
WHERE D.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND D.CODIGO_PESSOA = :NEW.CODIGO_PESSOA  AND D.DT_REG_OCORRENCIA = :NEW.DT_REG_OCORRENCIA AND D.OCORRENCIA = :NEW.OCORRENCIA;
*/
INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
CODIGO_PESSOA,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
--,NEW_C_LIVRE_OPCAO01, 
--NEW_C_LIVRE_DESCR02,
--NEW_QTD_DOENCA
)
VALUES
(ARTERH.SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:NEW.CODIGO_EMPRESA,
:NEW.CODIGO_PESSOA,
:NEW.DT_REG_OCORRENCIA,
:NEW.OCORRENCIA,
:NEW.OCOR_DOENCA,
NULL,
:NEW.COD_DOENCA,
NULL,
SYSDATE,
vLOGIN_NEW,
vLOGIN_NEW
,'N'
--,vNEW_C_LIVRE_OPCAO01,
--vNEW_C_LIVRE_DESCR02,
--vNEW_QTD_DOENCA
);
--------------------------------------------------------------------------UPDATE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF UPDATING THEN
v_DML := 'U';

INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
CODIGO_PESSOA,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
)
VALUES
(ARTERH.SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:NEW.CODIGO_EMPRESA,
:NEW.CODIGO_PESSOA,
:NEW.DT_REG_OCORRENCIA,
:NEW.OCORRENCIA,
:NEW.OCOR_DOENCA,
:OLD.OCOR_DOENCA,
:NEW.COD_DOENCA,
:OLD.COD_DOENCA,
SYSDATE,
vLOGIN_NEW,
vLOGIN_OLD
,'N'
);
--------------------------------------------------------------------------DELETE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF DELETING THEN
v_DML := 'D';

INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
CODIGO_PESSOA,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
)
VALUES
(ARTERH.SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:OLD.CODIGO_EMPRESA,
:OLD.CODIGO_PESSOA,
:OLD.DT_REG_OCORRENCIA,
:OLD.OCORRENCIA,
NULL,
:OLD.OCOR_DOENCA,
NULL,
:OLD.COD_DOENCA,
SYSDATE,
vLOGIN_OLD,
vLOGIN_OLD
,'N'
);

END IF;

--------------------------------------------------------------------------------CHAMAR PROCEDURE DE FICHAS MEDICAS E FILHAS
--select ID into vULT_ID FROM SUGESP_FICHAS_MEDICAS WHERE ID = (SELECT MAX(ID) FROM SUGESP_FICHAS_MEDICAS);
--PR_SUGESP_FICHAS_MEDICAS('RHMEDI_RL_FICH_DOE', vULT_ID);
--------------------------------------------------------------------------------CHAMAR PROCEDURE DE FICHAS MEDICAS E FILHAS

END;
ALTER TRIGGER "ARTERH"."TR_SUGESP_RHMEDI_RL_FICH_DOE" ENABLE