
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_SUGESP_RHMEDI_FICHA_MED" 
AFTER INSERT OR UPDATE OR DELETE ON "ARTERH"."RHMEDI_FICHA_MED"   
FOR EACH ROW

DECLARE
v_DML SUGESP_FICHAS_MEDICAS.TIPO_DML%TYPE;

vID NUMBER;
vTIPO_DML VARCHAR2(1);
vTABELA VARCHAR2(30);
vCODIGO_EMPRESA VARCHAR2(4);
vTIPO_CONTRATO VARCHAR2(4);
vCODIGO_CONTRATO VARCHAR2(15);
vCODIGO_PESSOA VARCHAR2(15);
vNEW_COD_SIT_FUNCIONAL VARCHAR2(4);
vOLD_COD_SIT_FUNCIONAL VARCHAR2(4);
vDT_REG_OCORRENCIA DATE;
vOCORRENCIA NUMBER;
vNEW_NATUREZA_EXAME VARCHAR2(4);
vOLD_NATUREZA_EXAME VARCHAR2(4);
vNEW_DATA_INI_AFAST DATE;
vOLD_DATA_INI_AFAST DATE;
vNEW_DATA_FIM_AFAST DATE;
vOLD_DATA_FIM_AFAST DATE;
vNEW_DATA_INICIAL_INDEFERIMENT DATE;
vOLD_DATA_INICIAL_INDEFERIMENT DATE;
vNEW_DATA_FINAL_INDEFERIMENTO DATE;
vOLD_DATA_FINAL_INDEFERIMENTO DATE;
vNEW_OCOR_PROC_MED NUMBER;
vOLD_OCOR_PROC_MED NUMBER;
vNEW_CODIGO_PROC_MED VARCHAR2(15);
vOLD_CODIGO_PROC_MED VARCHAR2(15);
vNEW_OCOR_DOENCA NUMBER;
vOLD_OCOR_DOENCA NUMBER;
vNEW_COD_DOENCA VARCHAR2(15);
vOLD_COD_DOENCA VARCHAR2(15);
vDT_ULT_ALTER_USUA DATE;
    vLOGIN_USUARIO_NEW VARCHAR2(40);
    vLOGIN_USUARIO_OLD VARCHAR2(40);
    vLOGIN_OS_NEW VARCHAR2(40);
    vLOGIN_OS_OLD VARCHAR2(40);
    vLOGIN_NEW VARCHAR2(40);
    vLOGIN_OLD VARCHAR2(40);

vULT_ID NUMBER;

vNEW_EMPRESA_ATENDENTE VARCHAR2(4);
vOLD_EMPRESA_ATENDENTE VARCHAR2(4);
vNEW_CODIGO_ATENDENTE VARCHAR2(15);
vOLD_CODIGO_ATENDENTE VARCHAR2(15);
vNEW_NOME_ATENDENTE VARCHAR2(70);
vOLD_NOME_ATENDENTE VARCHAR2(70);
vNEW_INSCRICAO_CONSELHO VARCHAR2(30);
vOLD_INSCRICAO_CONSELHO VARCHAR2(30);
vNEW_UF_INSCRICAO VARCHAR2(4);
vOLD_UF_INSCRICAO VARCHAR2(4);
vNEW_CONSELHO_REGIONAL VARCHAR2(4);
vOLD_CONSELHO_REGIONAL VARCHAR2(4);

vNEW_INFO_MESMO_MOTIVO VARCHAR2(4);
vOLD_INFO_MESMO_MOTIVO VARCHAR2(4);

vNEW_DT_EFEITO_MESMO_MOTIVO DATE;
vOLD_DT_EFEITO_MESMO_MOTIVO DATE;

BEGIN

vTABELA := 'RHMEDI_FICHA_MED';

vCODIGO_EMPRESA := NULL;
vTIPO_CONTRATO := NULL;
vCODIGO_CONTRATO := NULL;
vCODIGO_PESSOA := NULL;
vNEW_COD_SIT_FUNCIONAL := NULL;
vOLD_COD_SIT_FUNCIONAL := NULL;
vDT_REG_OCORRENCIA := NULL;
vOCORRENCIA := NULL;
vNEW_NATUREZA_EXAME := NULL;
vOLD_NATUREZA_EXAME := NULL; 
vNEW_DATA_INI_AFAST := NULL;
vOLD_DATA_INI_AFAST := NULL;
vNEW_DATA_FIM_AFAST := NULL;
vOLD_DATA_FIM_AFAST := NULL;
vNEW_DATA_INICIAL_INDEFERIMENT := NULL;
vOLD_DATA_INICIAL_INDEFERIMENT := NULL;
vNEW_DATA_FINAL_INDEFERIMENTO := NULL;
vOLD_DATA_FINAL_INDEFERIMENTO := NULL;
vNEW_OCOR_PROC_MED := NULL;
vOLD_OCOR_PROC_MED := NULL;
vNEW_CODIGO_PROC_MED := NULL;
vOLD_CODIGO_PROC_MED := NULL;
vNEW_OCOR_DOENCA := NULL;
vOLD_OCOR_DOENCA := NULL;
vNEW_COD_DOENCA := NULL;
vOLD_COD_DOENCA := NULL;

vDT_ULT_ALTER_USUA := SYSDATE;

    vLOGIN_USUARIO_NEW := :NEW.LOGIN_USUARIO;
    vLOGIN_USUARIO_OLD := :OLD.LOGIN_USUARIO;
    vLOGIN_OS_NEW := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_OS_OLD := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_NEW := NULL;
    vLOGIN_OLD := NULL;

vNEW_EMPRESA_ATENDENTE := NULL;
vOLD_EMPRESA_ATENDENTE := NULL;
vNEW_CODIGO_ATENDENTE := NULL;
vOLD_CODIGO_ATENDENTE := NULL;
vNEW_NOME_ATENDENTE := NULL;
vOLD_NOME_ATENDENTE := NULL;
vNEW_INSCRICAO_CONSELHO := NULL;
vOLD_INSCRICAO_CONSELHO := NULL;
vNEW_UF_INSCRICAO := NULL;
vOLD_UF_INSCRICAO := NULL;
vNEW_CONSELHO_REGIONAL := NULL;
vOLD_CONSELHO_REGIONAL := NULL;

vNEW_INFO_MESMO_MOTIVO := NULL;
vOLD_INFO_MESMO_MOTIVO := NULL;

vNEW_DT_EFEITO_MESMO_MOTIVO := NULL;
vOLD_DT_EFEITO_MESMO_MOTIVO := NULL;

--definir login a usar NEW
    IF vLOGIN_USUARIO_NEW = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_NEW;
    ELSE 
    vLOGIN_NEW := vLOGIN_USUARIO_NEW;
    END IF;

--definir login a usar OLD
    IF vLOGIN_USUARIO_OLD = 'ARTERH_UPBH' then 
    vLOGIN_NEW := vLOGIN_OS_OLD;
    ELSE 
    vLOGIN_OLD := vLOGIN_USUARIO_OLD;
    END IF;

vULT_ID := 0;    
--------------------------------------------------------------------------INSERT-------------------------------------------------------------------------------------------------------------------------------------------
IF INSERTING THEN 
v_DML := 'I';

/*
--parte NEW
SELECT 
--F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.SITUACAO_FUNCIONAL, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, 
F.DATA_INI_AFAST, F.DATA_FIM_AFAST, F.C_LIVRE_DATA01 DATA_INICIAL_INDEFERIMENTO, F.C_LIVRE_DATA02 DATA_FINAL_INDEFERIMENTO,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, D.OCOR_DOENCA, D.COD_DOENCA
INTO 
--vCODIGO_EMPRESA, vTIPO_CONTRATO, vCODIGO_CONTRATO, vCODIGO_PESSOA, vNEW_COD_SIT_FUNCIONAL, vDT_REG_OCORRENCIA, vOCORRENCIA, vNEW_NATUREZA_EXAME, 
vNEW_DATA_INI_AFAST, vNEW_DATA_FIM_AFAST, vNEW_DATA_INICIAL_INDEFERIMENT, vNEW_DATA_FINAL_INDEFERIMENTO, vNEW_OCOR_PROC_MED, vNEW_CODIGO_PROC_MED, vNEW_OCOR_DOENCA, vNEW_COD_DOENCA 
FROM RHMEDI_FICHA_MED F
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
WHERE F.CODIGO_EMPRESA = '0001' AND F.NATUREZA_EXAME IS NOT NULL
AND F.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND F.CODIGO_PESSOA = :NEW.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = :NEW.DT_REG_OCORRENCIA AND F.OCORRENCIA = :NEW.OCORRENCIA;
*/

INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
CODIGO_PESSOA,
NEW_COD_SIT_FUNCIONAL,
OLD_COD_SIT_FUNCIONAL,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_NATUREZA_EXAME,
OLD_NATUREZA_EXAME,
NEW_DATA_INI_AFAST,
OLD_DATA_INI_AFAST,
NEW_DATA_FIM_AFAST,
OLD_DATA_FIM_AFAST,
NEW_DATA_INICIAL_INDEFERIMENTO,
OLD_DATA_INICIAL_INDEFERIMENTO,
NEW_DATA_FINAL_INDEFERIMENTO,
OLD_DATA_FINAL_INDEFERIMENTO,
NEW_OCOR_PROC_MED,
OLD_OCOR_PROC_MED,
NEW_CODIGO_PROC_MED,
OLD_CODIGO_PROC_MED,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
,NEW_EMPRESA_ATENDENTE
,OLD_EMPRESA_ATENDENTE
,NEW_CODIGO_ATENDENTE
,OLD_CODIGO_ATENDENTE
,NEW_NOME_ATENDENTE
,OLD_NOME_ATENDENTE
,NEW_INSCRICAO_CONSELHO
,OLD_INSCRICAO_CONSELHO
,NEW_UF_INSCRICAO
,OLD_UF_INSCRICAO
,NEW_CONSELHO_REGIONAL
,OLD_CONSELHO_REGIONAL
,NEW_INFO_MESMO_MOTIVO
,OLD_INFO_MESMO_MOTIVO
,NEW_DT_EFEITO_MESMO_MOTIVO
,OLD_DT_EFEITO_MESMO_MOTIVO
)
VALUES
(SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO,
:NEW.CODIGO_PESSOA,
:NEW.SITUACAO_FUNCIONAL,
NULL,
:NEW.DT_REG_OCORRENCIA,
:NEW.OCORRENCIA,
:NEW.NATUREZA_EXAME,
NULL,
:NEW.DATA_INI_AFAST,
NULL,
:NEW.DATA_FIM_AFAST,
NULL,
:NEW.C_LIVRE_DATA01,
NULL,
:NEW.C_LIVRE_DATA02,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
SYSDATE,
vLOGIN_NEW,
vLOGIN_NEW
,'N',
:NEW.EMPRESA_ATENDENTE,
NULL,
:NEW.CODIGO_ATENDENTE,
NULL,
:NEW.NOME_ATENDENTE,
NULL,
:NEW.INSCRICAO_CONSELHO,
NULL,
:NEW.UF_INSCRICAO,
NULL,
:NEW.CONSELHO_REGIONAL,
NULL,
:NEW.INFO_MESMO_MOTIVO,
NULL,
:NEW.DT_EFEITO_MESMO_MOTIVO,
NULL
);

--------------------------------------------------------------------------UPDATE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF UPDATING THEN
v_DML := 'U';
/*
FOR C1 IN(
SELECT 
/*TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
TC2.DADO_ORIGEM DADO_ORIGEM_TC2, TC2.DADO_DESTINO DADO_DESTINO_TC2,
TC3.DADO_ORIGEM DADO_ORIGEM_TC3, TC3.DADO_DESTINO DADO_DESTINO_TC3,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, A.ANO_MES_REFERENCIA, A.VINCULO, V.tp_regime_trab_esocial, V.tp_regime_prev_esocial, V.cod_categ_esocial, 
D.OCOR_DOENCA, D.COD_DOENCA, DOE.C_LIVRE_OPCAO01 DOENCA_C_LIVRE_OPCAO01, DOE.C_LIVRE_DESCR02 DOENCA_C_LIVRE_DESCR02
F.CODIGO_EMPRESA INTO vCODIGO_EMPRESA
FROM 
RHMEDI_FICHA_MED F 
FULL OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
full OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (select max(AUX.ano_mes_referencia) from rhpess_contrato AUX where AUX.codigo_empresa = A.codigo_empresa and AUX.tipo_contrato = A.tipo_contrato and AUX.codigo = A.codigo))A ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1')TC1 ON SUBSTR(TC1.DADO_ORIGEM,1,24) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.tp_regime_trab_esocial|| V.tp_regime_prev_esocial||V.cod_categ_esocial --PROCEDIMENTO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG2')TC2 ON SUBSTR(TC2.DADO_ORIGEM,1,19)||SUBSTR(TC2.DADO_ORIGEM,28,LENGTH(TC2.DADO_ORIGEM)) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||DOE.C_LIVRE_DESCR02 --1Âª DOENCA 
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG2')TC3 ON SUBSTR(TC3.DADO_ORIGEM,1,19) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED      AND TC3.DADO_DESTINO = DOE.C_LIVRE_DESCR02 --2Âª DOENCA 
WHERE --X.ID = 40--40--36--21--15
F.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND F.CODIGO_PESSOA = :NEW.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = :NEW.DT_REG_OCORRENCIA AND F.OCORRENCIA = :NEW.OCORRENCIA
--F.CODIGO_EMPRESA = '0001' AND F.CODIGO_PESSOA = '000000000883291'  AND F.DT_REG_OCORRENCIA = '27/08/19' AND F.OCORRENCIA = 2
)
LOOP
INSERT INTO SUGESP_FICHAS_MEDICAS_LOG_TEST VALUES (1, 'RHMEDI_RL_FICH_DOE'||'- INSERT/DELETE/UPDATE' , SYSDATE);-- NÃƒO USAR APOS TESTE E NÃƒO LEVAR PARA PRODUCAO
END LOOP;
--parte NEW
/*SELECT 
--F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.SITUACAO_FUNCIONAL, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, 
F.DATA_INI_AFAST, F.DATA_FIM_AFAST, F.C_LIVRE_DATA01 DATA_INICIAL_INDEFERIMENTO, F.C_LIVRE_DATA02 DATA_FINAL_INDEFERIMENTO,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, D.OCOR_DOENCA, D.COD_DOENCA
INTO 
--vCODIGO_EMPRESA, vTIPO_CONTRATO, vCODIGO_CONTRATO, vCODIGO_PESSOA, vNEW_COD_SIT_FUNCIONAL, vDT_REG_OCORRENCIA, vOCORRENCIA, vNEW_NATUREZA_EXAME, 
vNEW_DATA_INI_AFAST, vNEW_DATA_FIM_AFAST, vNEW_DATA_INICIAL_INDEFERIMENT, vNEW_DATA_FINAL_INDEFERIMENTO, vNEW_OCOR_PROC_MED, vNEW_CODIGO_PROC_MED, vNEW_OCOR_DOENCA, vNEW_COD_DOENCA 
FROM RHMEDI_FICHA_MED F
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
WHERE F.CODIGO_EMPRESA = '0001' AND F.NATUREZA_EXAME IS NOT NULL
AND F.CODIGO_EMPRESA = :NEW.CODIGO_EMPRESA AND F.CODIGO_PESSOA = :NEW.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = :NEW.DT_REG_OCORRENCIA AND F.OCORRENCIA = :NEW.OCORRENCIA;

--parte OLD
SELECT 
--F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.SITUACAO_FUNCIONAL, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, 
F.DATA_INI_AFAST, F.DATA_FIM_AFAST, F.C_LIVRE_DATA01 DATA_INICIAL_INDEFERIMENTO, F.C_LIVRE_DATA02 DATA_FINAL_INDEFERIMENTO,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, D.OCOR_DOENCA, D.COD_DOENCA
INTO 
--vCODIGO_EMPRESA, vTIPO_CONTRATO, vCODIGO_CONTRATO, vCODIGO_PESSOA, vOLD_COD_SIT_FUNCIONAL, vDT_REG_OCORRENCIA, vOCORRENCIA, vOLD_NATUREZA_EXAME, 
vOLD_DATA_INI_AFAST, vOLD_DATA_FIM_AFAST, vOLD_DATA_INICIAL_INDEFERIMENT, vOLD_DATA_FINAL_INDEFERIMENTO, vOLD_OCOR_PROC_MED, vOLD_CODIGO_PROC_MED, vOLD_OCOR_DOENCA, vOLD_COD_DOENCA 
FROM RHMEDI_FICHA_MED F
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
WHERE F.CODIGO_EMPRESA = '0001' AND F.NATUREZA_EXAME IS NOT NULL
AND F.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND F.CODIGO_PESSOA = :OLD.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = :OLD.DT_REG_OCORRENCIA AND F.OCORRENCIA = :OLD.OCORRENCIA;
*/

INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
CODIGO_PESSOA,
NEW_COD_SIT_FUNCIONAL,
OLD_COD_SIT_FUNCIONAL,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_NATUREZA_EXAME,
OLD_NATUREZA_EXAME,
NEW_DATA_INI_AFAST,
OLD_DATA_INI_AFAST,
NEW_DATA_FIM_AFAST,
OLD_DATA_FIM_AFAST,
NEW_DATA_INICIAL_INDEFERIMENTO,
OLD_DATA_INICIAL_INDEFERIMENTO,
NEW_DATA_FINAL_INDEFERIMENTO,
OLD_DATA_FINAL_INDEFERIMENTO,
NEW_OCOR_PROC_MED,
OLD_OCOR_PROC_MED,
NEW_CODIGO_PROC_MED,
OLD_CODIGO_PROC_MED,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
,NEW_EMPRESA_ATENDENTE
,OLD_EMPRESA_ATENDENTE
,NEW_CODIGO_ATENDENTE
,OLD_CODIGO_ATENDENTE
,NEW_NOME_ATENDENTE
,OLD_NOME_ATENDENTE
,NEW_INSCRICAO_CONSELHO
,OLD_INSCRICAO_CONSELHO
,NEW_UF_INSCRICAO
,OLD_UF_INSCRICAO
,NEW_CONSELHO_REGIONAL
,OLD_CONSELHO_REGIONAL
,NEW_INFO_MESMO_MOTIVO
,OLD_INFO_MESMO_MOTIVO
,NEW_DT_EFEITO_MESMO_MOTIVO
,OLD_DT_EFEITO_MESMO_MOTIVO
)
VALUES
(SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO,
:NEW.CODIGO_PESSOA,
:NEW.SITUACAO_FUNCIONAL,
:OLD.SITUACAO_FUNCIONAL,
:NEW.DT_REG_OCORRENCIA,
:NEW.OCORRENCIA,
:NEW.NATUREZA_EXAME,
:OLD.NATUREZA_EXAME,
:NEW.DATA_INI_AFAST,
:OLD.DATA_INI_AFAST,
:NEW.DATA_FIM_AFAST,
:OLD.DATA_FIM_AFAST,
:NEW.C_LIVRE_DATA01,
:OLD.C_LIVRE_DATA01,
:NEW.C_LIVRE_DATA02,
:OLD.C_LIVRE_DATA02,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
SYSDATE,
vLOGIN_NEW,
vLOGIN_OLD
,'N',
:NEW.EMPRESA_ATENDENTE,
:OLD.EMPRESA_ATENDENTE,
:NEW.CODIGO_ATENDENTE,
:OLD.CODIGO_ATENDENTE,
:NEW.NOME_ATENDENTE,
:OLD.NOME_ATENDENTE,
:NEW.INSCRICAO_CONSELHO,
:OLD.INSCRICAO_CONSELHO,
:NEW.UF_INSCRICAO,
:OLD.UF_INSCRICAO,
:NEW.CONSELHO_REGIONAL,
:OLD.CONSELHO_REGIONAL,
:NEW.INFO_MESMO_MOTIVO,
:OLD.INFO_MESMO_MOTIVO,
:NEW.DT_EFEITO_MESMO_MOTIVO,
:OLD.DT_EFEITO_MESMO_MOTIVO
);

--------------------------------------------------------------------------DELETE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF DELETING THEN
v_DML := 'D';

/*
--parte OLD
SELECT 
--F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.SITUACAO_FUNCIONAL, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, 
F.DATA_INI_AFAST, F.DATA_FIM_AFAST, F.C_LIVRE_DATA01 DATA_INICIAL_INDEFERIMENTO, F.C_LIVRE_DATA02 DATA_FINAL_INDEFERIMENTO,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, D.OCOR_DOENCA, D.COD_DOENCA
INTO 
--vCODIGO_EMPRESA, vTIPO_CONTRATO, vCODIGO_CONTRATO, vCODIGO_PESSOA, vOLD_COD_SIT_FUNCIONAL, vDT_REG_OCORRENCIA, vOCORRENCIA, vOLD_NATUREZA_EXAME, 
vOLD_DATA_INI_AFAST, vOLD_DATA_FIM_AFAST, vOLD_DATA_INICIAL_INDEFERIMENT, vOLD_DATA_FINAL_INDEFERIMENTO, vOLD_OCOR_PROC_MED, vOLD_CODIGO_PROC_MED, vOLD_OCOR_DOENCA, vOLD_COD_DOENCA 
FROM RHMEDI_FICHA_MED F
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
WHERE F.CODIGO_EMPRESA = '0001' AND F.NATUREZA_EXAME IS NOT NULL
AND F.CODIGO_EMPRESA = :OLD.CODIGO_EMPRESA AND F.CODIGO_PESSOA = :OLD.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = :OLD.DT_REG_OCORRENCIA AND F.OCORRENCIA = :OLD.OCORRENCIA;
*/

INSERT INTO SUGESP_FICHAS_MEDICAS(
ID,
TIPO_DML,
TABELA,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
CODIGO_PESSOA,
NEW_COD_SIT_FUNCIONAL,
OLD_COD_SIT_FUNCIONAL,
DT_REG_OCORRENCIA,
OCORRENCIA,
NEW_NATUREZA_EXAME,
OLD_NATUREZA_EXAME,
NEW_DATA_INI_AFAST,
OLD_DATA_INI_AFAST,
NEW_DATA_FIM_AFAST,
OLD_DATA_FIM_AFAST,
NEW_DATA_INICIAL_INDEFERIMENTO,
OLD_DATA_INICIAL_INDEFERIMENTO,
NEW_DATA_FINAL_INDEFERIMENTO,
OLD_DATA_FINAL_INDEFERIMENTO,
NEW_OCOR_PROC_MED,
OLD_OCOR_PROC_MED,
NEW_CODIGO_PROC_MED,
OLD_CODIGO_PROC_MED,
NEW_OCOR_DOENCA,
OLD_OCOR_DOENCA,
NEW_COD_DOENCA,
OLD_COD_DOENCA,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_OS
,PROCESSADO
,NEW_EMPRESA_ATENDENTE
,OLD_EMPRESA_ATENDENTE
,NEW_CODIGO_ATENDENTE
,OLD_CODIGO_ATENDENTE
,NEW_NOME_ATENDENTE
,OLD_NOME_ATENDENTE
,NEW_INSCRICAO_CONSELHO
,OLD_INSCRICAO_CONSELHO
,NEW_UF_INSCRICAO
,OLD_UF_INSCRICAO
,NEW_CONSELHO_REGIONAL
,OLD_CONSELHO_REGIONAL
,NEW_INFO_MESMO_MOTIVO
,OLD_INFO_MESMO_MOTIVO
,NEW_DT_EFEITO_MESMO_MOTIVO
,OLD_DT_EFEITO_MESMO_MOTIVO
)
VALUES
(SEQUENCE_SUGESP_FICHAS_MEDICAS.NEXTVAL,--ATE 16/7/20--(SELECT MAX(ID)+1 FROM SUGESP_FICHAS_MEDICAS),
v_DML,
vTABELA,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO,
:OLD.CODIGO_PESSOA,
NULL,
:OLD.SITUACAO_FUNCIONAL,
:OLD.DT_REG_OCORRENCIA,
:OLD.OCORRENCIA,
NULL,
:OLD.NATUREZA_EXAME,
NULL,
:OLD.DATA_INI_AFAST,
NULL,
:OLD.DATA_FIM_AFAST,
NULL,
:OLD.C_LIVRE_DATA01,
NULL,
:OLD.C_LIVRE_DATA02,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
SYSDATE,
vLOGIN_OLD,
vLOGIN_OLD
,'N',
NULL,
:OLD.EMPRESA_ATENDENTE,
NULL,
:OLD.CODIGO_ATENDENTE,
NULL,
:OLD.NOME_ATENDENTE,
NULL,
:OLD.INSCRICAO_CONSELHO,
NULL,
:OLD.UF_INSCRICAO,
NULL,
:OLD.CONSELHO_REGIONAL,
NULL,
:OLD.INFO_MESMO_MOTIVO,
NULL,
:OLD.DT_EFEITO_MESMO_MOTIVO
);


END IF;


--------------------------------------------------------------------------------CHAMAR PROCEDURE DE FICHAS MEDICAS E FILHAS
--select ID into vULT_ID FROM SUGESP_FICHAS_MEDICAS WHERE ID = (SELECT MAX(ID) FROM SUGESP_FICHAS_MEDICAS);
--PR_SUGESP_FICHAS_MEDICAS('RHMEDI_FICHA_MED', vULT_ID);
--------------------------------------------------------------------------------CHAMAR PROCEDURE DE FICHAS MEDICAS E FILHAS


END;




ALTER TRIGGER "ARTERH"."TR_SUGESP_RHMEDI_FICHA_MED" ENABLE