
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_SUGESP_RHORGA_AGRUP_TIPO_G" 
AFTER INSERT OR UPDATE OR DELETE ON "ARTERH"."RHORGA_AGRUPADOR"
FOR EACH ROW
 DECLARE
v_DML SUGESP_RHORGA_AGRUP_TIPO_G.TIPO_DML%TYPE;

BEGIN

-----INICIO---------------------------------------------------------------UPDATE
-----INICIO-----------1ª PARTE -----------TROCOU O GESTOR DO LOCAL --LOCAL ATIVO
IF (UPDATING AND :OLD.CONTRATO_RESP <> :NEW.CONTRATO_RESP AND :NEW.DATA_EXTINCAO IS NULL)THEN --and (NEW.TIPO_AGRUP = 'G' OR OLD.TIPO_AGRUP = 'G') AND NEW.CONTRATO_RESP <> OLD.CONTRATO_RESP THEN
v_DML := 'U';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO
);
--commit;

---****************SEGUNDO CRIA REGISTRO DO NOVO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
INSERT INTO RHUSER_PESSOA_RESPONSAVEL (
ID,
ID_PROCESSO,
ID_TAREFA,
CODIGO_EMPRESA,
CODIGO_USUARIO,
CODIGO_EMPRESA_PESSOA_RESP,
CODIGO_PESSOA_RESP,
CODIGO_CONTRATO_RESP,
TIPO_CONTRATO_RESP,
CODIGO_EMPRESA_CONTRATO,
DT_INICIO_RESPONSABILIDADE,
DT_FIM_RESPONSABILIDADE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
NOME_COMPOSTO,
MOTIVO_DELEGACAO,
ID_DELEGACAO_SUBSTITUICAO)
VALUES
(
(SELECT MAX(ID)+1 FROM RHUSER_PESSOA_RESPONSAVEL),
2,
NULL,
:NEW.CODIGO_EMPRESA,
:NEW.LOGIN_USUARIO,
:NEW.COD_EMPRESA_PESS,
:NEW.COD_PESSOA_RESP,
:NEW.CONTRATO_RESP,
:NEW.TIPO_CONT_RESP,
:NEW.COD_EMPRESA_PESS,
SYSDATE,
NULL,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
(select C.CODIGO||' - '||NVL(TRIM(P.NOME_SOCIAL),TRIM(P.NOME_ACESSO)) ||' - '||C.TIPO_CONTRATO||' - '|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))from RHPESS_CONTRATO C left outer join RHPESS_PESSOA P ON P.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND P.CODIGO = C.CODIGO_PESSOA WHERE C.ANO_MES_REFERENCIA = (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX where AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = C.TIPO_CONTRATO and AUX.CODIGO = C.CODIGO)AND C.CODIGO_EMPRESA = :NEW.COD_EMPRESA_PESS AND C.TIPO_CONTRATO = :NEW.TIPO_CONT_RESP AND C.CODIGO = :NEW.CONTRATO_RESP),
--:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| :NEW.DESCRICAO|| '-'|| :NEW.ABREVIACAO,
'F',
:NEW.ID_AGRUP ----TESTES VOLTAR DEPOIS PARA NULL
);
--COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19
INSERT INTO rhuser_pessoa_resp_agrupador (
ID,
ID_RHUSER_PESSOA_RESPONSAVEL,
CODIGO_EMPRESA,
TIPO_AGRUP,
ID_AGRUP,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
DT_INICIO_RESPONSAVEL,
NOME_AGRUPADOR_COMPOSTO)
VALUES
(
(SELECT MAX(ID)+1 FROM rhuser_pessoa_resp_agrupador),
(SELECT MAX(ID) FROM RHUSER_PESSOA_RESPONSAVEL),
:NEW.CODIGO_EMPRESA,
'G',
:NEW.ID_AGRUP,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO
);
--commit;
-----FIM---------------1ª PARTE -----------TROCOU O GESTOR DO LOCAL--LOCAL ATIVO

-----INICIO----------------------------2ª PARTE -------------LOCAL SENDO INATIVO
ELSIF (UPDATING AND :OLD.DATA_EXTINCAO IS NULL AND :NEW.DATA_EXTINCAO IS NOT NULL)THEN --and (NEW.TIPO_AGRUP = 'G' OR OLD.TIPO_AGRUP = 'G') AND NEW.CONTRATO_RESP <> OLD.CONTRATO_RESP THEN
v_DML := 'U';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO
);
--commit;
-----FIM-----------------------2ª PARTE -------------LOCAL SENDO INATIVO

-----INICIO-----------3ª PARTE ------------LOCAL REATIVO
ELSIF (UPDATING AND :OLD.DATA_EXTINCAO IS NOT NULL AND :NEW.DATA_EXTINCAO IS NULL)THEN --and (NEW.TIPO_AGRUP = 'G' OR OLD.TIPO_AGRUP = 'G') AND NEW.CONTRATO_RESP <> OLD.CONTRATO_RESP THEN
v_DML := 'U';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO
);
--commit;

---****************SEGUNDO CRIA REGISTRO DO NOVO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
INSERT INTO RHUSER_PESSOA_RESPONSAVEL (
ID,
ID_PROCESSO,
ID_TAREFA,
CODIGO_EMPRESA,
CODIGO_USUARIO,
CODIGO_EMPRESA_PESSOA_RESP,
CODIGO_PESSOA_RESP,
CODIGO_CONTRATO_RESP,
TIPO_CONTRATO_RESP,
CODIGO_EMPRESA_CONTRATO,
DT_INICIO_RESPONSABILIDADE,
DT_FIM_RESPONSABILIDADE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
NOME_COMPOSTO,
MOTIVO_DELEGACAO,
ID_DELEGACAO_SUBSTITUICAO)
VALUES
(
(SELECT MAX(ID)+1 FROM RHUSER_PESSOA_RESPONSAVEL),
2,
NULL,
:NEW.CODIGO_EMPRESA,
:NEW.LOGIN_USUARIO,
:NEW.COD_EMPRESA_PESS,
:NEW.COD_PESSOA_RESP,
:NEW.CONTRATO_RESP,
:NEW.TIPO_CONT_RESP,
:NEW.COD_EMPRESA_PESS,
SYSDATE,
NULL,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
(select C.CODIGO||' - '||NVL(TRIM(P.NOME_SOCIAL),TRIM(P.NOME_ACESSO)) ||' - '||C.TIPO_CONTRATO||' - '|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))from RHPESS_CONTRATO C left outer join RHPESS_PESSOA P ON P.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND P.CODIGO = C.CODIGO_PESSOA WHERE C.ANO_MES_REFERENCIA = (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX where AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = C.TIPO_CONTRATO and AUX.CODIGO = C.CODIGO)AND C.CODIGO_EMPRESA = :NEW.COD_EMPRESA_PESS AND C.TIPO_CONTRATO = :NEW.TIPO_CONT_RESP AND C.CODIGO = :NEW.CONTRATO_RESP),
--:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| :NEW.DESCRICAO|| '-'|| :NEW.ABREVIACAO,
'F',
:NEW.ID_AGRUP ----TESTES VOLTAR DEPOIS PARA NULL
);
--COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19
INSERT INTO rhuser_pessoa_resp_agrupador (
ID,
ID_RHUSER_PESSOA_RESPONSAVEL,
CODIGO_EMPRESA,
TIPO_AGRUP,
ID_AGRUP,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
DT_INICIO_RESPONSAVEL,
NOME_AGRUPADOR_COMPOSTO)
VALUES
(
(SELECT MAX(ID)+1 FROM rhuser_pessoa_resp_agrupador),
(SELECT MAX(ID) FROM RHUSER_PESSOA_RESPONSAVEL),
:NEW.CODIGO_EMPRESA,
'G',
:NEW.ID_AGRUP,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO
);
--commit;
-----FIM---------------3ª PARTE -----------LOCAL REATIVADO

--INICIO---DEMAIS CASOS UPDATE EM 7/6/22
ELSIF (UPDATING)THEN 

v_DML := 'U';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO
);
--FIM---DEMAIS CASOS UPDATE EM 7/6/22


-----FIM--  --------------------------------------------------------------UPDATE


----INICIO----------------------------------------------------------------INSERT
ELSIF INSERTING THEN
v_DML := 'I';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO
);


---****************SEGUNDO CRIA REGISTRO DO NOVO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
INSERT INTO RHUSER_PESSOA_RESPONSAVEL (
ID,
ID_PROCESSO,
ID_TAREFA,
CODIGO_EMPRESA,
CODIGO_USUARIO,
CODIGO_EMPRESA_PESSOA_RESP,
CODIGO_PESSOA_RESP,
CODIGO_CONTRATO_RESP,
TIPO_CONTRATO_RESP,
CODIGO_EMPRESA_CONTRATO,
DT_INICIO_RESPONSABILIDADE,
DT_FIM_RESPONSABILIDADE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
NOME_COMPOSTO,
MOTIVO_DELEGACAO,
ID_DELEGACAO_SUBSTITUICAO)
VALUES
(
(SELECT MAX(ID)+1 FROM RHUSER_PESSOA_RESPONSAVEL),
2,
NULL,
:NEW.CODIGO_EMPRESA,
:NEW.LOGIN_USUARIO,
:NEW.COD_EMPRESA_PESS,
:NEW.COD_PESSOA_RESP,
:NEW.CONTRATO_RESP,
:NEW.TIPO_CONT_RESP,
:NEW.COD_EMPRESA_PESS,
SYSDATE,
NULL,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
(select C.CODIGO||' - '||NVL(TRIM(P.NOME_SOCIAL),TRIM(P.NOME_ACESSO)) ||' - '||C.TIPO_CONTRATO||' - '|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))from RHPESS_CONTRATO C left outer join RHPESS_PESSOA P ON P.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND P.CODIGO = C.CODIGO_PESSOA WHERE C.ANO_MES_REFERENCIA = (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX where AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = C.TIPO_CONTRATO and AUX.CODIGO = C.CODIGO)AND C.CODIGO_EMPRESA = :NEW.COD_EMPRESA_PESS AND C.TIPO_CONTRATO = :NEW.TIPO_CONT_RESP AND C.CODIGO = :NEW.CONTRATO_RESP),
--:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| :NEW.DESCRICAO|| '-'|| :NEW.ABREVIACAO,
'F',
:NEW.ID_AGRUP ----TESTES VOLTAR DEPOIS PARA NULL
);
--COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19
INSERT INTO rhuser_pessoa_resp_agrupador (
ID,
ID_RHUSER_PESSOA_RESPONSAVEL,
CODIGO_EMPRESA,
TIPO_AGRUP,
ID_AGRUP,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
DT_INICIO_RESPONSAVEL,
NOME_AGRUPADOR_COMPOSTO)
VALUES
(
(SELECT MAX(ID)+1 FROM rhuser_pessoa_resp_agrupador),
(SELECT MAX(ID) FROM RHUSER_PESSOA_RESPONSAVEL),
:NEW.CODIGO_EMPRESA,
'G',
:NEW.ID_AGRUP,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO
);
--commit;
----FIM-------------------------------------------------------------------INSERT




---------INICIO-----------------------------------------------------------DELETE
ELSIF DELETING THEN
v_DML := 'D';
INSERT INTO SUGESP_RHORGA_AGRUP_TIPO_G
(
TIPO_DML,
ID_AGRUP,
CODIGO_EMPRESA,
TIPO_AGRUP,
COD_AGRUP1,
COD_AGRUP2,
COD_AGRUP3,
COD_AGRUP4,
COD_AGRUP5,
COD_AGRUP6,
DESCRICAO,
ABREVIACAO,
OLD_COD_EMPRESA_PESS,
OLD_TIPO_CONT_RESP,
OLD_CONTRATO_RESP,
NEW_COD_EMPRESA_PESS,
NEW_TIPO_CONT_RESP,
NEW_CONTRATO_RESP,
OLD_LOGIN_USUARIO,
OLD_DT_ULT_ALTER_USUA,
NEW_LOGIN_USUARIO,
NEW_DT_ULT_ALTER_USUA,
DT_ULT_ALTER_USUA,
ID,
NEW_COD_PESSOA_RESP,
OLD_COD_PESSOA_RESP,
TEXTO_ASSOCIADO,
OLD_DATA_EXTINCAO,
NEW_DATA_EXTINCAO
)
VALUES
(
v_DML,
:OLD.ID_AGRUP,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_AGRUP,
:OLD.COD_AGRUP1,
:OLD.COD_AGRUP2,
:OLD.COD_AGRUP3,
:OLD.COD_AGRUP4,
:OLD.COD_AGRUP5,
:OLD.COD_AGRUP6,
:OLD.DESCRICAO,
:OLD.ABREVIACAO,
:OLD.COD_EMPRESA_PESS,
:OLD.TIPO_CONT_RESP,
:OLD.CONTRATO_RESP,
:NEW.COD_EMPRESA_PESS,
:NEW.TIPO_CONT_RESP,
:NEW.CONTRATO_RESP,
:OLD.LOGIN_USUARIO,
:OLD.DT_ULT_ALTER_USUA,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
SYSDATE,
(SELECT MAX(ID)+1 FROM SUGESP_RHORGA_AGRUP_TIPO_G),
:NEW.COD_PESSOA_RESP,
:OLD.COD_PESSOA_RESP,
:OLD.COD_AGRUP1|| '.'|| :OLD.COD_AGRUP2|| '.'|| :OLD.COD_AGRUP3|| '.'|| :OLD.COD_AGRUP4|| '.'|| :OLD.COD_AGRUP5|| '.'|| :OLD.COD_AGRUP6|| '-'|| NVL(TRIM(:OLD.TEXTO_ASSOCIADO),TRIM(:OLD.DESCRICAO))|| '-'|| :OLD.ABREVIACAO,
:OLD.DATA_EXTINCAO,
:NEW.DATA_EXTINCAO

);
END IF;
---------FIM--------------------------------------------------------------DELETE



/*
--INICIO----------------------------------------- versão com erro X-MEN no ORACLE
-------------------------------------------------------------------------------------------XXX1ª PARTE -----------LOCAL NÃO TINHA RESPONSAVEL E AGORA TEM
--CRIA REGISTRO DO NOVO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
IF (UPDATING AND :OLD.CONTRATO_RESP IS NULL AND :NEW.CONTRATO_RESP IS NOT NULL) THEN
INSERT INTO RHUSER_PESSOA_RESPONSAVEL (
ID,
ID_PROCESSO,
ID_TAREFA,
CODIGO_EMPRESA,
CODIGO_USUARIO,
CODIGO_EMPRESA_PESSOA_RESP,
CODIGO_PESSOA_RESP,
CODIGO_CONTRATO_RESP,
TIPO_CONTRATO_RESP,
CODIGO_EMPRESA_CONTRATO,
DT_INICIO_RESPONSABILIDADE,
DT_FIM_RESPONSABILIDADE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
NOME_COMPOSTO,
MOTIVO_DELEGACAO,
ID_DELEGACAO_SUBSTITUICAO)
VALUES
(
(SELECT MAX(ID)+1 FROM RHUSER_PESSOA_RESPONSAVEL),
2,
NULL,
:NEW.CODIGO_EMPRESA,
:NEW.LOGIN_USUARIO,
:NEW.COD_EMPRESA_PESS,
:NEW.COD_PESSOA_RESP,
:NEW.CONTRATO_RESP,
:NEW.TIPO_CONT_RESP,
:NEW.COD_EMPRESA_PESS,
SYSDATE,
NULL,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
(select C.CODIGO||' - '||NVL(TRIM(P.NOME_SOCIAL),TRIM(P.NOME_ACESSO)) ||' - '||C.TIPO_CONTRATO||' - '|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))from RHPESS_CONTRATO C left outer join RHPESS_PESSOA P ON P.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND P.CODIGO = C.CODIGO_PESSOA WHERE C.ANO_MES_REFERENCIA = (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX where AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = C.TIPO_CONTRATO and AUX.CODIGO = C.CODIGO)AND C.CODIGO_EMPRESA = :NEW.COD_EMPRESA_PESS AND C.TIPO_CONTRATO = :NEW.TIPO_CONT_RESP AND C.CODIGO = :NEW.CONTRATO_RESP),
--:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| :NEW.DESCRICAO|| '-'|| :NEW.ABREVIACAO,
'F',
:NEW.ID_AGRUP
);
commit;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19

INSERT INTO rhuser_pessoa_resp_agrupador (
ID,
ID_RHUSER_PESSOA_RESPONSAVEL,
CODIGO_EMPRESA,
TIPO_AGRUP,
ID_AGRUP,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
DT_INICIO_RESPONSAVEL,
NOME_AGRUPADOR_COMPOSTO)
VALUES
(
(SELECT MAX(ID)+1 FROM rhuser_pessoa_resp_agrupador),
(SELECT MAX(ID) FROM RHUSER_PESSOA_RESPONSAVEL),
:NEW.CODIGO_EMPRESA,
'G',
:NEW.ID_AGRUP,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO
);
commit;



-------------------------------------------------------------------------------------------XXX2ª PARTE -----------LOCAL TINHA RESPONSAVEL E AGORA NÃO TEM
ELSIF (UPDATING AND :OLD.CONTRATO_RESP IS NOT NULL AND :NEW.CONTRATO_RESP IS NULL) THEN
-- FINALIZA O REGISTRO ABERTO NO ANTIGO GESTOR

--tabela RHUSER_PESSOA_RESPONSAVEL
--select * from RHUSER_PESSOA_RESPONSAVEL WHERE id = (Select id_rhuser_pessoa_responsavel From rhuser_pessoa_resp_agrupador
UPDATE RHUSER_PESSOA_RESPONSAVEL SET DT_FIM_RESPONSABILIDADE = SYSDATE, UPDATED = SYSDATE, UPDATEDBY = :NEW.LOGIN_USUARIO
WHERE DT_FIM_RESPONSABILIDADE is null and ID =
(SELECT ID_RHUSER_PESSOA_RESPONSAVEL FROM rhuser_pessoa_resp_agrupador WHERE DT_FIM_RESPONSAVEL IS NULL AND CODIGO_EMPRESA = '0001' and TIPO_AGRUP = 'G' AND ID_AGRUP =
            (
            SELECT ID_AGRUP FROM RHORGA_AGRUPADOR WHERE CODIGO_EMPRESA = '0001' AND TIPO_AGRUP = 'G' AND COD_AGRUP1 = :OLD.COD_AGRUP1 AND COD_AGRUP2 = :OLD.COD_AGRUP2 AND COD_AGRUP3 = :OLD.COD_AGRUP3
            AND COD_AGRUP4 = :OLD.COD_AGRUP4 AND COD_AGRUP5 = :OLD.COD_AGRUP5 AND COD_AGRUP6 = :OLD.COD_AGRUP6
            ));
COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19

UPDATE rhuser_pessoa_resp_agrupador SET DT_FIM_RESPONSAVEL = SYSDATE, UPDATED = SYSDATE, UPDATEDBY = :NEW.LOGIN_USUARIO
WHERE ID =
      (SELECT ID FROM rhuser_pessoa_resp_agrupador WHERE DT_FIM_RESPONSAVEL IS NULL AND CODIGO_EMPRESA = '0001' and TIPO_AGRUP = 'G' AND ID_AGRUP =
            (
            SELECT ID_AGRUP FROM RHORGA_AGRUPADOR WHERE CODIGO_EMPRESA = '0001' AND TIPO_AGRUP = 'G' AND COD_AGRUP1 = :OLD.COD_AGRUP1 AND COD_AGRUP2 = :OLD.COD_AGRUP2 AND COD_AGRUP3 = :OLD.COD_AGRUP3
            AND COD_AGRUP4 = :OLD.COD_AGRUP4 AND COD_AGRUP5 = :OLD.COD_AGRUP5 AND COD_AGRUP6 = :OLD.COD_AGRUP6
            )
      );
commit;


-------------------------------------------------------------------------------------------XXX3ª PARTE -----------TROCOU O GESTOR DO LOCAL
ELSIF (UPDATING AND :OLD.CONTRATO_RESP <> :NEW.CONTRATO_RESP ) THEN

---****************PRIMEIRO FINALIZA O REGISTRO ABERTO NO ANTIGO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
--select * from RHUSER_PESSOA_RESPONSAVEL WHERE id = (Select id_rhuser_pessoa_responsavel From rhuser_pessoa_resp_agrupador
UPDATE RHUSER_PESSOA_RESPONSAVEL SET DT_FIM_RESPONSABILIDADE = SYSDATE, UPDATED = SYSDATE, UPDATEDBY = :NEW.LOGIN_USUARIO
WHERE DT_FIM_RESPONSABILIDADE is null and ID =
(SELECT ID_RHUSER_PESSOA_RESPONSAVEL FROM rhuser_pessoa_resp_agrupador WHERE DT_FIM_RESPONSAVEL IS NULL AND CODIGO_EMPRESA = '0001' and TIPO_AGRUP = 'G' AND ID_AGRUP =
            (
            SELECT ID_AGRUP FROM RHORGA_AGRUPADOR WHERE CODIGO_EMPRESA = '0001' AND TIPO_AGRUP = 'G' AND COD_AGRUP1 = :OLD.COD_AGRUP1 AND COD_AGRUP2 = :OLD.COD_AGRUP2 AND COD_AGRUP3 = :OLD.COD_AGRUP3
            AND COD_AGRUP4 = :OLD.COD_AGRUP4 AND COD_AGRUP5 = :OLD.COD_AGRUP5 AND COD_AGRUP6 = :OLD.COD_AGRUP6
            ));
COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19

UPDATE rhuser_pessoa_resp_agrupador SET DT_FIM_RESPONSAVEL = SYSDATE, UPDATED = SYSDATE, UPDATEDBY = :NEW.LOGIN_USUARIO
WHERE ID =
      (SELECT ID FROM rhuser_pessoa_resp_agrupador WHERE DT_FIM_RESPONSAVEL IS NULL AND CODIGO_EMPRESA = '0001' and TIPO_AGRUP = 'G' AND ID_AGRUP =
            (
            SELECT ID_AGRUP FROM RHORGA_AGRUPADOR WHERE CODIGO_EMPRESA = '0001' AND TIPO_AGRUP = 'G' AND COD_AGRUP1 = :OLD.COD_AGRUP1 AND COD_AGRUP2 = :OLD.COD_AGRUP2 AND COD_AGRUP3 = :OLD.COD_AGRUP3
            AND COD_AGRUP4 = :OLD.COD_AGRUP4 AND COD_AGRUP5 = :OLD.COD_AGRUP5 AND COD_AGRUP6 = :OLD.COD_AGRUP6
            )
      );
commit;


---****************SEGUNDO CRIA REGISTRO DO NOVO GESTOR
--tabela RHUSER_PESSOA_RESPONSAVEL
INSERT INTO RHUSER_PESSOA_RESPONSAVEL (
ID,
ID_PROCESSO,
ID_TAREFA,
CODIGO_EMPRESA,
CODIGO_USUARIO,
CODIGO_EMPRESA_PESSOA_RESP,
CODIGO_PESSOA_RESP,
CODIGO_CONTRATO_RESP,
TIPO_CONTRATO_RESP,
CODIGO_EMPRESA_CONTRATO,
DT_INICIO_RESPONSABILIDADE,
DT_FIM_RESPONSABILIDADE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
NOME_COMPOSTO,
MOTIVO_DELEGACAO,
ID_DELEGACAO_SUBSTITUICAO)
VALUES
(
(SELECT MAX(ID)+1 FROM RHUSER_PESSOA_RESPONSAVEL),
2,
NULL,
:NEW.CODIGO_EMPRESA,
:NEW.LOGIN_USUARIO,
:NEW.COD_EMPRESA_PESS,
:NEW.COD_PESSOA_RESP,
:NEW.CONTRATO_RESP,
:NEW.TIPO_CONT_RESP,
:NEW.COD_EMPRESA_PESS,
SYSDATE,
NULL,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
(select C.CODIGO||' - '||NVL(TRIM(P.NOME_SOCIAL),TRIM(P.NOME_ACESSO)) ||' - '||C.TIPO_CONTRATO||' - '|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))from RHPESS_CONTRATO C left outer join RHPESS_PESSOA P ON P.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND P.CODIGO = C.CODIGO_PESSOA WHERE C.ANO_MES_REFERENCIA = (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX where AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = C.TIPO_CONTRATO and AUX.CODIGO = C.CODIGO)AND C.CODIGO_EMPRESA = :NEW.COD_EMPRESA_PESS AND C.TIPO_CONTRATO = :NEW.TIPO_CONT_RESP AND C.CODIGO = :NEW.CONTRATO_RESP),
--:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| :NEW.DESCRICAO|| '-'|| :NEW.ABREVIACAO,
'F',
:NEW.ID_AGRUP
);
COMMIT;

--tabela rhuser_pessoa_resp_agrupador --NOVO EM 28/2/19

INSERT INTO rhuser_pessoa_resp_agrupador (
ID,
ID_RHUSER_PESSOA_RESPONSAVEL,
CODIGO_EMPRESA,
TIPO_AGRUP,
ID_AGRUP,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
DT_INICIO_RESPONSAVEL,
NOME_AGRUPADOR_COMPOSTO)
VALUES
(
(SELECT MAX(ID)+1 FROM rhuser_pessoa_resp_agrupador),
(SELECT MAX(ID) FROM RHUSER_PESSOA_RESPONSAVEL),
:NEW.CODIGO_EMPRESA,
'G',
:NEW.ID_AGRUP,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.LOGIN_USUARIO,
SYSDATE,
:NEW.COD_AGRUP1|| '.'|| :NEW.COD_AGRUP2|| '.'|| :NEW.COD_AGRUP3|| '.'|| :NEW.COD_AGRUP4|| '.'|| :NEW.COD_AGRUP5|| '.'|| :NEW.COD_AGRUP6|| '-'|| NVL(TRIM(:NEW.TEXTO_ASSOCIADO),TRIM(:NEW.DESCRICAO))|| '-'|| :NEW.ABREVIACAO
);
commit;

END IF;
*/ --fim----------------------------------------- versão com erro X-MEN no ORACLE
END;


--ALTER TRIGGER "ARTERH"."TR_SUGESP_RHORGA_AGRUP_TIPO_G" DISABLE
ALTER TRIGGER "ARTERH"."TR_SUGESP_RHORGA_AGRUP_TIPO_G" ENABLE