
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_SUGESP_NOME_COMPOSTO_AZC" 
AFTER INSERT OR UPDATE  ON "ARTERH"."RHPESS_CONTRATO"
FOR EACH ROW
 DECLARE
v_DML SUGESP_RHORGA_AGRUP_TIPO_G.TIPO_DML%TYPE;

BEGIN

IF INSERTING THEN
v_DML := 'I';
INSERT INTO SUGESP_NOME_COMPOSTO_AZC(
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
CODIGO_PESSOA,
NEW_NOME_ACESSO,
OLD_NOME_ACESSO,
NEW_COD_CUSTO_GERENC1,
NEW_COD_CUSTO_GERENC2,
NEW_COD_CUSTO_GERENC3,
NEW_COD_CUSTO_GERENC4,
NEW_COD_CUSTO_GERENC5,
NEW_COD_CUSTO_GERENC6,
OLD_COD_CUSTO_GERENC1,
OLD_COD_CUSTO_GERENC2,
OLD_COD_CUSTO_GERENC3,
OLD_COD_CUSTO_GERENC4,
OLD_COD_CUSTO_GERENC5,
OLD_COD_CUSTO_GERENC6,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
TIPO_DML,
ATUALIZOU
)
VALUES
(
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO,
:NEW.CODIGO_PESSOA,
:NEW.NOME_ACESSO,
NULL,
:NEW.COD_CUSTO_GERENC1,
:NEW.COD_CUSTO_GERENC2,
:NEW.COD_CUSTO_GERENC3,
:NEW.COD_CUSTO_GERENC4,
:NEW.COD_CUSTO_GERENC5,
:NEW.COD_CUSTO_GERENC6,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
v_DML,
'N'
);
END IF;
IF UPDATING THEN
v_DML := 'U';
INSERT INTO SUGESP_NOME_COMPOSTO_AZC(
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
CODIGO_PESSOA,
NEW_NOME_ACESSO,
OLD_NOME_ACESSO,
NEW_COD_CUSTO_GERENC1,
NEW_COD_CUSTO_GERENC2,
NEW_COD_CUSTO_GERENC3,
NEW_COD_CUSTO_GERENC4,
NEW_COD_CUSTO_GERENC5,
NEW_COD_CUSTO_GERENC6,
OLD_COD_CUSTO_GERENC1,
OLD_COD_CUSTO_GERENC2,
OLD_COD_CUSTO_GERENC3,
OLD_COD_CUSTO_GERENC4,
OLD_COD_CUSTO_GERENC5,
OLD_COD_CUSTO_GERENC6,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
TIPO_DML,
ATUALIZOU
)
VALUES
(
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO,
:NEW.CODIGO_PESSOA,
:NEW.NOME_ACESSO,
:OLD.NOME_ACESSO,
:NEW.COD_CUSTO_GERENC1,
:NEW.COD_CUSTO_GERENC2,
:NEW.COD_CUSTO_GERENC3,
:NEW.COD_CUSTO_GERENC4,
:NEW.COD_CUSTO_GERENC5,
:NEW.COD_CUSTO_GERENC6,
:OLD.COD_CUSTO_GERENC1,
:OLD.COD_CUSTO_GERENC2,
:OLD.COD_CUSTO_GERENC3,
:OLD.COD_CUSTO_GERENC4,
:OLD.COD_CUSTO_GERENC5,
:OLD.COD_CUSTO_GERENC6,
:NEW.LOGIN_USUARIO,
:NEW.DT_ULT_ALTER_USUA,
v_DML,
'N'
);
END IF;
END;




ALTER TRIGGER "ARTERH"."TR_SUGESP_NOME_COMPOSTO_AZC" ENABLE