
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TR_SUGESP_RHPONT_ALT_ESCALA" 
BEFORE INSERT OR UPDATE OR DELETE ON ARTERH.RHPONT_ALT_ESCALA
FOR EACH ROW
 DECLARE
vULT_ID number;
v_DML ARTERH.SUGESP_RHPONT_ALT_ESCALA_LOG.TIPO_DML%TYPE;

    vLOGIN_USUARIO_NEW VARCHAR2(40);
    vLOGIN_USUARIO_OLD VARCHAR2(40);
    vLOGIN_OS_NEW VARCHAR2(40);
    vLOGIN_OS_OLD VARCHAR2(40);
    vLOGIN_NEW VARCHAR2(40);
    vLOGIN_OLD VARCHAR2(40);
--PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
--POPULA VARIAVEIS
vULT_ID := 0;
    vLOGIN_USUARIO_NEW := :NEW.LOGIN_USUARIO;
    vLOGIN_USUARIO_OLD := :OLD.LOGIN_USUARIO;
    vLOGIN_OS_NEW := SYS_CONTEXT ('USERENV', 'OS_USER');
    vLOGIN_OS_OLD := SYS_CONTEXT ('USERENV', 'OS_USER');
--definir login a usar NEW
    IF vLOGIN_USUARIO_NEW = 'ARTERH_UPBH' then
    vLOGIN_NEW := vLOGIN_OS_NEW;
    ELSE
    vLOGIN_NEW := vLOGIN_USUARIO_NEW;
    END IF;
--definir login a usar OLD
    IF vLOGIN_USUARIO_OLD = 'ARTERH_UPBH' then
    vLOGIN_NEW := vLOGIN_OS_OLD;
    ELSE
    vLOGIN_OLD := vLOGIN_USUARIO_OLD;
    END IF;
--------------------------------------------------------------------------INSERT-------------------------------------------------------------------------------------------------------------------------------------------
IF INSERTING THEN
v_DML := 'I';
INSERT INTO ARTERH.SUGESP_RHPONT_ALT_ESCALA_LOG
(
ID,
TIPO_DML,
NEW_CODIGO_EMPRESA,
NEW_TIPO_CONTRATO,
NEW_CODIGO_CONTRATO,
NEW_DT_INICIO_TROCA,
NEW_DT_FIM_TROCA,
NEW_COD_ESCALA,
NEW_COD_MOTIVO,
NEW_ALTER_DEFINITIVA,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
ARTERH.SEQUENCE_RHPONT_ALT_ESCALA.NEXTVAL,
v_DML,
:NEW.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO,
:NEW.DT_INICIO_TROCA,
:NEW.DT_FIM_TROCA,
:NEW.COD_ESCALA,
:NEW.COD_MOTIVO,
:NEW.ALTER_DEFINITIVA,
:NEW.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
-------------------------------------------------------------------------UPDATE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF UPDATING THEN
v_DML := 'U';
INSERT INTO ARTERH.SUGESP_RHPONT_ALT_ESCALA_LOG
(
ID,
TIPO_DML,
NEW_CODIGO_EMPRESA,
OLD_CODIGO_EMPRESA,
NEW_TIPO_CONTRATO,
OLD_TIPO_CONTRATO,
NEW_CODIGO_CONTRATO,
OLD_CODIGO_CONTRATO,
NEW_DT_INICIO_TROCA,
OLD_DT_INICIO_TROCA,
NEW_DT_FIM_TROCA,
OLD_DT_FIM_TROCA,
NEW_COD_ESCALA,
OLD_COD_ESCALA,
NEW_COD_MOTIVO,
OLD_COD_MOTIVO,
NEW_ALTER_DEFINITIVA,
OLD_ALTER_DEFINITIVA,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
ARTERH.SEQUENCE_RHPONT_ALT_ESCALA.NEXTVAL,
v_DML,
:NEW.CODIGO_EMPRESA,
:OLD.CODIGO_EMPRESA,
:NEW.TIPO_CONTRATO,
:OLD.TIPO_CONTRATO,
:NEW.CODIGO_CONTRATO,
:OLD.CODIGO_CONTRATO,
:NEW.DT_INICIO_TROCA,
:OLD.DT_INICIO_TROCA,
:NEW.DT_FIM_TROCA,
:OLD.DT_FIM_TROCA,
:NEW.COD_ESCALA,
:OLD.COD_ESCALA,
:NEW.COD_MOTIVO,
:OLD.COD_MOTIVO,
:NEW.ALTER_DEFINITIVA,
:OLD.ALTER_DEFINITIVA,
:NEW.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
--------------------------------------------------------------------------DELETE-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF DELETING THEN
v_DML := 'D';
INSERT INTO ARTERH.SUGESP_RHPONT_ALT_ESCALA_LOG
(
ID,
TIPO_DML,
OLD_CODIGO_EMPRESA,
OLD_TIPO_CONTRATO,
OLD_CODIGO_CONTRATO,
OLD_DT_INICIO_TROCA,
OLD_DT_FIM_TROCA,
OLD_COD_ESCALA,
OLD_COD_MOTIVO,
OLD_ALTER_DEFINITIVA,
LOGIN_USUARIO,
LOGIN_OS,
DT_ULT_ALTER_USUA
)
VALUES
(
ARTERH.SEQUENCE_RHPONT_ALT_ESCALA.NEXTVAL,
v_DML,
:OLD.CODIGO_EMPRESA,
:OLD.TIPO_CONTRATO,
:OLD.CODIGO_CONTRATO,
:OLD.DT_INICIO_TROCA,
:OLD.DT_FIM_TROCA,
:OLD.COD_ESCALA,
:OLD.COD_MOTIVO,
:OLD.ALTER_DEFINITIVA,
:OLD.LOGIN_USUARIO,-- ATE 26/4/19 :OLD.LOGIN_USUARIO,
SYS_CONTEXT ('USERENV', 'OS_USER'),
SYSDATE
);
--COMMIT;--ORA-04092: cannot COMMIT in a trigger
END IF; --FIM IF PARA SABER SE Ãƒâ€° INSERT, UPDATE ou DELETE
END; --FIM TRIGGER




ALTER TRIGGER "ARTERH"."TR_SUGESP_RHPONT_ALT_ESCALA" ENABLE