
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TRG_ID_RHPBH_LOGIN_AD" BEFORE INSERT ON ARTERH.RHPBH_LOGIN_AD FOR EACH ROW
BEGIN
  IF :NEW.ID_RHPBH_LOGIN_AD IS NULL THEN
    SELECT ARTERH.SQ_RHPBH_LOGIN_AD.NEXTVAL INTO :NEW.ID_RHPBH_LOGIN_AD FROM DUAL;
  END IF;
END;




ALTER TRIGGER "ARTERH"."TRG_ID_RHPBH_LOGIN_AD" ENABLE