
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTERH"."TRG_ID_RHPBH_REGISTRO_AD" 
  BEFORE INSERT ON ARTERH.RHPBH_REGISTRO_AD FOR EACH ROW 
 BEGIN 
  IF :NEW.ID_RHPBH_REGISTRO_AD IS NULL THEN
    SELECT ARTERH.SQ_RHPBH_REGISTRO_AD.NEXTVAL INTO :NEW.ID_RHPBH_REGISTRO_AD FROM DUAL;
  END IF;
END;




ALTER TRIGGER "ARTERH"."TRG_ID_RHPBH_REGISTRO_AD" ENABLE