
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."DEPENDENTES" ("COD_ORG", "MATRICULA", "CPF_SEGURADO", "NOME_DEPENDENTE", "SEXO", "NOME_MAE_DEPE", "DATA_NASCIMENTO_DEPE", "INICIO_DEPENDENCIA", "SEQUENCIAL_PESSOA_DEPE", "CPF", "GRAU_PARENTESCO", "MOTIVO_INICIO_DEPE", "NOME_PAI", "ESTADO_CIVIL", "FIM_DEPE", "MOTIVO_FIM_DEPE", "NUMERO_CERTI_NASCIMENTO", "NUMERO_LIVRO", "NUMERO_FOLHA_NASCIMENTO", "NUMERO_RG", "COD_ORGAO_EMITENTE_RG", "DATA_EXPEDICAO_RG", "UF_ORGAO_EMISSOR_RG", "NACIONALIDADE", "NATURALIDADE", "UF_NATURALIDADE", "DEP_ABONO_FAMILIA", "DEP_IMPOSTO_RENDA") AS 
  SELECT 
      CASE SUBSTR(CO.COD_LOCAL1,5,2)||SUBSTR(CO.COD_LOCAL2,5,2)||SUBSTR(CO.COD_LOCAL3,5,2)||SUBSTR(CO.COD_LOCAL4,5,2)
      WHEN '99990100' THEN 0001/*ADMINISTRAÃ‡ÃƒO DIRETA*/
      WHEN '99990200' THEN 0001/*ADMINISTRAÃ‡ÃƒO DIRETA*/
      WHEN '99990101' THEN 0006/*BEPREM*/
      WHEN '99990102' THEN 0002/*CMBH*/
      WHEN '99990103' THEN 0005/*HOB*/
      WHEN '99990104' THEN 0003/*FPMZB*/
      WHEN '99990105' THEN 0003/*FPMZB*/
      WHEN '99990205' THEN 0003/*FPMZB*/
      WHEN '99990106' THEN 0004/*FMC*/
      WHEN '99990206' THEN 0004/*FMC*/
      ELSE 0001
    END AS COD_ORG,
        TO_NUMBER(SUBSTR(CO.CODIGO, 5,10)) ||CASE WHEN SUBSTR(CO.CODIGO, 15,1) != 'X' THEN TO_NUMBER(SUBSTR(CO.CODIGO, 15,1)) ELSE 7 END AS MATRICULA,
         SUBSTR(PS.CPF, 1,11) AS CPF_SEGURADO,
         SUBSTR(TRIM(PE.NOME),1,80) AS NOME_DEPENDENTE,
         CASE         
          WHEN  PE.SEXO = '0001'  THEN  'M'
          WHEN  PE.SEXO = '0002'  THEN  'F'
          ELSE 'M'
         END AS SEXO,
         CASE WHEN SUBSTR(PE.C_LIVRE_DESCR12,1,80) IS NULL THEN 'NÃO POSSUI NO CADASTRO' ELSE SUBSTR(TRIM(PE.C_LIVRE_DESCR12),1,80) END AS NOME_MAE_DEPE, 
         TO_CHAR(PE.DATA_NASCIMENTO, 'YYYYMMDD') AS DATA_NASCIMENTO_DEPE,
         TO_CHAR(D.DATA_INICIO, 'YYYYMMDD') AS INICIO_DEPENDENCIA,
         row_number() OVER (PARTITION BY substr(PS.CPF,1,11) ORDER BY CO.CODIGO_PESSOA) AS SEQUENCIAL_PESSOA_DEPE,       
         SUBSTR(PE.CPF, 1,11) AS CPF,
         CASE 
          WHEN PP.TP_RELACIONAMENTO = '0016' AND PE.CPF IN('01702674665','00475071603','06803742644','01735316601','53089413604','08346534604','37347020620','03833804645') THEN '07'
          WHEN PP.TP_RELACIONAMENTO = '0016' AND PE.CPF NOT IN('01702674665','00475071603','06803742644','01735316601','53089413604','08346534604','37347020620','03833804645') THEN '06'
          WHEN PP.TP_RELACIONAMENTO = '0017' THEN '14'
          WHEN PP.TP_RELACIONAMENTO = '0029' THEN '08'
          WHEN PP.TP_RELACIONAMENTO = '0034' THEN '05'
          WHEN PP.TP_RELACIONAMENTO = '0001' THEN '01'
          WHEN PP.TP_RELACIONAMENTO = '0002' THEN '03'
          WHEN PP.TP_RELACIONAMENTO = '0003' THEN '02'
          WHEN PP.TP_RELACIONAMENTO = '0004' THEN '05'
          WHEN PP.TP_RELACIONAMENTO = '0005' THEN '05'
          WHEN PP.TP_RELACIONAMENTO = '0006' THEN '10'
          WHEN PP.TP_RELACIONAMENTO = '0009' THEN '00'
          WHEN PP.TP_RELACIONAMENTO = '0031' THEN '13'
          WHEN PP.TP_RELACIONAMENTO = '0032' THEN '13'
          WHEN PP.TP_RELACIONAMENTO = '0015' THEN '10'
          WHEN PP.TP_RELACIONAMENTO = '0019' THEN '04'
          WHEN PP.TP_RELACIONAMENTO = '0020' THEN '04'
          WHEN PP.TP_RELACIONAMENTO = '0021' THEN '03'
          WHEN PP.TP_RELACIONAMENTO = '0024' THEN '05'
          WHEN PP.TP_RELACIONAMENTO = '0026' THEN '02'
          WHEN PP.TP_RELACIONAMENTO = '9999'  THEN '01'
          ELSE '00'
         END AS GRAU_PARENTESCO,
         CASE PP.TP_RELACIONAMENTO 
          WHEN '0001' THEN '12'  /*CASAMENTO*/
          WHEN '0002' THEN '10' /*NASCIMENTO*/
          WHEN '0003' THEN '13' /*UNIÃƒO ESTÃ?VEL*/
          WHEN '0009' THEN '98' /*OUTROS INICIO*/
          WHEN '0015' THEN '18' /*TUTELA*/
          WHEN '0019' THEN '11' /* INVALIDEZ*/
          WHEN '0020' THEN '11' /*INVALIDEZ*/
          WHEN '0021' THEN '16' /* DEPENDÃŠNCIA ECONÃ”MICO*/
          WHEN '0025' THEN '16' /*DEPENDÃŠNCIA ECONÃ”MICA*/
          WHEN '0005' THEN '16' /* DEPENDÃŠNCIA ECONÃ”MICA*/
          WHEN '0026' THEN '12' /* CASAMENTO*/
          WHEN '9999' THEN '12' /* CASAMENTO*/
         ELSE '98'
          END AS MOTIVO_INICIO_DEPE,
         SUBSTR(TRIM(PE.C_LIVRE_DESCR11),1,80) AS NOME_PAI,
      CASE          
    WHEN  PE.ESTADO_CIVIL = '0001'  THEN  'C' /*Casado*/
    WHEN  PE.ESTADO_CIVIL = '0002'  THEN  'S' /*Solteiro*/
    WHEN  PE.ESTADO_CIVIL = '0005'  THEN  'D' /*Divorciado*/
    WHEN  PE.ESTADO_CIVIL = '0003'  THEN  'V' /*ViÃºvo*/
    WHEN  PE.ESTADO_CIVIL = '0009'  THEN  'P' /*Separado*/
    WHEN  PE.ESTADO_CIVIL = '0008'  THEN  'U' /*UniÃ£o Estavel*/
    WHEN  PE.ESTADO_CIVIL = '0004'  THEN  'P' /*Desquitado*/
    WHEN  PE.ESTADO_CIVIL = '0006'  THEN  'D' /*SeparaÃ§Ã£o Judicial*/
    ELSE  'U' /*Outros*/
    END AS ESTADO_CIVIL,
         trim(TO_CHAR(D.DATA_FIM, 'YYYYMMDD')) AS FIM_DEPE,
         NULL AS MOTIVO_FIM_DEPE,/*MOTIVO FIM - NÃƒO POSSUI*/
        substr(TRIM(PE.CERT_NASCIMENTO),1,20) AS NUMERO_CERTI_NASCIMENTO,
         NULL AS NUMERO_LIVRO,
         NULL AS NUMERO_FOLHA_NASCIMENTO, /*NÃƒO EXISTE - Numero Livro, Numero Folha Nascimento*/
         trim(PE.IDENTIDADE) AS NUMERO_RG,
         CASE             
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%SSP%' THEN  '1'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%AERONAUT%'  THEN  '2'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%EXERCITO%'  THEN  '3'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%MARINHA%' THEN  '4'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%PF%'  THEN  '5'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRA%' THEN  '6'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRAS%'  THEN  '7'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRB%' THEN  '8'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRC%' THEN  '9'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRECI%' THEN  '10'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CORECON%' THEN  '11'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%COREN%' THEN  '12'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CREA  %'  THEN  '13'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CONRE%' THEN  '14'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRF%' THEN  '15'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CREFITO%' THEN  '16'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRM%' THEN  '17'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRMV%'  THEN  '18'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%OMBCRE%'  THEN  '19'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRN%' THEN  '20'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRO%' THEN  '21'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CONRERP%' THEN  '22'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRP%' THEN  '23'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRQ%' THEN  '24'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CORE%'  THEN  '25'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%OAB%' THEN  '26'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRBIO%' THEN  '27'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRFA%'  THEN  '28'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CORESS%'  THEN  '29'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CRTR%'  THEN  '30'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%DETRA%'  THEN  '31'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%PM%'  THEN  '32'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%CBM%' THEN  '33'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%IBA%' THEN  '34'
          WHEN  PE.ORGAO_EXPEDIDOR  LIKE  '%OUTROS%'  THEN  '99'
        END AS COD_ORGAO_EMITENTE_RG,
        TRIM(TO_CHAR(PE.DATA_EXPEDICAO, 'YYYYMMDD'))AS DATA_EXPEDICAO_RG, 
        substr(TRIM(PE.UF_IDENTIDADE),1,2) AS UF_ORGAO_EMISSOR_RG,
        SUBSTR(TRIM(NACIONALID.DESCRICAO),1,80) AS NACIONALIDADE,
        SUBSTR(TRIM(NATURALID.DESCRICAO),1,80) AS NATURALIDADE,    
        substr(TRIM(NATURALID.UF),1,2) AS UF_NATURALIDADE,
        CASE WHEN D.cod_classe_depend = '0001' THEN 'S' ELSE 'N' END AS DEP_ABONO_FAMILIA,
        CASE WHEN D.cod_classe_depend = '0002' THEN 'S' ELSE 'N' END AS DEP_IMPOSTO_RENDA


    FROM RHPESS_CONTRATO CO,

         RHPESS_PESSOA PS, 
         RHPESS_PESSOA PE,
         RHPESS_RL_PESS_PES PP,
         RHORGA_LOTACAO LO,
         RHTABS_NACIONALID NACIONALID,
         RHTABS_MUNICIPIO NATURALID,
         (SELECT 
         RHPESS_DEPENDENCIA.codigo_contrato,
         RHPESS_DEPENDENCIA.codigo_empresa,
         RHPESS_CONTRATO.TIPO_CONTRATO,
         RHPESS_DEPENDENCIA.codigo_pessoa,
         RHPESS_DEPENDENCIA.DATA_FIM,
         RHPESS_DEPENDENCIA.DATA_INICIO,
         trim(rhpess_pessoa.cpf) cpf,
         RHPESS_DEPENDENCIA.cod_classe_depend


  from RHPESS_DEPENDENCIA,RHPESS_PESSOA,RHPESS_CONTRATO   

        WHERE RHPESS_DEPENDENCIA.codigo_pessoa = RHPESS_PESSOA.codigo and   
        RHPESS_DEPENDENCIA.codigo_contrato = RHPESS_CONTRATO.CODIGO and 
              RHPESS_DEPENDENCIA.codigo_empresa = RHPESS_CONTRATO.CODIGO_EMPRESA and    
        RHPESS_CONTRATO.TIPO_CONTRATO =  RHPESS_DEPENDENCIA.TIPO_CONTRATO and 
              RHPESS_DEPENDENCIA.cod_classe_depend in('0002','0001') and    
              (RHPESS_DEPENDENCIA.data_fim  is null OR RHPESS_DEPENDENCIA.data_fim > add_months(sysdate,(-1))-0) AND   
              (RHPESS_DEPENDENCIA.data_inicio <= add_months(sysdate, -1) OR RHPESS_DEPENDENCIA.data_inicio IS NULL) AND   
        ( rhpess_pessoa.CODIGO_EMPRESA  = RHPESS_CONTRATO.CODIGO_EMPRESA ) and      
              ( RHPESS_CONTRATO.SITUACAO_FUNCIONAL NOT IN ('1710','1715','1800','1850','1900','5000','5001','5002','5003','5004','5005','5006',
                                  '5008','5009','5011', '5019', '5022','5026','5028','5200','5201','5400','5555','5700','5800',
                                  '5801', '5808', '5900','5901','6002','6003','8000'))AND   
              ( RHPESS_CONTRATO.CODIGO_EMPRESA IN('0001', '0013', '0014') ) AND     
              ( RHPESS_CONTRATO.TIPO_CONTRATO = '0001' AND RHPESS_CONTRATO.VINCULO IN ('0000', '0002')) AND    
        ( RHPESS_CONTRATO.ANO_MES_REFERENCIA = (SELECT MAX(A.ANO_MES_REFERENCIA)                                                    
                                                   FROM RHPESS_CONTRATO A                                                   
                                                   WHERE A.CODIGO = RHPESS_CONTRATO.CODIGO AND                                                  
                                                   A.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA AND                                                  
                                                   A.TIPO_CONTRATO = RHPESS_CONTRATO.TIPO_CONTRATO AND                                                
                                                   A.ANO_MES_REFERENCIA <= add_months(sysdate,(-1))-0))  

  group by RHPESS_DEPENDENCIA.codigo_contrato,
           RHPESS_DEPENDENCIA.codigo_empresa,
           RHPESS_CONTRATO.TIPO_CONTRATO,
           RHPESS_DEPENDENCIA.codigo_pessoa,
           RHPESS_DEPENDENCIA.DATA_FIM,
           RHPESS_DEPENDENCIA.DATA_INICIO,
           rhpess_pessoa.cpf,
           RHPESS_DEPENDENCIA.cod_classe_depend)D



      WHERE 


           CO.CODIGO_EMPRESA = D.CODIGO_EMPRESA 
           AND CO.TIPO_CONTRATO =  D.TIPO_CONTRATO  
           AND CO.CODIGO = D.CODIGO_CONTRATO
           AND CO.CODIGO_EMPRESA = PS.CODIGO_EMPRESA 
           AND CO.CODIGO_PESSOA = PS.CODIGO
           AND CO.CODIGO_EMPRESA = PE.CODIGO_EMPRESA 
           AND D.CODIGO_PESSOA = PE.CODIGO
           AND PP.COD_PESSOA = PS.CODIGO 
           AND PP.COD_PESSOA_RELAC = PE.CODIGO
           AND PP.COD_EMPRESA = PE.CODIGO_EMPRESA
           AND CO.COD_LOCAL1 = LO.COD_LOTACAO1 
           AND CO.COD_LOCAL2 = LO.COD_LOTACAO2 
           AND CO.COD_LOCAL3 = LO.COD_LOTACAO3 
           AND CO.COD_LOCAL4 = LO.COD_LOTACAO4 
           AND CO.COD_LOCAL5 = LO.COD_LOTACAO5 
           AND CO.COD_LOCAL6 = LO.COD_LOTACAO6
           AND CO.CODIGO_EMPRESA = LO.CODIGO_EMPRESA
           AND NACIONALID.CODIGO(+) = PE.NACIONALIDADE
           AND NATURALID.CODIGO(+) = PE.COD_MUNICIPIO 
           AND (CO.CODIGO < '000000099999999' AND CO.CODIGO NOT IN('000000000777777','000000000823701','000000000833014','000000000866265','000000000747428')) /*FALECIDOS PIA*/
           AND CO.SITUACAO_FUNCIONAL NOT IN ('1710','1715','1800','1850','1900','5000','5001','5002','5003','5004','5005','5006',
                                  '5008','5009','5011', '5019', '5022','5026','5028','5200','5201','5400','5555','5700','5800',
                                  '5801', '5808', '5900','5901','6002','6003','8000')


            AND CO.CODIGO_EMPRESA IN('0001', '0013', '0014')
            AND CO.TIPO_CONTRATO  = '0001'
            AND CO.VINCULO IN('0000', '0002')

            AND PP.tp_relacionamento IN('0033','0003','0030','0029','0001','0002','0019','0016','0022','0028','0005','0015','0031','0009','0018','0004','0034','0024','0017','0041','0006') 

            AND CO.ANO_MES_REFERENCIA  = (SELECT MAX(A.ANO_MES_REFERENCIA) 
                                           FROM RHPESS_CONTRATO A
                                          WHERE A.CODIGO = CO.CODIGO AND A.CODIGO_EMPRESA = CO.CODIGO_EMPRESA AND A.TIPO_CONTRATO = CO.TIPO_CONTRATO AND A.ANO_MES_REFERENCIA <= add_months(sysdate,(-1))-0)

  GROUP BY CO.COD_LOCAL1,
           CO.COD_LOCAL2,
           CO.COD_LOCAL3,
           CO.COD_LOCAL4,
           CO.CODIGO,
           PS.CPF,
           PE.NOME,
           PE.SEXO,
           PE.C_LIVRE_DESCR12,
           PE.DATA_NASCIMENTO,
           D.DATA_INICIO,       
           PE.CPF,
           PP.TP_RELACIONAMENTO, 
           PE.C_LIVRE_DESCR11,
         PE.ESTADO_CIVIL,
           D.DATA_FIM,
           PE.CERT_NASCIMENTO,
           PE.IDENTIDADE,
           PE.ORGAO_EXPEDIDOR, 
           PE.DATA_EXPEDICAO, 
           PE.UF_IDENTIDADE,
           NACIONALID.DESCRICAO,
           NATURALID.DESCRICAO,    
           NATURALID.UF,
           D.cod_classe_depend,
           D.CODIGO_PESSOA,
           CO.CODIGO_PESSOA