
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."V_RH_REL_5035_5009" ("STATUS_RELATORIO", "CODIGO_EMPRESA", "TIPO_CONTRATO", "MATRICULA", "NOME", "CPF", "DATA_ADMISSAO", "DATA_RESCISAO", "TIPO_CARGO", "CARGO", "DESC_CARGO", "CODIGO_FUNCAO", "DESC_FUNCAO", "COD_ESPECIALIDADE", "DESC_ESPECIALIDADE", "COD_UNIDADE", "UNIDADE", "ABREVIACAO_UNIDADE", "DIRETORIA", "ABREVIACAO_DIRETORIA", "SUPERINTENDENCIA", "ABREVIACAO_SUPERINTENDENCIA", "SALARIO") AS 
  SELECT 'ADMITIDOS' AS STATUS_RELATORIO, CNT.CODIGO_EMPRESA,
       CNT.TIPO_CONTRATO,
       SUBSTR(CNT.CODIGO,7,8) || '-' ||SUBSTR(CNT.CODIGO,15,1) AS MATRICULA,       
       CNT.NOME,
       PE.CPF,
       CNT.DATA_ADMISSAO,
       CNT.DATA_RESCISAO,       
       CASE 
         WHEN CNT.SALARIO_PAGTO = 'E' THEN 'EFETIVO'
         WHEN CNT.SALARIO_PAGTO = 'C' THEN 'COMISSIONADO'
         WHEN CNT.SALARIO_PAGTO = 'A' THEN 'AMPARADO'
         WHEN CNT.SALARIO_PAGTO = 'P' THEN 'PAGAMENTO'
       ELSE 'FUNÇÃO' END TIPO_CARGO,              
       CNT.COD_CARGO_PAGTO AS CARGO,
       CG.DESCRICAO AS DESC_CARGO,
       CNT.CODIGO_FUNCAO,
       FUN.DESCRICAO AS DESC_FUNCAO,
       CNT.COD_ESPECIALIDADE,
       ESP.DESCRICAO AS DESC_ESPECIALIDADE,
       SUBSTR(CNT.COD_UNIDADE1,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE2,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE3,5,2) || '.' ||
       SUBSTR(CNT.COD_UNIDADE4,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE5,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE6,4,3) AS COD_UNIDADE,       
       GER.DESCRICAO AS UNIDADE,
       GER.ABREVIACAO AS ABREVIACAO_UNIDADE,
       DIR.DESCRICAO AS DIRETORIA,
       DIR.ABREVIACAO AS ABREVIACAO_DIRETORIA,
       SUP.DESCRICAO AS SUPERINTENDENCIA,
       SUP.ABREVIACAO AS ABREVIACAO_SUPERINTENDENCIA,
       MAX(CASE WHEN CNT.SALARIO_PAGTO = 'E' THEN SAL.SAL_CONTR_EFET12 ELSE SAL.SAL_CONTR_COMIS12 END) AS SALARIO
FROM ARTERH.RHPESS_CONTRATO CNT
     INNER JOIN ARTERH.RHPESS_PESSOA PE           ON PE.CODIGO            = CNT.CODIGO_PESSOA
                                                 AND PE.CODIGO_EMPRESA    = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHPLCS_CARGO CG            ON CG.CODIGO = CNT.COD_CARGO_PAGTO
                                                 AND CG.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     LEFT JOIN ARTERH.RHORGA_UNIDADE GER     ON GER.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND GER.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND GER.COD_UNIDADE3 = CNT.COD_UNIDADE3
                                                 AND GER.COD_UNIDADE4 = CNT.COD_UNIDADE4
                                                 AND GER.COD_UNIDADE5 = CNT.COD_UNIDADE5
                                                 AND GER.COD_UNIDADE6 = CNT.COD_UNIDADE6
                                                 AND GER.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHORGA_UNIDADE SUP     ON SUP.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND SUP.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND SUP.COD_UNIDADE3 = CNT.COD_UNIDADE3
                                                 AND SUP.COD_UNIDADE4 = '000000'
                                                 AND SUP.COD_UNIDADE5 = '000000'
                                                 AND SUP.COD_UNIDADE6 = '000000'
                                                 AND SUP.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHORGA_UNIDADE DIR     ON DIR.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND DIR.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND DIR.COD_UNIDADE3 = '000000'
                                                 AND DIR.COD_UNIDADE4 = '000000'
                                                 AND DIR.COD_UNIDADE5 = '000000'
                                                 AND DIR.COD_UNIDADE6 = '000000'
                                                 AND DIR.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHPLCS_FUNCAO FUN           ON FUN.CODIGO = CNT.CODIGO_FUNCAO
                                                 AND FUN.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     LEFT JOIN ARTERH.RHPLCS_ESPECIALID ESP       ON ESP.CODIGO = CNT.COD_ESPECIALIDADE
                                                 AND ESP.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     INNER JOIN ARTERH.RHPESS_SALARIOS SAL ON SAL.CODIGO = CNT.CODIGO
                                          AND SAL.TIPO_CONTRATO = CNT.TIPO_CONTRATO
                                          AND SAL.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
WHERE 1 = 1
AND CNT.ANO_MES_REFERENCIA  = ( SELECT MAX (CNT2.ANO_MES_REFERENCIA)
        								  FROM ARTERH.RHPESS_CONTRATO CNT2
        								  WHERE CNT2.CODIGO              = CNT.CODIGO											  
        								  AND   TRUNC(CNT2.ANO_MES_REFERENCIA) <= (SELECT DT_MAX_DATAS FROM ARTERH.RHPARM_P_SIST)
        								  AND   CNT2.TIPO_CONTRATO       = CNT.TIPO_CONTRATO
        								  AND   CNT2.CODIGO_EMPRESA      = CNT.CODIGO_EMPRESA)
AND CNT.CODIGO_EMPRESA = '0002'
AND CNT.TIPO_CONTRATO = '0001'
AND CNT.DATA_ADMISSAO BETWEEN TO_DATE('01/01' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY')) 
                          AND TO_DATE('31/12' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY'))
AND SAL.ANO_BASE = TO_DATE('01/01' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY'))

GROUP BY CNT.CODIGO_EMPRESA,
       CNT.TIPO_CONTRATO,
       SUBSTR(CNT.CODIGO,7,8) || '-' ||SUBSTR(CNT.CODIGO,15,1),       
       CNT.NOME,
       PE.CPF,
       CNT.DATA_ADMISSAO,
       CNT.DATA_RESCISAO,       
       CASE 
         WHEN CNT.SALARIO_PAGTO = 'E' THEN 'EFETIVO'
         WHEN CNT.SALARIO_PAGTO = 'C' THEN 'COMISSIONADO'
         WHEN CNT.SALARIO_PAGTO = 'A' THEN 'AMPARADO'
         WHEN CNT.SALARIO_PAGTO = 'P' THEN 'PAGAMENTO'
       ELSE 'FUNÇÃO' END,              
       CNT.COD_CARGO_PAGTO,
       CG.DESCRICAO,
       CNT.CODIGO_FUNCAO,
       FUN.DESCRICAO,
       CNT.COD_ESPECIALIDADE,
       ESP.DESCRICAO,
       SUBSTR(CNT.COD_UNIDADE1,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE2,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE3,5,2) || '.' ||
       SUBSTR(CNT.COD_UNIDADE4,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE5,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE6,4,3),       
       GER.DESCRICAO,
       GER.ABREVIACAO,
       DIR.DESCRICAO,
       DIR.ABREVIACAO,
       SUP.DESCRICAO,
       SUP.ABREVIACAO
UNION ALL
SELECT 'DEMITIDOS' AS STATUS_RELATORIO, CNT.CODIGO_EMPRESA,
       CNT.TIPO_CONTRATO,
       SUBSTR(CNT.CODIGO,7,8) || '-' ||SUBSTR(CNT.CODIGO,15,1) AS MATRICULA,       
       CNT.NOME,
       PE.CPF,
       CNT.DATA_ADMISSAO,
       CNT.DATA_RESCISAO,       
       CASE 
         WHEN CNT.SALARIO_PAGTO = 'E' THEN 'EFETIVO'
         WHEN CNT.SALARIO_PAGTO = 'C' THEN 'COMISSIONADO'
         WHEN CNT.SALARIO_PAGTO = 'A' THEN 'AMPARADO'
         WHEN CNT.SALARIO_PAGTO = 'P' THEN 'PAGAMENTO'
       ELSE 'FUNÇÃO' END TIPO_CARGO,              
       CNT.COD_CARGO_PAGTO AS CARGO,
       CG.DESCRICAO AS DESC_CARGO,
       CNT.CODIGO_FUNCAO,
       FUN.DESCRICAO AS DESC_FUNCAO,
       CNT.COD_ESPECIALIDADE,
       ESP.DESCRICAO AS DESC_ESPECIALIDADE,
       SUBSTR(CNT.COD_UNIDADE1,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE2,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE3,5,2) || '.' ||
       SUBSTR(CNT.COD_UNIDADE4,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE5,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE6,4,3) AS COD_UNIDADE,       
       GER.DESCRICAO AS UNIDADE,
       GER.ABREVIACAO AS ABREVIACAO_UNIDADE,
       DIR.DESCRICAO AS DIRETORIA,
       DIR.ABREVIACAO AS ABREVIACAO_DIRETORIA,
       SUP.DESCRICAO AS SUPERINTENDENCIA,
       SUP.ABREVIACAO AS ABREVIACAO_SUPERINTENDENCIA,
       MAX(CASE WHEN CNT.SALARIO_PAGTO = 'E' THEN SAL.SAL_CONTR_EFET12 ELSE SAL.SAL_CONTR_COMIS12 END) AS SALARIO
FROM ARTERH.RHPESS_CONTRATO CNT
     INNER JOIN ARTERH.RHPESS_PESSOA PE           ON PE.CODIGO            = CNT.CODIGO_PESSOA
                                                 AND PE.CODIGO_EMPRESA    = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHPLCS_CARGO CG            ON CG.CODIGO = CNT.COD_CARGO_PAGTO
                                                 AND CG.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     LEFT JOIN ARTERH.RHORGA_UNIDADE GER     ON GER.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND GER.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND GER.COD_UNIDADE3 = CNT.COD_UNIDADE3
                                                 AND GER.COD_UNIDADE4 = CNT.COD_UNIDADE4
                                                 AND GER.COD_UNIDADE5 = CNT.COD_UNIDADE5
                                                 AND GER.COD_UNIDADE6 = CNT.COD_UNIDADE6
                                                 AND GER.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHORGA_UNIDADE SUP     ON SUP.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND SUP.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND SUP.COD_UNIDADE3 = CNT.COD_UNIDADE3
                                                 AND SUP.COD_UNIDADE4 = '000000'
                                                 AND SUP.COD_UNIDADE5 = '000000'
                                                 AND SUP.COD_UNIDADE6 = '000000'
                                                 AND SUP.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHORGA_UNIDADE DIR     ON DIR.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                                 AND DIR.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                                 AND DIR.COD_UNIDADE3 = '000000'
                                                 AND DIR.COD_UNIDADE4 = '000000'
                                                 AND DIR.COD_UNIDADE5 = '000000'
                                                 AND DIR.COD_UNIDADE6 = '000000'
                                                 AND DIR.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     LEFT JOIN ARTERH.RHPLCS_FUNCAO FUN           ON FUN.CODIGO = CNT.CODIGO_FUNCAO
                                                 AND FUN.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     LEFT JOIN ARTERH.RHPLCS_ESPECIALID ESP       ON ESP.CODIGO = CNT.COD_ESPECIALIDADE
                                                 AND ESP.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA     
     INNER JOIN ARTERH.RHPESS_SALARIOS SAL ON SAL.CODIGO = CNT.CODIGO
                                          AND SAL.TIPO_CONTRATO = CNT.TIPO_CONTRATO
                                          AND SAL.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
WHERE 1 = 1
AND CNT.ANO_MES_REFERENCIA  = ( SELECT MAX (CNT2.ANO_MES_REFERENCIA)
        								  FROM ARTERH.RHPESS_CONTRATO CNT2
        								  WHERE CNT2.CODIGO              = CNT.CODIGO											  
        								  AND   TRUNC(CNT2.ANO_MES_REFERENCIA) <= (SELECT DT_MAX_DATAS FROM ARTERH.RHPARM_P_SIST)
        								  AND   CNT2.TIPO_CONTRATO       = CNT.TIPO_CONTRATO
        								  AND   CNT2.CODIGO_EMPRESA      = CNT.CODIGO_EMPRESA)
AND CNT.CODIGO_EMPRESA = '0002'
AND CNT.TIPO_CONTRATO = '0001'
AND CNT.DATA_RESCISAO BETWEEN TO_DATE('01/01' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY')) 
                          AND TO_DATE('31/12' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY'))
--AND SAL.ANO_BASE = TO_DATE('01/01' ||'/'||TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYY'))

GROUP BY CNT.CODIGO_EMPRESA,
       CNT.TIPO_CONTRATO,
       SUBSTR(CNT.CODIGO,7,8) || '-' ||SUBSTR(CNT.CODIGO,15,1),       
       CNT.NOME,
       PE.CPF,
       CNT.DATA_ADMISSAO,
       CNT.DATA_RESCISAO,       
       CASE 
         WHEN CNT.SALARIO_PAGTO = 'E' THEN 'EFETIVO'
         WHEN CNT.SALARIO_PAGTO = 'C' THEN 'COMISSIONADO'
         WHEN CNT.SALARIO_PAGTO = 'A' THEN 'AMPARADO'
         WHEN CNT.SALARIO_PAGTO = 'P' THEN 'PAGAMENTO'
       ELSE 'FUNÇÃO' END,              
       CNT.COD_CARGO_PAGTO,
       CG.DESCRICAO,
       CNT.CODIGO_FUNCAO,
       FUN.DESCRICAO,
       CNT.COD_ESPECIALIDADE,
       ESP.DESCRICAO,
       SUBSTR(CNT.COD_UNIDADE1,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE2,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE3,5,2) || '.' ||
       SUBSTR(CNT.COD_UNIDADE4,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE5,5,2) || '.' || SUBSTR(CNT.COD_UNIDADE6,4,3),       
       GER.DESCRICAO,
       GER.ABREVIACAO,
       DIR.DESCRICAO,
       DIR.ABREVIACAO,
       SUP.DESCRICAO,
       SUP.ABREVIACAO
ORDER BY 5