
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."V_RHSAD_PONTO" ("MATRICULA_FUNCIONARIO", "LOGIN_FUNCIONARIO", "NOME", "NOME_SOCIAL", "DATA_ADMISSAO", "CPF", "EMAIL", "COD_CARGO_PAGTO", "DESCRICAO_CARGO", "CODIGO_FUNCAO", "DESCRICAO_FUNCAO", "COD_ESPECIALIDADE", "DESCRICAO_ESPECIALIDADE", "COD_LOTACAO", "DESCRICAO_LOTACAO", "MATRICULA_GERENTE", "LOGIN_GERENTE", "NOME_GERENTE", "INSCRICAO_CONSELHO", "CONSELHO_REGIONAL", "DESCRICAO_CONSELHO_REGIONAL", "SITUACAO_FUNCIONAL", "DESCRICAO_SITUACAO_FUNCIONAL", "CODIGO_REGISTRO_PONTO", "DESCRICAO_REGISTRO_PONTO", "MATRICULA_SUPERINTENDENTE", "LOGIN_SUPERINTENDENTE", "NOME_SUPERINTENDENTE", "MATRICULA_DIRETOR", "LOGIN_DIRETOR", "NOME_DIRETOR", "MATRICULA_PRESIDENTE", "LOGIN_PRESIDENTE", "NOME_PRESIDENTE") AS 
  SELECT SUBSTR (CNT.CODIGO, 7, 8) || '-' || SUBSTR (CNT.CODIGO, 15, 1)
               AS MATRICULA_FUNCIONARIO,
            CASE
               WHEN CG.DESCRICAO NOT LIKE '%ESTAG%'
               THEN
                  'pb' || SUBSTR (CNT.CODIGO, 9, 6)
               WHEN CG.DESCRICAO LIKE '%ESTAG%'
               THEN
                  'pbes' || SUBSTR (CNT.CODIGO, 9, 6)
               ELSE
                  'NÃO DEFINIDA'
            END
               LOGIN_FUNCIONARIO,
            CNT.NOME,
            PES.NOME_SOCIAL,
            CNT.DATA_ADMISSAO,
            PES.CPF,
            LOWER (NVL (E.ENDER_ELETRONICO, 'NA')) AS EMAIL,
            CNT.COD_CARGO_PAGTO,
            CG.DESCRICAO AS DESCRICAO_CARGO,
            CNT.CODIGO_FUNCAO,
            FUN.DESCRICAO AS DESCRICAO_FUNCAO,
            CNT.COD_ESPECIALIDADE,
            EP.DESCRICAO AS DESCRICAO_ESPECIALIDADE,
               SUBSTR (CNT.COD_CUSTO_GERENC1, 5, 2)
            || '-'
            || SUBSTR (CNT.COD_CUSTO_GERENC2, 5, 2)
            || '-'
            || SUBSTR (CNT.COD_CUSTO_GERENC3, 5, 2)
            || '-'
            || SUBSTR (CNT.COD_CUSTO_GERENC4, 5, 2)
            || '-'
            || SUBSTR (CNT.COD_CUSTO_GERENC5, 5, 2)
            || '-'
            || SUBSTR (CNT.COD_CUSTO_GERENC6, 4, 3)
               AS COD_LOTACAO,
            GER.DESCRICAO AS DESCRICAO_LOTACAO,
               SUBSTR (CM.CODIGO_CONTRATO, 7, 8)
            || '-'
            || SUBSTR (CM.CODIGO_CONTRATO, 15, 1)
               AS MATRICULA_GERENTE,
            'pb' || SUBSTR (CM.CODIGO_CONTRATO, 9, 6) AS LOGIN_GERENTE,
            TIT.NOME AS NOME_GERENTE,
            PES.INSCRICAO_CONSELHO,
            PES.CONSELHO_REGIONAL,
            CR.ABREVIACAO AS DESCRICAO_CONSELHO_REGIONAL,
            CNT.SITUACAO_FUNCIONAL,
            SF.DESCRICAO AS DESCRICAO_SITUACAO_FUNCIONAL,
            CNT.REGISTRO_PONTO,
            RP.DESCRICAO AS DESCRICAO_REGISTRO_PONTO,
            SUBSTR (CMS.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMS.CODIGO_CONTRATO, 15, 1) AS MATRICULA_SUPERINTENDENTE,
            'pb' || SUBSTR (CMS.CODIGO_CONTRATO, 9, 6) AS LOGIN_SUPERINTENDENTE,
            CMS.NOME_ACESSO AS NOME_SUPERINTENDENTE,
            -- DIRETORIA            
            SUBSTR (CMD.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMD.CODIGO_CONTRATO, 15, 1) AS MATRICULA_DIRETOR,
            'pb' || SUBSTR (CMD.CODIGO_CONTRATO, 9, 6) AS LOGIN_DIRETOR,
            CMD.NOME_ACESSO AS NOME_DIRETOR,
            -- PRESIDENCIA
            SUBSTR (CMP.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMP.CODIGO_CONTRATO, 15, 1) AS MATRICULA_PRESIDENTE,
            'pb' || SUBSTR (CMP.CODIGO_CONTRATO, 9, 6) AS LOGIN_PRESIDENTE,
            CMP.NOME_ACESSO AS NOME_PRESIDENTE
       FROM ARTERH.RHPESS_CONTRATO CNT
            INNER JOIN ARTERH.RHPESS_PESSOA PES
               ON     PES.CODIGO = CNT.CODIGO_PESSOA
                  AND PES.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_ENDERECO_P E
               ON     E.CODIGO_PESSOA = CNT.CODIGO_PESSOA
                  AND E.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHTABS_C_REGIONAL CR
               ON CR.CODIGO = PES.CONSELHO_REGIONAL
            INNER JOIN ARTERH.RHPLCS_CARGO CG
               ON     CG.CODIGO = CNT.COD_CARGO_PAGTO
                  AND CG.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            INNER JOIN ARTERH.RHPARM_SIT_FUNC SF
               ON SF.CODIGO = CNT.SITUACAO_FUNCIONAL
            LEFT JOIN ARTERH.RHPLCS_FUNCAO FUN
               ON     FUN.CODIGO = CNT.CODIGO_FUNCAO
                  AND FUN.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPLCS_ESPECIALID EP
               ON     EP.CODIGO = CNT.COD_ESPECIALIDADE
                  AND EP.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHORGA_UNIDADE GER
               ON     GER.COD_UNIDADE1 = CNT.COD_UNIDADE1
                  AND GER.COD_UNIDADE2 = CNT.COD_UNIDADE2
                  AND GER.COD_UNIDADE3 = CNT.COD_UNIDADE3
                  AND GER.COD_UNIDADE4 = CNT.COD_UNIDADE4
                  AND GER.COD_UNIDADE5 = CNT.COD_UNIDADE5
                  AND GER.COD_UNIDADE6 = CNT.COD_UNIDADE6
                  AND GER.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_PESSOA TIT
               ON     TIT.CODIGO = GER.COD_PESSOA_RESP
                  AND TIT.CODIGO_EMPRESA = GER.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_CONTR_MEST CM
               ON     CM.CODIGO_PESSOA = TIT.CODIGO
                  AND CM.CODIGO_EMPRESA = PES.CODIGO_EMPRESA
                  AND CM.DATA_RESCISAO IS NULL
                  AND CM.TIPO_CONTRATO = '0001'
            LEFT JOIN ARTERH.RHTABS_REG_PONTO RP
               ON RP.CODIGO = CNT.REGISTRO_PONTO
            -- **** SUPERINTENDENTE  ****
            LEFT JOIN (SELECT SUP.CODIGO_EMPRESA,SUP.COD_PESSOA_RESP,SUP.COD_UNIDADE1,SUP.COD_UNIDADE2,SUP.COD_UNIDADE3,SUP.COD_UNIDADE4,SUP.COD_UNIDADE5,SUP.COD_UNIDADE6,
                              SUP.COD_UNIDADE_SUP1,SUP.COD_UNIDADE_SUP2,SUP.COD_UNIDADE_SUP3,SUP.COD_UNIDADE_SUP4,SUP.COD_UNIDADE_SUP5,SUP.COD_UNIDADE_SUP6
                       FROM ARTERH.RHORGA_UNIDADE SUP 
                       ) SUPER ON SUPER.COD_UNIDADE1   = GER.COD_UNIDADE_SUP1
                              AND SUPER.COD_UNIDADE2   = GER.COD_UNIDADE_SUP2
                              AND SUPER.COD_UNIDADE3   = GER.COD_UNIDADE_SUP3
                              AND SUPER.COD_UNIDADE4   = GER.COD_UNIDADE_SUP4
                              AND SUPER.COD_UNIDADE5   = GER.COD_UNIDADE_SUP5
                              AND SUPER.COD_UNIDADE6   = GER.COD_UNIDADE_SUP6
                              AND SUPER.CODIGO_EMPRESA = GER.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMS ON CMS.CODIGO_PESSOA = SUPER.COD_PESSOA_RESP AND CMS.CODIGO_EMPRESA = SUPER.CODIGO_EMPRESA 
                                                  AND CMS.DATA_RESCISAO IS NULL AND CMS.TIPO_CONTRATO = '0001'
            -- **** DIRETORIA  ****
            LEFT JOIN (SELECT DIR.CODIGO_EMPRESA,DIR.COD_PESSOA_RESP,DIR.COD_UNIDADE1,DIR.COD_UNIDADE2,DIR.COD_UNIDADE3,DIR.COD_UNIDADE4,DIR.COD_UNIDADE5,DIR.COD_UNIDADE6,
                              DIR.COD_UNIDADE_SUP1,DIR.COD_UNIDADE_SUP2,DIR.COD_UNIDADE_SUP3,DIR.COD_UNIDADE_SUP4,DIR.COD_UNIDADE_SUP5,DIR.COD_UNIDADE_SUP6
                       FROM ARTERH.RHORGA_UNIDADE DIR 
                       ) DIRET ON DIRET.COD_UNIDADE1   = SUPER.COD_UNIDADE_SUP1
                              AND DIRET.COD_UNIDADE2   = SUPER.COD_UNIDADE_SUP2
                              AND DIRET.COD_UNIDADE3   = SUPER.COD_UNIDADE_SUP3
                              AND DIRET.COD_UNIDADE4   = SUPER.COD_UNIDADE_SUP4
                              AND DIRET.COD_UNIDADE5   = SUPER.COD_UNIDADE_SUP5
                              AND DIRET.COD_UNIDADE6   = SUPER.COD_UNIDADE_SUP6
                              AND DIRET.CODIGO_EMPRESA = SUPER.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMD ON CMD.CODIGO_PESSOA = DIRET.COD_PESSOA_RESP AND CMD.CODIGO_EMPRESA = DIRET.CODIGO_EMPRESA 
                                                  AND CMD.DATA_RESCISAO IS NULL AND CMD.TIPO_CONTRATO = '0001'
            -- **** PRESIDENCIA  ****
            LEFT JOIN (SELECT PR.CODIGO_EMPRESA,PR.COD_PESSOA_RESP,PR.COD_UNIDADE1,PR.COD_UNIDADE2,PR.COD_UNIDADE3,PR.COD_UNIDADE4,PR.COD_UNIDADE5,PR.COD_UNIDADE6,
                              PR.COD_UNIDADE_SUP1,PR.COD_UNIDADE_SUP2,PR.COD_UNIDADE_SUP3,PR.COD_UNIDADE_SUP4,PR.COD_UNIDADE_SUP5,PR.COD_UNIDADE_SUP6
                       FROM ARTERH.RHORGA_UNIDADE PR 
                       ) PRESI ON PRESI.COD_UNIDADE1   = DIRET.COD_UNIDADE_SUP1
                              AND PRESI.COD_UNIDADE2   = DIRET.COD_UNIDADE_SUP2
                              AND PRESI.COD_UNIDADE3   = DIRET.COD_UNIDADE_SUP3
                              AND PRESI.COD_UNIDADE4   = DIRET.COD_UNIDADE_SUP4
                              AND PRESI.COD_UNIDADE5   = DIRET.COD_UNIDADE_SUP5
                              AND PRESI.COD_UNIDADE6   = DIRET.COD_UNIDADE_SUP6
                              AND PRESI.CODIGO_EMPRESA = DIRET.CODIGO_EMPRESA
            LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMP ON CMP.CODIGO_PESSOA = PRESI.COD_PESSOA_RESP AND CMP.CODIGO_EMPRESA = PRESI.CODIGO_EMPRESA 
                                                  AND CMP.DATA_RESCISAO IS NULL AND CMP.TIPO_CONTRATO = '0001'
                             
      WHERE     CNT.ANO_MES_REFERENCIA =
                   (SELECT CM1.ULTIMA_DATA
                      FROM ARTERH.RHPESS_CONTR_MEST CM1
                     WHERE     CM1.CODIGO_CONTRATO = CNT.CODIGO
                           AND CM1.TIPO_CONTRATO = CNT.TIPO_CONTRATO
                           AND CM1.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA)
            AND CNT.TIPO_CONTRATO IN ('0001', '0003', '0098')
            AND CNT.CODIGO_EMPRESA = '0002'
            AND CNT.DATA_RESCISAO IS NULL
            AND SF.CONTROLE_FOLHA <> 'S'            
   ORDER BY CNT.NOME, CNT.SITUACAO_FUNCIONAL