
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."V_RHSAD_HORA_EXTRA" ("MATRICULA_FUNCIONARIO", "LOGIN_FUNCIONARIO", "NOME", "MATRICULA_GERENTE", "LOGIN_GERENTE", "NOME_GERENTE", "MATRICULA_SUPERINTENDENTE", "LOGIN_SUPERINTENDENTE", "NOME_SUPERINTENDENTE", "MATRICULA_DIRETOR", "LOGIN_DIRETOR", "NOME_DIRETOR", "MATRICULA_PRESIDENTE", "LOGIN_PRESIDENTE", "NOME_PRESIDENTE", "MES", "ANO", "BANCO_DE_HORAS", "HORAS_COMPESADAS", "SALDO", "DATA_EXPIRACAO") AS 
  SELECT SUBSTR (CNT.CODIGO, 7, 8) || '-' || SUBSTR (CNT.CODIGO, 15, 1) AS MATRICULA_FUNCIONARIO,
          CASE WHEN CG.DESCRICAO NOT LIKE '%ESTAG%' THEN 'pb' || SUBSTR (CNT.CODIGO, 9, 6)
               WHEN CG.DESCRICAO LIKE '%ESTAG%' THEN 'pbes' || SUBSTR (CNT.CODIGO, 9, 6)
          ELSE 'NÃO DEFINIDA' END LOGIN_FUNCIONARIO,
          CNT.NOME,
          SUBSTR (CM.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CM.CODIGO_CONTRATO, 15, 1) AS MATRICULA_GERENTE,
          'pb' || SUBSTR (CM.CODIGO_CONTRATO, 9, 6) AS LOGIN_GERENTE,
          TIT.NOME AS NOME_GERENTE,
          SUBSTR (CMS.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMS.CODIGO_CONTRATO, 15, 1) AS MATRICULA_SUPERINTENDENTE,
          'pb' || SUBSTR (CMS.CODIGO_CONTRATO, 9, 6) AS LOGIN_SUPERINTENDENTE,
          CMS.NOME_ACESSO AS NOME_SUPERINTENDENTE,
          SUBSTR (CMD.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMD.CODIGO_CONTRATO, 15, 1) AS MATRICULA_DIRETOR,
          'pb' || SUBSTR (CMD.CODIGO_CONTRATO, 9, 6) AS LOGIN_DIRETOR,
          CMD.NOME_ACESSO AS NOME_DIRETOR,
          SUBSTR (CMP.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMP.CODIGO_CONTRATO, 15, 1) AS MATRICULA_PRESIDENTE,
          'pb' || SUBSTR (CMP.CODIGO_CONTRATO, 9, 6) AS LOGIN_PRESIDENTE,
          CMP.NOME_ACESSO AS NOME_PRESIDENTE,
          TO_CHAR(SDE.DATA,'MM') AS MES,
          TO_CHAR(SDE.DATA,'YYYY') AS ANO,
          SUM(SDE.REF_HORAS) AS BANCO_DE_HORAS,       
          CASE WHEN SDS.HORAS_COMPESADAS IS NOT NULL THEN SDS.HORAS_COMPESADAS ELSE 0 END HORAS_COMPESADAS,
          CASE WHEN SUM(SDE.REF_HORAS) <> 0 AND SDS.HORAS_COMPESADAS IS NULL THEN SUM(SDE.REF_HORAS) 
               WHEN SUM(SDE.REF_HORAS) <> 0 AND SDS.HORAS_COMPESADAS <> 0 THEN (SUM(SDE.REF_HORAS) - SDS.HORAS_COMPESADAS)
          ELSE 0 END SALDO,
          CASE WHEN CNT.MOTIVO_ADMISSAO = '0002' THEN TO_CHAR(ADD_MONTHS(SDE.DATA,4),'DD/MM/YYYY')
          ELSE TO_CHAR(ADD_MONTHS(SDE.DATA,6),'DD/MM/YYYY')
          END DATA_EXPIRACAO          		  
   FROM ARTERH.RHPONT_RES_SIT_DIA SDE
        LEFT JOIN (SELECT PSD.CODIGO_CONTRATO,TO_CHAR(PSD.DATA,'YYYY-MM') AS OCORRENCIA_SAIDA,PSD.TIPO_APURACAO,PSD.TIPO_CONTRATO,PSD.CODIGO_EMPRESA,
                   SUM(PSD.REF_HORAS) AS HORAS_COMPESADAS
                   FROM ARTERH.RHPONT_RES_SIT_DIA PSD
                   WHERE 1 = 1
                   AND   PSD.CODIGO_SITUACAO = 'P031'
                   AND   PSD.TIPO_APURACAO = 'F'
                   AND   PSD.TIPO_CONTRATO IN ('0001', '0003', '0098')
                   AND   PSD.CODIGO_EMPRESA = '0002'                
                   GROUP BY PSD.CODIGO_CONTRATO,PSD.DATA,PSD.TIPO_APURACAO,PSD.TIPO_CONTRATO,PSD.CODIGO_EMPRESA) 
                   SDS ON SDS.CODIGO_CONTRATO = SDE.CODIGO_CONTRATO     
                      AND SDS.OCORRENCIA_SAIDA = TO_CHAR(SDE.DATA,'YYYY-MM')
                      AND SDS.TIPO_APURACAO = SDE.TIPO_APURACAO
                      AND SDS.TIPO_CONTRATO = SDE.TIPO_CONTRATO
                      AND SDS.CODIGO_EMPRESA = SDE.CODIGO_EMPRESA
        INNER JOIN ARTERH.RHPESS_CONTRATO CNT ON CNT.CODIGO = SDE.CODIGO_CONTRATO
                                             AND CNT.ANO_MES_REFERENCIA = (SELECT MAX (CNT2.ANO_MES_REFERENCIA)
											                               FROM ARTERH.RHPESS_CONTRATO CNT2
											                               WHERE CNT2.CODIGO              = CNT.CODIGO											  
											                               AND   TRUNC(CNT2.ANO_MES_REFERENCIA) <= (SELECT DT_MAX_DATAS FROM ARTERH.RHPARM_P_SIST)
											                               AND   CNT2.TIPO_CONTRATO       = CNT.TIPO_CONTRATO
											                               AND   CNT2.CODIGO_EMPRESA      = CNT.CODIGO_EMPRESA)
                                             AND CNT.TIPO_CONTRATO  = SDE.TIPO_CONTRATO
                                             AND CNT.CODIGO_EMPRESA = SDE.CODIGO_EMPRESA
                                             AND CNT.DATA_RESCISAO IS NULL
        INNER JOIN ARTERH.RHPLCS_CARGO CG ON CG.CODIGO = CNT.COD_CARGO_PAGTO
                                         AND CG.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHORGA_UNIDADE GER ON GER.COD_UNIDADE1 = CNT.COD_UNIDADE1
                                           AND GER.COD_UNIDADE2 = CNT.COD_UNIDADE2
                                           AND GER.COD_UNIDADE3 = CNT.COD_UNIDADE3
                                           AND GER.COD_UNIDADE4 = CNT.COD_UNIDADE4
                                           AND GER.COD_UNIDADE5 = CNT.COD_UNIDADE5
                                           AND GER.COD_UNIDADE6 = CNT.COD_UNIDADE6
                                           AND GER.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHPESS_PESSOA TIT ON TIT.CODIGO = GER.COD_PESSOA_RESP
                                          AND TIT.CODIGO_EMPRESA = GER.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHPESS_CONTR_MEST CM ON CM.CODIGO_PESSOA = TIT.CODIGO
                                             AND CM.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
                                             AND CM.DATA_RESCISAO IS NULL
                                             AND CM.TIPO_CONTRATO = '0001'
        -- **** SUPERINTENDENTE  ****
        LEFT JOIN (SELECT SUP.CODIGO_EMPRESA,SUP.COD_PESSOA_RESP,SUP.COD_UNIDADE1,SUP.COD_UNIDADE2,SUP.COD_UNIDADE3,SUP.COD_UNIDADE4,SUP.COD_UNIDADE5,SUP.COD_UNIDADE6,
                          SUP.COD_UNIDADE_SUP1,SUP.COD_UNIDADE_SUP2,SUP.COD_UNIDADE_SUP3,SUP.COD_UNIDADE_SUP4,SUP.COD_UNIDADE_SUP5,SUP.COD_UNIDADE_SUP6
                   FROM ARTERH.RHORGA_UNIDADE SUP ) SUPER ON SUPER.COD_UNIDADE1   = GER.COD_UNIDADE_SUP1
                                                         AND SUPER.COD_UNIDADE2   = GER.COD_UNIDADE_SUP2
                                                         AND SUPER.COD_UNIDADE3   = GER.COD_UNIDADE_SUP3
                                                         AND SUPER.COD_UNIDADE4   = GER.COD_UNIDADE_SUP4
                                                         AND SUPER.COD_UNIDADE5   = GER.COD_UNIDADE_SUP5
                                                         AND SUPER.COD_UNIDADE6   = GER.COD_UNIDADE_SUP6
                                                         AND SUPER.CODIGO_EMPRESA = GER.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMS ON CMS.CODIGO_PESSOA = SUPER.COD_PESSOA_RESP 
                                              AND CMS.CODIGO_EMPRESA = SUPER.CODIGO_EMPRESA 
                                              AND CMS.DATA_RESCISAO IS NULL AND CMS.TIPO_CONTRATO = '0001'
        -- **** DIRETORIA  ****
        LEFT JOIN (SELECT DIR.CODIGO_EMPRESA,DIR.COD_PESSOA_RESP,DIR.COD_UNIDADE1,DIR.COD_UNIDADE2,DIR.COD_UNIDADE3,DIR.COD_UNIDADE4,DIR.COD_UNIDADE5,DIR.COD_UNIDADE6,
                          DIR.COD_UNIDADE_SUP1,DIR.COD_UNIDADE_SUP2,DIR.COD_UNIDADE_SUP3,DIR.COD_UNIDADE_SUP4,DIR.COD_UNIDADE_SUP5,DIR.COD_UNIDADE_SUP6
                   FROM ARTERH.RHORGA_UNIDADE DIR ) DIRET ON DIRET.COD_UNIDADE1   = SUPER.COD_UNIDADE_SUP1
                                                         AND DIRET.COD_UNIDADE2   = SUPER.COD_UNIDADE_SUP2
                                                         AND DIRET.COD_UNIDADE3   = SUPER.COD_UNIDADE_SUP3
                                                         AND DIRET.COD_UNIDADE4   = SUPER.COD_UNIDADE_SUP4
                                                         AND DIRET.COD_UNIDADE5   = SUPER.COD_UNIDADE_SUP5
                                                         AND DIRET.COD_UNIDADE6   = SUPER.COD_UNIDADE_SUP6
                                                         AND DIRET.CODIGO_EMPRESA = SUPER.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMD ON CMD.CODIGO_PESSOA = DIRET.COD_PESSOA_RESP 
                                              AND CMD.CODIGO_EMPRESA = DIRET.CODIGO_EMPRESA 
                                              AND CMD.DATA_RESCISAO IS NULL AND CMD.TIPO_CONTRATO = '0001'
        -- **** PRESIDENCIA  ****
        LEFT JOIN (SELECT PR.CODIGO_EMPRESA,PR.COD_PESSOA_RESP,PR.COD_UNIDADE1,PR.COD_UNIDADE2,PR.COD_UNIDADE3,PR.COD_UNIDADE4,PR.COD_UNIDADE5,PR.COD_UNIDADE6,
                          PR.COD_UNIDADE_SUP1,PR.COD_UNIDADE_SUP2,PR.COD_UNIDADE_SUP3,PR.COD_UNIDADE_SUP4,PR.COD_UNIDADE_SUP5,PR.COD_UNIDADE_SUP6
                   FROM ARTERH.RHORGA_UNIDADE PR ) PRESI ON PRESI.COD_UNIDADE1   = DIRET.COD_UNIDADE_SUP1
                                                        AND PRESI.COD_UNIDADE2   = DIRET.COD_UNIDADE_SUP2
                                                        AND PRESI.COD_UNIDADE3   = DIRET.COD_UNIDADE_SUP3
                                                        AND PRESI.COD_UNIDADE4   = DIRET.COD_UNIDADE_SUP4
                                                        AND PRESI.COD_UNIDADE5   = DIRET.COD_UNIDADE_SUP5
                                                        AND PRESI.COD_UNIDADE6   = DIRET.COD_UNIDADE_SUP6
                                                        AND PRESI.CODIGO_EMPRESA = DIRET.CODIGO_EMPRESA
        LEFT JOIN ARTERH.RHPESS_CONTR_MEST CMP ON CMP.CODIGO_PESSOA = PRESI.COD_PESSOA_RESP 
                                              AND CMP.CODIGO_EMPRESA = PRESI.CODIGO_EMPRESA 
                                              AND CMP.DATA_RESCISAO IS NULL AND CMP.TIPO_CONTRATO = '0001'                                          
    WHERE TRUNC(SDE.DATA) >= TO_DATE('01/01/2021','DD/MM/YYYY')    
    AND SDE.CODIGO_SITUACAO = 'P030' -- ENTRA DE BCO DE HORAS 
    AND SDE.TIPO_APURACAO = 'F'
    AND SDE.TIPO_CONTRATO IN ('0001', '0003', '0098')
    AND SDE.CODIGO_EMPRESA = '0002'
    GROUP BY SUBSTR (CNT.CODIGO, 7, 8) || '-' || SUBSTR (CNT.CODIGO, 15, 1),
           CASE WHEN CG.DESCRICAO NOT LIKE '%ESTAG%' THEN 'pb' || SUBSTR (CNT.CODIGO, 9, 6)
                WHEN CG.DESCRICAO LIKE '%ESTAG%' THEN 'pbes' || SUBSTR (CNT.CODIGO, 9, 6)
           ELSE 'NÃO DEFINIDA' END,
           CNT.NOME,
           SUBSTR (CM.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CM.CODIGO_CONTRATO, 15, 1),
           'pb' || SUBSTR (CM.CODIGO_CONTRATO, 9, 6),
           TIT.NOME,
           SUBSTR (CMS.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMS.CODIGO_CONTRATO, 15, 1),
           'pb' || SUBSTR (CMS.CODIGO_CONTRATO, 9, 6),
           CMS.NOME_ACESSO,
           SUBSTR (CMD.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMD.CODIGO_CONTRATO, 15, 1),
           'pb' || SUBSTR (CMD.CODIGO_CONTRATO, 9, 6),
           CMD.NOME_ACESSO,
           SUBSTR (CMP.CODIGO_CONTRATO, 7, 8) || '-' || SUBSTR (CMP.CODIGO_CONTRATO, 15, 1),
           'pb' || SUBSTR (CMP.CODIGO_CONTRATO, 9, 6),
           TO_CHAR(SDE.DATA,'MM'),
           TO_CHAR(SDE.DATA,'YYYY'),
           CMP.NOME_ACESSO,TO_CHAR(SDE.DATA,'YYYY-MM'),SDS.HORAS_COMPESADAS,
           CASE WHEN CNT.MOTIVO_ADMISSAO = '0002' THEN TO_CHAR(ADD_MONTHS(SDE.DATA,4),'DD/MM/YYYY')
           ELSE TO_CHAR(ADD_MONTHS(SDE.DATA,6),'DD/MM/YYYY')
           END