
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."V_RHSMEDXX_WAG" ("CODIGO", "NOME", "ENDERECO", "NUMERO", "COMPLEMENTO", "BAIRRO", "NOME_MUNICIPIO", "UF", "CEP", "FAX", "ENDER_ELETRONICO", "NOME_PAI", "NOME_MAE", "DATA_NASCIMENTO", "FATOR_RH", "RACA_COR", "DESCR_COR", "SEXO", "DESCR_SEXO", "ESTADO_CIVIL", "DESCR_EST_CIVIL", "NATURALIDADE", "NACIONALIDADE", "DESCR_NACION", "ANO_CHEGADA", "DATA_NATURALIZACAO", "IDENTIDADE", "ORGAO_EXPEDIDOR", "LOCAL_EXPEDICAO", "DATA_EXPEDICAO", "CPF", "TITULO_ELEITOR", "SECAO_TIT_ELEITOR", "ZONA_TIT_ELEITOR", "PIS_PASEP", "INSCRICAO_CONSELHO", "CART_TRABALHO", "SERIE_CART_TRAB", "DATA_CART_TRAB", "HABILITACAO", "DATA_HABILITACAO", "CATEGORIA", "CERT_RESERVISTA", "TELEFONE", "PESSOA", "COD_CARGO_EFETIVO", "DESC_CARGO", "COD_CARGO_COMISS", "CODIGO_FUNCAO", "DESCRICAO", "COD_UNIDADE1", "COD_UNIDADE2", "COD_UNIDADE3", "COD_UNIDADE4", "COD_UNIDADE5", "COD_UNIDADE6", "DESC_UNIDADE", "PUBLIC_DOM", "DATA_POSSE", "DATA_ADMISSAO", "DATA_EFETIVO_EXERC", "DATA_RESCISAO", "CLASSIFICACAO_CAND", "HOMOLOGACAO_CONCURSO", "DATA_EDITAL", "NUMERO_EDITAL", "DOIS_BM", "VINCULO", "DESC_VÍNCULO", "DESC_JORNADA_TRAB", "JORNADA_DIARIA", "HORAS_SEMANA_RAIS", "SITUACAO_FUNCIONAL", "DESC_SIT_FUNC") AS 
  SELECT RHPESS_CONTRATO.CODIGO,
          RHPESS_CONTRATO.NOME,
          RHPESS_ENDERECO_P.ENDERECO,
          RHPESS_ENDERECO_P.NUMERO,
          RHPESS_ENDERECO_P.COMPLEMENTO,
          RHPESS_ENDERECO_P.BAIRRO,
          RHPESS_ENDERECO_P.C_LIVRE_DESCR01 NOME_MUNICIPIO,
          RHPESS_ENDERECO_P.UF,
          RHPESS_ENDERECO_P.CEP,
          RHPESS_ENDERECO_P.FAX,
          RHPESS_ENDERECO_P.ENDER_ELETRONICO,
          RHPESS_PESSOA.C_LIVRE_DESCR11 NOME_PAI,
          RHPESS_PESSOA.C_LIVRE_DESCR12 NOME_MAE,
          RHPESS_PESSOA.DATA_NASCIMENTO,
          RHPESS_PESSOA.FATOR_RH,
          RHPESS_PESSOA.RACA_COR,
          RHTABS_RACA_COR.DESCRICAO DESCR_COR,
          RHPESS_PESSOA.SEXO,
          RHTABS_SEXO.DESCRICAO DESCR_SEXO,
          RHPESS_PESSOA.ESTADO_CIVIL,
          RHTABS_EST_CIVIL.DESCRICAO DESCR_EST_CIVIL,
          RHPESS_PESSOA.NATURALIDADE,
          RHPESS_PESSOA.NACIONALIDADE,
          RHTABS_NACIONALID.DESCRICAO DESCR_NACION,
          RHPESS_PESSOA.ANO_CHEGADA,
          RHPESS_PESSOA.DATA_NATURALIZACAO,
          RHPESS_PESSOA.IDENTIDADE,
          RHPESS_PESSOA.ORGAO_EXPEDIDOR,
          RHPESS_PESSOA.LOCAL_EXPEDICAO,
          RHPESS_PESSOA.DATA_EXPEDICAO,
          RHPESS_PESSOA.CPF,
          RHPESS_PESSOA.TITULO_ELEITOR,
          RHPESS_PESSOA.SECAO_TIT_ELEITOR,
          RHPESS_PESSOA.ZONA_TIT_ELEITOR,
          RHPESS_PESSOA.PIS_PASEP,
          RHPESS_PESSOA.INSCRICAO_CONSELHO,
          RHPESS_PESSOA.CART_TRABALHO,
          RHPESS_PESSOA.SERIE_CART_TRAB,
          RHPESS_PESSOA.DATA_CART_TRAB,
          RHPESS_PESSOA.HABILITACAO,
          RHPESS_PESSOA.DATA_HABILITACAO,
          RHPESS_PESSOA.CATEGORIA,
          RHPESS_PESSOA.CERT_RESERVISTA,
          RHPESS_PESSOA.TELEFONE,
          RHPESS_PESSOA.CODIGO PESSOA,
          RHPESS_CONTRATO.COD_CARGO_EFETIVO,
          RHPLCS_CARGO.DESCRICAO DESC_CARGO,
          RHPESS_CONTRATO.COD_CARGO_COMISS,
          RHPESS_CONTRATO.CODIGO_FUNCAO,
          RHPLCS_FUNCAO.DESCRICAO,
          RHPESS_CONTRATO.COD_UNIDADE1,
          RHPESS_CONTRATO.COD_UNIDADE2,
          RHPESS_CONTRATO.COD_UNIDADE3,
          RHPESS_CONTRATO.COD_UNIDADE4,
          RHPESS_CONTRATO.COD_UNIDADE5,
          RHPESS_CONTRATO.COD_UNIDADE6,
          RHORGA_UNIDADE.DESCRICAO DESC_UNIDADE,
          RHPESS_CONTRATO.C_LIVRE_DATA31 PUBLIC_DOM,
          RHPESS_CONTRATO.DATA_POSSE,
          RHPESS_CONTRATO.DATA_ADMISSAO,
          RHPESS_CONTRATO.DATA_EFETIVO_EXERC,
          RHPESS_CONTRATO.DATA_RESCISAO,
          RHPESS_CONTRATO.CLASSIFICACAO_CAND,
          RHPESS_CONTRATO.C_LIVRE_DATA32 HOMOLOGACAO_CONCURSO,
          RHPESS_CONTRATO.C_LIVRE_DATA30 DATA_EDITAL,
          RHPESS_CONTRATO.NUMERO_EDITAL,
          RHPESS_CONTRATO.C_LIVRE_OPCAO48 DOIS_BM,
          RHPESS_CONTRATO.VINCULO,
          RHTABS_VINCULO_EMP.DESCRICAO DESC_VÍNCULO,
          RHPONT_ESCALA.DESCRICAO DESC_JORNADA_TRAB,
          RHPONT_ESCALA.JORNADA_DIARIA,
          TO_CHAR (RHPONT_ESCALA.HORAS_SEMANA_RAIS, '99.99')
             HORAS_SEMANA_RAIS,
          RHPESS_CONTRATO.SITUACAO_FUNCIONAL,
          RHPARM_SIT_FUNC.DESCRICAO DESC_SIT_FUNC
     FROM RHPESS_CONTRATO,
          RHPESS_PESSOA,
          RHPESS_ENDERECO_P,
          RHORGA_UNIDADE,
          RHPARM_SIT_FUNC,
          RHPLCS_FUNCAO,
          RHPLCS_CARGO,
          RHPONT_ESCALA,
          RHTABS_UF,
          RHTABS_NACIONALID,
          RHTABS_SEXO,
          RHTABS_EST_CIVIL,
          RHTABS_RACA_COR,
          RHTABS_VINCULO_EMP
    WHERE     (RHPESS_CONTRATO.CODIGO_PESSOA = RHPESS_PESSOA.CODIGO)
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA = RHPESS_PESSOA.CODIGO_EMPRESA)
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA =
                  RHPESS_ENDERECO_P.CODIGO_EMPRESA)
          AND (RHPESS_CONTRATO.CODIGO_PESSOA =
                  RHPESS_ENDERECO_P.CODIGO_PESSOA)
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA = RHORGA_UNIDADE.CODIGO_EMPRESA)
          AND (RHPESS_CONTRATO.COD_UNIDADE1 = RHORGA_UNIDADE.COD_UNIDADE1)
          AND (RHPESS_CONTRATO.COD_UNIDADE2 = RHORGA_UNIDADE.COD_UNIDADE2)
          AND (RHPESS_CONTRATO.COD_UNIDADE3 = RHORGA_UNIDADE.COD_UNIDADE3)
          AND (RHPESS_CONTRATO.COD_UNIDADE4 = RHORGA_UNIDADE.COD_UNIDADE4)
          AND (RHPESS_CONTRATO.COD_UNIDADE5 = RHORGA_UNIDADE.COD_UNIDADE5)
          AND (RHPESS_CONTRATO.COD_UNIDADE6 = RHORGA_UNIDADE.COD_UNIDADE6)
          AND (RHPESS_CONTRATO.SITUACAO_FUNCIONAL = RHPARM_SIT_FUNC.CODIGO)
          AND (RHPESS_CONTRATO.CODIGO_FUNCAO = RHPLCS_FUNCAO.CODIGO(+))
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA =
                  RHPLCS_FUNCAO.CODIGO_EMPRESA(+))
          AND (RHPESS_CONTRATO.COD_CARGO_EFETIVO = RHPLCS_CARGO.CODIGO)
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA = RHPLCS_CARGO.CODIGO_EMPRESA)
          AND (RHPESS_CONTRATO.VINCULO = RHTABS_VINCULO_EMP.CODIGO(+))
          AND (RHPESS_CONTRATO.CODIGO_ESCALA = RHPONT_ESCALA.CODIGO(+))
          AND (RHPESS_PESSOA.UF_NATURALIDADE = RHTABS_UF.CODIGO(+))
          AND (RHPESS_PESSOA.NACIONALIDADE = RHTABS_NACIONALID.CODIGO(+))
          AND (RHPESS_PESSOA.SEXO = RHTABS_SEXO.CODIGO(+))
          AND (RHPESS_PESSOA.ESTADO_CIVIL = RHTABS_EST_CIVIL.CODIGO(+))
          AND (RHPESS_PESSOA.RACA_COR = RHTABS_RACA_COR.CODIGO(+))
          AND (RHPESS_CONTRATO.CODIGO_EMPRESA = '0001')
          AND (RHPESS_CONTRATO.TIPO_CONTRATO = '0001')
          AND (RHPESS_CONTRATO.SITUACAO_FUNCIONAL <= '1800')
          AND (RHPESS_CONTRATO.SITUACAO_FUNCIONAL <> '1700')
          AND (   (    RHPESS_CONTRATO.COD_UNIDADE1 = '000070'
                   AND RHPESS_CONTRATO.COD_UNIDADE2 = '000003')
               OR (    RHPESS_CONTRATO.COD_UNIDADE1 >= '000071'
                   AND RHPESS_CONTRATO.COD_UNIDADE1 <= '000079'
                   AND RHPESS_CONTRATO.COD_UNIDADE2 = '000002'
                   AND RHPESS_CONTRATO.COD_UNIDADE3 = '000001')
               OR (RHPESS_CONTRATO.COD_UNIDADE1 = '000094'))
          AND (RHPESS_CONTRATO.ANO_MES_REFERENCIA =
                  (SELECT MAX (A.ANO_MES_REFERENCIA)
                     FROM RHPESS_CONTRATO A
                    WHERE     A.CODIGO = RHPESS_CONTRATO.CODIGO
                          AND A.CODIGO_EMPRESA =
                                 RHPESS_CONTRATO.CODIGO_EMPRESA
                          AND A.TIPO_CONTRATO = RHPESS_CONTRATO.TIPO_CONTRATO
                          AND A.ANO_MES_REFERENCIA <= SYSDATE))