
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."V_RH_REL_0069" ("CODIGO_VERBA", "DESC_VERBA", "TIPO_MOVIMENTO", "MES_INCIDENCIA", "CTRL_DEMO", "REF_VERBA", "VALOR_VERBA", "CONT", "PADRAO_SELECAO", "CTRL_LANCAMENTO") AS 
  SELECT DISTINCT MV.CODIGO_VERBA,
       VB.DESCRICAO AS DESC_VERBA,
       MV.TIPO_MOVIMENTO,
       MV.MES_INCIDENCIA,
       MV.CTRL_DEMO,
       SUM(MV.REF_VERBA) AS REF_VERBA,
       SUM(MV.VALOR_VERBA) AS VALOR_VERBA,
       COUNT(CNT.CODIGO) AS CONT,
       CASE WHEN CNT.DATA_RESCISAO IS NULL THEN 'ATIVOS' ELSE 'DEMITIDOS' END AS PADRAO_SELECAO,       
       MV.CTRL_LANCAMENTO
FROM ARTERH.RHPESS_CONTRATO CNT
     INNER JOIN ARTERH.RHMOVI_MOVIMENTO MV ON MV.CODIGO_CONTRATO = CNT.CODIGO
                                          AND MV.TIPO_CONTRATO = MV.TIPO_CONTRATO
                                          AND MV.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA
     INNER JOIN ARTERH.RHPARM_VERBA VB     ON VB.CODIGO = MV.CODIGO_VERBA                                           
WHERE 1 = 1
AND CNT.ANO_MES_REFERENCIA  = ( SELECT MAX (CNT2.ANO_MES_REFERENCIA)
        								  FROM ARTERH.RHPESS_CONTRATO CNT2
        								  WHERE CNT2.CODIGO              = CNT.CODIGO											  
        								  AND   TRUNC(CNT2.ANO_MES_REFERENCIA) <= (SELECT DT_MAX_DATAS FROM ARTERH.RHPARM_P_SIST)
        								  AND   CNT2.TIPO_CONTRATO       = CNT.TIPO_CONTRATO
        								  AND   CNT2.CODIGO_EMPRESA      = CNT.CODIGO_EMPRESA)
AND CNT.TIPO_CONTRATO = '0001'
AND CNT.CODIGO_EMPRESA = '0002'
AND MV.ANO_MES_REFERENCIA  = TO_DATE('01/'||TO_CHAR(SYSDATE,'MM')||'/'||TO_CHAR(SYSDATE,'YYYY'))
AND MV.TIPO_MOVIMENTO NOT IN ('TV')
AND MV.FASE = 0
AND MV.MODO_OPERACAO = 'R'
GROUP BY MV.CODIGO_VERBA,VB.DESCRICAO,MV.TIPO_MOVIMENTO,MV.MES_INCIDENCIA,MV.CTRL_DEMO,
         CASE WHEN CNT.DATA_RESCISAO IS NULL THEN 'ATIVOS' ELSE 'DEMITIDOS' END, MV.CTRL_LANCAMENTO
ORDER BY MV.CODIGO_VERBA,PADRAO_SELECAO