
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VIEW_SIF_DADOS_SERVIDOR" ("CODIGO_EMPRESA", "NOME_EMPRESA", "AD", "TIPO_CONTRATO", "MATRICULA", "NOME_SOCIAL", "NOME_COMPLETO", "CPF", "NOME_MAE", "DATA_NASCIMENTO", "EMAIL_PREFERENCIAL", "EMAIL_ADICIONAL", "GRAU_ESCOLARIDADE", "AREA_FORMACAO", "CELULAR_PESSOAL", "CELUCAR_INSTITUCIONAL", "UNIDADE_ORGANIZACIONAL", "LOTACAO", "CODIGO_CARGO_EFETIVO", "CARGO_EFETIVO", "CODIGO_CARGO_COMISS", "CARGO_COMISS", "ID_UNIDADE", "CODIGO_UNIDADE1", "CODIGO_UNIDADE2", "CODIGO_UNIDADE3", "CODIGO_UNIDADE4", "CODIGO_UNIDADE5", "CODIGO_UNIDADE6", "DESCRICAO_UNIDADE", "ABREVIACAO_UNIDADE", "CODIGO_FUNCAO", "FUNCAO", "READAPTACAO", "CODIGO_SITUACAO_FUNCIONAL", "SITUACAO_FUNCIONAL", "DATA_RESCISAO") AS 
  WITH MaxAnoMes AS (
    SELECT 
        AUX.CODIGO, 
        AUX.TIPO_CONTRATO, 
        AUX.CODIGO_EMPRESA,
        MAX(AUX.ANO_MES_REFERENCIA) AS MAX_ANO_MES_REFERENCIA
    FROM 
        ARTERH.RHPESS_CONTRATO AUX
    GROUP BY 
        AUX.CODIGO, 
        AUX.TIPO_CONTRATO, 
        AUX.CODIGO_EMPRESA
)
SELECT 
    EMP.CODIGO AS CODIGO_EMPRESA,
    EMP.RAZAO_SOCIAL AS NOME_EMPRESA,
    AD.CODIGO_USUARIO AS AD,
    C.TIPO_CONTRATO,
    C.CODIGO AS MATRICULA,
    TRIM(P.NOME_SOCIAL) AS NOME_SOCIAL,
    TRIM(P.NOME_ACESSO) AS NOME_COMPLETO,
    P.CPF,
    CASE WHEN TRIM(MAE.NOME_ACESSO) IS NULL THEN P.c_livre_descr12 ELSE TRIM(MAE.NOME_ACESSO) END AS NOME_MAE,
    P.data_nascimento,
    C.E_MAIL AS EMAIL_PREFERENCIAL,
    EMAIL.ENDER_ELETRONICO AS EMAIL_ADICIONAL,
    GRAU.DESCRICAO AS GRAU_ESCOLARIDADE,
    FORMACAO.DESCRICAO AS AREA_FORMACAO,
    CASE WHEN TEL.TELEFONE IS NULL THEN NULL ELSE '(' || TEL.DDD || ')' || ' ' || TEL.TELEFONE END AS CELULAR_PESSOAL,
    NULL AS CELUCAR_INSTITUCIONAL,
    UNIDADE.COD_UNIDADE1 || '.' || UNIDADE.COD_UNIDADE2 || '.' || UNIDADE.COD_UNIDADE3 || '.' || UNIDADE.COD_UNIDADE4 || '.' || UNIDADE.COD_UNIDADE5 || '.' || UNIDADE.COD_UNIDADE6 || '-' || NVL(UNIDADE.DESCRICAO, UNIDADE.TEXTO_ASSOCIADO) AS UNIDADE_ORGANIZACIONAL,
    LOTACAO.COD_LOTACAO1 || '.' || LOTACAO.COD_LOTACAO2 || '.' || LOTACAO.COD_LOTACAO3 || '.' || LOTACAO.COD_LOTACAO4 || '.' || LOTACAO.COD_LOTACAO5 || '.' || LOTACAO.COD_LOTACAO6 || '-' || NVL(LOTACAO.DESCRICAO, LOTACAO.TEXTO_ASSOCIADO) AS LOTACAO,
    CE.CODIGO AS CODIGO_CARGO_EFETIVO,
    CE.DESCRICAO AS CARGO_EFETIVO,
    CC.CODIGO AS CODIGO_CARGO_COMISS,
    CC.DESCRICAO AS CARGO_COMISS,
    G.ID_AGRUP AS ID_UNIDADE,
    G.COD_CGERENC1 as CODIGO_UNIDADE1 ,
    G.COD_CGERENC2 as CODIGO_UNIDADE2 ,
    G.COD_CGERENC3 as CODIGO_UNIDADE3 ,
    G.COD_CGERENC4 as CODIGO_UNIDADE4 , 
    G.COD_CGERENC5 AS CODIGO_UNIDADE5,
    G.COD_CGERENC6 AS CODIGO_UNIDADE6,
    NVL(G.DESCRICAO, G.TEXTO_ASSOCIADO) AS DESCRICAO_UNIDADE,
    g.abreviacao as abreviacao_unidade,
    F.CODIGO AS CODIGO_FUNCAO,
    F.DESCRICAO AS FUNCAO,
    C.REABILITADO AS READAPTACAO,
    SF.CODIGO AS CODIGO_SITUACAO_FUNCIONAL,
    SF.DESCRICAO AS SITUACAO_FUNCIONAL,
    C.DATA_RESCISAO
FROM 
    ARTERH.RHPESS_CONTRATO C 
INNER JOIN 
    ARTERH.RHORGA_EMPRESA EMP ON C.CODIGO_EMPRESA = EMP.CODIGO
INNER JOIN 
    ARTERH.RHPESS_PESSOA P ON P.CODIGO = C.CODIGO_PESSOA AND P.CODIGO_EMPRESA = C.CODIGO_EMPRESA
LEFT OUTER JOIN 
    ARTERH.rhpess_rl_pess_pes RL ON RL.COD_EMPRESA = P.CODIGO_EMPRESA AND RL.COD_PESSOA = P.CODIGO AND RL.TP_RELACIONAMENTO = '0005' AND RL.DATA_FIM_VIGENCIA IS NULL
LEFT OUTER JOIN 
    ARTERH.RHPESS_PESSOA MAE ON MAE.CODIGO = RL.COD_PESSOA_RELAC AND MAE.CODIGO_EMPRESA = RL.COD_EMPRESA
LEFT OUTER JOIN 
    ARTERH.RHPESS_ENDERECO_P EMAIL ON EMAIL.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND EMAIL.CODIGO_PESSOA = P.CODIGO
LEFT OUTER JOIN 
    ARTERH.RHTABS_GRAU_INST GRAU ON GRAU.CODIGO = P.grau_instrucao
LEFT OUTER JOIN 
    ARTERH.RHTREI_ATIVIDADE FORMACAO ON FORMACAO.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND FORMACAO.CODIGO = P.COD_ATIVIDADE
LEFT OUTER JOIN 
    ARTERH.RHPESS_TELEFONE_P TEL ON TEL.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND TEL.CODIGO_PESSOA = P.CODIGO AND TEL.PREFERENCIAL = 'S'
LEFT OUTER JOIN 
    ARTERH.RHORGA_UNIDADE UNIDADE ON UNIDADE.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND UNIDADE.COD_UNIDADE1 = C.COD_UNIDADE1 AND UNIDADE.COD_UNIDADE2 = C.COD_UNIDADE2 AND UNIDADE.COD_UNIDADE3 = C.COD_UNIDADE3 AND UNIDADE.COD_UNIDADE4 = C.COD_UNIDADE4 AND UNIDADE.COD_UNIDADE5 = C.COD_UNIDADE5 AND UNIDADE.COD_UNIDADE6 = C.COD_UNIDADE6
LEFT OUTER JOIN 
    ARTERH.RHORGA_LOTACAO LOTACAO ON LOTACAO.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND LOTACAO.COD_LOTACAO1 = C.COD_LOCAL1 AND LOTACAO.COD_LOTACAO2 = C.COD_LOCAL2 AND LOTACAO.COD_LOTACAO3 = C.COD_LOCAL3 AND LOTACAO.COD_LOTACAO4 = C.COD_LOCAL4 AND LOTACAO.COD_LOTACAO5 = C.COD_LOCAL5 AND LOTACAO.COD_LOTACAO6 = C.COD_LOCAL6
LEFT OUTER JOIN 
    ARTERH.RHPLCS_CARGO CE ON CE.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND CE.CODIGO = C.COD_CARGO_EFETIVO
LEFT OUTER JOIN 
    ARTERH.RHPLCS_CARGO CC ON CC.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND CC.CODIGO = C.COD_CARGO_COMISS
LEFT OUTER JOIN 
    ARTERH.rhorga_custo_geren G ON G.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND G.COD_CGERENC1 = C.COD_CUSTO_GERENC1 AND G.COD_CGERENC2 = C.COD_CUSTO_GERENC2 AND G.COD_CGERENC3 = C.COD_CUSTO_GERENC3 AND G.COD_CGERENC4 = C.COD_CUSTO_GERENC4 AND G.COD_CGERENC5 = C.COD_CUSTO_GERENC5 AND G.COD_CGERENC6 = C.COD_CUSTO_GERENC6
LEFT OUTER JOIN 
    ARTERH.RHPLCS_FUNCAO F ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO = C.CODIGO_FUNCAO
LEFT OUTER JOIN 
    ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO = C.SITUACAO_FUNCIONAL
LEFT OUTER JOIN 
    ARTERH.RHUSER_P_SIST@LK_HOM_PBH12 AD ON 
    AD.EMPRESA_USUARIO = C.CODIGO_EMPRESA AND
    AD.TP_CONTR_USUARIO = C.TIPO_CONTRATO AND
    AD.CONTRATO_USUARIO = C.CODIGO AND
    AD.STATUS_USUARIO = CASE WHEN C.DATA_RESCISAO IS NOT NULL THEN 'E' ELSE 'A' END AND
    (
        (C.DATA_RESCISAO IS NULL AND USUARIO_LDAP IS NOT NULL) OR
        (C.DATA_RESCISAO IS NOT NULL AND USUARIO_LDAP IS NULL)
    ) AND
    AD.TIPO_LOGIN IN ('2', '3') AND
    AD.CODIGO_SERV_AUTENT = 'PWS1'
JOIN MaxAnoMes M ON 
    M.CODIGO = C.CODIGO AND
    M.TIPO_CONTRATO = C.TIPO_CONTRATO AND
    M.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND
    M.MAX_ANO_MES_REFERENCIA = C.ANO_MES_REFERENCIA
WHERE 
    C.CODIGO_EMPRESA IN ('0001', '0003', '0005', '0007', '0013', '0014')
AND (
    (C.DATA_RESCISAO >= TO_DATE('01/01/2013', 'DD/MM/YYYY')) OR
    (C.DATA_RESCISAO IS NULL)
)