
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VIEW_SIGBASES_ESCALA_CARGO" ("CODIGO_EMPRESA", "CODIGO_CARGO", "NOME_CARGO", "CBO2002", "CBO", "CODIGO_ESCALA", "DESCRICAO_ESCALA", "ABREVIACAO_ESCALA", "ULTIMA_ALTERCAO") AS 
  SELECT CG.CODIGO_EMPRESA,CG.CODIGO AS CODIGO_CARGO,CG.DESCRICAO AS NOME_CARGO,CG.cbo2002, CG.CBO,  EL.CODIGO AS CODIGO_ESCALA,EL.DESCRICAO AS DESCRICAO_ESCALA, EL.ABREVIACAO AS ABREVIACAO_ESCALA,JORNADA.DT_ULT_ALTER_USUA AS ULTIMA_ALTERCAO FROM ARTERH.RHPLCS_CARGO CG
INNER JOIN ARTERH.RHPLCS_CARG_JOR_TB JORNADA 
ON CG.CODIGO_EMPRESA=JORNADA.CODIGO_EMPRESA
AND CG.CODIGO=JORNADA.CODIGO_CARGO
INNER JOIN ARTERH.RHPONT_ESCALA EL 
ON EL.CODIGO_EMPRESA=CG.CODIGO_EMPRESA
AND EL.TIPO_JORNADA=jornada.tipo_jornada
WHERE CG.CODIGO_EMPRESA='0001'