
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_ARQUIVO_0004" ("ID_ARQUIVO", "CODIGO_EMPRESA_ARQUIVO", "SITUACAO_ARQUIVO", "DATA_CARGA", "NUMERO_LINHA", "SITUACAO_LINHA", "LINHA_ORIGINAL", "PERIODO_REFERENCIA", "CODIGO_EMPRESA", "CODIGO_CONTRATO", "CPF", "CNPJ_FORNECEDOR", "TIPO_BENEFICIO", "CODIGO_VERBA", "VALOR_VERBA") AS 
  select
RHPBH_ARQUIVO.ID_ARQUIVO,
RHPBH_ARQUIVO.CODIGO_EMPRESA AS CODIGO_EMPRESA_ARQUIVO,
RHPBH_ARQUIVO.SITUACAO AS SITUACAO_ARQUIVO,
RHPBH_ARQUIVO.DATA_CARGA,
RHPBH_ARQUIVO_LINHA.NUMERO_LINHA,
RHPBH_ARQUIVO_LINHA.SITUACAO AS SITUACAO_LINHA,
RHPBH_ARQUIVO_LINHA.LINHA AS LINHA_ORIGINAL,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 1)	AS	PERIODO_REFERENCIA,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 2)	AS	CODIGO_EMPRESA,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 3)	AS	CODIGO_CONTRATO,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 4)	AS	CPF,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 5)	AS	CNPJ_FORNECEDOR,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 6)	AS	TIPO_BENEFICIO,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 7)	AS	CODIGO_VERBA,
regexp_substr(REPLACE(RHPBH_ARQUIVO_LINHA.LINHA,';;','; ;'), '[^;]+', 1, 8)	AS	VALOR_VERBA
  from RHPBH_ARQUIVO, RHPBH_ARQUIVO_LINHA
 where RHPBH_ARQUIVO.ID_ARQUIVO = RHPBH_ARQUIVO_LINHA.ID_ARQUIVO
   and RHPBH_ARQUIVO.TIPO_ARQUIVO = '0004'