
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_ARQUIVO_0003" ("ID_ARQUIVO", "CODIGO_EMPRESA_ARQUIVO", "SITUACAO_ARQUIVO", "DATA_CARGA", "NUMERO_LINHA", "SITUACAO_LINHA", "LINHA_ORIGINAL", "OPERACAO", "PERIODO_REFERENCIA", "CODIGO_EMPRESA", "INDICADOR_EMPRESA", "MATRICULA", "CPF_SERVIDOR", "CPF_BENEFICIARIO", "ADE_NUMERO", "NUMERO_CARTEIRA", "NUMERO_CONTRATO_OPERADORA", "CNPJ_FORNECEDOR", "CODIGO_VERBA", "VALOR_VERBA", "NUMERO_PARCELAS", "DATA_AUTORIZACAO_INICIAL", "DATA_AUTORIZACAO_CORRENTE", "VALOR_DESCONTADO", "CODIGO_SITUACAO_FUNCIONAL", "FUNDO_REPASSE") AS 
  select
RHPBH_ARQUIVO.ID_ARQUIVO,
RHPBH_ARQUIVO.CODIGO_EMPRESA AS CODIGO_EMPRESA_ARQUIVO,
RHPBH_ARQUIVO.SITUACAO AS SITUACAO_ARQUIVO,
RHPBH_ARQUIVO.DATA_CARGA,
RHPBH_ARQUIVO_LINHA.NUMERO_LINHA,
RHPBH_ARQUIVO_LINHA.SITUACAO AS SITUACAO_LINHA,
RHPBH_ARQUIVO_LINHA.LINHA AS LINHA_ORIGINAL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	1	  ,	1	  )	AS	OPERACAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	2	  ,	8	  )	AS	PERIODO_REFERENCIA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	10	,	4	  )	AS	CODIGO_EMPRESA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	14	,	2	  )	AS	INDICADOR_EMPRESA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	16	,	15	)	AS	MATRICULA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	31	,	11	)	AS	CPF_SERVIDOR,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	42	,	11	)	AS	CPF_BENEFICIARIO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	53	,	10	)	AS	ADE_NUMERO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	63	,	23	)	AS	NUMERO_CARTEIRA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	86	,	10	)	AS	NUMERO_CONTRATO_OPERADORA ,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	96	,	14	)	AS	CNPJ_FORNECEDOR,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	110	,	4	  )	AS	CODIGO_VERBA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	114	,	10	)	AS	VALOR_VERBA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	124	,	3	  )	AS	NUMERO_PARCELAS,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	127	,	14	)	AS	DATA_AUTORIZACAO_INICIAL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	141	,	14	)	AS	DATA_AUTORIZACAO_CORRENTE,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	155	,	10	)	AS	VALOR_DESCONTADO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	165	,	2	  )	AS	CODIGO_SITUACAO_FUNCIONAL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA,	167	,	2	  )	AS	FUNDO_REPASSE
  from RHPBH_ARQUIVO, RHPBH_ARQUIVO_LINHA
 where RHPBH_ARQUIVO.ID_ARQUIVO = RHPBH_ARQUIVO_LINHA.ID_ARQUIVO
   and RHPBH_ARQUIVO.TIPO_ARQUIVO = '0003'