
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_ARQUIVO_0002_POSICAO" ("ID_ARQUIVO", "CODIGO_EMPRESA_ARQUIVO", "SITUACAO_ARQUIVO", "DATA_CARGA", "NUMERO_LINHA", "SITUACAO_LINHA", "LINHA_ORIGINAL", "IDENTIFICADOR_ARQUIVO", "DATA_HORA_GERACAO_ARQUIVO", "SEQUENCIAL_REGISTRO", "TIPO_OPERACAO", "CODIGO_EMPRESA", "CODIGO_CONTRATO", "CPF", "NOME", "DATA_NASCIMENTO", "CODIGO_SEXO", "CODIGO_TIPO_RELACIONAMENTO", "CODIGO_ESTADO_CIVIL", "IDENTIDADE", "NOME_DA_MAE", "CODIGO_TIPO_LOGRADOURO", "ENDERECO", "NUMERO", "COMPLEMENTO", "BAIRRO", "CODIGO_MUNICIPIO", "UF", "CEP", "TELEFONE_FIXO", "TELEFONE_CELULAR", "DATA_CADASTRAMENTO") AS 
  select
RHPBH_ARQUIVO.ID_ARQUIVO,
RHPBH_ARQUIVO.CODIGO_EMPRESA AS CODIGO_EMPRESA_ARQUIVO,
RHPBH_ARQUIVO.SITUACAO AS SITUACAO_ARQUIVO,
RHPBH_ARQUIVO.DATA_CARGA,
RHPBH_ARQUIVO_LINHA.NUMERO_LINHA,
RHPBH_ARQUIVO_LINHA.SITUACAO AS SITUACAO_LINHA,
RHPBH_ARQUIVO_LINHA.LINHA AS LINHA_ORIGINAL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 001,04)  AS IDENTIFICADOR_ARQUIVO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 006,14)  AS DATA_HORA_GERACAO_ARQUIVO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 021,06)  AS SEQUENCIAL_REGISTRO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 028,01)  AS TIPO_OPERACAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 030,04)  AS CODIGO_EMPRESA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 035,15)  AS CODIGO_CONTRATO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 051,11)  AS CPF,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 063,60)  AS NOME,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 124,08)  AS DATA_NASCIMENTO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 133,04)  AS CODIGO_SEXO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 138,04)  AS CODIGO_TIPO_RELACIONAMENTO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 143,04)  AS CODIGO_ESTADO_CIVIL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 148,20)  AS IDENTIDADE,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 169,60)  AS NOME_DA_MAE,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 230,04)  AS CODIGO_TIPO_LOGRADOURO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 235,40)  AS ENDERECO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 276,10)  AS NUMERO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 287,40)  AS COMPLEMENTO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 328,40)  AS BAIRRO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 369,07)  AS CODIGO_MUNICIPIO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 377,02)  AS UF,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 380,08)  AS CEP,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 389,10)  AS TELEFONE_FIXO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 400,11)  AS TELEFONE_CELULAR,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 412,14)  AS DATA_CADASTRAMENTO
  from RHPBH_ARQUIVO, RHPBH_ARQUIVO_LINHA
 where RHPBH_ARQUIVO.ID_ARQUIVO = RHPBH_ARQUIVO_LINHA.ID_ARQUIVO
   and RHPBH_ARQUIVO.TIPO_ARQUIVO = '0002'