
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_ARQUIVO_0001_POSICAO" ("ID_ARQUIVO", "CODIGO_EMPRESA_ARQUIVO", "SITUACAO_ARQUIVO", "DATA_CARGA", "NUMERO_LINHA", "SITUACAO_LINHA", "LINHA_ORIGINAL", "IDENTIFICADOR_ARQUIVO", "DATA_HORA_GERACAO_ARQUIVO", "SEQUENCIAL_REGISTRO", "TIPO_OPERACAO", "CODIGO_EMPRESA", "CODIGO_CONTRATO", "CPF", "REGISTRO_ANS", "CODIGO_BENEFICIO", "CATEGORIA_BENEFICIARIO", "ORDEM_DEPENDENCIA", "MOTIVO_CONCESSAO", "DATA_CONCESSAO", "MOTIVO_CANCELAMENTO", "DATA_CANCELAMENTO", "OBSERVACAO", "NUMERO_CARTEIRA", "NUMERO_PROTOCOLO", "DATA_FIM_EXCECAO_DEPENDENCIA", "EXCECAO_DEPENDENCIA", "DATA_CADASTRAMENTO") AS 
  select
RHPBH_ARQUIVO.ID_ARQUIVO,
RHPBH_ARQUIVO.CODIGO_EMPRESA AS CODIGO_EMPRESA_ARQUIVO,
RHPBH_ARQUIVO.SITUACAO AS SITUACAO_ARQUIVO,
RHPBH_ARQUIVO.DATA_CARGA,
RHPBH_ARQUIVO_LINHA.NUMERO_LINHA,
RHPBH_ARQUIVO_LINHA.SITUACAO AS SITUACAO_LINHA,
RHPBH_ARQUIVO_LINHA.LINHA AS LINHA_ORIGINAL,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 001,04)  AS IDENTIFICADOR_ARQUIVO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 006,14)  AS DATA_HORA_GERACAO_ARQUIVO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 021,06)  AS SEQUENCIAL_REGISTRO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 028,01)  AS TIPO_OPERACAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 030,04)  AS CODIGO_EMPRESA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 035,15)  AS CODIGO_CONTRATO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 051,11)  AS CPF,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 063,15)  AS REGISTRO_ANS,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 079,15)  AS CODIGO_BENEFICIO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 095,04)  AS CATEGORIA_BENEFICIARIO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 100,02)  AS ORDEM_DEPENDENCIA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 103,04)  AS MOTIVO_CONCESSAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 108,08)  AS DATA_CONCESSAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 117,04)  AS MOTIVO_CANCELAMENTO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 122,08)  AS DATA_CANCELAMENTO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 131,60)  AS OBSERVACAO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 192,30)  AS NUMERO_CARTEIRA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 223,30)  AS NUMERO_PROTOCOLO,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 254,08)  AS DATA_FIM_EXCECAO_DEPENDENCIA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 263,01)  AS EXCECAO_DEPENDENCIA,
SUBSTR(RHPBH_ARQUIVO_LINHA.LINHA, 265,14)  AS DATA_CADASTRAMENTO
  from RHPBH_ARQUIVO, RHPBH_ARQUIVO_LINHA
 where RHPBH_ARQUIVO.ID_ARQUIVO = RHPBH_ARQUIVO_LINHA.ID_ARQUIVO
   and RHPBH_ARQUIVO.TIPO_ARQUIVO = '0001'