
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_AFASTAMENTOS" ("CODIGO_EMPRESA", "TIPO_CONTRATO", "CODIGO_CONTRATO", "CODIGO_LEGADO", "CODIGO_JUSTIFICATIVA", "DATA_INICIO", "DATA_FIM", "TIPO", "DT_SAIU_ARTE", "DT_ENVIADO_IFPONTO_SURICATO", "CODIGO_INTEGRA_ARTE", "PK_ARTE") AS 
  SELECT CODIGO_EMPRESA,
            TIPO_CONTRATO,
            CODIGO_CONTRATO,
            CODIGO_LEGADO,
            CODIGO_JUSTIFICATIVA,
            DATA_INICIO,
            DATA_FIM,
            TIPO,
            DT_SAIU_ARTE,
            DT_ENVIADO_IFPONTO_SURICATO
            ,CODIGO_INTEGRA_ARTE 
            ,PK_ARTE
       FROM PONTO_ELETRONICO.SMARH_INT_PE_AFASTAMENTOS_V1
      WHERE DT_ENVIADO_IFPONTO_SURICATO IS NULL
   GROUP BY CODIGO_EMPRESA,
            TIPO_CONTRATO,
            CODIGO_CONTRATO,
            CODIGO_LEGADO,
            CODIGO_JUSTIFICATIVA,
            DATA_INICIO,
            DATA_FIM,
            DT_SAIU_ARTE,
            DT_ENVIADO_IFPONTO_SURICATO,
            TIPO
            ,CODIGO_INTEGRA_ARTE 
            ,PK_ARTE
   ORDER BY CODIGO_EMPRESA,
            TIPO_CONTRATO,
            CODIGO_CONTRATO,
            CODIGO_LEGADO,
            CODIGO_JUSTIFICATIVA,
            DATA_INICIO,
            DATA_FIM,
            DT_SAIU_ARTE,
            DT_ENVIADO_IFPONTO_SURICATO,
            TIPO