
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_CONSULTA_LOTACAO" ("CODIGO_EMPRESA", "COD_UNIDADE1", "COD_UNIDADE2", "COD_UNIDADE3", "COD_UNIDADE4", "COD_UNIDADE5", "COD_UNIDADE6", "DESCRICAO", "ABREVIACAO", "RAZAO_SOCIAL", "CGC", "COD_PESSOA_RESP", "DT_ULT_ALTER_USUA", "DATA_IMPLANT", "DATA_EXTINCAO") AS 
  SELECT
UNIDADE.CODIGO_EMPRESA,
UNIDADE.COD_UNIDADE1,
UNIDADE.COD_UNIDADE2,
UNIDADE.COD_UNIDADE3,
UNIDADE.COD_UNIDADE4,
UNIDADE.COD_UNIDADE5,
UNIDADE.COD_UNIDADE6,
UNIDADE.DESCRICAO,
UNIDADE.ABREVIACAO,
UNIDADE.RAZAO_SOCIAL,
UNIDADE.CGC,
UNIDADE.COD_PESSOA_RESP,
UNIDADE.DT_ULT_ALTER_USUA,
UNIDADE.DATA_IMPLANT,
UNIDADE.DATA_EXTINCAO
FROM
RHORGA_UNIDADE UNIDADE
WHERE UNIDADE.CODIGO_EMPRESA = '0010' AND UNIDADE.COD_UNIDADE1 = '000089'
UNION
SELECT
U.CODIGO_EMPRESA,
U.COD_UNIDADE1,
U.COD_UNIDADE2,
U.COD_UNIDADE3,
U.COD_UNIDADE4,
U.COD_UNIDADE5,
U.COD_UNIDADE6,
U.DESCRICAO,
U.ABREVIACAO,
U.RAZAO_SOCIAL,
U.CGC,
U.COD_PESSOA_RESP,
U.DT_ULT_ALTER_USUA,
U.DATA_IMPLANT,
U.DATA_EXTINCAO
FROM
RHORGA_UNIDADE U,
RHPESS_CONTRATO CONTRATO
WHERE CONTRATO.CODIGO_EMPRESA = '0010' AND
((CONTRATO.CODIGO_EMPRESA = U.CODIGO_EMPRESA) AND
(CONTRATO.COD_UNIDADE1 = U.COD_UNIDADE1) AND
(CONTRATO.COD_UNIDADE2 = U.COD_UNIDADE2) AND
(CONTRATO.COD_UNIDADE3 = U.COD_UNIDADE3) AND
(CONTRATO.COD_UNIDADE4 = U.COD_UNIDADE4) AND
(CONTRATO.COD_UNIDADE5 = U.COD_UNIDADE5) AND
(CONTRATO.COD_UNIDADE6 = U.COD_UNIDADE6)) AND
(CONTRATO.ANO_MES_REFERENCIA = (SELECT MAX(ARTERH_CONTRATO.ANO_MES_REFERENCIA) FROM
RHPESS_CONTRATO ARTERH_CONTRATO WHERE
CONTRATO.CODIGO_EMPRESA = ARTERH_CONTRATO.CODIGO_EMPRESA AND
CONTRATO.TIPO_CONTRATO = ARTERH_CONTRATO.TIPO_CONTRATO AND
CONTRATO.CODIGO = ARTERH_CONTRATO.CODIGO AND
ARTERH_CONTRATO.ANO_MES_REFERENCIA >= (SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL))) AND
CONTRATO.COD_UNIDADE1 <> '000089'