
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_DEPENDENTE_PROFISSIONAL_CONTRATO_DBV" ("CODIGO_EMPRESA", "EMPRESA", "MATRICULA_TITULAR", "NOME_TITULAR", "CPF", "CODIGO_DEPENDENTE", "NOME_DEPENDENTE", "CPF_DEPENDENTE", "ID_PARENTESCO", "GRAU_PARENTESCO") AS 
  SELECT CNT.CODIGO_EMPRESA,
       CASE 
          WHEN CNT.CODIGO_EMPRESA = '0001' AND CNT.TIPO_CONTRATO = '0001' THEN 'PBH'
          WHEN CNT.CODIGO_EMPRESA = '0001' AND CNT.TIPO_CONTRATO = '0098' THEN 'CONTRATOS PBH'
          WHEN CNT.CODIGO_EMPRESA = '0001' AND NVL(CNT.C_LIVRE_SELEC02,0) IN (21,0) AND CNT.TIPO_CONTRATO <> '0015' THEN 'CONTRATOS SA'
          WHEN CNT.CODIGO_EMPRESA = '0001' AND NVL(CNT.C_LIVRE_SELEC02,0) =  32     AND CNT.TIPO_CONTRATO <> '0015' THEN 'ZOONOZES'
          WHEN CNT.CODIGO_EMPRESA = '0001' AND NVL(CNT.C_LIVRE_SELEC02,0) =  0      AND CNT.TIPO_CONTRATO  = '0015' THEN 'SAUDE'
          WHEN CNT.CODIGO_EMPRESA = '0002'                                                                          THEN 'PRODABEL'
          WHEN CNT.CODIGO_EMPRESA = '0003'                                                                          THEN 'SUDECAP'
          WHEN CNT.CODIGO_EMPRESA = '0005'                                                                          THEN 'SUMOB'
          WHEN CNT.CODIGO_EMPRESA = '0007'                                                                          THEN 'SLU'
          WHEN CNT.CODIGO_EMPRESA = '0009'                                                                          THEN 'BELOTUR'
          WHEN CNT.CODIGO_EMPRESA = '0010'                                                                          THEN 'URBEL'
          WHEN CNT.CODIGO_EMPRESA = '0013'                                                                          THEN 'FMC'
          WHEN CNT.CODIGO_EMPRESA = '0014'                                                                          THEN 'FPM' 
       ELSE
          'N/A'
       END AS EMPRESA,       
       SUBSTR(CNT.CODIGO,7,8) || '-' ||SUBSTR(CNT.CODIGO,15,1) AS MATRICULA_TITULAR,
       CNT.NOME AS NOME_TITULAR,
       PES.CPF,
       DEP.COD_PESSOA_RELAC AS CODIGO_DEPENDENTE,
       DEP.NOME AS NOME_DEPENDENTE,
       DEP.CPF AS CPF_DEPENDENTE,
       DEP.TP_RELACIONAMENTO AS ID_PARENTESCO,
	   DEP.DESCRICAO AS GRAU_PARENTESCO
FROM RHPESS_CONTRATO CNT
     INNER JOIN RHPESS_PESSOA PES ON PES.CODIGO = CNT.CODIGO_PESSOA AND PES.CODIGO_EMPRESA = CNT.CODIGO_EMPRESA 
     ,(SELECT COD_PESSOA,D.COD_PESSOA_RELAC, P.NOME ,D.TP_RELACIONAMENTO,TR.DESCRICAO,P.CPF
       FROM   RHPESS_RL_PESS_PES D
              INNER JOIN RHPESS_PESSOA P ON P.CODIGO = D.COD_PESSOA_RELAC AND P.CODIGO_EMPRESA = D.COD_EMPRESA
              INNER JOIN RHPESS_TIPO_RELAC TR ON TR.CODIGO = D.TP_RELACIONAMENTO) DEP
WHERE CNT.CODIGO_EMPRESA IN ('0001','0002','0003','0005','0007','0009','0010','0013','0014')
AND CNT.ANO_MES_REFERENCIA  = ( SELECT MAX (CNT2.ANO_MES_REFERENCIA)
							    FROM ARTERH.RHPESS_CONTRATO CNT2
								WHERE CNT2.CODIGO              = CNT.CODIGO											  
								AND   TRUNC(CNT2.ANO_MES_REFERENCIA) <= (SELECT DT_MAX_DATAS FROM ARTERH.RHPARM_P_SIST)
								AND   CNT2.TIPO_CONTRATO       = CNT.TIPO_CONTRATO
								AND   CNT2.CODIGO_EMPRESA      = CNT.CODIGO_EMPRESA)
AND  CNT.DATA_RESCISAO IS NULL
AND  DEP.COD_PESSOA = CNT.CODIGO_PESSOA
ORDER BY CNT.CODIGO,DEP.COD_PESSOA_RELAC