
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_FERIAS" ("CODIGO_EMPRESA", "EMPRESA", "AGRUPAMENTO_EMPRESA", "TIPO_CONTRATO", "CODIGO_CONTRATO", "DT_INI_AQUISICAO", "TIPO_FERIAS", "PERIODO", "DT_INI_GOZO", "DT_FIM_GOZO", "TIPO", "SITUACAO_PONTO", "CODIGO_LEGADO") AS 
  ( select "CODIGO_EMPRESA", "EMPRESA", "AGRUPAMENTO_EMPRESA", "TIPO_CONTRATO", "CODIGO_CONTRATO", "DT_INI_AQUISICAO" ,"TIPO_FERIAS" ,"PERIODO","DT_INI_GOZO", "DT_FIM_GOZO", "TIPO","SITUACAO_PONTO","CODIGO_LEGADO"
from SMARH_INT_PE_FERIAS_V3 
where --1= 0-- codigo_contrato = '000000001110215' 
DT_ENVIADO_IFPONTO_SURICATO is null)