
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_GIGPES_TP_CONTRATO" ("CODIGO", "DESCRICAO", "MESES_PRORROG", "LOGIN_USUARIO", "DT_ULT_ALTER_USUA", "USA_BALCAO", "EXIGE_ESCALA", "EXIGE_VAGA_POS", "PERMITE_VAGA_CONC", "TEM_IRRF", "TEM_INSS", "TEM_FGTS", "TEM_FERIAS", "TEM_RESCISAO", "TEM_SAL_FAMILIA", "TEM_SAL_MATERN", "TEM_CONTRIB_SIND", "CODIGO_LISTA_CONTR", "DT_REFER_MOVTO", "DT_REFER_CADASTRO", "DT_REFER_PONTO", "COD_PARM_SELE_PER", "SIT_FUNC_RESC", "CAUSA_RESCISAO", "MOTIVO_DEMISSAO", "COD_MOVIMENTACAO", "CATEG_PESSOA_RESC", "ATUAL_RL_PESS_CAT", "L_CONTR_COD_UNICO", "TEXTO_ASSOCIADO") AS 
  SELECT "CODIGO", "DESCRICAO", "MESES_PRORROG", "LOGIN_USUARIO",  "DT_ULT_ALTER_USUA", "USA_BALCAO", "EXIGE_ESCALA",
       "EXIGE_VAGA_POS", "PERMITE_VAGA_CONC","TEM_IRRF", "TEM_INSS", "TEM_FGTS", "TEM_FERIAS", "TEM_RESCISAO",
         "TEM_SAL_FAMILIA", "TEM_SAL_MATERN", "TEM_CONTRIB_SIND", "CODIGO_LISTA_CONTR", "DT_REFER_MOVTO",
           "DT_REFER_CADASTRO", "DT_REFER_PONTO", "COD_PARM_SELE_PER", "SIT_FUNC_RESC", "CAUSA_RESCISAO",
             "MOTIVO_DEMISSAO", "COD_MOVIMENTACAO","CATEG_PESSOA_RESC", "ATUAL_RL_PESS_CAT", "L_CONTR_COD_UNICO",
               "TEXTO_ASSOCIADO" FROM RHPESS_TP_CONTRATO
