
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_GIGPES_MOT_INTERRUPCAO" ("COD_MOT_INTERRUPCAO", "DESCRICAO", "ABREVIACAO", "INDENIZAVEL", "TEXTO_ASSOCIADO", "LOGIN_USUARIO", "DT_ULT_ALTER_USUA") AS 
  SELECT "COD_MOT_INTERRUPCAO", "DESCRICAO", "ABREVIACAO", "INDENIZAVEL", "TEXTO_ASSOCIADO", "LOGIN_USUARIO", "DT_ULT_ALTER_USUA"
FROM RHFERI_MOT_INTERRUPCAO
