
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_GIGPES_SUBSTITUTO" ("CODIGO_USUARIO", "CODIGO_USUARIO_SUBSTITUTO", "ID_AGRUP", "CODIGO_CONTRATO", "CODIGO_EMPRESA", "TIPO_CONTRATO", "NOME", "NOME_COMPOSTO", "STATUS_USUARIO") AS 
  SELECT P_SIST.CODIGO_USUARIO AS CODIGO_USUARIO,
       P_SIST_SUBSTITUTO.CODIGO_USUARIO AS CODIGO_USUARIO_SUBSTITUTO,
       AGRUP_SUBSEC.ID_AGRUP AS ID_AGRUP,
       CONTRATO.CODIGO AS CODIGO_CONTRATO,
       CONTRATO.CODIGO_EMPRESA AS CODIGO_EMPRESA,
       CONTRATO.TIPO_CONTRATO AS TIPO_CONTRATO,
       CONTRATO.NOME AS NOME,
       CONTRATO_MESTRE.NOME_COMPOSTO AS NOME_COMPOSTO,
       P_SIST.STATUS_USUARIO AS STATUS_USUARIO
FROM RHPESS_CONTRATO CONTRATO_USUARIO,
     RHPESS_CONTRATO CONTRATO,
   rhpess_contr_mest CONTRATO_MESTRE,
     RHUSER_P_SIST P_SIST,
     RHUSER_P_SIST P_SIST_SUBSTITUTO,
     RHORGA_AGRUPADOR AGRUP_SUBSEC,
     RHORGA_AGRUPADOR AGRUP_USUA,
     RHORGA_ESTRUT_AGR ESTRUT_AGR,
     RHORGA_ESTRUT_AGR ESTRUT_SUBSEC
WHERE CONTRATO_USUARIO.CODIGO_EMPRESA=P_SIST.EMPRESA_USUARIO
  AND CONTRATO_USUARIO.TIPO_CONTRATO=P_SIST.TP_CONTR_USUARIO
  AND CONTRATO_USUARIO.CODIGO=P_SIST.CONTRATO_USUARIO
  AND CONTRATO.CODIGO_EMPRESA=P_SIST_SUBSTITUTO.EMPRESA_USUARIO
  AND CONTRATO.TIPO_CONTRATO=P_SIST_SUBSTITUTO.TP_CONTR_USUARIO
  AND CONTRATO.CODIGO=P_SIST_SUBSTITUTO.CONTRATO_USUARIO
  AND CONTRATO.CODIGO=CONTRATO_MESTRE.CODIGO_CONTRATO
  AND CONTRATO.TIPO_CONTRATO=CONTRATO_MESTRE.TIPO_CONTRATO
  AND CONTRATO.CODIGO_EMPRESA=CONTRATO_MESTRE.CODIGO_EMPRESA
  AND P_SIST_SUBSTITUTO.STATUS_USUARIO='A'
  AND ESTRUT_AGR.CODIGO_EMPRESA = ESTRUT_SUBSEC.CODIGO_EMPRESA
  AND ESTRUT_AGR.ID_AGRUP_SUP = ESTRUT_SUBSEC.ID_AGRUP_SUP
  AND ESTRUT_AGR.CODIGO_EMPRESA = AGRUP_SUBSEC.CODIGO_EMPRESA
  AND ESTRUT_AGR.ID_AGRUP = AGRUP_SUBSEC.ID_AGRUP
  AND ESTRUT_AGR.ANO_MES_REFERENCIA =
    (SELECT max(ESTRUT_AGR_MAX.ANO_MES_REFERENCIA)
     FROM RHORGA_ESTRUT_AGR ESTRUT_AGR_MAX
     WHERE ESTRUT_AGR_MAX.CODIGO_EMPRESA=ESTRUT_AGR.CODIGO_EMPRESA
       AND ESTRUT_AGR_MAX.ID_AGRUP_SUP=ESTRUT_AGR.ID_AGRUP_SUP
       AND ESTRUT_AGR_MAX.ID_AGRUP=ESTRUT_AGR.ID_AGRUP
       AND ESTRUT_AGR_MAX.ANO_MES_REFERENCIA < sysdate )
  AND ESTRUT_SUBSEC.CODIGO_EMPRESA = AGRUP_USUA.CODIGO_EMPRESA
  AND ESTRUT_SUBSEC.ID_AGRUP = AGRUP_USUA.ID_AGRUP
  AND ESTRUT_SUBSEC.NIVEL_SUP_AGR_EST=3
  AND ESTRUT_SUBSEC.ANO_MES_REFERENCIA =
    (SELECT max(ESTRUT_AGR_MAX.ANO_MES_REFERENCIA)
     FROM RHORGA_ESTRUT_AGR ESTRUT_AGR_MAX
     WHERE ESTRUT_AGR_MAX.CODIGO_EMPRESA=ESTRUT_SUBSEC.CODIGO_EMPRESA
       AND ESTRUT_AGR_MAX.ID_AGRUP_SUP=ESTRUT_SUBSEC.ID_AGRUP_SUP
       AND ESTRUT_AGR_MAX.ID_AGRUP=ESTRUT_SUBSEC.ID_AGRUP
       AND ESTRUT_AGR_MAX.ANO_MES_REFERENCIA < sysdate )
  AND AGRUP_USUA.TIPO_AGRUP=P_SIST.TIPO_AGRUP_USUARIO
  AND AGRUP_SUBSEC.TIPO_AGRUP=P_SIST.TIPO_AGRUP_USUARIO
  AND AGRUP_SUBSEC.DATA_EXTINCAO IS NULL
  AND ((AGRUP_USUA.TIPO_AGRUP = 'G'
           AND AGRUP_USUA.TIPO_AGRUP = CONTRATO_USUARIO.TIPO_AGRUP_CGER
           AND AGRUP_USUA.COD_AGRUP1 = CONTRATO_USUARIO.COD_CUSTO_GERENC1
           AND AGRUP_USUA.COD_AGRUP2 = CONTRATO_USUARIO.COD_CUSTO_GERENC2
           AND AGRUP_USUA.COD_AGRUP3 = CONTRATO_USUARIO.COD_CUSTO_GERENC3
           AND AGRUP_USUA.COD_AGRUP4 = CONTRATO_USUARIO.COD_CUSTO_GERENC4
           AND AGRUP_USUA.COD_AGRUP5 = CONTRATO_USUARIO.COD_CUSTO_GERENC5
           AND AGRUP_USUA.COD_AGRUP6 = CONTRATO_USUARIO.COD_CUSTO_GERENC6))
  AND ((AGRUP_SUBSEC.TIPO_AGRUP = 'G'
           AND AGRUP_SUBSEC.TIPO_AGRUP = CONTRATO.TIPO_AGRUP_CGER
           AND AGRUP_SUBSEC.COD_AGRUP1 = CONTRATO.COD_CUSTO_GERENC1
           AND AGRUP_SUBSEC.COD_AGRUP2 = CONTRATO.COD_CUSTO_GERENC2
           AND AGRUP_SUBSEC.COD_AGRUP3 = CONTRATO.COD_CUSTO_GERENC3
           AND AGRUP_SUBSEC.COD_AGRUP4 = CONTRATO.COD_CUSTO_GERENC4
           AND AGRUP_SUBSEC.COD_AGRUP5 = CONTRATO.COD_CUSTO_GERENC5
           AND AGRUP_SUBSEC.COD_AGRUP6 = CONTRATO.COD_CUSTO_GERENC6))
  AND (CONTRATO.DATA_RESCISAO IS NULL
       OR CONTRATO.DATA_RESCISAO > sysdate)
  AND CONTRATO.ANO_MES_REFERENCIA=
    (SELECT max(MAX_CONTRATO.ANO_MES_REFERENCIA)
     FROM RHPESS_CONTRATO MAX_CONTRATO
     WHERE MAX_CONTRATO.CODIGO_EMPRESA=CONTRATO.CODIGO_EMPRESA
       AND MAX_CONTRATO.TIPO_CONTRATO=CONTRATO.TIPO_CONTRATO
       AND MAX_CONTRATO.CODIGO=CONTRATO.CODIGO
       AND MAX_CONTRATO.ANO_MES_REFERENCIA > trunc(sysdate, 'yyyy'))
  AND (CONTRATO_USUARIO.DATA_RESCISAO IS NULL
       OR CONTRATO_USUARIO.DATA_RESCISAO > sysdate)
  AND CONTRATO_USUARIO.ANO_MES_REFERENCIA=
    (SELECT max(MAX_CONTRATO.ANO_MES_REFERENCIA)
     FROM RHPESS_CONTRATO MAX_CONTRATO
     WHERE MAX_CONTRATO.CODIGO_EMPRESA=CONTRATO_USUARIO.CODIGO_EMPRESA
       AND MAX_CONTRATO.TIPO_CONTRATO=CONTRATO_USUARIO.TIPO_CONTRATO
       AND MAX_CONTRATO.CODIGO=CONTRATO_USUARIO.CODIGO
       AND MAX_CONTRATO.ANO_MES_REFERENCIA > trunc(sysdate, 'yyyy'))
ORDER BY CONTRATO.NOME