
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_GIGPES_PADR_SEL_CONT" ("CODIGO_GRUPO", "CODIGO", "DESCRICAO", "ABREVIACAO", "TEXTO_ASSOCIADO") AS 
  SELECT "CODIGO_GRUPO", "CODIGO", "DESCRICAO", "ABREVIACAO", "TEXTO_ASSOCIADO" FROM RHPESS_P_SEL_CONT
