
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_IFPONTO_FECHAMENTO" ("TIPO", "TIPO_FECHAMENTO", "CODIGO", "EMPRESA", "TIPO_CONTRATO", "DESCRICAO", "DATA_INICIO", "DATA_FIM", "INCLUIR_DEMITIDOS", "ASSINATURA_ESPELHO", "DT_SAIU_ARTE", "DT_ENVIADO_IFPONTO_SURICATO", "CODIGO_INTEGRA_ARTE") AS 
  SELECT TIPO, TIPO_FECHAMENTO, CODIGO, EMPRESA, TIPO_CONTRATO, DESCRICAO, DATA_INICIO, DATA_FIM, INCLUIR_DEMITIDOS, ASSINATURA_ESPELHO, DT_SAIU_ARTE, DT_ENVIADO_IFPONTO_SURICATO, CODIGO_INTEGRA_ARTE
  FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO
WHERE DT_ENVIADO_IFPONTO_SURICATO IS NULL