
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_PRG_GERA_SIT_PONTO_ESPELHO" ("SITUACAO_FUNCIONAL", "COD_SIT_FUNCIONAL", "DATA_INIC_SITUACAO", "CONTROLE_FOLHA", "SIT_FUNC_IFPONTO", "DATA_RESCISAO", "ERRO_IFPONTO_OCORREN_ESPELHO", "PREVISTO_F", "PREVISTO_N", "H_NORMAIS", "H_NORMAIS_F", "H_NORMAIS_N", "H_EXCEDIDAS", "EXTRA_DIA_INFO_SEM_MENSAL_F", "H_DIFERENCIADAS", "DESCONTO_DIA_INFO_SEM_MENSAL_F", "PREV_TRAT", "DESC_ABONADO", "HORAS_ABONAD", "HORAS_ABONADA_F", "HORAS_MARCACOES_F", "COMPENSAD", "FALTA_COMPENSAR_", "JUSTIF_GERA_HORAS_NORMAIS", "CODIGO_REG_OCORRENCIA", "O_QUE_FAZER", "COD_VINCULO", "VINCULO", "COD_RG_TRAB", "RG_TRAB", "COD_RG_PREV", "RG_PREV", "COD_TIPO_TRAB", "TIPO_TRAB", "FOLHA_ESPECIAL", "REGISTRO_PONTO", "TIPO_REFERENCIA", "TEM_SIT_PONTO", "TEM_PREVISTO", "TEM_PREVISTO_TRATADO", "TEM_H_NORMAIS", "TEM_DESCONTO_ABONADO", "TEM_HORAS_ABONADA", "TEM_DESCONTO", "TEM_H_EXTRA", "TEM_H_EXTRA_FERIADO", "TEM_H_NOTURNA", "TEM_COMPENSADO", "TEM_FALTA_COMPENSAR", "TEM_ATRASO", "TEM_SAIDA_ANTECIPADA", "TEM_H_EXTRA_NOTURNA", "TEM_H_INTRA_JORNADA", "TEM_DESCONTO_AUX", "TEM_INTERJORNADA", "TEM_BH_CREDITO", "TEM_BH_DEBITO", "TEM_DESCONTO_TOLERADO", "TEM_INTERVALO_A_MENOR", "TEM_ENTRADA_ANTECIPADA", "TEM_MULTA_INTERJORNADA", "TEM_EXTRA_DIA_INFO_SEM_MENSAL", "TEM_DESC_DIA_INFO_SEM_MENSAL", "EMPRESA", "TIPO_CONTRATO", "MATRICULA", "CODIGO", "DATA", "SITUACAO", "SITUACAO_TRATADA", "TIPO_FOLGA", "ENTRADA", "MARCACAO_E1", "ACEITO", "SIT_PONTO", "DESCONTO_ABONADO", "HORAS_ABONADA", "HORAS_MARCACOES", "DESCONTO", "H_EXTRA", "H_EXTRA_FERIADO", "H_NOTURNA", "COMPENSADO", "FALTA_COMPENSAR", "ATRASO", "SAIDA_ANTECIPADA", "H_EXTRA_NOTURNA", "H_INTRA_JORNADA", "DESCONTO_AUX", "INTERJORNADA", "BH_CREDITO", "BH_DEBITO", "DESCONTO_TOLERADO", "INTERVALO_A_MENOR", "ENTRADA_ANTECIPADA", "MULTA_INTERJORNADA", "EXTRA_DIA_INFO_SEM_MENSAL", "DESCONTO_DIA_INFO_SEM_MENSAL", "DTCADASTRO", "COD_PESSOA", "COD_JUSTIFICATIVA_PONTO", "COD_PONTO_FECHAMENTO", "COD_BANCO_HORAS", "COD_CARGO", "COD_UNIDADE", "COD_HORARIO", "COD_ESCALA_PADRAO", "CAMPO_LIVRE", "MARCACAO1", "MARCACAO2", "MARCACAO3", "MARCACAO4", "MARCACAO5", "MARCACAO6", "MARCACAO7", "MARCACAO8", "MARCACAO9", "MARCACAO10", "MARCACAO11", "MARCACAO12", "MARCACAO_E2", "MARCACAO_E3", "MARCACAO_E4", "MARCACAO_E5", "MARCACAO_E6", "MARCACAO_E7", "MARCACAO_E8", "MARCACAO_E9", "MARCACAO_E10", "MARCACAO_E11", "MARCACAO_E12", "MARCACAO1_ALTERADA", "MARCACAO2_ALTERADA", "MARCACAO3_ALTERADA", "MARCACAO4_ALTERADA", "MARCACAO5_ALTERADA", "MARCACAO6_ALTERADA", "MARCACAO7_ALTERADA", "MARCACAO8_ALTERADA", "MARCACAO9_ALTERADA", "MARCACAO10_ALTERADA", "MARCACAO11_ALTERADA", "MARCACAO12_ALTERADA", "OBS_MARCACAO_ALTERADA", "BANCO_HORAS", "TIPO_BANCO_HORAS", "OBS", "BIT_DIVERGENCIA", "COD_COMPENSACAO", "MULTIPLICADOR_BANCO_HORAS", "NA009", "DTJUSTIFICATIVA", "LOGIN_JUSTIFICATIVA", "DTAVALIADOR", "LOGIN_AVALIADOR", "DTALTERACAO", "LOGIN_ALTERACAO", "FOTO", "SOBREAVISO_DOBRA", "COD_JUSTIFICATIVA_BANCO_HORAS", "DESCRICAO_BANCO_HORAS", "COMPROVANTE_JUSTIFICATIVA", "RELATORIO_RH_VALIDADO", "TOTAIS", "AGRUPADOR") AS 
  (
  
SELECT 
X5.SITUACAO_FUNCIONAL, X5.COD_SIT_FUNCIONAL, X5.DATA_INIC_SITUACAO, X5.CONTROLE_FOLHA, X5.SIT_FUNC_IFPONTO, --NOVO EM 9/12/21
X5.DATA_RESCISAO,
X5.ERRO_IFPONTO_OCORREN_ESPELHO,
X5.PREVISTO_F,
X5.PREVISTO_N,
X5.H_NORMAIS, 
X5.H_NORMAIS_F,
X5.H_NORMAIS_N,
X5.H_EXCEDIDAS,  X5.EXTRA_DIA_INFO_SEM_MENSAL_F,  X5.H_DIFERENCIADAS,  X5.DESCONTO_DIA_INFO_SEM_MENSAL_F,  X5.PREV_TRAT,  X5.DESC_ABONADO,  X5.HORAS_ABONAD,  X5.HORAS_ABONADA_F,  X5.HORAS_MARCACOES_F,  X5.COMPENSAD,  X5.FALTA_COMPENSAR_,  X5.JUSTIF_GERA_HORAS_NORMAIS,  X5.CODIGO_REG_OCORRENCIA,  X5.O_QUE_FAZER,  X5.COD_VINCULO,  X5.VINCULO,  X5.COD_RG_TRAB,  X5.RG_TRAB,  X5.COD_RG_PREV,  X5.RG_PREV,  X5.COD_TIPO_TRAB,  X5.TIPO_TRAB,  X5.FOLHA_ESPECIAL,  X5.REGISTRO_PONTO,  X5.TIPO_REFERENCIA,  X5.TEM_SIT_PONTO,  X5.TEM_PREVISTO,  X5.TEM_PREVISTO_TRATADO,  X5.TEM_H_NORMAIS,  X5.TEM_DESCONTO_ABONADO,  X5.TEM_HORAS_ABONADA,  X5.TEM_DESCONTO,  X5.TEM_H_EXTRA,  X5.TEM_H_EXTRA_FERIADO,  X5.TEM_H_NOTURNA,  X5.TEM_COMPENSADO,  X5.TEM_FALTA_COMPENSAR,  X5.TEM_ATRASO,  X5.TEM_SAIDA_ANTECIPADA,  X5.TEM_H_EXTRA_NOTURNA,  X5.TEM_H_INTRA_JORNADA,  X5.TEM_DESCONTO_AUX,  X5.TEM_INTERJORNADA,  X5.TEM_BH_CREDITO,  X5.TEM_BH_DEBITO,  X5.TEM_DESCONTO_TOLERADO,  X5.TEM_INTERVALO_A_MENOR,  X5.TEM_ENTRADA_ANTECIPADA,  X5.TEM_MULTA_INTERJORNADA,  X5.TEM_EXTRA_DIA_INFO_SEM_MENSAL,  X5.TEM_DESC_DIA_INFO_SEM_MENSAL,  X5.EMPRESA,  X5.TIPO_CONTRATO,  X5.MATRICULA,  X5.CODIGO,  X5.DATA,  X5.SITUACAO,  X5.SITUACAO_TRATADA,  X5.TIPO_FOLGA,  X5.ENTRADA,  X5.MARCACAO_E1,  X5.ACEITO,  X5.SIT_PONTO,  
X5.DESCONTO_ABONADO,  X5.HORAS_ABONADA,  X5.HORAS_MARCACOES,  X5.DESCONTO,  X5.H_EXTRA,  X5.H_EXTRA_FERIADO,  X5.H_NOTURNA,  X5.COMPENSADO,  X5.FALTA_COMPENSAR,  X5.ATRASO,  X5.SAIDA_ANTECIPADA,  X5.H_EXTRA_NOTURNA,  X5.H_INTRA_JORNADA,  X5.DESCONTO_AUX,  X5.INTERJORNADA,  X5.BH_CREDITO,  X5.BH_DEBITO,  X5.DESCONTO_TOLERADO,  X5.INTERVALO_A_MENOR,  X5.ENTRADA_ANTECIPADA,  X5.MULTA_INTERJORNADA,  X5.EXTRA_DIA_INFO_SEM_MENSAL,  X5.DESCONTO_DIA_INFO_SEM_MENSAL,  X5.DTCADASTRO,  X5.COD_PESSOA,  X5.COD_JUSTIFICATIVA_PONTO,  X5.COD_PONTO_FECHAMENTO,  X5.COD_BANCO_HORAS,  X5.COD_CARGO,  X5.COD_UNIDADE,  X5.COD_HORARIO,  X5.COD_ESCALA_PADRAO,  X5.CAMPO_LIVRE,  X5.MARCACAO1,  X5.MARCACAO2,  X5.MARCACAO3,  X5.MARCACAO4,  X5.MARCACAO5,  X5.MARCACAO6,  X5.MARCACAO7,  X5.MARCACAO8,  X5.MARCACAO9,  X5.MARCACAO10,  X5.MARCACAO11,  X5.MARCACAO12,  X5.MARCACAO_E2,  X5.MARCACAO_E3,  X5.MARCACAO_E4,  X5.MARCACAO_E5,  X5.MARCACAO_E6,  X5.MARCACAO_E7,  X5.MARCACAO_E8,  X5.MARCACAO_E9,  X5.MARCACAO_E10,  X5.MARCACAO_E11,  X5.MARCACAO_E12,  X5.MARCACAO1_ALTERADA,  X5.MARCACAO2_ALTERADA,  X5.MARCACAO3_ALTERADA,  X5.MARCACAO4_ALTERADA,  X5.MARCACAO5_ALTERADA,  X5.MARCACAO6_ALTERADA,  X5.MARCACAO7_ALTERADA,  X5.MARCACAO8_ALTERADA,  X5.MARCACAO9_ALTERADA,  X5.MARCACAO10_ALTERADA,  X5.MARCACAO11_ALTERADA,  X5.MARCACAO12_ALTERADA,  X5.OBS_MARCACAO_ALTERADA,  X5.BANCO_HORAS,  X5.TIPO_BANCO_HORAS,  X5.OBS,  X5.BIT_DIVERGENCIA,  X5.COD_COMPENSACAO,  X5.MULTIPLICADOR_BANCO_HORAS,  X5.NA009,  X5.DTJUSTIFICATIVA,  X5.LOGIN_JUSTIFICATIVA,  X5.DTAVALIADOR,  X5.LOGIN_AVALIADOR,  X5.DTALTERACAO,  X5.LOGIN_ALTERACAO,  X5.FOTO,  X5.SOBREAVISO_DOBRA,  X5.COD_JUSTIFICATIVA_BANCO_HORAS,  X5.DESCRICAO_BANCO_HORAS,  X5.COMPROVANTE_JUSTIFICATIVA,  X5.RELATORIO_RH_VALIDADO,  X5.TOTAIS
,X5.AGRUPADOR
FROM(
SELECT 
X4.SITUACAO_FUNCIONAL,  X4.COD_SIT_FUNCIONAL, X4.DATA_INIC_SITUACAO, X4.CONTROLE_FOLHA,  X4.SIT_FUNC_IFPONTO, --NOVO EM 9/12/21
X4.DATA_RESCISAO,
X4.PREVISTO_F AS PREVISTO_N, 
X4.H_NORMAIS_F AS H_NORMAIS_N,
CASE WHEN X4.CODIGO_REG_OCORRENCIA IS NOT NULL AND X4.SITUACAO IN ('TRABALHANDO','FOLGA') AND X4.COD_JUSTIFICATIVA_PONTO IS NULL THEN 'SIM' ELSE 'NAO' 
END ERRO_IFPONTO_OCORREN_ESPELHO,
X4.H_NORMAIS H_NORMAL, 
X4.H_NORMAIS_F,
X4.PREVISTO PREVISTO_F,
X4.EXTRA_DIA_INFO_SEM_MENSAL H_EXCEDIDAS, 
X4.EXTRA_DIA_INFO_SEM_MENSAL EXTRA_DIA_INFO_SEM_MENSAL_F,
X4.DESCONTO_DIA_INFO_SEM_MENSAL H_DIFERENCIADAS, 
X4.DESCONTO_DIA_INFO_SEM_MENSAL DESCONTO_DIA_INFO_SEM_MENSAL_F,
X4.PREVISTO_TRATADO PREV_TRAT, 
X4.DESCONTO_ABONADO DESC_ABONADO, 
X4.HORAS_ABONADA HORAS_ABONAD,
X4.HORAS_ABONADA_F,
X4.HORAS_MARCACOES HORAS_MARCACOES_F,
X4.COMPENSADO COMPENSAD, 
X4.FALTA_COMPENSAR FALTA_COMPENSAR_, 
X4.JUSTIF_GERA_HORAS_NORMAIS,  X4.CODIGO_REG_OCORRENCIA,  X4.O_QUE_FAZER,  X4.COD_VINCULO,  X4.VINCULO,  X4.COD_RG_TRAB,  X4.RG_TRAB,  X4.COD_RG_PREV,  X4.RG_PREV,  X4.COD_TIPO_TRAB,  X4.TIPO_TRAB,  X4.FOLHA_ESPECIAL,  X4.REGISTRO_PONTO,  X4.TIPO_REFERENCIA,  X4.TEM_SIT_PONTO,  X4.TEM_PREVISTO,  X4.TEM_PREVISTO_TRATADO,  X4.TEM_H_NORMAIS,  X4.TEM_DESCONTO_ABONADO,  X4.TEM_HORAS_ABONADA,  X4.TEM_DESCONTO,  X4.TEM_H_EXTRA,  X4.TEM_H_EXTRA_FERIADO,  X4.TEM_H_NOTURNA,  X4.TEM_COMPENSADO,  X4.TEM_FALTA_COMPENSAR,  X4.TEM_ATRASO,  X4.TEM_SAIDA_ANTECIPADA,  X4.TEM_H_EXTRA_NOTURNA,  X4.TEM_H_INTRA_JORNADA,  X4.TEM_DESCONTO_AUX,  X4.TEM_INTERJORNADA,  X4.TEM_BH_CREDITO,  X4.TEM_BH_DEBITO,  X4.TEM_DESCONTO_TOLERADO,  X4.TEM_INTERVALO_A_MENOR,  X4.TEM_ENTRADA_ANTECIPADA,  X4.TEM_MULTA_INTERJORNADA,  X4.TEM_EXTRA_DIA_INFO_SEM_MENSAL,  X4.TEM_DESC_DIA_INFO_SEM_MENSAL,  
X4.EMPRESA,  X4.TIPO_CONTRATO,  X4.MATRICULA,  X4.CODIGO,  X4.DATA,  X4.SITUACAO,  X4.SITUACAO_TRATADA,  X4.TIPO_FOLGA,  X4.ENTRADA,  X4.MARCACAO_E1,  X4.ACEITO,  X4.SIT_PONTO,  X4.PREVISTO,  X4.PREVISTO_TRATADO,  X4.H_NORMAIS,  X4.DESCONTO_ABONADO,  X4.HORAS_ABONADA,  X4.HORAS_MARCACOES,  X4.DESCONTO,  X4.H_EXTRA,  X4.H_EXTRA_FERIADO,  X4.H_NOTURNA,  X4.COMPENSADO,  X4.FALTA_COMPENSAR,  X4.ATRASO,  X4.SAIDA_ANTECIPADA,  X4.H_EXTRA_NOTURNA,  X4.H_INTRA_JORNADA,  X4.DESCONTO_AUX,  X4.INTERJORNADA,  X4.BH_CREDITO,  X4.BH_DEBITO,  X4.DESCONTO_TOLERADO,  X4.INTERVALO_A_MENOR,  X4.ENTRADA_ANTECIPADA,  X4.MULTA_INTERJORNADA,  X4.EXTRA_DIA_INFO_SEM_MENSAL,  X4.DESCONTO_DIA_INFO_SEM_MENSAL,  X4.DTCADASTRO,  X4.COD_PESSOA,  X4.COD_JUSTIFICATIVA_PONTO,  X4.COD_PONTO_FECHAMENTO,  X4.COD_BANCO_HORAS,  X4.COD_CARGO,  X4.COD_UNIDADE,  X4.COD_HORARIO,  X4.COD_ESCALA_PADRAO,  X4.CAMPO_LIVRE,  X4.MARCACAO1,  X4.MARCACAO2,  X4.MARCACAO3,  X4.MARCACAO4,  X4.MARCACAO5,  X4.MARCACAO6,  X4.MARCACAO7,  X4.MARCACAO8,  X4.MARCACAO9,  X4.MARCACAO10,  X4.MARCACAO11,  X4.MARCACAO12,  X4.MARCACAO_E2,  X4.MARCACAO_E3,  X4.MARCACAO_E4,  X4.MARCACAO_E5,  X4.MARCACAO_E6,  X4.MARCACAO_E7,  X4.MARCACAO_E8,  X4.MARCACAO_E9,  X4.MARCACAO_E10,  X4.MARCACAO_E11,  X4.MARCACAO_E12,  X4.MARCACAO1_ALTERADA,  X4.MARCACAO2_ALTERADA,  X4.MARCACAO3_ALTERADA,  X4.MARCACAO4_ALTERADA,  X4.MARCACAO5_ALTERADA,  X4.MARCACAO6_ALTERADA,  X4.MARCACAO7_ALTERADA,  X4.MARCACAO8_ALTERADA,  X4.MARCACAO9_ALTERADA,  X4.MARCACAO10_ALTERADA,  X4.MARCACAO11_ALTERADA,  X4.MARCACAO12_ALTERADA,  X4.OBS_MARCACAO_ALTERADA,  X4.BANCO_HORAS,  X4.TIPO_BANCO_HORAS,  X4.OBS,  X4.BIT_DIVERGENCIA,  X4.COD_COMPENSACAO,  X4.MULTIPLICADOR_BANCO_HORAS,  X4.NA009,  X4.DTJUSTIFICATIVA,  X4.LOGIN_JUSTIFICATIVA,  X4.DTAVALIADOR,  X4.LOGIN_AVALIADOR,  X4.DTALTERACAO,  X4.LOGIN_ALTERACAO,  X4.FOTO,  X4.SOBREAVISO_DOBRA,  X4.COD_JUSTIFICATIVA_BANCO_HORAS,  X4.DESCRICAO_BANCO_HORAS,  X4.COMPROVANTE_JUSTIFICATIVA,  X4.RELATORIO_RH_VALIDADO,  X4.TOTAIS
,X4.AGRUPADOR
FROM(
SELECT 
C.SITUACAO_FUNCIONAL,ASF.COD_SIT_FUNCIONAL, ASF.DATA_INIC_SITUACAO, SF.CONTROLE_FOLHA, POST.SIT_FUNC_IFPONTO,--NOVO EM 9/12/21
C.DATA_RESCISAO,
CASE WHEN IFP1.DADO_ORIGEM IS NOT NULL THEN 'SIM' ELSE 'NAO' END JUSTIF_GERA_HORAS_NORMAIS,
OC.CODIGO CODIGO_REG_OCORRENCIA,
--INICIO 16/7/20-------------------------------------O QUE FAZER 2
CASE
-------------------SITUACAO_TRATADA = OCORRENCIA
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'OCORRENCIA' AND X3.TIPO_FOLGA IS NULL AND X3.TEM_PREVISTO = 'SIM'  
THEN 'A.27 - Gravado como ocorrencia as permitidas e aprovadas'
--------------TIPO_FOLGA IN (FOLGA, FERIADO, PONTO FACULTATIVO)
--SEM ATIVIDADE NO DIA
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO'
THEN 'A.1-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' 
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.3-GRAVAR: 0068-FERIADO'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' 
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.2-GRAVAR: 1012-PONTO FACULTATIVO'
--SO COM JUSTIFICATIVA ABONADA
WHEN /* V.CODIGO <> '0009' AND*/                                         X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' 
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.32-DIA DESCANSO SO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' */                                            X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' 
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.33-DIA DESCANSO SO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
--SO COM JUSTIFICATIVA NAO ABONADA
WHEN /* V.CODIGO <> '0009' AND*/  X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' 
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.38-DIA DESCANSO SO COM JUSTIFICATIVA NAO ABONADA GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' 
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.39-DIA DESCANSO SO COM JUSTIFICATIVA NAO ABONADA GRAVAR: 0068-FERIADO'
WHEN /* V.CODIGO <> '0009' AND*/  X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' 
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.40-DIA DESCANSO SO COM JUSTIFICATIVA NAO ABONADA GRAVAR: 1012-PONTO FACULTATIVO'
--SO COM MARCACAO E SEM JUSTIFICATIVA
WHEN /* V.CODIGO <> '0009' AND*/   X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.34-DIA DESCANSO SO COM MARCACAO E SEM JUSTIFICATIVA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND*/    X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' 
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.35-DIA DESCANSO SO COM MARCACAO E SEM JUSTIFICATIVA GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
--COM MARCACAO E JUSTIFICATIVA ABONADA
WHEN /* V.CODIGO <> '0009' AND*/    X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.36-DIA DESCANSO COM MARCACAO E JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND*/    X3.TIPO_FOLGA IN ('FOLGA','FERIADO','PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.37-DIA DESCANSO COM MARCACAO E JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
--COM MARCACAO E JUSTIFICATIVA NAO ABONADA

--INICIO----CENARIOS NOVOS EM 3/12/20 DO A.45 a A.54 E 10/12/20 A.55 a A.58
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.45-GRAVAR: 1012-PONTO FACULTATIVO'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.46-PONTO FACULTATIVO GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.47-GRAVAR: 0068-FERIADO'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FOLGA') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.48-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FOLGA') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.49-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.50-GRAVAR: 1012-PONTO FACULTATIVO'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.51-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.52-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.53-GRAVAR: 1003-FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('TRABALHANDO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.54-GRAVAR: 1001 HORAS DIFERENCIADAS'

WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.55-PONTO FACULTATIVO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FOLGA') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.56-DIA DESCANSO COM MARCACAO E JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.57-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.57-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('PONTO_FACULTATIVO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.58-PONTO FACULTATIVO COM MARCACAO GRAVAR: 1000-HORAS NORMAIS'

WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('TRABALHANDO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.59-GRAVAR: 0020-FALTA'
--FIM----CENARIOS NOVOS EM 3/12/20 DO A.45 a A.54 E 10/12/20 A.55 a A.58

--INICIO----CENARIOS NOVOS EM 30/12/20 DO A.60 a A.66
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('TRABALHANDO') AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.60-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('TRABALHANDO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.61-GRAVAR: 0020-FALTA ULTIMO DIA PERIODO'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.62-GRAVAR FALTA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.63-GRAVA FALTA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.64-GRAVA FERIADO'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FOLGA') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.65-GRAVA FOLGA'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA IN ('FERIADO') AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO'
AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.66-HORAS NORMAIS E HORAS EXCEDIDAS'
--FIM----CENARIOS NOVOS EM 30/12/20 DO A.60 a A.66

-------------------------O QUE SOBROU DE SITUACAO_TRATADA = TRABALHANDO
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.6.1-GRAVAR: 1000-HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.7.1-GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.8.1-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.9.1-GRAVAR: 0020-FALTA PODE VIRAR FALTA COMPENSADA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.9.2-GRAVAR: 0020-FALTA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.10.1-POSSIVEL FALTA VIRAR FALTA COMPENSADA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.10.2-POSSIVEL FALTA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM'
THEN 'A.12-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.13-GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO'
THEN 'A.14-?Gravar no dia a Situação de Ponto da Justificativa?'
--WHEN  /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO'
--THEN  '17-1.2-Avaliar trabalhou tem marcação mas total impar e dá alerta no espelho e possui uma JUSTIFICATIVA ABONADA apenas com HORAS NORMAIS'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.15-?Gravar no dia a Situação de Ponto da Justificativa + horas excedidas?'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.16-?Gravar no dia a Situação de Ponto da Justificativa + horas diferenciadas?'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'NAO LOCALIZADO SIT PONTO 13-GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'NAO LOCALIZADO SIT PONTO 14-?Gravar no dia a Situação de Ponto da Justificativa?'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.17-GRAVAR: 0020 FALTA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.18-GRAVAR: 0020 FALTA PODE VIRAR FALTA COMPENSADA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.19.1-GRAVAR: 1001 HORAS DIFERENCIADAS e 1000 HORAS NORMAIS'
--inicio --NOVO EM 6/11/20
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.19.2-GRAVAR: 1001 HORAS DIFERENCIADAS E 1000-HORAS NORMAIS ULTIMO DIA PERIODO'
--fim--NOVO EM 6/11/20
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.20-GRAVAR: 0020 FALTA'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.21-GRAVAR: 1002 HORAS EXCEDIDAS'
WHEN /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.22-GRAVAR: 1001 HORAS DIFERENCIADAS'
--WHEN  /* V.CODIGO <> '0009' AND*/  X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
--THEN  'A.23-FOLGA GRAVAR: 1000-HORAS NORMAIS'


--INICIO----------------------------------------------------NOVO EM 6/7/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.54.2-GRAVAR: 1001 HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.60.2-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.87-GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.70-FOLGA GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.71-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.72-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.73-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.74-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.75-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.76-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.77-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.78-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.79-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.80-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.81-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.82-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.83-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.84-GRAVAR: 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.85-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.86-FERIADO GRAVAR: JUSTIFICATIVA E 1001- HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.113-GRAVAR: 1000-HORAS NORMAIS'-- '********A.88- ERRO IFRACTAL AVISAR ASTIN E FAZER AJUSTE MANUAL'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.89-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.90-GRAVAR: 0020 FALTA'  
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.91-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'  
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.92-GRAVAR: JUSTIFICATIVA' 
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.93-GRAVAR: 0020 FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.94-GRAVAR: 0020 FALTA' 
--FIM----------------------------------------------------NOVO EM 6/7/21

--INICIO----------------------------------------------------NOVO EM 11/8/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.95-GRAVAR: 1003-FOLGA' 
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.96-GRAVAR: 1003-FOLGA' 
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'NAO' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.97-GRAVAR: 1002-HORAS EXCEDENTES' 
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.98-GRAVAR: 1002-HORAS EXCEDENTES' 
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.99-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.100-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.101-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.102-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS e 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.103-FERIADO GRAVAR: JUSTIFICATIVA E 1002- HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.109-GRAVAR: 0020 FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.104-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS e 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.105-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.106-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.107-FERIADO COM JUSTIFICATIVA ABONADA GRAVAR: 1000-HORAS NORMAIS+1002-EXEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.108-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.110- GRAVAR: 1000-HORAS NORMAIS + 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.111-GRAVAR: 0020 FALTA'
--FIM----------------------------------------------------NOVO EM 11/8/21

--INICIO----------------------------------------------------NOVO EM 28/9/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.112-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.115-GRAVAR: 1001-HORAS DIFERENCIADAS'

WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.15-?Gravar no dia a Situacao de Ponto da Justificativa + horas excedidas?'

WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.114-GRAVAR: 1001-HORAS DIFERENCIADAS'
WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.116-GRAVAR: 1000-HORAS NORMAIS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.117-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.118-DIA DESCANSO COM MARCACAO E JUSTIFICATIVA ABONADA GRAVAR: 1002-HORAS EXCEDIDAS'
--FIM----------------------------------------------------NOVO EM 28/9/21

--INICIO----------------------------------------------------NOVO EM 29/10/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.119-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.120-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.121-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.122-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.123-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.124-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.125-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.126-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.127-GRAVAR: 1000-HORAS NORMAIS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.128-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.129-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.130-GRAVAR: 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.131-GRAVAR: 1001-HORAS DIFERENCIADAS'

WHEN /* V.CODIGO <> '0009' AND */X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.15-?Gravar no dia a Situacao de Ponto da Justificativa + horas excedidas?'
--FIM----------------------------------------------------NOVO EM 29/10/21

--INICIO----------------------------------------------------NOVO EM 11/11/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.132-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.133-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.134-PONTO_FACULTATIVO GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.135-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.136-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.137-PONTO_FACULTATIVO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'--ESTRANHO O VALOR ESTA COMO DESCONTO MAS NO ESPELHO SER EXECEDIDAS
--FIM----------------------------------------------------NOVO EM 11/11/21

--INICIO----------------------------------------------------NOVO EM 10/12/21
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.138-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.139-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.140-GRAVA FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.141-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'FOLGA' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.142-GRAVA FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.143-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.144-GRAVAR: 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'FOLGA' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.145-GRAVAR: 1003-FOLGA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--'A.146-FERIADO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'FERIADO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.147-GRAVAR: 1000-HORAS NORMAIS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.148-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.149-PONTO_FACULTATIVO GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDIDAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'SIM' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.11-GRAVAR: Situação de Ponto da Justificativa'--A.150-GRAVAR: JUSTIFICATIVA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.151-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'PONTO_FACULTATIVO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'NAO AVALIADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.152-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'NAO' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.153-GRAVAR: 0020-FALTA'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.154-GRAVAR: 1000-HORAS NORMAIS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.155-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 0 AND X3.MARCACAO_E1 = 0 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'SIM' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'NAO' 
THEN 'A.156-GRAVAR: 1000-HORAS NORMAIS E 1002-HORAS EXCEDENTES'
WHEN /*V.CODIGO <> '0009' AND*/ X3.SITUACAO_TRATADA = 'TRABALHANDO' AND X3.TIPO_FOLGA = 'TRABALHANDO' AND X3.ENTRADA = 1 AND X3.MARCACAO_E1 = 1 AND X3.ACEITO = 'ABONADO' AND X3.TEM_SIT_PONTO = 'NAO' AND X3.TEM_PREVISTO = 'SIM' AND X3.TEM_H_NORMAIS = 'SIM' AND X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL = 'NAO' AND X3.TEM_DESC_DIA_INFO_SEM_MENSAL = 'SIM' 
THEN 'A.157-GRAVAR: 1000-HORAS NORMAIS E 1001-HORAS DIFERENCIADAS'
--FIM----------------------------------------------------NOVO EM 10/12/21

ELSE '**********************NÃO MAPEADO AINDA'
END O_QUE_FAZER,

V.CODIGO COD_VINCULO, V.DESCRICAO VINCULO,
RG_TRAB.CONTEUDO_INICIAL COD_RG_TRAB, RG_TRAB.DESCR_IT_DOMINIO RG_TRAB,
RG_PREV.CONTEUDO_INICIAL COD_RG_PREV, RG_PREV.DESCR_IT_DOMINIO RG_PREV,
COD_CATEG.CONTEUDO_INICIAL COD_TIPO_TRAB, COD_CATEG.DESCR_IT_DOMINIO TIPO_TRAB,
c.cod_cargo_efetivo,
CASE WHEN CC.c_livre_selec01 = 0 THEN 'NAO' ELSE 'SIM' END FOLHA_ESPECIAL, C.registro_ponto, SP.tipo_referencia,
X3.PREVISTO_F,
CASE WHEN X3.H_NORMAIS_F IS NOT NULL AND X3.H_NORMAIS_F <> 0 AND X3.H_NORMAIS_F > 24 AND X3.PREVISTO_F IS NOT NULL THEN X3.PREVISTO_F
WHEN X3.H_NORMAIS_F IS NULL THEN 0
ELSE X3.H_NORMAIS_F END H_NORMAIS_F, --NOVO 17/7/20 CORRIGI EXCESSOS NO ULTIMO DIA
CASE WHEN X3.HORAS_ABONADA_F IS NOT NULL AND X3.HORAS_ABONADA_F <> 0 AND X3.HORAS_ABONADA_F > 24 AND X3.PREVISTO_F IS NOT NULL THEN X3.PREVISTO_F 
WHEN X3.HORAS_ABONADA_F IS NULL THEN 0 
ELSE X3.HORAS_ABONADA_F END HORAS_ABONADA_F, --NOVO 17/7/20 CORRIGI EXCESSOS NO ULTIMO DIA
X3.TEM_SIT_PONTO,  X3.TEM_PREVISTO,  X3.TEM_PREVISTO_TRATADO,  X3.TEM_H_NORMAIS,  X3.TEM_DESCONTO_ABONADO,  X3.TEM_HORAS_ABONADA,  X3.TEM_DESCONTO,  X3.TEM_H_EXTRA,  X3.TEM_H_EXTRA_FERIADO,  X3.TEM_H_NOTURNA,  X3.TEM_COMPENSADO,  X3.TEM_FALTA_COMPENSAR,  X3.TEM_ATRASO,  X3.TEM_SAIDA_ANTECIPADA,  X3.TEM_H_EXTRA_NOTURNA,  X3.TEM_H_INTRA_JORNADA,  X3.TEM_DESCONTO_AUX,  X3.TEM_INTERJORNADA,  X3.TEM_BH_CREDITO,  X3.TEM_BH_DEBITO,  X3.TEM_DESCONTO_TOLERADO,  X3.TEM_INTERVALO_A_MENOR,  X3.TEM_ENTRADA_ANTECIPADA,  X3.TEM_MULTA_INTERJORNADA,  X3.TEM_EXTRA_DIA_INFO_SEM_MENSAL,  X3.TEM_DESC_DIA_INFO_SEM_MENSAL,  
X3.EMPRESA,  X3.TIPO_CONTRATO,  X3.MATRICULA,  X3.CODIGO,  X3.DATA,  X3.SITUACAO,  X3.SITUACAO_TRATADA,  X3.TIPO_FOLGA,  X3.ENTRADA,  X3.MARCACAO_E1,  X3.ACEITO,  X3.SIT_PONTO,  X3.PREVISTO,  X3.PREVISTO_TRATADO,  X3.H_NORMAIS,  X3.DESCONTO_ABONADO,  X3.HORAS_ABONADA,  X3.HORAS_MARCACOES,  X3.DESCONTO,  X3.H_EXTRA,  X3.H_EXTRA_FERIADO,  X3.H_NOTURNA,  X3.COMPENSADO,  X3.FALTA_COMPENSAR,  X3.ATRASO,  X3.SAIDA_ANTECIPADA,  X3.H_EXTRA_NOTURNA,  X3.H_INTRA_JORNADA,  X3.DESCONTO_AUX,  X3.INTERJORNADA,  X3.BH_CREDITO,  X3.BH_DEBITO,  X3.DESCONTO_TOLERADO,  X3.INTERVALO_A_MENOR,  X3.ENTRADA_ANTECIPADA,  X3.MULTA_INTERJORNADA,  X3.EXTRA_DIA_INFO_SEM_MENSAL,  X3.DESCONTO_DIA_INFO_SEM_MENSAL,  X3.DTCADASTRO,  X3.COD_PESSOA,  X3.COD_JUSTIFICATIVA_PONTO,  X3.COD_PONTO_FECHAMENTO,  X3.COD_BANCO_HORAS,  X3.COD_CARGO,  X3.COD_UNIDADE,  X3.COD_HORARIO,  X3.COD_ESCALA_PADRAO,  X3.CAMPO_LIVRE,  X3.MARCACAO1,  X3.MARCACAO2,  X3.MARCACAO3,  X3.MARCACAO4,  X3.MARCACAO5,  X3.MARCACAO6,  X3.MARCACAO7,  X3.MARCACAO8,  X3.MARCACAO9,  X3.MARCACAO10,  X3.MARCACAO11,  X3.MARCACAO12,  X3.MARCACAO_E2,  X3.MARCACAO_E3,  X3.MARCACAO_E4,  X3.MARCACAO_E5,  X3.MARCACAO_E6,  X3.MARCACAO_E7,  X3.MARCACAO_E8,  X3.MARCACAO_E9,  X3.MARCACAO_E10,  X3.MARCACAO_E11,  X3.MARCACAO_E12,  X3.MARCACAO1_ALTERADA,  X3.MARCACAO2_ALTERADA,  X3.MARCACAO3_ALTERADA,  X3.MARCACAO4_ALTERADA,  X3.MARCACAO5_ALTERADA,  X3.MARCACAO6_ALTERADA,  X3.MARCACAO7_ALTERADA,  X3.MARCACAO8_ALTERADA,  X3.MARCACAO9_ALTERADA,  X3.MARCACAO10_ALTERADA,  X3.MARCACAO11_ALTERADA,  X3.MARCACAO12_ALTERADA,  X3.OBS_MARCACAO_ALTERADA,  X3.BANCO_HORAS,  X3.TIPO_BANCO_HORAS,  X3.OBS,  X3.BIT_DIVERGENCIA,  X3.COD_COMPENSACAO,  X3.MULTIPLICADOR_BANCO_HORAS,  X3.NA009,  X3.DTJUSTIFICATIVA,  X3.LOGIN_JUSTIFICATIVA,  X3.DTAVALIADOR,  X3.LOGIN_AVALIADOR,  X3.DTALTERACAO,  X3.LOGIN_ALTERACAO,  X3.FOTO,  X3.SOBREAVISO_DOBRA,  X3.COD_JUSTIFICATIVA_BANCO_HORAS,  X3.DESCRICAO_BANCO_HORAS,  X3.COMPROVANTE_JUSTIFICATIVA,  X3.RELATORIO_RH_VALIDADO,  X3.TOTAIS
,X3.AGRUPADOR
FROM(
SELECT 
CASE WHEN X2.SIT_PONTO IS NULL OR X2.SIT_PONTO = 0 THEN 'NAO' ELSE 'SIM' END TEM_SIT_PONTO
,CASE WHEN X2.PREVISTO IS NULL OR X2.PREVISTO  = 0 THEN 'NAO' ELSE 'SIM' END TEM_PREVISTO
,CASE WHEN X2.PREVISTO_TRATADO IS NULL OR X2.PREVISTO_TRATADO = 0 THEN 'NAO' ELSE 'SIM' END TEM_PREVISTO_TRATADO
,CASE WHEN X2.H_NORMAIS IS NULL OR X2.H_NORMAIS  = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_NORMAIS
,CASE WHEN X2.DESCONTO_ABONADO IS NULL OR X2.DESCONTO_ABONADO = 0 THEN 'NAO' ELSE 'SIM' END TEM_DESCONTO_ABONADO
,CASE WHEN X2.HORAS_ABONADA IS NULL OR X2.HORAS_ABONADA = 0 THEN 'NAO' ELSE 'SIM' END TEM_HORAS_ABONADA
,CASE WHEN X2.DESCONTO IS NULL OR X2.DESCONTO = 0 THEN 'NAO' ELSE 'SIM' END TEM_DESCONTO
,CASE WHEN X2.H_EXTRA IS NULL OR X2.H_EXTRA = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_EXTRA
,CASE WHEN X2.H_EXTRA_FERIADO IS NULL OR X2.H_EXTRA_FERIADO = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_EXTRA_FERIADO
,CASE WHEN X2.H_NOTURNA IS NULL OR X2.H_NOTURNA = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_NOTURNA
,CASE WHEN X2.COMPENSADO IS NULL OR X2.COMPENSADO = 0 THEN 'NAO' ELSE 'SIM' END TEM_COMPENSADO
,CASE WHEN X2.FALTA_COMPENSAR IS NULL OR X2.FALTA_COMPENSAR = 0 THEN 'NAO' ELSE 'SIM' END TEM_FALTA_COMPENSAR
,CASE WHEN X2.ATRASO IS NULL OR X2.ATRASO = 0 THEN 'NAO' ELSE 'SIM' END TEM_ATRASO
,CASE WHEN X2.SAIDA_ANTECIPADA IS NULL OR X2.SAIDA_ANTECIPADA = 0 THEN 'NAO' ELSE 'SIM' END TEM_SAIDA_ANTECIPADA
,CASE WHEN X2.H_EXTRA_NOTURNA IS NULL OR X2.H_EXTRA_NOTURNA = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_EXTRA_NOTURNA
,CASE WHEN X2.H_INTRA_JORNADA IS NULL OR X2.H_INTRA_JORNADA = 0 THEN 'NAO' ELSE 'SIM' END TEM_H_INTRA_JORNADA
,CASE WHEN X2.DESCONTO_AUX IS NULL OR X2.DESCONTO_AUX = 0 THEN 'NAO' ELSE 'SIM' END TEM_DESCONTO_AUX
,CASE WHEN X2.INTERJORNADA IS NULL OR X2.INTERJORNADA = 0 THEN 'NAO' ELSE 'SIM' END TEM_INTERJORNADA
,CASE WHEN X2.BH_CREDITO IS NULL OR X2.BH_CREDITO = 0 THEN 'NAO' ELSE 'SIM' END TEM_BH_CREDITO
,CASE WHEN X2.BH_DEBITO IS NULL OR X2.BH_DEBITO = 0 THEN 'NAO' ELSE 'SIM' END TEM_BH_DEBITO
,CASE WHEN X2.DESCONTO_TOLERADO IS NULL OR X2.DESCONTO_TOLERADO = 0 THEN 'NAO' ELSE 'SIM' END TEM_DESCONTO_TOLERADO
,CASE WHEN X2.INTERVALO_A_MENOR IS NULL OR X2.INTERVALO_A_MENOR = 0 THEN 'NAO' ELSE 'SIM' END TEM_INTERVALO_A_MENOR
,CASE WHEN X2.ENTRADA_ANTECIPADA IS NULL OR X2.ENTRADA_ANTECIPADA  = 0 THEN 'NAO' ELSE 'SIM' END TEM_ENTRADA_ANTECIPADA
,CASE WHEN X2.MULTA_INTERJORNADA IS NULL OR X2.MULTA_INTERJORNADA = 0 THEN 'NAO' ELSE 'SIM' END TEM_MULTA_INTERJORNADA
,CASE WHEN X2.EXTRA_DIA_INFO_SEM_MENSAL IS NULL OR X2.EXTRA_DIA_INFO_SEM_MENSAL = 0 THEN 'NAO' ELSE 'SIM' END TEM_EXTRA_DIA_INFO_SEM_MENSAL
,CASE WHEN X2.DESCONTO_DIA_INFO_SEM_MENSAL IS NULL OR X2.DESCONTO_DIA_INFO_SEM_MENSAL = 0 THEN 'NAO' ELSE 'SIM' END TEM_DESC_DIA_INFO_SEM_MENSAL
,X2.H_NORMAIS_F,  X2.HORAS_ABONADA_F,  X2.PREVISTO_F,  
X2.EMPRESA,  X2.TIPO_CONTRATO,  X2.MATRICULA,  X2.CODIGO,  X2.DATA,  X2.SITUACAO,  X2.SITUACAO_TRATADA,  X2.TIPO_FOLGA,  X2.ENTRADA,  X2.MARCACAO_E1,  X2.ACEITO,  X2.SIT_PONTO,  X2.PREVISTO,  X2.PREVISTO_TRATADO,  X2.H_NORMAIS,  X2.DESCONTO_ABONADO,  X2.HORAS_ABONADA,  X2.HORAS_MARCACOES,  X2.DESCONTO,  X2.H_EXTRA,  X2.H_EXTRA_FERIADO,  X2.H_NOTURNA,  X2.COMPENSADO,  X2.FALTA_COMPENSAR,  X2.ATRASO,  X2.SAIDA_ANTECIPADA,  X2.H_EXTRA_NOTURNA,  X2.H_INTRA_JORNADA,  X2.DESCONTO_AUX,  X2.INTERJORNADA,  X2.BH_CREDITO,  X2.BH_DEBITO,  X2.DESCONTO_TOLERADO,  X2.INTERVALO_A_MENOR,  X2.ENTRADA_ANTECIPADA,  X2.MULTA_INTERJORNADA,  X2.EXTRA_DIA_INFO_SEM_MENSAL,  X2.DESCONTO_DIA_INFO_SEM_MENSAL,  X2.DTCADASTRO,  X2.COD_PESSOA,  X2.COD_JUSTIFICATIVA_PONTO,  X2.COD_PONTO_FECHAMENTO,  X2.COD_BANCO_HORAS,  X2.COD_CARGO,  X2.COD_UNIDADE,  X2.COD_HORARIO,  X2.COD_ESCALA_PADRAO,  X2.CAMPO_LIVRE,  X2.MARCACAO1,  X2.MARCACAO2,  X2.MARCACAO3,  X2.MARCACAO4,  X2.MARCACAO5,  X2.MARCACAO6,  X2.MARCACAO7,  X2.MARCACAO8,  X2.MARCACAO9,  X2.MARCACAO10,  X2.MARCACAO11,  X2.MARCACAO12,  X2.MARCACAO_E2,  X2.MARCACAO_E3,  X2.MARCACAO_E4,  X2.MARCACAO_E5,  X2.MARCACAO_E6,  X2.MARCACAO_E7,  X2.MARCACAO_E8,  X2.MARCACAO_E9,  X2.MARCACAO_E10,  X2.MARCACAO_E11,  X2.MARCACAO_E12,  X2.MARCACAO1_ALTERADA,  X2.MARCACAO2_ALTERADA,  X2.MARCACAO3_ALTERADA,  X2.MARCACAO4_ALTERADA,  X2.MARCACAO5_ALTERADA,  X2.MARCACAO6_ALTERADA,  X2.MARCACAO7_ALTERADA,  X2.MARCACAO8_ALTERADA,  X2.MARCACAO9_ALTERADA,  X2.MARCACAO10_ALTERADA,  X2.MARCACAO11_ALTERADA,  X2.MARCACAO12_ALTERADA,  X2.OBS_MARCACAO_ALTERADA,  X2.BANCO_HORAS,  X2.TIPO_BANCO_HORAS,  X2.OBS,  X2.BIT_DIVERGENCIA,  X2.COD_COMPENSACAO,  X2.MULTIPLICADOR_BANCO_HORAS,  X2.NA009,  X2.DTJUSTIFICATIVA,  X2.LOGIN_JUSTIFICATIVA,  X2.DTAVALIADOR,  X2.LOGIN_AVALIADOR,  X2.DTALTERACAO,  X2.LOGIN_ALTERACAO,  X2.FOTO,  X2.SOBREAVISO_DOBRA,  X2.COD_JUSTIFICATIVA_BANCO_HORAS,  X2.DESCRICAO_BANCO_HORAS,  X2.COMPROVANTE_JUSTIFICATIVA,  X2.RELATORIO_RH_VALIDADO,  X2.TOTAIS
,X2.AGRUPADOR
FROM(
SELECT 
X.PREVISTO
,case when x.entrada = 1 then X.PREVISTO else 0 end PREVISTO_TRATADO 
,CASE WHEN X.PREVISTO IS NULL THEN 0 ELSE X.PREVISTO 
END PREVISTO_F ,
X.H_NORMAIS, 
CASE WHEN X.H_NORMAIS IS NOT NULL AND X.H_NORMAIS <> 0 AND X.H_NORMAIS > 24 AND X.PREVISTO IS NOT NULL THEN X.PREVISTO
WHEN X.H_NORMAIS IS NULL THEN 0
ELSE X.H_NORMAIS END H_NORMAIS_F, --NOVO 17/7/20 CORRIGI EXCESSOS NO ULTIMO DIA
CASE WHEN X.HORAS_ABONADA IS NOT NULL AND X.HORAS_ABONADA <> 0 AND X.HORAS_ABONADA > 24 AND X.PREVISTO IS NOT NULL THEN X.PREVISTO 
WHEN X.HORAS_ABONADA IS NULL THEN 0 
ELSE X.HORAS_ABONADA END HORAS_ABONADA_F, --NOVO 17/7/20 CORRIGI EXCESSOS NO ULTIMO DIA
X.EMPRESA ,X.TIPO_CONTRATO ,X.MATRICULA ,X.CODIGO, X.DATA 
,X.SITUACAO
,case when X.SITUACAO = 'TRABALHANDO' THEN 'TRABALHANDO' when X.SITUACAO = 'FOLGA' THEN 'FOLGA' WHEN X.SITUACAO IS NULL THEN 'NULO' ELSE 'OCORRENCIA' END SITUACAO_TRATADA, 
X.TIPO_FOLGA, X.ENTRADA ,X.MARCACAO_E1, X.ACEITO
,X.SIT_PONTO 
,X.DESCONTO_ABONADO ,X.HORAS_ABONADA
,X.H_NORMAIS-X.HORAS_ABONADA HORAS_MARCACOES--novo em 23/6/20
,X.DESCONTO ,X.H_EXTRA ,X.H_EXTRA_FERIADO ,X.H_NOTURNA ,X.COMPENSADO ,X.FALTA_COMPENSAR  ,X.ATRASO ,X.SAIDA_ANTECIPADA ,X.H_EXTRA_NOTURNA ,X.H_INTRA_JORNADA ,X.DESCONTO_AUX ,X.INTERJORNADA ,X.BH_CREDITO ,X.BH_DEBITO
,X.DESCONTO_TOLERADO ,X.INTERVALO_A_MENOR ,X.ENTRADA_ANTECIPADA ,X.MULTA_INTERJORNADA ,X.EXTRA_DIA_INFO_SEM_MENSAL ,X.DESCONTO_DIA_INFO_SEM_MENSAL
,X.DTCADASTRO ,X.COD_PESSOA ,X.COD_JUSTIFICATIVA_PONTO ,X.COD_PONTO_FECHAMENTO ,X.COD_BANCO_HORAS ,X.COD_CARGO ,X.COD_UNIDADE ,X.COD_HORARIO ,X.COD_ESCALA_PADRAO ,X.CAMPO_LIVRE
,X.MARCACAO1 ,X.MARCACAO2 ,X.MARCACAO3 ,X.MARCACAO4 ,X.MARCACAO5 ,X.MARCACAO6 ,X.MARCACAO7 ,X.MARCACAO8 ,X.MARCACAO9 ,X.MARCACAO10 ,X.MARCACAO11 ,X.MARCACAO12 ,X.MARCACAO_E2 ,X.MARCACAO_E3 ,X.MARCACAO_E4 ,X.MARCACAO_E5 ,X.MARCACAO_E6 ,X.MARCACAO_E7 ,X.MARCACAO_E8 ,X.MARCACAO_E9 ,X.MARCACAO_E10 ,X.MARCACAO_E11 ,X.MARCACAO_E12 ,X.MARCACAO1_ALTERADA ,X.MARCACAO2_ALTERADA ,X.MARCACAO3_ALTERADA ,X.MARCACAO4_ALTERADA ,X.MARCACAO5_ALTERADA ,X.MARCACAO6_ALTERADA ,X.MARCACAO7_ALTERADA ,X.MARCACAO8_ALTERADA ,X.MARCACAO9_ALTERADA ,X.MARCACAO10_ALTERADA ,X.MARCACAO11_ALTERADA ,X.MARCACAO12_ALTERADA 
,X.OBS_MARCACAO_ALTERADA ,X.BANCO_HORAS ,X.TIPO_BANCO_HORAS ,X.OBS 
 ,X.BIT_DIVERGENCIA ,X.COD_COMPENSACAO ,X.MULTIPLICADOR_BANCO_HORAS ,X.NA009 ,X.DTJUSTIFICATIVA ,X.LOGIN_JUSTIFICATIVA ,X.DTAVALIADOR ,X.LOGIN_AVALIADOR ,X.DTALTERACAO ,X.LOGIN_ALTERACAO ,X.FOTO ,X.SOBREAVISO_DOBRA ,X.COD_JUSTIFICATIVA_BANCO_HORAS ,X.DESCRICAO_BANCO_HORAS ,X.COMPROVANTE_JUSTIFICATIVA ,X.RELATORIO_RH_VALIDADO
,X.TOTAIS , X.AGRUPADOR
FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA X 
WHERE DATA_PROCESSAMENTO IS NULL
and X.MATRICULA IS NOT NULL -- DE 8218 PARA 8218
)X2
)X3
LEFT OUTER JOIN ARTERH.rhpess_contrato c on LPAD(X3.EMPRESA,4,0) = c.codigo_empresa and LPAD(X3.TIPO_CONTRATO,4,0) = C.TIPO_CONTRATO AND LPAD(X3.MATRICULA,15,0) = C.CODIGO
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON LPAD(X3.SIT_PONTO, 4,0) = SP.CODIGO  
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO CC ON CC.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND CC.CODIGO = C.cod_cargo_comiss
left outer join ARTERH.RHTABS_VINCULO_EMP V ON V.CODIGO = c.VINCULO
LEFT OUTER JOIN (select * from ARTERH.rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'TP_REGIME_TRAB_ESOCIAL'))RG_TRAB
ON RG_TRAB.CONTEUDO_INICIAL = V.TP_REGIME_TRAB_ESOCIAL
LEFT OUTER JOIN (select * from ARTERH.rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'TP_REGIME_PREV_ESOCIAL'))RG_PREV
ON RG_PREV.CONTEUDO_INICIAL = V.TP_REGIME_PREV_ESOCIAL
LEFT OUTER JOIN (select * from ARTERH.rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'COD_CATEG_ESOCIAL'))COD_CATEG
ON COD_CATEG.CONTEUDO_INICIAL = V.COD_CATEG_ESOCIAL
LEFT OUTER JOIN (select OC.* from PONTO_ELETRONICO.IFPONTO_OCORRENCIAS OC WHERE OC.DATA_PROCESSAMENTO IS NULL)OC
ON X3.EMPRESA = OC.EMPRESA AND X3.TIPO_CONTRATO = OC.TIPO_CONTRATO AND X3.MATRICULA = OC.MATRICULA AND TRUNC(X3.DATA) BETWEEN TRUNC(OC.DTINICIO) AND TRUNC(DTFIM)
LEFT OUTER JOIN (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP1')IFP1 ON IFP1.DADO_ORIGEM = SP.CODIGO--novo em 26/6/20
LEFT OUTER JOIN (SELECT U.* FROM ARTERH.RHCGED_ALT_SIT_FUN U WHERE U.DATA_INIC_SITUACAO = (SELECT MAX(A.DATA_INIC_SITUACAO)
               FROM ARTERH.RHCGED_ALT_SIT_FUN A WHERE A.CODIGO_EMPRESA = U.CODIGO_EMPRESA AND A.TIPO_CONTRATO = U.TIPO_CONTRATO AND A.CODIGO = U.CODIGO))ASF
                ON ASF.CODIGO_EMPRESA = X3.EMPRESA AND ASF.TIPO_CONTRATO = X3.TIPO_CONTRATO AND ASF.CODIGO = X3.MATRICULA --novo em 9/12/21
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO = ASF.COD_SIT_FUNCIONAL--novo em 9/12/21
LEFT OUTER JOIN (SELECT SUBSTR(DADO_ORIGEM,5,4)SIT_FUNC_IFPONTO, DADO_DESTINO STATUS_IFPONTO FROM ARTERH.RHINTE_ED_IT_CONV where codigo_CONVERSAO ='POST' AND SUBSTR(DADO_ORIGEM, 1,4) = '0001')POST ON POST.SIT_FUNC_IFPONTO = ASF.COD_SIT_FUNCIONAL--novo em 9/12/21
WHERE
C.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO = C.CODIGO)
)X4 
)X5  


)