
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_PS_VALORES" ("ANO_MES_REFERENCIA", "ANO_MES_REF_PLANO", "ANO_MES_REF_FAIXA_SALARIAL", "ANO_MES_REF_FAIXA_ETARIA", "PLANO", "IDENTIFICADOR_FAIXA_SALARIAL", "FAIXA_SALARIAL", "LIMITE_INFERIOR_FAIXA_SALARIAL", "LIMITE_SUPERIOR_FAIXA_SALARIAL", "IDENTIFICADOR_FAIXA_ETARIA", "FAIXA_ETARIA", "LIMITE_INFERIOR_FAIXA_ETARIA", "LIMITE_SUPERIOR_FAIXA_ETARIA", "VALOR_MENSALIDADE", "VALOR_SUBSIDIO", "VALOR_SUBSIDIO_DEP", "CODIGO_PLANO", "DESCRICAO_PLANO") AS 
  select ANO_MES_REFERENCIA, ANO_MES_REF_PLANO, ANO_MES_REF_FAIXA_SALARIAL, ANO_MES_REF_FAIXA_ETARIA,
       PLANO,
       IDENTIFICADOR_FAIXA_SALARIAL, FAIXA_SALARIAL, LIMITE_INFERIOR_FAIXA_SALARIAL, LIMITE_SUPERIOR_FAIXA_SALARIAL,
       IDENTIFICADOR_FAIXA_ETARIA, FAIXA_ETARIA, LIMITE_INFERIOR_FAIXA_ETARIA, LIMITE_SUPERIOR_FAIXA_ETARIA,
       NVL(VALOR_MENSALIDADE,0.00) AS VALOR_MENSALIDADE,
       NVL(VALOR_SUBSIDIO,0.00) AS VALOR_SUBSIDIO,
       NVL(VALOR_SUBSIDIO_DEP,0.00) AS VALOR_SUBSIDIO_DEP,
       CODIGO_PLANO,
       DESCRICAO_PLANO
from(
select RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REFERENCIA,
       RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_PLANO,
       RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_FAIXA_SALARIAL,
       RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_FAIXA_ETARIA,
       RHPBH_PS_PLANOS.IDENTIFICADOR AS PLANO,
       RHPBH_PS_FAIXA_SALARIAL.IDENTIFICADOR AS IDENTIFICADOR_FAIXA_SALARIAL,
       RHPBH_PS_FAIXA_SALARIAL.DESCRICAO AS FAIXA_SALARIAL,
       RHPBH_PS_FAIXA_SALARIAL.LIMITE_INFERIOR AS LIMITE_INFERIOR_FAIXA_SALARIAL,
       RHPBH_PS_FAIXA_SALARIAL.LIMITE_SUPERIOR AS LIMITE_SUPERIOR_FAIXA_SALARIAL,
       RHPBH_PS_FAIXA_ETARIA.IDENTIFICADOR AS IDENTIFICADOR_FAIXA_ETARIA,
       RHPBH_PS_FAIXA_ETARIA.DESCRICAO AS FAIXA_ETARIA,
       RHPBH_PS_FAIXA_ETARIA.LIMITE_INFERIOR AS LIMITE_INFERIOR_FAIXA_ETARIA,
       RHPBH_PS_FAIXA_ETARIA.LIMITE_SUPERIOR AS LIMITE_SUPERIOR_FAIXA_ETARIA,
       RHPBH_PS_VALORES_PLANO_SAUDE.VALOR_MENSALIDADE,
       RHPBH_PS_VALORES_PLANO_SAUDE.VALOR_SUBSIDIO,
       RHPBH_PS_VALORES_PLANO_SAUDE.VALOR_SUBSIDIO_DEP,
       RHBENF_BENEFICIO.CODIGO AS CODIGO_PLANO,
       RHBENF_BENEFICIO.DESCRICAO AS DESCRICAO_PLANO
  from RHPBH_PS_VALORES_PLANO_SAUDE, RHPBH_PS_PLANOS, RHPBH_PS_FAIXA_ETARIA, RHPBH_PS_FAIXA_SALARIAL, RHBENF_BENEFICIO
 where RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_PLANO = RHPBH_PS_PLANOS.ANO_MES_REFERENCIA
   and RHPBH_PS_VALORES_PLANO_SAUDE.IDENTIFICADOR_PLANO = RHPBH_PS_PLANOS.IDENTIFICADOR
   and RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_FAIXA_ETARIA = RHPBH_PS_FAIXA_ETARIA.ANO_MES_REFERENCIA
   and RHPBH_PS_VALORES_PLANO_SAUDE.IDENTIFICADOR_FAIXA_ETARIA = RHPBH_PS_FAIXA_ETARIA.IDENTIFICADOR
   and RHPBH_PS_VALORES_PLANO_SAUDE.ANO_MES_REF_FAIXA_SALARIAL = RHPBH_PS_FAIXA_SALARIAL.ANO_MES_REFERENCIA
   and RHPBH_PS_VALORES_PLANO_SAUDE.IDENTIFICADOR_FAIXA_SALARIAL = RHPBH_PS_FAIXA_SALARIAL.IDENTIFICADOR
   and RHPBH_PS_PLANOS.CODIGO = RHBENF_BENEFICIO.CODIGO
)
order by ANO_MES_REFERENCIA, FAIXA_SALARIAL, FAIXA_ETARIA
