
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_PONTO_ESPELHO" ("CODIGO_EMPRESA", "TIPO_CONTRATO", "CODIGO_CONTRATO", "DATA", "COD_ESCOLA", "MARCACOES_PURAS", "MARCACOES_COM_CHAVE", "DATA_PROCESSAMENTO", "ACAO", "DT_ENVIADO_IFPONTO") AS 
  (
    SELECT '0001' CODIGO_EMPRESA, '0001' TIPO_CONTRATO, BM CODIGO_CONTRATO, TO_CHAR(DATA,'YYYY/MM/DD')DATA, COD_ESCOLA, MARCACOES_PURAS, MARCACOES_COM_CHAVE, DATA_PROCESSAMENTO, ACAO, DT_ENVIADO_IFPONTO
      FROM PONTO_ELETRONICO.SUGESP_SGE_ESPELHO_PONTO
     WHERE DT_ENVIADO_IFPONTO IS NULL
)