
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_PS_VALORES_SUBSIDIO" ("ANO_MES_REFERENCIA", "PLANO", "CODIGO_PLANO", "DESCRICAO_PLANO", "IDENTIFICADOR_FAIXA_SALARIAL", "FAIXA_SALARIAL", "LIMITE_INFERIOR_FAIXA_SALARIAL", "LIMITE_SUPERIOR_FAIXA_SALARIAL", "IDENTIFICADOR_FAIXA_ETARIA", "FAIXA_ETARIA", "LIMITE_INFERIOR_FAIXA_ETARIA", "LIMITE_SUPERIOR_FAIXA_ETARIA", "VALOR_SUBSIDIO") AS 
  select ANO_MES_REFERENCIA, PLANO, CODIGO_PLANO, DESCRICAO_PLANO,
       IDENTIFICADOR_FAIXA_SALARIAL, FAIXA_SALARIAL, LIMITE_INFERIOR_FAIXA_SALARIAL, LIMITE_SUPERIOR_FAIXA_SALARIAL,
       IDENTIFICADOR_FAIXA_ETARIA, FAIXA_ETARIA, LIMITE_INFERIOR_FAIXA_ETARIA, LIMITE_SUPERIOR_FAIXA_ETARIA,
       MAX(NVL(VALOR_SUBSIDIO,0.00)) AS VALOR_SUBSIDIO
  from VW_PS_VALORES group by ANO_MES_REFERENCIA, PLANO, CODIGO_PLANO, DESCRICAO_PLANO,
       IDENTIFICADOR_FAIXA_SALARIAL, FAIXA_SALARIAL, LIMITE_INFERIOR_FAIXA_SALARIAL, LIMITE_SUPERIOR_FAIXA_SALARIAL,
       IDENTIFICADOR_FAIXA_ETARIA, FAIXA_ETARIA, LIMITE_INFERIOR_FAIXA_ETARIA, LIMITE_SUPERIOR_FAIXA_ETARIA
       order by ANO_MES_REFERENCIA, PLANO, LIMITE_INFERIOR_FAIXA_SALARIAL, LIMITE_INFERIOR_FAIXA_ETARIA
