
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_SGE_PAR_REGE_ARQ_DATAS_DE_PARA" ("CPF", "ID_JORNADA_U", "STATUS_REGISTRO", "BM_U", "TIPO_JORNADA_U", "TURNO_U", "HORA_INI_TURNO_U", "HORA_FIM_TURNO_U", "DURACAO_AULA_U", "COD_ORGAO_U", "COORDENACAO_U", "INICIO_JORNADA_U", "FIM_JORNADA_U", "DT_CANCELAMENTO_USAR_U", "SEGUNDA_U", "INTERVALO_SEGUNDA_U", "TERCA_U", "INTERVALO_TERCA_U", "QUARTA_U", "INTERVALO_QUARTA_U", "QUINTA_U", "INTERVALO_QUINTA_U", "SEXTA_U", "INTERVALO_SEXTA_U", "CARGA_HORARIA", "ID_HORARIO", "SEMANA_ANO", "DATA", "INICIO_TURNO", "INICIO_REGENCIA", "FIM_REGENCIA", "OBS_PROCESSAMENTO", "TIPO", "CONTROLE_MINUTOS_EXTRACLASSE", "EXTRA_IGUAL_TURNO_E_DIA", "EXTRA_IGUAL_TURNO_DIA_DIFERE", "EXTRA_DIFERE_TURNO_DIA_IGUAL", "EXTRA_DIFERE_TURNO_E_DIA", "ORDEM_TURNO", "ORDEM_REG_NO_TURNO", "ORDEM_ID_HORARIO_DIA", "ORDEM_PAR_REG", "ORDEM_DIA_CPF") AS 
  (
SELECT  X.CPF, X.ID_JORNADA_U, X.STATUS_REGISTRO, X.BM_U, X.TIPO_JORNADA_U, X.TURNO_U, X.HORA_INI_TURNO_U, X.HORA_FIM_TURNO_U, X.DURACAO_AULA_U, X.COD_ORGAO_U, X.COORDENACAO_U, X.INICIO_JORNADA_U, X.FIM_JORNADA_U, X.DT_CANCELAMENTO_USAR_U, X.SEGUNDA_U, X.INTERVALO_SEGUNDA_U, X.TERCA_U, X.INTERVALO_TERCA_U, X.QUARTA_U, X.INTERVALO_QUARTA_U, X.QUINTA_U, X.INTERVALO_QUINTA_U, X.SEXTA_U, X.INTERVALO_SEXTA_U, X.CARGA_HORARIA, X.ID_HORARIO,X.SEMANA_ANO, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.FIM_REGENCIA, X.OBS_PROCESSAMENTO, X.TIPO, X.CONTROLE_MINUTOS_EXTRACLASSE, X.EXTRA_IGUAL_TURNO_E_DIA, X.EXTRA_IGUAL_TURNO_DIA_DIFERE, X.EXTRA_DIFERE_TURNO_DIA_IGUAL, X.EXTRA_DIFERE_TURNO_E_DIA, 
X.ORDEM_TURNO, X.ORDEM_REG_NO_TURNO, X.ORDEM_ID_HORARIO_DIA, X.ORDEM_PAR_REG, X.ORDEM_DIA_CPF 
FROM (
SELECT P.CPF, A.ID_JORNADA_U, A.STATUS_REGISTRO, A.BM_U, A.TIPO_JORNADA_U, A.TURNO_U, A.HORA_INI_TURNO_U, A.HORA_FIM_TURNO_U, A.DURACAO_AULA_U, A.COD_ORGAO_U, A.COORDENACAO_U, A.INICIO_JORNADA_U, A.FIM_JORNADA_U,
A.DT_CANCELAMENTO_USAR_U, A.SEGUNDA_U, A.INTERVALO_SEGUNDA_U, A.TERCA_U, A.INTERVALO_TERCA_U, A.QUARTA_U, A.INTERVALO_QUARTA_U, A.QUINTA_U, A.INTERVALO_QUINTA_U, A.SEXTA_U, A.INTERVALO_SEXTA_U, A.CARGA_HORARIA,
X.* 
,CASE WHEN A.TURNO_U = 'MANHÃ' THEN 1 WHEN A.TURNO_U = 'INTEGRAL' THEN 1 WHEN A.TURNO_U = 'TARDE' THEN 2 WHEN A.TURNO_U = 'NOITE' THEN 3 END ORDEM_TURNO,
ROW_NUMBER() OVER(PARTITION BY P.CPF, X.DATA, X.INICIO_TURNO ORDER BY P.CPF, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.ID_HORARIO)ORDEM_REG_NO_TURNO, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, X.ID_HORARIO, X.DATA ORDER BY P.CPF, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.ID_HORARIO)ORDEM_ID_HORARIO_DIA, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, X.ID_HORARIO, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.FIM_REGENCIA ORDER BY P.CPF, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.ID_HORARIO)ORDEM_PAR_REG, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, X.DATA ORDER BY P.CPF, X.DATA, X.INICIO_TURNO, X.INICIO_REGENCIA, X.ID_HORARIO)ORDEM_DIA_CPF
FROM
( 
SELECT R.* FROM(
SELECT ID_HORARIO, TO_NUMBER(TO_CHAR(TO_DATE(DATA),'WW')) SEMANA_ANO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TIPO, CONTROLE_MINUTOS_EXTRACLASSE, EXTRA_IGUAL_TURNO_E_DIA, EXTRA_IGUAL_TURNO_DIA_DIFERE, 
EXTRA_DIFERE_TURNO_DIA_IGUAL, EXTRA_DIFERE_TURNO_E_DIA 
FROM 
PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) AND OBS_PROCESSAMENTO IN ('TOTALIZA','ACUMULA','EXCLUI') AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
)R 
)X 
LEFT OUTER JOIN 
(SELECT A.* FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES A LEFT OUTER JOIN 
        (SELECT ID_HORARIO, MAX(TRUNC(DATA_PROCESSAMENTO))DATA_PROCESSAMENTO FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' GROUP BY ID_HORARIO)U ON U.ID_HORARIO = A.ID_HORARIO AND TRUNC(A.DATA_PROCESSAMENTO) = TRUNC(U.DATA_PROCESSAMENTO)
WHERE U.ID_HORARIO IS NOT NULL)A ON X.ID_HORARIO = A.ID_HORARIO
LEFT OUTER JOIN 
(SELECT M.CODIGO_EMPRESA, M.TIPO_CONTRATO, M.CODIGO_CONTRATO, M.CODIGO_PESSOA, P.CPF FROM ARTERH.RHPESS_CONTR_MEST M LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P ON P.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND P.CODIGO = M.CODIGO_PESSOA)P
ON P.CODIGO_EMPRESA = '0001' AND P.TIPO_CONTRATO = '0001' AND P.CODIGO_CONTRATO = A.BM_U
)X

)