
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_SGE_PAR_REGE_ARQ_DIA" ("ID_JORNADA_U", "TIPO", "CPF", "BM_U", "TIPO_JORNADA_U", "TURNO_U", "DATA_INICIO_U", "DATA_FIM_U", "DATA_CANCELAMENTO_U", "DURACAO_AULA_U", "CARGA_HORARIA", "COORDENACAO_U", "ORDEM_TURNO", "ORDEM_REG_NO_TURNO", "ORDEM_ID_HORARIO_DIA", "ORDEM_PAR_REG", "ORDEM_DIA_CPF", "ID_HORARIO", "DATA", "SEMANA_ANO", "INICIO_TURNO", "INICIO_REGENCIA", "FIM_REGENCIA", "DATA_PROCESSAMENTO", "OBS_PROCESSAMENTO", "CONTROLE_MINUTOS_EXTRACLASSE", "EXTRA_IGUAL_TURNO_E_DIA", "EXTRA_IGUAL_TURNO_DIA_DIFERE", "EXTRA_DIFERE_TURNO_DIA_IGUAL", "EXTRA_DIFERE_TURNO_E_DIA") AS 
  (

SELECT X.ID_JORNADA_U, X.TIPO, X."CPF", X."BM_U", X."TIPO_JORNADA_U", X."TURNO_U", X."DATA_INICIO_U", X."DATA_FIM_U",X."DATA_CANCELAMENTO_U",
X.DURACAO_AULA_U, X.CARGA_HORARIA, X.COORDENACAO_U,
X."ORDEM_TURNO", X.ORDEM_REG_NO_TURNO, X."ORDEM_ID_HORARIO_DIA",X."ORDEM_PAR_REG",X."ORDEM_DIA_CPF",X."ID_HORARIO",X."DATA",
X.SEMANA_ANO,
X."INICIO_TURNO",X."INICIO_REGENCIA", X."FIM_REGENCIA", X."DATA_PROCESSAMENTO", X."OBS_PROCESSAMENTO"
,X.CONTROLE_MINUTOS_EXTRACLASSE, X.EXTRA_IGUAL_TURNO_E_DIA, X.EXTRA_IGUAL_TURNO_DIA_DIFERE, X.EXTRA_DIFERE_TURNO_DIA_IGUAL ,X.EXTRA_DIFERE_TURNO_E_DIA
FROM(
SELECT A.ID_JORNADA_U, A.BM_U, A.TIPO_JORNADA_U, A.TURNO_U, A.DATA_INICIO_U, A.DATA_FIM_U, A.DATA_CANCELAMENTO_U,
A.DURACAO_AULA_U, A.CARGA_HORARIA, A.COORDENACAO_U,
CASE WHEN A.TURNO_U = 'MANHÃ' THEN 1 WHEN A.TURNO_U = 'INTEGRAL' THEN 1 WHEN A.TURNO_U = 'TARDE' THEN 2 WHEN A.TURNO_U = 'NOITE' THEN 3 END ORDEM_TURNO,
ROW_NUMBER() OVER(PARTITION BY D.CPF, D.DATA, D.INICIO_TURNO ORDER BY D.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_REG_NO_TURNO, 
ROW_NUMBER() OVER(PARTITION BY D.CPF, D.ID_HORARIO, D.DATA ORDER BY D.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_ID_HORARIO_DIA, 
ROW_NUMBER() OVER(PARTITION BY D.CPF, D.ID_HORARIO, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.FIM_REGENCIA ORDER BY D.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_PAR_REG, 
ROW_NUMBER() OVER(PARTITION BY D.CPF, D.DATA ORDER BY D.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_DIA_CPF, 
TO_NUMBER(TO_CHAR(TO_DATE(D.DATA),'WW')) SEMANA_ANO,
D.* FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS D 
LEFT OUTER JOIN (SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES  WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
                    --AND ID_HORARIO IN(2356,2401,2458,2611,2634,2636, 2787,2784,2783,2790,2788)--TESTE
                    ) A ON A.ID_HORARIO = D.ID_HORARIO

WHERE D.ID_HORARIO IN --(2356,2401,2458,2611,2634,2636, 2787,2784,2783,2790,2788)--TESTES
(SELECT ID_HORARIO FROM(SELECT ID_HORARIO, COUNT(1) FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES  WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
                    --AND ID_HORARIO IN(2356,2401,2458,2611,2634,2636, 2787,2784,2783,2790,2788)--TESTE
GROUP BY ID_HORARIO))--CARGA DO DIA
AND D.TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
ORDER BY D.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC
)X

)