
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_SIT_FUNC_PONTO_ATIVO" ("CODIGO_EMPRESA", "CODIGO_CONTRATO", "TIPO_CONTRATO", "CONTROLE_FOLHA", "CHAVE_INTEGRACAO", "COD_SIT_FUNCIONAL") AS 
  SELECT X."CODIGO_EMPRESA",X."CODIGO_CONTRATO",X."TIPO_CONTRATO",X."CONTROLE_FOLHA",X."CHAVE_INTEGRACAO",X."COD_SIT_FUNCIONAL" FROM (SELECT 
               C.CODIGO_EMPRESA,
               C.CODIGO           AS CODIGO_CONTRATO,
               C.TIPO_CONTRATO,
               SF.CONTROLE_FOLHA,
               CHAVE.DADO_DESTINO AS CHAVE_INTEGRACAO,
               CASE WHEN TRUNC(C.DT_ULT_ALTER_USUA)=TRUNC(SYSDATE) AND CHAVE.DADO_DESTINO='INATIVO' THEN( SELECT COD_SIT_FUNCIONAL
            FROM ARTERH.RHCGED_ALT_SIT_FUN AUX
            WHERE AUX.CODIGO = C.CODIGO AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
            AND AUX.DATA_INIC_SITUACAO=(
            SELECT MAX(AUXX.DATA_INIC_SITUACAO)
            FROM ARTERH.RHCGED_ALT_SIT_FUN AUXX
            WHERE AUXX.CODIGO = AUXX.CODIGO AND AUXX.TIPO_CONTRATO = AUXX.TIPO_CONTRATO AND AUXX.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA
            AND AUXX.DATA_INIC_SITUACAO<C.DATA_INIC_SITUACAO
        )
        
        ) ELSE COD_SIT_FUNCIONAL END AS COD_SIT_FUNCIONAL
        FROM ARTERH.RHCGED_ALT_SIT_FUN C
        INNER JOIN ARTERH.RHPARM_SIT_FUNC    SF ON SF.CODIGO = C.COD_SIT_FUNCIONAL
        INNER JOIN ARTERH.RHINTE_ED_IT_CONV  CHAVE ON SUBSTR(CHAVE.DADO_ORIGEM, 0, 4) = C.CODIGO_EMPRESA AND SUBSTR(CHAVE.DADO_ORIGEM, 5, 4) = SF.CODIGO AND CHAVE.CODIGO_CONVERSAO = 'POST'
        WHERE C.DATA_INIC_SITUACAO = (
            SELECT MAX(AUX.DATA_INIC_SITUACAO)
            FROM ARTERH.RHCGED_ALT_SIT_FUN AUX
            WHERE AUX.CODIGO = C.CODIGO AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA
        )
        )x