
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PONTO_ELETRONICO"."VW_SITUACAO_FUNCIONAL" ("CODIGO_EMPRESA", "EMPRESA", "AGRUPAMENTO_EMPRESA", "CODIGO", "DESCRICAO", "SITUACAO_PONTO", "E_AFASTAMENTO", "DATA_INI_VIGENCIA", "DATA_FIM_VIGENCIA") AS 
  select EMPRESAS.CODIGO_EMPRESA,
       EMPRESAS.EMPRESA,
       EMPRESAS.AGRUPAMENTO_EMPRESA,
       CODIGO, DESCRICAO, SITUACAO_PONTO, E_AFASTAMENTO, DATA_INI_VIGENCIA, DATA_FIM_VIGENCIA from RHPARM_SIT_FUNC
,
(select '0001' AS CODIGO_EMPRESA, 'PREF.MUN.BELO HORIZONTE' EMPRESA, 'ADM DIRETA' AGRUPAMENTO_EMPRESA from dual union
 select '0098' AS CODIGO_EMPRESA, 'PREF.MUN.BH CONTRATOS'   EMPRESA, 'ADM DIRETA' AGRUPAMENTO_EMPRESA from dual
) EMPRESAS
where 
RHPARM_SIT_FUNC.c_livre_valor03 = '999' 
--RHPARM_SIT_FUNC.c_livre_valor03 = '1'--comentado em 14/10/16 para limpar base IFPONTO
--RHPARM_SIT_FUNC.CODIGO = '1000'

order by CODIGO_EMPRESA, CODIGO