
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTERH"."VW_TABELA_PS_MENSALIDADE" ("ANO_MES_REF", "CODIGO_PLANO", "FAIXA_ETARIA", "VALOR") AS 
  select VALOR.ANO_MES_REF, PLANO.VALCHR as CODIGO_PLANO, FAIXA_ETARIA.VALNUM AS FAIXA_ETARIA, VALOR.VALNUM AS VALOR
  from
(
select VPNUM.*
  from RHPESS_TABELAS VP, RHPESS_VALCHR VPNUM
 where VP.CODIGO_TABELA = VPNUM.CODIGO_TABELA
   and VPNUM.CODIGO_TABELA = '000000000008001'
   and VPNUM.NRO_COLUNA = 1
) PLANO,
(
select VPNUM.*
  from RHPESS_TABELAS VP, RHPESS_VALNUM VPNUM
 where VP.CODIGO_TABELA = VPNUM.CODIGO_TABELA
   and VPNUM.CODIGO_TABELA = '000000000008001'
   and VPNUM.NRO_COLUNA = 2
) FAIXA_ETARIA,
(
select VPNUM.*
  from RHPESS_TABELAS VP, RHPESS_VALNUM VPNUM
 where VP.CODIGO_TABELA = VPNUM.CODIGO_TABELA
   and VPNUM.CODIGO_TABELA = '000000000008001'
   and VPNUM.NRO_COLUNA = 3
) VALOR
where FAIXA_ETARIA.CODIGO_TABELA = VALOR.CODIGO_TABELA
  and FAIXA_ETARIA.NRO_LINHA = VALOR.NRO_LINHA
  and FAIXA_ETARIA.ANO_MES_REF = VALOR.ANO_MES_REF
  and PLANO.CODIGO_TABELA = VALOR.CODIGO_TABELA
  and PLANO.NRO_LINHA = VALOR.NRO_LINHA
  and PLANO.ANO_MES_REF = VALOR.ANO_MES_REF