
  CREATE OR REPLACE EDITIONABLE TYPE "ARTERH"."DATA_VALES" as OBJECT (
DATA_INI VARCHAR2(10BYTE) ,
DATA_FIM VARCHAR2(10BYTE),
DIAS_UTEIS_SEM_FERIADO VARCHAR2(10BYTE),
QTD_FERIADOS VARCHAR2(10BYTE),
DIAS_UTEIS_MES VARCHAR2(10BYTE));

