
  CREATE OR REPLACE EDITIONABLE TYPE "ARTERH"."INTERFACE_ARQUIVO" as OBJECT (
     TIPO_ARQUIVO CHAR(4),
     DESCRICAO_TIPO_ARQUIVO VARCHAR2(4000),
     CARACTERE_SEPARADOR CHAR(1),
     TAMANHO_MAXIMO_LINHA NUMBER,
     QTDE_CAMPOS NUMBER,
     INTERFACE INTERFACE_SOFTWARE
    )

