
  CREATE OR REPLACE EDITIONABLE TYPE "ARTERH"."REG_INTERFACE_SOFTWARE" as OBJECT (
    CAMPO      VARCHAR2(1000),
    TAMANHO    NUMBER,
    TAMANHO_IS NUMBER,
    TIPO       NUMBER,
    TIPO_IS    NUMBER,
    NULO       NUMBER,
    VALOR      VARCHAR2(1000)
    )

