
  CREATE OR REPLACE EDITIONABLE TYPE "ARTERH"."TABLE_VALE" AS OBJECT 
( 
 DATA DATE, 
 DIA_SEMANA NUMBER,
 ABREV VARCHAR2(3),
 ABREVIACAO VARCHAR2(15),
 SEMANA NUMBER,
 ESCALA VARCHAR2(4),
 JORNADA VARCHAR2(4)
);

