
  CREATE OR REPLACE EDITIONABLE TYPE "ARTERH"."TYPE_DELEGAR_PARA_CIMA" AS OBJECT (
CODIGO_EMPRESA_PESSOA VARCHAR2(4),
CODIGO_PESSOA VARCHAR2(15),
TIPO_CONTRATO VARCHAR2(4),
CODIGO_CONTRATO VARCHAR2(15),
TEXTO_ASSOCIADO VARCHAR2(2000),
DESCRICAO VARCHAR2(255)
);

