
  CREATE OR REPLACE EDITIONABLE PACKAGE "ARTERH"."PKG_TELA_MOVIMENTACOES" AS 

FUNCTION GET_CENARIO_UPDATE (V_CODIGO_EMPRESA CHAR, V_TIPO_CONTRATO CHAR, 	V_CODIGO VARCHAR2, V_COD_MOVIMENTACAO CHAR, V_DT_ALT_UNID_CUSTO DATE)
RETURN VARCHAR2;

FUNCTION GET_ULTIMO_CONTRATO(O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR, O_CODIGO VARCHAR2) RETURN VARCHAR2;

FUNCTION GET_USER_ACERTA_BASEH(COD_USUARIO VARCHAR2) RETURN NUMBER;

PROCEDURE GRAVA_LOG_BD (TEXTO VARCHAR2) ;

FUNCTION GET_DT_ULT_MOV (V_CODIGO_EMPRESA CHAR, V_TIPO_CONTRATO CHAR, 	V_CODIGO VARCHAR2)
RETURN DATE;

FUNCTION GET_CONTR_MOV_ANTES (O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR,O_CODIGO VARCHAR2, O_DATA_ALTERACAO DATE, O_COD_ALTERACAO CHAR) RETURN VARCHAR2;

FUNCTION GET_CONTR_MOV_ATUAL (O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR,O_CODIGO VARCHAR2) RETURN VARCHAR2;
 
FUNCTION GET_MAX_OCORR (fCODIGO_EMPRESA CHAR , fTIPO_CONTRATO CHAR, fCODIGO_CONTRATO VARCHAR, fDATA_ALTERACAO DATE, fCODIGO_ALTERACAO CHAR )
RETURN NUMBER;

END PKG_TELA_MOVIMENTACOES;
CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ARTERH"."PKG_TELA_MOVIMENTACOES" AS
  -- get funcionário nomeCompleto
vDEVMODE BOOLEAN DEFAULT TRUE; --SET FALSE QUANDO RODAR EM PRODUÇÃO


FUNCTION GET_DT_ULT_MOV (V_CODIGO_EMPRESA CHAR, V_TIPO_CONTRATO CHAR, 	V_CODIGO VARCHAR2) RETURN DATE IS
		V_DT_ULT_MOV DATE;		
		BEGIN
			SELECT DT_ALT_UNID_CUSTO INTO V_DT_ULT_MOV FROM ARTERH.RHCGED_TRANSFERENC MOV WHERE CODIGO_EMPRESA = LPAD(V_CODIGO_EMPRESA,4,0) AND TIPO_CONTRATO = LPAD(V_TIPO_CONTRATO,4,0) AND CODIGO =LPAD(V_CODIGO,15,0) AND DT_ALT_UNID_CUSTO = (SELECT MAX(DT_ALT_UNID_CUSTO) FROM ARTERH.RHCGED_TRANSFERENC 
			WHERE CODIGO_EMPRESA = MOV.CODIGO_EMPRESA AND TIPO_CONTRATO = MOV.TIPO_CONTRATO AND CODIGO = MOV.CODIGO);
		
			RETURN V_DT_ULT_MOV;
	END; --GET_DT_ULT_MOV

FUNCTION GET_CENARIO_UPDATE (V_CODIGO_EMPRESA CHAR, V_TIPO_CONTRATO CHAR, 	V_CODIGO VARCHAR2, V_COD_MOVIMENTACAO CHAR, V_DT_ALT_UNID_CUSTO DATE) RETURN VARCHAR2 IS
	V_CENARIO NUMBER DEFAULT 0;
	V_ACERTA_BASEH NUMBER;
	V_DIF_CONTRATO NUMBER;
	V_MOV_ROWID UROWID;
	V_ULT_MOV_ROWID UROWID;
	V_DT_MOV DATE;
	V_DT_ULT_MOV DATE;
    
    --CENARIOS
    -- 0 = CONTRATO NÃO ALTERADO -- NADA A FAZER
    -- 1 = CONTRATO ALTERADO  -- PERSISTIR ALTERACAO --- NADA A FAZER
    -- 2 = CONRATO ALTERADO -- REVERTER (VOLTAR CONTRATO PARA SITUAÇÃO ANTES DO UPDATE MOV)   
        
  BEGIN
   
	--PODE ACERTAR BASE HISTÓRICA?
	V_ACERTA_BASEH:=GET_USER_ACERTA_BASEH('prcp1329446');
	
	--PEGA ULTIMO MOVIMENTO - DATA
   	V_DT_ULT_MOV:=ARTERH.PKG_TELA_MOVIMENTACOES.GET_DT_ULT_MOV(V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CODIGO);
	
   	-- PEGA MOVIMENTO ATUAL  = DATA LANÇAMENTO NO ARTERH
  	V_DT_MOV:=V_DT_ALT_UNID_CUSTO;
	 
  	--VERIFICAR MOVIMENTAÇÃO NO CONTRATO ATUAL X CONTRATO HIST. ALT CONTRATO
  	SELECT COUNT(1) INTO V_DIF_CONTRATO FROM (
	SELECT ARTERH.PKG_TELA_MOVIMENTACOES.GET_CONTR_MOV_ANTES(1, 98, '1329446', TO_DATE('01-03-2023','DD-MM-RRRR'), 'M001') FROM DUAL MINUS
	SELECT ARTERH.PKG_TELA_MOVIMENTACOES.GET_CONTR_MOV_ATUAL(1, 98, '1329446') FROM DUAL);
	 	
	SELECT  CASE 
		WHEN V_DT_MOV >= V_DT_ULT_MOV THEN 1
		WHEN V_DT_MOV<V_DT_ULT_MOV  AND V_ACERTA_BASEH = 0 AND V_DIF_CONTRATO=1 THEN 2
		ELSE 0
		END CENARIO_MOVIMENTO INTO V_CENARIO
	FROM DUAL;
	
    RETURN V_CENARIO;

	EXCEPTION
	  WHEN NO_DATA_FOUND THEN
	    RETURN 7;
	  WHEN TOO_MANY_ROWS THEN
	    RETURN 8;
	  WHEN OTHERS THEN
	  	RETURN 9;
  END; -- end get_nomeCompleto
  
  --FUNÇÃO PARA GERAR LOGS NO BANCO EM TABELA TEMPORARIA -- OBS: SET vDEVMODE =TRUE PARA FUNCIONAR
	PROCEDURE GRAVA_LOG_BD (TEXTO IN VARCHAR2) AS 	
		PRAGMA AUTONOMOUS_TRANSACTION;
		BEGIN			
			INSERT INTO "ARTERH"."DEBUG_SQL_VALID_APOIO_ROBSON" (DEBUG_MSG,DT_ULT_ALTER_USUA) VALUES (TEXTO ,SYSDATE);
	      	  COMMIT;
		    IF vDEVMODE=TRUE THEN
		    	dbms_output.put_line(TEXTO  ||' - '|| SYSDATE);
	    	END IF;
	END GRAVA_LOG_BD;

	FUNCTION GET_USER_ACERTA_BASEH(COD_USUARIO VARCHAR2) RETURN NUMBER IS 
		V_ACERTO_BASE_HIST NUMBER;
		
		BEGIN
			SELECT CASE ACERTO_BASE_HIST WHEN 'N' THEN 0 ELSE 1 END "acerta_base" 
			INTO V_ACERTO_BASE_HIST FROM ARTERH.RHUSER_P_SIST WHERE UPPER(CODIGO_USUARIO)=UPPER(COD_USUARIO);
		
			RETURN V_ACERTO_BASE_HIST;
			EXCEPTION
				  WHEN NO_DATA_FOUND THEN
				    RETURN 7;
				  WHEN TOO_MANY_ROWS THEN
				    RETURN 8;
				  WHEN OTHERS THEN
				  	RETURN 9;

	END; --FIM FUNC USER_ACERTA_BASEH
	

  
  FUNCTION GET_ULTIMO_CONTRATO(O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR, O_CODIGO VARCHAR2) RETURN VARCHAR2 IS
  	V_CODIGO_ULT_CONT_ROWID VARCHAR2(100);
  	err_msg varchar2 (32000) DEFAULT NULL;
	vEXCEPTION EXCEPTION;

  	BEGIN 
	  	SELECT  TO_CHAR(ANO_MES_REFERENCIA,'DDMMRRRR') || ROWID INTO V_CODIGO_ULT_CONT_ROWID FROM ARTERH.RHPESS_CONTRATO C WHERE
	  	C.CODIGO = O_CODIGO AND C.TIPO_CONTRATO = O_TIPO_CONTRATO AND  C.CODIGO_EMPRESA = O_EMPRESA	AND ROWNUM =1 ORDER BY ANO_MES_REFERENCIA DESC ;
	  	
	  	--GRAVA_LOG_BD(V_CODIGO_ULT_CONT_ROWID);

	  	RETURN V_CODIGO_ULT_CONT_ROWID;
	  
	  	EXCEPTION
	  	WHEN NO_DATA_FOUND THEN
	  		RETURN NULL;
	  	WHEN OTHERS THEN
	  		err_msg := SQLERRM;
		     GRAVA_LOG_BD('GET_ULTIMO_CONTRATO:Error code: ' || SQLCODE || ': ' || err_msg);
	  		RETURN NULL;
	END;

FUNCTION GET_CONTR_MOV_ANTES (O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR,O_CODIGO VARCHAR2, O_DATA_ALTERACAO DATE, O_COD_ALTERACAO CHAR) RETURN VARCHAR2 IS
  	V_CONDIGO_TEXTO_ASSOCIADO VARCHAR2(2000);
  	V_ANO_MES_REF DATE;
  	err_msg varchar2 (32000) DEFAULT NULL;
	vEXCEPTION EXCEPTION;

  	BEGIN 
	  	V_ANO_MES_REF:= TO_DATE(SUBSTR(ARTERH.PKG_TELA_MOVIMENTACOES.GET_ULTIMO_CONTRATO(lpad(O_EMPRESA,4,0),lpad(O_TIPO_CONTRATO,4,0),lpad(O_CODIGO,15,0)),0,8),'DDMMRRRR');
	  	
	  	SELECT TRIM(TEXTO_ASSOCIADO) INTO  V_CONDIGO_TEXTO_ASSOCIADO FROM ARTERH.RHPESS_ALT_CONTRAT AC
		WHERE CODIGO_CONTRATO =lpad(O_CODIGO,15,0) AND CODIGO_ALTERACAO = O_COD_ALTERACAO AND TIPO_CONTRATO = LPAD(O_TIPO_CONTRATO,4,0)
		AND CODIGO_EMPRESA = LPAD(O_EMPRESA,4,0) AND DATA_ALTERACAO = V_ANO_MES_REF
		AND OCORRENCIA =GET_MAX_OCORR(AC.CODIGO_EMPRESA  , AC.TIPO_CONTRATO, AC.CODIGO_CONTRATO , AC.DATA_ALTERACAO, AC.CODIGO_ALTERACAO);
	
	  	--GRAVA_LOG_BD(V_CODIGO_ULT_CONT_ROWID);

	  	RETURN V_CONDIGO_TEXTO_ASSOCIADO;
	  
	  	EXCEPTION
	  	WHEN NO_DATA_FOUND THEN
	  		RETURN NULL;
	  	WHEN OTHERS THEN
	  		err_msg := SQLERRM;
		     GRAVA_LOG_BD('GET_CONTR_MOV_ANTES: Error code: ' || SQLCODE || ': ' || err_msg);
	  		RETURN NULL;
	END;

FUNCTION GET_CONTR_MOV_ATUAL (O_EMPRESA VARCHAR, O_TIPO_CONTRATO VARCHAR,O_CODIGO VARCHAR2) RETURN VARCHAR2 IS
  	V_CONDIGO_TEXTO_ASSOCIADO VARCHAR2(2000);
  	err_msg varchar2 (32000) DEFAULT NULL;
	vEXCEPTION EXCEPTION;

  	BEGIN 
	  	SELECT TO_CHAR(ANO_MES_REFERENCIA,'MMYYYY') || COD_MOVIMENTACAO || COD_LOCAL1 || COD_LOCAL2 || COD_LOCAL3 || COD_LOCAL4 || COD_LOCAL5 || COD_LOCAL6 || COD_UNIDADE1 || COD_UNIDADE2 || COD_UNIDADE3 || COD_UNIDADE4 || COD_UNIDADE5 || COD_UNIDADE6 || COD_CUSTO_CONTAB1 || COD_CUSTO_CONTAB2 || COD_CUSTO_CONTAB3 || COD_CUSTO_CONTAB4 || COD_CUSTO_CONTAB5 || COD_CUSTO_CONTAB6 || COD_CUSTO_GERENC1 || COD_CUSTO_GERENC2 || COD_CUSTO_GERENC3 || COD_CUSTO_GERENC4 || COD_CUSTO_GERENC5 || COD_CUSTO_GERENC6 || TO_CHAR(DATA_TRANSF_ENTRAD,'DDMMYYYY') 
	  	INTO V_CONDIGO_TEXTO_ASSOCIADO
		FROM ARTERH.RHPESS_CONTRATO C 
		WHERE codigo_empresa = lpad(O_EMPRESA,4,0) AND tipo_contrato=lpad(O_TIPO_CONTRATO,4,0) AND codigo = lpad(O_CODIGO,15,0) 
		AND ANO_MES_REFERENCIA =(SELECT MAX(ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO C1 WHERE CODIGO_EMPRESA = C.CODIGO_EMPRESA AND TIPO_CONTRATO = C.TIPO_CONTRATO AND CODIGO = C.CODIGO);
		
	  	--GRAVA_LOG_BD(V_CODIGO_ULT_CONT_ROWID);

	  	RETURN V_CONDIGO_TEXTO_ASSOCIADO;
	  
	  	EXCEPTION
	  	WHEN NO_DATA_FOUND THEN
	  		RETURN NULL;
	  	WHEN OTHERS THEN
	  		err_msg := SQLERRM;
		     GRAVA_LOG_BD('GET_CONTR_MOV_ATUAL: Error code: ' || SQLCODE || ': ' || err_msg);
	  		RETURN NULL;
	END;

FUNCTION GET_MAX_OCORR (fCODIGO_EMPRESA CHAR , fTIPO_CONTRATO CHAR, fCODIGO_CONTRATO VARCHAR, fDATA_ALTERACAO DATE, fCODIGO_ALTERACAO CHAR ) RETURN NUMBER
	IS
	vOCORRENCIA_MAX NUMBER;
	BEGIN	  
	  	SELECT NVL(MAX(OCORRENCIA),0) INTO vOCORRENCIA_MAX FROM ARTERH.RHPESS_ALT_CONTRAT 
		WHERE CODIGO_CONTRATO = LPAD(fCODIGO_CONTRATO,15,0)
		AND CODIGO_EMPRESA = LPAD(fCODIGO_EMPRESA,4,0)
		AND TIPO_CONTRATO =  LPAD(fTIPO_CONTRATO,4,0)
		AND DATA_ALTERACAO = fDATA_ALTERACAO
		AND CODIGO_ALTERACAO = fCODIGO_ALTERACAO;
		
		--GRAVA_LOG_BD ('MAX_OCORRENCIA: ' || fCODIGO_EMPRESA ||'-'|| fTIPO_CONTRATO  ||'-'|| fCODIGO_CONTRATO ||'-'|| fDATA_ALTERACAO ||'-'|| fCODIGO_ALTERACAO);
	  	
	    RETURN vOCORRENCIA_MAX;
	END;
	
	BEGIN
		dbms_output.enable(null);
		GRAVA_LOG_BD('O PACOTE FOI INICIADO PKG_TELA_MOVIMENTACOES');
		dbms_output.put_line('O PACOTE FOI ACIONADO'|| SYSDATE);

		
  END PKG_TELA_MOVIMENTACOES;
 
 
