
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."ASTIN_TABLES_ASSOCS_CONTR" 
(

    PCODIGO_EMPRESA CHAR,
    PTIPO_CONTRATO  CHAR,
    PCODIGO_CONTRATO CHAR)
   AS
  V_CONT NUMBER;
BEGIN
/*
AUTOR: MARCOS 
DATA_VERSAO: 01/04/2022
OBJETIVO: LISTAR TABELAS EM QUE POSSUI UM CODIGO_CONTRATO RELACIONADO
SAIDA DBMS
*/
  DECLARE
    vSQL      VARCHAR2(256);
    vTOT1     PLS_INTEGER;
    VCONT               NUMBER;
    VDATA_BASE          DATE;
    VANO_MES_REFERENCIA DATE;
    VDT_FIM_CONTR_DETER DATE;
    VTAMANHO            NUMBER;
    VCODIGO             VARCHAR2(15);
    VCODIGO_VALIDA      VARCHAR2(15);
    VCONT_VALIDA        NUMBER;
    VCODIGO_EMPRESA     VARCHAR2(4);
    VTIPO_CONTRATO      VARCHAR2(4);
  BEGIN
    dbms_output.enable(NULL);

    VCODIGO_EMPRESA     :=PCODIGO_EMPRESA;
    VTIPO_CONTRATO      :=PTIPO_CONTRATO;
    VCODIGO             :=PCODIGO_CONTRATO;
    VCONT               :=0;
    vTOT1               :=0;
      FOR C1 IN (
        SELECT X.* FROM (
       SELECT  CODIGO_CONTRATO
        FROM RHPESS_CONTR_MEST
        WHERE CODIGO_EMPRESA =PCODIGO_EMPRESA
        AND TIPO_CONTRATO =PTIPO_CONTRATO
        AND CODIGO_CONTRATO =PCODIGO_CONTRATO)X)
      LOOP
      dbms_output.put_line('CODIGO_CONTRATO'||C1.CODIGO_CONTRATO);


            FOR C2 IN (
            SELECT X.* FROM (SELECT CODIGO_TABELA, CODIGO_COLUNA,(SELECT DISTINCT CODIGO_COLUNA
                 FROM ARTERH.RHTABS_COLS_SIST WHERE CODIGO_TABELA IN(
                SELECT DISTINCT CODIGO_TABELA
                FROM ARTERH.RHTABS_COLS_SIST
                WHERE TABELA_RELAC ='RHPESS_CONTR_MEST'
                AND CODIGO_TABELA   = CS.CODIGO_TABELA
                AND NULO ='N') AND TABELA_RELAC ='RHPESS_CONTR_MEST' AND COLUNA_RELAC IN('CODIGO_CONTRATO')AND NULO ='N'
                ) AS COLUNA_2
                 FROM ARTERH.RHTABS_COLS_SIST CS WHERE CS.CODIGO_TABELA IN(
                SELECT DISTINCT CODIGO_TABELA
                FROM ARTERH.RHTABS_COLS_SIST CS
                WHERE TABELA_RELAC ='RHPESS_CONTR_MEST'
                AND CODIGO_TABELA   IN (SELECT CODIGO_TABELA
                FROM ARTERH.RHTABS_COLS_SIST
                WHERE COLUNA_RELAC ='CODIGO_CONTRATO'
                AND NULO ='N')
                AND NULO ='N') AND CS.TABELA_RELAC ='RHPESS_CONTR_MEST' AND CS.COLUNA_RELAC ='CODIGO_EMPRESA')X)
            LOOP
                 vSQL:='SELECT COUNT(1) FROM ARTERH.'||C2.CODIGO_TABELA|| ' WHERE '||C2.CODIGO_COLUNA||' ='''||VCODIGO_EMPRESA||''' AND '||C2.COLUNA_2||' = '''    ||C1.CODIGO_CONTRATO||'''';


                 EXECUTE IMMEDIATE vSQL  INTO vTOT1;

                      IF vTOT1 > 0 THEN 
                      BEGIN 
                      dbms_output.put_line('POSSUI REGISTRO NA TABELA '||C2.CODIGO_TABELA);

                      END;
                      END IF;


        END LOOP; 
       dbms_output.put_line('FIM --> '||VCONT);
       vTOT1:=0;
  END LOOP; 
 END; 
END;
