
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."GRAVA_MODULO_APOSENT" 
(vCODIGO IN CHAR , TABELA  in varchar2, vTIPO_CONTRATO in char, vCODIGO_EMPRESA IN CHAR,
vCOD_MOVIMENTACAO IN CHAR, --movimentação
vDT_ALT_UNID_CUSTO date, --movimentação
vANO_MES_REFERENCIA date,--contrato
vCODIGO_PESSOA IN CHAR, --contrato
vID_LEI_CONTR IN CHAR, --lei contrato
vDATA_INICIO_FUNCAO date, --função
vOCORRENCIA IN CHAR, --RHTEMP_EMPREG_ANT
vDATA_INI_DESAVERB date, --desaverbação
vCPF IN CHAR, --pessoa
vDT_ALTER_NIVEL date, --alteração de nivel
vDATA_INICIO_ESPEC date,--alteração de especialidade
vDT_ALTER_CARGO date --data de alteraçaõ de cargo
                                    
) AS
BEGIN
DECLARE

CONTADOR_1 NUMBER;
CONT NUMBER;
BEGIN

/*
IF TABELA='RHPESS_CONTRATO' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHPESS_CONTRATO_AUDIT WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE)
)
LOOP
CONTADOR_1:=C1.QUANT;
IF CONTADOR_1=1 THEN
update RHPBH_RHPESS_CONTRATO_AUDIT set ID_ALT=1 WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND ID_ALT IS NULL and
 TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
ELSIF  CONTADOR_1 > 1 THEN
update RHPBH_RHPESS_CONTRATO_AUDIT set ID_ALT =
(SELECT MAX (ID_ALT)+1 FROM RHPBH_RHPESS_CONTRATO_AUDIT WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE))
 WHERE ID_ALT IS NULL AND CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA ;

END IF;
END LOOP;
END IF;


IF TABELA='RHCGED_ALT_SIT_FUN' THEN
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHCGED_ALT_SIT_FUN'
WHERE modulo IS NULL AND CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
END IF;
*/

IF TABELA='RHCGED_TRANSFERENC' THEN
CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHCGED_TRANSFERENC_AUDIT WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND COD_MOVIMENTACAO = vCOD_MOVIMENTACAO and trunc(DT_ALT_UNID_CUSTO) = trunc(vDT_ALT_UNID_CUSTO)
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE MOVIMENTAÇÃO */
update RHPBH_RHCGED_TRANSFERENC_AUDIT set ID_ALT=1 WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND COD_MOVIMENTACAO = vCOD_MOVIMENTACAO and trunc(DT_ALT_UNID_CUSTO) = trunc(vDT_ALT_UNID_CUSTO);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE MOVIMENTAÇÃO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHCGED_TRANSFERENC'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN
update RHPBH_RHCGED_TRANSFERENC_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHCGED_TRANSFERENC_AUDIT WHERE CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND COD_MOVIMENTACAO = vCOD_MOVIMENTACAO and trunc(DT_ALT_UNID_CUSTO) = trunc(vDT_ALT_UNID_CUSTO))
 WHERE ID_ALT IS NULL AND CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND COD_MOVIMENTACAO = vCOD_MOVIMENTACAO and trunc(DT_ALT_UNID_CUSTO) = trunc(vDT_ALT_UNID_CUSTO) ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA MOVIMENTAÇÃO */
/*update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHCGED_TRANSFERENC'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;

IF TABELA='RHLEGI_LEI_CONTR' THEN
CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHLEGI_LEI_CONTR_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and ID_LEI_CONTR = vID_LEI_CONTR
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO LEI/CARGO */
update RHPBH_RHLEGI_LEI_CONTR_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and ID_LEI_CONTR = vID_LEI_CONTR;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO LEI/CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHLEGI_LEI_CONTR'
WHERE modulo IS NULL and codigo=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHLEGI_LEI_CONTR_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHLEGI_LEI_CONTR_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and ID_LEI_CONTR = vID_LEI_CONTR)
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and ID_LEI_CONTR = vID_LEI_CONTR ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHLEGI_LEI_CONTR'
WHERE modulo IS NULL and codigo=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);*/

END IF;

END LOOP;
END IF;


IF TABELA='RHPLCA_ALT_NIVEL' THEN
CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHPLCA_ALT_NIVEL_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_NIVEL) = trunc(vDT_ALTER_NIVEL)
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO DE CARGO */
update RHPBH_RHPLCA_ALT_NIVEL_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_NIVEL) = trunc(vDT_ALTER_NIVEL);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARREIRA */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCA_ALT_NIVEL'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHPLCA_ALT_NIVEL_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHPLCA_ALT_NIVEL_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_NIVEL) = trunc(vDT_ALTER_NIVEL))
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and trunc(DT_ALTER_NIVEL) = trunc(vDT_ALTER_NIVEL) ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE CARREIRA */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCA_ALT_NIVEL'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;


IF TABELA='RHPLCS_ALT_CARGO' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHPLCS_ALT_CARGO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_CARGO) = trunc(vDT_ALTER_CARGO)
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO DE CARGO */
update RHPBH_RHPLCS_ALT_CARGO_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_CARGO) = trunc(vDT_ALTER_CARGO);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_CARGO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHPLCS_ALT_CARGO_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHPLCS_ALT_CARGO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DT_ALTER_CARGO) = trunc(vDT_ALTER_CARGO))
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and trunc(DT_ALTER_CARGO) = trunc(vDT_ALTER_CARGO) ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_CARGO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);*/

END IF;

END LOOP;
END IF;



IF TABELA='RHPLCS_ALT_FUNCAO' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHPLCS_ALT_FUNCAO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_FUNCAO) = trunc(vDATA_INICIO_FUNCAO)
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO DE FUNÇÃO */
update RHPBH_RHPLCS_ALT_FUNCAO_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_FUNCAO) = trunc(vDATA_INICIO_FUNCAO);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE FUNÇÃO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_FUNCAO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/


ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHPLCS_ALT_FUNCAO_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHPLCS_ALT_FUNCAO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_FUNCAO) = trunc(vDATA_INICIO_FUNCAO))
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and trunc(DATA_INICIO_FUNCAO) = trunc(vDATA_INICIO_FUNCAO) ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE FUNÇÃO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_FUNCAO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;



IF TABELA='RHTEMP_COMPUTO' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHTEMP_COMPUTO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and OCORRENCIA = vOCORRENCIA
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE Colaborador/Cômputo */
update RHPBH_RHTEMP_COMPUTO_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and OCORRENCIA = vOCORRENCIA;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE Colaborador/Cômputo */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_COMPUTO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHTEMP_COMPUTO_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHTEMP_COMPUTO_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and OCORRENCIA = vOCORRENCIA)
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and OCORRENCIA = vOCORRENCIA ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE Colaborador/Cômputo */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_COMPUTO'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;



IF TABELA='RHTEMP_DESAVERB' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHTEMP_DESAVERB_AUDIT WHERE CODIGO_PESSOA=vCODIGO_PESSOA and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INI_DESAVERB) = trunc(vDATA_INI_DESAVERB)

)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE Colaborador/Desaverbações */
update RHPBH_RHTEMP_DESAVERB_AUDIT set ID_ALT=1 WHERE CODIGO_PESSOA=vCODIGO_PESSOA and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INI_DESAVERB) = trunc(vDATA_INI_DESAVERB);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE Colaborador/Desaverbações */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_DESAVERB'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHTEMP_DESAVERB_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHTEMP_DESAVERB_AUDIT WHERE CODIGO_PESSOA=vCODIGO_PESSOA and codigo_empresa = vCODIGO_EMPRESA AND TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INI_DESAVERB) = trunc(vDATA_INI_DESAVERB))
 WHERE ID_ALT IS NULL AND CODIGO_PESSOA=vCODIGO_PESSOA and codigo_empresa = vCODIGO_EMPRESA and trunc(DATA_INI_DESAVERB) = trunc(vDATA_INI_DESAVERB) ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE Colaborador/Desaverbações */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_DESAVERB'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;


IF TABELA='RHTEMP_EMPREG_ANT' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHTEMP_EMPREG_ANT_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND OCORRENCIA = vOCORRENCIA
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO DE CARGO */
update RHPBH_RHTEMP_EMPREG_ANT_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND OCORRENCIA = vOCORRENCIA;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_EMPREG_ANT'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHTEMP_EMPREG_ANT_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHTEMP_EMPREG_ANT_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) AND OCORRENCIA = vOCORRENCIA)
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND OCORRENCIA = vOCORRENCIA ;
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHTEMP_EMPREG_ANT'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/
END IF;

END LOOP;
END IF;

IF TABELA='RHPLCS_ALT_ESPEC' THEN

CONTADOR_1:=0;
FOR C1 IN  (
SELECT COUNT(1)QUANT FROM RHPBH_RHPLCS_ALT_ESPEC_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA
and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_ESPEC) = trunc(vDATA_INICIO_ESPEC)
)
LOOP
CONTADOR_1:=C1.QUANT;

IF CONTADOR_1=1 THEN
/* ATUALIZA O CAMPO ID_ALT=1 DA TABELA DE LOG DE ALTERAÇÃO DE CARGO */
update RHPBH_RHPLCS_ALT_ESPEC_AUDIT set ID_ALT=1 WHERE CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA AND
ID_ALT IS NULL and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_ESPEC) = trunc(vDATA_INICIO_ESPEC);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_ESPEC'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);
*/

ELSIF  CONTADOR_1 > 1 THEN

update RHPBH_RHPLCS_ALT_ESPEC_AUDIT set ID_ALT = (SELECT MAX (ID_ALT)+1 FROM RHPBH_RHPLCS_ALT_ESPEC_AUDIT WHERE CODIGO_CONTRATO=vCODIGO and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE) and trunc(DATA_INICIO_ESPEC) = trunc(vDATA_INICIO_ESPEC))
 WHERE ID_ALT IS NULL AND CODIGO_CONTRATO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA  and trunc(DATA_INICIO_ESPEC) = trunc(vDATA_INICIO_ESPEC);
/* ATUALIZA O CAMPO MODULO DA TABELA DE LOG DE CONTRATO PARA INFORMAR QUE O REFLEXO FOI GERADO PELA TABELA DE ALTERAÇÃO DE CARGO */
/*
update RHPBH_RHPESS_CONTRATO_AUDIT set Modulo = 'RHPLCS_ALT_ESPEC'
WHERE modulo IS NULL and CODIGO=vCODIGO and tipo_contrato = vTIPO_CONTRATO and codigo_empresa = vCODIGO_EMPRESA and TRUNC(DT_ULT_ALTER_USUA) = TRUNC(SYSDATE);*/

END IF;

END LOOP;
END IF;


END;
end;