
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."GRAVA_ERRO" ( 
      CODIGO_EMPRESA  IN CHAR ,
      TIPO_CONTRATO   IN CHAR,
      CODIGO_CONTRATO IN VARCHAR2,
      COD_ERRO        IN VARCHAR2,
      DES_ERRO        IN VARCHAR2 ,
      objeto          IN VARCHAR2)
  AS
  /*CRIADA PARA GRAVAR OS ERROS EXISTENTES NA TABELA SMARH_INT_ERRO_VALE */
  BEGIN
    INSERT
    INTO ARTERH.SMARH_INT_ERRO_VALE
      (
        ID,
        CODIGO_EMPRESA,
        TIPO_CONTRATO,
        CODIGO_CONTRATO,
        COD_ERRO,
        DESCRICAO_ERRO,
        OBJETO_ERRO
      )
      VALUES
      (
        ARTERH.ID_SEQ_VALE_ERRO.NEXTVAL,
        CODIGO_EMPRESA,
        TIPO_CONTRATO,
        CODIGO_CONTRATO,
        COD_ERRO,
        DES_ERRO,
        objeto
      );
    COMMIT;
  END;