
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."IMPORTAR_EMAIL" (
    
    vCodigo_empresa IN NUMBER,
    vTipo_contrato  IN NUMBER)
AS
  vCONTADOR     NUMBER;
  vDATA_SISTEMA DATE;
BEGIN
  dbms_output.enable(NULL);
  vCONTADOR :=0;

  --SELECT QUE SELECIONA A DATA DO SISTEMA
  SELECT DATA_DO_SISTEMA  INTO vDATA_SISTEMA  FROM rhparm_p_sist;

  /*SELECT PARA RECUPERAR O E-MAIL DO CONTRATO DO ESTAGIÁRIO E O E-MAIL DA TABELA IMPORT_EMAIL*/
  FOR C1 IN
  (SELECT RHPESS_CONTRATO.CODIGO_EMPRESA AS CODIGO_EMPRESA,
    RHPESS_CONTRATO.TIPO_CONTRATO        AS TIPO_CONTRATO,
    RHPESS_CONTRATO.CODIGO               AS CODIGO,
    RHPESS_CONTRATO.NOME                 AS NOME,
    RHPESS_PESSOA.CPF                    AS CPF,
    RHPESS_CONTRATO.E_MAIL               AS E_MAIL,
    IMPORT_EMAIL.E_MAIL                  AS E_MAIL_ATUALIZAR
  FROM IMPORT_EMAIL,
    RHPESS_CONTRATO,
    RHPESS_PESSOA,
    RHUSER_P_SIST
  WHERE RHPESS_PESSOA.CODIGO             = RHPESS_CONTRATO.CODIGO_PESSOA
  AND RHPESS_PESSOA.CPF                  = IMPORT_EMAIL.CPF
  AND IMPORT_EMAIL.CODIGO_USUARIO        = RHUSER_P_SIST.codigo_usuario
  AND RHPESS_CONTRATO.CODIGO             = RHUSER_P_SIST.contrato_usuario
  AND RHPESS_CONTRATO.ANO_MES_REFERENCIA =
    (SELECT MAX (A.ANO_MES_REFERENCIA)
    FROM RHPESS_CONTRATO A
    WHERE A.CODIGO            = RHPESS_CONTRATO.CODIGO
    AND A.CODIGO_EMPRESA      = RHPESS_CONTRATO.CODIGO_EMPRESA
    AND A.TIPO_CONTRATO       = RHPESS_CONTRATO.TIPO_CONTRATO
    AND a.ano_mes_referencia <= TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')
    )
  AND RHPESS_CONTRATO.SITUACAO_FUNCIONAL IN  (select codigo from RHPARM_SIT_FUNC where controle_folha IN ('N','M','L'))
  AND RHPESS_CONTRATO.TIPO_CONTRATO       = vTipo_contrato
  AND RHPESS_CONTRATO.CODIGO_EMPRESA      = vCodigo_empresa
  AND (RHPESS_CONTRATO.E_MAIL            <> IMPORT_EMAIL.E_MAIL
  OR RHPESS_CONTRATO.E_MAIL              IS NULL )
  AND IMPORT_EMAIL.STATUS                 = 'N'
  AND IMPORT_EMAIL.ORGAO                  = 'PBH'
  AND IMPORT_EMAIL.E_MAIL                IS NOT NULL
  )
  LOOP
    vCONTADOR :=vCONTADOR+1;
    dbms_output.put_line('UPDATE :' || vCONTADOR);

    /*UPDATE PARA ATUALIZAR E-MAIL DE ESTAGIÁRIOS NO MAX CONTRATO*/
    UPDATE RHPESS_CONTRATO
    SET E_MAIL                             = C1.E_MAIL_ATUALIZAR,
      DT_ULT_ALTER_USUA                    = SYSDATE,
      LOGIN_USUARIO                        = 'IMPORTACAO EMAIL'
    WHERE RHPESS_CONTRATO.CODIGO_EMPRESA   = C1.CODIGO_EMPRESA
    AND RHPESS_CONTRATO.TIPO_CONTRATO      = C1.TIPO_CONTRATO
    AND RHPESS_CONTRATO.CODIGO             = C1.CODIGO
    AND RHPESS_CONTRATO.ANO_MES_REFERENCIA =
      (SELECT MAX (A.ANO_MES_REFERENCIA)
      FROM RHPESS_CONTRATO A
      WHERE A.CODIGO            = RHPESS_CONTRATO.CODIGO
      AND A.CODIGO_EMPRESA      = RHPESS_CONTRATO.CODIGO_EMPRESA
      AND A.TIPO_CONTRATO       = RHPESS_CONTRATO.TIPO_CONTRATO
      AND a.ano_mes_referencia <= TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')
      );

    /*UPDATE PARA ATUALIZAR STATUS NA TABELA IMPORT_EMAIL*/
    UPDATE IMPORT_EMAIL
    SET STATUS   = 'S'
    WHERE C1.CPF = IMPORT_EMAIL.CPF;
  END LOOP;

  /* COMMIT;*/
  dbms_output.put_line('UPDATE CONCLUIDO COM SUCESSO');
END;