
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_AJUSTE_BASE_UNIDADE" AS
CONT NUMBER:=0;
BEGIN 
FOR C1 IN (
SELECT X.* FROM (SELECT X.* FROM (SELECT 
X.CGC,--NOVO EM 2/11/22
X.CODIGO_EMPRESA,
         CASE
           WHEN X.CODIGO_EMPRESA = '0001' THEN 'PREF.MUN.BELO HORIZONTE'
           WHEN X.CODIGO_EMPRESA = '0098' THEN 'PREF.MUN.BH CONTRATOS'
         END                       AS EMPRESA,
         CASE
           WHEN X.CODIGO_EMPRESA IN ( '0001', '0098', '0015', '0021', '0032' ) THEN 'ADM DIRETA_AJUSTE'
           ELSE 'ADM INDIRETA_AJUSTE'
         END                       AS AGRUPAMENTO_EMPRESA,
         CASE
           WHEN X.COD_CGERENC1 IS NOT NULL THEN SUBSTR(X.CODIGO_EMPRESA, 3, 2) || '.' || X.COD_CGERENC1 || '.' || X.COD_CGERENC2 || '.' || X.COD_CGERENC3 || '.' || X.COD_CGERENC4 || '.' || X.COD_CGERENC5 || '.' || X.COD_CGERENC6
           ELSE NULL
         END                       AS CODIGO_UNIDADE,
         TRIM(X.TEXTO_ASSOCIADO)   AS DESCRICAO_UNIDADE,
         TRIM(X.ABREVIACAO)        AS ABREVIACAO,

         X.DATA_IMPLANT,
         X.DATA_EXTINCAO,
         NULL                      AS TIPO_LOGRADOURO,
         NULL                      AS ENDERECO,
         NULL                      AS NUMERO,
         NULL                      AS COMPLEMENTO,
         NULL                      AS BAIRRO,
         NULL                      AS MUNICIPIO,
         NULL                      AS UF,
         NULL                      AS CEP,
         SYSDATE                   DT_SAIU_ARTE,
         NULL                      AS DT_ENVIADO_IFPONTO_SURICATO,
         'POR_LOCAL'               AS TIPO_HIERARQUIA,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.COD_PESS_INFORMAL
           ELSE X.COD_PESSOA_RESP
         END                       AS COD_PESSOA_RESP,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.CONTRATO_RESP_INF
           ELSE X.CONTRATO_RESP
         END                       AS CONTRATO_RESP,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.TIPO_CONT_RESP_INF
           ELSE X.TIPO_CONT_RESP
         END                       AS TIPO_CONT_RESP,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.COD_EMPR_PESS_INF
           ELSE X.COD_EMPRESA_PESS
         END                       AS COD_EMPRESA_PESS,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.COD_EMPR_PESS_INF
           ELSE X.COD_EMPRESA_PESS
         END                       AS EMPRESA_CODIGO_RESPONSAVEL,
         CASE
           WHEN X.CONTRATO_RESP_INF IS NOT NULL THEN X.CONTRATO_RESP_INF
           ELSE X.CONTRATO_RESP
         END                       AS CODIGO_RESPONSAVEL,
         CASE
           WHEN X.COD_CGERENC_SUP1 IS NOT NULL THEN SUBSTR(X.CODIGO_EMPRESA, 3, 2) || '.' || X.COD_CGERENC_SUP1 || '.' || X.COD_CGERENC_SUP2 || '.' || X.COD_CGERENC_SUP3 || '.' || X.COD_CGERENC_SUP4 || '.' || X.COD_CGERENC_SUP5 || '.' || X.COD_CGERENC_SUP6
           ELSE NULL
         END                       AS CODIGO_LOCAL_SUPERIOR,
         S.TEXTO_ASSOCIADO         AS DESCRICAO_LOCAL_SUPERIO,
          X.COD_CGERENC1            AS COD_UNIDADE1,
         X.COD_CGERENC2            AS COD_UNIDADE2,
         X.COD_CGERENC3            AS COD_UNIDADE3,
         X.COD_CGERENC4            AS COD_UNIDADE4,
         X.COD_CGERENC5            AS COD_UNIDADE5,
         X.COD_CGERENC6            AS COD_UNIDADE6,
         IF.CODIGO_UNIDADE         AS UNIDADE_NOVA_REGRA,
         IF.CODIGO_EMPRESA_GESTOR  AS EMPRESA_GESTOR_IFPONTO_NOVA_REGRA,
         IF.TIPO_CONTRATO_GESTOR   AS TIPO_CONTRATO_IFPONTO_NOVA_REGRA,
         IF.CODIGO_CONTRATO_GESTOR AS GESTOR_IFPONTO_NOVA_REGRA
  FROM ARTERH.RHORGA_CUSTO_GEREN                 X
  LEFT OUTER JOIN RHORGA_CUSTO_GEREN                        S
  ON S.CODIGO_EMPRESA = X.CODIGO_EMPRESA
     AND S.COD_CGERENC1 = X.COD_CGERENC_SUP1
     AND S.COD_CGERENC2 = X.COD_CGERENC_SUP2
     AND S.COD_CGERENC3 = X.COD_CGERENC_SUP3
     AND S.COD_CGERENC4 = X.COD_CGERENC_SUP4
     AND S.COD_CGERENC5 = X.COD_CGERENC_SUP5
     AND S.COD_CGERENC6 = X.COD_CGERENC_SUP6
  LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA                     EM
  ON X.CODIGO_EMPRESA = EM.CODIGO
  LEFT OUTER JOIN PONTO_ELETRONICO.SUGES_BI_UNIDADE_IFPONTO IF
  ON X.CODIGO_EMPRESA = IF.CODIGO_EMPRESA
     AND X.COD_CGERENC1 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 2)
     AND X.COD_CGERENC2 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 3)
     AND X.COD_CGERENC3 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 4)
     AND X.COD_CGERENC4 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 5)
     AND X.COD_CGERENC5 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 6)
     AND X.COD_CGERENC6 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7)
     AND REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7) IS NOT NULL
      WHERE TRIM(X.CGC) = TRIM(EM.CGC)
  AND X.CODIGO_EMPRESA =(SELECT PONT.* FROM (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=X.CODIGO_EMPRESA)
                                             AND X.COD_CGERENC1 NOT IN ('000099','000098')
  )X WHERE ( ( X.GESTOR_IFPONTO_NOVA_REGRA <> X.CODIGO_RESPONSAVEL AND X.DATA_EXTINCAO IS NULL )
        OR ( X.UNIDADE_NOVA_REGRA IS NULL AND X.CODIGO_UNIDADE IS NOT NULL AND X.DATA_EXTINCAO IS NULL )  )   

UNION ---------------------------------------------UNIAO

        SELECT 
        NULL CGC,--NOVO EM 2/11/22
 IF.CODIGO_EMPRESA,
         CASE
           WHEN IF.CODIGO_EMPRESA = '0001' THEN 'PREF.MUN.BELO HORIZONTE'
           WHEN IF.CODIGO_EMPRESA = '0098' THEN 'PREF.MUN.BH CONTRATOS'
         END                       AS EMPRESA,
         CASE
           WHEN X.CODIGO_EMPRESA IN ( '0001', '0098', '0015', '0021', '0032' ) THEN 'ADM DIRETA_AJUSTE'
           ELSE 'ADM INDIRETA_AJUSTE'
         END                       AS AGRUPAMENTO_EMPRESA,
        IF.CODIGO_UNIDADE,
         NULL DESCRICAO_UNIDADE,
         NULL ABREVIACAO,

         NULL DATA_IMPLANT,
         SYSDATE DATA_EXTINCAO,
         NULL                      AS TIPO_LOGRADOURO,
         NULL                      AS ENDERECO,
         NULL                      AS NUMERO,
         NULL                      AS COMPLEMENTO,
         NULL                      AS BAIRRO,
         NULL                      AS MUNICIPIO,
         NULL                      AS UF,
         NULL                      AS CEP,
         SYSDATE                   DT_SAIU_ARTE,
         NULL                      AS DT_ENVIADO_IFPONTO_SURICATO,
         'POR_LOCAL'               AS TIPO_HIERARQUIA,
         NULL COD_PESSOA_RESP,
         NULL CONTRATO_RESP,
         NULL TIPO_CONT_RESP,
         NULL COD_EMPRESA_PESS,
          NULL EMPRESA_CODIGO_RESPONSAVEL,
         NULL CODIGO_RESPONSAVEL,
         NULL CODIGO_LOCAL_SUPERIOR,
         NULL DESCRICAO_LOCAL_SUPERIO,

           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 2) AS COD_UNIDADE1,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 3) AS COD_UNIDADE2,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 4) AS COD_UNIDADE3,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 5) AS COD_UNIDADE4,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 6) AS COD_UNIDADE5,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7) AS COD_UNIDADE6,
           IF.CODIGO_UNIDADE         AS UNIDADE_NOVA_REGRA,
         IF.CODIGO_EMPRESA_GESTOR  AS EMPRESA_GESTOR_IFPONTO_NOVA_REGRA,
         IF.TIPO_CONTRATO_GESTOR   AS TIPO_CONTRATO_IFPONTO_NOVA_REGRA,
         IF.CODIGO_CONTRATO_GESTOR AS GESTOR_IFPONTO_NOVA_REGRA
           FROM PONTO_ELETRONICO.SUGES_BI_UNIDADE_IFPONTO IF
LEFT OUTER JOIN(SELECT * FROM  ARTERH.RHORGA_CUSTO_GEREN X 
LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA                     EM
  ON X.CODIGO_EMPRESA = EM.CODIGO
  WHERE TRIM(X.CGC) = TRIM(EM.CGC))X 
  ON X.CODIGO_EMPRESA = IF.CODIGO_EMPRESA
     AND X.COD_CGERENC1 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 2)
     AND X.COD_CGERENC2 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 3)
     AND X.COD_CGERENC3 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 4)
     AND X.COD_CGERENC4 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 5)
     AND X.COD_CGERENC5 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 6)
     AND X.COD_CGERENC6 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7)

WHERE (IF.CODIGO_UNIDADE IS NOT NULL AND CASE WHEN X.COD_CGERENC1 IS NULL THEN NULL ELSE SUBSTR(X.CODIGO_EMPRESA, 3, 2) || '.' || X.COD_CGERENC1 || '.' || X.COD_CGERENC2 || '.' || X.COD_CGERENC3 || '.' || X.COD_CGERENC4 || '.' || X.COD_CGERENC5 || '.' || X.COD_CGERENC6 END IS NULL)
AND REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7) IS NOT NULL
AND IF.CODIGO_UNIDADE<>'01.000091.000098.000000.000000.000000.000000'

UNION ----------------------------------------------------------UNIAO

SELECT 
NULL CGC,--NOVO EM 2/11/22
 IF.CODIGO_EMPRESA,
         CASE
           WHEN IF.CODIGO_EMPRESA = '0001' THEN 'PREF.MUN.BELO HORIZONTE'
           WHEN IF.CODIGO_EMPRESA = '0098' THEN 'PREF.MUN.BH CONTRATOS'
         END                       AS EMPRESA,
         CASE
           WHEN X.CODIGO_EMPRESA IN ( '0001', '0098', '0015', '0021', '0032' ) THEN 'ADM DIRETA_AJUSTE'
           ELSE 'ADM INDIRETA_AJUSTE'
         END                       AS AGRUPAMENTO_EMPRESA,
        IF.CODIGO_UNIDADE,
         NULL DESCRICAO_UNIDADE,
         NULL ABREVIACAO,

         NULL DATA_IMPLANT,
         SYSDATE DATA_EXTINCAO,
         NULL                      AS TIPO_LOGRADOURO,
         NULL                      AS ENDERECO,
         NULL                      AS NUMERO,
         NULL                      AS COMPLEMENTO,
         NULL                      AS BAIRRO,
         NULL                      AS MUNICIPIO,
         NULL                      AS UF,
         NULL                      AS CEP,
         SYSDATE                   DT_SAIU_ARTE,
         NULL                      AS DT_ENVIADO_IFPONTO_SURICATO,
         'POR_LOCAL'               AS TIPO_HIERARQUIA,
         NULL COD_PESSOA_RESP,
         NULL CONTRATO_RESP,
         NULL TIPO_CONT_RESP,
         NULL COD_EMPRESA_PESS,
          NULL EMPRESA_CODIGO_RESPONSAVEL,
         NULL CODIGO_RESPONSAVEL,
         NULL CODIGO_LOCAL_SUPERIOR,
         NULL DESCRICAO_LOCAL_SUPERIO,

           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 2) AS COD_UNIDADE1,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 3) AS COD_UNIDADE2,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 4) AS COD_UNIDADE3,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 5) AS COD_UNIDADE4,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 6) AS COD_UNIDADE5,
           REGEXP_SUBSTR(REPLACE(CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7) AS COD_UNIDADE6,
           IF.CODIGO_UNIDADE         AS UNIDADE_NOVA_REGRA,
         IF.CODIGO_EMPRESA_GESTOR  AS EMPRESA_GESTOR_IFPONTO_NOVA_REGRA,
         IF.TIPO_CONTRATO_GESTOR   AS TIPO_CONTRATO_IFPONTO_NOVA_REGRA,
         IF.CODIGO_CONTRATO_GESTOR AS GESTOR_IFPONTO_NOVA_REGRA
           FROM PONTO_ELETRONICO.SUGES_BI_UNIDADE_IFPONTO IF
LEFT OUTER JOIN(SELECT * FROM  ARTERH.RHORGA_CUSTO_GEREN X 
LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA                     EM
  ON X.CODIGO_EMPRESA = EM.CODIGO
  WHERE TRIM(X.CGC) = TRIM(EM.CGC))X 
  ON X.CODIGO_EMPRESA = IF.CODIGO_EMPRESA
     AND X.COD_CGERENC1 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 1)
     AND X.COD_CGERENC2 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 2)
     AND X.COD_CGERENC3 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 3)
     AND X.COD_CGERENC4 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 4)
     AND X.COD_CGERENC5 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 5)
     AND X.COD_CGERENC6 = REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 6)

WHERE (IF.CODIGO_UNIDADE IS NOT NULL
AND REGEXP_SUBSTR(REPLACE(IF.CODIGO_UNIDADE, '..', '. .'), '[^.]+', 1, 7) IS  NULL)

)X
/*where X.CODIGO_UNIDADE IN ('01.000095.000000.000015.000050.000010.000000','03.000088.000010.000000.000000.000000.000000')
AND CODIGO_EMPRESA='0001'*/

--INICIO -- NOVO EM 2/11/22

left outer join RHORGA_AGRUPADOR A on x.codigo_empresa = a.codigo_empresa and x.COD_UNIDADE1 = a.cod_agrup1 and x.COD_UNIDADE2 = a.cod_agrup2 and x.COD_UNIDADE3 = a.cod_agrup3 and x.COD_UNIDADE4 = a.cod_agrup4 and x.COD_UNIDADE5 = a.cod_agrup5 and x.COD_UNIDADE6 = a.cod_agrup6
left outer join rhorga_estrut_agr E on  E.ID_AGRUP = A.ID_AGRUP and e.codigo_empresa=a.codigo_empresa and e.codigo_empresa=a.codigo_empresa
LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA EM ON X.CODIGO_EMPRESA=EM.CODIGO

WHERE
e.ano_mes_referencia = (select max(ano_mes_referencia) from rhorga_estrut_agr aux where aux.id_agrup = e.id_agrup and aux.codigo_empresa=e.codigo_empresa)
and E.Nivel_Agrup_Estrut = E.Nivel_Sup_Agr_Est AND TRIM(X.CGC)=TRIM(EM.CGC)
--FIM ---NOVO EM 2/11/22

)
LOOP
CONT:=CONT+1;
INSERT INTO PONTO_ELETRONICO.SMARH_INT_PE_UNIDADE_V2 (
  CODIGO_EMPRESA,
  EMPRESA,
  AGRUPAMENTO_EMPRESA,
  CODIGO_UNIDADE,
  DESCRICAO_UNIDADE,
  ABREVIACAO,
  COD_UNIDADE1,
  COD_UNIDADE2,
  COD_UNIDADE3,
  COD_UNIDADE4,
  COD_UNIDADE5,
  COD_UNIDADE6,
  COD_PESSOA_RESP,
  CONTRATO_RESP,
  TIPO_CONT_RESP,
  COD_EMPRESA_PESS,
  DATA_IMPLANT,
  DATA_EXTINCAO,
  TIPO_LOGRADOURO,
  ENDERECO,
  NUMERO,
  COMPLEMENTO,
  BAIRRO,
  MUNICIPIO,
  UF,
  CEP,
  DT_SAIU_ARTE,
  DT_ENVIADO_IFPONTO_SURICATO,
  TIPO_HIERARQUIA,
  EMPRESA_CODIGO_RESPONSAVEL,
  CODIGO_RESPONSAVEL,
  CODIGO_LOCAL_SUPERIOR,
  DESCRICAO_LOCAL_SUPERIO
  ,CODIGO_INTEGRA_ARTE --NOVO 4/7/22
  ) VALUES (
  C1.CODIGO_EMPRESA,
  C1.EMPRESA,
  C1.AGRUPAMENTO_EMPRESA,
  C1.CODIGO_UNIDADE,
  C1.DESCRICAO_UNIDADE,
  C1.ABREVIACAO,
  C1.COD_UNIDADE1,
  C1.COD_UNIDADE2,
  C1.COD_UNIDADE3,
  C1.COD_UNIDADE4,
  C1.COD_UNIDADE5,
  C1.COD_UNIDADE6,
  C1.COD_PESSOA_RESP,
  C1.CONTRATO_RESP,
  C1.TIPO_CONT_RESP,
  C1.COD_EMPRESA_PESS,
  C1.DATA_IMPLANT,
  C1.DATA_EXTINCAO,
  C1.TIPO_LOGRADOURO,
  C1.ENDERECO,
  C1.NUMERO,
  C1.COMPLEMENTO,
  C1.BAIRRO,
  C1.MUNICIPIO,
  C1.UF,
  C1.CEP,
  C1.DT_SAIU_ARTE,
  C1.DT_ENVIADO_IFPONTO_SURICATO,
  C1.TIPO_HIERARQUIA,
  C1.EMPRESA_CODIGO_RESPONSAVEL,
  C1.CODIGO_RESPONSAVEL,
  C1.CODIGO_LOCAL_SUPERIOR,
  C1.DESCRICAO_LOCAL_SUPERIO
  ,SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
);
COMMIT;
END LOOP;
END;
