
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_ACERTO_TEG_SIT_FUNC" (DATA_INICIO IN VARCHAR2, DATA_FIM IN VARCHAR2)
AS
BEGIN
 --Kellysson em 21/12/21 PARA AJUSTAR ALT SIT FUNC QUANDO GERADO MAIS DE UM REGISTRO PARA A MESMA FICHA, TEM QUE 1-EXCLUIR OS REGISTROS DA ALT SIT FUNC 2-CRIAR UM ATIVO DE TODO O PERIODO, 3-UNIR TODO PERIODO ATIVO E 4-DEPOIS REPROCESSAR A FICHA
BEGIN

DECLARE   
vDATA_INICIO Varchar2(10);
vDATA_FIM Varchar2(10);
err_msg VARCHAR2 (4000 BYTE);

vCONTADOR NUMBER; 
vCONTADOR1 NUMBER; 
vCONTADOR2 NUMBER; 
vULTIMO_REG_ATIVO_SEM_FIM VARCHAR2(1);
vDATA_INICIO_MAIS_RECENTE DATE;
vDATA_INICIO_MAIS_ANTIGO DATE;
vDATA_FIM_MAIS_RECENTE DATE;--novo em 25/10/21

vULTIMO_REG_E_LICENCA VARCHAR2(1);--novo em 25/10/21
vDATA_INICIO_MAIS_RECENTE_L DATE;--novo em 25/10/21
vDATA_INICIO_MAIS_ANTIGO_L DATE;--novo em 25/10/21
vDATA_FIM_MAIS_RECENTE_L DATE;--novo em 25/10/21
vPROXIMA_SITUACAO VARCHAR2(4);--novo em 25/10/21
vTEM_FICHA_PERIODO VARCHAR2(1);--novo em 25/10/21 
vQTD_FICHAS_SEQUENCIAIS NUMBER;--NOVO EM 26/10/21
vQTD_SIT_FUNC_SEQUENCIAIS NUMBER;--NOVO EM 26/10/21

--V_ULT_SIT_FUNC0_ATIVA VARCHAR2 (4 BYTE);
vQTD_DIAS_FICHA NUMBER;
vQTD_DIAS_SIT_FUNC NUMBER;

V_SIT_FUNC_ATIVA_VINCULO VARCHAR2 (4 BYTE);

BEGIN
dbms_output.enable(null);

vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

vCONTADOR := 0;
vCONTADOR1 := 0;
vCONTADOR2 := 0;
vULTIMO_REG_ATIVO_SEM_FIM := NULL;
vDATA_INICIO_MAIS_RECENTE := NULL;
vDATA_INICIO_MAIS_ANTIGO := NULL;
vDATA_FIM_MAIS_RECENTE := NULL;

vULTIMO_REG_E_LICENCA := NULL;---novo em 25/10/21
vDATA_INICIO_MAIS_RECENTE_L := NULL;--novo em 25/10/21
vDATA_INICIO_MAIS_ANTIGO_L := NULL;---novo em 25/10/21
vDATA_FIM_MAIS_RECENTE_L := NULL;---novo em 25/10/21
vPROXIMA_SITUACAO := NULL;--novo em 25/10/21
vTEM_FICHA_PERIODO := NULL; --novo em 25/10/21
vQTD_FICHAS_SEQUENCIAIS := 0;--NOVO EM 26/10/21
vQTD_SIT_FUNC_SEQUENCIAIS := 0;--NOVO EM 26/10/21

--V_ULT_SIT_FUNC0_ATIVA := NULL;
vQTD_DIAS_FICHA := 0;
vQTD_DIAS_SIT_FUNC := 0;

V_SIT_FUNC_ATIVA_VINCULO := NULL;

err_msg := NULL;


UPDATE ARTERH.SUGESP_FICHAS_MEDICAS  SET processado = 'N' where processado is null; COMMIT;--NOVO EM 1/4/22 PARA DEIXAR LIMPO A TABELA E NAO DAR ERRO NA IMPORTACAO DAS FICHAS DA TEG

FOR C1 IN (



SELECT 
CASE
WHEN TRUNC(X2.DATA_INICIO_FERIAS) < TRUNC(X2.DATA_INI_AFAST) AND TRUNC(X2.DATA_FIM_FERIAS) >= TRUNC(X2.DATA_FIM_AFAST) THEN
'1-FERIAS COMECOU ANTES DO INICIO AFASTAMENTO E TERMINOU AS FERIAS DEPOIS DO FIM DO AFASTAMENTO'
WHEN TRUNC(X2.DATA_INICIO_FERIAS) < TRUNC(X2.DATA_INI_AFAST) AND TRUNC(X2.DATA_FIM_FERIAS) < TRUNC(X2.DATA_FIM_AFAST) THEN
'2-FERIAS COMECOU ANTES DO INICIO AFASTAMENTO E TERMINOU ANTES DO FIM DO AFASTAMENTO'
WHEN TRUNC(X2.DATA_INICIO_FERIAS) >= TRUNC(X2.DATA_INI_AFAST) THEN '3-FERIAS COMECOU NO MESMO DIA OU DURANTE O AFASTAMENTO'
ELSE 'SEM_FERIAS_PERIODO' END STATUS_FERIAS,
X2.* FROM(

SELECT 
F.DATA_INICIO_FERIAS, F.DATA_FIM_FERIAS,
UA.ULT_SIT_FUNC_ATIVA,
--TEG1.PROCEDIMENTO, TEG1.CONDUTA, TEG1.VINCULO, 
FM.LOGIN_USUARIO, TEG1.COD_SIT_FUNC_DEFERIDA, TEG1.COD_SIT_FUNC_DOENCA_GRAVE,
FM.TIPO_CONTRATO, FM.CODIGO_CONTRATO, M.VINCULO,
X.* FROM(
-------------------------------INICIO------------------------ NUCLEO DOS REGISTROS DAS FICHAS PROCESSADAS LOG
SELECT L.CODIGO_EMPRESA, L.CODIGO_PESSOA, L.DT_REG_OCORRENCIA, L.OCORRENCIA,
F.NATUREZA_EXAME, F.DATA_INI_AFAST, F.DATA_FIM_AFAST, P.CODIGO_PROC_MED
,COUNT(1)QUANT_REG_LOG 
FROM SUGESP_FICHAS_MEDICAS L 
LEFT OUTER JOIN RHMEDI_FICHA_MED F ON F.CODIGO_EMPRESA = L.CODIGO_EMPRESA AND F.CODIGO_PESSOA = L.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = L.DT_REG_OCORRENCIA AND F.OCORRENCIA = L.OCORRENCIA
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO P ON F.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND F.CODIGO_PESSOA = P.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = P.DT_REG_OCORRENCIA AND F.OCORRENCIA = P.OCORRENCIA
WHERE L.CODIGO_EMPRESA = '0001' 
--AND TRUNC(L.DT_ULT_ALTER_USUA) = TRUNC(SYSDATE)-1 --TO_DATE('23/12/2021','DD/MM/YYYY')--TO_DATE('16/12/2021','DD/MM/YYYY')--TRUNC(SYSDATE)-2--PARA NÃO RODAR-- >= TRUNC(SYSDATE)+1----------------------------------TROCA DATA----------------------------------------DATA A FILTRAR NOS REGISTROS ALTERADOS NA LOG DE FICHAS MEDICAS 
AND TRUNC(L.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM --TO_DATE('23/12/2021','DD/MM/YYYY')--TO_DATE('16/12/2021','DD/MM/YYYY')--TRUNC(SYSDATE)-2--PARA NÃO RODAR-- >= TRUNC(SYSDATE)+1----------------------------------TROCA DATA----------------------------------------DATA A FILTRAR NOS REGISTROS ALTERADOS NA LOG DE FICHAS MEDICAS 
--AND L.login_usuario in('pb003374_via_imp_ficha','pr114641_via_imp_ficha')
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL AND TRUNC(F.DATA_INI_AFAST)>= TO_DATE('01/10/2019','DD/MM/YYYY')
GROUP BY L.CODIGO_EMPRESA, L.CODIGO_PESSOA, L.DT_REG_OCORRENCIA, L.OCORRENCIA,
F.NATUREZA_EXAME, F.DATA_INI_AFAST, F.DATA_FIM_AFAST, P.CODIGO_PROC_MED
ORDER BY L.CODIGO_EMPRESA, L.CODIGO_PESSOA, L.DT_REG_OCORRENCIA, L.OCORRENCIA,
F.NATUREZA_EXAME, F.DATA_INI_AFAST, F.DATA_FIM_AFAST, P.CODIGO_PROC_MED
-------------------------------FIM------------------------ NUCLEO DOS REGISTROS DAS FICHAS PROCESSADAS LOG
)X
LEFT OUTER JOIN RHMEDI_FICHA_MED FM ON FM.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND FM.CODIGO_PESSOA = X.CODIGO_PESSOA AND FM.DT_REG_OCORRENCIA = X.DT_REG_OCORRENCIA AND FM.OCORRENCIA = X.OCORRENCIA
LEFT OUTER JOIN RHPESS_CONTRATO M ON M.CODIGO_EMPRESA = FM.CODIGO_EMPRESA AND M.TIPO_CONTRATO = FM.TIPO_CONTRATO AND M.CODIGO = FM.CODIGO_CONTRATO 
LEFT OUTER JOIN 
(SELECT SUBSTR(TEG1.DADO_ORIGEM,1,4)PROCEDIMENTO, SUBSTR(TEG1.DADO_ORIGEM,5,15)CONDUTA, SUBSTR(TEG1.DADO_ORIGEM,20,4)VINCULO, SUBSTR(TEG1.DADO_DESTINO,1,4)COD_SIT_FUNC_DEFERIDA, SUBSTR(TEG1.DADO_DESTINO,17,4)COD_SIT_FUNC_DOENCA_GRAVE
FROM RHINTE_ED_IT_CONV TEG1 where TEG1.codigo_CONVERSAO ='TEG1' 
)TEG1 ON TEG1.PROCEDIMENTO= X.NATUREZA_EXAME AND TEG1.CONDUTA = X.CODIGO_PROC_MED AND TEG1.VINCULO = M.VINCULO 

LEFT OUTER JOIN
(
-- INICIO ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO
SELECT A.CODIGO_EMPRESA,A.TIPO_CONTRATO, A.CODIGO, A.DATA_INIC_SITUACAO, A.COD_SIT_FUNCIONAL ULT_SIT_FUNC_ATIVA
FROM RHCGED_ALT_SIT_FUN A
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE 
A.DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO)FROM RHCGED_ALT_SIT_FUN AUX
                                 LEFT OUTER JOIN RHPARM_SIT_FUNC SX ON SX.CODIGO = AUX.COD_SIT_FUNCIONAL
                                WHERE  A.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND A.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND A.CODIGO = AUX.CODIGO
                                --AND TRUNC(AUX.DATA_INIC_SITUACAO) < TRUNC(X3.DATA_INICIO)
                                AND SX.CONTROLE_FOLHA = 'N' AND SX.E_AFASTAMENTO = 'N' AND SX.SUSPENDE_REMUNERA = 'N' AND SX.C_LIVRE_SELEC02 = '2')
AND S.CONTROLE_FOLHA = 'N' AND S.E_AFASTAMENTO = 'N' AND S.SUSPENDE_REMUNERA = 'N' AND S.C_LIVRE_SELEC02 = '2'
-- FIM ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO
)UA ON UA.CODIGO_EMPRESA = FM.CODIGO_EMPRESA AND UA.TIPO_CONTRATO = FM.TIPO_CONTRATO AND UA.CODIGO = FM.CODIGO_CONTRATO


LEFT OUTER JOIN (
SELECT  
F.CODIGO_EMPRESA CODIGO_EMPRESA_F, F.TIPO_CONTRATO TIPO_CONTRATO_F, F.CODIGO_CONTRATO CODIGO_CONTRATO_F,
F.TIPO_FERIAS, F.DT_INI_AQUISICAO, F.PERIODO,
'F' CONTROLE_FOLHA_F, 'N' E_AFASTAMENTO_F, P.SITUACAO_PONTO COD_SIT_PONTO_F,
--NULL PROXIMA_SITUACAO, 0 QTDE_DIAS_PROXIMO,
'N' SUSPENDE_REMUNERA_F, 9 SO_GERA_SIT_PONTO_F,
--P.DESCRICAO SITUACAO_PONTO_F, 'P' TIPO_SITUACAO_F, 
F.DT_INI_GOZO DATA_INICIO_FERIAS, 
CASE
    WHEN F.STATUS_CONFIRMACAO in ('5','D')
    THEN
      (SELECT MAX(DT.DATA_DIA)
      FROM RHFERI_FERIAS FF,
        RHTABS_DATAS DT
      WHERE FF.CODIGO_EMPRESA = F.CODIGO_EMPRESA
      AND FF.TIPO_CONTRATO = F.TIPO_CONTRATO
      AND FF.DT_INI_AQUISICAO = F.DT_INI_AQUISICAO
      AND FF.DT_FIM_AQUISICAO = F.DT_FIM_AQUISICAO
      AND FF.CODIGO_CONTRATO = F.codigo_contrato
      AND DT.DATA_DIA BETWEEN F.DT_INI_GOZO AND F.DT_RETORNO-1
      AND FF.STATUS_CONFIRMACAO =F.STATUS_CONFIRMACAO
      AND DT.DATA_DIA NOT          IN
        (SELECT D.DATA_DIA
        FROM RHPARM_CALEND_DT D
        WHERE D.CODIGO  = '0001'
        AND DT.DATA_DIA = D.DATA_DIA))
        else F.DT_FIM_GOZO
  END
DATA_FIM_FERIAS
FROM RHFERI_FERIAS F
LEFT OUTER JOIN RHPARM_P_FERI P ON P.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND P.CODIGO = F.TIPO_FERIAS
WHERE F.STATUS_CONFIRMACAO in ('1','5','D','G')

)F  ON --FERIAS NO PERIODO DA FICHA
F.CODIGO_EMPRESA_F = FM.CODIGO_EMPRESA AND F.TIPO_CONTRATO_F = FM.TIPO_CONTRATO AND F.CODIGO_CONTRATO_F = FM.CODIGO_CONTRATO
AND
  ((TRUNC(F.DATA_INICIO_FERIAS) >= TRUNC(FM.DATA_INI_AFAST) AND TRUNC(F.DATA_INICIO_FERIAS) <= TRUNC(FM.DATA_FIM_AFAST))
  OR (TRUNC(F.DATA_INICIO_FERIAS)< TRUNC(FM.DATA_INI_AFAST) AND TRUNC(F.DATA_FIM_FERIAS) >= TRUNC(FM.DATA_INI_AFAST))
)

WHERE M.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = M.TIPO_CONTRATO AND AUX.CODIGO = M.CODIGO) 
--AND FM.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')

)X2
--where x2.codigo_contrato = '000000001027989' --testes

)
LOOP
vCONTADOR1 :=vCONTADOR1+1; 
dbms_output.put_line('--vCONTADOR1: '||vCONTADOR1||'--------------------------------------------INICIO DE 1 BM');
dbms_output.put_line('--C1.CODIGO_EMPRESA: '||C1.CODIGO_EMPRESA||' C1.TIPO_CONTRATO: '||C1.TIPO_CONTRATO||' C1.CODIGO_CONTRATO: '||C1.CODIGO_CONTRATO||' C1.CODIGO_PESSOA: '||C1.CODIGO_PESSOA||' C1.DT_REG_OCORRENCIA: '||C1.DT_REG_OCORRENCIA||' C1.OCORRENCIA: '||C1.OCORRENCIA
||' C1.NATUREZA_EXAME: '||C1.NATUREZA_EXAME||' C1.DATA_INI_AFAST: '||C1.DATA_INI_AFAST||' C1.DATA_FIM_AFAST: '||C1.DATA_FIM_AFAST||' C1.CODIGO_PROC_MED: '||C1.CODIGO_PROC_MED);


/*--comentado em 29/12/21
-- inicio ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO
select A.COD_SIT_FUNCIONAL
into V_ULT_SIT_FUNC0_ATIVA
--, A.DATA_FIM_SITUACAO, A.DATA_INIC_SITUACAO, S.DESCRICAO SITUACAO_FUNCIONAL, S.CONTROLE_FOLHA, S.E_AFASTAMENTO,s.suspende_remunera, s.c_livre_selec02 SO_GERA_SIT_PONTO,S.SITUACAO_PONTO COD_SIT_PONTO, P.DESCRICAO SITUACAO_PONTO, p.tipo_situacao
from RHCGED_ALT_SIT_FUN A
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE A.CODIGO_EMPRESA = C1.CODIGO_EMPRESA --'0001'
AND A.TIPO_CONTRATO = C1.TIPO_CONTRATO--'0001'
AND A.CODIGO = C1.CODIGO_CONTRATO--'000000001109306'
AND
A.DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO)FROM RHCGED_ALT_SIT_FUN AUX
                                 LEFT OUTER JOIN RHPARM_SIT_FUNC SX ON SX.CODIGO = AUX.COD_SIT_FUNCIONAL
                                WHERE  A.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND A.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND A.CODIGO = AUX.CODIGO
                                AND trunc(AUX.DATA_INIC_SITUACAO) < TRUNC(C1.DATA_INI_AFAST)
                                AND SX.CONTROLE_FOLHA = 'N' and SX.E_AFASTAMENTO = 'N' and SX.suspende_remunera = 'N' AND SX.C_LIVRE_SELEC02 = '2')
AND S.CONTROLE_FOLHA = 'N' and S.E_AFASTAMENTO = 'N' and S.suspende_remunera = 'N' AND S.C_LIVRE_SELEC02 = '2';
-- FIM ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO
*/


-- INICIO ---------------------DEFINE SITUACAO ATIVA POR VINCULO
select CASE 
WHEN C1.ULT_SIT_FUNC_ATIVA IS NOT NULL THEN C1.ULT_SIT_FUNC_ATIVA
WHEN C1.ULT_SIT_FUNC_ATIVA IS NULL AND C1.VINCULO IN ('0000','0001','0002','0007','0013','0015','0023','0033') THEN '1000'
WHEN C1.ULT_SIT_FUNC_ATIVA IS NULL AND C1.VINCULO IN ('0010','0012','0030') THEN '1012'
ELSE '0000'
END
INTO V_SIT_FUNC_ATIVA_VINCULO 
FROM DUAL ;
-- FIM ---------------------DEFINE SITUACAO ATIVA POR VINCULO

dbms_output.put_line('--V_SIT_FUNC_ATIVA_VINCULO: '||V_SIT_FUNC_ATIVA_VINCULO);

IF C1.STATUS_FERIAS IN ('SEM_FERIAS_PERIODO', '3-FERIAS COMECOU NO MESMO DIA OU DURANTE O AFASTAMENTO' ) THEN---NAO REPROCESSAR SE PESSOA DE FERAS--NOVO EM 4/1/22


---INICIO---C2. POR BM VERIFICAR HISTORICO A PARTIR DE 01/10/19
--INICIO ---------novo EM 20/12/21-- pego da HOMOLOGA_EXADATA PROCEDURE ----------------------------------------------------------------------------------------------------------------------
FOR C6 IN (


select  
TEG1.SF_TEG1,
x2.* from(
SELECT
X.*
 FROM (
SELECT 
S.* 
FROM (
select 
k.*
 from (
SELECT 
C.CODIGO_PESSOA,
COD_CATEG.CONTEUDO_INICIAL TIPO_TRABALHADOR, C.SITUACAO_FUNCIONAL SIT_FUNC_ULT_CONTR
--,TRUNC(Q.DATA_INICIO_COMPARAR) - TRUNC(Q.DATA_FIM_COMPARAR) -1 AS LACUNAS 
,Q.* 
FROM(
SELECT 
T.* 
, TRUNC(T.DATA_FIM)- TRUNC(T.DATA_INICIO) QTD_DIAS_SIT_FUNC
FROM (
SELECT 
ROW_NUMBER() OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC) AS ORDEM_BM,
A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO, A.COD_SIT_FUNCIONAL, S.DESCRICAO SIT_FUNCIONAL, S.CONTROLE_FOLHA, 
S.E_AFASTAMENTO, S.SUSPENDE_REMUNERA, S.qtde_dias_proximo,
to_date(to_char(A.DATA_INIC_SITUACAO,'dd/mm/yyyy'),'dd/mm/yyyy') DATA_INICIO, to_date(to_char(A.DATA_FIM_SITUACAO,'dd/mm/yyyy'),'dd/mm/yyyy') DATA_FIM--, A.PROXIMA_SITUACAO 
,a.login_usuario, a.dt_ult_alter_usua, A.PROXIMA_SITUACAO
,LEAD(A.COD_SIT_FUNCIONAL, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMO_COD_SIT_FUNCIONAL
,LEAD(S.DESCRICAO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMA_SIT_FUNCIONAL
,LEAD(S.CONTROLE_FOLHA, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMO_CONTROLE_FOLHA
,LEAD(S.E_AFASTAMENTO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMO_E_AFASTAMENTO
,LEAD(S.SUSPENDE_REMUNERA, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMO_SUSPENDE_REMUNERA
,LEAD(to_date(to_char(A.DATA_INIC_SITUACAO,'dd/mm/yyyy'),'dd/mm/yyyy'), 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO  ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMA_DATA_INICIO
,LEAD(to_date(to_char(A.DATA_FIM_SITUACAO,'dd/mm/yyyy'),'dd/mm/yyyy'), 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO  ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMA_DATA_FIM
,LEAD(a.login_usuario, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMO_login_usuario
,LEAD( a.dt_ult_alter_usua, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO DESC ) AS PROXIMa_dt_ult_alter_usua

FROM RHCGED_ALT_SIT_FUN A
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
WHERE 
--A.CODIGO IN ('000000000883291','00000000021005X','000000000239597', '00000000028777X', '000000000297562', '000000000302450') AND
A.CODIGO_EMPRESA = '0001'
--A.CODIGO_EMPRESA IN ('0001','0098','0003','0013','0014', '0002','0007','0009','0010')-- '1' 
                                                                            -- and trunc(A.DT_ULT_ALTER_USUA) >= to_date('19/12/2019','dd/mm/yyyy')--1291
and 
(trunc(A.DATA_INIC_SITUACAO) >= to_date('30/09/2019','dd/mm/yyyy')
or A.DATA_FIM_SITUACAO IS NULL --NOVO EM 15/10/21
OR trunc(A.DATA_FIM_SITUACAO) >= to_date('30/09/2019','dd/mm/yyyy')--NOVO EM 15/10/21
)
--AND A.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
)T
)Q
LEFT OUTER JOIN rhpess_contrato c ON C.CODIGO_EMPRESA = q.CODIGO_EMPRESA AND C.TIPO_CONTRATO = q.TIPO_CONTRATO AND C.CODIGO = q.CODIGO
left outer join RHTABS_VINCULO_EMP V ON V.CODIGO = c.VINCULO
LEFT OUTER JOIN (select * from rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'TP_REGIME_TRAB_ESOCIAL'))RG_TRAB
ON RG_TRAB.CONTEUDO_INICIAL = V.TP_REGIME_TRAB_ESOCIAL
LEFT OUTER JOIN (select * from rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'TP_REGIME_PREV_ESOCIAL'))RG_PREV
ON RG_PREV.CONTEUDO_INICIAL = V.TP_REGIME_PREV_ESOCIAL
LEFT OUTER JOIN (select * from rhtabs_itds_sist WHERE CODIGO_DOMINIO IN (select CODIGO_DOMINIO from RHTABS_COLS_SIST  where codigo_tabela = 'RHTABS_VINCULO_EMP' and codigo_coluna = 'COD_CATEG_ESOCIAL'))COD_CATEG
ON COD_CATEG.CONTEUDO_INICIAL = V.COD_CATEG_ESOCIAL
WHERE 
C.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA)FROM RHPESS_CONTRATO AUX WHERE C.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND C.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND C.CODIGO = AUX.CODIGO)
and c.data_rescisao is null 
and c.CODIGO_EMPRESA = '0001'
--and c.CODIGO_EMPRESA IN ('0001','0098','0003','0013','0014', '0002','0007','0009','0010')-----------------------para todos bm ativos em geral
)k
--WHERE k.lacunas <> 0 --teste urbel sequencia de ativos
order by  K.CODIGO_EMPRESA , K.TIPO_CONTRATO , K.CODIGO , K.data_inicIO
)S
)X 
)x2 
LEFT OUTER JOIN (
 SELECT SUBSTR(X.DADO_DESTINO,1,4)SF_TEG1 FROM RHINTE_ED_IT_CONV X where X.codigo_CONVERSAO ='TEG1' AND SUBSTR(X.DADO_DESTINO,1,4) IS NOT NULL GROUP BY SUBSTR(X.DADO_DESTINO,1,4)
UNION ALL  SELECT SUBSTR(X.DADO_DESTINO,17,4)SF_TEG1 FROM RHINTE_ED_IT_CONV X where X.codigo_CONVERSAO ='TEG1' AND SUBSTR(X.DADO_DESTINO,17,4) IS NOT NULL GROUP BY SUBSTR(X.DADO_DESTINO,17,4)
)TEG1 ON TEG1.SF_TEG1 = X2.COD_SIT_FUNCIONAL
WHERE X2.CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND X2.TIPO_CONTRATO = C1.TIPO_CONTRATO AND X2.CODIGO = C1.CODIGO_CONTRATO---QUE LINKA O C2 COM O C6
--AND (TRUNC(X2.DATA_INICIO) BETWEEN TRUNC(C1.DATA_INI_AFAST) AND TRUNC(C1.DATA_FIM_AFAST) OR TRUNC(X2.DATA_FIM) BETWEEN TRUNC(C1.DATA_INI_AFAST) AND TRUNC(C1.DATA_FIM_AFAST)) --NOVO EM 21/12/21
order by  x2.CODIGO_EMPRESA , x2.TIPO_CONTRATO , x2.CODIGO , x2.data_inicIO desc


)
LOOP

vCONTADOR :=vCONTADOR+1; 
dbms_output.put_line('--'||vCONTADOR);
dbms_output.put_line('--ORDEM_BM: '||C6.ORDEM_BM||' CODIGO_EMPRESA: '||C6.CODIGO_EMPRESA	||' TIPO_CONTRATO: '||C6.TIPO_CONTRATO||' CODIGO: '||C6.CODIGO|| ' COD_SIT_FUNCIONAL: '||C6.COD_SIT_FUNCIONAL|| ' DATA_INICIO: '||C6.DATA_INICIO||' DATA_FIM: '||C6.DATA_FIM);



--INICIO -------------------------------------IF DE LICENCAS
IF TRUNC(C1.DATA_INI_AFAST) >= TRUNC(C6.DATA_INICIO) AND C6.ORDEM_BM = 1 AND C6.CONTROLE_FOLHA = 'N' AND C6.E_AFASTAMENTO = 'N' AND C6.SUSPENDE_REMUNERA = 'N' --AND C6.PROXIMO_CONTROLE_FOLHA IS NULL
THEN
dbms_output.put_line('');
dbms_output.put_line('--REPROCESSA FICHA POIS ULTIMO REGISTRO SIT FUNC SER ATIVO E TER DATA INICIO IGUAL OU MENOR QUE INICIO DO AFASTAMENTO');
--dbms_output.put_line('EXECUTE PR_ACERTO_REPFICHA_1BM('''||C6.CODIGO_EMPRESA||''','''||C6.TIPO_CONTRATO||''','''||C6.CODIGO||''', TO_DATE('''||C1.DATA_INI_AFAST||''',''DD/MM/YYYY''), TO_DATE('''||C1.DATA_FIM_AFAST||''',''DD/MM/YYYY''));');
--COMENTADO EM 27/12/23--PR_ACERTO_REPFICHA_1BM(C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO, TO_DATE(C1.DATA_INI_AFAST,'DD/MM/YYYY'), TO_DATE(C1.DATA_FIM_AFAST,'DD/MM/YYYY'));
PR_REPROCESSA_FICHA_PERICIA (C6.CODIGO_EMPRESA, C1.CODIGO_PESSOA, TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY'), C1.OCORRENCIA);--NOVO EM 27/12/23

dbms_output.put_line('');

ELSIF 
C6.CONTROLE_FOLHA = 'L' AND C6.E_AFASTAMENTO = 'S' 
AND C6.PROXIMO_CONTROLE_FOLHA = 'L' AND C6.PROXIMO_E_AFASTAMENTO = 'S' 
AND C6.ORDEM_BM = 1 
AND C6.COD_SIT_FUNCIONAL = C6.PROXIMO_COD_SIT_FUNCIONAL--NOVO 20/12/21
--AND C6.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha') AND C6.PROXIMO_LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
AND C6.SF_TEG1 IS NOT NULL
THEN
vULTIMO_REG_E_LICENCA := 'S';
vDATA_INICIO_MAIS_RECENTE_L := C6.DATA_INICIO;
vDATA_FIM_MAIS_RECENTE_L := C6.DATA_FIM;
vPROXIMA_SITUACAO := C6.PROXIMA_SITUACAO;
vQTD_SIT_FUNC_SEQUENCIAIS := 1;
vQTD_DIAS_SIT_FUNC := C6.QTD_DIAS_SIT_FUNC;
dbms_output.put_line('--vQTD_SIT_FUNC_SEQUENCIAIS: '||vQTD_SIT_FUNC_SEQUENCIAIS);
dbms_output.put_line('--*********1-ULTIMO REG. ALT SIT FUNC LICENCA, SEQUENCIAL COM OUTRO LICENCA (PRIMEIRO SENDO O ULTIMO DO HISTORICO). vULTIMO_REG_E_LICENCA: '||vULTIMO_REG_E_LICENCA ||' vDATA_INICIO_MAIS_RECENTE_L: '||vDATA_INICIO_MAIS_RECENTE_L|| ' vDATA_FIM_MAIS_RECENTE_L: '||vDATA_FIM_MAIS_RECENTE_L|| ' vPROXIMA_SITUACAO: '||vPROXIMA_SITUACAO);

ELSIF
C6.CONTROLE_FOLHA = 'L' AND C6.E_AFASTAMENTO = 'S' 
AND C6.PROXIMO_CONTROLE_FOLHA = 'L' AND C6.PROXIMO_E_AFASTAMENTO = 'S' 
AND C6.ORDEM_BM <> 1 AND vDATA_INICIO_MAIS_RECENTE_L IS NULL
AND C6.COD_SIT_FUNCIONAL = C6.PROXIMO_COD_SIT_FUNCIONAL--NOVO 20/12/21
--AND C6.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha') AND C6.PROXIMO_LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
AND C6.SF_TEG1 IS NOT NULL
THEN
vULTIMO_REG_E_LICENCA := 'N';
vDATA_INICIO_MAIS_RECENTE_L := C6.DATA_INICIO;
vDATA_FIM_MAIS_RECENTE_L := C6.DATA_FIM;
vPROXIMA_SITUACAO := C6.PROXIMA_SITUACAO;
vQTD_SIT_FUNC_SEQUENCIAIS := 1;
vQTD_DIAS_SIT_FUNC := C6.QTD_DIAS_SIT_FUNC;
dbms_output.put_line('--vQTD_SIT_FUNC_SEQUENCIAIS: '||vQTD_SIT_FUNC_SEQUENCIAIS);
dbms_output.put_line('--*********1-REG. ALT SIT FUNC LICENCA, SEQUENCIAL COM OUTRO LICENCA (PRIMEIRO NAO SENDO O ULTIMO DO HISTORICO). vULTIMO_REG_E_LICENCA: '||vULTIMO_REG_E_LICENCA ||' vDATA_INICIO_MAIS_RECENTE_L: '||vDATA_INICIO_MAIS_RECENTE_L|| ' vDATA_FIM_MAIS_RECENTE_L: '||vDATA_FIM_MAIS_RECENTE_L|| ' vPROXIMA_SITUACAO: '||vPROXIMA_SITUACAO);

ELSIF
C6.CONTROLE_FOLHA = 'L' AND C6.E_AFASTAMENTO = 'S' 
AND C6.PROXIMO_CONTROLE_FOLHA = 'L' AND C6.PROXIMO_E_AFASTAMENTO = 'S' 
AND C6.ORDEM_BM <> 1 AND vDATA_INICIO_MAIS_RECENTE_L IS NOT NULL
AND C6.COD_SIT_FUNCIONAL = C6.PROXIMO_COD_SIT_FUNCIONAL--NOVO 20/12/21
--AND C6.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha') AND C6.PROXIMO_LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
AND C6.SF_TEG1 IS NOT NULL
THEN
vQTD_SIT_FUNC_SEQUENCIAIS :=  vQTD_SIT_FUNC_SEQUENCIAIS + 1;
vQTD_DIAS_SIT_FUNC := vQTD_DIAS_SIT_FUNC + C6.QTD_DIAS_SIT_FUNC;
dbms_output.put_line('--vQTD_SIT_FUNC_SEQUENCIAIS: '||vQTD_SIT_FUNC_SEQUENCIAIS);
dbms_output.put_line('--*********2-REG. ALT SIT FUNC LICENCA SEQUENCIAL COM OUTRO LICENCA (NO MEIO). vULTIMO_REG_E_LICENCA: '||vULTIMO_REG_E_LICENCA ||' vDATA_INICIO_MAIS_RECENTE_L: '||vDATA_INICIO_MAIS_RECENTE_L|| ' vDATA_FIM_MAIS_RECENTE_L: '||vDATA_FIM_MAIS_RECENTE_L);

ELSIF
C6.CONTROLE_FOLHA = 'L' AND C6.E_AFASTAMENTO = 'S' 
AND 
  (
  ((C6.PROXIMO_CONTROLE_FOLHA = 'L' AND C6.PROXIMO_E_AFASTAMENTO = 'S' AND C6.COD_SIT_FUNCIONAL <> C6.PROXIMO_COD_SIT_FUNCIONAL) 
    OR  (C6.PROXIMO_CONTROLE_FOLHA <> 'L' OR C6.PROXIMO_E_AFASTAMENTO <> 'S' ))
  OR C6.PROXIMO_CONTROLE_FOLHA IS NULL
  )
AND C6.ORDEM_BM <> 1 AND vDATA_INICIO_MAIS_RECENTE_L IS NOT NULL
AND vQTD_SIT_FUNC_SEQUENCIAIS >= 1 --NOVO 20/12/21
--AND C6.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha') AND C6.PROXIMO_LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
THEN
vDATA_INICIO_MAIS_ANTIGO_L := C6.DATA_INICIO;
--COMENTADO 20/12/21--vQTD_SIT_FUNC_SEQUENCIAIS :=  vQTD_SIT_FUNC_SEQUENCIAIS + 1;
dbms_output.put_line('--*********3-REG. ALT SIT FUNC LICENCA SEQUENCIAL COM OUTRO LICENCA (ULTIMO). vULTIMO_REG_E_LICENCA: '||vULTIMO_REG_E_LICENCA ||' vDATA_INICIO_MAIS_ANTIGO_L: '||vDATA_INICIO_MAIS_ANTIGO_L);

dbms_output.put_line('--****ATENCAO**** NESTE MOMENTO AJUSTAR O HISTORICO E LIMPAR AS VARIAVEIS,MAS DEVE AVALIAR SE A SEQUENCIA SER A ULTIMA NO HISTORICO OU NO MEIO DEVIDO A DATA FIM DA LICENCA');
dbms_output.put_line('--C6.COD_SIT_FUNCIONAL: '||C6.COD_SIT_FUNCIONAL|| ' vULTIMO_REG_E_LICENCA: '||vULTIMO_REG_E_LICENCA ||' vDATA_INICIO_MAIS_RECENTE_L: '||vDATA_INICIO_MAIS_RECENTE_L||' vDATA_INICIO_MAIS_ANTIGO_L: '||vDATA_INICIO_MAIS_ANTIGO_L || ' vDATA_FIM_MAIS_RECENTE_L: '||vDATA_FIM_MAIS_RECENTE_L);
dbms_output.put_line('');

vQTD_SIT_FUNC_SEQUENCIAIS := vQTD_SIT_FUNC_SEQUENCIAIS +1; --novo em 20/12/21 14h43
vQTD_DIAS_SIT_FUNC := vQTD_DIAS_SIT_FUNC + C6.QTD_DIAS_SIT_FUNC;

--SABER SE A LICENCA ESTA NA TABELA TEG1
SELECT 
--CASE WHEN COUNT(X2.CODIGO_EMPRESA)= 1 THEN 'S' ELSE 'N' END INTO vTEM_FICHA_PERIODO
COUNT(X2.CODIGO_EMPRESA) , SUM(QTD_DIAS)
INTO vQTD_FICHAS_SEQUENCIAIS, vQTD_DIAS_FICHA 
FROM(
SELECT F.CODIGO_EMPRESA, F.CODIGO_PESSOA, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, F.DATA_INI_AFAST, F.DATA_FIM_AFAST, TRUNC(F.DATA_FIM_AFAST)-TRUNC(F.DATA_INI_AFAST) QTD_DIAS
, P.CODIGO_PROC_MED, M.VINCULO
FROM RHMEDI_FICHA_MED F
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO P ON F.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND F.CODIGO_PESSOA = P.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = P.DT_REG_OCORRENCIA AND F.OCORRENCIA = P.OCORRENCIA
LEFT OUTER JOIN RHPESS_CONTRATO M ON M.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND M.TIPO_CONTRATO = F.TIPO_CONTRATO AND M.CODIGO = F.CODIGO_CONTRATO 
LEFT OUTER JOIN (
        SELECT SUBSTR(X.DADO_DESTINO,1,4)SF, COUNT(1)QTD ,
      S.DESCRICAO, S.CONTROLE_FOLHA, S.SUSPENDE_REMUNERA, S.E_AFASTAMENTO
      FROM RHINTE_ED_IT_CONV X 
    LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = SUBSTR(X.DADO_DESTINO,1,4)
    where X.codigo_CONVERSAO ='TEG1' GROUP BY SUBSTR(X.DADO_DESTINO,1,4)
    ,S.DESCRICAO, S.CONTROLE_FOLHA, S.SUSPENDE_REMUNERA, S.E_AFASTAMENTO
)T ON T.SF= C6.COD_SIT_FUNCIONAL--'1005'---TROCAR PELO C6.COD_SIT_FUNCIONAL
WHERE 
M.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = M.TIPO_CONTRATO AND AUX.CODIGO = M.CODIGO) 
AND F.CODIGO_EMPRESA = C6.CODIGO_EMPRESA--'0001' ---TROCAR PELO C6.CODIGO_EMPRESA
AND F.CODIGO_PESSOA = C6.CODIGO_PESSOA--'000000000883291' ---TROCAR PELO C6.CODIGO_PESSOA
AND F.CODIGO_CONTRATO = C6.CODIGO -- NOVO EM 20/12/21 14H49
AND 
(TRUNC(F.DATA_INI_AFAST) BETWEEN TRUNC(vDATA_INICIO_MAIS_ANTIGO_L) AND TRUNC(vDATA_FIM_MAIS_RECENTE_L)--TO_DATE('10/04/2021','DD/MM/YYYY') AND TO_DATE('13/04/2021','DD/MM/YYYY')
OR
TRUNC(F.DATA_FIM_AFAST) BETWEEN TRUNC(vDATA_INICIO_MAIS_ANTIGO_L) AND TRUNC(vDATA_FIM_MAIS_RECENTE_L)--TO_DATE('10/04/2021','DD/MM/YYYY') AND TO_DATE('13/04/2021','DD/MM/YYYY')
)
--AND F.LOGIN_USUARIO IN ('pb003374_via_imp_teg','pb003374_via_imp_ficha','pr114641_via_imp_ficha')
)X2;
dbms_output.put_line('--vQTD_SIT_FUNC_SEQUENCIAIS: '||vQTD_SIT_FUNC_SEQUENCIAIS|| ' vQTD_FICHAS_SEQUENCIAIS: '||vQTD_FICHAS_SEQUENCIAIS);
dbms_output.put_line('--vQTD_DIAS_SIT_FUNC: '||vQTD_DIAS_SIT_FUNC||' vQTD_DIAS_FICHA: '||vQTD_DIAS_FICHA);


--DEFINI SE SAO MESMA QUANTIDADE REGISTROS DE FICHAS E SIT FUNC NO PERIODO SEQUENCIAL
IF vQTD_FICHAS_SEQUENCIAIS = vQTD_SIT_FUNC_SEQUENCIAIS AND vQTD_DIAS_SIT_FUNC = vQTD_DIAS_FICHA THEN 
vTEM_FICHA_PERIODO := 'N';--DESFIZ NA MESMA DATA INVERTIR N para S em 20/12/21
ELSE
vTEM_FICHA_PERIODO := 'S';--DESFIZ NA MESMA DATA INVERTIR S para N em 20/12/21
END IF;
dbms_output.put_line('--vTEM_FICHA_PERIODO: '||vTEM_FICHA_PERIODO);

--GRAVAR O AJUSTE FINAL
IF vTEM_FICHA_PERIODO = 'S' THEN
BEGIN--BEGIN EXCEPTION
dbms_output.put_line('--DELETA E CRIA ALT SIT FUNC CODIGO SITUACAO: '||C6.COD_SIT_FUNCIONAL|| ' E DATA INICIO ENTRE TRUNC(vDATA_INICIO_MAIS_ANTIGO_L): '|| TRUNC(vDATA_INICIO_MAIS_ANTIGO_L)|| ' TRUNC(vDATA_FIM_MAIS_RECENTE_L): '||TRUNC(vDATA_FIM_MAIS_RECENTE_L)|| ' vPROXIMA_SITUACAO: '||vPROXIMA_SITUACAO);
--DELETE RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C6.CODIGO_EMPRESA AND  TIPO_CONTRATO = C6.TIPO_CONTRATO AND  CODIGO = C6.CODIGO AND COD_SIT_FUNCIONAL = C6.COD_SIT_FUNCIONAL AND TRUNC(DATA_INIC_SITUACAO)BETWEEN TRUNC(vDATA_INICIO_MAIS_ANTIGO_L) AND TRUNC(vDATA_INICIO_MAIS_RECENTE_L); COMMIT;
--dbms_output.put_line('DELETE RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = '''||C6.CODIGO_EMPRESA||''' AND  TIPO_CONTRATO = '''|| C6.TIPO_CONTRATO||''' AND  CODIGO = '''|| C6.CODIGO ||''' AND COD_SIT_FUNCIONAL = '''|| C6.COD_SIT_FUNCIONAL||''' AND TRUNC(DATA_INIC_SITUACAO)BETWEEN TO_DATE('''|| vDATA_INICIO_MAIS_ANTIGO_L||''',''DD/MM/YYYY'') AND TO_DATE('''|| vDATA_INICIO_MAIS_RECENTE_L||''',''DD/MM/YYYY''); COMMIT;');
DELETE RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C6.CODIGO_EMPRESA AND TIPO_CONTRATO = C6.TIPO_CONTRATO AND  CODIGO = C6.CODIGO AND COD_SIT_FUNCIONAL = C6.COD_SIT_FUNCIONAL AND TRUNC(DATA_INIC_SITUACAO)BETWEEN TO_DATE(vDATA_INICIO_MAIS_ANTIGO_L,'DD/MM/YYYY') AND TO_DATE(vDATA_INICIO_MAIS_RECENTE_L,'DD/MM/YYYY'); COMMIT;
--dbms_output.put_line('DELETE RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = '''||C6.CODIGO_EMPRESA||''' AND  TIPO_CONTRATO = '''|| C6.TIPO_CONTRATO||''' AND  CODIGO = '''|| C6.CODIGO ||''' AND COD_SIT_FUNCIONAL = '''|| V_SIT_FUNC_ATIVA_VINCULO||''' AND TRUNC(DATA_INIC_SITUACAO)BETWEEN TO_DATE('''|| vDATA_INICIO_MAIS_ANTIGO_L||''',''DD/MM/YYYY'') AND TO_DATE('''|| vDATA_INICIO_MAIS_RECENTE_L||''',''DD/MM/YYYY''); COMMIT;');
DELETE RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C6.CODIGO_EMPRESA AND  TIPO_CONTRATO = C6.TIPO_CONTRATO AND  CODIGO = C6.CODIGO AND COD_SIT_FUNCIONAL = V_SIT_FUNC_ATIVA_VINCULO AND TRUNC(DATA_INIC_SITUACAO)BETWEEN TO_DATE(vDATA_INICIO_MAIS_ANTIGO_L,'DD/MM/YYYY') AND TO_DATE(vDATA_INICIO_MAIS_RECENTE_L,'DD/MM/YYYY'); COMMIT;
--INSERT INTO RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, PROXIMA_SITUACAO)VALUES ('N', C6.CODIGO_EMPRESA, C6.TIPO_CONTRATO, C6.CODIGO, TRUNC(vDATA_INICIO_MAIS_ANTIGO_L), TRUNC(vDATA_FIM_MAIS_RECENTE_L), C6.COD_SIT_FUNCIONAL, 'AJUSTE_ATIVO_SEQUENCIA', SYSDATE, vPROXIMA_SITUACAO);COMMIT;
--COMENTADO 21/12/21 PARA GERAR NOVO AFASTAMENTO--dbms_output.put_line('INSERT INTO RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, PROXIMA_SITUACAO)VALUES (''N'','''|| C6.CODIGO_EMPRESA||''','''||C6.TIPO_CONTRATO||''','''||C6.CODIGO||''',TO_DATE('''|| vDATA_INICIO_MAIS_ANTIGO_L||''',''DD/MM/YYYY''), TO_DATE('''||vDATA_FIM_MAIS_RECENTE_L||''',''DD/MM/YYYY''),'''|| C6.COD_SIT_FUNCIONAL||''', ''AJUSTE_LICENCA_SEQUENCIA'', SYSDATE,'''||vPROXIMA_SITUACAO||''');COMMIT;');
--dbms_output.put_line('INSERT INTO RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA)VALUES (''N'','''|| C6.CODIGO_EMPRESA||''','''||C6.TIPO_CONTRATO||''','''||C6.CODIGO||''',TO_DATE('''|| vDATA_INICIO_MAIS_ANTIGO_L||''',''DD/MM/YYYY''), TO_DATE('''||vDATA_FIM_MAIS_RECENTE_L||''',''DD/MM/YYYY''),'''|| V_SIT_FUNC_ATIVA_VINCULO ||''', ''AJUSTE_LICENCA_SEQUENCIA'', SYSDATE);COMMIT;');
INSERT INTO RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA)VALUES ('N',C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO,TO_DATE(vDATA_INICIO_MAIS_ANTIGO_L,'DD/MM/YYYY'), TO_DATE(vDATA_FIM_MAIS_RECENTE_L,'DD/MM/YYYY'),V_SIT_FUNC_ATIVA_VINCULO, 'AJUSTE_LICENCA_SEQUENCIA', SYSDATE);COMMIT;
--PR_SUGESP_REPFICHAS_SANEAMENTO  (C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO);
--dbms_output.put_line('EXECUTE PR_ACERTO_SEQ_ATIVO_1BM('''||C6.CODIGO_EMPRESA||''','''||C6.TIPO_CONTRATO||''','''||C6.CODIGO||''');');
--dbms_output.put_line('EXECUTE PR_ACERTO_REPFICHA_1BM('''||C6.CODIGO_EMPRESA||''','''||C6.TIPO_CONTRATO||''','''||C6.CODIGO||''', TO_DATE('''||vDATA_INICIO_MAIS_ANTIGO_L||''',''DD/MM/YYYY''), TO_DATE('''||vDATA_FIM_MAIS_RECENTE_L||''',''DD/MM/YYYY''));');
--COMENTADO EM 27/12/23--PR_ACERTO_REPFICHA_1BM(C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO, TO_DATE(vDATA_INICIO_MAIS_ANTIGO_L,'DD/MM/YYYY'), TO_DATE(vDATA_FIM_MAIS_RECENTE_L,'DD/MM/YYYY'));
PR_REPROCESSA_FICHA_PERICIA (C6.CODIGO_EMPRESA, C1.CODIGO_PESSOA, TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY'), C1.OCORRENCIA);--NOVO EM 27/12/23

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_1, CAMPO_VALOR_2, DATA_DADOS, CONSIDERACOES)
VALUES(C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO,'LOG EXECUCAO PROCEDURE PR_ACERTO_TEG_SIT_FUNC','PARTE_1_PROCESSAMENTO',SYSDATE, 
'DELETA E CRIA ALT SIT FUNC CODIGO SITUACAO: '||C6.COD_SIT_FUNCIONAL|| ' E DATA INICIO ENTRE TRUNC(vDATA_INICIO_MAIS_ANTIGO_L): '|| TRUNC(vDATA_INICIO_MAIS_ANTIGO_L)|| ' TRUNC(vDATA_FIM_MAIS_RECENTE_L): '||TRUNC(vDATA_FIM_MAIS_RECENTE_L)|| ' vPROXIMA_SITUACAO: '||vPROXIMA_SITUACAO
||' EXECUTA PR_REPROCESSA_FICHA_PERICIA('||C6.CODIGO_EMPRESA||','||C6.TIPO_CONTRATO||','||C6.CODIGO||','|| TO_DATE(vDATA_INICIO_MAIS_ANTIGO_L,'DD/MM/YYYY')||','|| TO_DATE(vDATA_FIM_MAIS_RECENTE_L,'DD/MM/YYYY')
);COMMIT;
dbms_output.put_line('');

EXCEPTION WHEN OTHERS THEN
err_msg := SQLCODE||' '||SUBSTR(SQLERRM, 1, 4000);
dbms_output.put_line('err_msg:' ||err_msg);

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_1, CAMPO_VALOR_2, DATA_DADOS, CONSIDERACOES)
VALUES(C6.CODIGO_EMPRESA,C6.TIPO_CONTRATO,C6.CODIGO,'LOG EXECUCAO PROCEDURE PR_ACERTO_TEG_SIT_FUNC','PARTE_1_EXCEPTION', SYSDATE, err_msg
);COMMIT;

END;--BEGIN EXCEPTION
END IF; 
--AJUSTAR AS LICENCAS
--LIMPAR VARIAVEIS PARA PROXIMO GRUPO DE LICENCAS NO MESMO BM, MUDEI DE LUGAR 20/12/21 14H12
vULTIMO_REG_E_LICENCA := 'N';---novo em 25/10/21
vDATA_INICIO_MAIS_RECENTE_L := NULL;--novo em 25/10/21
vDATA_INICIO_MAIS_ANTIGO_L := NULL;---novo em 25/10/21
vDATA_FIM_MAIS_RECENTE_L := NULL;---novo em 25/10/21
vPROXIMA_SITUACAO := NULL;
vTEM_FICHA_PERIODO := NULL; 
vQTD_FICHAS_SEQUENCIAIS := 0;--NOVO EM 26/10/21
vQTD_SIT_FUNC_SEQUENCIAIS := 0;--NOVO EM 26/10/21

vQTD_DIAS_FICHA := 0;
vQTD_DIAS_SIT_FUNC := 0;

ELSE -- NOVO EM 20/12/21 14H32
dbms_output.put_line('--ELSE -- LIMPAR VARIAVEIS PARA PROXIMO GRUPO DE LICENCAS NO MESMO BM');
--LIMPAR VARIAVEIS PARA PROXIMO GRUPO DE LICENCAS NO MESMO BM, MUDEI DE LUGAR 20/12/21 14H12
vULTIMO_REG_E_LICENCA := 'N';---novo em 25/10/21
vDATA_INICIO_MAIS_RECENTE_L := NULL;--novo em 25/10/21
vDATA_INICIO_MAIS_ANTIGO_L := NULL;---novo em 25/10/21
vDATA_FIM_MAIS_RECENTE_L := NULL;---novo em 25/10/21
vPROXIMA_SITUACAO := NULL;
vTEM_FICHA_PERIODO := NULL; 
vQTD_FICHAS_SEQUENCIAIS := 0;--NOVO EM 26/10/21
vQTD_SIT_FUNC_SEQUENCIAIS := 0;--NOVO EM 26/10/21

vQTD_DIAS_FICHA := 0;
vQTD_DIAS_SIT_FUNC := 0;

END IF;--GERAL
--FIM------------------------------------------IF LICENCAS



END LOOP;---FIM C6
--FIM ------------novo EM 20/12/21-- pego da HOMOLOGA_EXADATA PROCEDURE ------------------------------------------------------------------------------------------------------------------------------



dbms_output.put_line('------------FIM DE 1 BM');
vCONTADOR := 0;
--LIMPAR VARIAVEIS PARA PROXIMO BM --NOVO EM 20/12/21
vULTIMO_REG_E_LICENCA := 'N';---novo em 25/10/21
vDATA_INICIO_MAIS_RECENTE_L := NULL;--novo em 25/10/21
vDATA_INICIO_MAIS_ANTIGO_L := NULL;---novo em 25/10/21
vDATA_FIM_MAIS_RECENTE_L := NULL;---novo em 25/10/21
vPROXIMA_SITUACAO := NULL;
vTEM_FICHA_PERIODO := NULL; 
vQTD_FICHAS_SEQUENCIAIS := 0;--NOVO EM 26/10/21
vQTD_SIT_FUNC_SEQUENCIAIS := 0;--NOVO EM 26/10/21

--V_ULT_SIT_FUNC0_ATIVA := NULL;
vQTD_DIAS_FICHA := 0;
vQTD_DIAS_SIT_FUNC := 0;

V_SIT_FUNC_ATIVA_VINCULO := NULL;

END IF; ---NAO REPROCESSAR SE PESSOA DE FERAS --NOVO EM 4/1/22

END LOOP; --FIM C1. BUSCAR REGISTROS NA LOG ALT SIT FUNC


--FIM--------------------------------------------------------------------------------------------------------------------AJUSTES 2--- SEQUENCIA DE SITUACOES DE LICENCA VINDO DE FICHA MEIDCA UNINDO AS MESMAS EM UMA SO REGISTRO ALT SIT FUNC----------------


--INICIO------------------------------GRAVAR RELATORIO DOS REGISTROS GRAVADOS COM A ANALISE DO DIA-------------------------------------------------------------------------------------------------------------------------
INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST( CAMPO_VALOR_1, CAMPO_VALOR_2, DATA_DADOS, CONSIDERACOES)
VALUES('LOG EXECUCAO PROCEDURE PR_ACERTO_TEG_SIT_FUNC','PARTE_2_RELATORIO', SYSDATE, 
'|CENARIO|QTD_DIAS_FICHA|QTD_DIAS_SF_PARCIAL|QTD_DIAS_FERIAS_NA_FICHA|DUPLICIDADE_RELATORIO_FICHA|MOTIVO|STATUS_REGISTRO|DADOS_FICHA_MEDICA|DT_ALTER_FICHA|ORDEM_NA_FICHA|CODIGO_EMPRESA|TIPO_CONTRATO|CODIGO_CONTRATO|CODIGO_PESSOA|DT_REG_OCORRENCIA|OCORRENCIA|NATUREZA_EXAME|PROCEDIMENTO|CODIGO_PROC_MED|CONDUTA|VINCULO|COD_SIT_FUNC_DEFERIDA|SITUACAO_PONTO|SFF_CONTROLE_FOLHA|SFF_E_AFASTAMENTO|SFF_SUSPENDE_REMUNERA|COD_SIT_FUNC_DOENCA_GRAVE|SIT_PONTO_DOENCA_GRAVE|DATA_INI_AFAST|DATA_FIM_AFAST|LOGIN_USUARIO|DT_ULT_ALTER_USUA|COD_DOENCA|DADOS_ALT_SIT_FUNC|DT_ALTER_SIT_FUNC|ORDEM_NA_SIT_FUNC|CODIGO_EMPRESA_S|TIPO_CONTRATO_S|CODIGO_S|DATA_INIC_SITUACAO|COD_SIT_FUNCIONAL|DATA_FIM_SITUACAO|PROXIMA_SITUACAO|LOGIN_USUARIO_S|DT_ULT_ALTER_USUA_S|CODIGO_DOENCA_S|DADOS_ULT_ASF|CODIGO_EMPRESA_A|TIPO_CONTRATO_A|CODIGO_A|COD_SIT_FUNCIONAL_A|ULT_ASF_DESC_SIT_FUNC|ULT_ASF_CONTROLE_FOLHA|ULT_ASF_E_AFASTAMENTO|ULT_ASF_SUSPENDE_REMUNERA|ULT_ASF_SO_PONTO|DATA_INIC_SITUACAO_A|DATA_FIM_SITUACAO_A|PROXIMA_SITUACAO_A|LOGIN_USUARIO_A|DT_ULT_ALTER_USUA_A|DADOS_FERIAS|CODIGO_EMPRESA_F|TIPO_CONTRATO_F|CODIGO_CONTRATO_F|TIPO_FERIAS|DT_INI_AQUISICAO|PERIODO|CONTROLE_FOLHA_F|E_AFASTAMENTO_F|COD_SIT_PONTO_F|SUSPENDE_REMUNERA_F|SO_GERA_SIT_PONTO_F|DATA_INICIO_FERIAS|DATA_FIM_FERIAS|DADOS_ALT_SIT_FUNC_PARCIAL|CODIGO_EMPRESA_SFP|TIPO_CONTRATO_SFP|CODIGO_CONTRATO_SFP|COD_SIT_FUNCIONAL_SFP|SFP_DESC_SIT_FUNC|DATA_INIC_SITUACAO_SFP|DATA_FIM_SITUACAO_SFP|CONTROLE_FOLHA_SFP|E_AFASTAMENTO_SFP|SUSPENDE_REMUNERA_SFP|SO_PONTO_SFP'
);COMMIT;



FOR C2 IN (
--AJUSTES EVOLUINDO EM 21/12/21
SELECT 
CASE 
WHEN X3.MOTIVO = 'OK' THEN 'CENARIO_OK'
WHEN X3.MOTIVO IN ('AFASTAMENTO_INSS_NAO_GERA_SIT_FUNC_IMEDIATAMENTE','PESSOA_EM_SIT_FUNC_QUE_NAO_PODE_ALTERAR','PESSOA_EM_SIT_FUNC_QUE_CAMPO_SO_GERA_PONTO_INDEFINIDO') THEN 'A_PRINCIPIO_OK'
WHEN X3.MOTIVO IN('AVALIAR_MOTIVO_AINDA','NAO_MAPEADO_AINDA') AND X3.QTD_DIAS_FICHA = (X3.QTD_DIAS_SF_PARCIAL + X3.QTD_DIAS_FERIAS_NA_FICHA) THEN 'FERIAS_COMECOU_ANTES_OK_SIT_FUNC'
WHEN TRUNC(X3.DATA_INI_AFAST) > TRUNC(SYSDATE) THEN 'FICHA_SERA_PROCESSADA_NO_DIA_INICIO_AFASTAMENTO'
WHEN X3.DATA_INI_AFAST IS NOT NULL AND X3.DT_ALTER_SIT_FUNC IS NULL THEN 'SEM_HISTORICO_ALT_SIT_FUNC_NO_PERIODO_DA_FICHA'
WHEN X3.CODIGO_PROC_MED = '000000000000036' THEN 'OK_FICHA_APOSENTADORIA_PREVIA'
ELSE 'NAO_MAPEADO_CENARIO'
END CENARIO,
X3.*
FROM (
SELECT 
TRUNC(X2.DATA_FIM_AFAST) - TRUNC(X2.DATA_INI_AFAST) +1 AS QTD_DIAS_FICHA,
CASE WHEN X2.DATA_FIM_SITUACAO_SFP IS NULL OR X2.DATA_INIC_SITUACAO_SFP IS NULL THEN 0 ELSE TRUNC(X2.DATA_FIM_SITUACAO_SFP) - TRUNC(X2.DATA_INIC_SITUACAO_SFP) +1 END QTD_DIAS_SF_PARCIAL,
CASE
WHEN TRUNC(X2.DATA_INI_AFAST) > TRUNC(DATA_INICIO_FERIAS) AND TRUNC(X2.DATA_FIM_AFAST) <= TRUNC(DATA_FIM_FERIAS) THEN TRUNC(X2.DATA_FIM_AFAST) - TRUNC(X2.DATA_INI_AFAST) +1 --FERIAS COMECOU ANTES DO INICIO DO AFASTAMENTO E ACABOU NO DIA OU DEPOIS DO AFASTAMENTO, ENTAO TODO PERIODO DO AFASTAMENTO NAO DEVE GRAVAR SIT FUNC
--WHEN TRUNC(X2.DATA_INI_AFAST) > TRUNC(DATA_INICIO_FERIAS) AND TRUNC(X2.DATA_FIM_AFAST) >  TRUNC(DATA_FIM_FERIAS) THEN TRUNC(X2.DATA_FIM_AFAST) - TRUNC(DATA_FIM_FERIAS)  --FERIAS COMECOU ANTES DO INICIO DO AFASTAMENTO E ACABOU ANTES DO AFASTAMENTO, ENTAO DEVE GRAVAR PARCIAL SIT FUNC DEPOIS DO FIM DAS FERIAS
WHEN TRUNC(X2.DATA_INI_AFAST) > TRUNC(DATA_INICIO_FERIAS) AND TRUNC(X2.DATA_FIM_AFAST) >  TRUNC(DATA_FIM_FERIAS) THEN TRUNC(DATA_FIM_FERIAS) - TRUNC(X2.DATA_INI_AFAST) +1 --FERIAS COMECOU ANTES DO INICIO DO AFASTAMENTO E ACABOU ANTES DO AFASTAMENTO, ENTAO DEVE GRAVAR PARCIAL SIT FUNC DEPOIS DO FIM DAS FERIAS
WHEN TRUNC(X2.DATA_INI_AFAST) <= TRUNC(DATA_INICIO_FERIAS) THEN 0 --FERIAS COMECOU DEPOIS DO AFASTAMENTO VALE TODO O AFASTAMENTO E CANCELA AS FERIAS
ELSE 0
END QTD_DIAS_FERIAS_NA_FICHA,
ROW_NUMBER()OVER(PARTITION BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, X2.DT_REG_OCORRENCIA, X2.OCORRENCIA ORDER BY X2.DATA_INIC_SITUACAO_SFP)AS DUPLICIDADE_RELATORIO_FICHA,
CASE
WHEN X2.STATUS_REGISTRO = 'OK' THEN 'OK'
WHEN X2.STATUS_REGISTRO = 'VERIFICAR SIT FUNC DIFERENTES' THEN 'AVALIAR_MOTIVO_AINDA'
WHEN X2.STATUS_REGISTRO = 'VERIFICAR' AND X2.SFF_CONTROLE_FOLHA = 'N' AND X2.SFF_E_AFASTAMENTO = 'S' AND X2.SFF_SUSPENDE_REMUNERA = 'S' THEN 'AFASTAMENTO_INSS_NAO_GERA_SIT_FUNC_IMEDIATAMENTE'
WHEN X2.STATUS_REGISTRO = 'VERIFICAR' AND X2.ULT_ASF_SO_PONTO = 1 THEN 'PESSOA_EM_SIT_FUNC_QUE_NAO_PODE_ALTERAR'
WHEN X2.STATUS_REGISTRO = 'VERIFICAR' AND X2.ULT_ASF_SO_PONTO = 0 THEN 'PESSOA_EM_SIT_FUNC_QUE_CAMPO_SO_GERA_PONTO_INDEFINIDO'
ELSE 'NAO_MAPEADO_AINDA' END
MOTIVO,
X2.* FROM(
-------------------------------------novo em 18/10/21 --conferindo se deu certo na ALT SIT FUNC----analitico 
SELECT 
CASE 
WHEN X.COD_SIT_FUNCIONAL IS NULL AND TEG1.COD_SIT_FUNC_DEFERIDA IS NOT NULL THEN 'VERIFICAR' 
WHEN X.COD_SIT_FUNCIONAL IS NOT NULL AND TEG1.COD_SIT_FUNC_DEFERIDA IS NOT NULL AND (X.COD_SIT_FUNCIONAL <> TEG1.COD_SIT_FUNC_DEFERIDA AND X.COD_SIT_FUNCIONAL <> TEG1.COD_SIT_FUNC_DOENCA_GRAVE)  THEN 'VERIFICAR SIT FUNC DIFERENTES' 
ELSE 'OK' END STATUS_REGISTRO,
--CASE WHEN X.COD_SIT_FUNCIONAL <> TEG1.COD_SIT_FUNC_DEFERIDA AND X.COD_SIT_FUNCIONAL <> TEG1.COD_SIT_FUNC_DOENCA_GRAVE THEN 'NAO' ELSE 'SIM' END GEROU_SIT_FUNC_CORRETA,
--X.FICHA_GEROU_SIT_FUNC,
X.DADOS_FICHA_MEDICA, X.DT_ALTER_FICHA, X.ORDEM_NA_FICHA, X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.DT_REG_OCORRENCIA, X.OCORRENCIA,
X.NATUREZA_EXAME, 
X.PROCEDIMENTO,--NOVO EM 5/8/22 
X.CODIGO_PROC_MED,
X.CONDUTA ,--NOVO EM 5/8/22
X.VINCULO,
TEG1.COD_SIT_FUNC_DEFERIDA, SFF.SITUACAO_PONTO,
SFF.CONTROLE_FOLHA SFF_CONTROLE_FOLHA, SFF.E_AFASTAMENTO SFF_E_AFASTAMENTO, SFF.SUSPENDE_REMUNERA  SFF_SUSPENDE_REMUNERA,
TEG1.COD_SIT_FUNC_DOENCA_GRAVE, SFD.SITUACAO_PONTO SIT_PONTO_DOENCA_GRAVE,
X.DATA_INI_AFAST, X.DATA_FIM_AFAST, 
X.LOGIN_USUARIO, X.DT_ULT_ALTER_USUA, X.COD_DOENCA,  

X.DADOS_ALT_SIT_FUNC, X.DT_ALTER_SIT_FUNC, X.ORDEM_NA_SIT_FUNC, X.CODIGO_EMPRESA_S, X.TIPO_CONTRATO_S, X.CODIGO_S, X.DATA_INIC_SITUACAO, X.COD_SIT_FUNCIONAL, X.DATA_FIM_SITUACAO, X.PROXIMA_SITUACAO, 
X.LOGIN_USUARIO_S, X.DT_ULT_ALTER_USUA_S, X.CODIGO_DOENCA_S

,'DADOS_ULT_ASF' DADOS_ULT_ASF, ULT_ASF.*
,'DADOS_FERIAS' DADOS_FERIAS, F.*
,'DADOS_ALT_SIT_FUNC_PARCIAL' DADOS_ALT_SIT_FUNC_PARCIAL , SFP.*
FROM(
SELECT 
--CASE WHEN FM.DATA_INI_AFAST IS NOT NULL AND S.DATA_INIC_SITUACAO IS NOT NULL THEN 'SIM' ELSE 'NAO' END FICHA_GEROU_SIT_FUNC,
'DADOS_FICHA_MEDICA' DADOS_FICHA_MEDICA, to_char(FM.DT_ULT_ALTER_USUA,'DD/MM/YYYY HH24:MI:SS')DT_ALTER_FICHA, FM.*,
'DADOS_ALT_SIT_FUNC' DADOS_ALT_SIT_FUNC, to_char(S.DT_ULT_ALTER_USUA_S,'DD/MM/YYYY HH24:MI:SS')DT_ALTER_SIT_FUNC, S.* 
FROM
(--ALT SIT FUNC
select
ROW_NUMBER()OVER(PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO ORDER BY X.DATA_INIC_SITUACAO DESC)AS ORDEM_NA_SIT_FUNC,
X.CODIGO_EMPRESA CODIGO_EMPRESA_S, X.TIPO_CONTRATO TIPO_CONTRATO_S, X.CODIGO CODIGO_S, X.DATA_INIC_SITUACAO, X.COD_SIT_FUNCIONAL, X.DATA_FIM_SITUACAO, X.PROXIMA_SITUACAO, X.LOGIN_USUARIO LOGIN_USUARIO_S, X.DT_ULT_ALTER_USUA DT_ULT_ALTER_USUA_S, X.CODIGO_DOENCA CODIGO_DOENCA_S
from RHCGED_ALT_SIT_FUN X where LOGIN_USUARIO in('pb003374_via_imp_ficha','pr114641_via_imp_ficha')
--and trunc(dt_ult_alter_usua) = TO_DATE('15/12/2021','DD/MM/YYYY')--trunc(sysdate)-2----------------------------------------TROCA DATA
ORDER BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO,X.DATA_INIC_SITUACAO DESC
)S
FULL OUTER JOIN
(--juntando, ficha, conduta e doenca
SELECT 
FM.ORDEM_NA_FICHA, FM.CODIGO_EMPRESA, FM.TIPO_CONTRATO, FM.CODIGO_CONTRATO,  FM.CODIGO_PESSOA, FM.DT_REG_OCORRENCIA, FM.OCORRENCIA, FM.NATUREZA_EXAME, 
FM.DATA_INI_AFAST, FM.DATA_FIM_AFAST, FM.LOGIN_USUARIO, FM.DT_ULT_ALTER_USUA, 
FM.CODIGO_PROC_MED, FM.COD_DOENCA, FM.VINCULO
,FM.PROCEDIMENTO, FM.CONDUTA --NOVO EM 5/8/22
FROM(
-------------------------------INICIO------------------------ NUCLEO DOS REGISTROS DAS FICHAS PROCESSADAS
select  
ROW_NUMBER()OVER(PARTITION BY F.CODIGO_EMPRESA ,F.CODIGO_PESSOA ,F.DT_REG_OCORRENCIA ,F.OCORRENCIA ORDER BY F.OCORRENCIA)AS ORDEM_NA_FICHA,
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.DT_REG_OCORRENCIA, F.OCORRENCIA, F.NATUREZA_EXAME, 
F.DATA_INI_AFAST, F.DATA_FIM_AFAST,  
P.CODIGO_PROC_MED, D.COD_DOENCA,
F.LOGIN_USUARIO, F.DT_ULT_ALTER_USUA, M.VINCULO
,E.DESCRICAO PROCEDIMENTO, C.DESCRICAO CONDUTA --NOVO EM 5/8/22
from RHMEDI_FICHA_MED F 
LEFT OUTER JOIN RHMEDI_NATUREZA_EX E ON E.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND E.CODIGO = F.NATUREZA_EXAME
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO P ON F.CODIGO_EMPRESA = P.CODIGO_EMPRESA AND F.CODIGO_PESSOA = P.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = P.DT_REG_OCORRENCIA AND F.OCORRENCIA = P.OCORRENCIA
LEFT OUTER JOIN RHMEDI_PROC_MED C ON C.CODIGO_PROC_MED = P.CODIGO_PROC_MED
LEFT OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND F.OCORRENCIA = D.OCORRENCIA
LEFT OUTER JOIN RHPESS_PESSOA PS ON F.CODIGO_EMPRESA = PS.CODIGO_EMPRESA and F.CODIGO_PESSOA = PS.CODIGO
LEFT OUTER JOIN RHPESS_CONTRATO M ON M.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND M.TIPO_CONTRATO = F.TIPO_CONTRATO AND M.CODIGO = F.CODIGO_CONTRATO 
where 
F.CODIGO_EMPRESA = '0001'
AND M.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = M.TIPO_CONTRATO AND AUX.CODIGO = M.CODIGO) 
 AND f.login_usuario in('pb003374_via_imp_ficha','pr114641_via_imp_ficha')  
--and trunc(f.DT_ULT_ALTER_USUA) = trunc(sysdate)-1 --TO_DATE('23/12/2021','DD/MM/YYYY')--TO_DATE('15/12/2021','DD/MM/YYYY')--trunc(sysdate)-2----------------------------------------TROCA DATA*********************************************
and trunc(f.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM 
--BETWEEN TO_DATE('30/12/2021','DD/MM/YYYY') AND TO_DATE('02/01/2022','DD/MM/YYYY')
--and f.codigo_contrato = '000000000715909'--testes
--and f.codigo_contrato in ('000000000486829','000000000733303')
order by F.CODIGO_EMPRESA ,F.CODIGO_PESSOA ,F.DT_REG_OCORRENCIA ,F.OCORRENCIA, P.OCORRENCIA, D.OCOR_DOENCA
-------------------------------FIM------------------------ NUCLEO DOS REGISTROS DAS FICHAS PROCESSADAS
)FM
)FM ON S.CODIGO_EMPRESA_S = FM.CODIGO_EMPRESA AND S.TIPO_CONTRATO_S = FM.TIPO_CONTRATO AND S.CODIGO_S = FM.CODIGO_CONTRATO AND TRUNC(S.DATA_INIC_SITUACAO) = TRUNC(FM.DATA_INI_AFAST) AND TRUNC(S.DATA_FIM_SITUACAO) = TRUNC(FM.DATA_FIM_AFAST)
 ORDER BY S.CODIGO_EMPRESA_S, S.TIPO_CONTRATO_S, S.CODIGO_S, S.DATA_INIC_SITUACAO, FM.CODIGO_EMPRESA, FM.TIPO_CONTRATO, FM.CODIGO_CONTRATO
)X
LEFT OUTER JOIN (SELECT SUBSTR(DADO_ORIGEM,1,4)PROCEDIMENTO, SUBSTR(DADO_ORIGEM,5,15)CONDUTA, SUBSTR(DADO_ORIGEM,20,4)VINCULO, SUBSTR(DADO_DESTINO,1,4)COD_SIT_FUNC_DEFERIDA, SUBSTR(DADO_DESTINO,17,4)COD_SIT_FUNC_DOENCA_GRAVE
FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1' )TEG1 
ON TEG1.PROCEDIMENTO = X.NATUREZA_EXAME AND TEG1.CONDUTA = X.CODIGO_PROC_MED AND TEG1.VINCULO = X.VINCULO
LEFT OUTER JOIN RHPARM_SIT_FUNC SFF ON SFF.CODIGO = TEG1.COD_SIT_FUNC_DEFERIDA
LEFT OUTER JOIN RHPARM_SIT_FUNC SFD ON SFD.CODIGO = TEG1.COD_SIT_FUNC_DOENCA_GRAVE
LEFT OUTER JOIN--ULTIMA ALT SIT FUNC INDEPENDENTE DO CODIGO
(
SELECT
X.CODIGO_EMPRESA CODIGO_EMPRESA_A, X.TIPO_CONTRATO TIPO_CONTRATO_A, X.CODIGO CODIGO_A,  X.COD_SIT_FUNCIONAL COD_SIT_FUNCIONAL_A, S.DESCRICAO ULT_ASF_DESC_SIT_FUNC,
S.CONTROLE_FOLHA ULT_ASF_CONTROLE_FOLHA, S.E_AFASTAMENTO ULT_ASF_E_AFASTAMENTO, S.SUSPENDE_REMUNERA ULT_ASF_SUSPENDE_REMUNERA, S.c_livre_selec02 ULT_ASF_SO_PONTO,
X.DATA_INIC_SITUACAO DATA_INIC_SITUACAO_A, X.DATA_FIM_SITUACAO DATA_FIM_SITUACAO_A, X.PROXIMA_SITUACAO PROXIMA_SITUACAO_A, X.LOGIN_USUARIO LOGIN_USUARIO_A, X.DT_ULT_ALTER_USUA DT_ULT_ALTER_USUA_A 
FROM RHCGED_ALT_SIT_FUN X 
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = X.COD_SIT_FUNCIONAL
where X.DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO) FROM RHCGED_ALT_SIT_FUN AUX WHERE X.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND X.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND X.CODIGO = AUX.CODIGO)
)ULT_ASF ON ULT_ASF.CODIGO_EMPRESA_A = X.CODIGO_EMPRESA AND ULT_ASF.TIPO_CONTRATO_A = X.TIPO_CONTRATO AND ULT_ASF.CODIGO_A = X.CODIGO_CONTRATO

LEFT OUTER JOIN (
SELECT  
F.CODIGO_EMPRESA CODIGO_EMPRESA_F, F.TIPO_CONTRATO TIPO_CONTRATO_F, F.CODIGO_CONTRATO CODIGO_CONTRATO_F,
F.TIPO_FERIAS, F.DT_INI_AQUISICAO, F.PERIODO,
'F' CONTROLE_FOLHA_F, 'N' E_AFASTAMENTO_F, P.SITUACAO_PONTO COD_SIT_PONTO_F,
--NULL PROXIMA_SITUACAO, 0 QTDE_DIAS_PROXIMO,
'N' SUSPENDE_REMUNERA_F, 9 SO_GERA_SIT_PONTO_F,
--P.DESCRICAO SITUACAO_PONTO_F, 'P' TIPO_SITUACAO_F, 
F.DT_INI_GOZO DATA_INICIO_FERIAS, 
CASE
    WHEN F.STATUS_CONFIRMACAO in ('5','D')
    THEN
      (SELECT MAX(DT.DATA_DIA)
      FROM RHFERI_FERIAS FF,
        RHTABS_DATAS DT
      WHERE FF.CODIGO_EMPRESA = F.CODIGO_EMPRESA
      AND FF.TIPO_CONTRATO = F.TIPO_CONTRATO
      AND FF.DT_INI_AQUISICAO = F.DT_INI_AQUISICAO
      AND FF.DT_FIM_AQUISICAO = F.DT_FIM_AQUISICAO
      AND FF.CODIGO_CONTRATO = F.codigo_contrato
      AND DT.DATA_DIA BETWEEN F.DT_INI_GOZO AND F.DT_RETORNO-1
      AND FF.STATUS_CONFIRMACAO =F.STATUS_CONFIRMACAO
      AND DT.DATA_DIA NOT          IN
        (SELECT D.DATA_DIA
        FROM RHPARM_CALEND_DT D
        WHERE D.CODIGO  = '0001'
        AND DT.DATA_DIA = D.DATA_DIA))
        else F.DT_FIM_GOZO
  END
DATA_FIM_FERIAS
FROM RHFERI_FERIAS F
LEFT OUTER JOIN RHPARM_P_FERI P ON P.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND P.CODIGO = F.TIPO_FERIAS
WHERE F.STATUS_CONFIRMACAO in ('1','5','D','G')

)F  ON --FERIAS NO PERIODO DA FICHA
F.CODIGO_EMPRESA_F = X.CODIGO_EMPRESA AND F.TIPO_CONTRATO_F = X.TIPO_CONTRATO AND F.CODIGO_CONTRATO_F = X.CODIGO_CONTRATO
AND
  ((TRUNC(F.DATA_INICIO_FERIAS) >= TRUNC(X.DATA_INI_AFAST) AND TRUNC(F.DATA_INICIO_FERIAS) <= TRUNC(X.DATA_FIM_AFAST))
  OR (TRUNC(F.DATA_INICIO_FERIAS)< TRUNC(X.DATA_INI_AFAST) AND TRUNC(F.DATA_FIM_FERIAS) >= TRUNC(X.DATA_INI_AFAST))
)

LEFT OUTER JOIN
(--ALT SIT FUNC PARCIAL
select
X.CODIGO_EMPRESA CODIGO_EMPRESA_SFP, X.TIPO_CONTRATO TIPO_CONTRATO_SFP, X.CODIGO CODIGO_CONTRATO_SFP, X.COD_SIT_FUNCIONAL COD_SIT_FUNCIONAL_SFP,
S.DESCRICAO SFP_DESC_SIT_FUNC,
X.DATA_INIC_SITUACAO DATA_INIC_SITUACAO_SFP,  X.DATA_FIM_SITUACAO DATA_FIM_SITUACAO_SFP,
S.CONTROLE_FOLHA CONTROLE_FOLHA_SFP, S.E_AFASTAMENTO E_AFASTAMENTO_SFP, S.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_SFP, S.c_livre_selec02 SO_PONTO_SFP
from RHCGED_ALT_SIT_FUN X 
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = X.COD_SIT_FUNCIONAL
WHERE S.SITUACAO_PONTO IS NOT NULL--S.CONTROLE_FOLHA <> 'N' -- AND S.E_AFASTAMENTO <> 'N' AND S.SUSPENDE_REMUNERA <> 'N'
)SFP  ON --SIT FUNC PARCIAL NO PERIODO DA FICHA
SFP.CODIGO_EMPRESA_SFP = X.CODIGO_EMPRESA AND SFP.TIPO_CONTRATO_SFP = X.TIPO_CONTRATO AND SFP.CODIGO_CONTRATO_SFP = X.CODIGO_CONTRATO
AND
  ((TRUNC(SFP.DATA_INIC_SITUACAO_SFP) >= TRUNC(X.DATA_INI_AFAST) AND TRUNC(SFP.DATA_INIC_SITUACAO_SFP) <= TRUNC(X.DATA_FIM_AFAST))
  OR (TRUNC(SFP.DATA_INIC_SITUACAO_SFP)< TRUNC(X.DATA_INI_AFAST) AND TRUNC(SFP.DATA_FIM_SITUACAO_SFP) >= TRUNC(X.DATA_INI_AFAST))
)

WHERE X.ORDEM_NA_FICHA IS NOT NULL --somente os registros com fichas para nAo confundir os registros tipo ativos na alt sit func

)X2
)X3

)

LOOP

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_1, CAMPO_VALOR_2, DATA_DADOS, CONSIDERACOES)
VALUES(C2.CODIGO_EMPRESA,C2.TIPO_CONTRATO,C2.CODIGO_CONTRATO,'LOG EXECUCAO PROCEDURE PR_ACERTO_TEG_SIT_FUNC','PARTE_2_RELATORIO', SYSDATE, 
'|'||C2.CENARIO||'|'||C2.QTD_DIAS_FICHA||'|'||C2.QTD_DIAS_SF_PARCIAL||'|'||C2.QTD_DIAS_FERIAS_NA_FICHA||'|'||C2.DUPLICIDADE_RELATORIO_FICHA||'|'||C2.MOTIVO||'|'||C2.STATUS_REGISTRO||'|'||C2.DADOS_FICHA_MEDICA||'|'||C2.DT_ALTER_FICHA||'|'||C2.ORDEM_NA_FICHA||'|'||C2.CODIGO_EMPRESA||'|'||C2.TIPO_CONTRATO||'|'||C2.CODIGO_CONTRATO||'|'||C2.CODIGO_PESSOA||'|'||C2.DT_REG_OCORRENCIA||'|'||C2.OCORRENCIA||'|'||C2.NATUREZA_EXAME||'|'||C2.PROCEDIMENTO||'|'||C2.CODIGO_PROC_MED||'|'||C2.CONDUTA||'|'||C2.VINCULO||'|'||C2.COD_SIT_FUNC_DEFERIDA||'|'||C2.SITUACAO_PONTO||'|'||C2.SFF_CONTROLE_FOLHA||'|'||C2.SFF_E_AFASTAMENTO||'|'||C2.SFF_SUSPENDE_REMUNERA||'|'||C2.COD_SIT_FUNC_DOENCA_GRAVE||'|'||C2.SIT_PONTO_DOENCA_GRAVE||'|'||C2.DATA_INI_AFAST||'|'||C2.DATA_FIM_AFAST||'|'||C2.LOGIN_USUARIO||'|'||C2.DT_ULT_ALTER_USUA||'|'||C2.COD_DOENCA||'|'||C2.DADOS_ALT_SIT_FUNC||'|'||C2.DT_ALTER_SIT_FUNC||'|'||C2.ORDEM_NA_SIT_FUNC||'|'||C2.CODIGO_EMPRESA_S||'|'||C2.TIPO_CONTRATO_S||'|'||C2.CODIGO_S||'|'||C2.DATA_INIC_SITUACAO||'|'||C2.COD_SIT_FUNCIONAL||'|'||C2.DATA_FIM_SITUACAO||'|'||C2.PROXIMA_SITUACAO||'|'||C2.LOGIN_USUARIO_S||'|'||C2.DT_ULT_ALTER_USUA_S||'|'||C2.CODIGO_DOENCA_S||'|'||C2.DADOS_ULT_ASF||'|'||C2.CODIGO_EMPRESA_A||'|'||C2.TIPO_CONTRATO_A||'|'||C2.CODIGO_A||'|'||C2.COD_SIT_FUNCIONAL_A||'|'||C2.ULT_ASF_DESC_SIT_FUNC||'|'||C2.ULT_ASF_CONTROLE_FOLHA||'|'||C2.ULT_ASF_E_AFASTAMENTO||'|'||C2.ULT_ASF_SUSPENDE_REMUNERA||'|'||C2.ULT_ASF_SO_PONTO||'|'||C2.DATA_INIC_SITUACAO_A||'|'||C2.DATA_FIM_SITUACAO_A||'|'||C2.PROXIMA_SITUACAO_A||'|'||C2.LOGIN_USUARIO_A||'|'||C2.DT_ULT_ALTER_USUA_A||'|'||C2.DADOS_FERIAS||'|'||C2.CODIGO_EMPRESA_F||'|'||C2.TIPO_CONTRATO_F||'|'||C2.CODIGO_CONTRATO_F||'|'||C2.TIPO_FERIAS||'|'||C2.DT_INI_AQUISICAO||'|'||C2.PERIODO||'|'||C2.CONTROLE_FOLHA_F||'|'||C2.E_AFASTAMENTO_F||'|'||C2.COD_SIT_PONTO_F||'|'||C2.SUSPENDE_REMUNERA_F||'|'||C2.SO_GERA_SIT_PONTO_F||'|'||C2.DATA_INICIO_FERIAS||'|'||C2.DATA_FIM_FERIAS||'|'||C2.DADOS_ALT_SIT_FUNC_PARCIAL||'|'||C2.CODIGO_EMPRESA_SFP||'|'||C2.TIPO_CONTRATO_SFP||'|'||C2.CODIGO_CONTRATO_SFP||'|'||C2.COD_SIT_FUNCIONAL_SFP||'|'||C2.SFP_DESC_SIT_FUNC||'|'||C2.DATA_INIC_SITUACAO_SFP||'|'||C2.DATA_FIM_SITUACAO_SFP||'|'||C2.CONTROLE_FOLHA_SFP||'|'||C2.E_AFASTAMENTO_SFP||'|'||C2.SUSPENDE_REMUNERA_SFP||'|'||C2.SO_PONTO_SFP
);COMMIT;

END LOOP; --FIM LOOP C2 RELATORIO
--FIM------------------------------GRAVAR RELATORIO DOS REGISTROS GRAVADOS COM A ANALISE DO DIA-----------------------------------------------------------------------------------------------------------------------------

END;
END; --BEGIN GERAL

END;
