
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_ACERTOS_HIST_ESCALA_CONTR" 
AS
--KELLYSSON EM 7/8/20 BASEADO dif_contrato_hist_escala_absenteismo.sql
--kellysson em 3/7/20
BEGIN

DECLARE
vCONTADOR NUMBER;
vDATA_SISTEMA DATE;

err_msg varchar2 (4000);

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_SISTEMA := NULL;

err_msg := NULL;

dbms_output.put_line('--RELATORIO DIFERENÇA NO HISTORICO ESCALA E CONTRATO');

--PEGAR DATA DO SISTEMA ARTERH
SELECT DATA_DO_SISTEMA INTO vDATA_SISTEMA from rhparm_p_sist;


FOR C1 IN (


SELECT
--X4.CENARIO, X4.TRATATIVA, COUNT(1)QUANT
CASE WHEN TO_DATE(x4.ANO_MES_REFERENCIA,'DD/MM/YYYY') = TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY')THEN 'SIM' ELSE 'NAO' END AS TEM_CONTRATO, X4.*
FROM(
SELECT X3.* FROM(
select
--/*
CASE
WHEN X2.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND X2.DT_FIM_TROCA IS NULL THEN '0.0-TUDO OK, FAZER NADA'
WHEN X2.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND TRUNC(X2.DT_INICIO_TROCA) = TRUNC(X2.DT_FIM_TROCA) THEN '0.1-TUDO OK, APENAS LIMPAR DATA FIM DO HISTORICO'
WHEN X2.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND TRUNC(X2.DT_FIM_TROCA) <= trunc(sysdate) THEN '0.2-DATA FIM JA PASSOU, O QUE FAZER?'
WHEN X2.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND TRUNC(X2.DT_FIM_TROCA) > trunc(sysdate) THEN '0.3-DATA FIM FUTURA, O QUE FAZER DEPOIS QUE VENCER?'
WHEN X2.CENARIO = '1-SEM ESCALA NO ULTIMO CONTRATO' THEN '1-AJUSTAR MANUALMENTE'
WHEN X2.CENARIO = '2-SEM HISTORICO DE ESCALA' AND X2.DT_ULT_ESCALA_CONTRATO IS NOT NULL AND X2.DT_ULT_ESCALA_CONTRATO IS NOT NULL THEN '2.1-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA NO CONTRATO'
WHEN X2.CENARIO = '2-SEM HISTORICO DE ESCALA' AND X2.DT_ULT_ESCALA_CONTRATO IS NULL AND X2.DT_ULT_ESCALA_CONTRATO IS NULL THEN '2.2-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA DO EFETIVO EXERCICIO E GRAVAR DT_ULT_ESCALA NO CONTRATO'
WHEN X2.CENARIO = '3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO' THEN '3-SEGUIR A ESCALA DO CONTRATO E REGRAS DE DATAS SUGERIDAS NAS TRATATIVAS ANTERIORES?'
WHEN X2.CENARIO = '4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO' THEN '4-SEGUIR QUAL DATA E AJUSTAR COMO A DATA FIM DO HISTORICO QUANDO TIVER PREENCHIDA?'
WHEN X2.CENARIO = '5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO' THEN '5-SEGUIR A ESCALA O CONTRATO? E AJUSTAR COMO A DATA FIM DO HISTORICO QUANDO TIVER PREENCHIDA?'
WHEN X2.CENARIO = '6-CODIGO ESCALA IGUAL SEM DATA NO CONTRATO' THEN '6-GRAVAR DATA INICIO HISTORICO NO CONTRATO E REGRAS DE DATA FIM SE TIVER?'
WHEN X2.CENARIO = '7-CODIGO ESCALA DIFERENTE E SEM DATA NO CONTRATO' THEN '7-USA ESCALA DO CONTRATO, GRAVAR DATA INICIO HISTORICO NO CONTRATO E REGRAS DE DATA FIM SE TIVER?'
ELSE '9-NAO MAPEADO'
END TRATATIVA,
x2.*
--*/
--X2.CENARIO, COUNT(1)QUANT
from(
SELECT
CASE
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST = X.COD_ESCALA_ULT_CONTRATO  AND TRUNC(X.DT_ULT_ESCALA_CONTRATO) = TRUNC(X.DT_INICIO_TROCA)THEN '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NULL THEN '1-SEM ESCALA NO ULTIMO CONTRATO'
WHEN X.COD_ESCALA_ULT_HIST IS NULL THEN '2-SEM HISTORICO DE ESCALA'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST <> X.COD_ESCALA_ULT_CONTRATO AND TRUNC(X.DT_ULT_ESCALA_CONTRATO) <> TRUNC(X.DT_INICIO_TROCA) THEN '3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST = X.COD_ESCALA_ULT_CONTRATO  AND TRUNC(X.DT_ULT_ESCALA_CONTRATO) <> TRUNC(X.DT_INICIO_TROCA)THEN '4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST <> X.COD_ESCALA_ULT_CONTRATO  AND TRUNC(X.DT_ULT_ESCALA_CONTRATO) = TRUNC(X.DT_INICIO_TROCA)THEN '5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST = X.COD_ESCALA_ULT_CONTRATO  AND X.DT_ULT_ESCALA_CONTRATO IS NULL THEN '6-CODIGO ESCALA IGUAL SEM DATA NO CONTRATO'
WHEN X.COD_ESCALA_ULT_CONTRATO IS NOT NULL AND X.COD_ESCALA_ULT_HIST IS NOT NULL AND X.COD_ESCALA_ULT_HIST <> X.COD_ESCALA_ULT_CONTRATO  AND X.DT_ULT_ESCALA_CONTRATO IS NULL THEN '7-CODIGO ESCALA DIFERENTE E SEM DATA NO CONTRATO'
ELSE '9-NAO MALEADO'
END CENARIO,
CASE
WHEN X.DT_FIM_TROCA IS NULL AND X.DT_INICIO_TROCA < X.DT_ULT_ESCALA_CONTRATO THEN 'GRAVAR DATA CONTRATO NA FIM'
WHEN X.DT_FIM_TROCA IS NOT NULL AND X.DT_FIM_TROCA >= X.DT_ULT_ESCALA_CONTRATO AND X.DT_INICIO_TROCA < X.DT_ULT_ESCALA_CONTRATO THEN 'DIMINUIR DATA FIM DT CONTRATO-1 DIA'
WHEN X.DT_FIM_TROCA IS NOT NULL AND X.DT_FIM_TROCA <  X.DT_ULT_ESCALA_CONTRATO AND X.DT_INICIO_TROCA < X.DT_ULT_ESCALA_CONTRATO THEN 'AUMENTAR DATA FIM DT CONTRATO-1 DIA'
ELSE 'EXCLUIR HISTORICO E CRIAR NOVO'
END TIPO_AJUSTE_HIST_EXISTENTE,
X.*
FROM(
select
c.codigo_escala cod_escala_ULT_CONTRATO, c.dt_ult_escala dt_ult_escala_CONTRATO,
ULT_ESC.COD_ESCALA COD_ESCALA_ULT_HIST, ULT_ESC.DT_INICIO_TROCA, ULT_ESC.DT_FIM_TROCA, ULT_ESC.ALTER_DEFINITIVA,
c.codigo_empresa, c.tipo_contrato, c.codigo BM, c.nome,
c.situacao_funcional cod_sit_func,
c.ANO_MES_REFERENCIA,
 c.data_admissao, c.data_posse, c.data_efetivo_exerc, c.data_base_ferias, c.data_rescisao,
C.cod_cargo_efetivo,
E.DESCRICAO CARGO_EFETIVO,
C.cod_cargo_comiss,
CC.DESCRICAO CARGO_COMISSIONADO,
C.codigo_funcao,
F.DESCRICAO FUNCAO

from rhpess_contrato c
LEFT OUTER JOIN (SELECT ULT_ESC.* FROM RHPONT_ALT_ESCALA ULT_ESC WHERE ULT_ESC.DT_INICIO_TROCA =
    (SELECT MAX(AUX.dt_inicIO_TROCA) FROM RHPONT_ALT_ESCALA AUX
        WHERE AUX.CODIGO_EMPRESA =  ULT_ESC.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = ULT_ESC.TIPO_CONTRATO AND AUX.CODIGO_CONTRATO = ULT_ESC.CODIGO_CONTRATO))
ULT_ESC ON C.CODIGO_EMPRESA = ULT_ESC.CODIGO_EMPRESA AND C.TIPO_CONTRATO = ULT_ESC.TIPO_CONTRATO AND C.CODIGO = ULT_ESC.CODIGO_CONTRATO
left outer join RHPLCS_FUNCAO F ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO = C.codigo_funcao
left outer join RHPLCS_CARGO CC ON Cc.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND Cc.CODIGO = C.cod_cargo_comiss
left outer join RHPLCS_CARGO E ON e.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND e.CODIGO = C.cod_cargo_efetivo

where
c.ANO_MES_REFERENCIA = (select max(aux.ANO_MES_REFERENCIA) from rhpess_contrato AUX
                                       where AUX.CODIGO_EMPRESA = c.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = c.TIPO_CONTRATO and AUX.CODIGO = c.CODIGO
                                       and trunc(aux.ANO_MES_REFERENCIA) <= TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY'))

AND C.DATA_RESCISAO IS NULL
AND C.CODIGO_EMPRESA IN ('0001','0003','0013','0014','0002')--adicionado empresa 2 em 5/7/23
order by 1,3,4,7
)X
)x2 --GROUP BY X2.CENARIO ORDER BY X2.CENARIO
)X3 ORDER BY X3.CENARIO, X3.TRATATIVA
)X4
WHERE-- X4.CENARIO <> '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND
X4.TRATATIVA <> '0.0-TUDO OK, FAZER NADA'
and  X4.TRATATIVA <> '0.3-DATA FIM FUTURA, O QUE FAZER DEPOIS QUE VENCER?'
--WHERE X4.BM IN ('000000000175181','000000000442821') --TESTES
--GROUP BY X4.CENARIO, X4.TRATATIVA
ORDER BY X4.CENARIO, X4.TRATATIVA
, X4.CODIGO_EMPRESA, X4.TIPO_CONTRATO, X4.BM



)LOOP

vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--'||vCONTADOR);

--/*
--inicio---1º passo ---------------------------------------------------------------------------------------1º criar contrato e tab auxiliar no mes 01/07/2020
IF C1.TEM_CONTRATO = 'NAO' THEN
dbms_output.put_line('--INSERT REALIZADO NO CONTRATO: '|| C1.CODIGO_EMPRESA||'-'||C1.TIPO_CONTRATO||'-'||C1.BM);
INSERT INTO RHPESS_CONTRATO SELECT RHPESS_CONTRATO.CODIGO_EMPRESA,
  RHPESS_CONTRATO.TIPO_CONTRATO,
  RHPESS_CONTRATO.CODIGO,
  RHPESS_CONTRATO.CODIGO_PESSOA,
  RHPESS_CONTRATO.NOME,
  RHPESS_CONTRATO.REGISTRO,
  RHPESS_CONTRATO.NUMERO_ARQUIVO,
  RHPESS_CONTRATO.SITUACAO_FUNCIONAL,
  RHPESS_CONTRATO.SITUACAO_CONTRATO,
  RHPESS_CONTRATO.STATUS_CONTRATO,
  RHPESS_CONTRATO.DATA_ADMISSAO,
  RHPESS_CONTRATO.MOTIVO_ADMISSAO,
  RHPESS_CONTRATO.MOTIVO_DEMISSAO,
  RHPESS_CONTRATO.TIPO_PAGAMENTO,
  RHPESS_CONTRATO.TIPO_SALARIO,
  RHPESS_CONTRATO.VINCULO,
  RHPESS_CONTRATO.FORMA_PROVIMENTO,
  RHPESS_CONTRATO.COD_LOCAL1,
  RHPESS_CONTRATO.COD_LOCAL2,
  RHPESS_CONTRATO.COD_LOCAL3,
  RHPESS_CONTRATO.COD_LOCAL4,
  RHPESS_CONTRATO.COD_LOCAL5,
  RHPESS_CONTRATO.COD_LOCAL6,
  RHPESS_CONTRATO.DT_ULT_ALT_LOC,
  RHPESS_CONTRATO.COD_UNIDADE1,
  RHPESS_CONTRATO.COD_UNIDADE2,
  RHPESS_CONTRATO.COD_UNIDADE3,
  RHPESS_CONTRATO.COD_UNIDADE4,
  RHPESS_CONTRATO.COD_UNIDADE5,
  RHPESS_CONTRATO.COD_UNIDADE6,
  RHPESS_CONTRATO.DT_ULT_ALT_UNID,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB1,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB2,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB3,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB4,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB5,
  RHPESS_CONTRATO.COD_CUSTO_CONTAB6,
  RHPESS_CONTRATO.DT_ULT_ALT_CONT,
  RHPESS_CONTRATO.COD_CUSTO_GERENC1,
  RHPESS_CONTRATO.COD_CUSTO_GERENC2,
  RHPESS_CONTRATO.COD_CUSTO_GERENC3,
  RHPESS_CONTRATO.COD_CUSTO_GERENC4,
  RHPESS_CONTRATO.COD_CUSTO_GERENC5,
  RHPESS_CONTRATO.COD_CUSTO_GERENC6,
  RHPESS_CONTRATO.DT_ULT_ALT_GER,
  RHPESS_CONTRATO.SALARIO_PAGTO,
  RHPESS_CONTRATO.COD_CARGO_PAGTO,
  RHPESS_CONTRATO.NIVEL_CARGO_PAGTO,
  RHPESS_CONTRATO.COD_CARGO_EFETIVO,
  RHPESS_CONTRATO.NIVEL_CARGO_EFETIV,
  RHPESS_CONTRATO.DT_ULT_CARGO_EFET,
  RHPESS_CONTRATO.COD_CARGO_COMISS,
  RHPESS_CONTRATO.NIVEL_CARGO_COMISS,
  RHPESS_CONTRATO.DT_ULT_CARGO_COM,
  RHPESS_CONTRATO.COD_CARGO_AMPAR,
  RHPESS_CONTRATO.NIVEL_CARGO_AMPAR,
  RHPESS_CONTRATO.DT_ULT_CARGO_AMPAR,
  RHPESS_CONTRATO.CODIGO_FUNCAO,
  RHPESS_CONTRATO.DT_ULT_FUNCAO,
  RHPESS_CONTRATO.COD_ESPECIALIDADE,
  RHPESS_CONTRATO.DT_ULT_ESPEC,
  RHPESS_CONTRATO.CODIGO_VAGA,
  RHPESS_CONTRATO.DT_ULT_VAGA,
  RHPESS_CONTRATO.AREA_ATUACAO,
  RHPESS_CONTRATO.CATEG_PROFISSIONAL,
  RHPESS_CONTRATO.CODIGO_ESCALA,
  RHPESS_CONTRATO.REGISTRO_PONTO,
  RHPESS_CONTRATO.DT_ULT_ESCALA,
  RHPESS_CONTRATO.CODIGO_BANCO_CC,
  RHPESS_CONTRATO.CONTA_CORRENTE,
  RHPESS_CONTRATO.CODIGO_BANCO_FGTS,
  RHPESS_CONTRATO.CONTA_FGTS,
  RHPESS_CONTRATO.DATA_OPCAO_FGTS,
  RHPESS_CONTRATO.DATA_RETROACAO,
  RHPESS_CONTRATO.DATA_RETRATACAO,
  RHPESS_CONTRATO.COD_SINDICATO,
  RHPESS_CONTRATO.NIVEL_SINDICATO,
  RHPESS_CONTRATO.DT_ULT_SINDICATO,
  RHPESS_CONTRATO.DESC_CONTRIB_SIND,
  RHPESS_CONTRATO.SINDICALIZADO,
  RHPESS_CONTRATO.INSCRICAO_INSS,
  RHPESS_CONTRATO.COD_MOVIMENTACAO,
  RHPESS_CONTRATO.DATA_TRANSF_ENTRAD,
  RHPESS_CONTRATO.DATA_PRI_ADMISSAO,
  RHPESS_CONTRATO.DATA_REINTEGRACAO,
  RHPESS_CONTRATO.DATA_EFETIVO_EXERC,
  RHPESS_CONTRATO.DATA_POSSE,
  RHPESS_CONTRATO.DATA_NOMEACAO,
  RHPESS_CONTRATO.DATA_INICIO_ESTAB,
  RHPESS_CONTRATO.DATA_FIM_ESTAB,
  RHPESS_CONTRATO.DT_FIM_CONTR_EXP,
  RHPESS_CONTRATO.DT_FIM_CONTR_DETER,
  RHPESS_CONTRATO.DATA_FIM_RENOV_EXP,
  RHPESS_CONTRATO.DATA_AV_PREVIO,
  RHPESS_CONTRATO.DATA_RESCISAO,
  RHPESS_CONTRATO.CAUSA_RESCISAO,
  RHPESS_CONTRATO.DATA_INIC_AFAST,
  RHPESS_CONTRATO.DATA_FIM_AFAST,
  RHPESS_CONTRATO.NRO_MESES_AFAST,
  RHPESS_CONTRATO.CTRL_VERBAS,
  RHPESS_CONTRATO.FORMA_PAGAMENTO,
  RHPESS_CONTRATO.DATA_BASE_FERIAS,
  RHPESS_CONTRATO.DATA_INIC_GOZO,
  RHPESS_CONTRATO.DATA_FIM_GOZO,
  RHPESS_CONTRATO.DEPENDENTES_SF,
  RHPESS_CONTRATO.DEPENDENTES_IRRF,
  RHPESS_CONTRATO.COD_PROCURADOR,
  RHPESS_CONTRATO.DATA_PAGTO_CALCULO,
  RHPESS_CONTRATO.DATA_PAGTO_ADIANT,
  RHPESS_CONTRATO.DATA_PAGTO_FERIAS,
  RHPESS_CONTRATO.DATA_PAGTO_13SAL,
  RHPESS_CONTRATO.DATA_PAGTO_RESCISA,
  RHPESS_CONTRATO.SAL_CONT_EFETIVO,
  RHPESS_CONTRATO.DT_ULT_SAL_C_EFET,
  RHPESS_CONTRATO.SAL_CONT_COMISSION,
  RHPESS_CONTRATO.DT_ULT_SAL_C_COM,
  RHPESS_CONTRATO.SAL_CONT_AMPAR,
  RHPESS_CONTRATO.DT_ULT_SAL_C_AMP,
  RHPESS_CONTRATO.SAL_AUX_EFETIVO,
  RHPESS_CONTRATO.DT_ULT_SAL_A_EFET,
  RHPESS_CONTRATO.SAL_AUX_COMISSION,
  RHPESS_CONTRATO.DT_ULT_SAL_A_COM,
  RHPESS_CONTRATO.SAL_AUX_AMPAR,
  RHPESS_CONTRATO.DT_ULT_SAL_A_AMP,
  RHPESS_CONTRATO.C_LIVRE_SELEC01,
  RHPESS_CONTRATO.C_LIVRE_SELEC02,
  RHPESS_CONTRATO.C_LIVRE_SELEC03,
  RHPESS_CONTRATO.C_LIVRE_SELEC04,
  RHPESS_CONTRATO.C_LIVRE_SELEC05,
  RHPESS_CONTRATO.C_LIVRE_SELEC06,
  RHPESS_CONTRATO.C_LIVRE_SELEC07,
  RHPESS_CONTRATO.C_LIVRE_SELEC08,
  RHPESS_CONTRATO.C_LIVRE_SELEC09,
  RHPESS_CONTRATO.C_LIVRE_SELEC10,
  RHPESS_CONTRATO.C_LIVRE_SELEC11,
  RHPESS_CONTRATO.C_LIVRE_SELEC12,
  RHPESS_CONTRATO.C_LIVRE_SELEC13,
  RHPESS_CONTRATO.C_LIVRE_SELEC14,
  RHPESS_CONTRATO.C_LIVRE_SELEC15,
  RHPESS_CONTRATO.C_LIVRE_SELEC36,
  RHPESS_CONTRATO.C_LIVRE_SELEC37,
  RHPESS_CONTRATO.C_LIVRE_SELEC38,
  RHPESS_CONTRATO.C_LIVRE_SELEC39,
  RHPESS_CONTRATO.C_LIVRE_SELEC40,
  RHPESS_CONTRATO.C_LIVRE_VALOR16,
  RHPESS_CONTRATO.C_LIVRE_VALOR17,
  RHPESS_CONTRATO.C_LIVRE_VALOR18,
  RHPESS_CONTRATO.C_LIVRE_VALOR19,
  RHPESS_CONTRATO.C_LIVRE_VALOR20,
  RHPESS_CONTRATO.C_LIVRE_VALOR21,
  RHPESS_CONTRATO.C_LIVRE_VALOR22,
  RHPESS_CONTRATO.C_LIVRE_VALOR23,
  RHPESS_CONTRATO.C_LIVRE_DESCR24,
  RHPESS_CONTRATO.C_LIVRE_DESCR25,
  RHPESS_CONTRATO.C_LIVRE_DESCR26,
  RHPESS_CONTRATO.C_LIVRE_DESCR27,
  RHPESS_CONTRATO.C_LIVRE_DATA28,
  RHPESS_CONTRATO.C_LIVRE_DATA29,
  RHPESS_CONTRATO.C_LIVRE_DATA30,
  RHPESS_CONTRATO.C_LIVRE_DATA31,
  RHPESS_CONTRATO.C_LIVRE_DATA32,
  RHPESS_CONTRATO.C_LIVRE_DATA33,
  RHPESS_CONTRATO.C_LIVRE_DATA34,
  RHPESS_CONTRATO.C_LIVRE_DATA35,
  RHPESS_CONTRATO.C_LIVRE_OPCAO41,
  RHPESS_CONTRATO.C_LIVRE_OPCAO42,
  RHPESS_CONTRATO.C_LIVRE_OPCAO43,
  RHPESS_CONTRATO.C_LIVRE_OPCAO44,
  RHPESS_CONTRATO.C_LIVRE_OPCAO45,
  RHPESS_CONTRATO.C_LIVRE_OPCAO46,
  RHPESS_CONTRATO.C_LIVRE_OPCAO47,
  RHPESS_CONTRATO.C_LIVRE_OPCAO48,
  RHPESS_CONTRATO.INDIC_ALTERAC1,
  RHPESS_CONTRATO.INDIC_ALTERAC2,
  RHPESS_CONTRATO.INDIC_ALTERAC3,
  RHPESS_CONTRATO.INDIC_ALTERAC4,
  RHPESS_CONTRATO.INDIC_ALTERAC5,
  RHPESS_CONTRATO.TEXTO_ASSOCIADO,
  'script_ajuste_escala',
  SYSDATE,
  RHPESS_CONTRATO.TELEFONE,
to_char(TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
  RHPESS_CONTRATO.DATA_APOSENTA_FGTS,
  RHPESS_CONTRATO.REABILITADO,
  RHPESS_CONTRATO.C_LIVRE_VALOR49,
  RHPESS_CONTRATO.C_LIVRE_VALOR50,
  RHPESS_CONTRATO.C_LIVRE_VALOR51,
  RHPESS_CONTRATO.C_LIVRE_VALOR52,
  RHPESS_CONTRATO.C_LIVRE_VALOR53,
  RHPESS_CONTRATO.C_LIVRE_VALOR54,
  RHPESS_CONTRATO.C_LIVRE_VALOR55,
  RHPESS_CONTRATO.C_LIVRE_VALOR56,
  RHPESS_CONTRATO.C_LIVRE_DATA57,
  RHPESS_CONTRATO.C_LIVRE_DATA58,
  RHPESS_CONTRATO.C_LIVRE_DATA59,
  RHPESS_CONTRATO.C_LIVRE_DATA60,
  RHPESS_CONTRATO.C_LIVRE_DATA61,
  RHPESS_CONTRATO.C_LIVRE_DATA62,
  RHPESS_CONTRATO.C_LIVRE_DATA63,
  RHPESS_CONTRATO.C_LIVRE_DATA64,
  RHPESS_CONTRATO.C_LIVRE_OPCAO65,
  RHPESS_CONTRATO.C_LIVRE_OPCAO66,
  RHPESS_CONTRATO.C_LIVRE_OPCAO67,
  RHPESS_CONTRATO.C_LIVRE_OPCAO68,
  RHPESS_CONTRATO.INDIC_ALTERAC6,
  RHPESS_CONTRATO.CLASSE_CONT_INSS,
  RHPESS_CONTRATO.E_MAIL,
  RHPESS_CONTRATO.USA_ASSOC_CONT_ESC,
  RHPESS_CONTRATO.CLASSIFICACAO_CAND,
  RHPESS_CONTRATO.NUMERO_EDITAL,
  RHPESS_CONTRATO.TIPO_AGRUP_UNID,
  RHPESS_CONTRATO.TIPO_AGRUP_CONT,
  RHPESS_CONTRATO.TIPO_AGRUP_CGER,
  RHPESS_CONTRATO.TIPO_AGRUP_LOTA,
  RHPESS_CONTRATO.NOME_ACESSO,
  RHPESS_CONTRATO.CODIGO_SOLICITACAO,
  RHPESS_CONTRATO.ID_CONTR_FORN,
  RHPESS_CONTRATO.FUNC_COMP_EMPR_AV,
  RHPESS_CONTRATO.DT_MOLESTIA_GRAVE,
  RHPESS_CONTRATO.SAL_CONT_FUNCAO,
  RHPESS_CONTRATO.DT_ULT_SAL_C_FUN,
  RHPESS_CONTRATO.SAL_AUX_FUNCAO,
  RHPESS_CONTRATO.DT_ULT_SAL_A_FUN,
  RHPESS_CONTRATO.DATA_PROJ_AV_PREV,
  RHPESS_CONTRATO.DT_PROJ_AFAST_ESOCIAL,
  RHPESS_CONTRATO.TP_AVISO_PREVIO_ESOCIAL,
  RHPESS_CONTRATO.TP_CONTA_BANCARIA,
  RHPESS_CONTRATO.DT_PROC_ESOCIAL,
  RHPESS_CONTRATO.DT_ALTER_ESOCIAL,
  RHPESS_CONTRATO.DT_CANC_AVISO_PREVIO,
  RHPESS_CONTRATO.MOT_CANC_AV_PREV_ESOCIAL,
  RHPESS_CONTRATO.DESC_SAL_VARIAVEL,
  RHPESS_CONTRATO.MOTIVO_CONTRATACAO,
  RHPESS_CONTRATO.CPF_TRAB_SUBSTITUIDO,
  RHPESS_CONTRATO.MATRIC_TRAB_SUBSTITUIDO,
  RHPESS_CONTRATO.IND_SEGURO_DESEMPREGO,
  RHPESS_CONTRATO.DT_GERACAO_CAGED,
  RHPESS_CONTRATO.OBS_RESCISAO,
  RHPESS_CONTRATO.DT_FIM_QUARENTENA,
  RHPESS_CONTRATO.CNPJ_EMPRESA_SUCESSORA,
  RHPESS_CONTRATO.JUST_CONTR_ESOCIAL,
  RHPESS_CONTRATO.TP_INCL_CONTR_ESOCIAL,
  RHPESS_CONTRATO.INFO_COTA_ESOCIAL,
  RHPESS_CONTRATO.CLAUSULA_ASSEC,
  RHPESS_CONTRATO.DT_ALTERACAO_CONTR,
  RHPESS_CONTRATO.DT_EFEITO_ALTER_CONTR,
  RHPESS_CONTRATO.DESC_ALTER_CONTR,
  RHPESS_CONTRATO.IND_CUMPR_PARC_AV,
  RHPESS_CONTRATO.CODIGO_CONTR_ANTERIOR,
  RHPESS_CONTRATO.CPF_ANTERIOR,
  RHPESS_CONTRATO.DATA_ALTER_CPF,
  RHPESS_CONTRATO.OBS_ALTER_CPF,
  RHPESS_CONTRATO.TEM_ALTER_CPF,
  RHPESS_CONTRATO.INFO_COTA_RACA,
  RHPESS_CONTRATO.MATRICULA_ESOCIAL
,RHPESS_CONTRATO.CONSELHO_REGIONAL, --NOVO V.22.3.1
RHPESS_CONTRATO.INSCRICAO_CONSELHO,--NOVO V.22.3.1
RHPESS_CONTRATO.UF_CONSELHO --NOVO V.22.3.1
,RHPESS_CONTRATO.COD_CARREIRA--a partir de 26/4/21 V.23.2.2
,RHPESS_CONTRATO.COD_EIXO--a partir de 26/4/21 V.23.2.2
,RHPESS_CONTRATO.COD_NIVEL--a partir de 26/4/21 V.23.2.2
, RHPESS_CONTRATO.IND_REMUN --EM 16/3/23 Versao 25.2.1
 , RHPESS_CONTRATO.IND_PDV --EM 30/1/24 Versao 26.1.1
FROM RHPESS_CONTRATO
WHERE RHPESS_CONTRATO.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX
WHERE AUX.CODIGO_EMPRESA=RHPESS_CONTRATO.CODIGO_EMPRESA
AND AUX.TIPO_CONTRATO=RHPESS_CONTRATO.TIPO_CONTRATO
AND AUX.CODIGO=RHPESS_CONTRATO.CODIGO)
AND RHPESS_CONTRATO.DATA_RESCISAO IS NULL
AND RHPESS_CONTRATO.CODIGO=''||C1.BM||''
AND RHPESS_CONTRATO.CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||''
AND RHPESS_CONTRATO.TIPO_CONTRATO=''||C1.TIPO_CONTRATO||''; commit;

INSERT INTO RHPESS_CONTRATO_AUX X
SELECT
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
to_char(TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
  'script_ajuste_escala' as LOGIN_USUARIO,
sysdate DT_ULT_ALTER_USUA,
C_LIVRE_AUX_SELEC01,
C_LIVRE_AUX_SELEC02,
C_LIVRE_AUX_SELEC03,
C_LIVRE_AUX_SELEC04,
C_LIVRE_AUX_SELEC05,
C_LIVRE_AUX_SELEC06,
C_LIVRE_AUX_SELEC07,
C_LIVRE_AUX_SELEC08,
C_LIVRE_AUX_SELEC09,
C_LIVRE_AUX_SELEC10,
C_LIVRE_AUX_SELEC11,
C_LIVRE_AUX_SELEC12,
C_LIVRE_AUX_SELEC13,
C_LIVRE_AUX_SELEC14,
C_LIVRE_AUX_SELEC15,
C_LIVRE_AUX_SELEC16,
C_LIVRE_AUX_SELEC17,
C_LIVRE_AUX_SELEC18,
C_LIVRE_AUX_SELEC19,
C_LIVRE_AUX_SELEC20,
C_LIVRE_AUX_VALOR01,
C_LIVRE_AUX_VALOR02,
C_LIVRE_AUX_VALOR03,
C_LIVRE_AUX_VALOR04,
C_LIVRE_AUX_VALOR05,
C_LIVRE_AUX_VALOR06,
C_LIVRE_AUX_VALOR07,
C_LIVRE_AUX_VALOR08,
C_LIVRE_AUX_VALOR09,
C_LIVRE_AUX_VALOR10,
C_LIVRE_AUX_VALOR11,
C_LIVRE_AUX_VALOR12,
C_LIVRE_AUX_VALOR13,
C_LIVRE_AUX_VALOR14,
C_LIVRE_AUX_VALOR15,
C_LIVRE_AUX_VALOR16,
C_LIVRE_AUX_VALOR17,
C_LIVRE_AUX_VALOR18,
C_LIVRE_AUX_VALOR19,
C_LIVRE_AUX_VALOR20,
C_LIVRE_AUX_DATA01,
C_LIVRE_AUX_DATA02,
C_LIVRE_AUX_DATA03,
C_LIVRE_AUX_DATA04,
C_LIVRE_AUX_DATA05,
C_LIVRE_AUX_DATA06,
C_LIVRE_AUX_DATA07,
C_LIVRE_AUX_DATA08,
C_LIVRE_AUX_DATA09,
C_LIVRE_AUX_DATA10,
C_LIVRE_AUX_DATA11,
C_LIVRE_AUX_DATA12,
C_LIVRE_AUX_DATA13,
C_LIVRE_AUX_DATA14,
C_LIVRE_AUX_DATA15,
C_LIVRE_AUX_DATA16,
C_LIVRE_AUX_DATA17,
C_LIVRE_AUX_DATA18,
C_LIVRE_AUX_DATA19,
C_LIVRE_AUX_DATA20,
C_LIVRE_AUX_OPCAO01,
C_LIVRE_AUX_OPCAO02,
C_LIVRE_AUX_OPCAO03,
C_LIVRE_AUX_OPCAO04,
C_LIVRE_AUX_OPCAO05,
C_LIVRE_AUX_OPCAO06,
C_LIVRE_AUX_OPCAO07,
C_LIVRE_AUX_OPCAO08,
C_LIVRE_AUX_OPCAO09,
C_LIVRE_AUX_OPCAO10,
C_LIVRE_AUX_OPCAO11,
C_LIVRE_AUX_OPCAO12,
C_LIVRE_AUX_OPCAO13,
C_LIVRE_AUX_OPCAO14,
C_LIVRE_AUX_OPCAO15,
C_LIVRE_AUX_OPCAO16,
C_LIVRE_AUX_OPCAO17,
C_LIVRE_AUX_OPCAO18,
C_LIVRE_AUX_OPCAO19,
C_LIVRE_AUX_OPCAO20,
C_LIVRE_AUX_DESCR01,
C_LIVRE_AUX_DESCR02,
C_LIVRE_AUX_DESCR03,
C_LIVRE_AUX_DESCR04,
C_LIVRE_AUX_DESCR05,
C_LIVRE_AUX_DESCR06,
C_LIVRE_AUX_DESCR07,
C_LIVRE_AUX_DESCR08,
C_LIVRE_AUX_DESCR09,
C_LIVRE_AUX_DESCR10,
C_LIVRE_AUX_DESCR11,
C_LIVRE_AUX_DESCR12,
C_LIVRE_AUX_DESCR13,
C_LIVRE_AUX_DESCR14,
C_LIVRE_AUX_DESCR15,
C_LIVRE_AUX_DESCR16,
C_LIVRE_AUX_DESCR17,
C_LIVRE_AUX_DESCR18,
C_LIVRE_AUX_DESCR19,
C_LIVRE_AUX_DESCR20,
C_LIVRE_AUX_TEXTO01,
C_LIVRE_AUX_TEXTO02,
C_LIVRE_AUX_TEXTO03,
C_LIVRE_AUX_TEXTO04,
C_LIVRE_AUX_TEXTO05,
C_LIVRE_AUX_TEXTO06,
C_LIVRE_AUX_TEXTO07,
C_LIVRE_AUX_TEXTO08,
C_LIVRE_AUX_TEXTO09,
C_LIVRE_AUX_TEXTO10,
C_LIVRE_AUX_TEXTO11,
C_LIVRE_AUX_TEXTO12,
C_LIVRE_AUX_TEXTO13,
C_LIVRE_AUX_TEXTO14,
C_LIVRE_AUX_TEXTO15,
C_LIVRE_AUX_TEXTO16,
C_LIVRE_AUX_TEXTO17,
C_LIVRE_AUX_TEXTO18,
C_LIVRE_AUX_TEXTO19,
C_LIVRE_AUX_TEXTO20
FROM RHPESS_CONTRATO_AUX X
where X.codigo_empresa = C1.CODIGO_EMPRESA and X.tipo_contrato = C1.TIPO_CONTRATO And X.CODIGO = C1.BM
AND X.ano_mes_referencia = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO_aux AUX
where X.codigo_empresa = AUX.CODIGO_EMPRESA and X.tipo_contrato = AUX.TIPO_CONTRATO And X.CODIGO = AUX.CODIGO ); commit;

END IF;
--fim---1º passo ---------------------------------------------------------------------------------------1º criar contrato e tab auxiliar no mes 01/07/2020
--*/

BEGIN --EXCEPTION
--/*
--inicio---------------------2º passo ---------------------------------------------ajustes no historico de escala e contrato-------------------------------------
IF C1.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND C1.TRATATIVA = '0.0-TUDO OK, FAZER NADA' THEN
dbms_output.put_line('--(0)FAZER NADA');

ELSIF C1.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND C1.TRATATIVA  = '0.1-TUDO OK, APENAS LIMPAR DATA FIM DO HISTORICO' AND C1.DT_FIM_TROCA IS NOT NULL THEN
dbms_output.put_line('--(1)0.1-TUDO OK, APENAS LIMPAR DATA FIM DO HISTORICO');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;

ELSIF C1.CENARIO = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND C1.TRATATIVA  = '0.2-DATA FIM JA PASSOU, O QUE FAZER?' AND C1.DT_FIM_TROCA IS NOT NULL THEN
dbms_output.put_line('--(2)0.2-DATA FIM JA PASSOU, O QUE FAZER?');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;

ELSIF C1.CENARIO  = '0-IGUAIS ULT CONTRATO E ULT HIST ESCALA' AND C1.TRATATIVA  = '0.3-DATA FIM FUTURA, O QUE FAZER DEPOIS QUE VENCER?' AND C1.DT_FIM_TROCA IS NOT NULL THEN
dbms_output.put_line('--(3)0.3-DATA FIM FUTURA, O QUE FAZER DEPOIS QUE VENCER? --VERIFICAR POIS PARECE PROCEDER');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');

ELSIF C1.CENARIO = '1-SEM ESCALA NO ULTIMO CONTRATO' AND C1.TRATATIVA  = '1-AJUSTAR MANUALMENTE' THEN
dbms_output.put_line('--(4)FAZER NADA--1-AJUSTAR MANUALMENTE');
dbms_output.put_line('--CODIGO_EMPRESA: '|| C1.CODIGO_EMPRESA ||' TIPO_CONTRATO: '|| C1.TIPO_CONTRATO ||' CODIGO_CONTRATO: '|| C1.BM);

ELSIF C1.CENARIO = '2-SEM HISTORICO DE ESCALA' AND C1.TRATATIVA  = '2.1-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA NO CONTRATO' THEN
--dbms_output.put_line('--(5)2.1-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA NO CONTRATO');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''||C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
dbms_output.put_line('--(5)FAZER NADA--1-AJUSTAR MANUALMENTE');
dbms_output.put_line('--CODIGO_EMPRESA: '|| C1.CODIGO_EMPRESA ||' TIPO_CONTRATO: '|| C1.TIPO_CONTRATO ||' CODIGO_CONTRATO: '|| C1.BM);

ELSIF C1.CENARIO = '2-SEM HISTORICO DE ESCALA' AND C1.TRATATIVA = '2.2-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA DO EFETIVO EXERCICIO E GRAVAR DT_ULT_ESCALA NO CONTRATO' and C1.DATA_EFETIVO_EXERC IS NOT NULL THEN
dbms_output.put_line('--(6)2.2-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA DO EFETIVO EXERCICIO E GRAVAR DT_ULT_ESCALA NO CONTRATO');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DATA_EFETIVO_EXERC ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.BM, TO_DATE(C1.DATA_EFETIVO_EXERC,'DD/MM/YYYY'), C1.COD_ESCALA_ULT_CONTRATO,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO = '2-SEM HISTORICO DE ESCALA' AND C1.TRATATIVA = '2.2-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA DO EFETIVO EXERCICIO E GRAVAR DT_ULT_ESCALA NO CONTRATO' and C1.DATA_EFETIVO_EXERC IS NULL THEN
dbms_output.put_line('--(7)2.2-CRIAR HISTORICO COM DATA_INICIO IGUAL A DATA DA ADMISSAO E GRAVAR DT_ULT_ESCALA NO CONTRATO');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DATA_ADMISSAO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.BM, TO_DATE(C1.DATA_ADMISSAO,'DD/MM/YYYY'), C1.COD_ESCALA_ULT_CONTRATO,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO IN ('3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO')
and C1.TIPO_AJUSTE_HIST_EXISTENTE = 'GRAVAR DATA CONTRATO NA FIM' THEN
dbms_output.put_line('--(8)3/4/5-CODIGO E/OU DATA ESCALA DIVERGE DO CONTRATO E HISTORICO > SEGUIR A ESCALA DO CONTRATO, GRAVAR DATA CONTRATO NA FIM EXISTENTE E CRIA NOVA');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = TO_DATE('''||C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY'')-1 WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY')-1 WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;
INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.BM, TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY'), C1.COD_ESCALA_ULT_CONTRATO,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO IN ('3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO')
and C1.TIPO_AJUSTE_HIST_EXISTENTE = 'DIMINUIR DATA FIM DT CONTRATO-1 DIA' THEN
dbms_output.put_line('--(9)3/4/5-CODIGO E/OU DATA ESCALA DIVERGE DO CONTRATO E HISTORICO > SEGUIR A ESCALA DO CONTRATO, DIMINUIR DATA FIM DT CONTRATO-1 DIA NA EXISTENTE E CRIA NOVA');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = TO_DATE('''||C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY'')-1 WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY')-1 WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;
INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA ,C1.TIPO_CONTRATO ,C1.BM , TO_DATE(C1.DT_ULT_ESCALA_CONTRATO ,'DD/MM/YYYY'), C1.COD_ESCALA_ULT_CONTRATO ,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO IN ('3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO')
and C1.TIPO_AJUSTE_HIST_EXISTENTE = 'AUMENTAR DATA FIM DT CONTRATO-1 DIA' THEN
dbms_output.put_line('--(10)3/4/5-CODIGO E/OU DATA ESCALA DIVERGE DO CONTRATO E HISTORICO > SEGUIR A ESCALA DO CONTRATO, AUMENTAR DATA FIM DT CONTRATO-1 DIA NA EXISTENTE E CRIA NOVA');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = TO_DATE('''||C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY'')-1 WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY')-1 WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;
INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA ,C1.TIPO_CONTRATO ,C1.BM , TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY'), C1.COD_ESCALA_ULT_CONTRATO,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO IN ('3-CODIGO E DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','4-DATA ESCALA DIVERGE DO CONTRATO E HISTORICO','5-CODIGO ESCALA DIVERGE DO CONTRATO E HISTORICO')
and C1.TIPO_AJUSTE_HIST_EXISTENTE = 'EXCLUIR HISTORICO E CRIAR NOVO' THEN
dbms_output.put_line('--(11)3/4/5-CODIGO E/OU DATA ESCALA DIVERGE DO CONTRATO E HISTORICO > SEGUIR A ESCALA DO CONTRATO, EXCLUIR HISTORICO E CRIAR NOVO');
--dbms_output.put_line('DELETE RHPONT_ALT_ESCALA WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.BM ||''', TO_DATE('''|| C1.DT_ULT_ESCALA_CONTRATO ||''',''DD/MM/YYYY''), '''|| C1.COD_ESCALA_ULT_CONTRATO ||''',''S'', sysdate, ''script_ajuste_escala''); COMMIT;');
--DELETE RHPONT_ALT_ESCALA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA, 'DD/MM/YYYY'); COMMIT;
--INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values(C1.CODIGO_EMPRESA , C1.TIPO_CONTRATO, C1.BM , TO_DATE(C1.DT_ULT_ESCALA_CONTRATO,'DD/MM/YYYY'),C1.COD_ESCALA_ULT_CONTRATO,'S', sysdate, 'script_ajuste_escala'); COMMIT;

ELSIF C1.CENARIO = '6-CODIGO ESCALA IGUAL SEM DATA NO CONTRATO' THEN
dbms_output.put_line('--(12)6-GRAVAR DATA INICIO HISTORICO NO CONTRATO E LIMPA DATA FIM ');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('UPDATE RHPESS_CONTRATO SET /*C.CODIGO_ESCALA=*/ DT_ULT_ESCALA = TO_DATE('''||C1.DT_INICIO_TROCA||''',''DD/MM/YYYY''), DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO= ''script_ajuste_escala'' WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = ''' || C1.TIPO_CONTRATO || ''' AND CODIGO = ''' || C1.BM ||''' AND TRUNC(ANO_MES_REFERENCIA) = TO_DATE('''||vDATA_SISTEMA||''',''DD/MM/YYYY''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = NULL WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;
UPDATE RHPESS_CONTRATO SET  DT_ULT_ESCALA = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'), DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO= 'script_ajuste_escala' WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO =  C1.BM AND TRUNC(ANO_MES_REFERENCIA) = TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY'); COMMIT;

ELSIF C1.CENARIO = '7-CODIGO ESCALA DIFERENTE E SEM DATA NO CONTRATO' THEN
dbms_output.put_line('--(13)6-GRAVAR DATA INICIO HISTORICO NO CONTRATO E TROCAR CODIGO ESCALA NO HISTORICO E LIMPA DATA FIM');
--dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = ''script_ajuste_escala'', DT_FIM_TROCA = NULL, COD_ESCALA = '''||C1.COD_ESCALA_ULT_CONTRATO ||''' WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = '''|| C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DT_INICIO_TROCA) = TO_DATE('''|| C1.DT_INICIO_TROCA ||''',''DD/MM/YYYY''); COMMIT;');
--dbms_output.put_line('UPDATE RHPESS_CONTRATO SET /*C.CODIGO_ESCALA=*/ DT_ULT_ESCALA = TO_DATE('''||C1.DT_INICIO_TROCA||''',''DD/MM/YYYY''), DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO= ''script_ajuste_escala'' WHERE CODIGO_EMPRESA = '''|| C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = ''' || C1.TIPO_CONTRATO || ''' AND CODIGO = ''' || C1.BM ||''' AND TRUNC(ANO_MES_REFERENCIA) = TO_DATE('''||vDATA_SISTEMA||''',''DD/MM/YYYY''); COMMIT;');
UPDATE RHPONT_ALT_ESCALA SET DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO = 'script_ajuste_escala', DT_FIM_TROCA = NULL, COD_ESCALA = C1.COD_ESCALA_ULT_CONTRATO  WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO =  C1.TIPO_CONTRATO AND CODIGO_CONTRATO =  C1.BM AND TRUNC(DT_INICIO_TROCA) = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'); COMMIT;
UPDATE RHPESS_CONTRATO SET  DT_ULT_ESCALA = TO_DATE(C1.DT_INICIO_TROCA,'DD/MM/YYYY'), DT_ULT_ALTER_USUA = SYSDATE, LOGIN_USUARIO= 'script_ajuste_escala' WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.BM AND TRUNC(ANO_MES_REFERENCIA) = TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY'); COMMIT;

END IF;
--fim---------------------2º passo ---------------------------------------------ajustes no historico de escala e contrato-------------------------------------
--*/

EXCEPTION WHEN OTHERS THEN
err_msg := SQLCODE||' '||SUBSTR(SQLERRM, 1, 4000);
dbms_output.put_line('err_msg:' ||err_msg);

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_2, CAMPO_VALOR_1,  DATA_DADOS, CONSIDERACOES)
VALUES(C1.CODIGO_EMPRESA,C1.TIPO_CONTRATO , C1.BM,C1.DT_INICIO_TROCA, 'LOG EXECUCAO PROCEDURE PR_ACERTOS_HIST_ESCALA_CONTR', SYSDATE, err_msg
);COMMIT;
END;--BEGIN EXCEPTION

err_msg := NULL;

END LOOP;
END;
END;