
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_ATUALIZAR_SIT_FUNC" 
AS
  vDATA_SISTEMA date;
  vIsTrue VARCHAR2(2000);
  vERRO VARCHAR2(2000);
  vDATA_MAX_SIT date;

/*
Para atender o Protocolo de número 3596/2022
*/



BEGIN 

  FOR C1 IN
  (
    SELECT ID, CODIGO_EMPRESA,TIPO_CONTRATO,LPAD(REPLACE(CODIGO_CONTRATO,' ',''),15,'0') CONTRATO,
    DATA_INIC_SITUACAO ,DATA_FIM_SITUACAO , SITUACAO_FUNCIONAL
    FROM ARTERH.RHPBH_APOIO_SIT_FUNC

    WHERE PROCESSADO = 'N' 
 --   and codigo_contrato in ('00000000092379X', '000000001030726', '000000001048684', '000000000969374')
    AND DATA_EXECUCAO IS NULL 

    ORDER BY CODIGO_EMPRESA,TIPO_CONTRATO, CONTRATO, DATA_INIC_SITUACAO
  )
  LOOP
  dbms_output.enable(NULL);

  /*--------------------------------------------------------------------- AÇÕES DE CONFERENCIA NA BASE --------------------------------------------------------------------- */


   DBMS_Output.PUT_LINE('----- CODIGO_EMPRESA: '||C1.CODIGO_EMPRESA||'--- TIPO_CONTRATO: '||C1.TIPO_CONTRATO||'--- CONTRATO: '||C1.CONTRATO);
BEGIN
    BEGIN
    select DATA_DO_SISTEMA into vDATA_SISTEMA from RHPARM_P_SIST;   
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    vERRO := 'ERRO NO MOMENTO DE OBTER A DATA DO SISTEMA. ';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
   -- raise_application_error (-20003, vERRO || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM );
    WHEN OTHERS THEN
    vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
    -- DBMS_Output.PUT_LINE(vERRO);
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    END;

     vIsTrue:=NULL;

    BEGIN
    select codigo into vIsTrue from RHPESS_CONTRATO WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO =C1.CONTRATO AND ANO_MES_REFERENCIA =   (SELECT MAX(ANO_MES_REFERENCIA)   FROM RHPESS_CONTRATO AUX   WHERE AUX.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA   AND AUX.TIPO_CONTRATO    = RHPESS_CONTRATO.TIPO_CONTRATO  AND AUX.CODIGO           = RHPESS_CONTRATO.CODIGO   )  ;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    vERRO := 'CONTRATO NÃO EXISTE. ';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    WHEN OTHERS THEN
    vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
    -- DBMS_Output.PUT_LINE(vERRO);
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    END;

     vIsTrue:=NULL;


    BEGIN
    select * into vIsTrue from DUAL WHERE C1.DATA_INIC_SITUACAO <= C1.DATA_FIM_SITUACAO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    vERRO := 'DATA INICIO NÃO É MENOR QUE DATA FIM';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    WHEN OTHERS THEN
    vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
    -- DBMS_Output.PUT_LINE(vERRO);
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    END;

     vIsTrue:=NULL;


    BEGIN
    select codigo into vIsTrue from RHPESS_CONTRATO WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO =C1.CONTRATO AND ANO_MES_REFERENCIA =   (SELECT MAX(ANO_MES_REFERENCIA)   FROM RHPESS_CONTRATO AUX   WHERE AUX.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA   AND AUX.TIPO_CONTRATO    = RHPESS_CONTRATO.TIPO_CONTRATO  AND AUX.CODIGO = RHPESS_CONTRATO.CODIGO   AND AUX.ANO_MES_REFERENCIA <= C1.DATA_INIC_SITUACAO)  ;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    vERRO := 'NAO EXISTE CONTRATO MENOR OU IGUAL DATA DE INICIO ';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    WHEN OTHERS THEN
    vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
    -- DBMS_Output.PUT_LINE(vERRO);
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    END;

     vIsTrue:=NULL; 

    BEGIN
    select CODIGO into vIsTrue FROM RHPARM_SIT_FUNC WHERE CODIGO= C1.SITUACAO_FUNCIONAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    vERRO := 'SITUACAO_FUNCIONAL NÃO EXISTE. ';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    WHEN OTHERS THEN
    vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
    -- DBMS_Output.PUT_LINE(vERRO);
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
    END;

     vIsTrue:=NULL; 

  /* FOR C3 IN    
    ( 
    SELECT CODIGO_EMPRESA,TIPO_CONTRATO, CODIGO_CONTRATO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO FROM ARTERH.RHPBH_APOIO_SIT_FUNC 
    WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CONTRATO 
    AND DATA_FIM_SITUACAO > TO_DATE(C1.DATA_FIM_SITUACAO,'DD/MM/YYYY')
    AND ROWNUM=1
    ORDER BY CODIGO_EMPRESA,TIPO_CONTRATO, CODIGO_CONTRATO, DATA_INIC_SITUACAO
    )    
    LOOP
    DBMS_Output.PUT_LINE('ENTROU');

    IF ( TO_DATE(C3.DATA_INIC_SITUACAO,'DD/MM/YYYY') <> TO_DATE(C1.DATA_FIM_SITUACAO,'DD/MM/YYYY')+1 ) THEN
      --DBMS_Output.PUT_LINE('DATA_INIC_SITUACAO: '||C3.DATA_INIC_SITUACAO || '-- DATA_FIM_SITUACAO : ' ||  C1.DATA_FIM_SITUACAO );
        vERRO := 'CONFERIR HISTORICO. ';
        EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');

    END IF;



    END LOOP; 
  */  
    SELECT DISTINCT DATA_FIM_SITUACAO INTO vDATA_MAX_SIT FROM ARTERH.RHPBH_APOIO_SIT_FUNC 
    WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CONTRATO 
    AND DATA_INIC_SITUACAO = (
    select MAX(AUX.DATA_INIC_SITUACAO) from ARTERH.RHPBH_APOIO_SIT_FUNC aux
    where RHPBH_APOIO_SIT_FUNC.CODIGO_EMPRESA = aux.CODIGO_EMPRESA 
    AND RHPBH_APOIO_SIT_FUNC.TIPO_CONTRATO = aux.TIPO_CONTRATO 
    AND RHPBH_APOIO_SIT_FUNC.CODIGO_CONTRATO = aux.CODIGO_CONTRATO 
    )
    ;

    DBMS_Output.PUT_LINE('DATA_FIM_SITUACAO MAX: ' || vDATA_MAX_SIT );
    IF vDATA_MAX_SIT <= SYSDATE THEN

        BEGIN
        SELECT cod_sit_funcional INTO vIsTrue FROM RHCGED_ALT_SIT_FUN
        WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.CONTRATO 
        AND data_inic_situacao = to_date(vDATA_MAX_SIT,'dd/mm/yyyy')+1;

        EXCEPTION
        WHEN NO_DATA_FOUND THEN
        vERRO := 'OLHAR HISTÓRICO POIS NÃO TEM SIT POSTERIOR A DATA FIM';
        EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
        WHEN OTHERS THEN
        vERRO := 'ENCONTRADO ERRO - '||SQLCODE|| ' -ERROR- '||SQLERRM||'';
        -- DBMS_Output.PUT_LINE(vERRO);
        EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROBLEMA = PROBLEMA ||'''||vERRO||''' WHERE ID = '''||C1.ID||'''');
        END;

    END IF;

 EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET DATA_EXECUCAO = SYSDATE WHERE PROCESSADO = ''N'' AND DATA_EXECUCAO IS NULL AND  ID = '|| C1.ID);

    UPDATE RHCGED_ALT_SIT_FUN SET cod_sit_funcional = C1.SITUACAO_FUNCIONAL, LOGIN_USUARIO = 'PR_ATUALIZAR_SIT_FUNC(3596/2022)', dt_ult_alter_usua = sysdate
    WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.CONTRATO 
    AND DATA_INIC_SITUACAO = to_date(C1.DATA_INIC_SITUACAO,'dd/mm/yyyy') AND DATA_FIM_SITUACAO = to_date(C1.DATA_FIM_SITUACAO,'dd/mm/yyyy')
    ;
    vERRO := ' --- UPDATE REALIZADO NA SITUACAO_FUNCIONAL --- ';
    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET ACAO_REALIZADA = ACAO_REALIZADA ||'''||vERRO||''' WHERE ID = '|| C1.ID);


    --arterh.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CONTRATO, 'PR_ATUALIZAR_SIT_FUNC(3596/2022)') ;


END;

END LOOP;
  vIsTrue:=NULL; 



 FOR C2 IN
  (
    SELECT DISTINCT RHPESS_CONTRATO.CODIGO_EMPRESA,RHPESS_CONTRATO.TIPO_CONTRATO,LPAD(REPLACE(RHPBH_APOIO_SIT_FUNC.CODIGO_CONTRATO,' ',''),15,'0') CONTRATO, RHPESS_CONTRATO.SITUACAO_FUNCIONAL    
    FROM ARTERH.RHPBH_APOIO_SIT_FUNC
    INNER JOIN ARTERH.RHPESS_CONTRATO
    ON RHPESS_CONTRATO.CODIGO_EMPRESA = RHPBH_APOIO_SIT_FUNC.CODIGO_EMPRESA 
    AND RHPESS_CONTRATO.TIPO_CONTRATO = RHPBH_APOIO_SIT_FUNC.TIPO_CONTRATO 
    AND RHPESS_CONTRATO.CODIGO = LPAD(REPLACE(RHPBH_APOIO_SIT_FUNC.CODIGO_CONTRATO,' ',''),15,'0')
    WHERE TRUNC(RHPBH_APOIO_SIT_FUNC.DATA_EXECUCAO) = TRUNC(SYSDATE)
  -- AND RHPBH_APOIO_SIT_FUNC.CODIGO_CONTRATO in ('00000000092379X', '000000001030726', '000000001048684', '000000000969374')
    AND RHPESS_CONTRATO.ANO_MES_REFERENCIA =
  ( SELECT MAX(ANO_MES_REFERENCIA)
  FROM RHPESS_CONTRATO AUX
  WHERE AUX.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA
  AND AUX.TIPO_CONTRATO    = RHPESS_CONTRATO.TIPO_CONTRATO
  AND AUX.CODIGO           = RHPESS_CONTRATO.CODIGO
  AND AUX.ANO_MES_REFERENCIA <= vDATA_SISTEMA
  )
  AND RHPESS_CONTRATO.SITUACAO_FUNCIONAL in ('1400', '1401', '1402','1450', '5300')
    ORDER BY CODIGO_EMPRESA,TIPO_CONTRATO, CONTRATO
  ) 
  LOOP  
  vIsTrue:=NULL; 
BEGIN
    SELECT cod_sit_funcional INTO vIsTrue FROM RHCGED_ALT_SIT_FUN
    WHERE CODIGO_EMPRESA = C2.CODIGO_EMPRESA AND TIPO_CONTRATO = C2.TIPO_CONTRATO AND CODIGO = C2.CONTRATO   
    AND DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO)FROM RHCGED_ALT_SIT_FUN AUX
    WHERE  RHCGED_ALT_SIT_FUN.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND RHCGED_ALT_SIT_FUN.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND RHCGED_ALT_SIT_FUN.CODIGO = AUX.CODIGO)
    AND cod_sit_funcional in ('1407', '1408', '1409','1456', '5303');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_Output.PUT_LINE('CONTRATO NÃO SERÁ ATUALIZADO');
    END;

  IF (  (C2.SITUACAO_FUNCIONAL  = '1400' AND vIsTrue  = '1407') or
        (C2.SITUACAO_FUNCIONAL  = '1401' AND vIsTrue  = '1408') or
        (C2.SITUACAO_FUNCIONAL  = '1402' AND vIsTrue  = '1409') or
        (C2.SITUACAO_FUNCIONAL  = '1450' AND vIsTrue  = '1456') or
        (C2.SITUACAO_FUNCIONAL  = '5300' AND vIsTrue  = '5303')   
  )
  THEN

        FOR C1 IN
          (
        select RHPESS_CONTRATO.CODIGO, RHPESS_CONTRATO.CODIGO_EMPRESA, RHPESS_CONTRATO.TIPO_CONTRATO, 
        RHPESS_CONTRATO.ANO_MES_REFERENCIA,
        C.ANO_MES_REFERENCIA as ANO_MES_REFERENCIA_AUX,
        ( select COUNT(1) from RHPESS_CONTRATO_AUX B where 
        B.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA AND
        B.TIPO_CONTRATO = RHPESS_CONTRATO.TIPO_CONTRATO AND
        B.CODIGO = RHPESS_CONTRATO.CODIGO )  CONTAGEM_AUX
        from rhpess_contrato 
        LEFT JOIN ( select * from RHPESS_CONTRATO_AUX B where 
          B.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO_AUX AUX
            WHERE AUX.CODIGO_EMPRESA  = B.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO     = B.TIPO_CONTRATO
            AND AUX.CODIGO            = B.CODIGO
            )
            ) C
          ON rhpess_contrato.CODIGO = C.CODIGO
          AND rhpess_contrato.CODIGO_EMPRESA = C.CODIGO_EMPRESA
          AND rhpess_contrato.TIPO_CONTRATO = C.TIPO_CONTRATO
        where RHPESS_CONTRATO.CODIGO_EMPRESA = C2.CODIGO_EMPRESA AND RHPESS_CONTRATO.TIPO_CONTRATO = C2.TIPO_CONTRATO 
        AND RHPESS_CONTRATO.CODIGO = C2.CONTRATO 
        AND RHPESS_CONTRATO.ANO_MES_REFERENCIA =
          (SELECT MAX(ANO_MES_REFERENCIA)
          FROM RHPESS_CONTRATO AUX
          WHERE AUX.CODIGO_EMPRESA = RHPESS_CONTRATO.CODIGO_EMPRESA
          AND AUX.TIPO_CONTRATO    = RHPESS_CONTRATO.TIPO_CONTRATO
          AND AUX.CODIGO           = RHPESS_CONTRATO.CODIGO
          )

          )
          LOOP
            IF (TRUNC(TO_DATE(C1.ANO_MES_REFERENCIA,'DD/MM/YYYY')) < TRUNC(TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY'))) THEN
              INSERT INTO RHPESS_CONTRATO C SELECT CODIGO_EMPRESA,TIPO_CONTRATO,  CODIGO,  CODIGO_PESSOA,  NOME,  REGISTRO,  NUMERO_ARQUIVO,  SITUACAO_FUNCIONAL,  SITUACAO_CONTRATO,  STATUS_CONTRATO,  DATA_ADMISSAO, MOTIVO_ADMISSAO,  MOTIVO_DEMISSAO,  TIPO_PAGAMENTO,  TIPO_SALARIO,  VINCULO,  FORMA_PROVIMENTO,  COD_LOCAL1,  COD_LOCAL2,  COD_LOCAL3,  COD_LOCAL4,  COD_LOCAL5,  COD_LOCAL6,  DT_ULT_ALT_LOC,  COD_UNIDADE1,  COD_UNIDADE2,  COD_UNIDADE3,  COD_UNIDADE4,  COD_UNIDADE5,  COD_UNIDADE6,  DT_ULT_ALT_UNID,  COD_CUSTO_CONTAB1,  COD_CUSTO_CONTAB2,  COD_CUSTO_CONTAB3,  COD_CUSTO_CONTAB4,  COD_CUSTO_CONTAB5,  COD_CUSTO_CONTAB6,  DT_ULT_ALT_CONT,  COD_CUSTO_GERENC1,  COD_CUSTO_GERENC2,  COD_CUSTO_GERENC3,  COD_CUSTO_GERENC4,  COD_CUSTO_GERENC5,  COD_CUSTO_GERENC6,  DT_ULT_ALT_GER,  SALARIO_PAGTO,  COD_CARGO_PAGTO,  NIVEL_CARGO_PAGTO,  COD_CARGO_EFETIVO,  NIVEL_CARGO_EFETIV,  DT_ULT_CARGO_EFET,  COD_CARGO_COMISS,  NIVEL_CARGO_COMISS,  DT_ULT_CARGO_COM,  COD_CARGO_AMPAR,  NIVEL_CARGO_AMPAR,  DT_ULT_CARGO_AMPAR,  CODIGO_FUNCAO,  DT_ULT_FUNCAO,  COD_ESPECIALIDADE,  DT_ULT_ESPEC,  CODIGO_VAGA,  DT_ULT_VAGA,  AREA_ATUACAO,  CATEG_PROFISSIONAL,  CODIGO_ESCALA,  REGISTRO_PONTO,  DT_ULT_ESCALA,  CODIGO_BANCO_CC,  CONTA_CORRENTE,  CODIGO_BANCO_FGTS,  CONTA_FGTS,  DATA_OPCAO_FGTS,  DATA_RETROACAO,  DATA_RETRATACAO,  COD_SINDICATO,  NIVEL_SINDICATO,  DT_ULT_SINDICATO,  DESC_CONTRIB_SIND,  SINDICALIZADO,  INSCRICAO_INSS,  COD_MOVIMENTACAO,  DATA_TRANSF_ENTRAD,  DATA_PRI_ADMISSAO,  DATA_REINTEGRACAO,  DATA_EFETIVO_EXERC,  DATA_POSSE,  DATA_NOMEACAO,  DATA_INICIO_ESTAB,  DATA_FIM_ESTAB,  DT_FIM_CONTR_EXP,  DT_FIM_CONTR_DETER,  DATA_FIM_RENOV_EXP,  DATA_AV_PREVIO,  DATA_RESCISAO,  CAUSA_RESCISAO,  DATA_INIC_AFAST,  DATA_FIM_AFAST,  NRO_MESES_AFAST,  CTRL_VERBAS,  FORMA_PAGAMENTO,  DATA_BASE_FERIAS,  DATA_INIC_GOZO,  DATA_FIM_GOZO,  DEPENDENTES_SF,  DEPENDENTES_IRRF,  COD_PROCURADOR,  DATA_PAGTO_CALCULO,  DATA_PAGTO_ADIANT,  DATA_PAGTO_FERIAS,  DATA_PAGTO_13SAL,  DATA_PAGTO_RESCISA,  SAL_CONT_EFETIVO,  DT_ULT_SAL_C_EFET,  SAL_CONT_COMISSION,  DT_ULT_SAL_C_COM,  SAL_CONT_AMPAR,  DT_ULT_SAL_C_AMP,  SAL_AUX_EFETIVO,  DT_ULT_SAL_A_EFET,  SAL_AUX_COMISSION,  DT_ULT_SAL_A_COM,  SAL_AUX_AMPAR,  DT_ULT_SAL_A_AMP,  C_LIVRE_SELEC01,  C_LIVRE_SELEC02,  C_LIVRE_SELEC03,  C_LIVRE_SELEC04,  C_LIVRE_SELEC05,  C_LIVRE_SELEC06,  C_LIVRE_SELEC07,  C_LIVRE_SELEC08,  C_LIVRE_SELEC09,  C_LIVRE_SELEC10,  C_LIVRE_SELEC11,  C_LIVRE_SELEC12,  C_LIVRE_SELEC13,  C_LIVRE_SELEC14,  C_LIVRE_SELEC15,  C_LIVRE_SELEC36,  C_LIVRE_SELEC37,  C_LIVRE_SELEC38,  C_LIVRE_SELEC39,  C_LIVRE_SELEC40,  C_LIVRE_VALOR16,  C_LIVRE_VALOR17,  C_LIVRE_VALOR18,  C_LIVRE_VALOR19,  C_LIVRE_VALOR20,  C_LIVRE_VALOR21,  C_LIVRE_VALOR22,  C_LIVRE_VALOR23,  C_LIVRE_DESCR24,  C_LIVRE_DESCR25,  C_LIVRE_DESCR26,  C_LIVRE_DESCR27,  C_LIVRE_DATA28,  C_LIVRE_DATA29,  C_LIVRE_DATA30,  C_LIVRE_DATA31,  C_LIVRE_DATA32,  C_LIVRE_DATA33,  C_LIVRE_DATA34,  C_LIVRE_DATA35,  C_LIVRE_OPCAO41,  C_LIVRE_OPCAO42,  C_LIVRE_OPCAO43,  C_LIVRE_OPCAO44,  C_LIVRE_OPCAO45,  C_LIVRE_OPCAO46,  C_LIVRE_OPCAO47,  C_LIVRE_OPCAO48,  INDIC_ALTERAC1,  INDIC_ALTERAC2,  INDIC_ALTERAC3,  INDIC_ALTERAC4,  INDIC_ALTERAC5,  TEXTO_ASSOCIADO,  LOGIN_USUARIO,  DT_ULT_ALTER_USUA,  TELEFONE,  TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY') ANO_MES_REFERENCIA,  DATA_APOSENTA_FGTS,  REABILITADO,  C_LIVRE_VALOR49,  C_LIVRE_VALOR50,  C_LIVRE_VALOR51,  C_LIVRE_VALOR52,  C_LIVRE_VALOR53,  C_LIVRE_VALOR54,  C_LIVRE_VALOR55,  C_LIVRE_VALOR56,  C_LIVRE_DATA57,  C_LIVRE_DATA58,  C_LIVRE_DATA59,  C_LIVRE_DATA60,  C_LIVRE_DATA61,  C_LIVRE_DATA62,  C_LIVRE_DATA63,  C_LIVRE_DATA64,  C_LIVRE_OPCAO65,  C_LIVRE_OPCAO66,  C_LIVRE_OPCAO67,  C_LIVRE_OPCAO68,  INDIC_ALTERAC6,  CLASSE_CONT_INSS,  E_MAIL,  USA_ASSOC_CONT_ESC,  CLASSIFICACAO_CAND,  NUMERO_EDITAL,  TIPO_AGRUP_UNID,  TIPO_AGRUP_CONT,  TIPO_AGRUP_CGER,  TIPO_AGRUP_LOTA,  NOME_ACESSO,  CODIGO_SOLICITACAO,  ID_CONTR_FORN,  FUNC_COMP_EMPR_AV,  DT_MOLESTIA_GRAVE,  SAL_CONT_FUNCAO,  DT_ULT_SAL_C_FUN,  SAL_AUX_FUNCAO,  DT_ULT_SAL_A_FUN,  DATA_PROJ_AV_PREV,  DT_PROJ_AFAST_ESOCIAL,  TP_AVISO_PREVIO_ESOCIAL,  TP_CONTA_BANCARIA,  DT_PROC_ESOCIAL,  DT_ALTER_ESOCIAL,  DT_CANC_AVISO_PREVIO,  MOT_CANC_AV_PREV_ESOCIAL,  DESC_SAL_VARIAVEL,  MOTIVO_CONTRATACAO,  CPF_TRAB_SUBSTITUIDO,  MATRIC_TRAB_SUBSTITUIDO,  IND_SEGURO_DESEMPREGO,  DT_GERACAO_CAGED,  OBS_RESCISAO,  DT_FIM_QUARENTENA,  CNPJ_EMPRESA_SUCESSORA,  JUST_CONTR_ESOCIAL,  TP_INCL_CONTR_ESOCIAL,  INFO_COTA_ESOCIAL,  CLAUSULA_ASSEC,  DT_ALTERACAO_CONTR,  DT_EFEITO_ALTER_CONTR,  DESC_ALTER_CONTR,  IND_CUMPR_PARC_AV,  CODIGO_CONTR_ANTERIOR,  CPF_ANTERIOR,  DATA_ALTER_CPF,  OBS_ALTER_CPF,  TEM_ALTER_CPF,  INFO_COTA_RACA,  MATRICULA_ESOCIAL, CONSELHO_REGIONAL, INSCRICAO_CONSELHO,  UF_CONSELHO , COD_CARREIRA, COD_EIXO, COD_NIVEL, IND_REMUN, IND_PDV FROM RHPESS_CONTRATO C WHERE C.codigo_empresa   = C1.CODIGO_EMPRESA AND C.tipo_contrato      = C1.TIPO_CONTRATO AND C.CODIGO = C1.CODIGO AND C.ano_mes_referencia =  (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX WHERE C.codigo_empresa = AUX.CODIGO_EMPRESA AND C.tipo_contrato = AUX.TIPO_CONTRATO AND C.CODIGO = AUX.CODIGO);
              UPDATE RHPESS_CONTR_MEST SET ULTIMA_DATA = TO_CHAR(vDATA_SISTEMA,'DD/MM/YYYY'), LOGIN_USUARIO = 'PR_ATUALIZAR_SIT_FUNC(3596/2022)', DT_ULT_ALTER_USUA = SYSDATE WHERE CODIGO_EMPRESA   = C1.CODIGO_EMPRESA AND TIPO_CONTRATO      = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO;


            END IF;
            IF(C1.ANO_MES_REFERENCIA_AUX IS NULL AND C1.CONTAGEM_AUX = '0' ) THEN
               INSERT INTO RHPESS_CONTRATO_AUX ( CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, ANO_MES_REFERENCIA, LOGIN_USUARIO, DT_ULT_ALTER_USUA ) VALUES ( C1.CODIGO_EMPRESA , C1.TIPO_CONTRATO, C1.CODIGO, TO_CHAR(vDATA_SISTEMA,'DD/MM/YYYY'),'PR_ATUALIZAR_SIT_FUNC(3596/2022)',SYSDATE );

            ELSIF (TRUNC(TO_DATE(C1.ANO_MES_REFERENCIA_AUX,'DD/MM/YYYY')) < TRUNC(TO_DATE(vDATA_SISTEMA,'DD/MM/YYYY'))) THEN
               INSERT INTO RHPESS_CONTRATO_AUX X SELECT CODIGO_EMPRESA,TIPO_CONTRATO,CODIGO,TO_CHAR(vDATA_SISTEMA,'DD/MM/YYYY') ANO_MES_REFERENCIA,'PR_ATUALIZAR_SIT_FUNC(3596/2022)',SYSDATE,C_LIVRE_AUX_SELEC01,C_LIVRE_AUX_SELEC02,C_LIVRE_AUX_SELEC03,C_LIVRE_AUX_SELEC04,C_LIVRE_AUX_SELEC05,C_LIVRE_AUX_SELEC06,C_LIVRE_AUX_SELEC07,C_LIVRE_AUX_SELEC08,C_LIVRE_AUX_SELEC09,C_LIVRE_AUX_SELEC10,C_LIVRE_AUX_SELEC11,C_LIVRE_AUX_SELEC12,C_LIVRE_AUX_SELEC13,C_LIVRE_AUX_SELEC14,C_LIVRE_AUX_SELEC15,C_LIVRE_AUX_SELEC16,C_LIVRE_AUX_SELEC17,C_LIVRE_AUX_SELEC18,C_LIVRE_AUX_SELEC19,C_LIVRE_AUX_SELEC20,C_LIVRE_AUX_VALOR01,C_LIVRE_AUX_VALOR02,C_LIVRE_AUX_VALOR03,C_LIVRE_AUX_VALOR04,C_LIVRE_AUX_VALOR05,C_LIVRE_AUX_VALOR06,C_LIVRE_AUX_VALOR07,C_LIVRE_AUX_VALOR08,C_LIVRE_AUX_VALOR09,C_LIVRE_AUX_VALOR10,C_LIVRE_AUX_VALOR11,C_LIVRE_AUX_VALOR12,C_LIVRE_AUX_VALOR13,C_LIVRE_AUX_VALOR14,C_LIVRE_AUX_VALOR15,C_LIVRE_AUX_VALOR16,C_LIVRE_AUX_VALOR17,C_LIVRE_AUX_VALOR18,C_LIVRE_AUX_VALOR19,C_LIVRE_AUX_VALOR20,C_LIVRE_AUX_DATA01,C_LIVRE_AUX_DATA02,C_LIVRE_AUX_DATA03,C_LIVRE_AUX_DATA04,C_LIVRE_AUX_DATA05,C_LIVRE_AUX_DATA06,C_LIVRE_AUX_DATA07,C_LIVRE_AUX_DATA08,C_LIVRE_AUX_DATA09,C_LIVRE_AUX_DATA10,C_LIVRE_AUX_DATA11,C_LIVRE_AUX_DATA12,C_LIVRE_AUX_DATA13,C_LIVRE_AUX_DATA14,C_LIVRE_AUX_DATA15,C_LIVRE_AUX_DATA16,C_LIVRE_AUX_DATA17,C_LIVRE_AUX_DATA18,C_LIVRE_AUX_DATA19,C_LIVRE_AUX_DATA20,C_LIVRE_AUX_OPCAO01,C_LIVRE_AUX_OPCAO02,C_LIVRE_AUX_OPCAO03,C_LIVRE_AUX_OPCAO04,C_LIVRE_AUX_OPCAO05,C_LIVRE_AUX_OPCAO06,C_LIVRE_AUX_OPCAO07,C_LIVRE_AUX_OPCAO08,C_LIVRE_AUX_OPCAO09,C_LIVRE_AUX_OPCAO10,C_LIVRE_AUX_OPCAO11,C_LIVRE_AUX_OPCAO12,C_LIVRE_AUX_OPCAO13,C_LIVRE_AUX_OPCAO14,C_LIVRE_AUX_OPCAO15,C_LIVRE_AUX_OPCAO16,C_LIVRE_AUX_OPCAO17,C_LIVRE_AUX_OPCAO18,C_LIVRE_AUX_OPCAO19,C_LIVRE_AUX_OPCAO20,C_LIVRE_AUX_DESCR01,C_LIVRE_AUX_DESCR02,C_LIVRE_AUX_DESCR03,C_LIVRE_AUX_DESCR04,C_LIVRE_AUX_DESCR05,C_LIVRE_AUX_DESCR06,C_LIVRE_AUX_DESCR07,C_LIVRE_AUX_DESCR08,C_LIVRE_AUX_DESCR09,C_LIVRE_AUX_DESCR10,C_LIVRE_AUX_DESCR11,C_LIVRE_AUX_DESCR12,C_LIVRE_AUX_DESCR13,C_LIVRE_AUX_DESCR14,C_LIVRE_AUX_DESCR15,C_LIVRE_AUX_DESCR16,C_LIVRE_AUX_DESCR17,C_LIVRE_AUX_DESCR18,C_LIVRE_AUX_DESCR19,C_LIVRE_AUX_DESCR20,C_LIVRE_AUX_TEXTO01,C_LIVRE_AUX_TEXTO02,C_LIVRE_AUX_TEXTO03,C_LIVRE_AUX_TEXTO04,C_LIVRE_AUX_TEXTO05,C_LIVRE_AUX_TEXTO06,C_LIVRE_AUX_TEXTO07,C_LIVRE_AUX_TEXTO08,C_LIVRE_AUX_TEXTO09,C_LIVRE_AUX_TEXTO10,C_LIVRE_AUX_TEXTO11,C_LIVRE_AUX_TEXTO12,C_LIVRE_AUX_TEXTO13,C_LIVRE_AUX_TEXTO14,C_LIVRE_AUX_TEXTO15,C_LIVRE_AUX_TEXTO16,C_LIVRE_AUX_TEXTO17,C_LIVRE_AUX_TEXTO18,C_LIVRE_AUX_TEXTO19,C_LIVRE_AUX_TEXTO20 FROM RHPESS_CONTRATO_AUX X where X.codigo_empresa = C1.CODIGO_EMPRESA and X.tipo_contrato = C1.TIPO_CONTRATO And X.CODIGO = C1.CODIGO AND X.ano_mes_referencia = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO_aux AUX where X.codigo_empresa = AUX.CODIGO_EMPRESA and X.tipo_contrato = AUX.TIPO_CONTRATO And X.CODIGO = AUX.CODIGO ); 

            END IF;

            UPDATE RHPESS_CONTRATO SET SITUACAO_FUNCIONAL = '1407', LOGIN_USUARIO = 'PR_ATUALIZAR_SIT_FUNC(3596/2022)', dt_ult_alter_usua = sysdate
            WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.CODIGO 
            AND ANO_MES_REFERENCIA = to_date(vDATA_SISTEMA,'dd/mm/yyyy') ;

            vERRO := 'UPDATE REALIZADO NO CONTRATO';
            EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET ACAO_REALIZADA = ACAO_REALIZADA ||'''||vERRO||''' WHERE CODIGO_CONTRATO = '''||C1.CODIGO||'''');


    EXECUTE immediate('UPDATE ARTERH.RHPBH_APOIO_SIT_FUNC SET PROCESSADO = ''S'' WHERE CODIGO_CONTRATO = '''||C1.CODIGO||'''');

  END LOOP;  


  END IF;

  END LOOP;    

END;