
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_ACERTO_DATA_ADMISSAO_1BM" (COD_EMPR IN VARCHAR2,TP_CONTR IN VARCHAR2, COD_CONTR IN VARCHAR2,DT_BASE IN VARCHAR2, DT_FIM_CONTR IN VARCHAR2,MES_REF IN VARCHAR2) AS
--MARCOS --> CRIACAO 22/09/2022
/*OBJETIVO
APOIAR ALTERAÇÃO DE DATA ADMISSÃO PARA RECÉM CONTRATADOS
EXECUTE PR_ACERTO_DATA_ADMISSAO_1BM ('0001','0001', '000000003128707','29/09/2022','','01/09/2022');
*/
BEGIN
  DECLARE
    VCONT               NUMBER;
    VDATA_BASE          varchar(10);
    VANO_MES_REFERENCIA varchar(10);
    VDT_FIM_CONTR_DETER varchar(10);
    VTAMANHO            NUMBER;
    VCODIGO             VARCHAR2(15);
    VCODIGO_VALIDA      VARCHAR2(15);
    VCONT_VALIDA        NUMBER;
    VLOGIN_USUARIO      VARCHAR2(60);
    VCODIGO_EMPRESA     VARCHAR2(4);
    VTIPO_CONTRATO      VARCHAR2(4);
  BEGIN
    dbms_output.enable(NULL);
    /*
    ALTERAR AS VARIÁVEIS ABAIXO PARA SETAR OS VALORES
    DATA_BASE --> DATA_ADMISSÃO
    VDT_FIM_CONTR_DETER --> QUANDO_ENVIADA
    VCODIGO_EMPRESA E VTIPO_CONTRATO
    VLOGIN_USUARIO  --> CONTRANDO O LOGIN + NUMERO CHAMADO DE SOLCITAÇÃO
    VANO_MES_REFERENCIA --> PARA CONTROLE DO CONTRATO MESTRE
    */

    VLOGIN_USUARIO      := 'prcp1329446-2183/2023';
    VCODIGO_EMPRESA     :='0001';
    VCODIGO             :=lpad('305867',15,0);
    VTIPO_CONTRATO      :='0098';
    VDATA_BASE          :='23/07/1986';
    VDT_FIM_CONTR_DETER :=null;
    VANO_MES_REFERENCIA :='01/09/2023';
    VCONT               :=0;


     SELECT COUNT(CODIGO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPESS_CONTRATO
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO           = VCODIGO;


    IF VCONT_VALIDA <> 1 THEN --APENAS UM CONTRATO PODEMOS SEGUIR
      dbms_output.put_line('TOTAL DE CONTRATOS --> '||VCONT);
      dbms_output.put_line('DATA_BASE --> '||VDATA_BASE);
      dbms_output.put_line( CHR(13));
      /* RHPESS_CONTRATO  */
      IF VDT_FIM_CONTR_DETER IS NOT NULL THEN
        dbms_output.put_line('DATA_FIM_CONTRATO_DETER --> '||VDT_FIM_CONTR_DETER);
        dbms_output.put_line('--RHPESS_CONTRATO');
        dbms_output.put_line('UPDATE RHPESS_CONTRATO SET  DATA_ADMISSAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''),DT_ULT_ESCALA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''),  DT_ULT_ALT_LOC = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DATA_BASE_FERIAS = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_FIM_CONTR_DETER = TO_DATE('''||VDT_FIM_CONTR_DETER||''',''DD/MM/YYYY''), DT_ULT_ALT_UNID = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ALT_GER = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ALT_CONT = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_CARGO_AMPAR = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_CARGO_COM = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DATA_PRI_ADMISSAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''' ;');
      ELSE
        dbms_output.put_line('SEM DATA FIM');
        dbms_output.put_line('--RHPESS_CONTRATO');
        dbms_output.put_line('UPDATE RHPESS_CONTRATO SET  DATA_ADMISSAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ESCALA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ALT_LOC = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DATA_BASE_FERIAS = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''),  DT_ULT_ALT_UNID = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ALT_GER = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_ALT_CONT = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_CARGO_AMPAR = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DT_ULT_CARGO_COM = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), DATA_PRI_ADMISSAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''' ;');
      END IF;
      dbms_output.put_line( CHR(13));
      /* RHPESS_CONTR_MEST  */
      dbms_output.put_line('--RHPESS_CONTR_MEST');
      dbms_output.put_line('UPDATE RHPESS_CONTR_MEST SET  DATA_ADMISSAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE), ULTIMA_DATA  = TO_DATE('''||VANO_MES_REFERENCIA||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''' ;');
      dbms_output.put_line( CHR(13));
      /* RHCGED_ALT_SIT_FUN  */
      SELECT COUNT(CODIGO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHCGED_ALT_SIT_FUN
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO           = VCODIGO;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHCGED_ALT_SIT_FUN');
        dbms_output.put_line('UPDATE RHCGED_ALT_SIT_FUN SET  DATA_INIC_SITUACAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE), ULTIMA_DATA  = TO_DATE('''||VANO_MES_REFERENCIA||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''' ;');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHCGED_ALT_SIT_FUN');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHCGED_ALT_SIT_FUN!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHCGED_ALT_SIT_FUN');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHCGED_ALT_SIT_FUN!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHPLCS_ALT_CARGO
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPLCS_ALT_CARGO
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_CARGO');
        dbms_output.put_line('UPDATE RHPLCS_ALT_CARGO SET  DT_ALTER_CARGO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''' ;');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_CARGO');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_CARGO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_CARGO');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_CARGO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHPLCS_ALT_ESPEC
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPLCS_ALT_ESPEC
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO
      AND DT_FIM_TEMP     IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_ESPEC');
        dbms_output.put_line('UPDATE RHPLCS_ALT_ESPEC SET  DATA_INICIO_ESPEC = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_ESPEC');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_ESPEC!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_ESPEC');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_ESPEC!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHPLCS_ALT_FUNCAO
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPLCS_ALT_FUNCAO
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO
      AND DT_FIM_TEMP     IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_FUNCAO');
        dbms_output.put_line('UPDATE RHPLCS_ALT_FUNCAO SET  DATA_INICIO_FUNCAO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_FUNCAO');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_FUNCAO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_FUNCAO');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_FUNCAO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHPLCS_ALT_VAGA
      SELECT COUNT(CODIGO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPLCS_ALT_VAGA
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO           = VCODIGO
      AND DATA_FIM_VAGA   IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_VAGA');
        dbms_output.put_line('UPDATE RHPLCS_ALT_VAGA SET  DATA_INICIO_VAGA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_VAGA');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_VAGA!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_VAGA');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_VAGA!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));

      --RHPLCS_ALT_POSICAO
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHPLCS_ALT_POSICAO
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO           = VCODIGO
      AND DATA_FIM_VAGA   IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_POSICAO');
        dbms_output.put_line('UPDATE RHPLCS_ALT_POSICAO SET  DATA_INICIO_VAGA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_POSICAO');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_POSICAO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_POSICAO');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_POSICAO!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));


      --RHTRAB_ALT_SIND
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHTRAB_ALT_SIND
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO
      AND DT_FIM_RELACAO  IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHTRAB_ALT_SIND');
        dbms_output.put_line('UPDATE RHTRAB_ALT_SIND SET  DT_ALTER_SINDICATO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHTRAB_ALT_SIND');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHTRAB_ALT_SIND!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHTRAB_ALT_SIND');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHTRAB_ALT_SIND!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHCGED_TRANSFERENC
      SELECT COUNT(CODIGO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHCGED_TRANSFERENC
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO           = VCODIGO
      AND DT_FIM_TEMP     IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHCGED_TRANSFERENC');
        dbms_output.put_line('UPDATE RHCGED_TRANSFERENC SET  DT_ALT_UNID_CUSTO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHTRAB_ALT_SIND');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHCGED_TRANSFERENC!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHPLCS_ALT_VAGA');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHCGED_TRANSFERENC!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHLEGI_LEI_CONTR
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM ARTERH.RHLEGI_LEI_CONTR
      WHERE CODIGO_EMPRESA   = VCODIGO_EMPRESA
      AND TIPO_CONTRATO      = VTIPO_CONTRATO
      AND CODIGO_CONTRATO    = VCODIGO
      AND DATA_FIM_VIGENCIA IS NULL;
      IF VCONT_VALIDA        = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHLEGI_LEI_CONTR');
        dbms_output.put_line('UPDATE RHLEGI_LEI_CONTR SET  DATA_INI_VIGENCIA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHLEGI_LEI_CONTR');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHLEGI_LEI_CONTR!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHLEGI_LEI_CONTR');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHLEGI_LEI_CONTR!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));
      --RHPLCS_ALT_SAL
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM RHPLCS_ALT_SAL
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPLCS_ALT_SAL');
        dbms_output.put_line('UPDATE RHPLCS_ALT_SAL SET  DT_ALTER_SALARIO = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPLCS_ALT_SAL');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPLCS_ALT_SAL!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHLEGI_LEI_CONTR');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPLCS_ALT_SAL!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
      dbms_output.put_line( CHR(13));

      --RHPONT_ALT_ESCALA
      SELECT COUNT(CODIGO_CONTRATO)
      INTO VCONT_VALIDA
      FROM RHPONT_ALT_ESCALA
      WHERE CODIGO_EMPRESA = VCODIGO_EMPRESA
      AND TIPO_CONTRATO    = VTIPO_CONTRATO
      AND CODIGO_CONTRATO  = VCODIGO
      AND DT_FIM_TROCA    IS NULL;
      IF VCONT_VALIDA      = 1 THEN
        --dbms_output.put_line('MENOR QUE UM  '||VCONT_VALIDA);
        dbms_output.put_line('--RHPONT_ALT_ESCALA');
        dbms_output.put_line('UPDATE RHPONT_ALT_ESCALA SET  DT_INICIO_TROCA = TO_DATE('''||VDATA_BASE||''',''DD/MM/YYYY''), LOGIN_USUARIO = '''||VLOGIN_USUARIO||''', dt_ult_alter_usua    = TRUNC(SYSDATE) WHERE CODIGO_EMPRESA ='''||VCODIGO_EMPRESA||''' AND TIPO_CONTRATO ='''|| VTIPO_CONTRATO || ''' AND CODIGO_CONTRATO ='''||VCODIGO||''';');
      ELSIF VCONT_VALIDA = 0 THEN
        dbms_output.put_line('--RHPONT_ALT_ESCALA');
        dbms_output.put_line('ESSE CONTRATO NÃO POSSUI REGISTRO NA TABELA RHPONT_ALT_ESCALA!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      ELSE
        dbms_output.put_line('--RHLEGI_LEI_CONTR');
        dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO NA TABELA RHPONT_ALT_ESCALA!'||CHR(13)|| 'TOTAL: '||VCONT_VALIDA || CHR(13)||'NADA FOI ALTERADO!');
      END IF;
    	dbms_output.put_line( CHR(13));
    ELSE
      dbms_output.put_line('ESSE CONTRATO POSSUI MAIS DE UM REGISTRO!'||CHR(13)|| 'TOTAL: '||VCONT || CHR(13)||'NADA FOI ALTERADO!');
    END IF;
  END;
END;