
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_CRIAR_VALE_V2" (Pdata_vale1 DATE,Pdata_vale2 DATE,Pdata_corte date)
AS
 CONTADOR NUMBER;
  VALIDA TP_VALIDA_VALE;
  v_data_ini_vale DATE;
  v_data_fim_vale DATE;
  DADOS_CONT DADOS_RETORNO_FUN;
  vQTDE_LINHAS_AFETADAS NUMBER;
  COD_LINHA VARCHAR2(15 BYTE);
  COD_ITNERARIO CHAR(4 BYTE);
  SOMA NUMBER ;
  DIREITO CHAR;

  BEGIN
  CONTADOR:=0;

    FOR C1 IN
  (SELECT VL.ID_EXECUCAO,CODIGO_EMPRESA,TIPO_CONTRATO,CPF,DOIS_CONTRATOS
  FROM ARTERH.SMARH_INT_VALE VL
  LEFT OUTER JOIN ARTERH.SMARH_INT_DIA_EXECUCAO EX
  ON VL.ID_EXECUCAO      =EX.ID_EXECUCAO
  WHERE EX.DATA_EXECUCAO =
    (SELECT MAX(AUX.DATA_EXECUCAO) FROM SMARH_INT_DIA_EXECUCAO AUX
    )
 AND VL.CPF ='06701526683'
  GROUP BY VL.ID_EXECUCAO ,
    CODIGO_EMPRESA,
    TIPO_CONTRATO,
    CPF,
    DOIS_CONTRATOS
  )LOOP
  CONTADOR:=CONTADOR+1;
   DIREITO:='N';
  DBMS_Output.PUT_LINE('CONTADOR-----------'||CONTADOR||'--- CPF'||C1.CPF);
  FOR X1 IN (
  SELECT * FROM (
  SELECT X1.* FROM (SELECT X.*,CASE
        WHEN carga_horaria <'0800'AND X.HR_1 
        BETWEEN '0600'AND  '1259' THEN 'TURNO_MANHA'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1300'AND '1759'  THEN 'TURNO_TARDE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1800'AND '2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '0000'AND '0559'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
    FROM
      (SELECT X.*,
        H.tipo_horario,
        REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1 ,
        REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2')  AS hr_2,
        REGEXP_REPLACE(lpad( TO_CHAR(trim (HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
        REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_4 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
        REGEXP_REPLACE (lpad(TO_CHAR(trim (H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
      FROM
        (SELECT 'ESCALA_PRINCIPAL' AS TIPO,
          ALT.CODIGO_EMPRESA,
          ALT.TIPO_CONTRATO,
          ALT.CODIGO_CONTRATO,
          P.CPF,
          CASE WHEN ALT.DT_INICIO_TROCA < C.DATA_EFETIVO_EXERC THEN C.DATA_EFETIVO_EXERC ELSE ALT.DT_INICIO_TROCA END AS DT_INICIO_TROCA,
          ALT.DT_FIM_TROCA,
          ALT.COD_ESCALA,
          EL.tipo_escala,
          CG.CODIGO AS CARGO
        FROM ARTERH.RHPONT_ALT_ESCALA ALT
        LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
        ON C.CODIGO         =ALT.CODIGO_CONTRATO
        AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
        AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
        LEFT OUTER JOIN ARTERH.RHPLCS_CARGO CG 
        ON CG.CODIGO_EMPRESA=C.CODIGO_EMPRESA
        AND CG.CODIGO=c.cod_cargo_efetivo
        LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
        ON P.CODIGO         =C.CODIGO_PESSOA
        AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
        LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
        ON SF.CODIGO=C.SITUACAO_FUNCIONAL
        LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
        ON EL.CODIGO_EMPRESA     =ALT.CODIGO_EMPRESA
        AND EL.CODIGO            = ALT.COD_ESCALA
        WHERE P.CPF              =C1.CPF
        AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
        AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
        AND ALT.ALTER_DEFINITIVA = 'S'
        AND C.ANO_MES_REFERENCIA =
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.CODIGO            =C.CODIGO
          AND AUX.TIPO_CONTRATO       = C.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA      =C.CODIGO_EMPRESA
          AND AUX.ANO_MES_REFERENCIA <= Pdata_vale2
          )
       AND SF.CODIGO<'1715'
        ) X
      LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
      ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
      AND EH.CODIGO_ESCALA= X.COD_ESCALA
      LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
      ON H.CODIGO_EMPRESA = EH.CODIGO_EMPRESA
      AND H.CODIGO        = EH.CODIGO_HORARIO
      WHERE (
      ( x.DT_INICIO_TROCA BETWEEN Pdata_vale1 AND Pdata_vale2 )
      OR ( x.DT_INICIO_TROCA BETWEEN Pdata_vale1 AND Pdata_vale2 AND X.DT_FIM_TROCA IS NULL )
      OR (X.DT_FIM_TROCA IS NULL AND x.DT_INICIO_TROCA<=Pdata_vale2 )
      OR (X.DT_INICIO_TROCA<=Pdata_vale2 AND X.DT_FIM_TROCA>=Pdata_vale2)
       OR (X.DT_INICIO_TROCA<=Pdata_vale2 AND X.DT_FIM_TROCA BETWEEN Pdata_vale1 AND Pdata_vale2)
      )
      AND H.TIPO_HORARIO   IN ('N','T')
      ) X
      )X1
    GROUP BY X1.TIPO,X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO, X1.CODIGO_CONTRATO, X1.CPF, X1.DT_INICIO_TROCA, X1.DT_FIM_TROCA, X1.COD_ESCALA,X1.TIPO_ESCALA,X1.TIPO_HORARIO,X1.HR_1,X1.HR_2,X1.HR_3,X1.HR_4,X1.CARGA_HORARIA,X1.TURNO,X1.CARGO
    ORDER BY X1.CARGA_HORARIA DESC,
        X1.DT_INICIO_TROCA )
WHERE ROWNUM =1
)
    LOOP
    SOMA      :=0;
    IF ((X1.TURNO='TURNO_CHEIO' AND X1.CARGA_HORARIA>='0800') OR (X1.CARGO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') AND X1.CARGA_HORARIA>='0700' )) THEN
              DBMS_Output.PUT_LINE('CHAMOU CRIAR VALE 0');
              DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA DEFINITIVA TURNO CHEIO');
              DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);
      IF X1.DT_INICIO_TROCA <Pdata_corte THEN
          PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', Pdata_corte,NULL,'INCLUIR','S',Pdata_vale1,Pdata_vale2);
        ELSE
          PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', X1.DT_INICIO_TROCA,NULL,'INCLUIR','S',Pdata_vale1,Pdata_vale2);
        END IF;
        SOMA :=TO_NUMBER(REPLACE(X1.carga_horaria,':',''));
      ELSIF ( ( X1.TURNO='TURNO_MANHA' OR X1.TURNO='TURNO_TARDE' OR X1.TURNO= 'TURNO_NOITE' ) AND C1.DOIS_CONTRATOS = 'S' ) THEN
            DBMS_Output.PUT_LINE('ENTROU VERIFICA JORNADA PARTICIONADA');
            DBMS_Output.PUT_LINE('COD ESCALA'||X1.COD_ESCALA||' TURNO'||X1.TURNO);
            DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);
      SOMA :=TO_NUMBER(REPLACE(X1.carga_horaria,':',''));

           FOR EL IN (
           SELECT EL.* FROM (SELECT X.*,CASE
        WHEN carga_horaria <'0800'AND X.HR_1 
        BETWEEN '0600'AND  '1259' THEN 'TURNO_MANHA'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1300'AND '1759'  THEN 'TURNO_TARDE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1800'AND '2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '0000'AND '0559'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
        FROM
          (SELECT X.*,
            H.tipo_horario,
            REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1,
            REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0' ), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_2,
            REGEXP_REPLACE( lpad(TO_CHAR( trim(HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
            REGEXP_REPLACE(lpad( TO_CHAR(trim( HORARIO_NORMAL_4)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
            REGEXP_REPLACE(lpad(TO_CHAR( trim( H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
          FROM
            (SELECT 'ESCALA_PRINCIPAL' AS TIPO,
              ALT.CODIGO_EMPRESA,
              ALT.TIPO_CONTRATO ,
              ALT.CODIGO_CONTRATO,
              P.CPF,
              CASE WHEN ALT.DT_INICIO_TROCA < C.DATA_EFETIVO_EXERC THEN C.DATA_EFETIVO_EXERC ELSE ALT.DT_INICIO_TROCA END AS DT_INICIO_TROCA,
              ALT.DT_FIM_TROCA,
              ALT.COD_ESCALA,
              EL.tipo_escala
            FROM ARTERH.RHPONT_ALT_ESCALA ALT
            LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
            ON C.CODIGO         =ALT.CODIGO_CONTRATO
            AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
            AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
            LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
            ON P.CODIGO         =C.CODIGO_PESSOA
            AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
            LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
            ON SF.CODIGO=C.SITUACAO_FUNCIONAL
            LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
            ON EL.CODIGO_EMPRESA     = ALT.CODIGO_EMPRESA
            AND EL.CODIGO            = ALT.COD_ESCALA
            WHERE P.CPF              =C1.CPF
            AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
            AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
            AND ALT.ALTER_DEFINITIVA ='S'
            AND ALT.COD_ESCALA       <>X1.COD_ESCALA
            AND C.ANO_MES_REFERENCIA =
              (SELECT MAX(AUX.ANO_MES_REFERENCIA)
              FROM ARTERH.RHPESS_CONTRATO AUX
              WHERE AUX.CODIGO           =C.CODIGO
              AND AUX.TIPO_CONTRATO      = C.TIPO_CONTRATO
              AND AUX.CODIGO_EMPRESA     = C.CODIGO_EMPRESA
              AND AUX.ANO_MES_REFERENCIA<= Pdata_vale2
              )
           AND SF.CODIGO<'1715'
            ) X
          LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
          ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
          AND EH.CODIGO_ESCALA= X.COD_ESCALA
          LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
          ON H.CODIGO_EMPRESA                          = EH.CODIGO_EMPRESA
          AND H.CODIGO                                 = EH.CODIGO_HORARIO
         WHERE (
             (TO_DATE(x.DT_FIM_TROCA,'DD/MM/RRRR') IS NULL )
            OR (TO_DATE(x.DT_INICIO_TROCA,'DD/MM/RRRR')BETWEEN  X1.DT_INICIO_TROCA  AND Pdata_vale2 ) 
            )

          AND H.TIPO_HORARIO IN ('N','T')
          ) X
          )EL
        GROUP BY EL.TIPO,EL.CODIGO_EMPRESA,EL.TIPO_CONTRATO,EL.CODIGO_CONTRATO ,EL.CPF,EL.DT_INICIO_TROCA,EL.DT_FIM_TROCA,EL.COD_ESCALA,EL.TIPO_ESCALA,EL.TIPO_HORARIO,EL.HR_1,EL.HR_2,EL.HR_3,EL.HR_4,EL.CARGA_HORARIA,EL.TURNO
        ORDER BY EL.DT_INICIO_TROCA
           )
           LOOP
              DBMS_Output.PUT_LINE(EL.TURNO ||' ' ||X1.TURNO);

           IF (
              (X1.TURNO='TURNO_MANHA' AND EL.TURNO='TURNO_TARDE')
           OR ( X1.TURNO= 'TURNO_TARDE' AND EL.TURNO='TURNO_NOITE' )
           OR ( EL.TURNO='TURNO_MANHA' AND X1.TURNO='TURNO_TARDE' )
           OR ( EL.TURNO='TURNO_TARDE' AND X1.TURNO= 'TURNO_NOITE' )
           OR ( EL.TURNO='TURNO_CHEIO' AND EL.CARGA_HORARIA= '0800' )
           OR ( EL.TURNO=X1.TURNO AND  ( X1.hr_1 NOT BETWEEN EL.hr_1 AND EL.hr_2 AND X1.hr_2 NOT BETWEEN EL.hr_1 AND EL.hr_2  ) )
           or ( EL.TURNO<>X1.TURNO AND ( X1.hr_2 - EL.hr_1 BETWEEN 10 and 200 ))
           ) THEN
            SOMA:=(SOMA+ CAST(REPLACE(EL.carga_horaria,':','')AS NUMBER));
              IF SOMA >=800 THEN
              DBMS_Output.PUT_LINE('CHAMOU CRIAR VALE 1');
              DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA DEFINITIVA 2');
              DBMS_Output.PUT_LINE('DATAS'||EL.DT_INICIO_TROCA||'-'||EL.DT_FIM_TROCA);
              IF el.DT_INICIO_TROCA<Pdata_corte THEN
               DBMS_Output.PUT_LINE('ENTROU DATA IF'|| Pdata_corte);
                PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', Pdata_corte,NULL,'INCLUIR','S',Pdata_vale1,Pdata_vale2);
              ELSE
               DBMS_Output.PUT_LINE('ENTROU DATA ELSIF'|| el.DT_INICIO_TROCA);
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', el.DT_INICIO_TROCA,el.DT_fim_TROCA,'INCLUIR','S',Pdata_vale1,Pdata_vale2);
              END IF;
           END IF;
          END IF;
         END LOOP;-- FIM FOR EL

         FOR X2 IN (
         SELECT X2.* FROM (SELECT X.*,CASE
        WHEN carga_horaria <'0800'AND X.HR_1 
        BETWEEN '0600'AND  '1259' THEN 'TURNO_MANHA'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1300'AND '1759'  THEN 'TURNO_TARDE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '1800'AND '2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria <'0800'AND X.HR_1
        BETWEEN '0000'AND '0559'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
      FROM
        (SELECT X.*,
          H.tipo_horario,
          REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1,
          REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0' ), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_2,
          REGEXP_REPLACE( lpad(TO_CHAR( trim(HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
          REGEXP_REPLACE(lpad( TO_CHAR(trim( HORARIO_NORMAL_4)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
          REGEXP_REPLACE(lpad(TO_CHAR( trim( H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
        FROM
          (SELECT 'ESCALA_ALTERNATIVA' AS TIPO,
            ALT.CODIGO_EMPRESA,
            ALT.TIPO_CONTRATO,
            ALT.CODIGO_CONTRATO,
            P.CPF,
            CASE WHEN ALT.DT_INICIO_TROCA < C.DATA_EFETIVO_EXERC THEN C.DATA_EFETIVO_EXERC ELSE ALT.DT_INICIO_TROCA END AS DT_INICIO_TROCA,
            ALT.DT_FIM_TROCA,
            ALT.COD_ESCALA,
            EL.tipo_escala
          FROM ARTERH.RHPONT_ALT_ESCALA ALT
          LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
          ON C.CODIGO         =ALT.CODIGO_CONTRATO
          AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
          AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
          LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
          ON P.CODIGO         =C.CODIGO_PESSOA
          AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
          LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
          ON SF.CODIGO=C.SITUACAO_FUNCIONAL
          LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
          ON EL.CODIGO_EMPRESA     = ALT.CODIGO_EMPRESA
          AND EL.CODIGO            = ALT.COD_ESCALA
          WHERE P.CPF              =C1.CPF
          AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
          AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
          AND ALT.ALTER_DEFINITIVA ='N'
          AND C.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO           =C.CODIGO
            AND AUX.TIPO_CONTRATO      = C.TIPO_CONTRATO
            AND AUX.CODIGO_EMPRESA     = C.CODIGO_EMPRESA
            AND AUX.ANO_MES_REFERENCIA<= Pdata_vale2
            )
          AND SF.CODIGO<'1715'
          ) X
        LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
        ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
        AND EH.CODIGO_ESCALA= X.COD_ESCALA
        LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
        ON H.CODIGO_EMPRESA = EH.CODIGO_EMPRESA
        AND H.CODIGO        = EH.CODIGO_HORARIO
        WHERE ( ( TO_DATE(x.DT_INICIO_TROCA,'DD/MM/RRRR') BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA )
        OR ( x.DT_INICIO_TROCA BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA AND X.DT_FIM_TROCA IS NULL )
        OR ( X.DT_FIM_TROCA BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA AND x.DT_INICIO_TROCA  <=X1.DT_INICIO_TROCA )
        OR ( X.DT_INICIO_TROCA <= X1.DT_INICIO_TROCA AND ((X.DT_FIM_TROCA   <=X1.DT_FIM_TROCA)OR (X1.DT_FIM_TROCA    IS NULL) )) )
        AND H.TIPO_HORARIO    IN ('N','T')
        ) X
        )X2
      GROUP BY X2.TIPO,X2.CODIGO_EMPRESA,X2.TIPO_CONTRATO,X2.CODIGO_CONTRATO ,X2.CPF,X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,X2.COD_ESCALA,X2.TIPO_ESCALA,X2.TIPO_HORARIO,X2.HR_1,X2.HR_2,X2.HR_3,X2.HR_4,X2.CARGA_HORARIA,X2.TURNO
      ORDER BY X2.DT_INICIO_TROCA
         )LOOP
          IF ( (X1.TURNO='TURNO_MANHA' AND X2.TURNO='TURNO_TARDE')
          OR ( X1.TURNO= 'TURNO_TARDE' AND X2.TURNO='TURNO_NOITE' )
          OR ( X2.TURNO='TURNO_MANHA' AND X1.TURNO='TURNO_TARDE' )
          OR ( X2.TURNO='TURNO_TARDE' AND X1.TURNO= 'TURNO_NOITE' )
          OR ( X2.TURNO='TURNO_CHEIO' AND X2.CARGA_HORARIA>= '0800' ) 
          OR ( X2.TURNO=X1.TURNO AND  ( X1.hr_1 NOT BETWEEN X2.hr_1 AND X2.hr_2 AND X1.hr_2 NOT BETWEEN X2.hr_1 AND X2.hr_2  ) )
          or ( X2.TURNO<>X1.TURNO AND ( X1.hr_2 - X2.hr_1 BETWEEN 10 and 200 ))
          ) THEN
          SOMA :=(SOMA+CAST(REPLACE(X2.carga_horaria,':','')AS NUMBER));
          IF ((SOMA >=800) OR ( X2.TURNO='TURNO_CHEIO' AND X2.CARGA_HORARIA>= '0800' ) ) THEN
          DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA ALTERNATIVA');
          DBMS_Output.PUT_LINE('DATAS'||X2.DT_INICIO_TROCA||'-'||X2.DT_FIM_TROCA);
         -- PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,'INCLUIR','N');

           IF X2.DT_INICIO_TROCA<Pdata_corte THEN
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , Pdata_corte,X2.DT_FIM_TROCA,'INCLUIR','N',Pdata_vale1,Pdata_vale2);
            ELSE
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,'INCLUIR','N',Pdata_vale1,Pdata_vale2);
            END IF;

          END IF;
          END IF;
         END LOOP; -- FIM FOR X2


    END IF;
    IF ( SOMA <800 AND X1.TURNO!='TURNO_CHEIO' AND  X1.CARGO NOT IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') ) or  ( X1.CARGO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765')  and SOMA <700 )   THEN
    DBMS_Output.PUT_LINE('CHAMOU PROCEDURE EXCLUIR 1');
    DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);

      IF X1.DT_INICIO_TROCA<Pdata_corte THEN 
       PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', Pdata_corte,X1.DT_FIM_TROCA,'EXCLUIR',NULL,Pdata_vale1,Pdata_vale2);
       ELSE
      PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', X1.DT_INIcio_TROCA,X1.DT_FIM_TROCA,'EXCLUIR',NULL,Pdata_vale1,Pdata_vale2);
        END IF;
    END IF;
    END LOOP;---- FIM LOOP X1
  END LOOP;-- FIM LOOP FOR C1
  END;