
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_EXECUTE_CAT" AS
CONT NUMBER:=0;
FUNCIONAL arterh.rhcged_alt_sit_fun%ROWTYPE;
RHPBH_LOG_CAT ARTERH.RHPBH_LOG_CAT%ROWTYPE;

BEGIN 
dbms_output.enable(null);

FOR C1 IN (


    SELECT
     c.codigo_empresa,
     c.tipo_contrato,
     c.codigo,
     c.nome,
     c.ano_mes_referencia,
     c.data_admissao
    FROM
        arterh.rhpess_contrato c
    WHERE
            c.ano_mes_referencia = (
                SELECT
                    MIN(aux.ano_mes_referencia)
                FROM
                    arterh.rhpess_contrato aux
                WHERE
                        aux.codigo = c.codigo
                    AND aux.tipo_contrato = c.tipo_contrato
                    AND aux.codigo_empresa = c.codigo_empresa
            )

     and not exists (select * from  arterh.rhpess_contrato aux
     where aux.codigo=c.codigo
     and aux.codigo_empresa=c.codigo_empresa
     and aux.tipo_contrato=c.tipo_contrato
     and trunc(aux.ano_mes_referencia) = trunc(c.data_admissao,'mm')
     )
     and C.codigo_empresa in ('0005','0006','0001')
     AND TRUNC(C.DATA_ADMISSAO) <='31/12/2023'
-- and c.codigo='000000000950053'
 )LOOP
 CONT:=CONT+1;

 dbms_output.put_line('CODIGO_CONTRATO'||C1.CODIGO||'TIPO_CONTRATO'||C1.TIPO_CONTRATO);
BEGIN
 INSERT INTO ARTERH.RHPESS_CONTRATO VALUE

select CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
CODIGO_PESSOA,
NOME,
REGISTRO,
NUMERO_ARQUIVO,
'6008'SITUACAO_FUNCIONAL,
SITUACAO_CONTRATO,
STATUS_CONTRATO,
DATA_ADMISSAO,
MOTIVO_ADMISSAO,
MOTIVO_DEMISSAO,
TIPO_PAGAMENTO,
TIPO_SALARIO,
VINCULO,
FORMA_PROVIMENTO,
COD_LOCAL1,
COD_LOCAL2,
COD_LOCAL3,
COD_LOCAL4,
COD_LOCAL5,
COD_LOCAL6,
DT_ULT_ALT_LOC,
COD_UNIDADE1,
COD_UNIDADE2,
COD_UNIDADE3,
COD_UNIDADE4,
COD_UNIDADE5,
COD_UNIDADE6,
DT_ULT_ALT_UNID,
COD_CUSTO_CONTAB1,
COD_CUSTO_CONTAB2,
COD_CUSTO_CONTAB3,
COD_CUSTO_CONTAB4,
COD_CUSTO_CONTAB5,
COD_CUSTO_CONTAB6,
DT_ULT_ALT_CONT,
COD_CUSTO_GERENC1,
COD_CUSTO_GERENC2,
COD_CUSTO_GERENC3,
COD_CUSTO_GERENC4,
COD_CUSTO_GERENC5,
COD_CUSTO_GERENC6,
DT_ULT_ALT_GER,
SALARIO_PAGTO,
COD_CARGO_PAGTO,
NIVEL_CARGO_PAGTO,
COD_CARGO_EFETIVO,
NIVEL_CARGO_EFETIV,
DT_ULT_CARGO_EFET,
COD_CARGO_COMISS,
NIVEL_CARGO_COMISS,
DT_ULT_CARGO_COM,
COD_CARGO_AMPAR,
NIVEL_CARGO_AMPAR,
DT_ULT_CARGO_AMPAR,
CODIGO_FUNCAO,
DT_ULT_FUNCAO,
COD_ESPECIALIDADE,
DT_ULT_ESPEC,
CODIGO_VAGA,
DT_ULT_VAGA,
AREA_ATUACAO,
CATEG_PROFISSIONAL,
CODIGO_ESCALA,
REGISTRO_PONTO,
DT_ULT_ESCALA,
CODIGO_BANCO_CC,
CONTA_CORRENTE,
CODIGO_BANCO_FGTS,
CONTA_FGTS,
DATA_OPCAO_FGTS,
DATA_RETROACAO,
DATA_RETRATACAO,
COD_SINDICATO,
NIVEL_SINDICATO,
DT_ULT_SINDICATO,
DESC_CONTRIB_SIND,
SINDICALIZADO,
INSCRICAO_INSS,
COD_MOVIMENTACAO,
DATA_TRANSF_ENTRAD,
DATA_PRI_ADMISSAO,
DATA_REINTEGRACAO,
DATA_EFETIVO_EXERC,
DATA_POSSE,
DATA_NOMEACAO,
DATA_INICIO_ESTAB,
DATA_FIM_ESTAB,
DT_FIM_CONTR_EXP,
DT_FIM_CONTR_DETER,
DATA_FIM_RENOV_EXP,
DATA_AV_PREVIO,
DATA_RESCISAO,
CAUSA_RESCISAO,
DATA_INIC_AFAST,
DATA_FIM_AFAST,
NRO_MESES_AFAST,
CTRL_VERBAS,
FORMA_PAGAMENTO,
DATA_BASE_FERIAS,
DATA_INIC_GOZO,
DATA_FIM_GOZO,
DEPENDENTES_SF,
DEPENDENTES_IRRF,
COD_PROCURADOR,
DATA_PAGTO_CALCULO,
DATA_PAGTO_ADIANT,
DATA_PAGTO_FERIAS,
DATA_PAGTO_13SAL,
DATA_PAGTO_RESCISA,
SAL_CONT_EFETIVO,
DT_ULT_SAL_C_EFET,
SAL_CONT_COMISSION,
DT_ULT_SAL_C_COM,
SAL_CONT_AMPAR,
DT_ULT_SAL_C_AMP,
SAL_AUX_EFETIVO,
DT_ULT_SAL_A_EFET,
SAL_AUX_COMISSION,
DT_ULT_SAL_A_COM,
SAL_AUX_AMPAR,
DT_ULT_SAL_A_AMP,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_SELEC04,
C_LIVRE_SELEC05,
C_LIVRE_SELEC06,
C_LIVRE_SELEC07,
C_LIVRE_SELEC08,
C_LIVRE_SELEC09,
C_LIVRE_SELEC10,
C_LIVRE_SELEC11,
C_LIVRE_SELEC12,
C_LIVRE_SELEC13,
C_LIVRE_SELEC14,
C_LIVRE_SELEC15,
C_LIVRE_SELEC36,
C_LIVRE_SELEC37,
C_LIVRE_SELEC38,
C_LIVRE_SELEC39,
C_LIVRE_SELEC40,
C_LIVRE_VALOR16,
C_LIVRE_VALOR17,
C_LIVRE_VALOR18,
C_LIVRE_VALOR19,
C_LIVRE_VALOR20,
C_LIVRE_VALOR21,
C_LIVRE_VALOR22,
C_LIVRE_VALOR23,
C_LIVRE_DESCR24,
C_LIVRE_DESCR25,
C_LIVRE_DESCR26,
C_LIVRE_DESCR27,
C_LIVRE_DATA28,
C_LIVRE_DATA29,
C_LIVRE_DATA30,
C_LIVRE_DATA31,
C_LIVRE_DATA32,
C_LIVRE_DATA33,
C_LIVRE_DATA34,
C_LIVRE_DATA35,
C_LIVRE_OPCAO41,
C_LIVRE_OPCAO42,
C_LIVRE_OPCAO43,
C_LIVRE_OPCAO44,
C_LIVRE_OPCAO45,
C_LIVRE_OPCAO46,
C_LIVRE_OPCAO47,
C_LIVRE_OPCAO48,
INDIC_ALTERAC1,
INDIC_ALTERAC2,
INDIC_ALTERAC3,
INDIC_ALTERAC4,
INDIC_ALTERAC5,
TEXTO_ASSOCIADO,
'ACERTO_CAT'LOGIN_USUARIO,
SYSDATE DT_ULT_ALTER_USUA,
TELEFONE,
TRUNC(DATA_ADMISSAO,'MM')ANO_MES_REFERENCIA,
DATA_APOSENTA_FGTS,
REABILITADO,
C_LIVRE_VALOR49,
C_LIVRE_VALOR50,
C_LIVRE_VALOR51,
C_LIVRE_VALOR52,
C_LIVRE_VALOR53,
C_LIVRE_VALOR54,
C_LIVRE_VALOR55,
C_LIVRE_VALOR56,
C_LIVRE_DATA57,
C_LIVRE_DATA58,
C_LIVRE_DATA59,
C_LIVRE_DATA60,
C_LIVRE_DATA61,
C_LIVRE_DATA62,
C_LIVRE_DATA63,
C_LIVRE_DATA64,
C_LIVRE_OPCAO65,
C_LIVRE_OPCAO66,
C_LIVRE_OPCAO67,
C_LIVRE_OPCAO68,
INDIC_ALTERAC6,
CLASSE_CONT_INSS,
E_MAIL,
USA_ASSOC_CONT_ESC,
CLASSIFICACAO_CAND,
NUMERO_EDITAL,
TIPO_AGRUP_UNID,
TIPO_AGRUP_CONT,
TIPO_AGRUP_CGER,
TIPO_AGRUP_LOTA,
NOME_ACESSO,
CODIGO_SOLICITACAO,
NULL  ID_CONTR_FORN ,
FUNC_COMP_EMPR_AV,
DT_MOLESTIA_GRAVE,
SAL_CONT_FUNCAO,
DT_ULT_SAL_C_FUN,
SAL_AUX_FUNCAO,
DT_ULT_SAL_A_FUN,
DATA_PROJ_AV_PREV,
DT_PROJ_AFAST_ESOCIAL,
TP_AVISO_PREVIO_ESOCIAL,
TP_CONTA_BANCARIA,
DT_PROC_ESOCIAL,
DT_ALTER_ESOCIAL,
DT_CANC_AVISO_PREVIO,
MOT_CANC_AV_PREV_ESOCIAL,
DESC_SAL_VARIAVEL,
MOTIVO_CONTRATACAO,
CPF_TRAB_SUBSTITUIDO,
MATRIC_TRAB_SUBSTITUIDO,
IND_SEGURO_DESEMPREGO,
DT_GERACAO_CAGED,
OBS_RESCISAO,
DT_FIM_QUARENTENA,
CNPJ_EMPRESA_SUCESSORA,
JUST_CONTR_ESOCIAL,
TP_INCL_CONTR_ESOCIAL,
INFO_COTA_ESOCIAL,
CLAUSULA_ASSEC,
DT_ALTERACAO_CONTR,
DT_EFEITO_ALTER_CONTR,
DESC_ALTER_CONTR,
IND_CUMPR_PARC_AV,
CODIGO_CONTR_ANTERIOR,
CPF_ANTERIOR,
DATA_ALTER_CPF,
OBS_ALTER_CPF,
TEM_ALTER_CPF,
INFO_COTA_RACA,
MATRICULA_ESOCIAL,
CONSELHO_REGIONAL,
INSCRICAO_CONSELHO,
UF_CONSELHO,
COD_CARREIRA,
COD_EIXO,
COD_NIVEL,
IND_REMUN
from arterh.rhpess_contrato 
where rhpess_contrato.codigo=C1.CODIGO
and rhpess_contrato.tipo_contrato=C1.TIPO_CONTRATO
and rhpess_contrato.codigo_empresa=C1.CODIGO_EMPRESA
and rhpess_contrato.ano_mes_referencia=C1.ANO_MES_REFERENCIA;
COMMIT;



 UPDATE ARTERH.RHPESS_CONTR_MEST 
 SET PRIMEIRA_DATA= TRUNC(DATA_ADMISSAO,'MM'), LOGIN_USUARIO='ACERTO_CAT', DT_ULT_ALTER_USUA=SYSDATE 
WHERE CODIGO_CONTRATO=C1.CODIGO 
AND TIPO_CONTRATO=C1.TIPO_CONTRATO 
AND CODIGO_EMPRESA=c1.codigo_empresa
AND TRUNC(PRIMEIRA_DATA)<> TRUNC(DATA_ADMISSAO,'MM');
commit;



COMMIT;

exception
              when others then
       RHPBH_LOG_CAT.CODIGO_EMPRESA:=C1.CODIGO_EMPRESA;
       RHPBH_LOG_CAT.TIPO_CONTRATO:=C1.TIPO_CONTRATO;
       RHPBH_LOG_CAT.CODIGO_CONTRATO:=C1.CODIGO;
       RHPBH_LOG_CAT.DESCRICAO_ERRO:=  'CODIGO ERRO: '||SQLCODE||' DESCRICAO ERRO: ' ||SUBSTR(SQLERRM, 1, 4000);
       INSERT INTO ARTERH.RHPBH_LOG_CAT VALUES RHPBH_LOG_CAT;
       COMMIT;
              END;






 END LOOP;
 END;




