
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_FICHA_FUTURA_GRAVA_SIT_FUNC" (DATA_INICIO IN VARCHAR2, DATA_FIM IN VARCHAR2)
AS
BEGIN

--KELLYSSON EM 23/12/21 - BASE PARA NOVA PROCEDURE: PARA PROCESSAR FICHAS FUTURAS RECEBIDAS NO DIA QUE COMECA O AFASTAMENTO APOS RODAR A PROCEDURE: PR_PROXIMA_SITUACAO_FUNCIONAL

DECLARE   
vCONTADOR NUMBER; 
vDATA_INICIO Varchar2(10);
vDATA_FIM Varchar2(10);
err_msg varchar2 (4000);

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;
err_msg := NULL;

FOR C1 IN (

SELECT 'TEG' ORIGEM, 
X2.AUTOIDFICHAATENDIMENTO, X2.CODIGOEMPRESA, X2.CODIGOTIPOCONTRATO, X2.CODIGOCONTRATO, X2.DATAOCORRENCIA, 
X2.OCORRENCIA, X2.CODIGO_PESSOA,
X2.DATAINICIOAFAST, X2.DATAFIMAFAST, X2.TIPOPROCEDIMENTO, X2.CODIGOCONDUTA, X2.TOTAL_STATUS_PROCESSAMENTO, X2.GRAVOU_FICHA, X2.QTD_REGISTROS,
SFP.COD_SIT_FUNCIONAL_SFP, SFP.SFP_DESC_SIT_FUNC, SFP.DATA_INIC_SITUACAO_SFP, SFP.DATA_FIM_SITUACAO_SFP
FROM(
SELECT 
X.AUTOIDFICHAATENDIMENTO, X.CODIGOEMPRESA, X.CODIGOTIPOCONTRATO, X.CODIGOCONTRATO, X.DATAOCORRENCIA, X.DATAINICIOAFAST, X.DATAFIMAFAST, X.TIPOPROCEDIMENTO, X.CODIGOCONDUTA, 
X.OCORRENCIA, X.CODIGO_PESSOA,
SUM(X.TOTAL_STATUS_PROCESSAMENTO)TOTAL_STATUS_PROCESSAMENTO, SUM(X.GRAVOU_FICHA) GRAVOU_FICHA,COUNT(1)QTD_REGISTROS
FROM(
SELECT
CASE WHEN A.STATUS_PROCESSAMENTO = 'NAO' THEN 0 ELSE 1 END TOTAL_STATUS_PROCESSAMENTO,
CASE WHEN F.OCORRENCIA IS NULL THEN  0 ELSE 1 END GRAVOU_FICHA,
F.OCORRENCIA, F.CODIGO_PESSOA,
A.DATA_PROCESSAMENTO, A.STATUS_PROCESSAMENTO, A.ID, A.DATA_RECEBIMENTO, A.AUTOIDFICHAATENDIMENTO, A.SEQUENCIAL_TEG, A.CODIGOEMPRESA, A.CODIGOTIPOCONTRATO, A.CODIGOCONTRATO, A.DATAOCORRENCIA, A.DATAINICIOAFAST, A.DATAFIMAFAST, A.TIPOPROCEDIMENTO, A.CODIGOCONDUTA,
A.NOME, A.ATENDENTE, A.DATAEFETIVA, A.HORARIOEFETIVO, A. MODALIDADE, 
A.DATAINICIALINDEFERIMENTO, A.DATAFINALINDEFERIMENTO, A.DATARETORNOREAVALIACAO, A.DATACIENCIADECISAO, A.PERIODOLAUDO, A.INICIOLAUDO, A.FINALLAUDO, A.DOENCA, A.ESPECIALIDADETRATAMENTO, A.FREQUENCIA_SESSOES, A.PERIODOINICIALTRATAMENTO, A.PERIODOFINALTRATAMENTO, A.QTDE_SESSOES,
A.ABONO, A.MOTIVO, A.EXAMECLINICO, A. LOTE, A.RECONSIDERACAO, A.POSITIVOEXAME
FROM ARTERH.SUGESP_ARQUIVOS_FICHA A
LEFT OUTER JOIN RHMEDI_FICHA_MED F ON A.CODIGOEMPRESA = F.CODIGO_EMPRESA AND A.CODIGOTIPOCONTRATO = F.TIPO_CONTRATO AND A.CODIGOCONTRATO = F.CODIGO_CONTRATO 
AND TRUNC(A.DATAOCORRENCIA)= TRUNC(F.DT_REG_OCORRENCIA) AND A.TIPOPROCEDIMENTO = F.NATUREZA_EXAME AND TRUNC(A.DATAINICIOAFAST) = TRUNC(F.DATA_INI_AFAST) AND TRUNC(A.DATAFIMAFAST) = TRUNC(F.DATA_FIM_AFAST)

WHERE A.DATA_PROCESSAMENTO IS NOT NULL AND TRUNC(A.DATAINICIOAFAST)> TRUNC(A.DATA_RECEBIMENTO)--AND TRUNC(DATAINICIOAFAST)> TRUNC(DATAOCORRENCIA)
AND 
--TRUNC(DATAINICIOAFAST) BETWEEN TRUNC(SYSDATE)-354 AND TRUNC(SYSDATE)-1 ------------------------------------TROCAR A DATA*************************************** CASO QUERIA MAIS DIAS
--TESTES 27/12/23--
TRUNC(A.DATAINICIOAFAST) BETWEEN vDATA_INICIO AND vDATA_FIM --= TRUNC(SYSDATE)-1------------------------------------TROCAR A DATA*************************************** CASO QUERIA MAIS DIAS
--BETWEEN TO_DATE('07/01/2022','DD/MM/YYYY') AND TO_DATE('09/01/2022','DD/MM/YYYY')
ORDER BY A.CODIGOCONTRATO,A.AUTOIDFICHAATENDIMENTO
)X

GROUP BY 
 X.AUTOIDFICHAATENDIMENTO, X.CODIGOEMPRESA, X.CODIGOTIPOCONTRATO, X.CODIGOCONTRATO, X.DATAOCORRENCIA, X.DATAINICIOAFAST, X.DATAFIMAFAST, X.TIPOPROCEDIMENTO, X.CODIGOCONDUTA
,X.OCORRENCIA, X.CODIGO_PESSOA
 ORDER BY  X.AUTOIDFICHAATENDIMENTO, X.CODIGOEMPRESA, X.CODIGOTIPOCONTRATO, X.CODIGOCONTRATO, X.DATAOCORRENCIA, X.DATAINICIOAFAST, X.DATAFIMAFAST, X.TIPOPROCEDIMENTO, X.CODIGOCONDUTA
)X2
LEFT OUTER JOIN
(--ALT SIT FUNC PARCIAL
select
X.CODIGO_EMPRESA CODIGO_EMPRESA_SFP, X.TIPO_CONTRATO TIPO_CONTRATO_SFP, X.CODIGO CODIGO_CONTRATO_SFP, X.COD_SIT_FUNCIONAL COD_SIT_FUNCIONAL_SFP,
S.DESCRICAO SFP_DESC_SIT_FUNC,
X.DATA_INIC_SITUACAO DATA_INIC_SITUACAO_SFP,  X.DATA_FIM_SITUACAO DATA_FIM_SITUACAO_SFP,
S.CONTROLE_FOLHA CONTROLE_FOLHA_SFP, S.E_AFASTAMENTO E_AFASTAMENTO_SFP, S.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_SFP, S.c_livre_selec02 SO_PONTO_SFP
from RHCGED_ALT_SIT_FUN X 
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = X.COD_SIT_FUNCIONAL
WHERE S.SITUACAO_PONTO IS NOT NULL--S.CONTROLE_FOLHA <> 'N' -- AND S.E_AFASTAMENTO <> 'N' AND S.SUSPENDE_REMUNERA <> 'N'
)SFP  ON --SIT FUNC PARCIAL NO PERIODO DA FICHA
SFP.CODIGO_EMPRESA_SFP = X2.CODIGOEMPRESA AND SFP.TIPO_CONTRATO_SFP = X2.CODIGOTIPOCONTRATO AND SFP.CODIGO_CONTRATO_SFP = X2.CODIGOCONTRATO
AND
  ((TRUNC(SFP.DATA_INIC_SITUACAO_SFP) >= TRUNC(X2.DATAINICIOAFAST) AND TRUNC(SFP.DATA_INIC_SITUACAO_SFP) <= TRUNC(X2.DATAFIMAFAST))
  OR (TRUNC(SFP.DATA_INIC_SITUACAO_SFP)< TRUNC(X2.DATAINICIOAFAST) AND TRUNC(SFP.DATA_FIM_SITUACAO_SFP) >= TRUNC(X2.DATAINICIOAFAST))
)

-------------------------------------------------------------INICIO --NOVO EM 22/7/22 PARA ATENDER FICHAS MEDICAS MANUAIS NAO ORIGINADAS DA TEG EMAIL (LANÇAMENTO DE ATESTADO DATA FUTURA)
UNION ALL ------------------------------------------------------------------------

SELECT 'MANUAL' ORIGEM, 
NULL AUTOIDFICHAATENDIMENTO, X2.CODIGO_EMPRESA CODIGOEMPRESA, X2.TIPO_CONTRATO CODIGOTIPOCONTRATO, X2.CODIGO_CONTRATO CODIGOCONTRATO, X2.DT_REG_OCORRENCIA DATAOCORRENCIA, 
X2.OCORRENCIA, X2.CODIGO_PESSOA,
X2.data_ini_afast DATAINICIOAFAST, X2.data_FIM_afast DATAFIMAFAST, X2.NATUREZA_EXAME TIPOPROCEDIMENTO, NULL CODIGOCONDUTA, NULL TOTAL_STATUS_PROCESSAMENTO, NULL GRAVOU_FICHA, NULL QTD_REGISTROS,
SFP.COD_SIT_FUNCIONAL_SFP, SFP.SFP_DESC_SIT_FUNC, SFP.DATA_INIC_SITUACAO_SFP, SFP.DATA_FIM_SITUACAO_SFP
FROM(
SELECT 
X.*
FROM(
SELECT
CASE WHEN F.OCORRENCIA IS NULL THEN  0 ELSE 1 END GRAVOU_FICHA,
F.*
FROM  RHMEDI_FICHA_MED F 
WHERE
--COMENTAR PARA TESTES --
F.LOCAL_ATENDIMENTO IS NULL AND F.C_LIVRE_VALOR01 IS NULL AND--APENAS MANUAIS
TRUNC(F.data_ini_afast)> TRUNC(F.dt_reg_ocorrencia)AND 
--TRUNC(F.data_ini_afast) BETWEEN TRUNC(SYSDATE)-354 AND TRUNC(SYSDATE)-1 ------------------------------------TROCAR A DATA*************************************** CASO QUERIA MAIS DIAS
--TESTE 27/12/23--
TRUNC(F.data_ini_afast) BETWEEN vDATA_INICIO AND vDATA_FIM --= TRUNC(SYSDATE)-1 AND TRUNC(SYSDATE)-1------------------------------------TROCAR A DATA*************************************** CASO QUERIA MAIS DIAS
ORDER BY 1,2,3,4,5,6
)X

)X2
LEFT OUTER JOIN
(--ALT SIT FUNC PARCIAL
select
X.CODIGO_EMPRESA CODIGO_EMPRESA_SFP, X.TIPO_CONTRATO TIPO_CONTRATO_SFP, X.CODIGO CODIGO_CONTRATO_SFP, X.COD_SIT_FUNCIONAL COD_SIT_FUNCIONAL_SFP,
S.DESCRICAO SFP_DESC_SIT_FUNC,
X.DATA_INIC_SITUACAO DATA_INIC_SITUACAO_SFP,  X.DATA_FIM_SITUACAO DATA_FIM_SITUACAO_SFP,
S.CONTROLE_FOLHA CONTROLE_FOLHA_SFP, S.E_AFASTAMENTO E_AFASTAMENTO_SFP, S.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_SFP, S.c_livre_selec02 SO_PONTO_SFP
from RHCGED_ALT_SIT_FUN X 
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = X.COD_SIT_FUNCIONAL
WHERE S.SITUACAO_PONTO IS NOT NULL--S.CONTROLE_FOLHA <> 'N' -- AND S.E_AFASTAMENTO <> 'N' AND S.SUSPENDE_REMUNERA <> 'N'
)SFP  ON --SIT FUNC PARCIAL NO PERIODO DA FICHA
SFP.CODIGO_EMPRESA_SFP = X2.CODIGO_EMPRESA AND SFP.TIPO_CONTRATO_SFP = X2.TIPO_CONTRATO AND SFP.CODIGO_CONTRATO_SFP = X2.CODIGO_CONTRATO
AND
  ((TRUNC(SFP.DATA_INIC_SITUACAO_SFP) >= TRUNC(X2.data_ini_afast) AND TRUNC(SFP.DATA_INIC_SITUACAO_SFP) <= TRUNC(X2.data_FIM_afast))
  OR (TRUNC(SFP.DATA_INIC_SITUACAO_SFP)< TRUNC(X2.data_ini_afast) AND TRUNC(SFP.DATA_FIM_SITUACAO_SFP) >= TRUNC(X2.data_ini_afast))
)
-----------------------------------------------------------------FIM--NOVO EM 22/7/22 PARA ATENDER FICHAS MEDICAS MANUAIS NAO ORIGINADAS DA TEG EMAIL (LANÇAMENTO DE ATESTADO DATA FUTURA)


)LOOP

vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--'||vCONTADOR);
dbms_output.put_line('--C1.CODIGOEMPRESA: '||C1.CODIGOEMPRESA||' C1.CODIGOTIPOCONTRATO: '||C1.CODIGOTIPOCONTRATO||' C1.CODIGOCONTRATO: '||C1.CODIGOCONTRATO||' C1.DATAOCORRENCIA: '||C1.DATAOCORRENCIA||' C1.DATAINICIOAFAST: '||C1.DATAINICIOAFAST||' C1.DATAFIMAFAST: '||C1.DATAFIMAFAST|| ' AUTOIDFICHAATENDIMENTO: '||C1.AUTOIDFICHAATENDIMENTO);

BEGIN --EXCEPTION

IF C1.ORIGEM = 'TEG' THEN--IF NOVO EM 22/7/22
dbms_output.put_line('--C1.ORIGEM: ' ||C1.ORIGEM ); 
IF C1.COD_SIT_FUNCIONAL_SFP IS NULL AND C1.GRAVOU_FICHA = 0 THEN
--PR_ACERTO_REPFICHA_1BM(C1.CODIGOEMPRESA,C1.CODIGOTIPOCONTRATO,C1.CODIGOCONTRATO, C1.DATAINICIOAFAST, C1.DATAFIMAFAST);
--dbms_output.put_line('EXECUTE PR_ACERTO_REPFICHA_1BM('''||C1.CODIGOEMPRESA||''','''||C1.CODIGOTIPOCONTRATO||''','''||C1.CODIGOCONTRATO||''', TO_DATE('''||C1.DATAINICIOAFAST||''',''DD/MM/YYYY''), TO_DATE('''||C1.DATAFIMAFAST||''',''DD/MM/YYYY''));');
--UPDATE SUGESP_ARQUIVOS_FICHA  SET DATA_PROCESSAMENTO = SYSDATE, STATUS_PROCESSAMENTO =  'SIM' WHERE ID = C1.ID; COMMIT;
--dbms_output.put_line('UPDATE SUGESP_ARQUIVOS_FICHA  SET DATA_PROCESSAMENTO = NULL , STATUS_PROCESSAMENTO =  NULL WHERE ID = '||C1.ID||'; COMMIT;');
UPDATE SUGESP_ARQUIVOS_FICHA  SET DATA_PROCESSAMENTO = NULL , STATUS_PROCESSAMENTO =  NULL WHERE AUTOIDFICHAATENDIMENTO = C1.AUTOIDFICHAATENDIMENTO; COMMIT;
PR_GRAVA_FICHA_MEDICA_TEG;
UPDATE SUGESP_ARQUIVOS_FICHA SET  DATA_PROCESSAMENTO = SYSDATE , STATUS_PROCESSAMENTO =  'SIM' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL AND AUTOIDFICHAATENDIMENTO = C1.AUTOIDFICHAATENDIMENTO;COMMIT;

--dbms_output.put_line('--grava SUGESP_ARQUIVOS_FICHADATA_PROCESSAMENTO = SYSDATE, STATUS_PROCESSAMENTO =  SIM, ID: '|| C1.ID || ' SYSDATE:' || TO_DATE(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));

ELSIF C1.COD_SIT_FUNCIONAL_SFP IS NULL AND C1.GRAVOU_FICHA > 0 THEN
--COMENTADO EM 27/12/23--PR_ACERTO_REPFICHA_1BM(C1.CODIGOEMPRESA,C1.CODIGOTIPOCONTRATO,C1.CODIGOCONTRATO, TO_DATE(C1.DATAINICIOAFAST,'DD/MM/YYYY'), TO_DATE(C1.DATAFIMAFAST,'DD/MM/YYYY'));
PR_REPROCESSA_FICHA_PERICIA (C1.CODIGOEMPRESA, C1.CODIGO_PESSOA, TO_DATE(C1.DATAOCORRENCIA,'DD/MM/YYYY'), C1.OCORRENCIA);--NOVO EM 27/12/23
UPDATE SUGESP_ARQUIVOS_FICHA SET DATA_PROCESSAMENTO = SYSDATE , STATUS_PROCESSAMENTO =  'SIM' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL AND AUTOIDFICHAATENDIMENTO = C1.AUTOIDFICHAATENDIMENTO;COMMIT;

END IF;

ELSIF C1.ORIGEM = 'MANUAL' THEN --PARTE NVOA 22/7/22
dbms_output.put_line('--C1.ORIGEM: ' ||C1.ORIGEM );
--COMENTADO EM 27/12/23--PR_ACERTO_REPFICHA_1BM(C1.CODIGOEMPRESA,C1.CODIGOTIPOCONTRATO,C1.CODIGOCONTRATO, TO_DATE(C1.DATAINICIOAFAST,'DD/MM/YYYY'), TO_DATE(C1.DATAFIMAFAST,'DD/MM/YYYY'));
PR_REPROCESSA_FICHA_PERICIA (C1.CODIGOEMPRESA, C1.CODIGO_PESSOA, TO_DATE(C1.DATAOCORRENCIA,'DD/MM/YYYY'), C1.OCORRENCIA);--NOVO EM 27/12/23
END IF;--IF NOVO EM 22/7/22

EXCEPTION WHEN OTHERS THEN
err_msg := SQLCODE||' '||SUBSTR(SQLERRM, 1, 4000);
dbms_output.put_line('err_msg:' ||err_msg);

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_2, CAMPO_VALOR_3, CAMPO_VALOR_1,  DATA_DADOS, CONSIDERACOES)
VALUES(C1.CODIGOEMPRESA,C1.CODIGOTIPOCONTRATO, C1.CODIGOCONTRATO,C1.DATAINICIOAFAST, C1.DATAFIMAFAST, 'LOG EXECUCAO PR_FICHA_FUTURA_GRAVA_SIT_FUNC', SYSDATE, err_msg
);COMMIT;
END;--BEGIN EXCEPTION

err_msg := NULL;

END LOOP;


END;

END;