
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_FICHA_MEDICA_AJUSTE_DOENCAS" ( TABELA IN VARCHAR2, CODIGO_EMPRESA IN VARCHAR2, CODIGO_PESSOA IN VARCHAR2,  DATA_OCORRENCIA IN VARCHAR2, OCORRENCIA IN NUMBER , ORIGEM IN VARCHAR2, ID_EXTERNO IN NUMBER) AS 
--(ID IN NUMBER) AS 
--KELLYSSON CRIADO EM 03/11/20 PARA DESFAZER SITUAÇÃO FUNCIONAL E PONTO ORIGINADO DE FICHAS MEDICAS QUANDO ALTERA OU EXCLUI UMA FICHA.
--TRAZENDO A PARTE DE ATUALIZAR AS DOENCAS GRAVES QUE NÃO ESTAVAM FUNCIONANDO NA PROCEDURE PR_FICHA_MEDICA_AJUSTE_FICHAS

BEGIN

DECLARE
VCONTADOR NUMBER;
--VLOGIN_USUARIO VARCHAR2(40);
VID NUMBER;
V_ULT_SIT_FUNC0_ATIVA  VARCHAR2(4);
num_dias NUMBER;
vDATA_DIA DATE; 

VTABELA VARCHAR2(30);
VCODIGO_EMPRESA VARCHAR2(4);
VCODIGO_PESSOA VARCHAR2(15);
VDATA_OCORRENCIA VARCHAR2(8);
VOCORRENCIA NUMBER;
VORIGEM VARCHAR2 (1);
VID_EXTERNO NUMBER;


BEGIN

DBMS_OUTPUT.ENABLE(NULL);
VCONTADOR :=0;
--VLOGIN_USUARIO :=NULL;
VID := ID_EXTERNO; --NULL; --ID;
V_ULT_SIT_FUNC0_ATIVA := NULL;

num_dias := 0;
vDATA_DIA := null; --zera variavel


VTABELA := TABELA;
VCODIGO_EMPRESA := CODIGO_EMPRESA;
VCODIGO_PESSOA := CODIGO_PESSOA;
VDATA_OCORRENCIA := DATA_OCORRENCIA;
VOCORRENCIA := OCORRENCIA;
VORIGEM := ORIGEM;
VID_EXTERNO := ID_EXTERNO;


SELECT X.ID 
INTO VID--, VTIPO_DML, VTABELA, VCODIGO_EMPRESA, VTIPO_CONTRATO, VCODIGO_CONTRATO, VCODIGO_PESSOA, VNEW_COD_SIT_FUNCIONAL, VOLD_COD_SIT_FUNCIONAL, VDT_REG_OCORRENCIA, VOCORRENCIA, VNEW_NATUREZA_EXAME, VOLD_NATUREZA_EXAME,
--VNEW_DATA_INI_AFAST, VOLD_DATA_INI_AFAST, VNEW_DATA_FIM_AFAST, VOLD_DATA_FIM_AFAST, VNEW_DATA_INICIAL_INDEFERIMENT, VOLD_DATA_INICIAL_INDEFERIMENT, VNEW_DATA_FINAL_INDEFERIMENTO, VOLD_DATA_FINAL_INDEFERIMENTO, VNEW_OCOR_PROC_MED, VOLD_OCOR_PROC_MED, VNEW_CODIGO_PROC_MED, VOLD_CODIGO_PROC_MED, VNEW_OCOR_DOENCA, VOLD_OCOR_DOENCA, VNEW_COD_DOENCA, VOLD_COD_DOENCA, VDT_ULT_ALTER_USUA, VLOGIN_USUARIO, VLOGIN_OS
--,VNEW_C_LIVRE_OPCAO01, VOLD_C_LIVRE_OPCAO01, VNEW_C_LIVRE_DESCR02, VOLD_C_LIVRE_DESCR02, VNEW_QTD_DOENCA, VOLD_QTD_DOENCA , VPROCESSADO
FROM SUGESP_FICHAS_MEDICAS X WHERE 
X.CODIGO_EMPRESA = VCODIGO_EMPRESA AND X.CODIGO_PESSOA = VCODIGO_PESSOA  AND TRUNC(X.DT_REG_OCORRENCIA) = TO_DATE(VDATA_OCORRENCIA,'YYYYMMDD') AND X.OCORRENCIA = VOCORRENCIA
AND X.ID = (SELECT MAX(ID) FROM SUGESP_FICHAS_MEDICAS F WHERE F.CODIGO_EMPRESA = VCODIGO_EMPRESA AND F.CODIGO_PESSOA = VCODIGO_PESSOA  
AND TRUNC(F.DT_REG_OCORRENCIA) = TO_DATE(VDATA_OCORRENCIA,'YYYYMMDD') AND F.OCORRENCIA = VOCORRENCIA);


--inicio------------------------------------------------------PARA PEGAR DADOS DA FICHA PELA TABELA DE LOG
FOR C1 IN(

SELECT 
X.TIPO_DML, X.TABELA, F.NATUREZA_EXAME PROCEDIMENTO, CASE WHEN X.TIPO_DML <> 'D' THEN C.CODIGO_PROC_MED ELSE X.OLD_CODIGO_PROC_MED END CONDUTA, V.CODIGO VINCULO, V.c_livre_sel1 SIT_FUNC_ATIVA,
F.DATA_INI_AFAST, F.DATA_FIM_AFAST,
TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, X.LOGIN_USUARIO
,X.CODIGO_PESSOA, X.DT_REG_OCORRENCIA, X.OCORRENCIA
,X.NEW_NATUREZA_EXAME, X.OLD_NATUREZA_EXAME, X.NEW_DATA_INI_AFAST, X.OLD_DATA_INI_AFAST, X.NEW_DATA_FIM_AFAST, X.OLD_DATA_FIM_AFAST
FROM 
SUGESP_FICHAS_MEDICAS X
LEFT OUTER JOIN RHMEDI_RL_FICH_PRO C ON X.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND X.CODIGO_PESSOA = C.CODIGO_PESSOA AND X.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND X.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_FICHA_MED F ON F.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND F.CODIGO_PESSOA = X.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = X.DT_REG_OCORRENCIA AND F.OCORRENCIA = X.OCORRENCIA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = A.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = A.TIPO_CONTRATO AND AUX.CODIGO = A.CODIGO))
  A ON A.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO ='TEG1')TC1 
--ATE 2/7/20--ON SUBSTR(TC1.DADO_ORIGEM,1,24) =  F.NATUREZA_EXAME||X.OLD_CODIGO_PROC_MED||V.TP_REGIME_TRAB_ESOCIAL|| V.TP_REGIME_PREV_ESOCIAL||V.COD_CATEG_ESOCIAL --PROCEDIMENTO
ON SUBSTR(TC1.DADO_ORIGEM,1,23) = F.NATUREZA_EXAME||CASE WHEN X.TIPO_DML <> 'D' THEN C.CODIGO_PROC_MED ELSE X.OLD_CODIGO_PROC_MED END||V.CODIGO --novo em 2/7/20
WHERE X.ID = VID--201728
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL
AND TC1.DADO_ORIGEM  IS NOT NULL
--fim------------------------------------------------------PARA PEGAR DADOS DA FICHA PELA TABELA DE LOG


)
LOOP
VCONTADOR :=VCONTADOR+1;
DBMS_OUTPUT.PUT_LINE('--'||VCONTADOR);
DBMS_OUTPUT.PUT_LINE('--'||C1.CODIGO_EMPRESA ||'-'|| C1.TIPO_CONTRATO ||'-'|| C1.CODIGO_CONTRATO ||'-'|| C1.DATA_INI_AFAST ||'-'|| C1.DATA_FIM_AFAST ||'-'|| C1.DADO_ORIGEM_TC1 ||'-'|| C1.DADO_DESTINO_TC1 ||'-'|| C1.PROCEDIMENTO ||'-'||C1.CONDUTA ||'-'|| C1.VINCULO ||'-'|| C1.SIT_FUNC_ATIVA);

vDATA_DIA := C1.DATA_INI_AFAST;


----------------------------------------------------------------------------------****************************************************************-------------------------------


--INICIO  ------------------------------------------------------------------------------ALTERACAO DE PROCEDIMENTO OU DATA DEFERIMENTO
IF C1.TIPO_DML = 'U' AND C1.TABELA = 'RHMEDI_FICHA_MED' AND 
(
(C1.NEW_NATUREZA_EXAME IS NOT NULL AND C1.OLD_NATUREZA_EXAME IS NOT NULL AND C1.NEW_NATUREZA_EXAME <> C1.OLD_NATUREZA_EXAME) OR
(C1.NEW_DATA_INI_AFAST IS NOT NULL AND C1.OLD_DATA_INI_AFAST IS NOT NULL AND C1.NEW_DATA_INI_AFAST <> C1.OLD_DATA_INI_AFAST) OR
(C1.NEW_DATA_FIM_AFAST IS NOT NULL AND C1.OLD_DATA_FIM_AFAST IS NOT NULL AND C1.NEW_DATA_FIM_AFAST <> C1.OLD_DATA_FIM_AFAST)
)
THEN
DBMS_OUTPUT.PUT_LINE('--ALTERACAO DE PROCEDIMENTO OU DATA DEFERIMENTO');

--INICIO --PARTE NEW

--inicio--reprocessar doencas da ficha
FOR C4 IN (
/*SELECT  MAX(X.ID) ID, CODIGO_EMPRESA, CODIGO_PESSOA, DT_REG_OCORRENCIA, OCORRENCIA  
FROM SUGESP_FICHAS_MEDICAS X WHERE X.TABELA = 'RHMEDI_RL_FICH_DOE' AND X.TIPO_DML IN ('I','U') AND
            EXISTS (SELECT A.CODIGO_EMPRESA, A.CODIGO_PESSOA, A.DT_REG_OCORRENCIA, A.OCORRENCIA FROM SUGESP_FICHAS_MEDICAS A WHERE A.ID = VID--201821
            AND A.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND A.CODIGO_PESSOA = X.CODIGO_PESSOA
                        AND A.DT_REG_OCORRENCIA = X.DT_REG_OCORRENCIA AND A.OCORRENCIA = X.OCORRENCIA)
GROUP BY NEW_OCOR_DOENCA,  CODIGO_EMPRESA, CODIGO_PESSOA, DT_REG_OCORRENCIA, OCORRENCIA
ORDER BY NEW_OCOR_DOENCA    
*/
------INICIO------------------------------NOVA LOGICA
SELECT X5.* 
,CASE 
WHEN X5.DOENCA_GRAVE = 'FICHA_COM_DOENCA_GRAVE' THEN SUBSTR(X5.DADO_DESTINO_TC1,17,4) 
WHEN X5.DOENCA_GRAVE = 'FICHA_SEM_DOENCA_GRAVE' THEN SUBSTR(X5.DADO_DESTINO_TC1,1,4) 
END SITUACAO_FUNCIONAL
,CASE 
WHEN X5.DOENCA_GRAVE = 'FICHA_COM_DOENCA_GRAVE' THEN SUBSTR(X5.DADO_DESTINO_TC1,21,4) 
WHEN X5.DOENCA_GRAVE = 'FICHA_SEM_DOENCA_GRAVE' THEN SUBSTR(X5.DADO_DESTINO_TC1,9,4) 
END SITUACAO_PONTO
,SUBSTR(X5.DADO_DESTINO_TC1,21,4) SIT_PONTO_DOENCA_GRAVE 
,SUBSTR(X5.DADO_DESTINO_TC1,9,4) SIT_PONTO_DOENCA_NORMAL 
FROM (
SELECT 
X4.*
,CASE 
WHEN X4.SUM_CONDUTA < 1 THEN 'FICHA_IMCOMPLETA'
--WHEN X4.SUM_CONDUTA >= 1 AND X4.SUM_SIM < 1 AND X4.SUM_TEG2 < 1 AND X4.SUM_TEG3 < 1 THEN 'FICHA SEM DOENCA GRAVE'
WHEN X4.SUM_CONDUTA >= 1 AND ( (X4.SUM_SIM >= 1) OR ( X4.SUM_TEG2 >= 1 AND X4.SUM_TEG3 >= 1 ) ) THEN 'FICHA_COM_DOENCA_GRAVE'
ELSE 'FICHA_SEM_DOENCA_GRAVE'
END DOENCA_GRAVE
FROM(
SELECT 
X3.CODIGO_EMPRESA, X3.TIPO_CONTRATO, X3.CODIGO_CONTRATO, X3.CODIGO_PESSOA, X3.dt_reg_ocorrencia, X3.OCORRENCIA,  X3.DATA_INI_AFAST , X3.DATA_FIM_AFAST,
SUM(X3.CONDUTA) SUM_CONDUTA, SUM(X3.SIM) SUM_SIM, SUM(X3.TEG2) SUM_TEG2, SUM(X3.TEG3) SUM_TEG3, X3.DADO_ORIGEM_TC1, X3.DADO_DESTINO_TC1
FROM(
SELECT
X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST,
1 CONDUTA, 0 SIM, 0 TEG2 , 0 TEG3, COUNT(1)QUANT, 
'CONDUTA' TIPO,
X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1
,NULL DADO_ORIGEM_TC2, NULL DADO_DESTINO_TC2, NULL DADO_ORIGEM_TC3, NULL DADO_DESTINO_TC3
FROM (
SELECT 
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.dt_reg_ocorrencia, F.OCORRENCIA, F.DATA_INI_AFAST , F.DATA_FIM_AFAST,
TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, A.ANO_MES_REFERENCIA, A.VINCULO, V.tp_regime_trab_esocial, V.tp_regime_prev_esocial, V.cod_categ_esocial
FROM 
RHMEDI_FICHA_MED F 
FULL OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (select max(AUX.ano_mes_referencia) from rhpess_contrato AUX where AUX.codigo_empresa = A.codigo_empresa and AUX.tipo_contrato = A.tipo_contrato and AUX.codigo = A.codigo))A 
--ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--ERRO ATE 14/10/21
ON A.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--NOVO EM 14/10/21
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1')TC1 
ON SUBSTR(TC1.DADO_ORIGEM,1,23) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO --novo em 28/8/20
WHERE 
F.CODIGO_EMPRESA = C1.CODIGO_EMPRESA 
AND F.CODIGO_PESSOA = C1.CODIGO_PESSOA
AND TRUNC(F.DT_REG_OCORRENCIA) = TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY')
AND F.OCORRENCIA = C1.OCORRENCIA
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL
)X
WHERE X.DADO_ORIGEM_TC1 IS NOT NULL
GROUP BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA,  X.DATA_INI_AFAST , X.DATA_FIM_AFAST, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1
union all
--------------------------------------------------------------------------------------------------------------------------doencas
select x2.* 
from(
SELECT 
X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST, 0 CONDUTA, 1 SIM, 0 TEG2 , 0 TEG3,
COUNT(1)QUANT_REG,
'SIM' TIPO, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1, X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
FROM (
SELECT 
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.dt_reg_ocorrencia, F.OCORRENCIA, F.DATA_INI_AFAST , F.DATA_FIM_AFAST,
1 PONTOS, TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
NULL DADO_ORIGEM_TC2, NULL DADO_DESTINO_TC2,
NULL DADO_ORIGEM_TC3, NULL DADO_DESTINO_TC3,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, A.ANO_MES_REFERENCIA, A.VINCULO, V.tp_regime_trab_esocial, V.tp_regime_prev_esocial, V.cod_categ_esocial
,CASE when A.cod_cargo_efetivo IS NULL OR A.cod_cargo_efetivo = '000000000000000' THEN 'NAO' ELSE 'SIM' END TEM_CARGO_EFETIVO
,D.OCOR_DOENCA, D.COD_DOENCA,DOE.DESCRICAO, DOE.C_LIVRE_OPCAO01 DOENCA_C_LIVRE_OPCAO01, DOE.C_LIVRE_DESCR02 DOENCA_C_LIVRE_DESCR02
FROM 
RHMEDI_FICHA_MED F 
FULL OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
full OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (select max(AUX.ano_mes_referencia) from rhpess_contrato AUX where AUX.codigo_empresa = A.codigo_empresa and AUX.tipo_contrato = A.tipo_contrato and AUX.codigo = A.codigo))A 
--ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--ERRO ATE 14/10/21
ON A.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--NOVO EM 14/10/21
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1')TC1 
ON SUBSTR(TC1.DADO_ORIGEM,1,23) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO --novo em 28/8/20
WHERE 
F.CODIGO_EMPRESA = C1.CODIGO_EMPRESA 
AND F.CODIGO_PESSOA = C1.CODIGO_PESSOA
AND TRUNC(F.DT_REG_OCORRENCIA) = TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY')
AND F.OCORRENCIA = C1.OCORRENCIA
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL
)X
WHERE X.DOENCA_C_LIVRE_OPCAO01 = 'S'
and X.DADO_ORIGEM_TC1 IS NOT NULL
GROUP BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1 , X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
UNION ALL
SELECT 
X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST, 0 CONDUTA, 0 SIM, 1 TEG2 , 0 TEG3,
COUNT(1)QUANT,
'TEG2' TIPO, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1, X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
FROM (
SELECT 
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.dt_reg_ocorrencia, F.OCORRENCIA, F.DATA_INI_AFAST , F.DATA_FIM_AFAST,
0.5 PONTOS, TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
TC2.DADO_ORIGEM DADO_ORIGEM_TC2, TC2.DADO_DESTINO DADO_DESTINO_TC2,
NULL DADO_ORIGEM_TC3, NULL DADO_DESTINO_TC3,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, A.ANO_MES_REFERENCIA, A.VINCULO, V.tp_regime_trab_esocial, V.tp_regime_prev_esocial, V.cod_categ_esocial
,CASE when A.cod_cargo_efetivo IS NULL OR A.cod_cargo_efetivo = '000000000000000' THEN 'NAO' ELSE 'SIM' END TEM_CARGO_EFETIVO
,D.OCOR_DOENCA, D.COD_DOENCA, DOE.C_LIVRE_OPCAO01 DOENCA_C_LIVRE_OPCAO01, DOE.C_LIVRE_DESCR02 DOENCA_C_LIVRE_DESCR02
FROM 
RHMEDI_FICHA_MED F 
FULL OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
full OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (select max(AUX.ano_mes_referencia) from rhpess_contrato AUX where AUX.codigo_empresa = A.codigo_empresa and AUX.tipo_contrato = A.tipo_contrato and AUX.codigo = A.codigo))A 
--ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--ERRO ATE 14/10/21
ON A.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--NOVO EM 14/10/21
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1')TC1 
ON SUBSTR(TC1.DADO_ORIGEM,1,23) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO --novo em 28/8/20
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG2')TC2 
ON SUBSTR(TC2.DADO_ORIGEM,1,23) = F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO AND SUBSTR(TC2.DADO_ORIGEM,24,LENGTH(TC2.DADO_ORIGEM)) =  DOE.C_LIVRE_DESCR02
WHERE 
F.CODIGO_EMPRESA = C1.CODIGO_EMPRESA 
AND F.CODIGO_PESSOA = C1.CODIGO_PESSOA
AND TRUNC(F.DT_REG_OCORRENCIA) = TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY')
AND F.OCORRENCIA = C1.OCORRENCIA
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL
)X
WHERE X.DADO_ORIGEM_TC1 IS NOT NULL
and X.DADO_ORIGEM_TC2 IS NOT NULL
GROUP BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1
, X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
UNION ALL
SELECT 
X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA, X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST,
0 CONDUTA, 0 SIM, 0 TEG2 , 1 TEG3,
COUNT(1)QUANT,
'TEG3' TIPO, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1
, X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
FROM (
SELECT 
F.CODIGO_EMPRESA, F.TIPO_CONTRATO, F.CODIGO_CONTRATO, F.CODIGO_PESSOA, F.dt_reg_ocorrencia, F.OCORRENCIA, F.DATA_INI_AFAST , F.DATA_FIM_AFAST,
0.5 PONTOS,
TC1.DADO_ORIGEM DADO_ORIGEM_TC1, TC1.DADO_DESTINO DADO_DESTINO_TC1,
NULL DADO_ORIGEM_TC2, NULL DADO_DESTINO_TC2,
TC3.DADO_ORIGEM DADO_ORIGEM_TC3, TC3.DADO_DESTINO DADO_DESTINO_TC3,
C.OCOR_PROC_MED, C.CODIGO_PROC_MED, A.ANO_MES_REFERENCIA, A.VINCULO, V.tp_regime_trab_esocial, V.tp_regime_prev_esocial, V.cod_categ_esocial
,CASE when A.cod_cargo_efetivo IS NULL OR A.cod_cargo_efetivo = '000000000000000' THEN 'NAO' ELSE 'SIM' END TEM_CARGO_EFETIVO
,D.OCOR_DOENCA, D.COD_DOENCA, DOE.C_LIVRE_OPCAO01 DOENCA_C_LIVRE_OPCAO01, DOE.C_LIVRE_DESCR02 DOENCA_C_LIVRE_DESCR02
FROM 
RHMEDI_FICHA_MED F
FULL OUTER JOIN RHMEDI_RL_FICH_PRO C ON F.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND F.CODIGO_PESSOA = C.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = C.DT_REG_OCORRENCIA AND F.OCORRENCIA = C.OCORRENCIA
full OUTER JOIN RHMEDI_RL_FICH_DOE D ON F.CODIGO_EMPRESA = D.CODIGO_EMPRESA AND F.CODIGO_PESSOA = D.CODIGO_PESSOA AND F.DT_REG_OCORRENCIA = D.DT_REG_OCORRENCIA AND D.OCORRENCIA = C.OCORRENCIA
LEFT OUTER JOIN RHMEDI_DOENCA DOE ON DOE.CODIGO = D.COD_DOENCA
LEFT OUTER JOIN (SELECT A.* FROM RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (select max(AUX.ano_mes_referencia) from rhpess_contrato AUX where AUX.codigo_empresa = A.codigo_empresa and AUX.tipo_contrato = A.tipo_contrato and AUX.codigo = A.codigo))A 
--ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--ERRO ATE 14/10/21
ON A.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND A.TIPO_CONTRATO = F.TIPO_CONTRATO AND A.CODIGO = F.CODIGO_CONTRATO--NOVO EM 14/10/21
LEFT OUTER JOIN RHTABS_VINCULO_EMP V ON V.CODIGO = A.VINCULO
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG1')TC1 
ON SUBSTR(TC1.DADO_ORIGEM,1,23) =  F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO --novo em 28/8/20
LEFT OUTER JOIN(SELECT * FROM RHINTE_ED_IT_CONV where codigo_CONVERSAO ='TEG3')TC3 
ON SUBSTR(TC3.DADO_ORIGEM,1,23) = F.NATUREZA_EXAME||C.CODIGO_PROC_MED||V.CODIGO AND SUBSTR(TC3.DADO_ORIGEM,24,LENGTH(TC3.DADO_ORIGEM)) =  DOE.C_LIVRE_DESCR02 --2Âª DOENCA --NOVO EM 6/7/20
WHERE
F.CODIGO_EMPRESA = C1.CODIGO_EMPRESA 
AND F.CODIGO_PESSOA = C1.CODIGO_PESSOA
AND TRUNC(F.DT_REG_OCORRENCIA) = TO_DATE(C1.DT_REG_OCORRENCIA,'DD/MM/YYYY')
AND F.OCORRENCIA = C1.OCORRENCIA
AND F.DATA_INI_AFAST IS NOT NULL AND F.DATA_FIM_AFAST IS NOT NULL
)X
WHERE X.DADO_ORIGEM_TC1 IS NOT NULL
and X.DADO_ORIGEM_TC3 IS NOT NULL
GROUP BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.CODIGO_PESSOA,  X.dt_reg_ocorrencia, X.OCORRENCIA, X.DATA_INI_AFAST , X.DATA_FIM_AFAST, X.DADO_ORIGEM_TC1, X.DADO_DESTINO_TC1
, X.DADO_ORIGEM_TC2, X.DADO_DESTINO_TC2, X.DADO_ORIGEM_TC3, X.DADO_DESTINO_TC3
--FIM DO UNION
)x2
)X3
GROUP BY X3.CODIGO_EMPRESA, X3.TIPO_CONTRATO, X3.CODIGO_CONTRATO, X3.CODIGO_PESSOA, X3.dt_reg_ocorrencia, X3.OCORRENCIA, X3.DATA_INI_AFAST , X3.DATA_FIM_AFAST, X3.DADO_ORIGEM_TC1, X3.DADO_DESTINO_TC1
)X4
)X5 
--WHERE trunc(X5.DATA_INI_AFAST ) <= to_date('01/02/20','dd/mm/yy') --------------------------DATA CORTE DO BM SANEADO----------------------------------------------------------------------------------------------------------------------------------
ORDER BY X5.CODIGO_EMPRESA, X5.TIPO_CONTRATO, X5.CODIGO_CONTRATO, X5.CODIGO_PESSOA,  X5.DATA_INI_AFAST 
------FIM------------------------------NOVA LOGICA

)
LOOP
DBMS_OUTPUT.PUT_LINE('PARTE NEW-CHAMA ATUALIZA AS FICHAS PARA DOENCAS GRAVE SE FOR NECESSARIO');

IF C4.DOENCA_GRAVE = 'FICHA_COM_DOENCA_GRAVE' THEN
--INICIO----------------------------------------------------1 PARTE para TROCAR A SITUACAO FUNCIONAL DA FICHA PARA DOENCA GRAVE
FOR C5 IN (

SELECT   A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO,
A.COD_SIT_FUNCIONAL COD_SIT_FUNC, S.DESCRICAO SITUACAO_FUNCIONAL, S.SITUACAO_PONTO COD_SIT_PONTO, P.DESCRICAO SITUACAO_PONTO,  A.DATA_INIC_SITUACAO , A.DATA_FIM_SITUACAO 
FROM RHCGED_ALT_SIT_FUN A 
LEFT OUTER JOIN RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE A.CODIGO_EMPRESA = C1.CODIGO_EMPRESA  
AND A.TIPO_CONTRATO = C1.TIPO_CONTRATO 
AND A.CODIGO = C1.CODIGO_CONTRATO
AND 
((TRUNC(A.DATA_INIC_SITUACAO) BETWEEN TRUNC(C1.NEW_DATA_INI_AFAST) AND TRUNC(C1.NEW_DATA_FIM_AFAST)) 
OR (TRUNC(A.DATA_FIM_SITUACAO) BETWEEN TRUNC(C1.NEW_DATA_INI_AFAST) AND TRUNC(C1.NEW_DATA_FIM_AFAST))
OR (TRUNC(A.DATA_INIC_SITUACAO) <= TRUNC(C1.NEW_DATA_INI_AFAST) AND TRUNC(A.DATA_FIM_SITUACAO) >= TRUNC(C1.NEW_DATA_FIM_AFAST)) )
AND A.COD_SIT_FUNCIONAL = SUBSTR(C1.DADO_DESTINO_TC1,1,4)
ORDER BY A.DATA_INIC_SITUACAO

)
LOOP

--INICIO--IF PARA O QUE FAZER
DBMS_OUTPUT.PUT_LINE('PARTE NEW- TROCA A SITUACAO FUNCIONAL DA FICHA PARA DOENCA GRAVE');

UPDATE RHCGED_ALT_SIT_FUN SET COD_SIT_FUNCIONAL = C4.SITUACAO_FUNCIONAL,  LOGIN_USUARIO = C1.LOGIN_USUARIO , DT_ULT_ALTER_USUA = SYSDATE 
WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.CODIGO_CONTRATO AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C5.DATA_INIC_SITUACAO);  COMMIT;
SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.CODIGO_EMPRESA ,C1.TIPO_CONTRATO , C1.CODIGO_CONTRATO ,C1.LOGIN_USUARIO);

--FIM----------------------------------------------------1 PARTE para TROCAR A SITUACAO FUNCIONAL DA FICHA PARA DOENCA GRAVE

END LOOP; -- FIM C5

--INICIO-------------------------------------------------2 PARTE TROCAR SITUACAO DE PONTO PARA DOENCAS GRAVE
DBMS_OUTPUT.PUT_LINE('PARTE NEW- TROCA A SITUACAO PONTO DA FICHA PARA DOENCA GRAVE');
DELETE RHPONT_RES_SIT_DIA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND trunc(DATA) BETWEEN trunc(C1.NEW_DATA_INI_AFAST) AND trunc(C1.NEW_DATA_FIM_AFAST) AND CODIGO_SITUACAO = C4.SIT_PONTO_DOENCA_NORMAL ; COMMIT;

DELETE RHPONT_RES_SIT_DIA where CODIGO_EMPRESA = C1.CODIGO_EMPRESA and TIPO_CONTRATO = C1.TIPO_CONTRATO and CODIGO_CONTRATO = C1.CODIGO_CONTRATO and trunc(DATA) BETWEEN trunc(C1.NEW_DATA_INI_AFAST) AND trunc(C1.NEW_DATA_FIM_AFAST) and CODIGO_SITUACAO = C4.SIT_PONTO_DOENCA_GRAVE and TIPO_APURACAO = 'F';COMMIT;


num_dias := (C1.DATA_FIM_AFAST - C1.DATA_INI_AFAST)+1;
for i in 1..num_dias loop

INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TIPO_APURACAO, FORCA_SITUACAO  )
VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO_CONTRATO, trunc(vDATA_DIA), C4.SIT_PONTO_DOENCA_GRAVE, 1, C1.LOGIN_USUARIO, SYSDATE, 'F', 'N');
vDATA_DIA :=  vDATA_DIA + 1;
--vDATA_DIA :=  to_date(to_char((data_inicial-1)+i,'DD/MM/YYYY'),'DD/MM/YYYY');

end loop; -- fim loop num_dias
--FIM-------------------------------------------------2 PARTE TROCAR SITUACAO DE PONTO PARA DOENCAS GRAVE
vDATA_DIA := null; --zera variavel

END IF; --IF DOENCAS GRAVES

END LOOP; --FIM C4

--fim--reprocessar doencas da ficha


--FIM--PARTE NEW

--FIM-------------------ALTERACAO DE PROCEDIMENTO OU DATA DEFERIMENTO


END IF;
----FIM------------------------------------------------------------------------------------IF PARA SABER SE ESTA SENDO EXCLUSAO DE CONDUTA OU ALTERACAO DE PROCEDIMENTO/DATAS DEFERIMENTO DA FICHA

END LOOP; --FIM C1
END;

END;