
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_GRAVA_ESPELHO_NA_HISTORICA" (pCOD_FECHAMENTO IN NUMBER, pCOD_EMPRESA IN VARCHAR2)
-- *******************************************************************************************************************
-- Descricao.....: PROCEDURE RESPONSÁVEL PELA GRAVAÇÃO DOS REGISTROS DOS ESPELHOS NA HISTORICA
--                 ESSES GERADOS PELO POWER CENTER NA TABELA DE ESPELHO
--                 TABELA PRINCIPAL: PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA 

-- Autor................: MARCELO SOARES
-- Última alteração.....: 30/28/2023
-- Compilada em PRODUÇÃO: SIM

-- Parametros....: INFORMAR O CÓDIGO DE FECHAMENTO CRIADO NO SISTEMA IFPONTO MAIS 
--                 O CÓDIGO DA EMPRESA 
-- Funcionamento.: EXECUÇÃO MANUAL
-- Periodicidade.: CONFORME A NECESSIDADE DO RH DA EMPRESA

--  PASSOS DE EXECUÇÃO PARA INTEGRAÇÃO DA PRODABEL:

--	1) CRIAR O FECHAMENTO DO ESPELHO NO SISTEMA
--	2) ENTRAR NO SISTEMA POWER CENTER E EXECUTAR O WORKFLOW:
--		2.1) INTEGRAÇÃO DO ESPELHO
--		2.1) INTEGRAÇÃO DE BANCO DE HORAS
--	3) ENTRAR  NO SISTEMA ARTERH NA OPÇÃO COMANDO SQL  E EXECUTAR OS SQL´S:
--		3.1) GRAVA REGISTROS DO ESPELHO NA HISTORICA
--		3.2) GERAR TOTALIZADORA DO ESPELHO DE PONTO
--		3.3) GERAR TOTALIZADORA DE BANCO DE HORAS
--		3.4) GRAVA PLANILHA DE SITUAÇÃO DE PONTO 
-- 		3.5) EXECUTAR O SQL QUE APAGARÁ TODOS OS REGISTROS CRIADOS NA PLANILHA SITUAÇÃO PONTO E NAS TABELAS DE APOIO

-- *******************************************************************************************************************
IS
BEGIN
	INSERT INTO PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA
	(TIPO_CONTRATO, MATRICULA, CODIGO, SIT_PONTO, DTCADASTRO, COD_PESSOA, COD_JUSTIFICATIVA_PONTO, COD_PONTO_FECHAMENTO, COD_BANCO_HORAS, 
	COD_CARGO, COD_UNIDADE, COD_EMPRESA, COD_HORARIO, COD_ESCALA_PADRAO, CAMPO_LIVRE, DATA, MARCACAO1, MARCACAO2, MARCACAO3, MARCACAO4, 
	MARCACAO5, MARCACAO6, MARCACAO7, MARCACAO8, MARCACAO9, MARCACAO10, MARCACAO11, MARCACAO12, MARCACAO_E1, MARCACAO_E2, MARCACAO_E3, 
	MARCACAO_E4, MARCACAO_E5, MARCACAO_E6, MARCACAO_E7, MARCACAO_E8, MARCACAO_E9, MARCACAO_E10, MARCACAO_E11, MARCACAO_E12, MARCACAO1_ALTERADA, 
	MARCACAO2_ALTERADA, MARCACAO3_ALTERADA, MARCACAO4_ALTERADA, MARCACAO5_ALTERADA, MARCACAO6_ALTERADA, MARCACAO7_ALTERADA, MARCACAO8_ALTERADA, 
	MARCACAO9_ALTERADA, MARCACAO10_ALTERADA, MARCACAO11_ALTERADA, MARCACAO12_ALTERADA, OBS_MARCACAO_ALTERADA, SITUACAO, ENTRADA, BANCO_HORAS, 
	TIPO_BANCO_HORAS, OBS, ACEITO, H_NORMAIS, DESCONTO, H_EXTRA, H_EXTRA_FERIADO, H_NOTURNA, COMPENSADO, FALTA_COMPENSAR, PREVISTO, 
	DESCONTO_ABONADO, HORAS_ABONADA, ATRASO, SAIDA_ANTECIPADA, H_EXTRA_NOTURNA, H_INTRA_JORNADA, DESCONTO_AUX, INTERJORNADA, BH_CREDITO, 
	BH_DEBITO, BIT_DIVERGENCIA, COD_COMPENSACAO, MULTIPLICADOR_BANCO_HORAS, NA009, DTJUSTIFICATIVA, LOGIN_JUSTIFICATIVA, DTAVALIADOR, 
	LOGIN_AVALIADOR, DTALTERACAO, LOGIN_ALTERACAO, FOTO, SOBREAVISO_DOBRA, TOTAIS, COD_JUSTIFICATIVA_BANCO_HORAS, DESCRICAO_BANCO_HORAS, 
	COMPROVANTE_JUSTIFICATIVA, RELATORIO_RH_VALIDADO, DESCONTO_TOLERADO, INTERVALO_A_MENOR, ENTRADA_ANTECIPADA, MULTA_INTERJORNADA, 
	EXTRA_DIA_INFO_SEM_MENSAL, DESCONTO_DIA_INFO_SEM_MENSAL, TIPO_FOLGA, CARGA_HORARIA, DATA_PROCESSAMENTO, EMPRESA, TIPO_ESCALA, AGRUPADOR, 
	TIPO_SOBREAVISO, HRINICIO_SOBREAVISO, HRFIM_SOBREAVISO, PREVISTO_SOBREAVISO, EXECUTADO_SOBREAVISO, COD_TIPO_PESSA, DTDEMISSAO, TOTAIS_JSON, 
	FALTA_COMPENSADA, PREVISTO_TRABALHAR, SOBREAVISO_MENOS_TRABALHADO, EXTRA_AUTORIZADA, INTRAJORNADA, H_EXTRA_I, H_EXTRA_II, 
	H_EXTRA_NOTURNA_I, H_EXTRA_NOTURNA_II, DTADMISSAO, FALTA, DSR_REAL, NOTURNO_PRODABEL)

	SELECT 
	TIPO_CONTRATO, MATRICULA, CODIGO, SIT_PONTO, DTCADASTRO, COD_PESSOA, COD_JUSTIFICATIVA_PONTO, COD_PONTO_FECHAMENTO, COD_BANCO_HORAS, 
	COD_CARGO, COD_UNIDADE, COD_EMPRESA, COD_HORARIO, COD_ESCALA_PADRAO, CAMPO_LIVRE, DATA, MARCACAO1, MARCACAO2, MARCACAO3, MARCACAO4, 
	MARCACAO5, MARCACAO6, MARCACAO7, MARCACAO8, MARCACAO9, MARCACAO10, MARCACAO11, MARCACAO12, MARCACAO_E1, MARCACAO_E2, MARCACAO_E3, 
	MARCACAO_E4, MARCACAO_E5, MARCACAO_E6, MARCACAO_E7, MARCACAO_E8, MARCACAO_E9, MARCACAO_E10, MARCACAO_E11, MARCACAO_E12, MARCACAO1_ALTERADA, 
	MARCACAO2_ALTERADA, MARCACAO3_ALTERADA, MARCACAO4_ALTERADA, MARCACAO5_ALTERADA, MARCACAO6_ALTERADA, MARCACAO7_ALTERADA, MARCACAO8_ALTERADA, 
	MARCACAO9_ALTERADA, MARCACAO10_ALTERADA, MARCACAO11_ALTERADA, MARCACAO12_ALTERADA, OBS_MARCACAO_ALTERADA, SITUACAO, ENTRADA, BANCO_HORAS, 
	TIPO_BANCO_HORAS, OBS, ACEITO, H_NORMAIS, DESCONTO, H_EXTRA, H_EXTRA_FERIADO, H_NOTURNA, COMPENSADO, FALTA_COMPENSAR, PREVISTO, 
	DESCONTO_ABONADO, HORAS_ABONADA, ATRASO, SAIDA_ANTECIPADA, H_EXTRA_NOTURNA, H_INTRA_JORNADA, DESCONTO_AUX, INTERJORNADA, BH_CREDITO, 
	BH_DEBITO, BIT_DIVERGENCIA, COD_COMPENSACAO, MULTIPLICADOR_BANCO_HORAS, NA009, DTJUSTIFICATIVA, LOGIN_JUSTIFICATIVA, DTAVALIADOR, 
	LOGIN_AVALIADOR, DTALTERACAO, LOGIN_ALTERACAO, FOTO, SOBREAVISO_DOBRA, TOTAIS, COD_JUSTIFICATIVA_BANCO_HORAS, DESCRICAO_BANCO_HORAS, 
	COMPROVANTE_JUSTIFICATIVA, RELATORIO_RH_VALIDADO, 
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(DESCONTO_TOLERADO),1,1) = ','
					THEN '0' || TRIM(DESCONTO_TOLERADO)
					ELSE TRIM(DESCONTO_TOLERADO) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(DESCONTO_TOLERADO),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS DESCONTO_TOLERADO,
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(INTERVALO_A_MENOR),1,1) = ',' 
					THEN '0' || TRIM(INTERVALO_A_MENOR)
					ELSE TRIM(INTERVALO_A_MENOR) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(INTERVALO_A_MENOR),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS DINTERVALO_A_MENOR,		  
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(ENTRADA_ANTECIPADA),1,1) = ',' 
					THEN '0' || TRIM(ENTRADA_ANTECIPADA)
					ELSE TRIM(ENTRADA_ANTECIPADA) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(ENTRADA_ANTECIPADA),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS ENTRADA_ANTECIPADA,
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(MULTA_INTERJORNADA),1,1) = ',' 
					THEN '0' || TRIM(MULTA_INTERJORNADA)
					ELSE TRIM(MULTA_INTERJORNADA) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(MULTA_INTERJORNADA),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS MULTA_INTERJORNADA,
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(EXTRA_DIA_INFO_SEM_MENSAL),1,1) = ',' 
					THEN '0' || TRIM(EXTRA_DIA_INFO_SEM_MENSAL)
					ELSE TRIM(EXTRA_DIA_INFO_SEM_MENSAL) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(EXTRA_DIA_INFO_SEM_MENSAL),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS EXTRA_DIA_INFO_SEM_MENSAL,
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(DESCONTO_DIA_INFO_SEM_MENSAL),1,1) = ',' 
					THEN '0' || TRIM(DESCONTO_DIA_INFO_SEM_MENSAL)
					ELSE TRIM(DESCONTO_DIA_INFO_SEM_MENSAL) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(DESCONTO_DIA_INFO_SEM_MENSAL),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS DESCONTO_DIA_INFO_SEM_MENSAL,
	TIPO_FOLGA, CARGA_HORARIA, NULL AS DATA_PROCESSAMENTO, EMPRESA, TIPO_ESCALA, AGRUPADOR, TIPO_SOBREAVISO, 
	HRINICIO_SOBREAVISO, HRFIM_SOBREAVISO, 
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(PREVISTO_SOBREAVISO),1,1) = ',' 
					THEN '0' || TRIM(PREVISTO_SOBREAVISO)
					ELSE TRIM(PREVISTO_SOBREAVISO) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(PREVISTO_SOBREAVISO),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS PREVISTO_SOBREAVISO,
	TO_NUMBER(CASE 	WHEN SUBSTR(TRIM(EXECUTADO_SOBREAVISO),1,1) = ',' 
					THEN '0' || TRIM(EXECUTADO_SOBREAVISO)
					ELSE TRIM(EXECUTADO_SOBREAVISO) 
			END,'999999990D999999999999999',
			CASE WHEN INSTR(TRIM(EXECUTADO_SOBREAVISO),',') > 0 THEN 'NLS_NUMERIC_CHARACTERS='',.''' ELSE 'NLS_NUMERIC_CHARACTERS=''.,''' END)
			AS EXECUTADO_SOBREAVISO,
	COD_TIPO_PESSA, DTDEMISSAO, NULL AS TOTAIS_JSON,
	FALTA_COMPENSADA, 
	PREVISTO_TRABALHAR, SOBREAVISO_MENOS_TRABALHADO, EXTRA_AUTORIZADA, INTRAJORNADA, H_EXTRA_I, H_EXTRA_II, H_EXTRA_NOTURNA_I, 
	H_EXTRA_NOTURNA_II, DTADMISSAO, FALTA, DSR_REAL, NOTURNO_PRODABEL

	FROM PONTO_ELETRONICO.IFPONTO_ESPELHO

	WHERE COD_PONTO_FECHAMENTO = pCOD_FECHAMENTO
	AND   COD_EMPRESA = TO_NUMBER(pCOD_EMPRESA);

	COMMIT;

	-- APAGA OS REGISTRO DA TABELA DE ESPELHO
	DELETE FROM PONTO_ELETRONICO.IFPONTO_ESPELHO
	WHERE COD_PONTO_FECHAMENTO = pCOD_FECHAMENTO
	AND   COD_EMPRESA = TO_NUMBER(pCOD_EMPRESA);

	COMMIT;	
END PR_GRAVA_ESPELHO_NA_HISTORICA;