
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_GRAVA_SITUACAO_PONTO" (pCOD_EMPRESA IN VARCHAR2)
-- *****************************************************************************
-- Descricao.....: PROCEDURE RESPONSÁVEL PELA GRAVAÇÃO DOS REGISTROS NA TABELA
--                 DO ARTERH -> RHPONT_RES_SIT_DIA

-- Autor................: MARCELO SOARES
-- Última alteração.....: 25/28/2023
-- Compilada em PRODUÇÃO: SIM

-- Parametros....: INFORMAR O CÓDIGO DE EMPRESA
-- Funcionamento.: EXECUÇÃO MANUAL
-- Periodicidade.: CONFORME A NECESSIDADE DO RH DA EMPRESA

--  PASSOS DE EXECUÇÃO PARA INTEGRAÇÃO DA PRODABEL:

--	1) CRIAR O FECHAMENTO DO ESPELHO NO SISTEMA
--	2) ENTRAR NO SISTEMA POWER CENTER E EXECUTAR O WORKFLOW:
--		2.1) INTEGRAÇÃO DO ESPELHO
--		2.1) INTEGRAÇÃO DE BANCO DE HORAS
--	3) ENTRAR  NO SISTEMA ARTERH NA OPÇÃO COMANDO SQL  E EXECUTAR OS SQL´S:
--		3.1) GERAR TOTALIZADORA DE ESPELHO
--		3.2) GERAR TOTALIZADORA DE BANCO DE HORAS
--		3.3) GRAVAR REGISTROS NA PLANILHA SITUAÇÃO PONTO
-- 	4) SE EXISTIR A NECESSIDADE DE REPROCESSAMENTO DA INTEGRAÇÃO 
-- 		4.1) EXECUTAR O SQL QUE APAGARÁ TODOS OS REGISTROS CRIADOS NA PLANILHA SITUAÇÃO PONTO E NAS TABELAS DE APOIO

-- *****************************************************************************
IS
BEGIN
	-- GRAVA OS REGISTROS NA RHPONT_RES_SIT_DIA COM OS VALORES CONVERTIDOS EM HORA:MINUTO
	INSERT INTO ARTERH.RHPONT_RES_SIT_DIA  
	(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TIPO_APURACAO)

	SELECT CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, SITUACAO, 
		CASE WHEN INSTR(VALOR,',') > 0 
             THEN TRUNC(VALOR)||','|| LPAD(ROUND((VALOR - TRUNC(VALOR))* .60 * 100,0),2,0)
             ELSE TO_CHAR(VALOR)
        END VALOR,
        'IFPONTO', SYSDATE, 'F'
	FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_TOTALIZADORES  
	WHERE CODIGO_EMPRESA = pCOD_EMPRESA
	AND   DATA_PROCESSAMENTO IS NULL;

	COMMIT;
	
	-- PREENCHE A DATA_PROCESSAMENTO DA TABELA IFPONTO_ESPELHO_TOTALIZADORES
	UPDATE PONTO_ELETRONICO.IFPONTO_ESPELHO_TOTALIZADORES SET DATA_PROCESSAMENTO = TO_DATE(SYSDATE,'DD/MM/YYYY')	
	WHERE CODIGO_EMPRESA = pCOD_EMPRESA
	AND   DATA_PROCESSAMENTO IS NULL;

	COMMIT;	
END PR_GRAVA_SITUACAO_PONTO;