
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_GERA_RECESSO_ESTAGIO" AS
BEGIN

--Kellysson em 14/1/21 ajuste de recessos estagio já existentes

DECLARE 
vCONTADOR NUMBER; 

    vDT_INI_VIG_ESTAGIO DATE;
    vDT_FIM_VIG_ESTAGIO DATE;
    vQTD_MESES_ESTAGIO NUMBER;
    vQTD_RECESSO_ESTAGIO NUMBER;
    vDT_INI_AQUIS_RECESSO DATE;
    vDT_FIM_AQUIS_RECESSO DATE;
    vPER_AQUI_QTDE NUMBER;
    vMAX_DIAS_GOZO NUMBER;
    vQTD_ALT_SIT_FUNC_GERAL NUMBER;

BEGIN 
dbms_output.enable(null); 
vCONTADOR :=0;

    vDT_INI_VIG_ESTAGIO := NULL;
    vDT_FIM_VIG_ESTAGIO := NULL;
    vQTD_MESES_ESTAGIO := 0;
    vQTD_RECESSO_ESTAGIO := 0;
    vDT_INI_AQUIS_RECESSO := NULL;
    vDT_FIM_AQUIS_RECESSO := NULL;
    vPER_AQUI_QTDE := 0;
    vMAX_DIAS_GOZO :=0;
    vQTD_ALT_SIT_FUNC_GERAL := 0;


FOR C1 IN(

--C1
SELECT I.DT_INI_VIGENCIA, I.DT_FIM_VIGENCIA,
C.*  
FROM RHPESS_CONTRATO C
LEFT OUTER JOIN rhpess_info_estagio I ON C.CODIGO_EMPRESA = I.CODIGO_EMPRESA AND C.TIPO_CONTRATO = I.TIPO_CONTRATO AND C.CODIGO = I.CODIGO_CONTRATO
LEFT JOIN RHFERI_FERIAS F ON C.CODIGO_EMPRESA = F.CODIGO_EMPRESA AND C.TIPO_CONTRATO = F.TIPO_CONTRATO AND C.CODIGO = F.CODIGO_CONTRATO
WHERE C.VINCULO = '0009' AND C.DATA_RESCISAO IS NULL AND C.CODIGO_EMPRESA = '0001' AND
C.ANO_MES_REFERENCIA = (SELECT MAX(A.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO A WHERE A.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND A.TIPO_CONTRATO = C.TIPO_CONTRATO AND A.CODIGO = C.CODIGO)
AND (I.DT_INI_VIGENCIA IS NOT NULL AND I.DT_FIM_VIGENCIA IS NOT NULL)--1230
AND F.CODIGO_EMPRESA IS NULL
--AND TRUNC(I.DT_INI_VIGENCIA)>= TO_DATE('01/01/2020','DD/MM/YYYY')
--AND (I.DT_INI_VIGENCIA IS NULL or I.DT_FIM_VIGENCIA IS NULL)--31
ORDER BY C.CODIGO_EMPRESA, C.TIPO_CONTRATO, C.CODIGO

)LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--********vCONTADOR: '||vCONTADOR);

select max_dias_gozo 
INTO vMAX_DIAS_GOZO 
from rhparm_p_feri where codigo_empresa = C1.CODIGO_EMPRESA and codigo = '0013';

--INICIO--PEGA DADOS DA TABELA DE ESTAGIO
select dt_ini_vigencia, dt_fim_vigencia, MONTHS_BETWEEN(dt_fim_vigencia, dt_ini_vigencia) QTD_MESES, 
MONTHS_BETWEEN(dt_fim_vigencia, dt_ini_vigencia)/
(select (CASE p.per_aqui_unidade 	WHEN 'A' THEN 12*p.per_aqui_qtde WHEN 'M' THEN p.per_aqui_qtde 	WHEN 'D' THEN 30*p.per_aqui_qtde 	end) dt_fim_aquisicao from  rhparm_p_feri p  where p.codigo_empresa = C1.CODIGO_EMPRESA  and p.codigo = '0013') QTD_PERIODOS_RECESSO
,(select (CASE p.per_aqui_unidade 	WHEN 'A' THEN 12*p.per_aqui_qtde WHEN 'M' THEN p.per_aqui_qtde 	WHEN 'D' THEN 30*p.per_aqui_qtde 	end) dt_fim_aquisicao from  rhparm_p_feri p  where p.codigo_empresa = C1.CODIGO_EMPRESA  and p.codigo = '0013') per_aqui_qtde
INTO vDT_INI_VIG_ESTAGIO, vDT_FIM_VIG_ESTAGIO, vQTD_MESES_ESTAGIO, vQTD_RECESSO_ESTAGIO, vPER_AQUI_QTDE                
from rhpess_info_estagio
where CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO= C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO;
--codigo_contrato = lpad('000000003092818',15,'0')--'&1'
--FIM--PEGA DADOS DA TABELA DE ESTAGIO

dbms_output.put_line('--vDT_INI_VIG_ESTAGIO: '||vDT_INI_VIG_ESTAGIO ||' vDT_FIM_VIG_ESTAGIO: '|| vDT_FIM_VIG_ESTAGIO ||' vQTD_MESES_ESTAGIO: '|| vQTD_MESES_ESTAGIO ||' vQTD_RECESSO_ESTAGIO: '||vQTD_RECESSO_ESTAGIO|| ' vPER_AQUI_QTDE: '||vPER_AQUI_QTDE ); 

--INICIA PRIMEIRO INICIO AQUIS
vDT_INI_AQUIS_RECESSO := vDT_INI_VIG_ESTAGIO;

--INICIO--GRAVA OS PERIODOS DE RECESSO NA RHFERI_FERIAS
FOR I in 1..vQTD_RECESSO_ESTAGIO LOOP
dbms_output.put_line('--periodo I : '|| I );
--vPER_AQUI_QTDE := I;

--popula variaveis para o novo periodo
vDT_FIM_AQUIS_RECESSO :=  ADD_MONTHS(vDT_INI_VIG_ESTAGIO, I * vPER_AQUI_QTDE)-1;

IF I <> vQTD_RECESSO_ESTAGIO THEN
dbms_output.put_line('--RECESSO QUE NAO E O ULTIMO PERIODO');
--dbms_output.put_line('--INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO, vDT_INI_AQUIS_RECESSO, 1, vDT_FIM_AQUIS_RECESSO, 0, 0, NULL, NULL, vMAX_DIAS_GOZO, 0, 0, 0, ''N'',	0, 2, ''INSERT_FERIAS_ESTAGIO_SIT_FUNC_10/2022'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, NULL, vMAX_DIAS_GOZO, ''N'',	0, ''N'', ''N'');');
--dbms_output.put_line('--INSERT INTO SUGESP_RHFERI_FERIAS_REC_ESTAG (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES ('''||C1.CODIGO_EMPRESA||''','''|| C1.TIPO_CONTRATO||''','''||C1.CODIGO||''', TO_DATE('''|| vDT_INI_AQUIS_RECESSO||''',''DD/MM/YYYY''), 1, TO_DATE('''||vDT_FIM_AQUIS_RECESSO||''',''DD/MM/YYYY''), 0, 0, NULL, NULL, '||vMAX_DIAS_GOZO||', 0, 0, 0, ''N'',	0, 2, ''AJUSTE_JAN21_FERIAS_ESTAGIO_SIT_FUNC'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, NULL,'|| vMAX_DIAS_GOZO||', ''N'',	0, ''N'', ''N'');');
--dbms_output.put_line('INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES ('''||C1.CODIGO_EMPRESA||''','''|| C1.TIPO_CONTRATO||''','''||C1.CODIGO||''', TO_DATE('''|| vDT_INI_AQUIS_RECESSO||''',''DD/MM/YYYY''), 1, TO_DATE('''||vDT_FIM_AQUIS_RECESSO||''',''DD/MM/YYYY''), 0, 0, NULL, NULL, '||vMAX_DIAS_GOZO||', 0, 0, 0, ''N'',	0, 2, ''AJUSTE_MENSAL_FERIAS_ESTAGIO_SIT_FUNC'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, NULL,'|| vMAX_DIAS_GOZO||', ''N'',	0, ''N'', ''N'');');
INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO,C1.CODIGO, vDT_INI_AQUIS_RECESSO, 1, vDT_FIM_AQUIS_RECESSO, 0, 0, NULL, NULL, vMAX_DIAS_GOZO, 0, 0, 0, 'N',	0, 2, 'AJUSTE_MENSAL_FERIAS_ESTAGIO_SIT_FUNC', SYSDATE,0, '0013', 0, 0, 0, 0, 0, 0, NULL, vMAX_DIAS_GOZO, 'N',	0, 'N', 'N');COMMIT;


ELSIF I = vQTD_RECESSO_ESTAGIO THEN
dbms_output.put_line('--RECESSO QUE E O ULTIMO PERIODO');
--dbms_output.put_line('--INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO, vDT_INI_AQUIS_RECESSO, 1, vDT_FIM_AQUIS_RECESSO, 0, 0, (vDT_FIM_VIG_ESTAGIO - vMAX_DIAS_GOZO) + 1, vDT_FIM_VIG_ESTAGIO, vMAX_DIAS_GOZO, 0, 0, 0, ''N'',	0, 1, ''INSERT_FERIAS_ESTAGIO_SIT_FUNC_10/2022'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, vDT_FIM_VIG_ESTAGIO, vMAX_DIAS_GOZO, ''N'',	0, ''N'', ''N'');');
--dbms_output.put_line('--INSERT INTO SUGESP_RHFERI_FERIAS_REC_ESTAG (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS,DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES ('''||C1.CODIGO_EMPRESA||''','''||C1.TIPO_CONTRATO||''','''||C1.CODIGO||''', to_date('''|| vDT_INI_AQUIS_RECESSO||''',''dd/mm/yyyy''), 1, to_date('''||vDT_FIM_AQUIS_RECESSO||''',''dd/mm/yyyy''), 0, 0, to_date('''||(vDT_FIM_VIG_ESTAGIO - vMAX_DIAS_GOZO)||''',''dd/mm/yyyy'') + 1, to_date('''||vDT_FIM_VIG_ESTAGIO||''',''dd/mm/yyyy''), '||vMAX_DIAS_GOZO||', 0, 0, 0, ''N'',	0, 1, ''AJUSTE_JAN21_FERIAS_ESTAGIO_SIT_FUNC'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, to_date('''||vDT_FIM_VIG_ESTAGIO||''',''dd/mm/yyyy''), '|| vMAX_DIAS_GOZO|| ', ''N'',	0, ''N'', ''N'');');
--dbms_output.put_line('INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS,DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES ('''||C1.CODIGO_EMPRESA||''','''||C1.TIPO_CONTRATO||''','''||C1.CODIGO||''', to_date('''|| vDT_INI_AQUIS_RECESSO||''',''dd/mm/yyyy''), 1, to_date('''||vDT_FIM_AQUIS_RECESSO||''',''dd/mm/yyyy''), 0, 0, to_date('''||(vDT_FIM_VIG_ESTAGIO - vMAX_DIAS_GOZO)||''',''dd/mm/yyyy'') + 1, to_date('''||vDT_FIM_VIG_ESTAGIO||''',''dd/mm/yyyy''), '||vMAX_DIAS_GOZO||', 0, 0, 0, ''N'',	0, 1, ''AJUSTE_MENSAL_FERIAS_ESTAGIO_SIT_FUNC'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, to_date('''||vDT_FIM_VIG_ESTAGIO||''',''dd/mm/yyyy''), '|| vMAX_DIAS_GOZO|| ', ''N'',	0, ''N'', ''N'');');
INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS,DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES (C1.CODIGO_EMPRESA,C1.TIPO_CONTRATO,C1.CODIGO, vDT_INI_AQUIS_RECESSO, 1, vDT_FIM_AQUIS_RECESSO, 0, 0, (vDT_FIM_VIG_ESTAGIO - vMAX_DIAS_GOZO)+ 1, vDT_FIM_VIG_ESTAGIO, vMAX_DIAS_GOZO, 0, 0, 0, 'N',	0, 1, 'AJUSTE_MENSAL_FERIAS_ESTAGIO_SIT_FUNC', SYSDATE,0, '0013', 0, 0, 0, 0, 0, 0, vDT_FIM_VIG_ESTAGIO, vMAX_DIAS_GOZO, 'N',	0, 'N', 'N');COMMIT;


END IF;

--dbms_output.put_line('INSERT INTO RHFERI_FERIAS (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INI_AQUISICAO, PERIODO, DT_FIM_AQUISICAO, DIAS_PROG_FERIAS, DIAS_PROG_ABONO, DT_INI_GOZO, DT_FIM_GOZO, DIAS_GOZO_FERIAS, DIAS_ABONO, DIAS_COMPENSACAO, NRO_MESES_AFAST, ADIANT_13_SALARIO, SALDO_AUXILIAR, STATUS_CONFIRMACAO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, FALTAS_PERIODO, TIPO_FERIAS, C_LIVRE_SELEC01, C_LIVRE_SELEC02, C_LIVRE_SELEC03, C_LIVRE_VALOR01, C_LIVRE_VALOR02, C_LIVRE_VALOR03,DT_FIM_GOZO_FORCA,DIAS_GOZO_FORCA,RECEBE_ADIANT,DIAS_ABONO_FORCA,ACEITA_PREVISTO,STATUS_CALCULO)VALUES ('''||C1.CODIGO_EMPRESA||''','''|| C1.TIPO_CONTRATO||''','''||C1.CODIGO_contrato||''', TO_DATE('''|| C1.DT_INI_AQUISICAO||''',''DD/MM/YYYY''), 1, TO_DATE('''||C1.DT_FIM_AQUISICAO||''',''DD/MM/YYYY''), 0, 0, TO_DATE('''||C1.DT_INI_GOZO||''',''DD/MM/YYYY''), TO_DATE('''||C1.DT_FIM_GOZO||''',''DD/MM/YYYY''), '||c1.DIAS_GOZO_FERIAS||', 0, 0, 0, ''N'',	0, 2, ''AJUSTE_JAN21_FERIAS_ESTAGIO_SIT_FUNC'', SYSDATE,0, ''0013'', 0, 0, 0, 0, 0, 0, NULL,'||c1.DIAS_GOZO_FORCA||', ''N'',	0, ''N'', ''N'');');


--popula variaveis para o novo periodo
vDT_INI_AQUIS_RECESSO := vDT_FIM_AQUIS_RECESSO+1;

END LOOP;
--FIM--GRAVA OS PERIODOS DE RECESSO NA RHFERI_FERIAS




END LOOP;
END;

END;