
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_GERA_RELATORIO_VALE" (data_vale1 DATE,data_vale2 DATE,data_corte date)
AS
 CONTADOR NUMBER;
  VALIDA TP_VALIDA_VALE;
  v_data_ini_vale DATE;
  v_data_fim_vale DATE;
  DADOS_CONT DADOS_RETORNO_FUN;
  vQTDE_LINHAS_AFETADAS NUMBER;
  COD_LINHA VARCHAR2(15 BYTE);
  COD_ITNERARIO CHAR(4 BYTE);
  SOMA NUMBER ;
  DIRETIO CHAR;
    PROCEDURE PR_VERIFICA_VALE(V_CODIGO_EMPRESA CHAR, V_TIPO_CONTRATO  CHAR,  V_CPF VARCHAR2, V_TIPO_VALE CHAR,DATA_INI DATE,DATA_FIM DATE,tipo VARCHAR2 , ALT_DEFINITIVA CHAR)
  AS
    CONT        NUMBER;
    VEFIFICADOR NUMBER;
    dados DADOS_RETORNO_FUN;
    COD_LINHA             VARCHAR2(15 BYTE);
    COD_ITNERARIO         CHAR(4 BYTE);
    vQTDE_LINHAS_AFETADAS NUMBER;
  FUNCTION INCLUIR_VALE(v_CODIGO_EMPRESA  CHAR, v_TIPO_CONTRATO   CHAR, v_CODIGO_CONTRATO VARCHAR2 , LINHA VARCHAR2, ITINERARIO  VARCHAR2,DATA_INICIO DATE,data_fim DATE )
    RETURN NUMBER
  IS
    DADO_VALE RHVALE_TRANSPORTE%ROWTYPE;
    vQTDE_LINHAS_AFETADAS NUMBER;
    V_OCORRENCIA          NUMBER;
    V_SEQUENCIA           NUMBER;
  BEGIN
    BEGIN
      SELECT NVL(MAX(OCORRENCIA),0)+1
      INTO V_OCORRENCIA
      FROM ARTERH.RHVALE_TRANSPORTE
      WHERE CODIGO_EMPRESA =v_CODIGO_EMPRESA
      AND TIPO_CONTRATO    =v_TIPO_CONTRATO
      AND CODIGO_CONTRATO  =v_CODIGO_CONTRATO
      AND CODIGO_ITINERARIO=ITINERARIO
      AND CODIGO_LINHA     =LINHA ;
      SELECT NVL(MAX(VL.SEQUENCIA),0)+1 AS SEQUENCIA
      INTO V_SEQUENCIA
      FROM
        (SELECT TIPO_VALE
        FROM ARTERH.RHVALE_RL_LIN_ITIN LL
        WHERE LL.CODIGO_ITINERARIO=ITINERARIO
        AND LL.CODIGO_LINHA       =LINHA
        ) X
      LEFT OUTER JOIN ARTERH.RHVALE_RL_LIN_ITIN L
      ON L.TIPO_VALE=X.TIPO_VALE
      LEFT OUTER JOIN ARTERH.RHVALE_TRANSPORTE VL
      ON L.CODIGO_ITINERARIO       =VL.CODIGO_ITINERARIO
      AND L.CODIGO_LINHA           = VL.CODIGO_LINHA
      WHERE VL.CODIGO_CONTRATO     =v_CODIGO_CONTRATO
      AND VL.TIPO_CONTRATO         =v_TIPO_CONTRATO
      AND VL.CODIGO_EMPRESA        =v_CODIGO_EMPRESA ;
      DADO_VALE.CODIGO_EMPRESA    :=v_CODIGO_EMPRESA;
      DADO_VALE.TIPO_CONTRATO     :=v_TIPO_CONTRATO;
      DADO_VALE.CODIGO_CONTRATO   :=v_CODIGO_CONTRATO;
      DADO_VALE.CODIGO_LINHA      :=LINHA;
      DADO_VALE.CODIGO_ITINERARIO :=ITINERARIO;
      DADO_VALE.TIPO_DIA          :='Q';
      DADO_VALE.QTDE_VALES        :='1';
      DADO_VALE.LOGIN_USUARIO     :='PR_GERA_VALE_AUTOMATICO';
      DADO_VALE.DT_ULT_ALTER_USUA :=SYSDATE;
      DADO_VALE.SEQUENCIA         :=V_SEQUENCIA;
      DADO_VALE.OCORRENCIA        :=V_OCORRENCIA;
      DADO_VALE.DATA_INI_VIGENCIA :=DATA_INICIO;
      DADO_VALE.DATA_FIM_VIGENCIA :=data_fim;
      DADO_VALE.TEXTO_ASSOCIADO   :='REGISTRO CRIADO PELA ROTINA AUTOMATICA DO VALE';
      INSERT INTO RHVALE_TRANSPORTE VALUES DADO_VALE;
      vQTDE_LINHAS_AFETADAS := sql%rowcount;
      COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      raise_application_error (-20002,'[VALIDACAO_REGRAS] - OCORREU UMA EXCECAO AO TENTAR ATUALIZAR A SITUACAO DOS REGISTROS VALIDADOS. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' ||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;
    RETURN vQTDE_LINHAS_AFETADAS;
  END;
--FIM
--comentario teste
  FUNCTION ATUALIZAR_VALE(COD_EMPRESA CHAR,  TP_CONT CHAR,COD_CONT VARCHAR2,DATA_INI DATE,DATA_FIM DATE ,COD_LINHA CHAR,COD_IT   CHAR )
    RETURN NUMBER
  IS
    vQTDE_LINHAS_AFETADAS NUMBER;
  BEGIN
    BEGIN
      UPDATE ARTERH.RHVALE_TRANSPORTE
      SET DATA_FIM_VIGENCIA  =DATA_FIM,
        TEXTO_ASSOCIADO      = 'REGISTRO FINALIZADO PELA ROTINA AUTOMATICA DO VALE',
        LOGIN_USUARIO        = 'PR_GERA_VALE_AUTOMATICO',
        DT_ULT_ALTER_USUA    = SYSDATE
      WHERE CODIGO_CONTRATO  =COD_CONT
      AND TIPO_CONTRATO      =TP_CONT
      AND CODIGO_EMPRESA     = COD_EMPRESA
      AND CODIGO_LINHA       =COD_LINHA
      AND CODIGO_ITINERARIO  =COD_IT
      AND DATA_INI_VIGENCIA  =DATA_INI;
      vQTDE_LINHAS_AFETADAS := sql%rowcount;
      COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      raise_application_error (-20002,'[VALIDACAO_REGRAS] - OCORREU UMA EXCECAO AO TENTAR ATUALIZAR A SITUACAO DOS REGISTROS VALIDADOS. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.'||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;
    RETURN vQTDE_LINHAS_AFETADAS;
  END;
BEGIN
  dados      :=DADOS_RETORNO_FUN(NULL,NULL,NULL);
  VEFIFICADOR:=0;
  SELECT COUNT(1)QUANT
  INTO VEFIFICADOR
  FROM ARTERH.RHVALE_TRANSPORTE VL
  LEFT OUTER JOIN ARTERH.RHVALE_ITINERARIO IT
  ON IT.CODIGO=VL.CODIGO_ITINERARIO
  LEFT OUTER JOIN ARTERH.RHVALE_LINHA_TRANS LI
  ON LI.CODIGO    =VL.CODIGO_LINHA
  AND IT.TIPO_VALE=LI.TIPO_VALE
  LEFT OUTER JOIN
    (SELECT *
    FROM ARTERH.RHPESS_CONTRATO CN
    WHERE CN.ANO_MES_REFERENCIA=
      (SELECT MAX(AUX.ANO_MES_REFERENCIA)
      FROM ARTERH.RHPESS_CONTRATO AUX
      WHERE AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO
      AND AUX.CODIGO_EMPRESA  = CN.CODIGO_EMPRESA
      AND AUX.CODIGO          =CN.CODIGO
      )
    ) CN
  ON CN.CODIGO         =VL.CODIGO_CONTRATO
  AND CN.TIPO_CONTRATO =VL.TIPO_CONTRATO
  AND CN.CODIGO_EMPRESA=VL.CODIGO_EMPRESA
  LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
  ON P.CODIGO             =CN.CODIGO_PESSOA
  AND P.CODIGO_EMPRESA    =CN.CODIGO_EMPRESA
  WHERE CN.CODIGO_EMPRESA =V_CODIGO_EMPRESA
  AND CN.TIPO_CONTRATO    = V_TIPO_CONTRATO
  AND LI.TIPO_VALE        =V_TIPO_VALE
  AND P.CPF               =V_CPF
  AND (
         (VL.DATA_INI_VIGENCIA BETWEEN data_vale1 AND data_vale2)
         OR (VL.DATA_INI_VIGENCIA <=data_vale1 and VL.DATA_fim_VIGENCIA is null)
         )
  AND   OCORRENCIA          =
        (SELECT MAX (AUX.OCORRENCIA)
        FROM ARTERH.RHVALE_TRANSPORTE AUX
         LEFT OUTER JOIN
        (SELECT *
        FROM ARTERH.RHPESS_CONTRATO CN
        WHERE CN.ANO_MES_REFERENCIA=
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.TIPO_CONTRATO=CN.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA =CN.CODIGO_EMPRESA
          AND AUX.CODIGO         = CN.CODIGO
          )
        ) CN
      ON CN.CODIGO         =aux.CODIGO_CONTRATO
      AND CN.TIPO_CONTRATO =aux.TIPO_CONTRATO
      AND CN.CODIGO_EMPRESA=aux.CODIGO_EMPRESA
      LEFT OUTER JOIN ARTERH.RHPESS_PESSOA PAUX
      ON PAUX.CODIGO             =CN.CODIGO_PESSOA
      AND PAUX.CODIGO_EMPRESA    =CN.CODIGO_EMPRESA
        WHERE AUX.CODIGO_EMPRESA  =VL.CODIGO_EMPRESA
        AND AUX.TIPO_CONTRATO     =VL.TIPO_CONTRATO
        AND AUX.CODIGO_LINHA      =VL.CODIGO_LINHA
        AND AUX.CODIGO_ITINERARIO =VL.CODIGO_ITINERARIO
        AND P.CPF=PAUX.CPF
        AND (
         (AUX.DATA_INI_VIGENCIA BETWEEN data_vale1 AND data_vale2)
         OR (AUX.DATA_INI_VIGENCIA <= data_vale1 and AUX.DATA_fim_VIGENCIA is null)
         )
        );
  IF VEFIFICADOR          =0 AND TIPO='INCLUIR' AND ALT_DEFINITIVA= 'S' THEN

   INSERT INTO SMARRH_INT_RELATORIO_VALE (CODIGO_EMPRESA,TIPO_CONTRATO,CPF,TURNO,DATA_INICIO,DATA_FIM,ACAO)VALUES (V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CPF,null,DATA_INI,DATA_FIM,'INCLUIR');
              COMMIT;
    --vQTDE_LINHAS_AFETADAS :=INCLUIR_VALE(dados.CODIGO_EMPRESA,dados.TIPO_CONTRATO, dados.CODIGO_CONTRATO,COD_LINHA,COD_ITNERARIO,DATA_INI,DATA_FIM);
  ELSIF VEFIFICADOR        =0 AND TIPO='INCLUIR' AND ALT_DEFINITIVA='N' THEN

    INSERT INTO SMARRH_INT_RELATORIO_VALE (CODIGO_EMPRESA,TIPO_CONTRATO,CPF,TURNO,DATA_INICIO,DATA_FIM,ACAO)VALUES (V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CPF,null,DATA_INI,DATA_FIM,'INCLUIR');
              COMMIT;
  --  vQTDE_LINHAS_AFETADAS :=INCLUIR_VALE(dados.CODIGO_EMPRESA,dados.TIPO_CONTRATO, dados.CODIGO_CONTRATO,COD_LINHA,COD_ITNERARIO,DATA_INI,DATA_FIM);
  ELSIF VEFIFICADOR!=0 THEN
    BEGIN
      dados:=DADOS_RETORNO_FUN(NULL,NULL,NULL);
      CONT :=0;
      FOR C1 IN
      (SELECT VL.CODIGO_EMPRESA,
        VL.TIPO_CONTRATO,
        VL.CODIGO_CONTRATO,
        P.CPF,
        VL.DATA_INI_VIGENCIA,
        VL.DATA_FIM_VIGENCIA,
        VL.CODIGO_LINHA,
        VL.CODIGO_ITINERARIO
      FROM ARTERH.RHVALE_TRANSPORTE VL
      LEFT OUTER JOIN ARTERH.RHVALE_ITINERARIO IT
      ON IT.CODIGO=VL.CODIGO_ITINERARIO
      LEFT OUTER JOIN ARTERH.RHVALE_LINHA_TRANS LI
      ON LI.CODIGO    =VL.CODIGO_LINHA
      AND IT.TIPO_VALE=LI.TIPO_VALE
      LEFT OUTER JOIN
        (SELECT *
        FROM ARTERH.RHPESS_CONTRATO CN
        WHERE CN.ANO_MES_REFERENCIA=
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.TIPO_CONTRATO=CN.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA =CN.CODIGO_EMPRESA
          AND AUX.CODIGO         = CN.CODIGO
          )
        ) CN
      ON CN.CODIGO         =VL.CODIGO_CONTRATO
      AND CN.TIPO_CONTRATO =VL.TIPO_CONTRATO
      AND CN.CODIGO_EMPRESA=VL.CODIGO_EMPRESA
      LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
      ON P.CODIGO             =CN.CODIGO_PESSOA
      AND P.CODIGO_EMPRESA    =CN.CODIGO_EMPRESA
      WHERE CN.CODIGO_EMPRESA =V_CODIGO_EMPRESA
      AND CN.TIPO_CONTRATO    =V_TIPO_CONTRATO
      AND LI.TIPO_VALE        =V_TIPO_VALE
      AND P.CPF               =V_CPF
      AND (
         (VL.DATA_INI_VIGENCIA BETWEEN data_vale1 AND data_vale2)
         OR (VL.DATA_INI_VIGENCIA <=data_vale1 and VL.DATA_fim_VIGENCIA is null)
         )
      AND OCORRENCIA          =
        (SELECT MAX (AUX.OCORRENCIA)
        FROM ARTERH.RHVALE_TRANSPORTE AUX
         LEFT OUTER JOIN
        (SELECT *
        FROM ARTERH.RHPESS_CONTRATO CN
        WHERE CN.ANO_MES_REFERENCIA=
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.TIPO_CONTRATO=CN.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA =CN.CODIGO_EMPRESA
          AND AUX.CODIGO         = CN.CODIGO
          )
        ) CN
      ON CN.CODIGO         =aux.CODIGO_CONTRATO
      AND CN.TIPO_CONTRATO =aux.TIPO_CONTRATO
      AND CN.CODIGO_EMPRESA=aux.CODIGO_EMPRESA
      LEFT OUTER JOIN ARTERH.RHPESS_PESSOA PAUX
      ON PAUX.CODIGO             =CN.CODIGO_PESSOA
      AND PAUX.CODIGO_EMPRESA    =CN.CODIGO_EMPRESA
        WHERE AUX.CODIGO_EMPRESA  =VL.CODIGO_EMPRESA
        AND AUX.TIPO_CONTRATO     =VL.TIPO_CONTRATO
        AND AUX.CODIGO_LINHA      =VL.CODIGO_LINHA
        AND AUX.CODIGO_ITINERARIO =VL.CODIGO_ITINERARIO
        AND P.CPF=PAUX.CPF
        AND (
         (AUX.DATA_INI_VIGENCIA BETWEEN data_vale1 AND data_vale2)
         OR (AUX.DATA_INI_VIGENCIA <= data_vale1 and AUX.DATA_fim_VIGENCIA is null)
         )
        )
        -- AND DATA_INI_VIGENCIA=DATA_FIM
      )
      LOOP
        CONT                      :=CONT+1;
        IF TIPO                    ='INCLUIR' THEN
          IF C1.DATA_INI_VIGENCIA IS NOT NULL AND C1.DATA_FIM_VIGENCIA IS NULL AND DATA_INI> C1.DATA_INI_VIGENCIA THEN
          DBMS_Output.PUT_LINE('JA POSSUI REGISTRO ATIVO');
          ELSIF C1.DATA_INI_VIGENCIA IS NOT NULL AND C1.DATA_FIM_VIGENCIA IS NOT NULL AND C1.DATA_FIM_VIGENCIA <DATA_INI THEN
            IF ALT_DEFINITIVA         ='S' THEN
                         INSERT INTO SMARRH_INT_RELATORIO_VALE (CODIGO_EMPRESA,TIPO_CONTRATO,CPF,TURNO,DATA_INICIO,DATA_FIM,ACAO)VALUES (V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CPF,null,DATA_INI,DATA_FIM,'INCLUIR');
              COMMIT;
            ELSIF ALT_DEFINITIVA     ='N' THEN

               INSERT INTO SMARRH_INT_RELATORIO_VALE (CODIGO_EMPRESA,TIPO_CONTRATO,CPF,TURNO,DATA_INICIO,DATA_FIM,ACAO)VALUES (V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CPF,null,DATA_INI,DATA_FIM,'INCLUIR');
              COMMIT;
           --   vQTDE_LINHAS_AFETADAS :=INCLUIR_VALE(dados.CODIGO_EMPRESA, dados.TIPO_CONTRATO, dados.CODIGO_CONTRATO,COD_LINHA,COD_ITNERARIO , DATA_INI,DATA_FIM);
            END IF;
          END IF;
        ELSIF C1.DATA_INI_VIGENCIA IS NOT NULL AND C1.DATA_FIM_VIGENCIA IS NULL THEN
      --    DBMS_Output.PUT_LINE('CHAMOU REGISTRO PARA FINALZIAR COM DATA FIM ' ||TO_DATE( TO_DATE(DATA_INI,'DD/MM/rrrr')-1,'DD/MM/rrrr'));
          IF C1.DATA_INI_VIGENCIA >TO_DATE( TO_DATE(DATA_INI,'DD/MM/rrrr')-1,'DD/MM/rrrr')  THEN
         DBMS_Output.PUT_LINE('NÃO FINALZIAR AINDA');
          ELSE
           INSERT INTO SMARRH_INT_RELATORIO_VALE (CODIGO_EMPRESA,TIPO_CONTRATO,CPF,TURNO,DATA_INICIO,DATA_FIM,ACAO)VALUES (V_CODIGO_EMPRESA,V_TIPO_CONTRATO,V_CPF,null,DATA_INI,TO_DATE( DATA_INI,'DD/MM/rrrr')-1,'EXCLUIR');
              COMMIT;
        ---   vQTDE_LINHAS_AFETADAS :=ATUALIZAR_VALE (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO_CONTRATO ,C1.DATA_INI_VIGENCIA,TO_DATE( DATA_INI,'DD/MM/rrrr')-1, C1.CODIGO_LINHA ,C1.CODIGO_ITINERARIO);
          END IF;

        END IF;
      END LOOP;
    END;
  END IF;
END;
  BEGIN
  CONTADOR:=0;

    FOR C1 IN
  (SELECT P.CPF,CN.TIPO_CONTRATO,CN.CODIGO_EMPRESA 
FROM ARTERH.RHPESS_CONTRATO CN 
 LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
  ON P.CODIGO                =CN.CODIGO_PESSOA
  AND P.CODIGO_EMPRESA       =CN.CODIGO_EMPRESA
   WHERE CN.ANO_MES_REFERENCIA=
      (SELECT MAX(AUX.ANO_MES_REFERENCIA)
      FROM ARTERH.RHPESS_CONTRATO AUX
      WHERE AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO
      AND AUX.CODIGO_EMPRESA  = CN.CODIGO_EMPRESA
      AND AUX.CODIGO          =CN.CODIGO
      )
      AND CN.TIPO_CONTRATO='0001'
      AND CN.CODIGO_EMPRESA='0001'
      GROUP BY P.CPF,CN.TIPO_CONTRATO,CN.CODIGO_EMPRESA
  )LOOP
  CONTADOR:=CONTADOR+1;
   DIRETIO:='N';
---  DBMS_Output.PUT_LINE('CONTADOR-----------'||CONTADOR||'--- CPF'||C1.CPF);
  FOR X1 IN (SELECT X1.* FROM (SELECT X.*,CASE
        WHEN carga_horaria !='0800'AND X.HR_1>= '0600'AND HR_2 <= '1300' THEN 'TURNO_MANHA'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1300'AND HR_2 <='1800'  THEN 'TURNO_TARDE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1800'AND HR_2 <='2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '0000'AND HR_2<='0600'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
    FROM
      (SELECT X.*,
        H.tipo_horario,
        REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1 ,
        REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2')  AS hr_2,
        REGEXP_REPLACE(lpad( TO_CHAR(trim (HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
        REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_4 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
        REGEXP_REPLACE (lpad(TO_CHAR(trim (H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
      FROM
        (SELECT 'ESCALA_PRINCIPAL' AS TIPO,
          ALT.CODIGO_EMPRESA,
          ALT.TIPO_CONTRATO,
          ALT.CODIGO_CONTRATO,
          P.CPF,
          ALT.DT_INICIO_TROCA,
          ALT.DT_FIM_TROCA,
          ALT.COD_ESCALA,
          EL.tipo_escala
        FROM ARTERH.RHPONT_ALT_ESCALA ALT
        LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
        ON C.CODIGO         =ALT.CODIGO_CONTRATO
        AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
        AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
        LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
        ON P.CODIGO         =C.CODIGO_PESSOA
        AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
        LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
        ON SF.CODIGO=C.SITUACAO_FUNCIONAL
        LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
        ON EL.CODIGO_EMPRESA     =ALT.CODIGO_EMPRESA
        AND EL.CODIGO            = ALT.COD_ESCALA
        WHERE P.CPF              =C1.CPF
        AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
        AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
        AND ALT.ALTER_DEFINITIVA = 'S'
        AND C.ANO_MES_REFERENCIA =
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.CODIGO            =C.CODIGO
          AND AUX.TIPO_CONTRATO       = C.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA      =C.CODIGO_EMPRESA
          AND AUX.ANO_MES_REFERENCIA <= data_vale2
          )
       AND SF.CODIGO<'1715'
        ) X
      LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
      ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
      AND EH.CODIGO_ESCALA= X.COD_ESCALA
      LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
      ON H.CODIGO_EMPRESA = EH.CODIGO_EMPRESA
      AND H.CODIGO        = EH.CODIGO_HORARIO
      WHERE (
      ( x.DT_INICIO_TROCA BETWEEN data_vale1 AND data_vale2 )
      OR ( x.DT_INICIO_TROCA BETWEEN data_vale1 AND data_vale2 AND X.DT_FIM_TROCA IS NULL )
      OR (X.DT_FIM_TROCA IS NULL AND x.DT_INICIO_TROCA<=data_vale2 )
      OR (X.DT_INICIO_TROCA<=data_vale2 AND X.DT_FIM_TROCA>=data_vale2)
       OR (X.DT_INICIO_TROCA<=data_vale2 AND X.DT_FIM_TROCA BETWEEN data_vale1 AND data_vale2)
      )
      AND H.TIPO_HORARIO  ='N'
      ) X
      )X1
    GROUP BY X1.TIPO,X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO, X1.CODIGO_CONTRATO, X1.CPF, X1.DT_INICIO_TROCA, X1.DT_FIM_TROCA, X1.COD_ESCALA,X1.TIPO_ESCALA,X1.TIPO_HORARIO,X1.HR_1,X1.HR_2,X1.HR_3,X1.HR_4,X1.CARGA_HORARIA,X1.TURNO
    ORDER BY X1.DT_INICIO_TROCA)
    LOOP
    SOMA      :=0;
    IF X1.TURNO='TURNO_CHEIO' AND X1.CARGA_HORARIA>='0800' THEN
           /*   DBMS_Output.PUT_LINE('CHAMOU CRIAR VALE 0');
              DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA DEFINITIVA TURNO CHEIO');
              DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);*/
      IF X1.DT_INICIO_TROCA <data_corte THEN
          PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', data_corte,NULL,'INCLUIR','S');
        ELSE
          PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', X1.DT_INICIO_TROCA,NULL,'INCLUIR','S');
        END IF;
      ELSIF (X1.TURNO='TURNO_MANHA' OR X1.TURNO='TURNO_TARDE' OR X1.TURNO= 'TURNO_NOITE' ) THEN
         /*   DBMS_Output.PUT_LINE('ENTROU VERIFICA JORNADA PARTICIONADA');
            DBMS_Output.PUT_LINE('COD ESCALA'||X1.COD_ESCALA||' TURNO'||X1.TURNO);
            DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);*/
            DBMS_Output.PUT_LINE(X1.carga_horaria);
      SOMA :=TO_NUMBER(TRIM(REPLACE(X1.carga_horaria,':','')));
           FOR EL IN (
           SELECT EL.* FROM (SELECT X.*,CASE
        WHEN carga_horaria !='0800'AND X.HR_1>= '0600'AND HR_2 <= '1300' THEN 'TURNO_MANHA'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1300'AND HR_2 <='1800'  THEN 'TURNO_TARDE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1800'AND HR_2 <='2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '0000'AND HR_2<'0600'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
        FROM
          (SELECT X.*,
            H.tipo_horario,
            REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1,
            REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0' ), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_2,
            REGEXP_REPLACE( lpad(TO_CHAR( trim(HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
            REGEXP_REPLACE(lpad( TO_CHAR(trim( HORARIO_NORMAL_4)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
            REGEXP_REPLACE(lpad(TO_CHAR( trim( H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
          FROM
            (SELECT 'ESCALA_PRINCIPAL' AS TIPO,
              ALT.CODIGO_EMPRESA,
              ALT.TIPO_CONTRATO ,
              ALT.CODIGO_CONTRATO,
              P.CPF,
              ALT.DT_INICIO_TROCA,
              ALT.DT_FIM_TROCA,
              ALT.COD_ESCALA,
              EL.tipo_escala
            FROM ARTERH.RHPONT_ALT_ESCALA ALT
            LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
            ON C.CODIGO         =ALT.CODIGO_CONTRATO
            AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
            AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
            LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
            ON P.CODIGO         =C.CODIGO_PESSOA
            AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
            LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
            ON SF.CODIGO=C.SITUACAO_FUNCIONAL
            LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
            ON EL.CODIGO_EMPRESA     = ALT.CODIGO_EMPRESA
            AND EL.CODIGO            = ALT.COD_ESCALA
            WHERE P.CPF              =C1.CPF
            AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
            AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
            AND ALT.ALTER_DEFINITIVA ='S'
            AND ALT.COD_ESCALA       <>X1.COD_ESCALA
            AND C.ANO_MES_REFERENCIA =
              (SELECT MAX(AUX.ANO_MES_REFERENCIA)
              FROM ARTERH.RHPESS_CONTRATO AUX
              WHERE AUX.CODIGO           =C.CODIGO
              AND AUX.TIPO_CONTRATO      = C.TIPO_CONTRATO
              AND AUX.CODIGO_EMPRESA     = C.CODIGO_EMPRESA
              AND AUX.ANO_MES_REFERENCIA<= DATA_VALE2
              )
           AND SF.CODIGO<'1715'
            ) X
          LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
          ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
          AND EH.CODIGO_ESCALA= X.COD_ESCALA
          LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
          ON H.CODIGO_EMPRESA                          = EH.CODIGO_EMPRESA
          AND H.CODIGO                                 = EH.CODIGO_HORARIO
          WHERE TO_DATE(x.DT_INICIO_TROCA,'DD/MM/RRRR')=(SELECT MAX (DT_INICIO_TROCA)
            FROM ARTERH.RHPONT_ALT_ESCALA AUX
            WHERE AUX.CODIGO_CONTRATO                     =X.CODIGO_CONTRATO
            AND AUX.TIPO_CONTRATO                         = X.TIPO_CONTRATO
            AND AUX.CODIGO_EMPRESA                        =X.CODIGO_EMPRESA
            AND AUX.ALTER_DEFINITIVA                      ='S'
            AND TO_DATE(AUX.DT_INICIO_TROCA,'DD/MM/RRRR')<= X1.DT_INICIO_TROCA
            )

          AND H.TIPO_HORARIO='N'
          ) X
          )EL
        GROUP BY EL.TIPO,EL.CODIGO_EMPRESA,EL.TIPO_CONTRATO,EL.CODIGO_CONTRATO ,EL.CPF,EL.DT_INICIO_TROCA,EL.DT_FIM_TROCA,EL.COD_ESCALA,EL.TIPO_ESCALA,EL.TIPO_HORARIO,EL.HR_1,EL.HR_2,EL.HR_3,EL.HR_4,EL.CARGA_HORARIA,EL.TURNO
        ORDER BY EL.DT_INICIO_TROCA
           )
           LOOP
           IF (
              (X1.TURNO='TURNO_MANHA' AND EL.TURNO='TURNO_TARDE')
           OR ( X1.TURNO= 'TURNO_TARDE' AND EL.TURNO='TURNO_NOITE' )
           OR ( EL.TURNO='TURNO_MANHA' AND X1.TURNO='TURNO_TARDE' )
           OR ( EL.TURNO='TURNO_TARDE' AND X1.TURNO= 'TURNO_NOITE' )
           OR ( EL.TURNO='TURNO_CHEIO' AND EL.CARGA_HORARIA= '0800' )
           ) THEN
            SOMA:=(SOMA+ CAST(TRIM(REPLACE(EL.carga_horaria,':',''))AS NUMBER));
              IF SOMA >=800 THEN
             /* DBMS_Output.PUT_LINE('CHAMOU CRIAR VALE 1');
              DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA DEFINITIVA 2');
              DBMS_Output.PUT_LINE('DATAS'||EL.DT_INICIO_TROCA||'-'||EL.DT_FIM_TROCA);*/
              IF X1.DT_INICIO_TROCA<data_corte THEN
                PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', data_corte,NULL,'INCLUIR','S');
              ELSE
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', X1.DT_INICIO_TROCA,NULL,'INCLUIR','S');
              END IF;
           END IF;
          END IF;
         END LOOP;-- FIM FOR EL
         FOR X2 IN (
         SELECT X2.* FROM (SELECT X.*,CASE
        WHEN carga_horaria !='0800'AND X.HR_1>= '0600'AND HR_2 <= '1300' THEN 'TURNO_MANHA'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1300'AND HR_2 <='1800'  THEN 'TURNO_TARDE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '1800'AND HR_2 <='2359' THEN 'TURNO_NOITE'
        WHEN carga_horaria !='0800'AND X.HR_1>= '0000'AND HR_2 <'0600'   THEN 'TURNO_NOITE'
        WHEN carga_horaria >= '0800'THEN 'TURNO_CHEIO'ELSE 'AVALIAR'
      END AS TURNO
      FROM
        (SELECT X.*,
          H.tipo_horario,
          REGEXP_REPLACE(lpad(TO_CHAR(trim( HORARIO_NORMAL_1 )),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_1,
          REGEXP_REPLACE(lpad( TO_CHAR(trim(HORARIO_NORMAL_2)),4,'0' ), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_2,
          REGEXP_REPLACE( lpad(TO_CHAR( trim(HORARIO_NORMAL_3)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_3,
          REGEXP_REPLACE(lpad( TO_CHAR(trim( HORARIO_NORMAL_4)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS hr_4,
          REGEXP_REPLACE(lpad(TO_CHAR( trim( H.JORNADA_DIARIA)),4,'0'), '([0-9]{2})([0-9]{2})', '\1\2') AS carga_horaria
        FROM
          (SELECT 'ESCALA_ALTERNATIVA' AS TIPO,
            ALT.CODIGO_EMPRESA,
            ALT.TIPO_CONTRATO,
            ALT.CODIGO_CONTRATO,
            P.CPF,
            ALT.DT_INICIO_TROCA,
            ALT.DT_FIM_TROCA,
            ALT.COD_ESCALA,
            EL.tipo_escala
          FROM ARTERH.RHPONT_ALT_ESCALA ALT
          LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
          ON C.CODIGO         =ALT.CODIGO_CONTRATO
          AND C.TIPO_CONTRATO = ALT.TIPO_CONTRATO
          AND C.CODIGO_EMPRESA= ALT.CODIGO_EMPRESA
          LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P
          ON P.CODIGO         =C.CODIGO_PESSOA
          AND P.CODIGO_EMPRESA= C.CODIGO_EMPRESA
          LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
          ON SF.CODIGO=C.SITUACAO_FUNCIONAL
          LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL
          ON EL.CODIGO_EMPRESA     = ALT.CODIGO_EMPRESA
          AND EL.CODIGO            = ALT.COD_ESCALA
          WHERE P.CPF              =C1.CPF
          AND C.TIPO_CONTRATO      =C1.TIPO_CONTRATO
          AND C.CODIGO_EMPRESA     =C1.CODIGO_EMPRESA
          AND ALT.ALTER_DEFINITIVA ='N'
          AND C.ANO_MES_REFERENCIA =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO           =C.CODIGO
            AND AUX.TIPO_CONTRATO      = C.TIPO_CONTRATO
            AND AUX.CODIGO_EMPRESA     = C.CODIGO_EMPRESA
            AND AUX.ANO_MES_REFERENCIA<= data_vale2
            )
          AND SF.CODIGO<'1715'
          ) X
        LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR EH
        ON EH.CODIGO_EMPRESA=X.CODIGO_EMPRESA
        AND EH.CODIGO_ESCALA= X.COD_ESCALA
        LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
        ON H.CODIGO_EMPRESA = EH.CODIGO_EMPRESA
        AND H.CODIGO        = EH.CODIGO_HORARIO
        WHERE ( ( TO_DATE(x.DT_INICIO_TROCA,'DD/MM/RRRR') BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA )
        OR ( x.DT_INICIO_TROCA BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA AND X.DT_FIM_TROCA IS NULL )
        OR ( X.DT_FIM_TROCA BETWEEN X1.DT_INICIO_TROCA AND X1.DT_FIM_TROCA AND x.DT_INICIO_TROCA  <=X1.DT_INICIO_TROCA )
        OR ( X.DT_INICIO_TROCA <= X1.DT_INICIO_TROCA AND ((X.DT_FIM_TROCA   <=X1.DT_FIM_TROCA)OR (X1.DT_FIM_TROCA    IS NULL) )) )
        AND H.TIPO_HORARIO      ='N'
        ) X
        )X2
      GROUP BY X2.TIPO,X2.CODIGO_EMPRESA,X2.TIPO_CONTRATO,X2.CODIGO_CONTRATO ,X2.CPF,X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,X2.COD_ESCALA,X2.TIPO_ESCALA,X2.TIPO_HORARIO,X2.HR_1,X2.HR_2,X2.HR_3,X2.HR_4,X2.CARGA_HORARIA,X2.TURNO
      ORDER BY X2.DT_INICIO_TROCA
         )LOOP
          IF ( (X1.TURNO='TURNO_MANHA' AND X2.TURNO='TURNO_TARDE')
          OR ( X1.TURNO= 'TURNO_TARDE' AND X2.TURNO='TURNO_NOITE' )
          OR ( X2.TURNO='TURNO_MANHA' AND X1.TURNO='TURNO_TARDE' )
          OR ( X2.TURNO='TURNO_TARDE' AND X1.TURNO= 'TURNO_NOITE' )
          OR ( X2.TURNO='TURNO_CHEIO' AND X2.CARGA_HORARIA>= '0800' ) ) THEN
          SOMA :=(SOMA+CAST(TRIM(REPLACE(X2.carga_horaria,':',''))AS NUMBER));
          IF ((SOMA >=800) OR ( X2.TURNO='TURNO_CHEIO' AND X2.CARGA_HORARIA>= '0800' ) ) THEN
      --    DBMS_Output.PUT_LINE('CRIAR VALE COM ESCALA ALTERNATIVA');
      ---    DBMS_Output.PUT_LINE('DATAS'||X2.DT_INICIO_TROCA||'-'||X2.DT_FIM_TROCA);
         -- PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,'INCLUIR','N');

           IF X2.DT_INICIO_TROCA<data_corte THEN
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , data_corte,X2.DT_FIM_TROCA,'INCLUIR','N');
            ELSE
              PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002' , X2.DT_INICIO_TROCA,X2.DT_FIM_TROCA,'INCLUIR','N');
            END IF;

          END IF;
          END IF;
         END LOOP; -- FIM FOR X2


    END IF;
    IF SOMA <=800 AND X1.TURNO!='TURNO_CHEIO'THEN
  --  DBMS_Output.PUT_LINE('CHAMOU PROCEDURE EXCLUIR 1');
   -- DBMS_Output.PUT_LINE('DATAS'||X1.DT_INICIO_TROCA||'-'||X1.DT_FIM_TROCA);

      IF X1.DT_INICIO_TROCA<data_corte THEN
       PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', data_corte,X1.DT_FIM_TROCA,'EXCLUIR',NULL);
       ELSE
          PR_VERIFICA_VALE(X1.CODIGO_EMPRESA,X1.TIPO_CONTRATO,X1.CPF,'0002', X1.DT_INIcio_TROCA,X1.DT_FIM_TROCA,'EXCLUIR',NULL);
        END IF;
    END IF;
    END LOOP;---- FIM LOOP X1
  END LOOP;-- FIM LOOP FOR C1
  END;