
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_IMP_SUGESP_ARQUIVOS_FICHA" 
AS BEGIN
--kELLYSSON EM 4/10/21 CRIOU PROCEDURE (PR_IMP_SUGESP_ARQUIVOS_FICHA)
       ---antes de importar para analise  
--SELECT count(1)quant FROM SUGESP_IMPORT_TEG1--244
--SELECT to_date(dataocorrencia, 'dd/mm/yyyy')dt_ocorrencia, count(1)quant FROM SUGESP_IMPORT_TEG1 group by dataocorrencia order by dataocorrencia desc--por dia
--     
DECLARE              
vCONTADOR NUMBER;  

BEGIN 
dbms_output.enable(null);
vCONTADOR :=0; 

---INICIO-----------------------------------------------------------------------------1ª parte ajustar os dados--------------------------------------------------------------------------------------------------------------------------
FOR 
C1 IN ( 


SELECT CASE WHEN X3.ORDEM_BM IS NULL THEN 1 ELSE X3.ORDEM_BM END ORDEM_BM
, A.*
FROM 
(
--COMENTADO EM 17/9/20 --SUGESP_IMPORT_TEG1 
--INICIO------------------------------------------------------------ TROCA EM 17/9/20
SELECT 

CASE WHEN A2.DATAINICIOAFAST = '01/01/1900' THEN NULL ELSE A2.DATAINICIOAFAST END DATAINICIOAFAST,
CASE WHEN A2.DATAFIMAFAST = '01/01/1900' THEN NULL ELSE A2.DATAFIMAFAST END DATAFIMAFAST,
CASE WHEN A2.DATAINICIALINDEFERIMENTO = '01/01/1900' THEN NULL ELSE A2.DATAINICIALINDEFERIMENTO END DATAINICIALINDEFERIMENTO,
CASE WHEN A2.DATAFINALINDEFERIMENTO = '01/01/1900' THEN NULL ELSE A2.DATAFINALINDEFERIMENTO END DATAFINALINDEFERIMENTO ,
A2.CODIGOEMPRESA, A2.AUTOIDFICHAATENDIMENTO, A2.DATAOCORRENCIA, A2.TIPOPROCEDIMENTO, A2.ATENDENTE, A2.DATARETORNOREAVALIACAO, A2.CODIGOCONTRATO, A2.DATAEFETIVA, A2.HORARIOEFETIVO, A2.DOENCA, A2.CODIGOCONDUTA, A2.PERIODOLAUDO, A2.INICIOLAUDO, A2.FINALLAUDO, A2.ESPECIALIDADETRATAMENTO, A2.FREQUENCIA_SESSOES, A2.PERIODOINICIALTRATAMENTO, A2.PERIODOFINALTRATAMENTO, A2.SEQUENCIAL_TEG, A2.DATACIENCIADECISAO, A2.CODIGOTIPOCONTRATO,
A2.POSITIVOEXAME, A2.RECONSIDERACAO
,A2.MOTIVO, A2.EXAMECLINICO
FROM(

SELECT 
ROW_NUMBER() OVER (PARTITION BY A.codigoempresa, A.codigotipocontrato, A.CODIGOCONTRATO, A.datainicioafast, A.datafimafast, A.DATAINICIALINDEFERIMENTO, A.DATAFINALINDEFERIMENTO, A.TIPOPROCEDIMENTO, A.CODIGOCONDUTA, A.DOENCA
,A.AUTOIDFICHAATENDIMENTO
ORDER BY X.datainicioafasT ) AS ORDEM_DUPLICIDADE,

A.* 
FROM

(SELECT 
A.CODIGOEMPRESA, A.AUTOIDFICHAATENDIMENTO, A.DATAOCORRENCIA, A.TIPOPROCEDIMENTO, A.ATENDENTE, A.MOTIVO, A.EXAMECLINICO, A.DATARETORNOREAVALIACAO, A.CODIGOCONTRATO, A.DATAEFETIVA, A.HORARIOEFETIVO, A.DOENCA, A.CODIGOCONDUTA, A.PERIODOLAUDO, A.INICIOLAUDO, A.FINALLAUDO, A.ESPECIALIDADETRATAMENTO, A.FREQUENCIA_SESSOES, A.PERIODOINICIALTRATAMENTO, A.PERIODOFINALTRATAMENTO, A.SEQUENCIAL_TEG, A.DATACIENCIADECISAO, A.CODIGOTIPOCONTRATO,
--inicio novo em 15/9/20
CASE WHEN POSITIVOEXAME = 'Não' THEN 'N' WHEN POSITIVOEXAME = 'Sim' THEN 'S' END POSITIVOEXAME 
,CASE WHEN RECONSIDERACAO = 'Não' THEN 'N' WHEN RECONSIDERACAO = 'Sim' THEN 'S' END RECONSIDERACAO
--fim novo em 15/9/20

,CASE WHEN A.DATAINICIOAFAST IS NULL THEN '01/01/1900' ELSE A.DATAINICIOAFAST END DATAINICIOAFAST,
CASE WHEN A.DATAFIMAFAST IS NULL THEN '01/01/1900' ELSE A.DATAFIMAFAST END DATAFIMAFAST,
CASE WHEN A.DATAINICIALINDEFERIMENTO IS NULL THEN '01/01/1900' ELSE A.DATAINICIALINDEFERIMENTO END DATAINICIALINDEFERIMENTO,
CASE WHEN A.DATAFINALINDEFERIMENTO IS NULL THEN '01/01/1900' ELSE A.DATAFINALINDEFERIMENTO END DATAFINALINDEFERIMENTO
from SUGESP_IMPORT_TEG1 A)A


LEFT OUTER JOIN

(--INICIO ----REGISTROS DUPLICADOS PELAS DATAS
SELECT  
X2.* FROM(
SELECT  
X.* FROM (
SELECT 
codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast, DATAINICIALINDEFERIMENTO, DATAFINALINDEFERIMENTO, TIPOPROCEDIMENTO, CODIGOCONDUTA, DOENCA
,AUTOIDFICHAATENDIMENTO
,count(1)quant
FROM(
SELECT 
codigoempresa, codigotipocontrato, CODIGOCONTRATO,
CASE WHEN DATAINICIOAFAST IS NULL THEN '01/01/1900' ELSE DATAINICIOAFAST END DATAINICIOAFAST,
CASE WHEN DATAFIMAFAST IS NULL THEN '01/01/1900' ELSE DATAFIMAFAST END DATAFIMAFAST,
CASE WHEN DATAINICIALINDEFERIMENTO IS NULL THEN '01/01/1900' ELSE DATAINICIALINDEFERIMENTO END DATAINICIALINDEFERIMENTO,
CASE WHEN DATAFINALINDEFERIMENTO IS NULL THEN '01/01/1900' ELSE DATAFINALINDEFERIMENTO END DATAFINALINDEFERIMENTO, 
TIPOPROCEDIMENTO, CODIGOCONDUTA, DOENCA
,AUTOIDFICHAATENDIMENTO
from SUGESP_IMPORT_TEG1
)A
group by codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast, DATAINICIALINDEFERIMENTO, DATAFINALINDEFERIMENTO, TIPOPROCEDIMENTO, CODIGOCONDUTA, DOENCA
,AUTOIDFICHAATENDIMENTO
order by codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast, DATAINICIALINDEFERIMENTO, DATAFINALINDEFERIMENTO, TIPOPROCEDIMENTO, CODIGOCONDUTA, DOENCA
,AUTOIDFICHAATENDIMENTO
)X
)X2
WHERE X2.QUANT <> 1
)X--FIM ----REGISTROS DUPLICADOS PELAS DATAS


ON X.codigoempresa = A.codigoempresa AND X.codigotipocontrato = A.codigotipocontrato AND X.CODIGOCONTRATO = A.CODIGOCONTRATO AND X.datainicioafast = A.datainicioafast
AND X.datafimafast = A.datafimafast AND X.DATAINICIALINDEFERIMENTO = A.DATAINICIALINDEFERIMENTO AND X.DATAFINALINDEFERIMENTO = A.DATAFINALINDEFERIMENTO
AND X.TIPOPROCEDIMENTO = A.TIPOPROCEDIMENTO AND X.CODIGOCONDUTA = A.CODIGOCONDUTA AND X.DOENCA = A.DOENCA
AND X.AUTOIDFICHAATENDIMENTO = A.AUTOIDFICHAATENDIMENTO
--WHERE X.CODIGOEMPRESA IS NOT NULL

order by A.codigoempresa, A.codigotipocontrato, A.CODIGOCONTRATO, A.datainicioafast, A.datafimafast, A.DATAINICIALINDEFERIMENTO, A.DATAFINALINDEFERIMENTO, A.TIPOPROCEDIMENTO, A.CODIGOCONDUTA, A.DOENCA
,A.AUTOIDFICHAATENDIMENTO
)A2 WHERE A2.ORDEM_DUPLICIDADE = 1

--FIM------------------------------------------------------------ TROCA EM 17/9/20
)
A 
LEFT OUTER JOIN
--FAZER GRUPOS POR BM
(SELECT 
X2.* FROM(
SELECT 
ROW_NUMBER() OVER (PARTITION BY X.codigoempresa, X.codigotipocontrato, X.CODIGOCONTRATO ORDER BY X.datainicioafasT ) AS ORDEM_BM,
X.* FROM (SELECT 
codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast 
,AUTOIDFICHAATENDIMENTO
,count(1)quant
from SUGESP_IMPORT_TEG1
group by codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast
,AUTOIDFICHAATENDIMENTO
order by codigoempresa, codigotipocontrato, CODIGOCONTRATO, datainicioafast, datafimafast
,AUTOIDFICHAATENDIMENTO
)X
)X2) X3 ON X3.codigoempresa = A.codigoempresa AND X3.codigotipocontrato = A.codigotipocontrato 
AND X3.CODIGOCONTRATO = A.CODIGOCONTRATO AND X3.datainicioafast = A.datainicioafast
AND X3.AUTOIDFICHAATENDIMENTO = A.AUTOIDFICHAATENDIMENTO
order by A.codigocontrato, A.DATAOCORRENCIA, A.TIPOPROCEDIMENTO, A.CODIGOCONDUTA, A.DOENCA
,A.AUTOIDFICHAATENDIMENTO



)

LOOP 
vCONTADOR := vCONTADOR+1 ;
dbms_output.put_line(vCONTADOR); 

dbms_output.put_line('--vCONTADOR: '||vCONTADOR || '- AUTOIDFICHAATENDIMENTO: '||C1.AUTOIDFICHAATENDIMENTO );

INSERT INTO SUGESP_ARQUIVOS_FICHA 
(
ID,
CODIGOEMPRESA, AUTOIDFICHAATENDIMENTO, DATAOCORRENCIA, TIPOPROCEDIMENTO, ATENDENTE, DATAINICIOAFAST, DATAFIMAFAST, MOTIVO, EXAMECLINICO, 
DATARETORNOREAVALIACAO, CODIGOCONTRATO, DATAEFETIVA, HORARIOEFETIVO, DATAINICIALINDEFERIMENTO, DATAFINALINDEFERIMENTO, DOENCA, CODIGOCONDUTA, 
PERIODOLAUDO, INICIOLAUDO, FINALLAUDO, ESPECIALIDADETRATAMENTO, FREQUENCIA_SESSOES, PERIODOINICIALTRATAMENTO, PERIODOFINALTRATAMENTO, SEQUENCIAL_TEG
,DATACIENCIADECISAO, CODIGOTIPOCONTRATO, DATA_RECEBIMENTO
,LOTE
,POSITIVOEXAME, RECONSIDERACAO  --NOVO EM 15/9/20
)
VALUES(
(SELECT MAX(ID)+1 FROM SUGESP_ARQUIVOS_FICHA),
LPAD(C1.CODIGOEMPRESA,4,0)
, C1.AUTOIDFICHAATENDIMENTO, TO_DATE(C1.DATAOCORRENCIA,'DD/MM/YYYY'), 
LPAD(C1.TIPOPROCEDIMENTO,4,0), 
LPAD(C1.ATENDENTE,11,0), TO_DATE(C1.DATAINICIOAFAST,'DD/MM/YYYY'), TO_DATE(C1.DATAFIMAFAST,'DD/MM/YYYY'), UPPER(C1.MOTIVO), UPPER(C1.EXAMECLINICO), TO_DATE(C1.DATARETORNOREAVALIACAO,'DD/MM/YYYY'), 
UPPER(LPAD(REPLACE(C1.CODIGOCONTRATO, '-', ''),15,'0')), TO_DATE(C1.DATAEFETIVA,'DD/MM/YYYY'), 
to_CHAR(replace(C1.HORARIOEFETIVO, ':', ''))/100, 
TO_DATE(C1.DATAINICIALINDEFERIMENTO,'DD/MM/YYYY'), TO_DATE(C1.DATAFINALINDEFERIMENTO,'DD/MM/YYYY'), UPPER(LPAD(C1.DOENCA,15,'0')), LPAD(C1.CODIGOCONDUTA,15,'0'), C1.PERIODOLAUDO, 
TO_DATE(C1.INICIOLAUDO,'DD/MM/YYYY'), TO_DATE(C1.FINALLAUDO,'DD/MM/YYYY'), UPPER(C1.ESPECIALIDADETRATAMENTO), UPPER(C1.FREQUENCIA_SESSOES), C1.PERIODOINICIALTRATAMENTO, C1.PERIODOFINALTRATAMENTO, C1.SEQUENCIAL_TEG
,TO_DATE(C1.DATACIENCIADECISAO,'DD/MM/YYYY'),LPAD(C1.CODIGOTIPOCONTRATO,4,0), sysdate
, C1.ORDEM_BM

--inicio novo em 15/9/20
,  C1.POSITIVOEXAME, C1.RECONSIDERACAO
--,CASE WHEN C1.POSITIVOEXAME = 'Não' THEN 'N' WHEN C1.POSITIVOEXAME = 'Sim' THEN 'S' END 
--,CASE WHEN C1.RECONSIDERACAO = 'Não' THEN 'N' WHEN C1.RECONSIDERACAO = 'Sim' THEN 'S' END
--fim novo em 15/9/20
); COMMIT;

END LOOP; 

end;

END ;

