
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_PONTO_LOGS" 
(
  SISTEMA IN VARCHAR2,
  OBJETO IN VARCHAR2,
  OPERACAO IN VARCHAR2,
  DADOS_VIEW IN VARCHAR2,
  IMPORTADO IN CHAR,
  DATA_LOG IN TIMESTAMP,
  LOG_IMP IN VARCHAR2
) AS 
BEGIN
 INSERT INTO PONTO_LOGS VALUES (SISTEMA,OBJETO,OPERACAO,DADOS_VIEW,IMPORTADO,DATA_LOG,LOG_IMP);
 -- DBMS_OUTPUT.PUT_LINE(OBJETO||OPERACAO||DADOS_VIEW||IMPORTADO||DATA_LOG||LOG_IMP);

END PR_PONTO_LOGS;

--para testar com F5 e SAIDA DBMS
/*BEGIN  
PR_PONTO_LOGS ('SURICATO','VW_CARGO','A', 'FADF:fAD','S',SYSDATE,': AFDASF: AFDDS');
END;
*/