
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_PROCESSAR_ARQUIVO_DUPLA_LOTACAO" (PCODIGO_EMPRESA CHAR, PID_ARQUIVO NUMBER, PACAO NUMBER) as
REG_LOG LOG_PROCESSAMENTO;
RH_AGRUPADOR rhorga_agrupador%rowtype;
RH_GERENCIAL rhorga_custo_geren%rowtype;
  vTIPO_ARQUIVO CHAR(4);
  vDATA_PROCESSAMENTO DATE;
 vIDENTIFICADOR_REGRA VARCHAR2(30);
  vCONTADOR NUMBER;

  vSITUACAO_PROCESSAMENTO CHAR(2);
  vCODIGO_EMPRESA CHAR(4);
  vID_ARQUIVO NUMBER;
  vSITUACAO_ARQUIVO CHAR(2);
  vLISTA_LOG LISTA_LOG := LISTA_LOG(null,null,null);
vUSUARIO_ATUALIZACAO VARCHAR2(40):= 'IMPORT_DUPLA_LOTACAO';
vDATA_ATUALIZACAO DATE := sysdate;
  ARQUIVO_DUPLA_LOTACAO      CONSTANT CHAR(4) := 'DPL1';
  STATUS_CARREGADO    CONSTANT NUMBER := 0;
  STATUS_VALIDADO     CONSTANT NUMBER := 1;
  STATUS_INVALIDADO   CONSTANT NUMBER := 2;
  STATUS_PROCESSADO   CONSTANT NUMBER := 3;
  STATUS_EFETIVADO    CONSTANT NUMBER := 4;
  TIPO_LOG_SUCESSO       CONSTANT NUMBER := 0;
  TIPO_LOG_INFO          CONSTANT NUMBER := 1;
  TIPO_LOG_ALERTA        CONSTANT NUMBER := 2;
  TIPO_LOG_ERRO          CONSTANT NUMBER := 99;
  TIPO_LOG_PROCESSAMENTO CONSTANT NUMBER := 50;
  CODIGO_LOG_PROCESSAMENTO_02 CONSTANT CHAR(4) := 'P002';
  CODIGO_LOG_PROCESSAMENTO_03 CONSTANT CHAR(4) := 'P003';
  CODIGO_LOG_PROCESSAMENTO_04 CONSTANT CHAR(4) := 'P004';
  CODIGO_LOG_PROCESSAMENTO_05 CONSTANT CHAR(4) := 'P005';
  CODIGO_LOG_PROCESSAMENTO_06 CONSTANT CHAR(4) := 'P006';
  CODIGO_LOG_PROCESSAMENTO_07 CONSTANT CHAR(4) := 'P007';
  CODIGO_LOG_PROCESSAMENTO_50 CONSTANT CHAR(4) := 'P050';
  CATEGORIA_LOG_VALIDACAO  CONSTANT NUMBER := 0;
  CATEGORIA_LOG_EXECUCAO   CONSTANT NUMBER := 1;
  CATEGORIA_LOG_LEIAUTE    CONSTANT NUMBER := 2;
  CATEGORIA_LOG_REGRAS     CONSTANT NUMBER := 3;
  CATEGORIA_LOG_EFETIVACAO CONSTANT NUMBER := 4;
  LOG_REGISTRO_JA_EXISTENTE      CONSTANT CHAR(4) := 'E025';

  LOG_CODIGO_EMPRESA_INVALIDO    CONSTANT CHAR(4) := 'E001';
  LOG_CODIGO_OPUS_NAO_ENCONTRADO    CONSTANT CHAR(4) := 'DP01';
  LOG_OPERACAO_INVALIDA          CONSTANT CHAR(4) := 'E033';
  LOG_ACAO_NAO_PODE_TER_PARA  CONSTANT CHAR(4) := 'DP02';
  LOG_ACAO_REQUER_PARA CONSTANT CHAR(4) := 'DP03';
  LOG_SUCESSO_INCLUSAO           CONSTANT CHAR(4) := 'S001';

PROCEDURE IMPRIMIR_VALORES_MAPEADOS(descricao_lista varchar2, lista LISTA, lista_mapeada LISTA) as
BEGIN
      DBMS_Output.PUT_LINE('IMPRIMINDO LISTA MAPEADA' || ' - ' || descricao_lista);
       for i in 1..lista.count()
         loop
             DBMS_Output.PUT_LINE(RPAD('lista('||i||')',10,' ') || ' = ' || lista(i) || ' -> ' || lista_mapeada(i));
         end loop;
END;

PROCEDURE GRAVA_LOG(CodigoEmpresa IN CHAR, CategoriaLog IN NUMBER, TipoLog IN NUMBER, IdArquivo IN NUMBER, Numero_linha IN NUMBER, CodigoLog IN CHAR, DetalheLog IN VARCHAR2) AS
BEGIN
     INSERT INTO RHPBH_ARQUIVO_LOG(ID_LOG, DATA_LOG, CATEGORIA, TIPO, ID_ARQUIVO, NUMERO_LINHA, CODIGO_LOG, DETALHE, CODIGO_EMPRESA)
     values (SQ_RHPBH_PS_IMPORTACAO_LOG.NEXTVAL, sysdate, CategoriaLog, TipoLog, IdArquivo, Numero_linha, CodigoLog, DetalheLog, CodigoEmpresa);
     COMMIT;
END;
PROCEDURE PR_CONTROLE_PROCESSAMENTO(CODIGO_EMPRESA IN CHAR, ID_ARQUIVO IN NUMBER, SITUACAO_PROCESSAMENTO IN CHAR, POBSERVACAO IN VARCHAR2 DEFAULT NULL) AS
BEGIN
    PR_GRAVA_LOG_PROCESSA_ARQUIVO(CODIGO_EMPRESA, ID_ARQUIVO, SITUACAO_PROCESSAMENTO, POBSERVACAO);
END;

PROCEDURE PR_SET_SITUACAO_PROCESSAMENTO(PSITUACAO_PROCESSAMENTO IN CHAR) AS
BEGIN
    IF PSITUACAO_PROCESSAMENTO IS NULL THEN
       raise_application_error (-20001,'ERRO NO CONTROLE DE PROCESSAMENTO. SITUACAO NULA.');
    END IF;

    IF PSITUACAO_PROCESSAMENTO NOT IN ('00','01','02','03','04','05','06','07') THEN
       raise_application_error (-20001,'ERRO NO CONTROLE DE PROCESSAMENTO. SITUACAO INVALIDA.');
    END IF;

    vSITUACAO_PROCESSAMENTO := PSITUACAO_PROCESSAMENTO;
END;

PROCEDURE PR_ATUALIZAR_SITUACAO_REGISTR0 AS
BEGIN
   BEGIN
      update RHPBH_ARQUIVO_LINHA AL
         set SITUACAO = 99
       where ID_ARQUIVO = PID_ARQUIVO
         and exists(
      select *
        from RHPBH_ARQUIVO_LOG
       where ID_ARQUIVO = AL.ID_ARQUIVO
         and NUMERO_LINHA = AL.NUMERO_LINHA
         and TIPO = 99
      );

      commit;

    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'[VALIDACAO_REGRAS] - OCORREU UMA EXCECAOO AO TENTAR ATUALIZAR A SITUACAO DOS REGISTROS VALIDADOS. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;
END;


PROCEDURE CRIAR_NOVOS_LOCAIS_AGRUP(agrup arterh.rhorga_agrupador%rowtype) AS 
BEGIN 
BEGIN
INSERT INTO rhorga_agrupador VALUES agrup;
 COMMIT;
EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI INSERIR OS NOVOS LOCAIS NA TABELA RHORAGA_AGRUPADOR.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END; 
   
    

END;


PROCEDURE CRIAR_NOVOS_LOCAIS_GERENC(rhorga_custo_geren arterh.rhorga_custo_geren%rowtype) AS 
BEGIN 

    BEGIN 
INSERT INTO rhorga_custo_geren VALUES rhorga_custo_geren;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI INSERIR OS NOVOS LOCAIS NA TABELA RHORGA_CUSTO_GEREN.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;
END;

    


/*INICIO LOGICA BEGIN INICIAL*/
BEGIN 
DBMS_OUTPUT.ENABLE (buffer_size => NULL);
vLISTA_LOG := LISTA_LOG();
REG_LOG := LOG_PROCESSAMENTO(null, null,null, null);

  BEGIN
         vCODIGO_EMPRESA := null;
         select CODIGO into vCODIGO_EMPRESA from RHORGA_EMPRESA where CODIGO = PCODIGO_EMPRESA;

         IF vCODIGO_EMPRESA IS NULL THEN
            raise_application_error (-20001,'CODIGO_EMPRESA INVALIDO.');
         END IF;
    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI POSSIVEL RECUPERAR O CODIGO_EMPRESA');
    END;

  BEGIN
         vID_ARQUIVO := null;
         select ID_ARQUIVO, SITUACAO into vID_ARQUIVO, vSITUACAO_ARQUIVO from RHPBH_ARQUIVO where ID_ARQUIVO = PID_ARQUIVO;

         IF vID_ARQUIVO IS NULL THEN
            raise_application_error (-20001,'ID ARQUIVO INVALIDO.');
         END IF;

         IF vSITUACAO_ARQUIVO NOT IN ('00','01','02','03','04','05','06','07') THEN
            raise_application_error (-20001,'O ARQUIVO INFORMADO ESTA COM SITUACAO INVALIDA. ENTRE EM CONTATO COM O SUPORTE TECNICO DA PBH.');
         END IF;

         CASE WHEN vSITUACAO_ARQUIVO = '07' THEN raise_application_error (-20002,'O ARQUIVO INFORMADO ESTA COM PROCESSAMENTO JÁ CONCLUIDO E NAO PODE SER MAIS PROCESSADO.');
              WHEN vSITUACAO_ARQUIVO = '01' THEN raise_application_error (-20002,'O ARQUIVO INFORMADO ESTA CANCELADO E NAO PODE SER MAIS PROCESSADO.');
              WHEN vSITUACAO_ARQUIVO in ('02','04','06') THEN raise_application_error (-20002,'O ARQUIVO INFORMADO JÁ ESTÁ EM PROCESSAMENTO E NAO PODE HAVER PROCESSAMENTOS COMCOMITANTES PARA O MESMO ARQUIVO.');
              WHEN vSITUACAO_ARQUIVO = '00' THEN
                   IF PACAO NOT IN (1,10) THEN
                      raise_application_error (-20002,'A ACAO INFORMADA NAO É COMPATIVEL COM A SITUACAO DO ARQUIVO. O ARQUIVO ESTÁ COM A SITUACAO CARREGADO E AS ACOES PERMITIDA SAO 1 ou 10.');
                   END IF;
              WHEN vSITUACAO_ARQUIVO = '03' THEN
                   IF PACAO NOT IN (2,10) THEN
                      raise_application_error (-20002,'A ACAO INFORMADA NAO É COMPATIVEL COM A SITUACAO DO ARQUIVO. O ARQUIVO ESTÁ COM A SITUACAO VALIDACAO DE LEIAUTE PROCESSADA E AS ACOES PERMITIDA SAO 2 ou 10.');
                   END IF;
              WHEN vSITUACAO_ARQUIVO = '05' THEN
                   IF PACAO NOT IN (3,4,10) THEN
                      raise_application_error (-20002,'A ACAO INFORMADA NAO É COMPATIVEL COM A SITUACAO DO ARQUIVO. O ARQUIVO ESTÁ COM A SITUACAO PROCESSADO E AS ACOES PERMITIDA SAO 3 ou 10.');
                   END IF;
              ELSE
                  NULL;
         END CASE;

         PR_SET_SITUACAO_PROCESSAMENTO(vSITUACAO_ARQUIVO);
    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI POSSIVEL RECUPERAR O ARQUIVO COM O ID_ARQUIVO INFORMADO.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;  
    PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO, '70');
    PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO, '71');
    PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO, '72'); 

-- Verifica se ha algum arquivo de importacao a ser processado
    -- a ser processado
    BEGIN
         IF PACAO = 1 THEN
             VCONTADOR := null;
             select count(1) into VCONTADOR
               from RHPBH_ARQUIVO
              where CODIGO_EMPRESA = PCODIGO_EMPRESA
                and TIPO_ARQUIVO = ARQUIVO_DUPLA_LOTACAO
                and ID_ARQUIVO = PID_ARQUIVO
                and SITUACAO in ('00');

             IF VCONTADOR = 0 THEN
                raise_application_error (-20002,'NAO EXISTE ARQUIVO DE DUPLA LOTACAO A SER PROCESSADO PARA OS PARAMETROS INFORMADOS.');
             END IF;
         END IF;
    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO EXISTE ARQUIVO DE DUPLA LOTACAO A SER PROCESSADO PARA OS PARAMETROS INFORMADOS.');
    END;
     PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO, '73');

  -- VALIDAR LEIAUTE ARQUIVO
    IF PACAO in (1, 10) THEN
    BEGIN

        FOR C1 IN (select * from RHPBH_ARQUIVO
         where CODIGO_EMPRESA = PCODIGO_EMPRESA
           and TIPO_ARQUIVO = ARQUIVO_DUPLA_LOTACAO
           and ID_ARQUIVO = PID_ARQUIVO
           and SITUACAO in ('00')
         order by ID_ARQUIVO)
         loop
            PR_SET_SITUACAO_PROCESSAMENTO('02');
            PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO);

            BEGIN
                PR_VALIDAR_LEIAUTE_ARQUIVO (C1.ID_ARQUIVO);
            EXCEPTION
            WHEN OTHERS THEN
                 raise_application_error (-20002,'ERRO AO TENTAR VALIDAR O LEIAUTE DO ARQUIVO. ' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
            END;

         end loop;

         PR_SET_SITUACAO_PROCESSAMENTO('03');
         PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO);
         PR_ATUALIZAR_SITUACAO_REGISTR0;

         commit;

    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DO ARQUIVO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;

    END IF;
    
    
    IF PACAO in (2, 10) THEN
    
    BEGIN 
    FOR C1 IN (select * from RHPBH_ARQUIVO
         where CODIGO_EMPRESA = PCODIGO_EMPRESA
           and TIPO_ARQUIVO = ARQUIVO_DUPLA_LOTACAO
           and ID_ARQUIVO = PID_ARQUIVO
           and SITUACAO in ('03', '05')
         order by ID_ARQUIVO)
         LOOP
         BEGIN 
          PR_SET_SITUACAO_PROCESSAMENTO('04');
            PR_CONTROLE_PROCESSAMENTO(C1.CODIGO_EMPRESA, C1.ID_ARQUIVO, vSITUACAO_PROCESSAMENTO);

            -- Remove os registros relacionados ao arquivo de ID informado
             BEGIN
                delete from ARTERH.RHPBH_ARQUIVO_DUPLA_LOTACAO  where ID_ARQUIVO = C1.ID_ARQUIVO;
             EXCEPTION
             WHEN OTHERS THEN
                dbms_output.put_line('ERRO AO TENTAR EXCLUIR RHPBH_PS_BENEFICIARIO');
                NULL;
             END;
             
             BEGIN
             
             insert into RHPBH_ARQUIVO_DUPLA_LOTACAO(
                ID_ARQUIVO,
                NUMERO_LINHA,
                IDENTIFICADOR_ARQUIVO,
                DATA_HORA_GERACAO_ARQUIVO,
                TIPO_OPERACAO,
                CODIGO_EMPRESA,
                CODIGO_OPUS_PAI ,
                CODIGO_DUPLA_LOTACAO_DE,
                DESCRICAO_DE ,
                ABREVICAO_DE,
                CODIGO_DUPLA_LOTACAO_PARA,
                DESCRICAO_PARA,
                ABREVICAO_PARA 
                )
                (
                select
                ID_ARQUIVO,
                NUMERO_LINHA,
                'DPL1'IDENTIFICADOR_ARQUIVO,
                TRUNC(TO_DATE(DATA_CARGA,'DD/MM/YYYY HH24:MI:SS')) AS DATA_HORA_GERACAO_ARQUIVO,
                ACAO,
                CODIGO_EMPRESA_ARQUIVO,
                TRIM(CODIGO_OPUS_PAI)CODIGO_OPUS_PAI ,
                TRIM(CODIGO_DUPLA_LOTACAO_DE)AS CODIGO_DUPLA_LOTACAO_DE ,
                TRIM(DESCRICAO_DE)DESCRICAO_DE ,
                TRIM(ABREVICAO_DE)ABREVICAO_DE,
                TRIM(CODIGO_DUPLA_LOTACAO_PARA) AS CODIGO_DUPLA_LOTACAO_PARA,
                TRIM(DESCRICAO_PARA)DESCRICAO_PARA ,
                TRIM(ABREVICAO_PARA) AS  ABREVICAO_PARA
                from ARTERH.VIEW_ARQUIVO_DUPLA_LOTACAO
                where CODIGO_EMPRESA_ARQUIVO = PCODIGO_EMPRESA
                  and ID_ARQUIVO = C1.ID_ARQUIVO
                  and SITUACAO_LINHA = '00'
                );
                
                COMMIT;

                select max(SITUACAO_ARQUIVO) into VCONTADOR
                  from (select * from ARTERH.VIEW_ARQUIVO_DUPLA_LOTACAO)
                 where CODIGO_EMPRESA_ARQUIVO = PCODIGO_EMPRESA
                   and ID_ARQUIVO = C1.ID_ARQUIVO;
                dbms_output.put_line('VW_ARQUIVO_0002 - ' || VCONTADOR || ' REGISTROS.');

                select count(1) into VCONTADOR
                  from RHPBH_ARQUIVO_DUPLA_LOTACAO
                 where CODIGO_EMPRESA = PCODIGO_EMPRESA
                   and ID_ARQUIVO = C1.ID_ARQUIVO;

                dbms_output.put_line('RHPBH_PS_BENEFICIARIO - ' || VCONTADOR || ' REGISTROS.');
             EXCEPTION
             WHEN OTHERS THEN
             --dbms_output.put_line('ERRO AO TENTAR INCLUIR RHPBH_PS_BENEFICIARIO. ' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
             NULL;
             END;  
             
        EXCEPTION
            WHEN OTHERS THEN
               --dbms_output.put_line('ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
               raise_application_error (-20002,'NAO FOI POSSIVEL REALIZAR O PROCESSAMENTO DO ARQUIVO DE DUPLA LOTACAO. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
            END; 
            
            
            
            dbms_output.put_line('VALIDACAO REGRAS');
            -- Regra 1
            -- Valida Identificador do arquivo
            for R2 in (
                select * from RHPBH_ARQUIVO_DUPLA_LOTACAO CS
                 where CODIGO_EMPRESA = PCODIGO_EMPRESA
                  and ID_ARQUIVO = C1.ID_ARQUIVO
                  and CS.IDENTIFICADOR_ARQUIVO <> ARQUIVO_DUPLA_LOTACAO
            )
            loop
                GRAVA_LOG(R2.CODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_ERRO, R2.ID_ARQUIVO, R2.NUMERO_LINHA, LOG_OPERACAO_INVALIDA, 'IDENTIFICADOR_ARQUIVO = '||R2.IDENTIFICADOR_ARQUIVO);
            end loop;

            vIDENTIFICADOR_REGRA := '1';
            GRAVA_LOG(PCODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_PROCESSAMENTO, PID_ARQUIVO, 0, CODIGO_LOG_PROCESSAMENTO_50, 'APLICACAO REGRA ' || vIDENTIFICADOR_REGRA || '.');
        
        
                    -- Regra 2
            -- Valida tipo de operação
            for R2 in (
                select * from RHPBH_ARQUIVO_DUPLA_LOTACAO CS
                 where CODIGO_EMPRESA = PCODIGO_EMPRESA
                  and ID_ARQUIVO = C1.ID_ARQUIVO
                  and CS.TIPO_OPERACAO NOT IN('I','A')
            )
            loop
                GRAVA_LOG(R2.CODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_ERRO, R2.ID_ARQUIVO, R2.NUMERO_LINHA, LOG_OPERACAO_INVALIDA, 'OPERACAO = '||R2.TIPO_OPERACAO);
            end loop;

            vIDENTIFICADOR_REGRA := '2';
            GRAVA_LOG(PCODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_PROCESSAMENTO, PID_ARQUIVO, 0, CODIGO_LOG_PROCESSAMENTO_50, 'APLICACAO REGRA ' || vIDENTIFICADOR_REGRA || '.');
            
          FOR R2 IN (
          select * from RHPBH_ARQUIVO_DUPLA_LOTACAO CS
                 where CODIGO_EMPRESA = PCODIGO_EMPRESA
                  and ID_ARQUIVO = C1.ID_ARQUIVO
                  AND CS.TIPO_OPERACAO ='I'
                  AND CS.CODIGO_DUPLA_LOTACAO_PARA IS NOT  NULL
          )LOOP
                          GRAVA_LOG(R2.CODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_ERRO, R2.ID_ARQUIVO, R2.NUMERO_LINHA, LOG_ACAO_NAO_PODE_TER_PARA, 'OPERACAO = '||R2.TIPO_OPERACAO);

          END LOOP;
          vIDENTIFICADOR_REGRA := '3';
          GRAVA_LOG(PCODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_PROCESSAMENTO, PID_ARQUIVO, 0, CODIGO_LOG_PROCESSAMENTO_50, 'APLICACAO REGRA ' || vIDENTIFICADOR_REGRA || '.');
          --regra 4
     FOR R2 IN (
          select * from RHPBH_ARQUIVO_DUPLA_LOTACAO CS
                 where CODIGO_EMPRESA = PCODIGO_EMPRESA
                  and ID_ARQUIVO = C1.ID_ARQUIVO
                  AND CS.TIPO_OPERACAO ='A'
                  AND CS.CODIGO_DUPLA_LOTACAO_PARA IS  NULL
          )LOOP
                          GRAVA_LOG(R2.CODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_ERRO, R2.ID_ARQUIVO, R2.NUMERO_LINHA, LOG_ACAO_REQUER_PARA, 'OPERACAO = '||R2.TIPO_OPERACAO);

          END LOOP;
          vIDENTIFICADOR_REGRA := '3';
          GRAVA_LOG(PCODIGO_EMPRESA, CATEGORIA_LOG_REGRAS, TIPO_LOG_PROCESSAMENTO, PID_ARQUIVO, 0, CODIGO_LOG_PROCESSAMENTO_50, 'APLICACAO REGRA ' || vIDENTIFICADOR_REGRA || '.');

            
             PR_SET_SITUACAO_PROCESSAMENTO('05');
            PR_CONTROLE_PROCESSAMENTO(C1.CODIGO_EMPRESA, C1.ID_ARQUIVO, vSITUACAO_PROCESSAMENTO);
         END LOOP;
          commit;
           
    END;
    
    END IF;

        PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO, '74');


IF PACAO in (3, 10) THEN

FOR C_INC IN (
select CS.*
          from ARTERH.VIEW_RHPBH_ARQUIVO_DUPLA_LOTACAO CS, RHPBH_ARQUIVO_LINHA AL
         where CS.ID_ARQUIVO = AL.ID_ARQUIVO
           and CS.NUMERO_LINHA = AL.NUMERO_LINHA
           and CS.CODIGO_EMPRESA = PCODIGO_EMPRESA
           and CS.ID_ARQUIVO = PID_ARQUIVO
           and AL.SITUACAO = 00
           and CS.TIPO_OPERACAO = 'I'
         order by CS.NUMERO_LINHA
)LOOP
BEGIN 
RH_AGRUPADOR.cod_agrup1:=C_INC.CODIGO_DUPLA_LOTACAO_DE_1;
RH_AGRUPADOR.cod_agrup2:=C_INC.CODIGO_DUPLA_LOTACAO_DE_2;
RH_AGRUPADOR.cod_agrup3:=C_INC.CODIGO_DUPLA_LOTACAO_DE_3;
RH_AGRUPADOR.cod_agrup4:=C_INC.CODIGO_DUPLA_LOTACAO_DE_4;
RH_AGRUPADOR.cod_agrup5:=C_INC.CODIGO_DUPLA_LOTACAO_DE_5;
RH_AGRUPADOR.cod_agrup6:=C_INC.CODIGO_DUPLA_LOTACAO_DE_6;
RH_AGRUPADOR.codigo_empresa:='0001';
RH_AGRUPADOR.descricao:=substr(trim(C_INC.DESCRICAO_DE),1,100);
RH_AGRUPADOR.login_usuario:=vUSUARIO_ATUALIZACAO;
RH_AGRUPADOR.dt_ult_alter_usua:=vDATA_ATUALIZACAO;
 SELECT
            MAX(id_agrup) + 1
            INTO RH_AGRUPADOR.id_agrup
        FROM
            rhorga_agrupador
        WHERE
            codigo_empresa = '0001';
RH_AGRUPADOR.c_livre_data16:=sysdate;
RH_AGRUPADOR.cod_agrup_sup1:=C_INC.OPUS_1;
RH_AGRUPADOR.cod_agrup_sup2:=C_INC.OPUS_2;
RH_AGRUPADOR.cod_agrup_sup3:=C_INC.OPUS_3;
RH_AGRUPADOR.cod_agrup_sup4:=C_INC.OPUS_4;
RH_AGRUPADOR.cod_agrup_sup5:=C_INC.OPUS_5;
RH_AGRUPADOR.cod_agrup_sup6:=C_INC.OPUS_6;
RH_AGRUPADOR.tipo_agrup:='G';
RH_AGRUPADOR.cgc:='18715383000140';
RH_AGRUPADOR.motivo_extincao:='ATIV';
RH_AGRUPADOR.texto_associado:=trim(C_INC.DESCRICAO_DE);
RH_AGRUPADOR.data_implant:=sysdate;
RH_AGRUPADOR.abreviacao:=C_INC.ABREVICAO_DE;
RH_AGRUPADOR.cgc_consol:='18715383000140';
RH_AGRUPADOR.razao_social:='PREF.MUN. BELO HORIZONTE';
RH_AGRUPADOR.natureza_estab:='0005';
RH_AGRUPADOR.cod_calendario:='0001';
RH_AGRUPADOR.cei_valido:='N';
RH_AGRUPADOR.empresa_peq_porte:='N';
RH_AGRUPADOR.microempresa:='N';
RH_AGRUPADOR.participa_pat:='N';
RH_AGRUPADOR.c_livre_selec02:='0';
RH_AGRUPADOR.c_livre_selec03:='1';
RH_AGRUPADOR.ente_fed_resp_esocial:=' ';
RH_AGRUPADOR.tp_insc_contra_esocial:='1'; 

CRIAR_NOVOS_LOCAIS_AGRUP(RH_AGRUPADOR);
 COMMIT;
 
 
RH_GERENCIAL.cod_cgerenc1:=C_INC.CODIGO_DUPLA_LOTACAO_DE_1;
RH_GERENCIAL.cod_cgerenc2:=C_INC.CODIGO_DUPLA_LOTACAO_DE_2;
RH_GERENCIAL.cod_cgerenc3:=C_INC.CODIGO_DUPLA_LOTACAO_DE_3;
RH_GERENCIAL.cod_cgerenc4:=C_INC.CODIGO_DUPLA_LOTACAO_DE_4;
RH_GERENCIAL.cod_cgerenc5:=C_INC.CODIGO_DUPLA_LOTACAO_DE_5;
RH_GERENCIAL.cod_cgerenc6:=C_INC.CODIGO_DUPLA_LOTACAO_DE_6;
RH_GERENCIAL.codigo_empresa:='0001';
RH_GERENCIAL.descricao:=RH_AGRUPADOR.descricao;
RH_GERENCIAL.login_usuario:=RH_AGRUPADOR.login_usuario;
RH_GERENCIAL.dt_ult_alter_usua:=RH_AGRUPADOR.dt_ult_alter_usua;
RH_GERENCIAL.c_livre_data16:=sysdate;
RH_GERENCIAL.cod_cgerenc_sup1:=C_INC.OPUS_1;
RH_GERENCIAL.cod_cgerenc_sup2:=C_INC.OPUS_2;
RH_GERENCIAL.cod_cgerenc_sup3:=C_INC.OPUS_3;
RH_GERENCIAL.cod_cgerenc_sup4:=C_INC.OPUS_4;
RH_GERENCIAL.cod_cgerenc_sup5:=C_INC.OPUS_5;
RH_GERENCIAL.cod_cgerenc_sup6:=C_INC.OPUS_6;
RH_GERENCIAL.cgc:='18715383000140';
RH_GERENCIAL.motivo_extincao:='ATIV';
RH_GERENCIAL.data_implant:=SYSDATE;
RH_GERENCIAL.texto_associado:=trim(RH_AGRUPADOR.texto_associado);
RH_GERENCIAL.id_agrup:=RH_AGRUPADOR.id_agrup;
RH_GERENCIAL.logo:='logo_pbh.png';
RH_GERENCIAL.abreviacao:=RH_AGRUPADOR.abreviacao;
RH_GERENCIAL.cgc_consol:='18715383000140';
RH_GERENCIAL.razao_social:='PREF.MUN. BELO HORIZONTE';
RH_GERENCIAL.natureza_estab:='0005';
RH_GERENCIAL.cod_calendario:='0001';
RH_GERENCIAL.cei_valido:='N';
RH_GERENCIAL.empresa_peq_porte:='N';
RH_GERENCIAL.microempresa:='N';
RH_GERENCIAL.participa_pat:='N';
RH_GERENCIAL.c_livre_selec02:='0';
RH_GERENCIAL.c_livre_selec03:='1';
RH_GERENCIAL.ente_fed_resp_esocial:=' ';
RH_GERENCIAL.tp_insc_contra_esocial:='1';

CRIAR_NOVOS_LOCAIS_GERENC(RH_GERENCIAL);

GRAVA_LOG(C_INC.CODIGO_EMPRESA, CATEGORIA_LOG_EFETIVACAO, TIPO_LOG_SUCESSO, C_INC.ID_ARQUIVO, C_INC.NUMERO_LINHA, LOG_SUCESSO_INCLUSAO, NULL);




EXCEPTION
     WHEN OTHERS THEN
              --dbms_output.put_line('ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
              --raise_application_error (-20002,'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO');
              GRAVA_LOG(C_INC.CODIGO_EMPRESA, CATEGORIA_LOG_EFETIVACAO, TIPO_LOG_ERRO, C_INC.ID_ARQUIVO, C_INC.NUMERO_LINHA, LOG_REGISTRO_JA_EXISTENTE, 'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO. '||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
END;

       

        vCONTADOR := vCONTADOR + 1;
END LOOP;


  -- #### INICIO OPERACAO ALTERACAO ####
    FOR C_INC in(

        select CS.*
          from ARTERH.VIEW_RHPBH_ARQUIVO_DUPLA_LOTACAO CS, RHPBH_ARQUIVO_LINHA AL
         where CS.ID_ARQUIVO = AL.ID_ARQUIVO
           and CS.NUMERO_LINHA = AL.NUMERO_LINHA
           and CS.CODIGO_EMPRESA = PCODIGO_EMPRESA
           and CS.ID_ARQUIVO = PID_ARQUIVO
           and AL.SITUACAO = 00
           and CS.tipo_OPERACAO = 'A'
         order by CS.NUMERO_LINHA
    )
    loop
    
    BEGIN 
    
 UPDATE ARTERH.RHORGA_AGRUPADOR SET DATA_EXTINCAO=SYSDATE, motivo_extincao='EXCL'  
 WHERE COD_AGRUP1=C_INC.CODIGO_DUPLA_LOTACAO_DE_1 
 AND COD_AGRUP2=C_INC.CODIGO_DUPLA_LOTACAO_DE_2 
 AND COD_AGRUP3=C_INC.CODIGO_DUPLA_LOTACAO_DE_3 
 AND COD_AGRUP4=C_INC.CODIGO_DUPLA_LOTACAO_DE_4 
 AND COD_AGRUP5=C_INC.CODIGO_DUPLA_LOTACAO_DE_5 
 AND COD_AGRUP6=C_INC.CODIGO_DUPLA_LOTACAO_DE_6 
 AND TIPO_AGRUP='G' 
 AND CODIGO_EMPRESA='0001';
 COMMIT;
 
 UPDATE ARTERH.rhorga_custo_geren 
 SET DATA_EXTINCAO=SYSDATE,motivo_extincao='EXCL'  
 WHERE CODIGO_EMPRESA='0001' 
 AND cod_cgerenc1=C_INC.CODIGO_DUPLA_LOTACAO_DE_1 
 and cod_cgerenc2=C_INC.CODIGO_DUPLA_LOTACAO_DE_2 
 and cod_cgerenc3=C_INC.CODIGO_DUPLA_LOTACAO_DE_3 
 and cod_cgerenc4=C_INC.CODIGO_DUPLA_LOTACAO_DE_4 
 and cod_cgerenc5=C_INC.CODIGO_DUPLA_LOTACAO_DE_5 
 and cod_cgerenc6=C_INC.CODIGO_DUPLA_LOTACAO_DE_6;
 
 EXCEPTION
     WHEN OTHERS THEN
              --dbms_output.put_line('ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
              --raise_application_error (-20002,'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO');
              GRAVA_LOG(C_INC.CODIGO_EMPRESA, CATEGORIA_LOG_EFETIVACAO, TIPO_LOG_ERRO, C_INC.ID_ARQUIVO, C_INC.NUMERO_LINHA, LOG_REGISTRO_JA_EXISTENTE, 'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO. '||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
END;




  BEGIN 
RH_AGRUPADOR.cod_agrup1:=C_INC.CODIGO_DUPLA_LOTACAO_para_1;
RH_AGRUPADOR.cod_agrup2:=C_INC.CODIGO_DUPLA_LOTACAO_para_2;
RH_AGRUPADOR.cod_agrup3:=C_INC.CODIGO_DUPLA_LOTACAO_para_3;
RH_AGRUPADOR.cod_agrup4:=C_INC.CODIGO_DUPLA_LOTACAO_para_4;
RH_AGRUPADOR.cod_agrup5:=C_INC.CODIGO_DUPLA_LOTACAO_para_5;
RH_AGRUPADOR.cod_agrup6:=C_INC.CODIGO_DUPLA_LOTACAO_para_6;
RH_AGRUPADOR.codigo_empresa:='0001';
RH_AGRUPADOR.descricao:=substr(trim(C_INC.DESCRICAO_DE),1,100);
RH_AGRUPADOR.login_usuario:=vUSUARIO_ATUALIZACAO;
RH_AGRUPADOR.dt_ult_alter_usua:=vDATA_ATUALIZACAO;
 SELECT
            MAX(id_agrup) + 1
            INTO RH_AGRUPADOR.id_agrup
        FROM
            rhorga_agrupador
        WHERE
            codigo_empresa = '0001';
RH_AGRUPADOR.c_livre_data16:=sysdate;
RH_AGRUPADOR.cod_agrup_sup1:=C_INC.OPUS_1;
RH_AGRUPADOR.cod_agrup_sup2:=C_INC.OPUS_2;
RH_AGRUPADOR.cod_agrup_sup3:=C_INC.OPUS_3;
RH_AGRUPADOR.cod_agrup_sup4:=C_INC.OPUS_4;
RH_AGRUPADOR.cod_agrup_sup5:=C_INC.OPUS_5;
RH_AGRUPADOR.cod_agrup_sup6:=C_INC.OPUS_6;
RH_AGRUPADOR.tipo_agrup:='G';
RH_AGRUPADOR.cgc:='18715383000140';
RH_AGRUPADOR.motivo_extincao:='ATIV';
RH_AGRUPADOR.texto_associado:=trim(C_INC.DESCRICAO_DE);
RH_AGRUPADOR.data_implant:=sysdate;
RH_AGRUPADOR.abreviacao:=C_INC.ABREVICAO_DE;
RH_AGRUPADOR.cgc_consol:='18715383000140';
RH_AGRUPADOR.razao_social:='PREF.MUN. BELO HORIZONTE';
RH_AGRUPADOR.natureza_estab:='0005';
RH_AGRUPADOR.cod_calendario:='0001';
RH_AGRUPADOR.cei_valido:='N';
RH_AGRUPADOR.empresa_peq_porte:='N';
RH_AGRUPADOR.microempresa:='N';
RH_AGRUPADOR.participa_pat:='N';
RH_AGRUPADOR.c_livre_selec02:='0';
RH_AGRUPADOR.c_livre_selec03:='1';
RH_AGRUPADOR.ente_fed_resp_esocial:=' ';
RH_AGRUPADOR.tp_insc_contra_esocial:='1'; 

CRIAR_NOVOS_LOCAIS_AGRUP(RH_AGRUPADOR);
 COMMIT;
 
 
RH_GERENCIAL.cod_cgerenc1:=C_INC.CODIGO_DUPLA_LOTACAO_para_1;
RH_GERENCIAL.cod_cgerenc2:=C_INC.CODIGO_DUPLA_LOTACAO_para_2;
RH_GERENCIAL.cod_cgerenc3:=C_INC.CODIGO_DUPLA_LOTACAO_para_3;
RH_GERENCIAL.cod_cgerenc4:=C_INC.CODIGO_DUPLA_LOTACAO_para_4;
RH_GERENCIAL.cod_cgerenc5:=C_INC.CODIGO_DUPLA_LOTACAO_para_5;
RH_GERENCIAL.cod_cgerenc6:=C_INC.CODIGO_DUPLA_LOTACAO_para_6;
RH_GERENCIAL.codigo_empresa:='0001';
RH_GERENCIAL.descricao:=RH_AGRUPADOR.descricao;
RH_GERENCIAL.login_usuario:=RH_AGRUPADOR.login_usuario;
RH_GERENCIAL.dt_ult_alter_usua:=RH_AGRUPADOR.dt_ult_alter_usua;
RH_GERENCIAL.c_livre_data16:=sysdate;
RH_GERENCIAL.cod_cgerenc_sup1:=C_INC.OPUS_1;
RH_GERENCIAL.cod_cgerenc_sup2:=C_INC.OPUS_2;
RH_GERENCIAL.cod_cgerenc_sup3:=C_INC.OPUS_3;
RH_GERENCIAL.cod_cgerenc_sup4:=C_INC.OPUS_4;
RH_GERENCIAL.cod_cgerenc_sup5:=C_INC.OPUS_5;
RH_GERENCIAL.cod_cgerenc_sup6:=C_INC.OPUS_6;
RH_GERENCIAL.cgc:='18715383000140';
RH_GERENCIAL.motivo_extincao:='ATIV';
RH_GERENCIAL.data_implant:=SYSDATE;
RH_GERENCIAL.texto_associado:=trim(RH_AGRUPADOR.texto_associado);
RH_GERENCIAL.id_agrup:=RH_AGRUPADOR.id_agrup;
RH_GERENCIAL.logo:='logo_pbh.png';
RH_GERENCIAL.abreviacao:=RH_AGRUPADOR.abreviacao;
RH_GERENCIAL.cgc_consol:='18715383000140';
RH_GERENCIAL.razao_social:='PREF.MUN. BELO HORIZONTE';
RH_GERENCIAL.natureza_estab:='0005';
RH_GERENCIAL.cod_calendario:='0001';
RH_GERENCIAL.cei_valido:='N';
RH_GERENCIAL.empresa_peq_porte:='N';
RH_GERENCIAL.microempresa:='N';
RH_GERENCIAL.participa_pat:='N';
RH_GERENCIAL.c_livre_selec02:='0';
RH_GERENCIAL.c_livre_selec03:='1';
RH_GERENCIAL.ente_fed_resp_esocial:=' ';
RH_GERENCIAL.tp_insc_contra_esocial:='1';

CRIAR_NOVOS_LOCAIS_GERENC(RH_GERENCIAL);

GRAVA_LOG(C_INC.CODIGO_EMPRESA, CATEGORIA_LOG_EFETIVACAO, TIPO_LOG_SUCESSO, C_INC.ID_ARQUIVO, C_INC.NUMERO_LINHA, LOG_SUCESSO_INCLUSAO, NULL);




EXCEPTION
     WHEN OTHERS THEN
              --dbms_output.put_line('ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
              --raise_application_error (-20002,'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO');
              GRAVA_LOG(C_INC.CODIGO_EMPRESA, CATEGORIA_LOG_EFETIVACAO, TIPO_LOG_ERRO, C_INC.ID_ARQUIVO, C_INC.NUMERO_LINHA, LOG_REGISTRO_JA_EXISTENTE, 'OCORREU UM ERRO AO TENTAR INCLUIR REGISTRO. '||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
END;

       

        vCONTADOR := vCONTADOR + 1;
    
    
    
    
    end loop;




    PR_SET_SITUACAO_PROCESSAMENTO('07');
    PR_CONTROLE_PROCESSAMENTO(PCODIGO_EMPRESA, PID_ARQUIVO, vSITUACAO_PROCESSAMENTO);
END IF; --ACAO 3;

END;
/*INICIO LOGICA END INICIAL*/