
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_PONTO_FECHAMENTO_MES" AS
--Kellysson em 13/12/22 baseado no script que uso desde o inicio melhorado em 2022 (roteiro_fechamento_IFPONTO.sql) criado esse usando tambem conceitos/objetos pensados no script (roteiro_fechamento_IFPONTO_DIA.sql)
--Kellysson em 7/11/23 incluido codigo empresa para pegar apenas as que fecham dia 11 na tabela de conversao 'IFP4'
vDATA_INICIO DATE;
vDATA_FIM DATE;
err_msg VARCHAR2(4000 BYTE);

vQTD_REGS NUMBER;
vLOG VARCHAR2(4000 BYTE);
vSTATUS VARCHAR2(10 BYTE);
vQTD_DIAS_MES NUMBER;
vQTD_DIAS_ESPELHO NUMBER;
vQTD_DIAS_OCORRENCIA NUMBER;
vQTD_DIAS_LMP_LMDP NUMBER;
vQTD_DIAS_SOBREAVISO NUMBER;
vQTD_DIAS_EVENTO NUMBER;

---PROCEDURE PARA GRAVAR LOG DE ERRO
PROCEDURE GRAVA_ERRO(PROCEDURE_ERRO IN VARCHAR2,COD_ERRO IN VARCHAR2, SQL_ERRO IN VARCHAR2) AS
BEGIN
INSERT INTO PONTO_ELETRONICO.SMARH_INT_LOG_INTEGRA_DIARIA(ID,PROCEDURE_ERRO,CODIGO_ERRO,DESCRICAO_ERRO) VALUES(PONTO_ELETRONICO.ID_SEQ_LOG_PONTO.NEXTVAL,PROCEDURE_ERRO,COD_ERRO,SQL_ERRO);
COMMIT;
END;

---PROCEDURE PARA GRAVAR LOG DE SUCESSO
PROCEDURE GRAVA_SUCESSO(PROCEDURE_ERRO IN VARCHAR2,COD_ERRO IN VARCHAR2, SQL_ERRO IN VARCHAR2) AS
BEGIN
INSERT INTO PONTO_ELETRONICO.SMARH_INT_LOG_INTEGRA_DIARIA(ID,PROCEDURE_ERRO,CODIGO_ERRO,DESCRICAO_ERRO,VERIFICADO) VALUES(PONTO_ELETRONICO.ID_SEQ_LOG_PONTO.NEXTVAL,PROCEDURE_ERRO,COD_ERRO,SQL_ERRO,'S');
COMMIT;
END;



BEGIN --BEGIN GERAL
dbms_output.enable(null);--ajuste 14/2/23
--PEGA DATA INICIO E FIM DO FECHAMENTO
--vDATA_INICIO := TO_DATE(DATA_INICIO,'DD/MM/YYYY'); --TROCAR PELO ARGUMENTO DA PROCEDURE
--vDATA_FIM := TO_DATE(DATA_FIM,'DD/MM/YYYY'); --TROCAR PELO ARGUMENTO DA PROCEDURE
SELECT DATA_INICIO INTO vDATA_INICIO FROM PONTO_ELETRONICO.VW_IFPONTO_FECHAMENTO WHERE EMPRESA = '0001' AND TIPO_FECHAMENTO = 'EMPRESA';
SELECT DATA_FIM INTO vDATA_FIM FROM PONTO_ELETRONICO.VW_IFPONTO_FECHAMENTO WHERE EMPRESA = '0001' AND TIPO_FECHAMENTO = 'EMPRESA';

vQTD_DIAS_MES := (TRUNC(vDATA_FIM)- TRUNC(vDATA_INICIO))+1;

------------------------------------------------------------------------------------------------------------------------INICIO--PROCESSO FECHAMENTO--------------------------------------------------------------------------------------
IF vDATA_INICIO IS NOT NULL AND vDATA_FIM IS NOT NULL THEN
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, POIS HA REGISTRO NA VIEW PONTO_ELETRONICO.VW_IFPONTO_FECHAMENTO PARA INICIAR PROCESSO DE FECHAMENTO COM vDATA_INICIO: '||vDATA_INICIO||'  E vDATA_FIM: '||vDATA_FIM|| ' vQTD_DIAS_MES: '||vQTD_DIAS_MES;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG);COMMIT;
vLOG := NULL;


-- TAREFA 1 -- criada em 19/12/22
-- Verifica se os phps que buscam os dados do Ifponto foram executados com seus valores de registros corretos

--parte do espelho serao 31 php (EspelhoD..php) um por dia onde vai levar 5 minutos cada total de 155 minutos ou 2h40 acabando por volta das 9h
SELECT COUNT(1)QTD_DIAS INTO vQTD_DIAS_ESPELHO FROM (SELECT TRUNC(DATA)DATA, COUNT(1)FROM PONTO_ELETRONICO.IFPONTO_ESPELHO 
WHERE LPAD(EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
GROUP BY TRUNC(DATA) ORDER BY TRUNC(DATA) DESC);
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vQTD_DIAS_ESPELHO: '||vQTD_DIAS_ESPELHO;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1, CAMPO_2)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG, vQTD_DIAS_ESPELHO); COMMIT;
vLOG := NULL;

--parte de OCORRENCIAS -- Ocorrencias.php
SELECT COUNT(1)QTD_DIAS INTO vQTD_DIAS_OCORRENCIA 
FROM(SELECT TRUNC(DTCADASTRO), COUNT(1)QTD FROM PONTO_ELETRONICO.IFPONTO_OCORRENCIAS WHERE DATA_PROCESSAMENTO IS NULL AND TRUNC(DTCADASTRO)BETWEEN vDATA_INICIO AND vDATA_FIM 
AND LPAD(EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
GROUP BY TRUNC(DTCADASTRO) ORDER BY TRUNC(DTCADASTRO)DESC);
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vQTD_DIAS_OCORRENCIA: '||vQTD_DIAS_OCORRENCIA;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1, CAMPO_2)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG, vQTD_DIAS_OCORRENCIA); COMMIT;
vLOG := NULL;

--parte de LMP e LMDP --LmpLmdp.php
SELECT COUNT(1)QTD_DIAS INTO vQTD_DIAS_LMP_LMDP 
FROM(SELECT TRUNC(DTCADASTRO), COUNT(1)QTD FROM PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC WHERE DATA_PROCESSAMENTO IS NULL AND TRUNC(DTCADASTRO) BETWEEN vDATA_INICIO AND vDATA_FIM GROUP BY TRUNC(DTCADASTRO) ORDER BY TRUNC(DTCADASTRO)DESC);
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vQTD_DIAS_LMP_LMDP: '||vQTD_DIAS_LMP_LMDP;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1, CAMPO_2)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG, vQTD_DIAS_LMP_LMDP); COMMIT;
vLOG := NULL;

--parte de sobreavisos -- Sobreavisos.php
SELECT COUNT(1)QTD_DIAS INTO vQTD_DIAS_SOBREAVISO
FROM(SELECT TRUNC(DTINICIO), COUNT(1)QTD FROM PONTO_ELETRONICO.AUTORIZACAO_EXTRA_PESSOA WHERE TRUNC(DTINICIO) BETWEEN vDATA_INICIO AND vDATA_FIM 
AND LPAD(EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
GROUP BY TRUNC(DTINICIO) ORDER BY TRUNC(DTINICIO)DESC);
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vQTD_DIAS_SOBREAVISO: '||vQTD_DIAS_SOBREAVISO;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1, CAMPO_2)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG, vQTD_DIAS_SOBREAVISO); COMMIT;
vLOG := NULL;

--parte das marcacoes para a SMSA e SMSP --EventosP1.php, EventosP2.php, EventosP3.php
SELECT COUNT(1)QTD_DIAS INTO vQTD_DIAS_EVENTO FROM(
select trunc(dtevento), COUNT(1) qtd_dia from PONTO_ELETRONICO.IFPONTO_MARCACOES WHERE DATA_PROCESSAMENTO IS NULL 
AND LPAD(EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
group by  trunc(dtevento) order by  trunc(dtevento) desc);
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vQTD_DIAS_EVENTO: '||vQTD_DIAS_EVENTO;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1, CAMPO_2)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG, vQTD_DIAS_EVENTO); COMMIT;
vLOG := NULL;

IF 
vQTD_DIAS_ESPELHO <> vQTD_DIAS_MES OR
vQTD_DIAS_OCORRENCIA < 10 OR
vQTD_DIAS_LMP_LMDP < 10 OR
vQTD_DIAS_SOBREAVISO < 10 OR
vQTD_DIAS_EVENTO  <> vQTD_DIAS_MES --ajuste 14/2/23
THEN
vSTATUS := 'PARA';
vLOG := 'TAREFA 0 PROCESSAMENTO PARA, vSTATUS: '||vSTATUS;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG);COMMIT;
vLOG := NULL;

ELSE
vSTATUS := 'SEGUE';
vLOG := 'TAREFA 0 PROCESSAMENTO SEGUE, vSTATUS: '||vSTATUS;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG);COMMIT;
vLOG := NULL;


--/*
BEGIN 
PONTO_ELETRONICO.PR_PONTO_FECHAMENTO_MES_P1(TO_DATE(vDATA_INICIO,'DD/MM/YYYY'),TO_DATE(vDATA_FIM,'DD/MM/YYYY'));
 err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_PONTO_FECHAMENTO_MES_P1','000',err_msg);
exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_PONTO_FECHAMENTO_MES_P1',SQLCODE,err_msg);
END;
--*/


END IF;


ELSE
vLOG := 'TAREFA 0 PROCESSAMENTO PARA, POIS NAO HA REGISTRO NA VIEW PONTO_ELETRONICO.VW_IFPONTO_FECHAMENTO PARA INICIAR PROCESSO DE FECHAMENTO COM DATA INICIO E FIM, VERIFICAR.' ;
DBMS_OUTPUT.PUT_LINE(vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CONSIDERACOES, DATA_DADOS, CAMPO_1)VALUES('LOG_PR_FECHAMENTO_MES', SYSDATE, vLOG);COMMIT;
vLOG := NULL;

END IF;
------------------------------------------------------------------------------------------------------------------------FIM--PROCESSO FECHAMENTO--------------------------------------------------------------------------------------





END;-- END GERAL
