
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_PROXIMA_SITUACAO_FUNCIONAL" (DATA_INICIO IN VARCHAR2, DATA_FIM IN VARCHAR2)
AS
BEGIN

DECLARE  
vCONTADOR NUMBER;
vDATA_INICIO Varchar2(10);
vDATA_FIM Varchar2(10);
err_msg varchar2 (4000);

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;
err_msg := NULL;

FOR C1 IN (

SELECT X2.* 
, ULT_ASF.COD_SIT_FUNCIONAL ULT_COD_SIT_FUNCIONAL_ATIVA
,CASE 
WHEN X2.QTDe_DIAS_PROXIMO IS NOT NULL and X2.QTDe_DIAS_PROXIMO > 0 THEN 'PROXIMA COM PROXIMA ATIVA'
WHEN (X2.QTDe_DIAS_PROXIMO IS NULL OR X2.QTDe_DIAS_PROXIMO <= 0) AND X2.CONTROLE_FOLHA_PROXIMA = 'N' THEN 'APENAS PROXIMA ATIVA'
END TIPO

FROM (

SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO ,X.DATA_INIC_SITUACAO ,X.COD_SIT_FUNCIONAL ,X.DATA_FIM_SITUACAO ,X.PROXIMA_SITUACAO 
,PROX_SF.qtde_dias_proximo, PROX_SF.CONTROLE_FOLHA CONTROLE_FOLHA_PROXIMA, PROX_SF.E_AFASTAMENTO E_AFASTAMENTO_PROXIMA, PROX_SF.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_PROXIMA
--, ULT_ASF.COD_SIT_FUNCIONAL ULT_COD_SIT_FUNCIONAL_ATIVA
,x.login_usuario, x.dt_ult_alter_usua
FROM RHCGED_ALT_SIT_FUN X
left outer join 
(select b.* from  RHPESS_CONTRATO B where B.ANO_MES_REFERENCIA = 
              (select max(ANO_MES_REFERENCIA) from RHPESS_CONTRATO AUX
              where AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = B.TIPO_CONTRATO and AUX.CODIGO = B.CODIGO and AUX.ANO_MES_REFERENCIA <= sysdate) 
              and B.CODIGO_EMPRESA in ('0001','0098', '0003','0013','0014','0002','0007','0009','0010')
              AND B.DATA_RESCISAO IS NULL 
)C on  c.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND c.TIPO_CONTRATO = X.TIPO_CONTRATO AND c.CODIGO = X.CODIGO
/*
LEFT OUTER JOIN (SELECT ULT_ASF_I.* FROM RHCGED_ALT_SIT_FUN ULT_ASF_I 
                                  LEFT OUTER JOIN RHPARM_SIT_FUNC ULT_ASF_SF ON ULT_ASF_SF.CODIGO = ULT_ASF_I.cod_sit_funcional 
        WHERE ULT_ASF_I.DATA_INIC_SITUACAO = (SELECT MAX(AUX.data_inic_situacao) FROM RHCGED_ALT_SIT_FUN AUX 
                                          WHERE AUX.CODIGO_EMPRESA =  ULT_ASF_I.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = ULT_ASF_I.TIPO_CONTRATO AND AUX.CODIGO = ULT_ASF_I.CODIGO)
                  AND ULT_ASF_SF.CONTROLE_FOLHA = 'N') ULT_ASF ON X.CODIGO_EMPRESA = ULT_ASF.CODIGO_EMPRESA AND X.TIPO_CONTRATO = ULT_ASF.TIPO_CONTRATO AND X.CODIGO = ULT_ASF.CODIGO 
*/
LEFT OUTER JOIN RHPARM_SIT_FUNC PROX_SF ON PROX_SF.CODIGO = X.PROXIMA_SITUACAO


WHERE X.CODIGO_EMPRESA IN ('0001','0098', '0003','0013','0014','0002','0007','0009','0010')
AND X.PROXIMA_SITUACAO IS NOT NULL 
and X.DATA_FIM_SITUACAO is not null
and X.DATA_INIC_SITUACAO = (Select max(AUX.DATA_INIC_SITUACAO) from RHCGED_ALT_SIT_FUN AUX
                             where AUX.CODIGO_EMPRESA = X.CODIGO_EMPRESA and AUX.TIPO_CONTRATO = X.TIPO_CONTRATO and AUX.CODIGO = X.CODIGO )
AND 
(
--------------------------TRUNC(X.DATA_FIM_SITUACAO)= to_date('03/10/19','dd/mm/yy')
--TRUNC(X.DATA_FIM_SITUACAO)>= TO_DATE('04/10/19 00:00:01', 'DD/MM/YY HH24:MI:SS')--to_date('01/10/19','dd/mm/yy')--vDATA_INICIO--PARAMETRO PROCEDURE
--AND
--TRUNC(X.DATA_FIM_SITUACAO)<= TO_DATE('06/10/19 23:59:59', 'DD/MM/YY HH24:MI:SS')--to_date('01/10/19','dd/mm/yy')--vDATA_FIM--PARAMETRO PROCEDURE
TRUNC(X.DATA_FIM_SITUACAO) BETWEEN vDATA_INICIO AND vDATA_FIM
--TRUNC(X.DATA_FIM_SITUACAO)>= vDATA_INICIO--TO_DATE('30/07/20', 'DD/MM/YY')--to_date('01/10/19','dd/mm/yy')----PARAMETRO PROCEDURE
--AND
--TRUNC(X.DATA_FIM_SITUACAO)<= vDATA_FIM--TO_DATE('02/08/20', 'DD/MM/YY')--to_date('01/10/19','dd/mm/yy')--PARAMETRO PROCEDURE

--and X.COD_SIT_FUNCIONAL in ('1202','1213') and x.login_usuario = 'script_kellysson_MATERNIDADE_081019' 
)
order by CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO

)X2

LEFT OUTER JOIN (SELECT ULT_ASF_I.* FROM RHCGED_ALT_SIT_FUN ULT_ASF_I 

        WHERE ULT_ASF_I.DATA_INIC_SITUACAO = (SELECT MAX(AUX.data_inic_situacao) FROM RHCGED_ALT_SIT_FUN AUX 
                                              LEFT OUTER JOIN RHPARM_SIT_FUNC ULT_ASF_SF ON ULT_ASF_SF.CODIGO = aux.cod_sit_funcional 
                                          WHERE AUX.CODIGO_EMPRESA =  ULT_ASF_I.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = ULT_ASF_I.TIPO_CONTRATO AND AUX.CODIGO = ULT_ASF_I.CODIGO
                                          AND ULT_ASF_SF.CONTROLE_FOLHA = 'N'
                                          AND ULT_ASF_SF.SUSPENDE_REMUNERA = 'N' AND ULT_ASF_SF.E_AFASTAMENTO = 'N'--NOVO EM 24/7/20
                                          )
                                    ) ULT_ASF ON X2.CODIGO_EMPRESA = ULT_ASF.CODIGO_EMPRESA AND X2.TIPO_CONTRATO = ULT_ASF.TIPO_CONTRATO AND X2.CODIGO = ULT_ASF.CODIGO 




) LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--'||vCONTADOR);

BEGIN --EXCEPTION

IF (C1.QTDe_DIAS_PROXIMO IS NOT NULL and C1.QTDe_DIAS_PROXIMO > 0) THEN--AND C1.CONTROLE_FOLHA_PROXIMA <> 'N'
--dbms_output.put_line('--PROXIMA COM PROXIMA ATIVA');
/*dbms_output.put_line('INSERT INTO RHCGED_ALT_SIT_FUN (ind_ef_retro_esocial, TEXTO_ASSOCIADO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL, DATA_FIM_SITUACAO, PROXIMA_SITUACAO )
values (''N'', ''Registro criado automaticamente pela rotina proxima situacao.'', ''script_proxima_situacao'' ,sysdate,'''|| C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.codigo|| ''', TO_DATE(''' || TRUNC(C1.DATA_FIM_SITUACAO) || ''',''dd/mm/yy'')+1, '''||C1.PROXIMA_SITUACAO 
|| ''', TO_DATE(''' || TRUNC(C1.DATA_FIM_SITUACAO) || ''',''dd/mm/yy'')+'||C1.QTDe_DIAS_PROXIMo|| ', '''||C1.ULT_COD_SIT_FUNCIONAL_ATIVA
||'''); COMMIT;'  );
dbms_output.put_line('EXECUTE SUGESP_ALT_SIT_FUNC_ULT_CONTRA('''||C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.CODIGO ||''',''script_proxima_situacao'' );');
*/
INSERT INTO RHCGED_ALT_SIT_FUN (ind_ef_retro_esocial, TEXTO_ASSOCIADO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL, DATA_FIM_SITUACAO, PROXIMA_SITUACAO )values ('N', 'Registro criado automaticamente pela rotina proxima situacao.', 'script_proxima_situacao' ,sysdate, C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.codigo, TO_DATE(TRUNC(C1.DATA_FIM_SITUACAO),'dd/mm/yy')+1, C1.PROXIMA_SITUACAO, TO_DATE(TRUNC(C1.DATA_FIM_SITUACAO),'dd/mm/yy')+ C1.QTDe_DIAS_PROXIMO, C1.ULT_COD_SIT_FUNCIONAL_ATIVA); COMMIT;
SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO ,'script_proxima_situacao' );


ELSIF (C1.QTDe_DIAS_PROXIMO IS NULL OR C1.QTDe_DIAS_PROXIMO <= 0) AND C1.CONTROLE_FOLHA_PROXIMA = 'N' THEN
/*
dbms_output.put_line('--APENAS PROXIMA ATIVA');
dbms_output.put_line('INSERT INTO RHCGED_ALT_SIT_FUN (ind_ef_retro_esocial, TEXTO_ASSOCIADO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL ) values (''N'', ''Registro criado automaticamente pela rotina proxima situacao.'', ''script_proxima_situacao'' ,sysdate,'''|| C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.codigo|| ''', TO_DATE(''' || TRUNC(C1.DATA_FIM_SITUACAO) || ''',''dd/mm/yy'')+1, '''||C1.PROXIMA_SITUACAO 
||'''); COMMIT;'  );
dbms_output.put_line('EXECUTE SUGESP_ALT_SIT_FUNC_ULT_CONTRA('''||C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.CODIGO ||''',''script_proxima_situacao'' );');
*/
INSERT INTO RHCGED_ALT_SIT_FUN (ind_ef_retro_esocial, TEXTO_ASSOCIADO, LOGIN_USUARIO, DT_ULT_ALTER_USUA, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL ) values ('N', 'Registro criado automaticamente pela rotina proxima situacao.', 'script_proxima_situacao' ,sysdate, C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.codigo, TO_DATE(TRUNC(C1.DATA_FIM_SITUACAO),'dd/mm/yy')+1, C1.PROXIMA_SITUACAO ); COMMIT;
SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO ,'script_proxima_situacao' );

END IF;

EXCEPTION WHEN OTHERS THEN
err_msg := SQLCODE||' '||SUBSTR(SQLERRM, 1, 4000);
dbms_output.put_line('err_msg:' ||err_msg);

INSERT INTO SUGESP_AJUSTE_LOTE_CAMPO_HIST(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_VALOR_1,  DATA_DADOS, CONSIDERACOES)
VALUES(C1.CODIGO_EMPRESA,C1.TIPO_CONTRATO, C1.CODIGO,'LOG EXECUCAO PROCEDURE PR_PROXIMA_SITUACAO_FUNCIONAL', SYSDATE, err_msg
);COMMIT;
END;--BEGIN EXCEPTION

err_msg := NULL;

END LOOP;

END;

END;