
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PR_RENOMEAR_ROTULO_ARQUIVO" (PID_ARQUIVO CHAR, PROTULO_ARQUIVO VARCHAR2) as

  vID_ARQUIVO NUMBER;
  vSITUACAO_ARQUIVO CHAR(2);
  vTIPO_ARQUIVO CHAR(4);
  vCODIGO_EMPRESA CHAR(4);
  vROTULO_ARQUIVO VARCHAR2(30);
  vCONTADOR NUMBER;
  vLOGIN_USUARIO VARCHAR2(40) := 'IMPORT_RENOMEAR';
  vLINHA_ATUALIZADA NUMBER;
BEGIN
    BEGIN
         vID_ARQUIVO := null;
         select ID_ARQUIVO, SITUACAO, TIPO_ARQUIVO, CODIGO_EMPRESA 
           into vID_ARQUIVO, vSITUACAO_ARQUIVO, vTIPO_ARQUIVO, vCODIGO_EMPRESA
           from RHPBH_ARQUIVO where ID_ARQUIVO = PID_ARQUIVO;

         IF vID_ARQUIVO IS NULL THEN
            raise_application_error (-20001,'ID ARQUIVO INVALIDO.');
         END IF;

    EXCEPTION
    WHEN OTHERS THEN
       raise_application_error (-20002,'NAO FOI POSSIVEL RECUPERAR O ARQUIVO COM O ID_ARQUIVO INFORMADO.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;

    -- Verifica se o rótulo para arquivo informado é válido
    IF PROTULO_ARQUIVO IS NULL THEN
        raise_application_error (-20001,'O ROTULO DO ARQUIVO NAO FOI INFORMADO.');    
    ELSE
      IF LENGTH(PROTULO_ARQUIVO) < 8 or LENGTH(PROTULO_ARQUIVO) > 30 THEN
        raise_application_error (-20001,'ROTULO_ARQUIVO INVALIDO. SE PARAMETRO DIFERENTE DE N, ENTAO DEVE CONTER NO MINIMO 8 E NO MAXIMO 30 CARACTERES. PODE NAO SER INFORMADO. NESTE CASO INFORME O CARACTERE N E O SISTEMA GERARÁ O ROTULO AUTOMATICAMENTE.');
      END IF;
      
        BEGIN
        vCONTADOR := 0;
        select COUNT(1)
          into vCONTADOR
          from RHPBH_ARQUIVO
         where CODIGO_EMPRESA = vCODIGO_EMPRESA
           and ROTULO_ARQUIVO = PROTULO_ARQUIVO;

        IF vCONTADOR > 0 THEN
          raise_application_error (-20001,'O ROTULO INFORMADO JA EXISTE PARA A EMPRESA DO ARQUIVO INFORMADO.');
        ELSE
            vROTULO_ARQUIVO := PROTULO_ARQUIVO;
        END IF;

        EXCEPTION
        WHEN OTHERS THEN
           raise_application_error (-20001,'ERRO AO VALIDAR ROTULO.'|| 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
           vROTULO_ARQUIVO := NULL;
        END;   
      
        BEGIN
             update RHPBH_ARQUIVO
                set ROTULO_ARQUIVO = vROTULO_ARQUIVO,
                    LOGIN_USUARIO = vLOGIN_USUARIO,
                    DT_ULT_ALTER_USUA = sysdate
              where ID_ARQUIVO = PID_ARQUIVO;
    
              vLINHA_ATUALIZADA := sql%rowcount;
    
              IF vLINHA_ATUALIZADA = 0 THEN
                 raise_application_error (-20002,'NAO FOI POSSIVEL RENOMEAR O ARQUIVO COM O ID_ARQUIVO INFORMADO. ENTRE EM CONTATO COM A AREA DE SUPORTE DA PBH.');
              END IF;    
        EXCEPTION
        WHEN OTHERS THEN
           raise_application_error (-20002,'NAO FOI POSSIVEL CANCELAR O ARQUIVO COM O ID_ARQUIVO INFORMADO.' || 'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
        END;
        COMMIT;
          
    END IF;
    
END;