
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SMSP_ESCALA_CERCA_CONTRATO" AS
BEGIN
  DECLARE
    CONT               NUMBER;
    EMPRESA_ESCALA_DE  VARCHAR2(4 BYTE);
    ESCALA_DE          VARCHAR2(4 BYTE);
    DATA_INI           DATE;
    COD_CERCA          VARCHAR2(15 BYTE);
    COD_PROPRIO        VARCHAR2(15 BYTE);
    COD_ARTE           VARCHAR2(15 BYTE);
    vDATA_SISTEMA      DATE;
    FECHAMENTO_SISTEMA CHAR(1 byte);
    DT_ULT_CONTRATO    DATE;
    vATUALIZAR         CHAR(1 BYTE);
    HIST_CERTO         CHAR(1 BYTE);
    DATA_COMPARA DATE;
    DIA_COMECO_CICLO NUMBER;
    FUNCTION ACERTO_HISTORICO_ESCALA(
        Vempresa   CHAR,
        vtipo_cont CHAR ,
        vcont      VARCHAR2 )
      RETURN CHAR
    AS
      correcao CHAR;
      CONT     NUMBER;
      comando  VARCHAR2( 4000 byte);
    BEGIN
      correcao:=NULL;
      CONT    :=0;
      FOR C1 IN
      (SELECT X.*
      FROM
        (SELECT P.CODIGO_EMPRESA,
          P.TIPO_CONTRATO,
          P.CODIGO_CONTRATO,
          P.DT_INICIO_TROCA,
          P.DT_FIM_TROCA,
          P.COD_ESCALA,
          (SELECT MIN(AUX.DT_INICIO_TROCA)-1
          FROM ARTERH.RHPONT_ALT_ESCALA AUX
          WHERE AUX.CODIGO_CONTRATO=P.CODIGO_CONTRATO
          AND AUX.TIPO_CONTRATO    =P.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA   =P.CODIGO_EMPRESA
          AND AUX.ALTER_DEFINITIVA ='S'
          AND AUX.DT_INICIO_TROCA  >P.DT_INICIO_TROCA
          )AS DATA_FIM
        FROM ARTERH.RHPONT_ALT_ESCALA P
        WHERE ALTER_DEFINITIVA='S'
        AND P.CODIGO_CONTRATO=vcont
        AND P.TIPO_CONTRATO=vtipo_cont
        AND P.CODIGO_EMPRESA=Vempresa
        )X
      WHERE TRUNC(X.DT_FIM_TROCA)<>TRUNC(X.DATA_FIM)
      )
      LOOP
        IF C1.DATA_FIM IS NOT NULL THEN
          comando      :='UPDATE ARTERH.RHPONT_ALT_ESCALA SET DT_FIM_TROCA=TO_DATE('''||C1.DATA_FIM||''',''DD/MM/YYYY''), LOGIN_USUARIO=''ACERTO_HIST_ESCACALA'',DT_ULT_ALTER_USUA=SYSDATE WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO_CONTRATO='''||C1.CODIGO_CONTRATO||''' AND TRUNC(DT_INICIO_TROCA)=TO_DATE('''||C1.DT_INICIO_TROCA||''',''DD/MM/YYYY'') AND COD_ESCALA='''||C1.COD_ESCALA||''';';
          UPDATE ARTERH.RHPONT_ALT_ESCALA SET DT_FIM_TROCA=TO_DATE(''||C1.DATA_FIM||'','DD/MM/YYYY'), LOGIN_USUARIO='ACERTO_HIST_ESCACALA',DT_ULT_ALTER_USUA=SYSDATE WHERE CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||'' AND TIPO_CONTRATO=''||C1.TIPO_CONTRATO||'' AND CODIGO_CONTRATO=''||C1.CODIGO_CONTRATO||'' AND TRUNC(DT_INICIO_TROCA)=TO_DATE(''||C1.DT_INICIO_TROCA||'','DD/MM/YYYY') AND COD_ESCALA=''||C1.COD_ESCALA||'';
          COMMIT;
          dbms_output.put_line('UPDATE DO ACERTO:---==='||comando);
          dbms_output.put_line('COMMIT;');
          correcao:='S';
        END IF;
      END LOOP;
      IF correcao IS NULL THEN
        correcao  :='S';
      END IF;
      return correcao;
    END;
  BEGIN
    DBMS_OUTPUT.ENABLE (buffer_size => NULL);
    Select trunc(SYSDATE,'MM') INTO DATA_COMPARA FROM DUAL;

    SELECT
      CASE
        WHEN X.CENARIOS IN ('1','2')
        THEN'S'
        ELSE'N'
      END AS SISTEMA_FECHADO,
      F2
    INTO FECHAMENTO_SISTEMA,
      vDATA_SISTEMA
    FROM
      (SELECT
        CASE
          WHEN (X.F2            > X.FIM_FOLHA
          AND X.REF_CONTRATO    > X.FIM_FOLHA)
          AND X.FIM_FECHAMENTO IS NULL
          THEN 1
            /*'1-SISTEMA_FECHADO_DATAS_OK'*/
          WHEN (X.F2           <= X.FIM_FOLHA
          OR X.REF_CONTRATO    <= X.FIM_FOLHA)
          AND X.FIM_FECHAMENTO IS NULL
          THEN 2
            /*'2-SISTEMA_FECHADO_DATAS_ERRADAS'*/
          WHEN (X.F2            > X.FIM_FOLHA
          AND X.REF_CONTRATO    > X.FIM_FOLHA)
          AND X.FIM_FECHAMENTO IS NOT NULL
          THEN 3
            /*'3-SISTEMA_ABERTO_DATAS_OK'*/
          WHEN (X.F2           <= X.FIM_FOLHA
          OR X.REF_CONTRATO    <= X.FIM_FOLHA)
          AND X.FIM_FECHAMENTO IS NOT NULL
          THEN 4
            /*'4-SISTEMA_ABERTO_DATAS_ERRADAS'*/
          ELSE 0
            /*'FALTA MAPEAR'*/
        END CENARIOS,
        X.*
      FROM
        (SELECT
          (SELECT DATA_DO_SISTEMA FROM rhparm_p_sist
          ) AS F2,
          (SELECT DT_REFER_CADASTRO FROM rhparm_p_sist
          ) AS REF_CONTRATO,
          u.data_ini_vigencia INICIO_FECHAMENTO,
          u.data_fim_vigencia FIM_FECHAMENTO,
          u.data_ini_folha INICIO_FOLHA,
          u.data_fim_folha FIM_FOLHA
        FROM RHPONT_APUR_AGRUP u
        WHERE u.ocorrencia =
          (SELECT MAX(x.ocorrencia)
          FROM RHPONT_APUR_AGRUP x
          WHERE x.codigo_empresa = '0001'
          AND x.tipo_apur        = 'F'
          AND c_livre_selec01    = 3
          AND id_agrup           = 152123
          )
        AND c_livre_selec01 = 3--novo em 19/3/21
        )X
      )x;
    CONT:=0;
    FOR C1 IN
    (SELECT 
CASE WHEN  NOVO='NOVO_CADASTRO' THEN CODIGO_PROPRIO 
WHEN ALTEROU_CODIGO_PROPRIO='CODIGO_PROPRIO_MUDOU'  THEN CODIGO_PROPRIO_SEGUINTE END AS CODIGO_PROPRIO,
CASE WHEN  NOVO='NOVO_CADASTRO' THEN ESCALA 
WHEN (ALTEROU_ESCALA='ESCALA_MUDOU' OR ALTEROU_HORA_INICIO='HORA_INICIO_MUDOU' OR ALTEROU_HORA_FIM='HORA_FIM_MUDOU')  THEN ESCALA_SEGUINTE  END AS ESCALA,
CASE WHEN  NOVO='NOVO_CADASTRO' THEN HORA_INICIO 
WHEN (ALTEROU_ESCALA='ESCALA_MUDOU' OR ALTEROU_HORA_INICIO='HORA_INICIO_MUDOU' OR ALTEROU_HORA_FIM='HORA_FIM_MUDOU')  THEN HORA_INICIO_SEGUINTE  END AS HORA_INICIO,
CASE WHEN  NOVO='NOVO_CADASTRO' THEN HORA_FIM 
WHEN (ALTEROU_ESCALA='ESCALA_MUDOU' OR ALTEROU_HORA_INICIO='HORA_INICIO_MUDOU' OR ALTEROU_HORA_FIM='HORA_FIM_MUDOU')  THEN HORA_FIM_SEGUINTE  END AS HORA_FIM,
X.CODIGO_CONTRATO,X.TIPO_CONTRATO,X.CODIGO_EMPRESA,X.ALTEROU_CODIGO_PROPRIO,X.ALTEROU_ESCALA,X.ALTEROU_HORA_INICIO,X.ALTEROU_HORA_FIM,X.NOVO
    FROM
      (SELECT
        CASE
          WHEN ( X1.INTEGRADO          ='N' AND X1.INTEGRADO_SEGUINTE IS NULL )or(X1.INTEGRADO='S' AND X1.INTEGRADO_SEGUINTE IS NULL AND X1.DIA='ULTIMO')

          THEN 'NOVO_CADASTRO'
          ELSE 'NAO'
        END AS NOVO,
        CASE
          WHEN X1.CHAVE_INTEGRACAO_SEGUINTE='ATIVO'
          AND ((X1.CODIGO_PROPRIO         <>X1.CODIGO_PROPRIO_SEGUINTE)
          OR(X1.CODIGO_PROPRIO            IS NULL
          AND X1.CODIGO_PROPRIO_SEGUINTE  IS NOT NULL))
          THEN 'CODIGO_PROPRIO_MUDOU'
          ELSE 'CODIGO_PROPRIO_IGUAL'
        END AS ALTEROU_CODIGO_PROPRIO,
        CASE
          WHEN X1.CHAVE_INTEGRACAO_SEGUINTE='ATIVO'
          AND ((X1.ESCALA                 <>X1.ESCALA_SEGUINTE)
          OR(X1.ESCALA                    IS NULL
          AND X1.ESCALA_SEGUINTE          IS NOT NULL))
          THEN 'ESCALA_MUDOU'
          ELSE 'ESCALA_IGUAL'
        END AS ALTEROU_ESCALA,
        CASE
          WHEN X1.CHAVE_INTEGRACAO_SEGUINTE='ATIVO'
          AND ((X1.HORA_INICIO            <>X1.HORA_INICIO_SEGUINTE)
          OR(X1.HORA_INICIO               IS NULL
          AND X1.HORA_INICIO_SEGUINTE     IS NOT NULL))
          THEN 'HORA_INICIO_MUDOU'
          ELSE 'HORA_INICIO_IGUAL'
        END AS ALTEROU_HORA_INICIO,
        CASE
          WHEN X1.CHAVE_INTEGRACAO_SEGUINTE='ATIVO'
          AND ((X1.HORA_FIM               <>X1.HORA_FIM_SEGUINTE)
          OR(X1.HORA_FIM                  IS NULL
          AND X1.HORA_FIM_SEGUINTE        IS NOT NULL))
          THEN 'HORA_FIM_MUDOU'
          ELSE 'HORA_FIM_IGUAL'
        END AS ALTEROU_HORA_FIM,
        X1.*
      FROM
        (SELECT X.*
        FROM
          (SELECT X.CODIGO_EMPRESA,
            X.TIPO_CONTRATO ,
            X.CODIGO_CONTRATO,
            Row_Number () Over (Partition BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO Order By X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA)ORDEM_BM,
            X.DIA,
            LEAD(X.DIA, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) DIA_SEGUINTE,
            X.INTEGRADO,
            LEAD(X.INTEGRADO, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) INTEGRADO_SEGUINTE,
            X.CODIGO_PROPRIO,
            LEAD(X.CODIGO_PROPRIO, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) CODIGO_PROPRIO_SEGUINTE,
            X.ESCALA,
            LEAD(X.ESCALA, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) ESCALA_SEGUINTE,
            X.HORA_INICIO,
            LEAD(X.HORA_INICIO, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) HORA_INICIO_SEGUINTE,
            X.HORA_FIM,
            LEAD(X.HORA_FIM, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) HORA_FIM_SEGUINTE,
            X.CHAVE_INTEGRACAO,
            LEAD(X.CHAVE_INTEGRACAO, 1, NULL) OVER(PARTITION BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO ORDER BY X.CODIGO_EMPRESA, X.CODIGO_CONTRATO, X.TIPO_CONTRATO,X.DIA) CHAVE_INTEGRACAO_SEGUINTE
          FROM
            (SELECT X.*
            FROM
              (SELECT X.DIA,
                CN.USA_ASSOC_CONT_ESC AS INTEGRADO,
                CN.CODIGO_EMPRESA,
                CN.TIPO_CONTRATO,
                X.CODIGO_CONTRATO,
                X.CODIGO_PROPRIO,
                X.ESCALA,
                X.HORA_INICIO,
                X.HORA_FIM,
                CHAVE.DADO_DESTINO AS CHAVE_INTEGRACAO,
                X.DATA_DADOS
              FROM
                (SELECT 'ULTIMO'      AS DIA,
                  LPAD(replace(CARGA.BM,'-',''),15,0) AS CODIGO_CONTRATO,
                  CARGA.CODPROPRIO    AS CODIGO_PROPRIO,
                  CARGA.ESCALA ,
                  CARGA.HORAINIC AS HORA_INICIO,
                  CARGA.HORAFIM  AS HORA_FIM,
                  CARGA.DATA_DADOS
                FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA carga
                WHERE TRUNC(CARGA.DATA_DADOS)=
                  (SELECT MAX(TRUNC(AUX.DATA_DADOS))
                  FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA AUX
              --   WHERE trunc(AUX.DATA_DADOS)<='08/12/2021'
                  )
                )X
              LEFT OUTER JOIN
                (SELECT *
                FROM ARTERH.RHPESS_CONTRATO CN
                WHERE CN.ANO_MES_REFERENCIA=
                  (SELECT MAX(AUX.ANO_MES_REFERENCIA)
                  FROM ARTERH.RHPESS_CONTRATO AUX
                  WHERE AUX.CODIGO      =CN.CODIGO
                  AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA
                  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO
                  )
                )CN
              ON CN.CODIGO         =X.CODIGO_CONTRATO
              AND CN.CODIGO_EMPRESA='0001'
              AND CN.TIPO_CONTRATO ='0001'
              LEFT OUTER JOIN ARTERH.RHINTE_ED_IT_CONV CHAVE
              ON SUBSTR(CHAVE.DADO_ORIGEM,0,4) =CN.CODIGO_EMPRESA
              AND SUBSTR(CHAVE.DADO_ORIGEM,5,4)=CN.SITUACAO_FUNCIONAL
              AND CHAVE.CODIGO_CONVERSAO       ='POST'
              )X
            UNION ALL
            SELECT X.*
            FROM
              (SELECT X.DIA,
                CN.USA_ASSOC_CONT_ESC AS INTEGRADO,
                CN.CODIGO_EMPRESA,
                CN.TIPO_CONTRATO,
                X.CODIGO_CONTRATO,
                X.CODIGO_PROPRIO,
                X.ESCALA,
                X.HORA_INICIO,
                X.HORA_FIM,
                CHAVE.DADO_DESTINO AS CHAVAE_INTEGRACAO,
                X.DATA_DADOS
              FROM
                (SELECT 'PENULTIMO'   AS DIA,
                  LPAD(replace(CARGA.BM,'-',''),15,0) AS CODIGO_CONTRATO,
                  CARGA.CODPROPRIO    AS CODIGO_PROPRIO,
                  CARGA.ESCALA ,
                  CARGA.HORAINIC AS HORA_INICIO,
                  CARGA.HORAFIM  AS HORA_FIM,
                  CARGA.DATA_DADOS
                FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA carga
                WHERE TRUNC(CARGA.DATA_DADOS)=
                  (SELECT MAX(TRUNC(AUX.DATA_DADOS))
                  FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA AUX
                  WHERE TRUNC(AUX.DATA_DADOS) <
                    (SELECT MAX(TRUNC(AUXX.DATA_DADOS))
                    FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA AUXX
             --      WHERE trunc(AUXX.DATA_DADOS)<='07/12/2021'
                    )
                  )
                )X
              LEFT OUTER JOIN
                (SELECT *
                FROM ARTERH.RHPESS_CONTRATO CN
                WHERE CN.ANO_MES_REFERENCIA=
                  (SELECT MAX(AUX.ANO_MES_REFERENCIA)
                  FROM ARTERH.RHPESS_CONTRATO AUX
                  WHERE AUX.CODIGO      =CN.CODIGO
                  AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA
                  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO
                  )
                )CN
              ON CN.CODIGO         =X.CODIGO_CONTRATO
              AND CN.CODIGO_EMPRESA='0001'
              AND CN.TIPO_CONTRATO ='0001'
              LEFT OUTER JOIN ARTERH.RHINTE_ED_IT_CONV CHAVE
              ON SUBSTR(CHAVE.DADO_ORIGEM,0,4) =CN.CODIGO_EMPRESA
              AND SUBSTR(CHAVE.DADO_ORIGEM,5,4)=CN.SITUACAO_FUNCIONAL
              AND CHAVE.CODIGO_CONVERSAO       ='POST'
              )X
            )X
          ORDER BY X.CODIGO_CONTRATO,
            X.DIA,
            X.DATA_DADOS
          )X
        WHERE ORDEM_BM=1
        )X1
      )X
    WHERE ( (NOVO               ='NOVO_CADASTRO')
    OR (X.ALTEROU_CODIGO_PROPRIO='CODIGO_PROPRIO_MUDOU'
    AND X.INTEGRADO_SEGUINTE    ='S')
    OR (X.ALTEROU_ESCALA        ='ESCALA_MUDOU'
    AND X.INTEGRADO_SEGUINTE    ='S')
    OR (X.ALTEROU_HORA_INICIO   ='HORA_INICIO_MUDOU'
    AND X.INTEGRADO_SEGUINTE    ='S')
    OR (X.ALTEROU_HORA_FIM      ='HORA_FIM_MUDOU'
    AND X.INTEGRADO_SEGUINTE    ='S') )
  ---  AND X.CODIGO_CONTRATO='000000000800221'
    )
    LOOP
    EMPRESA_ESCALA_DE:=NULL;
            ESCALA_DE:=NULL;
            DATA_INI:=NULL;
            DT_ULT_CONTRATO:=NULL;
            COD_PROPRIO:=NULL;
            COD_ARTE:=NULL;
            COD_CERCA:=NULL;
      CONT :=CONT+1;
      DBMS_Output.PUT_LINE(CONT||'--------------------------------------------------------------------------------------');
      DBMS_Output.PUT_LINE('DADOS: '||C1.CODIGO_CONTRATO||'---'||C1.ESCALA||'-----'||C1.HORA_INICIO||'----'||C1.HORA_FIM);
      IF ((C1.ALTEROU_ESCALA='ESCALA_MUDOU')OR (C1.ALTEROU_HORA_INICIO='HORA_INICIO_MUDOU') OR (C1.ALTEROU_HORA_FIM='HORA_FIM_MUDOU') OR(C1.NOVO='NOVO_CADASTRO')) THEN
        BEGIN
          SELECT DE.ARTERH_CODIGO_EMPRESA,
            DE.ARTERH_CODIGO_ESCALA,
            calend.dia,
            dia_ciclo
          INTO EMPRESA_ESCALA_DE ,
            ESCALA_DE ,
            DATA_INI,
            DIA_COMECO_CICLO
          FROM PONTO_ELETRONICO.SMSP_DE_PARA_ESCALA_HORARIO DE
          LEFT OUTER JOIN PONTO_ELETRONICO.SMSP_CALENDARIO_ESCALA CALEND
          ON CALEND.SICOOR_TIPO_ESCALA=DE.SICOOR_TIPO_ESCALA
          LEFT OUTER JOIN ARTERH.RHPONT_ESCALA EL 
          ON EL.CODIGO=DE.ARTERH_CODIGO_ESCALA
          AND EL.CODIGO_EMPRESA=DE.ARTERH_CODIGO_EMPRESA
          WHERE CALEND.DIA           =trunc(sysdate)
          AND DE.SICOOR_ESCALA        =C1.ESCALA
          AND DE.SICOOR_HORAINIC      =C1.HORA_INICIO
          AND DE.SICOOR_HORAFIM       = C1.HORA_FIM
          GROUP BY DE.ARTERH_CODIGO_EMPRESA, DE.ARTERH_CODIGO_ESCALA, dia_ciclo, calend.dia;
        EXCEPTION
        WHEN NO_DATA_FOUND THEN
         EMPRESA_ESCALA_DE:=NULL;
            ESCALA_DE:=NULL;
            DATA_INI:=NULL;
          DBMS_Output.PUT_LINE('VALOR_NAO_ENCONTRADO PARA ESCALA INFORMADA');
          DBMS_Output.PUT_LINE('ERRO NA ESCALA: '||C1.CODIGO_CONTRATO||' ESCALA_SICOOR: '||C1.ESCALA||' HORA INICIO: '||C1.HORA_INICIO||' HORA FIM: '||C1.HORA_FIM);
        END;
        IF EMPRESA_ESCALA_DE IS NOT NULL AND ESCALA_DE IS NOT NULL AND DATA_INI IS NOT NULL THEN
          DBMS_Output.PUT_LINE('DADOS ESCALA: '||EMPRESA_ESCALA_DE||'----'||ESCALA_DE||'-----'||DATA_INI);
          DBMS_Output.PUT_LINE('DADOS ENCONTRATOS E ATUALIZAR ESCALA E CONTRATO');

          HIST_CERTO:=ACERTO_HISTORICO_ESCALA(C1.CODIGO_EMPRESA,C1.TIPO_CONTRATO,C1.CODIGO_CONTRATO);

           DBMS_Output.PUT_LINE('RETORNO HISTORIOCO ESCALA '||CASE WHEN HIST_CERTO='S' THEN' CERTO' END);



          IF HIST_CERTO='S' THEN 
           FOR APG1 IN (
           SELECT P.CODIGO_EMPRESA,
          P.TIPO_CONTRATO,
          P.CODIGO_CONTRATO,
          P.DT_INICIO_TROCA,
          P.DT_FIM_TROCA,
          P.COD_ESCALA
        FROM ARTERH.RHPONT_ALT_ESCALA P
        WHERE ALTER_DEFINITIVA='S'
        AND P.CODIGO_CONTRATO=C1.CODIGO_CONTRATO
        AND P.TIPO_CONTRATO=C1.TIPO_CONTRATO
        AND P.CODIGO_EMPRESA=C1.CODIGO_EMPRESA
        AND TRUNC(P.DT_INICIO_TROCA)=TO_DATE(''||DATA_INI||'','DD/MM/YYYY')
          )LOOP
          DELETE FROM ARTERH.RHPONT_ALT_ESCALA WHERE CODIGO_CONTRATO=APG1.CODIGO_CONTRATO AND TIPO_CONTRATO=APG1.TIPO_CONTRATO AND CODIGO_EMPRESA=APG1.CODIGO_EMPRESA AND COD_ESCALA= APG1.COD_ESCALA AND DT_INICIO_TROCA=APG1.DT_INICIO_TROCA;
          COMMIT;
          END LOOP;

          DBMS_Output.PUT_LINE('UPDATE ARTERH.RHPONT_ALT_ESCALA P SET P.DT_FIM_TROCA     =TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'')-1,  P.DT_ULT_ALTER_USUA  =SYSDATE,  P.LOGIN_USUARIO      =''INTEGRACAO_SICOOR''WHERE PALTER_DEFINITIVA=''S'' AND P.DT_INICIO_TROCA  =  (SELECT MAX (AUX.DT_INICIO_TROCA)  FROM ARTERH.RHPONT_ALT_ESCALA AUX  WHERE AUX.CODIGO_CONTRATO=P.CODIGO_CONTRATO  AND AUX.TIPO_CONTRATO    =P.TIPO_CONTRATO   AND AUX.CODIGO_EMPRESA   =P.CODIGO_EMPRESA   AND AUX.ALTER_DEFINITIVA =''S'')AND P.CODIGO_CONTRATO=LPAD('''||C1.CODIGO_CONTRATO||''',15,0)AND P.TIPO_CONTRATO  ='''||C1.TIPO_CONTRATO||'''AND P.CODIGO_EMPRESA ='''||C1.CODIGO_EMPRESA||''';');
        --UPDATE PARA FECHAR O ULTIMO HISTORICO DE ESCALA
        UPDATE ARTERH.RHPONT_ALT_ESCALA P SET P.DT_FIM_TROCA     =TO_DATE(''||DATA_INI||'','DD/MM/YYYY')-1,  P.DT_ULT_ALTER_USUA  =SYSDATE,  P.LOGIN_USUARIO      ='INTEGRACAO_SICOOR'WHERE P.ALTER_DEFINITIVA='S' AND P.DT_INICIO_TROCA  =  (SELECT MAX (AUX.DT_INICIO_TROCA)  FROM ARTERH.RHPONT_ALT_ESCALA AUX  WHERE AUX.CODIGO_CONTRATO=P.CODIGO_CONTRATO  AND AUX.TIPO_CONTRATO    =P.TIPO_CONTRATO   AND AUX.CODIGO_EMPRESA   =P.CODIGO_EMPRESA   AND AUX.ALTER_DEFINITIVA ='S')AND P.CODIGO_CONTRATO=LPAD(''||C1.CODIGO_CONTRATO||'',15,0)AND P.TIPO_CONTRATO  =''||C1.TIPO_CONTRATO||''AND P.CODIGO_EMPRESA =''||C1.CODIGO_EMPRESA||'';
        COMMIT;
        --INSERT DA NOVA ESCALA COM DATA DE INICIO DO CALENDARIO GUARDA
        dbms_output.put_line('INSERT INTO RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, DT_ULT_ALTER_USUA, LOGIN_USUARIO)values('''|| C1.CODIGO_EMPRESA ||''', '''|| C1.TIPO_CONTRATO ||''', '''|| C1.CODIGO_CONTRATO ||''', TO_DATE('''||DATA_INI||''',''DD/MM/YYYY''), '''|| ESCALA_DE ||''',''S'', sysdate, ''INTEGRACAO_SICOOR''); COMMIT;');
            INSERT INTO ARTERH.RHPONT_ALT_ESCALA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DT_INICIO_TROCA, COD_ESCALA, ALTER_DEFINITIVA, origem_programacao,DT_ULT_ALTER_USUA, LOGIN_USUARIO,c_livre_valor01)values(''|| C1.CODIGO_EMPRESA ||'', ''|| C1.TIPO_CONTRATO ||'', ''|| C1.CODIGO_CONTRATO ||'', TO_DATE(''||DATA_INI||'','DD/MM/YYYY'), ''|| ESCALA_DE ||'','S', '8888',sysdate, 'INTEGRACAO_SICOOR',DIA_COMECO_CICLO); 
            COMMIT;



          END IF;

          SELECT CN.ANO_MES_REFERENCIA
          INTO DT_ULT_CONTRATO
          FROM ARTERH.RHPESS_CONTRATO CN
          WHERE CN.ANO_MES_REFERENCIA=
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM ARTERH.RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO      =CN.CODIGO
            AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO
            )
          AND CN.CODIGO         =C1.CODIGO_CONTRATO
          AND CN.CODIGO_EMPRESA ='0001'
          AND CN.TIPO_CONTRATO  ='0001';


          IF FECHAMENTO_SISTEMA ='N' AND DT_ULT_CONTRATO>vDATA_SISTEMA THEN
            vATUALIZAR         :='N';
            DBMS_Output.PUT_LINE('ERRO CONTRATO FUTURO');
           /* DBMS_Output.PUT_LINE('ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_SISTEMA: '||FECHAMENTO_SISTEMA);
            DBMS_Output.PUT_LINE('UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
         */ ELSIF FECHAMENTO_SISTEMA='S' AND DT_ULT_CONTRATO>vDATA_SISTEMA THEN
           vATUALIZAR         :='N';
            DBMS_Output.PUT_LINE('ERRO CONTRATO FUTURO');
           /* DBMS_Output.PUT_LINE('ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_SISTEMA: '||FECHAMENTO_SISTEMA);
            DBMS_Output.PUT_LINE('UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
          */ELSIF FECHAMENTO_SISTEMA='N' AND DT_ULT_CONTRATO<vDATA_SISTEMA THEN
            vATUALIZAR           :='N';
            DBMS_Output.PUT_LINE('INSERT CONTRATO COM DATA DO SISTEMA '||'ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_FECHAMENTO_SISTEMA: '||FECHAMENTO_SISTEMA);

            INSERT INTO RHPESS_CONTRATO
            SELECT RHPESS_CONTRATO.CODIGO_EMPRESA,
            RHPESS_CONTRATO.TIPO_CONTRATO,
            RHPESS_CONTRATO.CODIGO,
            RHPESS_CONTRATO.CODIGO_PESSOA,
            RHPESS_CONTRATO.NOME,
            RHPESS_CONTRATO.REGISTRO,
            RHPESS_CONTRATO.NUMERO_ARQUIVO,
            RHPESS_CONTRATO.SITUACAO_FUNCIONAL,
            RHPESS_CONTRATO.SITUACAO_CONTRATO,
            RHPESS_CONTRATO.STATUS_CONTRATO,
            RHPESS_CONTRATO.DATA_ADMISSAO,
            RHPESS_CONTRATO.MOTIVO_ADMISSAO,
            RHPESS_CONTRATO.MOTIVO_DEMISSAO,
            RHPESS_CONTRATO.TIPO_PAGAMENTO,
            RHPESS_CONTRATO.TIPO_SALARIO,
            RHPESS_CONTRATO.VINCULO,
            RHPESS_CONTRATO.FORMA_PROVIMENTO,
            RHPESS_CONTRATO.COD_LOCAL1,
            RHPESS_CONTRATO.COD_LOCAL2,
            RHPESS_CONTRATO.COD_LOCAL3,
            RHPESS_CONTRATO.COD_LOCAL4,
            RHPESS_CONTRATO.COD_LOCAL5,
            RHPESS_CONTRATO.COD_LOCAL6,
            RHPESS_CONTRATO.DT_ULT_ALT_LOC,
            RHPESS_CONTRATO.COD_UNIDADE1,
            RHPESS_CONTRATO.COD_UNIDADE2,
            RHPESS_CONTRATO.COD_UNIDADE3,
            RHPESS_CONTRATO.COD_UNIDADE4,
            RHPESS_CONTRATO.COD_UNIDADE5,
            RHPESS_CONTRATO.COD_UNIDADE6,
            RHPESS_CONTRATO.DT_ULT_ALT_UNID,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB1,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB2,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB3,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB4,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB5,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB6,
            RHPESS_CONTRATO.DT_ULT_ALT_CONT,
            RHPESS_CONTRATO.COD_CUSTO_GERENC1,
            RHPESS_CONTRATO.COD_CUSTO_GERENC2,
            RHPESS_CONTRATO.COD_CUSTO_GERENC3,
            RHPESS_CONTRATO.COD_CUSTO_GERENC4,
            RHPESS_CONTRATO.COD_CUSTO_GERENC5,
            RHPESS_CONTRATO.COD_CUSTO_GERENC6,
            RHPESS_CONTRATO.DT_ULT_ALT_GER,
            RHPESS_CONTRATO.SALARIO_PAGTO,
            RHPESS_CONTRATO.COD_CARGO_PAGTO,
            RHPESS_CONTRATO.NIVEL_CARGO_PAGTO,
            RHPESS_CONTRATO.COD_CARGO_EFETIVO,
            RHPESS_CONTRATO.NIVEL_CARGO_EFETIV,
            RHPESS_CONTRATO.DT_ULT_CARGO_EFET,
            RHPESS_CONTRATO.COD_CARGO_COMISS,
            RHPESS_CONTRATO.NIVEL_CARGO_COMISS,
            RHPESS_CONTRATO.DT_ULT_CARGO_COM,
            RHPESS_CONTRATO.COD_CARGO_AMPAR,
            RHPESS_CONTRATO.NIVEL_CARGO_AMPAR,
            RHPESS_CONTRATO.DT_ULT_CARGO_AMPAR,
            RHPESS_CONTRATO.CODIGO_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_FUNCAO,
            RHPESS_CONTRATO.COD_ESPECIALIDADE,
            RHPESS_CONTRATO.DT_ULT_ESPEC,
            RHPESS_CONTRATO.CODIGO_VAGA,
            RHPESS_CONTRATO.DT_ULT_VAGA,
            RHPESS_CONTRATO.AREA_ATUACAO,
            RHPESS_CONTRATO.CATEG_PROFISSIONAL,
            RHPESS_CONTRATO.CODIGO_ESCALA,
            RHPESS_CONTRATO.REGISTRO_PONTO,
            RHPESS_CONTRATO.DT_ULT_ESCALA,
            RHPESS_CONTRATO.CODIGO_BANCO_CC,
            RHPESS_CONTRATO.CONTA_CORRENTE,
            RHPESS_CONTRATO.CODIGO_BANCO_FGTS,
            RHPESS_CONTRATO.CONTA_FGTS,
            RHPESS_CONTRATO.DATA_OPCAO_FGTS,
            RHPESS_CONTRATO.DATA_RETROACAO,
            RHPESS_CONTRATO.DATA_RETRATACAO,
            RHPESS_CONTRATO.COD_SINDICATO,
            RHPESS_CONTRATO.NIVEL_SINDICATO,
            RHPESS_CONTRATO.DT_ULT_SINDICATO,
            RHPESS_CONTRATO.DESC_CONTRIB_SIND,
            RHPESS_CONTRATO.SINDICALIZADO,
            RHPESS_CONTRATO.INSCRICAO_INSS,
            RHPESS_CONTRATO.COD_MOVIMENTACAO,
            RHPESS_CONTRATO.DATA_TRANSF_ENTRAD,
            RHPESS_CONTRATO.DATA_PRI_ADMISSAO,
            RHPESS_CONTRATO.DATA_REINTEGRACAO,
            RHPESS_CONTRATO.DATA_EFETIVO_EXERC,
            RHPESS_CONTRATO.DATA_POSSE,
            RHPESS_CONTRATO.DATA_NOMEACAO,
            RHPESS_CONTRATO.DATA_INICIO_ESTAB,
            RHPESS_CONTRATO.DATA_FIM_ESTAB,
            RHPESS_CONTRATO.DT_FIM_CONTR_EXP,
            RHPESS_CONTRATO.DT_FIM_CONTR_DETER,
            RHPESS_CONTRATO.DATA_FIM_RENOV_EXP,
            RHPESS_CONTRATO.DATA_AV_PREVIO,
            RHPESS_CONTRATO.DATA_RESCISAO,
            RHPESS_CONTRATO.CAUSA_RESCISAO,
            RHPESS_CONTRATO.DATA_INIC_AFAST,
            RHPESS_CONTRATO.DATA_FIM_AFAST,
            RHPESS_CONTRATO.NRO_MESES_AFAST,
            RHPESS_CONTRATO.CTRL_VERBAS,
            RHPESS_CONTRATO.FORMA_PAGAMENTO,
            RHPESS_CONTRATO.DATA_BASE_FERIAS,
            RHPESS_CONTRATO.DATA_INIC_GOZO,
            RHPESS_CONTRATO.DATA_FIM_GOZO,
            RHPESS_CONTRATO.DEPENDENTES_SF,
            RHPESS_CONTRATO.DEPENDENTES_IRRF,
            RHPESS_CONTRATO.COD_PROCURADOR,
            RHPESS_CONTRATO.DATA_PAGTO_CALCULO,
            RHPESS_CONTRATO.DATA_PAGTO_ADIANT,
            RHPESS_CONTRATO.DATA_PAGTO_FERIAS,
            RHPESS_CONTRATO.DATA_PAGTO_13SAL,
            RHPESS_CONTRATO.DATA_PAGTO_RESCISA,
            RHPESS_CONTRATO.SAL_CONT_EFETIVO,
            RHPESS_CONTRATO.DT_ULT_SAL_C_EFET,
            RHPESS_CONTRATO.SAL_CONT_COMISSION,
            RHPESS_CONTRATO.DT_ULT_SAL_C_COM,
            RHPESS_CONTRATO.SAL_CONT_AMPAR,
            RHPESS_CONTRATO.DT_ULT_SAL_C_AMP,
            RHPESS_CONTRATO.SAL_AUX_EFETIVO,
            RHPESS_CONTRATO.DT_ULT_SAL_A_EFET,
            RHPESS_CONTRATO.SAL_AUX_COMISSION,
            RHPESS_CONTRATO.DT_ULT_SAL_A_COM,
            RHPESS_CONTRATO.SAL_AUX_AMPAR,
            RHPESS_CONTRATO.DT_ULT_SAL_A_AMP,
            RHPESS_CONTRATO.C_LIVRE_SELEC01,
            RHPESS_CONTRATO.C_LIVRE_SELEC02,
            RHPESS_CONTRATO.C_LIVRE_SELEC03,
            RHPESS_CONTRATO.C_LIVRE_SELEC04,
            RHPESS_CONTRATO.C_LIVRE_SELEC05,
            RHPESS_CONTRATO.C_LIVRE_SELEC06,
            RHPESS_CONTRATO.C_LIVRE_SELEC07,
            RHPESS_CONTRATO.C_LIVRE_SELEC08,
            RHPESS_CONTRATO.C_LIVRE_SELEC09,
            RHPESS_CONTRATO.C_LIVRE_SELEC10,
            RHPESS_CONTRATO.C_LIVRE_SELEC11,
            RHPESS_CONTRATO.C_LIVRE_SELEC12,
            RHPESS_CONTRATO.C_LIVRE_SELEC13,
            RHPESS_CONTRATO.C_LIVRE_SELEC14,
            RHPESS_CONTRATO.C_LIVRE_SELEC15,
            RHPESS_CONTRATO.C_LIVRE_SELEC36,
            RHPESS_CONTRATO.C_LIVRE_SELEC37,
            RHPESS_CONTRATO.C_LIVRE_SELEC38,
            RHPESS_CONTRATO.C_LIVRE_SELEC39,
            RHPESS_CONTRATO.C_LIVRE_SELEC40,
            RHPESS_CONTRATO.C_LIVRE_VALOR16,
            RHPESS_CONTRATO.C_LIVRE_VALOR17,
            RHPESS_CONTRATO.C_LIVRE_VALOR18,
            RHPESS_CONTRATO.C_LIVRE_VALOR19,
            RHPESS_CONTRATO.C_LIVRE_VALOR20,
            RHPESS_CONTRATO.C_LIVRE_VALOR21,
            RHPESS_CONTRATO.C_LIVRE_VALOR22,
            RHPESS_CONTRATO.C_LIVRE_VALOR23,
            RHPESS_CONTRATO.C_LIVRE_DESCR24,
            RHPESS_CONTRATO.C_LIVRE_DESCR25,
            RHPESS_CONTRATO.C_LIVRE_DESCR26,
            RHPESS_CONTRATO.C_LIVRE_DESCR27,
            RHPESS_CONTRATO.C_LIVRE_DATA28,
            RHPESS_CONTRATO.C_LIVRE_DATA29,
            RHPESS_CONTRATO.C_LIVRE_DATA30,
            RHPESS_CONTRATO.C_LIVRE_DATA31,
            RHPESS_CONTRATO.C_LIVRE_DATA32,
            RHPESS_CONTRATO.C_LIVRE_DATA33,
            RHPESS_CONTRATO.C_LIVRE_DATA34,
            RHPESS_CONTRATO.C_LIVRE_DATA35,
            RHPESS_CONTRATO.C_LIVRE_OPCAO41,
            RHPESS_CONTRATO.C_LIVRE_OPCAO42,
            RHPESS_CONTRATO.C_LIVRE_OPCAO43,
            RHPESS_CONTRATO.C_LIVRE_OPCAO44,
            RHPESS_CONTRATO.C_LIVRE_OPCAO45,
            RHPESS_CONTRATO.C_LIVRE_OPCAO46,
            RHPESS_CONTRATO.C_LIVRE_OPCAO47,
            RHPESS_CONTRATO.C_LIVRE_OPCAO48,
            RHPESS_CONTRATO.INDIC_ALTERAC1,
            RHPESS_CONTRATO.INDIC_ALTERAC2,
            RHPESS_CONTRATO.INDIC_ALTERAC3,
            RHPESS_CONTRATO.INDIC_ALTERAC4,
            RHPESS_CONTRATO.INDIC_ALTERAC5,
            RHPESS_CONTRATO.TEXTO_ASSOCIADO,
            'INTEGRACAO_SICOOR',
            SYSDATE,
            RHPESS_CONTRATO.TELEFONE,
            TO_CHAR(TO_DATE('01'
            ||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
            RHPESS_CONTRATO.DATA_APOSENTA_FGTS,
            RHPESS_CONTRATO.REABILITADO,
            RHPESS_CONTRATO.C_LIVRE_VALOR49,
            RHPESS_CONTRATO.C_LIVRE_VALOR50,
            RHPESS_CONTRATO.C_LIVRE_VALOR51,
            RHPESS_CONTRATO.C_LIVRE_VALOR52,
            RHPESS_CONTRATO.C_LIVRE_VALOR53,
            RHPESS_CONTRATO.C_LIVRE_VALOR54,
            RHPESS_CONTRATO.C_LIVRE_VALOR55,
            RHPESS_CONTRATO.C_LIVRE_VALOR56,
            RHPESS_CONTRATO.C_LIVRE_DATA57,
            RHPESS_CONTRATO.C_LIVRE_DATA58,
            RHPESS_CONTRATO.C_LIVRE_DATA59,
            RHPESS_CONTRATO.C_LIVRE_DATA60,
            RHPESS_CONTRATO.C_LIVRE_DATA61,
            RHPESS_CONTRATO.C_LIVRE_DATA62,
            RHPESS_CONTRATO.C_LIVRE_DATA63,
            RHPESS_CONTRATO.C_LIVRE_DATA64,
            RHPESS_CONTRATO.C_LIVRE_OPCAO65,
            RHPESS_CONTRATO.C_LIVRE_OPCAO66,
            RHPESS_CONTRATO.C_LIVRE_OPCAO67,
            RHPESS_CONTRATO.C_LIVRE_OPCAO68,
            RHPESS_CONTRATO.INDIC_ALTERAC6,
            RHPESS_CONTRATO.CLASSE_CONT_INSS,
            RHPESS_CONTRATO.E_MAIL,
            RHPESS_CONTRATO.USA_ASSOC_CONT_ESC,
            RHPESS_CONTRATO.CLASSIFICACAO_CAND,
            RHPESS_CONTRATO.NUMERO_EDITAL,
            RHPESS_CONTRATO.TIPO_AGRUP_UNID,
            RHPESS_CONTRATO.TIPO_AGRUP_CONT,
            RHPESS_CONTRATO.TIPO_AGRUP_CGER,
            RHPESS_CONTRATO.TIPO_AGRUP_LOTA,
            RHPESS_CONTRATO.NOME_ACESSO,
            RHPESS_CONTRATO.CODIGO_SOLICITACAO,
            RHPESS_CONTRATO.ID_CONTR_FORN,
            RHPESS_CONTRATO.FUNC_COMP_EMPR_AV,
            RHPESS_CONTRATO.DT_MOLESTIA_GRAVE,
            RHPESS_CONTRATO.SAL_CONT_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_SAL_C_FUN,
            RHPESS_CONTRATO.SAL_AUX_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_SAL_A_FUN,
            RHPESS_CONTRATO.DATA_PROJ_AV_PREV,
            RHPESS_CONTRATO.DT_PROJ_AFAST_ESOCIAL,
            RHPESS_CONTRATO.TP_AVISO_PREVIO_ESOCIAL,
            RHPESS_CONTRATO.TP_CONTA_BANCARIA,
            RHPESS_CONTRATO.DT_PROC_ESOCIAL,
            RHPESS_CONTRATO.DT_ALTER_ESOCIAL,
            RHPESS_CONTRATO.DT_CANC_AVISO_PREVIO,
            RHPESS_CONTRATO.MOT_CANC_AV_PREV_ESOCIAL,
            RHPESS_CONTRATO.DESC_SAL_VARIAVEL,
            RHPESS_CONTRATO.MOTIVO_CONTRATACAO,
            RHPESS_CONTRATO.CPF_TRAB_SUBSTITUIDO,
            RHPESS_CONTRATO.MATRIC_TRAB_SUBSTITUIDO,
            RHPESS_CONTRATO.IND_SEGURO_DESEMPREGO,
            RHPESS_CONTRATO.DT_GERACAO_CAGED,
            RHPESS_CONTRATO.OBS_RESCISAO,
            RHPESS_CONTRATO.DT_FIM_QUARENTENA,
            RHPESS_CONTRATO.CNPJ_EMPRESA_SUCESSORA,
            RHPESS_CONTRATO.JUST_CONTR_ESOCIAL,
            RHPESS_CONTRATO.TP_INCL_CONTR_ESOCIAL,
            RHPESS_CONTRATO.INFO_COTA_ESOCIAL,
            RHPESS_CONTRATO.CLAUSULA_ASSEC,
            RHPESS_CONTRATO.DT_ALTERACAO_CONTR,
            RHPESS_CONTRATO.DT_EFEITO_ALTER_CONTR,
            RHPESS_CONTRATO.DESC_ALTER_CONTR,
            RHPESS_CONTRATO.IND_CUMPR_PARC_AV,
            RHPESS_CONTRATO.CODIGO_CONTR_ANTERIOR,
            RHPESS_CONTRATO.CPF_ANTERIOR,
            RHPESS_CONTRATO.DATA_ALTER_CPF,
            RHPESS_CONTRATO.OBS_ALTER_CPF,
            RHPESS_CONTRATO.TEM_ALTER_CPF,
            RHPESS_CONTRATO.INFO_COTA_RACA,
            RHPESS_CONTRATO.MATRICULA_ESOCIAL ,
            RHPESS_CONTRATO.CONSELHO_REGIONAL, --NOVO V.22.3.1
            RHPESS_CONTRATO.INSCRICAO_CONSELHO,--NOVO V.22.3.1
            RHPESS_CONTRATO.UF_CONSELHO        --NOVO V.22.3.1
            ,
            RHPESS_CONTRATO.COD_CARREIRA--a partir de 26/4/21 V.23.2.2
            ,
            RHPESS_CONTRATO.COD_EIXO--a partir de 26/4/21 V.23.2.2
            ,
            RHPESS_CONTRATO.COD_NIVEL--a partir de 26/4/21 V.23.2.2
            , RHPESS_CONTRATO.IND_REMUN --EM 16/3/23 Versao 25.2.1
            ,IND_PDV
            FROM RHPESS_CONTRATO
            WHERE RHPESS_CONTRATO.ANO_MES_REFERENCIA=
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA=RHPESS_CONTRATO.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO   =RHPESS_CONTRATO.TIPO_CONTRATO
            AND AUX.CODIGO          =RHPESS_CONTRATO.CODIGO
            )
            --AND RHPESS_CONTRATO.DATA_RESCISAO IS NULL
            AND RHPESS_CONTRATO.CODIGO=''
            ||C1.CODIGO_CONTRATO
            ||''
            AND RHPESS_CONTRATO.CODIGO_EMPRESA=''
            ||C1.CODIGO_EMPRESA
            ||''
            AND RHPESS_CONTRATO.TIPO_CONTRATO=''
            ||C1.TIPO_CONTRATO
            ||'';
                     COMMIT;
            INSERT INTO RHPESS_CONTRATO_AUX X
            SELECT CODIGO_EMPRESA,
            TIPO_CONTRATO,
            CODIGO,
            TO_CHAR(TO_DATE('01'
            ||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
            'INTEGRACAO_SICOOR' AS LOGIN_USUARIO,
            sysdate DT_ULT_ALTER_USUA,
            C_LIVRE_AUX_SELEC01,
            C_LIVRE_AUX_SELEC02,
            C_LIVRE_AUX_SELEC03,
            C_LIVRE_AUX_SELEC04,
            C_LIVRE_AUX_SELEC05,
            C_LIVRE_AUX_SELEC06,
            C_LIVRE_AUX_SELEC07,
            C_LIVRE_AUX_SELEC08,
            C_LIVRE_AUX_SELEC09,
            C_LIVRE_AUX_SELEC10,
            C_LIVRE_AUX_SELEC11,
            C_LIVRE_AUX_SELEC12,
            C_LIVRE_AUX_SELEC13,
            C_LIVRE_AUX_SELEC14,
            C_LIVRE_AUX_SELEC15,
            C_LIVRE_AUX_SELEC16,
            C_LIVRE_AUX_SELEC17,
            C_LIVRE_AUX_SELEC18,
            C_LIVRE_AUX_SELEC19,
            C_LIVRE_AUX_SELEC20,
            C_LIVRE_AUX_VALOR01,
            C_LIVRE_AUX_VALOR02,
            C_LIVRE_AUX_VALOR03,
            C_LIVRE_AUX_VALOR04,
            C_LIVRE_AUX_VALOR05,
            C_LIVRE_AUX_VALOR06,
            C_LIVRE_AUX_VALOR07,
            C_LIVRE_AUX_VALOR08,
            C_LIVRE_AUX_VALOR09,
            C_LIVRE_AUX_VALOR10,
            C_LIVRE_AUX_VALOR11,
            C_LIVRE_AUX_VALOR12,
            C_LIVRE_AUX_VALOR13,
            C_LIVRE_AUX_VALOR14,
            C_LIVRE_AUX_VALOR15,
            C_LIVRE_AUX_VALOR16,
            C_LIVRE_AUX_VALOR17,
            C_LIVRE_AUX_VALOR18,
            C_LIVRE_AUX_VALOR19,
            C_LIVRE_AUX_VALOR20,
            C_LIVRE_AUX_DATA01,
            C_LIVRE_AUX_DATA02,
            C_LIVRE_AUX_DATA03,
            C_LIVRE_AUX_DATA04,
            C_LIVRE_AUX_DATA05,
            C_LIVRE_AUX_DATA06,
            C_LIVRE_AUX_DATA07,
            C_LIVRE_AUX_DATA08,
            C_LIVRE_AUX_DATA09,
            C_LIVRE_AUX_DATA10,
            C_LIVRE_AUX_DATA11,
            C_LIVRE_AUX_DATA12,
            C_LIVRE_AUX_DATA13,
            C_LIVRE_AUX_DATA14,
            C_LIVRE_AUX_DATA15,
            C_LIVRE_AUX_DATA16,
            C_LIVRE_AUX_DATA17,
            C_LIVRE_AUX_DATA18,
            C_LIVRE_AUX_DATA19,
            C_LIVRE_AUX_DATA20,
            C_LIVRE_AUX_OPCAO01,
            C_LIVRE_AUX_OPCAO02,
            C_LIVRE_AUX_OPCAO03,
            C_LIVRE_AUX_OPCAO04,
            C_LIVRE_AUX_OPCAO05,
            C_LIVRE_AUX_OPCAO06,
            C_LIVRE_AUX_OPCAO07,
            C_LIVRE_AUX_OPCAO08,
            C_LIVRE_AUX_OPCAO09,
            C_LIVRE_AUX_OPCAO10,
            C_LIVRE_AUX_OPCAO11,
            C_LIVRE_AUX_OPCAO12,
            C_LIVRE_AUX_OPCAO13,
            C_LIVRE_AUX_OPCAO14,
            C_LIVRE_AUX_OPCAO15,
            C_LIVRE_AUX_OPCAO16,
            C_LIVRE_AUX_OPCAO17,
            C_LIVRE_AUX_OPCAO18,
            C_LIVRE_AUX_OPCAO19,
            C_LIVRE_AUX_OPCAO20,
            C_LIVRE_AUX_DESCR01,
            C_LIVRE_AUX_DESCR02,
            C_LIVRE_AUX_DESCR03,
            C_LIVRE_AUX_DESCR04,
            C_LIVRE_AUX_DESCR05,
            C_LIVRE_AUX_DESCR06,
            C_LIVRE_AUX_DESCR07,
            C_LIVRE_AUX_DESCR08,
            C_LIVRE_AUX_DESCR09,
            C_LIVRE_AUX_DESCR10,
            C_LIVRE_AUX_DESCR11,
            C_LIVRE_AUX_DESCR12,
            C_LIVRE_AUX_DESCR13,
            C_LIVRE_AUX_DESCR14,
            C_LIVRE_AUX_DESCR15,
            C_LIVRE_AUX_DESCR16,
            C_LIVRE_AUX_DESCR17,
            C_LIVRE_AUX_DESCR18,
            C_LIVRE_AUX_DESCR19,
            C_LIVRE_AUX_DESCR20,
            C_LIVRE_AUX_TEXTO01,
            C_LIVRE_AUX_TEXTO02,
            C_LIVRE_AUX_TEXTO03,
            C_LIVRE_AUX_TEXTO04,
            C_LIVRE_AUX_TEXTO05,
            C_LIVRE_AUX_TEXTO06,
            C_LIVRE_AUX_TEXTO07,
            C_LIVRE_AUX_TEXTO08,
            C_LIVRE_AUX_TEXTO09,
            C_LIVRE_AUX_TEXTO10,
            C_LIVRE_AUX_TEXTO11,
            C_LIVRE_AUX_TEXTO12,
            C_LIVRE_AUX_TEXTO13,
            C_LIVRE_AUX_TEXTO14,
            C_LIVRE_AUX_TEXTO15,
            C_LIVRE_AUX_TEXTO16,
            C_LIVRE_AUX_TEXTO17,
            C_LIVRE_AUX_TEXTO18,
            C_LIVRE_AUX_TEXTO19,
            C_LIVRE_AUX_TEXTO20
            FROM ARTERH.RHPESS_CONTRATO_AUX X
            WHERE X.codigo_empresa   = C1.CODIGO_EMPRESA
            AND X.tipo_contrato      = C1.TIPO_CONTRATO
            AND X.CODIGO             = C1.CODIGO_CONTRATO
            AND X.ano_mes_referencia =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM ARTERH.RHPESS_CONTRATO_AUX AUX
            WHERE X.codigo_empresa = AUX.CODIGO_EMPRESA
            AND X.tipo_contrato    = AUX.TIPO_CONTRATO
            AND X.CODIGO           = AUX.CODIGO
            );
            COMMIT;

            DBMS_Output.PUT_LINE('UPDATE DEPOIS DO INSET DO NOVO CONTRATO ===='||'UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
          UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA=''||ESCALA_DE||'',DT_ULT_ESCALA=TO_DATE(''||DATA_INI||'','DD/MM/YYYY') WHERE CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||'' 
          AND TIPO_CONTRATO=''||C1.TIPO_CONTRATO||'' AND CODIGO=''||C1.CODIGO_CONTRATO||'' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX 
          WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);
          COMMIT;


          ELSIF FECHAMENTO_SISTEMA='S' AND DT_ULT_CONTRATO<vDATA_SISTEMA THEN
            vATUALIZAR           :='N';
            DBMS_Output.PUT_LINE('INSERT CONTRATO COM DATA DO SISTEMA '||'ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_FECHAMENTO_SISTEMA: '||FECHAMENTO_SISTEMA);

            INSERT INTO RHPESS_CONTRATO
            SELECT RHPESS_CONTRATO.CODIGO_EMPRESA,
            RHPESS_CONTRATO.TIPO_CONTRATO,
            RHPESS_CONTRATO.CODIGO,
            RHPESS_CONTRATO.CODIGO_PESSOA,
            RHPESS_CONTRATO.NOME,
            RHPESS_CONTRATO.REGISTRO,
            RHPESS_CONTRATO.NUMERO_ARQUIVO,
            RHPESS_CONTRATO.SITUACAO_FUNCIONAL,
            RHPESS_CONTRATO.SITUACAO_CONTRATO,
            RHPESS_CONTRATO.STATUS_CONTRATO,
            RHPESS_CONTRATO.DATA_ADMISSAO,
            RHPESS_CONTRATO.MOTIVO_ADMISSAO,
            RHPESS_CONTRATO.MOTIVO_DEMISSAO,
            RHPESS_CONTRATO.TIPO_PAGAMENTO,
            RHPESS_CONTRATO.TIPO_SALARIO,
            RHPESS_CONTRATO.VINCULO,
            RHPESS_CONTRATO.FORMA_PROVIMENTO,
            RHPESS_CONTRATO.COD_LOCAL1,
            RHPESS_CONTRATO.COD_LOCAL2,
            RHPESS_CONTRATO.COD_LOCAL3,
            RHPESS_CONTRATO.COD_LOCAL4,
            RHPESS_CONTRATO.COD_LOCAL5,
            RHPESS_CONTRATO.COD_LOCAL6,
            RHPESS_CONTRATO.DT_ULT_ALT_LOC,
            RHPESS_CONTRATO.COD_UNIDADE1,
            RHPESS_CONTRATO.COD_UNIDADE2,
            RHPESS_CONTRATO.COD_UNIDADE3,
            RHPESS_CONTRATO.COD_UNIDADE4,
            RHPESS_CONTRATO.COD_UNIDADE5,
            RHPESS_CONTRATO.COD_UNIDADE6,
            RHPESS_CONTRATO.DT_ULT_ALT_UNID,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB1,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB2,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB3,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB4,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB5,
            RHPESS_CONTRATO.COD_CUSTO_CONTAB6,
            RHPESS_CONTRATO.DT_ULT_ALT_CONT,
            RHPESS_CONTRATO.COD_CUSTO_GERENC1,
            RHPESS_CONTRATO.COD_CUSTO_GERENC2,
            RHPESS_CONTRATO.COD_CUSTO_GERENC3,
            RHPESS_CONTRATO.COD_CUSTO_GERENC4,
            RHPESS_CONTRATO.COD_CUSTO_GERENC5,
            RHPESS_CONTRATO.COD_CUSTO_GERENC6,
            RHPESS_CONTRATO.DT_ULT_ALT_GER,
            RHPESS_CONTRATO.SALARIO_PAGTO,
            RHPESS_CONTRATO.COD_CARGO_PAGTO,
            RHPESS_CONTRATO.NIVEL_CARGO_PAGTO,
            RHPESS_CONTRATO.COD_CARGO_EFETIVO,
            RHPESS_CONTRATO.NIVEL_CARGO_EFETIV,
            RHPESS_CONTRATO.DT_ULT_CARGO_EFET,
            RHPESS_CONTRATO.COD_CARGO_COMISS,
            RHPESS_CONTRATO.NIVEL_CARGO_COMISS,
            RHPESS_CONTRATO.DT_ULT_CARGO_COM,
            RHPESS_CONTRATO.COD_CARGO_AMPAR,
            RHPESS_CONTRATO.NIVEL_CARGO_AMPAR,
            RHPESS_CONTRATO.DT_ULT_CARGO_AMPAR,
            RHPESS_CONTRATO.CODIGO_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_FUNCAO,
            RHPESS_CONTRATO.COD_ESPECIALIDADE,
            RHPESS_CONTRATO.DT_ULT_ESPEC,
            RHPESS_CONTRATO.CODIGO_VAGA,
            RHPESS_CONTRATO.DT_ULT_VAGA,
            RHPESS_CONTRATO.AREA_ATUACAO,
            RHPESS_CONTRATO.CATEG_PROFISSIONAL,
            RHPESS_CONTRATO.CODIGO_ESCALA,
            RHPESS_CONTRATO.REGISTRO_PONTO,
            RHPESS_CONTRATO.DT_ULT_ESCALA,
            RHPESS_CONTRATO.CODIGO_BANCO_CC,
            RHPESS_CONTRATO.CONTA_CORRENTE,
            RHPESS_CONTRATO.CODIGO_BANCO_FGTS,
            RHPESS_CONTRATO.CONTA_FGTS,
            RHPESS_CONTRATO.DATA_OPCAO_FGTS,
            RHPESS_CONTRATO.DATA_RETROACAO,
            RHPESS_CONTRATO.DATA_RETRATACAO,
            RHPESS_CONTRATO.COD_SINDICATO,
            RHPESS_CONTRATO.NIVEL_SINDICATO,
            RHPESS_CONTRATO.DT_ULT_SINDICATO,
            RHPESS_CONTRATO.DESC_CONTRIB_SIND,
            RHPESS_CONTRATO.SINDICALIZADO,
            RHPESS_CONTRATO.INSCRICAO_INSS,
            RHPESS_CONTRATO.COD_MOVIMENTACAO,
            RHPESS_CONTRATO.DATA_TRANSF_ENTRAD,
            RHPESS_CONTRATO.DATA_PRI_ADMISSAO,
            RHPESS_CONTRATO.DATA_REINTEGRACAO,
            RHPESS_CONTRATO.DATA_EFETIVO_EXERC,
            RHPESS_CONTRATO.DATA_POSSE,
            RHPESS_CONTRATO.DATA_NOMEACAO,
            RHPESS_CONTRATO.DATA_INICIO_ESTAB,
            RHPESS_CONTRATO.DATA_FIM_ESTAB,
            RHPESS_CONTRATO.DT_FIM_CONTR_EXP,
            RHPESS_CONTRATO.DT_FIM_CONTR_DETER,
            RHPESS_CONTRATO.DATA_FIM_RENOV_EXP,
            RHPESS_CONTRATO.DATA_AV_PREVIO,
            RHPESS_CONTRATO.DATA_RESCISAO,
            RHPESS_CONTRATO.CAUSA_RESCISAO,
            RHPESS_CONTRATO.DATA_INIC_AFAST,
            RHPESS_CONTRATO.DATA_FIM_AFAST,
            RHPESS_CONTRATO.NRO_MESES_AFAST,
            RHPESS_CONTRATO.CTRL_VERBAS,
            RHPESS_CONTRATO.FORMA_PAGAMENTO,
            RHPESS_CONTRATO.DATA_BASE_FERIAS,
            RHPESS_CONTRATO.DATA_INIC_GOZO,
            RHPESS_CONTRATO.DATA_FIM_GOZO,
            RHPESS_CONTRATO.DEPENDENTES_SF,
            RHPESS_CONTRATO.DEPENDENTES_IRRF,
            RHPESS_CONTRATO.COD_PROCURADOR,
            RHPESS_CONTRATO.DATA_PAGTO_CALCULO,
            RHPESS_CONTRATO.DATA_PAGTO_ADIANT,
            RHPESS_CONTRATO.DATA_PAGTO_FERIAS,
            RHPESS_CONTRATO.DATA_PAGTO_13SAL,
            RHPESS_CONTRATO.DATA_PAGTO_RESCISA,
            RHPESS_CONTRATO.SAL_CONT_EFETIVO,
            RHPESS_CONTRATO.DT_ULT_SAL_C_EFET,
            RHPESS_CONTRATO.SAL_CONT_COMISSION,
            RHPESS_CONTRATO.DT_ULT_SAL_C_COM,
            RHPESS_CONTRATO.SAL_CONT_AMPAR,
            RHPESS_CONTRATO.DT_ULT_SAL_C_AMP,
            RHPESS_CONTRATO.SAL_AUX_EFETIVO,
            RHPESS_CONTRATO.DT_ULT_SAL_A_EFET,
            RHPESS_CONTRATO.SAL_AUX_COMISSION,
            RHPESS_CONTRATO.DT_ULT_SAL_A_COM,
            RHPESS_CONTRATO.SAL_AUX_AMPAR,
            RHPESS_CONTRATO.DT_ULT_SAL_A_AMP,
            RHPESS_CONTRATO.C_LIVRE_SELEC01,
            RHPESS_CONTRATO.C_LIVRE_SELEC02,
            RHPESS_CONTRATO.C_LIVRE_SELEC03,
            RHPESS_CONTRATO.C_LIVRE_SELEC04,
            RHPESS_CONTRATO.C_LIVRE_SELEC05,
            RHPESS_CONTRATO.C_LIVRE_SELEC06,
            RHPESS_CONTRATO.C_LIVRE_SELEC07,
            RHPESS_CONTRATO.C_LIVRE_SELEC08,
            RHPESS_CONTRATO.C_LIVRE_SELEC09,
            RHPESS_CONTRATO.C_LIVRE_SELEC10,
            RHPESS_CONTRATO.C_LIVRE_SELEC11,
            RHPESS_CONTRATO.C_LIVRE_SELEC12,
            RHPESS_CONTRATO.C_LIVRE_SELEC13,
            RHPESS_CONTRATO.C_LIVRE_SELEC14,
            RHPESS_CONTRATO.C_LIVRE_SELEC15,
            RHPESS_CONTRATO.C_LIVRE_SELEC36,
            RHPESS_CONTRATO.C_LIVRE_SELEC37,
            RHPESS_CONTRATO.C_LIVRE_SELEC38,
            RHPESS_CONTRATO.C_LIVRE_SELEC39,
            RHPESS_CONTRATO.C_LIVRE_SELEC40,
            RHPESS_CONTRATO.C_LIVRE_VALOR16,
            RHPESS_CONTRATO.C_LIVRE_VALOR17,
            RHPESS_CONTRATO.C_LIVRE_VALOR18,
            RHPESS_CONTRATO.C_LIVRE_VALOR19,
            RHPESS_CONTRATO.C_LIVRE_VALOR20,
            RHPESS_CONTRATO.C_LIVRE_VALOR21,
            RHPESS_CONTRATO.C_LIVRE_VALOR22,
            RHPESS_CONTRATO.C_LIVRE_VALOR23,
            RHPESS_CONTRATO.C_LIVRE_DESCR24,
            RHPESS_CONTRATO.C_LIVRE_DESCR25,
            RHPESS_CONTRATO.C_LIVRE_DESCR26,
            RHPESS_CONTRATO.C_LIVRE_DESCR27,
            RHPESS_CONTRATO.C_LIVRE_DATA28,
            RHPESS_CONTRATO.C_LIVRE_DATA29,
            RHPESS_CONTRATO.C_LIVRE_DATA30,
            RHPESS_CONTRATO.C_LIVRE_DATA31,
            RHPESS_CONTRATO.C_LIVRE_DATA32,
            RHPESS_CONTRATO.C_LIVRE_DATA33,
            RHPESS_CONTRATO.C_LIVRE_DATA34,
            RHPESS_CONTRATO.C_LIVRE_DATA35,
            RHPESS_CONTRATO.C_LIVRE_OPCAO41,
            RHPESS_CONTRATO.C_LIVRE_OPCAO42,
            RHPESS_CONTRATO.C_LIVRE_OPCAO43,
            RHPESS_CONTRATO.C_LIVRE_OPCAO44,
            RHPESS_CONTRATO.C_LIVRE_OPCAO45,
            RHPESS_CONTRATO.C_LIVRE_OPCAO46,
            RHPESS_CONTRATO.C_LIVRE_OPCAO47,
            RHPESS_CONTRATO.C_LIVRE_OPCAO48,
            RHPESS_CONTRATO.INDIC_ALTERAC1,
            RHPESS_CONTRATO.INDIC_ALTERAC2,
            RHPESS_CONTRATO.INDIC_ALTERAC3,
            RHPESS_CONTRATO.INDIC_ALTERAC4,
            RHPESS_CONTRATO.INDIC_ALTERAC5,
            RHPESS_CONTRATO.TEXTO_ASSOCIADO,
            'INTEGRACAO_SICOOR',
            SYSDATE,
            RHPESS_CONTRATO.TELEFONE,
            TO_CHAR(TO_DATE('01'
            ||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
            RHPESS_CONTRATO.DATA_APOSENTA_FGTS,
            RHPESS_CONTRATO.REABILITADO,
            RHPESS_CONTRATO.C_LIVRE_VALOR49,
            RHPESS_CONTRATO.C_LIVRE_VALOR50,
            RHPESS_CONTRATO.C_LIVRE_VALOR51,
            RHPESS_CONTRATO.C_LIVRE_VALOR52,
            RHPESS_CONTRATO.C_LIVRE_VALOR53,
            RHPESS_CONTRATO.C_LIVRE_VALOR54,
            RHPESS_CONTRATO.C_LIVRE_VALOR55,
            RHPESS_CONTRATO.C_LIVRE_VALOR56,
            RHPESS_CONTRATO.C_LIVRE_DATA57,
            RHPESS_CONTRATO.C_LIVRE_DATA58,
            RHPESS_CONTRATO.C_LIVRE_DATA59,
            RHPESS_CONTRATO.C_LIVRE_DATA60,
            RHPESS_CONTRATO.C_LIVRE_DATA61,
            RHPESS_CONTRATO.C_LIVRE_DATA62,
            RHPESS_CONTRATO.C_LIVRE_DATA63,
            RHPESS_CONTRATO.C_LIVRE_DATA64,
            RHPESS_CONTRATO.C_LIVRE_OPCAO65,
            RHPESS_CONTRATO.C_LIVRE_OPCAO66,
            RHPESS_CONTRATO.C_LIVRE_OPCAO67,
            RHPESS_CONTRATO.C_LIVRE_OPCAO68,
            RHPESS_CONTRATO.INDIC_ALTERAC6,
            RHPESS_CONTRATO.CLASSE_CONT_INSS,
            RHPESS_CONTRATO.E_MAIL,
            RHPESS_CONTRATO.USA_ASSOC_CONT_ESC,
            RHPESS_CONTRATO.CLASSIFICACAO_CAND,
            RHPESS_CONTRATO.NUMERO_EDITAL,
            RHPESS_CONTRATO.TIPO_AGRUP_UNID,
            RHPESS_CONTRATO.TIPO_AGRUP_CONT,
            RHPESS_CONTRATO.TIPO_AGRUP_CGER,
            RHPESS_CONTRATO.TIPO_AGRUP_LOTA,
            RHPESS_CONTRATO.NOME_ACESSO,
            RHPESS_CONTRATO.CODIGO_SOLICITACAO,
            RHPESS_CONTRATO.ID_CONTR_FORN,
            RHPESS_CONTRATO.FUNC_COMP_EMPR_AV,
            RHPESS_CONTRATO.DT_MOLESTIA_GRAVE,
            RHPESS_CONTRATO.SAL_CONT_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_SAL_C_FUN,
            RHPESS_CONTRATO.SAL_AUX_FUNCAO,
            RHPESS_CONTRATO.DT_ULT_SAL_A_FUN,
            RHPESS_CONTRATO.DATA_PROJ_AV_PREV,
            RHPESS_CONTRATO.DT_PROJ_AFAST_ESOCIAL,
            RHPESS_CONTRATO.TP_AVISO_PREVIO_ESOCIAL,
            RHPESS_CONTRATO.TP_CONTA_BANCARIA,
            RHPESS_CONTRATO.DT_PROC_ESOCIAL,
            RHPESS_CONTRATO.DT_ALTER_ESOCIAL,
            RHPESS_CONTRATO.DT_CANC_AVISO_PREVIO,
            RHPESS_CONTRATO.MOT_CANC_AV_PREV_ESOCIAL,
            RHPESS_CONTRATO.DESC_SAL_VARIAVEL,
            RHPESS_CONTRATO.MOTIVO_CONTRATACAO,
            RHPESS_CONTRATO.CPF_TRAB_SUBSTITUIDO,
            RHPESS_CONTRATO.MATRIC_TRAB_SUBSTITUIDO,
            RHPESS_CONTRATO.IND_SEGURO_DESEMPREGO,
            RHPESS_CONTRATO.DT_GERACAO_CAGED,
            RHPESS_CONTRATO.OBS_RESCISAO,
            RHPESS_CONTRATO.DT_FIM_QUARENTENA,
            RHPESS_CONTRATO.CNPJ_EMPRESA_SUCESSORA,
            RHPESS_CONTRATO.JUST_CONTR_ESOCIAL,
            RHPESS_CONTRATO.TP_INCL_CONTR_ESOCIAL,
            RHPESS_CONTRATO.INFO_COTA_ESOCIAL,
            RHPESS_CONTRATO.CLAUSULA_ASSEC,
            RHPESS_CONTRATO.DT_ALTERACAO_CONTR,
            RHPESS_CONTRATO.DT_EFEITO_ALTER_CONTR,
            RHPESS_CONTRATO.DESC_ALTER_CONTR,
            RHPESS_CONTRATO.IND_CUMPR_PARC_AV,
            RHPESS_CONTRATO.CODIGO_CONTR_ANTERIOR,
            RHPESS_CONTRATO.CPF_ANTERIOR,
            RHPESS_CONTRATO.DATA_ALTER_CPF,
            RHPESS_CONTRATO.OBS_ALTER_CPF,
            RHPESS_CONTRATO.TEM_ALTER_CPF,
            RHPESS_CONTRATO.INFO_COTA_RACA,
            RHPESS_CONTRATO.MATRICULA_ESOCIAL ,
            RHPESS_CONTRATO.CONSELHO_REGIONAL, --NOVO V.22.3.1
            RHPESS_CONTRATO.INSCRICAO_CONSELHO,--NOVO V.22.3.1
            RHPESS_CONTRATO.UF_CONSELHO        --NOVO V.22.3.1
            ,
            RHPESS_CONTRATO.COD_CARREIRA--a partir de 26/4/21 V.23.2.2
            ,
            RHPESS_CONTRATO.COD_EIXO--a partir de 26/4/21 V.23.2.2
            ,
            RHPESS_CONTRATO.COD_NIVEL--a partir de 26/4/21 V.23.2.2
            , RHPESS_CONTRATO.IND_REMUN --EM 16/3/23 Versao 25.2.1
            , RHPESS_CONTRATO.IND_PDV --EM 30/1/24 Versao 26.1.1
            FROM RHPESS_CONTRATO
            WHERE RHPESS_CONTRATO.ANO_MES_REFERENCIA=
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA=RHPESS_CONTRATO.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO   =RHPESS_CONTRATO.TIPO_CONTRATO
            AND AUX.CODIGO          =RHPESS_CONTRATO.CODIGO
            )
            --AND RHPESS_CONTRATO.DATA_RESCISAO IS NULL
            AND RHPESS_CONTRATO.CODIGO=''
            ||C1.CODIGO_CONTRATO
            ||''
            AND RHPESS_CONTRATO.CODIGO_EMPRESA=''
            ||C1.CODIGO_EMPRESA
            ||''
            AND RHPESS_CONTRATO.TIPO_CONTRATO=''
            ||C1.TIPO_CONTRATO
            ||'';
            COMMIT;
            INSERT INTO RHPESS_CONTRATO_AUX X
            SELECT CODIGO_EMPRESA,
            TIPO_CONTRATO,
            CODIGO,
            TO_CHAR(TO_DATE('01'
            ||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YY')) ANO_MES_REFERENCIA,
            'INTEGRACAO_SICOOR' AS LOGIN_USUARIO,
            sysdate DT_ULT_ALTER_USUA,
            C_LIVRE_AUX_SELEC01,
            C_LIVRE_AUX_SELEC02,
            C_LIVRE_AUX_SELEC03,
            C_LIVRE_AUX_SELEC04,
            C_LIVRE_AUX_SELEC05,
            C_LIVRE_AUX_SELEC06,
            C_LIVRE_AUX_SELEC07,
            C_LIVRE_AUX_SELEC08,
            C_LIVRE_AUX_SELEC09,
            C_LIVRE_AUX_SELEC10,
            C_LIVRE_AUX_SELEC11,
            C_LIVRE_AUX_SELEC12,
            C_LIVRE_AUX_SELEC13,
            C_LIVRE_AUX_SELEC14,
            C_LIVRE_AUX_SELEC15,
            C_LIVRE_AUX_SELEC16,
            C_LIVRE_AUX_SELEC17,
            C_LIVRE_AUX_SELEC18,
            C_LIVRE_AUX_SELEC19,
            C_LIVRE_AUX_SELEC20,
            C_LIVRE_AUX_VALOR01,
            C_LIVRE_AUX_VALOR02,
            C_LIVRE_AUX_VALOR03,
            C_LIVRE_AUX_VALOR04,
            C_LIVRE_AUX_VALOR05,
            C_LIVRE_AUX_VALOR06,
            C_LIVRE_AUX_VALOR07,
            C_LIVRE_AUX_VALOR08,
            C_LIVRE_AUX_VALOR09,
            C_LIVRE_AUX_VALOR10,
            C_LIVRE_AUX_VALOR11,
            C_LIVRE_AUX_VALOR12,
            C_LIVRE_AUX_VALOR13,
            C_LIVRE_AUX_VALOR14,
            C_LIVRE_AUX_VALOR15,
            C_LIVRE_AUX_VALOR16,
            C_LIVRE_AUX_VALOR17,
            C_LIVRE_AUX_VALOR18,
            C_LIVRE_AUX_VALOR19,
            C_LIVRE_AUX_VALOR20,
            C_LIVRE_AUX_DATA01,
            C_LIVRE_AUX_DATA02,
            C_LIVRE_AUX_DATA03,
            C_LIVRE_AUX_DATA04,
            C_LIVRE_AUX_DATA05,
            C_LIVRE_AUX_DATA06,
            C_LIVRE_AUX_DATA07,
            C_LIVRE_AUX_DATA08,
            C_LIVRE_AUX_DATA09,
            C_LIVRE_AUX_DATA10,
            C_LIVRE_AUX_DATA11,
            C_LIVRE_AUX_DATA12,
            C_LIVRE_AUX_DATA13,
            C_LIVRE_AUX_DATA14,
            C_LIVRE_AUX_DATA15,
            C_LIVRE_AUX_DATA16,
            C_LIVRE_AUX_DATA17,
            C_LIVRE_AUX_DATA18,
            C_LIVRE_AUX_DATA19,
            C_LIVRE_AUX_DATA20,
            C_LIVRE_AUX_OPCAO01,
            C_LIVRE_AUX_OPCAO02,
            C_LIVRE_AUX_OPCAO03,
            C_LIVRE_AUX_OPCAO04,
            C_LIVRE_AUX_OPCAO05,
            C_LIVRE_AUX_OPCAO06,
            C_LIVRE_AUX_OPCAO07,
            C_LIVRE_AUX_OPCAO08,
            C_LIVRE_AUX_OPCAO09,
            C_LIVRE_AUX_OPCAO10,
            C_LIVRE_AUX_OPCAO11,
            C_LIVRE_AUX_OPCAO12,
            C_LIVRE_AUX_OPCAO13,
            C_LIVRE_AUX_OPCAO14,
            C_LIVRE_AUX_OPCAO15,
            C_LIVRE_AUX_OPCAO16,
            C_LIVRE_AUX_OPCAO17,
            C_LIVRE_AUX_OPCAO18,
            C_LIVRE_AUX_OPCAO19,
            C_LIVRE_AUX_OPCAO20,
            C_LIVRE_AUX_DESCR01,
            C_LIVRE_AUX_DESCR02,
            C_LIVRE_AUX_DESCR03,
            C_LIVRE_AUX_DESCR04,
            C_LIVRE_AUX_DESCR05,
            C_LIVRE_AUX_DESCR06,
            C_LIVRE_AUX_DESCR07,
            C_LIVRE_AUX_DESCR08,
            C_LIVRE_AUX_DESCR09,
            C_LIVRE_AUX_DESCR10,
            C_LIVRE_AUX_DESCR11,
            C_LIVRE_AUX_DESCR12,
            C_LIVRE_AUX_DESCR13,
            C_LIVRE_AUX_DESCR14,
            C_LIVRE_AUX_DESCR15,
            C_LIVRE_AUX_DESCR16,
            C_LIVRE_AUX_DESCR17,
            C_LIVRE_AUX_DESCR18,
            C_LIVRE_AUX_DESCR19,
            C_LIVRE_AUX_DESCR20,
            C_LIVRE_AUX_TEXTO01,
            C_LIVRE_AUX_TEXTO02,
            C_LIVRE_AUX_TEXTO03,
            C_LIVRE_AUX_TEXTO04,
            C_LIVRE_AUX_TEXTO05,
            C_LIVRE_AUX_TEXTO06,
            C_LIVRE_AUX_TEXTO07,
            C_LIVRE_AUX_TEXTO08,
            C_LIVRE_AUX_TEXTO09,
            C_LIVRE_AUX_TEXTO10,
            C_LIVRE_AUX_TEXTO11,
            C_LIVRE_AUX_TEXTO12,
            C_LIVRE_AUX_TEXTO13,
            C_LIVRE_AUX_TEXTO14,
            C_LIVRE_AUX_TEXTO15,
            C_LIVRE_AUX_TEXTO16,
            C_LIVRE_AUX_TEXTO17,
            C_LIVRE_AUX_TEXTO18,
            C_LIVRE_AUX_TEXTO19,
            C_LIVRE_AUX_TEXTO20
            FROM RHPESS_CONTRATO_AUX X
            WHERE X.codigo_empresa   = C1.CODIGO_EMPRESA
            AND X.tipo_contrato      = C1.TIPO_CONTRATO
            AND X.CODIGO             = C1.CODIGO_CONTRATO
            AND X.ano_mes_referencia =
            (SELECT MAX(AUX.ANO_MES_REFERENCIA)
            FROM RHPESS_CONTRATO_aux AUX
            WHERE X.codigo_empresa = AUX.CODIGO_EMPRESA
            AND X.tipo_contrato    = AUX.TIPO_CONTRATO
            AND X.CODIGO           = AUX.CODIGO
            );
            COMMIT;

            DBMS_Output.PUT_LINE('UPDATE DEPOIS DO INSET DO NOVO CONTRATO ===='||'UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
         UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA=''||ESCALA_DE||'',DT_ULT_ESCALA=TO_DATE(''||DATA_INI||'','DD/MM/YYYY') WHERE CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||'' 
         AND TIPO_CONTRATO=''||C1.TIPO_CONTRATO||'' AND CODIGO=''||C1.CODIGO_CONTRATO||'' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX 
         WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);
         COMMIT;

         ELSIF FECHAMENTO_SISTEMA='N' AND DT_ULT_CONTRATO=vDATA_SISTEMA  THEN 
          vATUALIZAR:='S';
            DBMS_Output.PUT_LINE('ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_FECHAMENTO_SISTEMA: '||FECHAMENTO_SISTEMA);
            DBMS_Output.PUT_LINE('UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
          UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA=''||ESCALA_DE||'',DT_ULT_ESCALA=TO_DATE(''||DATA_INI||'','DD/MM/YYYY') WHERE CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||'' AND TIPO_CONTRATO=''||C1.TIPO_CONTRATO||'' 
          AND CODIGO=''||C1.CODIGO_CONTRATO||'' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);
          COMMIT;
          ELSIF FECHAMENTO_SISTEMA='S' AND DT_ULT_CONTRATO=vDATA_SISTEMA AND vDATA_SISTEMA>DATA_COMPARA THEN
          vATUALIZAR:='S';
           DBMS_Output.PUT_LINE('ATUALIZAR_CONTRATO :'|| vATUALIZAR||' DATA_ULT_CONTRATO: '||DT_ULT_CONTRATO||' DATA_SISTEMA: '||vDATA_SISTEMA||' STATUS_FECHAMENTO_SISTEMA: '||FECHAMENTO_SISTEMA);
            DBMS_Output.PUT_LINE('UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA='''||ESCALA_DE||''',DT_ULT_ESCALA=TO_DATE('''||DATA_INI||''',''DD/MM/YYYY'') WHERE CODIGO_EMPRESA='''||C1.CODIGO_EMPRESA||''' AND TIPO_CONTRATO='''||C1.TIPO_CONTRATO||''' AND CODIGO='''||C1.CODIGO_CONTRATO||''' AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);');
          UPDATE ARTERH.RHPESS_CONTRATO CN SET CODIGO_ESCALA=''||ESCALA_DE||'',DT_ULT_ESCALA=TO_DATE(''||DATA_INI||'','DD/MM/YYYY') WHERE CODIGO_EMPRESA=''||C1.CODIGO_EMPRESA||'' AND TIPO_CONTRATO=''||C1.TIPO_CONTRATO||'' AND CODIGO=''||C1.CODIGO_CONTRATO||'' 
          AND CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO=CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA  AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO);
          COMMIT;

          END IF;
        END IF;
      END IF;
      IF ( (C1.ALTEROU_CODIGO_PROPRIO='CODIGO_PROPRIO_MUDOU')OR (C1.NOVO='NOVO_CADASTRO')) THEN
        BEGIN
 select CASE WHEN ACAO='CERCA SIOM ' THEN CODIGO_ARTE ELSE COD_CERCA END AS CERCA into COD_CERCA from (
SELECT case when sm.codigo_arte  is null then 'CRIAR CERGA DADOS GEO' ELSE 'CERCA SIOM ' END AS ACAO,
sm.codigo_arte,RD.COD_GUARDA_MUNICIPAL AS PROPRIO,RD.cod_guarda_municipal AS COD_CERCA,rd.sigla_tipo_logradouro||' '||rd.nome_logradouro||' '||rd.numero_imovel as nome_cerca,
rd.latitude,
rd.longitude,
rd.faixa_rede FROM PONTO_ELETRONICO.smsp_carga_rede rd
left outer join  PONTO_ELETRONICO.arterh_siom SM 
on sm.id_endereco_corporativo=rd.cod_endereco_corporativo
AND TRUNC(SM.DATA_CARGA)=(SELECT MAX(trunc(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.arterh_siom AUX)
WHERE TRUNC(data_dados)=(SELECT MAX(trunc(AUX.data_dados)) FROM PONTO_ELETRONICO.smsp_carga_rede  AUX)

UNION ALL 
SELECT
case when sm.codigo_arte  is null then 'CRIAR CERGA DADOS GEO' ELSE 'CERCA SIOM ' END AS ACAO,
sm.codigo_arte,g.cod_guarda_municipal AS PROPRIO,RD.cod_guarda_municipal AS COD_CERCA,rd.sigla_tipo_logradouro||' '||rd.nome_logradouro||' '||rd.numero_imovel as nome_cerca,
rd.latitude,
rd.longitude,
rd.faixa_rede    FROM PONTO_ELETRONICO.smsp_local_g_guarda g
left outer join PONTO_ELETRONICO.smsp_carga_rede rd
on g.cod_referencia_endereco=rd.COD_GUARDA_MUNICIPAL
and TRUNC(rd.data_dados)=(SELECT MAX(trunc(AUX.data_dados)) FROM PONTO_ELETRONICO.smsp_carga_rede  AUX)
left outer join  PONTO_ELETRONICO.arterh_siom SM 
on sm.id_endereco_corporativo=rd.cod_endereco_corporativo
AND TRUNC(SM.DATA_CARGA)=(SELECT MAX(trunc(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.arterh_siom AUX)
WHERE trunc(g.DATA_CARGA)=(SELECT MAX(trunc(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.smsp_local_g_guarda AUX) 

)x
where x.PROPRIO=C1.CODIGO_PROPRIO
GROUP BY CASE WHEN ACAO='CERCA SIOM ' THEN CODIGO_ARTE ELSE COD_CERCA END ;
        EXCEPTION
        WHEN NO_DATA_FOUND THEN

            COD_CERCA:=NULL;




        END;
        IF COD_CERCA IS NOT NULL THEN
        /*  DBMS_Output.PUT_LINE('DADOS CERCA: '||COD_PROPRIO||'----'||COD_ARTE||'-----'||COD_CERCA);
          DBMS_Output.PUT_LINE('DADOS ENCONTRATOS E ATUALIZAR CERCA NO PONTO');
          DBMS_Output.PUT_LINE('INSERT INTO PONTO_ELETRONICO.SMARH_INT_CAD_PESS_CERCA(CODIGO_EMRPESA,AGRUPAMENTO_EMPRESA,TIPO_CONTRATO,CODIGO_CONTRATO,TIPO,CODIGO_LEGADO,DT_SAIU_ARTE)VALUES('''||C1.CODIGO_EMPrESA||''',''ADM DIRETA'','''||C1.TIPO_CONTRATO||''','''||C1.CODIGO_CONTRATO||''',''INCLUIR'','''||COD_CERCA||''',sysdate);');  
         */ INSERT INTO PONTO_ELETRONICO.SMARH_INT_CAD_PESS_CERCA(CODIGO_EMPRESA,AGRUPAMENTO_EMPRESA,TIPO_CONTRATO,CODIGO_CONTRATO,TIPO,CODIGO_LEGADO,DT_SAIU_ARTE
         ,CODIGO_INTEGRA_ARTE --NOVO 4/7/22
         )VALUES(''||C1.CODIGO_EMPrESA||'','ADM DIRETA',''||C1.TIPO_CONTRATO||'',''||C1.CODIGO_CONTRATO||'','INCLUIR',''||COD_CERCA||'',sysdate
         ,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
         );
        COMMIT;
        END IF;
      END IF;
    END LOOP;
  END;
END;