
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SMARHINT_AJUSTE_BASE" AS

  VULTIMOFECHAMENTOESPELHO DATE;
  VQTD_REG NUMBER;
  VQTD_REG2 NUMBER;
err_msg VARCHAR2(4000 BYTE);--NOVO 3/11/22

--INICIO--NOVO 3/11/22
PROCEDURE GRAVA_ERRO(PROCEDURE_ERRO IN VARCHAR2,COD_ERRO IN VARCHAR2, SQL_ERRO IN VARCHAR2) AS
BEGIN
INSERT INTO PONTO_ELETRONICO.SMARH_INT_LOG_INTEGRA_DIARIA(ID,PROCEDURE_ERRO,CODIGO_ERRO,DESCRICAO_ERRO) VALUES(PONTO_ELETRONICO.ID_SEQ_LOG_PONTO.NEXTVAL,PROCEDURE_ERRO,COD_ERRO,SQL_ERRO);
COMMIT;
END;


PROCEDURE GRAVA_SUCESSO(PROCEDURE_ERRO IN VARCHAR2,COD_ERRO IN VARCHAR2, SQL_ERRO IN VARCHAR2) AS
BEGIN
INSERT INTO PONTO_ELETRONICO.SMARH_INT_LOG_INTEGRA_DIARIA(ID,PROCEDURE_ERRO,CODIGO_ERRO,DESCRICAO_ERRO,VERIFICADO) VALUES(PONTO_ELETRONICO.ID_SEQ_LOG_PONTO.NEXTVAL,PROCEDURE_ERRO,COD_ERRO,SQL_ERRO,'S');
COMMIT;
END;
--FIM--NOVO 3/11/22

BEGIN 
 SELECT TO_DATE(DADO_ORIGEM,'DD/MM/YYYY')+1 INTO VULTIMOFECHAMENTOESPELHO
  FROM ARTERH.RHINTE_ED_IT_CONV CV
  WHERE CODIGO_CONVERSAO = 'FCPT'
        AND TO_DATE(DADO_ORIGEM, 'DD/MM/YYYY') = (
    SELECT MAX(TO_DATE(AUX.DADO_ORIGEM, 'DD/MM/YYYY'))
    FROM ARTERH.RHINTE_ED_IT_CONV AUX
    WHERE CV.CODIGO_CONVERSAO = AUX.CODIGO_CONVERSAO
  );


UPDATE PONTO_ELETRONICO.SMARH_INT_REPROCESSO_CONTRATO SET VERIFICADO='S' WHERE VERIFICADO='N';
/*limpar as vw antes de popular*/

UPDATE PONTO_ELETRONICO.SMARH_INT_PE_JUSTIFICATIVA_IF SET DT_ENVIADO_IFPONTO_SURICATO=SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO IS NULL;
COMMIT;
UPDATE PONTO_ELETRONICO.SMARH_INT_CAD_CERCA_DIGITAL SET DT_ENVIADO_IFPONTO_SURICATO=SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;
UPDATE PONTO_ELETRONICO.SMARH_INT_PE_CARGO_V2 set DT_ENVIADO_IFPONTO_SURICATO = SYSDATE where DT_ENVIADO_IFPONTO_SURICATO is  null;
COMMIT;
UPDATE PONTO_ELETRONICO.smarh_int_pe_escala_v2 SET DT_ENVIADO_IFPONTO_SURICATO= SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;
UPDATE PONTO_ELETRONICO.smarh_int_pe_jorn_escala_v2 SET DT_ENVIADO_IFPONTO_SURICATO= SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;
UPDATE PONTO_ELETRONICO.SMARH_INT_PE_JORNADA_V2 SET DT_ENVIADO_IFPONTO_SURICATO= SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;
update PONTO_ELETRONICO.smarh_int_pe_unidade_v2 set DT_ENVIADO_IFPONTO_SURICATO = SYSDATE   where DT_ENVIADO_IFPONTO_SURICATO is  null ;
COMMIT;
update PONTO_ELETRONICO.SMARH_INT_PONTO_DADOS_SERV_V10 set DT_ENVIADO_IFPONTO_SURICATO = SYSDATE   where DT_ENVIADO_IFPONTO_SURICATO is  null ;
COMMIT;
UPDATE PONTO_ELETRONICO.SMARH_INT_CAD_PESS_CERCA SET DT_ENVIADO_IFPONTO_SURICATO=SYSDATE WHERE DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;
UPDATE PONTO_ELETRONICO.SMARH_INT_PE_AFASTAMENTOS_V1  SET DT_ENVIADO_IFPONTO_SURICATO = SYSDATE where DT_ENVIADO_IFPONTO_SURICATO is null;
COMMIT;


BEGIN
/*PROCEDURE QUE GERAR OS REGISTRO NA VW DE SERVIDOR PARA RESOLVER O PROBLEMA DE 3 CONTRATOS ATIVOS NO IFPONTO(SMSA)*/
PONTO_ELETRONICO.PR_PONTO_REPROCESSO();
    err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_PONTO_REPROCESSO','000',err_msg);
  exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_PONTO_REPROCESSO',SQLCODE,err_msg);
END;

/*--INICIO--DESATIVADO EM 12/4/23
select count(1) INTO VQTD_REG FROM PONTO_ELETRONICO.IFPONTO_AFASTAMENTOS; --lado ifponto --52106 geralmente 25 mil --via php
IF VQTD_REG > 10000 THEN
BEGIN
--PROCEDURE QUE BUSCA TODOS OS AFASTAMENTOS NA DATA CORTE DO FECHAMENTO DOS ESPELHOS--
PONTO_ELETRONICO.PR_ACERTO_BASE_AFASTAMENTOS(VULTIMOFECHAMENTOESPELHO);
    err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_ACERTO_BASE_AFASTAMENTOS','000',err_msg);
  exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_ACERTO_BASE_AFASTAMENTOS',SQLCODE,err_msg);
END;
END IF;


select count(1) INTO VQTD_REG2 from PONTO_ELETRONICO.sugesp_bi_afastamentos; -- lado Arterh --via procedure PR_ACERTO_BASE_AFASTAMENTOS  23867 FERIAS
IF VQTD_REG2 > 10000 THEN
BEGIN
--GERA OS REGISTROS DAS FERIAS PARA AJUSTAR NA VW_FERIAS
PONTO_ELETRONICO.PR_GERA_DADOS_ACERTO_AFAST();
    err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_GERA_DADOS_ACERTO_AFAST','000',err_msg);
  exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_GERA_DADOS_ACERTO_AFAST',SQLCODE,err_msg);
END;
END IF;
*/--FIM--DESATIVADO EM 12/4/23

select count(1) INTO VQTD_REG FROM PONTO_ELETRONICO.SUGESP_INT_PE_IFPONTO; --82814 --via php
IF VQTD_REG > 90000 AND VQTD_REG < 120000 THEN --Kellysson em 9/10/23 aumentou de 80000 para 120000
BEGIN
/* PROCEDURE QUE COMPARA OS DADOS DO SERVIDOR ENTRE IFPONTO E ARTE E GERA NA VW SERVIDOR(OS DADOS COMPARADOS SAO: NOME, CARGO, HIERARQUIA, LOCAL DE TRABALHO, ESCALA, DIA DO CICLO DA ESCALA , DATA DE INICIO NA ESCALA E SE A PESSOA DEVERIA ESTA NO SISTEMA OU NAO*/
PONTO_ELETRONICO.PR_ACERTO_BASE();
    err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_ACERTO_BASE','000',err_msg);
  exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_ACERTO_BASE',SQLCODE,err_msg);
END;
END IF;

/*O COMANDO ABAIXO E PARA RETIRAR QUALQUER AJUSTE DO BM EM QUESTAO,
POIS A FUNDACAO NÃO RESOLE DE MANEIRA DEFINITICA A NOMEACAO DA NOVA RESPOSANVEL PELA FUNDACAO E ATE A PRESENTE DATA (20/04/2022) A RESPONSAVEL E SECRETARIA DE CULTURA DA EMPRESA 0001 o EMAIL COM O CASO TEM O ASSUNTO: Re: Sistema iFractal
 E A TATILA ESTA EM COPIA*/
delete FROM PONTO_ELETRONICO.smarh_int_ponto_dados_serv_v10 WHERE dt_enviado_ifponto_suricato IS NULL and codigo_contrato=lpad('6644',15,0);

--novo inicio em 6/6/22 Kellysson para evitar resetar senha conforme ocorreu em 1/6/22 limitando atualizacoes no contrato acima de 1000 registros no dia na rotina de reprocessamento da madrugada
select count(1) INTO VQTD_REG from  PONTO_ELETRONICO.SMARH_INT_PONTO_DADOS_SERV_V10 where DT_ENVIADO_IFPONTO_SURICATO is  null ;

IF VQTD_REG > 1000 THEN
update PONTO_ELETRONICO.SMARH_INT_PONTO_DADOS_SERV_V10 set DT_ENVIADO_IFPONTO_SURICATO = SYSDATE   where DT_ENVIADO_IFPONTO_SURICATO is  null ;
COMMIT;
END IF;
--novo fim em 6/6/22 Kellysson para evitar resetar senha conforme ocorreu em 1/6/22 limitando atualizacoes no contrato acima de 1000 registros no dia na rotina de reprocessamento da madrugada


select count(1) INTO VQTD_REG FROM PONTO_ELETRONICO.SUGES_BI_UNIDADE_IFPONTO; --3506 geralmente 1700 --via php
IF VQTD_REG > 1500  AND VQTD_REG < 2000 THEN --Kellysson em 9/10/23 aumentou de 1500 para 2000
BEGIN
--INICIO --NOVO EM 20/9/22 KELLYSSON MIGRANDO ESSA PROCEDURE DO JOB/PROCEDURE 1 PARA A 2, POIS DEPENDE DA FOTO DO IFPONTO VIA PHP/XAMP
PONTO_ELETRONICO.PR_AJUSTE_BASE_UNIDADE();
--FIM--NOVO EM 20/9/22 KELLYSSON MIGRANDO ESSA PROCEDURE DO JOB/PROCEDURE 1 PARA A 2, POIS DEPENDE DA FOTO DO IFPONTO VIA PHP/XAMP
    err_msg := SUBSTR('EXECUCAO_REALIZADA_COM_SUCESSO', 1, 4000);
              GRAVA_SUCESSO('PR_AJUSTE_BASE_UNIDADE','000',err_msg);
  exception
              when others then
               err_msg := SUBSTR(SQLERRM, 1, 4000);
              GRAVA_ERRO('PR_AJUSTE_BASE_UNIDADE',SQLCODE,err_msg);
END;
END IF;

/*--COMENTADO EM 6/7/23 AS 8H11 KELLYSSON
--kellysson em 30/11/22 até trocar escalas ciclicas da Prodabel no Arterh
update PONTO_ELETRONICO.SMARH_INT_PONTO_DADOS_SERV_V10 set DT_ENVIADO_IFPONTO_SURICATO = SYSDATE where DT_ENVIADO_IFPONTO_SURICATO is null and codigo_empresa = '0002' and LOCAL_GESTOR = 'PROCEDURE_ACERTO_BASE: AJUSTE_ESCALA'
and codigo_contrato in ('000000000005433','000000000006081','000000000006790','000000000007738','000000000008858','000000000010437','00000000001047X','000000000011409','000000000011670','000000000015250','000000000015633','000000000017423','000000000017784','000000000017873','000000000018039','000000000018136','000000000018152','000000000019116','000000000020025','000000000021285','000000000022796','000000000025221','000000000026333','00000000002683X','000000000026929','00000000002795X','000000000028176','000000000029873','000000000029881','000000000029903','000000000031981','000000000033593','000000000035618','000000000028176','000000000029881'
);commit;
*/--COMENTADO EM 6/7/23 AS 8H11 KELLYSSON

END;
