
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP1_EXTRAI_DBLINK" (ID_HORARIO IN VARCHAR2, DATA_INICIO IN DATE)
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_extrai_horarios_sge_b2.sql)
--Kellysson em 24/10/23 adicionou os campos: DAT_VALIDA_CANCELA e DT_CANCELAMENTO_USAR
--B2 em 31/8/23 ---NOVOS AJUSTES PARA DEMAIS ARQUIVOS DE/PARA
---Kellysson em 02/06/23 -- TABELA PEGAR DADOS SGE DIARIAMENTE VIA DBLINK
DECLARE 
vCONTADOR NUMBER;
vID_HORARIO VARCHAR2(20);
vDATA_INICIO DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vID_HORARIO := ID_HORARIO;
vDATA_INICIO := DATA_INICIO;

FOR C1 IN (

--SELECT X3.STATUS_ARQUIVO_ANTIGO_SGE, X3.SERA_INTEGRADO, COUNT(1)QTD_REGISTROS FROM (--PARA ANALISE ARQUIVOS DE/PARA EXTENSOES 2023

SELECT 
CASE WHEN X2.SITUACAO_JORNADA <> X2.SITUACAO_HORARIO THEN 'SIM' ELSE 'NAO' END DIFERE_SIT_HORARIO_JORNADA,
CASE 
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NULL     AND X2.DT_CANCELAMENTO_USAR IS NULL                                                                                                                                                                                             THEN 'EXTENSAO_NOVA_VALIDADA_CADASTRAR'
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NULL     AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') <= TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')                                                                                                    THEN 'EXTENSAO_NOVA_VALIDADA_CADASTRAR_JA_CANCELADA' --ADICIONADO EM 30/8/23 PARTE QUE ENTENDE COMO CANCELAMENTO APENAS DATAS MENORES OU IGUAIS DA FIM_JORNADA
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NULL     AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')  > TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')                                                                                                    THEN 'EXTENSAO_NOVA_VALIDADA_CADASTRAR_JA_REALIZADA' --ADICIONADO EM 30/8/23 DATAS CANCELAMENTO MAIORIES QUE FIM_JORNADA

WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NULL AND A.DT_CANCELAMENTO IS NULL                                                                                                  THEN 'EXTENSAO_ANTIGA_VALIDADA_JA_CADASTRADA_SEM_ALTERACOES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NULL AND A.DT_CANCELAMENTO IS NULL                                                                                                  THEN 'EXTENSAO_NOVA_VALIDADA_JA_CADASTRADA_SEM_ALTERACOES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(A.DT_CANCELAMENTO,'DD/MM/YYYY')   THEN 'EXTENSAO_ANTIGA_VALIDADA_JA_CANCELADA_SEM_ALTERACOES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(A.DT_CANCELAMENTO,'DD/MM/YYYY')   THEN 'EXTENSAO_NOVA_VALIDADA_JA_CANCELADA_SEM_ALTERACOES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') <> TO_DATE(A.DT_CANCELAMENTO,'DD/MM/YYYY')  THEN 'EXTENSAO_ANTIGA_VALIDADA_JA_CANCELADA_DATA_CANCELAMENTO_DIVERGENTES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NOT NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') <> TO_DATE(A.DT_CANCELAMENTO,'DD/MM/YYYY')  THEN 'EXTENSAO_NOVA_VALIDADA_JA_CANCELADA_DATA_CANCELAMENTO_DIVERGENTES'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') <= TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')         THEN 'EXTENSAO_ANTIGA_VALIDADA_CANCELAMENTO_RECENTE_CANCELAR_NO_ARTERH' --AJUSTADO 31/8/23--ADICIONADO EM 30/8/23 PARTE QUE ENTENDE COMO CANCELAMENTO APENAS DATAS MENORES OU IGUAIS DA FIM_JORNADA
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') <= TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')         THEN 'EXTENSAO_NOVA_VALIDADA_CANCELAMENTO_RECENTE_CANCELAR_NO_ARTERH' --AJUSTADO 31/8/23--ADICIONADO EM 30/8/23 PARTE QUE ENTENDE COMO CANCELAMENTO APENAS DATAS MENORES OU IGUAIS DA FIM_JORNADA
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')  > TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')         THEN 'EXTENSAO_ANTIGA_VALIDADA_CADASTRADA_JA_REALIZADA' --AJUSTADO 31/8/23 --ADICIONADO EM 30/8/23 DATAS CANCELAMENTO MAIORIES QUE FIM_JORNADA
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND A.DT_CANCELAMENTO IS NULL AND TO_DATE(X2.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')  > TO_DATE(X2.FIM_JORNADA,'DD/MM/YYYY')         THEN 'EXTENSAO_NOVA_VALIDADA_CADASTRADA_JA_REALIZADA' --AJUSTADO 31/8/23 --ADICIONADO EM 30/8/23 DATAS CANCELAMENTO MAIORIES QUE FIM_JORNADA
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO =  'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NULL AND A.DT_CANCELAMENTO IS NOT NULL                                                                                              THEN 'EXTENSAO_ANTIGA_VALIDADA_JA_CANCELADA_NO_ARTERH_MAS_AGORA_SEM_DATA_CANCELAMENTO_SGE_VERIFICAR'--AJUSTADO 31/8/23
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'SIM' AND A.ID_JORNADA IS NOT NULL AND A.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND X2.DT_CANCELAMENTO_USAR IS NULL AND A.DT_CANCELAMENTO IS NOT NULL                                                                                              THEN 'EXTENSAO_NOVA_VALIDADA_JA_CANCELADA_NO_ARTERH_MAS_AGORA_SEM_DATA_CANCELAMENTO_SGE_VERIFICAR'--AJUSTADO 31/8/23

WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'NAO' AND A.ID_JORNADA IS NULL                                                                                                                                                                                                                                 THEN 'EXTENSAO_NOVA_NAO_VALIDADA'
WHEN X2.TIPO_JORNADA = 3 AND X2.JORNADA_VALIDADA = 'NAO' AND A.ID_JORNADA IS NOT NULL                                                                                                                                                                                                                             THEN 'EXTENSAO_ANTIGA_NAO_VALIDADA'--AJUSTADO 31/8/23 
ELSE 'NAO_SE_APLICA'
END STATUS_ARQUIVO_ANTIGO_SGE,

CASE WHEN X2.CAMPOS_IMPORTANTES_INVALIDOS = 'SIM' OR X2.CAMPOS_OBRIGATORIOS_NULOS = 'SIM' OR X2.ERRO_CARGA_HORARIA = 'SIM' OR X2.ERRO_INTERVALO_TURNO = 'SIM' --comentado em 10/8 -- OR X2.SITUACAO_JORNADA LIKE '%_ERRO_%' 
OR X2.QTD_REG_MESMO_ID_HORARIO <> 1
THEN 'NAO' ELSE 'SIM' END SERA_INTEGRADO, 
X2.* FROM (
SELECT
--/*
'DADOS_DE_ANALISE' DADOS_DE_ANALISE,
CASE WHEN
X.TIPO_JORNADA NOT IN ('0','1','2','3')OR 
(SUBSTR(X.DURACAO_AULA,1,2)<> '01' OR SUBSTR(X.DURACAO_AULA,4,2)NOT IN ('00','30'))OR 
LENGTH(X.COD_ORGAO)<> 13 OR 
X.TURNO NOT IN ('MANHÃ','INTEGRAL','TARDE','NOITE')OR
(
(SUBSTR(X.HOR_INIC,1,2)>= 20 AND SUBSTR(X.HOR_INIC,4,2) > 1) OR (SUBSTR(X.HOR_INIC,1,2)>= 18 AND X.DURACAO_AULA = '01:30') 
)
OR (EXTRACT(YEAR FROM SYSDATE)<> EXTRACT(YEAR FROM TO_DATE(X.DAT_INICIO,'DD/MM/YYYY'))OR EXTRACT(YEAR FROM SYSDATE)<> EXTRACT(YEAR FROM TO_DATE(X.DAT_FIM,'DD/MM/YYYY')))--NOVO EM 29/7/23
OR (X.TURNO = 'INTEGRAL' AND X.TIPO_JORNADA <> '3')
THEN 'SIM' ELSE 'NAO' END CAMPOS_IMPORTANTES_INVALIDOS,

CASE WHEN X.ID_HORARIO IS NULL OR X.BM IS NULL OR X.TIPO_JORNADA IS NULL OR X.DURACAO_AULA IS NULL OR X.DAT_INICIO IS NULL OR X.DAT_FIM IS NULL OR X.COD_ORGAO IS NULL OR X.TURNO IS NULL OR X.HOR_INIC IS NULL OR X.HOR_FIM IS NULL
OR (X.SEGUNDA IS NULL AND X.TERCA IS NULL AND X.QUARTA IS NULL AND X.QUINTA IS NULL AND X.SEXTA IS NULL) THEN 'SIM' ELSE 'NAO' END CAMPOS_OBRIGATORIOS_NULOS,

CASE WHEN 
SUBSTR(X.CARGA_HORARIA,1,2)> '22' 
OR (SUBSTR(X.CARGA_HORARIA,1,2)= '22' AND SUBSTR(X.CARGA_HORARIA,4,2)> '30') 
OR (/*X.TIPO_JORNADA <> 3 AND --comentado 9/1/24*/ X.COORDENADOR = 'NÃO' AND X.DURACAO_AULA = '01:30' AND X.TURNO NOT IN ('MANHÃ','INTEGRAL') AND (X.SEGUNDA LIKE '%4%' OR X.TERCA LIKE '%4%' OR X.QUARTA LIKE '%4%' OR X.QUINTA LIKE '%4%' OR X.SEXTA LIKE '%4%'))--Existe aula 4 de duração 1h30 no turno TARDE?NÃO , Só pode ter tipo jornada = 3, o turno INTEGRAL/INTERMEDIÁRIO acontece pelo horário da manhã.  
OR (X.COORDENADOR = 'NÃO' AND X.TIPO_JORNADA <> 0 AND (SUBSTR(X.CARGA_HORARIA,1,2)> '15' OR ( SUBSTR(X.CARGA_HORARIA,1,2)= '15' AND SUBSTR(X.CARGA_HORARIA,4,2)> '00')))--Não é coordenador, não é jornada ZERO e tem mais que 15 horas, esta certo?NÃO, É ERRO MESMO DO USUÁRIO.
--OR (X.TURNO = 'INTEGRAL' AND X.DURACAO_AULA <> '01:30' )--INTEGRAL com aula de 1 hora não procede tambem, correto?Pode ocorrer jornada de extensão no Integral com módulo de 1 hora. São pouquíssimas extensões, mas existem e devem ser consideradas.
OR (X.TURNO = 'INTEGRAL' AND (X.TIPO_JORNADA <> 3 OR ((X.SEGUNDA IS NOT NULL AND X.SEGUNDA <> '4') OR (X.TERCA IS NOT NULL AND X.TERCA <> '4') OR (X.QUARTA IS NOT NULL AND X.QUARTA <>'4') OR (X.QUINTA IS NOT NULL AND X.QUINTA <>'4') OR (X.SEXTA IS NOT NULL AND X.SEXTA <>'4'))))--NOVO EM 25/9/23--INTEGRAL APENAS COM A AULA 4 PREENCHIDO
THEN 'SIM' ELSE 'NAO' END ERRO_CARGA_HORARIA,--CARGA HORARIO MAIOR 22H30 SE FOR GRAVAR HORAS REGENCIA + EXTRACLASSE

CASE
WHEN 
(X.SEGUNDA IS NOT NULL AND X.HORARIO_ENTRADA_SEGUNDA IS NOT NULL AND X.HORARIO_ENTRADA_SEGUNDA <> ':' AND SUBSTR(X.HORARIO_ENTRADA_SEGUNDA,1,2) > SUBSTR(X.HOR_FIM,1,2))OR
(X.TERCA IS NOT NULL AND X.HORARIO_ENTRADA_TERCA IS NOT NULL AND X.HORARIO_ENTRADA_TERCA <> ':' AND SUBSTR(X.HORARIO_ENTRADA_TERCA,1,2) > SUBSTR(X.HOR_FIM,1,2))OR
(X.QUARTA IS NOT NULL AND X.HORARIO_ENTRADA_QUARTA IS NOT NULL AND X.HORARIO_ENTRADA_QUARTA <> ':' AND SUBSTR(X.HORARIO_ENTRADA_QUARTA, 1,2) > SUBSTR(X.HOR_FIM,1,2))OR
(X.QUINTA IS NOT NULL AND X.HORARIO_ENTRADA_QUINTA IS NOT NULL AND X.HORARIO_ENTRADA_QUINTA <> ':' AND SUBSTR(X.HORARIO_ENTRADA_QUINTA,1,2) > SUBSTR(X.HOR_FIM,1,2))OR
(X.SEXTA IS NOT NULL AND X.HORARIO_ENTRADA_SEXTA IS NOT NULL AND X.HORARIO_ENTRADA_SEXTA <> ':' AND SUBSTR(X.HORARIO_ENTRADA_SEXTA,1,2) > SUBSTR(X.HOR_FIM,1,2))
THEN 'SIM' ELSE 'NAO' END ERRO_INTERVALO_TURNO,---HORARIO DE INTERVALO POR DIA MAIOR QUE HORA INICIO FIM DO TURNO
--*/
case 
when X.CANCELAMENTO IS NULL AND X.DT_CANCELAMENTO_USAR is null and TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY') < TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                              then '1_ERRO_SEM_DATA_CANCELAMENTO_DATA_FIM_MENOR_DATA_INICIO'
when X.CANCELAMENTO IS NULL AND X.DT_CANCELAMENTO_USAR is null and TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY') >= TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                             then '2_OK_SEM_DATA_CANCELAMENTO_DATA_INICIO_IGUAL_OU_MAIOR_DATA_FIM'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+1   < TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                      then '3_ERRO_LANCAMENTO_DATA_FIM_MENOR_DATA_INICIO' --AJUSTADO 10/8
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                      then '4_ERRO_LANCAMENTO_DATA_CANCELAMENTO_MENOR_DATA_INICIO' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') <> TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then '5_ERRO_EXTENSAO_SEM_NENHUM_DIA_TRABALHADO'--AJUSTADO 10/8
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')    then '6_OK_EXTENSAO_CANCELADA_ANTES_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')    then '7_OK_EXTENSAO_CANCELADA_NO_ULTIMO_DIA_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then '8_OK_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_CORRETO_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then '9_OK_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_ERRADO_MAIOR_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') AND TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then '10_OK_EXTENSAO_CANCELADA_SEM_NENHUM_DIA_REALIZADO'--NOVO 10/8
when x.id_jornada is null and x.TIPO_JORNADA = 0 then '11_OK_HORARIO_SEM_JORNADA'
else 'ERRO_SITUACAO_NAO_MAPEADA'
END AS SITUACAO_JORNADA, --NOVOS CAMPOS INICIO_JORNADA E FIM_JORNADA EM 30/8/23---REFERENTE A DATA DE CANCELAMENTO, --DATA INICIO MAIOR QUE DATA FIM
case 
when X.CANCELAMENTO IS NULL AND X.DT_CANCELAMENTO_USAR is null and TO_DATE(X.DAT_FIM,'DD/MM/YYYY') < TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                              then '1_ERRO_SEM_DATA_CANCELAMENTO_DATA_FIM_MENOR_DATA_INICIO'
when X.CANCELAMENTO IS NULL AND X.DT_CANCELAMENTO_USAR is null and TO_DATE(X.DAT_FIM,'DD/MM/YYYY') >= TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                             then '2_OK_SEM_DATA_CANCELAMENTO_DATA_INICIO_IGUAL_OU_MAIOR_DATA_FIM'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+1   < TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                      then '3_ERRO_LANCAMENTO_DATA_FIM_MENOR_DATA_INICIO' --AJUSTADO 10/8
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                  then '4_ERRO_LANCAMENTO_DATA_CANCELAMENTO_MENOR_DATA_INICIO' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')     <> TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then '5_ERRO_EXTENSAO_SEM_NENHUM_DIA_TRABALHADO'--AJUSTADO 10/8
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.DAT_FIM,'DD/MM/YYYY')    then '6_OK_EXTENSAO_CANCELADA_ANTES_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')    then '7_OK_EXTENSAO_CANCELADA_NO_ULTIMO_DIA_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then '8_OK_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_CORRETO_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then '9_OK_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_ERRADO_MAIOR_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.DAT_INICIO,'DD/MM/YYYY') AND TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')      = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then '10_OK_EXTENSAO_CANCELADA_SEM_NENHUM_DIA_REALIZADO'--NOVO 10/8
else 'ERRO_SITUACAO_NAO_MAPEADA'
END AS SITUACAO_HORARIO, --ALTERADO NOME CAMPO PARA HORARIO EM 30/8/23--REFERENTE A DATA DE CANCELAMENTO, --DATA INICIO MAIOR QUE DATA FIM
case 
when X.CANCELAMENTO IS NULL AND X.DT_CANCELAMENTO_USAR is null then TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')                                                                                                                                                                                  --'1OU2_SEM_DATA_CANCELAMENTO'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+1   < TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                       then TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')   --'3_ERRO_LANCAMENTO_LANCAR_NOVAMENTE_EXTENSAO_X.DAT_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')                                                                                       then TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')   --'4_ERRO_LANCAMENTO_LANCAR_NOVAMENTE_EXTENSAO_X.DT_CANCELAMENTO_USAR' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY') <> TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')  -- '5_EXTENSAO_SEM_NENHUM_DIA_TRABALHADO'--AJUSTADO 10/8
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') < TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')    then TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')-1 --'6_EXTENSAO_INTERROMPIDA_ANTES_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')    then TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY')-1 --'7_EXTENSAO_INTERROMPIDA_NO_ULTIMO_DIA_DO_FIM' 
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')   --'8_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_CORRETO_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') > TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')      --'9_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_ERRADO_MAIOR_X.DAT_FIM+1'
when X.CANCELAMENTO IS NOT NULL AND X.DT_CANCELAMENTO_USAR is not null and TO_DATE(X.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  AND TO_DATE(X.INICIO_JORNADA,'DD/MM/YYYY')  = TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')+ 1 then TO_DATE(X.FIM_JORNADA,'DD/MM/YYYY')     --'10_OK_EXTENSAO_CANCELADA_SEM_NENHUM_DIA_REALIZADO'--NOVO 10/8
else TO_DATE('01/01/2001','DD/MM/YYYY')
END AS DT_REAL_ULT_DIA_TRABALHADO, ---QUAL ULTIMO DIA REFERENTE A DATA DE CANCELAMENTO
/*--COMENTADO EM 30/8/23
case 
when X.DT_CANCELAMENTO is null then TO_DATE(X.DAT_FIM,'DD/MM/YYYY')                                                                                                                                                                                  --'1OU2_SEM_DATA_CANCELAMENTO'
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+1   < TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                       then TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY')   --'3_ERRO_LANCAMENTO_LANCAR_NOVAMENTE_EXTENSAO_X.DAT_FIM' 
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') < TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')                                                                                   then TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY')   --'4_ERRO_LANCAMENTO_LANCAR_NOVAMENTE_EXTENSAO_X.DT_CANCELAMENTO' 
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') = TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')     <> TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY')  -- '5_EXTENSAO_SEM_NENHUM_DIA_TRABALHADO'--AJUSTADO 10/8
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') < TO_DATE(X.DAT_FIM,'DD/MM/YYYY')    then TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY')-1 --'6_EXTENSAO_INTERROMPIDA_ANTES_DO_FIM' 
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')    then TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY')-1 --'7_EXTENSAO_INTERROMPIDA_NO_ULTIMO_DIA_DO_FIM' 
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then TO_DATE(X.DAT_FIM,'DD/MM/YYYY')           --'8_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_CORRETO_X.DAT_FIM+1'
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') > TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') > TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then TO_DATE(X.DAT_FIM,'DD/MM/YYYY')           --'9_EXTENSAO_REALIZADA_INTEGRALMENTE_PREENCHIMENTO_CANCELAMENTO_ERRADO_MAIOR_X.DAT_FIM+1'
when X.DT_CANCELAMENTO is not null and TO_DATE(X.DT_CANCELAMENTO,'DD/MM/YYYY') = TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')  AND TO_DATE(X.DAT_INICIO,'DD/MM/YYYY')      = TO_DATE(X.DAT_FIM,'DD/MM/YYYY')+ 1 then TO_DATE(X.DAT_FIM,'DD/MM/YYYY')           --'10_OK_EXTENSAO_CANCELADA_SEM_NENHUM_DIA_REALIZADO'--NOVO 10/8
else TO_DATE('01/01/2001','DD/MM/YYYY')
END AS DT_REAL_ULT_DIA_TRABALHADO, ---QUAL ULTIMO DIA REFERENTE A DATA DE CANCELAMENTO
*/
X.ID_REGISTRO_ARQUIVO, X.CANCELAMENTO,
X.QTD_REG_MESMO_ID_HORARIO, 
'DADOS_PUROS_SGE' DADOS_PUROS_SGE,
X.ID_JORNADA, X.ID_HORARIO, X.JORNADA_VALIDADA, X.BM, X.TIPO_JORNADA, X.JORNADA, X.COORDENADOR, X.DURACAO_AULA, X.CARGA_HORARIA, 
X.INICIO_JORNADA, X.FIM_JORNADA, X.EXTRA_CLASSE, 
X.DAT_INICIO, X.DAT_FIM, X.DT_CANCELAMENTO, X.DAT_VALIDA_CANCELA, X.DT_CANCELAMENTO_USAR, 
X.COD_ORGAO, X.NOM_OFIC_ESCL, X.TURNO, X.HOR_INIC, X.HOR_FIM, 
X.SEGUNDA, X.HORARIO_ENTRADA_SEGUNDA, X.TERCA, X.HORARIO_ENTRADA_TERCA, X.QUARTA, X.HORARIO_ENTRADA_QUARTA, X.QUINTA, X.HORARIO_ENTRADA_QUINTA, X.SEXTA, X.HORARIO_ENTRADA_SEXTA, 
X.REGIONAL, X.NOM_LOCA, X.DT_ULTIMA_ALTERACAO, X.BM_ULTIMA_ALTERACAO 
FROM
(
SELECT 
A.ID_REGISTRO_ARQUIVO, A.CANCELAMENTO,
D.QTD QTD_REG_MESMO_ID_HORARIO,
S.ID_HORARIO, S.JORNADA_VALIDADA, S.BM, S.TIPO_JORNADA, S.JORNADA, S.COORDENADOR, S.DURACAO_AULA, S.CARGA_HORARIA, S.DAT_INICIO, S.DAT_FIM, 
S.DT_CANCELAMENTO, S.DAT_VALIDA_CANCELA,
CASE WHEN S.DAT_VALIDA_CANCELA IS NOT NULL THEN S.DT_CANCELAMENTO ELSE NULL END DT_CANCELAMENTO_USAR, --AJUSTE EM 24/10/23 PARA NAO TER QUE MUDAR EM MUITOS LOCAIS INCLUIR UM CASE PARA O NOVO CAMPO 'DAT_VALIDA_CANCELA' QUE CONFIRMA A VALIDACAO DO CANCELAMENTO
S.COD_ORGAO, S.NOM_OFIC_ESCL, S.TURNO, S.HOR_INIC, S.HOR_FIM,
S.SEGUNDA, S.HORARIO_ENTRADA_SEGUNDA, S.TERCA, S.HORARIO_ENTRADA_TERCA, S.QUARTA, S.HORARIO_ENTRADA_QUARTA, S.QUINTA, S.HORARIO_ENTRADA_QUINTA, S.SEXTA, S.HORARIO_ENTRADA_SEXTA, 
S.REGIONAL, S.NOM_LOCA, S.DT_ULTIMA_ALTERACAO, S.BM_ULTIMA_ALTERACAO 
,S.ID_JORNADA, S.INICIO_JORNADA, S.FIM_JORNADA, S.EXTRA_CLASSE
FROM 
--SGE_PROD.HORARIO_TRABALHO_IFPONTO@LK_SIRH_SGE.PBH S --homologacao
--LEFT OUTER JOIN (SELECT ID_HORARIO, COUNT(1)QTD from SGE_PROD.HORARIO_TRABALHO_IFPONTO@LK_SIRH_SGE.PBH group by ID_HORARIO)D ON S.ID_HORARIO = D.ID_HORARIO --homologacao
SGE_PROD.HORARIO_TRABALHO_IFPONTO@LK_SGE_SIRH.PBH S--producao
LEFT OUTER JOIN (SELECT ID_HORARIO, COUNT(1)QTD from SGE_PROD.HORARIO_TRABALHO_IFPONTO@LK_SGE_SIRH.PBH group by ID_HORARIO)D ON S.ID_HORARIO = D.ID_HORARIO --producao
LEFT OUTER JOIN (SELECT A.* FROM PONTO_ELETRONICO.SMARH_INT_PONTO_SGE_ARQUIVOS A WHERE A.id_horario = vID_HORARIO)A--**********************TROCAR ID_HORARIO PARA A DATA DO DIA DA IMPORTACAO DO ARQUIVO
ON A.ID_JORNADA = S.ID_JORNADA --NOVO PARTE EM 11/10/23
--WHERE ID_HORARIO = 1581 --TESTES
ORDER BY BM, DAT_INICIO, TIPO_JORNADA, ID_HORARIO
)X
)X2 
--WHERE ID_HORARIO = 2588--2072
LEFT OUTER JOIN 
(SELECT A.* FROM PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD A WHERE TRUNC(A.DT_INICIO) >= TO_DATE(vDATA_INICIO,'DD/MM/YYYY')/*AND A.TIPO_EXTENSAO = 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA'*/ ORDER BY A.DT_INICIO)A --PARA OS PRIMEIROS ARQUIVOS DE/PARA EXTENSOES 2023
ON A.ID_JORNADA = X2.ID_JORNADA

--)X3 GROUP BY X3.STATUS_ARQUIVO_ANTIGO_SGE, X3.SERA_INTEGRADO ORDER BY X3.SERA_INTEGRADO, X3.STATUS_ARQUIVO_ANTIGO_SGE --PARA ANALISE ARQUIVOS DE/PARA EXTENSOES 2023



)LOOP

vCONTADOR := vCONTADOR +1;
dbms_output.put_line('-----------------------------------');
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' C1.ID_HORARIO: '||C1.ID_HORARIO);

INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_GERAL(DATA_PROCESSAMENTO, DATA_RECEBEU_ARTE, ID_HORARIO, JORNADA_VALIDADA, BM, TIPO_JORNADA, JORNADA, DURACAO_AULA, CARGA_HORARIA, DATA_INICIO, DATA_FIM , DATA_CANCELAMENTO, 
COD_ORGAO, NOM_OFIC_ESCL, TURNO, HORA_INI_TURNO, HORA_FIM_TURNO, SEGUNDA, INTERVALO_SEGUNDA, TERCA, INTERVALO_TERCA, QUARTA, INTERVALO_QUARTA, QUINTA, INTERVALO_QUINTA, SEXTA, INTERVALO_SEXTA
,COORDENACAO, REGIONAL, LOCAL, DATA_ULT_ALTERACAO, BM_ULTIMA_ALTERACAO
,SERA_INTEGRADO, CAMPOS_IMPORTANTES_INVALIDOS, CAMPOS_OBRIGATORIOS_NULOS, ERRO_CARGA_HORARIA, ERRO_INTERVALO_TURNO, SITUACAO_JORNADA, DT_REAL_ULT_DIA_TRABALHADO, QTD_REG_MESMO_ID_HORARIO
,ID_JORNADA, OBS_PROCESSAMENTO, INICIO_JORNADA, FIM_JORNADA, TIPO_REGISTRO, DT_VALIDA_CANCELA, DT_CANCELAMENTO_USAR, EXTRA_CLASSE
) 
VALUES(SYSDATE, SYSDATE, C1.ID_HORARIO, C1.JORNADA_VALIDADA, C1.BM, C1.TIPO_JORNADA, C1.JORNADA, C1.DURACAO_AULA, C1.CARGA_HORARIA, C1.DAT_INICIO, C1.DAT_FIM, C1.DT_CANCELAMENTO, 
C1.COD_ORGAO, C1.NOM_OFIC_ESCL, C1.TURNO, C1.HOR_INIC, C1.HOR_FIM, 
C1.SEGUNDA, C1.HORARIO_ENTRADA_SEGUNDA, C1.TERCA, C1.HORARIO_ENTRADA_TERCA, C1.QUARTA, C1.HORARIO_ENTRADA_QUARTA, C1.QUINTA, C1.HORARIO_ENTRADA_QUINTA, C1.SEXTA, C1.HORARIO_ENTRADA_SEXTA,
C1.COORDENADOR, C1.REGIONAL, C1.NOM_LOCA , C1.DT_ULTIMA_ALTERACAO, C1.BM_ULTIMA_ALTERACAO
,C1.SERA_INTEGRADO, C1.CAMPOS_IMPORTANTES_INVALIDOS, C1.CAMPOS_OBRIGATORIOS_NULOS, C1.ERRO_CARGA_HORARIA, C1.ERRO_INTERVALO_TURNO, C1.SITUACAO_JORNADA, C1.DT_REAL_ULT_DIA_TRABALHADO, C1.QTD_REG_MESMO_ID_HORARIO
,C1.ID_JORNADA, C1.STATUS_ARQUIVO_ANTIGO_SGE, C1.INICIO_JORNADA, C1.FIM_JORNADA, 'DE/PARA_EXTENSOES_2023', C1.DAT_VALIDA_CANCELA, C1.DT_CANCELAMENTO_USAR, C1.EXTRA_CLASSE
);COMMIT; 

END LOOP;--C1

END;

end;