
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP11_AJUSTE_HORAS_DIA" (ID_HORARIO IN VARCHAR2, DATA_INICIO IN DATE)
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_ajuste_horas_dia_DE_PARA_EXTENSOES_2023_b2.sql)

---b2 em 25/10/23 devido campo CANCELAMENTO_USAR
--Kellysson em 18/9/23 12º PASSO --novo em 18/9/23 ---ajuste horas individuais na semana (sql_ajuste_horas_dia_DE_PARA_EXTENSOES_2023_b1.sql)
--Kellysson em 5/9/23 b2 (sql_ajuste_DE_PARA_EXTENSOES_2023_b2.sql) para ajuste DATA_INICIO_U E DATA_FIM_U pARA INICIO_JORNADA_U e FIM_JORNADA_U
--Kellysson em 16/8/23 baseado (sql_relatorio_pos_passo8_DE-PARA.sql)
--9º PASSO TEMPORARIO OU NAO PARA O DE/PARA EM CASOS QUE NO FINAL DO PASSO 8 NAO BATEU A QUANTIDADE DE HORAS/MINUTOS NA SEMANA
--/*
DECLARE 
vCONTADOR NUMBER;
vB BOOLEAN := TRUE;
vID_HORARIO VARCHAR2(20);
vDATA_INICIO DATE;


BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vID_HORARIO := ID_HORARIO;
vDATA_INICIO := DATA_INICIO;


FOR C1 IN (


--SELECT CENARIO_FINAL_ID_JORNADA, CENARIO_FINAL_CANCELAMENTO, CENARIO_FINAL_TOTAL_SEMANA, COUNT(1)QTD FROM( --SINTETICO

SELECT 
X5.CENARIO_FINAL_ID_JORNADA, X5.CENARIO_FINAL_CANCELAMENTO, X5.CENARIO_FINAL_TOTAL_SEMANA, X5.CENARIO_GERAL, X5.CENARIO_CANCELAMENTO, 
X5.DADOS_ARQUIVO, X5.ID_JORNADA, X5.CANCELAMENTO, X5.HORAS, X5.ID_REGISTRO_ARQUIVO, X5.CODIGO_CONTRATO_SGE, X5.BM_SERVIDOR, X5.NOME_SERVIDOR, X5.CODIGO_ESCOLA, X5.NOME_ESCOLA, X5.MOTIVO, X5.INICIO, X5.FIM, X5.DIAS, X5.TURNO, X5.DISCIPLINA_MINISTRADA, X5.INICIO_SEGUNDA, X5.FIM_SEGUNDA, X5.INICIO_TERCA, X5.FIM_TERCA, X5.INICIO_QUARTA, X5.FIM_QUARTA, X5.INICIO_QUINTA, X5.FIM_QUINTA, X5.INICIO_SEXTA, X5.FIM_SEXTA, X5.INICIO_SABADO, X5.FIM_SABADO, X5.INICIO_DOMINGO, X5.FIM_DOMINGO, X5.FAZ_JUS_VALE_REF, X5.REQUER_VALE_REF, X5.DT_CRIACAO_SGE, X5.DT_CANCELAMENTO_SGE, X5.OBSERVACAO, X5.ID_HORARIO, 
X5.DADOS_DBLINK, X5.ID_JORNADA_D, X5.DT_CANCELAMENTO_USAR, X5.CARGA_HORARIA, X5.HM_TOTAIS, X5.HTOTAIS, X5.FRACAO_MIN_TOTAIS, X5.CARGA_HORARIA_CHEIA,
X5.QTD_CONCOMITA, X5.STATUS_HORARIO, 
X5.QTD_REG_PASSO_2, X5.STATUS_REGISTRO_C, X5.DATA_RECEBEU_ARTE_C, X5.DATA_CANCELAMENTO_C, X5.OBS_PROCESSAMENTO_C, X5.HORAS_TOTAIS, X5.MINUTOS_TOTAIS, X5.TOTAL_MINUTOS_AULA, X5.MINUTOS_NO_DIA_INI_TURNO, 
X5.AULAS_SEG, X5.PRIMEIRA_AULA_SEG, X5.AULAS_TER, X5.PRIMEIRA_AULA_TER, X5.AULAS_QUA, X5.PRIMEIRA_AULA_QUA, X5.AULAS_QUI, X5.PRIMEIRA_AULA_QUI, X5.AULAS_SEX, X5.PRIMEIRA_AULA_SEX, X5.TEMPO_GRAVAR_SEG, X5.TEMPO_GRAVAR_TER, X5.TEMPO_GRAVAR_QUA, X5.TEMPO_GRAVAR_QUI, X5.TEMPO_GRAVAR_SEX, 
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_SEG/60) ELSE 0 END H_INICIO_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_SEG,60) ELSE 0 END M_INICIO_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_SEG + X5.TEMPO_GRAVAR_SEG)/60) ELSE 0 END H_FIM_SEGUNDA,
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_SEG + X5.TEMPO_GRAVAR_SEG),60) ELSE 0 END M_FIM_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_TER/60) ELSE 0 END H_INICIO_TERCA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_TER,60) ELSE 0 END M_INICIO_TERCA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_TER + X5.TEMPO_GRAVAR_TER)/60) ELSE 0 END H_FIM_TERCA,
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_TER + X5.TEMPO_GRAVAR_TER),60) ELSE 0 END M_FIM_TERCA,
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_QUA/60) ELSE 0 END H_INICIO_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_QUA,60) ELSE 0 END M_INICIO_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_QUA + X5.TEMPO_GRAVAR_QUA)/60) ELSE 0 END H_FIM_QUARTA,
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_QUA + X5.TEMPO_GRAVAR_QUA),60) ELSE 0 END M_FIM_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_QUI/60) ELSE 0 END H_INICIO_QUINTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_QUI,60) ELSE 0 END M_INICIO_QUINTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_QUI + X5.TEMPO_GRAVAR_QUI)/60) ELSE 0 END H_FIM_QUINTA,
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_QUI + X5.TEMPO_GRAVAR_QUI),60) ELSE 0 END M_FIM_QUINTA,
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_SEX/60) ELSE 0 END H_INICIO_SEXTA, 
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_SEX,60) ELSE 0 END M_INICIO_SEXTA, 
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_SEX + X5.TEMPO_GRAVAR_SEX)/60) ELSE 0 END H_FIM_SEXTA,
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_SEX + X5.TEMPO_GRAVAR_SEX),60) ELSE 0 END M_FIM_SEXTA,
X5.DT_INICIO_IGUAL, X5.DT_FIM_IGUAL, X5.DT_CANCELAMENTO_IGUAL, X5.ID_HORARIO_D, X5.JORNADA_VALIDADA, X5.BM, X5.TIPO_JORNADA, X5.JORNADA, X5.DURACAO_AULA, X5.DATA_INICIO, X5.DATA_FIM, X5.COD_ORGAO, X5.NOM_OFIC_ESCL, X5.TURNO_D, X5.HORA_INI_TURNO, X5.HORA_FIM_TURNO, X5.SEGUNDA, X5.INTERVALO_SEGUNDA, X5.TERCA, X5.INTERVALO_TERCA, X5.QUARTA, X5.INTERVALO_QUARTA, X5.QUINTA, X5.INTERVALO_QUINTA, X5.SEXTA, X5.INTERVALO_SEXTA, X5.COORDENACAO, X5.REGIONAL, X5.LOCAL, X5.BM_ULTIMA_ALTERACAO, X5.DATA_ULT_ALTERACAO, X5.DATA_RECEBEU_ARTE, X5.DATA_PROCESSAMENTO, X5.OBS_PROCESSAMENTO, X5.SERA_INTEGRADO, X5.CAMPOS_IMPORTANTES_INVALIDOS, X5.CAMPOS_OBRIGATORIOS_NULOS, X5.ERRO_CARGA_HORARIA, X5.ERRO_INTERVALO_TURNO, X5.SITUACAO_JORNADA, X5.DT_REAL_ULT_DIA_TRABALHADO, X5.QTD_REG_MESMO_ID_HORARIO, X5.INICIO_JORNADA, X5.FIM_JORNADA, X5.TIPO_REGISTRO, 
X5.DADOS_ARTERH, X5.ID_JORNADA_E, X5.DT_CANCELAMENTO_E, X5.HORAS_SEMANAIS, X5.COMPARA_HORAS_DIA_SEMANA, X5.HM_AULAS_SEG, X5.PRIMEIRA_MARCACAO_SEG, X5.HM_AULAS_TER, X5.PRIMEIRA_MARCACAO_TER, X5.HM_AULAS_QUA, X5.PRIMEIRA_MARCACAO_QUA, X5.HM_AULAS_QUI, X5.PRIMEIRA_MARCACAO_QUI, X5.HM_AULAS_SEX, X5.PRIMEIRA_MARCACAO_SEX, X5.ORIGEM, X5.TIPO_EXTENSAO, X5.ID_REGISTRO_ARQUIVO_D, X5.CODIGO_EMPRESA, X5.BM_SERVIDOR_E, X5.NOME_SERVIDOR_E, X5.CODIGO_CONTRATO_SGE_E, X5.DT_INICIO, X5.DT_FIM, X5.DT_RECEBEU_CADASTRO, X5.DT_RECEBEU_CANCELAMENTO, X5.TOTAL_DIAS, X5.MESMO_LOCAL_DA_PRINCIPAL, X5.MESMO_TURNO_DA_PRINCIPAL, X5.TURNO_E, X5.COD_ESCALA, X5.COD_LOCAL1, X5.COD_LOCAL2, X5.COD_LOCAL3, X5.COD_LOCAL4, X5.COD_LOCAL5, X5.COD_LOCAL6, X5.NOME_ESCOLA_E, X5.MOTIVO_E, X5.DISCIPLINA_MINISTRADA_E, X5.HORARIO_INICIO_SEGUNDA, X5.HORARIO_FIM_SEGUNDA, X5.TOTAL_SEGUNDA, X5.HORARIO_INICIO_TERCA, X5.HORARIO_FIM_TERCA, X5.TOTAL_TERCA, X5.HORARIO_INICIO_QUARTA, X5.HORARIO_FIM_QUARTA, X5.TOTAL_QUARTA, X5.HORARIO_INICIO_QUINTA, X5.HORARIO_FIM_QUINTA, X5.TOTAL_QUINTA, X5.HORARIO_INICIO_SEXTA, X5.HORARIO_FIM_SEXTA, X5.TOTAL_SEXTA, X5.TOTAL_SEMANA_5_DIAS, X5.HORARIO_INICIO_SABADO, X5.HORARIO_FIM_SABADO, X5.HORARIO_INICIO_DOMINGO, X5.HORARIO_FIM_DOMINGO, X5.CODIGO_ESCOLA_E, X5.DT_CRIACAO_VERBA, X5.DT_CANCELAMENTO_VERBA, X5.TIPO_CONTRATO, X5.DT_CRIACAO_SGE_E, X5.DT_CANCELAMENTO_SGE_E, X5.FAZ_JUS_VALE_REF_E, X5.REQUER_VALE_REF_E, X5.OBSERVACAO_E, X5.ID_HORARIO_E
FROM (

SELECT X4.QTD_CONCOMITA, X4.STATUS_HORARIO, X4.CENARIO_FINAL_ID_JORNADA, X4.CENARIO_FINAL_CANCELAMENTO, X4.CENARIO_FINAL_TOTAL_SEMANA, X4.CENARIO_GERAL, X4.CENARIO_CANCELAMENTO, 
X4.DADOS_ARQUIVO, X4.ID_JORNADA, X4.CANCELAMENTO, X4.HORAS, X4.ID_REGISTRO_ARQUIVO, X4.CODIGO_CONTRATO_SGE, X4.BM_SERVIDOR, X4.NOME_SERVIDOR, X4.CODIGO_ESCOLA, X4.NOME_ESCOLA, X4.MOTIVO, X4.INICIO, X4.FIM, X4.DIAS, X4.TURNO, X4.DISCIPLINA_MINISTRADA, X4.INICIO_SEGUNDA, X4.FIM_SEGUNDA, X4.INICIO_TERCA, X4.FIM_TERCA, X4.INICIO_QUARTA, X4.FIM_QUARTA, X4.INICIO_QUINTA, X4.FIM_QUINTA, X4.INICIO_SEXTA, X4.FIM_SEXTA, X4.INICIO_SABADO, X4.FIM_SABADO, X4.INICIO_DOMINGO, X4.FIM_DOMINGO, X4.FAZ_JUS_VALE_REF, X4.REQUER_VALE_REF, X4.DT_CRIACAO_SGE, X4.DT_CANCELAMENTO_SGE, X4.OBSERVACAO, X4.ID_HORARIO, 
X4.DADOS_DBLINK, X4.ID_JORNADA_D, X4.DT_CANCELAMENTO_USAR, X4.CARGA_HORARIA, 
X4.HM_TOTAIS, X4.HTOTAIS, X4.FRACAO_MIN_TOTAIS, X4.CARGA_HORARIA_CHEIA,
X4.QTD_REG_PASSO_2, X4.STATUS_REGISTRO_C, X4.DATA_RECEBEU_ARTE_C, X4.DATA_CANCELAMENTO_C, X4.OBS_PROCESSAMENTO_C, X4.HORAS_TOTAIS, X4.MINUTOS_TOTAIS,
X4.TOTAL_MINUTOS_AULA, X4.MINUTOS_NO_DIA_INI_TURNO, X4.AULAS_SEG, X4.PRIMEIRA_AULA_SEG, X4.AULAS_TER, X4.PRIMEIRA_AULA_TER, X4.AULAS_QUA, X4.PRIMEIRA_AULA_QUA, X4.AULAS_QUI, X4.PRIMEIRA_AULA_QUI, X4.AULAS_SEX, X4.PRIMEIRA_AULA_SEX
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_SEG ELSE X4.HM_AULAS_SEG + (X4.HM_AULAS_SEG/2)END TEMPO_GRAVAR_SEG ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_TER ELSE X4.HM_AULAS_TER + (X4.HM_AULAS_TER/2)END TEMPO_GRAVAR_TER ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_QUA ELSE X4.HM_AULAS_QUA + (X4.HM_AULAS_QUA/2)END TEMPO_GRAVAR_QUA ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_QUI ELSE X4.HM_AULAS_QUI + (X4.HM_AULAS_QUI/2)END TEMPO_GRAVAR_QUI ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_SEX ELSE X4.HM_AULAS_SEX + (X4.HM_AULAS_SEX/2)END TEMPO_GRAVAR_SEX ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN TO_DATE(X4.DATA_INICIO,'DD/MM/YYYY') = TO_DATE(X4.DT_INICIO,'DD/MM/YYYY') THEN 'SIM' ELSE 'NAO' END DT_INICIO_IGUAL
,CASE WHEN TO_DATE(X4.DATA_FIM,'DD/MM/YYYY') = TO_DATE(X4.DT_FIM,'DD/MM/YYYY') THEN 'SIM' ELSE 'NAO' END DT_FIM_IGUAL
,CASE WHEN TO_DATE(X4.DT_CANCELAMENTO_USAR,'DD/MM/YYYY') = TO_DATE(X4.DT_CANCELAMENTO_E,'DD/MM/YYYY') OR (X4.DT_CANCELAMENTO_USAR IS NULL AND X4.DT_CANCELAMENTO_E IS NULL) THEN 'SIM' ELSE 'NAO' END DT_CANCELAMENTO_IGUAL
,X4.ID_HORARIO_D, X4.JORNADA_VALIDADA, X4.BM, X4.TIPO_JORNADA, X4.JORNADA, X4.DURACAO_AULA, X4.DATA_INICIO, X4.DATA_FIM, X4.COD_ORGAO, X4.NOM_OFIC_ESCL, X4.TURNO_D, X4.HORA_INI_TURNO, X4.HORA_FIM_TURNO, X4.SEGUNDA, X4.INTERVALO_SEGUNDA, X4.TERCA, X4.INTERVALO_TERCA, X4.QUARTA, X4.INTERVALO_QUARTA, X4.QUINTA, X4.INTERVALO_QUINTA, X4.SEXTA, X4.INTERVALO_SEXTA, X4.COORDENACAO, X4.REGIONAL, X4.LOCAL, X4.BM_ULTIMA_ALTERACAO, X4.DATA_ULT_ALTERACAO, X4.DATA_RECEBEU_ARTE, X4.DATA_PROCESSAMENTO, X4.OBS_PROCESSAMENTO, X4.SERA_INTEGRADO, X4.CAMPOS_IMPORTANTES_INVALIDOS, X4.CAMPOS_OBRIGATORIOS_NULOS, X4.ERRO_CARGA_HORARIA, X4.ERRO_INTERVALO_TURNO, X4.SITUACAO_JORNADA, X4.DT_REAL_ULT_DIA_TRABALHADO, X4.QTD_REG_MESMO_ID_HORARIO, X4.INICIO_JORNADA, X4.FIM_JORNADA, X4.TIPO_REGISTRO,
X4.DADOS_ARTERH, X4.ID_JORNADA_E, X4.DT_CANCELAMENTO_E, X4.HORAS_SEMANAIS, X4.COMPARA_HORAS_DIA_SEMANA, X4.HM_AULAS_SEG, X4.PRIMEIRA_MARCACAO_SEG, X4.HM_AULAS_TER, X4.PRIMEIRA_MARCACAO_TER, X4.HM_AULAS_QUA, X4.PRIMEIRA_MARCACAO_QUA, X4.HM_AULAS_QUI, X4.PRIMEIRA_MARCACAO_QUI, X4.HM_AULAS_SEX, X4.PRIMEIRA_MARCACAO_SEX, X4.ORIGEM, X4.TIPO_EXTENSAO, X4.ID_REGISTRO_ARQUIVO_D, X4.CODIGO_EMPRESA, X4.BM_SERVIDOR_E, X4.NOME_SERVIDOR_E, X4.CODIGO_CONTRATO_SGE_E, X4.DT_INICIO, X4.DT_FIM, X4.DT_RECEBEU_CADASTRO, X4.DT_RECEBEU_CANCELAMENTO, X4.TOTAL_DIAS, X4.MESMO_LOCAL_DA_PRINCIPAL, X4.MESMO_TURNO_DA_PRINCIPAL, X4.TURNO_E, X4.COD_ESCALA, X4.COD_LOCAL1, X4.COD_LOCAL2, X4.COD_LOCAL3, X4.COD_LOCAL4, X4.COD_LOCAL5, X4.COD_LOCAL6, X4.NOME_ESCOLA_E, X4.MOTIVO_E, X4.DISCIPLINA_MINISTRADA_E, X4.HORARIO_INICIO_SEGUNDA, X4.HORARIO_FIM_SEGUNDA, X4.TOTAL_SEGUNDA, X4.HORARIO_INICIO_TERCA, X4.HORARIO_FIM_TERCA, X4.TOTAL_TERCA, X4.HORARIO_INICIO_QUARTA, X4.HORARIO_FIM_QUARTA, X4.TOTAL_QUARTA, X4.HORARIO_INICIO_QUINTA, X4.HORARIO_FIM_QUINTA, X4.TOTAL_QUINTA, X4.HORARIO_INICIO_SEXTA, X4.HORARIO_FIM_SEXTA, X4.TOTAL_SEXTA, X4.TOTAL_SEMANA_5_DIAS, X4.HORARIO_INICIO_SABADO, X4.HORARIO_FIM_SABADO, X4.HORARIO_INICIO_DOMINGO, X4.HORARIO_FIM_DOMINGO, X4.CODIGO_ESCOLA_E, X4.DT_CRIACAO_VERBA, X4.DT_CANCELAMENTO_VERBA, X4.TIPO_CONTRATO, X4.DT_CRIACAO_SGE_E, X4.DT_CANCELAMENTO_SGE_E, X4.FAZ_JUS_VALE_REF_E, X4.REQUER_VALE_REF_E, X4.OBSERVACAO_E, X4.ID_HORARIO_E

FROM(

SELECT X3.QTD_CONCOMITA, X3.STATUS_HORARIO, X3.CENARIO_FINAL_ID_JORNADA, X3.CENARIO_FINAL_CANCELAMENTO, X3.CENARIO_FINAL_TOTAL_SEMANA,
X3.CENARIO_GERAL, X3.CENARIO_CANCELAMENTO, 
X3.DADOS_ARQUIVO, X3.ID_JORNADA, X3.CANCELAMENTO, X3.HORAS, X3.ID_REGISTRO_ARQUIVO, X3.CODIGO_CONTRATO_SGE, X3.BM_SERVIDOR, X3.NOME_SERVIDOR, X3.CODIGO_ESCOLA, X3.NOME_ESCOLA, X3.MOTIVO, X3.INICIO, X3.FIM, X3.DIAS, X3.TURNO, X3.DISCIPLINA_MINISTRADA, X3.INICIO_SEGUNDA, X3.FIM_SEGUNDA, X3.INICIO_TERCA, X3.FIM_TERCA, X3.INICIO_QUARTA, X3.FIM_QUARTA, X3.INICIO_QUINTA, X3.FIM_QUINTA, X3.INICIO_SEXTA, X3.FIM_SEXTA, X3.INICIO_SABADO, X3.FIM_SABADO, X3.INICIO_DOMINGO, X3.FIM_DOMINGO, X3.FAZ_JUS_VALE_REF, X3.REQUER_VALE_REF, X3.DT_CRIACAO_SGE, X3.DT_CANCELAMENTO_SGE, X3.OBSERVACAO, X3.ID_HORARIO, 
X3.DADOS_DBLINK, X3.ID_JORNADA_D, X3.DT_CANCELAMENTO_USAR, X3.CARGA_HORARIA, X3.HM_TOTAIS, X3.HTOTAIS, X3.FRACAO_MIN_TOTAIS, X3.CARGA_HORARIA_CHEIA, X3.TOTAL_MINUTOS_AULA, X3.MINUTOS_NO_DIA_INI_TURNO, X3.AULAS_SEG, X3.PRIMEIRA_AULA_SEG, X3.AULAS_TER, X3.PRIMEIRA_AULA_TER, X3.AULAS_QUA, X3.PRIMEIRA_AULA_QUA, X3.AULAS_QUI, X3.PRIMEIRA_AULA_QUI, X3.AULAS_SEX, X3.PRIMEIRA_AULA_SEX, X3.QTD_REG_PASSO_2, X3.STATUS_REGISTRO_C, X3.DATA_RECEBEU_ARTE_C, X3.DATA_CANCELAMENTO_C, X3.OBS_PROCESSAMENTO_C, X3.HORAS_TOTAIS, X3.MINUTOS_TOTAIS, X3.ID_HORARIO_D, X3.JORNADA_VALIDADA, X3.BM, X3.TIPO_JORNADA, X3.JORNADA, X3.DURACAO_AULA, X3.DATA_INICIO, X3.DATA_FIM, X3.COD_ORGAO, X3.NOM_OFIC_ESCL, X3.TURNO_D, X3.HORA_INI_TURNO, X3.HORA_FIM_TURNO, X3.SEGUNDA, X3.INTERVALO_SEGUNDA, X3.TERCA, X3.INTERVALO_TERCA, X3.QUARTA, X3.INTERVALO_QUARTA, X3.QUINTA, X3.INTERVALO_QUINTA, X3.SEXTA, X3.INTERVALO_SEXTA, X3.COORDENACAO, X3.REGIONAL, X3.LOCAL, X3.BM_ULTIMA_ALTERACAO, X3.DATA_ULT_ALTERACAO, X3.DATA_RECEBEU_ARTE, X3.DATA_PROCESSAMENTO, X3.OBS_PROCESSAMENTO, X3.SERA_INTEGRADO, X3.CAMPOS_IMPORTANTES_INVALIDOS, X3.CAMPOS_OBRIGATORIOS_NULOS, X3.ERRO_CARGA_HORARIA, X3.ERRO_INTERVALO_TURNO, X3.SITUACAO_JORNADA, X3.DT_REAL_ULT_DIA_TRABALHADO, X3.QTD_REG_MESMO_ID_HORARIO, X3.INICIO_JORNADA, X3.FIM_JORNADA, X3.TIPO_REGISTRO, 
X3.DADOS_ARTERH, X3.ID_JORNADA_E, X3.DT_CANCELAMENTO_E, X3.HORAS_SEMANAIS,
X3.COMPARA_HORAS_DIA_SEMANA 

,CASE WHEN X3.SEGUNDA IS NULL THEN 0 ELSE X3.AULAS_SEG * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEG --NOVO 16/8/23
,CASE WHEN X3.SEGUNDA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEG - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEG--NOVO 16/8/23
,CASE WHEN X3.TERCA IS NULL THEN 0 ELSE X3.AULAS_TER * X3.TOTAL_MINUTOS_AULA END HM_AULAS_TER --NOVO 16/8/23
,CASE WHEN X3.TERCA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_TER - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_TER--NOVO 16/8/23
,CASE WHEN X3.QUARTA IS NULL THEN 0 ELSE X3.AULAS_QUA * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUA --NOVO 16/8/23
,CASE WHEN X3.QUARTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUA - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUA--NOVO 16/8/23
,CASE WHEN X3.QUINTA IS NULL THEN 0 ELSE X3.AULAS_QUI * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUI --NOVO 16/8/23
,CASE WHEN X3.QUINTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUI - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUI--NOVO 16/8/23
,CASE WHEN X3.SEXTA IS NULL THEN 0 ELSE X3.AULAS_SEX * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEX --NOVO 16/8/23
,CASE WHEN X3.SEXTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEX - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEX--NOVO 16/8/23
,X3.ORIGEM, X3.TIPO_EXTENSAO, X3.ID_REGISTRO_ARQUIVO_D, X3.CODIGO_EMPRESA, X3.BM_SERVIDOR_E, X3.NOME_SERVIDOR_E, X3.CODIGO_CONTRATO_SGE_E, X3.DT_INICIO, X3.DT_FIM, X3.DT_RECEBEU_CADASTRO, X3.DT_RECEBEU_CANCELAMENTO, X3.TOTAL_DIAS, X3.MESMO_LOCAL_DA_PRINCIPAL, X3.MESMO_TURNO_DA_PRINCIPAL, X3.TURNO_E, X3.COD_ESCALA, X3.COD_LOCAL1, X3.COD_LOCAL2, X3.COD_LOCAL3, X3.COD_LOCAL4, X3.COD_LOCAL5, X3.COD_LOCAL6, X3.NOME_ESCOLA_E, X3.MOTIVO_E, X3.DISCIPLINA_MINISTRADA_E, X3.HORARIO_INICIO_SEGUNDA, X3.HORARIO_FIM_SEGUNDA, X3.TOTAL_SEGUNDA, X3.HORARIO_INICIO_TERCA, X3.HORARIO_FIM_TERCA, X3.TOTAL_TERCA, X3.HORARIO_INICIO_QUARTA, X3.HORARIO_FIM_QUARTA, X3.TOTAL_QUARTA, X3.HORARIO_INICIO_QUINTA, X3.HORARIO_FIM_QUINTA, X3.TOTAL_QUINTA, X3.HORARIO_INICIO_SEXTA, X3.HORARIO_FIM_SEXTA, X3.TOTAL_SEXTA, X3.TOTAL_SEMANA_5_DIAS, X3.HORARIO_INICIO_SABADO, X3.HORARIO_FIM_SABADO, X3.HORARIO_INICIO_DOMINGO, X3.HORARIO_FIM_DOMINGO, X3.CODIGO_ESCOLA_E, X3.DT_CRIACAO_VERBA, X3.DT_CANCELAMENTO_VERBA, X3.TIPO_CONTRATO, X3.DT_CRIACAO_SGE_E, X3.DT_CANCELAMENTO_SGE_E, X3.FAZ_JUS_VALE_REF_E, X3.REQUER_VALE_REF_E, X3.OBSERVACAO_E, X3.ID_HORARIO_E
FROM(

SELECT 
DP.QTD_CONCOMITA, CASE WHEN DP.QTD_CONCOMITA IS NOT NULL THEN 'HORARIO_CONCOMITOU' ELSE 'SEM_CONCOMITANCIA_HORARIO' END STATUS_HORARIO,
CASE
WHEN X2.ID_JORNADA IS NOT NULL AND X2.ID_JORNADA_D IS NOT NULL AND X2.ID_JORNADA_E IS NOT NULL 
                      AND X2.ID_JORNADA = X2.ID_JORNADA_D AND X2.ID_JORNADA_D = X2.ID_JORNADA_E THEN '1_OK_ID_JORNADA_NAS_3_FONTES_DADOS'
WHEN X2.ID_JORNADA IS     NULL AND X2.ID_JORNADA_D IS     NULL AND X2.ID_JORNADA_E IS     NULL THEN '999_???_SEM_ID_JORNADA_3_FONTES_DADOS' 
WHEN X2.ID_JORNADA IS NOT NULL AND X2.ID_JORNADA_D IS NOT NULL AND X2.ID_JORNADA_E IS     NULL THEN '2_ID_JORNADA_APENAS_2_FONTES_SGE' 
WHEN X2.ID_JORNADA IS NOT NULL AND X2.ID_JORNADA_D IS     NULL AND X2.ID_JORNADA_E IS NOT NULL THEN '3_ID_JORNADA_APENAS_ARQ_ANTIGO_SGE_E_ARTERH' 
WHEN X2.ID_JORNADA IS NOT NULL AND X2.ID_JORNADA_D IS     NULL AND X2.ID_JORNADA_E IS     NULL THEN '4_ID_JORNADA_APENAS_ARQ_ANTIGO_SGE' 
WHEN X2.ID_JORNADA IS     NULL AND X2.ID_JORNADA_D IS NOT NULL AND X2.ID_JORNADA_E IS NOT NULL THEN '5_ID_JORNADA_APENAS_DBLINK_SGE_E_ARTERH' 
WHEN X2.ID_JORNADA IS     NULL AND X2.ID_JORNADA_D IS NOT NULL AND X2.ID_JORNADA_E IS     NULL THEN '6_ID_JORNADA_APENAS_DBLINK_SGE' 
WHEN X2.ID_JORNADA IS     NULL AND X2.ID_JORNADA_D IS     NULL AND X2.ID_JORNADA_E IS NOT NULL THEN '7_ID_JORNADA_APENAS_ARTERH' 
ELSE 'VERIFICAR' END CENARIO_FINAL_ID_JORNADA,

CASE
WHEN X2.CANCELAMENTO IS NOT NULL AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND X2.DT_CANCELAMENTO_E IS NOT NULL 
                AND X2.CANCELAMENTO = X2.DT_CANCELAMENTO_USAR AND X2.DT_CANCELAMENTO_USAR = X2.DT_CANCELAMENTO_E THEN '1_OK_CANCELAMENTO_NAS_3_FONTES_DADOS'
WHEN X2.CANCELAMENTO IS     NULL AND X2.DT_CANCELAMENTO_USAR IS     NULL AND X2.DT_CANCELAMENTO_E IS     NULL THEN '2_OK_SEM_CANCELAMENTO_NAS_3_FONTES_DADOS'
WHEN X2.CANCELAMENTO IS NOT NULL AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND X2.DT_CANCELAMENTO_E IS     NULL THEN '3_CANCELAMENTO_APENAS_2_FONTES_SGE'
WHEN X2.CANCELAMENTO IS NOT NULL AND X2.DT_CANCELAMENTO_USAR IS     NULL AND X2.DT_CANCELAMENTO_E IS NOT NULL THEN '4_CANCELAMENTO_APENAS_ARQ_ANTIGO_SGE_E_ARTERH'
WHEN X2.CANCELAMENTO IS NOT NULL AND X2.DT_CANCELAMENTO_USAR IS     NULL AND X2.DT_CANCELAMENTO_E IS     NULL THEN '5_CANCELAMENTO_APENAS_ARQ_ANTIGO_SGE'
WHEN X2.CANCELAMENTO IS     NULL AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND X2.DT_CANCELAMENTO_E IS NOT NULL THEN '6_CANCELAMENTO_APENAS_DBLINK_SGE_E_ARTERH'
WHEN X2.CANCELAMENTO IS     NULL AND X2.DT_CANCELAMENTO_USAR IS NOT NULL AND X2.DT_CANCELAMENTO_E IS     NULL THEN '7_CANCELAMENTO_APENAS_DBLINK_SGE'
WHEN X2.CANCELAMENTO IS     NULL AND X2.DT_CANCELAMENTO_USAR IS     NULL AND X2.DT_CANCELAMENTO_E IS NOT NULL THEN '8_CANCELAMENTO_APENAS_ARTERH'
ELSE 'VERIFICAR' END CENARIO_FINAL_CANCELAMENTO,

CASE
WHEN X2.HORAS IS NOT NULL AND X2.CARGA_HORARIA_CHEIA IS NOT NULL AND X2.HORAS_SEMANAIS IS NOT NULL 
               AND X2.HORAS = X2.CARGA_HORARIA_CHEIA AND X2.CARGA_HORARIA_CHEIA = X2.HORAS_SEMANAIS THEN '1_OK_TOTAL_SEMANA_IGUAL_NAS_3_FONTES_DADOS'
WHEN X2.HORAS IS     NULL AND X2.CARGA_HORARIA_CHEIA IS     NULL AND X2.HORAS_SEMANAIS IS     NULL  THEN '999_???_SEM_TOTAL_SEMANA_NAS_3_FONTES_DADOS'
WHEN X2.HORAS IS NOT NULL AND X2.CARGA_HORARIA_CHEIA IS NOT NULL AND X2.HORAS_SEMANAIS IS     NULL  THEN '2_TOTAL_SEMANA_APENAS_2_FONTES_SGE'
WHEN X2.HORAS IS NOT NULL AND X2.CARGA_HORARIA_CHEIA IS     NULL AND X2.HORAS_SEMANAIS IS NOT NULL  THEN '3_TOTAL_SEMANA_APENAS_ARQ_ANTIGO_SGE_E_ARTERH'
WHEN X2.HORAS IS NOT NULL AND X2.CARGA_HORARIA_CHEIA IS     NULL AND X2.HORAS_SEMANAIS IS     NULL  THEN '4_TOTAL_SEMANA_APENAS_ARQ_ANTIGO_SGE'
WHEN X2.HORAS IS     NULL AND X2.CARGA_HORARIA_CHEIA IS NOT NULL AND X2.HORAS_SEMANAIS IS NOT NULL  THEN '5_TOTAL_SEMANA_APENAS_DBLINK_SGE_E_ARTERH'
WHEN X2.HORAS IS     NULL AND X2.CARGA_HORARIA_CHEIA IS NOT NULL AND X2.HORAS_SEMANAIS IS     NULL  THEN '6_TOTAL_SEMANA_APENAS_DBLINK_SGE'
WHEN X2.HORAS IS     NULL AND X2.CARGA_HORARIA_CHEIA IS     NULL AND X2.HORAS_SEMANAIS IS NOT NULL  THEN '7_TOTAL_SEMANA_APENAS_ARTERH'
ELSE 'VERIFICAR' END CENARIO_FINAL_TOTAL_SEMANA,

--CASE WHEN X2.HORAS_SEMANAIS = SUBSTR(X2.TOTAL_SEGUNDA+X2.TOTAL_TERCA+X2.TOTAL_QUARTA+X2.TOTAL_QUINTA+X2.TOTAL_SEXTA,12,5) THEN 'OK' ELSE 'ERRO' END COMPARA_HORAS_DIA_SEMANA,
CASE WHEN X2.QTD_REG_PASSO_2 IS NOT NULL AND X2.HORAS_SEMANAIS = SUBSTR(X2.TOTAL_SEGUNDA+X2.TOTAL_TERCA+X2.TOTAL_QUARTA+X2.TOTAL_QUINTA+X2.TOTAL_SEXTA,12,5) THEN 'OK' WHEN X2.QTD_REG_PASSO_2 IS NOT NULL AND X2.HORAS_SEMANAIS <> SUBSTR(X2.TOTAL_SEGUNDA+X2.TOTAL_TERCA+X2.TOTAL_QUARTA+X2.TOTAL_QUINTA+X2.TOTAL_SEXTA,12,5) THEN 'ERRO' END COMPARA_HORAS_DIA_SEMANA,

X2.CENARIO_GERAL, X2.CENARIO_CANCELAMENTO, 
X2.DADOS_ARQUIVO, X2.ID_JORNADA, X2.CANCELAMENTO, X2.HORAS, X2.ID_REGISTRO_ARQUIVO, X2.CODIGO_CONTRATO_SGE, X2.BM_SERVIDOR, X2.NOME_SERVIDOR, X2.CODIGO_ESCOLA, X2.NOME_ESCOLA, X2.MOTIVO, X2.INICIO, X2.FIM, X2.DIAS, X2.TURNO, X2.DISCIPLINA_MINISTRADA, X2.INICIO_SEGUNDA, X2.FIM_SEGUNDA, X2.INICIO_TERCA, X2.FIM_TERCA, X2.INICIO_QUARTA, X2.FIM_QUARTA, X2.INICIO_QUINTA, X2.FIM_QUINTA, X2.INICIO_SEXTA, X2.FIM_SEXTA, X2.INICIO_SABADO, X2.FIM_SABADO, X2.INICIO_DOMINGO, X2.FIM_DOMINGO, X2.FAZ_JUS_VALE_REF, X2.REQUER_VALE_REF, X2.DT_CRIACAO_SGE, X2.DT_CANCELAMENTO_SGE, X2.OBSERVACAO, X2.ID_HORARIO, 

X2.DADOS_DBLINK, X2.ID_JORNADA_D, X2.DT_CANCELAMENTO_USAR, X2.CARGA_HORARIA, 
X2.HM_TOTAIS, X2.HTOTAIS, X2.FRACAO_MIN_TOTAIS, X2.CARGA_HORARIA_CHEIA,
X2.TOTAL_MINUTOS_AULA, X2.MINUTOS_NO_DIA_INI_TURNO, X2.AULAS_SEG, X2.PRIMEIRA_AULA_SEG, X2.AULAS_TER, X2.PRIMEIRA_AULA_TER, X2.AULAS_QUA, X2.PRIMEIRA_AULA_QUA, X2.AULAS_QUI, X2.PRIMEIRA_AULA_QUI, X2.AULAS_SEX, X2.PRIMEIRA_AULA_SEX,

X2.QTD_REG_PASSO_2, X2.STATUS_REGISTRO_C, X2.DATA_RECEBEU_ARTE_C, X2.DATA_CANCELAMENTO_C, X2.OBS_PROCESSAMENTO_C,
X2.HORAS_TOTAIS, X2.MINUTOS_TOTAIS, X2.ID_HORARIO_D, X2.JORNADA_VALIDADA, X2.BM, X2.TIPO_JORNADA, X2.JORNADA, X2.DURACAO_AULA, X2.DATA_INICIO, X2.DATA_FIM, X2.COD_ORGAO, X2.NOM_OFIC_ESCL, X2.TURNO_D, X2.HORA_INI_TURNO, X2.HORA_FIM_TURNO, X2.SEGUNDA, X2.INTERVALO_SEGUNDA, X2.TERCA, X2.INTERVALO_TERCA, X2.QUARTA, X2.INTERVALO_QUARTA, X2.QUINTA, X2.INTERVALO_QUINTA, X2.SEXTA, X2.INTERVALO_SEXTA, X2.COORDENACAO, X2.REGIONAL, X2.LOCAL, X2.BM_ULTIMA_ALTERACAO, X2.DATA_ULT_ALTERACAO, X2.DATA_RECEBEU_ARTE, X2.DATA_PROCESSAMENTO, X2.OBS_PROCESSAMENTO, X2.SERA_INTEGRADO, X2.CAMPOS_IMPORTANTES_INVALIDOS, X2.CAMPOS_OBRIGATORIOS_NULOS, X2.ERRO_CARGA_HORARIA, X2.ERRO_INTERVALO_TURNO, X2.SITUACAO_JORNADA, X2.DT_REAL_ULT_DIA_TRABALHADO, X2.QTD_REG_MESMO_ID_HORARIO, X2.INICIO_JORNADA, X2.FIM_JORNADA, X2.TIPO_REGISTRO, 

X2.DADOS_ARTERH, X2.ID_JORNADA_E, X2.DT_CANCELAMENTO_E, X2.HORAS_SEMANAIS,
X2.ORIGEM, X2.TIPO_EXTENSAO, X2.ID_REGISTRO_ARQUIVO_D, X2.CODIGO_EMPRESA, X2.BM_SERVIDOR_E, X2.NOME_SERVIDOR_E, X2.CODIGO_CONTRATO_SGE_E, X2.DT_INICIO, X2.DT_FIM, X2.DT_RECEBEU_CADASTRO, X2.DT_RECEBEU_CANCELAMENTO, X2.TOTAL_DIAS, X2.MESMO_LOCAL_DA_PRINCIPAL, X2.MESMO_TURNO_DA_PRINCIPAL, X2.TURNO_E, X2.COD_ESCALA, X2.COD_LOCAL1, X2.COD_LOCAL2, X2.COD_LOCAL3, X2.COD_LOCAL4, X2.COD_LOCAL5, X2.COD_LOCAL6, X2.NOME_ESCOLA_E, X2.MOTIVO_E, X2.DISCIPLINA_MINISTRADA_E, 
X2.HORARIO_INICIO_SEGUNDA, X2.HORARIO_FIM_SEGUNDA,  X2.TOTAL_SEGUNDA,
X2.HORARIO_INICIO_TERCA, X2.HORARIO_FIM_TERCA, X2.TOTAL_TERCA,
X2.HORARIO_INICIO_QUARTA, X2.HORARIO_FIM_QUARTA, X2.TOTAL_QUARTA,
X2.HORARIO_INICIO_QUINTA, X2.HORARIO_FIM_QUINTA, X2.TOTAL_QUINTA,
X2.HORARIO_INICIO_SEXTA, X2.HORARIO_FIM_SEXTA, X2.TOTAL_SEXTA,
SUBSTR(X2.TOTAL_SEGUNDA+X2.TOTAL_TERCA+X2.TOTAL_QUARTA+X2.TOTAL_QUINTA+X2.TOTAL_SEXTA,12,5) TOTAL_SEMANA_5_DIAS,
X2.HORARIO_INICIO_SABADO, X2.HORARIO_FIM_SABADO, X2.HORARIO_INICIO_DOMINGO, X2.HORARIO_FIM_DOMINGO, X2.CODIGO_ESCOLA_E, X2.DT_CRIACAO_VERBA, X2.DT_CANCELAMENTO_VERBA, X2.TIPO_CONTRATO, X2.DT_CRIACAO_SGE_E, X2.DT_CANCELAMENTO_SGE_E, X2.FAZ_JUS_VALE_REF_E, X2.REQUER_VALE_REF_E, X2.OBSERVACAO_E, X2.ID_HORARIO_E
FROM(
SELECT 
X.HORAS_TOTAIS+X.MINUTOS_TOTAIS HM_TOTAIS
,TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60) HTOTAIS
,((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)-(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60)*60)) FRACAO_MIN_TOTAIS
,LPAD(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60),2,0)||':'||LPAD(((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)-(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60)*60)),2,0) CARGA_HORARIA_CHEIA

,CASE WHEN X.DURACAO_AULA = '01:00' THEN 60 WHEN X.DURACAO_AULA = '01:30' THEN 90 ELSE 0 END TOTAL_MINUTOS_AULA--NOVO 16/8/23
,X.H_INICIO_TURNO * 60 + X.M_INICIO_TURNO MINUTOS_NO_DIA_INI_TURNO--NOVO 16/8/23
,CASE WHEN X.SEGUNDA IS NULL THEN 0 ELSE LENGTH(X.SEGUNDA)- REGEXP_COUNT(X.SEGUNDA,',')END AULAS_SEG--NOVO 16/8/23
,CASE WHEN X.SEGUNDA IS NULL THEN '0' ELSE SUBSTR(X.SEGUNDA,1,1)END PRIMEIRA_AULA_SEG--NOVO 16/8/23
,CASE WHEN X.TERCA IS NULL THEN 0 ELSE LENGTH(X.TERCA)- REGEXP_COUNT(X.TERCA,',')END AULAS_TER--NOVO 16/8/23
,CASE WHEN X.TERCA IS NULL THEN '0' ELSE SUBSTR(X.TERCA,1,1)END PRIMEIRA_AULA_TER--NOVO 16/8/23
,CASE WHEN X.QUARTA IS NULL THEN 0 ELSE LENGTH(X.QUARTA)- REGEXP_COUNT(X.QUARTA,',')END AULAS_QUA--NOVO 16/8/23
,CASE WHEN X.QUARTA IS NULL THEN '0' ELSE SUBSTR(X.QUARTA,1,1)END PRIMEIRA_AULA_QUA--NOVO 16/8/23
,CASE WHEN X.QUINTA IS NULL THEN 0 ELSE LENGTH(X.QUINTA)- REGEXP_COUNT(X.QUINTA,',')END AULAS_QUI--NOVO 16/8/23
,CASE WHEN X.QUINTA IS NULL THEN '0' ELSE SUBSTR(X.QUINTA,1,1)END PRIMEIRA_AULA_QUI--NOVO 16/8/23
,CASE WHEN X.SEXTA IS NULL THEN 0 ELSE LENGTH(X.SEXTA)- REGEXP_COUNT(X.SEXTA,',')END AULAS_SEX--NOVO 16/8/23
,CASE WHEN X.SEXTA IS NULL THEN '0' ELSE SUBSTR(X.SEXTA,1,1)END PRIMEIRA_AULA_SEX--NOVO 16/8/23

,X.* FROM (
--SELECT X.CENARIO_GERAL, X.CENARIO_CANCELAMENTO, COUNT(1)QTD FROM ( --SINTETICO
SELECT CASE 
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL THEN '1.1-REGISTRO_EM_AMBOS_PROCESSOS_DENTRO_ARTERH'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS NOT NULL THEN '2.1-REGISTRO_APENAS_ARQUIVO_ANTIGO_DENTRO_ARTERH'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL THEN '3.1-REGISTRO_APENAS_VIEW_NOVA_DENTRO_ARTERH'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NULL THEN '1.2-REGISTRO_EM_AMBOS_PROCESSOS_FORA_ARTERH'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS NULL THEN '2.2-REGISTRO_APENAS_ARQUIVO_ANTIGO_FORA_ARTERH_NAO_SERA_CADASTRADA_AVALIAR'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NULL THEN '3.2-REGISTRO_APENAS_VIEW_NOVA_FORA_ARTERH'
END CENARIO_GERAL,
CASE 
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND A.CANCELAMENTO IS     NULL AND D.DT_CANCELAMENTO_USAR IS     NULL THEN '1.1.1-FAZER_NADA'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND (A.CANCELAMENTO IS NOT NULL OR D.DT_CANCELAMENTO_USAR IS NOT NULL) AND E.DT_CANCELAMENTO IS NOT NULL THEN '1.1.2.1-_JA_CANCELADA'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND (A.CANCELAMENTO IS NOT NULL OR D.DT_CANCELAMENTO_USAR IS NOT NULL) AND E.DT_CANCELAMENTO IS     NULL THEN '1.1.2.2-IRA_GRAVAR_CANCELAMENTO'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS NOT NULL AND A.CANCELAMENTO    IS     NULL THEN '2.1.1-FAZER_NADA'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS NOT NULL AND A.CANCELAMENTO    IS NOT NULL AND E.DT_CANCELAMENTO IS NOT NULL THEN '2.1.2.1-JA_CANCELADA'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS NOT NULL AND A.CANCELAMENTO    IS NOT NULL AND E.DT_CANCELAMENTO IS     NULL THEN '2.1.2.2-IRA_GRAVAR_CANCELAMENTO'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND D.DT_CANCELAMENTO_USAR IS     NULL THEN '3.1.1-A_PRINCIPIO_JA_CADASTRADA_PELA_VIEW_FAZER_NADA'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND D.DT_CANCELAMENTO_USAR IS NOT NULL AND E.DT_CANCELAMENTO IS NOT NULL THEN '3.1.2.1-A_PRINCIPIO_JA_CADASTRADA_PELA_VIEW_E_JA_CANCELADA'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS NOT NULL AND D.DT_CANCELAMENTO_USAR IS NOT NULL AND E.DT_CANCELAMENTO IS     NULL THEN '3.1.2.2-A_PRINCIPIO_JA_CADASTRADA_PELA_VIEW_IRA_GRAVAR_CANCELAMENTO'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS     NULL AND D.DT_CANCELAMENTO_USAR IS     NULL THEN '1.2.1-A_PRINCIPIO_SERA_CADASTRADA_PELA_VIEW'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS     NULL AND D.DT_CANCELAMENTO_USAR IS NOT NULL THEN '1.2.2-A_PRINCIPIO_SERA_CADASTRADA_JA_CANCELADA_PELA_VIEW'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS     NULL AND A.CANCELAMENTO    IS     NULL THEN '2.2.1-NAO_SERA_CADASTRADA_AVALIAR'
WHEN A.ID_JORNADA IS NOT NULL AND D.ID_JORNADA IS     NULL AND E.ID_JORNADA IS     NULL AND A.CANCELAMENTO    IS NOT NULL THEN '2.2.2-NAO_SERA_CADASTRADA_JA_CANCELADA_AVALIAR'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS     NULL AND D.DT_CANCELAMENTO_USAR IS     NULL THEN '3.2.1-A_PRINCIPIO_SERA_CADASTRADA_PELA_VIEW'
WHEN A.ID_JORNADA IS     NULL AND D.ID_JORNADA IS NOT NULL AND E.ID_JORNADA IS     NULL AND D.DT_CANCELAMENTO_USAR IS NOT NULL THEN '3.2.2-A_PRINCIPIO_SERA_CADASTRADA_JA_CANCELADA_PELA_VIEW'
END CENARIO_CANCELAMENTO,
'DADOS_ARQUIVO' DADOS_ARQUIVO, 
A.ID_JORNADA, A.CANCELAMENTO, A.HORAS, A.ID_REGISTRO_ARQUIVO, A.CODIGO_CONTRATO_SGE, A.BM_SERVIDOR, A.NOME_SERVIDOR, A.CODIGO_ESCOLA, A.NOME_ESCOLA, A.MOTIVO, A.INICIO, A.FIM, A.DIAS,  A.TURNO, A.DISCIPLINA_MINISTRADA, A.INICIO_SEGUNDA, A.FIM_SEGUNDA, A.INICIO_TERCA, A.FIM_TERCA, A.INICIO_QUARTA, A.FIM_QUARTA, A.INICIO_QUINTA, A.FIM_QUINTA, A.INICIO_SEXTA, A.FIM_SEXTA, A.INICIO_SABADO, A.FIM_SABADO, A.INICIO_DOMINGO, A.FIM_DOMINGO, A.FAZ_JUS_VALE_REF, A.REQUER_VALE_REF, A.DT_CRIACAO_SGE, A.DT_CANCELAMENTO_SGE, A.OBSERVACAO, A.ID_HORARIO, 
'DADOS_DBLINK' DADOS_DBLINK, 
--D.ID_JORNADA ID_JORNADA_D, D.DT_CANCELAMENTO, D.CARGA_HORARIA, D.ID_HORARIO ID_HORARIO_D, D.BM, D.TIPO_JORNADA, D.JORNADA, D.TURNO TURNO_D, D.SEGUNDA, D.TERCA, D.QUARTA, D.QUINTA, D.SEXTA, D.DURACAO_AULA,  D.EXTRA_CLASSE, D.DAT_INICIO, D.DAT_FIM, D.REGIONAL, D.COD_ORGAO, D.NOM_OFIC_ESCL, D.NOM_LOCA, D.BM_ULTIMA_ALTERACAO, D.DT_ULTIMA_ALTERACAO, D.INICIO_JORNADA, D.FIM_JORNADA,  D.HOR_INIC, D.HOR_FIM, D.COORDENADOR, D.HORARIO_ENTRADA_SEGUNDA, D.HORARIO_ENTRADA_TERCA, D.HORARIO_ENTRADA_QUARTA, D.HORARIO_ENTRADA_QUINTA, D.HORARIO_ENTRADA_SEXTA, D.JORNADA_VALIDADA,  
D.ID_JORNADA ID_JORNADA_D,  D.DT_CANCELAMENTO_USAR, D.CARGA_HORARIA, 
D.QTD_REG_PASSO_2, D.STATUS_REGISTRO_C, D.DATA_RECEBEU_ARTE_C, D.DATA_CANCELAMENTO_C, D.OBS_PROCESSAMENTO_C,
CASE WHEN D.CARGA_HORARIA = '22:30' THEN 1320
ELSE ((SUBSTR(D.CARGA_HORARIA,1,2)+ (SUBSTR(D.CARGA_HORARIA,1,2)/2)))*60 + (MOD((TRUNC((SUBSTR(D.CARGA_HORARIA,1,2)+ (SUBSTR(D.CARGA_HORARIA,1,2)/2))))*60,2)*60)*60 
END HORAS_TOTAIS,
CASE WHEN D.CARGA_HORARIA = '22:30' THEN 30 
    WHEN D.CARGA_HORARIA <> '22:30' AND SUBSTR(D.CARGA_HORARIA,4,2) = '00' THEN 0 
ELSE SUBSTR(D.CARGA_HORARIA,4,2)+ (SUBSTR(D.CARGA_HORARIA,4,2)/2) END MINUTOS_TOTAIS,
D.ID_HORARIO ID_HORARIO_D, D.JORNADA_VALIDADA, D.BM, D.TIPO_JORNADA, D.JORNADA, D.DURACAO_AULA,  D.DATA_INICIO, D.DATA_FIM, D.COD_ORGAO, D.NOM_OFIC_ESCL, D.TURNO TURNO_D, D.HORA_INI_TURNO, D.HORA_FIM_TURNO,
CASE WHEN LTRIM(SUBSTR(D.HORA_INI_TURNO,1,2),0) IS NULL OR LENGTH(D.HORA_INI_TURNO)<> 5 THEN '0' ELSE LTRIM(SUBSTR(D.HORA_INI_TURNO,1,2),0)END H_INICIO_TURNO,--NOVO 16/8/23
CASE WHEN LTRIM(SUBSTR(D.HORA_INI_TURNO,4,2),0) IS NULL OR LENGTH(D.HORA_INI_TURNO)<> 5 THEN '0' ELSE LTRIM(SUBSTR(D.HORA_INI_TURNO,4,2),0)END M_INICIO_TURNO,--NOVO 16/8/23
D.SEGUNDA, D.INTERVALO_SEGUNDA, D.TERCA, D.INTERVALO_TERCA, D.QUARTA, D.INTERVALO_QUARTA, D.QUINTA, D.INTERVALO_QUINTA, D.SEXTA, D.INTERVALO_SEXTA, D.COORDENACAO, D.REGIONAL, D.LOCAL, D.BM_ULTIMA_ALTERACAO, D.DATA_ULT_ALTERACAO, D.DATA_RECEBEU_ARTE, D.DATA_PROCESSAMENTO, D.OBS_PROCESSAMENTO, D.SERA_INTEGRADO, D.CAMPOS_IMPORTANTES_INVALIDOS, D.CAMPOS_OBRIGATORIOS_NULOS, D.ERRO_CARGA_HORARIA, D.ERRO_INTERVALO_TURNO, D.SITUACAO_JORNADA, D.DT_REAL_ULT_DIA_TRABALHADO, D.QTD_REG_MESMO_ID_HORARIO, D.INICIO_JORNADA, D.FIM_JORNADA, D.TIPO_REGISTRO,
'DADOS_ARTERH' DADOS_ARTERH, 
E.ID_JORNADA ID_JORNADA_E, E.DT_CANCELAMENTO DT_CANCELAMENTO_E, E.HORAS_SEMANAIS,
E.ORIGEM, E.TIPO_EXTENSAO,  E.ID_REGISTRO_ARQUIVO ID_REGISTRO_ARQUIVO_D, E.CODIGO_EMPRESA, E.BM_SERVIDOR BM_SERVIDOR_E, E.NOME_SERVIDOR NOME_SERVIDOR_E, E.CODIGO_CONTRATO_SGE CODIGO_CONTRATO_SGE_E, E.DT_INICIO, E.DT_FIM,  
E.DT_RECEBEU_CADASTRO, E.DT_RECEBEU_CANCELAMENTO, E.TOTAL_DIAS, E.MESMO_LOCAL_DA_PRINCIPAL, E.MESMO_TURNO_DA_PRINCIPAL, E.TURNO TURNO_E, E.COD_ESCALA, E.COD_LOCAL1, E.COD_LOCAL2, E.COD_LOCAL3, E.COD_LOCAL4, E.COD_LOCAL5, E.COD_LOCAL6, 
E.NOME_ESCOLA NOME_ESCOLA_E, E.MOTIVO MOTIVO_E, E.DISCIPLINA_MINISTRADA DISCIPLINA_MINISTRADA_E, 
E.HORARIO_INICIO_SEGUNDA, E.HORARIO_FIM_SEGUNDA,
CASE WHEN E.HORARIO_INICIO_SEGUNDA IS NOT NULL AND E.HORARIO_FIM_SEGUNDA IS NOT NULL THEN E.HORARIO_FIM_SEGUNDA-E.HORARIO_INICIO_SEGUNDA ELSE E.DT_RECEBEU_CADASTRO-E.DT_RECEBEU_CADASTRO END TOTAL_SEGUNDA,
E.HORARIO_INICIO_TERCA, E.HORARIO_FIM_TERCA,
CASE WHEN E.HORARIO_INICIO_TERCA IS NOT NULL AND E.HORARIO_FIM_TERCA IS NOT NULL THEN E.HORARIO_FIM_TERCA-E.HORARIO_INICIO_TERCA  ELSE E.DT_RECEBEU_CADASTRO-E.DT_RECEBEU_CADASTRO END TOTAL_TERCA,
E.HORARIO_INICIO_QUARTA, E.HORARIO_FIM_QUARTA, 
CASE WHEN E.HORARIO_INICIO_QUARTA IS NOT NULL AND E.HORARIO_FIM_QUARTA IS NOT NULL THEN E.HORARIO_FIM_QUARTA-E.HORARIO_INICIO_QUARTA  ELSE E.DT_RECEBEU_CADASTRO-E.DT_RECEBEU_CADASTRO END TOTAL_QUARTA,
E.HORARIO_INICIO_QUINTA, E.HORARIO_FIM_QUINTA,
CASE WHEN E.HORARIO_INICIO_QUINTA IS NOT NULL AND E.HORARIO_FIM_QUINTA IS NOT NULL THEN E.HORARIO_FIM_QUINTA-E.HORARIO_INICIO_QUINTA  ELSE E.DT_RECEBEU_CADASTRO-E.DT_RECEBEU_CADASTRO  END TOTAL_QUINTA,
E.HORARIO_INICIO_SEXTA, E.HORARIO_FIM_SEXTA, 
CASE WHEN E.HORARIO_INICIO_SEXTA IS NOT NULL AND E.HORARIO_FIM_SEXTA IS NOT NULL THEN E.HORARIO_FIM_SEXTA-E.HORARIO_INICIO_SEXTA  ELSE E.DT_RECEBEU_CADASTRO-E.DT_RECEBEU_CADASTRO END TOTAL_SEXTA,
E.HORARIO_INICIO_SABADO, E.HORARIO_FIM_SABADO, E.HORARIO_INICIO_DOMINGO, E.HORARIO_FIM_DOMINGO, 
E.CODIGO_ESCOLA CODIGO_ESCOLA_E, E.DT_CRIACAO_VERBA, E.DT_CANCELAMENTO_VERBA, E.TIPO_CONTRATO, E.DT_CRIACAO_SGE DT_CRIACAO_SGE_E, E.DT_CANCELAMENTO_SGE DT_CANCELAMENTO_SGE_E, 
E.FAZ_JUS_VALE_REF FAZ_JUS_VALE_REF_E, E.REQUER_VALE_REF REQUER_VALE_REF_E, E.OBSERVACAO OBSERVACAO_E, E.ID_HORARIO ID_HORARIO_E
FROM 
(SELECT A.* FROM PONTO_ELETRONICO.SMARH_INT_PONTO_SGE_ARQUIVOS A WHERE A.id_horario = vID_HORARIO ORDER BY ID_REGISTRO_ARQUIVO) A -------*********************TROCAR SEMPRE O CODIGO PARA A DATA DO DIA APOS IMPORTAR ARQUIVO DA SMED ENVIADO --11894 reg 15/9

FULL OUTER JOIN
--TROQUEI 17/9/23--(SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_GERAL WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' AND JORNADA = 'EXTENSÃO' ORDER BY ID_JORNADA)D--alterado de dblink para tabela passo 1--(SELECT * FROM SGE_PROD.HORARIO_TRABALHO_IFPONTO@LK_SGE_SIRH.PBH WHERE JORNADA = 'EXTENSÃO' ORDER BY ID_JORNADA)D 
(
SELECT A.QTD_REG_PASSO_2, C.STATUS_REGISTRO_C, C.DATA_RECEBEU_ARTE_C, C.DATA_CANCELAMENTO_C, C.OBS_PROCESSAMENTO_C, G.* FROM
(SELECT ROW_NUMBER() OVER(PARTITION BY ID_JORNADA ORDER BY ID_JORNADA, DATA_PROCESSAMENTO DESC)ORDEM_ID_JORNADA, X.* FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_GERAL X WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' AND JORNADA = 'EXTENSÃO' 
AND TO_DATE(DATA_INICIO,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
ORDER BY ID_JORNADA, data_recebeu_arte DESC
)G LEFT OUTER JOIN (
SELECT ID_JORNADA_U ID_JORNADA_A, COUNT(1)QTD_REG_PASSO_2 FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES X WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' 
AND TO_DATE(DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
GROUP BY ID_JORNADA_U --1246+1746=2992 2650 ID_JORNADA DISTITINTOS, OU SEJA HOUVE CADASTRO E DEPOIS CANCELAMENTO DE 342 JORNADAS INICIALMENTE NO PASSO 2
)A ON A.ID_JORNADA_A = G.ID_JORNADA
LEFT OUTER JOIN(
SELECT A.ID_JORNADA_C, A.STATUS_REGISTRO_C, A.DATA_RECEBEU_ARTE_C, A.DATA_CANCELAMENTO_C, A.OBS_PROCESSAMENTO_C FROM(
SELECT ROW_NUMBER() OVER(PARTITION BY ID_JORNADA_U ORDER BY ID_JORNADA_U, DATA_PROCESSAMENTO DESC)ORDEM_ID_JORNADA,
X.ID_JORNADA_U ID_JORNADA_C, X.STATUS_REGISTRO STATUS_REGISTRO_C, X.DATA_RECEBEU_ARTE_U DATA_RECEBEU_ARTE_C, X.DT_CANCELAMENTO_USAR_U DATA_CANCELAMENTO_C, X.OBS_PROCESSAMENTO OBS_PROCESSAMENTO_C
FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES X WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' 
AND TO_DATE(DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
ORDER BY ID_JORNADA_U, DATA_PROCESSAMENTO DESC)A WHERE A.ORDEM_ID_JORNADA = 2 --342
)C ON C.ID_JORNADA_C = G.ID_JORNADA WHERE G.ORDEM_ID_JORNADA = 1 --5126 EXTENSOES ORDER BY G.ID_JORNADA
)D
ON A.ID_JORNADA = D.ID_JORNADA

FULL OUTER JOIN 
(SELECT CASE WHEN TIPO_EXTENSAO = 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' THEN 'ARQUIVO_ANTIGO' ELSE 'VIEW_NOVA' END ORIGEM, E.* FROM SMARH_INT_PE_EXTENSOES_JORNAD E WHERE TRUNC(DT_INICIO) >= TO_DATE(vDATA_INICIO,'DD/MM/YYYY')ORDER BY E.ID_JORNADA)E --11787 18/9
ON A.ID_JORNADA = E.ID_JORNADA
ORDER BY CENARIO_GERAL, CENARIO_CANCELAMENTO, A.ID_JORNADA, D.ID_JORNADA

--)X GROUP BY X.cENARIO_GERAL, X.CENARIO_CANCELAMENTO ORDER BY X.CENARIO_GERAL, X.CENARIO_CANCELAMENTO --SINTETICO

)X
)X2
---------------------INICIO CONCOMITANCIAS
LEFT OUTER JOIN 
(SELECT DP.ID_HORARIO, COUNT(1)QTD_CONCOMITA FROM(
select CPF, BM_U, TIPO_JORNADA_U, TURNO_U, DATA_INICIO_U, DATA_FIM_U, DT_CANCELAMENTO_USAR_U, ID_HORARIO, NOM_OFIC_ESCL, REGIONAL from( SELECT X.TIPO, X.CPF, X.BM_U,X.TIPO_JORNADA_U,X.TURNO_U,X.DATA_INICIO_U,X.DATA_FIM_U, X.DT_CANCELAMENTO_USAR_U, X.NOM_OFIC_ESCL, X.REGIONAL,
X.ORDEM_TURNO,X.ORDEM_ID_HORARIO_DIA,X.ORDEM_PAR_REG,X.ORDEM_DIA_CPF,X.ID_HORARIO,X.DATA, X.SEMANA_ANO, X.INICIO_TURNO,X.INICIO_REGENCIA,X.FIM_REGENCIA,X.DATA_PROCESSAMENTO,X.OBS_PROCESSAMENTO
FROM(SELECT  A.BM_U, A.TIPO_JORNADA_U, A.TURNO_U, A.DATA_INICIO_U, A.DATA_FIM_U, A.DT_CANCELAMENTO_USAR_U, A.NOM_OFIC_ESCL, A.REGIONAL,
CASE WHEN A.TURNO_U = 'MANHÃ' THEN 1 WHEN A.TURNO_U = 'INTEGRAL' THEN 1 WHEN A.TURNO_U = 'TARDE' THEN 2 WHEN A.TURNO_U = 'NOITE' THEN 3 END ORDEM_TURNO,
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.ID_HORARIO, D.DATA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_ID_HORARIO_DIA, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.ID_HORARIO, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.FIM_REGENCIA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_PAR_REG, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.DATA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_DIA_CPF, 
TO_NUMBER(TO_CHAR(TO_DATE(D.DATA),'WW')) SEMANA_ANO, D.* FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS D LEFT OUTER JOIN (SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES  WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' 
AND TO_DATE(DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
)A ON A.ID_HORARIO = D.ID_HORARIO
LEFT OUTER JOIN (SELECT M.CODIGO_EMPRESA, M.TIPO_CONTRATO, M.CODIGO_CONTRATO, M.CODIGO_PESSOA, P.CPF FROM ARTERH.RHPESS_CONTR_MEST M LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P ON P.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND P.CODIGO = M.CODIGO_PESSOA)P
ON P.CODIGO_EMPRESA = '0001' AND P.TIPO_CONTRATO = '0001' AND P.CODIGO_CONTRATO = A.BM_U WHERE D.ID_HORARIO IN (SELECT ID_HORARIO FROM(SELECT ID_HORARIO, COUNT(1) FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES
GROUP BY ID_HORARIO)) AND D.OBS_PROCESSAMENTO IN ('CONCOMITA') AND D.TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC )X )group by CPF, BM_U, TIPO_JORNADA_U, TURNO_U, DATA_INICIO_U, DATA_FIM_U, DT_CANCELAMENTO_USAR_U, ID_HORARIO, NOM_OFIC_ESCL, REGIONAL
)DP GROUP BY DP.ID_HORARIO
)DP ON DP.ID_HORARIO = X2.ID_HORARIO_D
---------------------FIM CONCOMITANCIAS

WHERE X2.QTD_REG_PASSO_2 IS NOT NULL --APENAS REGISTROS NA LOGICA NOVA

)X3
)X4
)X5
WHERE X5.COMPARA_HORAS_DIA_SEMANA = 'ERRO' AND X5.ID_JORNADA_E IS NOT NULL---APENAS OS REGISTROS ERRADOS

--)GROUP BY CENARIO_FINAL_ID_JORNADA, CENARIO_FINAL_CANCELAMENTO, CENARIO_FINAL_TOTAL_SEMANA ORDER BY CENARIO_FINAL_ID_JORNADA, CENARIO_FINAL_CANCELAMENTO, CENARIO_FINAL_TOTAL_SEMANA--SINTETICO


)LOOP
vCONTADOR := vCONTADOR +1;

dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' UPDATE C1.ID_JORNADA_E: '||C1.ID_JORNADA_E||' C1.ID_HORARIO_E: '||C1.ID_HORARIO_E||' C1.ID_REGISTRO_ARQUIVO: '||C1.ID_REGISTRO_ARQUIVO );
--/*

IF C1.H_INICIO_SEGUNDA< 24 AND C1.H_FIM_SEGUNDA< 24 AND C1.H_INICIO_TERCA< 24 AND C1.H_FIM_TERCA< 24 AND C1.H_INICIO_QUARTA< 24 AND C1.H_FIM_QUARTA< 24 AND C1.H_INICIO_QUINTA< 24 AND C1.H_FIM_QUINTA< 24 AND C1.H_INICIO_SEXTA< 24 AND C1.H_FIM_SEXTA< 24
THEN--CONDICAO IF NOVA EM 16/10/23
UPDATE PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD 
SET TIPO_EXTENSAO = 'EXTENSAO_SGE_DE_PARA_2023_PR_SGE_DP11', 
HORARIO_INICIO_SEGUNDA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_SEGUNDA,2,0)||':'||LPAD(C1.M_INICIO_SEGUNDA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_SEGUNDA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_SEGUNDA,2,0)||':'||LPAD(C1.M_FIM_SEGUNDA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_TERCA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_TERCA,2,0)||':'||LPAD(C1.M_INICIO_TERCA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),   
HORARIO_FIM_TERCA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_TERCA,2,0)||':'||LPAD(C1.M_FIM_TERCA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_QUARTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_QUARTA,2,0)||':'||LPAD(C1.M_INICIO_QUARTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_QUARTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_QUARTA,2,0)||':'||LPAD(C1.M_FIM_QUARTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_QUINTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_QUINTA,2,0)||':'||LPAD(C1.M_INICIO_QUINTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_QUINTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_QUINTA,2,0)||':'||LPAD(C1.M_FIM_QUINTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),  
HORARIO_INICIO_SEXTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_SEXTA,2,0)||':'||LPAD(C1.M_INICIO_SEXTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_SEXTA = TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_SEXTA,2,0)||':'||LPAD(C1.M_FIM_SEXTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') 
WHERE ID_JORNADA = C1.ID_JORNADA_E AND ID_HORARIO = C1.ID_HORARIO_E AND C1.TIPO_EXTENSAO LIKE '%EXTENSAO_SGE_DE_PARA_2023%' AND TRUNC(DT_RECEBEU_CADASTRO) = TRUNC(SYSDATE) AND ID_REGISTRO_ARQUIVO = C1.ID_REGISTRO_ARQUIVO_D; COMMIT;
END IF;
--*/

END LOOP;
END;

END;
--*/
