
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP12_AJUSTE_EXTRA_P3" 
AS 
BEGIN 

--Kellysson em 22/1/24 baseado (sql_ajuste_extraclasse_erro_DE_PARA_EXTENSOES_2024_p3_v1.sql)

--kellysson --em 10/1/24 --- criado o (sql_ajuste_extraclasse_erro_DE_PARA_EXTENSOES_2024_v1.sql)basedo no (sql_apoio_ajuste_extraclasse_erro_nov-23.sql) para ajustar ligacao das tabelas com campos DATA_PROCESSAMENTO e DT_RECEBEU_CADASTRO
--b3 para ajustes gerais direto dados SGE--12º PASSO  novo em 18/9/23 ---ajuste horas individuais na semana ---SEMPRE ACOMPANHAR SE NAO TERMINA OU POR QUE GERA NOVOS CASOS--sql_ajuste_horas_dia_DE_PARA_EXTENSOES_2023_b1.sql>sql_ajuste_horas_dia_DE_PARA_EXTENSOES_2023_b2.sql 
--X.TIPO_EXTENSAO <> 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' AND (X.HORAS_SEGUNDA > '+00 04:30:00' OR X.HORAS_TERCA > '+00 04:30:00' OR X.HORAS_QUARTA > '+00 04:30:00' OR X.HORAS_QUINTA > '+00 04:30:00' OR X.HORAS_SEXTA > '+00 04:30:00')

---b2 em 25/10/23 devido campo CANCELAMENTO_USAR
--Kellysson em 18/9/23 12º PASSO --novo em 18/9/23 ---ajuste horas individuais na semana (sql_ajuste_horas_dia_DE_PARA_EXTENSOES_2023_b1.sql)
--Kellysson em 5/9/23 b2 (sql_ajuste_DE_PARA_EXTENSOES_2023_b2.sql) para ajuste DATA_INICIO_U E DATA_FIM_U pARA INICIO_JORNADA_U e FIM_JORNADA_U
--Kellysson em 16/8/23 baseado (sql_relatorio_pos_passo8_DE-PARA.sql)
--9º PASSO TEMPORARIO OU NAO PARA O DE/PARA EM CASOS QUE NO FINAL DO PASSO 8 NAO BATEU A QUANTIDADE DE HORAS/MINUTOS NA SEMANA

--/*
DECLARE 
vCONTADOR NUMBER;
vB BOOLEAN := TRUE;

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
--*/

--/*---inicio-- terceira parte para comentar parar rodar os blocos deste arquivo
----inicio-------------------analise GETED antes de rodar o 3º passo-------------------------------------------------------------------------------------------------------------
--SELECT COUNT(1) FROM (

FOR C1 IN (

SELECT 
CASE WHEN X3.ORDEM_CENARIO_CADASTRO_AULAS = X3.ORDEM_CENARIO_CONFIG_AULAS THEN 'PRIMEIRA_CONFIGURACAO' ELSE 'DEMAIS_CONFIGURACOES' END COMPARA_CAD_CONF_AULAS, 
X3.* FROM (
SELECT 
X2.DADOS_POSSIVEL_ERRO, 
ROW_NUMBER() OVER (PARTITION BY X2.COORDENACAO, X2.DURACAO_AULA, X2.CARGA_HORARIA, X2.HORA_INI_TURNO, X2.HORA_FIM_TURNO, X2.SEGUNDA, X2.INTERVALO_SEGUNDA, X2.TERCA, X2.INTERVALO_TERCA, X2.QUARTA, X2.INTERVALO_QUARTA,
X2.QUINTA, X2.INTERVALO_QUINTA, X2.SEXTA, X2.INTERVALO_SEXTA
,X2.HORARIO_INICIO_SEGUNDA, X2.HORARIO_FIM_SEGUNDA, X2.HORARIO_INICIO_TERCA, X2.HORARIO_FIM_TERCA, X2.HORARIO_INICIO_QUARTA, X2.HORARIO_FIM_QUARTA, X2.HORARIO_INICIO_QUINTA, X2.HORARIO_FIM_QUINTA, X2.HORARIO_INICIO_SEXTA, X2.HORARIO_FIM_SEXTA
ORDER BY X2.COORDENACAO ,DURACAO_AULA, X2.CARGA_HORARIA, X2.HORA_INI_TURNO, X2.HORA_FIM_TURNO ,SEGUNDA, X2.INTERVALO_SEGUNDA, X2.TERCA, X2.INTERVALO_TERCA ,QUARTA, X2.INTERVALO_QUARTA, X2.QUINTA, X2.INTERVALO_QUINTA,
X2.SEXTA, X2.INTERVALO_SEXTA, X2.ID_JORNADA
,X2.HORARIO_INICIO_SEGUNDA, X2.HORARIO_FIM_SEGUNDA, X2.HORARIO_INICIO_TERCA, X2.HORARIO_FIM_TERCA, X2.HORARIO_INICIO_QUARTA, X2.HORARIO_FIM_QUARTA, X2.HORARIO_INICIO_QUINTA, X2.HORARIO_FIM_QUINTA, X2.HORARIO_INICIO_SEXTA, X2.HORARIO_FIM_SEXTA) 
ORDEM_CENARIO_CADASTRO_AULAS,
X2.ID_JORNADA_A, X2.TEMPO_EXCESSO_TOTAL, X2.HORARIO_INICIO_SEGUNDA, X2.HORARIO_FIM_SEGUNDA, X2.TEMPO_EXCEDE_C_EXTRA_SGE_SEG, X2.TEMPO_GRAVADO_SEG, 
X2.HORARIO_INICIO_TERCA, X2.HORARIO_FIM_TERCA, X2.TEMPO_EXCEDE_C_EXTRA_SGE_TER, X2.TEMPO_GRAVADO_TER, X2.HORARIO_INICIO_QUARTA, X2.HORARIO_FIM_QUARTA, X2.TEMPO_EXCEDE_C_EXTRA_SGE_QUA, X2.TEMPO_GRAVADO_QUA, 
X2.HORARIO_INICIO_QUINTA, X2.HORARIO_FIM_QUINTA, X2.TEMPO_EXCEDE_C_EXTRA_SGE_QUI, X2.TEMPO_GRAVADO_QUI, X2.HORARIO_INICIO_SEXTA, X2.HORARIO_FIM_SEXTA, X2.TEMPO_EXCEDE_C_EXTRA_SGE_SEX, X2.TEMPO_GRAVADO_SEX, 
X2.DADOS_NOVOS, 
X2.ID_JORNADA, X2.VHORARIO_INICIO_SEGUNDA, X2.VHORARIO_FIM_SEGUNDA, X2.VMINUTOS_AJUSTADOS_SEG, X2.NOVO_TOTAL_MINUTOS_SEG, X2.VHORARIO_INICIO_TERCA, X2.VHORARIO_FIM_TERCA, X2.VMINUTOS_AJUSTADOS_TER, X2.NOVO_TOTAL_MINUTOS_TER, 
X2.VHORARIO_INICIO_QUARTA, X2.VHORARIO_FIM_QUARTA, X2.VMINUTOS_AJUSTADOS_QUA, X2.NOVO_TOTAL_MINUTOS_QUA, X2.VHORARIO_INICIO_QUINTA, X2.VHORARIO_FIM_QUINTA, X2.VMINUTOS_AJUSTADOS_QUI, X2.NOVO_TOTAL_MINUTOS_QUI, 
X2.VHORARIO_INICIO_SEXTA, X2.VHORARIO_FIM_SEXTA, X2.VMINUTOS_AJUSTADOS_SEX, X2.NOVO_TOTAL_MINUTOS_SEX, 
X2.DADOS_DBLINK_SGE, 
X2.ID_JORNADA_S, X2.ID_HORARIO, X2.ORDEM_CENARIO_CONFIG_AULAS, 
X2.COORDENACAO, X2.DURACAO_AULA, X2.CARGA_HORARIA, X2.HORA_INI_TURNO, X2.HORA_FIM_TURNO, X2.SEGUNDA, X2.INTERVALO_SEGUNDA, X2.TERCA, X2.INTERVALO_TERCA, X2.QUARTA, X2.INTERVALO_QUARTA, X2.QUINTA, X2.INTERVALO_QUINTA, X2.SEXTA, X2.INTERVALO_SEXTA,
X2.JORNADA_VALIDADA, X2.BM, X2.TIPO_JORNADA, X2.JORNADA, X2.DATA_INICIO, X2.DATA_FIM, X2.DATA_CANCELAMENTO, X2.COD_ORGAO, X2.NOM_OFIC_ESCL, X2.TURNO, X2.REGIONAL, X2.LOCAL, X2.BM_ULTIMA_ALTERACAO, X2.DATA_ULT_ALTERACAO, 
X2.DATA_RECEBEU_ARTE, X2.DATA_PROCESSAMENTO, X2.OBS_PROCESSAMENTO, X2.SERA_INTEGRADO, X2.CAMPOS_IMPORTANTES_INVALIDOS, X2.CAMPOS_OBRIGATORIOS_NULOS, X2.ERRO_CARGA_HORARIA, X2.ERRO_INTERVALO_TURNO, X2.SITUACAO_JORNADA, 
X2.DT_REAL_ULT_DIA_TRABALHADO, X2.QTD_REG_MESMO_ID_HORARIO, X2.INICIO_JORNADA, X2.FIM_JORNADA, X2.TIPO_REGISTRO, X2.DATA_INICIO_USAR, X2.DATA_FIM_USAR, X2.DT_VALIDA_CANCELA, X2.DT_CANCELAMENTO_USAR, 
X2.DADOS_ARTERH, 
X2.COD_CARGO_EFETIVO, X2.CARGO_EFETIVO, 
X2.DIAS_ARTE, X2.ORIGEM, X2.TIPO_EXTENSAO, X2.ID_JORNADA_ART, X2.ID_HORARIO_ART, X2.ID_REGISTRO_ARQUIVO, X2.CODIGO_EMPRESA, X2.BM_SERVIDOR, X2.NOME_SERVIDOR, X2.CODIGO_CONTRATO_SGE, X2.DT_INICIO, X2.DT_FIM, X2.DT_CANCELAMENTO, 
X2.DT_RECEBEU_CADASTRO, X2.DT_RECEBEU_CANCELAMENTO, X2.TOTAL_DIAS, X2.MESMO_LOCAL_DA_PRINCIPAL, X2.MESMO_TURNO_DA_PRINCIPAL, 
X2.TURNO_ART, X2.COD_ESCALA, X2.COD_LOCAL1, X2.COD_LOCAL2, X2.COD_LOCAL3, X2.COD_LOCAL4, X2.COD_LOCAL5, X2.COD_LOCAL6, X2.NOME_ESCOLA, X2.MOTIVO, X2.DISCIPLINA_MINISTRADA, X2.HORAS_SEMANAIS, 
X2.HORARIO_INICIO_SEGUNDA_ART, X2.HORARIO_FIM_SEGUNDA_ART, X2.HORARIO_INICIO_TERCA_ART, X2.HORARIO_FIM_TERCA_ART, X2.HORARIO_INICIO_QUARTA_ART, X2.HORARIO_FIM_QUARTA_ART, 
X2.HORARIO_INICIO_QUINTA_ART, X2.HORARIO_FIM_QUINTA_ART, X2.HORARIO_INICIO_SEXTA_ART, X2.HORARIO_FIM_SEXTA_ART, 
X2.HORARIO_INICIO_SABADO, X2.HORARIO_FIM_SABADO, X2.HORARIO_INICIO_DOMINGO, X2.HORARIO_FIM_DOMINGO, X2.CODIGO_ESCOLA, X2.DT_CRIACAO_VERBA, X2.DT_CANCELAMENTO_VERBA, 
X2.TIPO_CONTRATO, X2.DT_CRIACAO_SGE, X2.DT_CANCELAMENTO_SGE, X2.FAZ_JUS_VALE_REF, X2.REQUER_VALE_REF, X2.OBSERVACAO

FROM (
SELECT 
'DADOS_POSSIVEL_ERRO' DADOS_POSSIVEL_ERRO, 
AT.ID_JORNADA_A, AT.TEMPO_EXCESSO_TOTAL, 
CASE WHEN AT.HORARIO_INICIO_SEGUNDA = '00:00' THEN NULL ELSE AT.HORARIO_INICIO_SEGUNDA END HORARIO_INICIO_SEGUNDA, 
CASE WHEN AT.HORARIO_FIM_SEGUNDA = '00:00' THEN NULL ELSE AT.HORARIO_FIM_SEGUNDA END HORARIO_FIM_SEGUNDA, 
AT.TEMPO_EXCEDE_C_EXTRA_SGE_SEG, AT.TEMPO_GRAVADO_SEG,
CASE WHEN AT.HORARIO_INICIO_TERCA = '00:00' THEN NULL ELSE AT.HORARIO_INICIO_TERCA END HORARIO_INICIO_TERCA,  
CASE WHEN AT.HORARIO_FIM_TERCA = '00:00' THEN NULL ELSE AT.HORARIO_FIM_TERCA END HORARIO_FIM_TERCA,  
AT.TEMPO_EXCEDE_C_EXTRA_SGE_TER, AT.TEMPO_GRAVADO_TER, 
CASE WHEN AT.HORARIO_INICIO_QUARTA = '00:00' THEN NULL ELSE AT.HORARIO_INICIO_QUARTA END HORARIO_INICIO_QUARTA, 
CASE WHEN AT.HORARIO_FIM_QUARTA = '00:00' THEN NULL ELSE AT.HORARIO_FIM_QUARTA END HORARIO_FIM_QUARTA, 
AT.TEMPO_EXCEDE_C_EXTRA_SGE_QUA, AT.TEMPO_GRAVADO_QUA,
CASE WHEN AT.HORARIO_INICIO_QUINTA = '00:00' THEN NULL ELSE AT.HORARIO_INICIO_QUINTA END HORARIO_INICIO_QUINTA, 
CASE WHEN AT.HORARIO_FIM_QUINTA = '00:00' THEN NULL ELSE AT.HORARIO_FIM_QUINTA END HORARIO_FIM_QUINTA,
AT.TEMPO_EXCEDE_C_EXTRA_SGE_QUI, AT.TEMPO_GRAVADO_QUI, 
CASE WHEN AT.HORARIO_INICIO_SEXTA = '00:00' THEN NULL ELSE AT.HORARIO_INICIO_SEXTA END HORARIO_INICIO_SEXTA, 
CASE WHEN AT.HORARIO_FIM_SEXTA = '00:00' THEN NULL ELSE AT.HORARIO_FIM_SEXTA END HORARIO_FIM_SEXTA, 
AT.TEMPO_EXCEDE_C_EXTRA_SGE_SEX, AT.TEMPO_GRAVADO_SEX,
'DADOS_NOVOS' DADOS_NOVOS, NV.ID_JORNADA, 
CASE WHEN NV.VHORARIO_INICIO_SEGUNDA IS NOT NULL THEN NV.VHORARIO_INICIO_SEGUNDA ELSE AT.HORARIO_INICIO_SEGUNDA END VHORARIO_INICIO_SEGUNDA, 
CASE WHEN NV.VHORARIO_FIM_SEGUNDA IS NOT NULL THEN NV.VHORARIO_FIM_SEGUNDA ELSE AT.HORARIO_FIM_SEGUNDA END VHORARIO_FIM_SEGUNDA, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_SEG IS NOT NULL THEN NV.VMINUTOS_AJUSTADOS_SEG ELSE NULL END VMINUTOS_AJUSTADOS_SEG, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_SEG < 0 THEN AT.TEMPO_GRAVADO_SEG + NV.VMINUTOS_AJUSTADOS_SEG WHEN NV.VMINUTOS_AJUSTADOS_SEG > 0 THEN NV.VMINUTOS_AJUSTADOS_SEG + AT.TEMPO_GRAVADO_SEG ELSE TO_NUMBER(AT.TEMPO_GRAVADO_SEG) END NOVO_TOTAL_MINUTOS_SEG,

CASE WHEN NV.VHORARIO_INICIO_TERCA IS NOT NULL THEN NV.VHORARIO_INICIO_TERCA ELSE AT.HORARIO_INICIO_TERCA END VHORARIO_INICIO_TERCA, 
CASE WHEN NV.VHORARIO_FIM_TERCA IS NOT NULL THEN NV.VHORARIO_FIM_TERCA ELSE AT.HORARIO_FIM_TERCA END VHORARIO_FIM_TERCA, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_TER IS NOT NULL THEN NV.VMINUTOS_AJUSTADOS_TER ELSE NULL END VMINUTOS_AJUSTADOS_TER, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_TER < 0 THEN AT.TEMPO_GRAVADO_TER + NV.VMINUTOS_AJUSTADOS_TER WHEN NV.VMINUTOS_AJUSTADOS_TER > 0 THEN NV.VMINUTOS_AJUSTADOS_TER + AT.TEMPO_GRAVADO_TER ELSE TO_NUMBER(AT.TEMPO_GRAVADO_TER) END NOVO_TOTAL_MINUTOS_TER,

CASE WHEN NV.VHORARIO_INICIO_QUARTA IS NOT NULL THEN NV.VHORARIO_INICIO_QUARTA ELSE AT.HORARIO_INICIO_QUARTA END VHORARIO_INICIO_QUARTA, 
CASE WHEN NV.VHORARIO_FIM_QUARTA IS NOT NULL THEN NV.VHORARIO_FIM_QUARTA ELSE AT.HORARIO_FIM_QUARTA END VHORARIO_FIM_QUARTA, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_QUA IS NOT NULL THEN NV.VMINUTOS_AJUSTADOS_QUA ELSE NULL END VMINUTOS_AJUSTADOS_QUA,  
CASE WHEN NV.VMINUTOS_AJUSTADOS_QUA < 0 THEN AT.TEMPO_GRAVADO_QUA + NV.VMINUTOS_AJUSTADOS_QUA WHEN NV.VMINUTOS_AJUSTADOS_QUA > 0 THEN NV.VMINUTOS_AJUSTADOS_QUA + AT.TEMPO_GRAVADO_QUA ELSE TO_NUMBER(AT.TEMPO_GRAVADO_QUA) END NOVO_TOTAL_MINUTOS_QUA,

CASE WHEN NV.VHORARIO_INICIO_QUINTA IS NOT NULL THEN NV.VHORARIO_INICIO_QUINTA ELSE AT.HORARIO_INICIO_QUINTA END VHORARIO_INICIO_QUINTA, 
CASE WHEN NV.VHORARIO_FIM_QUINTA IS NOT NULL THEN NV.VHORARIO_FIM_QUINTA ELSE AT.HORARIO_FIM_QUINTA END VHORARIO_FIM_QUINTA, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_QUI IS NOT NULL THEN NV.VMINUTOS_AJUSTADOS_QUI ELSE NULL END VMINUTOS_AJUSTADOS_QUI,  
CASE WHEN NV.VMINUTOS_AJUSTADOS_QUI < 0 THEN AT.TEMPO_GRAVADO_QUI + NV.VMINUTOS_AJUSTADOS_QUI WHEN NV.VMINUTOS_AJUSTADOS_QUI > 0 THEN NV.VMINUTOS_AJUSTADOS_QUI + AT.TEMPO_GRAVADO_QUI ELSE TO_NUMBER(AT.TEMPO_GRAVADO_QUI) END NOVO_TOTAL_MINUTOS_QUI,

CASE WHEN NV.VHORARIO_INICIO_SEXTA IS NOT NULL THEN NV.VHORARIO_INICIO_SEXTA ELSE AT.HORARIO_INICIO_SEXTA END VHORARIO_INICIO_SEXTA, 
CASE WHEN NV.VHORARIO_FIM_SEXTA IS NOT NULL THEN NV.VHORARIO_FIM_SEXTA ELSE AT.HORARIO_FIM_SEXTA END VHORARIO_FIM_SEXTA, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_SEX IS NOT NULL THEN NV.VMINUTOS_AJUSTADOS_SEX ELSE NULL END VMINUTOS_AJUSTADOS_SEX, 
CASE WHEN NV.VMINUTOS_AJUSTADOS_SEX < 0 THEN AT.TEMPO_GRAVADO_SEX + NV.VMINUTOS_AJUSTADOS_SEX WHEN NV.VMINUTOS_AJUSTADOS_SEX > 0 THEN NV.VMINUTOS_AJUSTADOS_SEX + AT.TEMPO_GRAVADO_SEX ELSE TO_NUMBER(AT.TEMPO_GRAVADO_SEX) END NOVO_TOTAL_MINUTOS_SEX

,'DADOS_DBLINK_SGE' DADOS_DBLINK_SGE, 
ROW_NUMBER() OVER (PARTITION BY SGE.COORDENACAO, SGE.DURACAO_AULA, SGE.CARGA_HORARIA, SGE.HORA_INI_TURNO, SGE.HORA_FIM_TURNO, SGE.SEGUNDA, SGE.INTERVALO_SEGUNDA, SGE.TERCA, SGE.INTERVALO_TERCA, SGE.QUARTA, SGE.INTERVALO_QUARTA, 
SGE.QUINTA, SGE.INTERVALO_QUINTA, SGE.SEXTA, SGE.INTERVALO_SEXTA
ORDER BY SGE.COORDENACAO ,DURACAO_AULA, SGE.CARGA_HORARIA, SGE.HORA_INI_TURNO, SGE.HORA_FIM_TURNO ,SEGUNDA, SGE.INTERVALO_SEGUNDA, SGE.TERCA, SGE.INTERVALO_TERCA ,QUARTA, SGE.INTERVALO_QUARTA, 
SGE.QUINTA, SGE.INTERVALO_QUINTA, SGE.SEXTA, SGE.INTERVALO_SEXTA, SGE.ID_JORNADA)
ORDEM_CENARIO_CONFIG_AULAS,
SGE.ID_HORARIO, SGE.JORNADA_VALIDADA, SGE.BM, SGE.TIPO_JORNADA, SGE.JORNADA, SGE.DURACAO_AULA, SGE.CARGA_HORARIA, SGE.DATA_INICIO, SGE.DATA_FIM, SGE.DATA_CANCELAMENTO, SGE.COD_ORGAO, SGE.NOM_OFIC_ESCL, SGE.TURNO, SGE.HORA_INI_TURNO, SGE.HORA_FIM_TURNO,
SGE.SEGUNDA, SGE.INTERVALO_SEGUNDA, SGE.TERCA, SGE.INTERVALO_TERCA, SGE.QUARTA, SGE.INTERVALO_QUARTA, SGE.QUINTA, SGE.INTERVALO_QUINTA, SGE.SEXTA, SGE.INTERVALO_SEXTA, SGE.COORDENACAO, SGE.REGIONAL, SGE.LOCAL, SGE.BM_ULTIMA_ALTERACAO,
SGE.DATA_ULT_ALTERACAO, SGE.DATA_RECEBEU_ARTE, SGE.DATA_PROCESSAMENTO, SGE.OBS_PROCESSAMENTO, SGE.SERA_INTEGRADO, SGE.CAMPOS_IMPORTANTES_INVALIDOS, SGE.CAMPOS_OBRIGATORIOS_NULOS, SGE.ERRO_CARGA_HORARIA, SGE.ERRO_INTERVALO_TURNO, SGE.SITUACAO_JORNADA, 
SGE.DT_REAL_ULT_DIA_TRABALHADO, SGE.QTD_REG_MESMO_ID_HORARIO, SGE.ID_JORNADA ID_JORNADA_S, SGE.INICIO_JORNADA, SGE.FIM_JORNADA, SGE.TIPO_REGISTRO, SGE.DATA_INICIO_USAR, SGE.DATA_FIM_USAR, SGE.DT_VALIDA_CANCELA, SGE.DT_CANCELAMENTO_USAR

,'DADOS_ARTERH' DADOS_ARTERH, 
C.cod_cargo_efetivo, CE.DESCRICAO CARGO_EFETIVO,
ART.DIAS_ARTE, ART.ORIGEM, ART.TIPO_EXTENSAO, ART.ID_JORNADA ID_JORNADA_ART, ART.ID_HORARIO ID_HORARIO_ART, ART.ID_REGISTRO_ARQUIVO, ART.CODIGO_EMPRESA, ART.BM_SERVIDOR, ART.NOME_SERVIDOR, ART.CODIGO_CONTRATO_SGE, ART.DT_INICIO, ART.DT_FIM, ART.DT_CANCELAMENTO, 
ART.DT_RECEBEU_CADASTRO, ART.DT_RECEBEU_CANCELAMENTO, ART.TOTAL_DIAS, ART.MESMO_LOCAL_DA_PRINCIPAL, ART.MESMO_TURNO_DA_PRINCIPAL, 
ART.TURNO TURNO_ART, ART.COD_ESCALA, ART.COD_LOCAL1, ART.COD_LOCAL2, ART.COD_LOCAL3, ART.COD_LOCAL4, ART.COD_LOCAL5, ART.COD_LOCAL6, ART.NOME_ESCOLA, ART.MOTIVO, ART.DISCIPLINA_MINISTRADA, ART.HORAS_SEMANAIS, 
ART.HORARIO_INICIO_SEGUNDA HORARIO_INICIO_SEGUNDA_ART, ART.HORARIO_FIM_SEGUNDA HORARIO_FIM_SEGUNDA_ART, ART.HORARIO_INICIO_TERCA HORARIO_INICIO_TERCA_ART, ART.HORARIO_FIM_TERCA HORARIO_FIM_TERCA_ART, 
ART.HORARIO_INICIO_QUARTA HORARIO_INICIO_QUARTA_ART, ART.HORARIO_FIM_QUARTA HORARIO_FIM_QUARTA_ART, ART.HORARIO_INICIO_QUINTA HORARIO_INICIO_QUINTA_ART, ART.HORARIO_FIM_QUINTA HORARIO_FIM_QUINTA_ART, 
ART.HORARIO_INICIO_SEXTA HORARIO_INICIO_SEXTA_ART, ART.HORARIO_FIM_SEXTA HORARIO_FIM_SEXTA_ART, 
ART.HORARIO_INICIO_SABADO, ART.HORARIO_FIM_SABADO, ART.HORARIO_INICIO_DOMINGO, ART.HORARIO_FIM_DOMINGO, ART.CODIGO_ESCOLA, ART.DT_CRIACAO_VERBA, ART.DT_CANCELAMENTO_VERBA, 
ART.TIPO_CONTRATO, ART.DT_CRIACAO_SGE, ART.DT_CANCELAMENTO_SGE, ART.FAZ_JUS_VALE_REF, ART.REQUER_VALE_REF, ART.OBSERVACAO
FROM 
(
SELECT CAMPO_1 ID_JORNADA_A, CAMPO_2 TEMPO_EXCESSO_TOTAL, 
CASE WHEN SUBSTR(CAMPO_3,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_3,10,5)END HORARIO_INICIO_SEGUNDA, 
CASE WHEN SUBSTR(CAMPO_4,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_4,10,5)END HORARIO_FIM_SEGUNDA, 
CAMPO_5 TEMPO_EXCEDE_C_EXTRA_SGE_SEG, CAMPO_18 TEMPO_GRAVADO_SEG, 
CASE WHEN SUBSTR(CAMPO_6,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_6,10,5)END HORARIO_INICIO_TERCA, 
CASE WHEN SUBSTR(CAMPO_7,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_7,10,5)END HORARIO_FIM_TERCA, 
CAMPO_8 TEMPO_EXCEDE_C_EXTRA_SGE_TER,  CAMPO_19 TEMPO_GRAVADO_TER,
CASE WHEN SUBSTR(CAMPO_9,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_9,10,5)END HORARIO_INICIO_QUARTA, 
CASE WHEN SUBSTR(CAMPO_10,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_10,10,5)END HORARIO_FIM_QUARTA, 
CAMPO_11 TEMPO_EXCEDE_C_EXTRA_SGE_QUA, CAMPO_20 TEMPO_GRAVADO_QUA, 
CASE WHEN SUBSTR(CAMPO_12,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_12,10,5)END HORARIO_INICIO_QUINTA, 
CASE WHEN SUBSTR(CAMPO_13,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_13,10,5)END HORARIO_FIM_QUINTA, 
CAMPO_14 TEMPO_EXCEDE_C_EXTRA_SGE_QUI, CAMPO_21 TEMPO_GRAVADO_QUI,
CASE WHEN SUBSTR(CAMPO_15,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_15,10,5)END HORARIO_INICIO_SEXTA, 
CASE WHEN SUBSTR(CAMPO_16,10,5) = '00:00' THEN NULL ELSE SUBSTR(CAMPO_16,10,5)END HORARIO_FIM_SEXTA,
CAMPO_17 TEMPO_EXCEDE_C_EXTRA_SGE_SEX, CAMPO_22 TEMPO_GRAVADO_SEX

FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT 
WHERE CONSIDERACOES = 'AJUSTE_FINAL_DE-PARA_SMED_2023_ERRO_EXTRACLASSE_REGISTRO_ANTIGO' AND TRUNC(DATA_DADOS) = TRUNC(SYSDATE)--TO_DATE('17/01/2024','DD/MM/YYYY')-- --TO_DATE('10/01/2024','DD/MM/YYYY')
)AT
LEFT OUTER JOIN 
(
SELECT CAMPO_1 ID_JORNADA, SUBSTR(CAMPO_3,12,5) vHORARIO_INICIO_SEGUNDA, SUBSTR(CAMPO_4,12,5) vHORARIO_FIM_SEGUNDA, CAMPO_5 vMINUTOS_AJUSTADOS_SEG, SUBSTR(CAMPO_6,12,5) vHORARIO_INICIO_TERCA, SUBSTR(CAMPO_7,12,5) vHORARIO_FIM_TERCA,
CAMPO_8 vMINUTOS_AJUSTADOS_TER,  SUBSTR(CAMPO_9,12,5) vHORARIO_INICIO_QUARTA, SUBSTR(CAMPO_10,12,5) vHORARIO_FIM_QUARTA, CAMPO_11 vMINUTOS_AJUSTADOS_QUA, SUBSTR(CAMPO_12,12,5) vHORARIO_INICIO_QUINTA, SUBSTR(CAMPO_13,12,5) vHORARIO_FIM_QUINTA, 
CAMPO_14 vMINUTOS_AJUSTADOS_QUI, SUBSTR(CAMPO_15,12,5) vHORARIO_INICIO_SEXTA, SUBSTR(CAMPO_16,12,5) vHORARIO_FIM_SEXTA, CAMPO_17 vMINUTOS_AJUSTADOS_SEX 
FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT  WHERE CONSIDERACOES = 'AJUSTE_FINAL_DE-PARA_SMED_2023_ERRO_EXTRACLASSE_REGISTRO_NOVO' AND TRUNC(DATA_DADOS) = TRUNC(SYSDATE)--TO_DATE('17/01/2024','DD/MM/YYYY')----TO_DATE('10/01/2024','DD/MM/YYYY')  
)NV ON AT.ID_JORNADA_A = NV.ID_JORNADA 
LEFT OUTER JOIN
(
SELECT  CASE WHEN DT_CANCELAMENTO IS NOT NULL AND TRUNC(DT_CANCELAMENTO)<= TRUNC(DT_FIM) THEN TRUNC(DT_CANCELAMENTO)- TRUNC(DT_INICIO) ELSE TRUNC(DT_FIM)+1 - TRUNC(DT_INICIO) END DIAS_ARTE,
CASE WHEN TIPO_EXTENSAO = 'EXTENSAO_SGE_PROFESSOR_SALA_DE_AULA' THEN 'ARQUIVO_ANTIGO' ELSE 'VIEW_NOVA' END ORIGEM, E.* 
FROM PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD E WHERE TRUNC(DT_INICIO) >= TO_DATE('01/01/2023','DD/MM/YYYY')-- and id_horario in (55541, 60105)
)ART ON ART.ID_JORNADA = AT.ID_JORNADA_A

LEFT OUTER JOIN
(SELECT 
--CASE WHEN X.DT_CANCELAMENTO_USAR IS NOT NULL THEN (TO_DATE(DT_CANCELAMENTO_USAR,'DD/MM/YYYY')-1) - TO_DATE(DATA_INICIO,'DD/MM/YYYY') ELSE (TO_DATE(DATA_FIM,'DD/MM/YYYY')-1) - TO_DATE(DATA_INICIO,'DD/MM/YYYY') END DIAS,  
X.* FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_GERAL X WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' --AND TRUNC(DATA_PROCESSAMENTO) = TO_DATE('08/01/2024','DD/MM/YYYY') 
)SGE ON SGE.ID_JORNADA = ART.ID_JORNADA AND TRUNC(SGE.DATA_PROCESSAMENTO) = TRUNC(ART.DT_RECEBEU_CADASTRO)

LEFT OUTER JOIN
(SELECT C.* FROM  RHPESS_CONTRATO C
WHERE C.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX  WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO = C.CODIGO) )
C ON C.CODIGO_EMPRESA = '0001' AND C.TIPO_CONTRATO = '0001' AND C.CODIGO = LPAD(SGE.BM,15,0)
LEFT OUTER JOIN RHPLCS_CARGO CE ON CE.CODIGO = C.cod_cargo_efetivo AND CE.CODIGO_EMPRESA = '0001'

--WHERE AT.ID_JORNADA_A = 569593 ---TESTE
ORDER BY SGE.COORDENACAO, SGE.DURACAO_AULA, SGE.CARGA_HORARIA, SGE.HORA_INI_TURNO, SGE.HORA_FIM_TURNO, SGE.SEGUNDA, SGE.INTERVALO_SEGUNDA, SGE.TERCA, SGE.INTERVALO_TERCA, SGE.QUARTA, SGE.INTERVALO_QUARTA, SGE.QUINTA, SGE.INTERVALO_QUINTA, 
SGE.SEXTA, SGE.INTERVALO_SEXTA, ORDEM_CENARIO_CONFIG_AULAS, SGE.ID_JORNADA
,AT.HORARIO_INICIO_SEGUNDA, AT.HORARIO_FIM_SEGUNDA, AT.HORARIO_INICIO_TERCA, AT.HORARIO_FIM_TERCA, AT.HORARIO_INICIO_QUARTA, AT.HORARIO_FIM_QUARTA, AT.HORARIO_INICIO_QUINTA, AT.HORARIO_FIM_QUINTA, AT.HORARIO_INICIO_SEXTA, AT.HORARIO_FIM_SEXTA

)X2
)X3
WHERE X3.ORIGEM = 'VIEW_NOVA' --APENAS REGISTROS FORMATO NOVO
AND X3.TEMPO_EXCESSO_TOTAL <> 0 --APENAS OS REGISTROS COM ERRO
--AND X3.ID_JORNADA_A = 565399 --TESES DE PROCEDURE
--)

)LOOP
----fim-------------------analise GETED antes de rodar o 3º passo-------------------------------------------------------------------------------------------------------------
--*/---fim-- terceira parte para comentar parar rodar os blocos deste arquivo
vCONTADOR := vCONTADOR +1;


------INICIO-------------------------------------------------------------------------------------3º PASSO LOOP AJUSTAR OS REGISTROS COM ERRO JA INSERIDOS NA TABELA OFICIAL-------------------------------------------------------------
--/*---inicio-- quarta parte para comentar parar rodar os blocos deste arquivo


dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' UPDATE C1.ID_JORNADA_A: '||C1.ID_JORNADA_A||' C1.ID_HORARIO: '||C1.ID_HORARIO);

UPDATE PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD 
SET TIPO_EXTENSAO = 'EXTENSAO_SGE_DE_PARA_2023_PR_SGE_DP12P3', 
HORARIO_INICIO_SEGUNDA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_INICIO_SEGUNDA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_SEGUNDA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_FIM_SEGUNDA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_TERCA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_INICIO_TERCA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),   
HORARIO_FIM_TERCA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_FIM_TERCA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_QUARTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_INICIO_QUARTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_QUARTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_FIM_QUARTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_INICIO_QUINTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_INICIO_QUINTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_QUINTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_FIM_QUINTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),  
HORARIO_INICIO_SEXTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_INICIO_SEXTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
HORARIO_FIM_SEXTA = TO_CHAR(TO_DATE('01/01/2001 ' ||C1.VHORARIO_FIM_SEXTA|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') 
WHERE ID_JORNADA = C1.ID_JORNADA_A AND ID_HORARIO = C1.ID_HORARIO --AND TRUNC(DT_RECEBEU_CADASTRO) = TRUNC(SYSDATE);
;COMMIT;



END LOOP;
--*/---fim-- quarta parte para comentar parar rodar os blocos deste arquivo
------FIM-------------------------------------------------------------------------------------3º PASSO LOOP AJUSTAR OS REGISTROS COM ERRO JA INSERIDOS NA TABELA OFICIAL-------------------------------------------------------------


END;

END;