
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP3_POPULA_DATAS" 
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_popula_data_horarios_b7.sql)
--B7-- EM 31/8/23 --DEVIDO AJUSTE NOS CAMPOS DATA_INICIO, DATA_FIM PARA INICIO_JORNADA e FIM_JORNADA, TAMBEM DEVIDO AULA REFORCO MANHA TURNO INTEGRAL DE 1H00 AULA
--B6 --NOVO em 12/7/23 INCLUINDO TABELA SUGESP_SGE_PAR_REGE_ARQ_DATAS baseado no b5
--b5 em 22/6/23 16h14 baseado no b4
--Kellysson criado em 18/10/22--para criar as datas/horarios absolutos
--em 18/4/23 baseado no sql_popula_data_horarios_b2.sql ajuste para processar a diferenca entre 2 dias de registros
--REVISADO EM 06/06/23

--/*
DECLARE 
vCONTADOR NUMBER;
vAULAS VARCHAR2(7);
vNUMERO_AULA NUMBER;
vGRAVA VARCHAR2(1);
vAULAS_ANTES_INTERVALO NUMBER;
vQTD_AULAS_NO_DIA NUMBER;
vPRIMEIRA_AULA VARCHAR2(1);
vAULA_MEIO VARCHAR2(1);
vULTIMA_AULA VARCHAR2(1);
vAULAS_SEQUENCIA VARCHAR2(3);
vH_INTERVALO NUMBER;
vM_INTERVALO NUMBER;
vH_ATE_INTERVALO NUMBER;
vM_ATE_INTERVALO NUMBER;
--vMARCACOES VARCHAR2()
--vHORA_INI_TURNO VARCHAR2(5);
--vORDEM_AULA NUMBER:=0;
vMINUTOS_NO_DIA_INI_TURNO NUMBER;
vMINUTOS_NO_DIA_INI_INTERVALO NUMBER; 
vMINUTOS_INTERVALO NUMBER;
vPRIMEIRA_MARCACAO NUMBER;
vSEGUNDA_MARCACAO NUMBER;
vTERCEIRA_MARCACAO NUMBER;
vQUARTA_MARCACAO NUMBER;
vQUINTA_MARCACAO NUMBER;
vSEXTA_MARCACAO NUMBER;
vOBS_PROCESSAMENTO  VARCHAR2(4000);

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vAULAS := NULL ;
vNUMERO_AULA :=0;
vGRAVA := 'N';
vAULAS_ANTES_INTERVALO :=0;
vQTD_AULAS_NO_DIA :=0;
vPRIMEIRA_AULA := NULL ;
vAULA_MEIO := NULL ;
vULTIMA_AULA := NULL ;
vAULAS_SEQUENCIA := NULL ;
vH_INTERVALO :=0; 
vM_INTERVALO :=0;
vH_ATE_INTERVALO :=0; 
vM_ATE_INTERVALO :=0; 
vMINUTOS_NO_DIA_INI_TURNO  :=0;
vMINUTOS_NO_DIA_INI_INTERVALO :=0; 
vMINUTOS_INTERVALO :=0;
vPRIMEIRA_MARCACAO := NULL;
vSEGUNDA_MARCACAO := NULL;
vTERCEIRA_MARCACAO := NULL;
vQUARTA_MARCACAO := NULL;
vQUINTA_MARCACAO := NULL;
vSEXTA_MARCACAO := NULL;
vOBS_PROCESSAMENTO  := NULL;

-------------INICIO---------------------------------------------------------------------------------PARA REGISTROS NOVOS---------------------------------------------------------------
FOR 
C1 IN (
--*/

--X4 PARA TESTES
--SELECT COUNT(1)QTD_DIAS, X4.CPF, X4.LARG_STATUS, X4.STATUS_REGISTRO, X4.ID_HORARIO, X4.BM_U, X4.TIPO_JORNADA_U, X4.JORNADA, X4.TURNO_U, X4.HORA_INI_TURNO_U, X4.H_INICIO_TURNO, X4.M_INICIO_TURNO, X4.MINUTOS_NO_DIA_INI_TURNO, X4.HORA_FIM_TURNO_U, X4.H_FIM_TURNO, X4.M_FIM_TURNO, X4.MINUTOS_NO_DIA_FIM_TURNO, X4.TOTAL_MINUTOS_TURNO, X4.DURACAO_AULA_U, X4.H_DURACAO_AULA, X4.M_DURACAO_AULA, X4.TOTAL_MINUTOS_AULA, X4.QTD_AULAS_TURNO, X4.MINUTOS_INTERVALO, X4.INICIO_INTERVALO, X4.M_INICIO_INTERVALO, X4.FIM_INTERVALO, X4.M_FIM_INTERVALO, X4.CARGA_HORARIA, X4.COD_ORGAO_U, X4.NOM_OFIC_ESCL, X4.REGIONAL, X4.LOCAL, X4.COORDENACAO_U, X4.DOMINGO_ANTERIOR, X4.SEGUNDA_ANTERIOR, X4.INICIO_JORNADA_U, X4.FIM_JORNADA_U, X4.SEXTA_SEGUINTE, X4.DOMINGO_SEGUINTE, X4.DATA_CANCELAMENTO_U, X4.DATA_ULT_ALTERACAO_U, X4.LENGTH_5_DIAS, X4.AULAS_5_DIAS, X4.SEGUNDA_U, X4.PRIMEIRA_AULA_SEG, X4.AULA_MEIO_SEG, X4.ULTIMA_AULA_SEG, X4.LENGTH_SEG, X4.AULAS_SEG, X4.SEG_AULAS_SEQ, X4.HM_AULAS_SEG, X4.INTERVALO_SEGUNDA_U, X4.H_INTERVALO_SEG, X4.M_INTERVALO_SEG, X4.MINUTOS_NO_DIA_INI_INTER_SEG, X4.H_ATE_INTERVALO_SEG, X4.M_ATE_INTERVALO_SEG, X4.PRIMEIRA_MARCACAO_SEG, X4.SEGUNDA_MARCACAO_SEG, X4.TERCEIRA_MARCACAO_SEG, X4.QUARTA_MARCACAO_SEG, X4.TERCA_U, X4.PRIMEIRA_AULA_TER, X4.AULA_MEIO_TER, X4.ULTIMA_AULA_TER, X4.LENGTH_TER, X4.AULAS_TER, X4.TER_AULAS_SEQ, X4.HM_AULAS_TER, X4.INTERVALO_TERCA_U, X4.H_INTERVALO_TER, X4.M_INTERVALO_TER, X4.MINUTOS_NO_DIA_INI_INTER_TER, X4.H_ATE_INTERVALO_TER, X4.M_ATE_INTERVALO_TER, X4.PRIMEIRA_MARCACAO_TER, X4.SEGUNDA_MARCACAO_TER, X4.TERCEIRA_MARCACAO_TER, X4.QUARTA_MARCACAO_TER, X4.QUARTA_U, X4.PRIMEIRA_AULA_QUA, X4.AULA_MEIO_QUA, X4.ULTIMA_AULA_QUA, X4.LENGTH_QUA, X4.AULAS_QUA, X4.QUA_AULAS_SEQ, X4.HM_AULAS_QUA, X4.INTERVALO_QUARTA_U, X4.H_INTERVALO_QUA, X4.M_INTERVALO_QUA, X4.MINUTOS_NO_DIA_INI_INTER_QUA, X4.H_ATE_INTERVALO_QUA, X4.M_ATE_INTERVALO_QUA, X4.PRIMEIRA_MARCACAO_QUA, X4.SEGUNDA_MARCACAO_QUA, X4.TERCEIRA_MARCACAO_QUA, X4.QUARTA_MARCACAO_QUA, X4.QUINTA_U, X4.PRIMEIRA_AULA_QUI, X4.AULA_MEIO_QUI, X4.ULTIMA_AULA_QUI, X4.LENGTH_QUI, X4.AULAS_QUI, X4.QUI_AULAS_SEQ, X4.HM_AULAS_QUI, X4.INTERVALO_QUINTA_U, X4.H_INTERVALO_QUI, X4.M_INTERVALO_QUI, X4.MINUTOS_NO_DIA_INI_INTER_QUI, X4.H_ATE_INTERVALO_QUI, X4.M_ATE_INTERVALO_QUI, X4.PRIMEIRA_MARCACAO_QUI, X4.SEGUNDA_MARCACAO_QUI, X4.TERCEIRA_MARCACAO_QUI, X4.QUARTA_MARCACAO_QUI, X4.SEXTA_U, X4.PRIMEIRA_AULA_SEX, X4.AULA_MEIO_SEX, X4.ULTIMA_AULA_SEX, X4.LENGTH_SEX, X4.AULAS_SEX, X4.SEX_AULAS_SEQ, X4.HM_AULAS_SEX, X4.INTERVALO_SEXTA_U, X4.H_INTERVALO_SEX, X4.M_INTERVALO_SEX, X4.MINUTOS_NO_DIA_INI_INTER_SEX, X4.H_ATE_INTERVALO_SEX, X4.M_ATE_INTERVALO_SEX, X4.PRIMEIRA_MARCACAO_SEX, X4.SEGUNDA_MARCACAO_SEX, X4.TERCEIRA_MARCACAO_SEX, X4.QUARTA_MARCACAO_SEX FROM (

SELECT 
P.CPF,
X3.LARG_STATUS, X3.STATUS_REGISTRO,
X3.DATA_DIA, X3.DIA_SEMANA, X3.NRO_DIA_SEMANA, X3.NRO_SEMANA_MES,
X3.ID_HORARIO, X3.BM_U, X3.TIPO_JORNADA_U, X3.JORNADA, X3.TURNO_U, 
X3.HORA_INI_TURNO_U, 
--X3.H_INTERVALO_TURNO, X3.M_INTERVALO_TURNO, 
X3.H_INICIO_TURNO, X3.M_INICIO_TURNO, 
X3.MINUTOS_NO_DIA_INI_TURNO, 
X3.HORA_FIM_TURNO_U, X3.H_FIM_TURNO, X3.M_FIM_TURNO, X3.MINUTOS_NO_DIA_FIM_TURNO,
X3.TOTAL_MINUTOS_TURNO, X3.DURACAO_AULA_U, X3.H_DURACAO_AULA, X3.M_DURACAO_AULA, X3.TOTAL_MINUTOS_AULA,
X3.QTD_AULAS_TURNO,
X3.MINUTOS_INTERVALO, X3.INICIO_INTERVALO, X3.M_INICIO_INTERVALO, X3.FIM_INTERVALO, X3.M_FIM_INTERVALO, 
X3.CARGA_HORARIA, X3.COD_ORGAO_U, X3.NOM_OFIC_ESCL, X3.REGIONAL, X3.LOCAL, X3.COORDENACAO_U,
X3.DOMINGO_ANTERIOR,
X3.SEGUNDA_ANTERIOR,
X3.INICIO_JORNADA_U, X3.FIM_JORNADA_U,
X3.SEXTA_SEGUINTE,
X3.DOMINGO_SEGUINTE,
X3.DATA_CANCELAMENTO_U, X3.DATA_ULT_ALTERACAO_U, X3.LENGTH_5_DIAS, X3.AULAS_5_DIAS, 
X3.SEGUNDA_U, X3.PRIMEIRA_AULA_SEG, X3.AULA_MEIO_SEG, X3.ULTIMA_AULA_SEG, X3.LENGTH_SEG, X3.AULAS_SEG, X3.SEG_AULAS_SEQ, 
CASE WHEN X3.SEGUNDA_U IS NULL THEN 0 ELSE X3.AULAS_SEG * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEG,  
X3.INTERVALO_SEGUNDA_U, X3.H_INTERVALO_SEG, X3.M_INTERVALO_SEG, X3.MINUTOS_NO_DIA_INI_INTER_SEG, 
CASE WHEN X3.INTERVALO_SEGUNDA_U IS NULL OR LENGTH(X3.INTERVALO_SEGUNDA_U) <> 5 THEN 0 ELSE TRUNC(X3.MINUTOS_NO_DIA_INI_INTER_SEG - X3.MINUTOS_NO_DIA_INI_TURNO) END H_ATE_INTERVALO_SEG, 
CASE WHEN X3.INTERVALO_SEGUNDA_U IS NULL OR LENGTH(X3.INTERVALO_SEGUNDA_U) <> 5 THEN 0 ELSE MOD((X3.MINUTOS_NO_DIA_INI_INTER_SEG - X3.MINUTOS_NO_DIA_INI_TURNO),60) END M_ATE_INTERVALO_SEG,
CASE WHEN X3.SEGUNDA_U IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEG - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEG,
CASE 
WHEN X3.SEG_AULAS_SEQ = 'SIM'                                                 THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEG * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_SEG * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.AULA_MEIO_SEG * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_SEG * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END SEGUNDA_MARCACAO_SEG,
CASE 
WHEN X3.SEG_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_SEG -1) * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_SEG -1) * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.AULA_MEIO_SEG -1) * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END TERCEIRA_MARCACAO_SEG,
CASE 
WHEN X3.SEG_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEG * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEG * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEG_AULAS_SEQ = 'NAO' AND X3.AULAS_SEG = 3 AND X3.SEGUNDA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEG * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END QUARTA_MARCACAO_SEG,
X3.TERCA_U, X3.PRIMEIRA_AULA_TER, X3.AULA_MEIO_TER, X3.ULTIMA_AULA_TER, X3.LENGTH_TER, X3.AULAS_TER, X3.TER_AULAS_SEQ,
CASE WHEN X3.TERCA_U IS NULL THEN 0 ELSE X3.AULAS_TER * X3.TOTAL_MINUTOS_AULA END HM_AULAS_TER, 
X3.INTERVALO_TERCA_U, X3.H_INTERVALO_TER, X3.M_INTERVALO_TER, X3.MINUTOS_NO_DIA_INI_INTER_TER, 
CASE WHEN X3.INTERVALO_TERCA_U IS NULL OR LENGTH(X3.INTERVALO_TERCA_U) <> 5 THEN 0 ELSE TRUNC(X3.MINUTOS_NO_DIA_INI_INTER_TER - X3.MINUTOS_NO_DIA_INI_TURNO) END H_ATE_INTERVALO_TER,
CASE WHEN X3.INTERVALO_TERCA_U IS NULL OR LENGTH(X3.INTERVALO_TERCA_U) <> 5 THEN 0 ELSE MOD((X3.MINUTOS_NO_DIA_INI_INTER_TER - X3.MINUTOS_NO_DIA_INI_TURNO),60) END M_ATE_INTERVALO_TER,
CASE WHEN X3.TERCA_U IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_TER - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_TER,
CASE 
WHEN X3.TER_AULAS_SEQ = 'SIM'                                                 THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_TER * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_TER * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.AULA_MEIO_TER * X3.TOTAL_MINUTOS_AULA)
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_TER * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END SEGUNDA_MARCACAO_TER,
CASE 
WHEN X3.TER_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_TER -1) * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_TER -1) * X3.TOTAL_MINUTOS_AULA)
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.AULA_MEIO_TER -1) * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END TERCEIRA_MARCACAO_TER,
CASE 
WHEN X3.TER_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_TER * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_TER * X3.TOTAL_MINUTOS_AULA)
WHEN X3.TER_AULAS_SEQ = 'NAO' AND X3.AULAS_TER = 3 AND X3.TERCA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_TER * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END QUARTA_MARCACAO_TER,
X3.QUARTA_U, X3.PRIMEIRA_AULA_QUA, X3.AULA_MEIO_QUA, X3.ULTIMA_AULA_QUA, X3.LENGTH_QUA, X3.AULAS_QUA, X3.QUA_AULAS_SEQ, 
CASE WHEN X3.QUARTA_U IS NULL THEN 0 ELSE X3.AULAS_QUA * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUA,
X3.INTERVALO_QUARTA_U, X3.H_INTERVALO_QUA, X3.M_INTERVALO_QUA, X3.MINUTOS_NO_DIA_INI_INTER_QUA, 
CASE WHEN X3.INTERVALO_QUARTA_U IS NULL OR LENGTH(X3.INTERVALO_QUARTA_U) <> 5 THEN 0 ELSE TRUNC(X3.MINUTOS_NO_DIA_INI_INTER_QUA - X3.MINUTOS_NO_DIA_INI_TURNO) END H_ATE_INTERVALO_QUA, 
CASE WHEN X3.INTERVALO_QUARTA_U IS NULL OR LENGTH(X3.INTERVALO_QUARTA_U) <> 5 THEN 0 ELSE MOD((X3.MINUTOS_NO_DIA_INI_INTER_QUA - X3.MINUTOS_NO_DIA_INI_TURNO),60) END M_ATE_INTERVALO_QUA,
CASE WHEN X3.QUARTA_U IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUA - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUA,
CASE 
WHEN X3.QUA_AULAS_SEQ = 'SIM'                                                 THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUA * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_QUA * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.AULA_MEIO_QUA * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_QUA * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END SEGUNDA_MARCACAO_QUA,
CASE 
WHEN X3.QUA_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_QUA -1) * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_QUA -1) * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.AULA_MEIO_QUA -1) * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END TERCEIRA_MARCACAO_QUA,
CASE 
WHEN X3.QUA_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUA * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUA * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUA_AULAS_SEQ = 'NAO' AND X3.AULAS_QUA = 3 AND X3.QUARTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUA * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END QUARTA_MARCACAO_QUA,
X3.QUINTA_U, X3.PRIMEIRA_AULA_QUI, X3.AULA_MEIO_QUI, X3.ULTIMA_AULA_QUI, X3.LENGTH_QUI, X3.AULAS_QUI, X3.QUI_AULAS_SEQ, 
CASE WHEN X3.QUINTA_U IS NULL THEN 0 ELSE X3.AULAS_QUI * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUI,
X3.INTERVALO_QUINTA_U, X3.H_INTERVALO_QUI, X3.M_INTERVALO_QUI, X3.MINUTOS_NO_DIA_INI_INTER_QUI, 
CASE WHEN X3.INTERVALO_QUINTA_U IS NULL OR LENGTH(X3.INTERVALO_QUINTA_U) <> 5 THEN 0 ELSE TRUNC(X3.MINUTOS_NO_DIA_INI_INTER_QUI - X3.MINUTOS_NO_DIA_INI_TURNO) END H_ATE_INTERVALO_QUI, 
CASE WHEN X3.INTERVALO_QUINTA_U IS NULL OR LENGTH(X3.INTERVALO_QUINTA_U) <> 5 THEN 0 ELSE MOD((X3.MINUTOS_NO_DIA_INI_INTER_QUI - X3.MINUTOS_NO_DIA_INI_TURNO),60) END M_ATE_INTERVALO_QUI,
CASE WHEN X3.QUINTA_U IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUI - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUI,
CASE 
WHEN X3.QUI_AULAS_SEQ = 'SIM'                                                 THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUI * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_QUI * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.AULA_MEIO_QUI * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_QUI * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END SEGUNDA_MARCACAO_QUI,
CASE 
WHEN X3.QUI_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_QUI -1) * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_QUI -1) * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.AULA_MEIO_QUI -1) * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END TERCEIRA_MARCACAO_QUI,
CASE 
WHEN X3.QUI_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUI * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUI * X3.TOTAL_MINUTOS_AULA)
WHEN X3.QUI_AULAS_SEQ = 'NAO' AND X3.AULAS_QUI = 3 AND X3.QUINTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_QUI * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END QUARTA_MARCACAO_QUI,
X3.SEXTA_U, X3.PRIMEIRA_AULA_SEX, X3.AULA_MEIO_SEX, X3.ULTIMA_AULA_SEX, X3.LENGTH_SEX, X3.AULAS_SEX, X3.SEX_AULAS_SEQ, 
CASE WHEN X3.SEXTA_U IS NULL THEN 0 ELSE X3.AULAS_SEX * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEX, 
X3.INTERVALO_SEXTA_U, X3.H_INTERVALO_SEX, X3.M_INTERVALO_SEX, MINUTOS_NO_DIA_INI_INTER_SEX, 
CASE WHEN X3.INTERVALO_SEXTA_U IS NULL OR LENGTH(X3.INTERVALO_SEXTA_U) <> 5 THEN 0 ELSE TRUNC(X3.MINUTOS_NO_DIA_INI_INTER_SEX - X3.MINUTOS_NO_DIA_INI_TURNO) END H_ATE_INTERVALO_SEX,
CASE WHEN X3.INTERVALO_SEXTA_U IS NULL OR LENGTH(X3.INTERVALO_SEXTA_U) <> 5 THEN 0 ELSE MOD((X3.MINUTOS_NO_DIA_INI_INTER_SEX - X3.MINUTOS_NO_DIA_INI_TURNO),60) END M_ATE_INTERVALO_SEX,
CASE WHEN X3.SEXTA_U IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEX - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEX,
CASE 
WHEN X3.SEX_AULAS_SEQ = 'SIM'                                                 THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEX * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_SEX * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.AULA_MEIO_SEX * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.PRIMEIRA_AULA_SEX * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END SEGUNDA_MARCACAO_SEX,
CASE 
WHEN X3.SEX_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_SEX -1) * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.ULTIMA_AULA_SEX -1) * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + ((X3.AULA_MEIO_SEX -1) * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END TERCEIRA_MARCACAO_SEX,
CASE 
WHEN X3.SEX_AULAS_SEQ = 'SIM'                                                 THEN NULL
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 2                            THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEX * X3.TOTAL_MINUTOS_AULA) 
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,2,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEX * X3.TOTAL_MINUTOS_AULA)
WHEN X3.SEX_AULAS_SEQ = 'NAO' AND X3.AULAS_SEX = 3 AND X3.SEXTA_U = '1,3,4' THEN X3.MINUTOS_NO_DIA_INI_TURNO + (X3.ULTIMA_AULA_SEX * X3.TOTAL_MINUTOS_AULA)
ELSE 0 END QUARTA_MARCACAO_SEX
FROM(

SELECT 
TRUNC(X2.TOTAL_MINUTOS_TURNO/X2.TOTAL_MINUTOS_AULA) QTD_AULAS_TURNO,
--LPAD(TRUNC((X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2))/60,0),2,0) ||':'||LPAD(MOD((X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2)),60),2,0) INICIO_INTERVALO, 
NULL INICIO_INTERVALO, 
--(X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2))  M_INICIO_INTERVALO, 
NULL M_INICIO_INTERVALO, 
--LPAD(TRUNC((X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2))/60,0),2,0) ||':'||LPAD(MOD((X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2))+(MOD((X2.H_FIM_TURNO * 60 + X2.M_FIM_TURNO)- (X2.H_INTERVALO_TURNO * 60 + X2.M_INTERVALO_TURNO),(X2.H_DURACAO_AULA * 60 + X2.M_DURACAO_AULA))),60),2,0) FIM_INTERVALO, 
NULL FIM_INTERVALO, 
--(X2.MINUTOS_NO_DIA_INI_TURNO + (X2.TOTAL_MINUTOS_AULA * 2))+X2.MINUTOS_INTERVALO M_FIM_INTERVALO, 
NULL M_FIM_INTERVALO, 
X2.* FROM(

SELECT 
X.LARG_STATUS, X.STATUS_REGISTRO,
X.DATA_DIA, X.DIA_SEMANA, X.NRO_DIA_SEMANA, X.NRO_SEMANA_MES,
X.ID_HORARIO, X.BM_U, X.TIPO_JORNADA_U, X.JORNADA, X.TURNO_U, 
X.HORA_INI_TURNO_U, 
X.H_INICIO_TURNO, X.M_INICIO_TURNO,
X.H_INICIO_TURNO *60 + M_INICIO_TURNO MINUTOS_NO_DIA_INI_TURNO,
X.HORA_FIM_TURNO_U, X.H_FIM_TURNO, X.M_FIM_TURNO, 
X.H_FIM_TURNO * 60 + X.M_FIM_TURNO MINUTOS_NO_DIA_FIM_TURNO,
(X.H_FIM_TURNO * 60 + X.M_FIM_TURNO)- (X.H_INICIO_TURNO * 60 + X.M_INICIO_TURNO)TOTAL_MINUTOS_TURNO,
X.DURACAO_AULA_U,
X.H_DURACAO_AULA, X.M_DURACAO_AULA,
X.H_DURACAO_AULA * 60 + X.M_DURACAO_AULA TOTAL_MINUTOS_AULA,
20 MINUTOS_INTERVALO,--FIXO PARA TODOS EM 20 MINUTOS SEGUNDO SMED
X.CARGA_HORARIA, X.COD_ORGAO_U, X.NOM_OFIC_ESCL, X.REGIONAL, X.LOCAL, X.COORDENACAO_U, 
X.DOMINGO_ANTERIOR,
X.SEGUNDA_ANTERIOR,
X.INICIO_JORNADA_U, X.FIM_JORNADA_U,
X.SEXTA_SEGUINTE,
X.DOMINGO_SEGUINTE,
X.DATA_CANCELAMENTO_U, X.DATA_ULT_ALTERACAO_U, 
X.LENGTH_SEG + X.LENGTH_TER + X.LENGTH_QUA + X.LENGTH_QUI + X.LENGTH_SEX LENGTH_5_DIAS,
X.AULAS_SEG + X.AULAS_TER + X.AULAS_QUA + X.AULAS_QUI + X.AULAS_SEX AULAS_5_DIAS,
X.SEGUNDA_U, X.PRIMEIRA_AULA_SEG, X.AULA_MEIO_SEG, X.ULTIMA_AULA_SEG, X.LENGTH_SEG, X.AULAS_SEG, X.SEG_AULAS_SEQ,  X.INTERVALO_SEGUNDA_U, H_INTERVALO_SEG, M_INTERVALO_SEG, 
H_INTERVALO_SEG *60 + M_INTERVALO_SEG MINUTOS_NO_DIA_INI_INTER_SEG,
X.TERCA_U, X.PRIMEIRA_AULA_TER, X.AULA_MEIO_TER, X.ULTIMA_AULA_TER, X.LENGTH_TER, X.AULAS_TER, X.TER_AULAS_SEQ,  X.INTERVALO_TERCA_U, H_INTERVALO_TER, M_INTERVALO_TER,
H_INTERVALO_TER *60 + M_INTERVALO_TER MINUTOS_NO_DIA_INI_INTER_TER,
X.QUARTA_U, X.PRIMEIRA_AULA_QUA, X.AULA_MEIO_QUA, X.ULTIMA_AULA_QUA, X.LENGTH_QUA, X.AULAS_QUA, X.QUA_AULAS_SEQ, X.INTERVALO_QUARTA_U, H_INTERVALO_QUA, M_INTERVALO_QUA, 
H_INTERVALO_QUA *60 + M_INTERVALO_QUA MINUTOS_NO_DIA_INI_INTER_QUA,
X.QUINTA_U, X.PRIMEIRA_AULA_QUI, X.AULA_MEIO_QUI, X.ULTIMA_AULA_QUI, X.LENGTH_QUI, X.AULAS_QUI, X.QUI_AULAS_SEQ, X.INTERVALO_QUINTA_U, H_INTERVALO_QUI, M_INTERVALO_QUI,
H_INTERVALO_QUI *60 + M_INTERVALO_QUI MINUTOS_NO_DIA_INI_INTER_QUI,
X.SEXTA_U, X.PRIMEIRA_AULA_SEX, X.AULA_MEIO_SEX, X.ULTIMA_AULA_SEX, X.LENGTH_SEX, X.AULAS_SEX, X.SEX_AULAS_SEQ, X.INTERVALO_SEXTA_U, H_INTERVALO_SEX, M_INTERVALO_SEX
,H_INTERVALO_SEX *60 + M_INTERVALO_SEX MINUTOS_NO_DIA_INI_INTER_SEX
FROM(
--select count(1), LARG_STATUS, STATUS_REGISTRO, JORNADA_VALIDADA_U, ID_HORARIO, BM_U, TIPO_JORNADA_U, JORNADA, TURNO_U, HORA_INI_TURNO_U, H_INICIO_TURNO, M_INICIO_TURNO, HORA_FIM_TURNO_U, H_FIM_TURNO, M_FIM_TURNO, DURACAO_AULA_U, H_DURACAO_AULA, M_DURACAO_AULA, CARGA_HORARIA, COD_ORGAO_U, NOM_OFIC_ESCL, REGIONAL, LOCAL, COORDENACAO_U, INICIO_JORNADA_U, FIM_JORNADA_U, DATA_CANCELAMENTO_U, DATA_ULT_ALTERACAO_U, SEGUNDA_U, PRIMEIRA_AULA_SEG, AULA_MEIO_SEG, ULTIMA_AULA_SEG, LENGTH_SEG, AULAS_SEG, SEG_AULAS_SEQ, INTERVALO_SEGUNDA_U, H_INTERVALO_SEG, M_INTERVALO_SEG, TERCA_U, PRIMEIRA_AULA_TER, AULA_MEIO_TER, ULTIMA_AULA_TER, LENGTH_TER, AULAS_TER, TER_AULAS_SEQ, INTERVALO_TERCA_U, H_INTERVALO_TER, M_INTERVALO_TER, QUARTA_U, PRIMEIRA_AULA_QUA, AULA_MEIO_QUA, ULTIMA_AULA_QUA, LENGTH_QUA, AULAS_QUA, QUA_AULAS_SEQ, INTERVALO_QUARTA_U, H_INTERVALO_QUA, M_INTERVALO_QUA, QUINTA_U, PRIMEIRA_AULA_QUI, AULA_MEIO_QUI, ULTIMA_AULA_QUI, LENGTH_QUI, AULAS_QUI, QUI_AULAS_SEQ, INTERVALO_QUINTA_U, H_INTERVALO_QUI, M_INTERVALO_QUI, SEXTA_U, PRIMEIRA_AULA_SEX, AULA_MEIO_SEX, ULTIMA_AULA_SEX, LENGTH_SEX, AULAS_SEX, SEX_AULAS_SEQ, INTERVALO_SEXTA_U, H_INTERVALO_SEX, M_INTERVALO_SEX, STATUS_JORNADA_VALIDADA, STATUS_BM, STATUS_TIPO_JORNADA, STATUS_TURNO, STATUS_HORA_INI_TURNO, STATUS_HORA_FIM_TURNO, STATUS_DURACAO_AULA, STATUS_COD_ORGAO, STATUS_COORDENACAO, STATUS_DATA_INICIO, STATUS_DATA_FIM, STATUS_DATA_CANCELAMENTO, STATUS_DATA_ULT_ALTERACAO, STATUS_SEGUNDA, STATUS_INTERVALO_SEGUNDA, STATUS_TERCA, STATUS_INTERVALO_TERCA, STATUS_QUARTA, STATUS_INTERVALO_QUARTA, STATUS_QUINTA, STATUS_INTERVALO_QUINTA, STATUS_SEXTA, STATUS_INTERVALO_SEXTA from (
SELECT 
A.LARGURA_TODOS_STATUS_CAMPOS LARG_STATUS, A.STATUS_REGISTRO, A.JORNADA_VALIDADA_U,
D.DATA_DIA, D.DIA_SEMANA ,D.NRO_DIA_SEMANA ,D.NRO_SEMANA_MES,
A.ID_HORARIO ,A.BM_U ,A.TIPO_JORNADA_U ,A.JORNADA ,A.TURNO_U ,
A.HORA_INI_TURNO_U ,
CASE WHEN LTRIM(SUBSTR(A.HORA_INI_TURNO_U,1,2),0) IS NULL OR LENGTH(A.HORA_INI_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.HORA_INI_TURNO_U,1,2),0)END H_INICIO_TURNO,
CASE WHEN LTRIM(SUBSTR(A.HORA_INI_TURNO_U,4,2),0) IS NULL OR LENGTH(A.HORA_INI_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.HORA_INI_TURNO_U,4,2),0)END M_INICIO_TURNO,
A.HORA_FIM_TURNO_U ,
CASE WHEN LTRIM(SUBSTR(A.HORA_FIM_TURNO_U,1,2),0) IS NULL OR LENGTH(A.HORA_FIM_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.HORA_FIM_TURNO_U,1,2),0) END H_FIM_TURNO,
CASE WHEN LTRIM(SUBSTR(A.HORA_FIM_TURNO_U,4,2),0) IS NULL OR LENGTH(A.HORA_FIM_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.HORA_FIM_TURNO_U,4,2),0) END M_FIM_TURNO,
A.DURACAO_AULA_U ,
CASE WHEN LTRIM(SUBSTR(A.DURACAO_AULA_U,1,2),0)IS NULL OR LENGTH(A.DURACAO_AULA_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.DURACAO_AULA_U,1,2),0) END H_DURACAO_AULA,
CASE WHEN LTRIM(SUBSTR(A.DURACAO_AULA_U,4,2),0)IS NULL OR LENGTH(A.DURACAO_AULA_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(A.DURACAO_AULA_U,4,2),0) END M_DURACAO_AULA,
A.CARGA_HORARIA, A.COD_ORGAO_U, A.NOM_OFIC_ESCL, A.REGIONAL, A.LOCAL, A.COORDENACAO_U, 
--TRUNC(TO_DATE(A.INICIO_JORNADA_U,'DD/MM/YYYY'))-(SA.NRO_DIA_SEMANA-2)
A.DOMINGO_ANTERIOR,
A.SEGUNDA_ANTERIOR, 
A.INICIO_JORNADA_U, A.FIM_JORNADA_U, 
--TRUNC(TO_DATE(A.FIM_JORNADA_U,'DD/MM/YYYY'))+(7-DS.NRO_DIA_SEMANA+1)
A.SEXTA_SEGUINTE,
A.DOMINGO_SEGUINTE,
A.DATA_CANCELAMENTO_U, A.DATA_ULT_ALTERACAO_U,
--DADOS SEGUNDA
A.SEGUNDA_U,
CASE WHEN A.SEGUNDA_U IS NULL THEN '0' ELSE SUBSTR(A.SEGUNDA_U,1,1)END PRIMEIRA_AULA_SEG,
CASE WHEN A.SEGUNDA_U IS NULL OR LENGTH(A.SEGUNDA_U)<>5 THEN '0' ELSE SUBSTR(A.SEGUNDA_U,3,1)END AULA_MEIO_SEG,
CASE WHEN A.SEGUNDA_U IS NULL THEN '0' ELSE SUBSTR(A.SEGUNDA_U,LENGTH(A.SEGUNDA_U),1)END ULTIMA_AULA_SEG,
CASE WHEN A.SEGUNDA_U IS NULL THEN 0 ELSE LENGTH(A.SEGUNDA_U) END LENGTH_SEG, 
CASE WHEN A.SEGUNDA_U IS NULL THEN 0 ELSE LENGTH(A.SEGUNDA_U)- REGEXP_COUNT(A.SEGUNDA_U,',')END AULAS_SEG, 
CASE WHEN A.SEGUNDA_U IS NULL THEN NULL WHEN A.SEGUNDA_U IS NOT NULL AND A.SEGUNDA_U IN ('1,3','1,4','2,4','1,3,4','1,2,4') THEN 'NAO' ELSE 'SIM' END SEG_AULAS_SEQ, 
A.INTERVALO_SEGUNDA_U, 
CASE WHEN A.INTERVALO_SEGUNDA_U IS NULL OR LENGTH(A.INTERVALO_SEGUNDA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_SEGUNDA_U,1,2),0),'0') END H_INTERVALO_SEG, 
CASE WHEN A.INTERVALO_SEGUNDA_U IS NULL OR LENGTH(A.INTERVALO_SEGUNDA_U)<> 5 THEN '0' ELSE  NVL(LTRIM(SUBSTR(A.INTERVALO_SEGUNDA_U,4,2),0),'0') END M_INTERVALO_SEG, 
--DADOS TERCA
A.TERCA_U, 
CASE WHEN A.TERCA_U IS NULL THEN '0' ELSE SUBSTR(A.TERCA_U,1,1)END PRIMEIRA_AULA_TER,
CASE WHEN A.TERCA_U IS NULL OR LENGTH(A.TERCA_U)<>5 THEN '0' ELSE SUBSTR(A.TERCA_U,3,1)END AULA_MEIO_TER,
CASE WHEN A.TERCA_U IS NULL THEN '0' ELSE SUBSTR(A.TERCA_U,LENGTH(A.TERCA_U),1)END ULTIMA_AULA_TER,
CASE WHEN A.TERCA_U IS NULL THEN 0 ELSE LENGTH(A.TERCA_U) END LENGTH_TER, 
CASE WHEN A.TERCA_U IS NULL THEN 0 ELSE LENGTH(A.TERCA_U)- REGEXP_COUNT(A.TERCA_U,',')END AULAS_TER, 
CASE WHEN A.TERCA_U IS NULL THEN NULL WHEN A.TERCA_U IS NOT NULL AND A.TERCA_U IN ('1,3','1,4','2,4','1,3,4','1,2,4') THEN 'NAO' ELSE 'SIM' END TER_AULAS_SEQ, 
A.INTERVALO_TERCA_U, 
CASE WHEN A.INTERVALO_TERCA_U IS NULL OR LENGTH(A.INTERVALO_TERCA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_TERCA_U,1,2),0),'0') END H_INTERVALO_TER, 
CASE WHEN A.INTERVALO_TERCA_U IS NULL OR LENGTH(A.INTERVALO_TERCA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_TERCA_U,4,2),0),'0') END M_INTERVALO_TER, 
--DADOS QUARTA
A.QUARTA_U, 
CASE WHEN A.QUARTA_U IS NULL THEN '0' ELSE SUBSTR(A.QUARTA_U,1,1)END PRIMEIRA_AULA_QUA,
CASE WHEN A.QUARTA_U IS NULL OR LENGTH(A.QUARTA_U)<>5 THEN '0' ELSE SUBSTR(A.QUARTA_U,3,1)END AULA_MEIO_QUA,
CASE WHEN A.QUARTA_U IS NULL THEN '0' ELSE SUBSTR(A.QUARTA_U,LENGTH(A.QUARTA_U),1)END ULTIMA_AULA_QUA,
CASE WHEN A.QUARTA_U IS NULL THEN 0 ELSE LENGTH(A.QUARTA_U)END LENGTH_QUA, 
CASE WHEN A.QUARTA_U IS NULL THEN 0 ELSE LENGTH(A.QUARTA_U)- REGEXP_COUNT(A.QUARTA_U,',')END AULAS_QUA, 
CASE WHEN A.QUARTA_U IS NULL THEN NULL WHEN A.QUARTA_U IS NOT NULL AND A.QUARTA_U IN ('1,3','1,4','2,4','1,3,4','1,2,4') THEN 'NAO' ELSE 'SIM' END QUA_AULAS_SEQ,  
A.INTERVALO_QUARTA_U, 
CASE WHEN A.INTERVALO_QUARTA_U IS NULL OR LENGTH(A.INTERVALO_QUARTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_QUARTA_U,1,2),0),'0') END H_INTERVALO_QUA, 
CASE WHEN A.INTERVALO_QUARTA_U IS NULL OR LENGTH(A.INTERVALO_QUARTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_QUARTA_U,4,2),0),'0') END M_INTERVALO_QUA,
--DADOS QUINTA
A.QUINTA_U, 
CASE WHEN A.QUINTA_U IS NULL THEN '0' ELSE SUBSTR(A.QUINTA_U,1,1)END PRIMEIRA_AULA_QUI,
CASE WHEN A.QUINTA_U IS NULL OR LENGTH(A.QUINTA_U)<>5 THEN '0' ELSE SUBSTR(A.QUINTA_U,3,1)END AULA_MEIO_QUI,
CASE WHEN A.QUINTA_U IS NULL THEN '0' ELSE SUBSTR(A.QUINTA_U,LENGTH(A.QUINTA_U),1)END ULTIMA_AULA_QUI,
CASE WHEN A.QUINTA_U IS NULL THEN 0 ELSE LENGTH(A.QUINTA_U)END LENGTH_QUI, 
CASE WHEN A.QUINTA_U IS NULL THEN 0 ELSE LENGTH(A.QUINTA_U)- REGEXP_COUNT(A.QUINTA_U,',')END AULAS_QUI,
CASE WHEN A.QUINTA_U IS NULL THEN NULL WHEN A.QUINTA_U IS NOT NULL AND A.QUINTA_U IN ('1,3','1,4','2,4','1,3,4','1,2,4') THEN 'NAO' ELSE 'SIM' END QUI_AULAS_SEQ, 
A.INTERVALO_QUINTA_U, 
CASE WHEN A.INTERVALO_QUINTA_U IS NULL OR LENGTH(A.INTERVALO_QUINTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_QUINTA_U,1,2),0),'0') END H_INTERVALO_QUI,
CASE WHEN A.INTERVALO_QUINTA_U IS NULL OR LENGTH(A.INTERVALO_QUINTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_QUINTA_U,4,2),0),'0') END M_INTERVALO_QUI,
--DADOS SEXTA
A.SEXTA_U, 
CASE WHEN A.SEXTA_U IS NULL THEN '0' ELSE SUBSTR(A.SEXTA_U,1,1)END PRIMEIRA_AULA_SEX,
CASE WHEN A.SEXTA_U IS NULL OR LENGTH(A.SEXTA_U)<>5 THEN '0' ELSE SUBSTR(A.SEXTA_U,3,1)END AULA_MEIO_SEX,
CASE WHEN A.SEXTA_U IS NULL THEN '0' ELSE SUBSTR(A.SEXTA_U,LENGTH(A.SEXTA_U),1)END ULTIMA_AULA_SEX,
CASE WHEN A.SEXTA_U IS NULL THEN 0 ELSE LENGTH(A.SEXTA_U)END LENGTH_SEX, 
CASE WHEN A.SEXTA_U IS NULL THEN 0 ELSE LENGTH(A.SEXTA_U)- REGEXP_COUNT(A.SEXTA_U,',')END AULAS_SEX, 
CASE WHEN A.SEXTA_U IS NULL THEN NULL WHEN A.SEXTA_U IS NOT NULL AND A.SEXTA_U IN ('1,3','1,4','2,4','1,3,4','1,2,4') THEN 'NAO' ELSE 'SIM' END SEX_AULAS_SEQ, 
A.INTERVALO_SEXTA_U, 
CASE WHEN A.INTERVALO_SEXTA_U IS NULL OR LENGTH(A.INTERVALO_SEXTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_SEXTA_U,1,2),0),'0') END H_INTERVALO_SEX, 
CASE WHEN A.INTERVALO_SEXTA_U IS NULL OR LENGTH(A.INTERVALO_SEXTA_U)<> 5 THEN '0' ELSE NVL(LTRIM(SUBSTR(A.INTERVALO_SEXTA_U,4,2),0),'0') END M_INTERVALO_SEX
--DADOS GERAIS
,A.STATUS_JORNADA_VALIDADA, A.STATUS_BM, A.STATUS_TIPO_JORNADA, A.STATUS_TURNO, A.STATUS_HORA_INI_TURNO, A.STATUS_HORA_FIM_TURNO, A.STATUS_DURACAO_AULA, A.STATUS_COD_ORGAO, A.STATUS_COORDENACAO, A.STATUS_DATA_INICIO, A.STATUS_DATA_FIM, 
A.STATUS_DATA_CANCELAMENTO, A.STATUS_DATA_ULT_ALTERACAO, A.STATUS_SEGUNDA, A.STATUS_INTERVALO_SEGUNDA, A.STATUS_TERCA, A.STATUS_INTERVALO_TERCA, A.STATUS_QUARTA, A.STATUS_INTERVALO_QUARTA, A.STATUS_QUINTA, 
A.STATUS_INTERVALO_QUINTA, A.STATUS_SEXTA, A.STATUS_INTERVALO_SEXTA
FROM (SELECT 
      CASE WHEN SA.NRO_DIA_SEMANA = 1 THEN SA.DATA_DIA ELSE TRUNC(TO_DATE(A.INICIO_JORNADA_U,'DD/MM/YYYY'))-(SA.NRO_DIA_SEMANA-1)END DOMINGO_ANTERIOR,
      CASE WHEN SA.NRO_DIA_SEMANA = 1 THEN TRUNC(SA.DATA_DIA)+1 ELSE TRUNC(TO_DATE(A.INICIO_JORNADA_U,'DD/MM/YYYY'))-(SA.NRO_DIA_SEMANA-2)END SEGUNDA_ANTERIOR, 
      CASE WHEN DS.NRO_DIA_SEMANA = 6 THEN DS.DATA_DIA WHEN DS.NRO_DIA_SEMANA = 7 THEN TRUNC(DS.DATA_DIA)-1 WHEN DS.NRO_DIA_SEMANA = 1 THEN TRUNC(DS.DATA_DIA)-2 ELSE TRUNC(TO_DATE(A.FIM_JORNADA_U,'DD/MM/YYYY'))+(6-DS.NRO_DIA_SEMANA)END SEXTA_SEGUINTE,
      CASE WHEN DS.NRO_DIA_SEMANA = 1 THEN DS.DATA_DIA WHEN DS.NRO_DIA_SEMANA = 7 THEN TRUNC(DS.DATA_DIA)+1 ELSE TRUNC(TO_DATE(A.FIM_JORNADA_U,'DD/MM/YYYY'))+(7-DS.NRO_DIA_SEMANA+1)END DOMINGO_SEGUINTE,
      A.* FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES A 
      LEFT OUTER JOIN ARTERH.RHTABS_DATAS SA ON TRUNC(SA.DATA_DIA) = TO_DATE(A.INICIO_JORNADA_U,'DD/MM/YYYY') 
      LEFT OUTER JOIN ARTERH.RHTABS_DATAS DS ON TRUNC(DS.DATA_DIA) = TO_DATE(A.FIM_JORNADA_U,'DD/MM/YYYY'))A
--LEFT OUTER JOIN (SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_GERAL WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) )G ON G.ID_HORARIO = A.ID_HORARIO
LEFT OUTER JOIN ARTERH.RHTABS_DATAS D ON TRUNC(D.DATA_DIA) BETWEEN TO_DATE(A.DOMINGO_ANTERIOR,'DD/MM/YYYY') AND TO_DATE(A.SEXTA_SEGUINTE,'DD/MM/YYYY')--TO_DATE(A.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(A.FIM_JORNADA_U,'DD/MM/YYYY') OR TRUNC(D.DATA_DIA) BETWEEN TO_DATE(A.DATA_INICIO_P,'DD/MM/YYYY') AND TO_DATE(A.DATA_FIM_P,'DD/MM/YYYY')
WHERE TRUNC(A.DATA_PROCESSAMENTO)= TRUNC(SYSDATE) --A.DATA_PROCESSAMENTO IS NULL ---APENAS AS NAO PROCESSADAS AINDA
AND A.TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
--and a.id_horario in (2072)
ORDER BY A.ID_HORARIO, D.DATA_DIA

--)group by LARG_STATUS, STATUS_REGISTRO, JORNADA_VALIDADA_U, ID_HORARIO, BM_U, TIPO_JORNADA_U, JORNADA, TURNO_U, HORA_INI_TURNO_U, H_INICIO_TURNO, M_INICIO_TURNO, HORA_FIM_TURNO_U, H_FIM_TURNO, M_FIM_TURNO, DURACAO_AULA_U, H_DURACAO_AULA, M_DURACAO_AULA, CARGA_HORARIA, COD_ORGAO_U, NOM_OFIC_ESCL, REGIONAL, LOCAL, COORDENACAO_U, INICIO_JORNADA_U, FIM_JORNADA_U, DATA_CANCELAMENTO_U, DATA_ULT_ALTERACAO_U, SEGUNDA_U, PRIMEIRA_AULA_SEG, AULA_MEIO_SEG, ULTIMA_AULA_SEG, LENGTH_SEG, AULAS_SEG, SEG_AULAS_SEQ, INTERVALO_SEGUNDA_U, H_INTERVALO_SEG, M_INTERVALO_SEG, TERCA_U, PRIMEIRA_AULA_TER, AULA_MEIO_TER, ULTIMA_AULA_TER, LENGTH_TER, AULAS_TER, TER_AULAS_SEQ, INTERVALO_TERCA_U, H_INTERVALO_TER, M_INTERVALO_TER, QUARTA_U, PRIMEIRA_AULA_QUA, AULA_MEIO_QUA, ULTIMA_AULA_QUA, LENGTH_QUA, AULAS_QUA, QUA_AULAS_SEQ, INTERVALO_QUARTA_U, H_INTERVALO_QUA, M_INTERVALO_QUA, QUINTA_U, PRIMEIRA_AULA_QUI, AULA_MEIO_QUI, ULTIMA_AULA_QUI, LENGTH_QUI, AULAS_QUI, QUI_AULAS_SEQ, INTERVALO_QUINTA_U, H_INTERVALO_QUI, M_INTERVALO_QUI, SEXTA_U, PRIMEIRA_AULA_SEX, AULA_MEIO_SEX, ULTIMA_AULA_SEX, LENGTH_SEX, AULAS_SEX, SEX_AULAS_SEQ, INTERVALO_SEXTA_U, H_INTERVALO_SEX, M_INTERVALO_SEX, STATUS_JORNADA_VALIDADA, STATUS_BM, STATUS_TIPO_JORNADA, STATUS_TURNO, STATUS_HORA_INI_TURNO, STATUS_HORA_FIM_TURNO, STATUS_DURACAO_AULA, STATUS_COD_ORGAO, STATUS_COORDENACAO, STATUS_DATA_INICIO, STATUS_DATA_FIM, STATUS_DATA_CANCELAMENTO, STATUS_DATA_ULT_ALTERACAO, STATUS_SEGUNDA, STATUS_INTERVALO_SEGUNDA, STATUS_TERCA, STATUS_INTERVALO_TERCA, STATUS_QUARTA, STATUS_INTERVALO_QUARTA, STATUS_QUINTA, STATUS_INTERVALO_QUINTA, STATUS_SEXTA, STATUS_INTERVALO_SEXTA

)X

)X2
)X3
LEFT OUTER JOIN (SELECT M.CODIGO_EMPRESA, M.TIPO_CONTRATO, M.CODIGO_CONTRATO, M.CODIGO_PESSOA, P.CPF FROM ARTERH.RHPESS_CONTR_MEST M LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P ON P.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND P.CODIGO = M.CODIGO_PESSOA)P 
ON P.CODIGO_EMPRESA = '0001' AND P.TIPO_CONTRATO = '0001' AND P.CODIGO_CONTRATO = X3.BM_U

--where x3.bm_u = '000000000759574'--in('000000000454374') --('000000001069312','000000001154867')
--where x3.id_horario IN (1376,1443)--not in (2483,2484)--localizar bug ORA-01722: número inválido
--where x3.id_horario = 2072 --BUG
---X4 PARA TESES


--)X4 /*where x4.id_horario IN (2356, 2401, 2458, 2611, 2634, 2636)*//*where x4.id_horario IN (1601,1603,1626,1663,1665,1666,1667,1685,1688,1692,1696,1698,1701,1703,1722) */ GROUP BY X4.CPF, X4.LARG_STATUS, X4.STATUS_REGISTRO, X4.ID_HORARIO, X4.BM_U, X4.TIPO_JORNADA_U, X4.JORNADA, X4.TURNO_U, X4.HORA_INI_TURNO_U, X4.H_INICIO_TURNO, X4.M_INICIO_TURNO, X4.MINUTOS_NO_DIA_INI_TURNO, X4.HORA_FIM_TURNO_U, X4.H_FIM_TURNO, X4.M_FIM_TURNO, X4.MINUTOS_NO_DIA_FIM_TURNO, X4.TOTAL_MINUTOS_TURNO, X4.DURACAO_AULA_U, X4.H_DURACAO_AULA, X4.M_DURACAO_AULA, X4.TOTAL_MINUTOS_AULA, X4.QTD_AULAS_TURNO, X4.MINUTOS_INTERVALO, X4.INICIO_INTERVALO, X4.M_INICIO_INTERVALO, X4.FIM_INTERVALO, X4.M_FIM_INTERVALO, X4.CARGA_HORARIA, X4.COD_ORGAO_U, X4.NOM_OFIC_ESCL, X4.REGIONAL, X4.LOCAL, X4.COORDENACAO_U, X4.DOMINGO_ANTERIOR, X4.SEGUNDA_ANTERIOR, X4.INICIO_JORNADA_U, X4.FIM_JORNADA_U, X4.SEXTA_SEGUINTE, X4.DOMINGO_SEGUINTE, X4.DATA_CANCELAMENTO_U, X4.DATA_ULT_ALTERACAO_U, X4.LENGTH_5_DIAS, X4.AULAS_5_DIAS, X4.SEGUNDA_U, X4.PRIMEIRA_AULA_SEG, X4.AULA_MEIO_SEG, X4.ULTIMA_AULA_SEG, X4.LENGTH_SEG, X4.AULAS_SEG, X4.SEG_AULAS_SEQ, X4.HM_AULAS_SEG, X4.INTERVALO_SEGUNDA_U, X4.H_INTERVALO_SEG, X4.M_INTERVALO_SEG, X4.MINUTOS_NO_DIA_INI_INTER_SEG, X4.H_ATE_INTERVALO_SEG, X4.M_ATE_INTERVALO_SEG, X4.PRIMEIRA_MARCACAO_SEG, X4.SEGUNDA_MARCACAO_SEG, X4.TERCEIRA_MARCACAO_SEG, X4.QUARTA_MARCACAO_SEG, X4.TERCA_U, X4.PRIMEIRA_AULA_TER, X4.AULA_MEIO_TER, X4.ULTIMA_AULA_TER, X4.LENGTH_TER, X4.AULAS_TER, X4.TER_AULAS_SEQ, X4.HM_AULAS_TER, X4.INTERVALO_TERCA_U, X4.H_INTERVALO_TER, X4.M_INTERVALO_TER, X4.MINUTOS_NO_DIA_INI_INTER_TER, X4.H_ATE_INTERVALO_TER, X4.M_ATE_INTERVALO_TER, X4.PRIMEIRA_MARCACAO_TER, X4.SEGUNDA_MARCACAO_TER, X4.TERCEIRA_MARCACAO_TER, X4.QUARTA_MARCACAO_TER, X4.QUARTA_U, X4.PRIMEIRA_AULA_QUA, X4.AULA_MEIO_QUA, X4.ULTIMA_AULA_QUA, X4.LENGTH_QUA, X4.AULAS_QUA, X4.QUA_AULAS_SEQ, X4.HM_AULAS_QUA, X4.INTERVALO_QUARTA_U, X4.H_INTERVALO_QUA, X4.M_INTERVALO_QUA, X4.MINUTOS_NO_DIA_INI_INTER_QUA, X4.H_ATE_INTERVALO_QUA, X4.M_ATE_INTERVALO_QUA, X4.PRIMEIRA_MARCACAO_QUA, X4.SEGUNDA_MARCACAO_QUA, X4.TERCEIRA_MARCACAO_QUA, X4.QUARTA_MARCACAO_QUA, X4.QUINTA_U, X4.PRIMEIRA_AULA_QUI, X4.AULA_MEIO_QUI, X4.ULTIMA_AULA_QUI, X4.LENGTH_QUI, X4.AULAS_QUI, X4.QUI_AULAS_SEQ, X4.HM_AULAS_QUI, X4.INTERVALO_QUINTA_U, X4.H_INTERVALO_QUI, X4.M_INTERVALO_QUI, X4.MINUTOS_NO_DIA_INI_INTER_QUI, X4.H_ATE_INTERVALO_QUI, X4.M_ATE_INTERVALO_QUI, X4.PRIMEIRA_MARCACAO_QUI, X4.SEGUNDA_MARCACAO_QUI, X4.TERCEIRA_MARCACAO_QUI, X4.QUARTA_MARCACAO_QUI, X4.SEXTA_U, X4.PRIMEIRA_AULA_SEX, X4.AULA_MEIO_SEX, X4.ULTIMA_AULA_SEX, X4.LENGTH_SEX, X4.AULAS_SEX, X4.SEX_AULAS_SEQ, X4.HM_AULAS_SEX, X4.INTERVALO_SEXTA_U, X4.H_INTERVALO_SEX, X4.M_INTERVALO_SEX, X4.MINUTOS_NO_DIA_INI_INTER_SEX, X4.H_ATE_INTERVALO_SEX, X4.M_ATE_INTERVALO_SEX, X4.PRIMEIRA_MARCACAO_SEX, X4.SEGUNDA_MARCACAO_SEX, X4.TERCEIRA_MARCACAO_SEX, X4.QUARTA_MARCACAO_SEX ORDER BY X4.LARG_STATUS, X4.STATUS_REGISTRO, X4.ID_HORARIO, X4.BM_U, X4.TIPO_JORNADA_U, X4.JORNADA, X4.TURNO_U, X4.HORA_INI_TURNO_U, X4.H_INICIO_TURNO, X4.M_INICIO_TURNO, X4.MINUTOS_NO_DIA_INI_TURNO, X4.HORA_FIM_TURNO_U, X4.H_FIM_TURNO, X4.M_FIM_TURNO, X4.MINUTOS_NO_DIA_FIM_TURNO, X4.TOTAL_MINUTOS_TURNO, X4.DURACAO_AULA_U, X4.H_DURACAO_AULA, X4.M_DURACAO_AULA, X4.TOTAL_MINUTOS_AULA, X4.QTD_AULAS_TURNO, X4.MINUTOS_INTERVALO, X4.INICIO_INTERVALO, X4.M_INICIO_INTERVALO, X4.FIM_INTERVALO, X4.M_FIM_INTERVALO, X4.CARGA_HORARIA, X4.COD_ORGAO_U, X4.NOM_OFIC_ESCL, X4.REGIONAL, X4.LOCAL, X4.COORDENACAO_U, X4.DOMINGO_ANTERIOR, X4.SEGUNDA_ANTERIOR, X4.INICIO_JORNADA_U, X4.FIM_JORNADA_U, X4.SEXTA_SEGUINTE, X4.DOMINGO_SEGUINTE, X4.DATA_CANCELAMENTO_U, X4.DATA_ULT_ALTERACAO_U, X4.LENGTH_5_DIAS, X4.AULAS_5_DIAS, X4.SEGUNDA_U, X4.PRIMEIRA_AULA_SEG, X4.AULA_MEIO_SEG, X4.ULTIMA_AULA_SEG, X4.LENGTH_SEG, X4.AULAS_SEG, X4.SEG_AULAS_SEQ, X4.HM_AULAS_SEG, X4.INTERVALO_SEGUNDA_U, X4.H_INTERVALO_SEG, X4.M_INTERVALO_SEG, X4.MINUTOS_NO_DIA_INI_INTER_SEG, X4.H_ATE_INTERVALO_SEG, X4.M_ATE_INTERVALO_SEG, X4.PRIMEIRA_MARCACAO_SEG, X4.SEGUNDA_MARCACAO_SEG, X4.TERCEIRA_MARCACAO_SEG, X4.QUARTA_MARCACAO_SEG, X4.TERCA_U, X4.PRIMEIRA_AULA_TER, X4.AULA_MEIO_TER, X4.ULTIMA_AULA_TER, X4.LENGTH_TER, X4.AULAS_TER, X4.TER_AULAS_SEQ, X4.HM_AULAS_TER, X4.INTERVALO_TERCA_U, X4.H_INTERVALO_TER, X4.M_INTERVALO_TER, X4.MINUTOS_NO_DIA_INI_INTER_TER, X4.H_ATE_INTERVALO_TER, X4.M_ATE_INTERVALO_TER, X4.PRIMEIRA_MARCACAO_TER, X4.SEGUNDA_MARCACAO_TER, X4.TERCEIRA_MARCACAO_TER, X4.QUARTA_MARCACAO_TER, X4.QUARTA_U, X4.PRIMEIRA_AULA_QUA, X4.AULA_MEIO_QUA, X4.ULTIMA_AULA_QUA, X4.LENGTH_QUA, X4.AULAS_QUA, X4.QUA_AULAS_SEQ, X4.HM_AULAS_QUA, X4.INTERVALO_QUARTA_U, X4.H_INTERVALO_QUA, X4.M_INTERVALO_QUA, X4.MINUTOS_NO_DIA_INI_INTER_QUA, X4.H_ATE_INTERVALO_QUA, X4.M_ATE_INTERVALO_QUA, X4.PRIMEIRA_MARCACAO_QUA, X4.SEGUNDA_MARCACAO_QUA, X4.TERCEIRA_MARCACAO_QUA, X4.QUARTA_MARCACAO_QUA, X4.QUINTA_U, X4.PRIMEIRA_AULA_QUI, X4.AULA_MEIO_QUI, X4.ULTIMA_AULA_QUI, X4.LENGTH_QUI, X4.AULAS_QUI, X4.QUI_AULAS_SEQ, X4.HM_AULAS_QUI, X4.INTERVALO_QUINTA_U, X4.H_INTERVALO_QUI, X4.M_INTERVALO_QUI, X4.MINUTOS_NO_DIA_INI_INTER_QUI, X4.H_ATE_INTERVALO_QUI, X4.M_ATE_INTERVALO_QUI, X4.PRIMEIRA_MARCACAO_QUI, X4.SEGUNDA_MARCACAO_QUI, X4.TERCEIRA_MARCACAO_QUI, X4.QUARTA_MARCACAO_QUI, X4.SEXTA_U, X4.PRIMEIRA_AULA_SEX, X4.AULA_MEIO_SEX, X4.ULTIMA_AULA_SEX, X4.LENGTH_SEX, X4.AULAS_SEX, X4.SEX_AULAS_SEQ, X4.HM_AULAS_SEX, X4.INTERVALO_SEXTA_U, X4.H_INTERVALO_SEX, X4.M_INTERVALO_SEX, X4.MINUTOS_NO_DIA_INI_INTER_SEX, X4.H_ATE_INTERVALO_SEX, X4.M_ATE_INTERVALO_SEX, X4.PRIMEIRA_MARCACAO_SEX, X4.SEGUNDA_MARCACAO_SEX, X4.TERCEIRA_MARCACAO_SEX, X4.QUARTA_MARCACAO_SEX 


--WHERE X3.ID_HORARIO IN(
--1602, 1625 --TURNO NOITE
--1649 --1H30 VARIOS HORARIOS CONSECUTIVOS
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set  TERCA_U = '1,2,3',  QUARTA_U = '2,3,4' WHERE ID_HORARIO =1649
--1669 --1H30  HORARIOS 5 TIPOS NÃO CONSECUTIVOS
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,3', TERCA_U = '1,4', QUARTA_U = '2,4', QUINTA_U = '1,3,4', SEXTA_U = '1,2,4'WHERE ID_HORARIO =1669
--1708 1H INICIO TURNO 7H INTERVALO 9H
--1603 1H INICIO TURNO 7H30 INTERVALO 9H30
--1713--1H-1,2,3,4
--,1601-- 1H 1,2

--1667 --FUNDAMENTAL CENARIOS DE 1 A 5
--SELECT * FROM  PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE ID_HORARIO = 1667
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,2,3,4', INTERVALO_SEGUNDA_U = '09:25', TERCA_U = '1', INTERVALO_TERCA_U = '09:15', QUARTA_U = '2', INTERVALO_QUARTA_U = '08:10', QUINTA_U = '3', INTERVALO_QUINTA_U = '10:10', SEXTA_U = '4', INTERVALO_SEXTA_U = '10:10' WHERE ID_HORARIO =1667

--1708 --FUNDAMENTAL CENARIOS DE 6 A 10
--SELECT * FROM  PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE ID_HORARIO = 1708
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,2', INTERVALO_SEGUNDA_U = '10:05', TERCA_U = '2,3', INTERVALO_TERCA_U = '08:00', QUARTA_U = '3,4', INTERVALO_QUARTA_U = '09:50', QUINTA_U = '1,2,3', INTERVALO_QUINTA_U = '10:15', SEXTA_U = '2,3,4', INTERVALO_SEXTA_U = '08:00' WHERE ID_HORARIO =1708

--1708
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,2', INTERVALO_SEGUNDA_U = '08:10' WHERE ID_HORARIO =1708
--update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='2,4', INTERVALO_SEGUNDA_U = '10:50', DURACAO_AULA_U = '01:00', TURNO_U = 'MANHÃ' WHERE ID_HORARIO =1708;COMMIT;
--1601,1603,1626,1663,1665,1666,1667,1685,1688,1692,1696,1698,1701,1703,1722 --15 CENARIOS TERCEIRA TENTATIVA
/*
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1' WHERE ID_HORARIO = 1665;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='2' WHERE ID_HORARIO = 1666;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='3' WHERE ID_HORARIO = 1667;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='4' WHERE ID_HORARIO = 1685;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='2,3' WHERE ID_HORARIO = 1688;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,3' WHERE ID_HORARIO = 1696;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='1,4' WHERE ID_HORARIO = 1701;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set SEGUNDA_U ='2,4' WHERE ID_HORARIO = 1703;
update PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES set HORA_INI_TURNO_U ='07:00' WHERE ID_HORARIO = 1603;

*/

--)--TESTES 7/6/23


/*

WHERE TRUNC(X3.DATA_DIA) ------------------FILTRO PERIODO ATUAL PARA AJUSTES NO ARTERH/IFPONTO
BETWEEN 
(SELECT MAX(TO_DATE(DADO_ORIGEM,'DD/MM/YYYY')+1)PRIMEIRO_DIA_PROCESSAR FROM ARTERH.RHINTE_ED_IT_CONV AUX WHERE CODIGO_CONVERSAO = 'FCPT')
AND
(SELECT LAST_DAY(ADD_MONTHS(MAX(TO_DATE(DADO_ORIGEM,'DD/MM/YYYY')+1),1)) ULTIMO_DIA_PROCESSAR FROM ARTERH.RHINTE_ED_IT_CONV AUX WHERE CODIGO_CONVERSAO = 'FCPT')


--AND x3.bm  IN ('000000000234897','000000000263730','000000000701576','000000001031587') --X3.ID_HORARIO IN (128,202,203,282,284,285)--(,74, 273,364)--TESTES
*/

)LOOP
vCONTADOR := vCONTADOR +1;
vMINUTOS_NO_DIA_INI_TURNO := C1.MINUTOS_NO_DIA_INI_TURNO;--NOVO LOCAL EM 7/6/23

IF C1.DURACAO_AULA_U = '01:00' 
THEN vMINUTOS_INTERVALO := C1.MINUTOS_INTERVALO;
ELSE vMINUTOS_INTERVALO :=0;
END IF;

--dbms_output.put_line('-----------------------------------');
dbms_output.put_line('--vCONTADOR: '||vCONTADOR ||' C1.ID_HORARIO: '||C1.ID_HORARIO);



--INICIO-------------------------------PRIMEIRA PARTE ------------------------------INCLUSAO DE UMA NOVO REGISTRO DE JORNADA--------------------------------------------------------------------------------
--comentado IF EM 5/7/23 PARA GERAR DE TODOS --IF C1.LARG_STATUS = 44 AND C1.STATUS_REGISTRO = 'INCLUIR' THEN ---------------------------------------------------------------------- PARA INSERIR REGISTROS NOVOS
--INICIO--NOVO LOCAL EM 7/6/23 DEFINI DIA DA SEMANA PARA A VARIAVEL vAULAS

IF C1.NRO_DIA_SEMANA = 1 THEN --DOMINGO SEMPRE SERA O TOTALIZADOR NAO TER AULA NO DIA
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF, 'TOTAL', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;

IF C1.NRO_DIA_SEMANA = 2 THEN 
IF C1.AULAS_SEG <> 0 
AND ( TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') >= TO_DATE(C1.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') <= TO_DATE(C1.FIM_JORNADA_U,'DD/MM/YYYY'))
THEN
--INICIO--------------SEGUNDA-FEIRA
vGRAVA := 'S';
vAULAS := C1.SEGUNDA_U;
vAULAS_ANTES_INTERVALO := C1.H_INTERVALO_SEG - C1.H_INICIO_TURNO;
vQTD_AULAS_NO_DIA := C1.AULAS_SEG;
vPRIMEIRA_AULA := C1.PRIMEIRA_AULA_SEG;
vAULA_MEIO := C1.AULA_MEIO_SEG;
vULTIMA_AULA := C1.ULTIMA_AULA_SEG;
vAULAS_SEQUENCIA := C1.SEG_AULAS_SEQ;
vH_INTERVALO := C1.H_INTERVALO_SEG;
vM_INTERVALO := C1.M_INTERVALO_SEG;
vMINUTOS_NO_DIA_INI_INTERVALO := CASE WHEN C1.MINUTOS_NO_DIA_INI_INTER_SEG <> 0 THEN C1.MINUTOS_NO_DIA_INI_INTER_SEG ELSE C1.MINUTOS_NO_DIA_INI_TURNO+120 END; 
vH_ATE_INTERVALO := C1.H_ATE_INTERVALO_SEG; 
vM_ATE_INTERVALO :=C1.M_ATE_INTERVALO_SEG; 
--dbms_output.put_line('--TEM_AULA_SEGUNDA: '||C1.DATA_DIA||' vAULAS: '||vAULAS||' vAULAS_SEQUENCIA: '||vAULAS_SEQUENCIA||' vQTD_AULAS_NO_DIA: '|| vQTD_AULAS_NO_DIA||' vPRIMEIRA_AULA: '||vPRIMEIRA_AULA||' vAULA_MEIO: '||vAULA_MEIO||' vULTIMA_AULA: '||vULTIMA_AULA||' C1.TOTAL_MINUTOS_AULA: '||C1.TOTAL_MINUTOS_AULA||' C1.INTERVALO_SEGUNDA_U: '||C1.INTERVALO_SEGUNDA_U||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vAULAS_ANTES_INTERVALO: '||vAULAS_ANTES_INTERVALO||' vH_INTERVALO: '||vH_INTERVALO||' vM_INTERVALO: '||vM_INTERVALO||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vH_ATE_INTERVALO: '||vH_ATE_INTERVALO||' vM_ATE_INTERVALO: '||vM_ATE_INTERVALO);
vPRIMEIRA_MARCACAO := C1.PRIMEIRA_MARCACAO_SEG;
vSEGUNDA_MARCACAO := C1.SEGUNDA_MARCACAO_SEG;
vTERCEIRA_MARCACAO := C1.TERCEIRA_MARCACAO_SEG;
vQUARTA_MARCACAO := C1.QUARTA_MARCACAO_SEG;
--dbms_output.put_line('--vMINUTOS_NO_DIA_INI_TURNO: '||vMINUTOS_NO_DIA_INI_TURNO ||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);

ELSE
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;
END IF;

IF C1.NRO_DIA_SEMANA = 3 THEN
IF C1.AULAS_TER <> 0 
AND ( TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') >= TO_DATE(C1.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') <= TO_DATE(C1.FIM_JORNADA_U,'DD/MM/YYYY'))
THEN
--INICIO--------------TERCA-FEIRA
vGRAVA := 'S';
vAULAS := C1.TERCA_U;
vAULAS_ANTES_INTERVALO := C1.H_INTERVALO_TER - C1.H_INICIO_TURNO;
vQTD_AULAS_NO_DIA := C1.AULAS_TER;
vPRIMEIRA_AULA := C1.PRIMEIRA_AULA_TER;
vAULA_MEIO := C1.AULA_MEIO_TER;
vULTIMA_AULA := C1.ULTIMA_AULA_TER;
vAULAS_SEQUENCIA := C1.TER_AULAS_SEQ;
vH_INTERVALO := C1.H_INTERVALO_TER;
vM_INTERVALO := C1.M_INTERVALO_TER;
vMINUTOS_NO_DIA_INI_INTERVALO := CASE WHEN C1.MINUTOS_NO_DIA_INI_INTER_TER <> 0 THEN C1.MINUTOS_NO_DIA_INI_INTER_TER ELSE C1.MINUTOS_NO_DIA_INI_TURNO+120 END; 
vH_ATE_INTERVALO := C1.H_ATE_INTERVALO_TER; 
vM_ATE_INTERVALO :=C1.M_ATE_INTERVALO_TER; 
--dbms_output.put_line('--TEM_AULA_TERCA: '||C1.DATA_DIA||' vAULAS: '||vAULAS||' vAULAS_SEQUENCIA: '||vAULAS_SEQUENCIA||' vQTD_AULAS_NO_DIA: '|| vQTD_AULAS_NO_DIA||' vPRIMEIRA_AULA: '||vPRIMEIRA_AULA||' vAULA_MEIO: '||vAULA_MEIO||' vULTIMA_AULA: '||vULTIMA_AULA||' C1.TOTAL_MINUTOS_AULA: '||C1.TOTAL_MINUTOS_AULA||' C1.INTERVALO_TERCA_U: '||C1.INTERVALO_TERCA_U||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vAULAS_ANTES_INTERVALO: '||vAULAS_ANTES_INTERVALO||' vH_INTERVALO: '||vH_INTERVALO||' vM_INTERVALO: '||vM_INTERVALO||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vH_ATE_INTERVALO: '||vH_ATE_INTERVALO||' vM_ATE_INTERVALO: '||vM_ATE_INTERVALO);
vPRIMEIRA_MARCACAO := C1.PRIMEIRA_MARCACAO_TER;
vSEGUNDA_MARCACAO := C1.SEGUNDA_MARCACAO_TER;
vTERCEIRA_MARCACAO := C1.TERCEIRA_MARCACAO_TER;
vQUARTA_MARCACAO := C1.QUARTA_MARCACAO_TER;
--dbms_output.put_line('--vMINUTOS_NO_DIA_INI_TURNO: '||vMINUTOS_NO_DIA_INI_TURNO ||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);

ELSE
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;
END IF;

IF C1.NRO_DIA_SEMANA = 4 THEN
IF C1.AULAS_QUA <> 0 
AND ( TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') >= TO_DATE(C1.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') <= TO_DATE(C1.FIM_JORNADA_U,'DD/MM/YYYY'))
THEN
--INICIO--------------QUARTA-FEIRA
vGRAVA := 'S';
vAULAS := C1.QUARTA_U;
vAULAS_ANTES_INTERVALO := C1.H_INTERVALO_QUA - C1.H_INICIO_TURNO;
vQTD_AULAS_NO_DIA := C1.AULAS_QUA;
vPRIMEIRA_AULA := C1.PRIMEIRA_AULA_QUA;
vAULA_MEIO := C1.AULA_MEIO_QUA;
vULTIMA_AULA := C1.ULTIMA_AULA_QUA;
vAULAS_SEQUENCIA := C1.QUA_AULAS_SEQ;
vH_INTERVALO := C1.H_INTERVALO_QUA;
vM_INTERVALO := C1.M_INTERVALO_QUA;
vMINUTOS_NO_DIA_INI_INTERVALO := CASE WHEN C1.MINUTOS_NO_DIA_INI_INTER_QUA <> 0 THEN C1.MINUTOS_NO_DIA_INI_INTER_QUA ELSE C1.MINUTOS_NO_DIA_INI_TURNO+120 END;  
vH_ATE_INTERVALO := C1.H_ATE_INTERVALO_QUA; 
vM_ATE_INTERVALO :=C1.M_ATE_INTERVALO_QUA; 
--dbms_output.put_line('--TEM_AULA_QUARTA: '||C1.DATA_DIA||' vAULAS: '||vAULAS||' vAULAS_SEQUENCIA: '||vAULAS_SEQUENCIA||' vQTD_AULAS_NO_DIA: '|| vQTD_AULAS_NO_DIA||' vPRIMEIRA_AULA: '||vPRIMEIRA_AULA||' vAULA_MEIO: '||vAULA_MEIO||' vULTIMA_AULA: '||vULTIMA_AULA||' C1.TOTAL_MINUTOS_AULA: '||C1.TOTAL_MINUTOS_AULA||' C1.INTERVALO_QUARTA_U: '||C1.INTERVALO_QUARTA_U||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vAULAS_ANTES_INTERVALO: '||vAULAS_ANTES_INTERVALO||' vH_INTERVALO: '||vH_INTERVALO||' vM_INTERVALO: '||vM_INTERVALO||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vH_ATE_INTERVALO: '||vH_ATE_INTERVALO||' vM_ATE_INTERVALO: '||vM_ATE_INTERVALO);
vPRIMEIRA_MARCACAO := C1.PRIMEIRA_MARCACAO_QUA;
vSEGUNDA_MARCACAO := C1.SEGUNDA_MARCACAO_QUA;
vTERCEIRA_MARCACAO := C1.TERCEIRA_MARCACAO_QUA;
vQUARTA_MARCACAO := C1.QUARTA_MARCACAO_QUA;
--dbms_output.put_line('--vMINUTOS_NO_DIA_INI_TURNO: '||vMINUTOS_NO_DIA_INI_TURNO ||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);

ELSE
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;
END IF;

IF C1.NRO_DIA_SEMANA = 5 THEN
IF C1.AULAS_QUI <> 0 
AND ( TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') >= TO_DATE(C1.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') <= TO_DATE(C1.FIM_JORNADA_U,'DD/MM/YYYY'))
THEN
--INICIO--------------QUINTA-FEIRA
vGRAVA := 'S';
vAULAS := C1.QUINTA_U;
vAULAS_ANTES_INTERVALO := C1.H_INTERVALO_QUI - C1.H_INICIO_TURNO;
vQTD_AULAS_NO_DIA := C1.AULAS_QUI;
vPRIMEIRA_AULA := C1.PRIMEIRA_AULA_QUI;
vAULA_MEIO := C1.AULA_MEIO_QUI;
vULTIMA_AULA := C1.ULTIMA_AULA_QUI;
vAULAS_SEQUENCIA := C1.QUI_AULAS_SEQ;
vH_INTERVALO := C1.H_INTERVALO_QUI;
vM_INTERVALO := C1.M_INTERVALO_QUI;
vMINUTOS_NO_DIA_INI_INTERVALO := CASE WHEN C1.MINUTOS_NO_DIA_INI_INTER_QUI <> 0 THEN C1.MINUTOS_NO_DIA_INI_INTER_QUI ELSE C1.MINUTOS_NO_DIA_INI_TURNO+120 END;   
vH_ATE_INTERVALO := C1.H_ATE_INTERVALO_QUI; 
vM_ATE_INTERVALO :=C1.M_ATE_INTERVALO_QUI; 
--dbms_output.put_line('--TEM_AULA_QUINTA: '||C1.DATA_DIA||' vAULAS: '||vAULAS||' vAULAS_SEQUENCIA: '||vAULAS_SEQUENCIA||' vQTD_AULAS_NO_DIA: '|| vQTD_AULAS_NO_DIA||' vPRIMEIRA_AULA: '||vPRIMEIRA_AULA||' vAULA_MEIO: '||vAULA_MEIO||' vULTIMA_AULA: '||vULTIMA_AULA||' C1.TOTAL_MINUTOS_AULA: '||C1.TOTAL_MINUTOS_AULA||' C1.INTERVALO_QUINTA_U: '||C1.INTERVALO_QUINTA_U||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vAULAS_ANTES_INTERVALO: '||vAULAS_ANTES_INTERVALO||' vH_INTERVALO: '||vH_INTERVALO||' vM_INTERVALO: '||vM_INTERVALO||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vH_ATE_INTERVALO: '||vH_ATE_INTERVALO||' vM_ATE_INTERVALO: '||vM_ATE_INTERVALO);
vPRIMEIRA_MARCACAO := C1.PRIMEIRA_MARCACAO_QUI;
vSEGUNDA_MARCACAO := C1.SEGUNDA_MARCACAO_QUI;
vTERCEIRA_MARCACAO := C1.TERCEIRA_MARCACAO_QUI;
vQUARTA_MARCACAO := C1.QUARTA_MARCACAO_QUI;
--dbms_output.put_line('--vMINUTOS_NO_DIA_INI_TURNO: '||vMINUTOS_NO_DIA_INI_TURNO ||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);

ELSE
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;
END IF;

IF C1.NRO_DIA_SEMANA = 6 THEN
IF C1.AULAS_SEX <> 0 
AND ( TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') >= TO_DATE(C1.INICIO_JORNADA_U,'DD/MM/YYYY') AND TO_DATE(C1.DATA_DIA,'DD/MM/YYYY') <= TO_DATE(C1.FIM_JORNADA_U,'DD/MM/YYYY'))
THEN
--INICIO--------------SEXTA-FEIRA
vGRAVA := 'S';
vAULAS := C1.SEXTA_U;
vAULAS_ANTES_INTERVALO := C1.H_INTERVALO_SEX - C1.H_INICIO_TURNO;
vQTD_AULAS_NO_DIA := C1.AULAS_SEX;
vPRIMEIRA_AULA := C1.PRIMEIRA_AULA_SEX;
vAULA_MEIO := C1.AULA_MEIO_SEX;
vULTIMA_AULA := C1.ULTIMA_AULA_SEX;
vAULAS_SEQUENCIA := C1.SEX_AULAS_SEQ;
vH_INTERVALO := C1.H_INTERVALO_SEX;
vM_INTERVALO := C1.M_INTERVALO_SEX;
vMINUTOS_NO_DIA_INI_INTERVALO := CASE WHEN C1.MINUTOS_NO_DIA_INI_INTER_SEX <> 0 THEN C1.MINUTOS_NO_DIA_INI_INTER_SEX ELSE C1.MINUTOS_NO_DIA_INI_TURNO+120 END;   
vH_ATE_INTERVALO := C1.H_ATE_INTERVALO_SEX; 
vM_ATE_INTERVALO :=C1.M_ATE_INTERVALO_SEX; 
--dbms_output.put_line('--TEM_AULA_SEXTA: '||C1.DATA_DIA||' vAULAS: '||vAULAS||' vAULAS_SEQUENCIA: '||vAULAS_SEQUENCIA||' vQTD_AULAS_NO_DIA: '|| vQTD_AULAS_NO_DIA||' vPRIMEIRA_AULA: '||vPRIMEIRA_AULA||' vAULA_MEIO: '||vAULA_MEIO||' vULTIMA_AULA: '||vULTIMA_AULA||' C1.TOTAL_MINUTOS_AULA: '||C1.TOTAL_MINUTOS_AULA||' C1.INTERVALO_SEXTA_U: '||C1.INTERVALO_SEXTA_U||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vAULAS_ANTES_INTERVALO: '||vAULAS_ANTES_INTERVALO||' vH_INTERVALO: '||vH_INTERVALO||' vM_INTERVALO: '||vM_INTERVALO||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vH_ATE_INTERVALO: '||vH_ATE_INTERVALO||' vM_ATE_INTERVALO: '||vM_ATE_INTERVALO);
vPRIMEIRA_MARCACAO := C1.PRIMEIRA_MARCACAO_SEX;
vSEGUNDA_MARCACAO := C1.SEGUNDA_MARCACAO_SEX;
vTERCEIRA_MARCACAO := C1.TERCEIRA_MARCACAO_SEX;
vQUARTA_MARCACAO := C1.QUARTA_MARCACAO_SEX;
--dbms_output.put_line('--vMINUTOS_NO_DIA_INI_TURNO: '||vMINUTOS_NO_DIA_INI_TURNO ||' vMINUTOS_NO_DIA_INI_INTERVALO: '||vMINUTOS_NO_DIA_INI_INTERVALO||' vMINUTOS_INTERVALO: '||vMINUTOS_INTERVALO||' vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);

ELSE
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, TOTAL_REGENCIA, TIPO_REGISTRO)VALUES(C1.CPF, 'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, 0, 0, 0, 'DE/PARA_EXTENSOES_2023');COMMIT;
END IF;
END IF;

--FIM--NOVO LOCAL EM 7/6/23 DEFINI DIA DA SEMANA PARA A VARIAVEL vAULAS


--/*
IF  C1.TURNO_U NOT IN ('NOITE','INTEGRAL') AND C1.DURACAO_AULA_U = '01:00'--adicionado em 25/8/23 parte turno INTEGRAL ----------------------------------------DIFERENCIANDO PROFESSORES POR (FUNDAMENTAL, INFANTIL, EJA)
--comentado em 25/8/23---IF  C1.TURNO_U <> 'NOITE' AND C1.DURACAO_AULA_U = '01:00'------------------------------------------DIFERENCIANDO PROFESSORES POR (FUNDAMENTAL, INFANTIL, EJA)
THEN

--INICIO--IF INTERNO ---------------------------------------PARA CALCULAR OS HORARIOS --------------------------PROFESSOR FUNDAMENTAL AULA DE 1 HORA COM INTERVALO DE RECREIO
IF vGRAVA = 'S' THEN

-----------------QUARTA TENTATIVA 22/6/23
    --dbms_output.put_line('--QUARTA TENTATIVA 22/6/23');
    ---------------------INICIO COM 2 MARCACOES INICIAIS-------------------------------------
    IF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO < vPRIMEIRA_MARCACAO AND vPRIMEIRA_MARCACAO NOT BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
   -- dbms_output.put_line('--CENARIO FUNDAMENTAL 1: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO < vPRIMEIRA_MARCACAO AND vPRIMEIRA_MARCACAO NOT BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 1';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vPRIMEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 2: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vPRIMEIRA_MARCACAO');
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 2';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vPRIMEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 3: vTERCEIRA_MARCACAO IS NULL AND vPRIMEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO; --vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO; --vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 3';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vPRIMEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 4: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vPRIMEIRA_MARCACAO ');
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 4';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 5: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vSEGUNDA_MARCACAO');
    vQUARTA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 5';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 6: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vSEGUNDA_MARCACAO');
    vQUARTA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 6';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vSEGUNDA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 7: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vSEGUNDA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vQUARTA_MARCACAO :=(vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO))) + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vTERCEIRA_MARCACAO := vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 7';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 8: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vSEGUNDA_MARCACAO');
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 8';

    ELSIF vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 9: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vSEGUNDA_MARCACAO');
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 9';

    ---------------------INICIO COM 4 MARCACOES INICIAIS-------------------------------------
    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO < vPRIMEIRA_MARCACAO AND vPRIMEIRA_MARCACAO NOT BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 10: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO < vPRIMEIRA_MARCACAO AND vPRIMEIRA_MARCACAO NOT BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 10';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vPRIMEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 11: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vPRIMEIRA_MARCACAO');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 11';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vPRIMEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 12: vTERCEIRA_MARCACAO IS NOT NULL AND vPRIMEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;  --vQUARTA_MARCACAO := vQUARTA_MARCACAO + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;  --vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;  --vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO; --vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + (vMINUTOS_INTERVALO-(vPRIMEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 12';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vPRIMEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 13: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vPRIMEIRA_MARCACAO ');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vPRIMEIRA_MARCACAO := vPRIMEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 13';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 14: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vSEGUNDA_MARCACAO');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 14';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 15: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vSEGUNDA_MARCACAO');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO := vSEGUNDA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 15';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vSEGUNDA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 16: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vSEGUNDA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO :=(vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO))) + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vTERCEIRA_MARCACAO := vSEGUNDA_MARCACAO + (vMINUTOS_INTERVALO-(vSEGUNDA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vSEGUNDA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 16';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vSEGUNDA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 17: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vSEGUNDA_MARCACAO');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 17'; 

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vSEGUNDA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO < vTERCEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 18: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vPRIMEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vSEGUNDA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO < vTERCEIRA_MARCACAO');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 18';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vTERCEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 19: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO = vTERCEIRA_MARCACAO');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 19';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vTERCEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 20: vTERCEIRA_MARCACAO IS NOT NULL AND vTERCEIRA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;--vQUARTA_MARCACAO := vQUARTA_MARCACAO + (vMINUTOS_INTERVALO-(vTERCEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + vMINUTOS_INTERVALO; --vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO + (vMINUTOS_INTERVALO-(vTERCEIRA_MARCACAO-vMINUTOS_NO_DIA_INI_INTERVALO));
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 20';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vTERCEIRA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 21: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO = vTERCEIRA_MARCACAO ');
    vQUARTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vTERCEIRA_MARCACAO := vTERCEIRA_MARCACAO  + vMINUTOS_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 21';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vQUARTA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 22: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) < vQUARTA_MARCACAO');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 22';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vQUARTA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 23: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) = vQUARTA_MARCACAO');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 23';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vQUARTA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO) THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 24: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vQUARTA_MARCACAO BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO + 1 AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vSEXTA_MARCACAO := vQUARTA_MARCACAO + vMINUTOS_INTERVALO;
    vQUINTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO+ vMINUTOS_INTERVALO;
    vQUARTA_MARCACAO := vMINUTOS_NO_DIA_INI_INTERVALO;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO||' vQUINTA_MARCACAO: '||vQUINTA_MARCACAO||' vSEXTA_MARCACAO: '||vSEXTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 24';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vQUARTA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 25: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO = vQUARTA_MARCACAO');
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 25';

    ELSIF vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vQUARTA_MARCACAO THEN
    --dbms_output.put_line('--CENARIO FUNDAMENTAL 26: vTERCEIRA_MARCACAO IS NOT NULL AND vMINUTOS_NO_DIA_INI_INTERVALO > vTERCEIRA_MARCACAO AND vMINUTOS_NO_DIA_INI_INTERVALO > vQUARTA_MARCACAO');
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'CENARIO FUNDAMENTAL 26';          

    ELSE
    dbms_output.put_line('--NAO MAPEADO AINDA');

    END IF;---IF GERAL DOS CENARIOS DO FUNDAMENTAL  

END IF;
--FIM--IF INTERNO ------------------------------------------PARA CALCULAR OS HORARIOS--------------------------PROFESSOR FUNDAMENTAL AULA DE 1 HORA COM INTERVALO DE RECREIO

END IF; ------------------------------------------DIFERENCIANDO PROFESSORES POR (FUNDAMENTAL, INFANTIL, EJA)
--*/
--/*
--INICIO ---NOVO EM 25/8/23  PARA FIXAR HORARIO DA AULA DE REFORCO PELA MANHA APOS AS 11H30
IF  C1.TURNO_U = 'INTEGRAL' AND C1.DURACAO_AULA_U = '01:00' THEN
   -- dbms_output.put_line('--CENARIO FUNDAMENTAL 1: vTERCEIRA_MARCACAO IS NULL AND vMINUTOS_NO_DIA_INI_INTERVALO < vPRIMEIRA_MARCACAO AND vPRIMEIRA_MARCACAO NOT BETWEEN vMINUTOS_NO_DIA_INI_INTERVALO AND (vMINUTOS_NO_DIA_INI_INTERVALO + vMINUTOS_INTERVALO)');
    vPRIMEIRA_MARCACAO := 690;
    vSEGUNDA_MARCACAO := 750;
    --dbms_output.put_line('--vPRIMEIRA_MARCACAO: '||vPRIMEIRA_MARCACAO||' vSEGUNDA_MARCACAO: '||vSEGUNDA_MARCACAO||' vTERCEIRA_MARCACAO: '||vTERCEIRA_MARCACAO||' vQUARTA_MARCACAO: '||vQUARTA_MARCACAO);
    vOBS_PROCESSAMENTO := 'INTEGRAL REFORCO MANHA';
END IF;
--FIM---NOVO EM 25/8/23  PARA FIXAR HORARIO DA AULA DE REFORCO PELA MANHA APOS AS 11H30
--*/


IF vSEXTA_MARCACAO IS NOT NULL THEN --PARA GRAVAR NA TABELA E DAR CONTINUIDADE NO PROCESSO
/*dbms_output.put_line('INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, MARCACAO_3, MARCACAO_4, MARCACAO_5, MARCACAO_6, OBS_PROCESSAMENTO) VALUES ( '||C1.ID_HORARIO||', TO_DATE('''||C1.DATA_DIA||''',''DD/MM/YYYY'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vTERCEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vTERCEIRA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vQUARTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUARTA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vQUINTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUINTA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vSEXTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEXTA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,vOBS_PROCESSAMENTO );COMMIT;');
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (DATA_PROCESSAMENTO, ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, MARCACAO_3, MARCACAO_4, MARCACAO_5, MARCACAO_6, OBS_PROCESSAMENTO, DADOS_REGENCIA) 
VALUES (SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vTERCEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vTERCEIRA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vQUARTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUARTA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vQUINTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUINTA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vSEXTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEXTA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,vOBS_PROCESSAMENTO
,LPAD(C1.MINUTOS_NO_DIA_INI_TURNO,4,0)||'-'||LPAD(vPRIMEIRA_MARCACAO,4,0)||'-'||LPAD(vSEGUNDA_MARCACAO,4,0)||'-'||LPAD(vTERCEIRA_MARCACAO,4,0)||'-'||LPAD(vQUARTA_MARCACAO,4,0)||'-'||LPAD(vQUINTA_MARCACAO,4,0)||'-'||LPAD(vSEXTA_MARCACAO,4,0)
);COMMIT;
*/
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vPRIMEIRA_MARCACAO, vSEGUNDA_MARCACAO, vOBS_PROCESSAMENTO, vSEGUNDA_MARCACAO-vPRIMEIRA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vTERCEIRA_MARCACAO, vQUARTA_MARCACAO, vOBS_PROCESSAMENTO, vQUARTA_MARCACAO-vTERCEIRA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF,'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vQUINTA_MARCACAO, vSEXTA_MARCACAO, vOBS_PROCESSAMENTO, vSEXTA_MARCACAO-vQUINTA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;                                

ELSIF vSEXTA_MARCACAO IS NULL AND vQUARTA_MARCACAO IS NOT NULL THEN --PARA GRAVAR NA TABELA E DAR CONTINUIDADE NO PROCESSO
/*dbms_output.put_line('INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, MARCACAO_3, MARCACAO_4, OBS_PROCESSAMENTO) VALUES ('||C1.ID_HORARIO||', TO_DATE('''||C1.DATA_DIA||''',''DD/MM/YYYY'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vTERCEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vTERCEIRA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vQUARTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUARTA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,vOBS_PROCESSAMENTO );COMMIT;');
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (DATA_PROCESSAMENTO, ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, MARCACAO_3, MARCACAO_4, OBS_PROCESSAMENTO, DADOS_REGENCIA) 
VALUES (SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vTERCEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vTERCEIRA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vQUARTA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vQUARTA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,vOBS_PROCESSAMENTO
,LPAD(C1.MINUTOS_NO_DIA_INI_TURNO,4,0)||'-'||LPAD(vPRIMEIRA_MARCACAO,4,0)||'-'||LPAD(vSEGUNDA_MARCACAO,4,0)||'-'||LPAD(vTERCEIRA_MARCACAO,4,0)||'-'||LPAD(vQUARTA_MARCACAO,4,0)
);COMMIT;*/

INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF, 'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vPRIMEIRA_MARCACAO, vSEGUNDA_MARCACAO, vOBS_PROCESSAMENTO, vSEGUNDA_MARCACAO-vPRIMEIRA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF, 'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vTERCEIRA_MARCACAO, vQUARTA_MARCACAO, vOBS_PROCESSAMENTO, vQUARTA_MARCACAO-vTERCEIRA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;


ELSIF vSEXTA_MARCACAO IS NULL AND vQUARTA_MARCACAO IS NULL AND vSEGUNDA_MARCACAO IS NOT NULL THEN --PARA GRAVAR NA TABELA E DAR CONTINUIDADE NO PROCESSO
/*dbms_output.put_line('INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, OBS_PROCESSAMENTO) VALUES ('||C1.ID_HORARIO||', TO_DATE('''||C1.DATA_DIA||''',''DD/MM/YYYY'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
,TO_CHAR(TO_DATE('''||C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00'',''DD/MM/YYYY HH24:MI:SS''),''DD/MM/YYYY HH24:MI:SS'')
, vOBS_PROCESSAMENTO );COMMIT;');
INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_ARQ_DATAS (DATA_PROCESSAMENTO, ID_HORARIO, DATA, MARCACAO_1, MARCACAO_2, OBS_PROCESSAMENTO, DADOS_REGENCIA) 
VALUES (SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vPRIMEIRA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vPRIMEIRA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,TO_CHAR(TO_DATE(C1.DATA_DIA||' '|| LPAD(TRUNC(vSEGUNDA_MARCACAO/60,0),2,0) ||':'|| LPAD(MOD(vSEGUNDA_MARCACAO,60),2,0) || ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
,vOBS_PROCESSAMENTO
,LPAD(C1.MINUTOS_NO_DIA_INI_TURNO,4,0)||'-'||LPAD(vPRIMEIRA_MARCACAO,4,0)||'-'||LPAD(vSEGUNDA_MARCACAO,4,0)
);COMMIT;*/

INSERT INTO PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS(CPF, TIPO, DATA_PROCESSAMENTO, ID_HORARIO, DATA, INICIO_TURNO, INICIO_REGENCIA, FIM_REGENCIA, OBS_PROCESSAMENTO, TOTAL_REGENCIA, TIPO_REGISTRO)
                                VALUES (C1.CPF, 'DIA', SYSDATE, C1.ID_HORARIO, TO_DATE(C1.DATA_DIA,'DD/MM/YYYY'), C1.MINUTOS_NO_DIA_INI_TURNO, vPRIMEIRA_MARCACAO, vSEGUNDA_MARCACAO, vOBS_PROCESSAMENTO, vSEGUNDA_MARCACAO-vPRIMEIRA_MARCACAO, 'DE/PARA_EXTENSOES_2023');COMMIT;


END IF; --PARA GRAVAR NA TABELA E DAR CONTINUIDADE NO PROCESSO  


--comentado IF EM 5/7/23 PARA GERAR DE TODOS --END IF;----------------------------------------------------------------------------- PARA INSERIR REGISTROS NOVOS


vPRIMEIRA_MARCACAO := NULL;
vSEGUNDA_MARCACAO := NULL;
vTERCEIRA_MARCACAO := NULL;
vQUARTA_MARCACAO := NULL;
vQUINTA_MARCACAO := NULL;
vSEXTA_MARCACAO := NULL;
vOBS_PROCESSAMENTO := NULL;

--FIM-------------------------------PRIMEIRA PARTE ------------------------------INCLUSAO DE UMA NOVO REGISTRO DE JORNADA--------------------------------------------------------------------------------


vGRAVA := 'N';
END LOOP;


--UPDATE PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES SET DATA_PROCESSAMENTO = SYSDATE WHERE DATA_PROCESSAMENTO IS NULL; COMMIT;---ATUALIZA OS REGISTROS COMO PROCESSADOS

END;

END;
--*/