
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP10_EXCLUI_DUPLICIDAD" (DATA_INICIO IN DATE)
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_exclui_duplicidades_DE_PARA_EXTENSOES_2023.sql)

--kELLYSSON NOVO EM 17/10/23 
--Kellysson em 5/9/23 b2 (sql_ajuste_DE_PARA_EXTENSOES_2023_b2.sql) para ajuste DATA_INICIO_U E DATA_FIM_U pARA INICIO_JORNADA_U e FIM_JORNADA_U
--Kellysson em 16/8/23 baseado (sql_relatorio_pos_passo8_DE-PARA.sql)
--9º PASSO TEMPORARIO OU NAO PARA O DE/PARA EM CASOS QUE NO FINAL DO PASSO 8 NAO BATEU A QUANTIDADE DE HORAS/MINUTOS NA SEMANA
--/*
DECLARE 
vCONTADOR NUMBER;
vDATA_INICIO DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;

FOR C1 IN (

SELECT X2.* FROM(
SELECT 
ROW_NUMBER() OVER(PARTITION BY ID_JORNADA ORDER BY ID_JORNADA, ROWID DESC)ORDEM_ID_JORNADA,
ROWID, X.* FROM SMARH_INT_PE_EXTENSOES_JORNAD X WHERE X.ID_JORNADA IN (SELECT ID_JORNADA FROM(
(SELECT ID_HORARIO, ID_JORNADA , COUNT(1) QTD FROM SMARH_INT_PE_EXTENSOES_JORNAD WHERE TIPO_EXTENSAO LIKE 'EXTENSAO_SGE_DE_PARA_2023%' 
AND TO_DATE(DT_INICIO,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
GROUP BY ID_HORARIO, ID_JORNADA HAVING COUNT(1)>1 )))
ORDER BY ID_JORNADA, ROWID DESC
)X2 WHERE X2.ORDEM_ID_JORNADA = 1


)LOOP
vCONTADOR := vCONTADOR +1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR);

dbms_output.put_line('**DELETE C1.ID_REGISTRO_ARQUIVO: '||C1.ID_REGISTRO_ARQUIVO ||' C1.ID_HORARIO: '||C1.ID_HORARIO||' C1.ROWID:' ||C1.ROWID);
DELETE PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD WHERE ROWID = C1.ROWID; COMMIT;

END LOOP;
END;
--*/
END;