
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP9_GRAVA_REG_ARTE_MAN" (DATA_INICIO IN DATE)
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_manual_DE_PARA_EXTENSOES_2023_b3.sql)

--Kellysson em 18/9/23 b3--ajustar para colocar 1/3 campo HORAS_SEMANAIS e NÃO CADASTRAR AS CONCOMITANCIAS (C1.CARGA_HORARIA_CHEIA, --AJUSTADO EM 18/9/23--C1.CARGA_HORARIA,)
--Kellysson em 5/9/23 b2 (sql_manual_DE_PARA_EXTENSOES_2023_b2.sql) para ajuste DATA_INICIO_U E DATA_FIM_U pARA INICIO_JORNADA_U e FIM_JORNADA_U

--Kellysson em 17/8/23 baseado (sql_manual_DE_PARA_EXTENSOES_2023_b1.sql)
--10º passo insercao 'manual' dos que faltaram do passo 2 ate passo 9
--/*
DECLARE 
vCONTADOR NUMBER;
vB BOOLEAN := TRUE;
vDATA_INICIO DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;

FOR C1 IN (
--*/

--SELECT CENARIO_FINAL, COUNT(1) FROM(--SINTETICO  

SELECT X5.*,
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_SEG/60) ELSE 0 END H_INICIO_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_SEG,60) ELSE 0 END M_INICIO_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_SEG + X5.TEMPO_GRAVAR_SEG)/60) ELSE 0 END H_FIM_SEGUNDA,
CASE WHEN X5.TEMPO_GRAVAR_SEG IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_SEG + X5.TEMPO_GRAVAR_SEG),60) ELSE 0 END M_FIM_SEGUNDA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_TER/60) ELSE 0 END H_INICIO_TERCA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_TER,60) ELSE 0 END M_INICIO_TERCA, 
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_TER + X5.TEMPO_GRAVAR_TER)/60) ELSE 0 END H_FIM_TERCA,
CASE WHEN X5.TEMPO_GRAVAR_TER IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_TER + X5.TEMPO_GRAVAR_TER),60) ELSE 0 END M_FIM_TERCA,
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_QUA/60) ELSE 0 END H_INICIO_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_QUA,60) ELSE 0 END M_INICIO_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_QUA + X5.TEMPO_GRAVAR_QUA)/60) ELSE 0 END H_FIM_QUARTA,
CASE WHEN X5.TEMPO_GRAVAR_QUA IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_QUA + X5.TEMPO_GRAVAR_QUA),60) ELSE 0 END M_FIM_QUARTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_QUI/60) ELSE 0 END H_INICIO_QUINTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_QUI,60) ELSE 0 END M_INICIO_QUINTA, 
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_QUI + X5.TEMPO_GRAVAR_QUI)/60) ELSE 0 END H_FIM_QUINTA,
CASE WHEN X5.TEMPO_GRAVAR_QUI IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_QUI + X5.TEMPO_GRAVAR_QUI),60) ELSE 0 END M_FIM_QUINTA,
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN TRUNC(X5.PRIMEIRA_MARCACAO_SEX/60) ELSE 0 END H_INICIO_SEXTA, 
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN MOD(X5.PRIMEIRA_MARCACAO_SEX,60) ELSE 0 END M_INICIO_SEXTA, 
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN TRUNC((X5.PRIMEIRA_MARCACAO_SEX + X5.TEMPO_GRAVAR_SEX)/60) ELSE 0 END H_FIM_SEXTA,
CASE WHEN X5.TEMPO_GRAVAR_SEX IS NOT NULL THEN MOD((X5.PRIMEIRA_MARCACAO_SEX + X5.TEMPO_GRAVAR_SEX),60) ELSE 0 END M_FIM_SEXTA
FROM (
SELECT X4.* 
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_SEG ELSE X4.HM_AULAS_SEG + (X4.HM_AULAS_SEG/2)END TEMPO_GRAVAR_SEG ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_TER ELSE X4.HM_AULAS_TER + (X4.HM_AULAS_TER/2)END TEMPO_GRAVAR_TER ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_QUA ELSE X4.HM_AULAS_QUA + (X4.HM_AULAS_QUA/2)END TEMPO_GRAVAR_QUA ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_QUI ELSE X4.HM_AULAS_QUI + (X4.HM_AULAS_QUI/2)END TEMPO_GRAVAR_QUI ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
,CASE WHEN X4.COORDENACAO = 'SIM' OR X4.CARGA_HORARIA = '22:30' THEN X4.HM_AULAS_SEX ELSE X4.HM_AULAS_SEX + (X4.HM_AULAS_SEX/2)END TEMPO_GRAVAR_SEX ---NAO ADICIONAR 1/3 DE EXTRACLASSE PARA CARGA_HORARIA JA COM 22:30 SENDO COORDENADOR = SIM
FROM (
SELECT X3.* 
,CASE WHEN X3.SEGUNDA IS NULL THEN 0 ELSE X3.AULAS_SEG * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEG --NOVO 16/8/23
,CASE WHEN X3.SEGUNDA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEG - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEG--NOVO 16/8/23
,CASE WHEN X3.TERCA IS NULL THEN 0 ELSE X3.AULAS_TER * X3.TOTAL_MINUTOS_AULA END HM_AULAS_TER --NOVO 16/8/23
,CASE WHEN X3.TERCA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_TER - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_TER--NOVO 16/8/23
,CASE WHEN X3.QUARTA IS NULL THEN 0 ELSE X3.AULAS_QUA * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUA --NOVO 16/8/23
,CASE WHEN X3.QUARTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUA - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUA--NOVO 16/8/23
,CASE WHEN X3.QUINTA IS NULL THEN 0 ELSE X3.AULAS_QUI * X3.TOTAL_MINUTOS_AULA END HM_AULAS_QUI --NOVO 16/8/23
,CASE WHEN X3.QUINTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_QUI - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_QUI--NOVO 16/8/23
,CASE WHEN X3.SEXTA IS NULL THEN 0 ELSE X3.AULAS_SEX * X3.TOTAL_MINUTOS_AULA END HM_AULAS_SEX --NOVO 16/8/23
,CASE WHEN X3.SEXTA IS NULL THEN 0 ELSE X3.MINUTOS_NO_DIA_INI_TURNO +((X3.PRIMEIRA_AULA_SEX - 1)* X3.TOTAL_MINUTOS_AULA) END PRIMEIRA_MARCACAO_SEX--NOVO 16/8/23
FROM(
SELECT X2.* 
,CASE WHEN X2.DURACAO_AULA = '01:00' THEN 60 WHEN X2.DURACAO_AULA = '01:30' THEN 90 ELSE 0 END TOTAL_MINUTOS_AULA--NOVO 16/8/23
,X2.H_INICIO_TURNO * 60 + X2.M_INICIO_TURNO MINUTOS_NO_DIA_INI_TURNO--NOVO 16/8/23
,CASE WHEN X2.SEGUNDA IS NULL THEN 0 ELSE LENGTH(X2.SEGUNDA)- REGEXP_COUNT(X2.SEGUNDA,',')END AULAS_SEG--NOVO 16/8/23
,CASE WHEN X2.SEGUNDA IS NULL THEN '0' ELSE SUBSTR(X2.SEGUNDA,1,1)END PRIMEIRA_AULA_SEG--NOVO 16/8/23
,CASE WHEN X2.TERCA IS NULL THEN 0 ELSE LENGTH(X2.TERCA)- REGEXP_COUNT(X2.TERCA,',')END AULAS_TER--NOVO 16/8/23
,CASE WHEN X2.TERCA IS NULL THEN '0' ELSE SUBSTR(X2.TERCA,1,1)END PRIMEIRA_AULA_TER--NOVO 16/8/23
,CASE WHEN X2.QUARTA IS NULL THEN 0 ELSE LENGTH(X2.QUARTA)- REGEXP_COUNT(X2.QUARTA,',')END AULAS_QUA--NOVO 16/8/23
,CASE WHEN X2.QUARTA IS NULL THEN '0' ELSE SUBSTR(X2.QUARTA,1,1)END PRIMEIRA_AULA_QUA--NOVO 16/8/23
,CASE WHEN X2.QUINTA IS NULL THEN 0 ELSE LENGTH(X2.QUINTA)- REGEXP_COUNT(X2.QUINTA,',')END AULAS_QUI--NOVO 16/8/23
,CASE WHEN X2.QUINTA IS NULL THEN '0' ELSE SUBSTR(X2.QUINTA,1,1)END PRIMEIRA_AULA_QUI--NOVO 16/8/23
,CASE WHEN X2.SEXTA IS NULL THEN 0 ELSE LENGTH(X2.SEXTA)- REGEXP_COUNT(X2.SEXTA,',')END AULAS_SEX--NOVO 16/8/23
,CASE WHEN X2.SEXTA IS NULL THEN '0' ELSE SUBSTR(X2.SEXTA,1,1)END PRIMEIRA_AULA_SEX--NOVO 16/8/23
FROM(
SELECT 
X.HORAS_TOTAIS+X.MINUTOS_TOTAIS HM_TOTAIS
,TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60) HTOTAIS
,((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)-(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60)*60)) FRACAO_MIN_TOTAIS
, LPAD(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60),2,0)||':'||LPAD(((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)-(TRUNC((X.HORAS_TOTAIS + X.MINUTOS_TOTAIS)/60)*60)),2,0) CARGA_HORARIA_CHEIA,
X.* FROM(
SELECT ID_JORNADA_U ID_JORNADA, COORDENACAO_U COORDENACAO, ID_HORARIO, BM_U BM, COD_ORGAO_U COD_ORGAO, TURNO_U TURNO, INICIO_JORNADA_U DATA_INICIO, FIM_JORNADA_U DATA_FIM, DT_CANCELAMENTO_USAR_U DATA_CANCELAMENTO, 
DURACAO_AULA_U DURACAO_AULA, CARGA_HORARIA, HORA_INI_TURNO_U HORA_INI_TURNO, SEGUNDA_U SEGUNDA, TERCA_U TERCA, QUARTA_U QUARTA, QUINTA_U QUINTA, SEXTA_U SEXTA
,CASE WHEN LTRIM(SUBSTR(HORA_INI_TURNO_U,1,2),0) IS NULL OR LENGTH(HORA_INI_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(HORA_INI_TURNO_U,1,2),0)END H_INICIO_TURNO,--NOVO 16/8/23
CASE WHEN LTRIM(SUBSTR(HORA_INI_TURNO_U,4,2),0) IS NULL OR LENGTH(HORA_INI_TURNO_U)<> 5 THEN '0' ELSE LTRIM(SUBSTR(HORA_INI_TURNO_U,4,2),0)END M_INICIO_TURNO,--NOVO 16/8/23
--(SUBSTR(CARGA_HORARIA,1,2)+ (SUBSTR(CARGA_HORARIA,1,2)/2))HORASMINUTOS_TOTAIS,
--((SUBSTR(CARGA_HORARIA,1,2)+ (SUBSTR(CARGA_HORARIA,1,2)/2)))*60 + (MOD((TRUNC((SUBSTR(CARGA_HORARIA,1,2)+ (SUBSTR(CARGA_HORARIA,1,2)/2))))*60,2)*60)*60 HORAS_TOTAIS
--,CASE WHEN SUBSTR(CARGA_HORARIA,4,2) = '00' THEN 0 ELSE SUBSTR(CARGA_HORARIA,4,2)+ (SUBSTR(CARGA_HORARIA,4,2)/2)END MINUTOS_TOTAIS
CASE WHEN CARGA_HORARIA = '22:30' THEN 1320
ELSE ((SUBSTR(CARGA_HORARIA,1,2)+ (SUBSTR(CARGA_HORARIA,1,2)/2)))*60 + (MOD((TRUNC((SUBSTR(CARGA_HORARIA,1,2)+ (SUBSTR(CARGA_HORARIA,1,2)/2))))*60,2)*60)*60 
END HORAS_TOTAIS,
CASE WHEN CARGA_HORARIA = '22:30' THEN 30 
    WHEN CARGA_HORARIA <> '22:30' AND SUBSTR(CARGA_HORARIA,4,2) = '00' THEN 0 
ELSE SUBSTR(CARGA_HORARIA,4,2)+ (SUBSTR(CARGA_HORARIA,4,2)/2) END MINUTOS_TOTAIS
FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE) -----------------------------------*******************data do dia
AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
)X
WHERE X.ID_HORARIO IN (--16862,9335,12184,12866,17854,18445 --REGISTROS 1ª CARGA
--16890,21308,16862,13372,14935,16843,17065,21567,24480,25462 --REGISTROS SIMULACAO DIA 11/9/23
--22482,29565,29583,30421,31723,34041,34141,34481,34781,36481,36501,36721,36961,40281,40581,41182,41561,41721,21308,31521,10219,15246,16862,17065,21567,24480,24930,25462,26956,28421,31861,31862,33483,34726,36302,36562,41241-- 37 REGISTROS SEGUNDO DE/PARA 15/9/23
--10219,15246,40281,33483 --ajuste 4 do dia 22/9/23
--59549,59901,49502,51683,14028,34781,36481,40581,41561,52541,55601,58003,58581--3 CARGA EM 16/10/23
--60861--reprocessamento 20/10/23
--36501,59549,59901,62961,63062,63661,65481,66581,68861,69581,69922,70624,71283,72821,64481,67641,68503,68765,69821,70881,70941,71405,60105,69163,72141,72367--processamento dia 11/11/23
--73841,73601,58983,70924,71241--reprocessamento 16/11/23
--72367,74682,75961,75721,79741,79861,81181,81341,68062,77541,78721--PROCESSAMENTO 5/12/23
--83661,82821--re PROCESSAMENTO 6/12/23
--85561,88582,77541,78721--PROCESSAMENTO 8/1/24

--USAR A PARTIR DA SEGUNDA CARGA em 11/9/23 ---para ajuste no passo 10 logo abaixo
SELECT ID_HORARIO_USAR FROM(
SELECT I.ID_HORARIO ID_HORARIO_USAR, DP.ID_HORARIO, DP.QTD_CONCOMITA, I.ID_HORARIO||',' ID_H, I.*,F.*
FROM
(SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE) AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' 
AND TO_DATE(DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
)I --1246
LEFT OUTER JOIN
(SELECT * FROM SMARH_INT_PE_EXTENSOES_JORNAD WHERE TIPO_EXTENSAO LIKE 'EXTENSAO_SGE_DE_PARA_2023%' --AND TRUNC(DT_RECEBEU_CADASTRO) = TRUNC(SYSDATE)
AND (TRUNC(DT_RECEBEU_CADASTRO)= TRUNC(SYSDATE) OR TRUNC(DT_RECEBEU_CANCELAMENTO)= TRUNC(SYSDATE))
)F --1209, DIF 37
ON F.ID_HORARIO = I.ID_HORARIO
---------------------INICIO CONCOMITANCIAS
LEFT OUTER JOIN 
(SELECT  DP.ID_HORARIO, COUNT(1)QTD_CONCOMITA FROM(
select CPF, BM_U, TIPO_JORNADA_U, TURNO_U, DATA_INICIO_U, DATA_FIM_U, DT_CANCELAMENTO_USAR_U, ID_HORARIO, NOM_OFIC_ESCL, REGIONAL from( SELECT X.TIPO, X.CPF, X.BM_U,X.TIPO_JORNADA_U,X.TURNO_U,X.DATA_INICIO_U,X.DATA_FIM_U,X.DT_CANCELAMENTO_USAR_U, X.NOM_OFIC_ESCL, X.REGIONAL,
X.ORDEM_TURNO,X.ORDEM_ID_HORARIO_DIA,X.ORDEM_PAR_REG,X.ORDEM_DIA_CPF,X.ID_HORARIO,X.DATA, X.SEMANA_ANO, X.INICIO_TURNO,X.INICIO_REGENCIA,X.FIM_REGENCIA,X.DATA_PROCESSAMENTO,X.OBS_PROCESSAMENTO
FROM(SELECT  A.BM_U, A.TIPO_JORNADA_U, A.TURNO_U, A.DATA_INICIO_U, A.DATA_FIM_U, A.DT_CANCELAMENTO_USAR_U, A.NOM_OFIC_ESCL, A.REGIONAL,
CASE WHEN A.TURNO_U = 'MANHÃ' THEN 1 WHEN A.TURNO_U = 'INTEGRAL' THEN 1 WHEN A.TURNO_U = 'TARDE' THEN 2 WHEN A.TURNO_U = 'NOITE' THEN 3 END ORDEM_TURNO,
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.ID_HORARIO, D.DATA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_ID_HORARIO_DIA, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.ID_HORARIO, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.FIM_REGENCIA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_PAR_REG, 
ROW_NUMBER() OVER(PARTITION BY P.CPF, D.DATA ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC)ORDEM_DIA_CPF, 
TO_NUMBER(TO_CHAR(TO_DATE(D.DATA),'WW')) SEMANA_ANO, D.* FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS D LEFT OUTER JOIN (SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES  WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023' 
AND TO_DATE(DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
)A ON A.ID_HORARIO = D.ID_HORARIO
LEFT OUTER JOIN (SELECT M.CODIGO_EMPRESA, M.TIPO_CONTRATO, M.CODIGO_CONTRATO, M.CODIGO_PESSOA, P.CPF FROM ARTERH.RHPESS_CONTR_MEST M LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P ON P.CODIGO_EMPRESA = M.CODIGO_EMPRESA AND P.CODIGO = M.CODIGO_PESSOA)P
ON P.CODIGO_EMPRESA = '0001' AND P.TIPO_CONTRATO = '0001' AND P.CODIGO_CONTRATO = A.BM_U WHERE D.ID_HORARIO IN (SELECT ID_HORARIO FROM(SELECT ID_HORARIO, COUNT(1) FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES
GROUP BY ID_HORARIO)) AND D.OBS_PROCESSAMENTO IN ('CONCOMITA') AND D.TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
--AND TO_DATE(D.DATA_INICIO_U,'DD/MM/YYYY')>=  TO_DATE(vDATA_INICIO,'DD/MM/YYYY')--NOVO A PARTIR DE 2024
ORDER BY P.CPF, D.DATA, D.INICIO_TURNO, D.INICIO_REGENCIA, D.ID_HORARIO, D.ID_HORARIO, D.DATA_PROCESSAMENTO DESC )X )group by CPF, BM_U, TIPO_JORNADA_U, TURNO_U, DATA_INICIO_U, DATA_FIM_U, DT_CANCELAMENTO_USAR_U, ID_HORARIO, NOM_OFIC_ESCL, REGIONAL
)DP GROUP BY DP.ID_HORARIO
)DP ON DP.ID_HORARIO = I.ID_HORARIO
---------------------FIM CONCOMITANCIAS
WHERE F.ID_HORARIO IS NULL --37 REGISTROS
AND DP.ID_HORARIO IS NULL --TIRANDO AS CONCOMITANCIAS
ORDER BY I.OBS_PROCESSAMENTO, I.ID_HORARIO
)


)----------------------------------------------------------REGISTROS A TRATAR
)X2
)X3 
)X4
)X5



--)GROUP BY CENARIO_FINAL ORDER BY CENARIO_FINAL --SINTETICO

--/*
)LOOP
vCONTADOR := vCONTADOR +1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR);

INSERT INTO PONTO_ELETRONICO.SMARH_INT_PE_EXTENSOES_JORNAD (ID_JORNADA, ID_HORARIO, TIPO_EXTENSAO, CODIGO_EMPRESA, ID_REGISTRO_ARQUIVO, BM_SERVIDOR, 
CODIGO_ESCOLA, COD_LOCAL1, COD_LOCAL2, COD_LOCAL3, COD_LOCAL4, COD_LOCAL5, COD_LOCAL6, 
HORAS_SEMANAIS, TURNO, DT_INICIO, DT_FIM, DT_CANCELAMENTO, DT_RECEBEU_CADASTRO, DT_RECEBEU_CANCELAMENTO, 
HORARIO_INICIO_SEGUNDA, HORARIO_FIM_SEGUNDA, HORARIO_INICIO_TERCA, HORARIO_FIM_TERCA, HORARIO_INICIO_QUARTA, HORARIO_FIM_QUARTA, HORARIO_INICIO_QUINTA, HORARIO_FIM_QUINTA, HORARIO_INICIO_SEXTA, HORARIO_FIM_SEXTA)--10
VALUES
(C1.ID_JORNADA,C1.ID_HORARIO, 'EXTENSAO_SGE_DE_PARA_2023_PR_SGE_DP9', '0001', vCONTADOR, C1.BM, C1.COD_ORGAO, 
LPAD(SUBSTR(C1.COD_ORGAO,1,2),6,0), LPAD(SUBSTR(C1.COD_ORGAO,3,2),6,0), LPAD(SUBSTR(C1.COD_ORGAO,5,2),6,0), LPAD(SUBSTR(C1.COD_ORGAO,7,2),6,0), LPAD(SUBSTR(C1.COD_ORGAO,9,2),6,0), LPAD(SUBSTR(C1.COD_ORGAO,11,3),6,0), 
C1.CARGA_HORARIA_CHEIA, --AJUSTADO EM 18/9/23--C1.CARGA_HORARIA,
C1.TURNO, TO_CHAR(TO_DATE(C1.DATA_INICIO,'DD/MM/YYYY'),'DD/MM/YYYY'), TO_CHAR(TO_DATE(C1.DATA_FIM,'DD/MM/YYYY'),'DD/MM/YYYY'), 
CASE WHEN C1.DATA_CANCELAMENTO IS NOT NULL THEN TO_CHAR(TO_DATE(C1.DATA_CANCELAMENTO,'DD/MM/YYYY'),'DD/MM/YYYY') ELSE NULL END,
SYSDATE, 
CASE WHEN C1.DATA_CANCELAMENTO IS NOT NULL THEN SYSDATE ELSE NULL END, 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_SEGUNDA,2,0)||':'||LPAD(C1.M_INICIO_SEGUNDA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_SEGUNDA,2,0)||':'||LPAD(C1.M_FIM_SEGUNDA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_TERCA,2,0)||':'||LPAD(C1.M_INICIO_TERCA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),   
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_TERCA,2,0)||':'||LPAD(C1.M_FIM_TERCA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_QUARTA,2,0)||':'||LPAD(C1.M_INICIO_QUARTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_QUARTA,2,0)||':'||LPAD(C1.M_FIM_QUARTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_QUINTA,2,0)||':'||LPAD(C1.M_INICIO_QUINTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_QUINTA,2,0)||':'||LPAD(C1.M_FIM_QUINTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),  
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_INICIO_SEXTA,2,0)||':'||LPAD(C1.M_INICIO_SEXTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'), 
TO_CHAR(TO_DATE('01/01/2001 ' ||LPAD(C1.H_FIM_SEXTA,2,0)||':'||LPAD(C1.M_FIM_SEXTA,2,0)|| ':00','DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') 
); COMMIT;


END LOOP;
END;

END;
--*/