
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PR_SGE_DP5_REGRA1_EXTRA" 
AS 
BEGIN 

--Kellysson em 19/1/24 baseado (sql_4_regras_extraclasse_p1_b6.sql)

--Kellysson novo em 4/9/23 nova em sql_4_regras_extraclasse_p1_b6.sql--alterando NOT IN ('EXCLUI','CONCOMITA') PARA IN ('ACUMULA','TOTALIZA')
--Kellysson novo em 2/8/23 nova em sql_4_regras_extraclasse_p1_b4.sql --trocando de tabela
--Kellysson novo em 1/8/23 nova em sql_4_regras_extraclasse_b3.sql
--Kellysson novo em 31/7/23 ---nova abordagem apos ajustes na ultima semana
DECLARE
--vCONTADOR NUMBER;
vSALDO_REGENCIA_IGUAL_TURNO_DIA NUMBER;
vTRUE BOOLEAN := TRUE ;

BEGIN
dbms_output.enable(null);
--vCONTADOR :=0;
vSALDO_REGENCIA_IGUAL_TURNO_DIA := 0 ;

------------------------------------------------------------------------------------------------INICIO ----PRIMEIRA PARTE ---CONTROLE MESMO TURNO E DIA----------------------------------------------------------------------------------------------------------
FOR C1 IN (

--SELECT COUNT(1) FROM (--COUNT

SELECT
C.COORDENACAO_U, C. TIPO_JORNADA_U, M.GERA_EXTRACLASSE,
ROW_NUMBER () OVER (PARTITION BY M.CPF, M.DATA, M.INICIO_TURNO ORDER BY M.CPF, M.DATA, M.INICIO_TURNO, M.INICIO_REGENCIA)ORDEM_MESMO_CPF_DIA_TURNO,
TST.QTD_REG_MESMO_DIA_TURNO_TST, TST.SOMA_MINUTOS_REGENCIA_TST, 
TDT.QTD_REG_MESMO_DIA_TURNO_TDT, TDT.SOMA_MINUTOS_REGENCIA_TDT, 
M.CPF, TO_NUMBER(TO_CHAR(TO_DATE(M.DATA),'WW')) SEMANA_ANO, D.NRO_DIA_SEMANA, M.DATA, M.ID_HORARIO, M.INICIO_TURNO, M.INICIO_REGENCIA, M.FIM_REGENCIA,M.OBS_PROCESSAMENTO, 
--LAG(M.TOTAL_REGENCIA, 1, NULL) OVER(PARTITION BY M.CPF, M.DATA, M.INICIO_TURNO ORDER BY M.CPF, M.DATA, M.INICIO_TURNO, M.INICIO_REGENCIA) TOTAL_REGENCIA_ANTERIOR,
M.TOTAL_REGENCIA,   
--LEAD(M.TOTAL_REGENCIA, 1, NULL) OVER(PARTITION BY M.CPF, M.DATA, M.INICIO_TURNO ORDER BY M.CPF, M.DATA, M.INICIO_TURNO, M.INICIO_REGENCIA) PROXIMO_TOTAL_REGENCIA,
M.EXTRA_IGUAL_TURNO_E_DIA, M.EXTRA_IGUAL_TURNO_DIA_DIFERE, M.EXTRA_DIFERE_TURNO_DIA_IGUAL, M.EXTRA_DIFERE_TURNO_E_DIA
--, A.BM_U, A.TIPO_JORNADA_U, A.TURNO_U, A.HORA_INI_TURNO_U, A.DURACAO_AULA_U, A.CARGA_HORARIA, A.DATA_INICIO_U, A.DATA_FIM_U, A.DATA_CANCELAMENTO_U
FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS M 

LEFT OUTER JOIN 
    (SELECT CPF, DATA, INICIO_TURNO, SUM(TOTAL_REGENCIA) SOMA_MINUTOS_REGENCIA_TDT, COUNT(1)QTD_REG_MESMO_DIA_TURNO_TDT FROM
            (SELECT CPF, DATA, INICIO_TURNO, TOTAL_REGENCIA
             FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE)
             AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
             AND OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')) GROUP BY CPF, DATA, INICIO_TURNO 
             )TDT --------------------------------------TOTAL DIA E TURNO
    ON TDT.CPF = M.CPF AND TDT.DATA = M.DATA AND TDT.INICIO_TURNO = M.INICIO_TURNO

LEFT OUTER JOIN 
    (SELECT CPF, SEMANA_ANO, INICIO_TURNO, SUM(TOTAL_REGENCIA) SOMA_MINUTOS_REGENCIA_TST, COUNT(1)QTD_REG_MESMO_DIA_TURNO_TST FROM
            (SELECT CPF, TO_NUMBER(TO_CHAR(TO_DATE(DATA),'WW')) SEMANA_ANO, INICIO_TURNO, TOTAL_REGENCIA
             FROM PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE)
             AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
             AND OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')) GROUP BY CPF, SEMANA_ANO, INICIO_TURNO
             )TST -------------------------------------TOTAL SEMANA E TURNO
    ON TST.CPF = M.CPF AND TST.SEMANA_ANO = TO_NUMBER(TO_CHAR(TO_DATE(M.DATA),'WW')) AND TST.INICIO_TURNO = M.INICIO_TURNO

LEFT OUTER JOIN ARTERH.RHTABS_DATAS D ON TRUNC(D.DATA_DIA) = TRUNC(M.DATA)
/*
LEFT OUTER JOIN 
(SELECT * FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE))A ON A.ID_HORARIO = M.ID_HORARIO
*/
--INICIO ---NOVO EM 25/9/23
LEFT OUTER JOIN (
SELECT * FROM ( SELECT ROW_NUMBER() OVER (PARTITION BY ID_HORARIO ORDER BY ID_HORARIO, COORDENACAO_U)ORDEM_ID,
ID_HORARIO, COORDENACAO_U, TIPO_JORNADA_U, COUNT(1)QTD FROM PONTO_ELETRONICO.SUGESP_SGE_JORNADAS_AJUSTES WHERE TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
AND TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE)--NOVO EM 16/10/23
GROUP BY ID_HORARIO, COORDENACAO_U, TIPO_JORNADA_U ORDER BY COUNT(1)DESC, ID_HORARIO, COORDENACAO_U ) WHERE ORDEM_ID = 1
)C ON C.ID_HORARIO = M.ID_HORARIO
--FIM---NOVO EM 25/9/23


WHERE TRUNC(M.DATA_PROCESSAMENTO)= TRUNC(SYSDATE)
AND M.OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')
AND M.TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'

AND M.GERA_EXTRACLASSE = 'SIM'-- NOVO EM 4/10/23 --APENAS REGISTROS QUE PRECISAM DE EXTRACLASSE
--COMENTADO 3/10/23 --AND C.COORDENACAO_U = 'NÃO' --NOVO EM 25/9/23 --- PARA NAO ADICIONAR EXTRACLASSE PARA COORDENADORES

--AND M.CPF --= '65902084687' ---TESTES
--in ('65902084687','44395426620','05977311605','67548989687','03324512670','03268343627','03611128660','74393383672','02762267633','44773854634','06364973647','76755622672','56482396615','96067845687','88203255604','04224017652','91774802600','07865358652','84200626691','79280382691','85124133600','06401982608','02996366662','50666240663','03456317654','06090534692','78772010606','59375280691','07820101644','16083584884','02613598603','94361347620','02744482625','00821066650','09267702688','08756655606','01282420607','85883840604','40378365649','06054125613','11944452680','01542390621','01192300629','01041868367','56121784687','54177413615')
--IN ('05096889696','00064003612','88434974649','07465582601','03385076633')
ORDER BY M.CPF, M.DATA, M.INICIO_TURNO, M.INICIO_REGENCIA, M.ID_HORARIO

--)--count

--UPDATE PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS SET EXTRA_IGUAL_TURNO_E_DIA = NULL WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) AND EXTRA_IGUAL_TURNO_E_DIA IS NOT NULL; COMMIT;

)LOOP
--vCONTADOR := vCONTADOR +1;
--dbms_output.put_line('vCONTADOR: '||vCONTADOR||'-'||C1.CPF||'-'||C1.SEMANA_ANO||'-'||C1.NRO_DIA_SEMANA||'-'||C1.DATA||'-'||C1.INICIO_TURNO||'-'||C1.INICIO_REGENCIA||'-'||C1.FIM_REGENCIA||'-'||C1.TOTAL_REGENCIA||'-'||C1.ID_HORARIO||'-'||C1.TIPO_MARCACAO||'-'||C1.OBS_PROCESSAMENTO);

--INICIO---APENAS PARA SETAR OS SALDO DO MESMO DIA/TURNO
IF C1.ORDEM_MESMO_CPF_DIA_TURNO = 1 --AND C1.QTD_REG_MESMO_DIA_TURNO_TDT <> C1.ORDEM_MESMO_CPF_DIA_TURNO  --USANDO O PAR DE REGISTROS PARA TOMAR DECISAO NAO PRECISA DIFERENCIAR OS DEMAIS REGISTROS NO MESMO DIA/TURNO 
THEN
--dbms_output.put_line('PRIMEIRO_REGISTRO_MESMO_DIA_TURNO_SETA_VARIAVEIS');
vSALDO_REGENCIA_IGUAL_TURNO_DIA := 270-C1.SOMA_MINUTOS_REGENCIA_TDT ;
--vSALDO_EXTRA_IGUAL_TURNO_DIA := C1.SOMA_MINUTOS_EXTRA_DISPONIVEL_TDT ;
--dbms_output.put_line('vSALDO_REGENCIA_IGUAL_TURNO_DIA: '||vSALDO_REGENCIA_IGUAL_TURNO_DIA||' vSALDO_EXTRA_IGUAL_TURNO_DIA: '||vSALDO_EXTRA_IGUAL_TURNO_DIA);
END IF;
--FIM---APENAS PARA SETAR OS SALDO DO MESMO DIA/TURNO

--INICIO-------IF GERAL SALDO DO TURNO NO DIA --NOVO EM 1/8/23 AS 09H04------------------------------------------------------------ 
--TURNO ONDE HA HORAS EXTRACLASSES SUFICIENTES PARA COBRIR AS HORAS DE REGENCIA DO DIA/TURNO
IF vSALDO_REGENCIA_IGUAL_TURNO_DIA > 0 AND vSALDO_REGENCIA_IGUAL_TURNO_DIA >= C1.TOTAL_REGENCIA/2 THEN
UPDATE PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS SET EXTRA_IGUAL_TURNO_E_DIA = C1.TOTAL_REGENCIA/2 WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) --AND TIPO_MARCACAO = C1.TIPO_MARCACAO
AND CPF = C1.CPF AND DATA = C1.DATA AND INICIO_TURNO = C1.INICIO_TURNO AND INICIO_REGENCIA = C1.INICIO_REGENCIA AND ID_HORARIO = C1.ID_HORARIO
AND OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')--NOVO EM 4/9/23
AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
; COMMIT;
vSALDO_REGENCIA_IGUAL_TURNO_DIA := vSALDO_REGENCIA_IGUAL_TURNO_DIA - C1.TOTAL_REGENCIA/2;

ELSIF vSALDO_REGENCIA_IGUAL_TURNO_DIA > 0 AND vSALDO_REGENCIA_IGUAL_TURNO_DIA < C1.TOTAL_REGENCIA/2 THEN
UPDATE PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS SET EXTRA_IGUAL_TURNO_E_DIA = vSALDO_REGENCIA_IGUAL_TURNO_DIA WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) --AND TIPO_MARCACAO = C1.TIPO_MARCACAO
AND CPF = C1.CPF AND DATA = C1.DATA AND INICIO_TURNO = C1.INICIO_TURNO AND INICIO_REGENCIA = C1.INICIO_REGENCIA AND ID_HORARIO = C1.ID_HORARIO
AND OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')--NOVO EM 4/9/23
AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
; COMMIT;
vSALDO_REGENCIA_IGUAL_TURNO_DIA := vSALDO_REGENCIA_IGUAL_TURNO_DIA - vSALDO_REGENCIA_IGUAL_TURNO_DIA;

ELSE
UPDATE PONTO_ELETRONICO.SUGESP_SGE_PAR_REGE_ARQ_DATAS SET EXTRA_IGUAL_TURNO_E_DIA = 0 WHERE TRUNC(DATA_PROCESSAMENTO)= TRUNC(SYSDATE) --AND TIPO_MARCACAO = C1.TIPO_MARCACAO
AND CPF = C1.CPF AND DATA = C1.DATA AND INICIO_TURNO = C1.INICIO_TURNO AND INICIO_REGENCIA = C1.INICIO_REGENCIA AND ID_HORARIO = C1.ID_HORARIO
AND OBS_PROCESSAMENTO IN ('ACUMULA','TOTALIZA')--NOVO EM 4/9/23
AND TIPO_REGISTRO = 'DE/PARA_EXTENSOES_2023'
; COMMIT;

END IF;
--FIM-------IF GERAL SALDO DO TURNO NO DIA --NOVO EM 1/8/23 AS 09H04------------------------------------------------------------ 
--dbms_output.put_line('--------------------');
END LOOP;---FIM FOR C1
------------------------------------------------------------------------------------------------INICIO ----PRIMEIRA PARTE ---CONTROLE MESMO TURNO E DIA----------------------------------------------------------------------------------------------------------
END;

END;