
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG11_CAMPANHA_VACINACAO" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN

--Kellysson em 2/2/22 - v1  gravar SOBREAVISO Ifponto CAMPANHA DE VACINACAO script inicial baseado no (grava_3_tipos_sit_ponto_verba_SMSA_v5.2.2.sql)

------------------------------------------------------------TROCAR DATAS
--/*
DECLARE               
vCONTADOR NUMBER; 
vDT_INI_PERIODO DATE;
vDT_FIM_PERIODO DATE;
vTIPO_DIA_CALENDARIO VARCHAR2 (2);
vCARGO_PODE_VERBA VARCHAR2 (1);
vTOTAL_MARCACOES_DIA NUMBER;
vMARCACAO_ATUAL VARCHAR2 (20);
vCODIGOM_ATUAL VARCHAR2 (20);
vQTD_MARCACOES NUMBER;
vQTD_EVENTOS NUMBER;
vCODIGO_ME NUMBER;
vCODIGO_MS NUMBER;
vLOCAL_USAR VARCHAR2 (4);
vTIPO_DIA_PAGAR VARCHAR2 (2);
vCHAVE_SAV1 VARCHAR2(20);
vCHAVE_SAV1_PARCIAL VARCHAR2(20);
vLOCAIS_PODE_VERBA VARCHAR2 (1);
vNUMERO NUMBER  ;
vSTRING VARCHAR2(100 BYTE);

vDISTANCIA NUMBER;
vDISTANCIA_MAIS_PROXIMA NUMBER;
vLOCAL_MAIS_PROXIMO VARCHAR2(15);
vQUANT_LOCAIS_ENDERECO NUMBER;
vDADOS_LOCAL_MAIS_PROXIMO VARCHAR2(4000);
vTIPO_LOCAL_C3 VARCHAR2(30);
vCHAVE_SAV1_FINAL VARCHAR2(20);
vLOCAIS_PODE_VERBA_FINAL VARCHAR2 (1);
vLOG VARCHAR2(4000);
vLOG_MARCACOES VARCHAR2(4000);
vPODE_PAGAR_CHAVE_PARCIAL NUMBER;
vLOG_ERRO_REGRA_MARCACAO VARCHAR2(4000);
vLOG_ERRO_REGRA_CARGO VARCHAR2(4000);
vLOG_ERRO_REGRA_LOCAL_MARCA VARCHAR2(4000);
vORIGEM_MARCACAO VARCHAR2(35);
vPAGA_1_MARCACAO_VALIDA VARCHAR2(1);
vCHAVE_SAV1_LOTACAO VARCHAR2(20);
vCODIGO_ME_LOG VARCHAR2(4000);
vCODIGO_MS_LOG VARCHAR2(4000);
vQTD_LOCAIS_PODE_VERBA NUMBER;--EM 3/1/22

vCAMPO_3 VARCHAR2(400);--PREVIA_PROCESSO
vCAMPO_4 VARCHAR2(400);--RESULTADO_FINAL_PROCESSAMENTO
vCAMPO_5 VARCHAR2(400);--vQTD_LOCAIS_PODE_VERBA
vCAMPO_6 VARCHAR2(400);--ORIGEM_MARCACAO_ENTRADA
vCAMPO_7 VARCHAR2(400);--EFETIVADO_ENTRADA
vCAMPO_8 VARCHAR2(400);--ORIGEM_MARCACAO_SAIDA
vCAMPO_9 VARCHAR2(400);--EFETIVADO_SAIDA

v1_LOCAL_PBH_MARCACAO_ENTRADA VARCHAR2(1000);
v1_LOCAL_PBH_MARCACAO_SAIDA VARCHAR2(1000);

BEGIN
dbms_output.enable(null);
vDT_INI_PERIODO := TO_DATE(DATA_INICIO,'DD/MM/YY'); -------------ALTERAR DATAS
vDT_FIM_PERIODO := TO_DATE(DATA_FIM,'DD/MM/YY');-------------ALTERAR DATAS
vCONTADOR := 0;
vTIPO_DIA_CALENDARIO := NULL;
vCARGO_PODE_VERBA := NULL;
vTOTAL_MARCACOES_DIA :=0;
vMARCACAO_ATUAL := NULL;
vCODIGOM_ATUAL := NULL;
vQTD_MARCACOES :=0;
vQTD_EVENTOS :=0;
vCODIGO_ME :=0;
vCODIGO_MS :=0;
vLOCAL_USAR := NULL;
vTIPO_DIA_PAGAR := 'T1';
vCHAVE_SAV1 := NULL;
vCHAVE_SAV1_PARCIAL := NULL;
vLOCAIS_PODE_VERBA := NULL;
vNUMERO := 0;
vSTRING := NULL;

vDISTANCIA := 0;
vDISTANCIA_MAIS_PROXIMA := 0;
vLOCAL_MAIS_PROXIMO := NULL;
vQUANT_LOCAIS_ENDERECO := 0;
vDADOS_LOCAL_MAIS_PROXIMO := NULL;
vTIPO_LOCAL_C3 := NULL;
vCHAVE_SAV1_FINAL := NULL;
vLOCAIS_PODE_VERBA_FINAL := NULL;

vLOG := NULL;
vLOG_MARCACOES := NULL;
vPODE_PAGAR_CHAVE_PARCIAL := 0;
vLOG_ERRO_REGRA_MARCACAO := NULL;
vLOG_ERRO_REGRA_CARGO := NULL;
vLOG_ERRO_REGRA_LOCAL_MARCA := NULL;
vORIGEM_MARCACAO := NULL;
vPAGA_1_MARCACAO_VALIDA := NULL;
vCHAVE_SAV1_LOTACAO := NULL;
vCODIGO_ME_LOG := NULL;
vCODIGO_MS_LOG := NULL;
vQTD_LOCAIS_PODE_VERBA :=0;

vCAMPO_3 := NULL;--PREVIA_PROCESSO
vCAMPO_4 := NULL;--RESULTADO_FINAL_PROCESSAMENTO
vCAMPO_5 := NULL;--vQTD_LOCAIS_PODE_VERBA
vCAMPO_6 := NULL;--ORIGEM_MARCACAO_ENTRADA
vCAMPO_7 := NULL;--EFETIVADO_ENTRADA
vCAMPO_8 := NULL;--ORIGEM_MARCACAO_SAIDA
vCAMPO_9 := NULL;--EFETIVADO_SAIDA

v1_LOCAL_PBH_MARCACAO_ENTRADA := NULL;
v1_LOCAL_PBH_MARCACAO_SAIDA := NULL;

--CABECALHO DO LOG
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES)
VALUES(NULL,NULL,NULL, SYSDATE,'PRG11_CAMPANHA_VACINACAO',
--'CONTADOR|EMPRESA|TIPO_CONTRATO|CONTRATO|DATA|TIPO_SOBREAVISO|PREVISTO|REALIZADO|COD_CARGO_EFETIVO|CARGO_EFETIVO|TIPO_LOCAL_LOTACAO|COD_CG1|COD_CG2|COD_CG3|COD_CG4|COD_CG5|COD_CG6|LOCAL_LOTADO|vCHAVE_SAV1_PARCIAL|COD_MARCACAO_ENTRADA|COD_MARCACAO_SAIDA|PRIMEIRO_STATUS_PROCESSAMENTO|RESULTADO_FINAL_PROCESSAMENTO|LOG_ERRO_REGRAS_TABELA_SAV1|VAZIO|1_ORIGEM_MARCACAO|1_EFETIVADO|1_CHAVE_SAV1|2_ORIGEM_MARCACAO|2_EFETIVADO|2_CHAVE_SAV1|3_ORIGEM_MARCACAO|3_EFETIVADO|3_CHAVE_SAV1|4_ORIGEM_MARCACAO|4_EFETIVADO|4_CHAVE_SAV1|5_ORIGEM_MARCACAO|5_EFETIVADO|5_CHAVE_SAV1|6_ORIGEM_MARCACAO|6_EFETIVADO|6_CHAVE_SAV1|7_ORIGEM_MARCACAO|7_EFETIVADO|7_CHAVE_SAV1|8_ORIGEM_MARCACAO|8_EFETIVADO|8_CHAVE_SAV1|9_ORIGEM_MARCACAO|9_EFETIVADO|9_CHAVE_SAV1|10_ORIGEM_MARCACAO|10_EFETIVADO|10_CHAVE_SAV1|11_ORIGEM_MARCACAO|11_EFETIVADO|11_CHAVE_SAV1|12_ORIGEM_MARCACAO|12_EFETIVADO|12_CHAVE_SAV1|13_ORIGEM_MARCACAO|13_EFETIVADO|13_CHAVE_SAV1|14_ORIGEM_MARCACAO|14_EFETIVADO|14_CHAVE_SAV1|15_ORIGEM_MARCACAO|15_EFETIVADO|15_CHAVE_SAV1|16_ORIGEM_MARCACAO|16_EFETIVADO|16_CHAVE_SAV1|17_ORIGEM_MARCACAO|17_EFETIVADO|17_CHAVE_SAV1|18_ORIGEM_MARCACAO|18_EFETIVADO|18_CHAVE_SAV1|19_ORIGEM_MARCACAO|19_EFETIVADO|19_CHAVE_SAV1|20_ORIGEM_MARCACAO|20_EFETIVADO|20_CHAVE_SAV1'
--'CONTADOR|EMPRESA|TIPO_CONTRATO|CONTRATO|NOME|DATA|TIPO_SOBREAVISO|PREVISTO|REALIZADO|COD_CARGO_EFETIVO|CARGO_EFETIVO|TIPO_LOCAL_LOTACAO|COD_CG1|COD_CG2|COD_CG3|COD_CG4|COD_CG5|COD_CG6|LOCAL_LOTADO|vCHAVE_SAV1_PARCIAL|PRIMEIRO_STATUS_PROCESSAMENTO|RESULTADO_FINAL_PROCESSAMENTO|ORIGEM_MARCACAO_ENTRADA|EFETIVADO_ENTRADA|DADOS_MARCACAO_ENTRADA|ORIGEM_MARCACAO_SAIDA|EFETIVADO_SAIDA|DADOS_MARCACAO_SAIDA'
'CONTADOR|EMPRESA|TIPO_CONTRATO|CONTRATO|NOME|DATA|TIPO_SOBREAVISO|PREVISTO|REALIZADO|COD_CARGO_EFETIVO|CARGO_EFETIVO|TIPO_LOCAL_LOTACAO|COD_CG1|COD_CG2|COD_CG3|COD_CG4|COD_CG5|COD_CG6|LOCAL_LOTADO|vCHAVE_SAV1_PARCIAL|PREVIA_PROCESSO|vCHAVE_SAV1_FINAL|RESULTADO_FINAL_PROCESSAMENTO|MARCACAO_ENTRADA|ORIGEM_MARCACAO_ENTRADA|EFETIVADO_ENTRADA|DADOS_MARCACAO_ENTRADA|MARCACAO_SAIDA|ORIGEM_MARCACAO_SAIDA|EFETIVADO_SAIDA|DADOS_MARCACAO_SAIDA|vQTD_LOCAIS_PODE_VERBA|v1_LOCAL_PBH_MARCACAO_ENTRADA|v1_LOCAL_PBH_MARCACAO_SAIDA'
);COMMIT;

--inicio-------------------------------------------------- FOR C1 PARA PEGAR OS DIAS DE ESPELHO QUE TIVERAM SOBREAVISO EXECUTADO
FOR C1 IN(



--*/
SELECT 
CASE
WHEN  X3.VIRA_DIA = 'SIM' AND X3.TIPO_DIA_CALENDARIO = 'T1' AND	X3.TIPO_DIA_CALENDARIO_DIA_SEGUI = 'T2' THEN 'T2' 
ELSE X3.TIPO_DIA_CALENDARIO
END TIPO_DIA_USAR,
X3.* FROM(
SELECT
CASE 
WHEN X2.DESCRICAO_MES = 'JANEIRO' THEN CASE WHEN SUBSTR(C.JANEIRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'FEVEREIRO' THEN CASE WHEN SUBSTR(C.FEVEREIRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'MARCO' THEN CASE WHEN SUBSTR(C.MARCO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'ABRIL' THEN CASE WHEN SUBSTR(C.ABRIL, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'MAIO' THEN CASE WHEN SUBSTR(C.MAIO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'JUNHO' THEN CASE WHEN SUBSTR(C.JUNHO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'JULHO' THEN CASE WHEN SUBSTR(C.JULHO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'AGOSTO' THEN CASE WHEN SUBSTR(C.AGOSTO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'SETEMBRO' THEN CASE WHEN SUBSTR(C.SETEMBRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'OUTUBRO' THEN CASE WHEN SUBSTR(C.OUTUBRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'NOVEMBRO' THEN CASE WHEN SUBSTR(C.NOVEMBRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES = 'DEZEMBRO' THEN CASE WHEN SUBSTR(C.DEZEMBRO, X2.NUMERO_DIA,1) IN ('F','O') OR X2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
END TIPO_DIA_CALENDARIO,
CASE 
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'JANEIRO' THEN CASE WHEN SUBSTR(CD.JANEIRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'FEVEREIRO' THEN CASE WHEN SUBSTR(CD.FEVEREIRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'MARCO' THEN CASE WHEN SUBSTR(CD.MARCO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'ABRIL' THEN CASE WHEN SUBSTR(CD.ABRIL, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'MAIO' THEN CASE WHEN SUBSTR(CD.MAIO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'JUNHO' THEN CASE WHEN SUBSTR(CD.JUNHO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'JULHO' THEN CASE WHEN SUBSTR(CD.JULHO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'AGOSTO' THEN CASE WHEN SUBSTR(CD.AGOSTO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'SETEMBRO' THEN CASE WHEN SUBSTR(CD.SETEMBRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'OUTUBRO' THEN CASE WHEN SUBSTR(CD.OUTUBRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'NOVEMBRO' THEN CASE WHEN SUBSTR(CD.NOVEMBRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN X2.DESCRICAO_MES_DIA_SEGUINTE = 'DEZEMBRO' THEN CASE WHEN SUBSTR(CD.DEZEMBRO, X2.NUMERO_DIA_SEGUINTE,1) IN ('F','O') OR X2.DIA_SEMANA_DIA_SEGUINTE IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
END 
TIPO_DIA_CALENDARIO_DIA_SEGUI,
X2.*
FROM(
SELECT 
CASE 
WHEN DD.NRO_DIA_SEMANA = 1 THEN 'DOM' WHEN DD.NRO_DIA_SEMANA = 2 THEN 'SEG' WHEN DD.NRO_DIA_SEMANA = 3 THEN 'TER' WHEN DD.NRO_DIA_SEMANA = 4 THEN 'QUA' WHEN DD.NRO_DIA_SEMANA = 5 
THEN 'QUI' WHEN DD.NRO_DIA_SEMANA = 6 THEN 'SEX' WHEN DD.NRO_DIA_SEMANA = 7 THEN 'SAB' ELSE 'ERRO'END DIA_SEMANA_DIA_SEGUINTE, 
CASE 
WHEN D.NRO_DIA_SEMANA = 1 THEN 'DOM' WHEN D.NRO_DIA_SEMANA = 2 THEN 'SEG' WHEN D.NRO_DIA_SEMANA = 3 THEN 'TER' WHEN D.NRO_DIA_SEMANA = 4 THEN 'QUA' WHEN D.NRO_DIA_SEMANA = 5 
THEN 'QUI' WHEN D.NRO_DIA_SEMANA = 6 THEN 'SEX' WHEN D.NRO_DIA_SEMANA = 7 THEN 'SAB' ELSE 'ERRO'END DIA_SEMANA, 
EXTRACT(DAY FROM X.DATA)NUMERO_DIA, 
EXTRACT(MONTH FROM X.DATA)NUMERO_MES, 
CASE
WHEN EXTRACT(MONTH FROM X.DATA) = 1  THEN 'JANEIRO'
WHEN EXTRACT(MONTH FROM X.DATA) = 2  THEN 'FEVEREIRO'
WHEN EXTRACT(MONTH FROM X.DATA) = 3  THEN 'MARCO'
WHEN EXTRACT(MONTH FROM X.DATA) = 4  THEN 'ABRIL'
WHEN EXTRACT(MONTH FROM X.DATA) = 5  THEN 'MAIO'
WHEN EXTRACT(MONTH FROM X.DATA) = 6  THEN 'JUNHO'
WHEN EXTRACT(MONTH FROM X.DATA) = 7  THEN 'JULHO'
WHEN EXTRACT(MONTH FROM X.DATA) = 8  THEN 'AGOSTO'
WHEN EXTRACT(MONTH FROM X.DATA) = 9  THEN 'SETEMBRO'
WHEN EXTRACT(MONTH FROM X.DATA) = 10 THEN 'OUTUBRO'
WHEN EXTRACT(MONTH FROM X.DATA) = 11 THEN 'NOVEMBRO'
WHEN EXTRACT(MONTH FROM X.DATA) = 12 THEN 'DEZEMBRO'
END DESCRICAO_MES,
EXTRACT(YEAR FROM X.DATA)NUMERO_ANO, 
EXTRACT(DAY FROM TRUNC(X.DATA)+1) NUMERO_DIA_SEGUINTE, 
EXTRACT(MONTH FROM TRUNC(X.DATA)+1) NUMERO_MES_DIA_SEGUINTE, 
CASE
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 1  THEN 'JANEIRO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 2  THEN 'FEVEREIRO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 3  THEN 'MARCO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 4  THEN 'ABRIL'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 5  THEN 'MAIO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 6  THEN 'JUNHO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 7  THEN 'JULHO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 8  THEN 'AGOSTO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 9  THEN 'SETEMBRO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 10 THEN 'OUTUBRO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 11 THEN 'NOVEMBRO'
WHEN EXTRACT(MONTH FROM TRUNC(X.DATA)+1) = 12 THEN 'DEZEMBRO'
END DESCRICAO_MES_DIA_SEGUINTE,
EXTRACT(YEAR FROM TRUNC(X.DATA)+1) NUMERO_ANO_DIA_SEGUINTE, 
M1.CODIGO CODIGO_M1, M2.CODIGO CODIGO_M2, M3.CODIGO CODIGO_M3, M4.CODIGO CODIGO_M4, M5.CODIGO CODIGO_M5, M6.CODIGO CODIGO_M6, M7.CODIGO CODIGO_M7, M8.CODIGO CODIGO_M8, M9.CODIGO CODIGO_M9, M10.CODIGO CODIGO_M10, M11.CODIGO CODIGO_M11, M12.CODIGO CODIGO_M12,
X.*
--,M1.*, M2.*, M3.*, M4.*, M5.*, M6.*, M7.*, M8.*, M9.*, M10.*, M11.*, M12.*
FROM(
SELECT 
LPAD(E.EMPRESA,4,0) EMPRESA, E.TIPO_CONTRATO, LPAD(E.MATRICULA,15,0) MATRICULA,b.cod_cargo_efetivo, ce.descricao cargo_efetivo,
CASE WHEN GN.c_livre_selec10 = '1' THEN 'APS'
WHEN GN.c_livre_selec10 = '2' THEN 'COM'
WHEN GN.c_livre_selec10 = '3' THEN 'UPA'
WHEN GN.c_livre_selec10 = '4' THEN 'SUP'
WHEN GN.c_livre_selec10 = '5' THEN 'CER'
ELSE 'ERRO'
END TIPO_LOCAL_LOTACAO
--, M.CODIGO COD_MARCACAO, M.DTEVENTO MARCACAO, M.EFETIVADO, M.IP, M.LATITUDE, M.LONGITUDE
,E.DATA, E.SITUACAO, E.ACEITO, E.COD_JUSTIFICATIVA_PONTO, 
A.TIPO, A.DTINICIO, A.DTFIM, A.HRINICIO, A.HRFIM, A.OBS,
E.TIPO_SOBREAVISO, 
CASE WHEN E.TIPO_SOBREAVISO = 'Plantão Extra'	THEN 'PEX' WHEN E.TIPO_SOBREAVISO = 'Plantão Extra SUP' THEN 'PSU' WHEN E.TIPO_SOBREAVISO ='Abono CERSAM' THEN'ACE' END COD_TIPO_SOBREAVISO,
E.HRINICIO_SOBREAVISO,
CASE WHEN TO_NUMBER(SUBSTR(E.HRINICIO_SOBREAVISO,1,2))>12 THEN 'SIM' ELSE 'NAO' END VIRA_DIA,
E.HRFIM_SOBREAVISO, E.PREVISTO_SOBREAVISO, E.EXECUTADO_SOBREAVISO
,B.NOME,b.cod_cargo_comiss, B.codigo_funcao, GN.c_livre_selec10 TIPO_LOCAL_SMSA, GN.COD_CGERENC1, GN.COD_CGERENC2, GN.COD_CGERENC3, GN.COD_CGERENC4, GN.COD_CGERENC5, GN.COD_CGERENC6, GN.DESCRICAO LOCAL
,E.AGRUPADOR
--, E.MARCACAO1, E.MARCACAO2, E.MARCACAO3, E.MARCACAO4, E.MARCACAO5, E.MARCACAO6, E.MARCACAO7, E.MARCACAO8, E.MARCACAO9, E.MARCACAO10, E.MARCACAO11, E.MARCACAO12
--, E.MARCACAO1_ALTERADA, E.MARCACAO2_ALTERADA, E.MARCACAO3_ALTERADA, E.MARCACAO4_ALTERADA, E.MARCACAO5_ALTERADA, E.MARCACAO6_ALTERADA, E.MARCACAO7_ALTERADA, E.MARCACAO8_ALTERADA, E.MARCACAO9_ALTERADA, E.MARCACAO10_ALTERADA, E.MARCACAO11_ALTERADA, E.MARCACAO12_ALTERADA
,CASE WHEN E.MARCACAO1_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO1_ALTERADA ELSE E.MARCACAO1 END MARCACAO_USAR1
,CASE WHEN E.MARCACAO2_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO2_ALTERADA ELSE E.MARCACAO2 END MARCACAO_USAR2
,CASE WHEN E.MARCACAO3_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO3_ALTERADA ELSE E.MARCACAO3 END MARCACAO_USAR3
,CASE WHEN E.MARCACAO4_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO4_ALTERADA ELSE E.MARCACAO4 END MARCACAO_USAR4
,CASE WHEN E.MARCACAO5_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO5_ALTERADA ELSE E.MARCACAO5 END MARCACAO_USAR5
,CASE WHEN E.MARCACAO6_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO6_ALTERADA ELSE E.MARCACAO6 END MARCACAO_USAR6
,CASE WHEN E.MARCACAO7_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO7_ALTERADA ELSE E.MARCACAO7 END MARCACAO_USAR7
,CASE WHEN E.MARCACAO8_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO8_ALTERADA ELSE E.MARCACAO8 END MARCACAO_USAR8
,CASE WHEN E.MARCACAO9_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO9_ALTERADA ELSE E.MARCACAO9 END MARCACAO_USAR9
,CASE WHEN E.MARCACAO10_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO10_ALTERADA ELSE E.MARCACAO10 END MARCACAO_USAR10
,CASE WHEN E.MARCACAO11_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO11_ALTERADA ELSE E.MARCACAO11 END MARCACAO_USAR11
,CASE WHEN E.MARCACAO12_ALTERADA IS NOT NULL AND E.ACEITO = 'ABONADO' THEN E.MARCACAO12_ALTERADA ELSE E.MARCACAO12 END MARCACAO_USAR12
--MI.EMPRESA EMPRES, MI.TIPO_CONTRATO TIPO_CONTR, MI.MATRICULA BM, MI.COD_PESSOA, MI.CODIGO, MI.DTEVENTO,  MI.OCORRENCIA OCORRENC, MI.EFETIVADO, MI.IP, MI.LATITUDE, MI.LONGITUDE, MI.DATA_PROCESSAMENTO
--,M.CODIGO_EMPRESA, M.TIPO_CONTRATO, M.CODIGO_CONTRATO, M.DATA, M.HORA, M.OCORRENCIA, M.ENQUADRA_HORARIO FEITO_NO_LOCAL_TRABALHO, M.NUM_SERIAL_REP
FROM 
PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA E
LEFT OUTER JOIN PONTO_ELETRONICO.AUTORIZACAO_EXTRA_PESSOA A ON A.COD_PESSOA = E.COD_PESSOA AND TRUNC(E.DATA) BETWEEN TRUNC(A.DTINICIO) AND TRUNC(A.DTFIM)
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B ON LPAD(E.EMPRESA,4,0) = B.CODIGO_EMPRESA AND E.TIPO_CONTRATO = B.TIPO_CONTRATO AND LPAD(E.MATRICULA,15,0) = B.CODIGO

--COMENTADO EM 9/11/21--LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON B.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND B.COD_CUSTO_GERENC1 = GN.cod_cgerenc1 AND B.COD_CUSTO_GERENC2 = GN.cod_cgerenc2 AND B.COD_CUSTO_GERENC3 = GN.cod_cgerenc3
--COMENTADO EM 9/11/21--AND B.COD_CUSTO_GERENC4 = GN.cod_cgerenc4 AND B.COD_CUSTO_GERENC5 = GN.cod_cgerenc5 AND B.COD_CUSTO_GERENC6 = GN.cod_cgerenc6
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON LPAD(SUBSTR(E.AGRUPADOR,1,2),4,0) = GN.CODIGO_EMPRESA AND SUBSTR(E.AGRUPADOR,4,6) = GN.cod_cgerenc1 AND SUBSTR(E.AGRUPADOR,11,6) = GN.cod_cgerenc2 AND SUBSTR(E.AGRUPADOR,18,6) = GN.cod_cgerenc3--novo em 9/11/21
AND SUBSTR(E.AGRUPADOR,25,6) = GN.cod_cgerenc4 AND SUBSTR(E.AGRUPADOR,32,6) = GN.cod_cgerenc5 AND SUBSTR(E.AGRUPADOR,39,6) = GN.cod_cgerenc6 --novo em 9/11/21

left outer join RHPLCS_CARGO C ON c.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND c.CODIGO = b.cod_cargo_comiss
left outer join RHPLCS_CARGO CE ON Ce.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND Ce.CODIGO = b.cod_cargo_efetivo
WHERE 
B.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO AND AUX.CODIGO = B.CODIGO) 
AND
E.DATA_PROCESSAMENTO IS NULL 
AND TRUNC(E.DATA) BETWEEN TO_DATE(vDT_INI_PERIODO,'DD/MM/YYYY')AND TO_DATE(vDT_FIM_PERIODO,'DD/MM/YYYY')   ------------------------------trocar datas

--para testes comentar-- 
AND E.EXECUTADO_SOBREAVISO is not null AND E.EXECUTADO_SOBREAVISO > 0

AND B.VINCULO <> '0009'--NOVO EM 9/11/21--PARA TIRAR OS ESTAGIARIOS

--AND E.MATRICULA LIKE '%883291%'--'%33747%'--TESTE
ORDER BY E.EMPRESA, E.TIPO_CONTRATO, E.MATRICULA, E.DATA
)X
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M1  ON LPAD(M1.EMPRESA,4,0) = X.EMPRESA AND M1.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M1.MATRICULA,15,0) = X.MATRICULA AND to_char(M1.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR1,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M2  ON LPAD(M2.EMPRESA,4,0) = X.EMPRESA AND M2.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M2.MATRICULA,15,0) = X.MATRICULA AND to_char(M2.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR2,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M3  ON LPAD(M3.EMPRESA,4,0) = X.EMPRESA AND M3.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M3.MATRICULA,15,0) = X.MATRICULA AND to_char(M3.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR3,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M4  ON LPAD(M4.EMPRESA,4,0) = X.EMPRESA AND M4.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M4.MATRICULA,15,0) = X.MATRICULA AND to_char(M4.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR4,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M5  ON LPAD(M5.EMPRESA,4,0) = X.EMPRESA AND M5.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M5.MATRICULA,15,0) = X.MATRICULA AND to_char(M5.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR5,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M6  ON LPAD(M6.EMPRESA,4,0) = X.EMPRESA AND M6.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M6.MATRICULA,15,0) = X.MATRICULA AND to_char(M6.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR6,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M7  ON LPAD(M7.EMPRESA,4,0) = X.EMPRESA AND M7.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M7.MATRICULA,15,0) = X.MATRICULA AND to_char(M7.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR7,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M8  ON LPAD(M8.EMPRESA,4,0) = X.EMPRESA AND M8.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M8.MATRICULA,15,0) = X.MATRICULA AND to_char(M8.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR8,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M9  ON LPAD(M9.EMPRESA,4,0) = X.EMPRESA AND M9.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M9.MATRICULA,15,0) = X.MATRICULA AND to_char(M9.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR9,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M10 ON LPAD(M10.EMPRESA,4,0) = X.EMPRESA AND M10.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M10.MATRICULA,15,0) = X.MATRICULA AND to_char(M10.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR10,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M11 ON LPAD(M11.EMPRESA,4,0) = X.EMPRESA AND M11.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M11.MATRICULA,15,0) = X.MATRICULA AND to_char(M11.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR11,'DD/MM/YYYY HH24:MI:SS')
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_MARCACOES M12 ON LPAD(M12.EMPRESA,4,0) = X.EMPRESA AND M12.TIPO_CONTRATO = X.TIPO_CONTRATO AND LPAD(M12.MATRICULA,15,0) = X.MATRICULA AND to_char(M12.DTEVENTO,'DD/MM/YYYY HH24:MI:SS') = to_char(X.MARCACAO_USAR12,'DD/MM/YYYY HH24:MI:SS')

LEFT OUTER JOIN ARTERH.RHTABS_DATAS D ON TRUNC(D.DATA_DIA) = TRUNC(X.DATA)
LEFT OUTER JOIN ARTERH.RHTABS_DATAS DD ON TRUNC(DD.DATA_DIA) = TRUNC(X.DATA)+1
)X2
 ------------------calendario especifico da SMSA no Arterh NOVO PARA FERIADO E PONTOS FACULTATIVOS
LEFT OUTER JOIN (SELECT * FROM ARTERH.RHPARM_CALENDARIO WHERE CODIGO = '0004')C ON TRUNC(C.ANO_REFERENCIA) = TO_DATE('01/01/'||X2.NUMERO_ANO,'DD/MM/YYYY') 
LEFT OUTER JOIN (SELECT * FROM ARTERH.RHPARM_CALENDARIO WHERE CODIGO = '0004')CD ON TRUNC(CD.ANO_REFERENCIA) = TO_DATE('01/01/'||X2.NUMERO_ANO_DIA_SEGUINTE,'DD/MM/YYYY') 

)X3
WHERE X3.TIPO_SOBREAVISO IN ('Campanha vacinação')-- NOVO EM 25/11/21 PARA NÃO PEGAR O ABONO CAMPANHA DE VACINACAO

--AND X3.MATRICULA NOT IN ('000000000240552')--testes
ORDER BY X3.EMPRESA, X3.TIPO_CONTRATO, X3.MATRICULA, X3.DATA



--/*
)

LOOP
--comentado em 2/2/22 usar a linha de baixo--vNUMERO := ROUND(C1.EXECUTADO_SOBREAVISO) ; --para arredondar os 15 minutos de tolerancia para o valor ser sempre 12 ou 24 horas
vNUMERO := ROUND(C1.EXECUTADO_SOBREAVISO,2) ; --em 2/2/22 atendendo ao email (Fwd: Customização: Plantões extra) agora aceita valores de 11h30 a 12h
vSTRING := CASE WHEN INSTR(vNUMERO,',',1,1) = 0 THEN TO_CHAR(vNUMERO) WHEN INSTR(vNUMERO,',',1,1) <> 0 THEN TO_CHAR(SUBSTR(vNUMERO,1,INSTR(vNUMERO,',',1,1)-1) ||'.'||SUBSTR(vNUMERO,INSTR(vNUMERO,',' ,1,1)+1, LENGTH(vNUMERO))) end ;




vCONTADOR :=vCONTADOR+1;
dbms_output.put_line(' ');
dbms_output.put_line('--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////INICIO DE UM REGISTRO//////////////////////////////////////////////////////////////////////////////////////');
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' EMPRESA: '||C1.EMPRESA|| ' TIPO_CONTRATO: '|| C1.TIPO_CONTRATO|| ' MATRICULA: '||C1.MATRICULA || ' DATA: '|| TRUNC(C1.DATA) || ' TIPO_SOBREAVISO: '||C1.TIPO_SOBREAVISO||' PREVISTO: '||C1.PREVISTO_SOBREAVISO ||' EXECUTADO: '||C1.EXECUTADO_SOBREAVISO);
dbms_output.put_line('--COD_CARGO_EFETIVO: '||C1.COD_CARGO_EFETIVO||' CARGO_EFETIVO: '||C1.CARGO_EFETIVO);
dbms_output.put_line('--TIPO_LOCAL_LOTACAO:'||C1.TIPO_LOCAL_LOTACAO||' LOCAL_LOTACAO: '||C1.COD_CGERENC1||'.'||C1.COD_CGERENC2||'.'|| C1.COD_CGERENC3||'.'|| C1.COD_CGERENC4||'.'||C1.COD_CGERENC5||'.'|| C1.COD_CGERENC6||'-'|| C1.LOCAL);
dbms_output.put_line('--vCHAVE_SAV1: '||vCHAVE_SAV1|| ' vCHAVE_SAV1_PARCIAL: '||vCHAVE_SAV1_PARCIAL);

vLOG := vLOG||vCONTADOR||'|'||C1.EMPRESA||'|'||C1.TIPO_CONTRATO||'|'||C1.MATRICULA||'|'||C1.NOME||'|'||TRUNC(C1.DATA)||'|'||C1.TIPO_SOBREAVISO||'|'||C1.PREVISTO_SOBREAVISO||'|'||C1.EXECUTADO_SOBREAVISO||'|'||C1.COD_CARGO_EFETIVO||'|'||C1.CARGO_EFETIVO||'|'||C1.TIPO_LOCAL_LOTACAO||'|'||C1.COD_CGERENC1||'|'||C1.COD_CGERENC2||'|'||C1.COD_CGERENC3||'|'||C1.COD_CGERENC4||'|'||C1.COD_CGERENC5||'|'||C1.COD_CGERENC6||'|'||C1.LOCAL||'|'||vCHAVE_SAV1_PARCIAL;





--------------------------------------------------------------------------------------VERIFICAR SE CARGO TEM DIREITO A VERBA
SELECT
CASE WHEN X.QUANT = 0 THEN 'N' ELSE 'S' END
INTO
vCARGO_PODE_VERBA
FROM
(SELECT COUNT(1)QUANT FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'SAV4' AND DADO_DESTINO = 'CAMPANHAVACINACAOCARGO' AND SUBSTR(DADO_ORIGEM,1,15) = C1.COD_CARGO_EFETIVO)X;


IF vCARGO_PODE_VERBA = 'N' THEN
vLOG_ERRO_REGRA_CARGO  := 'CARGO NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO E' ;
vCAMPO_4 := 'CARGO NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO E' ;
END IF;
dbms_output.put_line('--vCARGO_PODE_VERBA: '||vCARGO_PODE_VERBA);
















---------------------------------------------------------------------------CONTAR AS MARCACOES DO DIA
/*IF C1.MARCACAO_USAR12 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 12 ;
ELSIF C1.MARCACAO_USAR11 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 11 ;
ELSIF C1.MARCACAO_USAR10 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 10 ;
ELSIF C1.MARCACAO_USAR9 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 9 ;
ELSIF C1.MARCACAO_USAR8 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 8 ;
ELSIF C1.MARCACAO_USAR7 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 7 ;
ELSIF C1.MARCACAO_USAR6 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 6 ;
ELSIF C1.MARCACAO_USAR5 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 5 ;
ELS*/IF C1.MARCACAO_USAR4 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 4 ;
ELSIF C1.MARCACAO_USAR3 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 3 ;
ELSIF C1.MARCACAO_USAR2 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 2 ;
ELSIF C1.MARCACAO_USAR1 IS NOT NULL THEN
vTOTAL_MARCACOES_DIA := 1 ;
ELSE vTOTAL_MARCACOES_DIA := 0 ;
END IF;
dbms_output.put_line('--vTOTAL_MARCACOES_DIA: '||vTOTAL_MARCACOES_DIA);


------------------------------------------------------PEGAR CODIGO DA MARCACAO SE HOUVER NO IFPONTO

-----------------------------QUANTIDADE DE EVENTOS
/*--INICIO--COMENTADO 4/1/22
IF C1.CODIGO_M4 IS NOT NULL THEN
vQTD_EVENTOS :=4;
ELSIF C1.CODIGO_M3 IS NOT NULL THEN
vQTD_EVENTOS :=3;
ELSIF C1.CODIGO_M2 IS NOT NULL THEN
vQTD_EVENTOS :=2;
ELSIF C1.CODIGO_M1 IS NOT NULL THEN
vQTD_EVENTOS :=1;
ELSE vQTD_EVENTOS :=0;
END IF;
*/--FIM--COMENTADO 4/1/22
--INICIO--NOVO 4/1/22
IF    C1.CODIGO_M4 IS NOT NULL AND C1.CODIGO_M3 IS NOT NULL AND C1.CODIGO_M2 IS NOT NULL AND C1.CODIGO_M1 IS NOT NULL THEN
vQTD_EVENTOS :=4;
ELSIF C1.CODIGO_M4 IS     NULL AND C1.CODIGO_M3 IS NOT NULL AND C1.CODIGO_M2 IS NOT NULL AND C1.CODIGO_M1 IS NOT NULL THEN
vQTD_EVENTOS :=3;
ELSIF C1.CODIGO_M4 IS     NULL AND C1.CODIGO_M3 IS     NULL AND C1.CODIGO_M2 IS NOT NULL AND C1.CODIGO_M1 IS NOT NULL THEN
vQTD_EVENTOS :=2;
ELSIF C1.CODIGO_M4 IS     NULL AND C1.CODIGO_M3 IS     NULL AND C1.CODIGO_M2 IS     NULL AND C1.CODIGO_M1 IS NOT NULL THEN
vQTD_EVENTOS :=1;
ELSE vQTD_EVENTOS :=0;
END IF;
--FIM--NOVO 4/1/22
dbms_output.put_line('--vQTD_EVENTOS: '||vQTD_EVENTOS);


--INICIO--NOVO EM 19/11/21 --DEFINIR MELHOR QUAIS MARCACOES USAR
IF vQTD_EVENTOS <> 0 AND C1.VIRA_DIA = 'NAO' THEN
vCODIGO_ME := C1.CODIGO_M1;
vCODIGO_MS := C1.CODIGO_M2;
ELSIF vQTD_EVENTOS <> 0 AND C1.VIRA_DIA = 'SIM' AND vTOTAL_MARCACOES_DIA <= 3 THEN
vCODIGO_ME := C1.CODIGO_M1;
vCODIGO_MS := C1.CODIGO_M2;
ELSIF vQTD_EVENTOS <> 0 AND C1.VIRA_DIA = 'SIM' AND vTOTAL_MARCACOES_DIA > 3 THEN
vCODIGO_ME := C1.CODIGO_M3;
vCODIGO_MS := C1.CODIGO_M4;
END IF;
dbms_output.put_line('--MARCACAO DE ENTRADA(vCODIGO_ME):'||vCODIGO_ME ||' MARCACAO DE SAIDA(vCODIGO_MS):'||vCODIGO_MS);
--vLOG := vLOG||'|'||vCODIGO_ME||'|'||vCODIGO_MS;



--novo local vLOG_MARCACOES EM 9/12/21
IF vCODIGO_ME IS NOT NULL AND vCODIGO_ME <> '0' THEN
SELECT 
CODIGO||'|'|| CASE WHEN E_ORIGEM IS NULL AND LATITUDE IS NULL THEN 'RELOGIO_PONTO' WHEN E_ORIGEM IS NULL AND LATITUDE IS NOT NULL THEN 'COMPUTADOR' ELSE E_ORIGEM END --ORIGEM_MARCACAO
||'|'|| EFETIVADO||'|'|| ENDERECO||' BAIRRO: '||BAIRRO||' CEP: '||CEP-- AS ENDERECO
,CASE WHEN E_ORIGEM IS NULL AND LATITUDE IS NULL THEN 'RELOGIO_PONTO' WHEN E_ORIGEM IS NULL AND LATITUDE IS NOT NULL THEN 'COMPUTADOR' ELSE E_ORIGEM END --ORIGEM_MARCACAO
,EFETIVADO
INTO vCODIGO_ME_LOG, vCAMPO_6, vCAMPO_7 
FROM PONTO_ELETRONICO.IFPONTO_MARCACOES  WHERE CODIGO = vCODIGO_ME; -- IN (27453201,27454786);
dbms_output.put_line('--vCODIGO_ME_LOG: '||vCODIGO_ME_LOG);
END IF;

IF vCODIGO_MS IS NOT NULL AND vCODIGO_MS <> 0 THEN
SELECT 
CODIGO||'|'|| CASE WHEN E_ORIGEM IS NULL AND LATITUDE IS NULL THEN 'RELOGIO_PONTO' WHEN E_ORIGEM IS NULL AND LATITUDE IS NOT NULL THEN 'COMPUTADOR' ELSE E_ORIGEM END --ORIGEM_MARCACAO
||'|'|| EFETIVADO||'|'|| ENDERECO||' BAIRRO: '||BAIRRO||' CEP: '||CEP-- AS ENDERECO
,CASE WHEN E_ORIGEM IS NULL AND LATITUDE IS NULL THEN 'RELOGIO_PONTO' WHEN E_ORIGEM IS NULL AND LATITUDE IS NOT NULL THEN 'COMPUTADOR' ELSE E_ORIGEM END --ORIGEM_MARCACAO
,EFETIVADO
INTO vCODIGO_MS_LOG, vCAMPO_8, vCAMPO_9
FROM PONTO_ELETRONICO.IFPONTO_MARCACOES  WHERE CODIGO = vCODIGO_MS; 
dbms_output.put_line('--vCODIGO_MS_LOG: '||vCODIGO_MS_LOG);
END IF;


--FIM--NOVO EM 19/11/21 --DEFINIR MELHOR QUAIS MARCACOES USAR


--INICIO--------------------------------------IF GERAL IMPORTANTE PARA FAZER A GRAVACAO DA SIT PONTO DA VERBA OU ABORTAR-----************************************************************************************************************

--TIRADO DESTE LOCAL EM 17/11/21--IF vQTD_EVENTOS <> vTOTAL_MARCACOES_DIA THEN
--dbms_output.put_line('--****ATENCAO MARCACOES NAO FORAM FEITAS VIA APP, PC OU RELOGIO, NAO PODE SER PAGO A VERBA OU VERIFICAR COM A SMSA');
--vLOG := vLOG||'|'||'--****ATENCAO MARCACOES NAO FORAM FEITAS VIA APP, PC OU RELOGIO, NAO PODE SER PAGO A VERBA OU VERIFICAR COM A SMSA';
--ELSIF 

IF ((C1.COD_CARGO_COMISS IS NOT NULL AND C1.COD_CARGO_COMISS <> '000000000000000')OR C1.CODIGO_FUNCAO IS NOT NULL) THEN
dbms_output.put_line('--****ATENCAO PESSOA COM CARGO COMISSINADO OU FUNCAO PUBLICA, NAO PODE SER PAGO A VERBA OU VERIFICAR COM A SMSA');
vLOG := vLOG||'|'||'*ATENCAO PESSOA COM CARGO COMISSINADO OU FUNCAO PUBLICA, NAO PODE SER PAGO A VERBA OU VERIFICAR COM A SMSA';
vCAMPO_4 := '*ATENCAO PESSOA COM CARGO COMISSINADO OU FUNCAO PUBLICA, NAO PODE SER PAGO A VERBA OU VERIFICAR COM A SMSA';
--INICIO --JA EXISTIA ATE 19/11/21-------------------------------------------------------------------------------------------------------------------------------------------------------------------
--ELSE
--ELSIF vQTD_EVENTOS = vTOTAL_MARCACOES_DIA THEN
ELSIF vQTD_EVENTOS <> 0 THEN
dbms_output.put_line('--****PROCESSAMENTO SEGUE AVALIANDO MARCACOES');
vLOG := vLOG||'|'||'*PROCESSAMENTO SEGUE AVALIANDO MARCACOES';
vCAMPO_3 := '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES';



-------------------------------DEFINIR SE PEGA AS 2 PRIMEIRAS OU A TERCEIRA E QUARTA MARCACAO DO DIA
/*COMENTADO EM 19/11/21
IF vTOTAL_MARCACOES_DIA = 2 THEN
vCODIGO_ME := C1.CODIGO_M1;
vCODIGO_MS := C1.CODIGO_M2;
ELSE
vCODIGO_ME := C1.CODIGO_M3;
vCODIGO_MS := C1.CODIGO_M4;
END IF;
dbms_output.put_line('--MARCACAO DE ENTRADA(vCODIGO_ME):'||vCODIGO_ME ||' MARCACAO DE SAIDA(vCODIGO_MS):'||vCODIGO_MS);
vLOG := vLOG||'|'||vCODIGO_ME||'|'||vCODIGO_MS;
*/


--INICIO----------------------------------------------------------------------------------------FOR C2 PARA PEGAR AS MARCACOES DE CADA DIA E AVALIAR A GEOLOCALIZACAO E CALENDARIO
FOR C2 IN 
(
SELECT 
ROUND((X2.DISTANCIA_KM_MARCACAO_CERCA/.83333),2)DIST_KM_MARC_CERCA_8333, 
X2.* FROM (
SELECT 
ROUND((SQRT(
POWER((CAST(REGEXP_REPLACE(X.LATITUDE_MARC,'-','')AS NUMBER)-CAST(REGEXP_REPLACE(X.LATITUDE_ART,'-','')AS NUMBER)),2)
+
POWER((CAST(REGEXP_REPLACE(X.LONGITUDE_MARC,'-','')AS NUMBER)-CAST(REGEXP_REPLACE(X.LONGITUDE_ART,'-','')AS NUMBER)),2)
) * 111.2),2) DISTANCIA_KM_MARCACAO_CERCA,
X.* FROM(
SELECT 
REGEXP_SUBSTR(M.IP, '[^."]+', 1, 1) P1_MARC, REGEXP_SUBSTR(M.IP, '[^."]+', 1, 2) P2_MARC, REGEXP_SUBSTR(M.IP, '[^."]+', 1, 3) P3_MARC,
REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 1) P1_REDE, REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 2) P2_REDE, REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 3) P3_REDE, --REGEXP_SUBSTR(E.RANGE_IP, '[^/"]+', 1, 2)CLASSE_REDE,
CAST(REGEXP_REPLACE(M.LATITUDE,'-','')AS NUMBER)LATITUDE_MARC,
CAST(REGEXP_REPLACE(E.LATIT,'-','')AS NUMBER)LATITUDE_ART,
CAST(REGEXP_REPLACE(M.LONGITUDE,'-','')AS NUMBER)LONGITUDE_MARC,
CAST(REGEXP_REPLACE(E.LONGI,'-','')AS NUMBER)LONGITUDE_ART,
CASE 
WHEN D.NRO_DIA_SEMANA = 1 THEN 'DOM' WHEN D.NRO_DIA_SEMANA = 2 THEN 'SEG' WHEN D.NRO_DIA_SEMANA = 3 THEN 'TER' WHEN D.NRO_DIA_SEMANA = 4 THEN 'QUA' WHEN D.NRO_DIA_SEMANA = 5 
THEN 'QUI' WHEN D.NRO_DIA_SEMANA = 6 THEN 'SEX' WHEN D.NRO_DIA_SEMANA = 7 THEN 'SAB' ELSE 'ERRO'END DIA_SEMANA, 
TO_NUMBER(TO_CHAR(M.DTEVENTO, 'HH24'))HORA,
EXTRACT(DAY FROM M.DTEVENTO)NUMERO_DIA, 
EXTRACT(MONTH FROM M.DTEVENTO)NUMERO_MES, 
CASE
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 1  THEN 'JANEIRO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 2  THEN 'FEVEREIRO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 3  THEN 'MARCO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 4  THEN 'ABRIL'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 5  THEN 'MAIO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 6  THEN 'JUNHO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 7  THEN 'JULHO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 8  THEN 'AGOSTO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 9  THEN 'SETEMBRO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 10 THEN 'OUTUBRO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 11 THEN 'NOVEMBRO'
WHEN EXTRACT(MONTH FROM M.DTEVENTO) = 12 THEN 'DEZEMBRO'
END DESCRICAO_MES,
EXTRACT(YEAR FROM M.DTEVENTO)NUMERO_ANO,
M.* ,E.*
,CASE WHEN M.E_ORIGEM IS NULL AND M.LATITUDE IS NULL THEN 'RELOGIO_PONTO' WHEN M.E_ORIGEM IS NULL AND M.LATITUDE IS NOT NULL THEN 'COMPUTADOR' ELSE M.E_ORIGEM END ORIGEM_MARCACAO--ALTERADO EM 10/11/21
FROM PONTO_ELETRONICO.IFPONTO_MARCACOES M 
LEFT OUTER JOIN 
(
/*
SELECT E.CODIGO COD_ENDERECO, E.DESCRICAO DESC_ENDERECO, E.ENDERECO ENDERECO_, E.NUMERO, E.BAIRRO BAIRRO_, E.CEP CEP_, E.CAIXA_POSTAL LATIT, E.TELEX LONGI , E.TEXTO_ASSOC IPS_REDE,
CG.CODIGO_EMPRESA, CG.COD_CGERENC1, CG.COD_CGERENC2, CG.COD_CGERENC3, CG.COD_CGERENC4, CG.COD_CGERENC5, CG.COD_CGERENC6, CG.DESCRICAO LOCAL, CG.ABREVIACAO
,CASE WHEN CG.c_livre_selec10 = '1' THEN 'APS'WHEN CG.c_livre_selec10 = '2' THEN 'COM'WHEN CG.c_livre_selec10 = '3' THEN 'UPA'WHEN CG.c_livre_selec10 = '4' THEN 'SUP'WHEN CG.c_livre_selec10 = '5' THEN 'CER' ELSE 'ERRO' END TIPO_LOCAL_SMSA_FEITO_EXTRA
FROM ARTERH.RHORGA_CUSTO_GEREN CG  
LEFT OUTER JOIN ARTERH.RHORGA_ENDERECO E ON CG.COD_ENDERECO = E.CODIGO WHERE CG.CODIGO_EMPRESA = '0001' AND CG.data_extincao IS NULL
and e.caixa_postal is not null and  e.telex is not null and cg.cod_cgerenc1 = '000095' --and cg.c_livre_selec10 in ('1','2','3','4','5')--LOCAIS MARCADOS PARA AS VERBAS
*/
SELECT 
--CODIGO_EMPRESA, DATA_DADOS, CONSIDERACOES,
CAMPO_1 COD_ENDERECO, CAMPO_2 RANGE_IP, CAMPO_3 LATIT, CAMPO_4 LONGI, CAMPO_5 TIPO_LOCAL_SMSA_FEITO_EXTRA, CAMPO_6 LOCAL, CAMPO_7 COD_LOCAL , 
CAMPO_8 ENDERECO_, CAMPO_9 NUMERO_, CAMPO_10 BAIRRO_ FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT WHERE CONSIDERACOES = 'PRG8_DESMEMBRA_REDES_RMI' AND TRUNC(DATA_DADOS)= TRUNC(SYSDATE) -- -3 testes
AND CAMPO_5 <> 'ERRO'
)E 
--COMENTADO EM 18/11/21--ON SUBSTR(E.LATIT,1,7)= SUBSTR(TO_CHAR(M.LATITUDE),1,7) AND SUBSTR(E.LONGI,1,7)= SUBSTR(TO_CHAR(M.LONGITUDE),1,7)--MUDEI PARA 6 CASAS EM 23/9/21 MAS DEU ERRO VOLTEI PARA 7--ARREDONDEI A LATITUDE E LONGITUDE PARA 7 CASAS, EX: -19.1234
ON (--NOVO EM 18/11/21
(SUBSTR(E.LATIT,1,7)= SUBSTR(TO_CHAR(M.LATITUDE),1,7) AND SUBSTR(E.LONGI,1,7)= SUBSTR(TO_CHAR(M.LONGITUDE),1,7)--MUDEI PARA 6 CASAS EM 23/9/21 MAS DEU ERRO VOLTEI PARA 7--ARREDONDEI A LATITUDE E LONGITUDE PARA 7 CASAS, EX: -19.1234
)
OR
(REGEXP_SUBSTR(M.IP, '[^."]+', 1, 1) =  REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 1) AND REGEXP_SUBSTR(M.IP, '[^."]+', 1, 2) =  REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 2) AND  REGEXP_SUBSTR(M.IP, '[^."]+', 1, 3) = REGEXP_SUBSTR(E.RANGE_IP, '[^."]+', 1, 3))
--(REGEXP_SUBSTR(M.IP, '[^."]+', 1, 1) =  REGEXP_SUBSTR(E.IPS_REDE, '[^."]+', 1, 1) AND REGEXP_SUBSTR(M.IP, '[^."]+', 1, 2) =  REGEXP_SUBSTR(E.IPS_REDE, '[^."]+', 1, 2) AND  REGEXP_SUBSTR(M.IP, '[^."]+', 1, 3) = REGEXP_SUBSTR(E.IPS_REDE, '[^."]+', 1, 3))
)

LEFT OUTER JOIN (SELECT C.CODIGO_EMPRESA CODIGO_EMPRESA_C, C.TIPO_CONTRATO TIPO_CONTRATO_C, C.CODIGO CODIGO_C, C.ANO_MES_REFERENCIA  ANO_MES_REFERENCIA_C
,C.cod_custo_gerenc1 cod_custo_gerenc1_C ,C.cod_custo_gerenc2 cod_custo_gerenc2_C ,C.cod_custo_gerenc3 cod_custo_gerenc3_C ,C.cod_custo_gerenc4 cod_custo_gerenc4_C ,C.cod_custo_gerenc5 cod_custo_gerenc5_C ,C.cod_custo_gerenc6 cod_custo_gerenc6_C
FROM ARTERH.RHPESS_CONTRATO C) C ON C.CODIGO_EMPRESA_C = LPAD(M.EMPRESA,4,0) AND C.TIPO_CONTRATO_C = LPAD(M.TIPO_CONTRATO,4,0) AND C.CODIGO_C =  LPAD(M.MATRICULA,15,0)

LEFT OUTER JOIN ARTERH.RHTABS_DATAS D ON TRUNC(D.DATA_DIA) = TRUNC(M.DTEVENTO)
WHERE M.CODIGO IN (vCODIGO_ME, vCODIGO_MS) ------------------------------------------------------este loop pega as 2 marcacoes ou apenas uma quando forem 3 no dia para analisar porem neste momento pode pegar mais de um local do organograma se tiver no mesmo endereco

AND C.ANO_MES_REFERENCIA_C = (SELECT MAX(A.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO A WHERE A.CODIGO_EMPRESA = C.CODIGO_EMPRESA_C AND A.TIPO_CONTRATO = C.TIPO_CONTRATO_C AND A.CODIGO = C.CODIGO_C )

ORDER BY M.CODIGO
)X
)X2

)
LOOP  --INICIO LOOP C2





 -------------------------------PEGAR O TIPO DE DIA NO CALENDARIO
SELECT
CASE 
WHEN C2.DESCRICAO_MES = 'JANEIRO' THEN CASE WHEN SUBSTR(JANEIRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'FEVEREIRO' THEN CASE WHEN SUBSTR(FEVEREIRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'MARCO' THEN CASE WHEN SUBSTR(MARCO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'ABRIL' THEN CASE WHEN SUBSTR(ABRIL, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'MAIO' THEN CASE WHEN SUBSTR(MAIO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'JUNHO' THEN CASE WHEN SUBSTR(JUNHO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'JULHO' THEN CASE WHEN SUBSTR(JULHO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'AGOSTO' THEN CASE WHEN SUBSTR(AGOSTO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'SETEMBRO' THEN CASE WHEN SUBSTR(SETEMBRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'OUTUBRO' THEN CASE WHEN SUBSTR(OUTUBRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'NOVEMBRO' THEN CASE WHEN SUBSTR(NOVEMBRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
WHEN C2.DESCRICAO_MES = 'DEZEMBRO' THEN CASE WHEN SUBSTR(DEZEMBRO, C2.NUMERO_DIA,1) IN ('F','O') OR C2.DIA_SEMANA IN ('SAB','DOM') THEN 'T2' ELSE 'T1' END
END TIPO_DIA_CALENDARIO
INTO vTIPO_DIA_CALENDARIO 
FROM ARTERH.RHPARM_CALENDARIO
WHERE CODIGO = '0004' ------------------calendario especifico da SMSA no Arterh NOVO PARA FERIADO E PONTOS FACULTATIVOS
AND TRUNC(ANO_REFERENCIA) = TO_DATE('01/01/'||C2.NUMERO_ANO,'DD/MM/YYYY') 
;
dbms_output.put_line('--***********************************************************DADOS DE UMA MARCACAO**************************************************************************************');
dbms_output.put_line('--C2.CODIGO DA MARCACAO: '||C2.CODIGO||' ORIGEM_MARCACAO: '|| C2.ORIGEM_MARCACAO|| ' C2.EFETIVADO: '||C2.EFETIVADO);
dbms_output.put_line('--C2.DTEVENTO: '||C2.DTEVENTO||' vTIPO_DIA_CALENDARIO:'||vTIPO_DIA_CALENDARIO||' DATA: '|| C2.NUMERO_DIA||'/'|| C2.DESCRICAO_MES||'/'|| C2.NUMERO_ANO);   

dbms_output.put_line('--C2.LATITUDE_MARC: '||C2.LATITUDE_MARC||' C2.LATITUDE_ART:'||C2.LATITUDE_ART||' C2.LONGITUDE_MARC: '|| C2.LONGITUDE_MARC||' C2.LONGITUDE_ART: '|| C2.LONGITUDE_ART);   
dbms_output.put_line('--C2.DISTANCIA_KM_MARCACAO_CERCA: '|| C2.DISTANCIA_KM_MARCACAO_CERCA|| ' C2.DIST_KM_MARC_CERCA_8333: '|| C2.DIST_KM_MARC_CERCA_8333);

dbms_output.put_line('--C2.DTEVENTO:'||C2.DTEVENTO|| ' - C2.OCORRENCIA:'||C2.OCORRENCIA);
--C2.EMPRESA, C2.TIPO_CONTRATO, C2.MATRICULA, C2.COD_PESSOA, C2.CODIGO, C2.DTEVENTO, C2.EFETIVADO, C2.IP, C2.LATITUDE, C2.LONGITUDE, C2.DATA_PROCESSAMENTO, C2.OCORRENCIA, C2.FOTO, C2.E_ORIGEM, C2.ENDERECO, C2.BAIRRO, C2.CEP, C2.GL_ORIGEM, C2.COD_ENDERECO, C2.DESC_ENDERECO, C2.ENDERECO_1, C2.NUMERO, C2.BAIRRO_1, C2.CEP_1, C2.LATIT, C2.LONGI, C2.IPS_REDE, C2.CODIGO_EMPRESA, C2.COD_CGERENC1, C2.COD_CGERENC2, C2.COD_CGERENC3, C2.COD_CGERENC4, C2.COD_CGERENC5, C2.COD_CGERENC6, C2.LOCAL, C2.ABREVIACAO, C2.TIPO_LOCAL_SMSA_FEITO_EXTRA
dbms_output.put_line('--C2.TIPO_LOCAL_SMSA_FEITO_EXTRA: '|| c2.TIPO_LOCAL_SMSA_FEITO_EXTRA);
--dbms_output.put_line('--DADOS MARCACAO NO IFPONTO/ARTERH: '|| C2.EMPRESA||'-'||  C2.TIPO_CONTRATO||'-'||  C2.MATRICULA||'-'|| C2.COD_PESSOA||'-'||  C2.CODIGO||'-'|| C2.DIA_SEMANA ||'-'||C2.HORA||'-'|| C2.DTEVENTO||'-'||  C2.EFETIVADO||'-'||  C2.IP||'-'||  C2.LATITUDE||'-'||  C2.LONGITUDE||'-'||  C2.DATA_PROCESSAMENTO||'-'||  C2.OCORRENCIA||'-'||  C2.FOTO||'-'||  C2.E_ORIGEM||'-'||  C2.ENDERECO||'-'||  C2.BAIRRO||'-'||  C2.CEP||'-'||  C2.GL_ORIGEM||'-'||  C2.COD_ENDERECO||'-'||  C2.DESC_ENDERECO||'-'||  C2.ENDERECO_||'-'||  C2.NUMERO||'-'||  C2.BAIRRO_||'-'||  C2.CEP_||'-'||  C2.LATIT||'-'||  C2.LONGI||'-'||  C2.IPS_REDE||'-'||  C2.CODIGO_EMPRESA||'-'||  C2.COD_CGERENC1||'-'||  C2.COD_CGERENC2||'-'||  C2.COD_CGERENC3||'-'||  C2.COD_CGERENC4||'-'||  C2.COD_CGERENC5||'-'||  C2.COD_CGERENC6||'-'||  C2.LOCAL||'-'||  C2.ABREVIACAO);
dbms_output.put_line('--DADOS MARCACAO DO IFPONTO: '|| C2.E_ORIGEM||'-'||  C2.ENDERECO||'-'||  C2.BAIRRO||'-'||  C2.CEP||'-'||  C2.GL_ORIGEM);
dbms_output.put_line('--DADOS LOCAL NO ARTERH: '|| C2.TIPO_LOCAL_SMSA_FEITO_EXTRA ||'-'|| C2.COD_LOCAL||'-'|| C2.LOCAL);
dbms_output.put_line('--DADOS ENDERECO LOCAL NO ARTERH: '||C2.COD_ENDERECO||'-'||  C2.ENDERECO_||'-'||  C2.NUMERO_||'-'||  C2.BAIRRO_);


--INICIO--NOVO EM 4/2/22
IF C2.CODIGO = vCODIGO_ME AND C2.TIPO_LOCAL_SMSA_FEITO_EXTRA IS NOT NULL AND v1_LOCAL_PBH_MARCACAO_ENTRADA IS NULL THEN 
v1_LOCAL_PBH_MARCACAO_ENTRADA :=  C2.TIPO_LOCAL_SMSA_FEITO_EXTRA ||'-'|| C2.COD_LOCAL||'-'|| C2.LOCAL ||'-'|| C2.COD_ENDERECO ||'-'||  C2.ENDERECO_ ||'-'||  C2.NUMERO_ ||'-'||  C2.BAIRRO_ ;
dbms_output.put_line('--v1_LOCAL_PBH_MARCACAO_ENTRADA: '||v1_LOCAL_PBH_MARCACAO_ENTRADA );
END IF;

IF C2.CODIGO = vCODIGO_MS AND C2.TIPO_LOCAL_SMSA_FEITO_EXTRA IS NOT NULL AND v1_LOCAL_PBH_MARCACAO_SAIDA IS NULL THEN 
v1_LOCAL_PBH_MARCACAO_SAIDA :=  C2.TIPO_LOCAL_SMSA_FEITO_EXTRA ||'-'|| C2.COD_LOCAL||'-'|| C2.LOCAL ||'-'|| C2.COD_ENDERECO ||'-'||  C2.ENDERECO_ ||'-'||  C2.NUMERO_ ||'-'||  C2.BAIRRO_ ;
dbms_output.put_line('--v1_LOCAL_PBH_MARCACAO_SAIDA: '||v1_LOCAL_PBH_MARCACAO_SAIDA );
END IF;
--FIM--NOVO EM 4/2/22


--------------------------------------------------AJUSTE DO DIA PARA OS TIPOS T1/T2 DA SAV1
IF vTIPO_DIA_PAGAR = 'T1' AND vTIPO_DIA_CALENDARIO = 'T2' THEN
vTIPO_DIA_PAGAR := 'T2';
END IF;
dbms_output.put_line('--vTIPO_DIA_PAGAR:'||vTIPO_DIA_PAGAR);

--------------------------------------------------AJUSTAR O LOCAL DAS 2 MARCACOES

vLOCAL_USAR := C2.TIPO_LOCAL_SMSA_FEITO_EXTRA; --NOVO EM 12/10/21
dbms_output.put_line('--vLOCAL_USAR:'||vLOCAL_USAR);
--dbms_output.put_line('--****************************');

--COLOCANDO AQUI EM 12/10/21 11H23 PARA AVALIAR A CHAVE E PARAR DE TROCAR SE ACHAR A O LOCAL E MARCACAO QUE ATENDER O TIPO DE SOBREAVISO DEFINIDO NO IFPONTO
vCHAVE_SAV1 := vCHAVE_SAV1||vLOCAL_USAR||vTIPO_DIA_PAGAR|| CASE WHEN C1.TIPO_SOBREAVISO = 'Plantão Extra'	THEN 'PEX' WHEN C1.TIPO_SOBREAVISO = 'Plantão Extra SUP' THEN 'PSU' WHEN C1.TIPO_SOBREAVISO ='Abono CERSAM' THEN'ACE' END  ;
--vCHAVE_SAV1_PARCIAL := vCHAVE_SAV1_PARCIAL||vLOCAL_USAR||vTIPO_DIA_PAGAR|| CASE WHEN C1.TIPO_SOBREAVISO = 'Plantão Extra'	THEN 'PEX' WHEN C1.TIPO_SOBREAVISO = 'Plantão Extra SUP' THEN 'PSU' WHEN C1.TIPO_SOBREAVISO ='Abono CERSAM' THEN'ACE' END  ;
dbms_output.put_line('--vCHAVE_SAV1: '||vCHAVE_SAV1);


vLOCAIS_PODE_VERBA := 'S';--NOVO EM 3/2/22


dbms_output.put_line('--vLOCAIS_PODE_VERBA: '||vLOCAIS_PODE_VERBA);

--NOVO IF EM 12/10/21 PARA DEIXAR A CHAVE_SAV1 igaual a SIM quando achar a primeira ou ultima no final como SIM
IF vLOCAIS_PODE_VERBA = 'S' THEN
vCHAVE_SAV1_FINAL := vCHAVE_SAV1 ;
vLOCAIS_PODE_VERBA_FINAL := 'S' ;
--ELSE
--vLOCAIS_PODE_VERBA_FINAL := 'N' ;--NOVO EM 22/11/21
END IF;

--INICIO --novo em 3/1/22
IF vLOCAIS_PODE_VERBA = 'S' AND vMARCACAO_ATUAL IS NULL THEN
vQTD_LOCAIS_PODE_VERBA := vQTD_LOCAIS_PODE_VERBA + 1;
ELSIF vLOCAIS_PODE_VERBA = 'S' AND vMARCACAO_ATUAL IS NOT NULL AND vMARCACAO_ATUAL <> C2.CODIGO THEN
vQTD_LOCAIS_PODE_VERBA := vQTD_LOCAIS_PODE_VERBA + 1;--novo em 3/1/22
END IF;
vMARCACAO_ATUAL := C2.CODIGO;
--FIM--novo em 3/1/22


dbms_output.put_line('--***************vCHAVE_SAV1_FINAL: '||vCHAVE_SAV1_FINAL||' vLOCAIS_PODE_VERBA_FINAL: '||vLOCAIS_PODE_VERBA_FINAL|| ' vQTD_LOCAIS_PODE_VERBA: '||vQTD_LOCAIS_PODE_VERBA);

--vLOG := vLOG||'|'||C2.ORIGEM_MARCACAO ||'|'||vCHAVE_SAV1_FINAL;
vLOG_MARCACOES := vLOG_MARCACOES||'|'||C2.ORIGEM_MARCACAO ||'|'||C2.EFETIVADO||'|'||vCHAVE_SAV1_FINAL;

IF C2.ORIGEM_MARCACAO IS NOT NULL THEN
vORIGEM_MARCACAO := C2.ORIGEM_MARCACAO;
END IF;

--EM 12/10/21 11H40 --TROQUEI DE LOCAL COLOCANDO AQUI PARA CADA CADA C2
--/*
------------------------------------------------verificar LOCAL se pode em outros tipos de verba
IF vLOCAIS_PODE_VERBA = 'N' THEN
dbms_output.put_line('--LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO');
--vLOG := vLOG||'|'||'LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO';
vLOG_ERRO_REGRA_LOCAL_MARCA := '*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO';
vCAMPO_4 := '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO';
--inicio-----------------------------------SABER SE OS DADOS ESTAO NA TABELA DE CONVERSAO SAV1


--mudar da v1 para v2 aceitar qualquer tipo de sobreaviso se lancar errado no Ifponto validar apenas local origem e destino mas nao confrontar o tipo
vCHAVE_SAV1 := SUBSTR(vCHAVE_SAV1,1,8);
dbms_output.put_line('--vCHAVE_SAV1: '||vCHAVE_SAV1);
SELECT
CASE WHEN X2.QUANT = 0 OR X2.QUANT IS NULL THEN 0 ELSE X2.QUANT END
INTO vLOCAIS_PODE_VERBA
FROM (
SELECT SUM(X.QUANT) QUANT FROM
(
SELECT SUBSTR(X.DADO_ORIGEM,1,8)LOCAIS_DIA, COUNT(1)QUANT FROM ARTERH.RHINTE_ED_IT_CONV X WHERE X.CODIGO_CONVERSAO = 'SAV1' AND SUBSTR(X.DADO_ORIGEM,1,8) = vCHAVE_SAV1
GROUP BY SUBSTR(X.DADO_ORIGEM,1,8)
--SELECT COUNT(1)QUANT FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'SAV1' AND DADO_ORIGEM = vCHAVE_SAV1
)X
)X2;
ELSE
vLOG_ERRO_REGRA_LOCAL_MARCA := NULL;
END IF;
dbms_output.put_line('----QUANTIDADE DE TIPO E VERBA QUE O LOCAL PODE USAR: '||vLOCAIS_PODE_VERBA);
--fim-----------------------------------SABER SE OS DADOS ESTAO NA TABELA DE CONVERSAO SAV1
--*/



--INICIO --NOVO EM 11/10/21 -- PARA PERCORRER TODOS ENDERECOS ORGANOGRAMA PBH E APONTAR LOCAL MAIS PROXIMO DA MARCACAO----********************************************************************************************************
------------------------------------------------------------------------------------------------C2--LOCAIS DA PBH A PERCORRER PARA ACHAR O MAIS PROXIMO DA MARCACAO
--/*
IF C2.ORIGEM_MARCACAO <> 'RELOGIO_PONTO' THEN --NOVO EM 10/11/21
FOR C3 IN (

SELECT X3.* FROM(
SELECT 
ROW_NUMBER() OVER (PARTITION BY X2.COD_ENDERECO ORDER BY X2.COD_ENDERECO, X2.TIPO)ORDEM_COD_ENDERECO,
X2.TIPO, X2.COD_ENDERECO, X2.DESC_ENDERECO, X2.ENDERECO_, X2.NUMERO, X2.BAIRRO_, X2.CEP_, X2.LATIT, X2.LONGI, X2.IPS_REDE, COUNT(1)QUANT_LOCAIS_ENDERECO 
FROM(
SELECT 
'1_SMSA' TIPO, X.COD_ENDERECO, X.DESC_ENDERECO, X.ENDERECO_, X.NUMERO, X.BAIRRO_, X.CEP_, 
X.LATIT, X.LONGI,
X.IPS_REDE, COUNT(1)QUANT_LOCAIS_ENDERECO --X.* 
FROM (
SELECT E.CODIGO COD_ENDERECO, E.DESCRICAO DESC_ENDERECO, E.ENDERECO ENDERECO_, E.NUMERO, E.BAIRRO BAIRRO_, E.CEP CEP_, E.CAIXA_POSTAL LATIT, E.TELEX LONGI , E.TEXTO_ASSOC IPS_REDE
FROM
ARTERH.RHORGA_CUSTO_GEREN CG  
LEFT OUTER JOIN
ARTERH.RHORGA_ENDERECO E 
ON CG.COD_ENDERECO = E.CODIGO 
WHERE 
CG.CODIGO_EMPRESA = '0001' AND 
CG.data_extincao IS NULL and
e.caixa_postal is not null and  e.telex is not null --856
AND E.c_livre_data02 IS NULL--856
and cg.cod_cgerenc1 = '000095' --and cg.c_livre_selec10 in ('1','2','3','4','5')--LOCAIS MARCADOS PARA AS VERBAS
and cg.cod_cgerenc1 not in ('000099','000098') 
)X 
GROUP BY X.COD_ENDERECO, X.DESC_ENDERECO, X.ENDERECO_, X.NUMERO, X.BAIRRO_, X.CEP_, X.LATIT, X.LONGI, X.IPS_REDE-- ORDER BY X.LATIT, X.LONGI, COUNT(1)DESC
UNION ALL
SELECT 
'2_OUTRAS_SECRETARIAS' TIPO, X.COD_ENDERECO, X.DESC_ENDERECO, X.ENDERECO_, X.NUMERO, X.BAIRRO_, X.CEP_, 
X.LATIT, X.LONGI,
X.IPS_REDE, COUNT(1)QUANT_LOCAIS_ENDERECO --X.* 
FROM (
SELECT E.CODIGO COD_ENDERECO, E.DESCRICAO DESC_ENDERECO, E.ENDERECO ENDERECO_, E.NUMERO, E.BAIRRO BAIRRO_, E.CEP CEP_, E.CAIXA_POSTAL LATIT, E.TELEX LONGI , E.TEXTO_ASSOC IPS_REDE
FROM
ARTERH.RHORGA_CUSTO_GEREN CG  
LEFT OUTER JOIN
ARTERH.RHORGA_ENDERECO E 
ON CG.COD_ENDERECO = E.CODIGO 
WHERE 
CG.CODIGO_EMPRESA = '0001' AND 
CG.data_extincao IS NULL and
e.caixa_postal is not null and  e.telex is not null --856
AND E.c_livre_data02 IS NULL--856
and cg.cod_cgerenc1 <> '000095' --and cg.c_livre_selec10 in ('1','2','3','4','5')--LOCAIS MARCADOS PARA AS VERBAS
and cg.cod_cgerenc1 not in ('000099','000098') 
)X 
GROUP BY X.COD_ENDERECO, X.DESC_ENDERECO, X.ENDERECO_, X.NUMERO, X.BAIRRO_, X.CEP_, X.LATIT, X.LONGI, X.IPS_REDE --ORDER BY X.LATIT, X.LONGI, COUNT(1)DESC
)X2 
GROUP BY X2.TIPO, X2.COD_ENDERECO, X2.DESC_ENDERECO, X2.ENDERECO_, X2.NUMERO, X2.BAIRRO_, X2.CEP_, X2.LATIT, X2.LONGI, X2.IPS_REDE
ORDER BY X2.COD_ENDERECO, X2.TIPO, X2.LATIT, X2.LONGI
)X3 WHERE X3.ORDEM_COD_ENDERECO = 1 ORDER BY X3.LATIT, X3.LONGI

--*/

)

LOOP
vDADOS_LOCAL_MAIS_PROXIMO:= C3.COD_ENDERECO||'-'||C3.DESC_ENDERECO||'-'||C3.ENDERECO_||'-'||C3.NUMERO||'-'||C3.BAIRRO_||'-'||C3.CEP_;
--dbms_output.put_line('--vDISTANCIA_MAIS_PROXIMA: '||vDISTANCIA_MAIS_PROXIMA);--DEBUGAR
--dbms_output.put_line('--vLOCAL_MAIS_PROXIMO: '||vLOCAL_MAIS_PROXIMO);--DEBUGAR
--dbms_output.put_line('-- vQUANT_LOCAIS_ENDERECO: '||vQUANT_LOCAIS_ENDERECO);--DEBUGAR
----------------------------------------------------------------------------------------------------------CALCULAR F_DISTANCIA_V2
--/*
SELECT 
--ROUND((X2.DISTANCIA_KM_MARCACAO_CERCA/.83333),2)DIST_KM_MARC_CERCA_8333, 
X2.DISTANCIA_KM_MARCACAO_CERCA
INTO 
vDISTANCIA
FROM (
SELECT 
ROUND((SQRT(
POWER((CAST(REGEXP_REPLACE(X.LATITUDE_MARC,'-','')AS NUMBER)-CAST(REGEXP_REPLACE(X.LATITUDE_ART,'-','')AS NUMBER)),2)
+
POWER((CAST(REGEXP_REPLACE(X.LONGITUDE_MARC,'-','')AS NUMBER)-CAST(REGEXP_REPLACE(X.LONGITUDE_ART,'-','')AS NUMBER)),2)
) * 111.2),2) DISTANCIA_KM_MARCACAO_CERCA,
X.* FROM(
SELECT 
CAST(REGEXP_REPLACE(C2.LATITUDE_MARC,'-','')AS NUMBER)LATITUDE_MARC,
CAST(REGEXP_REPLACE(C3.LATIT,'-','')AS NUMBER)LATITUDE_ART,
CAST(REGEXP_REPLACE(C2.LONGITUDE_MARC,'-','')AS NUMBER)LONGITUDE_MARC,
CAST(REGEXP_REPLACE(C3.LONGI,'-','')AS NUMBER)LONGITUDE_ART
FROM DUAL)X)X2;
--*/


IF vLOCAL_MAIS_PROXIMO IS NULL THEN
vDISTANCIA_MAIS_PROXIMA := vDISTANCIA;
vLOCAL_MAIS_PROXIMO := C3.COD_ENDERECO;
vQUANT_LOCAIS_ENDERECO := C3.QUANT_LOCAIS_ENDERECO;
vTIPO_LOCAL_C3 := C3.TIPO;
ELSIF vLOCAL_MAIS_PROXIMO IS NOT NULL AND vDISTANCIA < vDISTANCIA_MAIS_PROXIMA THEN
vLOCAL_MAIS_PROXIMO := C3.COD_ENDERECO;
vDISTANCIA_MAIS_PROXIMA := vDISTANCIA;
vQUANT_LOCAIS_ENDERECO := C3.QUANT_LOCAIS_ENDERECO;
vTIPO_LOCAL_C3 := C3.TIPO;
END IF;

END LOOP; -----------------FIM DO C3
ELSE

vDISTANCIA := 0;
vDISTANCIA_MAIS_PROXIMA := 0;
vLOCAL_MAIS_PROXIMO := NULL;
vQUANT_LOCAIS_ENDERECO := 0;
vDADOS_LOCAL_MAIS_PROXIMO := NULL;
vTIPO_LOCAL_C3 := NULL;

END IF;--NOVO EM 10/11/21

dbms_output.put_line('--******************************************************************APENAS PARA ANALISE NAO ESTA NA LOGICA****--RESULTADO FINAL DE UM LOCAL MAIS PROXIMO DA PBH BASEADO NA MARCACAO--**********');
dbms_output.put_line('--vDISTANCIA_MAIS_PROXIMA: '||vDISTANCIA_MAIS_PROXIMA);
dbms_output.put_line('--vLOCAL_MAIS_PROXIMO: '||vLOCAL_MAIS_PROXIMO);
dbms_output.put_line('--vQUANT_LOCAIS_ENDERECO: '||vQUANT_LOCAIS_ENDERECO||' vTIPO_LOCAL_C3: '||vTIPO_LOCAL_C3);

--/*
IF vQUANT_LOCAIS_ENDERECO > 1 THEN
dbms_output.put_line('--ENDERECO DA PBH COM MAIS DE UM LOCAL NO ORGANOGRAMA VERIFICAR MANUALMENTE PELA VARIAVEL: vLOCAL_MAIS_PROXIMO');
dbms_output.put_line('--vDADOS_LOCAL_MAIS_PROXIMO: '||vDADOS_LOCAL_MAIS_PROXIMO);

ELSIF vQUANT_LOCAIS_ENDERECO = 1 AND vTIPO_LOCAL_C3 = '1_SMSA' THEN
SELECT 
--E.CODIGO ||'-'||E.DESCRICAO ||'-'||E.ENDERECO ||'-'||E.NUMERO||'-'||E.BAIRRO ||'-'||E.CEP ||'-'||E.CAIXA_POSTAL ||'-'||E.TELEX ||'-'||E.TEXTO_ASSOC ||'-'||CG.CODIGO_EMPRESA||'-'|| CG.COD_CGERENC1||'-'|| CG.COD_CGERENC2||'-'|| CG.COD_CGERENC3||'-'|| CG.COD_CGERENC4||'-'|| CG.COD_CGERENC5||'-'|| CG.COD_CGERENC6 ||'-'||CG.DESCRICAO ||'-'|| CG.ABREVIACAO||'-'|| CASE WHEN CG.c_livre_selec10 = '1' THEN 'APS'WHEN CG.c_livre_selec10 = '2' THEN 'COM'WHEN CG.c_livre_selec10 = '3' THEN 'UPA'WHEN CG.c_livre_selec10 = '4' THEN 'SUP'WHEN CG.c_livre_selec10 = '5' THEN 'CER' ELSE 'ERRO' END
CASE WHEN CG.c_livre_selec10 = '1' THEN 'APS'WHEN CG.c_livre_selec10 = '2' THEN 'COM'WHEN CG.c_livre_selec10 = '3' THEN 'UPA'WHEN CG.c_livre_selec10 = '4' THEN 'SUP'WHEN CG.c_livre_selec10 = '5' THEN 'CER' ELSE 'ERRO' END ||'-'|| CG.COD_CGERENC1||'-'|| CG.COD_CGERENC2||'-'|| CG.COD_CGERENC3||'-'|| CG.COD_CGERENC4||'-'|| CG.COD_CGERENC5||'-'|| CG.COD_CGERENC6 ||'-'||CG.DESCRICAO ||'-'|| CG.ABREVIACAO||'-'|| E.CODIGO ||'-'||E.DESCRICAO ||'-'||E.ENDERECO ||'-'||E.NUMERO||'-'||E.BAIRRO ||'-'||E.CEP ||'-'||E.CAIXA_POSTAL ||'-'||E.TELEX ||'-'||E.TEXTO_ASSOC
INTO vDADOS_LOCAL_MAIS_PROXIMO
FROM
ARTERH.RHORGA_CUSTO_GEREN CG  
LEFT OUTER JOIN
ARTERH.RHORGA_ENDERECO E 
ON CG.COD_ENDERECO = E.CODIGO 
WHERE 
CG.CODIGO_EMPRESA = '0001' AND 
CG.data_extincao IS NULL and
e.caixa_postal is not null and  e.telex is not null --856
AND E.c_livre_data02 IS NULL--856
and cg.cod_cgerenc1 not in ('000099','000098') 
AND CG.cod_cgerenc1 = '000095'
AND E.CODIGO = vLOCAL_MAIS_PROXIMO
AND ROWNUM = 1;

ELSIF vQUANT_LOCAIS_ENDERECO = 1 AND vTIPO_LOCAL_C3 <> '1_SMSA' THEN
SELECT 
--E.CODIGO ||'-'||E.DESCRICAO ||'-'||E.ENDERECO ||'-'||E.NUMERO||'-'||E.BAIRRO ||'-'||E.CEP ||'-'||E.CAIXA_POSTAL ||'-'||E.TELEX ||'-'||E.TEXTO_ASSOC ||'-'||CG.CODIGO_EMPRESA||'-'|| CG.COD_CGERENC1||'-'|| CG.COD_CGERENC2||'-'|| CG.COD_CGERENC3||'-'|| CG.COD_CGERENC4||'-'|| CG.COD_CGERENC5||'-'|| CG.COD_CGERENC6 ||'-'||CG.DESCRICAO ||'-'|| CG.ABREVIACAO||'-'|| CASE WHEN CG.c_livre_selec10 = '1' THEN 'APS'WHEN CG.c_livre_selec10 = '2' THEN 'COM'WHEN CG.c_livre_selec10 = '3' THEN 'UPA'WHEN CG.c_livre_selec10 = '4' THEN 'SUP'WHEN CG.c_livre_selec10 = '5' THEN 'CER' ELSE 'ERRO' END
CASE WHEN CG.c_livre_selec10 = '1' THEN 'APS'WHEN CG.c_livre_selec10 = '2' THEN 'COM'WHEN CG.c_livre_selec10 = '3' THEN 'UPA'WHEN CG.c_livre_selec10 = '4' THEN 'SUP'WHEN CG.c_livre_selec10 = '5' THEN 'CER' ELSE 'ERRO' END||'-'||CG.COD_CGERENC1||'-'|| CG.COD_CGERENC2||'-'|| CG.COD_CGERENC3||'-'|| CG.COD_CGERENC4||'-'|| CG.COD_CGERENC5||'-'|| CG.COD_CGERENC6 ||'-'||CG.DESCRICAO ||'-'|| CG.ABREVIACAO||'-'|| E.CODIGO ||'-'||E.DESCRICAO ||'-'||E.ENDERECO ||'-'||E.NUMERO||'-'||E.BAIRRO ||'-'||E.CEP ||'-'||E.CAIXA_POSTAL ||'-'||E.TELEX ||'-'||E.TEXTO_ASSOC
INTO vDADOS_LOCAL_MAIS_PROXIMO
FROM
ARTERH.RHORGA_CUSTO_GEREN CG  
LEFT OUTER JOIN
ARTERH.RHORGA_ENDERECO E 
ON CG.COD_ENDERECO = E.CODIGO 
WHERE 
CG.CODIGO_EMPRESA = '0001' AND 
CG.data_extincao IS NULL and
e.caixa_postal is not null and  e.telex is not null --856
AND E.c_livre_data02 IS NULL--856
and cg.cod_cgerenc1 not in ('000099','000098') 
AND CG.cod_cgerenc1 <> '000095'
AND E.CODIGO = vLOCAL_MAIS_PROXIMO
AND ROWNUM = 1;

dbms_output.put_line('--ENDERECO DA PBH COM 1 LOCAL NO ORGANOGRAMA PELA VARIAVEL: vLOCAL_MAIS_PROXIMO');
dbms_output.put_line('--vDADOS_LOCAL_MAIS_PROXIMO: '||vDADOS_LOCAL_MAIS_PROXIMO);
--*/
END IF;
--*/
dbms_output.put_line('--vDADOS_LOCAL_MAIS_PROXIMO: '||vDADOS_LOCAL_MAIS_PROXIMO);
--vLOG := vLOG||'|'||vDADOS_LOCAL_MAIS_PROXIMO;
--vLOG_MARCACOES := vLOG_MARCACOES||'|'||vDADOS_LOCAL_MAIS_PROXIMO;



vDISTANCIA := 0;
vDISTANCIA_MAIS_PROXIMA := 0;
vLOCAL_MAIS_PROXIMO := NULL;
vQUANT_LOCAIS_ENDERECO := 0;
vDADOS_LOCAL_MAIS_PROXIMO := NULL;
vTIPO_LOCAL_C3 := NULL;
--FIM --NOVO EM 11/10/21 -- PARA PERCORRER TODOS ENDERECOS ORGANOGRAMA PBH E APONTAR LOCAL MAIS PROXIMO DA MARCACAO-----*********************************************************************************************************

vCHAVE_SAV1 := C1.TIPO_LOCAL_LOTACAO;--NOVO LOCAL EM 12/10/21 11H47

END LOOP; -----------------------------------------------------FIM DO C2


--FIM----------------------------------------------------------------------------------------FOR C2 PARA PEGAR AS MARCACOES DE CADA DIA E AVALIAR A GEOLOCALIZACAO E CALENDARIO

dbms_output.put_line('-----------------------------------------------------------************RESULTADO ANALISE MARCACOES*********----------------------------------------------------------------------------------------------');

dbms_output.put_line('--vCHAVE_SAV1_FINAL: '||vCHAVE_SAV1_FINAL||' vLOCAIS_PODE_VERBA_FINAL: '||vLOCAIS_PODE_VERBA_FINAL );--NOVO EM 12/10/21 11H30
vLOG := vLOG||'|'||vCHAVE_SAV1_FINAL||'|';--novo em 4/1/22


--INICIO -----------------------------------------------------------------------ULTIMA PARTE ---GERAR A SITUACAO DE PONTO DEVIDA COM MARCACOES CORRETAS ---------------------------------------------
--/*
dbms_output.put_line('----------------------------------------*******************RESULTADO FINAL DO REGISTRO****************---------------------------------------------------------');
dbms_output.put_line('--vCARGO_PODE_VERBA: '||vCARGO_PODE_VERBA||' vLOCAIS_PODE_VERBA_FINAL: '||vLOCAIS_PODE_VERBA_FINAL|| ' vPAGA_1_MARCACAO_VALIDA: '||vPAGA_1_MARCACAO_VALIDA);
---INICIO------------------------------------------------------------------------------PARTE 1 DE TENTAR PAGAR COM MARCACOES VALIDAS
--vNUMERO := ROUND(C1.EXECUTADO_SOBREAVISO) ; --para arredondar os 15 minutos de tolerancia para o valor ser sempre 12 ou 24 horas
--vSTRING := CASE WHEN INSTR(vNUMERO,',',1,1) = 0 THEN TO_CHAR(vNUMERO) WHEN INSTR(vNUMERO,',',1,1) <> 0 THEN TO_CHAR(SUBSTR(vNUMERO,1,INSTR(vNUMERO,',',1,1)-1) ||'.'||SUBSTR(vNUMERO,INSTR(vNUMERO,',' ,1,1)+1, LENGTH(vNUMERO))) end ;


IF vCARGO_PODE_VERBA = 'S' AND vLOCAIS_PODE_VERBA_FINAL = 'S' THEN--TROQUEI VARIAVEL EM 12/10/21 11H37 --AND vLOCAIS_PODE_VERBA = 'S' THEN

dbms_output.put_line('--GRAVANDO SITUACAO DE PONTO COM VALIDACAO INTEGRAL TABELA SAV1 CONSIDERANDO MARCACOES: 0578-HORA EXTRA - CAMPANHA COVID-19');
dbms_output.put_line('DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C1.EMPRESA ||''' AND TIPO_CONTRATO = ''' || C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.MATRICULA ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''0578''; COMMIT;' );  
DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = 'F' AND CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.MATRICULA AND TRUNC(DATA) = C1.DATA AND CODIGO_SITUACAO = '0578'; COMMIT;  
dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES ('''||C1.EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.MATRICULA ||''', TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY''),''0578'','|| vSTRING ||', ''F'', SYSDATE, ''IFPONTO'',''N'',''SCRIPT FECHAMENTO IFPONTO(grava_sobreaviso_campanha_vacinacao_v1.sql)''); COMMIT;' );  
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES (C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, C1.DATA,'0578', vSTRING, 'F', SYSDATE, 'IFPONTO','N','PRG11_CAMPANHA_VACINACAO'); COMMIT;
vLOG := vLOG||'-'||'GRAVANDO SITUACAO DE PONTO COM VALIDACAO INTEGRAL TABELA SAV4 CONSIDERANDO MARCACOES: 0578-HORA EXTRA - CAMPANHA COVID-19';
vLOG_ERRO_REGRA_LOCAL_MARCA := NULL;
vCAMPO_4 := '*GRAVANDO SITUACAO DE PONTO COM VALIDACAO INTEGRAL TABELA SAV4 CONSIDERANDO MARCACOES: 0578-HORA EXTRA - CAMPANHA COVID-19';

---FIM------------------------------------------------------------------------------PARTE 1 DE TENTAR PAGAR COM MARCACOES VALIDAS
--ELSE
--COMENTADO 19/11/21--dbms_output.put_line('--***************POR ALGUM MOTIVO NAO SERA GRAVADA A SITUACAO DE PONTO, CONFERIR REGISTRO');
--COMENTADO 19/11/21--vLOG := vLOG||'|'||'--***************POR ALGUM MOTIVO NAO SERA GRAVADA A SITUACAO DE PONTO, CONFERIR REGISTRO';

--INICIO---NOVO EM 19/11/21 PAGAR APENAS COM O LOCAL DE LOTACAO MESMO NAO ACHANDO O LOCAL DA MARCACAO
ELSIF vCARGO_PODE_VERBA = 'N' AND vLOCAIS_PODE_VERBA_FINAL = 'S' THEN
dbms_output.put_line('--***************LOCAL E MARCACOES ATENDERAM A REGRA INTEGRAL POREM CARGO NAO PODE VERBA');
vLOG := vLOG||'-'||'--***************LOCAL E MARCACOES ATENDERAM A REGRA INTEGRAL POREM CARGO NAO PODE VERBA';
vCAMPO_4 := vCAMPO_4||'-'||'*LOCAL E MARCACOES ATENDERAM A REGRA INTEGRAL POREM CARGO NAO PODE VERBA';



--COLOCAR AQUI TALVEZ EM 7/12/21 MAIS 1 ELSIF

--comentado 19/11/21 17h18 --
END IF; --------------------- 
--FIM -----------------------------------------------------------------------ULTIMA PARTE ---GERAR A SITUACAO DE PONTO DEVIDA COM MARCACOES CORRETAS ---------------------------------------------
--FIM--JA EXISTIA ATE 19/11/21-------------------------------------------------------------------------------------------------------------------------------------------------------------------

---INICIO------------------------------------------------------------------------------PARTE 3 DE TENTAR PAGAR SEM MARCACOES
--INICIO----NOVO EM 19/11/21 --------------APENAS COM MARCACOES NO ESPELHO-------------------------------------------------------------------------------------------------------------------------------------------
ELSIF vQTD_EVENTOS = 0 THEN
dbms_output.put_line('--****PROCESSAMENTO SEGUE APENAS MARCACOES DIRETO NO ESPELHO');
vLOG := vLOG||'|'||'--****PROCESSAMENTO SEGUE APENAS MARCACOES DIRETO NO ESPELHO';
vCAMPO_3 := '*PROCESSAMENTO SEGUE APENAS MARCACOES DIRETO NO ESPELHO';
IF vCARGO_PODE_VERBA = 'S' THEN   
dbms_output.put_line('--GRAVANDO SITUACAO DE PONTO COM VALIDACAO PARCIAL TABELA SAV1 MARCACOES DIRETO NO ESPELHO: 0578-HORA EXTRA - CAMPANHA COVID-19');
dbms_output.put_line('DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C1.EMPRESA ||''' AND TIPO_CONTRATO = ''' || C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.MATRICULA ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''0578''; COMMIT;' );  
DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = 'F' AND CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.MATRICULA AND TRUNC(DATA) = C1.DATA AND CODIGO_SITUACAO = '0578'; COMMIT;  
dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES ('''||C1.EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.MATRICULA ||''', TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY''),''0578'','|| vSTRING ||', ''F'', SYSDATE, ''IFPONTO'',''N'',''SCRIPT FECHAMENTO IFPONTO(grava_sobreaviso_campanha_vacinacao_v1.sql)''); COMMIT;' );  
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES (C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, C1.DATA,'0578', vSTRING , 'F', SYSDATE, 'IFPONTO','N','PRG11_CAMPANHA_VACINACAO'); COMMIT;  
vLOG := vLOG||'-'||'GRAVANDO SITUACAO DE PONTO COM VALIDACAO PARCIAL TABELA SAV1 MARCACOES DIRETO NO ESPELHO: 0578-HORA EXTRA - CAMPANHA COVID-19';
vCAMPO_4 :='*GRAVANDO SITUACAO DE PONTO COM VALIDACAO PARCIAL TABELA SAV1 MARCACOES DIRETO NO ESPELHO: 0578-HORA EXTRA - CAMPANHA COVID-19';


ELSE
dbms_output.put_line('--***************MESMO COM VALIDACAO PARCIAL DAS REGRAS TABELA SAV1 APENAS MARCACOES NO ESPELHO, AINDA ASSIM NAO GEROU REGISTRO, CONFERIR');
vLOG := vLOG||'-'||'--***************MESMO COM VALIDACAO PARCIAL DAS REGRAS TABELA SAV1 APENAS MARCACOES NO ESPELHO, AINDA ASSIM NAO GEROU REGISTRO, CONFERIR';
vCAMPO_4 := vCAMPO_4||'-'||'*MESMO COM VALIDACAO PARCIAL DAS REGRAS TABELA SAV1 APENAS MARCACOES NO ESPELHO, AINDA ASSIM NAO GEROU REGISTRO, CONFERIR';
--comentado 19/11/21 17h27 --
END IF;
--INICIO----NOVO EM 19/11/21 ----------------APENAS COM MARCACOES NO ESPELHO-----------------------------------------------------------------------------------------------------------------------------------------

---FIM------------------------------------------------------------------------------PARTE 3 DE TENTAR PAGAR SEM MARCACOES


END IF;--FIM-------------------------------------IF GERAL IMPORTANTE PARA FAZER A GRAVACAO DA SIT PONTO DA VERBA OU ABORTAR-----************************************************************************************************************

vCAMPO_5 := vQTD_LOCAIS_PODE_VERBA;
dbms_output.put_line('--vLOG: '||vLOG);
dbms_output.put_line('--vLOG_ERRO_REGRA_CARGO : '||vLOG_ERRO_REGRA_CARGO );
dbms_output.put_line('--vLOG_ERRO_REGRA_LOCAL_MARCA : '||vLOG_ERRO_REGRA_LOCAL_MARCA );
dbms_output.put_line('--vLOG_MARCACOES: '||vLOG_MARCACOES);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CAMPO_2, CONSIDERACOES
, CAMPO_3, CAMPO_4, CAMPO_5, CAMPO_6, CAMPO_7, CAMPO_8, CAMPO_9)
VALUES(C1.EMPRESA,C1.TIPO_CONTRATO,C1.MATRICULA, SYSDATE,'PRG11_CAMPANHA_VACINACAO', C1.DATA,
vLOG||'-'||vLOG_ERRO_REGRA_CARGO||'-'||vLOG_ERRO_REGRA_LOCAL_MARCA||'|'||vQTD_LOCAIS_PODE_VERBA||'|'||vCODIGO_ME_LOG||'|'||vCODIGO_MS_LOG||'|'||v1_LOCAL_PBH_MARCACAO_ENTRADA ||'|'||v1_LOCAL_PBH_MARCACAO_SAIDA  --vLOG_MARCACOES
, vCAMPO_3, vCAMPO_4, vCAMPO_5, vCAMPO_6, vCAMPO_7, vCAMPO_8, vCAMPO_9 );COMMIT;
--SELECT LENGTH(X.CONSIDERACOES)LARG_vLOG, X.* FROM SUGESP_AJUSTE_LOTE_CAMPO_HIST X WHERE TRUNC(DATA_DADOS) = TRUNC(SYSDATE) AND CAMPO_VALOR_1 IS NULL AND CAMPO_VALOR_2 IS NULL
--DELETE SUGESP_AJUSTE_LOTE_CAMPO_HIST X WHERE TRUNC(DATA_DADOS) = TRUNC(SYSDATE) AND CAMPO_VALOR_1 IS NULL AND CAMPO_VALOR_2 IS NULL
--SELECT LENGTH(X.CONSIDERACOES)LARG_vLOG, X.* FROM SUGESP_AJUSTE_LOTE_CAMPO_HIST X WHERE TRUNC(DATA_DADOS) = TRUNC(SYSDATE) AND CAMPO_VALOR_1 ='grava_3_tipos_sit_ponto_verba_SMSA' ORDER BY LENGTH(X.CONSIDERACOES)DESC
--SELECT X.CONSIDERACOES FROM SUGESP_AJUSTE_LOTE_CAMPO_HIST X WHERE TRUNC(DATA_DADOS) = TRUNC(SYSDATE) AND CAMPO_VALOR_1 ='grava_3_tipos_sit_ponto_verba_SMSA' ORDER BY LENGTH(X.CONSIDERACOES)DESC


vTIPO_DIA_CALENDARIO := NULL;
vCARGO_PODE_VERBA := NULL;
vTOTAL_MARCACOES_DIA :=0;
vMARCACAO_ATUAL  := NULL;
vCODIGOM_ATUAL := NULL;
vQTD_MARCACOES :=0;
vQTD_EVENTOS :=0;
vCODIGO_ME :=0;
vCODIGO_MS :=0;
vLOCAL_USAR := NULL;
vTIPO_DIA_PAGAR := 'T1';
vCHAVE_SAV1 := NULL;
vCHAVE_SAV1_PARCIAL := NULL;
vLOCAIS_PODE_VERBA := NULL;
vNUMERO := 0;
vSTRING := NULL;
vCHAVE_SAV1_FINAL := NULL;
vLOCAIS_PODE_VERBA_FINAL := NULL;
vLOG := NULL;
vLOG_MARCACOES := NULL;
vPODE_PAGAR_CHAVE_PARCIAL := 0;
vLOG_ERRO_REGRA_MARCACAO := NULL;
vLOG_ERRO_REGRA_CARGO := NULL;
vLOG_ERRO_REGRA_LOCAL_MARCA := NULL;
vORIGEM_MARCACAO := NULL;
vPAGA_1_MARCACAO_VALIDA := NULL;
vCODIGO_ME_LOG := NULL;
vCODIGO_MS_LOG := NULL;
vQTD_LOCAIS_PODE_VERBA :=0;

vCAMPO_3 := NULL;--PREVIA_PROCESSO
vCAMPO_4 := NULL;--RESULTADO_FINAL_PROCESSAMENTO
vCAMPO_5 := NULL;--vQTD_LOCAIS_PODE_VERBA
vCAMPO_6 := NULL;--ORIGEM_MARCACAO_ENTRADA
vCAMPO_7 := NULL;--EFETIVADO_ENTRADA
vCAMPO_8 := NULL;--ORIGEM_MARCACAO_SAIDA
vCAMPO_9 := NULL;--EFETIVADO_SAIDA

v1_LOCAL_PBH_MARCACAO_ENTRADA := NULL;
v1_LOCAL_PBH_MARCACAO_SAIDA := NULL;

dbms_output.put_line('-----------------------------------------------------------------------------------------------');

END LOOP;


END;

END;
