
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG16_P2_TOT_SIT_PONTO_ARTE" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN

--Kellysson novo em 21/5/21
----------------------*****************************************mudar datas
--novo em 21/5/21--- gravar dados da SIT PONTO do Arterh para comparar com o fechamento do Ifponto

DECLARE   
vCONTADOR NUMBER;
vDATA_INICIO DATE;
vDATA_FIM DATE;

BEGIN 
dbms_output.enable(null);

vCONTADOR := 0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

--so total da 0020-FALTA
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_FALTA)TOTAL_REF_FALTA, SUM(X2.QTD_DIAS_FALTA) QTD_DIAS_FALTA FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,F.total_referencia TOTAL_REF_FALTA,                         F.quant_dias QTD_DIAS_FALTA
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--so total da 0020-FALTA
select ROW_NUMBER() OVER (PARTITION BY D.codigo_empresa, D.tipo_contrato, D.codigo_contrato ORDER BY D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao) AS ORDEM_BM,
D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao, sum(D.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA D
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO S ON D.CODIGO_SITUACAO = S.CODIGO--NOVO EM 10/8/21
where trunc(D.data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
--COMENTADO EM 10/8/21--and D.codigo_situacao in('0020') 
AND S.tipo_referencia = 'D' AND S.tipo_situacao = 'F'--NOVO EM 10/8/21
AND S.CODIGO <> '0514'--ADICIONADO EM 10/11/22 PARA NÃO PEGAR DIAS DE GREVE
--and trunc(dt_ult_alter_usua) = to_date('11/05/2021','dd/mm/yyyy'  )--testes
group by D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao
order by D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao
)F ON F.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND F.TIPO_CONTRATO = X.TIPO_CONTRATO AND F.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000000337890'--TESTES'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_FALTA IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_FALTA_0020 = C1.TOTAL_REF_FALTA, QTD_DIAS_FALTA_0020 = C1.QTD_DIAS_FALTA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--so total da 0020-FALTA




--so total da 1015-ESTORNO DE FALTA
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_ESTORNO_FALTA)TOTAL_REF_ESTORNO_FALTA, SUM(X2.QTD_DIAS_ESTORNO_FALTA)QTD_DIAS_ESTORNO_FALTA FROM (
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,EF.total_referencia TOTAL_REF_ESTORNO_FALTA,               EF.quant_dias QTD_DIAS_ESTORNO_FALTA
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--so total da 1015-ESTORNO DE FALTA
select ROW_NUMBER() OVER (PARTITION BY D.codigo_empresa, D.tipo_contrato, D.codigo_contrato ORDER BY D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao) AS ORDEM_BM,
D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao, sum(D.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA D
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO S ON D.CODIGO_SITUACAO = S.CODIGO
where trunc(D.data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') and D.codigo_situacao in('1015') 
--and trunc(dt_ult_alter_usua) = to_date('11/05/2021','dd/mm/yyyy'  )--testes
group by D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao
order by D.codigo_empresa, D.tipo_contrato, D.codigo_contrato, D.codigo_situacao
)EF ON EF.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND EF.TIPO_CONTRATO = X.TIPO_CONTRATO AND EF.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_ESTORNO_FALTA IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_ESTORNO_FALTA_1015 = C1.TOTAL_REF_ESTORNO_FALTA, QTD_DIAS_ESTORNO_FALTA_1015 = C1.QTD_DIAS_ESTORNO_FALTA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--so total da 1015-ESTORNO DE FALTA




--so total da 1013-TOTAL HORAS DIFERENCIADAS PERÍODO
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_TOT_H_DIFERENCIADAS)TOTAL_REF_TOT_H_DIFERENCIADAS, SUM(X2.QTD_DIAS_TOT_H_DIFERENCIADAS)QTD_DIAS_TOT_H_DIFERENCIADAS FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,TD.total_referencia TOTAL_REF_TOT_H_DIFERENCIADAS,          TD.quant_dias QTD_DIAS_TOT_H_DIFERENCIADAS
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--so total da 1013-TOTAL HORAS DIFERENCIADAS PERÍODO
select ROW_NUMBER() OVER (PARTITION BY codigo_empresa, tipo_contrato, codigo_contrato ORDER BY codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao) AS ORDEM_BM,
codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao, sum(ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') and codigo_situacao in('1013') 
--and trunc(dt_ult_alter_usua) = to_date('11/05/2021','dd/mm/yyyy'  )--testes
group by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
order by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
)TD ON TD.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND TD.TIPO_CONTRATO = X.TIPO_CONTRATO AND TD.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_TOT_H_DIFERENCIADAS IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_TOT_H_DIF_PER_1013 = C1.TOTAL_REF_TOT_H_DIFERENCIADAS, QTD_DIAS_TOT_H_DIF_PER_1013 = C1.QTD_DIAS_TOT_H_DIFERENCIADAS WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--so total da 1013-TOTAL HORAS DIFERENCIADAS PERÍODO




--so total de 1204-ESTORNO TOTAL HORAS DIFERENCIADAS PERIOD
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_ESTORNO_TOT_H_DIF)TOTAL_REF_ESTORNO_TOT_H_DIF, SUM(X2.QTD_DIAS_ESTORNO_TOT_H_DIF)QTD_DIAS_ESTORNO_TOT_H_DIF FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,DC.total_referencia TOTAL_REF_ESTORNO_TOT_H_DIF,           DC.quant_dias QTD_DIAS_ESTORNO_TOT_H_DIF
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--so total de 1204-ESTORNO TOTAL HORAS DIFERENCIADAS PERIOD
select ROW_NUMBER() OVER (PARTITION BY codigo_empresa, tipo_contrato, codigo_contrato ORDER BY codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao) AS ORDEM_BM,
codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao, sum(ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') and codigo_situacao in('1204') 
--and trunc(dt_ult_alter_usua) = to_date('11/05/2021','dd/mm/yyyy'  )--testes
group by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
order by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
)DC ON DC.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND DC.TIPO_CONTRATO = X.TIPO_CONTRATO AND DC.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_ESTORNO_TOT_H_DIF IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_EST_TOT_H_DIF_1204 = C1.TOTAL_REF_ESTORNO_TOT_H_DIF, QTD_DIAS_EST_TOT_H_DIF_1204 = C1.QTD_DIAS_ESTORNO_TOT_H_DIF WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--so total de 1204-ESTORNO TOTAL HORAS DIFERENCIADAS PERIOD



--so total de 1004-FALTA COMPENSADA
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_FALTA_COMPENSADA)TOTAL_REF_FALTA_COMPENSADA, SUM(X2.QTD_DIAS_FALTA_COMPENSADA)QTD_DIAS_FALTA_COMPENSADA FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,FC.total_referencia TOTAL_REF_FALTA_COMPENSADA,             FC.quant_dias QTD_DIAS_FALTA_COMPENSADA
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--so total de 1004-FALTA COMPENSADA
select ROW_NUMBER() OVER (PARTITION BY codigo_empresa, tipo_contrato, codigo_contrato ORDER BY codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao) AS ORDEM_BM,
codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao, sum(ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') and codigo_situacao in('1004') 
--and trunc(dt_ult_alter_usua) = to_date('11/05/2021','dd/mm/yyyy'  )--testes
group by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
order by codigo_empresa, tipo_contrato, codigo_contrato, codigo_situacao
)FC ON FC.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND FC.TIPO_CONTRATO = X.TIPO_CONTRATO AND FC.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_FALTA_COMPENSADA IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_FALTA_COMPENS_1004 = C1.TOTAL_REF_FALTA_COMPENSADA, QTD_DIAS_FALTA_COMPENS_1004 = C1.QTD_DIAS_FALTA_COMPENSADA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--so total de 1004-FALTA COMPENSADA



--HORAS DIFERENCIADAS E PROGRAMACOES DE HORAS 
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_FALTA_EM_HORAS)TOTAL_REF_FALTA_EM_HORAS, SUM(X2.QTD_DIAS_FALTA_EM_HORAS)QTD_DIAS_FALTA_EM_HORAS FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,FH.total_referencia TOTAL_REF_FALTA_EM_HORAS,              FH.quant_dias QTD_DIAS_FALTA_EM_HORAS
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--HORAS DIFERENCIADAS E PROGRAMACOES DE HORAS 
select 
d.codigo_empresa, d.tipo_contrato, d.codigo_contrato,
s.tipo_referencia, s.tipo_situacao,
sum(d.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA d
left outer join ARTERH.RHPONT_SITUACAO s on s.codigo = d.codigo_situacao
where trunc(d.data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
and (d.codigo_situacao not in('1013','1015','1004','1204','0569') --TIRANDO A PARTE DE FALTAS/TOT HORA DIF PERIODO E SUAS COMPENSACOES E ESTORNOS --EM 10/11/22 ADICIONADO CODIGO 0569-PARALIZACAO
or ( S.tipo_referencia <> 'D' AND S.tipo_situacao <> 'F'))--NOVO EM 10/8/21
and s.tipo_situacao = 'F' and s.tipo_referencia = 'H' 
group by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_situacao,s.tipo_referencia
order by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_referencia, s.tipo_situacao
)FH ON FH.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND FH.TIPO_CONTRATO = X.TIPO_CONTRATO AND FH.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_FALTA_EM_HORAS IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_FALTA_EM_HORAS = C1.TOTAL_REF_FALTA_EM_HORAS, QTD_DIAS_FALTA_EM_HORAS = C1.QTD_DIAS_FALTA_EM_HORAS WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--HORAS DIFERENCIADAS E PROGRAMACOES DE HORAS 



--HORAS NORMAIS EM HORAS 
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_HORAS_NORMAIS_HORAS)TOTAL_REF_HORAS_NORMAIS_HORAS, SUM(X2.QTD_DIAS_HORAS_NORMAIS_HORAS)QTD_DIAS_HORAS_NORMAIS_HORAS FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,NH.total_referencia 
TOTAL_REF_HORAS_NORMAIS_HORAS, 
NH.quant_dias 
QTD_DIAS_HORAS_NORMAIS_HORAS
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X
FULL OUTER JOIN (
--HORAS NORMAIS EM HORAS 
select 
d.codigo_empresa, d.tipo_contrato, d.codigo_contrato,
s.tipo_referencia, s.tipo_situacao,
sum(d.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA d
left outer join ARTERH.RHPONT_SITUACAO s on s.codigo = d.codigo_situacao
where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
and (codigo_situacao not in('1013','1015','1004','1204','0569') --TIRANDO A PARTE DE FALTAS/TOT HORA DIF PERIODO E SUAS COMPENSACOES E ESTORNOS --EM 10/11/22 ADICIONADO CODIGO 0569-PARALIZACAO
or ( S.tipo_referencia <> 'D' AND S.tipo_situacao <> 'F'))--NOVO EM 10/8/21
and s.tipo_situacao = 'N' and s.tipo_referencia = 'H' 
group by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_situacao,s.tipo_referencia
order by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_referencia, s.tipo_situacao
)NH ON NH.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND NH.TIPO_CONTRATO = X.TIPO_CONTRATO AND NH.CODIGO_CONTRATO = X.CODIGO_CONTRATO
 WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_HORAS_NORMAIS_HORAS IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_HORA_NORMAL_EM_HORA = C1.TOTAL_REF_HORAS_NORMAIS_HORAS, QTD_DIAS_HORA_NORMAL_EM_HORA = C1.QTD_DIAS_HORAS_NORMAIS_HORAS WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--HORAS NORMAIS EM HORAS 



--CESSAO E TELETRABALHO EM DIA 
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_CESSAO_TELETRABALHO)TOTAL_REF_CESSAO_TELETRABALHO, SUM(X2.QTD_DIAS_CESSAO_TELETRABALHO)QTD_DIAS_CESSAO_TELETRABALHO FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,CT.total_referencia TOTAL_REF_CESSAO_TELETRABALHO, CT.quant_dias QTD_DIAS_CESSAO_TELETRABALHO
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--CESSAO E TELETRABALHO EM DIA 
select 
d.codigo_empresa, d.tipo_contrato, d.codigo_contrato,
s.tipo_referencia, s.tipo_situacao,
sum(d.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA d
left outer join ARTERH.RHPONT_SITUACAO s on s.codigo = d.codigo_situacao
where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
and (codigo_situacao not in('1013','1015','1004','1204','0569') --TIRANDO A PARTE DE FALTAS/TOT HORA DIF PERIODO E SUAS COMPENSACOES E ESTORNOS--EM 10/11/22 ADICIONADO CODIGO 0569-PARALIZACAO
or ( S.tipo_referencia <> 'D' AND S.tipo_situacao <> 'F'))--NOVO EM 10/8/21
and s.tipo_situacao = 'N' and s.tipo_referencia = 'D' 
group by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_situacao,s.tipo_referencia
order by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_referencia, s.tipo_situacao
)CT ON CT.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND CT.TIPO_CONTRATO = X.TIPO_CONTRATO AND CT.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_CESSAO_TELETRABALHO IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_CESSAO_TELETRABALHO = C1.TOTAL_REF_CESSAO_TELETRABALHO, QTD_DIAS_CESSAO_TELETRABALHO = C1.QTD_DIAS_CESSAO_TELETRABALHO WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--CESSAO E TELETRABALHO EM DIA 




--AUSENCIAS ABONAS EM DIAS 
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_AUSENCIA_ABONAD_DIA)TOTAL_REF_AUSENCIA_ABONAD_DIA, SUM(X2.QTD_DIAS_AUSENCIA_ABONADA_DIA)QTD_DIAS_AUSENCIA_ABONADA_DIA FROM (
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,AD.total_referencia 
TOTAL_REF_AUSENCIA_ABONAD_DIA, 
AD.quant_dias 
QTD_DIAS_AUSENCIA_ABONADA_DIA
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--AUSENCIAS ABONAS EM DIAS 
select 
d.codigo_empresa, d.tipo_contrato, d.codigo_contrato,
s.tipo_referencia, s.tipo_situacao,
sum(d.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA d
left outer join ARTERH.RHPONT_SITUACAO s on s.codigo = d.codigo_situacao
where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
and (codigo_situacao not in('1013','1015','1004','1204','0569') --TIRANDO A PARTE DE FALTAS/TOT HORA DIF PERIODO E SUAS COMPENSACOES E ESTORNOS--EM 10/11/22 ADICIONADO CODIGO 0569-PARALIZACAO
or ( S.tipo_referencia <> 'D' AND S.tipo_situacao <> 'F'))--NOVO EM 10/8/21
and s.tipo_situacao IN ('I','P') and s.tipo_referencia = 'D' 
group by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_situacao,s.tipo_referencia
order by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_referencia, s.tipo_situacao
)AD ON AD.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND AD.TIPO_CONTRATO = X.TIPO_CONTRATO AND AD.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO); 
IF C1.TOTAL_REF_AUSENCIA_ABONAD_DIA IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_AUSENC_ABONA_EM_DIA = C1.TOTAL_REF_AUSENCIA_ABONAD_DIA, QTD_DIAS_AUSENC_ABONA_EM_DIA = C1.QTD_DIAS_AUSENCIA_ABONADA_DIA WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--AUSENCIAS ABONAS EM DIAS 




--AUSENCIAS ABONAS EM HORAS
FOR C1 IN (
SELECT X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO, SUM(X2.TOTAL_REF_AUSENCI_ABONA_HORAS) TOTAL_REF_AUSENCI_ABONA_HORAS, SUM(X2.QTD_DIAS_AUSENCIA_ABONA_HORAS)QTD_DIAS_AUSENCIA_ABONA_HORAS FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO
,AH.total_referencia 
TOTAL_REF_AUSENCI_ABONA_HORAS, 
AH.quant_dias 
QTD_DIAS_AUSENCIA_ABONA_HORAS
FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE X 
FULL OUTER JOIN (
--AUSENCIAS ABONAS EM HORAS
select 
d.codigo_empresa, d.tipo_contrato, d.codigo_contrato,
s.tipo_referencia, s.tipo_situacao,
sum(d.ref_horas)total_referencia, count(1)quant_dias 
from ARTERH.RHPONT_RES_SIT_DIA d
left outer join ARTERH.RHPONT_SITUACAO s on s.codigo = d.codigo_situacao
where trunc(data)between to_date(vDATA_INICIO,'dd/mm/yyyy')and to_date(vDATA_FIM,'dd/mm/yyyy') 
and (codigo_situacao not in('1013','1015','1004','1204','0569') --TIRANDO A PARTE DE FALTAS/TOT HORA DIF PERIODO E SUAS COMPENSACOES E ESTORNOS --EM 10/11/22 ADICIONADO CODIGO 0569-PARALIZACAO
or ( S.tipo_referencia <> 'D' AND S.tipo_situacao <> 'F'))--NOVO EM 10/8/21
and s.tipo_situacao IN ('I','P') and s.tipo_referencia = 'H' 
group by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_situacao,s.tipo_referencia
--order by d.codigo_empresa, d.tipo_contrato, d.codigo_contrato, s.tipo_referencia, s.tipo_situacao
)AH ON AH.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND AH.TIPO_CONTRATO = X.TIPO_CONTRATO AND AH.CODIGO_CONTRATO = X.CODIGO_CONTRATO
WHERE TRUNC(X.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)
--AND X.CODIGO_CONTRATO = '000000001209149'
)X2 GROUP BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO ORDER BY X2.CODIGO_EMPRESA, X2.TIPO_CONTRATO, X2.CODIGO_CONTRATO
)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||'- BM: '||C1.CODIGO_CONTRATO);
IF C1.TOTAL_REF_AUSENCI_ABONA_HORAS IS NOT NULL THEN
UPDATE ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE SET TOTAL_REF_AUSENC_ABONA_EM_HORA = C1.TOTAL_REF_AUSENCI_ABONA_HORAS, QTD_DIAS_AUSENC_ABONA_EM_HORA = C1.QTD_DIAS_AUSENCIA_ABONA_HORAS WHERE CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE);COMMIT; 
END IF;
END LOOP;
--AUSENCIAS ABONAS EM HORAS





END;

END;