
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG15_P1_TOT_SIT_PONTO_ARTE" (DATA_INICIO IN DATE, DATA_FIM IN DATE)AS
BEGIN
--Kellysson novo em 21/5/21
----------------------*****************************************mudar datas
--novo em 21/5/21--- gravar dados da SIT PONTO do Arterh para comparar com o fechamento do Ifponto

DECLARE   
vCONTADOR NUMBER;
vDATA_INICIO DATE;
vDATA_FIM DATE;

BEGIN 
dbms_output.enable(null);
vCONTADOR := 0;

vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;


FOR C1 IN (

SELECT X4.* FROM (
SELECT X2.* 
,B.NOME,SF.CODIGO COD_SIT_FUNC, SF.DESCRICAO SITUACAO_FUNCIONAL
,E.CODIGO COD_CARGO_EFETIVO, E.DESCRICAO CARGO_EFETIVO, C.CODIGO COD_CARGO_COMISSAO, C.DESCRICAO CARGO_COMISSAO, F.CODIGO COD_FUCNCAO, F.DESCRICAO FUNCAO
, GN.COD_CGERENC1, GN.COD_CGERENC2, GN.COD_CGERENC3, GN.COD_CGERENC4, GN.COD_CGERENC5, GN.COD_CGERENC6, GN.DESCRICAO LOCAL
,B.CODIGO_ESCALA, TJ.C_LIVRE_SELEC01 QTD_TOTAL_MINUTOS, TJ.C_LIVRE_DESCR02 TOTAL_CARGA_HORARIA
FROM(
SELECT X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO, X.ORDEM_BM, X.CODIGO_SITUACAO, X.TOTAL_REFERENCIA, X.QUANT_DIAS,
LEAD(X.ORDEM_BM, 1,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS PROXIMA_ORDEM_BM,
LEAD(X.CODIGO_SITUACAO, 1,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS PROXIMO_CODIGO_SITUACAO,
LEAD(X.TOTAL_REFERENCIA, 1,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS PROXIMO_TOTAL_REFERENCIA,
LEAD(X.QUANT_DIAS, 1,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS PROXIMO_QUANT_DIAS
/*,LEAD(X.ORDEM_BM, 2,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS ORDEM_BM_1015,
LEAD(X.CODIGO_SITUACAO, 2,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS CODIGO_SITUACAO_1015,
LEAD(X.TOTAL_REFERENCIA, 2,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS TOTAL_REFERENCIA_1015,
LEAD(X.QUANT_DIAS, 2,NULL) OVER (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO_CONTRATO ORDER BY X.ORDEM_BM ) AS QUANT_DIAS_1015*/
FROM(
SELECT ROW_NUMBER() OVER (PARTITION BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO ORDER BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CODIGO_SITUACAO) AS ORDEM_BM,
CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CODIGO_SITUACAO, SUM(REF_HORAS)TOTAL_REFERENCIA, COUNT(1)QUANT_DIAS 
FROM ARTERH.RHPONT_RES_SIT_DIA WHERE TRUNC(DATA)BETWEEN TO_DATE(VDATA_INICIO,'DD/MM/YYYY')AND TO_DATE(VDATA_FIM,'DD/MM/YYYY')----------------------*****************************************MUDAR DATAS
-- AND CODIGO_SITUACAO IN('0020','1013') 
GROUP BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CODIGO_SITUACAO
ORDER BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CODIGO_SITUACAO
)X 
)X2 
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B ON B.CODIGO_EMPRESA = X2.CODIGO_EMPRESA AND B.TIPO_CONTRATO = X2.TIPO_CONTRATO AND B.CODIGO = X2.CODIGO_CONTRATO
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON B.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND B.COD_CUSTO_GERENC1 = GN.COD_CGERENC1 AND B.COD_CUSTO_GERENC2 = GN.COD_CGERENC2 AND B.COD_CUSTO_GERENC3 = GN.COD_CGERENC3
AND B.COD_CUSTO_GERENC4 = GN.COD_CGERENC4 AND B.COD_CUSTO_GERENC5 = GN.COD_CGERENC5 AND B.COD_CUSTO_GERENC6 = GN.COD_CGERENC6
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO =  B.SITUACAO_FUNCIONAL 
LEFT OUTER JOIN ARTERH.RHPLCS_FUNCAO F ON F.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND F.CODIGO = B.CODIGO_FUNCAO
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO C ON C.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND C.CODIGO = B.COD_CARGO_COMISS
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO E ON E.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND E.CODIGO = B.COD_CARGO_EFETIVO
LEFT OUTER JOIN ARTERH.RHPONT_ESCALA ES ON ES.CODIGO_EMPRESA = B.CODIGO_EMPRESA  AND ES.CODIGO = B.CODIGO_ESCALA
LEFT OUTER JOIN ARTERH.RHPONT_TP_JORNADA TJ ON TJ. CODIGO = ES.TIPO_JORNADA
WHERE
X2.ORDEM_BM = 1
AND B.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO AND AUX.CODIGO = B.CODIGO)
--NOVO X4. DEVIDO AO FECHAMENTO COMPLEMENTAR PARA PEGAR APENAS O QUE AINDA ESTA NA SELECT COUNT(1) FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA WHERE DATA_PROCESSAMENTO IS NULL
)X4
LEFT OUTER JOIN (SELECT EMPRESA, TIPO_CONTRATO, MATRICULA, COUNT(1)QTD_DIAS FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA WHERE DATA_PROCESSAMENTO IS NULL 
AND LPAD(EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
GROUP BY EMPRESA, TIPO_CONTRATO, MATRICULA)H
ON H.EMPRESA = X4.CODIGO_EMPRESA AND H.TIPO_CONTRATO = X4.TIPO_CONTRATO AND H.MATRICULA = X4.CODIGO_CONTRATO
WHERE H.EMPRESA IS NOT NULL--APENAS O QUE ESTA NA HISTORICA

)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR);
INSERT INTO ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE
      (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, NOME, COD_SIT_FUNC, SITUACAO_FUNCIONAL, COD_CARGO_EFETIVO, CARGO_EFETIVO, COD_CARGO_COMISSAO, CARGO_COMISSAO, COD_FUCNCAO, FUNCAO, COD_CGERENC1, COD_CGERENC2, COD_CGERENC3, COD_CGERENC4, COD_CGERENC5, COD_CGERENC6, CUSTO_GERENCIAL, DATA_PROCESSAMENTO, CODIGO_ESCALA, QTD_TOTAL_MINUTOS_TIPO_JORNAD, CARGA_HORARIA_TIPO_JORNADA)
VALUES(C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO_CONTRATO, C1.NOME, C1.COD_SIT_FUNC, C1.SITUACAO_FUNCIONAL, C1.COD_CARGO_EFETIVO, C1.CARGO_EFETIVO, C1.COD_CARGO_COMISSAO, C1.CARGO_COMISSAO, C1.COD_FUCNCAO, C1.FUNCAO, C1.COD_CGERENC1, C1.COD_CGERENC2, C1.COD_CGERENC3, C1.COD_CGERENC4, C1.COD_CGERENC5, C1.COD_CGERENC6, C1.LOCAL ,SYSDATE, C1.CODIGO_ESCALA, C1.QTD_TOTAL_MINUTOS, C1.TOTAL_CARGA_HORARIA);COMMIT;

END LOOP;

END;

END;
