
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG4_SIT_FUNC_OCORRENCIA" (DATA_INICIO IN DATE, DATA_FIM IN DATE)
AS
BEGIN

--V3 em 14/2/22 - para melhorar e tirar registros de LMP/LMDP antes da data de admissão e/ou apos data de desligamento
--Kellysson em 4/1/21 v1 para começar com o processo de informar o FALECIMENTO diariamente mas podera ser usado para as demais ocorrencia
--Kellysson em 9/7/21 v2 para trocar a tabela origem dos dados DE: PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_TR PARA: PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2
--*************************************ALTERAR DATAS********************** 1 LOCAL DATA INICIO, 3 LOCAIS DATA FIM
DECLARE 
vDATA_INICIO DATE;
vDATA_FIM DATE;

vCONTADOR NUMBER (10);
vCONTADOR2 NUMBER (10);
data_inicial date;
data_final date; 
num_dias number;
vDATA_DIA DATE;

vCOD_ULT_SIT_FUNC VARCHAR2 (4 BYTE);
vULT_SIT_FUNC VARCHAR2 (100 BYTE);
vCONTROLE_FOLHA_ULT_SIT_FUNC VARCHAR2 (4 BYTE);
vDT_INICIO_ULT_SIT_FUNC DATE;
vDT_FIM_ULT_SIT_FUNC DATE;
vQTD_SIT_FUNC_DIFERE_NORMAL NUMBER;

V_ULT_SIT_FUNC0_ATIVA VARCHAR2 (4 BYTE);
vLOG VARCHAR2 (4000 BYTE);
V_SIT_FUNC_ATIVA_VINCULO VARCHAR2 (4 BYTE);

err_msg VARCHAR2(4000 BYTE);

begin
dbms_output.enable(null);

vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

vCONTADOR :=0;
vCONTADOR2 :=0;
data_inicial := NULL ;
data_final := NULL;
num_dias :=0;
vDATA_DIA := NULL;

vCOD_ULT_SIT_FUNC := NULL;
vULT_SIT_FUNC := NULL;
vCONTROLE_FOLHA_ULT_SIT_FUNC := NULL;
vDT_INICIO_ULT_SIT_FUNC := NULL;
vDT_FIM_ULT_SIT_FUNC := NULL;
vQTD_SIT_FUNC_DIFERE_NORMAL := 0;

V_ULT_SIT_FUNC0_ATIVA := NULL;
vLOG := NULL;
V_SIT_FUNC_ATIVA_VINCULO := NULL;

err_msg := NULL ;

--CABECALHO DO LOG
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES)
VALUES(NULL,NULL,NULL, SYSDATE,'PRG4_SIT_FUNC_OCORRENCIA',
'vCONTADOR|C1.EMPRESA|C1.TIPO_CONTRATO|C1.MATRICULA|C1.NOME|C1.COD_SIT_FUNC_OCORR|C1.SIT_FUNCIONAL_OCORR|C1.DTINICIO|C1.DTFIM|C1.COD_SIT_FUNC_CONTR|C1.SITUACAO_FUNCIONAL_CONTR|C1.DATA_ADMISSAO|DATA_RESCISAO|C1.SIT_FUNC_MESMA_DT_INICIO|C1.DATA_INIC_SITUACAO|C1.DATA_FIM_SITUACAO|C1.LOGIN_USUARIO|C1.DT_ULT_ALTER_USUA|C2.COD_SIT_FUNCIONAL|C2.DATA_INIC_SITUACAO|C2.DATA_FIM_SITUACAO|C2.LOGIN_USUARIO|C2.DT_ULT_ALTER_USUA|STATUS|CENARIO|'
);COMMIT;


for C1 in(


SELECT SFA.COD_SIT_FUNCIONAL ULT_SIT_FUNC_ATIVA,
CASE WHEN CS.DADO_ORIGEM IS NULL THEN 'NAO' ELSE 'SIM' END ESTA_CESSAO,
A.COD_SIT_FUNCIONAL SIT_FUNC_MESMA_DT_INICIO, A.DATA_INIC_SITUACAO, A.DATA_FIM_SITUACAO, A.LOGIN_USUARIO, A.DT_ULT_ALTER_USUA, A.TEXTO_ASSOCIADO,
CASE WHEN TRUNC(X3.DATA_PROCESSAMENTO) = TRUNC(SYSDATE) THEN 'PROCESSADO' 
WHEN TRUNC(X3.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)-1 THEN 'ERRO_VERIFICAR_NAO_PROCESSADO' 
ELSE 'NAO_PROCESSADO' END STATUS, 
X3.* FROM(
SELECT 
CASE WHEN TRUNC(X2.DTINICIO) > TRUNC(X2.DTFIM) THEN 'ERRO' ELSE 'OK' END STATUS_DATA_INICIO_FIM,
X2.* 
--X2.SIT_PONTO, X2.OCORRENCIA, X2.POSSUI_SIT_FUNC_ASSOCIADA, X2.TIPO_SIT_PONTO_ARTERH, COUNT(1)QUANT

FROM (
--ANALISE PREVIA DAS OCORRENCIAS
SELECT 
--SF_OCORR_QTD.QUANT QTD_SIT_FUNC, 
SF_OCORR.CODIGO COD_SIT_FUNC_OCORR, SF_OCORR.DESCRICAO SIT_FUNCIONAL_OCORR, SF_OCORR.CONTROLE_FOLHA CONTROLE_FOLHA_OCORR, 
SF_OCORR.E_AFASTAMENTO E_AFASTAMENTO_OCORR, SF_OCORR.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_OCORR,
CASE WHEN C.c_livre_selec01 = 0 THEN 'NAO' ELSE 'SIM' END FOLHA_ESPECIAL, b.registro_ponto, SP.tipo_referencia,
X.*
,B.NOME, b.vinculo cod_vinculo, v.descricao vinculo, SF_CONTR.CODIGO COD_SIT_FUNC_CONTR, SF_CONTR.DESCRICAO SITUACAO_FUNCIONAL_CONTR, 
B.DATA_ADMISSAO, B.DATA_RESCISAO,  SF_CONTR.CONTROLE_FOLHA CONTROLE_FOLHA_CONTR, SF_CONTR.E_AFASTAMENTO E_AFASTAMENTO_CONTR, SF_CONTR.SUSPENDE_REMUNERA SUSPENDE_REMUNERA_CONTR, B.data_inic_afast, B.data_fim_afast,
GN.cod_cgerenc1, GN.cod_cgerenc2, GN.cod_cgerenc3, GN.cod_cgerenc4, GN.cod_cgerenc5, GN.cod_cgerenc6, GN.DESCRICAO LOCAL, 
b.cod_cargo_efetivo, E.DESCRICAO CARGO_EFETIVO, b.cod_cargo_comiss, C.DESCRICAO CARGO_COMISSIONADO, b.codigo_funcao, F.DESCRICAO FUNCAO
 --X.SIT_PONTO, X.OCORRENCIA, X.POSSUI_SIT_FUNC_ASSOCIADA, X.TIPO_SIT_PONTO_ARTERH, COUNT(1)QUANT
FROM (
--INICIO----------------NUCLEO REGISTROS IFPONTO
SELECT O2.* FROM(
select --O.*
O.DATA_PROCESSAMENTO,
O.CODIGO, O.EMPRESA, O.TIPO_CONTRATO, O.MATRICULA
,SF.QUANT_SIT_FUNC --SF.CODIGO COD_SIT_FUNC, SF.DESCRICAO SIT_FUNCIONAL, SF.CONTROLE_FOLHA, SF.E_AFASTAMENTO, SF.SUSPENDE_REMUNERA,
,O.SIT_PONTO, O.SITUACAO OCORRENCIA,  O.DTINICIO, O.DTFIM, 
CASE WHEN TRUNC(O.DTFIM) > TO_DATE(vDATA_FIM,'DD/MM/YYYY')---------------NOVO EM 10/6/21*************************************ALTERAR DATAS************************************
THEN TO_DATE(vDATA_FIM,'DD/MM/YYYY')---------------NOVO EM 10/6/21*************************************ALTERAR DATAS************************************
ELSE O.DTFIM
END DTFIM_USAR,
SP.CODIGO COD_SIT_PONTO, SP.DESCRICAO SITUACAO_PONTO
,CASE WHEN SF.SITUACAO_PONTO IS NULL THEN 'NAO' ELSE 'SIM' END POSSUI_SIT_FUNC_ASSOCIADA
, CASE WHEN (SP.c_livre_selec01) = 1 THEN 'JUSTIFICATIVA' WHEN  (SP.c_livre_selec01) = 2 THEN 'OCORRENCIA' WHEN (SP.c_livre_selec01) =  9 THEN 'TOTALIZADOR' ELSE 'VERIFICAR' END TIPO_SIT_PONTO_ARTERH
from PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2 O 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON O.SIT_PONTO = SP.CODIGO
LEFT OUTER JOIN 
(SELECT SITUACAO_PONTO, COUNT(1)QUANT_SIT_FUNC--, CODIGO, DESCRICAO, CONTROLE_FOLHA, E_AFASTAMENTO, SUSPENDE_REMUNERA 
  FROM ARTERH.RHPARM_SIT_FUNC WHERE DATA_FIM_VIGENCIA IS NULL AND SITUACAO_PONTO IS NOT NULL GROUP BY SITUACAO_PONTO ORDER BY SITUACAO_PONTO) SF
ON SF.SITUACAO_PONTO = O.SIT_PONTO
WHERE 
--comentado para testes em 14/2/22 --
O.DATA_PROCESSAMENTO IS NULL AND --testes 25/11/21
(TRUNC(O.DTAPAGOU) = TO_DATE('01/01/1970','DD/MM/YYYY') OR O.DTAPAGOU IS NULL)
AND O.LOGIN_APROVACAO IS NOT NULL
AND O.LOGIN_CADASTRO <> 'Integração'--NOVO EM 25/6/20
ORDER BY O.EMPRESA, O.TIPO_CONTRATO, O.MATRICULA, O.DTINICIO 
)O2 
WHERE O2.QUANT_SIT_FUNC = 1 --TRAVA PARA USAR APENAS SIT PONTO QUE ESTA ASSOCIADA A UMA UNICA SIT FUNC
--FIM----------------NUCLEO REGISTROS IFPONTO
)X 
--GROUP BY  X.SIT_PONTO, X.OCORRENCIA, X.POSSUI_SIT_FUNC_ASSOCIADA, X.TIPO_SIT_PONTO_ARTERH ORDER BY COUNT(1)DESC

--inicio para o COVID
left outer join ARTERH.RHPESS_CONTRATO B on X.EMPRESA = B.CODIGO_EMPRESA AND X.TIPO_CONTRATO = B.TIPO_CONTRATO AND X.MATRICULA = B.CODIGO
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF_CONTR ON SF_CONTR.CODIGO =  B.SITUACAO_FUNCIONAL 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON LPAD(X.SIT_PONTO, 4,0) = SP.CODIGO 
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF_OCORR ON SF_OCORR.SITUACAO_PONTO = SP.CODIGO AND SF_OCORR.DATA_FIM_VIGENCIA IS NULL
--LEFT OUTER JOIN (SELECT SITUACAO_PONTO, COUNT(1)QUANT FROM ARTERH.RHPARM_SIT_FUNC WHERE SITUACAO_PONTO IS NOT NULL AND DATA_FIM_VIGENCIA IS NULL GROUP BY SITUACAO_PONTO HAVING COUNT(1)= 1)SF_OCORR_QTD ON SF_OCORR.SITUACAO_PONTO =  SP.CODIGO
left outer join ARTERH.RHTABS_VINCULO_EMP v on v.codigo = b.vinculo
left outer join ARTERH.RHPLCS_FUNCAO F ON F.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND F.CODIGO = b.codigo_funcao
left outer join ARTERH.RHPLCS_CARGO C ON c.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND c.CODIGO = b.cod_cargo_comiss
left outer join ARTERH.RHPLCS_CARGO E ON e.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND e.CODIGO = b.cod_cargo_efetivo
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON B.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND b.COD_CUSTO_GERENC1 = GN.cod_cgerenc1 AND b.COD_CUSTO_GERENC2 = GN.cod_cgerenc2 AND b.COD_CUSTO_GERENC3 = GN.cod_cgerenc3
AND b.COD_CUSTO_GERENC4 = GN.cod_cgerenc4 AND b.COD_CUSTO_GERENC5 = GN.cod_cgerenc5 AND b.COD_CUSTO_GERENC6 = GN.cod_cgerenc6

WHERE  
--X.OCORRENCIA LIKE '%COVID-19%' AND --somente covid-19
--comentado para testes em 14/2/22 --b.vinculo <> '0009' and--E.DESCRICAO NOT LIKE '%ESTAGIÁRIO%' --tirando estagiarios
--and 
b.ano_mes_referencia = (select max(a.ano_mes_referencia) from ARTERH.RHPESS_CONTRATO a where a.codigo_empresa = b.codigo_empresa and a.tipo_contrato = b.tipo_contrato and a.codigo = b.codigo)
--FIM para o COVID

--COMENTADO EM 11/12/21--AND E.DESCRICAO NOT LIKE '%GUARDA%' --TIRANDO OS GUARDAS MUNICIPAIS EM 31/8/20
)X2
WHERE-- comentado em 17/8/20--X2.COD_VINCULO <> '0009' AND 
--comentado para testes em 14/2/22 --X2.FOLHA_ESPECIAL = 'NAO' 
--comentado para testes em 14/2/22 --AND X2.REGISTRO_PONTO NOT IN ('0110','0120','0150','0160')--TIRAR ESTAGIARIOS, PESSOAS FOLHA ESPECIAL E NÂO USAR IFPONTO
--comentado para testes em 14/2/22 --and X2.OCORRENCIA not LIKE '%COVID-19%' --tirar covid-19
--comentado para testes em 14/2/22 --AND 
TRUNC(X2.DTINICIO) BETWEEN TO_DATE(vDATA_INICIO,'DD/MM/YYYY') AND TO_DATE(vDATA_FIM,'DD/MM/YYYY')--NOVO EM 10/9/20 *************************************ALTERAR DATAS**********************
--GROUP BY  X2.SIT_PONTO, X2.OCORRENCIA, X2.POSSUI_SIT_FUNC_ASSOCIADA, X2.TIPO_SIT_PONTO_ARTERH ORDER BY COUNT(1)DESC
ORDER BY X2.SIT_PONTO, X2.EMPRESA, X2.TIPO_CONTRATO, X2.MATRICULA, X2.DTINICIO

)X3
LEFT OUTER JOIN ARTERH.RHCGED_ALT_SIT_FUN A ON A.CODIGO_EMPRESA = X3.EMPRESA AND A.TIPO_CONTRATO = X3.TIPO_CONTRATO AND A.CODIGO = X3.MATRICULA AND TRUNC(A.DATA_INIC_SITUACAO) = TRUNC(X3.DTINICIO) --NOVO EM 17/2/22
LEFT OUTER JOIN (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'CESS')CS ON CS.DADO_ORIGEM = X3.COD_SIT_FUNC_CONTR
LEFT OUTER JOIN
(
select A.*
from ARTERH.RHCGED_ALT_SIT_FUN A
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE
A.DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO)FROM RHCGED_ALT_SIT_FUN AUX
                                 LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SX ON SX.CODIGO = AUX.COD_SIT_FUNCIONAL
                                WHERE  A.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND A.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND A.CODIGO = AUX.CODIGO
                                AND (
                                  (SX.CONTROLE_FOLHA = 'N' and SX.E_AFASTAMENTO = 'N' and SX.suspende_remunera = 'N' AND SX.C_LIVRE_SELEC02 = '2') 
                                  /*OR (SX.CONTROLE_FOLHA = 'A' and SX.E_AFASTAMENTO = 'N' and SX.suspende_remunera = 'S' AND SX.C_LIVRE_SELEC02 = '0') */
                                  )
)
AND 
(
(S.CONTROLE_FOLHA = 'N' and S.E_AFASTAMENTO = 'N' and S.suspende_remunera = 'N' AND S.C_LIVRE_SELEC02 = '2')
/*OR (S.CONTROLE_FOLHA = 'A' and S.E_AFASTAMENTO = 'N' and S.suspende_remunera = 'S' AND S.C_LIVRE_SELEC02 = '0')*/
)
)SFA ON  SFA.CODIGO_EMPRESA = X3.EMPRESA AND SFA.TIPO_CONTRATO = X3.TIPO_CONTRATO AND SFA.CODIGO = X3.MATRICULA --AND trunc(SFA.DATA_INIC_SITUACAO) <= TRUNC(X3.DTINICIO)--ADICIONEI SINAL DE IGUAL EM 18/2/22


--comentado para testes em 14/2/22 --WHERE X3.STATUS_DATA_INICIO_FIM = 'OK'
--comentado para testes em 14/2/22 --AND X3.EMPRESA = '0001'--novo em 11/11/21

--where x3.matricula = '000000001310338' --testes 25/11/21

--inicio----parte para particionar os registros
--WHERE X3.COD_SIT_FUNC_OCORR  = '1221' AND X3.TIPO_CONTRATO <> '0211'--1221 REG
--WHERE X3.COD_SIT_FUNC_OCORR  = '1221' AND X3.TIPO_CONTRATO <> '0211' AND TRUNC(X3.DTINICIO) <= TO_DATE('14/02/2022','DD/MM/YYYY')--651 REG
--WHERE X3.COD_SIT_FUNC_OCORR  = '1221' AND X3.TIPO_CONTRATO <> '0211' AND TRUNC(X3.DTINICIO) > TO_DATE('14/02/2022','DD/MM/YYYY')--570 REG

--WHERE X3.COD_SIT_FUNC_OCORR  = '1221' AND X3.TIPO_CONTRATO = '0211' --485 REG
--WHERE X3.COD_SIT_FUNC_OCORR  = '1220' AND X3.TIPO_CONTRATO <> '0211'-- 541 REG
--WHERE X3.COD_SIT_FUNC_OCORR  = '1220' AND X3.TIPO_CONTRATO = '0211' --299 REG
--fim----parte para particionar os registros

--AND X3.MATRICULA IN ('00000000028942X','000000000305247')--TESTE

ORDER BY  X3.EMPRESA, X3.TIPO_CONTRATO, X3.MATRICULA, X3.DTINICIO, X3.SIT_PONTO



)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('vCONTADOR: '|| vCONTADOR /*|| ' QTD_SIT_FUNC: '||C1.QTD_SIT_FUNC*/);
dbms_output.put_line('*NO IFPONTO *: EMPRESA: ' ||C1.EMPRESA||' TIPO_CONTRATO: '||C1.TIPO_CONTRATO||' MATRICULA: ' ||C1.MATRICULA||' COD_SIT_PONTO: '|| C1.COD_SIT_PONTO||'-'||C1.SITUACAO_PONTO 
|| ' DTINICIO: '||TRUNC(C1.DTINICIO) || ' DTFIM: '|| TRUNC(C1.DTFIM) || ' DTFIM_USAR: '|| TRUNC(C1.DTFIM_USAR)
||' COD_SIT_FUNC_OCORR: '||C1.COD_SIT_FUNC_OCORR || ' SIT_FUNCIONAL_OCORR: '|| C1.SIT_FUNCIONAL_OCORR|| ' CONTROLE_FOLHA_OCORR: '|| C1.CONTROLE_FOLHA_OCORR|| ' E_AFASTAMENTO_OCORR: '|| C1.E_AFASTAMENTO_OCORR ||' SUSPENDE_REMUNERA_OCORR: '||C1.SUSPENDE_REMUNERA_OCORR
);

vLOG := vCONTADOR||'|'||C1.EMPRESA||'|'||C1.TIPO_CONTRATO||'|'||C1.MATRICULA||'|'||C1.NOME||'|'||C1.COD_SIT_FUNC_OCORR||'|'||C1.SIT_FUNCIONAL_OCORR||'|'||TRUNC(C1.DTINICIO)||'|'||TRUNC(C1.DTFIM)||'|'||C1.COD_SIT_FUNC_CONTR||'|'||C1.SITUACAO_FUNCIONAL_CONTR||'|'||C1.DATA_ADMISSAO||'|'||C1.DATA_RESCISAO||'|'||C1.SIT_FUNC_MESMA_DT_INICIO||'|'||C1.DATA_INIC_SITUACAO||'|'||C1.DATA_FIM_SITUACAO||'|'||C1.LOGIN_USUARIO||'|'||C1.DT_ULT_ALTER_USUA;

BEGIN --EXCEPTION


IF C1.ULT_SIT_FUNC_ATIVA IS NOT NULL THEN
-- inicio ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO
select CASE WHEN A.COD_SIT_FUNCIONAL IS NULL THEN '9999' ELSE A.COD_SIT_FUNCIONAL END
into V_ULT_SIT_FUNC0_ATIVA
--, A.DATA_FIM_SITUACAO, A.DATA_INIC_SITUACAO, S.DESCRICAO SITUACAO_FUNCIONAL, S.CONTROLE_FOLHA, S.E_AFASTAMENTO,s.suspende_remunera, s.c_livre_selec02 SO_GERA_SIT_PONTO,S.SITUACAO_PONTO COD_SIT_PONTO, P.DESCRICAO SITUACAO_PONTO, p.tipo_situacao
from ARTERH.RHCGED_ALT_SIT_FUN A
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE A.CODIGO_EMPRESA = C1.EMPRESA --'0001'
AND A.TIPO_CONTRATO = C1.TIPO_CONTRATO--'0001'
AND A.CODIGO = C1.MATRICULA--'000000001109306'
AND
A.DATA_INIC_SITUACAO = (SELECT MAX(AUX.DATA_INIC_SITUACAO)FROM ARTERH.RHCGED_ALT_SIT_FUN AUX
                                 LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SX ON SX.CODIGO = AUX.COD_SIT_FUNCIONAL
                                WHERE  A.CODIGO_EMPRESA = AUX.CODIGO_EMPRESA AND A.TIPO_CONTRATO = AUX.TIPO_CONTRATO AND A.CODIGO = AUX.CODIGO
                                --comentado em 18/2/22--AND trunc(AUX.DATA_INIC_SITUACAO) <= TRUNC(C1.DTINICIO)--ADICIONEI SINAL DE IGUAL EM 18/2/22
                                AND (
                                  (SX.CONTROLE_FOLHA = 'N' and SX.E_AFASTAMENTO = 'N' and SX.suspende_remunera = 'N' AND SX.C_LIVRE_SELEC02 = '2') 
                                 /* OR (SX.CONTROLE_FOLHA = 'A' and SX.E_AFASTAMENTO = 'N' and SX.suspende_remunera = 'S' AND SX.C_LIVRE_SELEC02 = '0')*/
                                  )
)
AND 
(
(S.CONTROLE_FOLHA = 'N' and S.E_AFASTAMENTO = 'N' and S.suspende_remunera = 'N' AND S.C_LIVRE_SELEC02 = '2')
/*OR (S.CONTROLE_FOLHA = 'A' and S.E_AFASTAMENTO = 'N' and S.suspende_remunera = 'S' AND S.C_LIVRE_SELEC02 = '0')*/
)
;
END IF;
dbms_output.put_line('V_ULT_SIT_FUNC0_ATIVA: '||V_ULT_SIT_FUNC0_ATIVA);
-- FIM ---------------------BUSCAR ULTIMA SITUAÇÃO FUNCIONAL TIPO ATIVA ANTES DO ATESTADO



-- INICIO ---------------------DEFINE SITUACAO ATIVA POR VINCULO
select CASE 
WHEN C1.COD_VINCULO IN ('0000','0001','0002','0007','0013','0015','0023','0033') THEN '1000'
WHEN C1.COD_VINCULO IN ('0010','0012','0030') THEN '1012'
ELSE '0000'
END
INTO V_SIT_FUNC_ATIVA_VINCULO 
FROM DUAL ;
dbms_output.put_line('--V_SIT_FUNC_ATIVA_VINCULO: '||V_SIT_FUNC_ATIVA_VINCULO);
-- FIM ---------------------DEFINE SITUACAO ATIVA POR VINCULO


---INICIO--------------------------------------------------------------------------------------------------------IF GERAL PARA DAR O SEGUNDO LOOP NA TABELA DE ALT SIT FUNC NO PERIODO DO LANCAMENTO DO IFPONTO---------------------------------------------------
IF C1.COD_VINCULO = '0009' THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA NO VINCULO DE ESTAGIO NAO TEM DIREITO A LMP/LMDP.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;


ELSIF C1.ULT_SIT_FUNC_ATIVA IS NULL THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA SEM SITUACAO FUNCIONAL TIPO ATIVA OU INGRESSO NO HISTORICO.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.FOLHA_ESPECIAL <> 'NAO' THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA EM FOLHA ESPECIAL NAO PRECISA LANCAR A LMP/LMDP.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.REGISTRO_PONTO NOT IN ('0100','0130','0140')THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA CAMPO REGISTRO_PONTO NO CONTRATO NAO TEM DIREITO A LMP/LMDP.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.OCORRENCIA LIKE '%COVID-19%' THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|TIPO DE OCORRENCIA COVID-19 NAO TEM DIREITO A LANCAR COMO SIT FUNC.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.STATUS_DATA_INICIO_FIM <> 'OK' THEN --NOVA PARTE EM 18/2/22 ---IF GERAL
vLOG := vLOG||'|NAO_PROCESSADO|DATA INICIO E FIM DO LANCAMENTO COM ERRO NA LOGICA CONFERIR MANUALMENTE.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.EMPRESA NOT IN ('0001','0014','0013') THEN --NOVA PARTE EM 18/2/22 ---IF GERAL --AJUSTE 8/5/23
vLOG := vLOG||'|NAO_PROCESSADO|EMPRESA DIFERENTE DE 0001,0013, 0014 AINDA NAO TEM DIREITO A LMP/LMDP.'; --AJUSTE 8/5/23
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;



ELSIF C1.COD_VINCULO <> '0009' AND C1.ULT_SIT_FUNC_ATIVA IS NULL THEN --NOVO EM 14/12/21 PARA NAO TER MAIS O ERRO EM EXECUCAO 01403. 00000 -  "no data found" ORA-06512: em line 139
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA NAO TEM HISTORICO NA ALTERACAO SITAUCAO FUNCIONAL ANTES DA DATA DE LANCAMENTO EM PROCESSO DE INGRESSO OU ATIVO.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.COD_VINCULO <> '0009' AND C1.ULT_SIT_FUNC_ATIVA IS NOT NULL AND C1.ESTA_CESSAO = 'SIM' THEN 
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA EM CESSAO NAO ESTA SENDO ALTERADO SITUACAO FUNCIONAL E PONTO.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.COD_VINCULO <> '0009' AND C1.ULT_SIT_FUNC_ATIVA IS NOT NULL AND C1.ESTA_CESSAO = 'NAO' AND C1.DATA_RESCISAO IS NOT NULL AND (TRUNC(C1.DTINICIO)>= TRUNC(C1.DATA_RESCISAO) OR TRUNC(C1.DTFIM)>= TRUNC(C1.DATA_RESCISAO)) THEN 
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA COM DATA DE RESCISAO E LANCAMENTO IGUAL OU ULTRAPASSA ESTA DATA.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

ELSIF C1.COD_VINCULO <> '0009' AND C1.ULT_SIT_FUNC_ATIVA IS NOT NULL AND C1.ESTA_CESSAO = 'NAO' AND C1.DATA_RESCISAO IS NULL AND (TRUNC(C1.DTINICIO) < TRUNC(C1.DATA_ADMISSAO) OR TRUNC(C1.DTFIM)< TRUNC(C1.DATA_ADMISSAO)) THEN 
vLOG := vLOG||'|NAO_PROCESSADO|PESSOA COM DATA LANCAMENTO DATA ANTERIOR A DATA DE ADMISSAO.';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;



--ELSIF C1.COD_VINCULO <> '0009' AND V_ULT_SIT_FUNC0_ATIVA IS NOT NULL THEN --NOVO EM 14/12/21 PARA NAO TER MAIS O ERRO EM EXECUCAO 01403. 00000 -  "no data found" ORA-06512: em line 139
ELSE
FOR C2 IN (
--PEGAR HISTORICO DE ALTERACAO DE SITUAÇCAO FUNCIONAL
--SELECT A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO, S.CONTROLE_FOLHA, S.E_AFASTAMENTO, S.SUSPENDE_REMUNERA,A.COD_SIT_FUNCIONAL COD_SIT_FUNC, S.DESCRICAO SITUACAO_FUNCIONAL, S.SITUACAO_PONTO COD_SIT_PONTO, P.DESCRICAO SITUACAO_PONTO,  A.DATA_INIC_SITUACAO , A.DATA_FIM_SITUACAO 
SELECT 
ROW_NUMBER() OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO) AS ORDEM_BM,
A.COD_SIT_FUNCIONAL, S.DESCRICAO SIT_FUNCIONAL, S.CONTROLE_FOLHA, S.E_AFASTAMENTO, S.SUSPENDE_REMUNERA, 
A.DATA_INIC_SITUACAO, A.DATA_FIM_SITUACAO
,LEAD(A.COD_SIT_FUNCIONAL, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMA_COD_SIT_FUNCIONAL
,LEAD(S.DESCRICAO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMA_SIT_FUNCIONAL
,LEAD(S.CONTROLE_FOLHA, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMO_CONTROLE_FOLHA
,LEAD(S.E_AFASTAMENTO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMO_E_AFASTAMENTO
,LEAD(S.SUSPENDE_REMUNERA, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMO_SUSPENDE_REMUNERA
,LEAD(A.DATA_INIC_SITUACAO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO  ORDER BY A.DATA_INIC_SITUACAO) AS PROXIMA_DATA_INIC_SITUACAO
,LEAD(A.DATA_FIM_SITUACAO, 1, NULL) OVER (PARTITION BY A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO  ORDER BY A.DATA_INIC_SITUACAO ) AS PROXIMA_DATA_FIM_SITUACAO
,A.LOGIN_USUARIO, A.DT_ULT_ALTER_USUA
FROM ARTERH.RHCGED_ALT_SIT_FUN A 
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S ON S.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO P ON P.CODIGO = S.SITUACAO_PONTO
WHERE A.CODIGO_EMPRESA = C1.EMPRESA  
AND A.TIPO_CONTRATO = C1.TIPO_CONTRATO 
AND A.CODIGO = C1.MATRICULA
AND 
(
(TRUNC(A.DATA_INIC_SITUACAO) BETWEEN TRUNC(C1.DTINICIO) AND TRUNC(C1.DTFIM_USAR))--DT INICIO -- SIT FUNC COMECOU NO PERIODO DE OCORRENCIA
OR (TRUNC(A.DATA_FIM_SITUACAO) BETWEEN TRUNC(C1.DTINICIO) AND TRUNC(C1.DTFIM_USAR))--DT FIM -- SIT FUNC TERMINOU O PERIODO DE OCORRENCIA
OR (TRUNC(A.DATA_INIC_SITUACAO) <= TRUNC(C1.DTINICIO) AND TRUNC(A.DATA_FIM_SITUACAO) >= TRUNC(C1.DTFIM_USAR)) --SIT FUNC COMECOU ANTES E TERMINOU DEPOIS DO PERIODO DE OCORRENCIA
OR ((TRUNC(A.DATA_INIC_SITUACAO) <= TRUNC(C1.DTINICIO) AND A.DATA_FIM_SITUACAO IS NULL) OR (TRUNC(A.DATA_INIC_SITUACAO) <= TRUNC(C1.DTFIM_USAR) AND A.DATA_FIM_SITUACAO IS NULL) )--SIT FUNC COMECOU MAS NAO TERMINOU ATE O FIM DO PERIODO DE OCORRENCIA
)



)--;

LOOP
vCONTADOR2 :=vCONTADOR2+1;

dbms_output.put_line('* NO ARTERH *: vCONTADOR2: '||vCONTADOR2|| ' ORDEM_BM: '||C2.ORDEM_BM|| ' C2.COD_SIT_FUNCIONAL: '||C2.COD_SIT_FUNCIONAL|| ' C2.SIT_FUNCIONAL: '||C2.SIT_FUNCIONAL 
--|| ' C2.COD_SIT_PONTO: '||C2.COD_SIT_PONTO || ' C2.SITUACAO_PONTO: '||C2.SITUACAO_PONTO
|| ' C2.CONTROLE_FOLHA: '||C2.CONTROLE_FOLHA || ' C2.E_AFASTAMENTO: '||C2.E_AFASTAMENTO || ' C2.SUSPENDE_REMUNERA: '||C2.SUSPENDE_REMUNERA
|| ' C2.DATA_INIC_SITUACAO: '||C2.DATA_INIC_SITUACAO|| ' C2.DATA_FIM_SITUACAO:' ||C2.DATA_FIM_SITUACAO|| ' C2.LOGIN_USUARIO: '||C2.LOGIN_USUARIO||' C2.DT_ULT_ALTER_USUA: '||C2.DT_ULT_ALTER_USUA
|| ' C2.PROXIMA_COD_SIT_FUNCIONAL: '||C2.PROXIMA_COD_SIT_FUNCIONAL|| ' C2.PROXIMA_SIT_FUNCIONAL: '||C2.PROXIMA_SIT_FUNCIONAL
|| ' C2.PROXIMO_CONTROLE_FOLHA: '||C2.PROXIMO_CONTROLE_FOLHA|| ' C2.PROXIMO_E_AFASTAMENTO: '||C2.PROXIMO_E_AFASTAMENTO|| ' C2.PROXIMO_SUSPENDE_REMUNERA: '||C2.PROXIMO_SUSPENDE_REMUNERA
|| ' C2.PROXIMA_DATA_INIC_SITUACAO: '||C2.PROXIMA_DATA_INIC_SITUACAO|| ' C2.PROXIMA_DATA_FIM_SITUACAO:' ||C2.PROXIMA_DATA_FIM_SITUACAO
);

 vLOG := vLOG||'|'||C2.COD_SIT_FUNCIONAL||'|'||C2.DATA_INIC_SITUACAO||'|'||C2.DATA_FIM_SITUACAO||'|'||C2.LOGIN_USUARIO||'|'||C2.DT_ULT_ALTER_USUA;

--inicio-- cenarios IF------------------------------------------------------------
--INICIO-- AVISO FALECIMENTO
IF C1.CONTROLE_FOLHA_OCORR = 'P' AND C1.E_AFASTAMENTO_OCORR = 'S' AND C1.SUSPENDE_REMUNERA_OCORR = 'S' THEN
  --INICIO --DATAS E TIPOS SIT FUNC
  IF vCONTADOR2 = 1 AND C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N'
     AND C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL THEN
  dbms_output.put_line('--AVISO FALECIMENTO CENARIO 1: PESSOA ATIVA SEM DATA FIM');
  dbms_output.put_line('--1 COLOCAR DATA FIM NA ATIVA A PARTIR DO INICIO AVISO, 2 CRIAR O REGISTRO DO AVISO');
  vLOG := vLOG||'|NAO_PROCESSADO|AVISO FALECIMENTO CENARIO 1: PESSOA ATIVA SEM DATA FIM. 1 COLOCAR DATA FIM NA ATIVA A PARTIR DO INICIO AVISO, 2 CRIAR O REGISTRO DO AVISO.|';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

  END IF; 
  --INICIO --DATAS E TIPOS SIT FUNC
--FIM --AVISO FALECIMENTO

--INICIO-- OUTRAS OCORRENCIAS/JUSTIFICATIVAS DE AFASTAMENTO
ELSIF C1.CONTROLE_FOLHA_OCORR = 'L' AND C1.E_AFASTAMENTO_OCORR = 'S' AND C1.SUSPENDE_REMUNERA_OCORR = 'N' THEN

  IF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL 
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 2 (validado): C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL ');
  dbms_output.put_line('--1-trocar sit func ativo por afastamento gravando a data fim do afastamento, 2-voltar pessoa ativo 1 dia depois do fim do afastamento');
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 2 (validado): C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL: 1-trocar sit func ativo por afastamento gravando a data fim do afastamento, 2-voltar pessoa ativo 1 dia depois do fim do afastamento.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR, DATA_FIM_SITUACAO = TRUNC(C1.DTFIM_USAR), LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 2 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTFIM_USAR)+1 AND COD_SIT_FUNCIONAL = V_SIT_FUNC_ATIVA_VINCULO ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTFIM_USAR)+1, V_SIT_FUNC_ATIVA_VINCULO, 'IFPONTO', SYSDATE, 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 2 (validado)');COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL 
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 3 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL ');
  dbms_output.put_line('--1-colocar data fim no ativo = inicio afastamento -1dia, 2-criar o afastamento, 3-voltar pessoa ativo 1 dia depois do fim do afastamento');
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 3 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO IS NULL: 1-colocar data fim no ativo = inicio afastamento -1dia, 2-criar o afastamento, 3-voltar pessoa ativo 1 dia depois do fim do afastamento.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET DATA_FIM_SITUACAO = TRUNC(C1.DTINICIO)-1 , LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 3 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTINICIO) AND COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTINICIO), TRUNC(C1.DTFIM_USAR), C1.COD_SIT_FUNC_OCORR, 'IFPONTO', SYSDATE,'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 3 (validado)');COMMIT;
--COMENTADO 3/11/21--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTFIM_USAR)+1 AND COD_SIT_FUNCIONAL = V_SIT_FUNC_ATIVA_VINCULO ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTFIM_USAR)+1, V_SIT_FUNC_ATIVA_VINCULO, 'IFPONTO', SYSDATE,'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 3 (validado)');COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 4: C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR ');
  dbms_output.put_line('--1-trocar o codigo de ativo para o de afastamento');
  vLOG := vLOG||'|NAO_PROCESSADO|DEVERIA MAS POR ALGUM MOTIVO NAO CODIFIQUEI AINDA: GRAVAR OCORRENCIAS/JUSTIFICATIVAS CENARIO 4: C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR: 1-trocar o codigo de ativo para o de afastamento.|';

UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;  --NOVO EM 18/2/22


  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 5 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR');
  dbms_output.put_line('--1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio do afastamento até o fim que estava ativo');
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 5 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO < C1.DTFIM_USAR: 1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio do afastamento até o fim que estava ativo.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET DATA_FIM_SITUACAO = TRUNC(C1.DTINICIO)-1 , LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE  , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 5 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTINICIO) AND COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA , TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTINICIO), TRUNC(C2.DATA_FIM_SITUACAO), C1.COD_SIT_FUNC_OCORR, 'IFPONTO', SYSDATE,'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 5 (validado)');COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 6: C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR');
  dbms_output.put_line('--1-trocar o codigo de ativo para o de afastamento');
  vLOG := vLOG||'|NAO_PROCESSADO|DEVERIA MAS POR ALGUM MOTIVO NAO CODIFIQUEI AINDA: GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 6: C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR: 1-trocar o codigo de ativo para o de afastamento.|';

UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;  --NOVO EM 18/2/22


  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 7 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR');
  dbms_output.put_line('--1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio do afastamento até o fim que estava/afastamento');
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 7 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO = C1.DTFIM_USAR: 1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio do afastamento até o fim que estava/afastamento.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET DATA_FIM_SITUACAO = TRUNC(C1.DTINICIO)-1 , LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 7 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTINICIO) AND COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTINICIO), TRUNC(C2.DATA_FIM_SITUACAO), C1.COD_SIT_FUNC_OCORR, 'IFPONTO', SYSDATE,'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 7 (validado)');COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 8 (validado): C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR');
  dbms_output.put_line('--1-troco sit func ativo por afastamento diminuindo o seu fim para a o fim do afastamento, 2-crio ativo com inicio = fim afastamento +1dia e deixando o fim com o valor do fim que já estava antes do afastamento');
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 8 (validado): C1.DTINICIO <= C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR: 1-troco sit func ativo por afastamento diminuindo o seu fim para a o fim do afastamento, 2-crio ativo com inicio = fim afastamento +1dia e deixando o fim com o valor do fim que já estava antes do afastamento.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR, DATA_FIM_SITUACAO = TRUNC(C1.DTFIM_USAR), LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 8 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
--COMENTADO 3/11/21--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTFIM_USAR)+1 AND COD_SIT_FUNCIONAL = V_SIT_FUNC_ATIVA_VINCULO ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTFIM_USAR)+1, TRUNC(C2.DATA_FIM_SITUACAO), V_SIT_FUNC_ATIVA_VINCULO, 'IFPONTO', SYSDATE, 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 8 (validado)');COMMIT;
ARTERH.SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF ( (C2.CONTROLE_FOLHA = 'N' AND C2.E_AFASTAMENTO = 'N' AND C2.SUSPENDE_REMUNERA = 'N') OR (C2.CONTROLE_FOLHA = 'A' and C2.E_AFASTAMENTO = 'N' and C2.suspende_remunera = 'S') )--ADICIONADO EM 18/2/22 O CONTROLE_FOLHA = A-ADMITIDO
  AND C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR
  THEN
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 9 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR');
  dbms_output.put_line('--1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio afastamento até o fim do afastamento, 3-volto pessoa ativo inicio 1 dia depois do fim do afastamento com o fim o que estava antes do afastamento'); 
  vLOG := vLOG||'|PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 9 (validado): C1.DTINICIO > C2.DATA_INIC_SITUACAO AND C2.DATA_FIM_SITUACAO > C1.DTFIM_USAR: 1-diminui data fim ativo = inicio afastamento -1dia, 2-crio o afastamento a partir da data inicio afastamento até o fim do afastamento, 3-volto pessoa ativo inicio 1 dia depois do fim do afastamento com o fim o que estava antes do afastamento.|';
--/*
UPDATE ARTERH.RHCGED_ALT_SIT_FUN SET DATA_FIM_SITUACAO = TRUNC(C1.DTINICIO)-1 , LOGIN_USUARIO = 'IFPONTO' , DT_ULT_ALTER_USUA = SYSDATE , TEXTO_ASSOCIADO = 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 9 (validado)'
WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C2.DATA_INIC_SITUACAO);  COMMIT;
--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTINICIO) AND COD_SIT_FUNCIONAL = C1.COD_SIT_FUNC_OCORR ;COMMIT;
INSERT INTO ARTERH.RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, DATA_FIM_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTINICIO), TRUNC(C1.DTFIM_USAR), C1.COD_SIT_FUNC_OCORR, 'IFPONTO', SYSDATE, 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 9 (validado)');COMMIT;
--comentado em 24/9/21--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
DELETE ARTERH.RHCGED_ALT_SIT_FUN WHERE CODIGO_EMPRESA = C1.EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO  AND CODIGO = C1.MATRICULA AND TRUNC(DATA_INIC_SITUACAO) = TRUNC(C1.DTFIM_USAR)+1 AND COD_SIT_FUNCIONAL = V_SIT_FUNC_ATIVA_VINCULO ;COMMIT;
INSERT INTO RHCGED_ALT_SIT_FUN (IND_EF_RETRO_ESOCIAL, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO, DATA_INIC_SITUACAO, COD_SIT_FUNCIONAL, LOGIN_USUARIO, DT_ULT_ALTER_USUA, TEXTO_ASSOCIADO)VALUES ('N', C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA, TRUNC(C1.DTFIM_USAR)+1, V_SIT_FUNC_ATIVA_VINCULO, 'IFPONTO', SYSDATE, 'GRAVA OCORRENCIAS/JUSTIFICATIVAS CENARIO 9 (validado)');COMMIT;
--SUGESP_ALT_SIT_FUNC_ULT_CONTRA(C1.EMPRESA ,C1.TIPO_CONTRATO , C1.MATRICULA ,'IFPONTO');
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'S' WHERE CODIGO = C1.CODIGO;COMMIT;
--*/

  ELSIF C2.CONTROLE_FOLHA IN ('L','M') THEN
    IF C1.COD_SIT_FUNC_OCORR = C1.SIT_FUNC_MESMA_DT_INICIO THEN
    dbms_output.put_line('--PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO LMP/LMDP, INCOMUM INVESTIGAR');
    vLOG := vLOG||'|NAO_PROCESSADO|PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO LMP/LMDP, INCOMUM INVESTIGAR.|';
    IF C1.COD_SIT_FUNC_OCORR <> C1.SIT_FUNC_MESMA_DT_INICIO THEN
    dbms_output.put_line('--PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO AFASTAMENTO, VERIFICAR POSSIVEL ERRO DE INTEGRACAO');
    vLOG := vLOG||'|NAO_PROCESSADO|PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO AFASTAMENTO, VERIFICAR POSSIVEL ERRO DE INTEGRACAO.|';
    END IF;
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

  ELSIF C2.CONTROLE_FOLHA IN ('D','S') THEN
  dbms_output.put_line('--PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO DESLIGAMENTO');
  vLOG := vLOG||'|NAO_PROCESSADO|PERIODO JA COM LANCAMENTO DE SIT FUNC DO TIPO DESLIGAMENTO.|';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

  ELSE
  dbms_output.put_line('--GRAVA OCORRENCIAS/JUSTIFICATIVAS: *************CENARIO NAO MAPEADO, VERIFICAR');
  vLOG := vLOG||'|NAO_PROCESSADO|GRAVA OCORRENCIAS/JUSTIFICATIVAS: *************CENARIO NAO MAPEADO, VERIFICAR.|';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;
  END IF; 
--FIM-- OUTRAS OCORRENCIAS/JUSTIFICATIVAS DE AFASTAMENTO

ELSE
 dbms_output.put_line('--****************CENARIO NAO MAPEADO AVALIAR COM GETED/GEVIF');
 vLOG := vLOG||'|NAO_PROCESSADO|****************CENARIO NAO MAPEADO AVALIAR COM GETED/GEVIF.|';
UPDATE PONTO_ELETRONICO.IFPONTO_OCOR_JUST_SIT_FUNC_T2  SET data_processamento = SYSDATE, STATUS_PROCESSAMENTO = 'N' WHERE CODIGO = C1.CODIGO;COMMIT;

END IF;
--FIM--cenarios IF------------------------------------------------------------
vCONTADOR2 :=0;
--END LOOP;--2º loop --TIREI DAQUI EM 11/3/22 4H

--COMENTADO EM 18/2/22--ELSE
--COMENTADO EM 18/2/22-- dbms_output.put_line('--****************ERRO, PESSOA NAO TEM REGISTRO DE SITUACAO FUNCIONAL ATIVA NA ALT SIT FUNC');
END IF; -- V_ULT_SIT_FUNC0_ATIVA IS NOT NULL THEN --NOVO EM 14/12/21 PARA NAO TER MAIS O ERRO EM EXECUCAO 01403. 00000 -  "no data found" ORA-06512: em line 139
---FIM-------------------------------------------------------------------------------------------------------IF GERAL PARA DAR O SEGUNDO LOOP NA TABELA DE ALT SIT FUNC NO PERIODO DO LANCAMENTO DO IFPONTO---------------------------------------------------

END LOOP;--2º loop --COLOQUEI AQUI EM 11/3/22 4H

dbms_output.put_line('--vLOG: '||vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CAMPO_2, CONSIDERACOES)
VALUES(C1.EMPRESA,C1.TIPO_CONTRATO,C1.MATRICULA, SYSDATE,'PRG4_SIT_FUNC_OCORRENCIA', C1.DTINICIO, vLOG);COMMIT;

dbms_output.put_line('----------------------------------------------------------------------------------');


--vCONTADOR2 :=0;
data_inicial := NULL;
data_final := NULL;
num_dias := 0;
vDATA_DIA := NULL;

V_ULT_SIT_FUNC0_ATIVA := NULL;
vLOG := NULL;
V_SIT_FUNC_ATIVA_VINCULO := NULL;

END IF;--COLOQUEI AQUI EM 11/3/22 4H


EXCEPTION WHEN OTHERS THEN
err_msg := SQLCODE||' '||SUBSTR(SQLERRM, 1, 4000);
dbms_output.put_line('err_msg:' ||err_msg);

INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT(CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CAMPO_1,  DATA_DADOS, CONSIDERACOES)
VALUES(C1.EMPRESA, C1.TIPO_CONTRATO, C1.MATRICULA,'LOG EXECUCAO PRG4_SIT_FUNC_OCORRENCIA', SYSDATE, err_msg
);COMMIT;
END;--BEGIN EXCEPTION

END LOOP; --FIM LOOP 1
END;

END;
