
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG5_SIT_PONTO_OCORRENCIA" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS 
BEGIN

--Kellysson em 5/8/20 evoluindo da v3 para v4 para incluir o fechamento dos estagiários
--1º grande ajuste será tirar as excecoes para o vinculo = 0009

--KELLYSSON 4/6/20
--**************TROCAR DATAS

DECLARE 
vCONTADOR NUMBER (10);
vCONTADOR2 NUMBER (10);
data_inicial date;
data_final date;
num_dias number;
vDATA_DIA DATE;

vDT_INI_PERIODO DATE;
vDT_FIM_PERIODO DATE;

begin
dbms_output.enable(null);
vCONTADOR :=0;
vCONTADOR2 :=0;
data_inicial := NULL ;
data_final := NULL;
num_dias :=0;
vDATA_DIA := NULL;

vDT_INI_PERIODO := TO_DATE(DATA_INICIO,'DD/MM/YY'); -------------ALTERAR DATAS
vDT_FIM_PERIODO := TO_DATE(DATA_FIM,'DD/MM/YY');-------------ALTERAR DATAS

--dbms_output.put_line('EMPRESA|TIPO_CONTRATO|MATRICULA|NOME|DATA_DIA|COD_SIT_PONTO|SITUACAO_PONTO|COD_SIT_FUNC|SITUACAO_FUNCIONAL|COD_CGERENC1|COD_CGERENC2|COD_CGERENC3|COD_CGERENC4|COD_CGERENC5|COD_CGERENC6|LOCAL|COD_CARGO_EFETIVO|CARGO_EFETIVO|COD_CARGO_COMISS|CARGO_COMISSIONADO|CODIGO_FUNCAO|FUNCAO|');

for C1 in(

SELECT X2.* 
FROM (
--ANALISE PREVIA DAS OCORRENCIAS
SELECT 
CASE WHEN C.c_livre_selec01 = 0 THEN 'NAO' ELSE 'SIM' END FOLHA_ESPECIAL, b.registro_ponto, SP.tipo_referencia,
X.*
,B.NOME, b.vinculo, B.SITUACAO_FUNCIONAL COD_SIT_FUNC, SF.DESCRICAO SITUACAO_FUNCIONAL, 
GN.cod_cgerenc1, GN.cod_cgerenc2, GN.cod_cgerenc3, GN.cod_cgerenc4, GN.cod_cgerenc5, GN.cod_cgerenc6, GN.DESCRICAO LOCAL, 
b.cod_cargo_efetivo, E.DESCRICAO CARGO_EFETIVO, b.cod_cargo_comiss, C.DESCRICAO CARGO_COMISSIONADO, b.codigo_funcao, F.DESCRICAO FUNCAO
 --X.SIT_PONTO, X.OCORRENCIA, X.POSSUI_SIT_FUNC_ASSOCIADA, X.TIPO_SIT_PONTO_ARTERH, COUNT(1)QUANT
FROM (
select --O.*
 --O.SIT_PONTO, O.SITUACAO, COUNT(1)QUANT
O.EMPRESA, O.TIPO_CONTRATO, O.MATRICULA, O.SIT_PONTO, O.SITUACAO OCORRENCIA,  O.DTINICIO, O.DTFIM
, SP.CODIGO COD_SIT_PONTO, SP.DESCRICAO SITUACAO_PONTO
,CASE WHEN SF.SITUACAO_PONTO IS NULL THEN 'NAO' ELSE 'SIM' END POSSUI_SIT_FUNC_ASSOCIADA
, CASE WHEN (SP.c_livre_selec01) = 1 THEN 'JUSTIFICATIVA' WHEN  (SP.c_livre_selec01) = 2 THEN 'OCORRENCIA' WHEN (SP.c_livre_selec01) =  9 THEN 'TOTALIZADOR' ELSE 'VERIFICAR' END TIPO_SIT_PONTO_ARTERH
from PONTO_ELETRONICO.IFPONTO_OCORRENCIAS O 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON O.SIT_PONTO = SP.CODIGO
LEFT OUTER JOIN (SELECT SITUACAO_PONTO FROM ARTERH.RHPARM_SIT_FUNC WHERE DATA_FIM_VIGENCIA IS NULL AND SITUACAO_PONTO IS NOT NULL GROUP BY SITUACAO_PONTO) SF
ON SF.SITUACAO_PONTO = O.SIT_PONTO
WHERE O.DATA_PROCESSAMENTO IS NULL 
AND LPAD(O.EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
AND TRUNC(O.DTAPAGOU) = TO_DATE('01/01/1970','DD/MM/YYYY')
AND O.LOGIN_APROVACAO IS NOT NULL
AND O.LOGIN_CADASTRO <> 'Integração'--NOVO EM 25/6/20
--GROUP BY  O.SIT_PONTO, O.SITUACAO
ORDER BY O.EMPRESA, O.TIPO_CONTRATO, O.MATRICULA, O.DTINICIO --3.640>2.792
)X 
--GROUP BY  X.SIT_PONTO, X.OCORRENCIA, X.POSSUI_SIT_FUNC_ASSOCIADA, X.TIPO_SIT_PONTO_ARTERH ORDER BY COUNT(1)DESC

--inicio para o COVID
left outer join ARTERH.RHPESS_CONTRATO B on X.EMPRESA = B.CODIGO_EMPRESA AND X.TIPO_CONTRATO = B.TIPO_CONTRATO AND X.MATRICULA = B.CODIGO
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO =  B.SITUACAO_FUNCIONAL 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON LPAD(X.SIT_PONTO, 4,0) = SP.CODIGO 
left outer join ARTERH.RHPLCS_FUNCAO F ON F.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND F.CODIGO = b.codigo_funcao
left outer join ARTERH.RHPLCS_CARGO C ON c.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND c.CODIGO = b.cod_cargo_comiss
left outer join ARTERH.RHPLCS_CARGO E ON e.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND e.CODIGO = b.cod_cargo_efetivo
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON B.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND b.COD_CUSTO_GERENC1 = GN.cod_cgerenc1 AND b.COD_CUSTO_GERENC2 = GN.cod_cgerenc2 AND b.COD_CUSTO_GERENC3 = GN.cod_cgerenc3
AND b.COD_CUSTO_GERENC4 = GN.cod_cgerenc4 AND b.COD_CUSTO_GERENC5 = GN.cod_cgerenc5 AND b.COD_CUSTO_GERENC6 = GN.cod_cgerenc6

WHERE  
--X.OCORRENCIA LIKE '%COVID-19%' AND --somente covid-19
--b.vinculo = '0009'--E.DESCRICAO NOT LIKE '%ESTAGIÁRIO%' --tirando estagiarios
--and 
b.ano_mes_referencia = (select max(a.ano_mes_referencia) from ARTERH.RHPESS_CONTRATO a where a.codigo_empresa = b.codigo_empresa and a.tipo_contrato = b.tipo_contrato and a.codigo = b.codigo)
--FIM para o COVID
)X2
WHERE 
--X2.VINCULO <> '0009' AND--COMENTADO EM 6/8/20 PARA PEGAR TAMBEM OS ESTAGIARIOS
X2.FOLHA_ESPECIAL = 'NAO' 
AND X2.REGISTRO_PONTO NOT IN ('0110','0120','0150','0160')--TIRAR ESTAGIARIOS, PESSOAS FOLHA ESPECIAL E NÂO USAR IFPONTO
--COMENTADO EM 1/7/21 --AND X2.OCORRENCIA LIKE '%COVID-19%'  --somente covid-19
AND X2.SIT_PONTO IN ('0580', '0582'--INCLUIDO PATERNIDADE EM 25/1/24--COMENTADO AS DE COVID EM 25/1/24--'1188',/*'1189',*/'0580','1192'
)--AS 3 DE COVID 19--NOVO EM 1/7/21


/*comentado em 11/12/21
and x2.cod_cargo_efetivo not in ('000000000001730','000000000001761',
'000000000001763','000000000001765','000000000001766','000000000001767'
,'000000000003339','000000000003340','000000000009730','000000000009731')--tira os guardas municipais
*/

--AND X2.VINCULO = '0009'--SOMENTE ESTAGIO

--and x2.MATRICULA = '000000000307894'--testes

--AND X2.MATRICULA IN ('000000000248022','000000000247956')

--inicio --14/7/21--parte nova para testar
--/*
AND 
(
(
--(X2.cod_cgerenc1 NOT IN ('000095'))--TIRA SAUDE --comentado para o piloto SMSA
--OR
(--X2.cod_cgerenc1 IN ('000094') AND 
X2.LOCAL NOT LIKE '%ESCOLA%' AND X2.LOCAL NOT LIKE '%EMEI%')--SMED TIRANDO ESCOLAS E UMEIS
)
/*
OR
(
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000000' AND X2.cod_cgerenc3='000015' AND X2.cod_cgerenc4='000039' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000' OR
--95	0	15	39	0	0
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000000' AND X2.cod_cgerenc3='000016' AND X2.cod_cgerenc4='000030' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000' OR
--95	0	16	30	0	0
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000000' AND X2.cod_cgerenc3='000020' AND X2.cod_cgerenc4='000027' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000' OR
--95	0	20	27	0	0
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000000' AND X2.cod_cgerenc3='000021' AND X2.cod_cgerenc4='000024' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000' OR
--95	0	21	24	0	0
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000002' AND X2.cod_cgerenc3='000002' AND X2.cod_cgerenc4='000007' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000' OR
--95	2	2	7	0	0
X2.cod_cgerenc1 = '000095' AND X2.cod_cgerenc2='000004' AND X2.cod_cgerenc3='000002' AND X2.cod_cgerenc4='000003' AND X2.cod_cgerenc5='000000' AND X2.cod_cgerenc6='000000'
--95	4	2	3	0	0
)
*/
)  
--*/
--fim--14/7/21--parte nova para testar



)

LOOP
vCONTADOR :=vCONTADOR+1;
--dbms_output.put_line('vCONTADOR:'|| vCONTADOR);


--POPULAR VARIAVEIS
data_inicial := C1.DTINICIO;--to_date(c1.data_efetivo_exerc_to_char,'DD/MM/YYYY');--c1.data_efetivo_exerc;--
data_final := C1.DTFIM;--to_date(c1.sysdate_to_char,'DD/MM/YYYY');--SYSDATE;--
--dbms_output.put_line( 'DATA INICIO ANALISE: ' || to_date(data_inicial,'DD/MM/YY'));
--dbms_output.put_line( 'DATA FIM ANALISE: ' || to_date(data_final,'DD/MM/YY'));
num_dias := (data_final - data_inicial)+1;
--dbms_output.put_line( 'TOTAL DE DIAS: ' || num_dias);
--dbms_output.put_line( '' );


for i in 1..num_dias loop
vCONTADOR2 :=vCONTADOR2+1;
--  dbms_output.put_line( '| DIA: ' || i|| ' DATA: ' || to_char((data_inicial-1)+i,'DD/MM/YYYY')||'|'|| c1.codigo_empresa  ||'|'|| c1.tipo_contrato ||'|'||c1.codigo );
vDATA_DIA :=  to_date(to_char((data_inicial-1)+i,'DD/MM/YYYY'),'DD/MM/YYYY');
--dbms_output.put_line(vCONTADOR2||'-'|| vDATA_DIA );

IF 
TO_DATE(vDATA_DIA,'DD/MM/YY') BETWEEN vDT_INI_PERIODO and vDT_FIM_PERIODO--TO_DATE('01/07/21','DD/MM/YY') AND TO_DATE('31/07/21','DD/MM/YY')--**************TROCAR DATAS******************** 
THEN
--dbms_output.put_line('DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||LPAD(C1.EMPRESA,4,0) ||''' AND TIPO_CONTRATO = ''' || LPAD(C1.TIPO_CONTRATO,4,0) ||''' AND CODIGO_CONTRATO = '''|| LPAD(C1.MATRICULA,15,0) ||'''AND TRUNC(DATA) = TO_DATE('''|| trunc(vDATA_DIA) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = '''||C1.COD_SIT_PONTO||'''; COMMIT;' );  
DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = 'F' AND CODIGO_EMPRESA = LPAD(C1.EMPRESA,4,0) AND TIPO_CONTRATO = LPAD(C1.TIPO_CONTRATO,4,0) AND CODIGO_CONTRATO =  LPAD(C1.MATRICULA,15,0) AND TRUNC(DATA) = TO_DATE(vDATA_DIA ,'DD/MM/YYYY') AND CODIGO_SITUACAO = C1.COD_SIT_PONTO; COMMIT;  
--dbms_output.put_line('INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES ('''||LPAD(C1.EMPRESA,4,0) ||''','''|| LPAD(C1.TIPO_CONTRATO,4,0) ||''','''|| LPAD(C1.MATRICULA,15,0) ||''', TO_DATE('''|| trunc(vDATA_DIA) ||''',''DD/MM/YYYY''),'''||C1.COD_SIT_PONTO ||''', 1, ''F'', SYSDATE, ''IFPONTO'',''N'',''SCRIPT FECHAMENTO IFPONTO(gerar_SIT_PONTO_da_OCORRENCIA_V4.sql)''); COMMIT;' );  
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES (LPAD(C1.EMPRESA,4,0),LPAD(C1.TIPO_CONTRATO,4,0),LPAD(C1.MATRICULA,15,0), TO_DATE(vDATA_DIA,'DD/MM/YYYY'),C1.COD_SIT_PONTO, 1, 'F', SYSDATE, 'IFPONTO','N','SCRIPT FECHAMENTO IFPONTO(gerar_SIT_PONTO_da_OCORRENCIA_V4.sql)'); COMMIT;  
END IF;
--dbms_output.put_line(C1.EMPRESA||'|'||C1.TIPO_CONTRATO||'|'||C1.MATRICULA||'|'||C1.NOME||'|'||vDATA_DIA||'|'||C1.COD_SIT_PONTO||'|'||C1.SITUACAO_PONTO||'|'||C1.COD_SIT_FUNC||'|'||C1.SITUACAO_FUNCIONAL||'|'||C1.COD_CGERENC1||'|'||C1.COD_CGERENC2||'|'||C1.COD_CGERENC3||'|'||C1.COD_CGERENC4||'|'||C1.COD_CGERENC5||'|'||C1.COD_CGERENC6 ||'|'||C1.LOCAL||'|'||C1.COD_CARGO_EFETIVO||'|'||C1.CARGO_EFETIVO||'|'||C1.COD_CARGO_COMISS||'|'||C1.CARGO_COMISSIONADO||'|'||C1.CODIGO_FUNCAO||'|'||C1.FUNCAO);


end loop;--2º loop

vCONTADOR2 :=0;
data_inicial := NULL;
data_final := NULL;
num_dias := 0;
vDATA_DIA := NULL;

END LOOP; --FIM LOOP 1
END;

END;
