
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG6_DATA_ESPECIAL_SMSA" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN
--em 2/6/21 kellyson achar tidpo de dia no calendario especifico
--v2 em 9/7/21 para rever a questão de ter comecado ou terminado o plantao na data especial
--V3 EM 14/9/21 CORRIGINDO ALGUNS CENARIOS QUE FALTAVA
--v4 em 9/11/21 para refinar por tipo de dia x classificacao do local
--V5 EM 4/2/22 para ajustes na logica de classificacao dos locais com a classificacao do calendario
------------------------------------------------------------TROCAR DATAS

DECLARE               
vCONTADOR NUMBER; 
data_inicial date;
data_final date;
num_dias number;
vDATA_DIA date;
vDT_INI_PERIODO DATE;
vDT_FIM_PERIODO DATE;
vSTRING_DATAS_ESPECIAIS VARCHAR2(2000);
vTAMANHO_DATAS_ESPECIAIS NUMBER;
vPARTE_ATUAL_DATAS_ESPECIAIS NUMBER;
vDATA_ESPECIAL DATE;

vSTRING_TIPOS_DIAS VARCHAR2(2000);--novo 9/11/21
vTAMANHO_TIPOS_DIAS NUMBER;--novo 9/11/21
vPARTE_ATUAL_TIPOS_DIAS NUMBER;--novo 9/11/21
vTIPO_DIA VARCHAR2(1);--novo 9/11/21
vLOG VARCHAR2(4000);
vMAIS_DADOS VARCHAR2(4000);-- NOVO 4/2/22

vCARGO_PODE_VERBA VARCHAR2 (1); --novo em 9/2/22

BEGIN
dbms_output.enable(null);
vCONTADOR := 0;
vSTRING_DATAS_ESPECIAIS := NULL;
vTAMANHO_DATAS_ESPECIAIS := 0;
vPARTE_ATUAL_DATAS_ESPECIAIS := 1;
vDATA_ESPECIAL := NULL;

vSTRING_TIPOS_DIAS := NULL;--novo 9/11/21
vTAMANHO_TIPOS_DIAS := 0;--novo 9/11/21
vPARTE_ATUAL_TIPOS_DIAS := 1;--novo 9/11/21
vTIPO_DIA := NULL;--novo 9/11/21
vLOG := NULL;
vMAIS_DADOS := NULL; --NOVO EM 4/2/22

vDT_INI_PERIODO := TO_DATE(DATA_INICIO,'DD/MM/YY'); -------------ALTERAR DATAS
vDT_FIM_PERIODO := TO_DATE(DATA_FIM,'DD/MM/YY');-------------ALTERAR DATAS

vCARGO_PODE_VERBA := NULL;

--CABECALHO DO LOG
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES)
VALUES(NULL,NULL,NULL, SYSDATE,'PRG6_DATA_ESPECIAL_SMSA','RESULTADO_FINAL_PROCESSAMENTO|EMPRESA|TIPO_CONTRATO|CONTRATO|NOME|DATA|TIPO_DIA_CALENDARIO|COD_CARGO_COMISS|CARGO_COMISSIONADO|COD_CARGO_EFETIVO|CARGO_EFETIVO|CODIGO_FUNCAO|FUNCAO|COD_LOCAL1|COD_LOCAL2|COD_LOCAL3|COD_LOCAL4|COD_LOCAL5|COD_LOCAL6|LOCAL|CLASSIFICACAO_LOCAL|vCARGO_PODE_VERBA');COMMIT;


--INICIO----------------------------------------------------------1ª PARTE APENAS PARA SABER AS DATAS QUE DEVEM ENTRAR NA VERBA: Abono Plantão Data Especial
FOR C1 IN(

SELECT 
EXTRACT(DAY FROM DATA_DIA)NUMERO_DIA, 
EXTRACT(MONTH FROM DATA_DIA)NUMERO_MES, 
CASE
WHEN EXTRACT(MONTH FROM DATA_DIA) = 1  THEN 'JANEIRO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 2  THEN 'FEVEREIRO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 3  THEN 'MARCO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 4  THEN 'ABRIL'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 5  THEN 'MAIO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 6  THEN 'JUNHO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 7  THEN 'JULHO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 8  THEN 'AGOSTO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 9  THEN 'SETEMBRO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 10 THEN 'OUTUBRO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 11 THEN 'NOVEMBRO'
WHEN EXTRACT(MONTH FROM DATA_DIA) = 12 THEN 'DEZEMBRO'
END DESCRICAO_MES,
EXTRACT(YEAR FROM DATA_DIA)NUMERO_ANO, 
DATA_DIA, DIA_SEMANA, LOGIN_USUARIO, DT_ULT_ALTER_USUA, NRO_DIA_SEMANA, DESCRICAO, NRO_SEMANA_MES
FROM ARTERH.RHTABS_DATAS
WHERE TRUNC(DATA_DIA) BETWEEN vDT_INI_PERIODO AND vDT_FIM_PERIODO ORDER BY DATA_DIA

)

LOOP
--vCONTADOR :=vCONTADOR+1;
--dbms_output.put_line('--'||vCONTADOR||'-'|| C1.DATA_DIA ||'-'|| C1.DIA_SEMANA);

FOR C2 IN (

SELECT 
ANO_REFERENCIA, CODIGO, DESCRICAO,
DEZEMBRO_ANT,
JANEIRO, FEVEREIRO, MARCO, ABRIL, MAIO, JUNHO, JULHO, AGOSTO, SETEMBRO, OUTUBRO, NOVEMBRO, DEZEMBRO, 
JANEIRO_SEG
FROM ARTERH.RHPARM_CALENDARIO WHERE CODIGO = '0003' ------------------calendario especifico da SMSA no Arterh ja existente para DATAS ESPECIAIS DA SMSA --manutencao GESFO
AND TRUNC(ANO_REFERENCIA) = TO_DATE('01/01/'||C1.NUMERO_ANO,'DD/MM/YYYY') 
--(SELECT MAX(ANO_REFERENCIA) MAX_ANO_REFERENCIA FROM RHPARM_CALENDARIO WHERE CODIGO = '0003')

)
LOOP
--dbms_output.put_line('--'||C2.ANO_REFERENCIA||'-'|| C2.CODIGO);

IF C1.DESCRICAO_MES = 'JANEIRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.JANEIRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JANEIRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.JANEIRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JANEIRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.JANEIRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'FEVEREIRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.FEVEREIRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.FEVEREIRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.FEVEREIRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.FEVEREIRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.FEVEREIRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'MARCO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.MARCO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.MARCO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.MARCO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.MARCO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.MARCO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'ABRIL' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.ABRIL, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.ABRIL, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.ABRIL, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.ABRIL, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.ABRIL, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'MAIO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.MAIO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.MAIO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.MAIO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.MAIO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.MAIO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'JUNHO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.JUNHO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JUNHO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.JUNHO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JUNHO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.JUNHO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'JULHO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.JULHO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JULHO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.JULHO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.JULHO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.JULHO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'AGOSTO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.AGOSTO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.AGOSTO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.AGOSTO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.AGOSTO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.AGOSTO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'SETEMBRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.SETEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.SETEMBRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.SETEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.SETEMBRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.SETEMBRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'OUTUBRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.OUTUBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.OUTUBRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.OUTUBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.OUTUBRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.OUTUBRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'NOVEMBRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.NOVEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.NOVEMBRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.NOVEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.NOVEMBRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.NOVEMBRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

ELSIF C1.DESCRICAO_MES = 'DEZEMBRO' THEN
--dbms_output.put_line(CASE WHEN SUBSTR(C2.DEZEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.DEZEMBRO, C1.NUMERO_DIA,1)END );
IF CASE WHEN SUBSTR(C2.DEZEMBRO, C1.NUMERO_DIA,1) = ' ' THEN 'N' ELSE SUBSTR(C2.DEZEMBRO, C1.NUMERO_DIA,1)END IN ('E','G','U') THEN
vSTRING_DATAS_ESPECIAIS :=vSTRING_DATAS_ESPECIAIS||C1.DATA_DIA;
vSTRING_TIPOS_DIAS := vSTRING_TIPOS_DIAS||SUBSTR(C2.DEZEMBRO, C1.NUMERO_DIA,1);--NOVO EM 9/11/21
END IF;

END IF;
END LOOP; --FOR C2
dbms_output.put_line('--vSTRING_DATAS_ESPECIAIS: '||vSTRING_DATAS_ESPECIAIS);
dbms_output.put_line('--vSTRING_TIPOS_DIAS: '||vSTRING_TIPOS_DIAS);
END LOOP;---FOR C1
--FIM----------------------------------------------------------1ª PARTE APENAS PARA SABER AS DATAS QUE DEVEM ENTRAR NA VERBA: Abono Plantão Data Especial

--INICIO------------------------------------------------------2ª PARTE ----------GRAVAR AS SIT PONTO
vTAMANHO_DATAS_ESPECIAIS := LENGTH(vSTRING_DATAS_ESPECIAIS) ;
vTAMANHO_TIPOS_DIAS := LENGTH(vSTRING_TIPOS_DIAS) ;--novo em 9/11/21

WHILE vPARTE_ATUAL_DATAS_ESPECIAIS < vTAMANHO_DATAS_ESPECIAIS 
LOOP --WHILE 
vDATA_ESPECIAL := TO_DATE(SUBSTR(vSTRING_DATAS_ESPECIAIS,vPARTE_ATUAL_DATAS_ESPECIAIS,10),'DD/MM/YYYY');
dbms_output.put_line('--vPARTE_ATUAL_DATAS_ESPECIAIS: '||vPARTE_ATUAL_DATAS_ESPECIAIS||'vDATA_ESPECIAL: '||vDATA_ESPECIAL );

vTIPO_DIA := SUBSTR(vSTRING_TIPOS_DIAS,vPARTE_ATUAL_TIPOS_DIAS,1);--NOVO EM 9/11/21
dbms_output.put_line('--vPARTE_ATUAL_TIPOS_DIAS: '||vPARTE_ATUAL_TIPOS_DIAS||'vTIPO_DIA: '||vTIPO_DIA );--NOVO EM 9/11/21




FOR C3 IN
(
-----------------------------------------------------------------------------------------------------------------------PESSOAS COM SIT PONTO NA DATA ESPECIAL DA SMSA
--inicio----em 16/9/21--NOVA VERSAO DATA ESPECIAL baseado (sql_marcacoes_verba_dia_especial.sql)
SELECT X3.* , GN.DESCRICAO LOCAL, 
CASE 
WHEN GN.c_livre_selec10 IS NULL THEN 'DEMAIS_LOCAIS'
WHEN GN.c_livre_selec10 = '1' THEN '1-UNIDADE APS'
WHEN GN.c_livre_selec10 = '2' THEN '2-UNIDADE REDE COMP.'
WHEN GN.c_livre_selec10 = '3' THEN '3-UPA'
WHEN GN.c_livre_selec10 = '4' THEN '4-SUP'
WHEN GN.c_livre_selec10 = '5' THEN '5-CERSAM'
END CLASSIFICACAO_LOCAL,
B.cod_cargo_efetivo, CE.DESCRICAO CARGO_EFETIVO
,CC.DESCRICAO CARGO_COMISSIONADO
,F.DESCRICAO FUNCAO, B.NOME
,GN.cod_cgerenc1,GN.cod_cgerenc2,GN.cod_cgerenc3,GN.cod_cgerenc4,GN.cod_cgerenc5,GN.cod_cgerenc6
FROM(

SELECT
-- SUBSTR(X2.GRAVA_VERBA_DIA_ESPECIAL,1,3)CENARIO,
X2.EMPRESA, X2.TIPO_CONTRATO, X2.MATRICULA, COUNT(1)QUANT 
,B.cod_cargo_comiss, B.codigo_funcao, GN.C_LIVRE_SELEC10 TIPO_LOCAL, X2.AGRUPADOR
FROM (
SELECT
CASE
WHEN X.QUAL_MARCACAO = 'MARCACAO_1'    AND TRUNC(MARCACAO) =  TRUNC(DATA) AND X.SIT_PONTO_TRABALHO = 'SIM' AND X.ACEITO = 'ABONADO'                                            THEN 'SIM-5-Se tiver 1 marcações no dia da DATA ESPECIAL com JUSTIFICATIVA ABONADA'
WHEN X.QUAL_MARCACAO = 'MARCACAO_2'    AND TRUNC(MARCACAO) =  TRUNC(DATA)                                                                                                      THEN 'SIM-1e6-Se tiver um par de marcações sendo as 2 no dia da DATA ESPECIAL'
WHEN X.QUAL_MARCACAO = 'MARCACAO_2'    AND TRUNC(MARCACAO) <> TRUNC(DATA)                                                                                                      THEN 'SIM-2e10-Se tiver 2 marcações 1 sendo a ENTRADA/SAIDA no da DATA ESPECIAL e a outra ENTRADA dia ANTERIOR ou SAIDA dia SEGUINTE'
WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA'                                    AND ((X.SIT_PONTO_TRABALHO = 'SIM' AND X.ACEITO = 'ABONADO')OR SITUACAO = 'TELETRABALHO (COVID-19)')  THEN 'SIM-7-Sem marcações mas com JUSTIFICATIVA ABONADA ou OCORRENCIA ABONADA que significam TRABALHO'

WHEN X.QUAL_MARCACAO = 'MARCACAO_1'    AND TRUNC(MARCACAO) =  TRUNC(DATA) AND X.SIT_PONTO IS NULL                                                                              THEN 'NAO-3-Se tiver 1 marcação no dia da DATA ESPECIAL sem JUSTIFICATIVA'
WHEN X.QUAL_MARCACAO = 'MARCACAO_1'    AND TRUNC(MARCACAO) =  TRUNC(DATA) AND X.SIT_PONTO IS NOT NULL AND X.ACEITO <> 'ABONADO'                                                THEN 'NAO-4-Se tiver 1 marcação no dia da DATA ESPECIAL com JUSTIFICATIVA mas NÃO AVALIADA/ABONADA'
WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA'  AND TRUNC(MARCACAO) =  TRUNC(DATA) AND X.SIT_PONTO IS NOT NULL AND X.ACEITO <> 'ABONADO'                                                THEN 'NAO-8-Sem marcações mas com JUSTIFICATIVA NÃO ABONADA ou OCORRENCIA NÃO ABONADA que significam TRABALHO'
WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA'  AND TRUNC(MARCACAO) =  TRUNC(DATA) AND X.SIT_PONTO IS NOT NULL AND X.ACEITO = 'ABONADO' AND X.SIT_PONTO_TRABALHO = 'SIM'                THEN 'NAO-9-Sem marcações mas com JUSTIFICATIVA ou OCORRENCIA que NÃO significam TRABALHO abonada ou não'

WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA' AND X.ORDEM_BM = 1 AND X.H_NORMAIS = 0                                                                                                   THEN 'NAO-SEM MARCACOES NO DIA E SEM HORAS NORMAIS'
WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA' AND X.ORDEM_BM = 1 AND X.H_NORMAIS <> 0 AND X.SIT_PONTO_TRABALHO <> 'SIM'  AND X.ACEITO = 'ABONADO'                                      THEN 'NAO-SEM MARCACOES MESMO COM HORAS NORMAIS A JUSTIFICATIVA NÃO SER DE TRABALHO'
WHEN X.QUAL_MARCACAO = 'PONTO_DO_DIA' AND X.ORDEM_BM = 1 THEN '****IMPORTANTE_MAPEAR'

ELSE 'FALTA_MAPEAR_CENARIO_AINDA_INICIALMENTE_INRRELEVANTE_O_REGISTRO'
END GRAVA_VERBA_DIA_ESPECIAL,
X.* 
FROM(
SELECT ROW_NUMBER() OVER (PARTITION BY M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA ORDER BY M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA, M.DATA, M.QUAL_MARCACAO ) ORDEM_BM,  M.*
--M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA, COUNT(1) QTD_MARCACOES 
FROM (
SELECT 'PONTO_DO_DIA' QUAL_MARCACAO, NULL MARCACAO, 
E.CODIGO, E.EMPRESA, E.TIPO_CONTRATO, E.MATRICULA, E.DATA 
,E.SIT_PONTO, S.DESCRICAO, 
CASE WHEN T.DADO_ORIGEM IS NOT NULL THEN 'SIM' ELSE 'NAO' END SIT_PONTO_TRABALHO,
S.TIPO_REFERENCIA, S.TIPO_SITUACAO, s.usa_refeicao justificativa_presencial, E.SITUACAO, E.ACEITO, E.H_NORMAIS, E.AGRUPADOR
FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA E 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO S ON S.CODIGO = E.SIT_PONTO
LEFT OUTER JOIN (select DADO_ORIGEM from ARTERH.RHINTE_ED_IT_CONV  WHERE CODIGO_CONVERSAO = 'SAV3')T ON T.DADO_ORIGEM = E.SIT_PONTO
WHERE SUBSTR(E.AGRUPADOR,1,9)= '01.000095' AND TRUNC(E.DATA) = trunc(vDATA_ESPECIAL) --AND E.MARCACAO1 IS NULL AND E.MARCACAO1_ALTERADA IS NULL
UNION ALL
SELECT 'MARCACAO_1'QUAL_MARCACAO, CASE WHEN E.MARCACAO1_ALTERADA IS NOT NULL THEN E.MARCACAO1_ALTERADA ELSE E.MARCACAO1 END MARCACAO, 
E.CODIGO, E.EMPRESA, E.TIPO_CONTRATO, E.MATRICULA, E.DATA
,E.SIT_PONTO, S.DESCRICAO,
CASE WHEN T.DADO_ORIGEM IS NOT NULL THEN 'SIM' ELSE 'NAO' END SIT_PONTO_TRABALHO,
S.TIPO_REFERENCIA, S.TIPO_SITUACAO, s.usa_refeicao justificativa_presencial, E.SITUACAO, E.ACEITO, E.H_NORMAIS, E.AGRUPADOR
FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA E 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO S ON S.CODIGO = E.SIT_PONTO
LEFT OUTER JOIN (select DADO_ORIGEM from ARTERH.RHINTE_ED_IT_CONV  WHERE CODIGO_CONVERSAO = 'SAV3')T ON T.DADO_ORIGEM = E.SIT_PONTO
WHERE SUBSTR(E.AGRUPADOR,1,9)= '01.000095' AND (TRUNC(E.MARCACAO1) = trunc(vDATA_ESPECIAL) OR TRUNC(E.MARCACAO1_ALTERADA) = trunc(vDATA_ESPECIAL))
UNION ALL
SELECT 'MARCACAO_2'QUAL_MARCACAO, CASE WHEN E.MARCACAO2_ALTERADA IS NOT NULL THEN E.MARCACAO2_ALTERADA ELSE E.MARCACAO2 END MARCACAO, 
E.CODIGO, E.EMPRESA, E.TIPO_CONTRATO, E.MATRICULA, E.DATA
,E.SIT_PONTO, S.DESCRICAO, 
CASE WHEN T.DADO_ORIGEM IS NOT NULL THEN 'SIM' ELSE 'NAO' END SIT_PONTO_TRABALHO,
S.TIPO_REFERENCIA, S.TIPO_SITUACAO, s.usa_refeicao justificativa_presencial, E.SITUACAO, E.ACEITO, E.H_NORMAIS, E.AGRUPADOR
FROM PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA E 
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO S ON S.CODIGO = E.SIT_PONTO
LEFT OUTER JOIN (select DADO_ORIGEM from ARTERH.RHINTE_ED_IT_CONV  WHERE CODIGO_CONVERSAO = 'SAV3')T ON T.DADO_ORIGEM = E.SIT_PONTO
WHERE SUBSTR(E.AGRUPADOR,1,9)= '01.000095' 
AND( 
  (TRUNC(E.MARCACAO2) = trunc(vDATA_ESPECIAL) OR TRUNC(E.MARCACAO2_ALTERADA) = trunc(vDATA_ESPECIAL))--MARCACAO NO DIA
  OR
  ((TRUNC(E.MARCACAO2) = trunc(vDATA_ESPECIAL)+1 OR TRUNC(E.MARCACAO2_ALTERADA) = trunc(vDATA_ESPECIAL)+1)AND TRUNC(DATA) = trunc(vDATA_ESPECIAL) )--MARCACAO DIA SEGUINTE
  )
)M
--GROUP BY M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA ORDER BY M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA
ORDER BY M.EMPRESA, M.TIPO_CONTRATO, M.MATRICULA, M.DATA, M.QUAL_MARCACAO 
)X
--/*
)X2 
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B ON B.CODIGO_EMPRESA = X2.EMPRESA AND B.TIPO_CONTRATO = X2.TIPO_CONTRATO AND B.CODIGO = X2.MATRICULA

LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON LPAD(SUBSTR(X2.AGRUPADOR,1,2),4,0) = GN.CODIGO_EMPRESA AND SUBSTR(X2.AGRUPADOR,4,6) = GN.cod_cgerenc1 AND SUBSTR(X2.AGRUPADOR,11,6) = GN.cod_cgerenc2 AND SUBSTR(X2.AGRUPADOR,18,6) = GN.cod_cgerenc3
AND SUBSTR(X2.AGRUPADOR,25,6) = GN.cod_cgerenc4 AND SUBSTR(X2.AGRUPADOR,32,6) = GN.cod_cgerenc5 AND SUBSTR(X2.AGRUPADOR,39,6) = GN.cod_cgerenc6 --novo em 9/11/21

where SUBSTR(X2.GRAVA_VERBA_DIA_ESPECIAL,1,3) = 'SIM'----------------------------------SOMENTE CENARIO QUE SIM PODE PAGAR DATA ESPECIAL

AND B.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO AND AUX.CODIGO = B.CODIGO)

AND B.VINCULO <> '0009'--NOVO EM 9/11/21--PARA TIRAR OS ESTAGIARIOS

GROUP BY 
--SUBSTR(X2.GRAVA_VERBA_DIA_ESPECIAL,1,3),
X2.EMPRESA, X2.TIPO_CONTRATO, X2.MATRICULA ,B.cod_cargo_comiss, B.codigo_funcao ,GN.C_LIVRE_SELEC10 , X2.AGRUPADOR--NOVO EM 9/11/21
ORDER BY  X2.EMPRESA, X2.TIPO_CONTRATO, X2.MATRICULA 
--,SUBSTR(X2.GRAVA_VERBA_DIA_ESPECIAL,1,3)
--GROUP BY X2.GRAVA_VERBA_DIA_ESPECIAL ORDER BY X2.GRAVA_VERBA_DIA_ESPECIAL
--*/
--fim----em 16/9/21--NOVA VERSAO DATA ESPECIAL baseado (sql_marcacoes_verba_dia_especial.sql)

)X3 --6367
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON LPAD(SUBSTR(X3.AGRUPADOR,1,2),4,0) = GN.CODIGO_EMPRESA AND SUBSTR(X3.AGRUPADOR,4,6) = GN.cod_cgerenc1 AND SUBSTR(X3.AGRUPADOR,11,6) = GN.cod_cgerenc2 AND SUBSTR(X3.AGRUPADOR,18,6) = GN.cod_cgerenc3
AND SUBSTR(X3.AGRUPADOR,25,6) = GN.cod_cgerenc4 AND SUBSTR(X3.AGRUPADOR,32,6) = GN.cod_cgerenc5 AND SUBSTR(X3.AGRUPADOR,39,6) = GN.cod_cgerenc6 --novo em 9/11/21
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B ON B.CODIGO_EMPRESA = X3.EMPRESA AND B.TIPO_CONTRATO = X3.TIPO_CONTRATO AND B.CODIGO = X3.MATRICULA
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO CE ON CE.CODIGO = B.cod_cargo_efetivo AND CE.CODIGO_EMPRESA = B.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO CC ON CC.CODIGO = B.cod_cargo_COMISS AND CC.CODIGO_EMPRESA = B.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHPLCS_FUNCAO F ON F.CODIGO = B.CODIGO_FUNCAO AND F.CODIGO_EMPRESA = B.CODIGO_EMPRESA
WHERE
B.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO AND AUX.CODIGO = B.CODIGO)


)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--'||vCONTADOR||'-'|| C3.EMPRESA ||'-'|| C3.TIPO_CONTRATO||'-'|| C3.MATRICULA);


--novo 9/2/22
SELECT
CASE WHEN X.QUANT = 0 THEN 'N' ELSE 'S' END
INTO
vCARGO_PODE_VERBA
FROM
(SELECT COUNT(1)QUANT FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'SAV5' AND SUBSTR(DADO_ORIGEM,1,15) = C3.COD_CARGO_EFETIVO )X;


vMAIS_DADOS := CASE WHEN vTIPO_DIA = 'E' THEN 'E-DEMAIS_UNIDADES' WHEN vTIPO_DIA = 'G' THEN 'G-GERAL' WHEN vTIPO_DIA = 'U' THEN 'U-URGENCIA' END  ||'|'||C3.COD_CARGO_COMISS||'|'||C3.CARGO_COMISSIONADO||'|'||C3.COD_CARGO_EFETIVO||'|'||C3.CARGO_EFETIVO||'|'||C3.CODIGO_FUNCAO||'|'||C3.FUNCAO||'|'||C3.cod_cgerenc1||'|'||C3.cod_cgerenc2||'|'||C3.cod_cgerenc3||'|'||C3.cod_cgerenc4||'|'||C3.cod_cgerenc5||'|'||C3.cod_cgerenc6||'|'||C3.LOCAL||'|'||C3.CLASSIFICACAO_LOCAL||'|'||vCARGO_PODE_VERBA; --NOVO EM 4/2/22

/*
1	APS	UNIDADE APS
2	COM	UNIDADE REDE COMP.
3	UPA	UPA
4	SUP	SUP
5	CER	CERSAM
*/

IF vCARGO_PODE_VERBA = 'S' THEN--novo em 9/2/22

IF  (C3.cod_cargo_comiss IS NULL OR (C3.cod_cargo_comiss IS NOT NULL AND C3.cod_cargo_comiss  = '000000000000000'))AND(C3.codigo_funcao IS NULL)
--comentado em 4/2/22--AND( (C3.TIPO_LOCAL IN (1,2) AND vTIPO_DIA = 'E') OR (C3.TIPO_LOCAL IN (3,4,5) AND vTIPO_DIA = 'U') OR (C3.TIPO_LOCAL IN (1,2,3,4,5) AND vTIPO_DIA = 'G'))--NOVO EM 9/11/21
AND( ((C3.TIPO_LOCAL IN (1,2) or C3.TIPO_LOCAL IS NULL)AND vTIPO_DIA = 'E') OR (C3.TIPO_LOCAL IN (3,4,5) AND vTIPO_DIA = 'U') OR ((C3.TIPO_LOCAL IN (1,2,3,4,5) OR C3.TIPO_LOCAL IS NULL) AND vTIPO_DIA = 'G'))--NOVO EM 4/2/22
THEN
dbms_output.put_line('--OK GRAVAR DATA ESPECIAL: '||C3.EMPRESA ||'-' || C3.TIPO_CONTRATO ||'-'|| C3.MATRICULA||'-'||trunc(vDATA_ESPECIAL));
dbms_output.put_line('DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C3.EMPRESA ||''' AND TIPO_CONTRATO = ''' || C3.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C3.MATRICULA ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(vDATA_ESPECIAL) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''1193''; COMMIT;' );  
DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = 'F' AND CODIGO_EMPRESA = C3.EMPRESA AND TIPO_CONTRATO = C3.TIPO_CONTRATO AND CODIGO_CONTRATO = C3.MATRICULA AND TRUNC(DATA) = TO_DATE(vDATA_ESPECIAL,'DD/MM/YYYY') AND CODIGO_SITUACAO = '1193'; COMMIT;  
dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES ('''||C3.EMPRESA ||''','''|| C3.TIPO_CONTRATO ||''','''|| C3.MATRICULA ||''', TO_DATE('''|| trunc(vDATA_ESPECIAL) ||''',''DD/MM/YYYY''),''1193'', 1, ''F'', SYSDATE, ''IFPONTO'',''N'',''SCRIPT FECHAMENTO IFPONTO(grava_1193_DATA_ESPECIAL_SMSA_v4.sql)''); COMMIT;' );  
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES (C3.EMPRESA, C3.TIPO_CONTRATO, C3.MATRICULA,  TO_DATE(vDATA_ESPECIAL,'DD/MM/YYYY'),'1193', 1, 'F', SYSDATE, 'IFPONTO','N','PRG6_DATA_ESPECIAL_SMSA'); COMMIT;  

vLOG := 'OK GRAVAR DATA ESPECIAL|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||C3.NOME||'|'||trunc(vDATA_ESPECIAL);

--ELSIF C3.SOMA_TRABALHO_DATA_ESPECIAL = 0 THEN
--dbms_output.put_line('--PESSOA NAO TEVE SIT PONTO REFERENTE A TRABALHO GRAVA NO ARTERH NO DIA DA DATA ESPECIAL: '||C3.CODIGO_EMPRESA ||'-' || C3.TIPO_CONTRATO ||'-'|| C3.CODIGO_CONTRATO||'-'||trunc(vDATA_ESPECIAL));

ELSIF (C3.cod_cargo_comiss IS NOT NULL AND C3.cod_cargo_comiss  <> '000000000000000' )OR (C3.codigo_funcao IS NOT NULL ) THEN
dbms_output.put_line('--PESSOA COM CARGO COMISSIONADO/FUNCAO PUBLICA: '||C3.EMPRESA ||'-' || C3.TIPO_CONTRATO ||'-'|| C3.MATRICULA||'-'||trunc(vDATA_ESPECIAL));
vLOG := 'PESSOA COM CARGO COMISSIONADO/FUNCAO PUBLICA|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||C3.NOME||'|'||trunc(vDATA_ESPECIAL);

ELSIF  (C3.cod_cargo_comiss IS NULL OR (C3.cod_cargo_comiss IS NOT NULL AND C3.cod_cargo_comiss  = '000000000000000'))AND(C3.codigo_funcao IS NULL)
--comentado em 4/2/22--AND( (C3.TIPO_LOCAL IN (3,4,5) AND vTIPO_DIA = 'E') OR (C3.TIPO_LOCAL IN (1,2) AND vTIPO_DIA = 'U') OR (C3.TIPO_LOCAL IS NULL ))--NOVO EM 9/11/21
AND( (C3.TIPO_LOCAL IN (3,4,5) AND vTIPO_DIA = 'E') OR ((C3.TIPO_LOCAL IN (1,2) OR C3.TIPO_LOCAL IS NULL) AND vTIPO_DIA = 'U') )--NOVO EM 4/2/22
THEN
dbms_output.put_line('--TIPO LOCAL NAO TEM DIREITO DEVIDO AO TIPO DE DIA NO CALENDARIO|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||trunc(vDATA_ESPECIAL));
--dbms_output.put_line('--DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C3.EMPRESA ||''' AND TIPO_CONTRATO = ''' || C3.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C3.MATRICULA ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(vDATA_ESPECIAL) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''1193''; COMMIT;' );  --apenas para ajuste no mes de setembro
vLOG := 'TIPO LOCAL NAO TEM DIREITO DEVIDO AO TIPO DE DIA NO CALENDARIO|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||C3.NOME||'|'||trunc(vDATA_ESPECIAL);

ELSE
dbms_output.put_line('--CENARIO NAO MAPEADO AINDA|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||trunc(vDATA_ESPECIAL));
vLOG := 'CENARIO NAO MAPEADO AINDA|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||C3.NOME||'|'||trunc(vDATA_ESPECIAL);
END IF;

ELSE
dbms_output.put_line('--CARGO EFETIVO NAO TEM DIREITO A DATA ESPECIAL |'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||trunc(vDATA_ESPECIAL));
--dbms_output.put_line('--DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C3.EMPRESA ||''' AND TIPO_CONTRATO = ''' || C3.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C3.MATRICULA ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(vDATA_ESPECIAL) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''1193''; COMMIT;' );  --apenas para ajuste no mes de setembro
vLOG := 'CARGO EFETIVO NAO TEM DIREITO A DATA ESPECIAL|'||C3.EMPRESA ||'|' || C3.TIPO_CONTRATO ||'|'|| C3.MATRICULA||'|'||C3.NOME||'|'||trunc(vDATA_ESPECIAL);
END IF;



dbms_output.put_line('--vLOG: '||vLOG|| ' vMAIS_DADOS: '||vMAIS_DADOS);

INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES, CAMPO_2)
VALUES(C3.EMPRESA,C3.TIPO_CONTRATO,C3.MATRICULA, SYSDATE,'PRG6_DATA_ESPECIAL_SMSA' ,vLOG||'|'||vMAIS_DADOS, vDATA_ESPECIAL );COMMIT;


vLOG := NULL;
vMAIS_DADOS := NULL; --NOVO EM 4/2/22
vCARGO_PODE_VERBA := NULL; --novo 9/2/22

END LOOP;--C3
--*/

--FIM-------PESSOAS QUE TIVERAM MARCACAO NO DIA DE DATA ESPECIAL

vPARTE_ATUAL_DATAS_ESPECIAIS := vPARTE_ATUAL_DATAS_ESPECIAIS +10 ;
vPARTE_ATUAL_TIPOS_DIAS := vPARTE_ATUAL_TIPOS_DIAS +1 ;--NOVO EM 9/11/21
END LOOP;--WHILE 
--FIM------------------------------------------------------2ª PARTE ----------GRAVAR AS SIT PONTO


END;

END;