
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRG7_ADICIONAL_NOTURNO" (DATA_INICIO IN DATE, DATA_FIM IN DATE)AS
BEGIN
--novo em 7/6/21 Kellysson
-----TIPO VERBA: Adicional Noturno----TROCAR DATAS

DECLARE               
vCONTADOR NUMBER; 
vNUMERO NUMBER  ;
vSTRING VARCHAR2(100 BYTE);
vLOG VARCHAR2(4000);

vDATA_INICIO DATE;
vDATA_FIM DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR := 0;
vNUMERO := 0;
vSTRING := NULL;
vLOG := NULL;

vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

--CABECALHO DO LOG
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES)
VALUES(NULL,NULL,NULL, SYSDATE,'PRG7_ADICIONAL_NOTURNO',
'RESULTADO_FINAL_PROCESSAMENTO|EMPRESA|TIPO_CONTRATO|CONTRATO|NOME|DATA|H_NOTURMA_SEM_FATOR|CARGO_COMISSIONADO|CARGO_EFETIVO'
);COMMIT;

FOR C1 IN(

SELECT
CASE WHEN X.H_NOTURMA_SEM_FATOR > 7 THEN 7 ELSE X.H_NOTURMA_SEM_FATOR END H_NOTURMA_SEM_FATOR_AJUSTE,
X.* FROM(
SELECT 
B.NOME, C.DESCRICAO CARGO_COMISSIONADO, CE.DESCRICAO CARGO_EFETIVO,
B.CODIGO_EMPRESA, B.TIPO_CONTRATO, B.CODIGO BM, b.cod_cargo_comiss, B.codigo_funcao,
E.EMPRESA, E.TIPO_CONTRATO TIPO_CONTR, E.MATRICULA, E.DATA, E.H_NOTURNA, E.H_NOTURNA*0.875 H_NOTURMA_SEM_FATOR, E.H_EXTRA_NOTURNA,  E.MARCACAO1, E.MARCACAO2, E.MARCACAO3, E.MARCACAO4,
E.CODIGO, E.SIT_PONTO, E.DTCADASTRO, E.COD_PESSOA, E.COD_JUSTIFICATIVA_PONTO, E.COD_PONTO_FECHAMENTO, E.COD_BANCO_HORAS, E.COD_CARGO, E.COD_UNIDADE, E.COD_EMPRESA, E.COD_HORARIO,
E.COD_ESCALA_PADRAO, E.CAMPO_LIVRE,  E.MARCACAO5, E.MARCACAO6, E.MARCACAO7, E.MARCACAO8, E.MARCACAO9, E.MARCACAO10, E.MARCACAO11, E.MARCACAO12, E.MARCACAO_E1, 
E.MARCACAO_E2, E.MARCACAO_E3, E.MARCACAO_E4, E.MARCACAO_E5, E.MARCACAO_E6, E.MARCACAO_E7, E.MARCACAO_E8, E.MARCACAO_E9, E.MARCACAO_E10, E.MARCACAO_E11, E.MARCACAO_E12, E.MARCACAO1_ALTERADA, E.MARCACAO2_ALTERADA,
E.MARCACAO3_ALTERADA, E.MARCACAO4_ALTERADA, E.MARCACAO5_ALTERADA, E.MARCACAO6_ALTERADA, E.MARCACAO7_ALTERADA, E.MARCACAO8_ALTERADA, E.MARCACAO9_ALTERADA, E.MARCACAO10_ALTERADA, E.MARCACAO11_ALTERADA, E.MARCACAO12_ALTERADA,
E.OBS_MARCACAO_ALTERADA, E.SITUACAO, E.ENTRADA, E.BANCO_HORAS, E.TIPO_BANCO_HORAS, E.OBS, E.ACEITO, E.H_NORMAIS, E.DESCONTO, E.H_EXTRA_FERIADO,  E.H_EXTRA,  E.COMPENSADO, E.FALTA_COMPENSAR, E.PREVISTO, E.DESCONTO_ABONADO,
E.HORAS_ABONADA, E.ATRASO, E.SAIDA_ANTECIPADA, E.H_INTRA_JORNADA, E.DESCONTO_AUX, E.INTERJORNADA, E.BH_CREDITO, E.BH_DEBITO, E.BIT_DIVERGENCIA, E.COD_COMPENSACAO, E.MULTIPLICADOR_BANCO_HORAS, 
E.NA009, E.DTJUSTIFICATIVA, E.LOGIN_JUSTIFICATIVA, E.DTAVALIADOR, E.LOGIN_AVALIADOR, E.DTALTERACAO, E.LOGIN_ALTERACAO, E.FOTO, E.SOBREAVISO_DOBRA, E.TOTAIS,
E.COD_JUSTIFICATIVA_BANCO_HORAS, E.DESCRICAO_BANCO_HORAS, E.COMPROVANTE_JUSTIFICATIVA, E.RELATORIO_RH_VALIDADO, E.DESCONTO_TOLERADO, E.INTERVALO_A_MENOR, E.ENTRADA_ANTECIPADA, E.MULTA_INTERJORNADA, E.EXTRA_DIA_INFO_SEM_MENSAL,
E.DESCONTO_DIA_INFO_SEM_MENSAL, E.TIPO_FOLGA, E.CARGA_HORARIA, E.DATA_PROCESSAMENTO, E.TIPO_ESCALA, E.AGRUPADOR, 
E.TIPO_SOBREAVISO, E.HRINICIO_SOBREAVISO, E.HRFIM_SOBREAVISO, E.PREVISTO_SOBREAVISO, E.EXECUTADO_SOBREAVISO, E.COD_TIPO_PESSA
FROM 
PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA E
LEFT OUTER JOIN PONTO_ELETRONICO.AUTORIZACAO_EXTRA_PESSOA A ON A.COD_PESSOA = E.COD_PESSOA AND TRUNC(E.DATA) BETWEEN TRUNC(A.DTINICIO) AND TRUNC(A.DTFIM)
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B ON LPAD(E.EMPRESA,4,0) = B.CODIGO_EMPRESA AND E.TIPO_CONTRATO = B.TIPO_CONTRATO AND LPAD(E.MATRICULA,15,0) = B.CODIGO
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON B.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND B.COD_CUSTO_GERENC1 = GN.cod_cgerenc1 AND B.COD_CUSTO_GERENC2 = GN.cod_cgerenc2 AND B.COD_CUSTO_GERENC3 = GN.cod_cgerenc3
AND B.COD_CUSTO_GERENC4 = GN.cod_cgerenc4 AND B.COD_CUSTO_GERENC5 = GN.cod_cgerenc5 AND B.COD_CUSTO_GERENC6 = GN.cod_cgerenc6
left outer join ARTERH.RHPLCS_CARGO C ON c.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND c.CODIGO = b.cod_cargo_comiss
left outer join ARTERH.RHPLCS_CARGO CE ON Ce.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND Ce.CODIGO = b.cod_cargo_efetivo
WHERE 
B.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO AND AUX.CODIGO = B.CODIGO) 
--testes-- AND E.DATA_PROCESSAMENTO IS NULL 
AND TRUNC(E.DATA) BETWEEN TO_DATE(vDATA_INICIO,'DD/MM/YYYY')AND TO_DATE(vDATA_FIM,'DD/MM/YYYY') ------------------------------trocar datas
AND (E.H_NOTURNA > 0 /*or E.H_EXTRA_NOTURNA > 0*/)-------------------------------------------NOVO REFERENTE ADICIONAL NOTURNO
AND B.VINCULO <> '0009'--NOVO EM 9/11/21--PARA TIRAR OS ESTAGIARIOS
AND LPAD(E.EMPRESA,4,'0') IN (SELECT DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'IFP4')--NOVO EM 7/11/23
/* --INICIO --comentado em 4/2/22 email (TOM CARE-P - DEZEMBRO DE 2021)
AND 
(B.COD_CUSTO_GERENC1 = '000095'
OR CE.DESCRICAO LIKE '%GUARDA%'--NOVO EM 11/12/21
OR CE.DESCRICAO LIKE '%SUBINSPETOR%'--NOVO EM 6/1/22
)*/--FIM --comentado em 4/2/22

--testes 4/2/22 INICIO--pegar quem não esta lotacao na SMSA e não ser GUARDA/SUBSINSPETOR
/*
AND 
(B.COD_CUSTO_GERENC1 <> '000095'
and (CE.DESCRICAO NOT  LIKE '%GUARDA%'--NOVO EM 11/12/21
and CE.DESCRICAO not LIKE '%SUBINSPETOR%')--NOVO EM 6/1/22
and 
COD_CARGO_COMISS = '000000000000000' and  CODIGO_FUNCAO is null
)*/--testes 4/2/22 FIM--pegar quem não esta lotacao na SMSA e não ser GUARDA/SUBSINSPETOR

--and B.CODIGO = '00000000036281X' teste
ORDER BY E.EMPRESA, E.TIPO_CONTRATO, E.MATRICULA, E.DATA
)X



)
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--'||vCONTADOR);

IF C1.H_NOTURMA_SEM_FATOR_AJUSTE <> 0 AND (C1.cod_cargo_comiss IS NOT NULL AND C1.cod_cargo_comiss  = '000000000000000' )AND(C1.codigo_funcao IS NULL ) THEN
vNUMERO := ROUND(TO_NUMBER(C1.H_NOTURMA_SEM_FATOR_AJUSTE),2) ;
dbms_output.put_line('vNUMERO: '||vNUMERO);
vSTRING := CASE WHEN INSTR(vNUMERO,',',1,1) = 0 THEN TO_CHAR(vNUMERO) WHEN INSTR(vNUMERO,',',1,1) <> 0 THEN TO_CHAR(SUBSTR(vNUMERO,1,INSTR(vNUMERO,',',1,1)-1) ||'.'||SUBSTR(vNUMERO,INSTR(vNUMERO,',' ,1,1)+1, LENGTH(vNUMERO))) end ;
dbms_output.put_line('DELETE RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = ''F'' AND CODIGO_EMPRESA = ''' ||C1.CODIGO_EMPRESA ||''' AND TIPO_CONTRATO = ''' || C1.TIPO_CONTRATO ||''' AND CODIGO_CONTRATO = '''|| C1.BM ||''' AND TRUNC(DATA) = TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY'') AND CODIGO_SITUACAO = ''1009''; COMMIT;' );  
DELETE ARTERH.RHPONT_RES_SIT_DIA WHERE TIPO_APURACAO = 'F' AND CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CODIGO_CONTRATO = C1.BM AND TRUNC(DATA) = C1.DATA AND CODIGO_SITUACAO = '1009'; COMMIT; 
dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES ('''||C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.BM ||''', TO_DATE('''|| trunc(C1.DATA) ||''',''DD/MM/YYYY''),''1009'','|| vSTRING ||', ''F'', SYSDATE, ''IFPONTO'',''N'',''SCRIPT FECHAMENTO IFPONTO(gravar_ADICIONAL_NOTURNO.sql)''); COMMIT;' );  
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, FORCA_SITUACAO, TEXTO_ASSOCIADO) VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.BM, C1.DATA, '1009', vNUMERO , 'F', SYSDATE, 'IFPONTO', 'N','PRG7_ADICIONAL_NOTURNO'); COMMIT;
vLOG := 'GEROU VERBA DE HORAS NOTURNAS|'||C1.CODIGO_EMPRESA ||'|' || C1.TIPO_CONTRATO ||'|'|| C1.BM ||'|'||C1.NOME||'|'||TRUNC(C1.DATA)||'|'||C1.H_NOTURMA_SEM_FATOR_AJUSTE||'|'||C1.CARGO_COMISSIONADO||'|'||C1.CARGO_EFETIVO;
ELSE
dbms_output.put_line('--PESSOA COM CARGO COMISSIONADO/FUNCAO PUBLICA'||C1.CODIGO_EMPRESA ||'-' || C1.TIPO_CONTRATO ||'-'|| C1.BM||'-'||TRUNC(C1.DATA)||'-'||C1.H_NOTURMA_SEM_FATOR_AJUSTE);
vLOG := 'NAO GEROU SITUACAO, PESSOA COM CARGO COMISSIONADO/FUNCAO PUBLICA|'||C1.CODIGO_EMPRESA ||'|'|| C1.TIPO_CONTRATO ||'|'|| C1.BM ||'|'||C1.NOME||'|'||TRUNC(C1.DATA)||'|'||C1.H_NOTURMA_SEM_FATOR_AJUSTE||'|'||C1.CARGO_COMISSIONADO||'|'||C1.CARGO_EFETIVO;
END IF;

dbms_output.put_line('--vLOG: '||vLOG);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA_DADOS, CAMPO_1, CONSIDERACOES)
VALUES(C1.EMPRESA,C1.TIPO_CONTRATO,C1.BM, SYSDATE,'PRG7_ADICIONAL_NOTURNO' ,vLOG);COMMIT;
vLOG := NULL;

END LOOP;

END;

END;
