
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."PRG_SIT_PONTO_AFASTAMENTOS_ARTE" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN
--KELLYSSON AJUSTE EM 12/9/23 EMAIL (Re: DIVERGENCIA CT02 E CADASTRO DE FÉRIAS)
--Kellysson ajuste em 4/7/23 email (Re: Lançamento - À disposição - Carina Polastri BM 106753-0) ajuste DATA_INICIO_SIT_PONTO
--em 14/9/21 incluido as 4 ultimas empresas unificadas
----_v2 em 24/8/21 para ajustes de cessoes e outros casos fora baseado email Lilian Rabelo (Conversão de Situações de ponto para contagem de tempo)
--criado em 31/5/21 para unir (simulador_ifpontov4.sql/simulador_ifpontov5.sql)com logicas semelhantes e corrigir erro nos locais de cessao


--EM 19/8/20 FICARA PARA OS LOCAIS DA EMPRESA 1 QUE NÃO ESTAO USANDO O FECHAMENTO IFPONTO
--em 13/8/20 VERSÃO 5 justificou devido aos fechamentos de apuração por locais, tendo mais de uma data dentro da PBH
--VERSÃO 4 justificou devido as situações funcionais sem data fim
---****************************TROCAR DATAS
--KELLYSSON EM 21/10/19 continuando em 29/10/19
--/*
declare 
vCONTADOR NUMBER;
data_inicial date;
data_final date;
num_dias number;
vDATA_DIA date;

vDT_INI_PERIODO DATE;
vDT_FIM_PERIODO DATE;

vULT_DIA_FECHA_GERAL_FREQ DATE; 

begin
dbms_output.enable(null);
vCONTADOR :=0;

vDT_INI_PERIODO := TO_DATE(DATA_INICIO,'DD/MM/YY'); -------------ALTERAR DATAS
vDT_FIM_PERIODO := TO_DATE(DATA_FIM,'DD/MM/YY');-------------ALTERAR DATAS

--fechamento geral frequencia (locais ainda fora do fechamento Ifponto)
SELECT MAX(x.data_fim_folha) INTO vULT_DIA_FECHA_GERAL_FREQ
from RHPONT_APUR_AGRUP x where x.codigo_empresa = '0001' and x.tipo_apur = 'F' AND c_livre_selec01 = 2 AND id_agrup = 152123;

for c1 in(



SELECT 
I.*,
X3.DATA_USAR, X3.DESCRICAO_VW, X3.DATA_EXTINCAO, X3.ULTIMA_DATA_INI_FOLHA, X3.ULTIMA_DATA_FIM_FOLHA, X3.ORDEM_BM, X3.DADO_ORIGEM_VW, X3.DADO_DESTINO_VW, X3.LOCAL1_VW, X3.LOCAL2_VW, X3.LOCAL3_VW, X3.LOCAL4_VW, X3.LOCAL5_VW, X3.LOCAL6_VW, 
X3.TIPO, X3.CODIGO_EMPRESA, X3.TIPO_CONTRATO, X3.CONTRATO, X3.CODIGO, X3.DESCRICAO, X3.CONTROLE_FOLHA, X3.COD_SIT_PONTO, X3.SITUACAO_PONTO, X3.DATA_INICIO, X3.DATA_FIM, X3.LOGIN_USUARIO, X3.DT_ULT_ALTER_USUA, X3.DATA_INICIO_SIT_PONTO, X3.DATA_FIM_SIT_PONTO, 
X3.COD_CUSTO_GERENC1, X3.COD_CUSTO_GERENC2, X3.COD_CUSTO_GERENC3, X3.COD_CUSTO_GERENC4, X3.COD_CUSTO_GERENC5, X3.COD_CUSTO_GERENC6, X3.DT_EXTINCAO_LOCAL_FREQU, 
X3.COD_CUSTO_CONTAB1, X3.COD_CUSTO_CONTAB2, X3.COD_CUSTO_CONTAB3, X3.COD_CUSTO_CONTAB4, X3.COD_CUSTO_CONTAB5, X3.COD_CUSTO_CONTAB6, X3.DT_EXTINCAO_LOCAL_ORIGEM, 
X3.CGC_LOCAL, X3.SIT_FUNC_LOCAL, X3.SIT_PONT_LOCAL, X3.DADO_DESTINO, X3.SIT_FUNC_CESSAO, X3.SITUACAO_FUN_CESSAO, X3.SIT_PONTO_SIT_FUNC
,X3.cod_cargo_comiss, C.DESCRICAO CARGO_COMISSIONADO, X3.cod_cargo_efetivo, E.DESCRICAO CARGO_EFETIVO
FROM(

SELECT 
L.DATA_USAR, L.DESCRICAO DESCRICAO_vw, L.DATA_EXTINCAO,
X2.* 
--COMENTADO EM 4/7/23 --,CASE WHEN X2.DATA_INICIO < X2.ULTIMA_DATA_INI_FOLHA THEN X2.ULTIMA_DATA_INI_FOLHA ELSE X2.DATA_INICIO END DATA_INICIO_SIT_PONTO 
--COMENTADO 12/9/23 EMAIL(Re: DIVERGENCIA CT02 E CADASTRO DE FÉRIAS)--,CASE WHEN TRUNC(X2.DT_ULT_ALTER_USUA) >= TO_DATE('01/'||LPAD((EXTRACT(MONTH FROM X2.ULTIMA_DATA_INI_FOLHA)-1),2,0)||'/'||EXTRACT(YEAR FROM X2.ULTIMA_DATA_INI_FOLHA),'DD/MM/YY') THEN X2.DATA_INICIO ELSE X2.ULTIMA_DATA_INI_FOLHA END DATA_INICIO_SIT_PONTO --novo em 4/7/23
,CASE --novo em 12/9/23
WHEN TRUNC(X2.DT_ULT_ALTER_USUA) >= TO_DATE('01/'||LPAD((EXTRACT(MONTH FROM X2.ULTIMA_DATA_INI_FOLHA)-1),2,0)||'/'||EXTRACT(YEAR FROM X2.ULTIMA_DATA_INI_FOLHA),'DD/MM/YY') AND TRUNC(X2.DATA_INICIO) < TRUNC(X2.ULTIMA_DATA_INI_FOLHA) 
                                                                                                                                                            THEN X2.DATA_INICIO 
WHEN TRUNC(X2.DT_ULT_ALTER_USUA) < TO_DATE('01/'||LPAD((EXTRACT(MONTH FROM X2.ULTIMA_DATA_INI_FOLHA)-1),2,0)||'/'||EXTRACT(YEAR FROM X2.ULTIMA_DATA_INI_FOLHA),'DD/MM/YY') AND TRUNC(X2.DATA_INICIO) < TRUNC(X2.ULTIMA_DATA_INI_FOLHA) 
                                                                                                                                                            THEN X2.ULTIMA_DATA_INI_FOLHA 
ELSE X2.DATA_INICIO END DATA_INICIO_SIT_PONTO --novo em 12/9/23
,CASE WHEN X2.DATA_FIM > X2.ULTIMA_DATA_FIM_FOLHA THEN X2.ULTIMA_DATA_FIM_FOLHA ELSE X2.DATA_FIM END DATA_FIM_SIT_PONTO
,C.cod_cargo_comiss, C.cod_cargo_efetivo
,C.COD_CUSTO_GERENC1, C.COD_CUSTO_GERENC2, C.COD_CUSTO_GERENC3, C.COD_CUSTO_GERENC4, C.COD_CUSTO_GERENC5, C.COD_CUSTO_GERENC6, GN.DATA_EXTINCAO DT_EXTINCAO_LOCAL_FREQU
,C.cod_custo_contab1, C.cod_custo_contab2, C.cod_custo_contab3, C.cod_custo_contab4, C.cod_custo_contab5, C.cod_custo_contab6, CC.DATA_EXTINCAO DT_EXTINCAO_LOCAL_ORIGEM
,SPD.*
FROM 
(--INICIO X2
SELECT 
----------------------------------------------------------------INICIO-----PARA SABER PERIODO A SER PROCESSADO NA SITUAÇAO DE PONTO BASEADO NO ULTIMO FECHAMENTO IFPONTO CADASTRADO NO ARTERH
--TO_DATE('01/12/22','DD/MM/YY')
TO_DATE(vDT_INI_PERIODO,'DD/MM/YY') 
ULTIMA_DATA_INI_FOLHA,
--TO_DATE('31/12/22','DD/MM/YY')
TO_DATE(vDT_FIM_PERIODO,'DD/MM/YY') 
ULTIMA_DATA_FIM_FOLHA,
----------------------------------------------------------------FIM-----PARA SABER PERIODO A SER PROCESSADO NA SITUAÇAO DE PONTO BASEADO NO ULTIMO FECHAMENTO IFPONTO CADASTRADO NO ARTERH
ROW_NUMBER() OVER   (PARTITION BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CONTRATO ORDER BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CONTRATO, X.DATA_INICIO) AS ORDEM_BM,
--SPD.*,C.COD_CUSTO_GERENC1, C.COD_CUSTO_GERENC2, C.COD_CUSTO_GERENC3, C.COD_CUSTO_GERENC4, C.COD_CUSTO_GERENC5, C.COD_CUSTO_GERENC6,
SFC.DADO_ORIGEM DADO_ORIGEM_VW, SFC.DADO_DESTINO DADO_DESTINO_VW, 
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab1 ELSE  CX.cod_custo_gerenc1 END LOCAL1_VW,
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab2 ELSE  CX.cod_custo_gerenc2 END LOCAL2_VW,
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab3 ELSE  CX.cod_custo_gerenc3 END LOCAL3_VW,
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab4 ELSE  CX.cod_custo_gerenc4 END LOCAL4_VW,
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab5 ELSE  CX.cod_custo_gerenc5 END LOCAL5_VW,
CASE WHEN SUBSTR(SFC.DADO_DESTINO,1,6) = 'ORIGEM'  THEN CX.cod_custo_contab6 ELSE  CX.cod_custo_gerenc6 END LOCAL6_VW,
X.* 
--, TEG4.DADO_ORIGEM, TEG4.DADO_DESTINO COD_SIT_PONTO_DIFERENCIADA COMENGADO EM 31/5/21
FROM ----------------------inicio X
(------------------------------------------------INICIO DO UNION
select  'ALT_SIT_FUNC' TIPO, A.CODIGO_EMPRESA, A.TIPO_CONTRATO, A.CODIGO CONTRATO, A.COD_SIT_FUNCIONAL CODIGO, SF.DESCRICAO DESCRICAO, SF.CONTROLE_FOLHA,
SF.SITUACAO_PONTO COD_SIT_PONTO, SP.DESCRICAO SITUACAO_PONTO, 
A.DATA_INIC_SITUACAO DATA_INICIO, 
--A.DATA_FIM_SITUACAO DATA_FIM
CASE WHEN A.DATA_FIM_SITUACAO IS NULL THEN  TO_DATE(vDT_FIM_PERIODO,'DD/MM/YY')--TO_DATE('31/12/22','DD/MM/YY')-- TO_DATE('31/12/22','DD/MM/YY')--
ELSE A.DATA_FIM_SITUACAO END DATA_FIM --NOVO EM 31/7/20
,A.LOGIN_USUARIO, A.DT_ULT_ALTER_USUA
from ARTERH.RHCGED_ALT_SIT_FUN A 
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO = A.COD_SIT_FUNCIONAL
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON SP.CODIGO = SF.SITUACAO_PONTO
WHERE 
--SF.CONTROLE_FOLHA IN ('L','M')
SF.SITUACAO_PONTO is not null
--INICIO --NOVO EM 31/7/20 PARA GRAVAR SIT PONTO EM SIT FUNC QUE NÃO HÁ DATA FIM DEFINIDA
AND (SF.data_fim_vigencia IS NULL OR SF.data_fim_vigencia > TO_DATE(vDT_INI_PERIODO,'DD/MM/YY')-- TO_DATE('01/12/22','DD/MM/YY')-- TO_DATE('01/12/22','DD/MM/YY')--
)
AND (A.DATA_FIM_SITUACAO IS NOT NULL   
OR (A.DATA_FIM_SITUACAO IS NULL AND SF.CONTROLE_FOLHA IN ('N','O') AND SF.SITUACAO_PONTO IS NOT NULL))
--FIM--NOVO EM 31/7/20 PARA GRAVAR SIT PONTO EM SIT FUNC QUE NÃO HÁ DATA FIM DEFINIDA

UNION ALL

SELECT  'FERIAS' TIPO, FE.CODIGO_EMPRESA, FE.TIPO_CONTRATO, FE.CODIGO_CONTRATO CONTRATO, PF.CODIGO CODIGO, PF.DESCRICAO DESCRICAO, NULL CONTROLE_FOLHA,
SP.CODIGO COD_SIT_PONTO, SP.DESCRICAO SITUACAO_PONTO, 
FE.dt_ini_gozo DATA_INICIO, 
CASE
    WHEN FE.STATUS_CONFIRMACAO in ('5','D')
    THEN
      (SELECT MAX(DT.DATA_DIA)
      FROM RHFERI_FERIAS F,
        ARTERH.RHTABS_DATAS DT
      WHERE F.CODIGO_EMPRESA = FE.CODIGO_EMPRESA
      AND F.TIPO_CONTRATO = FE.TIPO_CONTRATO
      AND F.DT_INI_AQUISICAO = FE.DT_INI_AQUISICAO
      AND F.DT_FIM_AQUISICAO = FE.DT_FIM_AQUISICAO
      AND F.CODIGO_CONTRATO = FE.codigo_contrato
      AND DT.DATA_DIA BETWEEN FE.DT_INI_GOZO AND FE.DT_RETORNO-1
      AND F.STATUS_CONFIRMACAO =FE.STATUS_CONFIRMACAO
      AND DT.DATA_DIA NOT IN
        (SELECT D.DATA_DIA
        FROM ARTERH.RHPARM_CALEND_DT D
        WHERE D.CODIGO  = '0001'
        AND DT.DATA_DIA = D.DATA_DIA))
        else FE.DT_FIM_GOZO
  END
DATA_FIM
,FE.LOGIN_USUARIO, FE.DT_ULT_ALTER_USUA

FROM ARTERH.RHFERI_FERIAS FE
LEFT OUTER JOIN RHPARM_P_FERI PF ON PF.CODIGO_EMPRESA = FE.CODIGO_EMPRESA AND PF.CODIGO = FE.TIPO_FERIAS
LEFT OUTER JOIN RHPONT_SITUACAO SP ON SP.CODIGO = PF.SITUACAO_PONTO
WHERE
fe.STATUS_CONFIRMACAO in ('1','5','D','G')
and FE.dt_ini_gozo is not null and FE.dt_fim_gozo is not null


)X ----------------FIM X
--INICIO NOVO EM 3/8/21--------------------------------
LEFT OUTER JOIN (SELECT A.* FROM ARTERH.RHPESS_CONTRATO A WHERE A.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA)FROM RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = A.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = A.TIPO_CONTRATO AND AUX.CODIGO = A.CODIGO)
)CX ON CX.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND CX.TIPO_CONTRATO = X.TIPO_CONTRATO AND CX.CODIGO = X.CONTRATO
LEFT OUTER JOIN (SELECT SFC.DADO_DESTINO, SFC.DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV SFC WHERE SFC.codigo_conversao = 'CESS')SFC ON SFC.DADO_ORIGEM = X.CODIGO
--FIM NOVO EM 3/8/21----------------------------------------

------------------------------------------------FIM DO UNION

/*----------------------------------INICIO COMENTADO EM  31/5/21 POIS HAVIA ERROS NA CESSAO
----------------------INICIO--novo em 29/11/19 para diferenciar SITUAÇÃO PONTO nas CESSÕES referente a CONTAGEM DE TEMPO
LEFT OUTER JOIN RHPESS_CONTRATO C ON C.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND C.TIPO_CONTRATO = X.TIPO_CONTRATO AND C.CODIGO = X.CONTRATO
LEFT OUTER JOIN (SELECT * FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO = 'TEG4')TEG4 ON SUBSTR(TEG4.DADO_ORIGEM,37,40) = X.CODIGO AND SUBSTR(TEG4.DADO_ORIGEM,1,36)= C.COD_CUSTO_GERENC1||C.COD_CUSTO_GERENC2||C.COD_CUSTO_GERENC3||C.COD_CUSTO_GERENC4||C.COD_CUSTO_GERENC5||C.COD_CUSTO_GERENC6
WHERE 
C.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO = C.CODIGO)
AND 
----------------------FIM--novo em 29/11/19 para diferenciar SITUAÇÃO PONTO nas CESSÕES referente a CONTAGEM DE TEMPO
*/---------------------------FIM COMENTADO EM  31/5/21 POIS HAVIA ERROS NA CESSAO

where
X.COD_SIT_PONTO IS NOT NULL ----------------------------SOMENTE REGISTROS DE FERIAS E SIT FUNC QUE POSSUEM SITUACAO DE PONTO VINCULADP
AND (X.DATA_FIM IS NOT NULL   ----------------------------------DATA FIM DESTES LANÇAMENTOS NÃO ESTA NULA
/*OR (X.DATA_FIM IS NOT NULL AND X.CONTROLE_FOLHA IN ('N','O') AND X.COD_SIT_PONTO IS NOT NULL))*/--NOVO EM 31/7/20 PARA GRAVAR SIT PONTO EM SIT FUNC QUE NÃO HÁ DATA FIM DEFINIDA
OR (X.CONTROLE_FOLHA IN ('N','O') AND X.COD_SIT_PONTO IS NOT NULL)--NOVO EM 31/7/20 PARA GRAVAR SIT PONTO EM SIT FUNC QUE NÃO HÁ DATA FIM DEFINIDA
)
and------------------------------------------------------------ PERIODO INICIO E FIM DO AFASTAMENTO/FERIAS DENTRO DO PERIODO QUE DEVE SER CARIMBADO, OU SEJA O ULTIMO REGISTRO CRIADO DE FECHAMENTO
(x.data_inicio between TO_DATE(vDT_INI_PERIODO,'DD/MM/YY') AND TO_DATE(vDT_FIM_PERIODO,'DD/MM/YY')-- TO_DATE('01/12/22','DD/MM/YY')AND TO_DATE('31/12/22','DD/MM/YY')--TO_DATE('01/12/22','DD/MM/YY') AND TO_DATE('31/12/22','DD/MM/YY')
OR x.data_fim between TO_DATE(vDT_INI_PERIODO,'DD/MM/YY') AND TO_DATE(vDT_FIM_PERIODO,'DD/MM/YY')--TO_DATE('01/12/22','DD/MM/YY')AND TO_DATE('31/12/22','DD/MM/YY')--TO_DATE('01/12/22','DD/MM/YY') AND TO_DATE('31/12/22','DD/MM/YY')--
-------------------------INICIO-----PARTE NOVA EM 20/11/19
OR 
(trunc(X.DATA_INICIO) <= TO_DATE(vDT_INI_PERIODO,'DD/MM/YY')--to_date('01/12/22','dd/mm/yy') --TO_DATE('01/12/22','DD/MM/YY')
AND trunc(X.DATA_FIM)>= TO_DATE(vDT_FIM_PERIODO,'DD/MM/YY')--to_date('31/12/22','dd/mm/yy')--TO_DATE('31/12/22','DD/MM/YY')
)
-------------------------FIM-----PARTE NOVA EM 20/11/19
)
--AND X.CONTRATO IN ('000000000293486','000000000005508')--TESTES 3/8/21
ORDER BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO,  x.codigo, X.CONTRATO, X.DATA_INICIO, X.TIPO
)X2
------------------------------------------------------------------------------INICIO EM 31/5/21 NOVA PARTE DE CESSAO
LEFT OUTER JOIN ARTERH.rhpess_contrato c ON C.CODIGO_EMPRESA= X2.CODIGO_EMPRESA AND C.TIPO_CONTRATO = X2.TIPO_CONTRATO AND C.CODIGO = X2.CONTRATO 
LEFT OUTER JOIN 
(
--inicio-- parte nova em 19/8/20 para pegar os locais que não tem fechamento no Ifponto
SELECT CASE WHEN W.FECHAMENTO_AGRUPADOR IS NOT NULL THEN W.FECHAMENTO_AGRUPADOR WHEN W.FECHAMENTO_ORGANOGRAMA IS NOT NULL THEN W.FECHAMENTO_ORGANOGRAMA ELSE W.FECHAMENTO_GERAL 
END DATA_USAR, W.* FROM ARTERH.SUGESP_DATA_APURACAO_FREQUENC W --COMENTADO EM 3/8/21--VW_DATA_APURACAO_FREQUENCIA W
--WHERE W.FECHAMENTO_ORGANOGRAMA IS NULL AND W.FECHAMENTO_AGRUPADOR IS NULL
)L ON X2.CODIGO_EMPRESA = L.CODIGO_EMPRESA 
--AND C.COD_CUSTO_GERENC1 = L.COD_AGRUP1 AND C.COD_CUSTO_GERENC2 = L.COD_AGRUP2 AND C.COD_CUSTO_GERENC3 = L.COD_AGRUP3
--AND C.COD_CUSTO_GERENC4 = L.COD_AGRUP4 AND C.COD_CUSTO_GERENC5 = L.COD_AGRUP5 AND C.COD_CUSTO_GERENC6 = L.COD_AGRUP6
--AND X2.LOCAL1_VW = L.COD_AGRUP1 AND X2.LOCAL2_VW = L.COD_AGRUP2 AND X2.LOCAL3_VW = L.COD_AGRUP3 AND X2.LOCAL4_VW = L.COD_AGRUP4 AND X2.LOCAL5_VW = L.COD_AGRUP5 AND X2.LOCAL6_VW = L.COD_AGRUP6
AND C.COD_CUSTO_GERENC1 = L.COD_AGRUP1 AND C.COD_CUSTO_GERENC2 = L.COD_AGRUP2 AND C.COD_CUSTO_GERENC3 = L.COD_AGRUP3 AND C.COD_CUSTO_GERENC4 = L.COD_AGRUP4 AND C.COD_CUSTO_GERENC5 = L.COD_AGRUP5 AND C.COD_CUSTO_GERENC6 = L.COD_AGRUP6


LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO =  X2.CODIGO
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON SP.CODIGO = SF.SITUACAO_PONTO
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GN ON C.CODIGO_EMPRESA = GN.CODIGO_EMPRESA AND C.COD_CUSTO_GERENC1 = GN.cod_cgerenc1 AND C.COD_CUSTO_GERENC2 = GN.cod_cgerenc2 AND C.COD_CUSTO_GERENC3 = GN.cod_cgerenc3 AND C.COD_CUSTO_GERENC4 = GN.cod_cgerenc4 AND C.COD_CUSTO_GERENC5 = GN.cod_cgerenc5 AND C.COD_CUSTO_GERENC6 = GN.cod_cgerenc6
LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_CONT CC ON C.CODIGO_EMPRESA = CC.CODIGO_EMPRESA AND C.cod_custo_contab1 = CC.cod_ccontab1 AND C.cod_custo_contab2 = CC.cod_ccontab2 AND C.cod_custo_contab3 = CC.cod_ccontab3 AND C.cod_custo_contab4 = CC.cod_ccontab4 AND C.cod_custo_contab5 = CC.cod_ccontab5 AND C.cod_custo_contab6 = CC.cod_ccontab6

--AND X2.LOCAL1_VW = GN.cod_cgerenc1 AND X2.LOCAL2_VW = GN.cod_cgerenc2 AND X2.LOCAL3_VW = GN.cod_cgerenc3 AND X2.LOCAL4_VW = GN.cod_cgerenc4 AND X2.LOCAL5_VW = GN.cod_cgerenc5 AND X2.LOCAL6_VW = GN.cod_cgerenc6

LEFT OUTER JOIN 
(
SELECT SUBSTR(T5.DADO_ORIGEM, 1,14) CGC_LOCAL, SUBSTR(T5.DADO_ORIGEM, 15,4) SIT_FUNC_LOCAL, T5.DADO_DESTINO SIT_PONT_LOCAL, SFC.DADO_DESTINO, SFC.DADO_ORIGEM SIT_FUNC_CESSAO, SF.DESCRICAO SITUACAO_FUN_CESSAO, SF.SITUACAO_PONTO SIT_PONTO_SIT_FUNC
FROM ARTERH.RHINTE_ED_IT_CONV T5
LEFT OUTER JOIN (SELECT SFC.DADO_DESTINO, SFC.DADO_ORIGEM FROM ARTERH.RHINTE_ED_IT_CONV SFC WHERE SFC.codigo_conversao = 'CESS')SFC ON SFC.DADO_ORIGEM = SUBSTR(T5.DADO_ORIGEM, 15,4)
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF ON SF.CODIGO = SUBSTR(T5.DADO_ORIGEM, 15,4)
WHERE T5.codigo_conversao = 'TEG5'
)SPD ON 
GN.CGC = SPD.CGC_LOCAL 
AND SF.CODIGO = SPD.SIT_FUNC_LOCAL

WHERE
C.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = C.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = C.TIPO_CONTRATO AND AUX.CODIGO = C.CODIGO)
--and c.data_rescisao is null
--AND L.DATA_USAR IS NOT NULL
--AND X2.DADO_DESTINO_VW = 'ORIGEM_COM_ONUS'--TESTES 3/8/21
AND X2.CODIGO_EMPRESA IN ('0001','0003','0013','0014','0002','0007','0009','0010')
-----------------------------------------------------------------------FIM EM 31/5/21 NOVA PARTE DE CESSAO
)X3--9084
LEFT OUTER JOIN 
(SELECT LPAD(SUBSTR(CODIGO,1,2),4,0)EMPRESA, LPAD(SUBSTR(CODIGO,4,6),6,0)COD1, LPAD(SUBSTR(CODIGO,11,6),6,0)COD2, LPAD(SUBSTR(CODIGO,18,6),6,0)COD3, LPAD(SUBSTR(CODIGO,25,6),6,0)COD4, LPAD(SUBSTR(CODIGO,32,6),6,0)COD5, LPAD(SUBSTR(CODIGO,39,6),6,0)COD6
FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO WHERE TRUNC(DT_SAIU_ARTE) = (SELECT MAX(TRUNC(DT_SAIU_ARTE)) FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO) 
)I ON I.COD1 = X3.LOCAL1_VW AND I.COD2 = X3.LOCAL2_VW AND I.COD3 = X3.LOCAL3_VW AND I.COD4 = X3.LOCAL4_VW AND I.COD5 = X3.LOCAL5_VW AND I.COD6 = X3.LOCAL6_VW and i.empresa = x3.codigo_empresa

left outer join ARTERH.RHPLCS_CARGO C ON c.CODIGO_EMPRESA = X3.CODIGO_EMPRESA AND c.CODIGO = X3.cod_cargo_comiss
left outer join ARTERH.RHPLCS_CARGO E ON e.CODIGO_EMPRESA = X3.CODIGO_EMPRESA AND e.CODIGO = X3.cod_cargo_efetivo

--comentado em 01/12/22--WHERE X3.LOCAL1_VW <> '000095'--EM 1/9/21 --TIRANDO A SMSA PARA O PRIMEIRO FECHAMENTO IFPONTO

--where x3.contrato = '000000000731211'--testes

--WHERE X3.DADO_ORIGEM_VW IS NOT NULL AND I.COD1 = '000095'--ajuste em 23/11/21 para cessoes da SMSA não feitas na frequencia de SETEMBRO E OUTUBRO DEVIDO A VIRADA PARA O IFPONTO
--where  x3.contrato = '000000000807447'--'000000000731211'

ORDER BY X3.CODIGO_EMPRESA, X3.TIPO_CONTRATO, X3.CONTRATO, X3.DATA_INICIO






)loop
vCONTADOR :=vCONTADOR+1;
--dbms_output.put_line( '' );
dbms_output.put_line('--'||vCONTADOR||'-'|| C1.ORDEM_BM ||'-'|| C1.TIPO ||'-'|| C1.CODIGO_EMPRESA ||'-'|| C1.TIPO_CONTRATO ||'-'|| C1.CONTRATO ||'-'|| C1.CODIGO ||'-'|| C1.DESCRICAO ||'-'|| C1.DATA_INICIO ||'-'|| C1.DATA_FIM);

--POPULAR VARIAVEIS
data_inicial := to_date(c1.DATA_INICIO_SIT_PONTO,'DD/MM/YYYY'); --to_date('01/12/22','DD/MM/YY');--comentado em 10/8/20--
data_final := to_date(c1.DATA_FIM_SIT_PONTO,'DD/MM/YYYY');--to_date('31/12/22','DD/MM/YY');--comentado em 10/8/20--
--dbms_output.put_line( '--DATA INICIO ANALISE: ' || to_date(data_inicial,'DD/MM/YYYY'));
--dbms_output.put_line( '--DATA FIM ANALISE: ' || to_date(data_final,'DD/MM/YYYY'));
num_dias := (data_final - data_inicial)+1;
--dbms_output.put_line( '--TOTAL DE DIAS: ' || num_dias);


for i in 1..num_dias loop
   vDATA_DIA :=  to_date(to_char((data_inicial-1)+i,'DD/MM/YYYY'),'DD/MM/YYYY');

IF vULT_DIA_FECHA_GERAL_FREQ = C1.DATA_USAR THEN

IF C1.SIT_PONT_LOCAL IS NULL THEN   
--dbms_output.put_line( '--| DIA: ' || i|| ' DATA: ' || to_char((data_inicial-1)+i,'DD/MM/YYYY')||'|'|| c1.codigo_empresa  ||'|'|| c1.tipo_contrato ||'|'||c1.CONTRATO ||'|'|| vDATA_DIA  ||'|'||C1.COD_SIT_PONTO ||'|'||C1.SITUACAO_PONTO);
--dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO) VALUES ('''||C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.CONTRATO ||''', TO_DATE('''|| vDATA_DIA ||''',''DD/MM/YY''),''' || C1.COD_SIT_PONTO ||''', 1, ''F'', SYSDATE, '''|| C1.LOGIN_USUARIO ||'''); COMMIT;' );  
delete ARTERH.RHPONT_RES_SIT_DIA where CODIGO_EMPRESA = C1.CODIGO_EMPRESA and  TIPO_CONTRATO = C1.TIPO_CONTRATO and CODIGO_CONTRATO =  C1.CONTRATO and trunc(DATA) = TO_DATE(vDATA_DIA,'DD/MM/YY') and CODIGO_SITUACAO =  C1.COD_SIT_PONTO and  TIPO_APURACAO = 'F'; COMMIT; 
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, TEXTO_ASSOCIADO) VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CONTRATO, TO_DATE(vDATA_DIA,'DD/MM/YY'), C1.COD_SIT_PONTO, 1, 'F', C1.DT_ULT_ALTER_USUA, C1.LOGIN_USUARIO,'SCRIPT FECHAMENTO IFPONTO(simulador_ifpontov4e5_v2.sql)' ); COMMIT; 

ELSE
--dbms_output.put_line( '--| DIA: ' || i|| ' DATA: ' || to_char((data_inicial-1)+i,'DD/MM/YYYY')||'|'|| c1.codigo_empresa  ||'|'|| c1.tipo_contrato ||'|'||c1.CONTRATO ||'|'|| vDATA_DIA  ||'|'||C1.COD_SIT_PONTO ||'|'||C1.SITUACAO_PONTO);
--dbms_output.put_line('INSERT INTO RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO) VALUES ('''||C1.CODIGO_EMPRESA ||''','''|| C1.TIPO_CONTRATO ||''','''|| C1.CONTRATO ||''', TO_DATE('''|| vDATA_DIA ||''',''DD/MM/YY''),''' || C1.COD_SIT_PONTO_DIFERENCIADA ||''', 1, ''F'', SYSDATE, '''|| C1.LOGIN_USUARIO ||'''); COMMIT;' );  
delete ARTERH.RHPONT_RES_SIT_DIA where CODIGO_EMPRESA = C1.CODIGO_EMPRESA and  TIPO_CONTRATO = C1.TIPO_CONTRATO and CODIGO_CONTRATO =  C1.CONTRATO and trunc(DATA) = TO_DATE(vDATA_DIA,'DD/MM/YY') and CODIGO_SITUACAO =  C1.SIT_PONT_LOCAL and  TIPO_APURACAO = 'F'; COMMIT; 
INSERT INTO ARTERH.RHPONT_RES_SIT_DIA (CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, DATA, CODIGO_SITUACAO, REF_HORAS, TIPO_APURACAO, DT_ULT_ALTER_USUA, LOGIN_USUARIO, TEXTO_ASSOCIADO) VALUES (C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CONTRATO, TO_DATE(vDATA_DIA,'DD/MM/YY'), C1.SIT_PONT_LOCAL, 1, 'F', C1.DT_ULT_ALTER_USUA, C1.LOGIN_USUARIO,'SCRIPT FECHAMENTO IFPONTO(simulador_ifpontov4e5_v2.sql)'); COMMIT;

END IF;

END IF;

END LOOP;
END LOOP;

END;

END;
