
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRR_PLANTOES_ABONO_SMSA" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN

--em 4/1/22 criando para ja gerar os cenarios e passar mais traduzido para GETED encaminhar os casos negados para a SMSA
--/*
DECLARE               
vCONTADOR NUMBER; 
vDATA_INICIO DATE;
vDATA_FIM DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR := 0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

FOR C1 IN(
--*/

--------------------------------------------------------------------TROCAR DATAS

SELECT 'ORDEM_REG|CENARIO|CODIGO_EMPRESA|TIPO_CONTRATO|CODIGO_CONTRATO|DATA|CODIGO_SITUACAO|SITUACAO_PONTO|REFERENCIA|LOGIN_USUARIO|DT_ULT_ALTER_USUA|TIPO_APURACAO|EMPRESA|TIPO_CONT|CONTRATO|DATA_LANC|vINSERT|vTIPO_DIA_PAGAR|vTOTAL_MARCACOES_DIA|vQTD_EVENTOS|CONTADOR|EMPRESA|TIPO_CONTR|MATRICULA|NOME|DATA|TIPO_SOBREAVISO|PREVISTO|REALIZADO|COD_CARGO_EFETIVO|CARGO_EFETIVO|COD_CARGO_COMISSIONADO|COD_FUNCAO|TIPO_LOCAL_LOTACAO|COD_CG1|COD_CG2|COD_CG3|COD_CG4|COD_CG5|COD_CG6|LOCAL_LOTADO|vLOTACAO_CS_AMPLIADO|REGIONAL|vCHAVE_SAV1_PARCIAL|PREVIA_PROCESSO|vCHAVE_SAV1_FINAL|RESULTADO_FINAL_PROCESSAMENTO|vQTD_LOCAIS_PODE_VERBA|MARCACAO_ENTRADA|ORIGEM_MARCACAO_ENTRADA|EFETIVADO_ENTRADA|DADOS_MARCACAO_ENTRADA|MARCACAO_SAIDA|ORIGEM_MARCACAO_SAIDA|EFETIVADO_SAIDA|DADOS_MARCACAO_SAIDA|v1_LOCAL_PBH_MARCACAO_ENTRADA|v1_LOCAL_PBH_MARCACAO_SAIDA|vQTD_MARCACOES_LOCAL_CS_AMPLI|vDISTANCIA_MAIS_PROXIMA|vDADOS_LOCAL_MAIS_PROXIMO' AS LINHA FROM DUAL UNION ALL

--SELECT X2.CENARIO, COUNT(1)QUANT FROM (  --SINTETICO

--SELECT x2.* --testes
 SELECT X2.ORDEM_REG||'|'||X2.CENARIO ||'|'||X2.CODIGO_EMPRESA||'|'||X2.TIPO_CONTRATO||'|'||X2.CODIGO_CONTRATO||'|'||X2.DATA||'|'|| X2.CODIGO_SITUACAO||'|'|| X2.SITUACAO_PONTO||'|'||X2.REFERENCIA||'|'||X2.LOGIN_USUARIO||'|'||X2.DT_ULT_ALTER_USUA||'|'||X2.TIPO_APURACAO||'|'||X2.EMPRESA||'|'|| X2.TIPO_CONTR||'|'|| X2.MATRICULA||'|'||TO_DATE(SUBSTR(X2.DATA_ESPELHO,1,8),'DD/MM/RRRR')||'|'||X2.CONSIDERACOES AS LINHA

FROM(
SELECT 
ROW_NUMBER()OVER(PARTITION BY SP.CODIGO_EMPRESA, SP.TIPO_CONTRATO, SP.CODIGO_CONTRATO, SP.DATA ORDER BY SP.CODIGO_EMPRESA, SP.TIPO_CONTRATO, SP.CODIGO_CONTRATO, SP.DATA, SP.CODIGO_SITUACAO )ORDEM_REG,
CASE
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 IS NULL AND X.CAMPO_9 IS NULL AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE APENAS MARCACOES DIRETO NO ESPELHO' 
THEN '1-GEROU SIT PONTO, APENAS COM MARCACOES LANCADAS DIRETAS NO ESPELHO NAO VALIDANDO LOCAL DA MARCACAO APENAS DA LOTACAO'

WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '2' AND X.CAMPO_7 = '1'   AND X.CAMPO_9 = '1'   AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '2-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DAS 2 MARCACOES NO ARTERH E IFPONTO DENTRO DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '2' AND X.CAMPO_7 = '2'   AND X.CAMPO_9 = '2'   AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '3-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DAS 2 MARCACOES NO ARTERH E NENHUMA MARCACAO IFPONTO DENTRO DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '2' AND ((X.CAMPO_7 = '1' AND X.CAMPO_9 = '2')OR(X.CAMPO_7 = '2' AND X.CAMPO_9 = '1')) AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '4-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DAS 2 MARCACOES NO ARTERH E 1 MARCACAO IFPONTO DENTRO DA CERCA'

WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '1' AND (X.CAMPO_7 = '1'  AND X.CAMPO_9 = '1')  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '5-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DE 1 MARCACAO NO ARTERH E 2 MARCACOES NO IFPONTO DENTRO DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '1' AND (X.CAMPO_7 = '2'  AND X.CAMPO_9 = '2')  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '6-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DE 1 MARCACAO NO ARTERH E NENHUMA MARCACAO NO IFPONTO DENTRO DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '1' AND ((X.CAMPO_7 = '1' AND X.CAMPO_9 = '2')OR(X.CAMPO_7 = '2' AND X.CAMPO_9 = '1'))  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '7-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DE 1 MARCACAO NO ARTERH E 1 MARCACAO NO IFPONTO DENTRO DA CERCA'

WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '0' AND (X.CAMPO_7 = '1'  AND X.CAMPO_9 = '1')  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '8-GEROU SIT PONTO, COM VALIDACAO PARCIAL NENHUMA MARCACAO NO ARTERH E 2 MARCACOES NO IFPONTO DENTRO DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '0' AND (X.CAMPO_7 = '2'  AND X.CAMPO_9 = '2')  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '9-GEROU SIT PONTO, POSSIVEL ERRO LOGICA VERIFICAR - PAGO COM NENUMA VALIDACAO DE MARCACAO NO ARTERH E IFPONTO TODAS FORA DA CERCA'
WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '0' AND ((X.CAMPO_7 = '1' AND X.CAMPO_9 = '2')OR(X.CAMPO_7 = '2' AND X.CAMPO_9 = '1'))  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '10-GEROU SIT PONTO, COM VALIDACAO PARCIAL NENHUMA MARCACAO NO ARTERH E 1 MARCACAO NO IFPONTO DENTRO DA CERCA'

WHEN SP.CODIGO_EMPRESA IS NOT NULL AND X.CAMPO_5 = '1' AND X.CAMPO_7 = '1' AND X.CAMPO_9 IS NULL  AND X.CAMPO_3 = '*PROCESSAMENTO SEGUE AVALIANDO MARCACOES'         
THEN '15-GEROU SIT PONTO, COM VALIDACAO INTEGRAL DE 1 MARCACAO NO ARTERH E 1 MARCACAO NO IFPONTO DENTRO DA CERCA MAS NAO LOCALIZADO A SEGUNDA MARCACAO PARA AVALIAR'

WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 = '1'  AND X.CAMPO_9 = '1' AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO'
THEN '11-NAO GEROU SIT PONTO, INDEPENDENTE DE TER APENAS 1 MARCACAO DENTRO DA CERCA IFPONTO LOCAL DE MARCACAO NAO CONFERE COM AS REGRAS DE PAGAMENTO PARA ESTE TIPO DE VERBA'
WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 = '2'  AND X.CAMPO_9 = '2' AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO'
THEN '12-NAO GEROU SIT PONTO, POIS NAO HA MARCACOES DENTRO DA CERTA TANTO NO ARTERH QUANTO IFPONTO'
WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 = '1'  AND X.CAMPO_9 = '1' AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO-*MESMO COM VALIDACAO PARCIAL DAS REGRAS DESCONSIDERANDO MARCACOES, AINDA ASSIM NAO GEROU REGISTRO, CONFERIR'
THEN '13-NAO GEROU SIT PONTO, INDEPENDENTE DE TER APENAS 1 MARCACAO DENTRO DA CERCA IFPONTO LOCAL DE MARCACAO NAO CONFERE COM AS REGRAS DE PAGAMENTO PARA ESTE TIPO DE VERBA'
WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '2' AND X.CAMPO_7 = '1'  AND X.CAMPO_9 = '1' AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO-*LOCAL E MARCACOES ATENDERAM A REGRA INTEGRAL POREM CARGO NAO PODE VERBA'
THEN '14-NAO GEROU SIT PONTO, MESMO COM VALIDACAO INTEGRAL DAS 2 MARCACOES DENTRO DA CERCA ARTERH E IFPONTO, CARGO NAO CONFERE COM AS REGRAS DE PAGAMENTO PARA ESTE TIPO DE VERBA'

WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 = '2' AND X.CAMPO_9 IS NULL  AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO'         
THEN '16-NAO GEROU SIT PONTO, 1 MARCACAO NO ARTERH E NO IFPONTO FORA DA CERCA E NAO LOCALIZADO A SEGUNDA MARCACAO PARA AVALIAR'

--WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_5 = '0' AND X.CAMPO_7 = '2' AND X.CAMPO_9 IS NULL  AND X.CAMPO_4 = '-*LOCAL DAS MARCACOES NAO CONFERE COM A REGRA DO TIPO DE VERBA LANCADA NO IFPONTO'         
--THEN '17-NAO GEROU SIT PONTO, 1 MARCACAO NO ARTERH E NO IFPONTO FORA DA CERCA E NAO LOCALIZADO A SEGUNDA MARCACAO PARA AVALIAR'

WHEN SP.CODIGO_EMPRESA IS NULL AND X.CAMPO_14 = 'N' AND X.CAMPO_15 = 0 AND X.CAMPO_16 = 'Plantão / Hora extra centro de saúde ampliado'
THEN '18-NAO GEROU SIT PONTO, PESSOA LOTADA E MARCACOES, SE EXISTENTES, FEITAS VIA APP/PC ONDE NAO SAO LOCAIS DEFINIDOS PARA PAGAR A VERBA DOS CS AMPLIADOS'

WHEN SP.CODIGO_EMPRESA IS NOT NULL THEN 'GEROU SIT PONTO, MESMO NAO_MAPEADO_AINDA'
ELSE 'NAO GEROU SIT PONTO, NAO_MAPEADO_AINDA'

END CENARIO,
--SP.CODIGO_EMPRESA||'|'||SP.TIPO_CONTRATO||'|'||SP.CODIGO_CONTRATO||'|'||SP.DATA||'|'|| SP.CODIGO_SITUACAO||'|'|| SP.SITUACAO_PONTO||'|'|| SP.REFERENCIA||'|'|| SP.LOGIN_USUARIO||'|'|| SP.DT_ULT_ALTER_USUA||'|'|| SP.TIPO_APURACAO||'|'||X.CODIGO_EMPRESA||'|'|| X.TIPO_CONTRATO||'|'|| X.CODIGO_CONTRATO||'|'||TO_DATE(SUBSTR(X.CAMPO_2,1,8),'DD/MM/RRRR')||'|'||X.CONSIDERACOES AS LINHA
SP.CODIGO_EMPRESA, SP.TIPO_CONTRATO, SP.CODIGO_CONTRATO, SP.DATA, SP.CODIGO_SITUACAO, SP.SITUACAO_PONTO, SP.REFERENCIA, SP.LOGIN_USUARIO, SP.DT_ULT_ALTER_USUA, SP.TIPO_APURACAO
--, X.CONSIDERACOES AS LINHA
,X.CODIGO_EMPRESA EMPRESA, X.TIPO_CONTRATO TIPO_CONTR, X.CODIGO_CONTRATO MATRICULA , TO_DATE(SUBSTR(X.CAMPO_2,1,8),'DD/MM/RRRR')DATA_ESPELHO
, X.CAMPO_3 PREVIA_PROCESSO, X.CAMPO_4 RESULTADO_FINAL_PROCESSAMENTO, X.CAMPO_5 vQTD_LOCAIS_PODE_VERBA, 
X.CAMPO_6 ORIGEM_MARCACAO_ENTRADA, X.CAMPO_7 EFETIVADO_ENTRADA, X.CAMPO_8 ORIGEM_MARCACAO_SAIDA, X.CAMPO_9 EFETIVADO_SAIDA
,X.CAMPO_10 vINSERT, X.CAMPO_11 vTIPO_DIA_PAGAR, X.CAMPO_12 vTOTAL_MARCACOES_DIA, X.CAMPO_13 vQTD_EVENTOS, X.CAMPO_14 vLOTACAO_CS_AMPLIADO, X.CAMPO_15 vQTD_MARCACOES_LOCAL_CS_AMPLI, X.CAMPO_16 TIPO--NOVO EM 25/2/22
,X.CONSIDERACOES
FROM PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT X 
--/*
LEFT OUTER JOIN 
(SELECT D.CODIGO_EMPRESA, D.TIPO_CONTRATO, D.CODIGO_CONTRATO, D.DATA, D.CODIGO_SITUACAO, SP.DESCRICAO SITUACAO_PONTO, D.REF_HORAS REFERENCIA, D.LOGIN_USUARIO, D.DT_ULT_ALTER_USUA, D.TIPO_APURACAO
FROM ARTERH.RHPONT_RES_SIT_DIA D
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO SP ON SP.CODIGO = D.CODIGO_SITUACAO
WHERE D.login_usuario = 'IFPONTO' AND TRUNC(D.DATA) BETWEEN TO_DATE(vDATA_INICIO,'DD/MM/YY') AND TO_DATE(vDATA_FIM,'DD/MM/YY')-------------------------------trocar datas
AND TRUNC(D.DT_ULT_ALTER_USUA) >= TRUNC(SYSDATE)--TO_DATE('11/02/2022','DD/MM/YYYY')--TRUNC(SYSDATE)
and d.codigo_situacao IN ('1019','1020','1017','1021','1018','1026')
)SP ON SP.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND  SP.TIPO_CONTRATO = X.TIPO_CONTRATO AND SP.CODIGO_CONTRATO = X.CODIGO_CONTRATO
AND TO_DATE(SP.DATA,'DD/MM/RRRR') = TO_DATE(SUBSTR(X.CAMPO_2,1,8),'DD/MM/RRRR') 
--*/
WHERE TRUNC(DATA_DADOS) =  TRUNC(SYSDATE) --TO_DATE('11/12/2021','DD/MM/YYYY')
AND CAMPO_1 ='PRG10_PLANTOES_ABONO_SMSA'
AND X.CODIGO_EMPRESA IS NOT NULL


)X2 

--SINTETICO 
--GROUP BY X2.CENARIO ORDER BY X2.CENARIO--SINTETICO

--/*
)

LOOP

vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' C1.LINHA: '||C1.LINHA);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (DATA_DADOS, CAMPO_1, CONSIDERACOES)VALUES(SYSDATE,'PRR_PLANTOES_ABONO_SMSA',C1.LINHA);COMMIT;

END LOOP;

END;
--*/

END;