
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."PRR_DESCONTOS_FECHAMENTO" (DATA_INICIO IN DATE, DATA_FIM IN DATE) AS
BEGIN
--em 4/1/22 criando para ja gerar os cenarios e passar mais traduzido para GETED encaminhar os casos negados para a SMSA
--/*
DECLARE               
vCONTADOR NUMBER; 
vDATA_INICIO DATE;
vDATA_FIM DATE;

BEGIN
dbms_output.enable(null);
vCONTADOR := 0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;

FOR C1 IN(
--*/
--------------------------------------------------------------------TROCAR DATAS
SELECT 
'_PARTE_PROCESSAMENTO|EMPRESA|TIPO_CONTRATO|MATRICULA|CENARIO|TIPO_FECHAMENTO|QUANT_DIAS|PREVISTO|TOTAL_HORAS_PREVISTAS|BH_DEBITO|DESCONTO|STATUS_DESCONTO|TIPO_DIFERENCA_DESCONTO|DESCONTO_PROCESSAMENTO|DESCONTO_IFPONTO|DESCONTO_ARTERH|ORDEM_BM|TIPO_ESCALA|CARGA_HORARIA|EMPRESA_ESCALA|QTD_DIAS_ESCALA|JORNADA_VINCULADA_CARGO|QTD_DIAS|TIPO_DIA|PROXIMO_QTD_DIAS|PROXIMO_TIPO_DIA|TAM_COMPRIMENTO_ESCALA|QTD_REGISTROS|FOLHA_ESPECIAL|REGISTRO_PONTO|COD_VINCULO|ACUMULADO_FALTAS|ACUMULADO_PREVISTO|ACUMULADO_H_NORMAIS|ACUMULADO_H_DIFERENCIAS|ACUMULADO_H_EXCEDIDAS|DATA_PROCESSAMENTO|TRABALHOU|FOLGA|NAO_TRABALHOU|FERIAS_AFASTAMENTO|JUSTIFICATIVA_ABONADA|JUSTIFICATIVA_NAO_AVALIADA|JUSTIFICATIVA_NAO_ABONADA|ERROS_VERIFICAR|TOTAL_DIAS_PROCESSAMENTO|TEVE_DESCONTO|TEVE_DIAS_TRABALHOU|TEVE_DIAS_FOLGA|TEVE_DIAS_NAO_TRABALHOU|TEVE_FERIAS_AFASTAMENTO|TEVE_JUSTIFICATIVA_ABONADA|TEVE_JUSTIFICATIVA_NAO_AVALIA|TEVE_JUSTIFICATIVA_NAO_ABONADA|TEVE_ERROS_VERIFICAR|TOTAL_IFPONTO|COD_PESSOA|SOMA_DESCONTO|QTD_DIAS_DESCONTO|RESULTADOS_ARTERH|CODIGO_EMPRESA|TIPO_CONTRAT|CODIGO_CONTRATO|NOME|COD_SIT_FUNC|SITUACAO_FUNCIONAL|COD_CARGO_EFETIVO|CARGO_EFETIVO|COD_CARGO_COMISSAO|CARGO_COMISSAO|COD_FUCNCAO|FUNCAO|COD_CGERENC1|COD_CGERENC2|COD_CGERENC3|COD_CGERENC4|COD_CGERENC5|COD_CGERENC6|CUSTO_GERENCIAL|CODIGO_ESCALA|QTD_TOTAL_MINUTOS_TIPO_JORNAD|TOTAL_HORAS_TIPO_JORNADA|CARGA_HORARIA_TIPO_JORNADA|SOMA_MINUTOS_ESCALA|SOMA_HORAS_ESCALA|TOTAL_HORAS_NA_SEMANA_ESCALA|STATUS_ESCALA_JORNADA|TEVE_FALTA_COMPENS|TOTAL_REF_FALTA_0020|QTD_DIAS_FALTA_0020|TOTAL_REF_ESTORNO_FALTA_1015|QTD_DIAS_ESTORNO_FALTA_1015|TOTAL_REF_TOT_H_DIF_PER_1013|QTD_DIAS_TOT_H_DIF_PER_1013|TOTAL_REF_EST_TOT_H_DIF_1204|QTD_DIAS_EST_TOT_H_DIF_1204|TOTAL_DIAS_DESCONTADO|TOTAL_HORAS_DESCONTADAS|TOTAL_GERAL_DESCONTO_HORAS|TOTAL_REF_FALTA_COMPENS_1004|QTD_DIAS_FALTA_COMPENS_1004|TOTAL_REF_AUSENC_ABONA_EM_DIA|QTD_DIAS_AUSENC_ABONA_EM_DIA|TOTAL_REF_CESSAO_TELETRABALHO|QTD_DIAS_CESSAO_TELETRABALHO|TOTAL_REF_HORA_NORMAL_EM_HORA|QTD_DIAS_HORA_NORMAL_EM_HORA|TOTAL_REF_AUSENC_ABONA_EM_HORA|QTD_DIAS_AUSENC_ABONA_EM_HORA|TOTAL_REF_FALTA_EM_HORAS|QTD_DIAS_FALTA_EM_HORAS'
AS LINHA 
FROM DUAL UNION ALL
SELECT 
X6.PARTE_PROCESSAMENTO||'|'||X6.EMPRESA||'|'||X6.TIPO_CONTRATO||'|'||X6.MATRICULA||'|'||X6.CENARIO||'|'||X6.TIPO_FECHAMENTO||'|'||X6.QUANT_DIAS||'|'||X6.PREVISTO||'|'||X6.TOTAL_HORAS_PREVISTAS||'|'||X6.BH_DEBITO||'|'||X6.DESCONTO||'|'||X6.STATUS_DESCONTO||'|'||X6.TIPO_DIFERENCA_DESCONTO||'|'||X6.DESCONTO_PROCESSAMENTO||'|'||X6.DESCONTO_IFPONTO||'|'||X6.DESCONTO_ARTERH||'|'||X6.ORDEM_BM||'|'||X6.TIPO_ESCALA||'|'||X6.CARGA_HORARIA||'|'||X6.EMPRESA_ESCALA||'|'||X6.QTD_DIAS_ESCALA||'|'||X6.JORNADA_VINCULADA_CARGO||'|'||X6.QTD_DIAS||'|'||X6.TIPO_DIA||'|'||X6.PROXIMO_QTD_DIAS||'|'||X6.PROXIMO_TIPO_DIA||'|'||X6.TAM_COMPRIMENTO_ESCALA||'|'||X6.QTD_REGISTROS||'|'||X6.FOLHA_ESPECIAL||'|'||X6.REGISTRO_PONTO||'|'||X6.COD_VINCULO||'|'||X6.ACUMULADO_FALTAS||'|'||X6.ACUMULADO_PREVISTO||'|'||X6.ACUMULADO_H_NORMAIS||'|'||X6.ACUMULADO_H_DIFERENCIAS||'|'||X6.ACUMULADO_H_EXCEDIDAS||'|'||X6.DATA_PROCESSAMENTO||'|'||X6.TRABALHOU||'|'||X6.FOLGA||'|'||X6.NAO_TRABALHOU||'|'||X6.FERIAS_AFASTAMENTO||'|'||X6.JUSTIFICATIVA_ABONADA||'|'||X6.JUSTIFICATIVA_NAO_AVALIADA||'|'||X6.JUSTIFICATIVA_NAO_ABONADA||'|'||X6.ERROS_VERIFICAR||'|'||X6.TOTAL_DIAS_PROCESSAMENTO||'|'||X6.TEVE_DESCONTO||'|'||X6.TEVE_DIAS_TRABALHOU||'|'||X6.TEVE_DIAS_FOLGA||'|'||X6.TEVE_DIAS_NAO_TRABALHOU||'|'||X6.TEVE_FERIAS_AFASTAMENTO||'|'||X6.TEVE_JUSTIFICATIVA_ABONADA||'|'||X6.TEVE_JUSTIFICATIVA_NAO_AVALIA||'|'||X6.TEVE_JUSTIFICATIVA_NAO_ABONADA||'|'||X6.TEVE_ERROS_VERIFICAR||'|'||X6.TOTAL_IFPONTO||'|'||X6.COD_PESSOA||'|'||X6.SOMA_DESCONTO||'|'||X6.QTD_DIAS_DESCONTO||'|'||X6.RESULTADOS_ARTERH||'|'||X6.CODIGO_EMPRESA||'|'||X6.TIPO_CONTRAT||'|'||X6.CODIGO_CONTRATO||'|'||X6.NOME||'|'||X6.COD_SIT_FUNC||'|'||X6.SITUACAO_FUNCIONAL||'|'||X6.COD_CARGO_EFETIVO||'|'||X6.CARGO_EFETIVO||'|'||X6.COD_CARGO_COMISSAO||'|'||X6.CARGO_COMISSAO||'|'||X6.COD_FUCNCAO||'|'||X6.FUNCAO||'|'||X6.COD_CGERENC1||'|'||X6.COD_CGERENC2||'|'||X6.COD_CGERENC3||'|'||X6.COD_CGERENC4||'|'||X6.COD_CGERENC5||'|'||X6.COD_CGERENC6||'|'||X6.CUSTO_GERENCIAL||'|'||X6.CODIGO_ESCALA||'|'||X6.QTD_TOTAL_MINUTOS_TIPO_JORNAD||'|'||X6.TOTAL_HORAS_TIPO_JORNADA||'|'||X6.CARGA_HORARIA_TIPO_JORNADA||'|'||X6.SOMA_MINUTOS_ESCALA||'|'||X6.SOMA_HORAS_ESCALA||'|'||X6.TOTAL_HORAS_NA_SEMANA_ESCALA||'|'||X6.STATUS_ESCALA_JORNADA||'|'||X6.TEVE_FALTA_COMPENS||'|'||X6.TOTAL_REF_FALTA_0020||'|'||X6.QTD_DIAS_FALTA_0020||'|'||X6.TOTAL_REF_ESTORNO_FALTA_1015||'|'||X6.QTD_DIAS_ESTORNO_FALTA_1015||'|'||X6.TOTAL_REF_TOT_H_DIF_PER_1013||'|'||X6.QTD_DIAS_TOT_H_DIF_PER_1013||'|'||X6.TOTAL_REF_EST_TOT_H_DIF_1204||'|'||X6.QTD_DIAS_EST_TOT_H_DIF_1204||'|'||X6.TOTAL_DIAS_DESCONTADO||'|'||X6.TOTAL_HORAS_DESCONTADAS||'|'||X6.TOTAL_GERAL_DESCONTO_HORAS||'|'||X6.TOTAL_REF_FALTA_COMPENS_1004||'|'||X6.QTD_DIAS_FALTA_COMPENS_1004||'|'||X6.TOTAL_REF_AUSENC_ABONA_EM_DIA||'|'||X6.QTD_DIAS_AUSENC_ABONA_EM_DIA||'|'||X6.TOTAL_REF_CESSAO_TELETRABALHO||'|'||X6.QTD_DIAS_CESSAO_TELETRABALHO||'|'||X6.TOTAL_REF_HORA_NORMAL_EM_HORA||'|'||X6.QTD_DIAS_HORA_NORMAL_EM_HORA||'|'||X6.TOTAL_REF_AUSENC_ABONA_EM_HORA||'|'||X6.QTD_DIAS_AUSENC_ABONA_EM_HORA||'|'||X6.TOTAL_REF_FALTA_EM_HORAS||'|'||X6.QTD_DIAS_FALTA_EM_HORAS
AS LINHA
FROM(
--em 5/11/21 v5 para ajustes novos como duplicidades e relatados no fechamento set/21
--adaptando mais em 21/6/21 para a versão 3
--EM 21/5/21 AS 14H, ADICIONAR A LOGICA (analise_escala_semanal_toda_smsa.sql)
----------------------------------------TROCAR DATAS

--select ''''||X6.MATRICULA||''',' bm, count(1) from (
--analise para a SMSA
SELECT
--''''||X5.MATRICULA||''',' bm,
--comentado em 12/7/21--'PARTE_ARTERH_PRODUCAO' PARTE_ARTERH_PRODUCAO, SMSA.*,GN.DESCRICAO LOCAL,
--PARTE PROCESSAMENTO/IFPONTO
X5.PARTE_PROCESSAMENTO, X5.EMPRESA, X5.TIPO_CONTRATO, X5.MATRICULA, X5.CENARIO, X5.TIPO_FECHAMENTO, X5.QUANT_DIAS, X5.PREVISTO, X5.TOTAL_HORAS_PREVISTAS, X5.BH_DEBITO, X5.DESCONTO,
X5.STATUS_DESCONTO,  
CASE 
WHEN X5.DESCONTO_PROCESSAMENTO = 0  AND X5.DESCONTO_IFPONTO = 0 AND X5.DESCONTO_ARTERH = 0 THEN 'OK, SEM DESCONTOS'
WHEN X5.DESCONTO_PROCESSAMENTO = X5.DESCONTO_IFPONTO AND X5.DESCONTO_IFPONTO <> X5.DESCONTO_ARTERH THEN 'ERRO1, DESCONTO PROCESSAMENTO = IFPONTO E IFPONTO <> ARTERH'
WHEN X5.DESCONTO_PROCESSAMENTO <> X5.DESCONTO_IFPONTO AND X5.DESCONTO_IFPONTO = X5.DESCONTO_ARTERH THEN 'ERRO2, DESCONTO PROCESSAMENTO <> IFPONTO E IFPONTO = ARTERH'
WHEN X5.DESCONTO_PROCESSAMENTO = X5.DESCONTO_ARTERH AND X5.DESCONTO_IFPONTO <> X5.DESCONTO_ARTERH THEN 'ERRO3, DESCONTO PROCESSAMENTO = ARTERH E IFPONTO <> ARTERH'
WHEN X5.DESCONTO_PROCESSAMENTO <> X5.DESCONTO_ARTERH AND X5.DESCONTO_IFPONTO = X5.DESCONTO_ARTERH THEN 'ERRO4, DESCONTO PROCESSAMENTO <> ARTERH E IFPONTO = ARTERH'
WHEN X5.DESCONTO_PROCESSAMENTO <> X5.DESCONTO_IFPONTO AND X5.DESCONTO_IFPONTO <> X5.DESCONTO_ARTERH THEN 'ERRO5, OS 3 DESCONTOS DIFEREM PROCESSAMENTO, IFPONTO E ARTERH'
WHEN X5.DESCONTO_PROCESSAMENTO = X5.DESCONTO_IFPONTO AND X5.DESCONTO_IFPONTO = X5.DESCONTO_ARTERH THEN 'OK, 3 DESCONTOS IGUAIS PROCESSAMENTO, IFPONTO E ARTERH'
ELSE 'MAPEAR'
END TIPO_DIFERENCA_DESCONTO,
X5.DESCONTO_PROCESSAMENTO, X5.DESCONTO_IFPONTO, X5.DESCONTO_ARTERH,
X5.ORDEM_BM,--DESCONTO
X5.TIPO_ESCALA, X5.CARGA_HORARIA, X5.EMPRESA_ESCALA, X5.QTD_DIAS_ESCALA, X5.COMPRIMENTO_ESCALA,---ESCALA
X5.JORNADA_VINCULADA_CARGO, X5.QTD_DIAS, X5.TIPO_DIA, X5.PROXIMO_QTD_DIAS, X5.PROXIMO_TIPO_DIA, 
--comentado em 12/7/21--X5.ESCALA_SEMANA_CLASSICA, 
X5.TAM_COMPRIMENTO_ESCALA,--ESCALA
X5.QTD_REGISTROS, 
X5.FOLHA_ESPECIAL, X5.REGISTRO_PONTO, X5.COD_VINCULO,
X5.ACUMULADO_FALTAS, X5.ACUMULADO_PREVISTO, X5.ACUMULADO_H_NORMAIS, X5.ACUMULADO_H_DIFERENCIAS, X5.ACUMULADO_H_EXCEDIDAS, X5.DATA_PROCESSAMENTO, 
X5.TRABALHOU, X5.FOLGA, X5.NAO_TRABALHOU, X5.FERIAS_AFASTAMENTO, X5.JUSTIFICATIVA_ABONADA, X5.JUSTIFICATIVA_NAO_AVALIADA, X5.JUSTIFICATIVA_NAO_ABONADA, X5.ERROS_VERIFICAR, X5.TOTAL_DIAS_PROCESSAMENTO, 
X5.TEVE_DESCONTO, ---ESCALA
X5.TEVE_DIAS_TRABALHOU, X5.TEVE_DIAS_FOLGA, X5.TEVE_DIAS_NAO_TRABALHOU, X5.TEVE_FERIAS_AFASTAMENTO, X5.TEVE_JUSTIFICATIVA_ABONADA, X5.TEVE_JUSTIFICATIVA_NAO_AVALIA, X5.TEVE_JUSTIFICATIVA_NAO_ABONADA, X5.TEVE_ERROS_VERIFICAR, 


--PARTE IFPONTO
X5.TOTAL_IFPONTO, X5.COD_PESSOA, X5.SOMA_DESCONTO, X5.QTD_DIAS_DESCONTO, --X5.AGRUPADOR, X5.UNIDADE, 

--PARTE ARTERH
X5.RESULTADOS_ARTERH, X5.CODIGO_EMPRESA, X5.TIPO_CONTRAT, X5.CODIGO_CONTRATO, X5.NOME, X5.COD_SIT_FUNC, X5.SITUACAO_FUNCIONAL, X5.COD_CARGO_EFETIVO, X5.CARGO_EFETIVO, X5.COD_CARGO_COMISSAO, X5.CARGO_COMISSAO, X5.COD_FUCNCAO, X5.FUNCAO, 
X5.COD_CGERENC1, X5.COD_CGERENC2, X5.COD_CGERENC3, X5.COD_CGERENC4, X5.COD_CGERENC5, X5.COD_CGERENC6, X5.CUSTO_GERENCIAL, 
X5.CODIGO_ESCALA, X5.QTD_TOTAL_MINUTOS_TIPO_JORNAD, X5.TOTAL_HORAS_TIPO_JORNADA, X5.CARGA_HORARIA_TIPO_JORNADA, ---ESCALA
X5.SOMA_MINUTOS_ESCALA, X5.SOMA_HORAS_ESCALA, 
X5.SOMA_HORAS_ESCALA/(X5.QTD_DIAS_ESCALA/7) TOTAL_HORAS_NA_SEMANA_ESCALA, --ESCALA
CASE WHEN X5.TOTAL_HORAS_TIPO_JORNADA <> X5.SOMA_HORAS_ESCALA/(X5.QTD_DIAS_ESCALA/7) OR X5.TOTAL_HORAS_TIPO_JORNADA IS NULL OR X5.SOMA_HORAS_ESCALA IS NULL THEN 'VERIFICA SE ESCALA REDUZIDA OU ERRO' ELSE 'APARENTEMENTE IGUAL HORAS DA ESCALA E JORNADA' END STATUS_ESCALA_JORNADA,
X5.TEVE_FALTA_COMPENS, ---ESCALA
X5.TOTAL_REF_FALTA_0020, X5.QTD_DIAS_FALTA_0020, X5.TOTAL_REF_ESTORNO_FALTA_1015, X5.QTD_DIAS_ESTORNO_FALTA_1015, X5.TOTAL_REF_TOT_H_DIF_PER_1013, X5.QTD_DIAS_TOT_H_DIF_PER_1013, X5.TOTAL_REF_EST_TOT_H_DIF_1204, X5.QTD_DIAS_EST_TOT_H_DIF_1204, X5.TOTAL_DIAS_DESCONTADO, X5.TOTAL_HORAS_DESCONTADAS, X5.TOTAL_GERAL_DESCONTO_HORAS, X5.TOTAL_REF_FALTA_COMPENS_1004, X5.QTD_DIAS_FALTA_COMPENS_1004, X5.TOTAL_REF_AUSENC_ABONA_EM_DIA, X5.QTD_DIAS_AUSENC_ABONA_EM_DIA, X5.TOTAL_REF_CESSAO_TELETRABALHO, X5.QTD_DIAS_CESSAO_TELETRABALHO, X5.TOTAL_REF_HORA_NORMAL_EM_HORA, X5.QTD_DIAS_HORA_NORMAL_EM_HORA, X5.TOTAL_REF_AUSENC_ABONA_EM_HORA, X5.QTD_DIAS_AUSENC_ABONA_EM_HORA, X5.TOTAL_REF_FALTA_EM_HORAS, X5.QTD_DIAS_FALTA_EM_HORAS
/*---INICIO----SINTETICO
X5.QUANT_DIAS, X5.TEVE_DESCONTO,
X5.TIPO_ESCALA, X5.CARGA_HORARIA, X5.EMPRESA_ESCALA, X5.QTD_DIAS_ESCALA, 
X5.QTD_TOTAL_MINUTOS_TIPO_JORNAD, X5.TOTAL_HORAS_TIPO_JORNADA,	X5.CARGA_HORARIA_TIPO_JORNADA,
X5.TAM_COMPRIMENTO_ESCALA, X5.POSSIVEL_DIAS_SEMANA,  X5.COMPRIMENTO_ESCALA,
X5.FOLHA_ESPECIAL, X5.REGISTRO_PONTO, X5.COD_VINCULO,
X5.TEVE_DIAS_TRABALHOU, 
--X5.TEVE_DIAS_FOLGA, X5.TEVE_DIAS_NAO_TRABALHOU, X5.TEVE_FERIAS_AFASTAMENTO, X5.TEVE_JUSTIFICATIVA_ABONADA, X5.TEVE_JUSTIFICATIVA_NAO_AVALIA, X5.TEVE_JUSTIFICATIVA_NAO_ABONADA, X5.TEVE_ERROS_VERIFICAR,
X5.TEVE_FALTA_COMPENS,
X5.COD_CARGO_EFETIVO, X5.CARGO_EFETIVO, X5.COD_CARGO_COMISSAO, X5.CARGO_COMISSAO, X5.COD_FUCNCAO, X5.FUNCAO, X5.COD_CGERENC1
, COUNT(1)QUANT_REGISTROS
*/---INICIO----SINTETICO

FROM(
--INICIO --BASE desconto_vs_compensacao_pbh_v2.sql---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
TME.SOMA_MINUTOS_ESCALA, TME.SOMA_HORAS_ESCALA,
CASE WHEN CJ.CODIGO_TABELA IS NULL THEN 'NAO' ELSE 'SIM' END JORNADA_VINCULADA_CARGO,
PD.QTD_DIAS, PD.TIPO_DIA, PD.PROXIMO_QTD_DIAS, PD.PROXIMO_TIPO_DIA,
CASE WHEN LENGTH(X4.COMPRIMENTO_ESCALA) = 98 AND X4.TIPO_ESCALA = 'Semanal' AND PD.QTD_DIAS = 2 AND PD.TIPO_DIA = 'FOLGA' AND PD.PROXIMO_QTD_DIAS = 5 AND PD.PROXIMO_TIPO_DIA = 'TRABALHO' THEN 'SIM' ELSE 'NAO' END ESCALA_SEMANAL_CLASSICA,
LENGTH(X4.COMPRIMENTO_ESCALA) TAM_COMPRIMENTO_ESCALA,
CASE WHEN X4.DESCONTO IS NOT NULL AND X4.DESCONTO <>0 THEN 'SIM' ELSE 'NAO' END TEVE_DESCONTO,
CASE WHEN X4.TRABALHOU IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_DIAS_TRABALHOU,
CASE WHEN X4.FOLGA IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_DIAS_FOLGA,
CASE WHEN X4.NAO_TRABALHOU IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_DIAS_NAO_TRABALHOU,
CASE WHEN X4.FERIAS_AFASTAMENTO IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_FERIAS_AFASTAMENTO,
CASE WHEN X4.JUSTIFICATIVA_ABONADA IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_JUSTIFICATIVA_ABONADA,
CASE WHEN X4.JUSTIFICATIVA_NAO_AVALIADA IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_JUSTIFICATIVA_NAO_AVALIA,
CASE WHEN X4.JUSTIFICATIVA_NAO_ABONADA IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_JUSTIFICATIVA_NAO_ABONADA,
CASE WHEN X4.ERROS_VERIFICAR IS NOT NULL THEN 'SIM' ELSE 'NAO' END TEVE_ERROS_VERIFICAR,
CASE WHEN X4.QTD_DIAS_FALTA_COMPENS_1004 IS NOT NULL AND X4.QTD_DIAS_FALTA_COMPENS_1004  <>0 THEN 'SIM' ELSE 'NAO' END TEVE_FALTA_COMPENS,
X4.STATUS_DESCONTO, X4.DESCONTO_PROCESSAMENTO, X4.DESCONTO_IFPONTO, X4.DESCONTO_ARTERH, X4.ORDEM_BM, X4.PARTE_PROCESSAMENTO, X4.EMPRESA, X4.TIPO_CONTRATO, X4.MATRICULA, X4.CENARIO, X4.TIPO_FECHAMENTO, X4.QUANT_DIAS, X4.PREVISTO, X4.TOTAL_HORAS_PREVISTAS,
X4.BH_DEBITO, X4.DESCONTO, X4.TIPO_ESCALA, X4.CARGA_HORARIA, X4.EMPRESA_ESCALA, IFH.QTD_DIAS_ESCALA, X4.COMPRIMENTO_ESCALA, X4.QTD_REGISTROS, X4.FOLHA_ESPECIAL, X4.REGISTRO_PONTO, X4.COD_VINCULO, X4.ACUMULADO_FALTAS, X4.ACUMULADO_PREVISTO, X4.ACUMULADO_H_NORMAIS, X4.ACUMULADO_H_DIFERENCIAS, X4.ACUMULADO_H_EXCEDIDAS, X4.DATA_PROCESSAMENTO, X4.TRABALHOU, X4.FOLGA, X4.NAO_TRABALHOU, X4.FERIAS_AFASTAMENTO, X4.JUSTIFICATIVA_ABONADA, X4.JUSTIFICATIVA_NAO_AVALIADA, X4.JUSTIFICATIVA_NAO_ABONADA, X4.ERROS_VERIFICAR, X4.TOTAL_DIAS_PROCESSAMENTO, X4.TOTAL_IFPONTO, X4.COD_PESSOA, X4.SOMA_DESCONTO, X4.QTD_DIAS_DESCONTO,
--X4.AGRUPADOR, X4.UNIDADE, 
X4.RESULTADOS_ARTERH, X4.CODIGO_EMPRESA, X4.TIPO_CONTRAT, X4.CODIGO_CONTRATO, X4.NOME, X4.COD_SIT_FUNC, X4.SITUACAO_FUNCIONAL, X4.COD_CARGO_EFETIVO, X4.CARGO_EFETIVO, X4.COD_CARGO_COMISSAO, X4.CARGO_COMISSAO, X4.COD_FUCNCAO, X4.FUNCAO, X4.COD_CGERENC1, X4.COD_CGERENC2, X4.COD_CGERENC3, X4.COD_CGERENC4, X4.COD_CGERENC5, X4.COD_CGERENC6, X4.CUSTO_GERENCIAL, X4.CODIGO_ESCALA, X4.QTD_TOTAL_MINUTOS_TIPO_JORNAD, X4.TOTAL_HORAS_TIPO_JORNADA, X4.CARGA_HORARIA_TIPO_JORNADA, X4.TOTAL_REF_FALTA_0020, X4.QTD_DIAS_FALTA_0020, X4.TOTAL_REF_ESTORNO_FALTA_1015, X4.QTD_DIAS_ESTORNO_FALTA_1015, X4.TOTAL_REF_TOT_H_DIF_PER_1013, X4.QTD_DIAS_TOT_H_DIF_PER_1013, X4.TOTAL_REF_EST_TOT_H_DIF_1204, X4.QTD_DIAS_EST_TOT_H_DIF_1204, X4.TOTAL_DIAS_DESCONTADO, X4.TOTAL_HORAS_DESCONTADAS, X4.TOTAL_GERAL_DESCONTO_HORAS, X4.TOTAL_REF_FALTA_COMPENS_1004, X4.QTD_DIAS_FALTA_COMPENS_1004, X4.TOTAL_REF_AUSENC_ABONA_EM_DIA, X4.QTD_DIAS_AUSENC_ABONA_EM_DIA, X4.TOTAL_REF_CESSAO_TELETRABALHO, X4.QTD_DIAS_CESSAO_TELETRABALHO, X4.TOTAL_REF_HORA_NORMAL_EM_HORA, X4.QTD_DIAS_HORA_NORMAL_EM_HORA, X4.TOTAL_REF_AUSENC_ABONA_EM_HORA, X4.QTD_DIAS_AUSENC_ABONA_EM_HORA, X4.TOTAL_REF_FALTA_EM_HORAS, X4.QTD_DIAS_FALTA_EM_HORAS
FROM(
----------------------*****************************************mudar datas
SELECT
X3.STATUS_DESCONTO,
SUM(X3.DESCONTO_PROCESSAMENTO)DESCONTO_PROCESSAMENTO, SUM(X3.DESCONTO_IFPONTO)DESCONTO_IFPONTO, SUM(X3.DESCONTO_ARTERH)DESCONTO_ARTERH, COUNT(X3.ORDEM_BM)ORDEM_BM, 
X3.PARTE_PROCESSAMENTO, X3.EMPRESA, X3.TIPO_CONTRATO, X3.MATRICULA, X3.CENARIO, X3.TIPO_FECHAMENTO, 
SUM(X3.QUANT_DIAS)QUANT_DIAS, 
SUM(X3.PREVISTO)PREVISTO, SUM(X3.TOTAL_HORAS_PREVISTAS)TOTAL_HORAS_PREVISTAS, SUM(X3.BH_DEBITO)BH_DEBITO, SUM(X3.DESCONTO)DESCONTO, 
X3.TIPO_ESCALA, X3.CARGA_HORARIA, X3.EMPRESA_ESCALA, X3.COMPRIMENTO_ESCALA, 
SUM(X3.QTD_REGISTROS)QTD_REGISTROS, 
X3.FOLHA_ESPECIAL, X3.REGISTRO_PONTO, X3.COD_VINCULO, 
SUM(X3.ACUMULADO_FALTAS)ACUMULADO_FALTAS, SUM(X3.ACUMULADO_PREVISTO)ACUMULADO_PREVISTO, SUM(X3.ACUMULADO_H_NORMAIS)ACUMULADO_H_NORMAIS, SUM(X3.ACUMULADO_H_DIFERENCIAS)ACUMULADO_H_DIFERENCIAS, SUM(X3.ACUMULADO_H_EXCEDIDAS)ACUMULADO_H_EXCEDIDAS, 
X3.DATA_PROCESSAMENTO, 
SUM(X3.TRABALHOU)TRABALHOU, SUM(X3.FOLGA)FOLGA, SUM(X3.NAO_TRABALHOU)NAO_TRABALHOU, SUM(X3.FERIAS_AFASTAMENTO)FERIAS_AFASTAMENTO,
SUM(X3.JUSTIFICATIVA_ABONADA)JUSTIFICATIVA_ABONADA, SUM(X3.JUSTIFICATIVA_NAO_AVALIADA)JUSTIFICATIVA_NAO_AVALIADA, SUM(X3.JUSTIFICATIVA_NAO_ABONADA)JUSTIFICATIVA_NAO_ABONADA, SUM(X3.ERROS_VERIFICAR)ERROS_VERIFICAR, SUM(X3.TOTAL_DIAS_PROCESSAMENTO)TOTAL_DIAS_PROCESSAMENTO, 
X3.TOTAL_IFPONTO, X3.COD_PESSOA, 
SUM(X3.SOMA_DESCONTO)SOMA_DESCONTO, SUM(X3.QTD_DIAS_DESCONTO)QTD_DIAS_DESCONTO,
--X3.AGRUPADOR, X3.UNIDADE, 
X3.RESULTADOS_ARTERH, X3.CODIGO_EMPRESA, X3.TIPO_CONTRAT, X3.CODIGO_CONTRATO, X3.NOME, X3.COD_SIT_FUNC, X3.SITUACAO_FUNCIONAL, X3.COD_CARGO_EFETIVO, X3.CARGO_EFETIVO, X3.COD_CARGO_COMISSAO, X3.CARGO_COMISSAO, 
X3.COD_FUCNCAO, X3.FUNCAO, X3.COD_CGERENC1, X3.COD_CGERENC2, X3.COD_CGERENC3, X3.COD_CGERENC4, X3.COD_CGERENC5, X3.COD_CGERENC6, X3.CUSTO_GERENCIAL, X3.CODIGO_ESCALA, 
SUM(X3.QTD_TOTAL_MINUTOS_TIPO_JORNAD)QTD_TOTAL_MINUTOS_TIPO_JORNAD, SUM(X3.TOTAL_HORAS_TIPO_JORNADA)TOTAL_HORAS_TIPO_JORNADA, 
X3.CARGA_HORARIA_TIPO_JORNADA, 
SUM(X3.TOTAL_REF_FALTA_0020)TOTAL_REF_FALTA_0020, SUM(X3.QTD_DIAS_FALTA_0020)QTD_DIAS_FALTA_0020, SUM(X3.TOTAL_REF_ESTORNO_FALTA_1015)TOTAL_REF_ESTORNO_FALTA_1015, SUM(X3.QTD_DIAS_ESTORNO_FALTA_1015)QTD_DIAS_ESTORNO_FALTA_1015, SUM(X3.TOTAL_REF_TOT_H_DIF_PER_1013)TOTAL_REF_TOT_H_DIF_PER_1013, SUM(X3.QTD_DIAS_TOT_H_DIF_PER_1013)QTD_DIAS_TOT_H_DIF_PER_1013, 
SUM(X3.TOTAL_REF_EST_TOT_H_DIF_1204)TOTAL_REF_EST_TOT_H_DIF_1204, SUM(X3.QTD_DIAS_EST_TOT_H_DIF_1204)QTD_DIAS_EST_TOT_H_DIF_1204, SUM(X3.TOTAL_DIAS_DESCONTADO)TOTAL_DIAS_DESCONTADO, SUM(X3.TOTAL_HORAS_DESCONTADAS)TOTAL_HORAS_DESCONTADAS, SUM(X3.TOTAL_GERAL_DESCONTO_HORAS)TOTAL_GERAL_DESCONTO_HORAS, SUM(X3.TOTAL_REF_FALTA_COMPENS_1004)TOTAL_REF_FALTA_COMPENS_1004,
SUM(X3.QTD_DIAS_FALTA_COMPENS_1004)QTD_DIAS_FALTA_COMPENS_1004, SUM(X3.TOTAL_REF_AUSENC_ABONA_EM_DIA)TOTAL_REF_AUSENC_ABONA_EM_DIA, SUM(X3.QTD_DIAS_AUSENC_ABONA_EM_DIA)QTD_DIAS_AUSENC_ABONA_EM_DIA, SUM(X3.TOTAL_REF_CESSAO_TELETRABALHO)TOTAL_REF_CESSAO_TELETRABALHO, SUM(X3.QTD_DIAS_CESSAO_TELETRABALHO)QTD_DIAS_CESSAO_TELETRABALHO, 
SUM(X3.TOTAL_REF_HORA_NORMAL_EM_HORA)TOTAL_REF_HORA_NORMAL_EM_HORA, SUM(X3.QTD_DIAS_HORA_NORMAL_EM_HORA)QTD_DIAS_HORA_NORMAL_EM_HORA, SUM(X3.TOTAL_REF_AUSENC_ABONA_EM_HORA)TOTAL_REF_AUSENC_ABONA_EM_HORA, SUM(X3.QTD_DIAS_AUSENC_ABONA_EM_HORA)QTD_DIAS_AUSENC_ABONA_EM_HORA, SUM(X3.TOTAL_REF_FALTA_EM_HORAS)TOTAL_REF_FALTA_EM_HORAS, SUM(X3.QTD_DIAS_FALTA_EM_HORAS)QTD_DIAS_FALTA_EM_HORAS
FROM(
SELECT 
CASE WHEN ROUND(X2.DESCONTO,2) <> ROUND(X2.SOMA_DESCONTO,2) OR ROUND(X2.DESCONTO,2) <> ROUND(X2.TOTAL_GERAL_DESCONTO_HORAS,2) OR ROUND(X2.SOMA_DESCONTO,2) <> ROUND(X2.TOTAL_GERAL_DESCONTO_HORAS,2) THEN 'VERIFICAR' ELSE 'OK' END STATUS_DESCONTO,
ROUND(X2.DESCONTO,2) DESCONTO_PROCESSAMENTO, ROUND(X2.SOMA_DESCONTO,2) DESCONTO_IFPONTO, ROUND(X2.TOTAL_GERAL_DESCONTO_HORAS,2) DESCONTO_ARTERH,
X2.* FROM(
SELECT
ROW_NUMBER() OVER (PARTITION BY X.EMPRESA, X.TIPO_CONTRATO, X.MATRICULA ORDER BY X.EMPRESA, X.TIPO_CONTRATO, X.MATRICULA, X.CENARIO) AS ORDEM_BM,
X.* FROM(
--em 13/5/21 --falta agora juntar essas 3 fontes para soltar um relatorio já fazendo contas entre esses dados 3 apontando possiveis falhas
--CONTINUANDO EM 20/5/21 COM A SIMULACAO PBH TODA ABRIL/21
--TOTAIS DO PROCESSO (totais_periodo_comp_pbh_V8.sql)
SELECT 
'PARTE_PROCESSAMENTO' PARTE_PROCESSAMENTO, P.EMPRESA, P.TIPO_CONTRATO, P.MATRICULA, P.CENARIO, P.TIPO_FECHAMENTO, P.QUANT_DIAS, P.PREVISTO, 
 NVL(P.QUANT_DIAS,0)* NVL(P.PREVISTO,0) AS TOTAL_HORAS_PREVISTAS,
P.BH_DEBITO, NVL(P.DESCONTO,0) DESCONTO, 
P.TIPO_ESCALA, P.CARGA_HORARIA, EPA.CODIGO_LEGADO EMPRESA_ESCALA, EPA.COMPRIMENTO COMPRIMENTO_ESCALA, P.QUANT QTD_REGISTROS,  P.FOLHA_ESPECIAL, 
P.REGISTRO_PONTO, P.COD_VINCULO, P.ACUMULADO_FALTAS, P.ACUMULADO_PREVISTO, P.ACUMULADO_H_NORMAIS, P.ACUMULADO_H_DIFERENCIAS, P.ACUMULADO_H_EXCEDIDAS, P.DATA_PROCESSAMENTO
,P.TRABALHOU, P.FOLGA, P.NAO_TRABALHOU, P.FERIAS_AFASTAMENTO, P.JUSTIFICATIVA_ABONADA, P.JUSTIFICATIVA_NAO_AVALIADA, P.JUSTIFICATIVA_NAO_ABONADA, P.ERROS_VERIFICAR 
,NVL(P.TRABALHOU,0) + NVL(P.FOLGA,0) + NVL(P.NAO_TRABALHOU,0) + NVL(P.FERIAS_AFASTAMENTO,0) + NVL(P.JUSTIFICATIVA_ABONADA,0) + NVL(P.JUSTIFICATIVA_NAO_AVALIADA,0) + NVL(P.JUSTIFICATIVA_NAO_ABONADA,0) + NVL(P.ERROS_VERIFICAR,0) AS TOTAL_DIAS_PROCESSAMENTO

,'TOTAL_IFPONTO' TOTAL_IFPONTO,I.COD_PESSOA, NVL(I.SOMA_DESCONTO,0)SOMA_DESCONTO, I.QTD_DIAS_DESCONTO--, I.AGRUPADOR, I.LOCAL UNIDADE

,'RESULTADOS_ARTERH' RESULTADOS_ARTERH
,A.CODIGO_EMPRESA, A.TIPO_CONTRATO TIPO_CONTRAT, A.CODIGO_CONTRATO, A.NOME, A.COD_SIT_FUNC, A.SITUACAO_FUNCIONAL, A.COD_CARGO_EFETIVO, A.CARGO_EFETIVO, A.COD_CARGO_COMISSAO, A.CARGO_COMISSAO, A.COD_FUCNCAO, A.FUNCAO,
A.COD_CGERENC1, A.COD_CGERENC2, A.COD_CGERENC3, A.COD_CGERENC4, A.COD_CGERENC5, A.COD_CGERENC6, A.CUSTO_GERENCIAL,
A.CODIGO_ESCALA, A.QTD_TOTAL_MINUTOS_TIPO_JORNAD, NVL(A.QTD_TOTAL_MINUTOS_TIPO_JORNAD,0)/60 AS TOTAL_HORAS_TIPO_JORNADA , A.CARGA_HORARIA_TIPO_JORNADA,

A.TOTAL_REF_FALTA_0020, A.QTD_DIAS_FALTA_0020, A.TOTAL_REF_ESTORNO_FALTA_1015, A.QTD_DIAS_ESTORNO_FALTA_1015, 
A.TOTAL_REF_TOT_H_DIF_PER_1013, A.QTD_DIAS_TOT_H_DIF_PER_1013, A.TOTAL_REF_EST_TOT_H_DIF_1204, A.QTD_DIAS_EST_TOT_H_DIF_1204,

NVL(A.TOTAL_REF_FALTA_0020,0)-NVL(A.TOTAL_REF_ESTORNO_FALTA_1015,0) AS TOTAL_DIAS_DESCONTADO, 
NVL(A.TOTAL_REF_TOT_H_DIF_PER_1013,0)-NVL(A.TOTAL_REF_EST_TOT_H_DIF_1204,0)AS TOTAL_HORAS_DESCONTADAS,

((NVL(A.TOTAL_REF_FALTA_0020,0)-NVL(A.TOTAL_REF_ESTORNO_FALTA_1015,0)) * NVL(P.PREVISTO,0))+(NVL(A.TOTAL_REF_TOT_H_DIF_PER_1013,0)-NVL(A.TOTAL_REF_EST_TOT_H_DIF_1204,0))AS TOTAL_GERAL_DESCONTO_HORAS,

A.TOTAL_REF_FALTA_COMPENS_1004, A.QTD_DIAS_FALTA_COMPENS_1004,

A.TOTAL_REF_AUSENC_ABONA_EM_DIA, A.QTD_DIAS_AUSENC_ABONA_EM_DIA, A.TOTAL_REF_CESSAO_TELETRABALHO, A.QTD_DIAS_CESSAO_TELETRABALHO,

A.TOTAL_REF_HORA_NORMAL_EM_HORA, A.QTD_DIAS_HORA_NORMAL_EM_HORA, A.TOTAL_REF_AUSENC_ABONA_EM_HORA, A.QTD_DIAS_AUSENC_ABONA_EM_HORA, A.TOTAL_REF_FALTA_EM_HORAS, A.QTD_DIAS_FALTA_EM_HORAS


FROM PONTO_ELETRONICO.TOTAIS_PERIODO_COMP_PBH P --39.448 EM 21/5/21
LEFT OUTER JOIN ( SELECT X2.* FROM(SELECT ROW_NUMBER() OVER (PARTITION BY X.EMPRESA, X.TIPO_CONTRATO, X.MATRICULA ORDER BY X.DTCADASTRO DESC)ORDEM_BM, X.* FROM PONTO_ELETRONICO.IFPONTO_ESCALA_PESSOA X )X2 WHERE X2.ORDEM_BM = 1 )
EPE ON LPAD(EPE.EMPRESA,4,0) = LPAD(P.EMPRESA,4,0) AND LPAD(EPE.TIPO_CONTRATO,4,0) = LPAD(P.TIPO_CONTRATO,4,0) AND LPAD(EPE.MATRICULA,15,0) = LPAD(P.MATRICULA,15,0)
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_PADRAO EPA ON EPA.CODIGO = EPE.COD_ESCALA_PADRAO 


FULL OUTER JOIN(

---INICIO-------------------------------------------------------------------------------------------------------------------------------DADOS DE DESCONTO NO aRTERH
SELECT * FROM  ARTERH.TOTAIS_PERIODO_SIT_PONTO_ARTE WHERE TRUNC(DATA_PROCESSAMENTO) = TRUNC(SYSDATE)--TO_DATE('11/11/2021','DD/MM/YYYY') -- TRUNC(SYSDATE)  --40.756 EM 21/5/21
)A ON A.CODIGO_EMPRESA = P.EMPRESA AND A.TIPO_CONTRATO = P.TIPO_CONTRATO AND A.CODIGO_CONTRATO = P.MATRICULA
---FIM-----------------------------------------------------------------------------------------------------------------------------------DADOS DE DESCONTO NO aRTERH


FULL OUTER JOIN(

--INICIO----------------------------------------------------------------------------------------------------------------------------------------------------DESCONTO NO iFPONTO
select x.COD_PESSOA, X.EMPRESA, X.TIPO_CONTRATO, X.MATRICULA,-- X.TIPO_ESCALA, X.CARGA_HORARIA, 
--X.AGRUPADOR,
X.SOMA_DESCONTO, X.QTD_DIAS_DESCONTO
--, gn.descricao LOCAL 
from( 
select  
X.COD_PESSOA, x.empresa, x.tipo_contrato, x.matricula,  /* X.COD_ESCALA_PADRAO, x.data,*/-- x.tipo_escala, x.carga_horaria,
--x.agrupador, 
sum(desconto)soma_desconto, count(1) QTD_DIAS_DESCONTO  
from PONTO_ELETRONICO.IFPONTO_ESPELHO_HISTORICA X 
where trunc(x.data) between to_date(vDATA_INICIO,'dd/mm/yyyy') and to_date(vDATA_FIM,'dd/mm/yyyy')  ----------------------*****************************************mudar datas
AND X.data_processamento is null--------------APENAS 
and X.desconto is not null and desconto > 0 -------------------------------------**************************************************************PEGA APENAS QUEM TEVE DESCONTO
--and matricula like '%1138268%'--testes
--AND AGRUPADOR IN ('01.000095.000000.000015.000039.000000.000000','01.000095.000000.000021.000024.000000.000000','01.000095.000000.000016.000030.000000.000000','01.000095.000004.000002.000003.000000.000000','01.000095.000002.000002.000007.000000.000000','01.000095.000000.000020.000027.000000.000000')--NOVO 29/3/21 PARA OS TIPOS DE CONTRATO = 0001 DOS 6 LOCAIS DO PILOTO SMSA
group by X.COD_PESSOA, x.empresa, x.tipo_contrato, x.matricula--, /*X.COD_ESCALA_PADRAO, x.data,*/-- x.tipo_escala, x.carga_horaria,
--x.agrupador 
order by 
--x.agrupador,
x.empresa, x.tipo_contrato, x.matricula  /*X.COD_ESCALA_PADRAO,x.data,*/-- ,x.tipo_escala, x.carga_horaria 
)x 
--LEFT OUTER JOIN RHORGA_CUSTO_GEREN GN ON x.EMPRESA = GN.CODIGO_EMPRESA AND substr(x.agrupador,4,6) = GN.cod_cgerenc1 AND substr(x.agrupador,11,6) = GN.cod_cgerenc2 AND substr(x.agrupador,18,6) = GN.cod_cgerenc3 
--AND substr(x.agrupador,25,6) = GN.cod_cgerenc4 AND substr(x.agrupador,32,6) = GN.cod_cgerenc5 AND substr(x.agrupador,39,6) = GN.cod_cgerenc6 

--LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_PESSOA EPE ON EPE.COD_PESSOA = X.COD_PESSOA
--LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_PADRAO EPA ON EPA.CODIGO = X.COD_ESCALA_PADRAO 
--where gn.data_extincao is null
--order by x.agrupador
)I ON I.EMPRESA = P.EMPRESA AND I.TIPO_CONTRATO = P.TIPO_CONTRATO AND I.MATRICULA = P.MATRICULA 
--FIM--------------------------------------------------------------------------------------------------------------------------------------------------------------DESCONTO NO iFPONTO


WHERE TRUNC(P.DATA_PROCESSAMENTO) = TRUNC(SYSDATE)--TO_DATE('11/11/2021','DD/MM/YYYY') --TRUNC(SYSDATE)--3--24
)X
ORDER BY X.EMPRESA, X.TIPO_CONTRATO, X.MATRICULA , X.CODIGO_EMPRESA, X.TIPO_CONTRAT, X.CODIGO_CONTRATO
)X2
)X3
GROUP BY 
X3.STATUS_DESCONTO, X3.PARTE_PROCESSAMENTO, X3.EMPRESA, X3.TIPO_CONTRATO, X3.MATRICULA, X3.CENARIO, X3.TIPO_FECHAMENTO,
X3.TIPO_ESCALA, X3.CARGA_HORARIA, X3.EMPRESA_ESCALA, X3.COMPRIMENTO_ESCALA, 
X3.FOLHA_ESPECIAL, X3.REGISTRO_PONTO, X3.COD_VINCULO, 
X3.DATA_PROCESSAMENTO, 
X3.TOTAL_IFPONTO, X3.COD_PESSOA, 
--X3.AGRUPADOR, X3.UNIDADE, 
X3.RESULTADOS_ARTERH, X3.CODIGO_EMPRESA, X3.TIPO_CONTRAT, X3.CODIGO_CONTRATO, X3.NOME, X3.COD_SIT_FUNC, X3.SITUACAO_FUNCIONAL, X3.COD_CARGO_EFETIVO, X3.CARGO_EFETIVO, X3.COD_CARGO_COMISSAO, X3.CARGO_COMISSAO, 
X3.COD_FUCNCAO, X3.FUNCAO, X3.COD_CGERENC1, X3.COD_CGERENC2, X3.COD_CGERENC3, X3.COD_CGERENC4, X3.COD_CGERENC5, X3.COD_CGERENC6, X3.CUSTO_GERENCIAL, X3.CODIGO_ESCALA, 
X3.CARGA_HORARIA_TIPO_JORNADA
ORDER BY
X3.EMPRESA, X3.TIPO_CONTRATO, X3.MATRICULA, X3.CENARIO, X3.TIPO_FECHAMENTO,
X3.TIPO_ESCALA, X3.CARGA_HORARIA, X3.EMPRESA_ESCALA, X3.COMPRIMENTO_ESCALA, 
X3.FOLHA_ESPECIAL, X3.REGISTRO_PONTO, X3.COD_VINCULO, 
X3.DATA_PROCESSAMENTO, 
X3.TOTAL_IFPONTO, X3.COD_PESSOA, 
--X3.AGRUPADOR, X3.UNIDADE, 
X3.RESULTADOS_ARTERH, X3.CODIGO_EMPRESA, X3.TIPO_CONTRAT, X3.CODIGO_CONTRATO, X3.NOME, X3.COD_SIT_FUNC, X3.SITUACAO_FUNCIONAL, X3.COD_CARGO_EFETIVO, X3.CARGO_EFETIVO, X3.COD_CARGO_COMISSAO, X3.CARGO_COMISSAO, 
X3.COD_FUCNCAO, X3.FUNCAO, X3.COD_CGERENC1, X3.COD_CGERENC2, X3.COD_CGERENC3, X3.COD_CGERENC4, X3.COD_CGERENC5, X3.COD_CGERENC6, X3.CUSTO_GERENCIAL, X3.CODIGO_ESCALA, 
X3.CARGA_HORARIA_TIPO_JORNADA
)X4
--FIM BASE desconto_vs_compensacao_pbh_v2.sql---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
LEFT OUTER JOIN (select EP.CODIGO_LEGADO, COUNT(1)QTD_DIAS_ESCALA from PONTO_ELETRONICO.IFPONTO_RL_ESC_HOR IFH LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_HORARIO EH ON EH.CODIGO = IFH.CODIGO
LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_PADRAO EP ON EP.CODIGO = EH.COD_ESCALA_PADRAO
GROUP BY EP.CODIGO_LEGADO 
)IFH ON IFH.CODIGO_LEGADO = X4.EMPRESA_ESCALA 

--inicio---------------------------------------------------------------------------------- novo em 24/6/21
LEFT OUTER JOIN
(
SELECT X2.* FROM(SELECT ROW_NUMBER() OVER(PARTITION BY X.CODIGO_LEGADO ORDER BY X.TIPO_DIA)ORDEM_ESCALA, X.CODIGO_LEGADO, X.QTD_DIAS, X.TIPO_DIA, LEAD(X.QTD_DIAS,1, NULL)OVER (PARTITION BY X.CODIGO_LEGADO ORDER BY X.TIPO_DIA) PROXIMO_QTD_DIAS, LEAD(X.TIPO_DIA,1, NULL)OVER (PARTITION BY X.CODIGO_LEGADO ORDER BY X.TIPO_DIA) PROXIMO_TIPO_DIA FROM(SELECT E.CODIGO_LEGADO,COUNT(1)QTD_DIAS, IEH.TIPO_DIA FROM PONTO_ELETRONICO.IFPONTO_RL_ESC_HOR IEH LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_HORARIO EH ON IEH.CODIGO = EH.CODIGO LEFT OUTER JOIN PONTO_ELETRONICO.IFPONTO_ESCALA_PADRAO E ON E.CODIGO = EH.COD_ESCALA_PADRAO GROUP BY IEH.TIPO_DIA, E.CODIGO_LEGADO ORDER BY  E.CODIGO_LEGADO, IEH.TIPO_DIA )X )X2 WHERE X2.ORDEM_ESCALA = 1
)PD ON PD.CODIGO_LEGADO = X4.EMPRESA_ESCALA

--LEFT OUTER JOIN ARTERH.RHPONT_ESCALA E ON E.CODIGO_EMPRESA = LPAD(SUBSTR(X4.EMPRESA_ESCALA,1,2),4,0) AND E.CODIGO = LPAD(SUBSTR(X4.EMPRESA_ESCALA,3,4),4,0)
LEFT OUTER JOIN
(
--CARGO X JORNADA
select E.CODIGO CODIGO_ESCALA, CJ.codigo_empresa, CJ.codigo_cargo, C.DESCRICAO CARGO,
CJ.tipo_jornada, CJ.CODIGO_TABELA,
J.DESCRICAO JORNADA, J.C_LIVRE_SELEC01 QDT_TOTAL_MINUTOS_JORNADA, J.C_LIVRE_DESCR02 TIPO_CARGA_HORARIA_JORNADA, J.C_LIVRE_DATA03 DATA_EXTINCAO_JORNADA,
CJ.c_livre_opcao01 JORNADA_PRINCIPAL 
from ARTERH.RHPLCS_CARG_JOR_TB CJ 
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO C ON C.CODIGO_EMPRESA = CJ.CODIGO_EMPRESA AND C.CODIGO = CJ.CODIGO_CARGO
LEFT OUTER JOIN ARTERH.RHPONT_TP_JORNADA J ON J.CODIGO = CJ.TIPO_JORNADA
LEFT OUTER JOIN ARTERH.RHPONT_ESCALA E ON E.CODIGO_EMPRESA = CJ.CODIGO_EMPRESA AND CJ.TIPO_JORNADA= E.TIPO_JORNADA
WHERE CJ.CODIGO_EMPRESA IN ('0001') AND J.C_LIVRE_DATA03 IS NULL
)CJ ON CJ.CODIGO_EMPRESA = LPAD(SUBSTR(X4.EMPRESA_ESCALA,1,2),4,0) AND CJ.CODIGO_ESCALA = LPAD(SUBSTR(X4.EMPRESA_ESCALA,3,4),4,0) AND CJ.CODIGO_CARGO = X4.COD_CARGO_EFETIVO
--ON CJ.TIPO_JORNADA = E.TIPO_JORNADA AND CJ.CODIGO_EMPRESA = E.CODIGO_EMPRESA AND 

----------------------------------------------------inicio em 25/6/21 sql_TOTAL_MINUTOS_DIA.sql
LEFT OUTER JOIN
(SELECT TME.CODIGO_EMPRESA, TME.CODIGO_ESCALA, SUM(TME.MINUTOS_DIA) SOMA_MINUTOS_ESCALA, SUM(TME.MINUTOS_DIA)/60 SOMA_HORAS_ESCALA FROM (--ANALITICO
SELECT EH.*, 
H.CODIGO, H.DESCRICAO, H.TIPO_HORARIO, H.HORARIO_NORMAL_1, h.dia_ocorrencia1, H.HORARIO_NORMAL_2, h.dia_ocorrencia2, H.HORARIO_NORMAL_3, h.dia_ocorrencia3, H.HORARIO_NORMAL_4, h.dia_ocorrencia4,
CASE 
WHEN H.TIPO_HORARIO NOT IN ('T','N') THEN 0 --DIAS DE FOLGA
--ERRO NAS MARCACOES APENAS COM A PRIMEIRA MARCACAO
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND 
(H.HORARIO_NORMAL_2 IS NULL OR TRIM(H.HORARIO_NORMAL_2)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_2)) <> 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4)
THEN 0
--ERRO NAS MARCACOES APENAS COM A SEGUNDA MARCACAO
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NULL OR TRIM(H.HORARIO_NORMAL_1)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_1)) <> 4) AND 
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4)
THEN 0
--ERRO NAS MARCACOES APENAS COM A TERCEIRA MARCACAO
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NULL OR TRIM(H.HORARIO_NORMAL_1)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_1)) <> 4) AND 
(H.HORARIO_NORMAL_2 IS NULL OR TRIM(H.HORARIO_NORMAL_2)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_2)) <> 4) AND 
(H.HORARIO_NORMAL_3 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_3) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_3)) = 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4)
THEN 0
--ERRO NAS MARCACOES APENAS COM A QUARTA MARCACAO
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NULL OR TRIM(H.HORARIO_NORMAL_1)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_1)) <> 4) AND 
(H.HORARIO_NORMAL_2 IS NULL OR TRIM(H.HORARIO_NORMAL_2)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_2)) <> 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND
(H.HORARIO_NORMAL_4 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_4) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_4)) = 4) 
THEN 0
--4 MARCACAOES NO MESMO DIA
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_3) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_3)) = 4) AND 
(H.HORARIO_NORMAL_4 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_4) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_4)) = 4) 
AND (H.HORARIO_NORMAL_1 < H.HORARIO_NORMAL_2  AND H.HORARIO_NORMAL_2 < H.HORARIO_NORMAL_3 AND H.HORARIO_NORMAL_3 < H.HORARIO_NORMAL_4)
THEN ( (SUBSTR(H.HORARIO_NORMAL_4,1,2)*60+SUBSTR(H.HORARIO_NORMAL_4,3,2)) - (SUBSTR(H.HORARIO_NORMAL_3,1,2)*60+SUBSTR(H.HORARIO_NORMAL_3,3,2)) ) + ( (SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2)) - (SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2)) )
--4 MARCACAOES PASSANDO PELA MEIA NOITE 1 MARCACAO + 3 NO OUTRO DIA
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_3) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_3)) = 4) AND 
(H.HORARIO_NORMAL_4 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_4) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_4)) = 4) 
AND (H.HORARIO_NORMAL_1 > H.HORARIO_NORMAL_2  AND H.HORARIO_NORMAL_2 < H.HORARIO_NORMAL_3 AND H.HORARIO_NORMAL_3 < H.HORARIO_NORMAL_4)
--AND (H.HORARIO_NORMAL_1 > H.HORARIO_NORMAL_2 AND H.HORARIO_NORMAL_3 < H.HORARIO_NORMAL_4)--1>2, 2<3, 3<4
THEN (1440 -(SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2)) ) + ((SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2))) + ( (SUBSTR(H.HORARIO_NORMAL_4,1,2)*60+SUBSTR(H.HORARIO_NORMAL_4,3,2)) - (SUBSTR(H.HORARIO_NORMAL_3,1,2)*60+SUBSTR(H.HORARIO_NORMAL_3,3,2)) )
--4 MARCACAOES PASSANDO PELA MEIA NOITE 2 MARCACAO + 2 NO OUTRO DIA
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_3) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_3)) = 4) AND 
(H.HORARIO_NORMAL_4 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_4) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_4)) = 4) 
AND (H.HORARIO_NORMAL_1 < H.HORARIO_NORMAL_2  AND H.HORARIO_NORMAL_2 > H.HORARIO_NORMAL_3 AND H.HORARIO_NORMAL_3 < H.HORARIO_NORMAL_4)--verificar 1<2, 2>3, 3<4
THEN ( (SUBSTR(H.HORARIO_NORMAL_4,1,2)*60+SUBSTR(H.HORARIO_NORMAL_4,3,2)) - (SUBSTR(H.HORARIO_NORMAL_3,1,2)*60+SUBSTR(H.HORARIO_NORMAL_3,3,2)) ) + ( (SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2)) - (SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2)) )
--4 MARCACAOES PASSANDO PELA MEIA NOITE 3 MARCACAO + 1 NO OUTRO DIA
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_3) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_3)) = 4) AND 
(H.HORARIO_NORMAL_4 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_4) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_4)) = 4) 
AND (H.HORARIO_NORMAL_1 < H.HORARIO_NORMAL_2 AND H.HORARIO_NORMAL_2 < H.HORARIO_NORMAL_3 AND H.HORARIO_NORMAL_3 > H.HORARIO_NORMAL_4)--1<2, 2<3, 3>4
THEN ( (SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2)) - (SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2)) ) + (1440-(SUBSTR(H.HORARIO_NORMAL_3,1,2)*60+SUBSTR(H.HORARIO_NORMAL_3,3,2)))+ (SUBSTR(H.HORARIO_NORMAL_4,1,2)*60+SUBSTR(H.HORARIO_NORMAL_4,3,2))

--2 MARCACOES NO MESMO DIA
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND 
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4) 
AND (TO_NUMBER(H.HORARIO_NORMAL_1) < TO_NUMBER(H.HORARIO_NORMAL_2))
THEN (SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2)) - (SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2))
--2 MARCACOES PASSANDO PELA MEIA NOITE
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND 
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4) 
AND (H.HORARIO_NORMAL_1 > H.HORARIO_NORMAL_2)
THEN (1440 -(SUBSTR(H.HORARIO_NORMAL_1,1,2)*60+SUBSTR(H.HORARIO_NORMAL_1,3,2)) ) + ((SUBSTR(H.HORARIO_NORMAL_2,1,2)*60+SUBSTR(H.HORARIO_NORMAL_2,3,2)))
--2 MARCACOES 24 HORAS DE TRABALHO
WHEN H.TIPO_HORARIO IN ('T','N') AND
(H.HORARIO_NORMAL_1 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_1) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_1)) = 4) AND 
(H.HORARIO_NORMAL_2 IS NOT NULL AND TRIM(H.HORARIO_NORMAL_2) <>'0000' AND LENGTH(TRIM(H.HORARIO_NORMAL_2)) = 4) AND 
(H.HORARIO_NORMAL_3 IS NULL OR TRIM(H.HORARIO_NORMAL_3)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_3)) <> 4) AND 
(H.HORARIO_NORMAL_4 IS NULL OR TRIM(H.HORARIO_NORMAL_4)  = '0000' OR LENGTH(TRIM(H.HORARIO_NORMAL_4)) <> 4) 
AND (H.HORARIO_NORMAL_1 = H.HORARIO_NORMAL_2) AND H.DIA_OCORRENCIA1 = 'C' AND H.DIA_OCORRENCIA2 = 'S'
THEN 1440
ELSE 0
END MINUTOS_DIA
FROM
ARTERH.RHPONT_RL_ESC_HOR EH
LEFT OUTER JOIN ARTERH.RHPONT_ESCALA E ON EH.CODIGO_EMPRESA = E.CODIGO_EMPRESA AND EH.CODIGO_ESCALA = E.CODIGO
LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H ON EH.CODIGO_EMPRESA = H.CODIGO_EMPRESA AND EH.CODIGO_HORARIO = H.CODIGO
WHERE EH.CODIGO_EMPRESA = '0001' AND E.data_extincao IS NULL --AND H.TIPO_HORARIO IN ('T','N')
ORDER BY EH.CODIGO_ESCALA, EH.OCORRENCIA
)TME  GROUP BY TME.CODIGO_EMPRESA, TME.CODIGO_ESCALA ORDER BY TME.CODIGO_EMPRESA, TME.CODIGO_ESCALA --SINTETICO
)TME 
--mudado em 1/7/21 --ON TME.CODIGO_EMPRESA = CJ.CODIGO_EMPRESA AND TME.CODIGO_ESCALA = CJ.CODIGO_ESCALA
 ON TME.CODIGO_EMPRESA = LPAD(SUBSTR(X4.EMPRESA_ESCALA,1,2),4,0) AND TME.CODIGO_ESCALA = LPAD(SUBSTR(X4.EMPRESA_ESCALA,3,4),4,0) AND CJ.CODIGO_CARGO = X4.COD_CARGO_EFETIVO
--fim em 25/6/21 sql_TOTAL_MINUTOS_DIA.sql
--------------------------------------------------------------------------------------------fim novo em 24/6/21

--ANALISE SMSA
)X5
)X6
ORDER BY LINHA

)LOOP

vCONTADOR :=vCONTADOR+1;
dbms_output.put_line('--vCONTADOR: '||vCONTADOR||' C1.LINHA: '||C1.LINHA);
INSERT INTO PONTO_ELETRONICO.IFPONTO_FECHAMENTO_LOG_RELAT (DATA_DADOS, CAMPO_1, CONSIDERACOES,CODIGO_EMPRESA)VALUES(SYSDATE,'PRR_DESCONTOS_FECHAMENTO',C1.LINHA, SUBSTR(C1.LINHA,21,4));COMMIT;

END LOOP;

END;

END;
