
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."SANEAMENTO_CONTRATO" AS 

BEGIN

  DECLARE
    vDATA_SISTEMA DATE;
    vANO_MES_REF_ULT_CONTRATO DATE;
    vDATA_NOMEACAO DATE;
    vDATA_POSSE DATE;
    vDATA_EFETIVO_EXERC DATE;
    vC_LIVRE_DATA28 DATE;
    vC_LIVRE_DATA32 DATE;
    vDATA_ADMISSAO DATE;
    vDATA_OPTANTE DATE;

PROCEDURE ATUALIZA_CONTRATO_MESTRE (vCODIGO_CONTRATO VARCHAR2, vTIPO_CONTRATO VARCHAR2, vCODIGO_EMPRESA VARCHAR2, vDT_SISTEMA DATE, vLOGIN_USUARIO VARCHAR2) AS

CONT NUMBER;
BEGIN
FOR A1 IN (
SELECT CODIGO_EMPRESA,
       TIPO_CONTRATO,
       CODIGO_CONTRATO,
       ULTIMA_DATA,
       DATA_ADMISSAO,
       DATA_RESCISAO,
       CASE WHEN ULTIMA_DATA < vDATA_SISTEMA THEN 'ULTIMA_DATA MENOR QUE vDATA_SISTEMA'
            WHEN ULTIMA_DATA > vDATA_SISTEMA THEN 'ULTIMA_DATA MAIOR QUE vDATA_SISTEMA'
            WHEN ULTIMA_DATA = TRUNC(vDATA_SISTEMA) THEN 'ULTIMA_DATA IGUAL QUE vDATA_SISTEMA'
            ELSE 'ANALISAR' END AS ANALISE_DATAS
  FROM ARTERH.RHPESS_CONTR_MEST
 WHERE CODIGO_EMPRESA = vCODIGO_EMPRESA
   AND TIPO_CONTRATO   = vTIPO_CONTRATO
   AND CODIGO_CONTRATO = vCODIGO_CONTRATO

)LOOP
dbms_output.put_line('ENTROU NO ATUALIZA_CONTRATO_MESTRE :'||A1.ANALISE_DATAS||' CONTRATO: '||vCODIGO_CONTRATO);
IF A1.ANALISE_DATAS = 'ULTIMA_DATA MENOR QUE vDATA_SISTEMA' THEN 
   UPDATE RHPESS_CONTR_MEST SET ULTIMA_DATA = TO_DATE(vDT_SISTEMA,'DD/MM/YYYY'), LOGIN_USUARIO = vLOGIN_USUARIO, DT_ULT_ALTER_USUA = SYSDATE 
   WHERE CODIGO_EMPRESA = vCODIGO_EMPRESA AND TIPO_CONTRATO = vTIPO_CONTRATO AND CODIGO_CONTRATO = vCODIGO_CONTRATO; COMMIT WORK;
END IF;

END LOOP;

END;

BEGIN    

vDATA_OPTANTE := TO_DATE('01/01/1997','DD/MM/YYYY');

FOR C2 IN
(
select ANO_MES_REFERENCIA, 
CODIGO_EMPRESA,
CODIGO,
TIPO_CONTRATO,
DATA_ADMISSAO,
DATA_EFETIVO_EXERC,
DATA_NOMEACAO,
DATA_POSSE,
C_LIVRE_DATA28,
C_LIVRE_DATA32,
DT_ULT_ALTER_USUA,
LOGIN_USUARIO,
LOGIN_IMPORTACAO_INTERFACE,
DATA_PROCESSAMENTO,
DATA_CARGA,
STATUS_PROCESSAMENTO
from SUGESP_SANEAMENTO_DT_CONTRATO 
WHERE DATA_CARGA = (select max (a.DATA_CARGA)
                            from SUGESP_SANEAMENTO_DT_CONTRATO a
												    where a.codigo = SUGESP_SANEAMENTO_DT_CONTRATO.codigo and
                                  a.codigo_empresa = SUGESP_SANEAMENTO_DT_CONTRATO.codigo_empresa and
                                  a.tipo_contrato = SUGESP_SANEAMENTO_DT_CONTRATO.tipo_contrato)

)--FIM DO FOR

LOOP

SELECT DATA_DO_SISTEMA INTO vDATA_SISTEMA from rhparm_p_sist;

--EMITIR O ULTIMO CONTRATO E A DATAS QUE SERÃO ATUALIZADAS
SELECT C.ANO_MES_REFERENCIA, c.DATA_ADMISSAO, c.DATA_NOMEACAO, c.DATA_POSSE, c.DATA_EFETIVO_EXERC, c.C_LIVRE_DATA28, c.C_LIVRE_DATA32
INTO vANO_MES_REF_ULT_CONTRATO, vDATA_ADMISSAO, vDATA_NOMEACAO, vDATA_POSSE, vDATA_EFETIVO_EXERC, vC_LIVRE_DATA28, vC_LIVRE_DATA32
FROM RHPESS_CONTRATO C
WHERE C.CODIGO_EMPRESA   = C2.CODIGO_EMPRESA
AND C.TIPO_CONTRATO      = C2.TIPO_CONTRATO
AND C.CODIGO             = C2.CODIGO
AND C.ANO_MES_REFERENCIA =
  (SELECT MAX(AUX.ano_mes_referencia)
  FROM rhpess_contrato AUX
  WHERE AUX.codigo_empresa = c.codigo_empresa
  AND AUX.tipo_contrato    = c.tipo_contrato
  AND AUX.codigo           = c.codigo
    --and AUX.ano_mes_referencia <= vDATA_SISTEMA
  );

IF 
(   --VERIFICA SE O CONTRATO POSSUI O ANO_MES_REFERENCIA MAIOR OU IGUAL A DATA DO SISTEMA, DE ACORDO COM O SELECT DATA_DO_SISTEMA from rhparm_p_sist; 
    (TO_DATE('01'||SUBSTR(vANO_MES_REF_ULT_CONTRATO,3,8),'DD/MM/YYYY') >= TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YYYY')) AND
    (c2.DATA_PROCESSAMENTO IS NULL AND C2.STATUS_PROCESSAMENTO IS NULL) 
    AND 
    (
        ( -- SE A DATA DE EFETIVO EXERCICIO ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA_EFETIVO_EXERC DO CONTRATO
          (C2.DATA_EFETIVO_EXERC IS NOT NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A DATA_EFETIVO_EXERC ESTIVER EM BRANCO E NA A DATA_EFETIVO_EXERC NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        ) 
        OR
        ( -- SE A DATA_NOMEACAO ESTIVER PREENCHIDA E FOR DIFERENTE DA DDATA_NOMEACAO DO CONTRATO
          (C2.DATA_NOMEACAO IS NOT NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A DATA_NOMEACAO ESTIVER EM BRANCO E NA A DATA_NOMEACAO NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        )
        OR
        (
            ( -- SE A DATA_POSSE ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA_POSSE DO CONTRATO
              (C2.DATA_POSSE IS NOT NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY'))  
              OR 
              --OU SE A DATA_POSSE ESTIVER EM BRANCO E NA A DATA_POSSE NA TABELA TEMPORARIA ESTIVER PREENCHIDA
              (to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
            ) --A DATA DE POSSE DEVE SER MAIOR OU IGUAL A DATA DE ADMISSÃO
            AND  to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') >= to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') 
          )
        OR
        (
          ( -- SE A DATA DE C_LIVRE_DATA28 ESTIVER PREENCHIDA E FOR DIFERENTE DA C_LIVRE_DATA28 DO CONTRATO
            (C2.C_LIVRE_DATA28 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY'))  
            OR 
            --OU SE A C_LIVRE_DATA28 ESTIVER EM BRANCO E NA A C_LIVRE_DATA28 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
            (to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
          )-- E VERIFICA SE A DATA DE ADMISSÃO É MENOR QUE DATA_OPTANTE = '01/01/1997' (DATA INFORMADA PELA GEVIF)
          AND to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') < to_date(to_char(vDATA_OPTANTE,'DD/MM/YYYY'),'DD/MM/YYYY')
        )
        OR
        ( -- SE A C_LIVRE_DATA32 ESTIVER PREENCHIDA E FOR DIFERENTE DA C_LIVRE_DATA32 DO CONTRATO
          (C2.C_LIVRE_DATA32 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A C_LIVRE_DATA32 ESTIVER EM BRANCO E NA A C_LIVRE_DATA32 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        )
    )
) THEN 

dbms_output.put_line('--'||c2.codigo);
-------------------------------------*******************************ATUALIZA CONTRATO MES SISTEMA E FUTUROS
/*dbms_output.put_line('--FAZER UPDATE DO CONTRATO '||C2.CODIGO||' ANO MES REFERENCIA: '||vANO_MES_REF_ULT_CONTRATO);
dbms_output.put_line('--DATA DO OPTANTE '|| TO_CHAR(vDATA_OPTANTE,'DD/MM/YYYY'));*/
--ATUALIZA A DATA DO EFETIVO EXERCICIO
IF (
      (-- SE A DATA DE EFETIVO EXERCICIO ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA_EFETIVO_EXERC DO CONTRATO
      C2.DATA_EFETIVO_EXERC IS NOT NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (--OU SE A DATA DE EFETIVO EXERCICIO ESTIVER EM BRANCO E NA A DATA DE EFETIVO EXERCICIO NA TABELA TEMPORARIA ESTIVER PREENCHIDA
      to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN
   -- ENTÃO ATUALIZA A DATA DE EFETIVO EXERCICIO DO CONTRATO, ONDE OANO MÊS REFERENCIA É MAIOR OU IGUAL A DATA DO SISTEMA 
UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_EFETIVO_EXERC = TRUNC(C2.DATA_EFETIVO_EXERC) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA DA NOMEAÇÃO
IF (
      (-- SE A DATA DE NOMEAÇÃO ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA DE NOMEAÇÃO DO CONTRATO
      C2.DATA_NOMEACAO IS NOT NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (--OU SE A DATA DE NOMEAÇÃO ESTIVER EM BRANCO E NA A DATA NOMEAÇÃO NA TABELA TEMPORARIA ESTIVER PREENCHIDA
      to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN
   -- ENTÃO ATUALIZA A DATA DE NOMEAÇÃO DO CONTRATO, ONDE OANO MÊS REFERENCIA É MAIOR OU IGUAL A DATA DO SISTEMA 
UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_NOMEACAO = TRUNC(C2.DATA_NOMEACAO) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA DA POSSE
IF (  (
        (
        C2.DATA_POSSE IS NOT NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY')
        )  
        OR 
        (
        to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
        ) -- E A DATA DE POSSE DEVE SER MAIOR OU IGUAL A DATA DE ADMISSÃO.
      ) AND  to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') >= to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') 
   ) THEN
-- ENTÃO ATUALIZA A DATA DA POSSE DO CONTRATO, ONDE OANO MÊS REFERENCIA É MAIOR OU IGUAL A DATA DO SISTEMA    
UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_POSSE = TRUNC(C2.DATA_POSSE) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA C_LIVRE_DATA28 (Estatutario optante)
IF (
      (
        (-- SE A DATA C_LIVRE_DATA28 ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA C_LIVRE_DATA28 DO CONTRATO
          C2.C_LIVRE_DATA28 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') 
        )  
        OR 
        (--OU SE A DATA C_LIVRE_DATA28 ESTIVER EM BRANCO E NA A DATA C_LIVRE_DATA28 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
        to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
        )
      ) -- E VERIFICA SE A DATA DE ADMISSÃO É MENOR QUE DATA_OPTANTE = '01/01/1997' (DATA INFORMADA PELA GEVIF)
      AND to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') < to_date(to_char(vDATA_OPTANTE,'DD/MM/YYYY'),'DD/MM/YYYY')
   )THEN 
-- ENTÃO ATUALIZA A DATA C_LIVRE_DATA28 DO CONTRATO, ONDE O ANO MÊS REFERENCIA É MAIOR OU IGUAL A DATA DO SISTEMA        
UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, C_LIVRE_DATA28 = TRUNC(C2.C_LIVRE_DATA28) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA C_LIVRE_DATA32 (Homolog. Concurso)
IF (
      (-- SE A DATA C_LIVRE_DATA32 ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA C_LIVRE_DATA32 DO CONTRATO
      C2.C_LIVRE_DATA32 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (--OU SE A DATA C_LIVRE_DATA32 ESTIVER EM BRANCO E NA A DATA C_LIVRE_DATA32 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
      to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN
-- ENTÃO ATUALIZA A DATA C_LIVRE_DATA32 DO CONTRATO, ONDE O ANO MÊS REFERENCIA É MAIOR OU IGUAL A DATA DO SISTEMA           
UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, C_LIVRE_DATA32  = TRUNC(C2.C_LIVRE_DATA32) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

update SUGESP_SANEAMENTO_DT_CONTRATO set DATA_PROCESSAMENTO = sysdate, STATUS_PROCESSAMENTO = 'OK' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL and trunc(data_carga) = TRUNC(c2.DATA_CARGA) and codigo_empresa = ''||c2.codigo_empresa||'' and tipo_contrato = ''||c2.tipo_contrato||'' and codigo = ''||c2.codigo||'' ;
COMMIT;

END IF;
--dbms_output.put_line('UPDATE update SUGESP_SANEAMENTO_DT_CONTRATO set DATA_PROCESSAMENTO = sysdate, STATUS_PROCESSAMENTO = ''OK'' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL and trunc(data_carga) = TRUNC(sysdate) and codigo_empresa = '''||c2.codigo_empresa||''' and tipo_contrato = '''||c2.tipo_contrato||''' and codigo = '''||c2.codigo||''' ;');


IF 
(    --VERIFICA SE O CONTRATO POSSUI O ANO_MES_REFERENCIA MENOR QUE A DATA DO SISTEMA, DE ACORDO COM O SELECT DATA_DO_SISTEMA from rhparm_p_sist;
    (TO_DATE('01'||SUBSTR(vANO_MES_REF_ULT_CONTRATO,3,8),'DD/MM/YYYY') < TO_DATE('01'||SUBSTR(vDATA_SISTEMA,3,8),'DD/MM/YYYY'))AND
    (c2.DATA_PROCESSAMENTO IS NULL AND C2.STATUS_PROCESSAMENTO IS NULL)  
    AND 
    (
        ( -- SE A DATA DE EFETIVO EXERCICIO ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA_EFETIVO_EXERC DO CONTRATO
          (C2.DATA_EFETIVO_EXERC IS NOT NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A DATA_EFETIVO_EXERC ESTIVER EM BRANCO E NA A DATA_EFETIVO_EXERC NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        ) 
        OR
        (-- SE A DATA_NOMEACAO ESTIVER PREENCHIDA E FOR DIFERENTE DA DDATA_NOMEACAO DO CONTRATO
          (C2.DATA_NOMEACAO IS NOT NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A DATA_NOMEACAO ESTIVER EM BRANCO E NA A DATA_NOMEACAO NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        )
        OR
        (
          (-- SE A DATA_POSSE ESTIVER PREENCHIDA E FOR DIFERENTE DA DATA_POSSE DO CONTRATO
            (C2.DATA_POSSE IS NOT NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY'))  
            OR 
            --OU SE A DATA_POSSE ESTIVER EM BRANCO E NA A DATA_POSSE NA TABELA TEMPORARIA ESTIVER PREENCHIDA
            (to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
          ) -- A DATA DE POSSE DEVE SER MAIOR OU IGUAL A DATA DE ADMISSÃO
          AND  to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') >= to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') 
        )
        OR
        (
          (-- SE A DATA DE C_LIVRE_DATA28 ESTIVER PREENCHIDA E FOR DIFERENTE DA C_LIVRE_DATA28 DO CONTRATO
            (C2.C_LIVRE_DATA28 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY'))  
            OR
            --OU SE A C_LIVRE_DATA28 ESTIVER EM BRANCO E NA A C_LIVRE_DATA28 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
            (to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
          )-- E VERIFICA SE A DATA DE ADMISSÃO É MENOR QUE DATA_OPTANTE = '01/01/1997' (DATA INFORMADA PELA GEVIF)
          AND to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') < to_date(to_char(vDATA_OPTANTE,'DD/MM/YYYY'),'DD/MM/YYYY')
        )
        OR
        (-- SE A C_LIVRE_DATA32 ESTIVER PREENCHIDA E FOR DIFERENTE DA C_LIVRE_DATA32 DO CONTRATO
          (C2.C_LIVRE_DATA32 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY'))  
          OR 
          --OU SE A C_LIVRE_DATA32 ESTIVER EM BRANCO E NA A C_LIVRE_DATA32 NA TABELA TEMPORARIA ESTIVER PREENCHIDA
          (to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL)
        )
    )
) THEN 
--ENTÃO INSERE O CONTRATO NO ANO MÊS REFERENCIA DE ACORDO COM A DATA DO SISTEMA, NA TABELA RHPARM_P_SIST (DATA_DO_SISTEMA)
/*dbms_output.put_line('--INSERIR CONTRATO NO MES ATUAL '||C2.CODIGO||' ANO MES REFERENCIA: '||vANO_MES_REF_ULT_CONTRATO);
dbms_output.put_line('--'||c2.codigo);*/
-------------------------------------*******************************INSERE CONTRATO MES SISTEMA
INSERT INTO RHPESS_CONTRATO C
SELECT CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
CODIGO_PESSOA,
NOME,
REGISTRO,
NUMERO_ARQUIVO,
SITUACAO_FUNCIONAL,
SITUACAO_CONTRATO,
STATUS_CONTRATO,
DATA_ADMISSAO,
MOTIVO_ADMISSAO,
MOTIVO_DEMISSAO,
TIPO_PAGAMENTO,
TIPO_SALARIO,
VINCULO,
FORMA_PROVIMENTO,
COD_LOCAL1,
COD_LOCAL2,
COD_LOCAL3,
COD_LOCAL4,
COD_LOCAL5,
COD_LOCAL6,
DT_ULT_ALT_LOC,
COD_UNIDADE1,
COD_UNIDADE2,
COD_UNIDADE3,
COD_UNIDADE4,
COD_UNIDADE5,
COD_UNIDADE6,
DT_ULT_ALT_UNID,
COD_CUSTO_CONTAB1,
COD_CUSTO_CONTAB2,
COD_CUSTO_CONTAB3,
COD_CUSTO_CONTAB4,
COD_CUSTO_CONTAB5,
COD_CUSTO_CONTAB6,
DT_ULT_ALT_CONT,
COD_CUSTO_GERENC1,
COD_CUSTO_GERENC2,
COD_CUSTO_GERENC3,
COD_CUSTO_GERENC4,
COD_CUSTO_GERENC5,
COD_CUSTO_GERENC6,
DT_ULT_ALT_GER,
SALARIO_PAGTO,
COD_CARGO_PAGTO,
NIVEL_CARGO_PAGTO,
COD_CARGO_EFETIVO,
NIVEL_CARGO_EFETIV,
DT_ULT_CARGO_EFET,
COD_CARGO_COMISS,
NIVEL_CARGO_COMISS,
DT_ULT_CARGO_COM,
COD_CARGO_AMPAR,
NIVEL_CARGO_AMPAR,
DT_ULT_CARGO_AMPAR,
CODIGO_FUNCAO,
DT_ULT_FUNCAO,
COD_ESPECIALIDADE,
DT_ULT_ESPEC,
CODIGO_VAGA,
DT_ULT_VAGA,
AREA_ATUACAO,
CATEG_PROFISSIONAL,
CODIGO_ESCALA,
REGISTRO_PONTO,
DT_ULT_ESCALA,
CODIGO_BANCO_CC,
CONTA_CORRENTE,
CODIGO_BANCO_FGTS,
CONTA_FGTS,
DATA_OPCAO_FGTS,
DATA_RETROACAO,
DATA_RETRATACAO,
COD_SINDICATO,
NIVEL_SINDICATO,
DT_ULT_SINDICATO,
DESC_CONTRIB_SIND,
SINDICALIZADO,
INSCRICAO_INSS,
COD_MOVIMENTACAO,
DATA_TRANSF_ENTRAD,
DATA_PRI_ADMISSAO,
DATA_REINTEGRACAO,
DATA_EFETIVO_EXERC,
DATA_POSSE,
DATA_NOMEACAO,
DATA_INICIO_ESTAB,
DATA_FIM_ESTAB,
DT_FIM_CONTR_EXP,
DT_FIM_CONTR_DETER,
DATA_FIM_RENOV_EXP,
DATA_AV_PREVIO,
DATA_RESCISAO,
CAUSA_RESCISAO,
DATA_INIC_AFAST,
DATA_FIM_AFAST,
NRO_MESES_AFAST,
CTRL_VERBAS,
FORMA_PAGAMENTO,
DATA_BASE_FERIAS,
DATA_INIC_GOZO,
DATA_FIM_GOZO,
DEPENDENTES_SF,
DEPENDENTES_IRRF,
COD_PROCURADOR,
DATA_PAGTO_CALCULO,
DATA_PAGTO_ADIANT,
DATA_PAGTO_FERIAS,
DATA_PAGTO_13SAL,
DATA_PAGTO_RESCISA,
SAL_CONT_EFETIVO,
DT_ULT_SAL_C_EFET,
SAL_CONT_COMISSION,
DT_ULT_SAL_C_COM,
SAL_CONT_AMPAR,
DT_ULT_SAL_C_AMP,
SAL_AUX_EFETIVO,
DT_ULT_SAL_A_EFET,
SAL_AUX_COMISSION,
DT_ULT_SAL_A_COM,
SAL_AUX_AMPAR,
DT_ULT_SAL_A_AMP,
C_LIVRE_SELEC01,
C_LIVRE_SELEC02,
C_LIVRE_SELEC03,
C_LIVRE_SELEC04,
C_LIVRE_SELEC05,
C_LIVRE_SELEC06,
C_LIVRE_SELEC07,
C_LIVRE_SELEC08,
C_LIVRE_SELEC09,
C_LIVRE_SELEC10,
C_LIVRE_SELEC11,
C_LIVRE_SELEC12,
C_LIVRE_SELEC13,
C_LIVRE_SELEC14,
C_LIVRE_SELEC15,
C_LIVRE_SELEC36,
C_LIVRE_SELEC37,
C_LIVRE_SELEC38,
C_LIVRE_SELEC39,
C_LIVRE_SELEC40,
C_LIVRE_VALOR16,
C_LIVRE_VALOR17,
C_LIVRE_VALOR18,
C_LIVRE_VALOR19,
C_LIVRE_VALOR20,
C_LIVRE_VALOR21,
C_LIVRE_VALOR22,
C_LIVRE_VALOR23,
C_LIVRE_DESCR24,
C_LIVRE_DESCR25,
C_LIVRE_DESCR26,
C_LIVRE_DESCR27,
C_LIVRE_DATA28,
C_LIVRE_DATA29,
C_LIVRE_DATA30,
C_LIVRE_DATA31,
C_LIVRE_DATA32,
C_LIVRE_DATA33,
C_LIVRE_DATA34,
C_LIVRE_DATA35,
C_LIVRE_OPCAO41,
C_LIVRE_OPCAO42,
C_LIVRE_OPCAO43,
C_LIVRE_OPCAO44,
C_LIVRE_OPCAO45,
C_LIVRE_OPCAO46,
C_LIVRE_OPCAO47,
C_LIVRE_OPCAO48,
INDIC_ALTERAC1,
INDIC_ALTERAC2,
INDIC_ALTERAC3,
INDIC_ALTERAC4,
INDIC_ALTERAC5,
TEXTO_ASSOCIADO,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
TELEFONE,
TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY') ANO_MES_REFERENCIA,
DATA_APOSENTA_FGTS,
REABILITADO,
C_LIVRE_VALOR49,
C_LIVRE_VALOR50,
C_LIVRE_VALOR51,
C_LIVRE_VALOR52,
C_LIVRE_VALOR53,
C_LIVRE_VALOR54,
C_LIVRE_VALOR55,
C_LIVRE_VALOR56,
C_LIVRE_DATA57,
C_LIVRE_DATA58,
C_LIVRE_DATA59,
C_LIVRE_DATA60,
C_LIVRE_DATA61,
C_LIVRE_DATA62,
C_LIVRE_DATA63,
C_LIVRE_DATA64,
C_LIVRE_OPCAO65,
C_LIVRE_OPCAO66,
C_LIVRE_OPCAO67,
C_LIVRE_OPCAO68,
INDIC_ALTERAC6,
CLASSE_CONT_INSS,
E_MAIL,
USA_ASSOC_CONT_ESC,
CLASSIFICACAO_CAND,
NUMERO_EDITAL,
TIPO_AGRUP_UNID,
TIPO_AGRUP_CONT,
TIPO_AGRUP_CGER,
TIPO_AGRUP_LOTA,
NOME_ACESSO,
CODIGO_SOLICITACAO,
ID_CONTR_FORN,
FUNC_COMP_EMPR_AV,
DT_MOLESTIA_GRAVE,
SAL_CONT_FUNCAO,
DT_ULT_SAL_C_FUN,
SAL_AUX_FUNCAO,
DT_ULT_SAL_A_FUN,
DATA_PROJ_AV_PREV,
DT_PROJ_AFAST_ESOCIAL,
TP_AVISO_PREVIO_ESOCIAL,
TP_CONTA_BANCARIA,
DT_PROC_ESOCIAL,
DT_ALTER_ESOCIAL,
DT_CANC_AVISO_PREVIO,
MOT_CANC_AV_PREV_ESOCIAL,
DESC_SAL_VARIAVEL,
MOTIVO_CONTRATACAO,
CPF_TRAB_SUBSTITUIDO,
MATRIC_TRAB_SUBSTITUIDO,
IND_SEGURO_DESEMPREGO,
DT_GERACAO_CAGED,
OBS_RESCISAO,
DT_FIM_QUARENTENA,
CNPJ_EMPRESA_SUCESSORA,
JUST_CONTR_ESOCIAL,
TP_INCL_CONTR_ESOCIAL,
INFO_COTA_ESOCIAL,
CLAUSULA_ASSEC,
DT_ALTERACAO_CONTR,
DT_EFEITO_ALTER_CONTR,
DESC_ALTER_CONTR,
IND_CUMPR_PARC_AV,
CODIGO_CONTR_ANTERIOR,
CPF_ANTERIOR,
DATA_ALTER_CPF,
OBS_ALTER_CPF,
TEM_ALTER_CPF,
INFO_COTA_RACA,
MATRICULA_ESOCIAL,
CONSELHO_REGIONAL,
INSCRICAO_CONSELHO,
UF_CONSELHO,
COD_CARREIRA,
COD_EIXO,
COD_NIVEL,
IND_REMUN,
IND_PDV
FROM RHPESS_CONTRATO C
WHERE C.codigo_empresa   = ''||C2.CODIGO_EMPRESA||'' AND C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' AND C.CODIGO = ''||C2.CODIGO||'' AND 
C.ano_mes_referencia =  (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO AUX WHERE C.codigo_empresa = AUX.CODIGO_EMPRESA AND C.tipo_contrato = AUX.TIPO_CONTRATO AND C.CODIGO = AUX.CODIGO);
COMMIT;

INSERT INTO RHPESS_CONTRATO_AUX X
SELECT 
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO,
TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY') ANO_MES_REFERENCIA,
LOGIN_USUARIO,
DT_ULT_ALTER_USUA,
C_LIVRE_AUX_SELEC01,
C_LIVRE_AUX_SELEC02,
C_LIVRE_AUX_SELEC03,
C_LIVRE_AUX_SELEC04,
C_LIVRE_AUX_SELEC05,
C_LIVRE_AUX_SELEC06,
C_LIVRE_AUX_SELEC07,
C_LIVRE_AUX_SELEC08,
C_LIVRE_AUX_SELEC09,
C_LIVRE_AUX_SELEC10,
C_LIVRE_AUX_SELEC11,
C_LIVRE_AUX_SELEC12,
C_LIVRE_AUX_SELEC13,
C_LIVRE_AUX_SELEC14,
C_LIVRE_AUX_SELEC15,
C_LIVRE_AUX_SELEC16,
C_LIVRE_AUX_SELEC17,
C_LIVRE_AUX_SELEC18,
C_LIVRE_AUX_SELEC19,
C_LIVRE_AUX_SELEC20,
C_LIVRE_AUX_VALOR01,
C_LIVRE_AUX_VALOR02,
C_LIVRE_AUX_VALOR03,
C_LIVRE_AUX_VALOR04,
C_LIVRE_AUX_VALOR05,
C_LIVRE_AUX_VALOR06,
C_LIVRE_AUX_VALOR07,
C_LIVRE_AUX_VALOR08,
C_LIVRE_AUX_VALOR09,
C_LIVRE_AUX_VALOR10,
C_LIVRE_AUX_VALOR11,
C_LIVRE_AUX_VALOR12,
C_LIVRE_AUX_VALOR13,
C_LIVRE_AUX_VALOR14,
C_LIVRE_AUX_VALOR15,
C_LIVRE_AUX_VALOR16,
C_LIVRE_AUX_VALOR17,
C_LIVRE_AUX_VALOR18,
C_LIVRE_AUX_VALOR19,
C_LIVRE_AUX_VALOR20,
C_LIVRE_AUX_DATA01,
C_LIVRE_AUX_DATA02,
C_LIVRE_AUX_DATA03,
C_LIVRE_AUX_DATA04,
C_LIVRE_AUX_DATA05,
C_LIVRE_AUX_DATA06,
C_LIVRE_AUX_DATA07,
C_LIVRE_AUX_DATA08,
C_LIVRE_AUX_DATA09,
C_LIVRE_AUX_DATA10,
C_LIVRE_AUX_DATA11,
C_LIVRE_AUX_DATA12,
C_LIVRE_AUX_DATA13,
C_LIVRE_AUX_DATA14,
C_LIVRE_AUX_DATA15,
C_LIVRE_AUX_DATA16,
C_LIVRE_AUX_DATA17,
C_LIVRE_AUX_DATA18,
C_LIVRE_AUX_DATA19,
C_LIVRE_AUX_DATA20,
C_LIVRE_AUX_OPCAO01,
C_LIVRE_AUX_OPCAO02,
C_LIVRE_AUX_OPCAO03,
C_LIVRE_AUX_OPCAO04,
C_LIVRE_AUX_OPCAO05,
C_LIVRE_AUX_OPCAO06,
C_LIVRE_AUX_OPCAO07,
C_LIVRE_AUX_OPCAO08,
C_LIVRE_AUX_OPCAO09,
C_LIVRE_AUX_OPCAO10,
C_LIVRE_AUX_OPCAO11,
C_LIVRE_AUX_OPCAO12,
C_LIVRE_AUX_OPCAO13,
C_LIVRE_AUX_OPCAO14,
C_LIVRE_AUX_OPCAO15,
C_LIVRE_AUX_OPCAO16,
C_LIVRE_AUX_OPCAO17,
C_LIVRE_AUX_OPCAO18,
C_LIVRE_AUX_OPCAO19,
C_LIVRE_AUX_OPCAO20,
C_LIVRE_AUX_DESCR01,
C_LIVRE_AUX_DESCR02,
C_LIVRE_AUX_DESCR03,
C_LIVRE_AUX_DESCR04,
C_LIVRE_AUX_DESCR05,
C_LIVRE_AUX_DESCR06,
C_LIVRE_AUX_DESCR07,
C_LIVRE_AUX_DESCR08,
C_LIVRE_AUX_DESCR09,
C_LIVRE_AUX_DESCR10,
C_LIVRE_AUX_DESCR11,
C_LIVRE_AUX_DESCR12,
C_LIVRE_AUX_DESCR13,
C_LIVRE_AUX_DESCR14,
C_LIVRE_AUX_DESCR15,
C_LIVRE_AUX_DESCR16,
C_LIVRE_AUX_DESCR17,
C_LIVRE_AUX_DESCR18,
C_LIVRE_AUX_DESCR19,
C_LIVRE_AUX_DESCR20,
C_LIVRE_AUX_TEXTO01,
C_LIVRE_AUX_TEXTO02,
C_LIVRE_AUX_TEXTO03,
C_LIVRE_AUX_TEXTO04,
C_LIVRE_AUX_TEXTO05,
C_LIVRE_AUX_TEXTO06,
C_LIVRE_AUX_TEXTO07,
C_LIVRE_AUX_TEXTO08,
C_LIVRE_AUX_TEXTO09,
C_LIVRE_AUX_TEXTO10,
C_LIVRE_AUX_TEXTO11,
C_LIVRE_AUX_TEXTO12,
C_LIVRE_AUX_TEXTO13,
C_LIVRE_AUX_TEXTO14,
C_LIVRE_AUX_TEXTO15,
C_LIVRE_AUX_TEXTO16,
C_LIVRE_AUX_TEXTO17,
C_LIVRE_AUX_TEXTO18,
C_LIVRE_AUX_TEXTO19,
C_LIVRE_AUX_TEXTO20
FROM RHPESS_CONTRATO_AUX X
where X.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and X.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And X.CODIGO = ''||C2.CODIGO||'' AND X.ano_mes_referencia = (SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM RHPESS_CONTRATO_aux AUX
where X.codigo_empresa = AUX.CODIGO_EMPRESA and X.tipo_contrato = AUX.TIPO_CONTRATO And X.CODIGO = AUX.CODIGO );
COMMIT;

IF (
      (
      C2.DATA_EFETIVO_EXERC IS NOT NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (
      to_date(to_char(vDATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_EFETIVO_EXERC,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN

UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_EFETIVO_EXERC = TRUNC(C2.DATA_EFETIVO_EXERC) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA DA NOMEAÇÃO
IF (
      (
      C2.DATA_NOMEACAO IS NOT NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (
      to_date(to_char(vDATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_NOMEACAO,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN

UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_NOMEACAO = TRUNC(C2.DATA_NOMEACAO) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA DA POSSE
IF (  (
        (
        C2.DATA_POSSE IS NOT NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY')
        )  
        OR 
        (
        to_date(to_char(vDATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
        ) -- E A DATA DE POSSE DEVE SER MAIOR OU IGUAL A DATA DE ADMISSÃO.
      ) AND  to_date(to_char(C2.DATA_POSSE,'DD/MM/YYYY'),'DD/MM/YYYY') >= to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') 
   ) THEN

UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, DATA_POSSE = TRUNC(C2.DATA_POSSE) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA C_LIVRE_DATA28 (Estatutario optante)
IF (
      (
        (
          C2.C_LIVRE_DATA28 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') 
        )  
        OR 
        (
        to_date(to_char(vC_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA28,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
        )
      ) 
      AND to_date(to_char(vDATA_ADMISSAO,'DD/MM/YYYY'),'DD/MM/YYYY') < to_date(to_char(vDATA_OPTANTE,'DD/MM/YYYY'),'DD/MM/YYYY')
   )THEN


UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, C_LIVRE_DATA28 = TRUNC(C2.C_LIVRE_DATA28) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

--ATUALIZA A DATA C_LIVRE_DATA32 (Homolog. Concurso)
IF (
      (
      C2.C_LIVRE_DATA32 IS NOT NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') <> to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY')
      )  
      OR 
      (
      to_date(to_char(vC_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NULL AND to_date(to_char(C2.C_LIVRE_DATA32,'DD/MM/YYYY'),'DD/MM/YYYY') IS NOT NULL
      )
   ) THEN

UPDATE rhpess_contrato C SET C.login_usuario =''||c2.LOGIN_USUARIO||'', C.dt_ult_alter_usua = sysdate, C_LIVRE_DATA32  = TRUNC(C2.C_LIVRE_DATA32) where C.codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and C.tipo_contrato = ''||C2.TIPO_CONTRATO||'' And C.CODIGO = ''||C2.CODIGO||'' AND C.ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;
update rhpess_contrato_aux set LOGIN_USUARIO = ''||c2.LOGIN_USUARIO||'', dt_ult_alter_usua = sysdate where codigo_empresa = ''||C2.CODIGO_EMPRESA||'' and tipo_contrato = ''||C2.TIPO_CONTRATO||'' And CODIGO = ''||C2.CODIGO||'' AND ano_mes_referencia >= TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY');
COMMIT;

ATUALIZA_CONTRATO_MESTRE (C2.CODIGO, C2.TIPO_CONTRATO, C2.CODIGO_EMPRESA, TO_DATE('01'||SUBSTR(to_char(vDATA_SISTEMA,'DD/MM/YYYY'),3,8),'DD/MM/YYYY'), c2.LOGIN_USUARIO);

END IF;

update SUGESP_SANEAMENTO_DT_CONTRATO set DATA_PROCESSAMENTO = sysdate, STATUS_PROCESSAMENTO = 'OK' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL and trunc(data_carga) = TRUNC(c2.DATA_CARGA) and codigo_empresa = ''||c2.codigo_empresa||'' and tipo_contrato = ''||c2.tipo_contrato||'' and codigo = ''||c2.codigo||'';
COMMIT;

END IF;


--dbms_output.put_line('update SUGESP_SANEAMENTO_DT_CONTRATO set DATA_PROCESSAMENTO = sysdate, STATUS_PROCESSAMENTO = ''OK'' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL and trunc(data_carga) = TO_DATE('||to_char(c2.DATA_CARGA,'''DD/MM/YYYY''')||',''DD/MM/YYYY'') and codigo_empresa = '''||c2.codigo_empresa||''' and tipo_contrato = '''||c2.tipo_contrato||''' and codigo = '''||c2.codigo||''' ;');

END LOOP;
BEGIN
update SUGESP_SANEAMENTO_DT_CONTRATO set DATA_PROCESSAMENTO = sysdate, STATUS_PROCESSAMENTO = 'N' WHERE DATA_PROCESSAMENTO IS NULL AND STATUS_PROCESSAMENTO IS NULL;
COMMIT WORK;
END;
END; 
END SANEAMENTO_CONTRATO;