
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_CAD_FERIAS_EXCLUI" (
    DATA_INICIO IN VARCHAR2,
    DATA_FIM    IN VARCHAR2)
AS
BEGIN
  DECLARE
    vCONTADOR    NUMBER;
    vDATA_INICIO VARCHAR2(10);
    vDATA_FIM    VARCHAR2(10);
  BEGIN
    dbms_output.enable(NULL);
    vCONTADOR    :=0;
    vDATA_INICIO := DATA_INICIO;
    vDATA_FIM    := DATA_FIM;
    FOR C1 IN
    (

SELECT  * FROM (  SELECT CASE WHEN TIPO='ATUALIZAR' THEN CODIGO_LEGADO_ANTERIOR ELSE  LTRIM(FIM.CODIGO_CONTRATO,0)||FIM.TIPO_CONTRATO||FIM.CODIGO_EMPRESA||FIM.CODIGO_JUSTIFICATIVA||FIM.DATA_INICIO||FIM.DATA_FIM END  AS CODIGO_LEGADO ,SYSDATE AS DT_SAIU_ARTE,FIM.* FROM (SELECT 'FERIAS' AS ORIGEM,X.* FROM (
SELECT FIM.EMPRESA,FIM.AGRUPAMENTO_EMPRESA,FIM.CODIGO_EMPRESA,FIM.TIPO_CONTRATO,FIM.CODIGO_CONTRATO,FIM.SITUACAO_PONTO AS CODIGO_JUSTIFICATIVA  ,FIM.DESCRICAO_JUSTIFICATIVA,FIM.TIPO_FERIAS, CASE
        WHEN  TO_DATE(FIM.DATA_INICIO,'DD/MM/YYYY')<= TO_DATE(add_months(FIM.FECHAMENTO_SISTEMA,-2),'DD/MM/YYYY')  and FIM.FECHAMENTO_SISTEMA IS NOT NULL
        THEN TO_CHAR(TO_DATE(FIM.FECHAMENTO_SISTEMA,'DD/MM/YYYY')+1,'DD/MM/YYYY')
        WHEN TO_DATE(FIM.DATA_INICIO,'DD/MM/YYYY')>TO_DATE(FIM.FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND FIM.FECHAMENTO_SISTEMA IS NOT  NULL
        THEN DATA_INICIO
        ELSE FIM.DATA_INICIO
      END AS DATA_INICIO,
        CASE
          WHEN TIPO                          ='ATUALIZAR_DATA_EXCLUSAO'
          AND TO_DATE(DATA_FIM,'DD/MM/YYYY')<=TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND FIM.FECHAMENTO_SISTEMA IS NOT  NULL
          THEN TO_CHAR(TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY'),'DD/MM/YYYY')
          WHEN TIPO                          ='ATUALIZAR_DATA_EXCLUSAO'
          AND TO_DATE(DATA_FIM,'DD/MM/YYYY')>=TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND FIM.FECHAMENTO_SISTEMA IS NOT  NULL
          THEN TO_CHAR(TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY'),'DD/MM/YYYY')
          WHEN TIPO                          ='ATUALIZAR_DATA'
          AND TO_DATE(DATA_FIM,'DD/MM/YYYY')<=TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND FIM.FECHAMENTO_SISTEMA IS NOT  NULL
          THEN TO_CHAR(TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY'),'DD/MM/YYYY')
          WHEN TIPO                          ='ATUALIZAR_DATA'
          AND TO_DATE(DATA_FIM,'DD/MM/YYYY')>TO_DATE(FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND FIM.FECHAMENTO_SISTEMA IS NOT  NULL
          THEN TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'),'DD/MM/YYYY')

          ELSE TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'),'DD/MM/YYYY')
        END AS DATA_FIM ,
        CASE WHEN TIPO                           IN ('ATUALIZAR_DATA_EXCLUSAO','ATUALIZAR_DATA') THEN 'ATUALIZAR' ELSE 'EXCLUIR' END AS TIPO,
        LTRIM(FIM.CODIGO_CONTRATO,0)||FIM.TIPO_CONTRATO||FIM.CODIGO_EMPRESA||FIM.SITUACAO_PONTO||FIM.DATA_INICIO||FIM.DATA_FIM AS CODIGO_LEGADO_ANTERIOR
,FIM.PK_ARTE
FROM
        (SELECT CASE WHEN TIPO_COMANDO='U' AND X.new_status_confirmacao='G'  THEN 'ATUALIZAR_DATA_EXCLUSAO'
       WHEN TIPO_COMANDO='D' THEN 'ATUALIZAR_DATA_EXCLUSAO' 
       ELSE 'ATUALIZAR_DATA 'END
        AS TIPO ,X.CODIGO_EMPRESA,X.EMPRESA,X.AGRUPAMENTO_EMPRESA,X.TIPO_CONTRATO,X.CODIGO_CONTRATO,X.DT_INI_AQUISICAO,X.SITUACAO_PONTO,X.DESCRICAO_JUSTIFICATIVA,
X.TIPO_FERIAS,X.PERIODO,
X.DATA_INICIO_OLD AS DATA_INICIO,
CASE WHEN X.DATA_FIM_OLD>x.DATA_FIM_new  THEN x.DATA_FIM_new
WHEN x.DATA_FIM_OLD <x.DATA_FIM_new THEN x.DATA_FIM_new
WHEN x.DATA_FIM_OLD =x.DATA_FIM_new THEN x.DATA_FIM_new
WHEN x.DATA_FIM_new IS NULL THEN x.DATA_FIM_OLD
END AS DATA_FIM,
X.FECHAMENTO_SISTEMA
,X.PK_ARTE
FROM (SELECT
    TG.CODIGO_EMPRESA,
    CASE WHEN TG.CODIGO_EMPRESA = '0001'THEN 'PREF.MUN.BELO HORIZONTE'
         WHEN TG.CODIGO_EMPRESA = '0098'THEN 'PREF.MUN.BH CONTRATOS'
         WHEN TG.CODIGO_EMPRESA = '0013'THEN 'FUNDACAO DE CULTURA'
         WHEN TG.CODIGO_EMPRESA = '0014'THEN 'FUNDACAO DE PARQUES'
         WHEN TG.CODIGO_EMPRESA = '0003'THEN 'SUDECAP'
         END AS EMPRESA,
         CASE WHEN TG.CODIGO_EMPRESA = '0001'THEN 'PREF.MUN.BELO HORIZONTE'
         WHEN TG.CODIGO_EMPRESA = '0098'THEN 'PREF.MUN.BH CONTRATOS'
         WHEN TG.CODIGO_EMPRESA = '0013'THEN 'FUNDACAO DE CULTURA'
         WHEN TG.CODIGO_EMPRESA = '0014'THEN 'FUNDACAO DE PARQUES'
         WHEN TG.CODIGO_EMPRESA = '0003'THEN 'SUDECAP'
         END AS AGRUPAMENTO_EMPRESA,
      TG.TIPO_CONTRATO,
      TG.CODIGO_CONTRATO,
      TG.TIPO_COMANDO,
      TG.OLD_DT_INI_AQUISICAO AS DT_INI_AQUISICAO,
      PF.SITUACAO_PONTO,
      PF.DESCRICAO AS DESCRICAO_JUSTIFICATIVA,
      TG.OLD_TIPO_FERIAS      AS TIPO_FERIAS,
      TG.OLD_PERIODO AS PERIODO,
      TO_CHAR(TG.OLD_DT_INI_GOZO,'DD/MM/YYYY')    AS DATA_INICIO_OLD ,
      TO_CHAR(TG.OLD_DT_FIM_GOZO ,'DD/MM/YYYY')     AS DATA_FIM_OLD,
       TO_CHAR(TG.new_DT_INI_GOZO,'DD/MM/YYYY')    AS DATA_INICIO_new ,
      TO_CHAR(TG.new_DT_FIM_GOZO ,'DD/MM/YYYY')     AS DATA_FIM_new,
       TG.DT_ULT_ALTER_USUA    AS DT_ULT_ALTER_USUA,
        tg.old_status_confirmacao,
      tg.new_status_confirmacao,
          (SELECT    dado_origem FROM     ARTERH.rhinte_ed_it_conv cv WHERE codigo_conversao = 'FCPT' AND TO_DATE(dado_origem,'DD/MM/YYYY') = (SELECT MAX(TO_DATE(AUX.dado_origem,'DD/MM/YYYY')) FROM arterh.rhinte_ed_it_conv aux WHERE cv.codigo_conversao = aux.codigo_conversao))          FECHAMENTO_SISTEMA
,TG.CODIGO_EMPRESA||TG.TIPO_CONTRATO||TG.CODIGO_CONTRATO 
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_DT_INI_AQUISICAO ELSE TG.NEW_DT_INI_AQUISICAO END-- DT_INI_AQUISICAO,
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_TIPO_FERIAS ELSE TG.NEW_TIPO_FERIAS END --TIPO_FERIAS,
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_PERIODO ELSE TG.NEW_PERIODO END --PERIODO
PK_ARTE
FROM PONTO_ELETRONICO.SUGESP_BI_RHFERI_FERIAS TG
LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B
ON TG.CODIGO_EMPRESA  =B.CODIGO_EMPRESA
AND TG.TIPO_CONTRATO  =B.TIPO_CONTRATO
AND TG.CODIGO_CONTRATO= B.CODIGO
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S
ON B.SITUACAO_FUNCIONAL =S.CODIGO
LEFT OUTER JOIN ARTERH.RHPARM_P_FERI PF
ON PF.CODIGO_EMPRESA=TG.CODIGO_EMPRESA
AND PF.CODIGO       =TG.OLD_TIPO_FERIAS
LEFT OUTER JOIN
  (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO='PONT'
  )PONTR
ON SUBSTR(PONTR.DADO_ORIGEM,20,4) =TG.CODIGO_EMPRESA
AND SUBSTR(PONTR.DADO_ORIGEM,24,4)=TG.TIPO_CONTRATO
WHERE SUBSTR(PONTR.DADO_ORIGEM,20,4) IS NOT NULL
AND TG.OLD_DT_INI_GOZO               IS NOT NULL
AND TG.OLD_DT_FIM_GOZO               IS NOT NULL
---AND TG.OLD_DT_INI_GOZO <='31/03/2021'
AND  TG.OLD_DT_INI_GOZO >= TO_DATE('01/08/2021', 'DD/MM/YYYY')
AND TG.OLD_STATUS_CONFIRMACAO        IN('1','5','D','Q')
AND B.ANO_MES_REFERENCIA              =
  (SELECT MAX(ANO_MES_REFERENCIA)
  FROM ARTERH.RHPESS_CONTRATO AUX
  WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA
  AND AUX.TIPO_CONTRATO    = B.TIPO_CONTRATO
  AND AUX.CODIGO           = B.CODIGO
  )
AND S.CONTROLE_FOLHA NOT IN ('D','S')
AND B.DATA_RESCISAO      IS NULL
AND TG.TIPO_COMANDO      IN('U','D')
AND TG.DT_ULT_ALTER_USUA                 =
  (SELECT MAX(AUX.DT_ULT_ALTER_USUA)
  FROM PONTO_ELETRONICO.SUGESP_BI_RHFERI_FERIAS AUX
  WHERE AUX.CODIGO_EMPRESA     =TG.CODIGO_EMPRESA
  AND AUX.CODIGO_CONTRATO      =TG.CODIGO_CONTRATO
  AND AUX.TIPO_CONTRATO        = TG.TIPO_CONTRATO
  AND AUX.OLD_TIPO_FERIAS      = TG.OLD_TIPO_FERIAS
  and aux.old_periodo= TG.old_PERIODO 
  AND AUX.OLD_DT_INI_AQUISICAO =TG.OLD_DT_INI_AQUISICAO
  AND AUX.OLD_DT_FIM_AQUISICAO =TG.OLD_DT_FIM_AQUISICAO 
   AND aux.OLD_STATUS_CONFIRMACAO        IN('1','5','D','Q')
 AND AUX.OLD_DT_INI_GOZO=TG.OLD_DT_INI_GOZO
  AND AUX.OLD_DT_FIM_GOZO=TG.OLD_DT_FIM_GOZO
  )
AND (TRUNC(TG.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM)

  )X
  WHERE (
  (x.DATA_INICIO_OLD <=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  and
  TO_DATE(X.DATA_FIM_new ,'DD/MM/YYYY')<=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  )OR
  (x.DATA_INICIO_OLD <=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  AND
  TO_DATE(X.DATA_FIM_new ,'DD/MM/YYYY')>=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  )OR
  (x.DATA_INICIO_OLD <=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  AND
  TO_DATE(X.DATA_FIM_OLD ,'DD/MM/YYYY')>=CASE WHEN TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') IS NULL THEN TO_DATE('01/01/2020','DD/MM/YYYY') ELSE TO_DATE(x.FECHAMENTO_SISTEMA,'DD/MM/YYYY') END
  AND
  X.DATA_FIM_new IS NULL
  )


  )
  )FIM
  )X

  UNION ALL

  SELECT 'FERIAS' AS ORIGEM, X.EMPRESA,X.AGRUPAMENTO_EMPRESA,X.CODIGO_EMPRESA,X.TIPO_CONTRATO,X.CODIGO_CONTRATO,X.SITUACAO_PONTO AS CODIGO_JUSTIFICATIVA,X.DESCRICAO_JUSTIFICATIVA,X.TIPO_FERIAS,
  CASE
        WHEN  TO_DATE(X.DATA_INICIO,'DD/MM/YYYY')<= TO_DATE(add_months(X.FECHAMENTO_SISTEMA,-2),'DD/MM/YYYY')  and X.FECHAMENTO_SISTEMA IS NOT NULL
        THEN TO_CHAR(TO_DATE(X.FECHAMENTO_SISTEMA,'DD/MM/YYYY')+1,'DD/MM/YYYY')
        WHEN TO_DATE(X.DATA_INICIO,'DD/MM/YYYY')>=TO_DATE(X.FECHAMENTO_SISTEMA,'DD/MM/YYYY') AND X.FECHAMENTO_SISTEMA IS NOT  NULL
        THEN DATA_INICIO
        ELSE X.DATA_INICIO
      END AS DATA_INICIO,
      X.DATA_FIM,X.TIPO,
              LTRIM(X.CODIGO_CONTRATO,0)||X.TIPO_CONTRATO||X.CODIGO_EMPRESA||X.SITUACAO_PONTO||X.DATA_INICIO||X.DATA_FIM AS CODIGO_LEGADO_ANTERIOR
,X.PK_ARTE
  FROM (
  SELECT

    TG.CODIGO_EMPRESA,
    CASE WHEN TG.CODIGO_EMPRESA = '0001'THEN 'PREF.MUN.BELO HORIZONTE'
         WHEN TG.CODIGO_EMPRESA = '0098'THEN 'PREF.MUN.BH CONTRATOS'
         WHEN TG.CODIGO_EMPRESA = '0013'THEN 'FUNDACAO DE CULTURA'
         WHEN TG.CODIGO_EMPRESA = '0014'THEN 'FUNDACAO DE PARQUES'
         WHEN TG.CODIGO_EMPRESA = '0003'THEN 'SUDECAP'
         END AS EMPRESA,
         CASE WHEN TG.CODIGO_EMPRESA = '0001'THEN 'PREF.MUN.BELO HORIZONTE'
         WHEN TG.CODIGO_EMPRESA = '0098'THEN 'PREF.MUN.BH CONTRATOS'
         WHEN TG.CODIGO_EMPRESA = '0013'THEN 'FUNDACAO DE CULTURA'
         WHEN TG.CODIGO_EMPRESA = '0014'THEN 'FUNDACAO DE PARQUES'
         WHEN TG.CODIGO_EMPRESA = '0003'THEN 'SUDECAP'
         END AS AGRUPAMENTO_EMPRESA,
      TG.TIPO_CONTRATO,
      TG.CODIGO_CONTRATO,
      PF.SITUACAO_PONTO,
      PF.DESCRICAO AS DESCRICAO_JUSTIFICATIVA,
      TG.OLD_TIPO_FERIAS      AS TIPO_FERIAS,
      TG.OLD_PERIODO AS PERIODO,
      TO_CHAR(TG.OLD_DT_INI_GOZO,'DD/MM/YYYY')    AS DATA_INICIO ,
      TO_CHAR(TG.OLD_DT_FIM_GOZO ,'DD/MM/YYYY')     AS DATA_FIM,

      'EXCLUIR'               AS TIPO ,
          (SELECT    dado_origem FROM     ARTERH.rhinte_ed_it_conv cv WHERE codigo_conversao = 'FCPT' AND TO_DATE(dado_origem,'DD/MM/YYYY') = (SELECT MAX(TO_DATE(AUX.dado_origem,'DD/MM/YYYY')) FROM arterh.rhinte_ed_it_conv aux WHERE cv.codigo_conversao = aux.codigo_conversao))          FECHAMENTO_SISTEMA
,TG.CODIGO_EMPRESA||TG.TIPO_CONTRATO||TG.CODIGO_CONTRATO 
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_DT_INI_AQUISICAO ELSE TG.NEW_DT_INI_AQUISICAO END-- DT_INI_AQUISICAO,
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_TIPO_FERIAS ELSE TG.NEW_TIPO_FERIAS END --TIPO_FERIAS,
||CASE WHEN TG.TIPO_COMANDO = 'D' THEN TG.OLD_PERIODO ELSE TG.NEW_PERIODO END --PERIODO
PK_ARTE
      FROM PONTO_ELETRONICO.SUGESP_BI_RHFERI_FERIAS TG
      LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO B
      ON TG.CODIGO_EMPRESA =B.CODIGO_EMPRESA
      AND TG.TIPO_CONTRATO =B.TIPO_CONTRATO
      AND TG.CODIGO_CONTRATO= B.CODIGO
      LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S
      ON B.SITUACAO_FUNCIONAL =S.CODIGO
      LEFT OUTER JOIN ARTERH.RHPARM_P_FERI PF
      ON PF.CODIGO_EMPRESA=TG.CODIGO_EMPRESA
      AND PF.CODIGO=TG.OLD_TIPO_FERIAS
      LEFT OUTER JOIN
          (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO='PONT')PONTR
          ON   SUBSTR(PONTR.DADO_ORIGEM,20,4)=TG.CODIGO_EMPRESA
          AND SUBSTR(PONTR.DADO_ORIGEM,24,4)=TG.TIPO_CONTRATO

      WHERE SUBSTR(PONTR.DADO_ORIGEM,20,4) IS NOT NULL
      AND TG.OLD_DT_INI_GOZO        IS NOT NULL
      AND TG.OLD_DT_FIM_GOZO        IS NOT NULL
      AND TG.OLD_STATUS_CONFIRMACAO IN('1','5','D','Q')
      AND B.ANO_MES_REFERENCIA =(SELECT MAX(ANO_MES_REFERENCIA)FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = B.CODIGO_EMPRESA
      AND AUX.TIPO_CONTRATO = B.TIPO_CONTRATO
      AND AUX.CODIGO = B.CODIGO)
      AND S.CONTROLE_FOLHA NOT IN ('D','S')
      AND B.DATA_RESCISAO      IS NULL
      AND TG.OLD_DT_INI_GOZO   >= TO_DATE('01/08/2021', 'DD/MM/YYYY')
      AND TG.TIPO_COMANDO      IN('D','U')
      AND TG.DT_ULT_ALTER_USUA =(SELECT MAX(AUX.DT_ULT_ALTER_USUA)
              FROM PONTO_ELETRONICO.SUGESP_BI_RHFERI_FERIAS AUX
              WHERE AUX.CODIGO_EMPRESA=TG.CODIGO_EMPRESA
              AND AUX.CODIGO_CONTRATO =TG.CODIGO_CONTRATO
              AND AUX.TIPO_CONTRATO   = TG.TIPO_CONTRATO
              AND AUX.OLD_TIPO_FERIAS = TG.OLD_TIPO_FERIAS
              and aux.old_periodo= TG.old_PERIODO 
              AND AUX.OLD_DT_INI_AQUISICAO  =TG.OLD_DT_INI_AQUISICAO
              AND AUX.OLD_DT_FIM_AQUISICAO =TG.OLD_DT_FIM_AQUISICAO
               AND aux.OLD_STATUS_CONFIRMACAO        IN('1','5','D','Q')
              AND AUX.OLD_DT_INI_GOZO=TG.OLD_DT_INI_GOZO
              AND AUX.OLD_DT_FIM_GOZO=TG.OLD_DT_FIM_GOZO
             )
              AND (TRUNC(TG.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM)
  )x

  where to_date(data_inicio)>=to_date(x.fechamento_sistema)
)FIM
  )X
 ---WHERE CODIGO_CONTRATO='000000000706500'
    )--fim do FOR
    LOOP
      vCONTADOR :=vCONTADOR+1;
      dbms_output.put_line(vCONTADOR);
      dbms_output.put_line(vDATA_INICIO||'-'||vDATA_FIM);
        INSERT
      INTO PONTO_ELETRONICO.SMARH_INT_PE_AFASTAMENTOS_V1
        (
          EMPRESA,
          AGRUPAMENTO_EMPRESA,
          CODIGO_LEGADO,
          TIPO,
          CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO,
          CODIGO_JUSTIFICATIVA,
          DESCRICAO,
          DATA_INICIO,
          DATA_FIM,
          DT_SAIU_ARTE,
          ORIGEM
,CODIGO_INTEGRA_ARTE 
,PK_ARTE
        )
        VALUES
        (
          C1.EMPRESA,
          C1.AGRUPAMENTO_EMPRESA,
          C1.CODIGO_LEGADO,
          C1.TIPO,
          C1.CODIGO_EMPRESA,
          C1.TIPO_CONTRATO,
          C1.CODIGO_CONTRATO,
          C1.CODIGO_JUSTIFICATIVA,
          C1.DESCRICAO_JUSTIFICATIVA,
          C1.DATA_INICIO,
          C1.DATA_FIM,
          C1.DT_SAIU_ARTE,
          C1.ORIGEM
          ,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL 
          ,C1.PK_ARTE --NOVO EM 30/8/22
        );
      COMMIT;
    END LOOP;
  END;
END SMARH_INT_PE_CAD_FERIAS_EXCLUI;