
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_CONTRATOS_ARTE" 
as
BEGIN
  --KELLYSSON 28/12/18
  --BUSCA OS CONTRATOS PARA COMPARAR AS ALTERAÇÕES
  DECLARE
    vCONTADOR NUMBER;
    vDATA_MAX DATE;
  BEGIN -- 1º BEGIN
 ----------------------------------------------------GERENCIAL--------------------------------------------------------------------------------------
-- /* 
 UPDATE arterh.rhorga_custo_geren
    SET contrato_resp       = NULL ,
      cod_empresa_pess      = NULL,
      cod_pessoa_resp       = NULL,
      tipo_cont_resp        = NULL
    WHERE CODIGO_EMPRESA =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
      AND ((cod_empresa_pess IS NOT NULL
    AND(cod_pessoa_resp    IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (cod_pessoa_resp    IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (tipo_cont_resp     IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR contrato_resp       IS NULL ))
    OR (contrato_resp      IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR tipo_cont_resp      IS NULL )));
    COMMIT;
---------------------------------------------------------------------------------AGRUPADOR--------------------------------------------------------------------------------------------------
    UPDATE arterh.rhorga_AGRUPADOR
    SET contrato_resp       = NULL ,
      cod_empresa_pess      = NULL,
      cod_pessoa_resp       = NULL,
      tipo_cont_resp        = NULL
    WHERE tipo_agrup        = 'G'
     and CODIGO_EMPRESA =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
    AND ((cod_empresa_pess IS NOT NULL
    AND(cod_pessoa_resp    IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (cod_pessoa_resp    IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (tipo_cont_resp     IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR contrato_resp       IS NULL ))
    OR (contrato_resp      IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR tipo_cont_resp      IS NULL )));
    COMMIT;
 --------------------------------------------------------------------------------------------AGRUPADOR H-----------------------------------------------------------------------------
     UPDATE ARTERH.rhorga_AGRUPADOR_H
    SET contrato_resp  = NULL ,
      cod_empresa_pess = NULL,
      cod_pessoa_resp  = NULL,
      tipo_cont_resp   = NULL
    WHERE tipo_agrup   = 'G'
    AND CODIGO_EMPRESA =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
     AND ((cod_empresa_pess IS NOT NULL
    AND(cod_pessoa_resp    IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (cod_pessoa_resp    IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR tipo_cont_resp      IS NULL
    OR contrato_resp       IS NULL ))
    OR (tipo_cont_resp     IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR contrato_resp       IS NULL ))
    OR (contrato_resp      IS NOT NULL
    AND(cod_empresa_pess   IS NULL
    OR cod_pessoa_resp     IS NULL
    OR tipo_cont_resp      IS NULL )))
    AND rhorga_AGRUPADOR_H.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM rhorga_AGRUPADOR_H AUX
    WHERE AUX.CODIGO_EMPRESA =rhorga_AGRUPADOR_H.CODIGO_EMPRESA
    AND AUX.TIPO_AGRUP=rhorga_AGRUPADOR_H.TIPO_AGRUP);
    COMMIT;
---------------------------------------------------------------------------------------CUSTO GEREN INFORMAL-----------------------------------------------------------------
    UPDATE arterh.rhorga_custo_geren
    SET cod_empr_pess_INF    = NULL ,
      cod_pess_INFORMAL      = NULL,
      tipo_cont_resp_INF     = NULL,
      contrato_resp_INF      = NULL
     WHERE CODIGO_EMPRESA =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
    AND ((cod_empr_pess_INF IS NOT NULL
    AND(cod_pess_INFORMAL   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (cod_pess_INFORMAL   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (tipo_cont_resp_INF  IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (contrato_resp_INF   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR tipo_cont_resp_INF   IS NULL )));
    COMMIT;
 ---------------------------------------------------------------------------AGURPADOR INFOTMAL-------------------------------------------------------------------------------------
    UPDATE arterh.rhorga_AGRUPADOR
    SET cod_empr_pess_INF    = NULL ,
      cod_pess_INFORMAL      = NULL,
      tipo_cont_resp_INF     = NULL,
      contrato_resp_INF      = NULL
    WHERE tipo_agrup         = 'G'
     AND CODIGO_EMPRESA =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
    AND ((cod_empr_pess_INF IS NOT NULL
    AND(cod_pess_INFORMAL   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (cod_pess_INFORMAL   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (tipo_cont_resp_INF  IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (contrato_resp_INF   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR tipo_cont_resp_INF   IS NULL )));
    COMMIT;
 ------------------------------------------------------------------------------------AGRUPADOR H INFORMAL ---------------------------------------------------------------------
    ---- ACRESENTADO AQUI EM 29/07/2019 PARA ATENDER A AGRUPADORA H TAMBEM

    -------- CODIGOS 000000 EM UM DOS CAMPOS DO RESPONSAVEL_INFORMAL DA AGRUPADOR_H
    UPDATE ARTERH.rhorga_AGRUPADOR_H
    SET cod_empr_pess_INF = NULL ,
      cod_pess_INFORMAL   = NULL,
      tipo_cont_resp_INF  = NULL,
      contrato_resp_INF   = NULL
    WHERE tipo_agrup      = 'G'
    AND CODIGO_EMPRESA    =(SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
    AND ((cod_empr_pess_INF IS NOT NULL
    AND(cod_pess_INFORMAL   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (cod_pess_INFORMAL   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR tipo_cont_resp_INF   IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (tipo_cont_resp_INF  IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR contrato_resp_INF    IS NULL ))
    OR (contrato_resp_INF   IS NOT NULL
    AND(cod_empr_pess_INF   IS NULL
    OR cod_pess_INFORMAL    IS NULL
    OR tipo_cont_resp_INF   IS NULL )))
    AND rhorga_AGRUPADOR_H.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA) FROM rhorga_AGRUPADOR_H AUX
    WHERE AUX.CODIGO_EMPRESA =rhorga_AGRUPADOR_H.CODIGO_EMPRESA
    AND AUX.TIPO_AGRUP=rhorga_AGRUPADOR_H.TIPO_AGRUP);
    COMMIT;
 ------------------------------------------------------------------------------------------------FIM-----------------------------------------------------------------------------------------
--*/

--INICIO --10/11/22---------------------------------------LIMPA E POPULA TABELA DE LOCASIS FORMAIS BASEADO NA VIEW: PONTO_ELETRONICO.VW_LOCAIS_FORMAIS ----------------------------------------
DELETE PONTO_ELETRONICO.SUGESP_LOCAIS_FORMAIS; COMMIT;
FOR C1 IN (SELECT P.CPF CPF_GESTOR, V.* FROM PONTO_ELETRONICO.VW_LOCAIS_FORMAIS V LEFT OUTER JOIN RHPESS_PESSOA P ON P.CODIGO_EMPRESA = V.EMPRESA_GESTOR AND P.CODIGO = V.COD_PESSOA_GESTOR) LOOP
INSERT INTO PONTO_ELETRONICO.SUGESP_LOCAIS_FORMAIS VALUES (C1.CPF_GESTOR, C1.CODIGO_EMPRESA, C1.CGC, C1.CODIGO_END, C1.ID_AGRUP, C1.NIVEL_AGRUP_ESTRUT, C1.COD_CGERENC1, C1.COD_CGERENC2, C1.COD_CGERENC3, C1.COD_CGERENC4, C1.COD_CGERENC5, C1.COD_CGERENC6, C1.DESCRICAO, C1.ABREVIACAO, C1.DATA_IMPLANT, C1.DATA_EXTINCAO, C1.EMPRESA_GESTOR, C1.COD_PESSOA_GESTOR, C1.TIPO_CONTRATO_GESTOR, C1.CONTRATO_GESTOR, C1.COD_CGERENC_SUP1, C1.COD_CGERENC_SUP2, C1.COD_CGERENC_SUP3, C1.COD_CGERENC_SUP4, C1.COD_CGERENC_SUP5, C1.COD_CGERENC_SUP6, C1.DESCRIC_LOCAL_SUPERIOR, C1.COD_ENDERECO, C1.DESCR_ENDERECO, C1.TIPO_LOGRADOURO, C1.ENDERECO, C1.NUMERO, C1.COMPLEMENTO, C1.BAIRRO, C1.MUNICIPIO, C1.CEP, C1.REGIAO, C1.LATITUDE, C1.LONGITUDE, C1.IPS_REDE, C1.LOGIN_ENDERECO, C1.DT_ULT_ALTER_ENDE);COMMIT;
END LOOP;
--FIM--10/11/22---------------------------------------LIMPA E POPULA TABELA DE LOCASIS FORMAIS BASEADO NA VIEW: PONTO_ELETRONICO.VW_LOCAIS_FORMAIS ----------------------------------------


/* Gabriel miranda 18:30 02/10 comando para remover duplicidade na carga de proprios da guarda. ajuste necessario para corrigir erro de subconsulta com mais de uma linha */
for c1 in (select  x.* from(
SELECT ROW_NUMBER() OVER(PARTITION BY cod_guarda_municipal ORDER BY cod_guarda_municipal,rowid)ORDEM_BM, 
rowid, U.* FROM ponto_eletronico.smsp_local_g_guarda U WHERE TRUNC(U.data_carga) = TRUNC(SYSDATE)
)x where  ORDEM_BM >1
)loop
delete from ponto_eletronico.smsp_local_g_guarda where rowid=c1.rowid;
commit;
end loop;



--INICIO --10/11/22---------------------------------------INICIO BATE FOTO DIARIA CONTRATOS ARTERH----------------------------------------
    dbms_output.enable(NULL);
    vCONTADOR :=0;
    ------GABRIEL AQUI EM 04/06/2020 TESTANDO NOVA SOLUCAO DO F2
    SELECT XX.DATA_MAX  INTO vDATA_MAX FROM (SELECT
  CASE
    WHEN TRUNC(X.DATA_DO_SISTEMA)<TRUNC(X.DATA_DIA) THEN TRUNC(X.PRIMEIRO_DIA_MES_SEGUINTE)
    WHEN TRUNC(X.DATA_DO_SISTEMA)>TRUNC(X.DATA_DIA)THEN TRUNC(X.PRIMEIRO_DIA_MES_SEGUINTE)
    ELSE X.DATA_DO_SISTEMA
    END AS DATA_MAX
    FROM
      (SELECT data_do_sistema,TRUNC(sysdate, 'mm') AS DATA_DIA,
  TRUNC(add_months(TRUNC(sysdate, 'mm'),+1))AS PRIMEIRO_DIA_MES_SEGUINTE
   FROM rhparm_p_sist
      )X
      )XX;



    FOR C1 IN
    (

SELECT 
case when x.codigo_empresa='0003' then '1' else    '0' end  as GERA_MARCACAO_INTERVALO_AUTO,
CASE WHEN X.COD_PROCURADOR IS NOT NULL THEN 'HIERARQUIA POR PESSOA' WHEN X.COD_PROCURADOR IS NULL AND G.CONTRATO_GESTOR IS NOT NULL THEN 'HIERARQUIA POR LOCAL' ELSE 'PESSOA SEM HIERARQUIA' END TIPO,
X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO, 
CASE WHEN P.NOME_SOCIAL IS NOT NULL AND P.NOME IS NOT NULL THEN P.NOME_SOCIAL WHEN P.NOME_SOCIAL IS NULL THEN P.NOME END AS NOME, CASE WHEN P.APELIDO IS NOT NULL THEN SUBSTR(P.APELIDO, 1,20)END AS APELIDO,
X.CODIGO_PESSOA, P.CPF, P.PIS_PASEP, P.IDENTIDADE, X.CODIGO_ESCALA, X.DT_ULT_ESCALA,
X.SITUACAO_FUNCIONAL, X.DATA_ADMISSAO, X.DATA_RESCISAO, X.USA_ASSOC_CONT_ESC INTEGRADO,
CASE WHEN X.COD_CARGO_EFETIVO IS NOT NULL AND X.COD_CARGO_EFETIVO <>'000000000000000' THEN 'SIM' ELSE 'NAO' END TEM_CARGO_EFETIVO,
X.COD_CARGO_EFETIVO, X.COD_CARGO_COMISS, X.CODIGO_FUNCAO, X.VINCULO,
X.COD_PROCURADOR CODIGO_RESPONSAVEL ,---PEGAR AINDA O CODIGO CONTRATO
--G.COD_CGERENC1, G.COD_CGERENC2, G.COD_CGERENC3, G.COD_CGERENC4, G.COD_CGERENC5, G.COD_CGERENC6, G.DESCRICAO  DESCRICAO_UNIDADE,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000091' ELSE  G.COD_CGERENC1 END AS COD_CGERENC1 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000098' ELSE  G.COD_CGERENC2 END AS COD_CGERENC2 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000000' ELSE  G.COD_CGERENC3 END AS COD_CGERENC3 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000000' ELSE  G.COD_CGERENC4 END AS COD_CGERENC4 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000000' ELSE  G.COD_CGERENC5 END AS COD_CGERENC5 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN '000000' ELSE  G.COD_CGERENC6 END AS COD_CGERENC6 ,
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN 'SECRETARIA MUNICIPAL DE SEGURANÇA PUBLICA-GUARDA' ELSE  G.DESCRICAO END AS DESCRICAO_UNIDADE ,

--G.COD_ENDERECO AS CODIGO_LEGADO, 
CASE WHEN X.COD_CARGO_EFETIVO IN ('000000000001766','000000000001763','000000000001768','000000000001767','000000000001765') THEN (SELECT CASE WHEN X1.ACAO='CERCA SIOM ' THEN X1.CODIGO_ARTE ELSE X1.COD_GUARDA_MUNICIPAL END AS CERCA FROM (
SELECT CASE WHEN SM.CODIGO_ARTE  IS NULL THEN 'CRIAR CERGA DADOS GEO' ELSE 'CERCA SIOM ' END AS ACAO, SM.CODIGO_ARTE,RD.COD_GUARDA_MUNICIPAL,RD.SIGLA_TIPO_LOGRADOURO||' '||RD.NOME_LOGRADOURO||' '||RD.NUMERO_IMOVEL AS NOME_CERCA, RD.LATITUDE, RD.LONGITUDE, RD.FAIXA_REDE FROM PONTO_ELETRONICO.SMSP_CARGA_REDE RD LEFT OUTER JOIN  PONTO_ELETRONICO.ARTERH_SIOM SM ON SM.ID_ENDERECO_CORPORATIVO=RD.COD_ENDERECO_CORPORATIVO AND TRUNC(SM.DATA_CARGA)=(SELECT MAX(TRUNC(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.ARTERH_SIOM AUX)WHERE TRUNC(DATA_DADOS)=(SELECT MAX(TRUNC(AUX.DATA_DADOS)) FROM PONTO_ELETRONICO.SMSP_CARGA_REDE  AUX)
UNION ALL 
SELECT CASE WHEN SM.CODIGO_ARTE  IS NULL THEN 'CRIAR CERGA DADOS GEO' ELSE 'CERCA SIOM ' END AS ACAO,SM.CODIGO_ARTE,G.COD_GUARDA_MUNICIPAL,RD.SIGLA_TIPO_LOGRADOURO||' '||RD.NOME_LOGRADOURO||' '||RD.NUMERO_IMOVEL AS NOME_CERCA,RD.LATITUDE,RD.LONGITUDE,RD.FAIXA_REDE
FROM PONTO_ELETRONICO.SMSP_LOCAL_G_GUARDA G LEFT OUTER JOIN PONTO_ELETRONICO.SMSP_CARGA_REDE RD ON G.COD_REFERENCIA_ENDERECO=RD.COD_GUARDA_MUNICIPAL AND TRUNC(RD.DATA_DADOS)=(SELECT MAX(TRUNC(AUX.DATA_DADOS)) FROM PONTO_ELETRONICO.SMSP_CARGA_REDE  AUX)
LEFT OUTER JOIN  PONTO_ELETRONICO.ARTERH_SIOM SM ON SM.ID_ENDERECO_CORPORATIVO=RD.COD_ENDERECO_CORPORATIVO AND TRUNC(SM.DATA_CARGA)=(SELECT MAX(TRUNC(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.ARTERH_SIOM AUX) WHERE TRUNC(G.DATA_CARGA)=(SELECT MAX(TRUNC(AUX.DATA_CARGA)) FROM PONTO_ELETRONICO.SMSP_LOCAL_G_GUARDA AUX))X1
LEFT OUTER JOIN (SELECT CN.CODIGO_EMPRESA,CN.TIPO_CONTRATO,X.CODIGO_CONTRATO,X.CODIGO_PROPRIO FROM(SELECT 'ULTIMO' AS DIA, LPAD(REPLACE(CARGA.BM,'-',''),15,0) AS CODIGO_CONTRATO,CARGA.CODPROPRIO AS CODIGO_PROPRIO, CARGA.ESCALA ,CARGA.HORAINIC AS HORA_INICIO,CARGA.HORAFIM  AS HORA_FIM,CARGA.DATA_DADOS
FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA CARGA WHERE TRUNC(CARGA.DATA_DADOS)=(SELECT MAX(TRUNC(AUX.DATA_DADOS))FROM PONTO_ELETRONICO.SMSP_SICOOR_ESCALA_LOCAL_DIA AUX))X
LEFT OUTER JOIN(SELECT * FROM ARTERH.RHPESS_CONTRATO CN WHERE CN.ANO_MES_REFERENCIA=(SELECT MAX(AUX.ANO_MES_REFERENCIA)FROM ARTERH.RHPESS_CONTRATO AUX
WHERE AUX.CODIGO = CN.CODIGO AND AUX.CODIGO_EMPRESA=CN.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO =CN.TIPO_CONTRATO))CN ON CN.CODIGO = X.CODIGO_CONTRATO AND CN.CODIGO_EMPRESA = '0001' AND CN.TIPO_CONTRATO = '0001'
LEFT OUTER JOIN ARTERH.RHINTE_ED_IT_CONV CHAVE ON SUBSTR(CHAVE.DADO_ORIGEM,0,4) =CN.CODIGO_EMPRESA AND SUBSTR(CHAVE.DADO_ORIGEM,5,4) = CN.SITUACAO_FUNCIONAL AND CHAVE.CODIGO_CONVERSAO ='POST')C ON C.CODIGO_PROPRIO=X1.COD_GUARDA_MUNICIPAL 
WHERE C.CODIGO_CONTRATO=X.CODIGO AND C.TIPO_CONTRATO=X.TIPO_CONTRATO AND C.CODIGO_EMPRESA=X.CODIGO_EMPRESA GROUP BY CASE WHEN X1.ACAO='CERCA SIOM ' THEN X1.CODIGO_ARTE ELSE X1.COD_GUARDA_MUNICIPAL END)
ELSE G.COD_ENDERECO END AS CODIGO_LEGADO,

G.CODIGO_EMPRESA AS EMPRESA_HIERARQUIA, 
CASE WHEN X.COD_PROCURADOR IS NOT NULL THEN R.CODIGO_EMPRESA WHEN X.COD_PROCURADOR IS NULL AND P.CPF = G.CPF_GESTOR THEN GS.EMPRESA_GESTOR ELSE G.EMPRESA_GESTOR END CODIGO_EMPRESA_GESTOR, 
CASE WHEN X.COD_PROCURADOR IS NOT NULL THEN R.TIPO_CONTRATO WHEN X.COD_PROCURADOR IS NULL AND P.CPF = G.CPF_GESTOR THEN GS.TIPO_CONTRATO_GESTOR ELSE G.TIPO_CONTRATO_GESTOR END TIPO_CONTRATO_GESTOR, 
CASE WHEN X.COD_PROCURADOR IS NOT NULL THEN R.CODIGO WHEN X.COD_PROCURADOR IS NULL AND P.CPF = G.CPF_GESTOR THEN GS.CONTRATO_GESTOR ELSE G.CONTRATO_GESTOR END CONTRATO_GESTOR, 
CASE WHEN X.COD_PROCURADOR IS NOT NULL THEN PR.CPF WHEN X.COD_PROCURADOR IS NULL AND P.CPF = G.CPF_GESTOR THEN GS.CPF_GESTOR ELSE G.CPF_GESTOR END CPF_GESTOR,
'USA_AMBOS' TIPO_USUARIO,  X.REGISTRO_PONTO
, CASE WHEN X.COD_PROCURADOR IS NULL AND P.CPF = G.CPF_GESTOR THEN 'GESTOR_SUP_FORMAL' ELSE 'SERVIDOR' END TIPO_PESSOA, 'N' E_GESTOR, 'PESSOA' AS ENTIDADE, S.CONTROLE_FOLHA, S.E_AFASTAMENTO, S.SUSPENDE_REMUNERA

,CASE  WHEN X.VINCULO = '0055' THEN 'INATIVO'--KELLYSSON em 20/5/22 ajuste para tirar as pessoas JETON
     WHEN V.RETORNO_FOTO IS NOT NULL THEN V.RETORNO_FOTO ELSE CHAVE.DADO_DESTINO END AS CHAVE_INTEGRACAO
,EL.c_livre_valor01 AS DIA_COMECO_CICLO
, CASE WHEN CS.DADO_ORIGEM IS NOT NULL THEN 1 ELSE 0 END EXCECAO_FUNCIONAL--NOVO EM 16/8/22 EMAIL (Customização - Cadastro de justificativa)

FROM ARTERH.RHPESS_CONTRATO X
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC S ON S.CODIGO = X.SITUACAO_FUNCIONAL
LEFT OUTER JOIN ARTERH.RHPESS_PESSOA P ON X.CODIGO_PESSOA = P.CODIGO AND X.CODIGO_EMPRESA = P.CODIGO_EMPRESA
LEFT OUTER JOIN PONTO_ELETRONICO.SUGESP_LOCAIS_FORMAIS G ON -- X.CODIGO_EMPRESA     = G.CODIGO_EMPRESA AND
X.COD_CUSTO_GERENC1 = G.COD_CGERENC1 AND X.COD_CUSTO_GERENC2 = G.COD_CGERENC2 AND X.COD_CUSTO_GERENC3 = G.COD_CGERENC3 AND X.COD_CUSTO_GERENC4 = G.COD_CGERENC4 AND X.COD_CUSTO_GERENC5 = G.COD_CGERENC5 AND X.COD_CUSTO_GERENC6 = G.COD_CGERENC6
LEFT OUTER JOIN PONTO_ELETRONICO.SUGESP_LOCAIS_FORMAIS GS ON -- X.CODIGO_EMPRESA     = G.CODIGO_EMPRESA AND
G.COD_CGERENC_SUP1 = GS.COD_CGERENC1 AND G.COD_CGERENC_SUP2 = GS.COD_CGERENC2 AND G.COD_CGERENC_SUP3 = GS.COD_CGERENC3 AND G.COD_CGERENC_SUP4 = GS.COD_CGERENC4 AND G.COD_CGERENC_SUP5 = GS.COD_CGERENC5 AND G.COD_CGERENC_SUP6 = GS.COD_CGERENC6


----------------------GABRIEL AQUI EM 30/03/2020 NOVA CHAVE DE SEGURANCA DAS INTEGRACOES COM A TABELA DE CONVERSAO--------------------------------
LEFT OUTER JOIN (SELECT * FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO='PONT')PONT ON SUBSTR(PONT.DADO_ORIGEM,20,4)=X.CODIGO_EMPRESA AND SUBSTR(PONT.DADO_ORIGEM,24,4)=X.TIPO_CONTRATO
--------------------------------------------------------FIM NOVA CHAVE -------------------------------------------------------------------------------------------
-------------------------------------------NOVA BUSCA EMPRESA HIERAQUIA PONTO PARA RESOLVER PROBLEMAS SERVIDORES EM EMPRESA X LOTADOS EM LOCAIS DA EMPRESA Y------------------------------
--COMENTADO 2/11/22-- LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA EM ON TRIM(EM.CGC)=TRIM(G.CGC) AND EM.C_LIVRE_SELEC02='1'
LEFT OUTER JOIN (SELECT E.* FROM ARTERH.RHORGA_EMPRESA E LEFT OUTER JOIN (SELECT * FROM RHINTE_ED_IT_CONV  WHERE CODIGO_CONVERSAO = 'EMPA')V ON V.DADO_ORIGEM = E.CODIGO WHERE V.DADO_ORIGEM IS NOT NULL) EM ON TRIM(EM.CGC)=TRIM(G.CGC) --NOVO 2/11/22-- 

--VINCULA O CADASTRO DO CONTRATO (R) DA PESSOA DO GESTOR IFPONTO (GG) DO CONTRATO SUBORDINADO (X)
--GABRIEL AQUI UNIFIQUEI TODAS AS REGRAS DE GESTOR POR PESSOA EM UMA VIEW PARA RESOLVER TODOS OS PROBLEMAS QUE OCORRERAM NO MES 05/2023
LEFT JOIN (SELECT * FROM PONTO_ELETRONICO.VIEW_CONTRATO_GESTOR_PESSOA)R ON X.COD_PROCURADOR = R.CODIGO_PESSOA AND X.CODIGO_EMPRESA = R.CODIGO_EMPRESA AND X.TIPO_CONTRATO  = R.TIPO_CONTRATO 
LEFT OUTER JOIN ARTERH.RHPESS_PESSOA PR ON R.CODIGO_PESSOA = PR.CODIGO AND R.CODIGO_EMPRESA = PR.CODIGO_EMPRESA

LEFT OUTER JOIN  ARTERH.RHINTE_ED_IT_CONV CHAVE ON SUBSTR(CHAVE.DADO_ORIGEM,0,4)=X.CODIGO_EMPRESA AND SUBSTR(CHAVE.DADO_ORIGEM,5,4)=X.SITUACAO_FUNCIONAL AND CHAVE.CODIGO_CONVERSAO='POST'

LEFT OUTER JOIN (SELECT * FROM ARTERH.RHPONT_ALT_ESCALA EL WHERE EL.ALTER_DEFINITIVA='S' AND EL.DT_INICIO_TROCA=(SELECT MAX (AUX.DT_INICIO_TROCA) FROM ARTERH.RHPONT_ALT_ESCALA AUX  WHERE AUX.CODIGO_EMPRESA=EL.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO=EL.TIPO_CONTRATO AND AUX.CODIGO_CONTRATO=EL.CODIGO_CONTRATO AND AUX.COD_ESCALA=EL.COD_ESCALA AND AUX.ALTER_DEFINITIVA='S') 
)EL ON EL.CODIGO_CONTRATO=X.CODIGO AND EL.TIPO_CONTRATO=X.TIPO_CONTRATO AND EL.CODIGO_EMPRESA=X.CODIGO_EMPRESA AND EL.COD_ESCALA=X.CODIGO_ESCALA

LEFT OUTER JOIN ARTERH.VW_PONTO_1017_FOTO V ON V.CODIGO_EMPRESA=X.CODIGO_EMPRESA AND V.CODIGO_CONTRATO=X.CODIGO AND V.TIPO_CONTRATO=X.TIPO_CONTRATO

LEFT OUTER JOIN (SELECT * FROM RHINTE_ED_IT_CONV  WHERE CODIGO_CONVERSAO = 'CESS')CS ON CS.DADO_ORIGEM = X.SITUACAO_FUNCIONAL --NOVO EM 16/8/22 EMAIL (Customização - Cadastro de justificativa)

WHERE
X.ANO_MES_REFERENCIA = (SELECT MAX(AUX.ANO_MES_REFERENCIA)FROM ARTERH.RHPESS_CONTRATO AUX WHERE AUX.CODIGO_EMPRESA = X.CODIGO_EMPRESA AND AUX.TIPO_CONTRATO = X.TIPO_CONTRATO AND AUX.CODIGO = X.CODIGO 
AND AUX.ANO_MES_REFERENCIA <= vDATA_MAX
)
    -----------------------GABRIEL AQUI EM 30/03/2020 NOVA VERSAO COM NOVA FORAM DE COLOCAR AS CHAVES DE SEGURANDA NAS INTEGRACOES-----------------------------
AND SUBSTR(PONT.DADO_ORIGEM,24,4) IS NOT NULL 
--TROCADA PELA LINHA ABAIXO EM 21/12/22--AND G.CODIGO_EMPRESA= (SELECT PONT.* FROM(SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT WHERE PONT.EMPRESA=G.CODIGO_EMPRESA)
AND X.CODIGO_EMPRESA= (SELECT PONT.* FROM(SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT WHERE PONT.EMPRESA=X.CODIGO_EMPRESA)--EM 21/12/22 TROQUEI EMPRESA DE G PARA X EMAIL (Frequência AEG - HOB)
--and X.CODIGO = LPAD(33747,15,0)
 --------------------------------------------------------FIM NOVA CHAVE -------------------------------------------------------------------------------------------
AND X.VINCULO NOT IN ('0055','0033') -- KELLYSSON EM 23/11/22 ADICIONOU 33 PARA A PRODABEL --KELLYSSON EM 18/8/22 EMAIL (Alteração do Cadastro no ArteRH - Membros da CFCM)
AND X.REGISTRO_PONTO <> '0190' --NOVO EM 23/11/22 PARA ATENDER PRODABEL E DEMAIS EMPRESA
--AND X.CODIGO = LPAD('883291',15,0)---TESTE
--AND ((X.CODIGO_EMPRESA = '0006' OR X.TIPO_CONTRATO = '0007')OR(X.CODIGO = LPAD(3129762,15,0)))

ORDER BY X.CODIGO_EMPRESA, X.TIPO_CONTRATO, X.CODIGO


)LOOP

INSERT INTO PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE (DT_SAIU_ARTE, TIPO, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, NOME, APELIDO, CODIGO_PESSOA, CPF, PIS_PASEP, IDENTIDADE, CODIGO_ESCALA, DT_ULT_ESCALA, SITUACAO_FUNCIONAL, DATA_ADMISSAO, DATA_RESCISAO, INTEGRADO, TEM_CARGO_EFETIVO, COD_CARGO_EFETIVO, COD_CARGO_COMISS, CODIGO_FUNCAO, VINCULO, COD_UNIDADE1, COD_UNIDADE2, COD_UNIDADE3, COD_UNIDADE4, COD_UNIDADE5, COD_UNIDADE6,  DESCRICAO_UNIDADE, CODIGO_LEGADO, EMPRESA_HIERARQUIA, CODIGO_EMPRESA_GESTOR, TIPO_CONTRATO_GESTOR, CONTRATO_GESTOR, CPF_GESTOR, TIPO_USUARIO, REGISTRO_PONTO, TIPO_PESSOA, E_GESTOR, ENTIDADE, CONTROLE_FOLHA, E_AFASTAMENTO, SUSPENDE_REMUNERA, CHAVE_INTEGRACAO, DIA_COMECO_CICLO, EXCECAO_FUNCIONAL,GERA_MARCACAO_INTERVALO_AUTO) 
VALUES(SYSDATE, C1.TIPO, C1.CODIGO_EMPRESA, C1.TIPO_CONTRATO, C1.CODIGO, C1.NOME, C1.APELIDO, C1.CODIGO_PESSOA, C1.CPF, C1.PIS_PASEP, C1.IDENTIDADE, C1.CODIGO_ESCALA, C1.DT_ULT_ESCALA, C1.SITUACAO_FUNCIONAL, C1.DATA_ADMISSAO, C1.DATA_RESCISAO, C1.INTEGRADO, C1.TEM_CARGO_EFETIVO, C1.COD_CARGO_EFETIVO, C1.COD_CARGO_COMISS, C1.CODIGO_FUNCAO, C1.VINCULO, C1.COD_CGERENC1, C1.COD_CGERENC2, C1.COD_CGERENC3, C1.COD_CGERENC4, C1.COD_CGERENC5, C1.COD_CGERENC6, C1. DESCRICAO_UNIDADE, C1.CODIGO_LEGADO, C1.EMPRESA_HIERARQUIA, C1.CODIGO_EMPRESA_GESTOR, C1.TIPO_CONTRATO_GESTOR, C1.CONTRATO_GESTOR, C1.CPF_GESTOR, C1.TIPO_USUARIO,  C1.REGISTRO_PONTO, C1.TIPO_PESSOA, C1.E_GESTOR, C1.ENTIDADE, C1.CONTROLE_FOLHA, C1.E_AFASTAMENTO, C1.SUSPENDE_REMUNERA, C1.CHAVE_INTEGRACAO, C1.DIA_COMECO_CICLO, C1.EXCECAO_FUNCIONAL,c1.GERA_MARCACAO_INTERVALO_AUTO );COMMIT;
END LOOP;


--FIM --10/11/22---------------------------------------BATE FOTO DIARIA CONTRATOS ARTERH----------------------------------------


--INICIO --18/11/22 --------------------------TIRAR DUPLICIDADE DE BM NA FOTO---------------------------------------------
--EM 17/11/22 --TIRAR DUPLICIDADE FOTO
FOR C1 IN (
select 'delete PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE where rowid ='''|| x.rowid||''';commit;' comando, x.* from(
SELECT ROW_NUMBER() OVER(PARTITION BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO ORDER BY CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO,rowid)ORDEM_BM, 
rowid, U.* FROM PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE U WHERE TRUNC(U.DT_SAIU_ARTE) = TRUNC(SYSDATE)
)x where  ORDEM_BM >1

)LOOP
delete PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE where rowid = C1.rowid; commit;
END LOOP;
--FIM--18/11/22 --------------------------TIRAR DUPLICIDADE DE BM NA FOTO---------------------------------------------


--INICIO--11/11/22---------------------------------------POPULA O E_GESTOR----------------------------------------
FOR C1 IN (


SELECT X.* FROM (SELECT 
'REGRA_NOVA' AS ORIGEM,
ROW_NUMBER() OVER(PARTITION BY CPF ORDER BY CPF )ORDEM_MESMO_CPF,
ROW_NUMBER() OVER(PARTITION BY CPF,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO ORDER BY CPF,CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO )ORDEM_MESMO_BM,
CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO, CPF, DT_SAIU_ARTE FROM  PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE U
WHERE TRUNC(U.DT_SAIU_ARTE) = ( SELECT TRUNC(MAX(AUX.DT_SAIU_ARTE)) FROM PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE AUX )
AND  EXISTS(SELECT G.CPF_GESTOR  FROM PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE G WHERE TRUNC(G.DT_SAIU_ARTE) = TRUNC(U.DT_SAIU_ARTE) AND G.CPF_GESTOR IS NOT NULL AND G.CPF_GESTOR = U.CPF 
                --AND G.DATA_RESCISAO IS NULL
                GROUP BY G.CPF_GESTOR )
               -- AND CODIGO_CONTRATO=LPAD('3135142',15,0)
ORDER BY CPF, CODIGO_EMPRESA, TIPO_CONTRATO, CODIGO_CONTRATO
)X
UNION ALL

SELECT
    x.*
FROM
    (
        SELECT
            'REGRA_ANTIGA'     AS origem,
            NULL               AS ordem_mesmo_cpf,
            NULL               AS ordem_mesmo_bm,
            g.cod_empresa_pess AS codigo_empresa,
            g.tipo_cont_resp   AS tipo_contrato,
            g.contrato_resp    AS codigo_contrato,
            p.cpf              AS cpf,
            NULL               AS dt_saiu_arte
        FROM
            arterh.rhorga_custo_geren g
            LEFT OUTER JOIN arterh.rhpess_pessoa      p ON p.codigo = g.cod_pessoa_resp
                                                      AND p.codigo_empresa = g.cod_empresa_pess
            LEFT OUTER JOIN arterh.rhorga_empresa     emp ON emp.codigo = g.codigo_empresa
        WHERE
                TRIM(emp.cgc) = TRIM(g.cgc)
            AND g.data_extincao IS NULL
            AND G.COD_CGERENC1 NOT IN ('000099') AND COD_CGERENC2 NOT IN ('000095','000098')
            AND g.cod_empresa_pess IS NOT NULL AND g.contrato_resp IS NOT NULL
            GROUP BY g.cod_empresa_pess,g.tipo_cont_resp,g.contrato_resp,P.CPF
    ) x



)LOOP
if (c1.origem='REGRA_NOVA') then
UPDATE PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE  SET E_GESTOR='S' WHERE CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CPF = C1.CPF AND TRUNC(DT_SAIU_ARTE) = TRUNC(C1.DT_SAIU_ARTE);
COMMIT;
else
UPDATE PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE  SET E_GESTOR='S' WHERE CODIGO_CONTRATO = C1.CODIGO_CONTRATO AND CODIGO_EMPRESA = C1.CODIGO_EMPRESA AND TIPO_CONTRATO = C1.TIPO_CONTRATO AND CPF = C1.CPF AND TRUNC(DT_SAIU_ARTE) = TRUNC(sysdate);
end if;
END LOOP;

--/*
UPDATE PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE U SET U.E_GESTOR = '?'
WHERE TRUNC(U.DT_SAIU_ARTE) = (SELECT TRUNC(MAX(DT_SAIU_ARTE)) FROM PONTO_ELETRONICO.SUGESP_BI_1CONTRAT_INTIF_ARTE)
AND U.TIPO_PESSOA IN ('GESTOR_SUP_INFORMAL','GESTOR_SUP_FORMAL') AND U.E_GESTOR NOT IN ('S'); COMMIT;
--*/
--FIM --11/11/22---------------------------------------POPULA O E_GESTOR----------------------------------------


END;       -- 1º BEGIN  
END SMARH_INT_PE_CONTRATOS_ARTE;