
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_CAD_PESSOA" (DATA_INICIO IN VARCHAR2, DATA_FIM IN VARCHAR2)
AS
BEGIN
DECLARE
vDATA_INICIO VARCHAR2(100);
vDATA_FIM VARCHAR2(100);
vCONTADOR NUMBER;
BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;
FOR C1 IN (
SELECT GERN.CODIGO_EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
GERN.COD_ENDERECO AS CODIGO_LEGADO,
SUBSTR( GERN.CODIGO_EMPRESA,3,2)||'.'||GERN.COD_CGERENC1||'.'||GERN.COD_CGERENC2||'.'||GERN.COD_CGERENC3||'.'||GERN.COD_CGERENC4||'.'||GERN.COD_CGERENC5||'.'||GERN.COD_CGERENC6 AS COD_UNIDADE,
GERN.DESCRICAO,
SYSDATE AS DT_SAIU_ARTE,
NULL AS TIPO_CONTRATO,
NULL AS CODIGO_CONTRATO,
NULL AS COD_CARGO,
NULL AS DT_ENVIADO_IFPONTO_SURICATO,
CASE WHEN EN.c_livre_data01 IS NOT NULL  AND EN.c_livre_data02 IS NULL THEN'INCLUIR'
WHEN EN.c_livre_data02 IS NOT NULL AND EN.c_livre_data01 IS NOT NULL THEN 'EXCLUIR'
ELSE 'ALTERACAO_DIVERSAS' END AS TIPO
FROM ARTERH.RHORGA_CUSTO_GEREN GERN
LEFT OUTER JOIN ARTERH.RHORGA_ENDERECO EN
ON  GERN.COD_ENDERECO =EN.CODIGO
LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA EP
ON GERN.CODIGO_EMPRESA=EP.CODIGO
WHERE GERN.DATA_EXTINCAO IS NULL
AND GERN.CODIGO_EMPRESA = (SELECT PONT.*
                                             FROM
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=GERN.CODIGO_EMPRESA)
AND EN.c_livre_data01 IS NOT NULL
AND GERN.CGC=EP.CGC
AND  (TRUNC(GERN.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND  vDATA_FIM)
AND GERN.LOGIN_USUARIO NOT IN ('IFPONTO','IMP_AMPS_SMED') --NOVO EM 12/8/22
)
LOOP
vCONTADOR:=vCONTADOR+1;
INSERT INTO PONTO_ELETRONICO.SMARH_INT_CAD_PESS_CERCA
(CODIGO_EMPRESA,
AGRUPAMENTO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
COD_UNIDADE,
DESCRICAO_UNIDADE,
TIPO,
COD_CARGO,
CODIGO_LEGADO,
DT_SAIU_ARTE,
DT_ENVIADO_IFPONTO_SURICATO
,CODIGO_INTEGRA_ARTE --NOVO 4/7/22
)
VALUES
(C1.CODIGO_EMPRESA,
C1.AGRUPAMENTO_EMPRESA,
C1.TIPO_CONTRATO,
C1.CODIGO_CONTRATO,
C1.COD_UNIDADE,
C1.DESCRICAO,
C1.TIPO,
C1.COD_CARGO,
C1.CODIGO_LEGADO,
C1.DT_SAIU_ARTE,
C1.DT_ENVIADO_IFPONTO_SURICATO
,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
);
COMMIT;
END LOOP;
END;
------ GABRIEL AQUI EM 20/02/2020 NOVA ATUALIZACAO INCLUINDO A CERCA POR PESSOA BASEADO NO ENDERECO AUXILIAR COLOCADO  A CERCA REGIONAL VINCULADA A UNIDADE DE LOTACAO DA PESSOA
 BEGIN
DECLARE
vDATA_INICIO VARCHAR2(100);
vDATA_FIM VARCHAR2(100);
vCONTADOR NUMBER;
  BEGIN
    dbms_output.enable(NULL);
    vCONTADOR    :=0;
    vDATA_INICIO := DATA_INICIO;
    vDATA_FIM    := DATA_FIM;
    FOR C1 IN
    (
SELECT 'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,X.*,EN.CODIGO_ENDERECO01 AS CODIGO_LEGADO,CASE WHEN GX.c_livre_opcao25='N' THEN' EXCLUIR'
WHEN GX.c_livre_opcao25='S' AND CG.c_livre_opcao9='S' THEN'INCLUIR'
WHEN GX.c_livre_opcao25='S'  AND CG.c_livre_opcao9='N' THEN 'EXCLUIR'
WHEN GX.c_livre_opcao25='S'   AND F.c_livre_opcao9='S' THEN'INCLUIR'
WHEN GX.c_livre_opcao25='S' AND  F.c_livre_opcao9='N'THEN 'EXCLUIR'
END AS TIPO,
SYSDATE AS DT_SAIU_ARTE,
NULL AS DT_ENVIADO_IFPONTO_SURICATO
FROM (SELECT X.CODIGO_EMPRESA,
X.TIPO_CONTRATO,
X.CODIGO AS CODIGO_CONTRATO,
X.CODIGO_FUNCAO,
X.COD_CARGO_EFETIVO,
X.COD_CARGO_COMISS,
X.COD_CUSTO_GERENC1 AS CODIGO_UNIDADE1,
X.COD_CUSTO_GERENC2 AS CODIGO_UNIDADE2,
X.COD_CUSTO_GERENC3 AS CODIGO_UNIDADE3,
X.COD_CUSTO_GERENC4 AS CODIGO_UNIDADE4,
X.COD_CUSTO_GERENC5 AS CODIGO_UNIDADE5,
X.COD_CUSTO_GERENC6 AS CODIGO_UNIDADE6,
CASE WHEN ((X.COD_CARGO_EFETIVO IS NULL OR X.COD_CARGO_EFETIVO='000000000000000') AND (X.COD_CARGO_COMISS IS NULL OR X.COD_CARGO_COMISS ='000000000000000') AND (X.CODIGO_FUNCAO IS NULL OR  X.CODIGO_FUNCAO='000000000000000')) THEN NULL
WHEN ((X.COD_CARGO_EFETIVO IS NOT  NULL OR X.COD_CARGO_EFETIVO !='000000000000000')AND (X.COD_CARGO_COMISS IS NULL OR X.COD_CARGO_COMISS ='000000000000000') AND (X.CODIGO_FUNCAO IS NULL OR  X.CODIGO_FUNCAO='000000000000000')) THEN X.COD_CARGO_EFETIVO

WHEN ((X.COD_CARGO_EFETIVO IS NULL OR X.COD_CARGO_EFETIVO='000000000000000') AND (X.COD_CARGO_COMISS IS NOT NULL OR X.COD_CARGO_COMISS !='000000000000000') AND (X.CODIGO_FUNCAO IS NULL OR  X.CODIGO_FUNCAO='000000000000000')) THEN X.COD_CARGO_COMISS
WHEN ((X.COD_CARGO_EFETIVO IS NOT  NULL OR X.COD_CARGO_EFETIVO !='000000000000000')AND (X.COD_CARGO_COMISS IS NOT NULL OR X.COD_CARGO_COMISS !='000000000000000') AND (X.CODIGO_FUNCAO IS NULL OR  X.CODIGO_FUNCAO='000000000000000')) THEN X.COD_CARGO_COMISS

WHEN ((X.COD_CARGO_EFETIVO IS NOT  NULL OR X.COD_CARGO_EFETIVO !='000000000000000')AND (X.COD_CARGO_COMISS IS NULL OR X.COD_CARGO_COMISS ='000000000000000') AND (X.CODIGO_FUNCAO IS NOT  NULL OR  X.CODIGO_FUNCAO!='000000000000000')) THEN X.CODIGO_FUNCAO
WHEN ((X.COD_CARGO_EFETIVO IS NULL OR X.COD_CARGO_EFETIVO='000000000000000') AND (X.COD_CARGO_COMISS IS NOT NULL OR X.COD_CARGO_COMISS !='000000000000000')  AND (X.CODIGO_FUNCAO IS NOT  NULL OR  X.CODIGO_FUNCAO!='000000000000000')) THEN X.CODIGO_FUNCAO
WHEN ((X.COD_CARGO_EFETIVO IS NOT  NULL OR X.COD_CARGO_EFETIVO !='000000000000000')AND (X.COD_CARGO_COMISS IS NOT NULL OR X.COD_CARGO_COMISS !='000000000000000')AND (X.CODIGO_FUNCAO IS NOT  NULL OR  X.CODIGO_FUNCAO!='000000000000000')) THEN X.CODIGO_FUNCAO
WHEN ((X.COD_CARGO_EFETIVO IS NULL OR X.COD_CARGO_EFETIVO='000000000000000')AND (X.COD_CARGO_COMISS IS NULL OR X.COD_CARGO_COMISS ='000000000000000') AND (X.CODIGO_FUNCAO IS NOT  NULL OR  X.CODIGO_FUNCAO!='000000000000000')) THEN X.CODIGO_FUNCAO END AS CARGO_CERCA

FROM ARTERH.RHPESS_CONTRATO X
LEFT OUTER JOIN ARTERH.RHPARM_SIT_FUNC SF
ON SF.CODIGO=X.SITUACAO_FUNCIONAL
LEFT OUTER JOIN
          (SELECT * FROM RHINTE_ED_IT_CONV WHERE CODIGO_CONVERSAO='PONT')PONTR
          ON   SUBSTR(PONTR.DADO_ORIGEM,20,4)=X.CODIGO_EMPRESA
          AND SUBSTR(PONTR.DADO_ORIGEM,24,4)=X.TIPO_CONTRATO
WHERE  X.ANO_MES_REFERENCIA =
            (SELECT MAX(ANO_MES_REFERENCIA)
            FROM ARTERH.RHPESS_CONTRATO AUX
            WHERE AUX.CODIGO_EMPRESA    = X.CODIGO_EMPRESA
            AND AUX.TIPO_CONTRATO       = X.TIPO_CONTRATO
            AND AUX.CODIGO              = X.CODIGO
            AND AUX.ANO_MES_REFERENCIA <=
              (SELECT data_do_sistema FROM ARTERH.rhparm_p_sist
              ))
               AND SUBSTR(PONTR.DADO_ORIGEM,20,4) IS NOT NULL
                AND X.DATA_RESCISAO IS NULL
                AND SF.CONTROLE_FOLHA NOT IN ('D','S')
)X LEFT OUTER JOIN ARTERH.RHORGA_CUSTO_GEREN GX
ON GX.CODIGO_EMPRESA=X.CODIGO_EMPRESA
AND GX.COD_CGERENC1=X.CODIGO_UNIDADE1
AND GX.COD_CGERENC2=X.CODIGO_UNIDADE2
AND GX.COD_CGERENC3=X.CODIGO_UNIDADE3
AND GX.COD_CGERENC4=X.CODIGO_UNIDADE4
AND GX.COD_CGERENC5=X.CODIGO_UNIDADE5
AND GX.COD_CGERENC6=X.CODIGO_UNIDADE6
LEFT OUTER JOIN ARTERH.RHPLCS_CARGO CG
ON CG.CODIGO=X.CARGO_CERCA
AND CG.CODIGO_EMPRESA=X.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHPLCS_FUNCAO F
ON F.CODIGO_EMPRESA=CG.CODIGO_EMPRESA
AND F.CODIGO=X.CARGO_CERCA
LEFT OUTER JOIN ARTERH.RHORGA_ENDERECO EN
ON EN.CODIGO=GX.COD_ENDERECO
-----DEFINE QUE USAR CERCA POR REGIONAL
WHERE GX.c_livre_opcao25='S'
AND (CG.c_livre_opcao9='S' OR F.c_livre_opcao9='S')
AND (
     (TRUNC(GX.DT_ULT_ALTER_USUA)  BETWEEN vDATA_INICIO AND vDATA_FIM)
 OR (TRUNC(CG.DT_ULT_ALTER_USUA)  BETWEEN vDATA_INICIO AND vDATA_FIM)
 OR (TRUNC(F.DT_ULT_ALTER_USUA)  BETWEEN vDATA_INICIO AND vDATA_FIM)
 )
)LOOP
vCONTADOR:=vCONTADOR+1;
INSERT INTO PONTO_ELETRONICO.SMARH_INT_CAD_PESS_CERCA
(AGRUPAMENTO_EMPRESA,
CODIGO_EMPRESA,
TIPO_CONTRATO,
CODIGO_CONTRATO,
CODIGO_LEGADO,
TIPO,
DT_SAIU_ARTE,
DT_ENVIADO_IFPONTO_SURICATO
,CODIGO_INTEGRA_ARTE --NOVO 4/7/22
)VALUES(
C1.AGRUPAMENTO_EMPRESA,
C1.CODIGO_EMPRESA,
C1.TIPO_CONTRATO,
C1.CODIGO_CONTRATO,
C1.CODIGO_LEGADO,
C1.TIPO,
C1.DT_SAIU_ARTE,
C1.DT_ENVIADO_IFPONTO_SURICATO
,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
);
COMMIT;

END LOOP;
END;
end;
END SMARH_INT_CAD_PESSOA;