
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_ATUALIZA_IFPONTO" AS
BEGIN
--KELLYSSON 28/12/18
----BUSCAR CONTRATOS PARA COMPARAR OS DIAS E ATUALIAR O IFPONTO
DECLARE
vCONTADOR NUMBER;

BEGIN
dbms_output.enable(null);
vCONTADOR :=0;

FOR C1 IN (
SELECT * FROM PONTO_ELETRONICO.VIEW_SELECT_BASE_FOR_ATUALIZA_IFPONTO_ARTE 
)------FIM DO FOR

LOOP

insert into PONTO_ELETRONICO.SMARH_INT_PONTO_DADOS_SERV_V10
(CODIGO_EMPRESA, EMPRESA, AGRUPAMENTO_EMPRESA, CPF, NOME, APELIDO, PIS_PASEP, IDENTIDADE, TIPO_CONTRATO, CODIGO_CONTRATO, CODIGO_ESCALA, DT_ULT_ESCALA, COD_UNIDADE1, COD_UNIDADE2, COD_UNIDADE3, COD_UNIDADE4, COD_UNIDADE5, COD_UNIDADE6, DESCRICAO_UNIDADE, CODIGO_CARGO_EFETIVO, DESCRICAO_CARGO_EFETIVO, CODIGO_CARGO_COMISSIONADO, DESCRICAO_CARGO_COMISSIONADO, DATA_ADMISSAO, DATA_RESCISAO,  REGISTRO_PONTO,CODIGO_EMPRESA_GESTOR,TIPO_CONTRATO_GESTOR, CODIGO_RESPONSAVEL, TIPO_VW_DADOS_SERVIDOR, DT_SAIU_ARTE, DT_ENVIADO_IFPONTO_SURICATO, LOCAL_GESTOR,COD_TIPO_PESSOA,CODIGO_LEGADO,CODIGO_UNIDADE, DIA_COMECO_CICLO, CODIGO_INTEGRA_ARTE, EXCECAO_FUNCIONAL,GERA_MARCACAO_INTERVALO_AUTO,CODIGO_VINCULO,descricao_vinCULO)
values
(C1.CODIGO_EMPRESA, C1.EMPRESA, C1.AGRUPAMENTO_EMPRESA, C1.CPF, C1.NOME, C1.APELIDO, C1.PIS_PASEP, C1.IDENTIDADE, C1.TIPO_CONTRATO, C1.CODIGO_CONTRATO, C1.CODIGO_ESCALA, C1.DT_ULT_ESCALA, C1.COD_UNIDADE1, C1.COD_UNIDADE2, C1.COD_UNIDADE3, C1.COD_UNIDADE4, C1.COD_UNIDADE5, C1.COD_UNIDADE6, C1.DESCRICAO_UNIDADE, C1.CODIGO_CARGO_EFETIVO, C1.DESCRICAO_CARGO_EFETIVO, C1.CODIGO_CARGO_COMISSIONADO, C1.DESCRICAO_CARGO_COMISSIONADO, C1.DATA_ADMISSAO, C1.DATA_RESCISAO,  C1.REGISTRO_PONTO, C1.CODIGO_EMPRESA_GESTOR,C1.TIPO_CONTRATO_GESTOR,C1.CODIGO_RESPONSAVEL, C1.TIPO_VW_DADOS_SERVIDOR, C1.DT_SAIU_ARTE, C1.DT_ENVIADO_IFPONTO_SURICATO, C1.LOCAL_GESTOR,C1.COD_TIPO_PESSOA,C1.CODIGO_LEGADO,C1.CODIGO_UNIDADE,C1.DIA_COMECO_CICLO
,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
,C1.EXCECAO_FUNCIONAL--NOVO EM 16/8/22 EMAIL (Customização - Cadastro de justificativa)
,C1.MARCACAO_INTERVALO_AUTO,
C1.CODIGO_VINCULO,
C1.descricao_vinCULO
);

commit;

END LOOP;

END;
END SMARH_INT_PE_ATUALIZA_IFPONTO;