
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_CAD_JUSTIFICATIVA" (
    DATA_INICIO IN VARCHAR2,
    DATA_FIM    IN VARCHAR2)
AS
BEGIN
  DECLARE
    vCONTADOR    NUMBER;
    vDATA_INICIO VARCHAR2(10);
    vDATA_FIM    VARCHAR2(10);
  BEGIN
    dbms_output.enable(NULL);
    vCONTADOR    :=0;
    vDATA_INICIO := DATA_INICIO;
    vDATA_FIM    := DATA_FIM;
    FOR C1 IN
    (
    SELECT X.* FROM (
SELECT XXX.*,SYSDATE AS DT_SAIU_ARTE,NULL AS DT_ENVIADO_IFPONTO_SURICATO,'INCLUIR' AS TIPO FROM (SELECT TUDO.* FROM (SELECT SIT_FUN.* FROM (SELECT X1.* FROM (
SELECT '0001' AS CODIGO_EMPRESA,
'PREF.MUN.BELO HORIZONTE'AS EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
PN.DESCRICAO,
PN.CODIGO AS NRO,
PN.CODIGO AS CODIGO_LEGADO,

CASE WHEN PN.c_livre_selec01='1'THEN'01'----espelho
WHEN PN.c_livre_selec01='2' THEN '02'---lancamento de ocorrencia
WHEN PN.c_livre_selec01='3' THEN'03'---- BANCO DE HORAS
WHEN PN.c_livre_selec01='4' THEN '04' ----TODOS
WHEN PN.c_livre_selec01='9'THEN 'TOTALIZADOR_IFPONTO' ELSE 'ERRO'END AS  VISUALIZAR_NO_SUBMENU,
CASE
        WHEN PN.c_livre_selec02 = 1
        THEN 'Semanal'
        WHEN PN.c_livre_selec02 = 2
        THEN 'Mensal'
        WHEN PN.c_livre_selec02 = 3
        THEN 'Anual'
        WHEN PN.c_livre_selec02 = 9
        THEN 'Ilimitda'
        ELSE 'ERRO'
      END periodo,
      c_livre_selec03 QTD_LIMITE,
      PN.data_extincao
,CASE WHEN PN.c_livre_opcao01 = 'S' THEN 0 WHEN PN.c_livre_opcao01 = 'N' THEN 1 END APENAS_ADMIN
,PN.TIPO_REFERENCIA --NOVO EM 22/11/23 EMAIL (Customização - LICENÇA PARCIAL)
FROM ARTERH.RHPARM_SIT_FUNC SF
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO PN
ON SF.SITUACAO_PONTO=PN.CODIGO
WHERE SF.DATA_FIM_VIGENCIA IS NULL
AND SF.CONTROLE_FOLHA IN('L','M','N')
AND PN.tipo_situacao IN ('P','I')
--AND PN.DATA_EXTINCAO IS NULL
and pn.c_livre_valor01='1'
---PN.usa_apuracao='S'
AND trunc(PN.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM)X1
GROUP BY X1.CODIGO_EMPRESA,X1.DESCRICAO,X1.NRO,X1.CODIGO_LEGADO,X1.VISUALIZAR_NO_SUBMENU,X1.PERIODO,X1.QTD_LIMITE,X1.EMPRESA,X1.AGRUPAMENTO_EMPRESA,x1.data_extincao,X1.APENAS_ADMIN, X1.TIPO_REFERENCIA
ORDER BY X1.CODIGO_EMPRESA,X1.DESCRICAO,X1.NRO,X1.CODIGO_LEGADO,X1.VISUALIZAR_NO_SUBMENU,X1.PERIODO,X1.QTD_LIMITE,X1.EMPRESA,X1.AGRUPAMENTO_EMPRESA,x1.data_extincao,X1.APENAS_ADMIN, X1.TIPO_REFERENCIA
)SIT_FUN
UNION ALL
SELECT PONT.* FROM (SELECT X2.* FROM (SELECT '0001' AS CODIGO_EMPRESA,
'PREF.MUN.BELO HORIZONTE'AS EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
PN.DESCRICAO,
PN.CODIGO AS NRO,
PN.CODIGO AS CODIGO_LEGADO,
CASE WHEN PN.c_livre_selec01='1'THEN'01'----espelho
WHEN PN.c_livre_selec01='2' THEN '02'---lancamento de ocorrencia
WHEN PN.c_livre_selec01='3' THEN'03'---- BANCO DE HORAS
WHEN PN.c_livre_selec01='4' THEN '04' ----TODOS
WHEN PN.c_livre_selec01='9'THEN 'TOTALIZADOR_IFPONTO' ELSE 'ERRO'END AS  VISUALIZAR_NO_SUBMENU,
CASE
        WHEN PN.c_livre_selec02 = 1
        THEN 'Semanal'
        WHEN PN.c_livre_selec02 = 2
        THEN 'Mensal'
        WHEN PN.c_livre_selec02 = 3
        THEN 'Anual'
        WHEN PN.c_livre_selec02 = 9
        THEN 'Ilimitda'
        ELSE 'ERRO'
      END periodo,
      c_livre_selec03 QTD_LIMITE,
      pn.data_extincao
,CASE WHEN PN.c_livre_opcao01 = 'S' THEN 0 WHEN PN.c_livre_opcao01 = 'N' THEN 1 END APENAS_ADMIN
,PN.TIPO_REFERENCIA --NOVO EM 22/11/23 EMAIL (Customização - LICENÇA PARCIAL)
FROM  ARTERH.RHPONT_SITUACAO PN
WHERE
--PN.DATA_EXTINCAO IS NULL
 PN.tipo_situacao IN ('P','I','N')
AND PN.CODIGO NOT IN (SELECT AUX.SITUACAO_PONTO FROM ARTERH.RHPARM_SIT_FUNC AUX WHERE AUX.SITUACAO_PONTO=PN.CODIGO)
AND PN.CODIGO NOT IN (SELECT FR.situacao_ponto FROM ARTERH.RHPARM_P_FERI FR WHERE FR.situacao_ponto=PN.CODIGO)
and  pn.c_livre_valor01='1'
---PN.usa_apuracao='S'
AND trunc(PN.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM
)X2
GROUP BY X2.CODIGO_EMPRESA,X2.DESCRICAO,X2.NRO,X2.CODIGO_LEGADO,X2.VISUALIZAR_NO_SUBMENU,X2.PERIODO,X2.QTD_LIMITE,X2.EMPRESA,X2.AGRUPAMENTO_EMPRESA,X2.data_extincao,X2.APENAS_ADMIN, X2.TIPO_REFERENCIA
ORDER BY X2.CODIGO_EMPRESA,X2.DESCRICAO,X2.NRO,X2.CODIGO_LEGADO,X2.VISUALIZAR_NO_SUBMENU,X2.PERIODO,X2.QTD_LIMITE,X2.EMPRESA,X2.AGRUPAMENTO_EMPRESA,X2.data_extincao,X2.APENAS_ADMIN, X2.TIPO_REFERENCIA
)PONT
UNION ALL
SELECT FERI.*FROM (SELECT X3.* FROM (SELECT '0001' AS CODIGO_EMPRESA,
'PREF.MUN.BELO HORIZONTE'AS EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
PN.DESCRICAO,
PN.CODIGO AS NRO,
PN.CODIGO AS CODIGO_LEGADO,
CASE WHEN PN.c_livre_selec01='1'THEN'01'----espelho
WHEN PN.c_livre_selec01='2'THEN '02'---lancamento de ocorrencia
WHEN PN.c_livre_selec01='3' THEN'03'---- BANCO DE HORAS
WHEN PN.c_livre_selec01='4' THEN '04' ----TODOS
WHEN PN.c_livre_selec01='9'THEN 'TOTALIZADOR_IFPONTO' ELSE 'ERRO'END AS  VISUALIZAR_NO_SUBMENU,
CASE
        WHEN PN.c_livre_selec02 = 1
        THEN 'Semanal'
        WHEN PN.c_livre_selec02 = 2
        THEN 'Mensal'
        WHEN PN.c_livre_selec02 = 3
        THEN 'Anual'
        WHEN PN.c_livre_selec02 = 9
        THEN 'Ilimitda'
        ELSE 'ERRO'
      END periodo,
      c_livre_selec03 QTD_LIMITE,
      PN.data_extincao
,CASE WHEN PN.c_livre_opcao01 = 'S' THEN 0 WHEN PN.c_livre_opcao01 = 'N' THEN 1 END APENAS_ADMIN
,PN.TIPO_REFERENCIA --NOVO EM 22/11/23 EMAIL (Customização - LICENÇA PARCIAL)
      FROM ARTERH.RHPARM_P_FERI FR
LEFT OUTER JOIN ARTERH.RHPONT_SITUACAO PN
ON FR.situacao_ponto=PN.CODIGO
WHERE 

--PN.DATA_EXTINCAO IS NULL
 PN.TIPO_SITUACAO IN ('P','I')
and pn.c_livre_valor01='1'
---PN.usa_apuracao='S'
AND trunc(PN.DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM)X3
GROUP BY X3.CODIGO_EMPRESA,X3.DESCRICAO,X3.NRO,X3.CODIGO_LEGADO,X3.VISUALIZAR_NO_SUBMENU,X3.PERIODO,X3.QTD_LIMITE,X3.EMPRESA,X3.AGRUPAMENTO_EMPRESA,X3.data_extincao,X3.APENAS_ADMIN, X3.TIPO_REFERENCIA
ORDER BY X3.CODIGO_EMPRESA,X3.DESCRICAO,X3.NRO,X3.CODIGO_LEGADO,X3.VISUALIZAR_NO_SUBMENU,X3.PERIODO,X3.QTD_LIMITE,X3.EMPRESA,X3.AGRUPAMENTO_EMPRESA,X3.data_extincao,X3.APENAS_ADMIN, X3.TIPO_REFERENCIA
)FERI
)TUDO
GROUP BY TUDO.CODIGO_EMPRESA,TUDO.DESCRICAO,TUDO.NRO,TUDO.CODIGO_LEGADO,TUDO.VISUALIZAR_NO_SUBMENU,TUDO.PERIODO,TUDO.QTD_LIMITE,TUDO.EMPRESA,TUDO.AGRUPAMENTO_EMPRESA,TUDO.data_extincao,TUDO.APENAS_ADMIN, TUDO.TIPO_REFERENCIA
ORDER BY TUDO.CODIGO_EMPRESA,TUDO.DESCRICAO,TUDO.NRO,TUDO.CODIGO_LEGADO,TUDO.VISUALIZAR_NO_SUBMENU,TUDO.PERIODO,TUDO.QTD_LIMITE,TUDO.EMPRESA,TUDO.AGRUPAMENTO_EMPRESA,TUDO.data_extincao,TUDO.APENAS_ADMIN, TUDO.TIPO_REFERENCIA
)XXX
)X WHERE X.CODIGO_LEGADO NOT IN ('1192','1191','1190','1189')
AND X.VISUALIZAR_NO_SUBMENU IN ('01','02','04')--NOVO EM 28/4/23 -- PARA RESTRINGIR MAIS CADASTRO NO IFPONTO E NAO MANDAR MAIS OS TOTALIZADORES E DEMAIS--
)
LOOP
INSERT INTO PONTO_ELETRONICO.SMARH_INT_PE_JUSTIFICATIVA_IF
(CODIGO_EMPRESA,EMPRESA,AGRUPAMENTO_EMPRESA,DESCRICAO,NRO,CODIGO_LEGADO,VISUALIZAR_NO_SUBMENU,PERIODO,QTD_LIMITE,data_extincao,DT_SAIU_ARTE,DT_ENVIADO_IFPONTO_SURICATO
,CODIGO_INTEGRA_ARTE --NOVO 4/7/22
,APENAS_ADMIN
,TIPO_REFERENCIA--NOVO EM 22/11/23 EMAIL (Customização - LICENÇA PARCIAL)
)
VALUES
(C1.CODIGO_EMPRESA,C1.EMPRESA,C1.AGRUPAMENTO_EMPRESA,C1.DESCRICAO,C1.NRO,C1.CODIGO_LEGADO,C1.VISUALIZAR_NO_SUBMENU,C1.PERIODO,C1.QTD_LIMITE,C1.data_extincao,C1.DT_SAIU_ARTE,C1.DT_ENVIADO_IFPONTO_SURICATO
,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
,C1.APENAS_ADMIN
,C1.TIPO_REFERENCIA--NOVO EM 22/11/23 EMAIL (Customização - LICENÇA PARCIAL)
);
COMMIT;
END LOOP;
END;
END;
