
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_CAD_ESCALA" (DATA_INICIO IN VARCHAR2,DATA_FIM    IN VARCHAR2)
AS
BEGIN
  DECLARE
    vCONTADOR    NUMBER;
    vDATA_INICIO VARCHAR2(10);
    vDATA_FIM    VARCHAR2(10);
  BEGIN
    dbms_output.enable(NULL);
    vCONTADOR    :=0;
    vDATA_INICIO := DATA_INICIO;
    vDATA_FIM    := DATA_FIM;

    FOR C1 IN (
SELECT X.* FROM (
SELECT  E.CODIGO_EMPRESA,
    SUBSTR(E.CODIGO_EMPRESA,3,2)||LPAD(E.CODIGO,4,0) AS CODIGO,
    E.DESCRICAO AS NOME,
    E.DESCRICAO AS DESCRICAO,
     CASE WHEN E.TIPO_ESCALA = '1'THEN 'Semanal'
          WHEN E.TIPO_ESCALA = '2'THEN 'Cíclica'
          WHEN E.TIPO_ESCALA = '3'THEN 'Ciclo semanal'
          ELSE 'Não Informado'
          END AS TIPO,
     CASE WHEN H.per_hor_flexivel = 'S'THEN 0
          ELSE NULL
          END AS FLEXIBILIDADE_ENTRADA,
    CASE WHEN H.per_hor_flexivel = 'S'THEN 0
          ELSE NULL
          END AS FLEXIBILIDADE_SAIDA,
    CASE WHEN E.C_LIVRE_SELEC2 = '1'THEN 'Diária'
         WHEN E.C_LIVRE_SELEC2 = '2'THEN 'Semanal'
         WHEN E.C_LIVRE_SELEC2 = '3'THEN 'Mensal'
         ELSE 'Não Informado'
        END AS CARGA_HORARIA,
    TO_DATE (E.DT_ULT_ALTER_USUA,'DD/MM/RR')AS DTULTIMA_ALTERACAO,
    E.DT_ULT_ALTER_USUA,
    E.turno_fer_g_trab AS FALTA_FERIADO,
    e.turno_extra_fer AS PONTO_FACULTATIVO,
    SYSDATE AS DT_SAIU_ARTE,
    E.DATA_EXTINCAO,
    CASE WHEN E.data_extincao IS NULL THEN 'INCLUIR' ELSE 'EXCLUIR' END AS ACAO,
    REGEXP_REPLACE(Rpad(REPLACE(TO_CHAR(trim( tp.c_livre_selec01/60)),',',''),4,'0'), '([0-9]{2})([0-9]{2})', '\1:\2')   AS carga_semanal
    FROM
ARTERH.RHPONT_ESCALA E
LEFT OUTER JOIN ARTERH.RHPONT_RL_ESC_HOR HE
ON E.CODIGO=HE.CODIGO_ESCALA
AND E.CODIGO_EMPRESA=HE.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHPONT_HORARIO H
ON H.CODIGO=HE.CODIGO_HORARIO
AND H.CODIGO_EMPRESA=HE.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHORGA_EMPRESA EMP
ON EMP.CODIGO=E.CODIGO_EMPRESA
LEFT OUTER JOIN ARTERH.RHPONT_TP_JORNADA TP
ON TP.CODIGO=e.tipo_jornada
WHERE EMP.c_livre_selec02=1
AND (E.TIPO_ESCALA    IS NOT NULL AND E.TIPO_ESCALA     IN ('1','2','3'))
AND (E.c_livre_selec2 IS NOT NULL AND E.c_livre_selec2  IN ('1','2','3'))
AND (E.c_livre_selec3 IS NOT NULL AND E.c_livre_selec3   = '1')
AND (
(TRUNC(E.DT_ULT_ALTER_USUA) BETWEEN  vDATA_INICIO AND vDATA_FIM )
OR
EXISTS
( SELECT AUX.* FROM ARTERH.RHPONT_RL_ESC_HOR AUX
WHERE AUX.CODIGO_EMPRESA = he.CODIGO_EMPRESA
AND AUX.CODIGO_ESCALA = he.CODIGO_ESCALA
AND (TRUNC(AUX.DT_ULT_ALTER_USUA) BETWEEN  vDATA_INICIO AND vDATA_FIM)
)
/* OR  
(TRUNC(H.DT_ULT_ALTER_USUA) BETWEEN  vDATA_INICIO AND vDATA_FIM )  */  --Retirado em 08/03/24
)
--AND H.TIPO_HORARIO IN ('N','T') --Retirado em 08/03/24
)X
GROUP BY X.CODIGO_EMPRESA,X.CODIGO,X.NOME,X.DESCRICAO,X.TIPO,X.FLEXIBILIDADE_ENTRADA,X.FLEXIBILIDADE_SAIDA,X.CARGA_HORARIA,X.DTULTIMA_ALTERACAO,
X.DT_ULT_ALTER_USUA,X.FALTA_FERIADO,X.PONTO_FACULTATIVO,X.DT_SAIU_ARTE,X.DATA_EXTINCAO,X.ACAO,X.carga_semanal)
LOOP
      vCONTADOR :=vCONTADOR+1;
      dbms_output.put_line(vCONTADOR);
      dbms_output.put_line(vDATA_INICIO||'-'||vDATA_FIM);
      INSERT
      INTO PONTO_ELETRONICO.SMARH_INT_PE_ESCALA_V2
        (
          CODIGO_EMPRESA,
          CODIGO,
          NOME,
          DESCRICAO,
          TIPO,
          CARGA_HORARIA,
          FLEXIBILIDADE_ENTRADA,
          FLEXIBILIDADE_SAIDA,
          DTULTIMA_ALTERACAO,
          DT_SAIU_ARTE,
          FALTA_FERIADO,
          PONTO_FACULTATIVO,
          DT_ULT_ALTER_USUA,
          ACAO,
          DATA_EXTINCAO,
          carga_semanal
          ,CODIGO_INTEGRA_ARTE
        )
        VALUES
        (
          C1.CODIGO_EMPRESA,
          C1.CODIGO,
          C1.NOME,
          C1.DESCRICAO,
          C1.TIPO,
          C1.CARGA_HORARIA,
          C1.FLEXIBILIDADE_ENTRADA,
          C1.FLEXIBILIDADE_SAIDA,
          C1.DTULTIMA_ALTERACAO,
          C1.DT_SAIU_ARTE,
          C1.FALTA_FERIADO,
          C1.PONTO_FACULTATIVO,
          C1.DT_ULT_ALTER_USUA,
          C1.ACAO,
          C1.DATA_EXTINCAO,
          C1.carga_semanal
          ,PONTO_ELETRONICO.SEQUENCE_INTEGRA_ARTE.NEXTVAL 
        );
      COMMIT;
      END LOOP;
END;
END;