
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."SMARH_USER_P_SIST_A" (
VCODIGO_USUARIO IN VARCHAR, VEMPRESA_SELEC IN VARCHAR,VTIPO_CONTR_SELEC IN VARCHAR,VSTATUS_USUARIO IN CHAR , VCODIGO_SGBD_PADRAO IN VARCHAR ) AS 
BEGIN

  -- REATIVAR USUÁRIOS QUE POSSUEM ACESSO APENAS AO PORTAL DO SERVIDOR 
          IF ( VSTATUS_USUARIO = 'E' AND VCODIGO_SGBD_PADRAO IS NULL ) THEN

              UPDATE RHUSER_P_SIST SET STATUS_USUARIO = 'A',USUARIO_LDAP = CODIGO_USUARIO, LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND EXISTS ( SELECT distinct U.CODIGO_USUARIO FROM RHUSER_P_SIST u, RHUSER_RL_USR_GRP grp, rhpess_contrato c, rhparm_sit_func sf 
              WHERE grp.codigo_usuario = u.codigo_usuario 
              AND u.codigo_serv_autent = 'PWS1'  
              AND U.STATUS_USUARIO     = 'E'  
              AND u.LOGIN_USUARIO     IN ('EXCLUSAO_AUTOMATICA','Exclusão automatica','INTEGRACAO_IFPONTO')  
              AND grp.CODIGO_GRUPO    <> '0070' 
              and not exists ( select sgbd.codigo_usuario from RHUSER_USR_SGBD sgbd where sgbd.codigo_usuario = u.codigo_usuario)
              AND c.codigo = u.CONTRATO_USUARIO  
              AND c.TIPO_CONTRATO      = u.TP_CONTR_USUARIO  
              AND c.codigo_empresa     = u.EMPRESA_USUARIO  
              AND c.ANO_MES_REFERENCIA = (SELECT MAX (a.ano_mes_referencia) FROM rhpess_contrato a WHERE a.codigo = c.codigo AND a.codigo_empresa = c.codigo_empresa AND a.tipo_contrato  = c.tipo_contrato )  
              AND sf.codigo          = c.situacao_funcional  
              AND u.codigo_usuario = U.USUARIO_LDAP
              AND sf.CONTROLE_FOLHA <> 'D'  
              and ( to_char(C.DATA_RESCISAO,'yyyy') >= to_char(sysdate,'yyyy')-1  or c.DATA_RESCISAO is null )
              AND u.codigo_usuario = VCODIGO_USUARIO  ); 

          END IF;

        IF ( VSTATUS_USUARIO = 'A' ) THEN
          -- CORRIGIR A EMPRESA_SELEC DO CADASTRO DO USUÁRIO
              UPDATE RHUSER_P_SIST SET EMPRESA_SELEC = ( SELECT CODIGO_EMPRESA FROM RHUSER_RL_USR_EMP WHERE CODIGO_USUARIO = VCODIGO_USUARIO AND ROWNUM = 1 ),LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND NOT EXISTS ( SELECT CODIGO_EMPRESA FROM RHUSER_RL_USR_EMP WHERE CODIGO_EMPRESA IN ( VEMPRESA_SELEC )  AND CODIGO_USUARIO = VCODIGO_USUARIO  )
              AND EXISTS ( SELECT CODIGO_EMPRESA FROM RHUSER_RL_USR_EMP WHERE CODIGO_USUARIO = VCODIGO_USUARIO AND ROWNUM = 1 );

          -- CORRIGIR O TIPO_CONTR_SELEC DO CADASTRO DO USUÁRIO
              UPDATE RHUSER_P_SIST SET TIPO_CONTR_SELEC = ( SELECT TIPO_CONTRATO FROM RHUSER_USR_TPCONT WHERE CODIGO_USUARIO = VCODIGO_USUARIO AND ROWNUM = 1 ), LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND NOT EXISTS ( SELECT TIPO_CONTRATO FROM RHUSER_USR_TPCONT WHERE TIPO_CONTRATO IN ( VTIPO_CONTR_SELEC )  AND CODIGO_USUARIO = VCODIGO_USUARIO  )
              AND EXISTS ( SELECT TIPO_CONTRATO FROM RHUSER_USR_TPCONT WHERE CODIGO_USUARIO = VCODIGO_USUARIO AND ROWNUM = 1 );

         -- CORRIGE O CODIGO_GRUPO DO USUARIO
              UPDATE RHUSER_P_SIST SET codigo_grupo = ( select * from ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO order by 1 ) where rownum = 1  ), LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND codigo_grupo not in ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO  )
              and EXISTS ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO   );

         -- CORRIGE O GRUPO_SEGURANÇA DO USUARIO      
              UPDATE RHUSER_P_SIST SET grupo_seguranca = ( select * from ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO order by 1 ) where rownum = 1  ),
              LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND grupo_seguranca not in ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO )
              and EXISTS ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO   );

        -- CORRIGE O ULTIMO_PERFIL_ACESSO_AZC DO USUARIO  
              UPDATE RHUSER_P_SIST SET ULTIMO_PERFIL_ACESSO_AZC = ( select * from ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO order by 1 ) where rownum = 1 ),
              LOGIN_USUARIO = 'TR_RHUSER_P_SIST', DT_ULT_ALTER_USUA = SYSDATE 
              WHERE CODIGO_USUARIO = VCODIGO_USUARIO
              AND ULTIMO_PERFIL_ACESSO_AZC not in ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO )
              and EXISTS ( SELECT codigo_grupo FROM RHUSER_RL_USR_GRP WHERE CODIGO_USUARIO = VCODIGO_USUARIO   );

          END IF;  
END SMARH_USER_P_SIST_A;