
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PONTO_ELETRONICO"."SMARH_INT_PE_CAD_CARGO_FUNCAO" (DATA_INICIO IN VARCHAR2, DATA_FIM IN VARCHAR2)
AS
BEGIN
DECLARE
vCONTADOR NUMBER;
vDATA_INICIO Varchar2(10);
vDATA_FIM Varchar2(10);
BEGIN
dbms_output.enable(null);
vCONTADOR :=0;
vDATA_INICIO := DATA_INICIO;
vDATA_FIM := DATA_FIM;
FOR C1 IN
(
SELECT CODIGO_EMPRESA,
CASE WHEN CODIGO_EMPRESA = '0001' THEN 'PREF.MUN.BELO HORIZONTE' WHEN CODIGO_EMPRESA = '0098' THEN 'PREF.MUN.BH CONTRATOS' END AS EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
SUBSTR(CODIGO_EMPRESA,3,2)||SUBSTR(CODIGO,11,5)AS CODIGO,
DESCRICAO,
NULL AS ISENTO_MARCACAO_FREQUENCIA,
NULL AS UTILIZA_BANCO_HORAS,
DATA_IMPLAN_CARGO,
DATA_EXTINC_CARGO,
C_LIVRE_DESCR08 AS DESCRICAO_ALTERNATIVA,
SYSDATE AS DT_SAIU_ARTE ,
NULL AS DT_ENVIADO_IFPONTO_SURICATO
FROM RHPLCS_CARGO
WHERE CODIGO_EMPRESA=(SELECT PONT.* 
                                             FROM 
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA 
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
AND trunc(DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UNION ALL
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT
CODIGO_EMPRESA,
CASE WHEN CODIGO_EMPRESA = '0001' THEN 'PREF.MUN.BELO HORIZONTE' WHEN CODIGO_EMPRESA = '0098' THEN 'PREF.MUN.BH CONTRATOS' END AS EMPRESA,
'ADM DIRETA' AS AGRUPAMENTO_EMPRESA,
SUBSTR(CODIGO_EMPRESA,3,2)||9 || SUBSTR(CODIGO,12,4) AS CODIGO,--NOVA REGRA 1: Kellysson 15/9/17 - Devido a nova estrutura da reforma tive que incorporar as FUNÇÕES (FCAs) do Arterh para compor os cargos, sendo assim para não ocorrer duplicidade no cadastro mascarei nas integrações o código da função com um 9 no primeiro digito, assim ficara dentro do Ifponto como o exemplo: Arterh = 2040-FCA 1, Ifponto = 92040-FCA 1.
DESCRICAO,
NULL AS ISENTO_MARCACAO_FREQUENCIA,
NULL AS UTILIZA_BANCO_HORAS,
DATA_IMPLANT AS DATA_IMPLAN_CARGO,
DATA_EXTINCAO AS DATA_EXTINC_CARGO,
substr(texto_associado,1,200) AS DESCRICAO_ALTERNATIVA,
SYSDATE AS DT_SAIU_ARTE ,
NULL AS DT_ENVIADO_IFPONTO_SURICATO
FROM RHPLCS_FUNCAO
WHERE CODIGO_EMPRESA=(SELECT PONT.* 
                                             FROM 
                                             (SELECT SUBSTR(PONT.DADO_ORIGEM,20,4)EMPRESA 
                                             FROM RHINTE_ED_IT_CONV PONT WHERE CODIGO_CONVERSAO='PONT' GROUP BY SUBSTR(PONT.DADO_ORIGEM,20,4))PONT
                                             WHERE PONT.EMPRESA=CODIGO_EMPRESA)
AND trunc(DT_ULT_ALTER_USUA) BETWEEN vDATA_INICIO AND vDATA_FIM
)---FIM DO FOR
LOOP
vCONTADOR :=vCONTADOR+1;
dbms_output.put_line(vCONTADOR);
dbms_output.put_line(vDATA_INICIO||'-'||vDATA_FIM);
dbms_output.put_line (C1.CODIGO);

insert into PONTO_ELETRONICO.SMARH_INT_PE_CARGO_V2 (CODIGO_EMPRESA, EMPRESA, AGRUPAMENTO_EMPRESA, CODIGO, DESCRICAO, ISENTO_MARCACAO_FREQUENCIA, UTILIZA_BANCO_HORAS, DATA_IMPLAN_CARGO, DATA_EXTINC_CARGO,
DESCRICAO_ALTERNATIVA, DT_SAIU_ARTE, DT_ENVIADO_IFPONTO_SURICATO
,CODIGO_INTEGRA_ARTE)--NOVO 4/7/22
VALUES (C1.CODIGO_EMPRESA, C1.EMPRESA, C1.AGRUPAMENTO_EMPRESA, C1.CODIGO, C1.DESCRICAO, C1.ISENTO_MARCACAO_FREQUENCIA, C1.UTILIZA_BANCO_HORAS,
C1.DATA_IMPLAN_CARGO, C1.DATA_EXTINC_CARGO, C1.DESCRICAO_ALTERNATIVA, C1.DT_SAIU_ARTE, C1.DT_ENVIADO_IFPONTO_SURICATO
,SEQUENCE_INTEGRA_ARTE.NEXTVAL --NOVO 4/7/22
);
Commit;

END LOOP;

END;

END SMARH_INT_PE_CAD_CARGO_FUNCAO;

