
  CREATE OR REPLACE EDITIONABLE PROCEDURE "ARTERH"."TESTE_MARCOS" (
  DIAS_ANOS_REF IN NUMBER,
  DIAS_MES_REF  IN NUMBER,
  DATA_INICIO   IN DATE,
  DATA_FIM      IN DATE
) AS
  NRO_MESES_LOOP NUMBER := 0;
  NRO_DIAS       NUMBER := 0;
  NRO_MESES      NUMBER := 0;
  MES_INI        NUMBER := 0;
  NRO_DIAS_FINAL NUMBER := 0;
  NRO_ANOS       NUMBER := 0;
  NRO_DIAS_LIQUI NUMBER := 0;
  RET            TP_VALOR_DIAS;
  DT_FIM         DATE;
  DATA_NOVA DATE;
  DATA_NOVA_1 DATE;
  QTD_MESES NUMBER;
BEGIN

/*
CENÁRIOS AVALIADOS

--19 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('12/02/2003','DD/MM/YYYY') ,TO_DATE('28/02/2003','DD/MM/YYYY'));

--4 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('28/02/2003','DD/MM/YYYY') ,TO_DATE('01/03/2003','DD/MM/YYYY'));
--3DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('29/02/2024','DD/MM/YYYY') ,TO_DATE('01/03/2024','DD/MM/YYYY'));
--30 DIA
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/02/2024','DD/MM/YYYY') ,TO_DATE('29/02/2024','DD/MM/YYYY'));
--9 M 13 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('10/05/2003','DD/MM/YYYY') ,TO_DATE('22/02/2004','DD/MM/YYYY'));

--9 MESES E 20 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('11/05/2023','DD/MM/YYYY') ,TO_DATE('29/02/2024','DD/MM/YYYY'));
--9 MESES E 20 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('11/05/2022','DD/MM/YYYY') ,TO_DATE('28/02/2023','DD/MM/YYYY'));
--30 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/03/2022','DD/MM/YYYY') ,TO_DATE('31/03/2022','DD/MM/YYYY'));
--6 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('31/03/2022','DD/MM/YYYY') ,TO_DATE('05/04/2022','DD/MM/YYYY'));
--1 DIA 
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('31/03/2022','DD/MM/YYYY') ,TO_DATE('31/03/2022','DD/MM/YYYY'));

--30 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/03/2022','DD/MM/YYYY') ,TO_DATE('31/03/2022','DD/MM/YYYY'));
--2 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('28/03/2022','DD/MM/YYYY') ,TO_DATE('29/03/2022','DD/MM/YYYY'));
--1 DIA
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('28/02/2024','DD/MM/YYYY') ,TO_DATE('28/02/2024','DD/MM/YYYY'));
--1 DIA
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2024','DD/MM/YYYY') ,TO_DATE('01/01/2024','DD/MM/YYYY'));
--30 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2024','DD/MM/YYYY') ,TO_DATE('31/01/2024','DD/MM/YYYY'));

--360 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2024','DD/MM/YYYY') ,TO_DATE('31/12/2024','DD/MM/YYYY'));
--360 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2024','DD/MM/YYYY') ,TO_DATE('30/12/2024','DD/MM/YYYY'));
--359 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2024','DD/MM/YYYY') ,TO_DATE('29/12/2024','DD/MM/YYYY'));


--359 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2023','DD/MM/YYYY') ,TO_DATE('29/12/2023','DD/MM/YYYY'));

--360 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2023','DD/MM/YYYY') ,TO_DATE('30/12/2023','DD/MM/YYYY'));

--360 DIAS
EXECUTE TESTE_MARCOS  ('360','30',TO_DATE('01/01/2023','DD/MM/YYYY') ,TO_DATE('31/12/2023','DD/MM/YYYY'));




*/
  RET := TP_VALOR_DIAS(NULL, NULL, NULL, NULL);
  NRO_MESES_LOOP := ROUND(MONTHS_BETWEEN(DATA_FIM, DATA_INICIO));
  NRO_ANOS := TRUNC(EXTRACT(YEAR FROM(DATA_FIM)) - EXTRACT(YEAR FROM(DATA_INICIO)));
  DBMS_OUTPUT.ENABLE (buffer_size => NULL);
  FOR C1 IN 0..NRO_MESES_LOOP LOOP
 dbms_output.put_line(c1||'NRO_MESES_LOOP: '||NRO_MESES_LOOP);
    IF
      DIAS_MES_REF = 31 AND C1 > 0 AND C1 < NRO_MESES_LOOP
    THEN
      DBMS_OUTPUT.PUT_LINE('0 --> '||DT_FIM );
      NRO_DIAS := NRO_DIAS + ( TRUNC(LAST_DAY(ADD_MONTHS(DATA_INICIO, C1)) - TRUNC(ADD_MONTHS(DATA_INICIO, C1), 'MM')) + 1 );
    END IF;
    
    IF C1 = 0 THEN 
---dbms_output.put_line(TO_CHAR(last_day(add_months(DATA_INICIO,C1)),'DD') ||' '||DIAS_MES_REF);
      IF
       --                                  31                >     30       '29/07/1990' > '01/10/1989'
        TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO, C1)), 'DD') > DIAS_MES_REF AND DATA_FIM > LAST_DAY(DATA_INICIO)
      THEN 
---dbms_output.put_line(last_day(add_months(DATA_INICIO,C1))-1);
       DT_FIM := LAST_DAY(ADD_MONTHS(DATA_INICIO, C1)) - 1;
      ELSIF
        TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO, C1)), 'DD') <= DIAS_MES_REF AND DATA_FIM > LAST_DAY(DATA_INICIO)
      THEN DT_FIM := LAST_DAY(ADD_MONTHS(DATA_INICIO, C1));
      ELSE DT_FIM := DATA_FIM;
      END IF;
      
      -- IF TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD/MM/YYYY') = TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD/MM/YYYY')
      --THEN 
      --NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1);
      --DBMS_OUTPUT.PUT_LINE('NOVO IF: ' || NRO_DIAS);
      --END IF;
      
      
      IF TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'MM/YYYY') = TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'MM/YYYY') 
      THEN 
          IF  
            TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD') = '31'  
            THEN 
            NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1);
            DBMS_OUTPUT.PUT_LINE('ENTRADA 1 ' || NRO_DIAS);
            ELSIF
            TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '30' 
            THEN 
            NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1));
            DBMS_OUTPUT.PUT_LINE(' ENTRADA 2 ' || NRO_DIAS);
            ELSIF
            TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '28'   
            THEN 
            NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1) +2;
            DBMS_OUTPUT.PUT_LINE(' ENTRADA 3 ' || NRO_DIAS);
            ELSIF  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '29' 
            THEN 
            NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1) ;
            DBMS_OUTPUT.PUT_LINE('ENTRADA 4 ' || NRO_DIAS);
            ELSE
                IF  
                  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '31' AND  TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD') = '01'  
                  AND TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD') <> TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD')  
                THEN 
                  NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1));
                  DBMS_OUTPUT.PUT_LINE('ENTRADA 5 ' || NRO_DIAS);
                  ELSIF
                  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '31' AND 
                  TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD')  = TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD')  
                THEN 
                  NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1)+1);
                  DBMS_OUTPUT.PUT_LINE('ENTRADA 6 ' || NRO_DIAS);
                  ELSIF
                  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '29' AND 
                  TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD')  = TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD')  
                THEN 
                  NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1)+1);
                  DBMS_OUTPUT.PUT_LINE('ENTRADA 7 ' || NRO_DIAS);
                  ELSIF
                  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '29' AND 
                  TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD')  <> TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD')  
                THEN 
                  NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1)+1)+1;
                  DBMS_OUTPUT.PUT_LINE('ENTRADA 8 ' || NRO_DIAS);
                ELSE
                  NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1)+1);
                  DBMS_OUTPUT.PUT_LINE('ENTRADA 9 ' || NRO_DIAS);
                END IF;
            
            END IF;
   
       ELSE
       IF  
        TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'DD') = '31'  
        THEN 
        NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1) +1;
        DBMS_OUTPUT.PUT_LINE('NOVA ENTRADA 1 ' || NRO_DIAS);
        ELSIF
        TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '30' 
        THEN 
        NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1)+ 1);
        DBMS_OUTPUT.PUT_LINE('NOVA ENTRADA 2 ' || NRO_DIAS);
        ELSIF            
         TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '28'  
        THEN 
        NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1) +2;
        DBMS_OUTPUT.PUT_LINE('NOVA ENTRADA 3 ' || NRO_DIAS);
        ELSIF  TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_INICIO,  C1)), 'DD') = '29' THEN 
        NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1) +1;
        DBMS_OUTPUT.PUT_LINE('NOVA ENTRADA 4 ' || NRO_DIAS);
        ELSE
        NRO_DIAS := NRO_DIAS + TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) +1);
        DBMS_OUTPUT.PUT_LINE('NOVA ENTRADA 5 ' || NRO_DIAS);
        END IF;
      END IF;
      

   
      
      
      DBMS_OUTPUT.PUT_LINE('4 --> NRO_DIAS: ' || NRO_DIAS);
      DBMS_OUTPUT.PUT_LINE('4 --> DT_FIM: ' || DT_FIM);
      DBMS_OUTPUT.PUT_LINE('4 --> DATA_FIM: ' || DATA_FIM);
      DBMS_OUTPUT.PUT_LINE('4 --> DATA_INICIO: ' || DATA_INICIO);
      DBMS_OUTPUT.PUT_LINE('4 --> C1: ' || C1);
     
    
      
     
     
      
     
      
      DBMS_OUTPUT.PUT_LINE('PRIMEIRO MES DO LOOP: ' ||NRO_DIAS);
     -- DBMS_OUTPUT.PUT_LINE('PRIMEIRO MES DO LOOP: ' ||(TRUNC(DT_FIM - ADD_MONTHS(DATA_INICIO, C1) + 1)));
      DBMS_OUTPUT.PUT_LINE('4 --> NRO_DIAS: ' || NRO_DIAS || ' --> N MESES LOOP'||NRO_MESES_LOOP);
    ELSIF C1 = NRO_MESES_LOOP THEN
     
      
      IF DT_FIM <> DATA_FIM THEN 
      IF                 
         TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD') =  '28'  
        THEN 
         NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 ) ) ) + 2;
        DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 1 ' || NRO_DIAS);
        ELSIF  TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD') = '29' AND TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_FIM,  C1)), 'DD')='31'
        AND  TO_CHAR(EXTRACT(MONTH FROM(DATA_FIM))) <> 2
        THEN 
         NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 ) ) );
        DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 2 ' || NRO_DIAS);
         ELSIF  TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD') = '29' AND TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_FIM,  C1)), 'DD')='31'
        AND  TO_CHAR(EXTRACT(MONTH FROM(DATA_FIM))) = 2
        THEN 
         NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 ) ) )+1;
        DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 3 ' || NRO_DIAS);
        ELSIF  TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD') = '29' AND TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_FIM,  C1)), 'DD')='29'
        THEN 
         NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM'))+1 ) ) +1 ) ;
        DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 4 ' || NRO_DIAS);
        ELSE
          IF TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD') ='31' 
          THEN
          DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 5 DATA FIM' || TO_CHAR(LAST_DAY(ADD_MONTHS(DATA_FIM,  C1)), 'DD'));
          NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) ) ) );
          DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 6 ' || NRO_DIAS);
           ELSIF TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'DD')='30' 
          THEN
          
          NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) +1) ) );
          DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 7 ' || NRO_DIAS);
          ELSE
          
          NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 ) ) );
          DBMS_OUTPUT.PUT_LINE('ULTIMA ENTRADA 7 ' || NRO_DIAS);
          END IF;
          
        END IF;
        DBMS_OUTPUT.PUT_LINE('VALOR_DATA_FIM '|| DT_FIM || 'DATA_FIM_SIS'|| DATA_FIM);
     -- DBMS_OUTPUT.PUT_LINE(DATA_FIM);
      DBMS_OUTPUT.PUT_LINE('ULTIMO MES DO LOOP: ' || (  ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 )  ));
      DBMS_OUTPUT.PUT_LINE('5 --> DATA_FIM: '|| DATA_FIM);
      DBMS_OUTPUT.PUT_LINE('5 --> NRO_DIAS: ' || NRO_DIAS);
       DBMS_OUTPUT.PUT_LINE('6 --> ' || DATA_FIM ||'-'|| DT_FIM);
       DBMS_OUTPUT.PUT_LINE('6 --> ' || NRO_DIAS);
       
      END IF;
    END IF;
---    DBMS_OUTPUT.PUT_LINE('1   --' || NRO_DIAS);



        IF
        DIAS_MES_REF = 30 AND NRO_MESES_LOOP = 0 AND (TO_CHAR(TO_DATE(DATA_INICIO,'DD/MM/YYYY'), 'MM/YYYY') <> TO_CHAR(TO_DATE(DATA_FIM,'DD/MM/YYYY'), 'MM/YYYY'))
        THEN 
        dbms_output.put_line(TRUNC(add_months(DATA_INICIO,C1),'MM')||' ----'||last_day(add_months(DATA_INICIO,C1)));
        Dbms_output.put_line((trunc(last_day(add_months(DATA_INICIO,C1))-TRUNC(add_months(DATA_INICIO,C1),'MM'))+1));
        NRO_DIAS := ( NRO_DIAS + ( ( TRUNC(DATA_FIM - TRUNC(DATA_FIM, 'MM')) + 1 ) ) );
        END IF;


  END LOOP;
--dbms_output.put_line(TRUNC(add_months(DATA_INICIO,1),'MM'));
---dbms_output.put_line(LAST_DAY(add_months(DATA_FIM,-1)));
---dbms_output.put_line((ROUND(MONTHS_BETWEEN(LAST_DAY(add_months(DATA_FIM,-1)),TRUNC(add_months(DATA_INICIO,1),'MM')))*DIAS_MES_REF));
---dbms_output.put_line('2   --'||NRO_DIAS);
---dbms_output.put_line(((ROUND(MONTHS_BETWEEN(add_months(DATA_FIM,-1),add_months(DATA_INICIO,1)))*DIAS_MES_REF)));
  IF
    DIAS_MES_REF != 31 AND DATA_FIM > LAST_DAY(DATA_INICIO)
  THEN NRO_DIAS := NRO_DIAS + ( ROUND(MONTHS_BETWEEN(LAST_DAY(ADD_MONTHS(DATA_FIM, -1)), TRUNC(ADD_MONTHS(DATA_INICIO, 1), 'MM'))) * DIAS_MES_REF );
     DBMS_OUTPUT.PUT_LINE('7 --> ' || NRO_DIAS);
  END IF;
  NRO_DIAS_LIQUI := NRO_DIAS;
  dbms_output.put_line('saida 1 --> NRO_DIAS_LIQUI: '|| NRO_DIAS);
  NRO_DIAS := MOD(NRO_DIAS,DIAS_ANOS_REF); --71
  dbms_output.put_line('saida 2 --> NRO_DIAS: '||NRO_DIAS);
  NRO_ANOS := TRUNC(NRO_DIAS_LIQUI / DIAS_ANOS_REF); --11
  dbms_output.put_line('saida 3 --> NRO_ANOS: '||NRO_ANOS);
  NRO_MESES := TRUNC(MOD(NRO_DIAS, DIAS_ANOS_REF) / DIAS_MES_REF); --2
  dbms_output.put_line('saida 4 --> NRO_MESES: '||NRO_MESES);
   NRO_DIAS_FINAL := MOD(NRO_DIAS, DIAS_MES_REF);
    dbms_output.put_line('saida 5 --> NRO_DIAS_FINAL: '||NRO_DIAS_FINAL);
  --NRO_DIAS := MOD(NRO_DIAS, DIAS_MES_REF);
  dbms_output.put_line(NRO_ANOS||' ANOS - '||NRO_MESES||'MESES -'||NRO_DIAS_FINAL|| ' DIAS');
  RET.QTD_DIAS := NRO_DIAS_FINAL;
  RET.QTD_MESES := NRO_MESES;
  RET.QTD_ANOS := NRO_ANOS;
  RET.QTD_DIAS_LIQUIDOS := NRO_DIAS_LIQUI;
   
  
END;