
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."BUSCAR_USUARIO_ARTE" (pCODIGO_EMPRESA IN CHAR, pTIPO_CONTRATO IN CHAR, pCODIGO_CONTRATO IN VARCHAR2)RETURN VARCHAR2 AS
vUSUARIO VARCHAR2(15):=NULL;
BEGIN 

/*SELECT codigo_usuario INTO vUSUARIO FROM rhuser_p_sist
WHERE EMPRESA_USUARIO=pCODIGO_EMPRESA
AND tp_contr_usuario=pTIPO_CONTRATO
AND CONTRATO_USUARIO=pCODIGO_CONTRATO
AND tipo_login = '2'
AND usuario_ldap = codigo_usuario
AND codigo_serv_autent = 'PWS1';*/
	
	SELECT codigo_usuario INTO vUSUARIO FROM rhuser_p_sist
WHERE EMPRESA_USUARIO=pCODIGO_EMPRESA
AND tp_contr_usuario=pTIPO_CONTRATO
AND CONTRATO_USUARIO=lpad(pCODIGO_CONTRATO,15,0)
AND CODIGO_USUARIO=USUARIO_LDAP 
AND  tipo_login = '1';
RETURN vUSUARIO;
END;