
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."FN_GET_CONVERSAO" (COD_CONV IN VARCHAR2, COD_SEARCH IN VARCHAR2, T_RETURN IN VARCHAR2)

RETURN VARCHAR2 

IS 
 CVARCHAR VARCHAR2(20);
 CRETORNO VARCHAR2(50);

BEGIN

IF upper(T_RETURN)='ORIGEM' THEN

for c_emp in (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV  WHERE UPPER(DADO_DESTINO) = UPPER(COD_SEARCH) AND CODIGO_CONVERSAO = UPPER(COD_CONV)) LOOP
--dbms_output.put_line('ORIGEM: ' || C_EMP.DADO_ORIGEM);
CRETORNO:=C_EMP.DADO_ORIGEM;

END LOOP;

END IF;

IF upper(T_RETURN)='DESTINO' THEN

for c_emp in (SELECT * FROM ARTERH.RHINTE_ED_IT_CONV WHERE UPPER(DADO_ORIGEM) = UPPER(COD_SEARCH) AND CODIGO_CONVERSAO = UPPER(COD_CONV)) LOOP

--dbms_output.put_line('ORIGEM:'|| COD_SEARCH||' DESTINO:' || C_EMP.DADO_DESTINO);
CRETORNO:=C_EMP.DADO_DESTINO;

END LOOP;

END IF;

--dbms_output.put_line('COD_CONV: ' || COD_CONV || ' COD_SEARCH:' || COD_SEARCH || ' RETORNO: ' || CRETORNO);
	
RETURN CRETORNO;
END;

