
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."FN_SOF_RPA_INSERT_MOVIMENTO" (
	v_CODIGO_CONTRATO IN VARCHAR,
	v_ANO_MES_REFERENCIA IN TIMESTAMP,
	v_CODIGO_VERBA IN VARCHAR,
	v_TIPO_MOVIMENTO IN VARCHAR,
	v_FASE IN VARCHAR,
	v_MODO_OPERACAO IN VARCHAR,
	v_MES_INCIDENCIA IN VARCHAR,
	v_TIPO_CONTRATO IN VARCHAR,
	v_CODIGO_EMPRESA IN VARCHAR,
	v_LOGIN_USUARIO IN VARCHAR,
	v_NOME_COLUNA_VALOR IN VARCHAR	
		)
	RETURN NUMBER
		IS total_reg NUMBER;
	 	PRAGMA AUTONOMOUS_TRANSACTION;
	BEGIN
		
		DECLARE 
		v_HEADER_SQL  VARCHAR2(32767);
		v_BODY_SQL   VARCHAR2(32767);
		v_FOOTER_SQL  VARCHAR2(32767);	
		v_ANO_REF VARCHAR2(4);
		
		BEGIN
		v_ANO_REF := EXTRACT (YEAR FROM (v_ANO_MES_REFERENCIA));
		v_HEADER_SQL :='INSERT INTO arterh.RHMOVI_MOVIMENTO (CODIGO_EMPRESA, MODO_OPERACAO, ANO_MES_REFERENCIA,TIPO_MOVIMENTO, TIPO_CONTRATO,CODIGO_CONTRATO, CODIGO_VERBA, MES_INCIDENCIA,FASE, VALOR_VERBA, CTRL_LANCAMENTO , CONTADOR,REF_VERBA,  CTRL_DEMO, LOGIN_USUARIO, DT_ULT_ALTER_USUA )';
		v_BODY_SQL:='SELECT rcm.CODIGO_EMPRESA , '''|| v_MODO_OPERACAO|| ''' "MODO_OPERACAO",''' || TRUNC(v_ANO_MES_REFERENCIA) ||''' "ANO_MES_REFERENCIA",'''|| v_TIPO_MOVIMENTO ||''' "TIPO_MOVIMENTO",'''|| v_TIPO_CONTRATO ||''' "TIPO_CONTRATO",rcm.CODIGO_CONTRATO,''' || v_CODIGO_VERBA ||''' "CODIGO_VERBA",LPAD(VW_RPA.MES_COMPETENCIA,2,0) "MES_INCIDENCIA",''0'' FASE, VW_RPA.'||v_NOME_COLUNA_VALOR || '  "VALOR_VERBA",0 CTRL_LANCAMENTO,1 CONTADOR ,0 REF_VERBA,''N'' CTRL_DEMO,''' ||v_LOGIN_USUARIO ||''' "LOGIN_USUARIO",SYSDATE "DT_ULT_ALTER_USUA"';
		v_FOOTER_SQL:=' FROM RHPESS_CONTR_MEST rcm , RHPESS_PESSOA pp, DBO.VW_ARTERH_INFORMACOES_ESOCIAL vw_rpa WHERE  rcm.CODIGO_EMPRESA  = pp.CODIGO_EMPRESA AND LPAD(vw_rpa.EMPRESA_ARTERH,4,0) = pp.CODIGO_EMPRESA AND rcm.CODIGO_PESSOA  = pp.CODIGO AND pp.cpf = VW_RPA.nro_documento_credor AND VW_RPA.ANO_COMPETENCIA =''' || v_ANO_REF || 	''' AND rcm.CODIGO_CONTRATO  = ''' || v_CODIGO_CONTRATO || 	''' AND LPAD(VW_RPA.MES_COMPETENCIA,2,0) = ''' || v_MES_INCIDENCIA || 	''' AND LPAD(vw_rpa.EMPRESA_ARTERH,4,0) = ''' || v_CODIGO_EMPRESA || '''';
		
--		DBMS_OUTPUT.PUT_LINE ('---------- DEBUG INSERT MOVIMENTO ----------------');
--		DBMS_OUTPUT.PUT_LINE (v_HEADER_SQL);
--		DBMS_OUTPUT.PUT_LINE (v_BODY_SQL);
--		DBMS_OUTPUT.PUT_LINE (v_FOOTER_SQL);
	
		 EXECUTE IMMEDIATE  v_HEADER_SQL || v_BODY_SQL || v_FOOTER_SQL;
	--EXECUTE IMMEDIATE  'select count(1) from rhpess_conrato where codigo_empresa =''0003''';
		COMMIT;
		 
		total_reg:=1;
		END;
	
		RETURN (total_reg);
	END;

--MODO ANTIGO
/*INSERT INTO RHMOVI_MOVIMENTO (CODIGO_EMPRESA, MODO_OPERACAO, ANO_MES_REFERENCIA,TIPO_MOVIMENTO, TIPO_CONTRATO,CODIGO_CONTRATO, CODIGO_VERBA, MES_INCIDENCIA,FASE, VALOR_VERBA, CTRL_LANCAMENTO , CONTADOR,REF_VERBA,  CTRL_DEMO, LOGIN_USUARIO, DT_ULT_ALTER_USUA )
			SELECT 
			rcm.CODIGO_EMPRESA , 'T' "MODO_OPERACAO",
			V_ANO_MES_REF "ANO_MES_REFERENCIA",
			'AU' "TIPO_MOVIMENTO",
			V_TIPO_CONTRATO "TIPO_CONTRATO",
			rcm.CODIGO_CONTRATO,
			'10PA' "CODIGO_VERBA",
			LPAD(VW_RPA.MES_COMPETENCIA,2,0) "MES_INCIDENCIA",
			'0' FASE, 
			VW_RPA.VALOR_BRUTO "VALOR_VERBA",
			0 CTRL_LANCAMENTO,
			1 CONTADOR ,
			0 REF_VERBA,
			'N' CTRL_DEMO,
			'INSERT_VIEW_RPA' "LOGIN_USUARIO",
			SYSDATE "DT_ULT_ALTER_USUA" 
			FROM RHPESS_CONTR_MEST rcm , RHPESS_PESSOA pp, VW_ARTERH_INFORMACOES_ESOCIAL_TEMP vw_rpa
			WHERE  rcm.CODIGO_EMPRESA  = pp.CODIGO_EMPRESA 
			AND rcm.CODIGO_PESSOA  = pp.CODIGO
			AND pp.cpf = VW_RPA.nro_documento_credor
			AND VW_RPA.ANO_COMPETENCIA =V_ANO_REF
			AND rcm.CODIGO_CONTRATO  = V_COD_CONTRATO
			AND LPAD(VW_RPA.MES_COMPETENCIA,2,0) = V_MES_REF;

			COMMIT;*/