
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."INCLUIR_VALE" (v_CODIGO_EMPRESA  CHAR, v_TIPO_CONTRATO   CHAR, v_CODIGO_CONTRATO VARCHAR2 , vLINHA VARCHAR2, vITINERARIO  VARCHAR2,vDATA_INICIO DATE,vdata_fim DATE )
    RETURN NUMBER
  IS
    DADO_VALE RHVALE_TRANSPORTE%ROWTYPE;
    vQTDE_LINHAS_AFETADAS NUMBER;
    V_OCORRENCIA          NUMBER;
    V_SEQUENCIA           NUMBER;
  BEGIN
    BEGIN
      SELECT NVL(MAX(OCORRENCIA),0)+1
      INTO V_OCORRENCIA
      FROM ARTERH.RHVALE_TRANSPORTE
      WHERE CODIGO_EMPRESA =v_CODIGO_EMPRESA
      AND TIPO_CONTRATO    =v_TIPO_CONTRATO
      AND CODIGO_CONTRATO  =v_CODIGO_CONTRATO
      AND CODIGO_ITINERARIO=vITINERARIO
      AND CODIGO_LINHA     =vLINHA ;
      SELECT NVL(MAX(VL.SEQUENCIA),0)+1 AS SEQUENCIA
      INTO V_SEQUENCIA
      FROM
        (SELECT TIPO_VALE
        FROM ARTERH.RHVALE_RL_LIN_ITIN LL
        WHERE LL.CODIGO_ITINERARIO=vITINERARIO
        AND LL.CODIGO_LINHA       =vLINHA
        ) X
      LEFT OUTER JOIN ARTERH.RHVALE_RL_LIN_ITIN L
      ON L.TIPO_VALE=X.TIPO_VALE
      LEFT OUTER JOIN ARTERH.RHVALE_TRANSPORTE VL
      ON L.CODIGO_ITINERARIO       =VL.CODIGO_ITINERARIO
      AND L.CODIGO_LINHA           = VL.CODIGO_LINHA
      WHERE VL.CODIGO_CONTRATO     =v_CODIGO_CONTRATO
      AND VL.TIPO_CONTRATO         =v_TIPO_CONTRATO
      AND VL.CODIGO_EMPRESA        =v_CODIGO_EMPRESA 
      ;
      DADO_VALE.CODIGO_EMPRESA    :=v_CODIGO_EMPRESA;
      DADO_VALE.TIPO_CONTRATO     :=v_TIPO_CONTRATO;
      DADO_VALE.CODIGO_CONTRATO   :=v_CODIGO_CONTRATO;
      DADO_VALE.CODIGO_LINHA      :=vLINHA;
      DADO_VALE.CODIGO_ITINERARIO :=vITINERARIO;
      DADO_VALE.TIPO_DIA          :='Q';
      DADO_VALE.QTDE_VALES        :='1';
      DADO_VALE.LOGIN_USUARIO     :='PR_GERA_VALE_AUTOMATICO';
      DADO_VALE.DT_ULT_ALTER_USUA :=SYSDATE;
      DADO_VALE.SEQUENCIA         :=V_SEQUENCIA;
      DADO_VALE.OCORRENCIA        :=V_OCORRENCIA;
      DADO_VALE.DATA_INI_VIGENCIA :=vDATA_INICIO;
      DADO_VALE.DATA_FIM_VIGENCIA :=vdata_fim;
      DADO_VALE.TEXTO_ASSOCIADO   :='REGISTRO CRIADO PELA ROTINA AUTOMATICA DO VALE';
      INSERT INTO RHVALE_TRANSPORTE VALUES DADO_VALE;
      vQTDE_LINHAS_AFETADAS := sql%rowcount;
      COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
      raise_application_error (-20002,'[VALIDACAO_REGRAS] - OCORREU UMA EXCECAO AO TENTAR ATUALIZAR A SITUACAO DOS REGISTROS VALIDADOS. ENTRE EM CONTATO COM A EQUIPE DE SUPORTE DA PBH.' ||'ENCONTRADO ERRO - '||SQLCODE||' -ERROR- '||SQLERRM);
    END;
    RETURN vQTDE_LINHAS_AFETADAS;
  END;
--FIM
