
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."OBETER_CONTRATO_VALE" ( pCOD_EMPRESA  CHAR, pTP_CONTRATO  CHAR,  pCPF_VERIFICA VARCHAR2)
      RETURN DADOS_RETORNO_FUN
    IS
      v_retorno DADOS_RETORNO_FUN;
      err_msg VARCHAR2(4000 BYTE);
    BEGIN
      v_retorno:=DADOS_RETORNO_FUN(NULL,NULL,NULL);
      BEGIN
        SELECT CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO
        INTO v_retorno.CODIGO_EMPRESA,
          v_retorno.TIPO_CONTRATO,
          v_retorno.CODIGO_CONTRATO
        FROM ARTERH.SMARH_INT_VALE VL
        LEFT OUTER JOIN ARTERH.SMARH_INT_DIA_EXECUCAO EX
        ON EX.ID_EXECUCAO         =VL.ID_EXECUCAO
        WHERE VL.CODIGO_EMPRESA   =pCOD_EMPRESA
        AND VL.CPF                =pCPF_VERIFICA
        AND VL.TIPO_CONTRATO      =pTP_CONTRATO
        AND VL.DATA_DESLIGAMENTO IS NULL
        AND EX.DATA_EXECUCAO      =
          (SELECT MAX(AUX.DATA_EXECUCAO) FROM ARTERH.SMARH_INT_DIA_EXECUCAO AUX
          );
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_retorno.CODIGO_EMPRESA :=NULL;
        v_retorno.TIPO_CONTRATO  :=NULL;
        v_retorno.CODIGO_CONTRATO:=NULL;
      WHEN TOO_MANY_ROWS THEN
        v_retorno.CODIGO_EMPRESA :=NULL;
        v_retorno.TIPO_CONTRATO  :=NULL;
        v_retorno.CODIGO_CONTRATO:=NULL;
        SELECT CODIGO_EMPRESA,
          TIPO_CONTRATO,
          CODIGO_CONTRATO
        INTO v_retorno.CODIGO_EMPRESA,
          v_retorno.TIPO_CONTRATO,
          v_retorno.CODIGO_CONTRATO
        FROM ARTERH.SMARH_INT_VALE VL
        LEFT OUTER JOIN ARTERH.SMARH_INT_DIA_EXECUCAO EX
        ON EX.ID_EXECUCAO         =VL.ID_EXECUCAO
        WHERE VL.CODIGO_EMPRESA   =pCOD_EMPRESA
        AND VL.CPF                =pCPF_VERIFICA
        AND VL.TIPO_CONTRATO      =pTP_CONTRATO
        AND VL.DATA_DESLIGAMENTO IS NULL
        AND EX.DATA_EXECUCAO      =
          (SELECT MAX(AUX.DATA_EXECUCAO) FROM ARTERH.SMARH_INT_DIA_EXECUCAO AUX
          )
        AND VL.CODIGO_CONTRATO=
          (SELECT MAX(CODIGO_CONTRATO)
          FROM ARTERH.SMARH_INT_VALE AUX
          LEFT OUTER JOIN ARTERH.SMARH_INT_DIA_EXECUCAO EX
          ON EX.ID_EXECUCAO          = AUX.ID_EXECUCAO
          WHERE VL.TIPO_CONTRATO     =AUX.TIPO_CONTRATO
          AND VL.CODIGO_EMPRESA      = AUX.CODIGO_EMPRESA
          AND VL.CPF                 =AUX.CPF
          AND AUX.DATA_DESLIGAMENTO IS NULL
          AND EX.DATA_EXECUCAO       =
            (SELECT MAX(AUX.DATA_EXECUCAO) FROM ARTERH.SMARH_INT_DIA_EXECUCAO AUX
            )
          );
      END;
      RETURN v_retorno;
END;