
  CREATE OR REPLACE EDITIONABLE FUNCTION "ARTERH"."VERIFICA_SEGUNDO_BM" ( pCODIGO_EMPRESA  IN CHAR , pTIPO_CONTRATO   IN CHAR, pCODIGO_CONTRATO IN VARCHAR2 )
/* FUNCTION CRIADA PARA VERIFICAR SE O CONTRATO POSSUI MAIS DE 1 BM*/
    RETURN CHAR
  AS  v_retorno CHAR(1 byte );
  BEGIN
   SELECT CASE WHEN CODIGO >= 1 THEN 'S' ELSE 'N' END AS DOIS_CONTRATOS INTO V_RETORNO
    FROM
      (SELECT COUNT(1) AS codigo
      FROM
        (SELECT *
        FROM ARTERH.RHPESS_CONTRATO C
        WHERE C.TIPO_CONTRATO= pTIPO_CONTRATO
        AND C.CODIGO_EMPRESA= pCODIGO_EMPRESA
        AND CODIGO= pCODIGO_CONTRATO
        AND C.ANO_MES_REFERENCIA=
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.CODIGO      =C.CODIGO
          AND AUX.TIPO_CONTRATO =C.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA=C.CODIGO_EMPRESA
          )
        )X
      LEFT OUTER JOIN ARTERH.RHPESS_CONTRATO C
      ON C.CODIGO_PESSOA  =X.CODIGO_PESSOA
      AND C.TIPO_CONTRATO =X.TIPO_CONTRATO
      AND C.CODIGO_EMPRESA=X.CODIGO_EMPRESA
      WHERE C.CODIGO     <>X.CODIGO
      /*INICIO--- INCLUIDO EM 01/07/2022 POR LETICIA*/
      AND C.DATA_RESCISAO IS NULL
      AND C.ANO_MES_REFERENCIA=
          (SELECT MAX(AUX.ANO_MES_REFERENCIA)
          FROM ARTERH.RHPESS_CONTRATO AUX
          WHERE AUX.CODIGO      =C.CODIGO
          AND AUX.TIPO_CONTRATO =C.TIPO_CONTRATO
          AND AUX.CODIGO_EMPRESA=C.CODIGO_EMPRESA
          )
      /*FIM--- INCLUIDO EM 01/07/2022 POR LETICIA*/
      )x;
    RETURN v_retorno;
  END;